### ISSUE TITLE
Issue with SPDK mdns discovery Inbox

### ISSUE THREAD

**Issue by AmanAaroh** [spdk/spdk#3483] opened 2024-08-14 06:09 UTC
Hi ,
We have a CDC instance with SPDK and connecting to a target (linux) SSD.
Following are the snapshots
Setup: 
Host <-> CDC <-> Target

Commands on CDC (SPDK) 
![image](https://github.com/user-attachments/assets/2c1a21be-91d2-4fdf-ab1b-0349f08938b6)

According to the SPDK official RPC page, 'bdev_nvme_start_mdns_discovery' command will also attach to the subsystem listed in the discovered log page.
This entry should  be added to the SPDK discovery log page too.
But we do not see the 'connect' (attach) happening from CDC to target SSD.

Also if we send a discover command to this CDC machine from a host we see following :
![image(1)](https://github.com/user-attachments/assets/cf9c57e9-e54d-4e2b-a4d0-722da537ddb7)
Are we missing something?
Please advise.

**Comment by jimharris** [comment] 2024-08-14 14:41
Hi,

> Hi , We have a CDC instance with SPDK and connecting to a target (linux) SSD. Following are the snapshots Setup: Host <-> CDC <-> Target
> 
> Commands on CDC (SPDK) ![image](https://private-user-images.githubusercontent.com/126143892/357694981-2c1a21be-91d2-4fdf-ab1b-0349f08938b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDYyNTUsIm5iZiI6MTcyMzY0NTk1NSwicGF0aCI6Ii8xMjYxNDM4OTIvMzU3Njk0OTgxLTJjMWEyMWJlLTkxZDItNGZkZi1hYjFiLTAzNDlmMDg5MzhiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxNDMyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzJhNzY4NGRkNWUzOGFlNTcwMmJhNDQ0NGQxZThjMWI3NjEzZjczZThmNmVjYThiM2UzMTVjODMwNGFkZThkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nSwyew4WskeBiHAkwloH0yrwclPUP622JiBBeKR-hVk)

Please paste text into the issues instead of images. Otherwise it is impossible to be able to reply inline to specific parts of the logs/output.

What is the target in this case? Has it registered itself with mDNS? Please provide specifics on how the target is configured.

> According to the SPDK official RPC page, 'bdev_nvme_start_mdns_discovery' command will also attach to the subsystem listed in the discovered log page. This entry should be added to the SPDK discovery log page too. But we do not see the 'connect' (attach) happening from CDC to target SSD.

The connect to the target will only happen if the target has registered itself correctly with mDNS, so that the SPDK CDC gets a notification to discover it.

`This entry should be added to the SPDK discovery log page too.` - Please clarify which discovery log page you are referring to.

> 
> Also if we send a discover command to this CDC machine from a host we see following : ![image(1)](https://private-user-images.githubusercontent.com/126143892/357695393-cf9c57e9-e54d-4e2b-a4d0-722da537ddb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDYyNTUsIm5iZiI6MTcyMzY0NTk1NSwicGF0aCI6Ii8xMjYxNDM4OTIvMzU3Njk1MzkzLWNmOWM1N2U5LWU1NGQtNGUyYi1hNGQwLTcyMmRhNTM3ZGRiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxNDMyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTMxYTc4NmIzMGU3NTk0ZDhjODUzZmIxODVmYTZmZDk3N2E2YmFiODNiMjFmYmMxOGNiZThkY2M2YjcwOWYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V-MsPF2HoCcITjNBtzxFoS7V2vsRgR7kiBuHoSKe6mw) Are we missing something? Please advise.

**Comment by prohom** [comment] 2024-08-16 06:51
Hi , We have a CDC instance with SPDK and connecting to a target (linux) SSD. Following are the snapshots
 Setup: 
Host <-> **CDC(SPDK) <-> Target(SSD)**



Commands on CDC (SPDK) image

Please paste text into the issues instead of images. Otherwise it is impossible to be able to reply inline to specific parts of the logs/output.
>>Please refer this output of rpc command on CDC (SPDK)  : 
cdc@pc5:~/spdk$ sudo scripts/rpc.py bdev_nvme_get_mdns_discovery_info
[
  {
    "name": "CDC_auto",
    "svcname": "_nvme-disc._tcp",
    "referrals": [
      {
        "name": "CDC_auto0_nvme",
        "trid": {
          "trtype": "TCP",
          "adrfam": "IPv4",
          "traddr": "**192.168.1.29**",
          "trsvcid": "8009",
          "subnqn": "nqn.2014-08.org.nvmexpress.discovery"
        }
      }
    ]
  }
]_
What is the target in this case? Has it registered itself with mDNS? Please provide specifics on how the target is configured.
>>The target here is a NVMe SSD (192.168.1.29) with linux which has registered with mDNS. As we can see in the discovery_info above it is discovered by the CDC_auto. 

According to the SPDK official RPC page, 'bdev_nvme_start_mdns_discovery' command will also attach to the subsystem listed in the discovered log page. This entry should be added to the SPDK discovery log page too. But we do not see the 'connect' (attach) happening from CDC to target SSD.

The connect to the target will only happen if the target has registered itself correctly with mDNS, so that the SPDK CDC gets a notification to discover it.
>><Again referring to about discovery info command output, this seems to be registered>

This entry should be added to the SPDK discovery log page too. - Please clarify which discovery log page you are referring to.
>> Expected result: The CDC (SPDK) discovery log page should be updated with the new target(:29) found in mdns discovery.
Hope info is clear now.

Also if we send a discover command to this CDC machine from a host we see following : image(1) Are we missing something? Please advise.

**Comment by jimharris** [comment] 2024-08-16 15:26
> > > Please refer this output of rpc command on CDC (SPDK)  :
> > > cdc@pc5:~/spdk$ sudo scripts/rpc.py bdev_nvme_get_mdns_discovery_info
> > > [
> > > {
> > > "name": "CDC_auto",
> > > "svcname": "_nvme-disc._tcp",
> > > "referrals": [
> > > {
> > > "name": "CDC_auto0_nvme",
> > > "trid": {
> > > "trtype": "TCP",
> > > "adrfam": "IPv4",
> > > "traddr": "**192.168.1.29**",
> > > "trsvcid": "8009",
> > > "subnqn": "nqn.2014-08.org.nvmexpress.discovery"
> > > }
> > > }
> > > ]
> > > }
> > > ]_
> > > What is the target in this case? Has it registered itself with mDNS? Please provide specifics on how the target is configured.
> > > The target here is a NVMe SSD (192.168.1.29) with linux which has registered with mDNS. As we can see in the discovery_info above it is discovered by the CDC_auto.

Hi,

What is the log page if you `nvme discover` the 192.168.1.29 system?

Also try enabling `bdev_nvme` log messages, use a debug build and pass `-L bdev_nvme` on SPDK CDC target command line.

Please also note that even when the bdev_nvme attaches to the target system and creates a bdev for that SSD, it is not automatically added to the discovery log page for the CDC's nvmf target. Something would need to create an nvmf subsystem on the CDC and then add that bdev from the Linux SSD target as a namespace.

-Jim

**Comment by prohom** [comment] 2024-08-19 05:29
Hi,

What is the log page if you nvme discover the 192.168.1.29 system?

>>
>>__pc5:~$ sudo nvme discover -t tcp -a 192.168.1.29 -s 8009
[sudo] password for odroid: 
Discovery Log Number of Records 2, Generation counter 2
=====Discovery Log Entry 0======
trtype:  tcp
adrfam:  ipv4
subtype: current discovery subsystem
treq:    not specified, sq flow control disable supported
portid:  1
trsvcid: 8009
subnqn:  nqn.2014-08.org.nvmexpress.discovery
traddr:  192.168.1.29
eflags:  none
sectype: none
=====Discovery Log Entry 1======
trtype:  tcp
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified, sq flow control disable supported
portid:  1
trsvcid: 8009
subnqn:  nvmet-test1
traddr:  192.168.1.29
eflags:  none
sectype: none__


Also try enabling bdev_nvme log messages, use a debug build and pass -L bdev_nvme on SPDK CDC target command line.

>> _Sure will try this and let you know._

_Please also note that even when the bdev_nvme attaches to the target system and creates a bdev for that SSD, it is not automatically added to the discovery log page for the CDC's nvmf target. Something would need to create an nvmf subsystem on the CDC and then add that bdev from the Linux SSD target as a namespace_.

>> __Ok , then maybe I misunderstood this. From the json-rpc commands page , the 'bdev_nvme_start_mdns_discovery' command has following information :
"The discovery service will listen for the mDNS discovery events from the Avahi-daemon and will connect to the newly learnt discovery controllers. Then the discovery service will automatically attach to any subsystem found in the discovery log page from the discovery controllers learnt using mDNS."
So here I assumed that the target subsytem information is taken from target discovery log page and saved in to the host(CDC here) discovery log page.  If this interpretation is wrong then can I  add a referral  to CDC using this information of target then?
PS: I also do not see any connect(attach) commands going out from CDC to target on wireshark._
I really appreciate your feedback . Thanks!

**Comment by prohom** [comment] 2024-08-22 06:26
Also try enabling bdev_nvme log messages, use a debug build and pass -L bdev_nvme on SPDK CDC target command line.
>>
### @pc5:~/spdk$ sudo build/bin/nvmf_tgt  -L bdev_nvme 0x20 &
>>
_@pc5:~/spdk$ [2024-08-21 06:45:32.538842] Starting SPDK v24.05-pre git sha1 56317f627 / DPDK 23.11.0 initialization...
[2024-08-21 06:45:32.539241] [ DPDK EAL parameters: nvmf --no-shconf -c 0x1 --huge-unlink --no-telemetry --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid451817 ]
[2024-08-21 06:45:32.572050] app.c: 828:spdk_app_start: NOTICE: Total cores available: 1
[2024-08-21 06:45:32.737812] reactor.c: 937:reactor_run: NOTICE: Reactor started on core 0
[2024-08-21 06:46:39.856940] bdev_mdns_client.c: 369:mdns_browse_handler: DEBUG: (Browser) NEW: service 'pc1' of type '_nvme-disc._tcp' in domain 'local'
[2024-08-21 06:46:39.956951] bdev_mdns_client.c: 369:mdns_browse_handler: DEBUG: (Browser) NEW: service 'pc1' of type '_nvme-disc._tcp' in domain 'local'
[2024-08-21 06:46:40.056957] bdev_mdns_client.c: 395:mdns_browse_handler: INFO: (Browser) CACHE_EXHAUSTED
[2024-08-21 06:46:40.156965] bdev_mdns_client.c: 395:mdns_browse_handler: INFO: (Browser) ALL_FOR_NOW
[2024-08-21 06:46:40.357035] bdev_mdns_client.c: 254:mdns_resolve_handler: INFO: Service 'pc1' of type '_nvme-disc._tcp' in domain 'local'
[2024-08-21 06:46:40.357130] bdev_mdns_client.c: 259:mdns_resolve_handler: INFO:     pc1.local:8009 (fe80::21e:6ff:fe51:bbc)
    TXT="A=192.168.1.29" "NQN=nqn.2014-08.org.nvmexpress.discovery" "P=tcp"
    cookie is 0
    is_local: 0
    our_own: 0
    wide_area: 0
    multicast: 1
    cached: 1
[2024-08-21 06:46:40.357192] bdev_mdns_client.c: 292:mdns_resolve_handler: INFO: trid family is not IPV4 2
[2024-08-21 06:46:40.457034] bdev_mdns_client.c: 254:mdns_resolve_handler: INFO: Service 'pc1' of type '_nvme-disc._tcp' in domain 'local'
[2024-08-21 06:46:40.457129] bdev_mdns_client.c: 259:mdns_resolve_handler: INFO:     pc1.local:8009 (192.168.1.29)
    TXT="A=192.168.1.29" "NQN=nqn.2014-08.org.nvmexpress.discovery" "P=tcp"
    cookie is 0
    is_local: 0
    our_own: 0
    wide_area: 0
    multicast: 1
    cached: 1
[2024-08-21 06:46:41.467123] bdev_nvme.c:6923:discovery_attach_cb: INFO: Discovery[[192.168.1.29:8009](http://192.168.1.29:8009/)] discovery ctrlr attached
[2024-08-21 06:46:41.467222] bdev_nvme.c:7003:discovery_poller: INFO: Discovery[[192.168.1.29:8009](http://192.168.1.29:8009/)] discovery ctrlr connected
[2024-08-21 06:46:41.467276] bdev_nvme.c:6886:get_discovery_log_page: INFO: Discovery[[192.168.1.29:8009](http://192.168.1.29:8009/)] sent discovery log page command
[2024-08-21 06:46:41.473163] bdev_nvme.c:6852:discovery_log_page_cb: INFO: Discovery[[192.168.1.29:8009](http://192.168.1.29:8009/)] NVM nvmet-test1:[192.168.1.29:8009](http://192.168.1.29:8009/) new subsystem CDC_auto0_nvme0
[2024-08-21 06:46:41.555765] bdev_nvme.c:7713:bdev_nvme_readv: DEBUG: read 64 blocks with offset 0
[2024-08-21 06:46:41.555932] bdev_nvme.c:7713:bdev_nvme_readv: DEBUG: read 1 blocks with offset 0
[2024-08-21 06:46:41.556195] bdev_nvme.c:7713:bdev_nvme_readv: DEBUG: read 8 blocks with offset 0
[2024-08-21 06:46:41.556266] bdev_nvme.c:6742:discovery_attach_controller_done: INFO: Discovery[[192.168.1.29:8009](http://192.168.1.29:8009/)] attach CDC_auto0_nvme0 done
[2024-08-21 06:46:41.556302] bdev_nvme.c:6701:discovery_remove_controllers: INFO: Discovery[[192.168.1.29:8009](http://192.168.1.29:8009/)] NVM nvmet-test1:[192.168.1.29:8009](http://192.168.1.29:8009/) found again
[2024-08-21 06:46:41.590470] bdev_nvme.c:1606:bdev_nvme_disconnected_qpair_cb: DEBUG: qpair 0xaaaae81b0320 was disconnected and freed. delete nvme_qpair.__

**Comment by jimharris** [comment] 2024-08-22 20:54
OK, to me it looks like it did attach to the discovered subsystem. We even see read commands going to a namespace that was apparently discovered when attaching to the discovered subsystem (bdev_nvme.c:7713 lines).

This seems to all be working as intended.  You should see a bdev now for whatever namespace is attached to that newly discovered subsystem.

**Comment by prohom** [comment] 2024-08-28 09:07
Hi Jim , 
Thanks for the confirmation. But now if I run command 
>sudo nvme list

Node                  Generic               SN                   Model                                    Namespace  Usage                      Format           FW Rev  
--------------------- --------------------- -------------------- ---------------------------------------- ---------- -------------------------- ---------------- --------
/dev/nvme0n1          /dev/ng0n1            2M392L12AJNC         XPG GAMMIX S5                            0x1        256.06  GB / 256.06  GB    512   B +  0 B   VC0S036H
 I do not see the namespace added.
Also if I run the command 
@pc5:~/spdk$ sudo scripts/rpc.py nvmf_get_subsystems
[
  {
    "nqn": "nqn.2014-08.org.nvmexpress.discovery",
    "subtype": "Discovery",
    "listen_addresses": [
      {
        "trtype": "TCP",
        "adrfam": "IPv4",
        "traddr": "192.168.1.30",
        "trsvcid": "4420"
      }
    ],
    "allow_any_host": true,
    "hosts": []
  },
  {
    "nqn": "nqn.2016-06.io.spdk:cnode1",
    "subtype": "NVMe",
    "listen_addresses": [
      {
        "trtype": "TCP",
        "adrfam": "IPv4",
        "traddr": "192.168.1.30",
        "trsvcid": "4420"
      }
    ],
    "allow_any_host": true,
    "hosts": [],
    "serial_number": "SPDK00000000000001",
    "model_number": "SPDK_CDC",
    "max_namespaces": 32,
    "min_cntlid": 1,
    "max_cntlid": 65519,
    "namespaces": [
      {
        "nsid": 1,
        "bdev_name": "Malloc0",
        "name": "Malloc0",
        "nguid": "1F7AD6F5FCF3464098B3DF037F17FCA7",
        "uuid": "1f7ad6f5-fcf3-4640-98b3-df037f17fca7"
      }
    ]
  }
]

I see here only the subsystems of this same CDC machine(:30) and not the subsystem that is discovered in mdns (192.168.1.29).
Does it mean it is not actually attached and the discovery log page not updated? 

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
_For reference copying output of **nvme-cli discover and connect** to 192.168.1.29 here ->_

sudo nvme discover -t tcp -a 192.168.1.29 -s 8009

Discovery Log Number of Records 2, Generation counter 2
=====Discovery Log Entry 0======
trtype:  tcp
adrfam:  ipv4
subtype: current discovery subsystem
treq:    not specified, sq flow control disable supported
portid:  1
trsvcid: 8009
subnqn:  nqn.2014-08.org.nvmexpress.discovery
traddr:  192.168.1.29
eflags:  none
sectype: none
=====Discovery Log Entry 1======
trtype:  tcp
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified, sq flow control disable supported
portid:  1
trsvcid: 8009
subnqn:  nvmet-test1
traddr:  192.168.1.29
eflags:  none
sectype: none

sudo nvme connect -t tcp -a 192.168.1.29 -n nvmet-test1 -s 8009
connecting to device: nvme1
@pc5:~/spdk$ sudo nvme list
Node                  Generic               SN                   Model                                    Namespace  Usage                      Format           FW Rev  
--------------------- --------------------- -------------------- ---------------------------------------- ---------- -------------------------- ---------------- --------
/dev/nvme0n1          /dev/ng0n1            2M392L12AJNC         XPG GAMMIX S5                            0x1        256.06  GB / 256.06  GB    512   B +  0 B   VC0S036H
**/dev/nvme1n1          /dev/ng1n1            110b43437c92a881a65e Linux                                    0x1        256.06  GB / 256.06  GB    512   B +  0 B   6.1.0-od**

**Comment by jimharris** [comment] 2024-08-28 15:25
> 
> I see here only the subsystems of this same CDC machine(:30) and not the subsystem that is discovered in mdns (192.168.1.29). Does it mean it is not actually attached and the discovery log page not updated?

Hi,

I will refer you to part of my earlier response on this issue:

>Please also note that even when the bdev_nvme attaches to the target system and creates a bdev for that SSD, it is not automatically added to the discovery log page for the CDC's nvmf target. Something would need to create an nvmf subsystem on the CDC and then add that bdev from the Linux SSD target as a namespace.

You have NVMe-oF target A (192.168.1.29) exposing 'nvmet-test1' subsystem.
You have NVMe-oF target B (192.168.1.30) that has connected to target A and discovered the 'nvmet-test1' subsystem.
Target B will not automatically expose the 'nvmet-test1' subsystem itself. You need to either:

* create an nvmf subsystem on target B and add the nvmet-test1 namespaces to it
* add a referral to target B that points to target A

SPDK is working as intended here, so I'm closing this issue.

-Jim

**Closed by jimharris** 2024-08-28 15:25 UTC
Labels: Sighting

**Comment by prohom** [comment] 2024-08-29 05:57
Okay understood. 
We have gone ahead with option B but were hoping spdk did it on its own.
It is clear now.
Thanks for the support Jim!

Regards,
Prajakta
