### ISSUE TITLE
vhost nightly tests fail due to vtophys translation

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1135] opened 2020-01-08 12:17 UTC
Vhost nightly tests fail on step "nightly_vhost_integrity_blk". This started between commits 80da9548 and 801e76d8. Most likely candidate that introduced it is dd7cd80c.

All of the following logs occurred on fedora_phy_nightly_1.
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-nightly_1339.html
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-nightly_1340.html
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-nightly_1341.html
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-nightly_1342.html
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-nightly_1344.html
Have only seen passes on fedora_phy_nightly_2.

Both machines have iommu enabled. Although checking logs the failing fedora_phy_nightly_1 selects PA mode, and passing fedora_phy_nightly_2 machines selects VA.

@benlwalker Do you mind taking a look ?

**Comment by ChenBo2333** [comment] 2020-01-15 01:57
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/1393/archive/vhost_autotest_nightly/build.log
This issue occured recently.

**Comment by Seth5141** [comment] 2020-01-24 22:48
Hi @tomzawadzki @benlwalker I will start with the good news. I have a proposed change that I have verified fixes this issue on master: https://review.gerrithub.io/c/spdk/spdk/+/482714

Now I will get into some of the details around this issue which kind of, but don't really, make sense to me.

DPDK allows you to work with the iommu in either pa or va mode which is what Ben's patch was trying to address. We used to always just set the physical address equal to the virtual address before setting the vfio iommu mappings with ioctl(g_vfio.fd, VFIO_IOMMU_MAP_DMA, &dma_map->map);.

However, after Ben's patch, we started actually using physical addresses when making that call. Which is all fine and dandy, but we run into a problem as soon as we attempt to register multiple devices.

I found a very simple reproduction case for this job. You essentially just have to modify the dpdk command line parameters to specify iova-mode=pa and then run

~~~
./spdk/test/vhost/fiotest/fio.sh -x --fio-bin=$FIO_BIN \
	--vm=0,$VM_IMAGE,Nvme0n1p0:RaidBdev0:RaidBdev1:RaidBdev2 \
	--test-type=spdk_vhost_blk \
	--fio-job=./spdk/test/vhost/common/fio_jobs/default_integrity.job
~~~

or really with any number of block devices greater than 1. What ends up happening is each of these devices maps 1G of memory into our host processes virtual address space. Virtually speaking, these address spaces are mutually exclusive, but when you translate the host virtual addresses to host physical addresses, you get collisions. I didn't realize that was possible, but it looks like the vm uses the same buffers for data transfer between the guest and host for all of the devices exposed by vhost. This can be seen from the output here:

~~~
rte_vhost_compat.c:  80:vhost_session_mem_register: *WARNING*: Failed to register memory region 0. Future vtophys translation might fail.
vhost.c:1008:vhost_stop_device_cb: *NOTICE*: In stop device cb for vid 2.
nvme_pcie.c:1761:nvme_pcie_prp_list_append: *ERROR*: vtophys(0x7fa4ad7f3000) failed
~~~

As you can see, the memory we failed to register for the second device corresponds to a bdev_io buffer. So what I believe is going on is that we just didn't realize before that those physical addresses are shared.

My change essentially just prevents us from failing to put these virtual to physical mappings in our memory map just because we already had an entry for that physical address in the vfio_iommu. With my current knowledge, I think that's OK. But I would really like your guys insight/expertise on this subject so I don't screw something up. 
But here is an intel internal link of the nightly vhost test passing with this my change:
https://10.102.17.104:8080/job/Vhost_tests/job/vhost_autotest_nightly/5862/

**Comment by peluse** [comment] 2020-01-28 15:11
bug scrub: wip understood

**Comment by darsto** [comment] 2020-01-30 15:40
Fix merged: https://review.gerrithub.io/c/spdk/spdk/+/483133
Thanks Seth!

**Closed by darsto** 2020-01-30 15:40 UTC
Labels: Medium, bug
