### ISSUE TITLE
[nvmf_perf_adq] num_busy_count error() on E810 ADQ

### ISSUE THREAD

**Issue by tae-kyung-kim** [spdk/spdk#2605] opened 2022-07-25 05:21 UTC
## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_81093.html
https://ci.spdk.io/results/autotest-per-patch/builds/81093/archive/nvmf-tcp-phy-autotest/build.log

## Execution failed at

```
00:11:51.582   05:29:42	-- target/perf_adq.sh@156 -- # /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/build/examples/perf -q 64 -o 4096 -w randread -t 15 -P 4 -c 0x70 -r 'trtype:tcp adrfam:IPv4 traddr:10.0.0.2 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode1'
00:11:51.582   05:29:42	-- target/perf_adq.sh@160 -- # sleep 3
00:11:51.582  EAL: No free 2048 kB hugepages reported on node 1
00:11:51.582  TELEMETRY: No legacy callbacks, legacy socket not created
00:11:54.871   05:29:45	-- target/perf_adq.sh@161 -- # check_ints_result
00:11:54.871   05:29:45	-- target/perf_adq.sh@111 -- # (( i = 1 ))
00:11:54.871   05:29:45	-- target/perf_adq.sh@111 -- # (( i <= 3 ))
00:11:54.871   05:29:45	-- target/perf_adq.sh@112 -- # compare_ints 2 eth8
00:11:54.871   05:29:45	-- target/perf_adq.sh@86 -- # grep eth8
00:11:54.871   05:29:45	-- target/perf_adq.sh@92 -- # awk '{
00:11:54.871  		for (i = 1; i <= NF; i++) {
00:11:54.871  				val[i]=$i;
00:11:54.871  				if (i>1)
00:11:54.871  					printf "%d\n", $i;
00:11:54.871  		}
00:11:54.871  	}'
00:11:54.871   05:29:45	-- target/perf_adq.sh@93 -- # sleep 2
00:11:56.778   05:29:47	-- target/perf_adq.sh@94 -- # grep eth8
00:11:56.778   05:29:47	-- target/perf_adq.sh@100 -- # awk '{
00:11:56.778  		for (i = 1; i <= NF; i++) {
00:11:56.778  				val[i]=$i;
00:11:56.778  				if (i>1)
00:11:56.778  					printf "%d\n", $i;
00:11:56.778  		}
00:11:56.778  	}'
00:11:56.778   05:29:47	-- target/perf_adq.sh@102 -- # diff temp_ints1.log temp_ints2.log
00:11:56.778   05:29:47	-- target/perf_adq.sh@103 -- # return 0
00:11:56.778   05:29:47	-- target/perf_adq.sh@113 -- # return 0
00:11:56.778    05:29:47	-- target/perf_adq.sh@165 -- # num_busy_count
00:11:56.778    05:29:47	-- target/perf_adq.sh@72 -- # get_pollers_busy_count0=($(get_nvmf_poll_groups))
00:11:56.778     05:29:47	-- target/perf_adq.sh@72 -- # get_nvmf_poll_groups
00:11:56.778     05:29:47	-- target/perf_adq.sh@67 -- # /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py thread_get_pollers
00:11:56.778     05:29:47	-- target/perf_adq.sh@67 -- # jq -r '.threads[] | .active_pollers[] |
00:11:56.778  	select(.name == "nvmf_poll_group_poll").busy_count'
00:11:56.778    05:29:47	-- target/perf_adq.sh@73 -- # sleep 2
00:11:59.312    05:29:49	-- target/perf_adq.sh@74 -- # get_pollers_busy_count1=($(get_nvmf_poll_groups))
00:11:59.312     05:29:49	-- target/perf_adq.sh@74 -- # get_nvmf_poll_groups
00:11:59.312     05:29:49	-- target/perf_adq.sh@67 -- # /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py thread_get_pollers
00:11:59.312     05:29:49	-- target/perf_adq.sh@67 -- # jq -r '.threads[] | .active_pollers[] |
00:11:59.312  	select(.name == "nvmf_poll_group_poll").busy_count'
00:11:59.312    05:29:50	-- target/perf_adq.sh@75 -- # local num=0
00:11:59.312    05:29:50	-- target/perf_adq.sh@76 -- # for i in "${!get_pollers_busy_count0[@]}"
00:11:59.312    05:29:50	-- target/perf_adq.sh@77 -- # increment=8151
00:11:59.312    05:29:50	-- target/perf_adq.sh@78 -- # (( increment > 0 ))
00:11:59.312    05:29:50	-- target/perf_adq.sh@79 -- # (( ++num ))
00:11:59.312    05:29:50	-- target/perf_adq.sh@76 -- # for i in "${!get_pollers_busy_count0[@]}"
00:11:59.312    05:29:50	-- target/perf_adq.sh@77 -- # increment=0
00:11:59.312    05:29:50	-- target/perf_adq.sh@78 -- # (( increment > 0 ))
00:11:59.312    05:29:50	-- target/perf_adq.sh@76 -- # for i in "${!get_pollers_busy_count0[@]}"
00:11:59.312    05:29:50	-- target/perf_adq.sh@77 -- # increment=0
00:11:59.312    05:29:50	-- target/perf_adq.sh@78 -- # (( increment > 0 ))
00:11:59.312    05:29:50	-- target/perf_adq.sh@76 -- # for i in "${!get_pollers_busy_count0[@]}"
00:11:59.312    05:29:50	-- target/perf_adq.sh@77 -- # increment=0
00:11:59.312    05:29:50	-- target/perf_adq.sh@78 -- # (( increment > 0 ))
00:11:59.312    05:29:50	-- target/perf_adq.sh@82 -- # echo 1
00:11:59.312   05:29:50	-- target/perf_adq.sh@165 -- # [[ 1 -ne 2 ]]
00:11:59.312   05:29:50	-- target/perf_adq.sh@166 -- # echo 'ERROR: num_busy_count != tc1 queues of traffic classes! Testcase 2 failed.'
00:11:59.312  ERROR: num_busy_count != tc1 queues of traffic classes! Testcase 2 failed.
00:11:59.312   05:29:50	-- target/perf_adq.sh@167 -- # exit 1
```

The same issue was reported in #2577.
https://review.spdk.io/gerrit/c/spdk/spdk/+/13684

**Comment by spdkci** [comment] 2022-07-25 05:23
Another instance of this failure. Reported by @tae-kyung-kim. log: https://ci.spdk.io/public_build/autotest-per-patch_81093.html

**Comment by Comphix** [comment] 2022-07-25 05:29
Duplicate of #2577 and close this one.

**Closed by Comphix** 2022-07-25 05:29 UTC
Labels: Intermittent Failure
