### ISSUE TITLE
[OCF performance] - ring error due to the qd=128 bdevperf or fio testing on OCF device

### ISSUE THREAD

**Issue by gaowayne** [spdk/spdk#1875] opened 2021-04-06 07:40 UTC
## Expected Behavior
need fix this error and performance goes back

## Current Behavior
during testing OCF performance 
```
[2021-04-01 09:23:45.308325] thread.c: 928:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
[2021-04-01 09:23:45.308332] thread.c: 928:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
[2021-04-01 09:23:45.308425] thread.c: 928:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
[2021-04-01 09:23:45.308426] thread.c: 928:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
[2021-04-01 09:23:45.308440] thread.c: 928:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
[2021-04-01 09:23:45.308446] thread.c: 928:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
[2021-04-01 09:23:45.308461] thread.c: 928:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
[2021-04-01 09:23:45.308466] thread.c: 928:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
[2021-04-01 09:23:45.308549] thread.c: 928:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
[2021-04-01 09:23:45.308563] thread.c: 928:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
[2021-04-01 09:23:45.308565] thread.c: 928:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
[2021-04-01 09:23:45.308576] thread.c: 928:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
[2021-04-01 09:23:45.308577] thread.c: 928:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
[2021-04-01 09:23:45.308600] thread.c: 928:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
[2021-04-01 09:23:45.308602] thread.c: 928:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
[2021-04-01 09:23:45.308612] thread.c: 928:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
[2021-04-01 09:23:45.308617] thread.c: 928:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
[2021-04-01 09:23:45.308627] thread.c: 928:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
^Cbs: 2 (f=2), 0B/s-0B/s: [_(1),w(1),_(2),w(1),_(1)][0.3%][eta 143d:01h:20m:46s]                  
fio: terminating on signal 2
````
performance is very poor
Device                  tps       MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn  MB_dscd  aqu-sz  wareq-sz  rareq-sz  w_await(us)  r_await(us)  util
Nvme3n1(no sampling)    0.00      0.00       0.00       0.00       0.00     0.00     0.00     0       0         0         0            0            0   
Cache1(no sampling)     2666.60   0.00       41.67      0.00       0.00     208.75   0.00     0       0         0         0            0            0   
Cache2(no sampling)     2666.60   0.00       41.67      0.00       0.00     208.75   0.00     0       0         0         0            0            0   
Cache3(no sampling)     2666.60   0.00       41.67      0.00       0.00     208.75   0.00     0       0         0         0            0            0   
Cache4(no sampling)     2666.80   0.00       41.67      0.00       0.00     208.77   0.00     0       0         0         0            0            0   
Cache5(no sampling)     2666.80   0.00       41.67      0.00       0.00     208.77   0.00     0       0         0         0            0            0   
Cache6(no sampling)     2666.60   0.00       41.67      0.00       0.00     208.75   0.00     0       0         0         0            0            0   
Nvme0n1(no sampling)    14402.03  0.00       150.01     0.00       0.00     751.55   0.00     0       0         0         0            0            0   
Nvme0n1p0(no sampling)  4800.68   0.00       50.00      0.00       0.00     250.52   0.00     0       0         0         0            0            0   
Nvme0n1p1(no sampling)  4800.68   0.00       50.00      0.00       0.00     250.52   0.00     0       0         0         0            0            0   
Nvme0n1p2(no sampling)  4800.68   0.00       50.00      0.00       0.00     250.52   0.00     0       0         0         0            0            0   
Nvme1n1(no sampling)    0.00      0.00       0.00       0.00       0.00     0.00     0.00     0       0         0         0            0            0   
Nvme1n1p0(no sampling)  0.00      0.00       0.00       0.00       0.00     0.00     0.00     0       0         0         0            0            0   
Nvme1n1p1(no sampling)  0.00      0.00       0.00       0.00       0.00     0.00     0.00     0       0         0         0            0            0   
Nvme1n1p2(no sampling)  0.00      0.00       0.00       0.00       0.00     0.00     0.00     0       0         0         0            0            0   
Nvme1n1p3(no sampling)  0.00      0.00       0.00       0.00       0.00     0.00     0.00     0       0         0         0            0            0   
Nvme1n1p4(no sampling)  0.00      0.00       0.00       0.00       0.00     0.00     0.00     0       0         0         0            0            0   
Nvme1n1p5(no sampling)  0.00      0.00       0.00       0.00       0.00     0.00     0.00     0       0         0         0            0            0   
Nvme2n1(no sampling)    14402.23  0.00       150.01     0.00       0.00     751.55   0.00     0       0         0         0            0            0   
Nvme2n1p0(no sampling)  4800.68   0.00       50.00      0.00       0.00     250.52   0.00     0       0         0         0            0            0   
Nvme2n1p1(no sampling)  4800.68   0.00       50.00      0.00       0.00     250.52   0.00     0       0         0         0            0            0   
Nvme2n1p2(no sampling)  4800.88   0.00       50.00      0.00       0.00     250.52   0.00     0       0         0         0            0            0   
===error call stack===
>             __rte_ring_move_prod_head(uint32_t * free_entries, uint32_t * new_head, uint32_t * old_head, enum rte_ring_queue_behavior behavior, unsigned int n, unsigned int is_sp, struct rte_ring * r) Line 90               C++
              __rte_ring_do_enqueue_elem(unsigned int * free_space, unsigned int is_sp, enum rte_ring_queue_behavior behavior, unsigned int n, unsigned int esize, const void * obj_table, struct rte_ring * r) Line 419    C++
              rte_ring_mp_enqueue_bulk_elem(unsigned int * free_space, unsigned int n, unsigned int esize, const void * obj_table, struct rte_ring * r) Line 507     C++
              rte_ring_enqueue_bulk_elem(unsigned int * free_space, unsigned int n, unsigned int esize, const void * obj_table, struct rte_ring * r) Line 574        C++
              rte_ring_enqueue_bulk(unsigned int * free_space, unsigned int n, void * const * obj_table, struct rte_ring * r) Line 266    C++
              spdk_ring_enqueue(struct spdk_ring * ring, void ** objs, size_t count, size_t * free_space) Line 428       C
              spdk_thread_send_msg(const struct spdk_thread * thread, spdk_msg_fn fn, void * ctx) Line 926       C
              vbdev_ocf_volume_updater_kick(ocf_metadata_updater_t mu) Line 475              C
              ctx_metadata_updater_kick(ocf_ctx_t ctx, ocf_metadata_updater_t mu) Line 168               C++
              ocf_metadata_updater_kick(ocf_cache_t cache) Line 29 C
              metadata_io_io_end(struct metadata_io_request * m_req, int error) Line 275     C
              metadata_io_io_cmpl(struct ocf_io * io, int error) Line 205           C
              vbdev_ocf_volume_submit_io_cb(struct spdk_bdev_io * bdev_io, _Bool success, void * opaque) Line 199 C
              bdev_io_complete(void * ctx) Line 5139 C
              spdk_bdev_io_complete(struct spdk_bdev_io * bdev_io, enum spdk_bdev_io_status status) Line 5227              C
              bdev_part_complete_io(struct spdk_bdev_io * bdev_io, _Bool success, void * cb_arg) Line 293               C
              bdev_io_complete(void * ctx) Line 5139 C
              spdk_bdev_io_complete(struct spdk_bdev_io * bdev_io, enum spdk_bdev_io_status status) Line 5227              C
              spdk_bdev_io_complete_nvme_status(struct spdk_bdev_io * bdev_io, uint32_t cdw0, int sct, int sc) Line 5322    C
              bdev_nvme_writev_done(void * ref, const struct spdk_nvme_cpl * cpl) Line 2320               C
              nvme_complete_request(spdk_nvme_cmd_cb cb_fn, void * cb_arg, struct spdk_nvme_qpair * qpair, struct nvme_request * req, struct spdk_nvme_cpl * cpl) Line 1158               C++
              nvme_pcie_qpair_complete_tracker(struct spdk_nvme_qpair * qpair, struct nvme_tracker * tr, struct spdk_nvme_cpl * cpl, _Bool print_on_error) Line 637    C
              nvme_pcie_qpair_process_completions(struct spdk_nvme_qpair * qpair, uint32_t max_completions) Line 828         C
              nvme_transport_qpair_process_completions(struct spdk_nvme_qpair * qpair, uint32_t max_completions) Line 403       C
              spdk_nvme_qpair_process_completions(struct spdk_nvme_qpair * qpair, uint32_t max_completions) Line 715         C
              nvme_pcie_poll_group_process_completions(struct spdk_nvme_transport_poll_group * tgroup, uint32_t completions_per_qpair, spdk_nvme_disconnected_qpair_cb disconnected_qpair_cb) Line 1051   C
              nvme_transport_poll_group_process_completions(struct spdk_nvme_transport_poll_group * tgroup, uint32_t completions_per_qpair, spdk_nvme_disconnected_qpair_cb disconnected_qpair_cb) Line 499     C
              spdk_nvme_poll_group_process_completions(struct spdk_nvme_poll_group * group, uint32_t completions_per_qpair, spdk_nvme_disconnected_qpair_cb disconnected_qpair_cb) Line 127              C
              bdev_nvme_poll(void * arg) Line 259      C
              thread_poll(struct spdk_thread * thread, uint32_t max_msgs, uint64_t now) Line 652        C
              spdk_thread_poll(struct spdk_thread * thread, uint32_t max_msgs, uint64_t now) Line 740               C
              _reactor_run(struct spdk_reactor * reactor) Line 885       C
              reactor_run(void * arg) Line 930               C
              spdk_reactors_start() Line 1050 C
              spdk_app_start(struct spdk_app_opts * opts_user, spdk_msg_fn start_fn, void * arg1) Line 580    C
              main(int argc, char ** argv) Line 2127     C

       thread->messages = spdk_ring_create(SPDK_RING_TYPE_MP_SC, 65536, SPDK_ENV_SOCKET_ID_ANY);
       if (!thread->messages) {
             SPDK_ERRLOG("Unable to allocate memory for message ring\n");
             free(thread);
             return NULL;
       }

==

## Steps to Reproduce

1. run benchmark testing just with qd=128, more jobs
2.
3.
4.

**Comment by rafalste** [comment] 2021-04-07 12:06
Hi @gaowayne @jimharris,
it looks like we do not remove all messages from the queue after each metadata updater request, so after a while free entries in the ring drops to 0, resulting with no more messages being sent.
I'm looking for a way to efficiently clear the queue after each request (probably at the metadata updater side after receiving a message), so if any of you guys have some suggestions I'll appreciate if you share any thoughts.

**Comment by rafalste** [comment] 2021-04-07 12:12
@jimharris maybe there is an already implemented quick way to accomplish this task and I'm missing something?

**Comment by jimharris** [comment] 2021-04-07 15:21
Calling spdk_thread_poll() from within your module is not supported.  I think instead you need something a bit more efficient to kick the md_thread.

There is a non-zero cost every time you do an spdk_thread_send_msg.  It looks like the I/O threads are sending a flood of so many kick messages that the md_thread cannot process all of them quickly enough.

Can you instead create your own spdk_ring?  It could be multi-producer so that it is shared by all of the I/O threads, or single-producer and allocate a separate one for each I/O thread?  Then the md_thread can consume entries from those rings.  You just need a poller on the md_thread that will check for entries in those rings that need to be processed.

**Comment by rafalste** [comment] 2021-04-08 12:45
@jimharris thank you for the feedback!
I used `spdk_thread_poll()` in the function that is called on thread (i.e. in the function which is passed to `spdk_thread_send_msg()` along with the context) and it actually work - queue isn't stuck anymore. In SPDK's documentation I've seen the statement that `spdk_thread_poll()` should be called frequently, so I assumed that will be a good idea... Now I suppose although it may fix one issue, other issues will be caused by this approach, right?

So about your suggestion to create separate spdk_ring - is there any working example that I can build on? Is any other bdev doing such thing? This seems pretty complicated at first sight, so it will be great to have some examples.

On the other hand there is a work in progress in OCF to get rid of metadata updater thread completely and handle updates differently, so probably the message passing won't be an issue anymore, but it will be nice to have a fix for the existing method as well.

**Comment by jimharris** [comment] 2021-04-08 16:03
Calling spdk_thread_poll() like this would cause other issues.  It can cause messages to get executed out of order for example.  When spdk_thread_poll() runs, it reads SPDK_MSG_BATCH_SIZE (8) messages from the message queue into a local array, and then executes them one by one.  But then if in the context of one of those messages, you call spdk_thread_poll() again, it will read the next SPDK_MSG_BATCH_SIZE messages and start executing them.  So ones from this second batch could get executed before ones from the first batch.  For your specific metadata thread kick use case, that doesn't matter, but it would cause subtle breakage when you mix in other types of message being sent between threads.

The best example I can think of is the ctrlq_ring in the virtio-scsi driver.  See module/bdev/virtio/bdev_virtio_scsi.c.  If you just look at where "ctrlq_ring" gets used, you'll see how the ring is created, how requests are enqueued/dequeued, and the bdev_virtio_mgmt_poll() function that polls the ring.

**Comment by rafalste** [comment] 2021-04-13 11:34
Hi @jimharris,
we've discussed this issue among the CAS team and came up with a different approach. Instead of creating a separate ring to handle all the messages, we've limited the number of metadata updater kicks by checking if the metadata updater is already running and processing messages from the queue. This also slightly improves performance as there is much less updater calls.
If you have time, please review the patch here:
https://review.spdk.io/gerrit/c/spdk/spdk/+/7346
and share any thoughts or suggestions.

Thank you very much for your help on this subject! :)

**Comment by jimharris** [comment] 2021-04-14 14:54
I think this patch will work, and would fix this bug.  But I'm concerned with adding this atomic operation.  You said this slightly improves performance - how many cores did you run in that performance test?  I think with more cores you're going to start seeing a lot of contention with this atomic operation.

I think you really need to use per-thread contexts to do this correctly.  These "ocf_metadata_updater_t" objects - this is just a single updater object used by all threads?  You really want to have per-thread private rings, or even just a couple of boolean states, something like:

`
  if (!qctx->update_in_progress) {
    qctx->update_in_progress = true;
    qctx->mu = mu;
    spdk_thread_send_msg(md_thread, vbdev_ocf_md_kick, qctx);
  } else {
    qctx->needs_update = true;
  }
`

Then when vbdev_ocf_md_kick executes, it sends a message back to qctx->thread.  That message function would do something like:

`
  if (qctx->needs_update) {
    qctx->needs_update = false;
    spdk_thread_send_msg(md_thread, vbdev_ocf_md_kick, qctx);
  } else {
    qctx->update_in_progress = false;
  }
`

**Comment by rafalste** [comment] 2021-11-05 12:52
Metadata updater was removed in OCF 21.6 which is a part of latest SPDK 21.10 release, so this problem should no longer exist.
I suggest to close this issue. @gaowayne, can you confirm that it works for you?

**Comment by tomzawadzki** [comment] 2021-11-30 11:20
Since update to OCF 21.6 the troublesome code path of metadata updater has been removed.

@gaowayne Please feel free to re-open this issue if you observe the original issue.

**Closed by tomzawadzki** 2021-11-30 11:20 UTC
Labels: 3rd party issue, Waiting on Submitter
