### ISSUE TITLE
[nvmf-phy-autotest] Failed to init the trace resource

### ISSUE THREAD

**Issue by krish-reddy** [spdk/spdk#2041] opened 2021-07-14 11:36 UTC
00:03:18.533  ************************************
00:03:18.533  START TEST nvmf_filesystem_no_incapsule
00:03:18.533  ************************************

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/52910/archive/nvmf-phy-autotest/build.log

## Execution failed at

00:03:18.533  ************************************
00:03:18.533  START TEST nvmf_filesystem_no_incapsule
00:03:18.533  ************************************
00:03:18.533   12:59:48	# xtrace_enable
00:03:18.534   12:59:48	# nvmf_filesystem_part 0
00:03:18.534   12:59:48	# incapsule=0
00:03:18.534   12:59:48	# nvmfappstart -m 0xF
00:03:18.534   12:59:48	# timing_enter start_nvmf_tgt
00:03:18.535   12:59:48	# xtrace_disable
00:03:18.535   12:59:48	# '[' no '!=' yes ']'
00:03:18.535   12:59:48	# PREV_BASH_OPTS=ehxBET
00:03:18.536   12:59:48	# [[ ehxBET == *\x* ]]
00:03:18.536   12:59:48	# XTRACE_DISABLED=yes
00:03:18.536   12:59:48	# set +x
00:03:18.536   12:59:48	# xtrace_enable
00:03:18.537   12:59:48	# nvmfpid=61096
00:03:18.537   12:59:48	# waitforlisten 61096
00:03:18.537   12:59:48	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/build/bin/nvmf_tgt -i 0 -e 0xFFFF -m 0xF
00:03:18.537   12:59:48	# '[' -z 61096 ']'
00:03:18.537   12:59:48	# local rpc_addr=/var/tmp/spdk.sock
00:03:18.538   12:59:48	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
00:03:18.538  Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
00:03:18.538   12:59:48	# xtrace_disable
00:03:18.538   12:59:48	# '[' no '!=' yes ']'
00:03:18.539   12:59:48	# PREV_BASH_OPTS=ehxBET
00:03:18.539   12:59:48	# [[ ehxBET == *\x* ]]
00:03:18.539   12:59:48	# XTRACE_DISABLED=yes
00:03:18.539   12:59:48	# set +x
00:03:18.562  [2021-07-14 12:59:48.635054] Starting SPDK v21.07-pre git sha1 eb22bb767 / DPDK 21.05.0 initialization...
00:03:18.562  [2021-07-14 12:59:48.635151] [ DPDK EAL parameters: [2021-07-14 12:59:48.635164] nvmf [2021-07-14 12:59:48.635174] -c 0xF [2021-07-14 12:59:48.635183] --log-level=lib.eal:6 [2021-07-14 12:59:48.635192] --log-level=lib.cryptodev:5 [2021-07-14 12:59:48.635201] --log-level=user1:6 [2021-07-14 12:59:48.635212] --base-virtaddr=0x200000000000 [2021-07-14 12:59:48.635221] --match-allocations [2021-07-14 12:59:48.635230] --file-prefix=spdk0 [2021-07-14 12:59:48.635240] --proc-type=auto [2021-07-14 12:59:48.635250] ]
00:03:18.602  EAL: No free 2048 kB hugepages reported on node 1
00:03:18.602  EAL: No available 1048576 kB hugepages reported
00:03:18.618  TELEMETRY: No legacy callbacks, legacy socket not created
00:03:18.651  [2021-07-14 12:59:48.723738] app.c: 537:spdk_app_start: *NOTICE*: Total cores available: 4
00:03:18.771  [2021-07-14 12:59:48.844312] trace.c: 188:spdk_trace_init: *ERROR*: could not shm_open spdk_trace
00:03:18.771  [2021-07-14 12:59:48.844385] trace.c: 189:spdk_trace_init: *ERROR*: errno=13 Permission denied
00:03:19.247  /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/common/autotest_common.sh: line 712: kill: (61096) - No such process
00:03:19.247  ERROR: process (pid: 61096) is no longer running
00:03:19.248   12:59:49	# xtrace_enable
00:03:19.248   12:59:49	# (( i == 0 ))
00:03:19.248   12:59:49	# return 1
00:03:19.248    12:59:49	# trap - ERR
00:03:19.248    12:59:49	# print_backtrace
00:03:19.249    12:59:49	# [[ ehxBET =~ e ]]
00:03:19.249    12:59:49	# args=("${BASH_ARGV[@]}")
00:03:19.249    12:59:49	# local args
00:03:19.250    12:59:49	# xtrace_disable
00:03:19.250    12:59:49	# '[' no '!=' yes ']'
00:03:19.250    12:59:49	# PREV_BASH_OPTS=ehxBET
00:03:19.250    12:59:49	# [[ ehxBET == *\x* ]]
00:03:19.250    12:59:49	# XTRACE_DISABLED=yes
00:03:19.250    12:59:49	# set +x
00:03:19.250  ========== Backtrace start: ==========
00:03:19.251  
00:03:19.253  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/nvmf/common.sh:452 -> nvmfappstart(["-m"],["0xF"])
00:03:19.253       ...
00:03:19.253     447 	
00:03:19.253     448 	function nvmfappstart() {
00:03:19.253     449 		timing_enter start_nvmf_tgt
00:03:19.253     450 		"${NVMF_APP[@]}" "$@" &
00:03:19.253     451 		nvmfpid=$!
00:03:19.253  => 452 		waitforlisten $nvmfpid
00:03:19.253     453 		timing_exit start_nvmf_tgt
00:03:19.253     454 	}
00:03:19.253     455 	
00:03:19.253     456 	function nvmftestfini() {
00:03:19.253     457 		nvmfcleanup || :
00:03:19.253       ...
00:03:19.258  in test/nvmf/target/filesystem.sh:47 -> nvmf_filesystem_part(["0"])
00:03:19.258       ...
00:03:19.258     42  	}
00:03:19.258     43  	
00:03:19.258     44  	function nvmf_filesystem_part() {
00:03:19.258     45  		incapsule=$1
00:03:19.258     46  	
00:03:19.258  => 47  		nvmfappstart -m 0xF
00:03:19.258     48  	
00:03:19.258     49  		$rpc_py nvmf_create_transport $NVMF_TRANSPORT_OPTS -u 8192 -c $incapsule
00:03:19.258     50  		$rpc_py bdev_malloc_create $MALLOC_BDEV_SIZE $MALLOC_BLOCK_SIZE -b Malloc1
00:03:19.258     51  		$rpc_py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s $NVMF_SERIAL
00:03:19.258     52  		$rpc_py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc1
00:03:19.258       ...
00:03:19.263  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/common/autotest_common.sh:959 -> run_test(["nvmf_filesystem_no_incapsule"],["nvmf_filesystem_part"],["0"])
00:03:19.263       ...
00:03:19.263     954 		timing_enter $test_name
00:03:19.263     955 		echo "************************************"
00:03:19.263     956 		echo "START TEST $test_name"
00:03:19.263     957 		echo "************************************"
00:03:19.263     958 		xtrace_restore
00:03:19.263  => 959 		time "$@"
00:03:19.263     960 		xtrace_disable
00:03:19.263     961 		echo "************************************"
00:03:19.263     962 		echo "END TEST $test_name"
00:03:19.263     963 		echo "************************************"
00:03:19.263     964 		timing_exit $test_name
00:03:19.263       ...
00:03:19.267  in test/nvmf/target/filesystem.sh:89 -> main(["--transport=rdma"])
00:03:19.268       ...
00:03:19.268     84  	
00:03:19.268     85  		killprocess $nvmfpid
00:03:19.268     86  		nvmfpid=
00:03:19.268     87  	}
00:03:19.268     88  	
00:03:19.268  => 89  	run_test "nvmf_filesystem_no_incapsule" nvmf_filesystem_part 0
00:03:19.268     90  	run_test "nvmf_filesystem_incapsule" nvmf_filesystem_part 4096
00:03:19.268     91  	
00:03:19.268     92  	nvmftestfini
00:03:19.268       ...
00:03:19.268  
00:03:19.268  ========== Backtrace end ==========
00:03:19.268    12:59:49	# xtrace_enable
00:03:19.268    12:59:49	# return 0
00:03:19.269  
00:03:19.269  real	0m0.735s
00:03:19.269  user	0m0.443s
00:03:19.269  sys	0m0.136s

**Comment by spdkci** [comment] 2021-07-14 11:38
Another instance of this failure. Reported by @krish-reddy. log: https://ci.spdk.io/public_build/autotest-per-patch_52910.html

**Comment by changpe1** [comment] 2021-07-22 04:22
[Bug Scrub] this maybe a intermittent failure caused by this patch, so let's keep it open for a while to see it can happen again.

**Comment by spdkci** [comment] 2021-07-30 09:49
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_54569.html

**Comment by spdkci** [comment] 2021-08-09 11:43
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_55601.html

**Comment by spdkci** [comment] 2021-08-13 15:07
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_56034.html

**Comment by spdkci** [comment] 2021-08-16 07:25
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_56114.html

**Comment by spdkci** [comment] 2021-09-02 13:27
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_57441.html

**Comment by spdkci** [comment] 2021-09-07 11:21
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_57735.html

**Comment by spdkci** [comment] 2021-09-29 13:35
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_59351.html

**Comment by spdkci** [comment] 2021-10-05 11:40
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_59604.html

**Comment by jimharris** [comment] 2021-12-22 00:04
This intermittent CI issue has not been seen for 2 months.  Closing.

**Closed by jimharris** 2021-12-22 00:04 UTC
Labels: Intermittent Failure

**Comment by spdkci** [comment] 2022-04-24 16:06
Another instance of this failure. Reported by @amichon-kalray. log: https://ci.spdk.io/public_build/autotest-per-patch_75919.html
