### ISSUE TITLE
nvmf_create_transport unable to create SRQ errno 22

### ISSUE THREAD

**Issue by tkg61** [spdk/spdk#2275] opened 2021-12-09 18:33 UTC
# Bug report

## Expected Behavior

When running through the basic configuration of NVME-OF on this page: https://spdk.io/doc/nvmf.html that we would successfully be able to create a target to host an NVME drive

## Current Behavior

While following the above tutorial when the command to run: `scripts/rpc.py nvmf_create_transport -t RDMA -u 8192 -m 4 -c 0` is given we receive the following error from rpc.py: 

```
root@spdk-ubnt:/home/myuser/spdk# ./scripts/rpc.py nvmf_create_transport -t RDMA -u 8192 -m 4 -c 0
request:
{
  "trtype": "RDMA",
  "max_io_qpairs_per_ctrlr": 4,
  "in_capsule_data_size": 0,
  "io_unit_size": 8192,
  "no_srq": false,
  "c2h_success": true,
  "dif_insert_or_strip": false,
  "no_wr_batching": false,
  "disable_mappable_bar0": false,
  "method": "nvmf_create_transport",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32603,
  "message": "Failed to add transport to tgt.(-1)"
}
```

and error messages on the nvmf_tgt side: 

```
common.c: 269:spdk_rdma_srq_create: *ERROR*: Unable to create SRQ, errno 22 (Invalid argument)
 rdma.c:3274:nvmf_rdma_poll_group_create: *ERROR*: Unable to create shared receive queue, errno 22
nvmf.c:1190:nvmf_poll_group_add_transport: *ERROR*: Unable to create poll group for transport
nvmf_rpc.c:1961:nvmf_rpc_tgt_add_transport_done: *ERROR*: Failed to add transport to tgt.(-1)

```

## Steps to Reproduce

Follow the link above and run the same steps but ignoring the FC LLD commands
1.
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)

Latest SPDK version
Ubuntu 20 5.4.0-88-generic - Virtual machine with NVME passthrough 
```
root@spdk-ubnt:/home/myuser/spdk# scripts/setup.sh status
Hugepages
node     hugesize     free /  total
node0   1048576kB        0 /      0
node0      2048kB      861 /   1024

Type     BDF             Vendor Device NUMA    Driver           Device     Block devices
NVMe     0000:13:00.0    144d   a808   0       uio_pci_generic  -          -
```

```
root@spdk-ubnt:/home/myuser/spdk/build/examples# ./hello_world
[2021-12-09 18:38:30.371315] Starting SPDK v22.01-pre git sha1 91b8cd379 / DPDK 21.08.0 initialization...
[2021-12-09 18:38:30.371385] [ DPDK EAL parameters: [2021-12-09 18:38:30.371395] hello_world [2021-12-09 18:38:30.371407] --no-shconf [2021-12-09 18:38:30.371413] -c 0x1 [2021-12-09 18:38:30.371419] --log-level=lib.eal:6 [2021-12-09 18:38:30.371432] --log-level=lib.cryptodev:5 [2021-12-09 18:38:30.371438] --log-level=user1:6 [2021-12-09 18:38:30.371444] --iova-mode=pa [2021-12-09 18:38:30.371452] --base-virtaddr=0x200000000000 [2021-12-09 18:38:30.371458] --match-allocations [2021-12-09 18:38:30.371464] --file-prefix=spdk_pid46002 [2021-12-09 18:38:30.371470] ]
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
Initializing NVMe Controllers
Attaching to 0000:13:00.0
Attached to 0000:13:00.0
  Namespace ID: 1 size: 2000GB
Initialization complete.
INFO: using host memory buffer for IO
Hello world!
```

Happy to provide any other logs

**Comment by tkg61** [comment] 2021-12-09 18:52
i did some reading on the help page for this command and i am able to negate the error by using the "-r" flag. i don't know what that effects but it mitigates the issue.

**Comment by jimharris** [comment] 2021-12-09 19:07
-r disables SRQ (shared receive queues), so it makes sense why that would mitigate the error you reported.

Can you provide more details on your platform - specifically what kind of RDMA NIC you are using in this setup?

**Comment by tkg61** [comment] 2021-12-09 19:07
I am using a Mellanox ConnectX-5 100Gb

**Comment by tkg61** [comment] 2021-12-09 19:10
After using the -r flag, i ran: 

```
sudo ./rpc.py bdev_nvme_attach_controller  --name NVMe0 --trtype pcie --traddr "0000:13:00.0"
sudo ./rpc.py nvmf_create_subsystem nqn.2018-09.io.spdk:cnode0 -a -s SPDK0000000000001 -d SPDK_Controller1
sudo ./rpc.py nvmf_subsystem_add_ns nqn.2018-09.io.spdk:cnode0 NVMe0n1
sudo ./rpc.py nvmf_subsystem_add_listener nqn.2018-09.io.spdk:cnode0 -t rdma -a 192.168.119.17 -s 4420
```

Upon trying to discover the endpoint from the same machine i get: 

```
 rdma.c:3197:nvmf_rdma_cdata_init: *WARNING*: RDMA is configured to support up to 16 SGL entries while in capsule data is greater than 4KiB.
rdma.c:3199:nvmf_rdma_cdata_init: *WARNING*: When used in conjunction with the NVMe-oF initiator from the Linux kernel between versions 5.4 and 5.12 data corruption may occur for writes that are not a multiple of 4KiB in size.
rdma.c:3775:nvmf_rdma_log_wc_status: *ERROR*: Error on CQ 0x55bbfde4e440, (qp state 1 ibv_state 6) request 0x94265907425880, type SEND, status: (2): local QP operation error
```

**Comment by AlekseyMarchuk** [comment] 2021-12-10 08:20
Hi @tkg61 
This NIC supports SRQ, maybe the problem is in drivers or kernel modules on your VM. Could you query properties of your NIC using `ibv_devinfo -v` on both VM and bare metal host? You can grep the output using `| grep -i srq` to verify that SRQ properties are correctly reported. On my bare metal system with Ubuntu 21.04 and ConnectX-5 the output is following:
```
        max_srq:                        8388608
        max_srq_wr:                     32767
        max_srq_sge:                    31
        rc_odp_caps:
                                        SUPPORT_SEND
                                        SUPPORT_RECV
                                        SUPPORT_WRITE
                                        SUPPORT_READ
                                        SUPPORT_SRQ

```
If you don't have ibv_devinfo tool, please try to install ibverbs-utils package

**Comment by tkg61** [comment] 2021-12-10 13:29
Here is the output of the VM and the PVRDMA nic (was hoping the VM would play host to the NVME drive, not a baremetal box, the client of this would be the ESXi server itself as a test of NVME-OF): 

```
root@spdk-ubnt:/home/myuser/spdk/scripts# ibv_devinfo -v
hca_id: rocep27s0f1
        transport:                      InfiniBand (0)
        fw_ver:                         3.0.000
        node_guid:                      0050:5600:00b2:668c
        sys_image_guid:                 0000:0000:0000:0000
        vendor_id:                      0x15ad
        vendor_part_id:                 2080
        hw_ver:                         0x1
        board_id:                       1
        phys_port_cnt:                  1
        max_mr_size:                    0xffffffff
        page_size_cap:                  0xc
        max_qp:                         32768
        max_qp_wr:                      1024
        device_cap_flags:               0x00201400
                                        PORT_ACTIVE_EVENT
                                        RC_RNR_NAK_GEN
                                        MEM_MGT_EXTENSIONS
        max_sge:                        16
        max_sge_rd:                     16
        max_cq:                         4096
        max_cqe:                        262144
        max_mr:                         262144
        max_pd:                         4096
        max_qp_rd_atom:                 16
        max_ee_rd_atom:                 0
        max_res_rd_atom:                0
        max_qp_init_rd_atom:            128
        max_ee_init_rd_atom:            0
        atomic_cap:                     ATOMIC_NONE (0)
        max_ee:                         0
        max_rdd:                        0
        max_mw:                         0
        max_raw_ipv6_qp:                0
        max_raw_ethy_qp:                0
        max_mcast_grp:                  0
        max_mcast_qp_attach:            0
        max_total_mcast_qp_attach:      0
        max_ah:                         1048576
        max_fmr:                        0
        max_srq:                        4096
        max_srq_wr:                     1024
        max_srq_sge:                    16
        max_pkeys:                      128
        local_ca_ack_delay:             5
        general_odp_caps:
        rc_odp_caps:
                                        NO SUPPORT
        uc_odp_caps:
                                        NO SUPPORT
        ud_odp_caps:
                                        NO SUPPORT
        xrc_odp_caps:
                                        NO SUPPORT
        completion_timestamp_mask not supported
        core clock not supported
        device_cap_flags_ex:            0x0
        tso_caps:
        max_tso:                        0
        rss_caps:
                max_rwq_indirection_tables:                     0
                max_rwq_indirection_table_size:                 0
                rx_hash_function:                               0x0
                rx_hash_fields_mask:                            0x0
        max_wq_type_rq:                 0
        packet_pacing_caps:
                qp_rate_limit_min:      0kbps
                qp_rate_limit_max:      0kbps
        tag matching not supported
                port:   1
                        state:                  PORT_ACTIVE (4)
                        max_mtu:                4096 (5)
                        active_mtu:             4096 (5)
                        sm_lid:                 0
                        port_lid:               0
                        port_lmc:               0x00
                        link_layer:             Ethernet
                        max_msg_sz:             0x7fffffff
                        port_cap_flags:         0x04010000
                        port_cap_flags2:        0x0000
                        max_vl_num:             1 (1)
                        bad_pkey_cntr:          0x0
                        qkey_viol_cntr:         0x0
                        sm_sl:                  0
                        pkey_tbl_len:           1
                        gid_tbl_len:            6
                        subnet_timeout:         0
                        init_type_reply:        0
                        active_width:           1X (1)
                        active_speed:           2.5 Gbps (1)
                        phys_state:             LINK_UP (5)
                        GID[  0]:               fe80:0000:0000:0000:0250:56ff:feb2:668c
                        GID[  2]:               0000:0000:0000:0000:0000:ffff:c0a8:7711
```

**Comment by AlekseyMarchuk** [comment] 2021-12-10 13:53
This looks interesting `max_srq_wr:                     1024` - it looks like we missed some check on target side since we use default SRQ depth `4096` and don't check device capabilities in that case. Can you try to create RDMA transport with SRQ depth 1024? E.g. `nvmf_create_transport -s 1024` and see if it helps? I'll prepare a patch to check device max_srq_wr when we create an SRQ

**Comment by tkg61** [comment] 2021-12-10 14:43
@AlekseyMarchuk I was able to add that to the nvmf_create_transport command and it did not error out! 

Another question, do you know of anyone who has successfully connected an ESXi host server to an SPDK hosted NVME-OF backend (regardless of being a VM or not)

**Comment by tkg61** [comment] 2021-12-10 14:51
> After using the -r flag, i ran:
> 
> ```
> sudo ./rpc.py bdev_nvme_attach_controller  --name NVMe0 --trtype pcie --traddr "0000:13:00.0"
> sudo ./rpc.py nvmf_create_subsystem nqn.2018-09.io.spdk:cnode0 -a -s SPDK0000000000001 -d SPDK_Controller1
> sudo ./rpc.py nvmf_subsystem_add_ns nqn.2018-09.io.spdk:cnode0 NVMe0n1
> sudo ./rpc.py nvmf_subsystem_add_listener nqn.2018-09.io.spdk:cnode0 -t rdma -a 192.168.119.17 -s 4420
> ```
> 
> Upon trying to discover the endpoint (`nvme discover -t rdma -a 192.168.119.17 -s 4420`) from the same machine i get:
> 
> ```
>  rdma.c:3197:nvmf_rdma_cdata_init: *WARNING*: RDMA is configured to support up to 16 SGL entries while in capsule data is greater than 4KiB.
> rdma.c:3199:nvmf_rdma_cdata_init: *WARNING*: When used in conjunction with the NVMe-oF initiator from the Linux kernel between versions 5.4 and 5.12 data corruption may occur for writes that are not a multiple of 4KiB in size.
> rdma.c:3775:nvmf_rdma_log_wc_status: *ERROR*: Error on CQ 0x55bbfde4e440, (qp state 1 ibv_state 6) request 0x94265907425880, type SEND, status: (2): local QP operation error
> ```

I still received the above error when trying to discover the drive

**Comment by AlekseyMarchuk** [comment] 2021-12-10 15:56
@tkg61 it looks like the first SEND is failed, really strange. Have you tried to use standard tools like `udaddy` or `rping` or `ibv_rc_pingpong` or `ib_write_bw` to verify that RDMA works in your environment?

**Comment by tkg61** [comment] 2021-12-10 18:23
@AlekseyMarchuk i was able to perform a ib_send_bw on my vm to itself (which is the same as trying to mount the nvme on itself)

```
spdk-ubnt:~$ ib_send_bw 192.168.119.17
---------------------------------------------------------------------------------------
                    Send BW Test
 Dual-port       : OFF          Device         : rocep27s0f1
 Number of qps   : 1            Transport type : IB
 Connection type : RC           Using SRQ      : OFF
 TX depth        : 128
 CQ Moderation   : 100
 Mtu             : 4096[B]
 Link type       : Ethernet
 GID index       : 2
 Max inline data : 0[B]
 rdma_cm QPs     : OFF
 Data ex. method : Ethernet
---------------------------------------------------------------------------------------
 local address: LID 0000 QPN 0x0007 PSN 0xd7a484
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:192:168:119:17
 remote address: LID 0000 QPN 0x0006 PSN 0x57184e
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:192:168:119:17
---------------------------------------------------------------------------------------
 #bytes     #iterations    BW peak[MB/sec]    BW average[MB/sec]   MsgRate[Mpps]
 65536      1000             11687.22            11638.44                  0.186215
---------------------------------------------------------------------------------------

```

**Comment by tkg61** [comment] 2021-12-17 15:08
@AlekseyMarchuk here is an example with the ib_write_bw


```
spdk-ubnt:/home/myuser/spdk/scripts# ib_write_bw

************************************
* Waiting for client to connect... *
************************************
---------------------------------------------------------------------------------------
                    RDMA_Write BW Test
 Dual-port       : OFF          Device         : rocep27s0f1
 Number of qps   : 1            Transport type : IB
 Connection type : RC           Using SRQ      : OFF
 CQ Moderation   : 100
 Mtu             : 4096[B]
 Link type       : Ethernet
 GID index       : 2
 Max inline data : 0[B]
 rdma_cm QPs     : OFF
 Data ex. method : Ethernet
---------------------------------------------------------------------------------------
 local address: LID 0000 QPN 0x0008 PSN 0x8b32fa RKey 0x00d900 VAddr 0x007f37a0f98000
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:192:168:119:17
 remote address: LID 0000 QPN 0x0009 PSN 0x6bb19a RKey 0x00da00 VAddr 0x007f30e3ee0000
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:192:168:119:17
---------------------------------------------------------------------------------------
 #bytes     #iterations    BW peak[MB/sec]    BW average[MB/sec]   MsgRate[Mpps]
 65536      5000             11743.47            11714.90                  0.187438
---------------------------------------------------------------------------------------

```

Client (same vm)

```
root@spdk-ubnt:/home/myuser# ib_write_bw 192.168.119.17
---------------------------------------------------------------------------------------
                    RDMA_Write BW Test
 Dual-port       : OFF          Device         : rocep27s0f1
 Number of qps   : 1            Transport type : IB
 Connection type : RC           Using SRQ      : OFF
 TX depth        : 128
 CQ Moderation   : 100
 Mtu             : 4096[B]
 Link type       : Ethernet
 GID index       : 2
 Max inline data : 0[B]
 rdma_cm QPs     : OFF
 Data ex. method : Ethernet
---------------------------------------------------------------------------------------
 local address: LID 0000 QPN 0x0009 PSN 0x6bb19a RKey 0x00da00 VAddr 0x007f30e3ee0000
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:192:168:119:17
 remote address: LID 0000 QPN 0x0008 PSN 0x8b32fa RKey 0x00d900 VAddr 0x007f37a0f98000
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:192:168:119:17
---------------------------------------------------------------------------------------
 #bytes     #iterations    BW peak[MB/sec]    BW average[MB/sec]   MsgRate[Mpps]
 65536      5000             11743.47            11714.90                  0.187438
---------------------------------------------------------------------------------------


```

**Comment by tkg61** [comment] 2021-12-17 15:08
> @AlekseyMarchuk I was able to add that to the nvmf_create_transport command and it did not error out!
> 
> Another question, do you know of anyone who has successfully connected an ESXi host server to an SPDK hosted NVME-OF backend (regardless of being a VM or not)

Any advice on this question? ^^^

**Comment by AlekseyMarchuk** [comment] 2021-12-18 16:58
@tkg61 I'm not aware of who use ESXi.
Regarding your problem with SEND operation error - I'll take a closer look next week. Will it work for you if I prepare some debug patch with more logs for you to reproduce this issue?

**Comment by AlekseyMarchuk** [comment] 2022-02-22 10:09
Hi @tkg61 is there any progress with this issue? Do you need help from our side?

**Comment by tkg61** [comment] 2022-02-23 13:17
Thanks for checking in, i just tried the other day and was able to make some progress on successfully getting a connection from ESXi to a VM running SPDK. Not exactly sure what was difference, possibly missed using 'sudo' in a couple commands or needed it when running spdk in addition to sending requests with rpc.py. 

One question i do have, is if i create an RDMA endpoint with SPDK, how do i recover from a reboot of the system to get it back to the state in which it was in? Is it as simple as using a configuration file and pointing it at the same drives with the data on it or is there another methodology? 

Second question is: Is there a suggestion or best practice on using SPDK to host virtual machines? Is there any redundancies or protections in place for drive failure (normally raid) or duplication of data to another system? 

Thanks!

Ian P

**Comment by tkg61** [comment] 2022-02-23 14:04
Thanks for checking in, i just tried the other day and was able to make some progress on successfully getting a connection from ESXi to a VM running SPDK. Not exactly sure what was difference, possibly missed using 'sudo' in a couple commands or needed it when running spdk in addition to sending requests with rpc.py. 

One question i do have, is if i create an RDMA endpoint with SPDK, how do i recover from a reboot of the system to get it back to the state in which it was in? Is it as simple as using a configuration file and pointing it at the same drives with the data on it or is there another methodology? 

Second question is: Is there a suggestion or best practice on using SPDK to host virtual machines? Is there any redundancies or protections in place for drive failure (normally raid) or duplication of data to another system? 

Thanks!

**Comment by AlekseyMarchuk** [comment] 2022-02-25 11:53
Hi @tkg61 
Regarding your question about configuration recovery - we usually use persistent configuration files. Or as alternative you can create SPDK service (to be used with `systemctl`) and configure it with RPC commands or config file on startup
Regarding your 2nd question - SPDK supports only raid0, so there is no redundancy for now. There is a work on raid5 support

If you don't mind, I'm closing this ticket. You can ask any questions on Slack

**Closed by AlekseyMarchuk** 2022-02-25 11:53 UTC
Labels: Sighting
