### ISSUE TITLE
spdk_thread_send_msg() performance degradation

### ISSUE THREAD

**Issue by alekseymmm** [spdk/spdk#637] opened 2019-01-30 10:04 UTC
I haven't checked updates of SPDK for awhile  but after recent pull from upstream/master I found significant performance degradation if using function spdk_thread_send_msg in some of my experimental bdevs. After small investigation I wrote a simple  modification of null bdev to show the case of perf degradation.
Look at this patch
```
diff --git a/lib/bdev/null/bdev_null.c b/lib/bdev/null/bdev_null.c
index a7a84f9..d0c1798 100644
--- a/lib/bdev/null/bdev_null.c
+++ b/lib/bdev/null/bdev_null.c
@@ -227,6 +227,13 @@ delete_null_bdev(struct spdk_bdev *bdev, spdk_delete_null_complete cb_fn, void *
 	spdk_bdev_unregister(bdev, cb_fn, cb_arg);
 }
 
+static void null_send_complete(void *arg)
+{
+   struct spdk_bdev_io *bdev_io = arg;
+
+   spdk_bdev_io_complete(bdev_io, SPDK_BDEV_IO_STATUS_SUCCESS);
+}
+
 static int
 null_io_poll(void *arg)
 {
@@ -244,7 +251,9 @@ null_io_poll(void *arg)
 	while (!TAILQ_EMPTY(&io)) {
 		bdev_io = TAILQ_FIRST(&io);
 		TAILQ_REMOVE(&io, bdev_io, module_link);
-		spdk_bdev_io_complete(bdev_io, SPDK_BDEV_IO_STATUS_SUCCESS);
+		spdk_thread_send_msg(spdk_bdev_io_get_thread(bdev_io),
+			           null_send_complete, bdev_io);
+
 	}
 
 	return 1;
```
It just send bdev_io completeion to the same thread it was submitted instead of immediate completion.
Test it with fio.
fio_config.ini:
```
[global]
ioengine=spdk_bdev
spdk_conf=bdev.conf
filename=Null_0
thread=1
group_reporting=1
direct=1
verify=0
time_based=1
runtime=60
iodepth=32
offset_increment=5G
rw=randread
bs=4k

[test]
numjobs=32
```

bdev.conf : 
```
[Null]
  Dev Null_0 1024000 4096
```
and run
```
 LD_PRELOAD=examples/bdev/fio_plugin/fio_plugin /root/fio/fio fio_config.ini
```
Results of latest master fio rand read 4k 32jobs 32 depth
Immediate bdev_io completion : 31 M IOPS
Send bdev_io completion : 1,5 M IOPS

After binary search through commits I found the exact time when the degradation occurred.

-  commit f50d7325f8c9519029425f86fb179b48cd3f6179
immediate completion : 31 M IOPS
send completion by spdk_thread_send_msg: 25 M IOPS
- commit 605e530a4e42139298034129a902685935b31a90
immediate completion : 31 M IOPS
send completion by spdk_thread_send_msg: 1,5 M IOPS

The performance of spdk_thread_send_msg is really important for me (and probably other people).

## Expected Behavior

At least the same performance as in the past
## Current Behavior

Not that fast at this moment
## Possible Solution

No idea
## Steps to Reproduce

1. git clone https://github.com/spdk/spdk.git 
2. git checkout master (or 605e530a4e42139298034129a902685935b31a90)
3. ./configure --with-fio=/root/fio --disable-tests
4. make
5. LD_PRELOAD=examples/bdev/fio_plugin/fio_plugin /root/fio/fio fio_config.ini
see 31 M IOPS
6. patch -p1 < null_send.patch (patch posted above)
7. make 
8. LD_PRELOAD=examples/bdev/fio_plugin/fio_plugin /root/fio/fio fio_config.ini
see 1,5 M IOPS
9. git reset --hard; git checkout f50d7325f8c9519029425f86fb179b48cd3f6179
10. ./configure --with-fio=/root/fio --disable-tests
11. make 
12. LD_PRELOAD=examples/bdev/fio_plugin/fio_plugin /root/fio/fio fio_config.ini
see 31 M IOPS
13.  patch -p1 < null_send.patch (patch posted above)
14. make 
15. LD_PRELOAD=examples/bdev/fio_plugin/fio_plugin /root/fio/fio fio_config.ini
see 25 M IOPS

## Context (Environment including OS version, SPDK version, etc.)

1. SPDK master (latest or commit 605e530a4e42139298034129a902685935b31a90 and f50d7325f8c9519029425f86fb179b48cd3f6179)
2. Centos 7.5 kernel 3.10.0-862.14.4.el7.x86_64
3. Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz

**Comment by benlwalker** [comment] 2019-01-30 19:01
Are you sure this is related to TLS? The thread is allocated and a TLS pointer is stored that points at it, but then a new pointer is created inside the I/O channel (not thread local) that also points to it. It's from this new pointer that we're doing the thread lookup in your case, so there's no TLS involved that I see.

Can you run perftop on your benchmark and see what it says the problem is? spdk_thread_send_msg does effectively two operations - get a msg object out of the global memory pool and queue it on a ring. Getting the msg object out of the global memory pool is ripe for optimization via thread-local caches and I plan to do that shortly. I'd be interested to see if it's the mempool showing up highest on your benchmark.

**Comment by alekseymmm** [comment] 2019-01-30 21:03
@ak-gh  As far as I remember bdevperf do not test bdev using multiple threads (like what fio does with numjobs > 1). It generate queuedepth ios in the single thread and submit them to bdev. So the bdevperf test wouldn't  be the same as I described above. Correct me if It is not true. But still I could try it with send msg and immediate completion just for curiosity.

In fact the current performance degradation of spdk_thread_send_msg happens only when the number of io threads is big (like 32 or more). It is not such huge performance lost  if one runs only 2 or 1 threads.

**Comment by jimharris** [comment] 2019-01-30 21:33
By my count, there are 81 commits between f50d732 and 605e530.  Could you try running your test with f50d732~1 (i.e. 7d38f1667) just to confirm this is the exact patch that introduced the failure?

**Comment by jimharris** [comment] 2019-01-30 21:33
sorry - I meant 605e530~1 (70642bcbe)

**Comment by jimharris** [comment] 2019-01-30 21:45
Never mind.  The problem is that before the threading changes, an spdk_thread_send_msg() resulted in a calloc() in the fio plugin itself.  This is pretty cheap.  Now that we've moved that send_msg logic into the threading library itself,  an spdk_mempool is always used - the fio_plugin doesn't have to manage this part of the logic anymore.

But with the fio plugin, the threads aren't DPDK threads, meaning that accessing the mempool always requires a lock to get and put buffers.  That's why you see terrible performance especially as you move to more threads.

We hit this same problem with spdk_bdev_io structures, and solved it by keeping a cache of objects separate (and instead of) the per-thread cache that DPDK mempools keep.  We should be able to use a similar strategy here.  It doesn't work the exact same, since the calling thread allocates the buffer and called thread frees it - but in all of the cases I can think of, thread A calls thread B, but then thread B calls thread A back later.  Or we round robin across all of the threads (A calls B, B calls C, C calls D, D finally calls A).  So in the end it should all just work out - and even if it's not perfect, it's far far better than what's there currently.

**Comment by jimharris** [comment] 2019-01-30 21:46
Of course this is pretty much exactly what @benlwalker said earlier - I just explained it a bit more.  :-)

**Comment by benlwalker** [comment] 2019-01-30 21:50
I'm working on the fix here: https://review.gerrithub.io/c/spdk/spdk/+/442774. Not passing all of the tests in the CI system yet (although it passes everything for me locally).

**Comment by alekseymmm** [comment] 2019-01-30 22:02
@jimharris 

> By my count, there are 81 commits between f50d732 and 605e530
Sorry for not very clear description.  


I mean the commits I mentioned are the commits that touch lib/thread/thread.c where spdk_thread_send_msg lives. 

I will test 605e530~1 (70642bc) and post results today. 

@benlwalker Is your fix supposed to fix the performance degradation?

**Comment by jimharris** [comment] 2019-01-30 22:12
@alekseymmm - no need to post additional results.  We know exactly where the problem is now.

**Comment by benlwalker** [comment] 2019-01-31 17:54
This patch is ready for testing now: https://review.gerrithub.io/c/spdk/spdk/+/442774

I haven't thoroughly benchmarked it just yet myself, but I suspect it's a major improvement.

**Comment by benlwalker** [comment] 2019-01-31 18:51
I applied your change in the original report above to the null bdev so that it specifically tests the performance of spdk_thread_send_message. Then I set up fio with 4 jobs doing random reads at queue depth 32 to a single null bdev (so 4 threads). Here are the results:

I/O per second
18.10.1: 10.2M
19.01: 3.2M
New Patch: 10.2M

**Comment by darsto** [comment] 2019-02-05 10:53
Merged as 2446c5c6f3f4c061b0c1bf9d52739efe2a8a1525

@benlwalker @alekseymmm since you have the setup already, would you mind testing the following patch as well?

https://review.gerrithub.io/c/spdk/spdk/+/443374

**Closed by darsto** 2019-02-05 10:53 UTC

**Comment by alekseymmm** [comment] 2019-02-06 08:09
@darsto 
I checked https://review.gerrithub.io/c/spdk/spdk/+/443374

32 numjobs with 32 depth, randread 4k blocksize
complete immediately: 31 M IOPS
send complete : 28 M IOPS

**Comment by darsto** [comment] 2019-02-06 13:01
Using rte_ring + calloc() buffers instead of rte_mempool cuts down hugepage memory requirement by about 50MB per SPDK instance, but also drops all those rte_mempool's fancy features like extra buffer alignment and memory channel balancing.

@alekseymmm Thanks for testing it! Now I have to run a couple of microbenchmarks on different NUMA nodes.
