### ISSUE TITLE
fio_plugin with md support not calculating lba size correctly with extended lba.

### ISSUE THREAD

**Issue by peterjweir** [spdk/spdk#474] opened 2018-10-23 17:04 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

When using an extended lba format, the fio_plugin does not correctly use the size of the lba for the transfer, 

## Expected Behavior

fio_plugin should be using the extended lba to calculate transfer sizes when using formats like 512+8

## Current Behavior

All calculations are done with the base lba size, so 512 instead of 520.

## Possible Solution

Extending the if statement that checks for doing pi to the following allows both 512 and 520 extended lba to work, not sure about dix, or if solution is appropriate. But I have tested the two above formats.
`	
if (fio_qpair->do_nvme_pi) {
		fio_extended_lba_setup_pi(fio_qpair, io_u);
		block_size = spdk_nvme_ns_get_extended_sector_size(ns);
		lba = io_u->offset / block_size;
		lba_count = io_u->xfer_buflen / block_size;
	}
`

## Steps to Reproduce

1. Run fio plugin against a drive formatted to 512+8 pi type 2, extended lba, with metadata at the end. spdk will report invalid sgl element.

## Context (Environment including OS version, SPDK version, etc.)

Centos7, SPDK from master branch

**Comment by peterjweir** [comment] 2018-10-25 19:45
I have tried the above code, and it does indeed work. I saw this elsewhere and originally was concerned that always using the extended sector size would not be a generic solution. It does work with dif, but i wonder about pract = 1 and dix as well, I am not situated to be able to test those two cases. I don't know if there is any added value in treating all the pi cases explicitly independently from the non pi case.

**Comment by shuhei-matsumoto** [comment] 2018-10-25 23:35
@peterjweir @jimharris 

I could reproduce the issue Peter observed.

I observed the following error when
- I format the P3700 NVMe SSD to 512+8 with PI type 1
- I don't add pi_chk=GUARD|REFTAG|APPTAG to the FIO config file.

```
EAL: Detected 16 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/spdk_pid25245/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL:   using IOMMU type 1 (Type 1)
nvme_ns_cmd.c: 447:_nvme_ns_cmd_rw: *ERROR*: io_flags 0x1 bottom 16 bits is not empty
nvme_ns_cmd.c: 447:_nvme_ns_cmd_rw: *ERROR*: io_flags 0x1 bottom 16 bits is not empty
nvme_ns_cmd.c: 447:_nvme_ns_cmd_rw: *ERROR*: io_flags 0x1 bottom 16 bits is not empty
nvme_ns_cmd.c: 447:_nvme_ns_cmd_rw: *ERROR*: io_flags 0x1 bottom 16 bits is not empty
nvme_ns_cmd.c: 447:_nvme_ns_cmd_rw: *ERROR*: io_flags 0x1 bottom 16 bits is not empty
nvme_ns_cmd.c: 447:_nvme_ns_cmd_rw: *ERROR*: io_flags 0x1 bottom 16 bits is not empty
nvme_ns_cmd.c: 447:_nvme_ns_cmd_rw: *ERROR*: io_flags 0x1 bottom 16 bits is not empty
nvme_ns_cmd.c: 447:_nvme_ns_cmd_rw: *ERROR*: io_flags 0x1 bottom 16 bits is not empty

```

Even if I added pi_chk to the FIO config file, nothing changes.

```
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL:   using IOMMU type 1 (Type 1)
nvme_ns_cmd.c: 447:_nvme_ns_cmd_rw: *ERROR*: io_flags 0x1 bottom 16 bits is not empty
nvme_ns_cmd.c: 447:_nvme_ns_cmd_rw: *ERROR*: io_flags 0x1 bottom 16 bits is not empty
nvme_ns_cmd.c: 447:_nvme_ns_cmd_rw: *ERROR*: io_flags 0x1 bottom 16 bits is not empty
nvme_ns_cmd.c: 447:_nvme_ns_cmd_rw: *ERROR*: io_flags 0x1 bottom 16 bits is not empty
```

**Comment by shuhei-matsumoto** [comment] 2018-10-26 01:45
I added the patch to fix the issue I observed. But I haven't observed the same issue with @peterjweir .

**Comment by jimharris** [comment] 2018-11-01 04:45
@peterjweir, @shuhei-matsumoto 

Is there a patch out for the proposed fix on GerritHub?  If so, and it is merged, can we close this issue?

**Comment by shuhei-matsumoto** [comment] 2018-11-01 04:46
my patch was merged.

**Comment by jimharris** [comment] 2018-11-01 04:48
Hi @shuhei-matsumoto - is is commit 25d5f2?

**Comment by jimharris** [comment] 2018-11-01 04:48
commit 25d5f262

**Comment by shuhei-matsumoto** [comment] 2018-11-01 04:50
Hi @jimharris 
Yes, and I think the possible solution is already implemented and the reason why Peter observed was that read was done to the area not written yet.

**Comment by xuhuagen** [comment] 2018-11-01 06:09
I  could  reproduce  the issue shuhei observed. 
I test it in latest code (commit id is 544e863db18872937fc18dd68e7021ffb9ae7a82)
`nvme_ns_cmd.c: 447:_nvme_ns_cmd_rw: *ERROR*: io_flags 0x10000001 bottom 16 bits is not empty`
 not occur,this issue is fixed.

**Comment by peterjweir** [comment] 2018-11-01 15:10
It looks like when i originally reported this the line had not been changed to always use the extended lba. Now my question is if this is correct. Is it right to always use the extended lba even in the pract =1 case, and for dix where the data is not transmitted as part of an extended lba. I don’t have access to equipment with those capabilities today To be able to test, but at first glance it looks like there may be a problem with one of those formats.  No i did not report this because i had not written to a block yet.

**Comment by shuhei-matsumoto** [comment] 2018-11-05 02:49
@peterjweir 

Thank you for your clarification.

As the following line in fio_plugin.c says, it looks that T10 PI implementation is not enough.
```
        /* TODO: considering situations that fio will randomize and verify io_u */
        if (fio_qpair->do_nvme_pi) {
                fio_extended_lba_setup_pi(fio_qpair, io_u);
        }
```

If my understanding is correct, we will have to support stripping the separate metadata for read and inserting the separate metadata for write to run FIO with SPDK FIO plugin for the NVMe SSD enabled with T10 PI. FIO isn't aware of the extended LBA.

As you say, we should use spdk_nvme_ns_get_extended_sector_size() only when the extended LBA is enabled and PRACT is disabled. But we have not a few things to do. Pending this change is OK for now?

**Comment by liang2yan** [comment] 2018-11-15 04:54
@peterjweir @shuhei-matsumoto , what is the next steps for this issue?

**Comment by peterjweir** [comment] 2018-12-12 19:42
Sorry for leaving this as it was for so long. The problem is that this doesn't support the general case of PI, so the current code path prohibits some PI settings from being tested. I think the solution to this ticket is to acknowledge this and make a feature request to extend the support to allow PI to work generally. It seems to fall less in the category of a bug and more in the category of a partially complete feature.

**Comment by jimharris** [comment] 2018-12-13 16:03
Hi @peterjweir,

Could I trouble you to post some text here that specifically calls out the enhancement request?  Then we can get that onto a Trello card in the NVMe backlog for future development, and close this issue.

If you post the text here, I'll take care of getting it on Trello with links between that Trello card and this issue (both ways).

Thanks,

-Jim

**Comment by peterjweir** [comment] 2018-12-13 16:59
Certainly, @jimharris 

The wording for the feature request:

Please extend the fio_plugin to support all e2e protection types correctly. In addition to DIF support which it has today, this means DIX support, and making sure that PRACT and all PI types are behaving as expected in both cases.

**Comment by jimharris** [comment] 2018-12-13 20:21
Trello card added here:  https://trello.com/c/gBwYtulh/20-full-pi-support-in-fio-nvme-plugin

Closing this issue.  This full conversation will still remain intact - further discussion or details should go in the Trello card.  Thanks for the input @peterjweir!

**Closed by jimharris** 2018-12-13 20:21 UTC
Labels: Medium, bug
