### ISSUE TITLE
[examples] spdk_nvme_perf hangs on readv() when pattern = randread and queue depth > 128

### ISSUE THREAD

**Issue by Maciej-Szulik** [spdk/spdk#2677] opened 2022-08-31 10:31 UTC
# Bug report
`spdk_nvme_perf` hangs on `readv()` when io pattern (`--io-pattern`) is `randread` and queue depth (`--io-depth`) > `128`.

> Note: for randwrite it works fine.

## Expected Behavior

`spdk_nvme_perf` should support queue depth up to `Maximum Queue Entries Supported (MQES)`.

## Current Behavior

`spdk_nvme_perf` hangs on `readv()` when io pattern (`--io-pattern`) is `randread` and queue depth (`--io-depth`) > 128.

## Possible Solution

N/A

## Steps to Reproduce
1. Run target:
	```bash
	$SPDK_REPO/build/bin/nvmf_tgt --cpumask $SPDK_CPU_MASK --wait-for-rpc &

	sleep 2

	$SPDK_REPO/scripts/rpc.py sock_impl_set_options -i posix --enable-zerocopy-send-server

	$SPDK_REPO/scripts/rpc.py framework_start_init 

	$SPDK_REPO/scripts/rpc.py nvmf_create_transport --trtype TCP --max-queue-depth=4096 --num-shared-buffers=8192

	SPDK_BDEV_NUM_BLOCKS=1024
	SPDK_BDEV_BLOCK_SIZE=4096
	SPDK_SNQN_BASE=nqn.2019-06.io.spdk
	SPDK_BDEV_BASE=Null

	i=0
	$SPDK_REPO/scripts/rpc.py bdev_null_create $SPDK_BDEV_BASE$((i)) $SPDK_BDEV_NUM_BLOCKS $SPDK_BDEV_BLOCK_SIZE 
	$SPDK_REPO/scripts/rpc.py nvmf_create_subsystem $SPDK_SNQN_BASE:$((i+1)) --allow-any-host --max-namespaces 8 
	$SPDK_REPO/scripts/rpc.py nvmf_subsystem_add_ns $SPDK_SNQN_BASE:$((i+1))  $SPDK_BDEV_BASE$((i)) 
	$SPDK_REPO/scripts/rpc.py nvmf_subsystem_add_listener $SPDK_SNQN_BASE:$((i+1)) --trtype tcp --traddr $STORAGE_NODE_IP --trsvcid 4420 

	$SPDK_REPO/scripts/rpc.py bdev_nvme_set_options --keep-alive-timeout-ms 40000 
	```

2. Run `spdk_nvme_perf`:

	```bash
		spdk_nvme_perf -r "trtype:TCP traddr:$STORAGE_NODE_IP adrfam:IPv4 trsvcid:4420 subnqn:nqn.2019-06.io.spdk:1" -T nvme --io-depth 512 --io-size 4096 --io-pattern randread --time 10 --warmup-time 5 --core-mask 0x1 --num-qpairs 1 --default-sock-impl posix
	```

	Backtrace:

	```
	(gdb) bt
	#0  0x0000007ff7aa66d8 in readv () from /lib/libc.so.6
	#1  0x000000555556fc10 in posix_sock_read (sock=0x55557a6500) at posix.c:1368
	#2  posix_sock_readv (_sock=0x55557a6500, iov=0x7fffffef20, iovcnt=1) at posix.c:1443
	#3  0x000000555556fc70 in posix_sock_recv (sock=<optimized out>, buf=<optimized out>, len=<optimized out>) at posix.c:1460
	#4  0x00000055555839ac in spdk_sock_recv (len=<optimized out>, buf=<optimized out>, sock=<optimized out>) at sock.c:458
	#5  nvme_tcp_read_data (sock=<optimized out>, bytes=<optimized out>, buf=<optimized out>) at /root/spdk/include/spdk_internal/nvme_tcp.h:384
	#6  0x0000005555584eb8 in nvme_tcp_read_pdu (reaped=0x7fffffefd4, tqpair=0x55557a6360) at nvme_tcp.c:1632
	#7  nvme_tcp_qpair_process_completions (qpair=0x55557a6360, max_completions=4095) at nvme_tcp.c:1783
	#8  0x0000005555578bb8 in nvme_transport_qpair_process_completions (max_completions=0, qpair=0x55557a6360) at nvme_transport.c:605
	#9  spdk_nvme_qpair_process_completions (qpair=0x55557a6360, max_completions=0) at nvme_qpair.c:745
	#10 0x0000005555580708 in nvme_tcp_qpair_sock_cb (ctx=<optimized out>, group=<optimized out>, sock=<optimized out>) at nvme_tcp.c:1841
	#11 0x00000055555871b0 in sock_group_impl_poll_count (max_events=32, group=0x55557a66b0, group_impl=0x55557a6720) at sock.c:695
	#12 spdk_sock_group_poll_count (max_events=32, group=0x55557a66b0) at sock.c:721
	#13 spdk_sock_group_poll (group=0x55557a66b0) at sock.c:672
	#14 nvme_tcp_poll_group_process_completions (tgroup=0x55557a6610, completions_per_qpair=<optimized out>, disconnected_qpair_cb=0x5555569340 <perf_disconnect_cb>) at nvme_tcp.c:2346
	#15 0x0000005555581ba4 in nvme_transport_poll_group_process_completions (disconnected_qpair_cb=0x5555569340 <perf_disconnect_cb>, completions_per_qpair=0, tgroup=0x55557a6610) at nvme_transport.c:708
	#16 spdk_nvme_poll_group_process_completions (group=<optimized out>, completions_per_qpair=0, disconnected_qpair_cb=0x5555569340 <perf_disconnect_cb>) at nvme_poll_group.c:130
	#17 0x000000555556bc84 in nvme_check_io (ns_ctx=<optimized out>) at perf.c:915
	#18 0x000000555556cda0 in work_fn (arg=0x5555793430) at perf.c:1654
	#19 work_fn (arg=0x5555793430) at perf.c:1603
	#20 0x0000005555565a80 in main (argc=<optimized out>, argv=0x7ffffff9e8) at perf.c:3005
	```
3. Verify MQES using `identify` app:
	```
	identify -r "trtype:TCP traddr:$STORAGE_NODE_IP adrfam:IPv4 trsvcid:4420 subnqn:nqn.2019-06.io.spdk:1"
	```

	```
	Maximum Queue Entries:                 4096
	```

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit `cd1b7ab0e7709a117ed6d0a727695e0d2749eda6`

**Comment by yidong0635** [comment] 2022-09-07 00:03
I just curious to run this :
```
./build/examples/perf -r "trtype:TCP traddr:x.x.x.x adrfam:IPv4 trsvcid:4420 subnqn:nqn.2019-06.io.spdk:1" 
-T nvme --io-depth 4096 --io-size 4096 --io-pattern randread --time 10 --warmup-time 5 
--core-mask 0x1 --num-qpairs 1 --default-sock-impl posix
EAL: No free 2048 kB hugepages reported on node 1
TELEMETRY: No legacy callbacks, legacy socket not created
Initializing NVMe Controllers
Attached to NVMe over Fabrics controller at x.x.x.x:4420: nqn.2019-06.io.spdk:1
controller IO queue size 4096 less than required
Consider using lower queue depth or small IO size because IO requests may be queued at the NVMe driver.
Associating TCP (addr:x.x.x.x subnqn:nqn.2019-06.io.spdk:1) NSID 1 with lcore 0
Initialization complete. Launching workers.
========================================================
                                                                                                           Latency(us)
Device Information                                                     :       IOPS      MiB/s    Average        min        max
TCP (addr:x.x.x.x subnqn:nqn.2019-06.io.spdk:1) NSID 1 from core  0:    3680.90      14.38 1256718.68 1163227.73 1368563.94
========================================================
Total                                                                  :    3680.90      14.38 1256718.68 1163227.73 1368563.94
```
It works fine.

**Comment by wanghailiangx** [comment] 2022-10-08 09:43
I verified your spdk commit version and did not reproduce the problem, build/examples/perf can work well with your steps and --io-depth 512 or 1024. Or you switch to the latest commit and try again.

**Comment by Maciej-Szulik** [comment] 2022-10-25 09:23
I've submitted a patch https://review.spdk.io/gerrit/c/spdk/spdk/+/15136

**Comment by wanghailiangx** [comment] 2022-11-03 06:58
@Maciej-Szulik The patch #15136 had been merged, so could you close this issue if you can't reproduce it?

**Closed** 2022-11-30 17:10 UTC
Labels: Sighting
