### ISSUE TITLE
Devices behind VMD that have address with leading zero are not found

### ISSUE THREAD

**Issue by tanabarr** [spdk/spdk#2896] opened 2023-02-06 14:57 UTC
# Sighting report

We are coming up against an issue where a VMD backing device address with a leading zero is resulting in a device not being found during probe:

```
102 ERROR 2023/02/03 17:56:56 daos_engine:0 EAL: Cannot find device (50505:03:00.0)
103 ERROR 2023/02/03 17:56:56 daos_engine:0 EAL: Failed to attach device on primary process
104 [2023-02-03 17:56:56.646479] nvme.c: 838:nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
105 [2023-02-03 17:56:56.646496] bdev_nvme.c:4022:bdev_nvme_create: *ERROR*: No controller was found with provided trid (traddr: 050505:03:00.0)
106 ERROR 2023/02/03 17:56:56 daos_engine:0 [2023-02-03 17:56:56.650122] json_config.c: 221:rpc_client_poller: *ERROR*: error response:-
107 {
108   "code": -19,
109   "message": "No such device"
110 }
```
The leading zero is contained in the config supplied to SPDK but seems to get truncated internally.

From the JSON SPDK config used to init:
```
[1:58 PM] Nabarro, Tom
33         {
34           "params": {
35             "trtype": "PCIe",
36             "name": "Nvme_0_1",
37             "traddr": "050505:03:00.0"
38           },
39           "method": "bdev_nvme_attach_controller"
40         },
41         {
42           "params": {
43             "trtype": "PCIe",
44             "name": "Nvme_1_1",
45             "traddr": "050505:05:00.0"
46           },
47           "method": "bdev_nvme_attach_controller"
48         }
```
We are only seeing this problem with devices behind the specific domain 0000:05:05.5, not for example 0000:d5:05.5.

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)
Rocky Linux 8.5, SPDK v22.01.2

**Comment by tanabarr** [comment] 2023-02-06 16:08
```
{
  "daos_data": {
    "config": []
  },
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "params": {
            "bdev_io_pool_size": 65536,
            "bdev_io_cache_size": 256
          },
          "method": "bdev_set_options"
        },
        {
          "params": {
            "retry_count": 4,
            "timeout_us": 0,
            "nvme_adminq_poll_period_us": 100000,
            "action_on_timeout": "none",
            "nvme_ioq_poll_period_us": 0
          },
          "method": "bdev_nvme_set_options"
        },
        {
          "params": {
            "enable": false,
            "period_us": 0
          },
          "method": "bdev_nvme_set_hotplug"
        },
        {
          "params": {
            "trtype": "PCIe",
            "name": "Nvme_nvm0605.hpc.eu.lenovo.com_0_1",
            "traddr": "050505:03:00.0"
          },
          "method": "bdev_nvme_attach_controller"
        },
        {
          "params": {
            "trtype": "PCIe",
            "name": "Nvme_nvm0605.hpc.eu.lenovo.com_1_1",
            "traddr": "050505:05:00.0"
          },
          "method": "bdev_nvme_attach_controller"
        }
      ]
    },
    {
      "subsystem": "vmd",
      "config": [
        {
          "params": {},
          "method": "enable_vmd"
        }
      ]
    }
  ]
}
```
The working one is identical to above with `"traddr": "d50505:03:00.0"` and `"traddr": "d50505:05:00.0"` .

**Comment by tanabarr** [comment] 2023-02-07 15:07
Currently testing with the leading zero removed in traddr in the SPDK JSON conf.

**Comment by tanabarr** [comment] 2023-02-07 15:09
issue closed by mistake, reopening

**Comment by ksztyber** [comment] 2023-02-10 08:52
@tanabarr, could you post logs with debug flag enabled?

**Comment by tanabarr** [comment] 2023-02-22 11:56
awaiting logs from customer after being on leave last week

**Comment by mazahirhussain** [comment] 2023-07-03 08:02
@tanabarr Hi, Is there any fix for this issue? I am also stuck here, building for ubuntu 22.04.

**Comment by tomzawadzki** [comment] 2023-09-05 15:44
[Bug scrub] @tanabarr Were you able to get some logs for this issue ?

**Comment by ksztyber** [comment] 2024-09-03 15:20
[Bug scrub] There was no comments for a year, closing the issue. @tanabarr feel free to re-open if the issue is still happening.

**Closed by ksztyber** 2024-09-03 15:20 UTC
Labels: Waiting on Submitter, Sighting
