### ISSUE TITLE
nvmf target reported error with multi-core while running large IO in two host machines

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#636] opened 2019-01-30 08:26 UTC
This issue is similar with issue 570, except run nvmf target with some modification.

## Expected Behavior
no error is out.

## Steps to Reproduce
1. run nvmf target with following transport config and "-m 0xffff":
```
[Transport]
  Type RDMA
  MaxQueueDepth 1024
  MaxQueuesPerSession 8
  InCapsuleDataSize 4096
  MaxIOSize 131072

```

2. run fio job in two host machines. the fiojob can refer to issue 570.
3.  the nvmf target will report error.
```
ctrlr.c: 441:_spdk_nvmf_ctrlr_add_io_qpair: *ERROR*: Unknown controller ID 0x2
rdma.c:2781:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067d95000 length=131072
rdma.c:2781:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200066280000 length=131072
rdma.c:2755:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067d95000 length=131072
rdma.c:2781:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067c6c000 length=131072
rdma.c:2755:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067c6c000 length=131072
rdma.c:2755:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200066280000 length=131072
rdma.c:2781:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20006602e000 length=131072
rdma.c:2755:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20006602e000 length=131072

```

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit: abc156458fff4f25104604bf91b39651d9423a9a

**Comment by jimharris** [comment] 2019-01-30 16:02
Hi @liang2yan,

Please add all of the details in each issue.  It becomes difficult to find all of the details when one issue points to another issue.

Thanks,

-Jim

**Comment by optimistyzy** [comment] 2019-02-12 04:33
@liang2yan Can you provide detail steps for this issue?

**Comment by liang2yan** [comment] 2019-02-14 02:12
## Steps to reproduce:
1. get latest spdk codes, I used commit(77a55a2fc4d6abf79ac0fdbb5fbb060e79a51b31).
2.  start spdk nvmf target with the config file in attachment and "-m 0xffff":
[nvmf-nvme-hotplug-multicore.txt](https://github.com/spdk/spdk/files/2862982/nvmf-nvme-hotplug-multicore.txt)
3.  run fio job in two host machines, job file can be as below:

```
[global]
thread=1
rw=randrw
runtime=300
time_based=1
ioengine=libaio
direct=1
bs=4096
invalidate=1
iodepth=16
norandommap=1
[job0]
filename=/dev/nvme0n1
[job1]
filename=/dev/nvme1n1
[job2]
filename=/dev/nvme2n1
[job3]
filename=/dev/nvme3n1
[job4]
filename=/dev/nvme4n1
[job5]
filename=/dev/nvme5n1
```
4. while fio is running, the nvmf target will report following error:

```
transport.c: 215:spdk_nvmf_transport_poll_group_create: *NOTICE*: Unable to reserve the full number of buffers for the pg buffer cache.
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067fd3000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067fd3000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067fca000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067fca000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200068070000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200068070000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200068033000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200068033000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20006809a000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20006809a000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x2000680d9000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x2000680d9000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067e9f000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067e9f000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067ea2000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067ea2000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067f3c000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067f3c000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067f33000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067f33000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067b29000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067b29000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067b53000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067b53000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067b5f000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067b5f000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067b83000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067b83000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067df6000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067df6000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067dc6000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067dc6000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067cf3000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067cf3000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067cc9000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067cc9000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067e42000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067e42000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067e7e000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067e7e000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067d6f000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067d6f000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067d6c000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067d6c000 length=131072
ctrlr.c: 441:_spdk_nvmf_ctrlr_add_io_qpair: *ERROR*: Unknown controller ID 0x3
ctrlr.c: 441:_spdk_nvmf_ctrlr_add_io_qpair: *ERROR*: Unknown controller ID 0x3
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067c99000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067c99000 length=131072
rdma.c:2811:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067c9f000 length=131072
rdma.c:2783:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200067c9f000 length=131072

```

**Comment by yidong0635** [comment] 2019-02-22 07:03
@liang2yan , @optimistyzy ,I observed the log  spdk_nvmf_transport_poll_group_create  failed.
it may caused by  lacking of memory which need be got  from : rte_mempool_get. 
maybe we need to clean some  occupied memory and try again.

**Comment by wanqunintel** [comment] 2019-03-12 06:17
@yidong0635 , Ziye mentioned there should be a patch merged for this issue, would you retest with master and update here?

**Comment by yidong0635** [comment] 2019-03-14 03:17
use the latest code, follow liang's steps. I got the results and the target never report errors.

**Comment by yidong0635** [comment] 2019-03-14 03:20
@liang2yan @wanqunintel @ZiyeYang   this issue can be closed I think.

**Comment by optimistyzy** [comment] 2019-03-14 06:58
@yidong0635 Let me close this issue. If you detect this issue again, please do reopen this.

**Closed by optimistyzy** 2019-03-14 06:58 UTC
Labels: Waiting on Submitter
