### ISSUE TITLE
When building shared libraries, dynamic link dependencies not declared

### ISSUE THREAD

**Issue by jgrodman** [spdk/spdk#911] opened 2019-08-14 16:01 UTC
This is related to #901, which @Seth5141 helped with

When I compile after configuring with `--with-shared`, the `.so` files are built, but their dependencies are not linked. This makes it so that the applications which depend on the `.so` files need to declare the dependencies of the `.so` files.

For example, the `examples/bdev/hello_world` application depends on `lib/bdev`, but it needs to then declare dependencies that `lib/bdev` has.
`ldd build/lib/libspdk_bdev.so` shows that bdev is not declaring the dependency
And `examples/bdev/hello_world/Makefile` then has to declare the dependencies.

I think the solution is to have the `.so` files linked explicitly with the `-l` flag, so that applications which depend on them don't have to depend on their dependencies.

This is currently creating a problem for me because I am loading the ".so" files into a dotnet c# application, and from what I've seen, c# doesn't have a way to declare these dependencies, so I had to build a ".so" file that does declare the dependencies with the `-l` flag, and then load that ".so" into c#. However, after adding enough libraries that the dotnet program will start, I'm still getting the "spdk_event_mempool creation failed" error from the other ticket, which seems to me like I am missing a dependency still (and I am building with `--no-as-needed`).

Thank you very much for the help,
Jesse

**Comment by Seth5141** [comment] 2019-08-14 19:47
@jgrodman Funny you should mention this. I have had it on my to do list for a while, and just started revisiting it a couple of days ago after we closed #901. I am slogging through a couple of dependency loops trying to figure out the best way to link some of the bdev modules right now, but am close to having it set up. Here is the tip of my current review chain: https://review.gerrithub.io/c/spdk/spdk/+/465196/1

**Comment by jgrodman** [comment] 2019-08-14 20:06
Hi Seth, okay great so glad we are in sync!

Are you planning on doing the same thing for dpdk? I suspect that is where I'm currently hitting my issue, because of the `spdk_event_mempool` issue. I guess one way to do this would be to include all of the `DPDK_LIB_LIST` libs from https://github.com/spdk/spdk/blob/master/lib/env_dpdk/env.mk when `lib/env_dpdk` is depended on.

As a semi-related meta-issue, is there any way to make the "spdk_event_mempool creation failed" error more explicit since it seemed from #901 like that is actually the result of a missing dependency?

Thanks,
Jesse

**Comment by Seth5141** [comment] 2019-08-14 21:16
In regards to the dpdk stuff, I am hesitant to make those dependencies at link time. The reason for that is that people may be using their own version of dpdk with different names for the shared objects. I am actually not 100% sure how the naming convention for dpdk .so files works or if we are even compatible against dpdk shared objects with different versions. But that is my concern there. Similarly, I am not planning on creating linker dependencies from libspdk_*.so to libspdk_env_dpdk.so since there are plenty of SPDK users who implement their own environment abstraction layer. They will need to replace the libspdk_env_dpdk.so library at will.

For linking against dpdk shared libraries, you can link against the libdpdk.so which is a linker script that will handle the minutia of finding each dpdk library for you. The libspdk.so linker script is actually based on that concept.

So the way I see linking against individual SPDK shared libraries is as follows.

~~~
gcc -o my_app my_app.c -lspdk_x.so -lspdk_y.so -lspdk_env_dpdk -ldpdk
~~~

If there is a compelling reason for creating all of the linker dependencies through env down to dpdk, I think we could add a flag to configure to make that possible while still preserving a default that left the SPDK shared objects able to link against alternative environments and versions of DPDK.

**Comment by Seth5141** [comment] 2019-08-14 21:23
Oh and I'm not sure about the whole spdk_event_mempool error. My assumption would have been that if the symbol couldn't be found it would fail in some more spectacular way. I don't know enough yet about how a binary handles symbols that don't resolve to know why it fails in that way. If there's something I can do about the message within the SPDK make system, I will, but it'll take some research to figure that out.

**Comment by jgrodman** [comment] 2019-08-19 16:37
Hi Seth,

Thanks for your responses, that all makes sense. It's strange because I did link with `-lspdk_env_dpdk -ldpdk`, but was still getting the spdk_event_mempool error...but it could be something else. I'm out of town at the moment, but will double check it all when I'm back.

Jesse

**Comment by Seth5141** [comment] 2019-08-20 17:16
Please see the following patch series for updates to the shared library dependencies. https://review.gerrithub.io/c/spdk/spdk/+/465704. You can double check this series by checking out the tip and after doing a shared object make, running readelf -d to confirm that the proper SPDK shared objects are listed.

I am working on creating a little test repository that will demonstrate how one might compile a custom application and a custom bdev module and link those against SPDK shared objects. My thought is that will act as both an example and something we can put in the spdk autotest to prevent regressions.

**Comment by jgrodman** [comment] 2019-08-22 14:48
Thanks, Seth - the `readelf -d` test works for me - I'm seeing the dependencies. When I have a chance, I will try rebasing on your change and see if my error still occurs.

This is unrelated, but for some reason, when I run `sudo ./scripts/setup.sh` now, I'm getting:
```$ sudo ./scripts/setup.sh
No valid drivers found [vfio-pci, uio_pci_generic, igb_uio]. Please either enable the vfio-pci or uio_pci_generic
kernel modules, or have SPDK build the igb_uio driver by running ./configure --with-igb-uio-driver and recompiling.```

**Comment by Seth5141** [comment] 2019-08-22 16:02
Hey Jesse,

I just want to confirm, when you say "see if my error still occurs", you are talking about having to link the dependencies of each shared object?
I just want to make sure that we aren't talking about the spdk_event_mempool error you mentioned a couple of comments ago. That was fixed by the patch linked in #901, correct?

If you look in setup.sh at the configure_linux_pci function, you will see the checks we are doing for each of those kernel modules. For uio_pci_generic, we are just calling modinfo, but for vfio-pci we are doing some more involved things in the sysfs. You will have to see why your kernel is acting like it doesn't have those modules available. Note, for a VM, we don't typically expect it to have vfio since it doesn't have an IOMMU.

**Comment by jgrodman** [comment] 2019-08-23 15:49
Hey Seth,

Actually, I was referring to the mempool error, which is happening to me when I load the shared object library from c#. It looks like this:

```
$ sudo LD_LIBRARY_PATH=../../../build/lib/:../../../dpdk/build/lib/ dotnet run
Hello World!
Starting SPDK v19.10-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid29814 ]
app.c: 627:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 467:spdk_reactors_init: *ERROR*: spdk_event_mempool creation failed
app.c: 635:spdk_app_start: *ERROR*: Reactor Initilization failed: rc = -1
```

And this is the .so that I'm loading:
```
$ LD_LIBRARY_PATH=../../../build/lib/:../../../dpdk/build/lib/ ldd libspdk_storone_with_links.so
        linux-vdso.so.1 (0x00007fffaefed000)
        libspdk_event.so.1.0 => ../../../build/lib/libspdk_event.so.1.0 (0x00007f21f39f4000)
        libspdk_trace.so.1.0 => ../../../build/lib/libspdk_trace.so.1.0 (0x00007f21f37f0000)
        libspdk_log.so.1.0 => ../../../build/lib/libspdk_log.so.1.0 (0x00007f21f35ed000)
        libspdk_conf.so.1.0 => ../../../build/lib/libspdk_conf.so.1.0 (0x00007f21f33e9000)
        libspdk_thread.so.1.0 => ../../../build/lib/libspdk_thread.so.1.0 (0x00007f21f31e3000)
        libspdk_util.so.1.0 => ../../../build/lib/libspdk_util.so.1.0 (0x00007f21f2fd6000)
        libspdk_rpc.so.1.0 => ../../../build/lib/libspdk_rpc.so.1.0 (0x00007f21f2dd2000)
        libspdk_jsonrpc.so.1.0 => ../../../build/lib/libspdk_jsonrpc.so.1.0 (0x00007f21f2bcb000)
        libspdk_json.so.1.0 => ../../../build/lib/libspdk_json.so.1.0 (0x00007f21f29c3000)
        libspdk_env_dpdk.so.1.0 => ../../../build/lib/libspdk_env_dpdk.so.1.0 (0x00007f21f27b5000)
        librte_eal.so.10.1 => ../../../dpdk/build/lib/librte_eal.so.10.1 (0x00007f21f24d8000)
        librte_mempool.so.5.1 => ../../../dpdk/build/lib/librte_mempool.so.5.1 (0x00007f21f22d2000)
        librte_ring.so.2.1 => ../../../dpdk/build/lib/librte_ring.so.2.1 (0x00007f21f20cf000)
        librte_bus_pci.so.2.1 => ../../../dpdk/build/lib/librte_bus_pci.so.2.1 (0x00007f21f1ec3000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f21f1cbb000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f21f1a9c000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f21f16ab000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f21f3e04000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f21f14a4000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f21f12a0000)
        librte_kvargs.so.1.1 => ../../../dpdk/build/lib/librte_kvargs.so.1.1 (0x00007f21f109d000)
        libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f21f0e92000)
        librte_pci.so.1.1 => ../../../dpdk/build/lib/librte_pci.so.1.1 (0x00007f21f0c8f000)
```

==========

Regarding uio_pci_generic, I was trying to run on AWS. I found the following:
The Ubuntu 18.04 image has the `uio` module in `/lib/modules/`, but it is not loaded. It does not have the `uio_pci_generic` module in `/lib/modules/`
The "Amazon Linux" image has both the `uio` and the `uio_pci_generic` modules in `/lib/modules`, but neither is loaded.

I tried `./configure --with-igb-uio-driver` and recompiling, as directed by the error message, but that didn't help. In any event - I'm back to running on a local Ubuntu VM now, so I'm back to the mempool error.

**Comment by jgrodman** [comment] 2019-09-03 11:51
Hi Seth, yes, the same issue from #901 has returned, when I run the program via c# as I described above. I'm trying to figure out why

**Comment by jgrodman** [comment] 2019-09-03 14:14
I fixed the mempool issue - it was an issue with how I was building the .so that c# was using - I needed to move the `--no-as-needed` flag to the beginning of the command to include all of the libs.

The command to build the intermediary .so which declares the dependencies now looks like this (I just added all the libs in spdk and dpdk):
```
DEPS="-lspdk_bdev_malloc -lspdk_bdev_null -lspdk_bdev_nvme -lspdk_bdev_passthru \
-lspdk_bdev_lvol -lspdk_bdev_raid -lspdk_bdev_error -lspdk_bdev_gpt \
-lspdk_bdev_split -lspdk_bdev_delay -lspdk_blobfs -lspdk_blob_bdev -lspdk_blob \
-lspdk_lvol -lspdk_vmd -lspdk_nvme -lspdk_ftl -lspdk_bdev_aio \
-lspdk_bdev_virtio -lspdk_virtio -lspdk_copy_ioat -lspdk_ioat -lspdk_sock_posix \
-lspdk_event_bdev -lspdk_event_copy -lspdk_event_iscsi -lspdk_event_net \
-lspdk_event_scsi -lspdk_event_nvmf -lspdk_event_vmd -lspdk_event -lspdk_nvmf \
-lspdk_trace -lspdk_log -lspdk_conf -lspdk_thread -lspdk_util -lspdk_bdev \
-lspdk_iscsi -lspdk_scsi -lspdk_copy -lspdk_rpc -lspdk_jsonrpc -lspdk_json \
-lspdk_app_rpc -lspdk_log_rpc -lspdk_trace_rpc -lspdk_bdev_rpc -lspdk_net \
-lspdk_sock -lspdk_notify -lspdk_storone -lspdk_event_nbd -lspdk_nbd -lspdk_env_dpdk \
-lrte_eal -lrte_mempool -lrte_ring -lrte_bus_pci -lrte_bus_vdev \
-lrte_compressdev -lrte_cryptodev -lrte_kvargs -lrte_mbuf \
-lrte_mempool_bucket -lrte_mempool_ring -lrte_mempool -lrte_net -lrte_pci -ldpdk -lspdk"

cc -o libspdk_storone_with_links.so -Wl,--no-as-needed -shared \
-Wl,-z,relro,-z,now -Wl,-z,noexecstack -fuse-ld=bfd -pthread ../../../lib/storone/storone.c \
$DEPS -L../../../build/lib -L../../../dpdk/build/lib -I \
../../../include -fPIC \
-Wl,--soname,libspdk_storone.so.1.0 -Wl,--whole-archive \
-Wl,--no-whole-archive -Wl,--version-script=../../../shared_lib/spdk.map -lrt
```

I'm still interested in Seth's change to have the libs declare their dependencies so that I won't need this intermediary .so file at all!

**Comment by Seth5141** [comment] 2019-09-03 17:00
@jgrodman The changes to add dependencies have been merged to master if you want to give them a try.

**Comment by jgrodman** [comment] 2019-09-04 17:13
Thanks - I will give that a shot! In the meanwhile, happy to close this ticket if you want

**Comment by Seth5141** [comment] 2019-09-04 21:27
Sounds good! We can reopen it if there are any issues down the road, but I feel pretty confident with the dependencies and I have a test verifying that they are correct running on the per-patch CI.

I am still interested in your feedback on the new dependencies and if they work well for your use case, so let me know either way after you have tried it.

**Closed by Seth5141** 2019-09-04 21:27 UTC
Labels: Medium, bug
