### ISSUE TITLE
[crypto-autotest] Starting spdk_tgt got segmentation fault

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#2424] opened 2022-03-11 02:05 UTC
# CI Intermittent Failure

```
00:08:17.049  [2022-03-10 14:47:35.935839] Starting SPDK v22.05-pre git sha1 a7ca8435add / DPDK 22.03.0-rc3 initialization...
00:08:17.049  [2022-03-10 14:47:35.935876] [ DPDK EAL parameters: [2022-03-10 14:47:35.935884] spdk_tgt [2022-03-10 14:47:35.935889] --no-shconf [2022-03-10 14:47:35.935893] -c 0x1 [2022-03-10 14:47:35.935898] --huge-unlink [2022-03-10 14:47:35.935902] --log-level=lib.eal:6 [2022-03-10 14:47:35.935907] --log-level=lib.cryptodev:5 [2022-03-10 14:47:35.935911] --log-level=user1:6 [2022-03-10 14:47:35.935915] --base-virtaddr=0x200000000000 [2022-03-10 14:47:35.935919] --match-allocations [2022-03-10 14:47:35.935924] --file-prefix=spdk_pid222047 [2022-03-10 14:47:35.935928] ]
00:08:17.049  TELEMETRY: No legacy callbacks, legacy socket not created
00:08:17.049  [2022-03-10 14:47:35.986889] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 1
00:08:17.049  [2022-03-10 14:47:36.114278] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 0
00:08:17.049  [2022-03-10 14:47:36.114363] accel_engine.c: 558:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:08:17.310  compdev_isal_create(): 
00:08:17.310  ISA-L library version used: 2.30.0
00:08:17.310  [2022-03-10 14:47:36.168061] vbdev_compress.c: 359:vbdev_init_compress_drivers: *NOTICE*: created virtual PMD compress_isal
00:08:19.856  /var/jenkins/workspace/crypto-autotest/spdk/test/common/autotest_common.sh: line 706: 222047 Segmentation fault      (core dumped) $SPDK_BIN_DIR/spdk_tgt
00:08:19.856  /var/jenkins/workspace/crypto-autotest/spdk/test/common/autotest_common.sh: line 722: kill: (222047) - No such process
00:08:19.856  ERROR: process (pid: 222047) is no longer running
00:08:19.856   14:47:38	-- common/autotest_common.sh@735 -- # xtrace_enable
00:08:19.856   14:47:38	-- common/autotest_common.sh@736 -- # (( i == 0 ))
00:08:19.856   14:47:38	-- common/autotest_common.sh@740 -- # return 1
00:08:19.856    14:47:38	-- common/autotest_common.sh@1402 -- # trap - ERR
00:08:19.856    14:47:38	-- common/autotest_common.sh@1402 -- # print_backtrace
00:08:19.856    14:47:38	-- common/autotest_common.sh@996 -- # [[ ehxBET =~ e ]]
00:08:19.856    14:47:38	-- common/autotest_common.sh@998 -- # args=('autorun-spdk.conf')
00:08:19.856    14:47:38	-- common/autotest_common.sh@998 -- # local args
00:08:19.856    14:47:38	-- common/autotest_common.sh@1000 -- # xtrace_disable
00:08:19.856    14:47:38	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:08:19.856    14:47:38	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:08:19.856    14:47:38	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:08:19.856    14:47:38	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:08:19.856    14:47:38	-- common/autotest_common.sh@19 -- # set +x
```

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_73270.html

## Execution failed at

```
00:08:19.856  ========== Backtrace start: ==========
00:08:19.856  
00:08:19.856  in /var/jenkins/workspace/crypto-autotest/spdk/test/common/autotest_common.sh:1402 -> opal_revert_cleanup([])
00:08:19.856       ...
00:08:19.856     1397			return 0
00:08:19.856     1398		fi
00:08:19.856     1399	
00:08:19.856     1400		$SPDK_BIN_DIR/spdk_tgt &
00:08:19.856     1401		spdk_tgt_pid=$!
00:08:19.856     1402		waitforlisten $spdk_tgt_pid
00:08:19.856     1403	
00:08:19.856     1404		bdf_id=0
00:08:19.856     1405		for bdf in "${bdfs[@]}"; do
00:08:19.856     1406			$rootdir/scripts/rpc.py bdev_nvme_attach_controller -b "nvme"${bdf_id} -t "pcie" -a ${bdf}
00:08:19.856     1407			# Ignore if this fails.
00:08:19.856       ...
00:08:19.856  in /var/jenkins/workspace/crypto-autotest/spdk/autotest.sh:130 -> main(["autorun-spdk.conf"])
00:08:19.856       ...
00:08:19.856     125 	./scripts/setup.sh
00:08:19.856     126 	timing_exit afterboot
00:08:19.856     127 	
00:08:19.856     128 	# Revert existing OPAL to factory settings that may have been left from earlier failed tests.
00:08:19.856     129 	# This ensures we won't hit any unexpected failures due to NVMe SSDs being locked.
00:08:19.856  => 130 	opal_revert_cleanup
00:08:19.856     131 	
00:08:19.856     132 	#####################
00:08:19.856     133 	# Unit Tests
00:08:19.856     134 	#####################
00:08:19.856     135 	
00:08:19.856       ...
00:08:19.856  
00:08:19.856  ========== Backtrace end ==========

```

**Comment by spdkci** [comment] 2022-03-11 02:06
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_73269.html

**Comment by spdkci** [comment] 2022-03-11 02:06
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_73270.html

**Comment by changpe1** [comment] 2022-03-11 02:25
The coredump happened when starting spdk_tgt, and at that moment, we didn't attach the NVMe controller, so it should not related with the OPAL tests, let's continue to see if we can get a valid core trace.

**Comment by shuhei-matsumoto** [comment] 2022-03-11 04:11
Thank you @changpe1 The patch series is for crypto bdev and the seg. fault is caused when running crypto test.  However, it is unlikely that the first two patches caused this failure. So I added this to github. Yes, let's keep monitoring this issue.

**Comment by spdkci** [comment] 2022-03-12 06:34
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_73351.html

**Comment by spdkci** [comment] 2022-03-14 03:00
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_73233.html

**Comment by spdkci** [comment] 2022-03-14 04:34
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_73238.html

**Comment by spdkci** [comment] 2022-03-14 04:37
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_73243.html

**Comment by spdkci** [comment] 2022-03-14 04:38
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_73293.html

**Comment by spdkci** [comment] 2022-03-15 01:44
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_73404.html

**Comment by spdkci** [comment] 2022-03-16 11:03
Another instance of this failure. Reported by @AlekseyMarchuk. log: Not Found

**Comment by changpe1** [comment] 2022-03-17 04:13
[Bug Scrub] @karlatec can you take a look of this environment why the backtrace didn't show in the log? thanks.

**Comment by spdkci** [comment] 2022-03-18 08:00
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_73603.html

**Comment by spdkci** [comment] 2022-03-18 10:11
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_73615.html

**Comment by spdkci** [comment] 2022-03-18 10:11
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_73613.html

**Comment by spdkci** [comment] 2022-03-19 12:46
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_73679.html

**Comment by spdkci** [comment] 2022-03-19 12:47
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_73680.html

**Comment by spdkci** [comment] 2022-03-21 21:45
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_73717.html

**Comment by spdkci** [comment] 2022-03-23 08:07
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_73638.html

**Comment by spdkci** [comment] 2022-03-24 16:45
Another instance of this failure. Reported by @benlwalker. log: https://ci.spdk.io/public_build/autotest-per-patch_73902.html

**Comment by spdkci** [comment] 2022-03-24 23:18
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_73988.html

**Comment by spdkci** [comment] 2022-03-29 23:25
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_74165.html

**Comment by spdkci** [comment] 2022-03-29 23:27
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_74166.html

**Comment by spdkci** [comment] 2022-03-30 10:43
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_74312.html

**Comment by spdkci** [comment] 2022-03-30 10:45
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_74311.html

**Comment by karlatec** [comment] 2022-03-31 08:41
I am unable to reproduce this manually, so this must be some kind on issue in which the fail is caused by whatever was run previously on the test node. In progress.

**Comment by spdkci** [comment] 2022-04-01 03:31
Another instance of this failure. Reported by @fengchunsong. log: https://ci.spdk.io/public_build/autotest-per-patch_74482.html

**Comment by spdkci** [comment] 2022-04-05 13:39
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_74754.html

**Comment by tomzawadzki** [comment] 2022-04-05 15:28
[Bug scrub] Paul will prepare additional instrumentation for compress that might be helpful when getting it reproduced. Then Karol might be able to produce a failing log with it.

**Comment by peluse** [comment] 2022-04-05 16:19
@karlatec lets run this is loop and see what the logs look like on failure.  Just added a bit more detail on init, whether we ever get to one operation or not and shutdown.  I looked at the patches. mentioned from Yuri before, there's little chance they are involved as they were on cleanup following an error, not regular shutdown.  There are some API we *could* call on shutdown to more formally cleanup both crypto/compression, they weren't in there before as we didn't believe they were needed (cryptdeiv_stop and _close, some for compressdev).  We can try adding those but lets see if these simple prints provide a better clue.  https://review.spdk.io/gerrit/c/spdk/spdk/+/12160

**Comment by peluse** [comment] 2022-04-05 17:51
Thanks @karlatec - there are a few things missing from the log which is sort of interesting.  I added a few more prints, please grab the latest version of the patch and lets fire it up again.

**Comment by peluse** [comment] 2022-04-07 21:38
@karlatec anything new w/latest patch?

**Comment by karlatec** [comment] 2022-04-08 06:43
Actually yes. I've been scheduling builds from time to time these past few days, but could not get a reproduction. I finally hit one today :) Unfortunately I think the output is the same as last time.

```
[2022-04-08T06:11:56.771Z] [2022-04-08 08:11:56.474341] Starting SPDK v22.05-pre git sha1 65420c6f7e1 / DPDK 22.07.0-rc0 initialization...
[2022-04-08T06:11:56.771Z] [2022-04-08 08:11:56.474396] [ DPDK EAL parameters: [2022-04-08 08:11:56.474406] spdk_tgt [2022-04-08 08:11:56.474413] --no-shconf [2022-04-08 08:11:56.474420] -c 0x1 [2022-04-08 08:11:56.474427] --huge-unlink [2022-04-08 08:11:56.474433] --log-level=lib.eal:6 [2022-04-08 08:11:56.474440] --log-level=lib.cryptodev:5 [2022-04-08 08:11:56.474447] --log-level=user1:6 [2022-04-08 08:11:56.474454] --base-virtaddr=0x200000000000 [2022-04-08 08:11:56.474461] --match-allocations [2022-04-08 08:11:56.474470] --file-prefix=spdk_pid1222863 [2022-04-08 08:11:56.474477] ]
[2022-04-08T06:11:56.771Z] TELEMETRY: No legacy callbacks, legacy socket not created
[2022-04-08T06:11:56.771Z] [2022-04-08 08:11:56.544241] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 1
[2022-04-08T06:11:56.771Z] [2022-04-08 08:11:56.666488] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
[2022-04-08T06:11:56.771Z] [2022-04-08 08:11:56.666580] accel_engine.c: 549:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2022-04-08T06:11:56.771Z] [2022-04-08 08:11:56.709480] vbdev_crypto.c: 461:vbdev_crypto_init_crypto_drivers: *NOTICE*: Found crypto devices: 1
[2022-04-08T06:11:56.771Z] compdev_isal_create(): 
[2022-04-08T06:11:56.771Z] ISA-L library version used: 2.30.0
[2022-04-08T06:11:56.771Z] [2022-04-08 08:11:56.718686] vbdev_compress.c: 360:vbdev_init_compress_drivers: *NOTICE*: created virtual PMD compress_isal
[2022-04-08T06:11:56.771Z] [2022-04-08 08:11:56.718697] vbdev_compress.c: 373:vbdev_init_compress_drivers: *NOTICE*: cdev_count = 1
[2022-04-08T06:11:56.771Z] [2022-04-08 08:11:56.718706] vbdev_compress.c: 384:vbdev_init_compress_drivers: *NOTICE*: g_mbuf_offset = 104
[2022-04-08T06:11:56.771Z] [2022-04-08 08:11:56.721287] vbdev_compress.c: 404:vbdev_init_compress_drivers: *NOTICE*: call create_compress_dev with 0
[2022-04-08T06:12:00.974Z] /var/jenkins/workspace/crypto-autotest/spdk/test/common/autotest_common.sh: line 708: 1222863 Segmentation fault      (core dumped) $SPDK_BIN_DIR/spdk_tgt
[2022-04-08T06:12:00.974Z] /var/jenkins/workspace/crypto-autotest/spdk/test/common/autotest_common.sh: line 724: kill: (1222863) - No such process
[2022-04-08T06:12:00.974Z] ERROR: process (pid: 1222863) is no longer running
[2022-04-08T06:12:00.974Z]  08:12:00	-- common/autotest_common.sh@737 -- # xtrace_enable
[2022-04-08T06:12:00.974Z]  08:12:00	-- common/autotest_common.sh@738 -- # (( i == 0 ))
[2022-04-08T06:12:00.974Z]  08:12:00	-- common/autotest_common.sh@742 -- # return 1
```
[crypto-log.txt](https://github.com/spdk/spdk/files/8449232/crypto-log.txt)

**Comment by spdkci** [comment] 2022-04-08 07:22
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_74959.html

**Comment by spdkci** [comment] 2022-04-08 10:32
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_75003.html

**Comment by peluse** [comment] 2022-04-08 13:24
@karlatec OK added a bunch more prints, lets check out the next failure.  Thanks

**Comment by karlatec** [comment] 2022-04-11 07:14
Here we go:
```
08:50:17  [2022-04-11 08:50:17.642233] Starting SPDK v22.05-pre git sha1 8fc6781a441 / DPDK 22.07.0-rc0 initialization...
08:50:17  [2022-04-11 08:50:17.642283] [ DPDK EAL parameters: [2022-04-11 08:50:17.642290] spdk_tgt [2022-04-11 08:50:17.642294] --no-shconf [2022-04-11 08:50:17.642299] -c 0x1 [2022-04-11 08:50:17.642303] --huge-unlink [2022-04-11 08:50:17.642308] --log-level=lib.eal:6 [2022-04-11 08:50:17.642316] --log-level=lib.cryptodev:5 [2022-04-11 08:50:17.642320] --log-level=user1:6 [2022-04-11 08:50:17.642325] --base-virtaddr=0x200000000000 [2022-04-11 08:50:17.642329] --match-allocations [2022-04-11 08:50:17.642334] --file-prefix=spdk_pid1307820 [2022-04-11 08:50:17.642338] ]
08:50:17  TELEMETRY: No legacy callbacks, legacy socket not created
08:50:17  [2022-04-11 08:50:17.693611] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 1
08:50:17  [2022-04-11 08:50:17.815825] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
08:50:17  [2022-04-11 08:50:17.815928] accel_engine.c: 549:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
08:50:17  [2022-04-11 08:50:17.859025] vbdev_crypto.c: 461:vbdev_crypto_init_crypto_drivers: *NOTICE*: Found crypto devices: 1
08:50:17  compdev_isal_create(): 
08:50:17  ISA-L library version used: 2.30.0
08:50:17  [2022-04-11 08:50:17.868395] vbdev_compress.c: 368:vbdev_init_compress_drivers: *NOTICE*: created virtual PMD compress_isal
08:50:17  [2022-04-11 08:50:17.868408] vbdev_compress.c: 381:vbdev_init_compress_drivers: *NOTICE*: cdev_count = 1
08:50:17  [2022-04-11 08:50:17.868417] vbdev_compress.c: 392:vbdev_init_compress_drivers: *NOTICE*: g_mbuf_offset = 104
08:50:17  [2022-04-11 08:50:17.871034] vbdev_compress.c: 412:vbdev_init_compress_drivers: *NOTICE*: call create_compress_dev with 0
08:50:17  [2022-04-11 08:50:17.871061] vbdev_compress.c: 236:create_compress_dev: *NOTICE*: Call rte_compressdev_info_get
08:50:17  [2022-04-11 08:50:17.871072] vbdev_compress.c: 240:create_compress_dev: *NOTICE*: cdev_id 0
08:50:17  [2022-04-11 08:50:17.871077] vbdev_compress.c: 248:create_compress_dev: *NOTICE*: qpairs = 48
08:50:17  [2022-04-11 08:50:17.871083] vbdev_compress.c: 257:create_compress_dev: *NOTICE*: Call rte_compressdev configure
08:50:20  /var/jenkins/workspace/crypto-autotest/spdk/test/common/autotest_common.sh: line 708: 1307820 Segmentation fault      (core dumped) $SPDK_BIN_DIR/spdk_tgt
08:50:20  /var/jenkins/workspace/crypto-autotest/spdk/test/common/autotest_common.sh: line 724: kill: (1307820) - No such process
```

**Comment by spdkci** [comment] 2022-04-12 06:10
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_75148.html

**Comment by peluse** [comment] 2022-04-12 15:28
@karlatec @jimharris OK it's crashing inside of DPDK in rte_compressdev_configure() as it never returns from that call.  Either that or it's totally unrelated and that just happens to be where we're at during init when it happens.  Either way, we could add some more prints to DPDK easily enough to see if we can find the offending code, not sure the easiest way to hack in DPDK changes though.  Give you a patch file that you can script in? Make a branch of our DPDK fork?  Jim?

**Comment by karlatec** [comment] 2022-04-12 15:38
How about pushing changes to our current branch in spdk/dpdk? CI is set up in a way that I can schedule builds with custom spdk/dpdk refspec gerrit link.

**Comment by peluse** [comment] 2022-04-12 15:52
dpdk is a submodule though so I'm not quite sure how to do that

**Comment by karlatec** [comment] 2022-04-12 15:55
I think you just need to push changes to spdk/dpdk repo located at our gerrit, the same way you'd normally do for spdk/spdk.
I believe you should send these to  spdk-v21.11 branch.

**Comment by peluse** [comment] 2022-04-12 16:02
So I'm likely over complicating this but the only thing I think I can control with a submoulde is the hash.  I don't think I can change anything (source code) and push it from my spdk branch which would mean I'd have to go to our fork and push a change and use that hash in my spdk repo to pull dpdk from.  I guess that's easy enough just figured there was a better way

**Comment by peluse** [comment] 2022-04-12 17:53
@karlatec OK, try now :)

**Comment by karlatec** [comment] 2022-04-15 11:51
Paul  could you remove the submodule update from the patch? CI cannot pick it up when checking out the submodule.
```
13:39:41  hudson.plugins.git.GitException: Command "git submodule update --init --recursive --reference /var/ci_repos/spdk_multi dpdk" returned status code 1:
13:39:41  stdout: 
13:39:41  stderr: Cloning into '/var/jenkins/workspace/crypto-autotest/spdk/dpdk'...
13:39:41  fatal: remote error: upload-pack: not our ref 59d99451daf7969100557f3a8184c93601d1823a
13:39:41  Fetched in submodule path 'dpdk', but it did not contain 59d99451daf7969100557f3a8184c93601d1823a. Direct fetching of that commit failed.
```

**Comment by spdkci** [comment] 2022-04-19 04:58
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_75495.html

**Comment by spdkci** [comment] 2022-04-19 05:00
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_75497.html

**Comment by tomzawadzki** [comment] 2022-04-19 15:25
[Bug scrub] @peluse Could you change the branch of the dpdk patch to `spdk-21.11` and remove dpdk submodule update from spdk patch ? This will allow to pull both of them and run through Jenkins.

**Comment by spdkci** [comment] 2022-04-20 05:54
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_75572.html

**Comment by spdkci** [comment] 2022-04-20 09:45
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_75629.html

**Comment by spdkci** [comment] 2022-04-21 08:37
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_75697.html

**Comment by spdkci** [comment] 2022-04-21 22:19
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_75850.html

**Comment by spdkci** [comment] 2022-04-25 14:33
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_75969.html

**Comment by spdkci** [comment] 2022-04-27 12:49
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_76089.html

**Comment by karlatec** [comment] 2022-04-27 13:26
@peluse Could you update your patch? I am unable to fetch or pull your change because git complains about inexistent dpdk ref

**Comment by karlatec** [comment] 2022-04-27 13:33
Alright, figured it out. Pushed a new patchset.

**Comment by spdkci** [comment] 2022-04-28 06:44
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_76160.html

**Comment by spdkci** [comment] 2022-04-28 06:47
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_76161.html

**Comment by spdkci** [comment] 2022-04-28 14:22
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_76272.html

**Comment by spdkci** [comment] 2022-04-28 15:25
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_76279.html

**Comment by spdkci** [comment] 2022-04-28 15:26
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_76278.html

**Comment by spdkci** [comment] 2022-04-28 21:13
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_76295.html

**Comment by peluse** [comment] 2022-04-28 21:24
@karlatec you mentioned you updated the patch with some prints in it on the DPDK side, any hits on that yet that we can look at?

**Comment by spdkci** [comment] 2022-04-29 08:10
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_76271.html

**Comment by spdkci** [comment] 2022-05-03 21:03
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_76414.html

**Comment by spdkci** [comment] 2022-05-04 12:10
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_76445.html

**Comment by spdkci** [comment] 2022-05-04 12:32
Another instance of this failure. Reported by @sberbz. log: https://ci.spdk.io/public_build/autotest-per-patch_76334.html

**Comment by spdkci** [comment] 2022-05-04 13:11
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_76443.html

**Comment by spdkci** [comment] 2022-05-04 13:47
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_76458.html

**Comment by karlatec** [comment] 2022-05-05 05:57
@peluse sorry for no updates for a while. I scheduled many re-runs but I was unable to reproduce the issue with spdk/dpdk patch applied.

**Comment by spdkci** [comment] 2022-05-05 06:54
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_76474.html

**Comment by spdkci** [comment] 2022-05-05 09:14
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_76556.html

**Comment by spdkci** [comment] 2022-05-05 09:42
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_76575.html

**Comment by spdkci** [comment] 2022-05-05 10:29
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_76584.html

**Comment by peluse** [comment] 2022-05-05 13:25
> @peluse sorry for no updates for a while. I scheduled many re-runs but I was unable to reproduce the issue with spdk/dpdk patch applied.

@karlatec that's strange, OK keep me posted :)

**Comment by spdkci** [comment] 2022-05-05 13:59
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_76614.html

**Comment by karlatec** [comment] 2022-05-05 18:13
@peluse  I don't think I'm going to be able to keep you posted :) Between my last comment over a week ago and today I've tried to reproduce this several times a day, so looks like it's not reproducible with this combination of patches.

**Comment by spdkci** [comment] 2022-05-06 07:17
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_76609.html

**Comment by spdkci** [comment] 2022-05-10 03:49
Another instance of this failure. Reported by @richael02. log: https://ci.spdk.io/public_build/autotest-per-patch_76824.html

**Comment by spdkci** [comment] 2022-05-10 07:34
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_76833.html

**Comment by spdkci** [comment] 2022-05-10 18:30
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_76887.html

**Comment by karlatec** [comment] 2022-05-10 19:10
@peluse any ideas how we can get this moving forward?
Could this be, by any chance, some timing/race issue which is masked by adding the prints? I know prints don't take much processing time, but still...

**Comment by spdkci** [comment] 2022-05-11 07:24
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_76930.html

**Comment by spdkci** [comment] 2022-05-12 11:21
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_77108.html

**Comment by spdkci** [comment] 2022-05-12 16:38
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_77165.html

**Comment by spdkci** [comment] 2022-05-13 01:19
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_77126.html

**Comment by spdkci** [comment] 2022-05-17 15:05
Another instance of this failure. Reported by @curtbruns. log: https://ci.spdk.io/public_build/autotest-per-patch_77361.html

**Comment by tomzawadzki** [comment] 2022-05-17 15:12
Bug scrub: @karlatec will try to reproduce the issue inside the VM for @peluse to work on. In the meantime @peluse will try to do it on the physical system.

**Comment by spdkci** [comment] 2022-05-17 21:47
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_77410.html

**Comment by peluse** [comment] 2022-05-17 22:11
@karlatec can you please provide steps to repro.  Looking at all the logs I'm not sure what's even running when this happens, looks like the end of the setup test then an target is fired up from somewhere

**Comment by karlatec** [comment] 2022-05-18 05:47
If you have a QAT card in your system the easiest thing to do is:
* Create `~/autorun.conf` file with:
```
SPDK_RUN_FUNCTIONAL_TEST=1
SPDK_TEST_BLOCKDEV=1
SPDK_TEST_ISAL=1
SPDK_TEST_CRYPTO=1
SPDK_TEST_REDUCE=1
SPDK_RUN_UBSAN=1
```
* build SPDK (you can use `--with-shared` too like in the CI)
```
./configure --enable-debug --enable-werror --with-rdma --with-idxd --with-fio=/usr/src/fio --with-iscsi-initiator --disable-unit-tests --with-reduce --with-crypto --enable-ubsan 
make -j
```
* run the tests
```
sudo -E ./autotest.sh ~/autorun.conf
(you can comment out test-setup.sh to speed things up)
```

**Comment by karlatec** [comment] 2022-05-18 05:59
@tomzawadzki I was unable to reproduce it in the VM.

First of all - the reproduction steps I provided to Paul won't work in a VM. I cannot run `autotest.sh` in the VM with SPDK_TEST_CRYPTO and SPDK_TEST_REDUCE flags as this results in script failure due to `qat_setup.sh` complaining about no QAT devices present.

The segfault reported in the issue happens when we start `spdk_tgt` app for the first time during the build. This happens to be done in `opal_revert_cleanup` function, which is quite simple as it just starts spdk add, attaches nvme controller, disables OPAL and kills the app. spdk_tgt crashes before we attach nvme controller so it's not significant, so we're actually just left with "start and stop spdk app" steps.
I've run this for well over 10k iterations and did not hit a segfault:
```
#!/usr/bin/env bash

rootdir=$(readlink -f $(dirname $0))

source "$rootdir/test/common/autotest_common.sh"
source "$rootdir/test/nvmf/common.sh"

set -e
for i in $(seq 1 100000); do
        echo "------------- ITERATION $i"
        ./scripts/setup.sh reset
        ./scripts/setup.sh
        ./build/bin/spdk_tgt &
        spdk_tgt_pid=$!
        waitforlisten $spdk_tgt_pid
        killprocess $spdk_tgt_pid
done
```

The output I get is of course slightly different than these from intermittent failures due to the fact that I don't have a physical QAT card in the VM.
```
[2022-05-18 05:48:53.665136] Starting SPDK v22.05-pre git sha1 00d46b80b / DPDK 22.03.0 initialization...
[2022-05-18 05:48:53.665216] [ DPDK EAL parameters: [2022-05-18 05:48:53.665231] spdk_tgt [2022-05-18 05:48:53.66526
6] --no-shconf [2022-05-18 05:48:53.665280] -c 0x1 [2022-05-18 05:48:53.665294] --huge-unlink [2022-05-18 05:48:53.6
65305] --log-level=lib.eal:6 [2022-05-18 05:48:53.665317] --log-level=lib.cryptodev:5 [2022-05-18 05:48:53.665332] -
-log-level=user1:6 [2022-05-18 05:48:53.665342] --iova-mode=pa [2022-05-18 05:48:53.665354] --base-virtaddr=0x200000
000000 [2022-05-18 05:48:53.665367] --match-allocations [2022-05-18 05:48:53.665377] --file-prefix=spdk_pid2906116 [
2022-05-18 05:48:53.665389] ]
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-05-18 05:48:53.799880] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 1
[2022-05-18 05:48:54.003370] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
[2022-05-18 05:48:54.003523] accel_engine.c: 842:sw_accel_engine_init: *NOTICE*: Accel framework software engine ini
tialized.
compdev_isal_create():
ISA-L library version used: 2.30.0
[2022-05-18 05:48:54.068400] vbdev_compress.c: 360:vbdev_init_compress_drivers: *NOTICE*: created virtual PMD compre
ss_isal
[2022-05-18 05:48:54.112780] vbdev_crypto.c: 461:vbdev_crypto_init_crypto_drivers: *NOTICE*: Found crypto devices: 1

```

**Comment by spdkci** [comment] 2022-05-18 09:06
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_77399.html

**Comment by spdkci** [comment] 2022-05-19 12:31
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_77605.html

**Comment by spdkci** [comment] 2022-05-19 16:00
Another instance of this failure. Reported by @MengjinWu. log: https://ci.spdk.io/public_build/autotest-per-patch_77607.html

**Comment by peluse** [comment] 2022-05-19 18:43
@karlatec OK finally got a machine up w/QAT running Fed35, just started your test script above.  Stay tuned....

**Comment by spdkci** [comment] 2022-05-20 09:37
Another instance of this failure. Reported by @xjjx. log: https://ci.spdk.io/public_build/autotest-per-patch_77664.html

**Comment by peluse** [comment] 2022-05-20 15:06
On my local system w/Fedora 35 and the script above (with a real QAT card) it looks like it will not repro, as you can see below its over 12K runs now.  @karlatec do I remember right that there was a timing related thing a long time ago having to do with setup.sh? I wonder if you can run a patch in CI over and over that just adds like a 1 sec delay before running the spdk_tgt in this case.  Not as a proposed solution but as a data point to see if it affects the test.  Seems like its not going to happen anywhere else

 08:03:50	-- common/autotest_common.sh@846 -- # wait 3597895

 08:03:50	-- ./t.sh@9 -- # for i in $(seq 1 100000)
 08:03:50	-- ./t.sh@10 -- # echo '------------- ITERATION 12767'
------------- ITERATION 12767
 08:03:50	-- ./t.sh@11 -- # ./scripts/setup.sh reset
0000:00:04.7 (8086 2021): vfio-pci -> ioatdma
0000:00:04.6 (8086 2021): vfio-pci -> ioatdma
0000:00:04.5 (8086 2021): vfio-pci -> ioatdma
0000:00:04.4 (8086 2021): vfio-pci -> ioatdma
0000:00:04.3 (8086 2021): vfio-pci -> ioatdma
0000:00:04.2 (8086 2021): vfio-pci -> ioatdma
0000:00:04.1 (8086 2021): vfio-pci -> ioatdma
0000:00:04.0 (8086 2021): vfio-pci -> ioatdma

**Comment by tomzawadzki** [comment] 2022-05-24 15:15
Bug scrub: @karlatec will try whether adding the 1 sec delay before start of the failing spdk_tgt app to see if it affects the failure rate.
Lowering the priority to Medium, due to lack of reproduction outside of the CI.

**Comment by tomzawadzki** [comment] 2022-06-14 15:03
Bug scrub: closing the issue due to lack of reproduction in the last 3 weeks.

**Closed by tomzawadzki** 2022-06-14 15:03 UTC
Labels: bug, Medium, Intermittent Failure
