### ISSUE TITLE
bdevperf 'Failed to submit bdev_io'

### ISSUE THREAD

**Issue by USTCqzy** [spdk/spdk#2108] opened 2021-08-19 08:20 UTC
# Bug report

bdevperf test nvme 'Failed to submit bdev_io' in some conditions.

## Expected Behavior

No failure.

## Current Behavior

$ ./bdevperf -q 1 -t 2 -w **randread** -o 4096 -m **0x1** -c test.json **-C**
[2021-08-19 08:14:29.277580] Starting SPDK v21.07.1-pre git sha1 2b616cdb3 / DPDK 21.05.0 initialization...
[2021-08-19 08:14:29.277621] [ DPDK EAL parameters: [2021-08-19 08:14:29.277625] bdevperf [2021-08-19 08:14:29.277629] --no-shconf [2021-08-19 08:14:29.277632] -c 0x1 [2021-08-19 08:14:29.277636] --log-level=lib.eal:6 [2021-08-19 08:14:29.277639] --log-level=lib.cryptodev:5 [2021-08-19 08:14:29.277642] --log-level=user1:6 [2021-08-19 08:14:29.277646] --iova-mode=pa [2021-08-19 08:14:29.277649] --base-virtaddr=0x200000000000 [2021-08-19 08:14:29.277652] --match-allocations [2021-08-19 08:14:29.277655] --file-prefix=spdk_pid909186 [2021-08-19 08:14:29.277659] ]
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
[2021-08-19 08:14:29.353590] app.c: 537:spdk_app_start: *NOTICE*: Total cores available: 1
[2021-08-19 08:14:29.478654] reactor.c: 931:reactor_run: *NOTICE*: Reactor started on core 0
[2021-08-19 08:14:29.479052] accel_engine.c: 988:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2021-08-19 08:14:29.636163] 'OCF Core' volume operations registered
[2021-08-19 08:14:29.639153] 'SPDK block device' volume operations registered
Running I/O for 2 seconds...
**Failed to submit bdev_io: -22**

## Possible Solution

No idea.

## Steps to Reproduce

1. ./bdevperf -q 1 -t 2 -w **randread** -o 4096 -m **0x1** -c test.json **-C** ×
2. ./bdevperf -q 1 -t 2 -w **read** -o 4096 -m **0x1** -c test.json **-C** √
3. ./bdevperf -q 1 -t 2 -w **randread** -o 4096 -m **0xF** -c test.json **-C** √
4. ./bdevperf -q 1 -t 2 -w **randread** -o 4096 -m **0x1** -c test.json √

test.json
```json
{
    "subsystems": [
      {
        "subsystem": "bdev",
        "config": [
          {
            "method": "bdev_nvme_attach_controller",
            "params": {
              "name": "NVMe1",
              "trtype": "PCIe",
              "traddr": "0000:9b:00.0",
              "prchk_reftag": false,
              "prchk_guard": false
            }
          }
        ]
      }
    ]
  }
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK 21.07.x
Ubuntu 20.04.2

**Comment by Comphix** [comment] 2021-08-19 08:24
Is this same NVMe bdev used in the OCF as Core device?

[2021-08-19 08:14:29.353590] app.c: 537:spdk_app_start: NOTICE: Total cores available: 1
[2021-08-19 08:14:29.478654] reactor.c: 931:reactor_run: NOTICE: Reactor started on core 0
[2021-08-19 08:14:29.479052] accel_engine.c: 988:spdk_accel_engine_initialize: NOTICE: Accel engine initialized to use software engine.
[2021-08-19 08:14:29.636163] 'OCF Core' volume operations registered
[2021-08-19 08:14:29.639153] 'SPDK block device' volume operations registered

Also assign to Wayne for some triage from OCF side.

**Comment by USTCqzy** [comment] 2021-08-19 08:32
@Comphix
yes, but it is not used in ocf now.

**Comment by Comphix** [comment] 2021-08-19 08:38
@gwnet , could you work with @USTCqzy to reproduce this issue first? Looks like first there is some OCF related testing, then the NVMe device is used directly. @USTCqzy , please also add more reproduction steps here including the OCF related.

**Comment by USTCqzy** [comment] 2021-08-19 08:43
@Comphix 
Actually, I am not using ocf here. I guess ocf-relevant messages come from configure flag (--with-ocf)

```bash
$ git clone https://github.com/spdk/spdk
$ cd spdk
spdk$ git checkout v21.07.x
spdk$ git submodule update --init
spdk$ ./configure --with-shared --with-ocf --with-pmdk
spdk$ make
```

**Comment by jimharris** [comment] 2021-08-19 15:26
Hi @USTCqzy,

Is this 100% reproducible on your system?  The only difference between #1 and #2 in your list is the workload (read v. randread) which would not by itself cause any kind of problem.  These are all very well-tested in SPDK CI.

Does this specific test case fail if you run those command lines in a different order?

**Comment by USTCqzy** [comment] 2021-08-19 16:13
@jimharris Yes, it is reproducible for days. It failed even in different order.
```bash
$ ./bdevperf -C -q 1 -t 2 -w read -o 4096 -m 0x1 -c test.json
[2021-08-19 16:08:02.981729] Starting SPDK v21.07.1-pre git sha1 2b616cdb3 / DPDK 21.05.0 initialization...
[2021-08-19 16:08:02.981788] [ DPDK EAL parameters: [2021-08-19 16:08:02.981794] bdevperf [2021-08-19 16:08:02.981798] --no-shconf [2021-08-19 16:08:02.981802] -c 0x1 [2021-08-19 16:08:02.981806] --log-level=lib.eal:6 [2021-08-19 16:08:02.981809] --log-level=lib.cryptodev:5 [2021-08-19 16:08:02.981813] --log-level=user1:6 [2021-08-19 16:08:02.981816] --iova-mode=pa [2021-08-19 16:08:02.981819] --base-virtaddr=0x200000000000 [2021-08-19 16:08:02.981825] --match-allocations [2021-08-19 16:08:02.981828] --file-prefix=spdk_pid982423 [2021-08-19 16:08:02.981832] ]
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
[2021-08-19 16:08:03.088335] app.c: 537:spdk_app_start: *NOTICE*: Total cores available: 1
[2021-08-19 16:08:03.340077] reactor.c: 931:reactor_run: *NOTICE*: Reactor started on core 0
[2021-08-19 16:08:03.340480] accel_engine.c: 988:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2021-08-19 16:08:03.591230] 'OCF Core' volume operations registered
[2021-08-19 16:08:03.594223] 'SPDK block device' volume operations registered
Running I/O for 2 seconds...
 Job: NVMe1n1 (Core Mask 0x1)
         NVMe1n1             :   86117.50 IOPS     336.40 MiB/s
 =============================================================
 Total                       :   86117.50 IOPS     336.40 MiB/s
EAL: device event monitor already stopped

$ ./bdevperf -C -q 1 -t 2 -w randread -o 4096 -m 0x1 -c test.json
[2021-08-19 16:08:56.029510] Starting SPDK v21.07.1-pre git sha1 2b616cdb3 / DPDK 21.05.0 initialization...
[2021-08-19 16:08:56.029541] [ DPDK EAL parameters: [2021-08-19 16:08:56.029545] bdevperf [2021-08-19 16:08:56.029549] --no-shconf [2021-08-19 16:08:56.029552] -c 0x1 [2021-08-19 16:08:56.029556] --log-level=lib.eal:6 [2021-08-19 16:08:56.029559] --log-level=lib.cryptodev:5 [2021-08-19 16:08:56.029562] --log-level=user1:6 [2021-08-19 16:08:56.029565] --iova-mode=pa [2021-08-19 16:08:56.029569] --base-virtaddr=0x200000000000 [2021-08-19 16:08:56.029588] --match-allocations [2021-08-19 16:08:56.029591] --file-prefix=spdk_pid982431 [2021-08-19 16:08:56.029597] ]
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
[2021-08-19 16:08:56.128266] app.c: 537:spdk_app_start: *NOTICE*: Total cores available: 1
[2021-08-19 16:08:56.371552] reactor.c: 931:reactor_run: *NOTICE*: Reactor started on core 0
[2021-08-19 16:08:56.371950] accel_engine.c: 988:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2021-08-19 16:08:56.631277] 'OCF Core' volume operations registered
[2021-08-19 16:08:56.634276] 'SPDK block device' volume operations registered
Running I/O for 2 seconds...
Failed to submit bdev_io: -22

```

**Comment by peluse** [comment] 2021-08-19 16:23
BTW this works fine for me

**Comment by peluse** [comment] 2021-08-19 16:26
do you by any chance have a different system with a different NVMe disk (or different NVMe disk) that you can try?

**Comment by jimharris** [comment] 2021-08-19 16:33
I can reproduce this on my system.  Debugging now.

**Comment by jimharris** [comment] 2021-08-19 17:13
https://review.spdk.io/gerrit/c/spdk/spdk/+/9231

Root cause is that bdevperf was using int in some places where it should have been using uint64_t.  If the SSD has INT32_MAX < num_blocks > UINT32_MAX, we end up storing a negative value for storing the extent to use in the job, which then gets converted to an incorrect value when converted to a uint64_t for purposes of selecting a random offset in the randread case.

**Comment by peluse** [comment] 2021-08-19 17:17
Well done Jim!! See review, looks like you an accidental commit in there....

**Comment by jimharris** [comment] 2021-08-19 17:20
> Well done Jim!! See review, looks like you an accidental commit in there....

Doh!  Thanks for the heads-up - fixed in version 2.

**Closed** 2021-08-20 04:48 UTC
Labels: bug, Patches out for review
