### ISSUE TITLE
[json_config] Error on create_bdev_subsystem_config - 233

### ISSUE THREAD

**Issue by apaszkie** [spdk/spdk#3046] opened 2023-06-05 15:18 UTC
# CI Intermittent Failure

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/105583/archive/crypto-autotest/build.log

## Execution failed at

```
00:04:56.905   14:57:45	-- json_config/json_config.sh@78 -- # cat
00:04:56.905    14:57:45	-- json_config/json_config.sh@78 -- # printf ' %s\n' bdev_register:Nvme0n1 bdev_register:Nvme0n1p1 bdev_register:Nvme0n1p0 bdev_register:Malloc3 bdev_register:PTBdevFromMalloc3 bdev_register:Null0 bdev_register:Malloc0 bdev_register:Malloc0p2 bdev_register:Malloc0p1 bdev_register:Malloc0p0 bdev_register:Malloc1 bdev_register:aio_disk bdev_register:fb773752-e6f3-4c80-a056-ff2283045747 bdev_register:3f6625c1-24f1-41f9-a7dc-17d3c97d49a0 bdev_register:916291a7-e2a7-4a94-b6d8-d851d16d5244 bdev_register:63623f52-bc8d-4271-9e1e-28eefb385b31 bdev_register:MallocForCryptoBdev bdev_register:CryptoMallocBdev
00:04:56.906    14:57:45	-- json_config/json_config.sh@78 -- # printf ' %s\n' bdev_register:Nvme0n1 bdev_register:Nvme0n1p1 bdev_register:Nvme0n1p0 bdev_register:Malloc3 bdev_register:PTBdevFromMalloc3 bdev_register:Null0 bdev_register:Malloc0 bdev_register:Malloc0p2 bdev_register:Malloc0p1 bdev_register:Malloc0p0 bdev_register:Malloc1 bdev_register:aio_disk bdev_register:916291a7-e2a7-4a94-b6d8-d851d16d5244 bdev_register:3f6625c1-24f1-41f9-a7dc-17d3c97d49a0 bdev_register:fb773752-e6f3-4c80-a056-ff2283045747 bdev_register:63623f52-bc8d-4271-9e1e-28eefb385b31 bdev_register:MallocForCryptoBdev bdev_register:CryptoMallocBdev
00:04:56.906  Expected events did not match.
00:04:56.906  
00:04:56.906  Expected:
00:04:56.906   bdev_register:Nvme0n1
00:04:56.906   bdev_register:Nvme0n1p1
00:04:56.906   bdev_register:Nvme0n1p0
00:04:56.906   bdev_register:Malloc3
00:04:56.906   bdev_register:PTBdevFromMalloc3
00:04:56.906   bdev_register:Null0
00:04:56.906   bdev_register:Malloc0
00:04:56.906   bdev_register:Malloc0p2
00:04:56.906   bdev_register:Malloc0p1
00:04:56.906   bdev_register:Malloc0p0
00:04:56.906   bdev_register:Malloc1
00:04:56.906   bdev_register:aio_disk
00:04:56.906   bdev_register:fb773752-e6f3-4c80-a056-ff2283045747
00:04:56.906   bdev_register:3f6625c1-24f1-41f9-a7dc-17d3c97d49a0
00:04:56.906   bdev_register:916291a7-e2a7-4a94-b6d8-d851d16d5244
00:04:56.906   bdev_register:63623f52-bc8d-4271-9e1e-28eefb385b31
00:04:56.906   bdev_register:MallocForCryptoBdev
00:04:56.906   bdev_register:CryptoMallocBdev
00:04:56.906  Recorded:
00:04:56.906   bdev_register:Nvme0n1
00:04:56.906   bdev_register:Nvme0n1p1
00:04:56.906   bdev_register:Nvme0n1p0
00:04:56.906   bdev_register:Malloc3
00:04:56.906   bdev_register:PTBdevFromMalloc3
00:04:56.906   bdev_register:Null0
00:04:56.906   bdev_register:Malloc0
00:04:56.906   bdev_register:Malloc0p2
00:04:56.906   bdev_register:Malloc0p1
00:04:56.906   bdev_register:Malloc0p0
00:04:56.906   bdev_register:Malloc1
00:04:56.906   bdev_register:aio_disk
00:04:56.906   bdev_register:916291a7-e2a7-4a94-b6d8-d851d16d5244
00:04:56.906   bdev_register:3f6625c1-24f1-41f9-a7dc-17d3c97d49a0
00:04:56.906   bdev_register:fb773752-e6f3-4c80-a056-ff2283045747
00:04:56.906   bdev_register:63623f52-bc8d-4271-9e1e-28eefb385b31
00:04:56.906   bdev_register:MallocForCryptoBdev
00:04:56.906   bdev_register:CryptoMallocBdev
00:04:56.906   14:57:45	-- json_config/json_config.sh@86 -- # return 1
00:04:56.906    14:57:45	-- json_config/json_config.sh@233 -- # on_error_exit create_bdev_subsystem_config 233
00:04:56.906    14:57:45	-- json_config/json_config.sh@411 -- # set -x
00:04:56.906    14:57:45	-- json_config/json_config.sh@412 -- # set +e
00:04:56.906    14:57:45	-- json_config/json_config.sh@413 -- # print_backtrace
00:04:56.906    14:57:45	-- common/autotest_common.sh@1107 -- # [[ hxBET =~ e ]]
00:04:56.906    14:57:45	-- common/autotest_common.sh@1107 -- # return 0
00:04:56.906    14:57:45	-- json_config/json_config.sh@414 -- # trap - ERR
00:04:56.906    14:57:45	-- json_config/json_config.sh@415 -- # echo 'Error on create_bdev_subsystem_config - 233'
00:04:56.906  Error on create_bdev_subsystem_config - 233
00:04:56.906    14:57:45	-- json_config/json_config.sh@416 -- # json_config_test_fini
00:04:56.906    14:57:45	-- json_config/json_config.sh@361 -- # timing_enter json_config_test_fini
00:04:56.906    14:57:45	-- common/autotest_common.sh@691 -- # xtrace_disable
00:04:56.906    14:57:45	-- common/autotest_common.sh@20 -- # '[' no '!=' yes ']'
00:04:56.906    14:57:45	-- common/autotest_common.sh@21 -- # PREV_BASH_OPTS=hxBET
00:04:56.906    14:57:45	-- common/autotest_common.sh@22 -- # [[ hxBET == *\x* ]]
00:04:56.906    14:57:45	-- common/autotest_common.sh@23 -- # XTRACE_DISABLED=yes
00:04:56.906    14:57:45	-- common/autotest_common.sh@25 -- # set +x
00:04:56.906    14:57:45	-- common/autotest_common.sh@693 -- # xtrace_enable
00:04:56.906    14:57:45	-- json_config/json_config.sh@362 -- # local ret=0
00:04:56.906    14:57:45	-- json_config/json_config.sh@364 -- # [[ -n '' ]]
00:04:56.906    14:57:45	-- json_config/json_config.sh@372 -- # [[ -n 874991 ]]
00:04:56.906    14:57:45	-- json_config/json_config.sh@375 -- # cleanup_bdev_subsystem_config
00:04:56.906    14:57:45	-- json_config/json_config.sh@239 -- # timing_enter cleanup_bdev_subsystem_config
00:04:56.906    14:57:45	-- common/autotest_common.sh@691 -- # xtrace_disable
00:04:56.906    14:57:45	-- common/autotest_common.sh@20 -- # '[' no '!=' yes ']'
00:04:56.906    14:57:45	-- common/autotest_common.sh@21 -- # PREV_BASH_OPTS=hxBET
00:04:56.906    14:57:45	-- common/autotest_common.sh@22 -- # [[ hxBET == *\x* ]]
00:04:56.906    14:57:45	-- common/autotest_common.sh@23 -- # XTRACE_DISABLED=yes
00:04:56.906    14:57:45	-- common/autotest_common.sh@25 -- # set +x
00:04:56.906    14:57:45	-- common/autotest_common.sh@693 -- # xtrace_enable
00:04:56.906    14:57:45	-- json_config/json_config.sh@241 -- # [[ 1 -eq 1 ]]
00:04:56.906    14:57:45	-- json_config/json_config.sh@242 -- # tgt_rpc bdev_lvol_delete lvs_test/clone0
00:04:56.906    14:57:45	-- json_config/json_config.sh@36 -- # /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_lvol_delete lvs_test/clone0
00:04:57.166    14:57:45	-- json_config/json_config.sh@243 -- # tgt_rpc bdev_lvol_delete lvs_test/lvol0
00:04:57.166    14:57:45	-- json_config/json_config.sh@36 -- # /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_lvol_delete lvs_test/lvol0
00:04:57.737    14:57:46	-- json_config/json_config.sh@244 -- # tgt_rpc bdev_lvol_delete lvs_test/snapshot0
00:04:57.737    14:57:46	-- json_config/json_config.sh@36 -- # /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_lvol_delete lvs_test/snapshot0
00:04:57.737    14:57:46	-- json_config/json_config.sh@245 -- # tgt_rpc bdev_lvol_delete_lvstore -l lvs_test
00:04:57.737    14:57:46	-- json_config/json_config.sh@36 -- # /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_lvol_delete_lvstore -l lvs_test
00:04:57.998     14:57:46	-- json_config/json_config.sh@248 -- # uname -s
00:04:57.998    14:57:46	-- json_config/json_config.sh@248 -- # [[ Linux = Linux ]]
00:04:57.998    14:57:46	-- json_config/json_config.sh@249 -- # rm -f /sample_aio
00:04:57.998    14:57:46	-- json_config/json_config.sh@252 -- # [[ 0 -eq 1 ]]
00:04:57.998    14:57:46	-- json_config/json_config.sh@256 -- # timing_exit cleanup_bdev_subsystem_config
00:04:57.998    14:57:46	-- common/autotest_common.sh@697 -- # xtrace_disable
00:04:57.998    14:57:46	-- common/autotest_common.sh@20 -- # '[' no '!=' yes ']'
00:04:57.998    14:57:46	-- common/autotest_common.sh@21 -- # PREV_BASH_OPTS=hxBET
00:04:57.998    14:57:46	-- common/autotest_common.sh@22 -- # [[ hxBET == *\x* ]]
00:04:57.998    14:57:46	-- common/autotest_common.sh@23 -- # XTRACE_DISABLED=yes
00:04:57.998    14:57:46	-- common/autotest_common.sh@25 -- # set +x
00:04:57.998    14:57:46	-- common/autotest_common.sh@699 -- # xtrace_enable
00:04:57.998    14:57:46	-- json_config/json_config.sh@378 -- # killprocess 874991
00:04:57.998    14:57:46	-- common/autotest_common.sh@907 -- # '[' -z 874991 ']'
00:04:57.998    14:57:46	-- common/autotest_common.sh@911 -- # kill -0 874991
00:04:57.998     14:57:46	-- common/autotest_common.sh@912 -- # uname
00:04:57.998    14:57:46	-- common/autotest_common.sh@912 -- # '[' Linux = Linux ']'
00:04:57.998     14:57:46	-- common/autotest_common.sh@913 -- # ps --no-headers -o comm= 874991
00:04:57.998    14:57:46	-- common/autotest_common.sh@913 -- # process_name=reactor_0
00:04:57.998    14:57:46	-- common/autotest_common.sh@917 -- # '[' reactor_0 = sudo ']'
00:04:57.998    14:57:46	-- common/autotest_common.sh@925 -- # echo 'killing process with pid 874991'
00:04:57.998  killing process with pid 874991
00:04:57.998    14:57:46	-- common/autotest_common.sh@926 -- # kill 874991
00:04:57.998    14:57:46	-- common/autotest_common.sh@931 -- # wait 874991
00:05:02.196    14:57:51	-- json_config/json_config.sh@381 -- # rm -f /var/jenkins/workspace/crypto-autotest/spdk/spdk_initiator_config.json /var/jenkins/workspace/crypto-autotest/spdk/spdk_tgt_config.json
00:05:02.196    14:57:51	-- json_config/json_config.sh@382 -- # timing_exit json_config_test_fini
00:05:02.196    14:57:51	-- common/autotest_common.sh@697 -- # xtrace_disable
00:05:02.196    14:57:51	-- common/autotest_common.sh@20 -- # '[' no '!=' yes ']'
00:05:02.196    14:57:51	-- common/autotest_common.sh@21 -- # PREV_BASH_OPTS=hxBET
00:05:02.196    14:57:51	-- common/autotest_common.sh@22 -- # [[ hxBET == *\x* ]]
00:05:02.196    14:57:51	-- common/autotest_common.sh@23 -- # XTRACE_DISABLED=yes
00:05:02.196    14:57:51	-- common/autotest_common.sh@25 -- # set +x
00:05:02.196    14:57:51	-- common/autotest_common.sh@699 -- # xtrace_enable
00:05:02.196    14:57:51	-- json_config/json_config.sh@383 -- # return 0
00:05:02.196    14:57:51	-- json_config/json_config.sh@417 -- # exit 1
00:05:02.196    14:57:51	-- common/autotest_common.sh@1079 -- # trap - ERR
00:05:02.196    14:57:51	-- common/autotest_common.sh@1079 -- # print_backtrace
00:05:02.196    14:57:51	-- common/autotest_common.sh@1107 -- # [[ ehxBET =~ e ]]
00:05:02.196    14:57:51	-- common/autotest_common.sh@1109 -- # args=('/var/jenkins/workspace/crypto-autotest/spdk/test/json_config/json_config.sh' 'json_config' '/var/jenkins/workspace/crypto-autotest/autorun-spdk.conf')
00:05:02.196    14:57:51	-- common/autotest_common.sh@1109 -- # local args
00:05:02.196    14:57:51	-- common/autotest_common.sh@1111 -- # xtrace_disable
00:05:02.196    14:57:51	-- common/autotest_common.sh@20 -- # '[' no '!=' yes ']'
00:05:02.196    14:57:51	-- common/autotest_common.sh@21 -- # PREV_BASH_OPTS=ehxBET
00:05:02.196    14:57:51	-- common/autotest_common.sh@22 -- # [[ ehxBET == *\x* ]]
00:05:02.196    14:57:51	-- common/autotest_common.sh@23 -- # XTRACE_DISABLED=yes
00:05:02.196    14:57:51	-- common/autotest_common.sh@25 -- # set +x
00:05:02.196  ========== Backtrace start: ==========
00:05:02.196  
00:05:02.196  in /var/jenkins/workspace/crypto-autotest/spdk/test/common/autotest_common.sh:1079 -> run_test(["json_config"],["/var/jenkins/workspace/crypto-autotest/spdk/test/json_config/json_config.sh"])
00:05:02.196       ...
00:05:02.196     1074		timing_enter $test_name
00:05:02.196     1075		echo "************************************"
00:05:02.196     1076		echo "START TEST $test_name"
00:05:02.196     1077		echo "************************************"
00:05:02.196     1078		xtrace_restore
00:05:02.196     1079		time "$@"
00:05:02.196     1080		xtrace_disable
00:05:02.196     1081		echo "************************************"
00:05:02.196     1082		echo "END TEST $test_name"
00:05:02.196     1083		echo "************************************"
00:05:02.196     1084		timing_exit $test_name
00:05:02.196       ...
00:05:02.196  in /var/jenkins/workspace/crypto-autotest/spdk/autotest.sh:164 -> main(["/var/jenkins/workspace/crypto-autotest/autorun-spdk.conf"])
00:05:02.196       ...
00:05:02.196     159 		timing_enter lib
00:05:02.196     160 	
00:05:02.196     161 		run_test "env" $rootdir/test/env/env.sh
00:05:02.196     162 		run_test "rpc" $rootdir/test/rpc/rpc.sh
00:05:02.196     163 		run_test "rpc_client" $rootdir/test/rpc_client/rpc_client.sh
00:05:02.196  => 164 		run_test "json_config" $rootdir/test/json_config/json_config.sh
00:05:02.196     165 		run_test "json_config_extra_key" $rootdir/test/json_config/json_config_extra_key.sh
00:05:02.196     166 		run_test "alias_rpc" $rootdir/test/json_config/alias_rpc/alias_rpc.sh
00:05:02.196     167 		run_test "spdkcli_tcp" $rootdir/test/spdkcli/tcp.sh
00:05:02.196     168 		run_test "dpdk_mem_utility" $rootdir/test/dpdk_memory_utility/test_dpdk_mem_info.sh
00:05:02.196     169 		run_test "event" $rootdir/test/event/event.sh
00:05:02.196       ...
00:05:02.196  
00:05:02.196  ========== Backtrace end ==========
```

**Comment by spdkci** [comment] 2023-06-05 15:19
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_105583.html

**Comment by mikeBashStuff** [comment] 2023-06-05 16:40
Potential workaround: https://review.spdk.io/gerrit/c/spdk/spdk/+/18526. From both reports it looks like the lvol related notifications were reported out of order (other than that, the expected list was complete). So the question is if it's expected. Is there any async action involved that would cause similar discrepancy?

**Comment by mikeBashStuff** [comment] 2023-06-05 16:42
> Potential workaround: https://review.spdk.io/gerrit/c/spdk/spdk/+/18526. From both reports it looks like the lvol related notifications were reported out of order (other than that, the expected list was complete). So the question is if it's expected. Is there any async action involved that would cause similar discrepancy?

Other than that, it's quite hard to reproduce under the current master, even on the same systems that got hit by this issue (I have been spinning this test for quite some time now and this issue hasn't surfaced yet).

**Comment by spdkci** [comment] 2023-06-07 06:33
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_105684.html

**Comment by ksztyber** [comment] 2023-06-07 06:57
> Potential workaround: https://review.spdk.io/gerrit/c/spdk/spdk/+/18526. From both reports it looks like the lvol related notifications were reported out of order (other than that, the expected list was complete). So the question is if it's expected. Is there any async action involved that would cause similar discrepancy?

I'm no lvol expert, but creating an asynchronous operation, so I don't think we should be relying on that order. In other words, I think your patch isn't a workaround, but actually fixes this issue.

**Comment by mikeBashStuff** [comment] 2023-06-07 07:54
Patch merged, closing.

**Closed by mikeBashStuff** 2023-06-07 07:54 UTC
Labels: Intermittent Failure
