### ISSUE TITLE
vhost: recvmsg failed message when disconnecting vhost-user client

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1038] opened 2019-11-06 19:46 UTC
Start SPDK target:
app/spdk_tgt/spdk_tgt

Configure vhost controller:
scripts/rpc.py bdev_malloc_create 128 512 --name malloc0
scripts/rpc.py vhost_create_blk_controller vhost0 malloc0

Start bdevperf (and wait for RPCs with -z option):
test/bdev/bdevperf/bdevperf -q 1 -o 4096 -w randread -t 1 --single-file-segments -m 0x10 -z -r /var/tmp/bdevperf.sock

Configure and start bdevperf test:
scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_virtio_attach_controller -t user -a vhost0 -d blk virtio0
PYTHONPATH=scripts/ test/bdev/bdevperf/bdevperf.py -s /var/tmp/bdevperf.sock perform_tests

Stop bdevperf:
scripts/rpc.py -s /var/tmp/bdevperf.sock spdk_kill_instance SIGTERM

spdk_tgt output will show:
VHOST_CONFIG: recvmsg failed

**Comment by Donaim** [comment] 2019-11-08 12:55
Reproduces even without any IO movement
I will investigate what is the cause of this message

**Comment by peluse** [comment] 2020-01-06 22:43
@Donaim did you ever get a chance to look at this?

**Comment by Donaim** [comment] 2020-01-08 16:02
@peluse I didn't spend much time on this because it seems that this behaviour was not impacting the host other than by printing a warning, but I will investigate more this week and try to fix it

**Comment by Donaim** [comment] 2020-01-10 17:11
I did more research and comfirmed that this message does not impact behaviour, but it is a bug in DPDK rte_vhost code. I will submit a patch to DPDK shortly and update here. Don't think there is anything to do in SPDK code to prevent this message from showing up.

So the issue is function that accepts client messages using `recvmsg`: https://github.com/DPDK/dpdk/blob/a02b9406a8769247737b55dbfa50b6b5f896d946/lib/librte_vhost/socket.c#L129 
It assumes that 0 bytes returned from socket read request is an error, which is false because it is [specified](https://linux.die.net/man/2/recvmsg) as expected behaviour of `recvmsg`  when client disconnects **and** there is no requirements in other parts of rte_vhost to treat that empty message as error - the only caller of `recvmsg` in question is from [this part of the code](https://github.com/DPDK/dpdk/blob/a02b9406a8769247737b55dbfa50b6b5f896d946/lib/librte_vhost/vhost_user.c#L2610) that treats "0" as ordinary peer disconnect.

**Comment by changpe1** [comment] 2020-01-13 01:40
@Donaim That's the right fix, connection was terminated from client, this should not be treated as an error log.

**Comment by Donaim** [comment] 2020-01-31 11:05
I submitted the fix: http://patches.dpdk.org/patch/65355/

**Comment by spdkci** [comment] 2020-02-08 13:22
Another instance of this failure. Reported by @Comphix. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60143.html

**Comment by Donaim** [comment] 2020-02-26 10:41
My fix was accepted and merged to DPDK
Adding it to our fork as well: https://review.spdk.io/gerrit/c/spdk/dpdk/+/1014

**Comment by darsto** [comment] 2020-03-17 09:17
It was merged to our spdk-19.11 branch and I just pushed a patch to move our dpdk submodule:
https://review.spdk.io/gerrit/c/spdk/spdk/+/1326

**Comment by darsto** [comment] 2020-05-11 08:58
Merged.

**Closed by darsto** 2020-05-11 08:58 UTC
Labels: 3rd party issue
