### ISSUE TITLE
iSCSI: *ERROR*: Not found task for transfer_tag=3ef

### ISSUE THREAD

**Issue by darsto** [spdk/spdk#715] opened 2019-03-15 08:12 UTC
This is a fairly rare intermittent failure on our CI.

```
 12:00:38	# [...]/scripts/rpc.py destroy_raid_bdev raid0
iscsi.c:4140:spdk_iscsi_op_data: *ERROR*: Not found task for transfer_tag=3ef
iscsi.c:4140:spdk_iscsi_op_data: *ERROR*: Not found task for transfer_tag=3ef 
```

full log here: https://ci.spdk.io/spdk-jenkins/results/autotest-per-patch/builds/25675/archive/RBD_autotest/build.log

**Comment by shuhei-matsumoto** [comment] 2019-03-18 11:15
@darsto  Thank you for finding this issue. I assign me.

**Comment by changpe1** [comment] 2019-03-21 02:07
From what I saw from the log, the failed was due to timeout but not the error log showed in the text "Not found task for transfer_tag=3ef", it showed "kill process" and "wait process" timeout, I assume it's a common issue for hotplug tests.

**Comment by changpe1** [comment] 2019-03-21 04:42
[Bug Scrub]: Maybe we can put some debug information when got KILL signal to see what happened.

**Comment by darsto** [comment] 2019-03-22 09:37
Another intermittent failure with some more logs:
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/26636/archive/RBD_autotest/build.log

**Comment by shuhei-matsumoto** [comment] 2019-03-24 22:36
Thank you @darsto .

I want to add a timeout mechanism to exit connection because we can't know why iSCSI target can't complete it.
- FIO doesn't stop I/O ?
- Bdev doesn't complete I/O ?
- or any other reason ?

Set iSCSI timeout shorter than RPC timeout and collect detailed logs when iSCSI timeout occurs may be a step to go forward. I want to do it first.

**Comment by shuhei-matsumoto** [comment] 2019-04-04 08:09
@darsto 

Finally I started to read logs in detail. It looks that all logs have the same pattern, create a raid bdev on top of two malloc bdevs.

Deleting the raid bdev and the first malloc bdev completed successfully, but deleting the second malloc bdev didn't complete within 20 seconds.

As you already reviewed, I added a few patches for iSCSI and SCSI. Now I'm investigating bdev layer and malloc bdev module.

On the other hand, #725 looks that iSCSI management task doesn't complete.

I will investigate further.

**Comment by shuhei-matsumoto** [comment] 2019-04-04 09:03
@darsto 

It is suspected that hot removal of an LUN on top of the malloc 1 doesn't complete. I hope my patches to dump the state will catch the state. So as you already did, further review will be very appreciated. On the other hand, I'll try to reproduce the issue locally.

Thanks,
Shuhei

**Comment by shuhei-matsumoto** [comment] 2019-04-05 06:45
@darsto 

I noticed that destroy_raid_bdev (for hot removal of raid bdev in this case) doesn't wait for completion. So I'm developing a patch to have destroy_raid_bdev wait for completion like other bdev modules.
I hope I can post the patch soon.

**Comment by shuhei-matsumoto** [comment] 2019-04-09 01:29
I think current implementation of destruction operation of raid bdev module is not good.

Some critical points are
*  destroy_raid_bdev RPC doesn't wait for completion of spdk_bdev_unregister.
*  spdk_io_device_unregister is called without waiting that all open descriptors to the raid bdev are closed.

I submitted patch series starting from https://review.gerrithub.io/#/c/spdk/spdk/+/450563/.

I hope this patch series fix the issue at the best but hope this patch makes our investigation go forward at least.

**Comment by shuhei-matsumoto** [comment] 2019-04-09 10:04
As long as I have worked on this issue, the patch series is sufficiently likely to be the fix. I submitted two patches for data collection but they will not be valuable even if being merged. So it will be nice if we can monitor how the test CI goes with possible fix.

**Comment by jimharris** [comment] 2019-05-10 03:55
https://10.102.17.104:8080/job/RBD_BlobFS_tests/job/RBD_autotest/25283/artifact/build.log

Is this test failure related?  It looks the same.

**Comment by shuhei-matsumoto** [comment] 2019-05-10 04:08
@jimharris Will you conver the URL to the public one?

**Comment by jimharris** [comment] 2019-05-10 04:17
Sorry @shuhei-matsumoto.  Please try this link:  https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_30756.html

**Comment by shuhei-matsumoto** [comment] 2019-05-10 04:38
Thank you @jimharris This looks same. I'll investigate it.

**Comment by shuhei-matsumoto** [comment] 2019-05-10 05:56
@jimharris I posted a fix for this issue. https://review.gerrithub.io/#/c/spdk/spdk/+/453959/

Probably the root cause is as follows:

Patch series for RAID bdev to make destroy_raid_bdev wait for its completion was helpful.
I saw removing raid0 caused timeout when the configuration was that raid0 is on malloc0 and malloc1.
And incoming I/Os from the host didn't stop.

I added "Fixes #715" in the commit message but I haven't verified this issue was fixed locally.
So of course removing "Fixes #715" from the commit message and monitoring CI is fine.

Anyway thank you for your help.

**Comment by jimharris** [comment] 2019-05-10 06:03
Hi Shuhei,

Good catch!  I posted a comment on your patch - I think there may be a way to simplify it a bit.

-Jim

**Comment by shuhei-matsumoto** [comment] 2019-05-10 08:18
Hi Jim,

Thank you for nice suggestion. I update the patch based on it. It will work well.

**Comment by jimharris** [comment] 2019-05-13 15:39
Patch merged.

**Comment by shuhei-matsumoto** [comment] 2019-05-15 03:34
Sorry, we still see the issue.

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/31246/archive/RBD_autotest/build.log

**Comment by jimharris** [comment] 2019-05-22 23:14
I think this patch helps fix part of this issue:  https://review.gerrithub.io/c/spdk/spdk/+/455454

But after applying this patch, I now hit a consistent segfault in the hotplug path.  Still investigating.

**Comment by jimharris** [comment] 2019-05-22 23:58
https://review.gerrithub.io/c/spdk/spdk/+/455460 plus 455454 above I think will fix this.

Note that the transfer_tag error messages themselves are relatively harmless.  We may even consider removing them, or make them a debug log.  What I think is happening is that we get a large write, send a bunch of R2Ts to the initiator, and then the LUN gets hot removed and we delete the transfer task internally.  Then when the initiator actually sends the DataOut PDUs in response to those R2Ts, we print the error since we deleted our reference to that transfer task.

Probably the cleaner way to handle this would be to wait until we get all of the DataOut PDUs, fail them, and only then do we clean up the transfer task.

**Comment by shuhei-matsumoto** [comment] 2019-05-23 00:15
@jimharris 

Thank you! Two patches look good to me, but ordering should be swapped? The second one should come first? Also I found an unrelated change (remove white space). So I swapped the ordering and remove the change. Please restore the original ordering if needed.

**Comment by shuhei-matsumoto** [comment] 2019-05-23 00:43
And waiting for remaining Data Out PDUs from the initiator may require timeout feature. So changing the error log to debug log may be the practical next step. I'm positive for your idea though.

**Comment by jimharris** [comment] 2019-05-23 14:27
Yes - you are right of course @shuhei-matsumoto.  Thanks for swapping the ordering and fixing up the unrelated whitespace change.  I've also just pushed some additional fixes to the commit messages.

**Comment by shuhei-matsumoto** [comment] 2019-05-29 04:47
Probable fixes are merged. We will reopen if reproduced.

**Closed by shuhei-matsumoto** 2019-05-29 04:47 UTC
Labels: Medium, bug
