### ISSUE TITLE
NVMf FIO test failed to shutdown because /run/dpdk/spdk0 is still open.

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1248] opened 2020-03-02 00:57 UTC
https://ci.spdk.io/results/autotest-per-patch/builds/5184/archive/nvmf-tcp-autotest/build.log

```
========== Backtrace end ==========
  01:28:10	# xtrace_enable
  01:28:10	# return 0

real	2m44.245s
user	9m55.211s
sys	0m34.807s
 01:28:10	# process_core
 01:28:10	# ret=0
 01:28:10	# IFS=
 01:28:10	# read -r -d '' core
  01:28:10	# find . -type f '(' -name 'core\.?[0-9]*' -o -name '*.core' ')' -print0
 01:28:10	# return 0
 01:28:10	# autotest_cleanup
 01:28:10	# /var/jenkins/workspace/nvmf-tcp-autotest/spdk/scripts/setup.sh reset
0000:00:04.0 (8086 5845): uio_pci_generic -> nvme
0000:00:0b.0 (1d1d 1f1f): Skipping un-whitelisted NVMe controller 
0000:00:0a.0 (1af4 1001): uio_pci_generic -> virtio-pci
0000:00:09.0 (1af4 1004): uio_pci_generic -> virtio-pci
 01:28:11	# /var/jenkins/workspace/nvmf-tcp-autotest/spdk/scripts/setup.sh cleanup
Cleaning
Still open: /run/dpdk/spdk0/config
Still open: /run/dpdk/spdk0/fbarray_memseg-2048k-0-0
Still open: /run/dpdk/spdk0/fbarray_memseg-2048k-0-1
Still open: /run/dpdk/spdk0/fbarray_memseg-2048k-0-2
Still open: /run/dpdk/spdk0/fbarray_memseg-2048k-0-3
Still open: /run/dpdk/spdk0/fbarray_memzone
Removing:    /run/dpdk/spdk0/hugepage_info
Removing:    /run/dpdk/spdk0/mp_socket
Removing:    /run/dpdk/spdk1/config
Removing:    /run/dpdk/spdk1/fbarray_memseg-2048k-0-0
Removing:    /run/dpdk/spdk1/fbarray_memseg-2048k-0-1
Removing:    /run/dpdk/spdk1/fbarray_memseg-2048k-0-2
Removing:    /run/dpdk/spdk1/fbarray_memseg-2048k-0-3
Removing:    /run/dpdk/spdk1/fbarray_memzone
Removing:    /run/dpdk/spdk1/hugepage_info
Removing:    /run/dpdk/spdk1/mp_socket
Removing:    /run/dpdk/spdk2/config
Removing:    /run/dpdk/spdk2/fbarray_memseg-2048k-0-0
Removing:    /run/dpdk/spdk2/fbarray_memseg-2048k-0-1
Removing:    /run/dpdk/spdk2/fbarray_memseg-2048k-0-2
Removing:    /run/dpdk/spdk2/fbarray_memseg-2048k-0-3
Removing:    /run/dpdk/spdk2/fbarray_memzone
Removing:    /run/dpdk/spdk2/hugepage_info
Removing:    /run/dpdk/spdk2/mp_socket
Removing:    /run/dpdk/spdk3/config
Removing:    /run/dpdk/spdk3/fbarray_memseg-2048k-0-0
Removing:    /run/dpdk/spdk3/fbarray_memseg-2048k-0-1
Removing:    /run/dpdk/spdk3/fbarray_memseg-2048k-0-2
Removing:    /run/dpdk/spdk3/fbarray_memseg-2048k-0-3
Removing:    /run/dpdk/spdk3/fbarray_memzone
Removing:    /run/dpdk/spdk3/hugepage_info
Removing:    /run/dpdk/spdk3/mp_socket
Removing:    /run/dpdk/spdk4/config
Removing:    /run/dpdk/spdk4/fbarray_memseg-2048k-0-0
Removing:    /run/dpdk/spdk4/fbarray_memseg-2048k-0-1
Removing:    /run/dpdk/spdk4/fbarray_memseg-2048k-0-2
Removing:    /run/dpdk/spdk4/fbarray_memseg-2048k-0-3
Removing:    /run/dpdk/spdk4/fbarray_memzone
Removing:    /run/dpdk/spdk4/hugepage_info
Removing:    /run/dpdk/spdk4/mp_socket
Still open: /dev/shm/nvmf_trace.0
Removing:    /var/run/dpdk/spdk0
rmdir: failed to remove '/var/run/dpdk/spdk0': Directory not empty
Process leaked file descriptors. See https://jenkins.io/redirect/troubleshooting/process-leaked-file-descriptors for more information
Build step 'Execute shell' marked build as failure
[PostBuildScript] - [INFO] Executing post build scripts.
[nvmf-tcp-autotest] $ /usr/bin/env bash /tmp/jenkins7787916175089
```733352.sh

**Comment by spdkci** [comment] 2020-03-02 01:00
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_5184.html

**Comment by spdkci** [comment] 2020-03-02 07:12
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_5203.html

**Comment by jimharris** [comment] 2020-03-05 04:23
Bug scrub: assigning to @changpe1 for further analysis

**Comment by spdkci** [comment] 2020-03-05 05:58
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_5598.html

**Comment by optimistyzy** [comment] 2020-03-09 05:26
Related with the checksum, when testing fio with plugin: examples/nvme/fio_plugin/mock_sgl_config.fio

 03:43:00	# asan_lib=
 03:43:00	# LD_PRELOAD=' /var/jenkins/workspace/nvmf-tcp-autotest/spdk/examples/nvme/fio_plugin/fio_plugin'
 03:43:00	# /usr/src/fio/fio /var/jenkins/workspace/nvmf-tcp-autotest/spdk/examples/nvme/fio_plugin/mock_sgl_config.fio '--filename=trtype=tcp adrfam=IPv4 traddr=127.0.0.1 trsvcid=4420 ns=1'
test: (g=0): rw=randrw, bs=(R) 16.0KiB-16.0KiB, (W) 16.0KiB-16.0KiB, (T) 16.0KiB-16.0KiB, ioengine=spdk, iodepth=128
fio-3.15
Starting 1 thread
Starting SPDK v20.01.1-pre git sha1 8842d8d2d / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid909574 ]
EAL: No available hugepages reported in hugepages-1048576kB
verify: bad header rand_seed 5525354256175058256, wanted 959627741899344 at file trtype=tcp adrfam=IPv4 traddr=127.0.0.1 trsvcid=4420 ns=1 offset 11206656, length 16384 (requested block: offset=11206656, length=16384)
verify: bad header rand_seed 1859088540537858825, wanted 5525354256175058256 at file trtype=tcp adrfam=IPv4 traddr=127.0.0.1 trsvcid=4420 ns=1 offset 42270720, length 16384 (requested block: offset=42270720, length=16384)
fio: pid=909605, err=84/file:io_u.c:2068, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character

**Comment by optimistyzy** [comment] 2020-03-09 06:58
In my mind, though it prints the following issue.
"rmdir: failed to remove '/var/run/dpdk/spdk0': Directory not empty
Process leaked file descriptors. See https://jenkins.io/redirect/troubleshooting/process-leaked-file-descriptors for more information
Build step 'Execute shell' marked build as failure"

But actually, there are different cases fail, so it cause this issue.

**Comment by spdkci** [comment] 2020-03-15 14:14
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_6387.html

**Comment by AlekseyMarchuk** [comment] 2020-03-16 05:43
> Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_6387.html

This failure was not "false positive", it was caused by my patch

**Comment by spdkci** [comment] 2020-03-23 03:16
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_7398.html

**Comment by AlekseyMarchuk** [comment] 2020-06-02 07:29
No reports for several months, suggest closing it

**Closed** 2020-06-02 13:20 UTC
Labels: Bug Scrub, Intermittent Failure
