### ISSUE TITLE
Fio Reports High(er) Latency for Queue Depth >= 4 Due to Latency Accounting

### ISSUE THREAD

**Issue by ashmrtn** [spdk/spdk#920] opened 2019-08-20 04:20 UTC
## Expected Behavior
SPDK with an NVMe SSD should have lower/similar latency compared to Ext4 on the same NMVe drive (running with the sync ioengine in fio) when the queue depth is >= 4.

## Current Behavior
When running the spdk fio_plugin, a near linear relationship between request latency and queue depth holds, which is in contrast to the sync ioengine's near constant latency with increasing queue depth. For queue depths >= 4 on some SSDs, it appears that sync/Ext4 has a lower latency than SPDK on the same SSD.

## Possible Solution
Allow the fio_plugin to use multiple threads so that fio can run in offload mode. According to fio, this should use a separate thread to poll for IO completions instead of the current system that checks for completions only when the IO queue has been filled to the specified depth. The sync/Ext4 setup also has an advantage in fio because it is considered synchronous so it's latency is calculated as soon as the syscall finishes.

## Steps to Reproduce
1. Run sequential write workload in fio using fio_plugin either for nvme or bdev on a fast SSD with a queue depth of 4 or greater (higher queue depths will most likely to show the sync ioengine as faster even if the SSD is not as fast)
2. Run the same sequential write workload and queue depth on the same device, but this time with the sync ioengine
3. Compare latencies form the SPDK fio_plugin and the sync ioengine, the sync ioengine should have lower latency than SPDK

## Context (Environment including OS version, SPDK version, etc.)
OS: Ubuntu 18.04.2
SPDK commit: 30ff7f7
fio: 3.3 (as noted in the README for the fio_plugin)

**Comment by benlwalker** [comment] 2019-08-20 18:01
Real SSDs scale linearly with increasing queue depth, especially for writes (there is additional drive-level parallelism for reads, typically). This isn't SPDK causing this scaling - that's the expected behavior of the hardware.

I'm fairly confident that using queue depth > 1 with the sync engine in fio is giving you nonsense results. The sync calls are synchronous, meaning they block. I believe it does these calls inside of the submit_io function to the engine, which is where it also starts to track the latency. So even if you set queue depth > 1 with that engine, you're only doing queue depth of 1 and the latency reported is for queue depth 1. That's why it doesn't ramp up linearly.

Also, are you running in direct mode or is the page cache enabled? If you have the page cache turned on for ext4, then it will certainly be faster because you're just doing a memcpy to RAM and it will flush in the background sometime later in a way that is measured by fio.

**Comment by ashmrtn** [comment] 2019-08-22 23:37
I understand that an SSD is going to have some scaling in latency as the number of requests queued gets larger, but the overhead that fio is adding by queuing all requests for a depth before checking for _any_ completions is adding more time to the latency than the actual latency of a single request.

I also get that only 1 request is ever really "queued" for the sync ioengine because of the fact that it is, well, synchronous. The fact is though that even doing an fsync after every IO (and accounting for fsync latency), fio will report the average latency of spdk with a queue of 4+ as higher than ext4 doing fsync after every write. This is especially confusing as the workload is sequential appends to a file, so every fsync will force out roughly 6x data in ext4 compared to spdk (ext4 journal header, journal commit, journal inode as the file size changed, data block, and inode table inode in-place update).

I modified fio to account for sync/ext4 completions in the same way that it accounts for spdk completions (basically, mark a request as queued and when `getevents()` is called, tell it all the requests since the last call to `getevents()` are done). I then ran fio with sync/ext4, my modified fio with sync/ext4, and spdk, all with the same NVMe SSD as the storage device. The plot below shows the average latency over several million requests for different queue depths in the setups described above.

![bench-slowdown](https://user-images.githubusercontent.com/3891298/63552816-99509880-c4ed-11e9-8885-9ea1bbbb69a5.png)

**Comment by jimharris** [comment] 2020-01-14 00:44
Hi @ashmrtn,

This issue seems like it's specific to fio accounting - not anything with the SPDK fio plugin itself.  

Closing this issue - we can continue to discuss on this thread however.

-Jim

**Closed by jimharris** 2020-01-14 00:44 UTC
Labels: question

**Comment by optimistyzy** [comment] 2020-01-14 04:20
One thing may not be quite related with this. For NVMe SSD sequential test, there is multiple threads test for sequential writes. Because if you use multiple threads (each thread still conducts sequential writes), when the requests are sent to NVMe SSDs, the I/Os from become rand writes from the firmware view in the controller.

**Comment by ashmrtn** [comment] 2020-01-14 15:57
I agree that using multiple threads for submitting IO will change the results (though they may be useful for benchmarking different sorts of situations). However, what I was suggesting that the fio plugin enable multiple threads specifically so that it could be run in offload mode, which has a different way of checking for completions. In that mode, one thread is responsible for submitting IO and another is responsible for checking for the completions. This method won't inflate the latency of some requests because it does not attempt to fill the request queue prior to checking for *any* completions. 

For example, if the request queue depth is set to 4k and a single request only takes 15us, going through a for loop 4095 more times to submit other IO can inflate the latency of the first request because we are working with such small time scales.
