### ISSUE TITLE
Cannot save configuration with IOAT accel module enabled

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#3251] opened 2024-02-02 12:26 UTC
# Sighting report

Cannot save configuration with IOAT accel module enabled.
Saved configuration file does not contain "ioat_scan_accel_module" method entry.

## Expected Behavior

Configuration should be saved.

## Current Behavior

As in description.

## Steps to Reproduce

1. Start SPDK Target, configure IOAT accel and a Malloc bdev.
```
[klateck@eagle2 spdk]$ sudo build/bin/spdk_tgt --wait-for-rpc &
[1] 1566964
[klateck@eagle2 spdk]$ [2024-02-02 11:19:14.410931] Starting SPDK v24.05-pre git sha1 158d15b74 / DPDK 23.11.0 initialization...
[2024-02-02 11:19:14.411123] [ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --huge-unlink --no-telemetry --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid1566966 ]
EAL: No free 2048 kB hugepages reported on node 1
[2024-02-02 11:19:14.503040] app.c: 798:spdk_app_start: *NOTICE*: Total cores available: 1
[2024-02-02 11:19:14.609789] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 0

[klateck@eagle2 spdk]$ sudo -E ./scripts/rpc.py ioat_scan_accel_module
[2024-02-02 11:19:18.623730] accel_ioat_rpc.c:  22:rpc_ioat_scan_accel_module: *NOTICE*: Enabling IOAT
[klateck@eagle2 spdk]$ sudo -E ./scripts/rpc.py framework_start_init
[klateck@eagle2 spdk]$ sudo -E ./scripts/rpc.py bdev_malloc_create 10 4096
Malloc0
```
2. Save running configuration
```
[klateck@eagle2 spdk]$ sudo -E ./scripts/rpc.py save_config > /tmp/test
```
3. Check if it contains `"ioat_scan_accel_module"` entry
```
[klateck@eagle2 spdk]$ cat /tmp/test | jq -r '.subsystems[] | select(.subsystem=="accel")'
{
  "subsystem": "accel",
  "config": [
    {
      "method": "accel_set_options",
      "params": {
        "small_cache_size": 128,
        "large_cache_size": 16,
        "task_count": 2048,
        "sequence_count": 2048,
        "buf_count": 2048
      }
    }
  ]
}
```

## Context (Environment including OS version, SPDK version, etc.)

Linux eagle2 6.2.9-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Mar 30 22:31:57 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
gcc version 12.2.1 20221121 (Red Hat 12.2.1-4) (GCC) 
SPDK 158d15b7400ae9b4373cf6a6ef6c880436d09a3c

**Comment by tomzawadzki** [comment] 2024-02-06 15:22
[Bug scrub] The issue is the same as in https://github.com/spdk/spdk/issues/3161, lets track that for all modules in one issue.

**Comment by jimharris** [comment] 2024-02-06 15:31
Reopening.

#3161 and #3251 are actually very different problems.  #3161 is emitting JSON incorrectly. #3251 (this one) just isn't emitting JSON at all.

These should be fixed with two separate patches.

Assigning to @ksprzacz who is also looking at #3161.

**Closed** 2024-02-19 09:08 UTC
Labels: bug, Medium
