### ISSUE TITLE
nvme hello_world example reports error on FreeBSD

### ISSUE THREAD

**Issue by reeveyoung** [spdk/spdk#2542] opened 2022-06-06 19:54 UTC
# Bug report

## Expected Behavior
I expect the example would run correctly.

## Current Behavior
I followed the instruction to run NVMe hellow_world example, here is the output for every step.
$ sudo scripts/setup.sh
hw.nic_uio.bdfs="00:0e:0"
hw.contigmem.num_buffers="8"
hw.contigmem.buffer_size="268435456"

$ sudo scripts/gen_nvme.sh --json-with-subsystems > ./build/examples/hello_bdev.json
pciconf: cannot parse selector pci0000:00:0e:0

Though there is error message above but I checked the script it should be fine. The json file is as follows:
$ cat build/examples/hello_bdev.json
{
"subsystems": [
{
"subsystem": "bdev",
"config": [
{
"method": "bdev_nvme_attach_controller",
"params": {
"trtype": "PCIe",
"name":"Nvme0",
"traddr":"0000:00:0e.0"
}
}
]
}
]
}

$ sudo ./build/examples/hello_bdev --json ./build/examples/hello_bdev.json -b Nvme0n1
[2022-06-06 05:50:53.147731] Starting SPDK v22.09-pre git sha1 abdefd22e / DPDK 22.03.0 initialization...
[2022-06-06 05:50:53.148960] [ DPDK EAL parameters: [2022-06-06 05:50:53.150078] hello_bdev [2022-06-06 05:50:53.150457] --no-shconf [2022-06-06 05:50:53.150623] -c 0x1 [2022-06-06 05:50:53.150990] --huge-unlink [2022-06-06 05:50:53.151077] --log-level=lib.eal:6 [2022-06-06 05:50:53.151252] --log-level=lib.cryptodev:5 [2022-06-06 05:50:53.151321] --log-level=user1:6 [2022-06-06 05:50:53.151381] ]
EAL: TSC is not safe to use in SMP mode
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-06-06 05:50:53.399955] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 1
[2022-06-06 05:50:53.489569] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
[2022-06-06 05:50:53.490744] accel_engine.c: 969:sw_accel_engine_init: *NOTICE*: Accel framework software engine initialized.
[2022-06-06 05:50:53.494648] pci_event.c: 256:spdk_pci_event_listen: *ERROR*: Non-Linux does not support this operation
EAL:   0000:00:0e.0 not managed by UIO driver, skipping
EAL: Driver cannot attach the device (0000:00:0e.0)
EAL: Failed to attach device on primary process
[2022-06-06 05:50:53.495558] nvme.c: 843:nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
[2022-06-06 05:50:53.496172] bdev_nvme.c:4682:bdev_nvme_create: *ERROR*: No controller was found with provided trid (traddr: 0000:00:0e.0)
[2022-06-06 05:50:53.498682] json_config.c: 221:rpc_client_poller: *ERROR*: error response:
{
  "code": -19,
  "message": "Operation not supported by device"
}
[2022-06-06 05:50:53.499114] app.c: 693:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
[2022-06-06 05:50:53.527457] hello_bdev.c: 335:main: *ERROR*: ERROR starting application

## Steps to Reproduce

1. Compile latest code under FreeBSD, and run the example
2. Making sure virtual host has nvme controller attached.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)

OS: FreeBSD-13.1-RELEASE
SPDK Version: SPDK v22.09-pre git sha1 abdefd22e / DPDK 22.03.0

**Comment by jimharris** [comment] 2022-06-06 20:01
What does ```scripts/setup.sh status``` show on your system, after running ```scripts/setup.sh```?

**Comment by reeveyoung** [comment] 2022-06-06 20:03
Hi Jim, here is the output.
$ sudo scripts/setup.sh status
pciconf: cannot parse selector pci0000:00:0e:0
Contigmem (present)
Buffer Size: 268435456
Num Buffers: 8

NVMe devices
BDF		Vendor	Device	Driver
0000:00:0e:0	0x0000	0x0000

I/IOAT DMA
BDF		Vendor	Device	Driver

DSA DMA
BDF		Vendor	Device	Driver

IAA DMA
BDF		Vendor	Device	Driver

VMD
BDF		Vendor	Device	Driver

**Comment by mikeBashStuff** [comment] 2022-06-06 21:11
The output of the `pciconf` here is not what the caching function actually expects hence the issue with `{vendor,device}` ids. There are some other minor issues with how pci addresses returned by the `pciconf` are interpreted. I will take a look into fixing it.

In the meantime, @reeveyoung would you kindly provide full output from the `pciconf -l; freebsd-version`?

**Comment by jimharris** [comment] 2022-06-06 21:27
Did something break/change w/ pciconf on FreeBSD 13?  I was just looking at one of our FreeBSD CI logs, it is using FreeBSD 12.3.  I don't see pciconf complaining about the 4 digit PCI domain number (pci0000) there:

```
00:01:32.521  + /usr/local/bin/ssh -t -F ssh_conf vagrant@vagrant uname -a
00:01:32.521  FreeBSD freebsd-cloud-1644288444-798.local 12.3-RELEASE FreeBSD 12.3-RELEASE r371126 GENERIC  amd64
00:01:32.534  [Pipeline] sh
00:01:32.815  + /usr/local/bin/ssh -t -F ssh_conf vagrant@vagrant sudo spdk_repo/spdk/scripts/setup.sh status
00:01:33.075  Contigmem (not present)
00:01:33.075  Buffer Size: not set
00:01:33.075  Num Buffers: not set
00:01:33.075  
00:01:33.075  NVMe devices
00:01:33.075  BDF		Vendor	Device	Driver
00:01:33.075  0000:00:06:0	0x1b36	0x0010	nvme0
00:01:33.075  
00:01:33.075  I/IOAT DMA
00:01:33.075  BDF		Vendor	Device	Driver
00:01:33.075  
00:01:33.075  DSA DMA
00:01:33.075  BDF		Vendor	Device	Driver
00:01:33.075  
00:01:33.075  IAA DMA
00:01:33.075  BDF		Vendor	Device	Driver
00:01:33.075  
00:01:33.075  VMD
00:01:33.075  BDF		Vendor	Device	Driver
```

**Comment by mikeBashStuff** [comment] 2022-06-06 21:37
@jimharris The problem is with converting different parts of the address to hexadecimal. Under 12.3 same problem exists:

```
root@freebsd-cloud-8686:~/spdk# pciconf -l pci0:0:6:0
nic_uio0@pci0:0:6:0:    class=0x010802 card=0x11001af4 chip=0x00101b36 rev=0x02 hdr=0x00
root@freebsd-cloud-8686:~/spdk# pciconf -l pci0:0:14:0 # device doesn't exist, but parser doesn't complain
root@freebsd-cloud-8686:~/spdk# pciconf -l pci0:0:0e:0 # here it does complain
pciconf: cannot parse selector pci0:0:0e:0
```
Apparently, every part of the pci address is interpreted as decimal (which is surprising to me).

**Comment by jimharris** [comment] 2022-06-06 21:42
> @jimharris The problem is with converting different parts of the address to hexadecimal. Under 12.3 same problem exists:
> 
> ```
> root@freebsd-cloud-8686:~/spdk# pciconf -l pci0:0:6:0
> nic_uio0@pci0:0:6:0:    class=0x010802 card=0x11001af4 chip=0x00101b36 rev=0x02 hdr=0x00
> root@freebsd-cloud-8686:~/spdk# pciconf -l pci0:0:14:0 # device doesn't exist, but parser doesn't complain
> root@freebsd-cloud-8686:~/spdk# pciconf -l pci0:0:0e:0 # here it does complain
> pciconf: cannot parse selector pci0:0:0e:0
> ```
> 
> Apparently, every part of the pci address is interpreted as decimal (which is surprising to me).

Makes sense now.  Reading the pciconf man page, these are always interpreted as base-10, with no option to interpret as hex instead.  Very unfortunate.

**Comment by mikeBashStuff** [comment] 2022-06-06 22:46
I think this should do the trick: https://review.spdk.io/gerrit/c/spdk/spdk/+/12914 (tested under 12.3). @reeveyoung Would you kindly test it on your end 13.1? I will do the same, just need to build myself 13.1 VM.

**Comment by reeveyoung** [comment] 2022-06-07 02:40
> The output of the `pciconf` here is not what the caching function actually expects hence the issue with `{vendor,device}` ids. There are some other minor issues with how pci addresses returned by the `pciconf` are interpreted. I will take a look into fixing it.
> 
> In the meantime, @reeveyoung would you kindly provide full output from the `pciconf -l; freebsd-version`?

Sorry for late reply, I was out for a while.

Here is the output you requested.

$ pciconf -l
hostb0@pci0:0:0:0:	class=0x060000 rev=0x02 hdr=0x00 vendor=0x8086 device=0x1237 subvendor=0x0000 subdevice=0x0000
isab0@pci0:0:1:0:	class=0x060100 rev=0x00 hdr=0x00 vendor=0x8086 device=0x7000 subvendor=0x0000 subdevice=0x0000
atapci0@pci0:0:1:1:	class=0x01018a rev=0x01 hdr=0x00 vendor=0x8086 device=0x7111 subvendor=0x0000 subdevice=0x0000
vgapci0@pci0:0:2:0:	class=0x030000 rev=0x00 hdr=0x00 vendor=0x15ad device=0x0405 subvendor=0x15ad subdevice=0x0405
em0@pci0:0:3:0:	class=0x020000 rev=0x02 hdr=0x00 vendor=0x8086 device=0x100e subvendor=0x8086 subdevice=0x001e
none0@pci0:0:4:0:	class=0x088000 rev=0x00 hdr=0x00 vendor=0x80ee device=0xcafe subvendor=0x0000 subdevice=0x0000
pcm0@pci0:0:5:0:	class=0x040100 rev=0x01 hdr=0x00 vendor=0x8086 device=0x2415 subvendor=0x8086 subdevice=0x0000
ohci0@pci0:0:6:0:	class=0x0c0310 rev=0x00 hdr=0x00 vendor=0x106b device=0x003f subvendor=0x0000 subdevice=0x0000
intsmb0@pci0:0:7:0:	class=0x068000 rev=0x08 hdr=0x00 vendor=0x8086 device=0x7113 subvendor=0x0000 subdevice=0x0000
ehci0@pci0:0:11:0:	class=0x0c0320 rev=0x00 hdr=0x00 vendor=0x8086 device=0x265c subvendor=0x0000 subdevice=0x0000
nvme0@pci0:0:14:0:	class=0x010802 rev=0x00 hdr=0x00 vendor=0x80ee device=0x4e56 subvendor=0x0000 subdevice=0x0000

$ uname -a
FreeBSD fbsdvm 13.1-RELEASE FreeBSD 13.1-RELEASE releng/13.1-n250148-fc952ac2212 GENERIC amd64

By the way, @mikeBashStuff, I tested FreeBSD-12.3, but I got compilation issue on dpdk for some reason.
../kernel/freebsd/BSDmakefile.meson:18: *** missing separator.  Stop.

I didn't dig into it deep. I could try again.

**Comment by reeveyoung** [comment] 2022-06-07 05:12
@mikeBashStuff, the patch seems fix the script problem, now the hello_world example tries to run but hung the VM.  From console I can see some message from nic_uio about mapped memory, and the whole system is frozen after ...

**Comment by mikeBashStuff** [comment] 2022-06-07 11:41
So I have not been able to compile DPDK from the SPDK's submodule (22.03) under 13.1, but the upstream version of the DPDK (22.07) was built just fine - the submodule is most likely missing the following commit: https://github.com/DPDK/dpdk/commit/2f51bc9c27a4f1da674d66499667155663dcc419.

Also, I am afraid I didn't reproduce the hung under my setup, `hello_bdev` worked just fine (note however, that I attempted to allocate only 512MB for the contigmem (the default is 2GB) as my VM had limited resources. I would recommend to adjust it properly on your end as well). Example below with the https://review.spdk.io/gerrit/c/spdk/spdk/+/12914 on top:

```
root@freebsd-cloud-23437:~/spdk# ./scripts/setup.sh status
Contigmem (not present)
Buffer Size: 268435456
Num Buffers: 2

NVMe devices
BDF             Vendor  Device  Driver
0:0:6:0 0x1b36  0x0010  nvme0

I/IOAT DMA
BDF             Vendor  Device  Driver

DSA DMA
BDF             Vendor  Device  Driver

IAA DMA
BDF             Vendor  Device  Driver

VMD
BDF             Vendor  Device  Driver
root@freebsd-cloud-23437:~/spdk# HUGEMEM=512 ./scripts/setup.sh 
./scripts/setup.sh: line 210: hash: lsblk: not found
kldunload: can't find file nic_uio.ko
hw.nic_uio.bdfs="0:6:0"
hw.contigmem.num_buffers="2"
hw.contigmem.buffer_size="268435456"
root@freebsd-cloud-23437:~/spdk# ./build/examples/hello_bdev --json=<(./scripts/gen_nvme.sh --json-with-subsystems) -b Nvme0n1
[2022-06-07 11:15:44.238919] Starting SPDK v22.09-pre git sha1 abdefd22e / DPDK 22.07.0-rc0 initialization...
[2022-06-07 11:15:44.239424] [ DPDK EAL parameters: [2022-06-07 11:15:44.239459] hello_bdev [2022-06-07 11:15:44.239482] --no-shconf [2022-06-07 11:15:44.239504] -c 0x1 [2022-06-07 11:15:44.239540] --huge-unlink [2022-06-07 11:15:44.239575] --log-level=lib.eal:6 [2022-06-07 11:15:44.239609] --log-level=lib.cryptodev:5 [2022-06-07 11:15:44.239646] --log-level=user1:6 [2022-06-07 11:15:44.239689] ]
EAL: TSC is not safe to use in SMP mode
EAL: TSC is not invariant
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-06-07 11:15:44.349711] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 1
[2022-06-07 11:15:44.497874] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
[2022-06-07 11:15:44.546902] accel_engine.c: 969:sw_accel_engine_init: *NOTICE*: Accel framework software engine initialized.
[2022-06-07 11:15:44.550797] pci_event.c: 256:spdk_pci_event_listen: *ERROR*: Non-Linux does not support this operation
[2022-06-07 11:15:44.596128] hello_bdev.c: 250:hello_start: *NOTICE*: Successfully started the application
[2022-06-07 11:15:44.596207] hello_bdev.c: 259:hello_start: *NOTICE*: Opening the bdev Nvme0n1
[2022-06-07 11:15:44.596225] hello_bdev.c: 272:hello_start: *NOTICE*: Opening io channel
[2022-06-07 11:15:44.596587] hello_bdev.c: 167:hello_write: *NOTICE*: Writing to the bdev
[2022-06-07 11:15:44.596977] hello_bdev.c: 144:write_complete: *NOTICE*: bdev io write completed successfully
[2022-06-07 11:15:44.597013] hello_bdev.c: 111:hello_read: *NOTICE*: Reading io
[2022-06-07 11:15:44.597467] hello_bdev.c:  91:read_complete: *NOTICE*: Read string from bdev : Hello World!

[2022-06-07 11:15:44.597579] hello_bdev.c: 100:read_complete: *NOTICE*: Stopping app
root@freebsd-cloud-23437:~/spdk# ./scripts/setup.sh status
Contigmem (present)
Buffer Size: 268435456
Num Buffers: 2

NVMe devices
BDF             Vendor  Device  Driver
0:0:6:0 0x1b36  0x0010  nic_uio0

I/IOAT DMA
BDF             Vendor  Device  Driver

DSA DMA
BDF             Vendor  Device  Driver

IAA DMA
BDF             Vendor  Device  Driver

VMD
BDF             Vendor  Device  Driver
root@freebsd-cloud-23437:~/spdk# 
```

**Comment by jimharris** [comment] 2022-08-16 18:41
Closing this issue since reported issue was fixed.

@reeveyoung, if you still have problems getting the example to run under FreeBSD, please file a new issue specifically for that.  Thanks.

**Closed by jimharris** 2022-08-16 18:41 UTC
Labels: Sighting
