### ISSUE TITLE
During the perf test, the target side reboot when target side deleted target cfg.

### ISSUE THREAD

**Issue by Cindy-010** [spdk/spdk#954] opened 2019-09-10 03:06 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

1.	Create two targets on node 38 as target side in kernel way (tgt1: 416d7463-d3c2-41e4-b2f5-76df2ed3db26/4420 and tgt2: 199212f7-33d0-46c3-b362-e47a217c2c49/4421);
2.	Run perf to write data to tgt2 on node 37 in SPDK way, command: sudo ./perf -q 1 -w read -o 4096 -t 60 -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.219.4 trsvcid:4421'
3.      During the perf test, deleted target tgt2, the node 38 reboot;
4.     When the target deleted, the host will try to reconnect **in kernel way**, and the target node doesn't reboot. 
## Expected Behavior

the perf test will recovery when the target item recovery 

## Current Behavior

The node 38 reboots when the target deleted.

## Steps to Reproduce

1.	Create two targets on node 38 as target side in kernel way (tgt1: 416d7463-d3c2-41e4-b2f5-76df2ed3db26/4420 and tgt2: 199212f7-33d0-46c3-b362-e47a217c2c49/4421);
2. Run perf to write data to tgt2 in SPDK way, command: sudo ./perf -q 1 -w read -o 4096 -t 60 -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.219.4 trsvcid:4421'
3.     Deleted tgt2 configuration on node 38 during perf execution,  and the node 38 reboot automatically. 
4.

## Context (Environment including OS version, SPDK version, etc.)

Spdk version: v19.07.x
Linux version: Linux orem-dirt 4.12.14-95.19.1.17807.0

**Comment by changpe1** [comment] 2019-09-10 03:10
I agree that SPDK should have similar recovery mechanism like the kernel does.

**Comment by gwnet** [comment] 2019-09-16 10:26
> I agree that SPDK should have similar recovery mechanism like the kernel does.

hello buddy, SPDK currently does not have self recovery for sure. but kernel host cannot make target node kernel panic, but SPDK can make the kernel target kernel panic. this is 100% reproduciable. I believe this is one compatible issue between SPDK host and kernel target. do Intel has any suggestion for debugging this to find the code level root cause?

**Comment by Comphix** [comment] 2019-09-17 06:24
Will discuss it in our next Bug Scrub meeting.

**Comment by Comphix** [comment] 2019-09-18 12:54
Here we also talk about some NVMe-oF host recovery mechanism. Is it similar to issue https://github.com/spdk/spdk/issues/407 ?

**Comment by Seth5141** [comment] 2019-09-19 04:24
@gwnet @Cindy-010 I am currently working on adding handling for cm events to the SPDK initiator (host). These are the events we need to handle in order to be able to recover from a disconnect like that. You can see the link here https://review.gerrithub.io/c/spdk/spdk/+/467701. Once I get the infrastructure in place, I plan on adding processing for ibv_async events as well and adding recovery steps when we lose a qpair.
I believe this set of changes will fix the recovery portion of your error.
I am interested in the portion of your issue where you get a kernel panic only when running against the spdk initiator. Can you provide some more logs from that kernel dump (dmesg, etc)?

**Comment by Cindy-010** [comment] 2019-09-19 06:20
@Seth5141 Thank you for your info, I will apply the patch for test and will update the results in here. 
And the kernel dump as you mentioned as below:
[dmesg.txt](https://github.com/spdk/spdk/files/3629684/dmesg.txt)

**Comment by jimharris** [comment] 2019-09-24 15:30
Bug scrub 09/24: Sasha has added comments to Seth's patches on GerritHub with some recommendations to better handle these types of errors.  Will continue discussion on those patches and report an update here once the patches are deemed ready for further testing by the submitter.

**Comment by Seth5141** [comment] 2019-10-09 15:52
@gwnet If you would like to test this issue against the head of my patchset mentioned on #936, I believe that the RDMA CM event handling should cover this use case. Of course, the changes I have now are still out for review and are pending approval by the rest of the community, but testing against your use cases can help us determine if it's a viable solution.
https://review.gerrithub.io/c/spdk/spdk/+/470257
Thanks!

**Comment by tomzawadzki** [comment] 2019-11-19 15:38
Bug scrub: @Cindy-010 Patches here https://review.gerrithub.io/c/spdk/spdk/+/471556 were merged, can you see if the issue still persists ?

**Comment by jimharris** [comment] 2020-02-20 05:23
Closing issue since patches were merged - please report back if you find that the issue still exists.

**Closed by jimharris** 2020-02-20 05:23 UTC
Labels: Waiting on Submitter, enhancement
