### ISSUE TITLE
CI: in test/nvmf/target/connect_disconnect.sh:35 -> main(["--transport=rdma"])

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1267] opened 2020-03-06 16:40 UTC

**Comment by spdkci** [comment] 2020-03-06 16:43
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_5804.html

**Comment by peluse** [comment] 2020-03-06 20:05
Looking at the logs a bit closer, this appears to be the start of the failure:

nvme_qpair.c: 475:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
nvme_ctrlr.c: 693:nvme_ctrlr_fail: *ERROR*: ctrlr 192.168.100.8 in failed state.
nvme_ctrlr.c:1088:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
nvme_rdma.c: 421:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_ESTABLISHED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = 28)
nvme_rdma.c: 944:nvme_rdma_connect: *ERROR*: RDMA connect error
nvme_rdma.c:1174:nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
nvme_ctrlr.c:1110:spdk_nvme_ctrlr_reset: *ERROR*: Controller reinitialization failed.
nvme_ctrlr.c: 693:nvme_ctrlr_fail: *ERROR*: ctrlr 192.168.100.8 in failed state.
bdev_nvme.c: 326:_bdev_nvme_reset_complete: *ERROR*: Resetting controller failed.

**Comment by jimharris** [comment] 2020-03-10 15:13
> Looking at the logs a bit closer, this appears to be the start of the failure:
> 
> nvme_qpair.c: 475:spdk_nvme_qpair_process_completions: _ERROR_: CQ error, abort requests after transport retry counter exceeded
> nvme_ctrlr.c: 693:nvme_ctrlr_fail: _ERROR_: ctrlr 192.168.100.8 in failed state.
> nvme_ctrlr.c:1088:spdk_nvme_ctrlr_reset: _NOTICE_: resetting controller
> nvme_rdma.c: 421:nvme_rdma_validate_cm_event: _ERROR_: Expected RDMA_CM_EVENT_ESTABLISHED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = 28)
> nvme_rdma.c: 944:nvme_rdma_connect: _ERROR_: RDMA connect error
> nvme_rdma.c:1174:nvme_rdma_ctrlr_connect_qpair: _ERROR_: Unable to connect the rqpair
> nvme_ctrlr.c:1110:spdk_nvme_ctrlr_reset: _ERROR_: Controller reinitialization failed.
> nvme_ctrlr.c: 693:nvme_ctrlr_fail: _ERROR_: ctrlr 192.168.100.8 in failed state.
> bdev_nvme.c: 326:_bdev_nvme_reset_complete: _ERROR_: Resetting controller failed.

Bug scrub: We do not see this text in the log mentioned in the original description.

**Comment by jimharris** [comment] 2020-03-10 15:14
Bug scrub: Further investigation from @tomzawadzki indicates this is a duplicate of #1227

**Closed by jimharris** 2020-03-10 15:14 UTC
Labels: Infrastructure, Intermittent Failure
