### ISSUE TITLE
nvme_perf w/ RDMA timeout 

### ISSUE THREAD

**Issue by darsto** [spdk/spdk#1283] opened 2020-03-17 08:39 UTC
No logs, errors - nothing.

```
 16:31:53	# /var/jenkins/workspace/nvmf-autotest/spdk/examples/nvme/perf/perf -q 128 -o 262144 -w randrw -M 50 -t 2 -r 'trtype:rdma adrfam:IPv4 traddr:10.102.17.186 trsvcid:4420'
Starting SPDK v20.04-pre git sha1 7ebf0a9c0 / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid1654462 ]
EAL: No available hugepages reported in hugepages-1048576kB
Build timed out (after 15 minutes). Marking the build as failed.
Build was aborted
```

**Comment by spdkci** [comment] 2020-03-17 08:40
Another instance of this failure. Reported by @darsto. log: https://ci.spdk.io/public_build/autotest-per-patch_6475.html

**Comment by AlekseyMarchuk** [comment] 2020-03-17 09:06
It seems that perf froze before any network operation started since it usually prints something like `Initializing NVMe Controllers` before call to `spdk_nvme_probe` and I don't see such print in this log. Possible hang in spdk_env_init() or rte_eal_init()?

**Comment by spdkci** [comment] 2020-04-09 11:30
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_9811.html

**Comment by AlekseyMarchuk** [comment] 2020-04-09 13:54
> Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_9811.html

That was caused by my patch

**Comment by AlekseyMarchuk** [comment] 2020-05-05 07:02
I haven't investigated this problem (it requires additional logs/counters). 
There have been no occurrences of this issue for more than a month. Suggest closing it.

**Closed** 2020-05-05 15:22 UTC
Labels: Bug Scrub, Intermittent Failure
