### ISSUE TITLE
[bdev_qos_iops] Could not find io_device 0x616000005d81 after test ends

### ISSUE THREAD

**Issue by ksprzacz** [spdk/spdk#3220] opened 2023-12-21 22:46 UTC
# CI Intermittent Failure

spdk_for_each_channel() fails after bdev_qos_iops test ends.

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/114355/archive/ubuntu20-vg-autotest_61106/build.log

## Execution failed at

00:13:01.224  ************************************
00:13:01.224  START TEST bdev_qos_iops
00:13:01.224  ************************************
00:13:01.224   16:04:24	-- common/autotest_common.sh@1084 -- # run_qos_test 16000 IOPS Malloc_0
00:13:01.224   16:04:24	-- bdev/blockdev.sh@387 -- # local qos_limit=16000
00:13:01.224   16:04:24	-- bdev/blockdev.sh@388 -- # local qos_result=0
00:13:01.224    16:04:24	-- bdev/blockdev.sh@390 -- # get_io_result IOPS Malloc_0
00:13:01.224    16:04:24	-- bdev/blockdev.sh@373 -- # local limit_type=IOPS
00:13:01.224    16:04:24	-- bdev/blockdev.sh@374 -- # local qos_dev=Malloc_0
00:13:01.224    16:04:24	-- bdev/blockdev.sh@375 -- # local iostat_result
00:13:01.224     16:04:24	-- bdev/blockdev.sh@376 -- # /home/vagrant/spdk_repo/spdk/scripts/iostat.py -d -i 1 -t 5
00:13:01.224     16:04:24	-- bdev/blockdev.sh@376 -- # grep Malloc_0
00:13:01.224     16:04:24	-- bdev/blockdev.sh@376 -- # tail -1
00:13:06.584    16:04:29	-- bdev/blockdev.sh@376 -- # iostat_result='Malloc_0  14262.98  57051.92   0.00       0.00       59456.00  0.00     0.00   '
00:13:06.584    16:04:29	-- bdev/blockdev.sh@377 -- # '[' IOPS = IOPS ']'
00:13:06.584     16:04:29	-- bdev/blockdev.sh@378 -- # awk '{print $2}'
00:13:06.584    16:04:29	-- bdev/blockdev.sh@378 -- # iostat_result=14262.98
00:13:06.584    16:04:29	-- bdev/blockdev.sh@383 -- # echo 14262
00:13:06.584   16:04:29	-- bdev/blockdev.sh@390 -- # qos_result=14262
00:13:06.584   16:04:29	-- bdev/blockdev.sh@391 -- # '[' IOPS = BANDWIDTH ']'
00:13:06.584   16:04:29	-- bdev/blockdev.sh@394 -- # lower_limit=14400
00:13:06.584   16:04:29	-- bdev/blockdev.sh@395 -- # upper_limit=17600
00:13:06.584   16:04:29	-- bdev/blockdev.sh@398 -- # '[' 14262 -lt 14400 ']'
00:13:06.584  Failed to limit the io read rate of NULL bdev by qos
00:13:06.584   16:04:29	-- bdev/blockdev.sh@399 -- # echo 'Failed to limit the io read rate of NULL bdev by qos'
00:13:06.584   16:04:29	-- bdev/blockdev.sh@400 -- # rpc_cmd bdev_malloc_delete Malloc_0
00:13:06.584   16:04:29	-- common/autotest_common.sh@550 -- # xtrace_disable
00:13:06.584   16:04:29	-- common/autotest_common.sh@10 -- # set +x
00:13:06.584  [2023-12-21 16:04:29.768696] thread.c:2585:spdk_for_each_channel: *ERROR*: could not find io_device 0x616000005d81
00:13:06.584  bdevperf: thread.c:2586: spdk_for_each_channel: Assertion `false' failed.
00:13:16.552  Connection closed with partial response:
00:13:16.552  
00:13:16.552  
00:13:16.552  Connection closed with partial response:
00:13:16.552  
00:13:16.552  
00:13:16.552   16:04:38	-- common/autotest_common.sh@578 -- # [[ 1 == 0 ]]
00:13:16.553  /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh: line 578: 103155 Aborted                 (core dumped) "$rootdir/build/examples/bdevperf" -z -m 0x2 -q 256 -o 4096 -w randread -t 60 "$env_ctx"
00:13:16.553    16:04:38	-- common/autotest_common.sh@578 -- # trap - ERR
00:13:16.553    16:04:38	-- common/autotest_common.sh@578 -- # print_backtrace
00:13:16.553    16:04:38	-- common/autotest_common.sh@1112 -- # [[ ehxBET =~ e ]]
00:13:16.553    16:04:38	-- common/autotest_common.sh@1114 -- # args=("${BASH_ARGV[@]}")
00:13:16.553    16:04:38	-- common/autotest_common.sh@1114 -- # local args
00:13:16.553    16:04:38	-- common/autotest_common.sh@1116 -- # xtrace_disable
00:13:16.553    16:04:38	-- common/autotest_common.sh@10 -- # set +x

**Comment by spdkci** [comment] 2023-12-21 22:47
Another instance of this failure. Reported by @ksprzacz. log: https://ci.spdk.io/public_build/autotest-per-patch_114355.html

**Comment by mikeBashStuff** [comment] 2023-12-21 23:36
Duplicate of #3218.

**Closed by mikeBashStuff** 2023-12-21 23:36 UTC
Labels: Intermittent Failure
