### ISSUE TITLE
nvmf_tgt TCP segmentation fault with high amount of traffic

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1970] opened 2021-06-01 11:28 UTC
## Current Behavior

When running randrw with high number of connections and high QD SPDK NVMe-oF TCP target segfaults.

```
Core was generated by `/var/jenkins/workspace/nvmf-perf/regression-tcp/spdk/build/bin/nvmf_tgt --wait-'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000046242b in posix_sock_recv_from_pipe (diovcnt=1, diov=0x7ffc6709abb0, sock=0x2c995d0) at posix.c:914
914                             TAILQ_REMOVE(&group->socks_with_data, sock, link);
[Current thread is 1 (Thread 0x7f13156049c0 (LWP 3233368))]
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.31-6.fc32.x86_64 libaio-0.3.111-7.fc32.x86_64 libibverbs-33.0-2.fc32.x86_64 libnl3-3.5.0-2.fc32.x86_64 librdmacm-33.0-2.fc32.x86_64 libuuid-2.35.2-1.fc32.x86_64 numactl-libs-2.0.12-4.fc32.x86_64 openssl-libs-1.1.1i-1.fc32.x86_64 zlib-1.2.11-21.fc32.x86_64
(gdb) bt
#0  0x000000000046242b in posix_sock_recv_from_pipe (diovcnt=1, diov=0x7ffc6709abb0, sock=0x2c995d0) at posix.c:914
#1  posix_sock_readv (_sock=0x2c995d0, iov=0x7ffc6709abb0, iovcnt=1) at posix.c:1008
#2  0x000000000046260a in posix_sock_recv (sock=<optimized out>, buf=<optimized out>, len=<optimized out>) at posix.c:1019
#3  0x000000000047e5d5 in nvme_tcp_read_data (sock=<optimized out>, bytes=<optimized out>, buf=<optimized out>) at /var/jenkins/workspace/nvmf-perf/regression-tcp/spdk/include/spdk_internal/nvme_tcp.h:474
#4  0x000000000047fe54 in nvme_tcp_readv_data (iovcnt=<optimized out>, iov=0x7ffc6709ac00, sock=0x2c995d0) at /var/jenkins/workspace/nvmf-perf/regression-tcp/spdk/include/spdk_internal/nvme_tcp.h:507
#5  nvme_tcp_read_payload_data (sock=0x2c995d0, pdu=pdu@entry=0x2000398fe440) at /var/jenkins/workspace/nvmf-perf/regression-tcp/spdk/include/spdk_internal/nvme_tcp.h:543
#6  0x0000000000480f6e in nvmf_tcp_sock_process (tqpair=tqpair@entry=0x2c99680) at tcp.c:2039
#7  0x0000000000481d59 in nvmf_tcp_sock_cb (arg=0x2c99680, group=<optimized out>, sock=<optimized out>) at tcp.c:2637
#8  0x00000000004ca309 in sock_group_impl_poll_count (max_events=32, group=0x2577770, group_impl=0x2577790) at sock.c:623
#9  spdk_sock_group_poll_count (group=0x2577770, max_events=max_events@entry=32) at sock.c:649
#10 0x00000000004ca39a in spdk_sock_group_poll (group=<optimized out>) at sock.c:600
#11 0x0000000000481cca in nvmf_tcp_poll_group_poll (group=0x25776e0) at tcp.c:2774
#12 0x00000000004761fb in nvmf_poll_group_poll (ctx=<optimized out>) at nvmf.c:101
#13 0x00000000004c649e in thread_execute_poller (poller=0x258bf10, thread=0x257bac0) at thread.c:775
#14 thread_poll (thread=thread@entry=0x257bac0, max_msgs=max_msgs@entry=0, now=now@entry=46607034995099038) at thread.c:897
#15 0x00000000004c6f4c in spdk_thread_poll (thread=thread@entry=0x257bac0, max_msgs=max_msgs@entry=0, now=46607034995099038) at thread.c:948
#16 0x0000000000467401 in _reactor_run (reactor=0x256eac0) at reactor.c:916
#17 reactor_run (arg=0x256eac0) at reactor.c:954
#18 0x00000000004678e7 in spdk_reactors_start () at reactor.c:1062
#19 0x0000000000465197 in spdk_app_start (opts_user=0x7ffc6709b200, opts_user@entry=0x7ffc6709b570, start_fn=start_fn@entry=0x41d5e0 <nvmf_tgt_started>, arg1=arg1@entry=0x0) at app.c:579
#20 0x00000000004196a8 in main (argc=4, argv=0x7ffc6709b738) at nvmf_main.c:75
```

## Steps to Reproduce

Reproduction steps are high-level, because issue seems to only reproduce at scale, so I'm usign spdk/scripts/perf/nvmf/run_nvmf.py script, which is used for performance tests. 

The configuration file for test looks like this:
```
{
  "target": {
    "nic_ips": ["20.0.0.1", "20.0.1.1", "10.0.0.1", "10.0.1.1"],
    "mode": "spdk",
    "use_null_block": false,
    "nvmet_dir": "/home/sys_sgci/nvmetcli",
    "core_mask": "[0]"
  },
  "initiator1": {
    "ip": "10.211.11.66",
    "nic_ips": ["20.0.0.2", "20.0.1.2"],
    "target_nic_ips": ["20.0.0.1", "20.0.1.1"],
    "fio_dir": "/usr/src/fio",
    "mode": "spdk",
    "num_cores": 6
  },
  "initiator2": {
    "ip": "10.211.11.65",
    "nic_ips": ["10.0.0.2", "10.0.1.2"],
    "target_nic_ips": ["10.0.0.1", "10.0.1.1"],
    "fio_dir": "/usr/src/fio",
    "mode": "spdk",
    "num_cores": 6
  },
  "fio": {
    "bs": ["4k"],
    "qd": [128],
    "rw": ["randrw"],
    "rwmixread": 70,
    "num_jobs": 3,
    "run_time": 20,
    "ramp_time": 0,
    "run_num": 1,
    "rate_iops": 0
  }
}

```

Configuration file translates roughly to this scenario:

Target:
```
1. Start nvmf_tgt with 1 CPU core (core 0)
2. Create 12 NVMe bdevs (Optane p4800 SSD)
3. Create TCP transport layer
4. Create 12 nvmf subsystems
5. Add 1 nvme bdev to each subsystem
6. Assign listener to subsystems; subsystems are evenly distributed between available nic_ips IP addresses
```

There are 2 initiators in use. For each one do:
```
1. Create bdev.conf file for spdk fio bdev plugin:
[sys_sgci@supermicro2 spdk]$ cat bdev.conf
{
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "method": "bdev_nvme_attach_controller",
          "params": {
            "name": "Nvme0",
            "trtype": "tcp",
            "traddr": "20.0.0.1",
            "trsvcid": "4420",
            "subnqn": "nqn.2018-09.io.spdk:cnode0",
            "adrfam": "IPv4"
          }
        },
[...etc...]
2. Create fio config file on each initiator
[global]
ioengine=/tmp/spdk/build/fio/spdk_bdev
spdk_json_conf=/tmp/spdk/bdev.conf
thread=1
group_reporting=1
direct=1
percentile_list=50:90:99:99.5:99.9:99.99:99.999

norandommap=1
rw=randrw
rwmixread=70
bs=4k
time_based=1
ramp_time=0
runtime=20
rate_iops=0
numjobs=3

[filename0]
filename=Nvme0n1
iodepth=43
[filename1]
filename=Nvme1n1
iodepth=43
[filename2]
filename=Nvme2n1
iodepth=43
[filename3]
filename=Nvme3n1
iodepth=43
[filename4]
filename=Nvme4n1
iodepth=43
[filename5]
filename=Nvme5n1
iodepth=43

(iodepth * numjobs =~ 128 iodepth for each subsystem)

3. Run the traffic
```

* Reducing the number of connections (numjobs) from 3 to 2 mitigates the issue
* Reducing the iodepth a bit from 128 to 64 mitigates the issue
* With numjobs=3 iodepth=128, but different workload (randread, randwrite) the issue does not show up

## Context (Environment including OS version, SPDK version, etc.)

System: 5.10.16-100.fc32.x86_64
Issue reproduced on: SPDK 9f5e3c99f2  nvme: add spdk_nvme_ctrlr_is_fabrics()

Bisecting points to `1ae601b573 sock/posix: Avoid extra readv calls after draining recv_pipe` as faulty commit.

**Comment by jimharris** [comment] 2021-06-01 15:10
@karlatec - can you 'p sock' and 'p group' when this crashes?  I'm curious which one is causing the segfault here.

I'm assuming this is a release build, is there any chance this reproduces with a debug build?

**Comment by karlatec** [comment] 2021-06-02 11:30
@optimistyzy https://review.spdk.io/gerrit/c/spdk/spdk/+/8152 looks good, at least for making the target not crash. Not sure about performance though. We could merge it and leave regressions tests enabled for a couple of days to see if it has any impact.

**Comment by optimistyzy** [comment] 2021-06-03 02:21
> @optimistyzy https://review.spdk.io/gerrit/c/spdk/spdk/+/8152 looks good, at least for making the target not crash. Not sure about performance though. We could merge it and leave regressions tests enabled for a couple of days to see if it has any impact.

Hi Karol,
Per Ben's comments,  could you  check the latest version of this patch and verify it again?  Thanks.

**Comment by karlatec** [comment] 2021-06-07 09:01
Tested refs/changes/52/8152/7, tests passed all workloads and did not crash

**Comment by karlatec** [comment] 2021-06-10 07:04
Hi, any update on  the fix? This issue blocks our performance regression tests.

**Comment by jimharris** [comment] 2021-06-10 14:46
@benlwalker, @optimistyzy - what are next steps here?

**Comment by benlwalker** [comment] 2021-06-10 15:05
I see the bug now and I just updated my comments on the review. We should be able to close this out shortly.

**Comment by optimistyzy** [comment] 2021-06-11 00:14
Hi @karlatec .

Could you retest with  this patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/8283  Since @benlwalker still have concern of one line change on my patch  refs/changes/52/8152/7. This time I used a new patch number. I think that if 8283 cannot solve this issue, we may still use refs/changes/52/8152/7.

Thanks.

**Comment by karlatec** [comment] 2021-06-11 12:09
refs/changes/83/8283/1 - tests passed, no crash enountered

**Comment by optimistyzy** [comment] 2021-06-15 01:17
@karlatec Hi Karol, patch was merged. I will close this issue if there is other issue you find, you can reopen this issue.

**Closed by optimistyzy** 2021-06-15 01:17 UTC
Labels: High, Patches out for review, bug

**Comment by optimistyzy** [comment] 2021-09-16 08:00
@karlatec @wawryk  Previously I provided this  https://review.spdk.io/gerrit/c/spdk/spdk/+/8283  patch to fix this issue, but it seems that there is performance drop reported in #2158 recently, so can you revert this patch and apply  this patch https://review.spdk.io/gerrit/c/spdk/spdk/+/9521 to see whether this patch can fix the coredump issue but also not degrade the performance.
