### ISSUE TITLE
CQ Error Transport Retry Counter Exceeded Occurs When 1 MB Sequential Write in the NoF RDMA

### ISSUE THREAD

**Issue by fengchunsong** [spdk/spdk#2436] opened 2022-03-25 07:10 UTC
# Bug report

## Current Behavior

The host and target of the NoF are deployed on different servers, When fio or perf is used to test 1 MB write, a CQ error occurs. No CQ error occurs when 4K write is tested. 

The host and target of the NoF are deployed on the same server,No CQ error occurs when 1 MB write is tested.

[root@node7 bin]# ./nvmf_tgt -m 0x3fff
[2022-03-25 14:39:00.274288] Starting SPDK v21.10 git sha1 4e4f11ff7 / DPDK 21.08.0 initialization...
[2022-03-25 14:39:00.274396] [ DPDK EAL parameters: [2022-03-25 14:39:00.274404] nvmf [2022-03-25 14:39:00.274411] --no-shconf [2022-03-25 14:39:00.274417] -c 0x3fff [2022-03-25 14:39:00.274423] --log-level=lib.eal:6 [2022-03-25 14:39:00.274429] --log-level=lib.cryptodev:5 [2022-03-25 14:39:00.274434] --log-level=user1:6 [2022-03-25 14:39:00.274440] --iova-mode=pa [2022-03-25 14:39:00.274446] --base-virtaddr=0x200000000000 [2022-03-25 14:39:00.274452] --match-allocations [2022-03-25 14:39:00.274457] --file-prefix=spdk_pid31298 [2022-03-25 14:39:00.274463] ]
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-03-25 14:39:00.325181] app.c: 543:spdk_app_start: *NOTICE*: Total cores available: 14
[2022-03-25 14:39:00.492497] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 1
[2022-03-25 14:39:00.492510] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 2
[2022-03-25 14:39:00.492521] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 3
[2022-03-25 14:39:00.492532] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 4
[2022-03-25 14:39:00.492544] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 5
[2022-03-25 14:39:00.492559] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 6
[2022-03-25 14:39:00.492570] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 7
[2022-03-25 14:39:00.492582] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 8
[2022-03-25 14:39:00.492596] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 9
[2022-03-25 14:39:00.492608] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 10
[2022-03-25 14:39:00.492620] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 11
[2022-03-25 14:39:00.492632] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 12
[2022-03-25 14:39:00.492644] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 13
[2022-03-25 14:39:00.492647] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 0
[2022-03-25 14:39:00.492973] accel_engine.c:1012:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2022-03-25 14:40:13.784293] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 840 ***
[2022-03-25 14:40:14.028042] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 841 ***
[2022-03-25 14:40:14.272039] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 842 ***
[2022-03-25 14:40:14.516039] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 843 ***
[2022-03-25 14:40:14.760036] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 844 ***
[2022-03-25 14:40:15.004027] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 845 ***
[2022-03-25 14:40:15.248028] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 846 ***
[2022-03-25 14:40:15.492029] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 847 ***
[2022-03-25 14:40:15.736024] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 848 ***
[2022-03-25 14:40:15.980021] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 849 ***
[2022-03-25 14:40:16.224026] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8410 ***
[2022-03-25 14:40:16.468026] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8411 ***
[2022-03-25 14:40:16.712020] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8412 ***
[2022-03-25 14:40:16.956019] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8413 ***
[2022-03-25 14:40:17.200021] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8414 ***
[2022-03-25 14:40:17.444019] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8415 ***
[2022-03-25 14:40:17.684015] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8416 ***
[2022-03-25 14:40:17.928019] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8417 ***
[2022-03-25 14:40:18.172017] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8418 ***
[2022-03-25 14:40:18.416015] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8419 ***
[2022-03-25 14:40:18.660012] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8420 ***
[2022-03-25 14:40:18.904011] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8421 ***
[2022-03-25 14:40:19.148008] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8422 ***
[2022-03-25 14:40:19.392013] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8423 ***
[2022-03-25 14:40:19.636006] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8424 ***
[2022-03-25 14:40:19.880001] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8425 ***
[2022-03-25 14:40:20.123994] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8426 ***
[2022-03-25 14:40:20.367999] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8427 ***
[2022-03-25 14:40:20.612001] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8428 ***
[2022-03-25 14:40:20.855995] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8429 ***
[2022-03-25 14:40:21.099989] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8430 ***
[2022-03-25 14:40:21.343998] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8431 ***
[2022-03-25 14:40:21.587998] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8432 ***
[2022-03-25 14:40:21.831993] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8433 ***
[2022-03-25 14:40:22.115987] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8434 ***
[2022-03-25 14:40:22.359990] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8435 ***
[2022-03-25 14:40:22.603988] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8436 ***
[2022-03-25 14:40:22.847986] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8437 ***
[2022-03-25 14:40:23.091983] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8438 ***
[2022-03-25 14:40:23.335980] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8439 ***
[2022-03-25 14:40:23.579983] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8440 ***
[2022-03-25 14:40:23.823980] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8441 ***
[2022-03-25 14:40:24.067974] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8442 ***
[2022-03-25 14:40:24.311981] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8443 ***
[2022-03-25 14:40:24.555980] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8444 ***
[2022-03-25 14:40:24.799973] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8445 ***
[2022-03-25 14:40:25.043969] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8446 ***
[2022-03-25 14:40:25.287969] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8447 ***
[2022-03-25 14:40:25.531971] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8448 ***
[2022-03-25 14:40:25.771963] rdma.c:2743:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 172.19.37.45 port 8449 ***
[2022-03-25 14:42:54.734407] rdma.c:3868:nvmf_rdma_log_wc_status: *ERROR*: Error on CQ 0x7f2a28011230, (qp state 1 ibv_state 6) request 0x139819061613720, type SEND, opcode 128, status: (12): transport retry counter exceeded rqpair 0x313ab70 byte_len 64
[2022-03-25 14:42:54.738633] rdma.c: 894:nvmf_rdma_qpair_destroy: *WARNING*: Destroying qpair when queue depth is 15
[2022-03-25 14:42:54.738667] rdma.c: 668:nvmf_rdma_dump_qpair_contents: *ERROR*: Dumping contents of queue pair (QID 1)
[2022-03-25 14:42:54.738677] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:54.738685] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:54.738694] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061453064
[2022-03-25 14:42:54.738703] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:54.738710] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:54.738719] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061453168
[2022-03-25 14:42:54.738728] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:54.738736] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:54.738746] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061453272
[2022-03-25 14:42:54.738755] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:54.738763] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:54.738770] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061453376
[2022-03-25 14:42:54.738778] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:54.738787] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:54.738794] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061453480
[2022-03-25 14:42:54.738803] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:54.738810] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:54.738817] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061453584
[2022-03-25 14:42:54.738825] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:54.738833] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:54.738840] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061453688
[2022-03-25 14:42:54.738847] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:54.738855] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:54.738862] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061453792
[2022-03-25 14:42:54.738870] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:54.738877] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:54.738887] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061453896
[2022-03-25 14:42:54.738895] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:54.738903] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:54.738912] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061454000
[2022-03-25 14:42:54.738921] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:54.738928] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:54.738936] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061454104
[2022-03-25 14:42:54.738945] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:54.738953] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:54.738961] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061454208
[2022-03-25 14:42:54.738969] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:54.738977] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:54.738985] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061456080
[2022-03-25 14:42:54.738993] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:54.739001] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:54.739009] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061456184
[2022-03-25 14:42:54.739017] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:54.739026] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:54.739038] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061452960
[2022-03-25 14:42:55.042683] rdma.c:3868:nvmf_rdma_log_wc_status: *ERROR*: Error on CQ 0x7f2a28011230, (qp state 1 ibv_state 6) request 0x139819061489400, type SEND, opcode 128, status: (12): transport retry counter exceeded rqpair 0x30a13b0 byte_len 64
[2022-03-25 14:42:55.046973] rdma.c: 894:nvmf_rdma_qpair_destroy: *WARNING*: Destroying qpair when queue depth is 15
[2022-03-25 14:42:55.047006] rdma.c: 668:nvmf_rdma_dump_qpair_contents: *ERROR*: Dumping contents of queue pair (QID 1)
[2022-03-25 14:42:55.047016] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:55.047026] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:55.047035] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061346616
[2022-03-25 14:42:55.047044] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:55.047052] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:55.047059] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061346824
[2022-03-25 14:42:55.047068] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:55.047076] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:55.047084] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061346720
[2022-03-25 14:42:55.047091] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:55.047100] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:55.047108] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061346928
[2022-03-25 14:42:55.047115] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:55.047124] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:55.047132] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061347032
[2022-03-25 14:42:55.047139] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:55.047148] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:55.047158] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061347136
[2022-03-25 14:42:55.047166] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:55.047174] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:55.047181] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061347240
[2022-03-25 14:42:55.047189] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:55.047198] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:55.047205] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061347344
[2022-03-25 14:42:55.047213] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:55.047221] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:55.047230] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061349216
[2022-03-25 14:42:55.047237] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:55.047246] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:55.047254] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061349320
[2022-03-25 14:42:55.047269] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:55.047278] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:55.047286] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061349424
[2022-03-25 14:42:55.047294] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:55.047302] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:55.047310] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061349528
[2022-03-25 14:42:55.047317] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:55.047326] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:55.047335] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061349632
[2022-03-25 14:42:55.047343] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:55.047352] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:55.047360] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061349736
[2022-03-25 14:42:55.047368] rdma.c: 654:nvmf_rdma_dump_request: *ERROR*:               Request Data From Pool: 1
[2022-03-25 14:42:55.047378] rdma.c: 656:nvmf_rdma_dump_request: *ERROR*:               Request opcode: 1
[2022-03-25 14:42:55.047386] rdma.c: 659:nvmf_rdma_dump_request: *ERROR*:               Request recv wr_id139819061346512

## Steps to Reproduce

1.
2.
3.
4.

**Comment by fengchunsong** [comment] 2022-03-25 07:12
@AlekseyMarchuk please help to debug this issue,thanks

**Comment by AlekseyMarchuk** [comment] 2022-03-25 08:07
Hi @fengchunsong I can start working on this issue next week

**Comment by AlekseyMarchuk** [comment] 2022-03-28 13:38
Hi @fengchunsong I forgot to ask about your SPDK configuration, could you please share it? That is important since default mdts in nvmf rdma is 128K and in that case initiator will split 1MiB payload. So I need to know if you changed default transport opts

**Comment by fengchunsong** [comment] 2022-03-29 06:36
> mdts

          "method": "nvmf_create_transport",
          "params": {
            "trtype": "RDMA",
            "max_queue_depth": 128,
            "max_io_qpairs_per_ctrlr": 127,
            "in_capsule_data_size": 4096,
            "max_io_size": 16384,
            "io_unit_size": 8320,
            "max_aq_depth": 128,
            "num_shared_buffers": 4096,
            "buf_cache_size": 32,
            "dif_insert_or_strip": true,
            "max_srq_depth": 16384,
            "no_srq": false,
            "acceptor_backlog": 100,
            "no_wr_batching": false,
            "abort_timeout_sec": 1

**Comment by fengchunsong** [comment] 2022-04-01 07:24
@AlekseyMarchuk Do you need any more information? My environment can easily reproduce this problem. Can your environment reproduce this problem?

**Comment by AlekseyMarchuk** [comment] 2022-04-01 08:29
Hi @fengchunsong I haven't looked at this problem yet, plan to do it today. I'll update your a bit later

**Comment by AlekseyMarchuk** [comment] 2022-04-01 10:27
@fengchunsong I checked your scenario in my environment, it works fine. I verified v21.10 and master branch. Here is my config:
```
sudo ./build/bin/spdk_tgt -m 0x3fff &
sleep 3
sudo ./scripts/rpc.py nvmf_create_transport -t RDMA -c 4096 -i 16384 -u 8320 -f -s 16384 
sudo ./scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a
sudo ./scripts/rpc.py bdev_null_create Null0 10241024 4104 -m 8 -t 2
sudo ./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Null0
sudo ./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 1.1.1.1 -s 4420
```
perf : `sudo ./build/examples/perf -q 16 -o 1048576 -w write -t 10 -r 'trtype:RDMA adrfam:IPV4 traddr:1.1.1.1 trsvcid:4420' -c 0x3fff`

Could you check if my config or perf parameters differ from yours?

**Comment by fengchunsong** [comment] 2022-04-01 10:44
The test time is increased to 10 minutes, increasing the number of memory disk until the network bandwidth has a bottleneck.

**Comment by AlekseyMarchuk** [comment] 2022-04-05 16:09
@fengchunsong I retested as you suggested, no failure for 3 iterations, 10 minutes each. Network BW was fully saturated
Here is my config:
```
sudo ./build/bin/spdk_tgt -m 0x3fff &
sleep 3
sudo ./scripts/rpc.py nvmf_create_transport -t RDMA -c 4096 -i 16384 -u 8320 -f -s 16384 
sudo ./scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a
sudo ./scripts/rpc.py bdev_null_create Null0 10241024 4104 -m 8 -t 2
sudo ./scripts/rpc.py bdev_null_create Null1 10241024 4104 -m 8 -t 2
sudo ./scripts/rpc.py bdev_null_create Null2 10241024 4104 -m 8 -t 2
sudo ./scripts/rpc.py bdev_null_create Null3 10241024 4104 -m 8 -t 2
sudo ./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Null0
sudo ./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Null1
sudo ./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Null2
sudo ./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Null3
sudo ./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 1.1.1.1 -s 4420
```
and perf:
```
sudo ./build/examples/perf -q 32 -o 1048576 -w write -t 600 -r 'trtype:RDMA adrfam:IPV4 traddr:1.1.1.1 trsvcid:4420' -c 0x3fff
```
Could you clarify if you used similar configuration?

As I remember, in another issue you mentioned that you used ConnectX5 RNIC. In this test I used the same NIC:
```
lspci -vv -s 3b:00.0
...
        Capabilities: [48] Vital Product Data
                Product Name: CX556A - ConnectX-5 QSFP28
                Read-only fields:
                        [PN] Part number: MCX556A-ECAT
                        [EC] Engineering changes: B2
                        [V2] Vendor specific: MCX556A-ECAT
                        [SN] Serial number: MT2043K07978
                        [V3] Vendor specific: e018c2e34a15eb118000043f72dd1554
                        [VA] Vendor specific: MLX:MODL=CX556A:MN=MLNX:CSKU=V2:UUID=V3:PCI=V0
                        [V0] Vendor specific: PCIeGen3 x16
                        [VU] Vendor specific: MT2043K07978MLNXS0D0F0
                        [RV] Reserved: checksum good, 2 byte(s) reserved
                End
```
If we If it is possible, could you install latest mlnx_ofed on your system?

**Comment by fengchunsong** [comment] 2022-04-06 04:01
I use the CX4 and the information is as follows:

        Capabilities: [48] Vital Product Data
                Product Name: CX456A - ConnectX-4 QSFP28
                Read-only fields:
                        [PN] Part number: MCX456A-ECAT
                        [EC] Engineering changes: AH
                        [SN] Serial number: MT1843K01357
                        [V0] Vendor specific: PCIeGen3 x16
                        [RV] Reserved: checksum good, 2 byte(s) reserved
                End

My test environment also appears randomly, today retested the morning still does not appear, I will look for the rule again.

**Comment by jimharris** [comment] 2022-06-28 15:15
hi @fengchunsong,

I'm going to close this issue.  If you are able to reproduce, please reopen with details on reproduction.  Also please try w/ latest mlnx_ofed like @AlekseyMarchuk suggested.

Thanks,

Jim

**Closed by jimharris** 2022-06-28 15:15 UTC
Labels: Waiting on Submitter, Sighting
