### ISSUE TITLE
Vhost-user crashed after Guest OS reboot

### ISSUE THREAD

**Issue by samhjn** [spdk/spdk#378] opened 2018-07-27 04:16 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Right after rebooting guest os, the spdk vhost app crashed.
Guest OS version: Ubuntu 18.04
Maybe crashed when grub loads

## Expected Behavior
vhost app keeps work

## Current Behavior
crashed with segment fault

## Possible Solution
unhandle reboot status

## Steps to Reproduce
1. start app/vhost/vhost
2. create malloc bdev & vhost-user device
3. attach bdev to vhost-user device
4. start guest os then reboot

## Context (Environment including OS version, SPDK version, etc.)
Guest OS: ubuntu 18.04
Qemu: qemu with spdk vhost-nvme patch / original qemu newest
spdk: newest

**Comment by pawelwod** [comment] 2018-07-27 08:15
Look like issue that is already fixed here https://review.gerrithub.io/#/c/spdk/spdk/+/420372/ . Can you check latest master?

**Comment by liang2yan** [comment] 2018-08-07 05:34
@samhjn , any updates about this issue?

**Comment by ChenWang01** [comment] 2018-08-07 06:58
@samhjn 
I can't reproduce this issue in my environment.
commit: 2b3abb2a339cfb1033108808ffa7577b860cca09

**Comment by samhjn** [comment] 2018-08-07 07:00
it fixed




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            Sam He
                            
                            
                                
                                    邮箱：samhjn@gmail.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


On 08/07/2018 14:59, Chen Wang wrote: @samhjn
I can't reproduce this issue in my environment.
commit: 2b3abb2a339cfb1033108808ffa7577b860cca09

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/spdk/spdk","title":"spdk/spdk","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/spdk/spdk"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ChenWang01 in #378: @samhjn \r\nI can't reproduce this issue in my environment.\r\ncommit: 2b3abb2a339cfb1033108808ffa7577b860cca09"}],"action":{"name":"View Issue","url":"https://github.com/spdk/spdk/issues/378#issuecomment-410954265"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/spdk/spdk/issues/378#issuecomment-410954265",
"url": "https://github.com/spdk/spdk/issues/378#issuecomment-410954265",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [spdk/spdk] Vhost-user crashed after Guest OS reboot (#378)",
"sections": [
{
"text": "",
"activityTitle": "**Chen Wang**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ChenWang01",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"spdk/spdk\",\n\"issueId\": 378,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"spdk/spdk\",\n\"issueId\": 378\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/spdk/spdk/issues/378#issuecomment-410954265"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 361467411\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by liang2yan** [comment] 2018-08-10 05:49
Close this issue since it fixed.

**Closed by liang2yan** 2018-08-10 05:49 UTC
