### ISSUE TITLE
Nvmf target print error messages while testing performance

### ISSUE THREAD

**Issue by fshenx** [spdk/spdk#568] opened 2019-01-11 02:26 UTC
Nvmf target print error messages while testing performance

log:
```
./app/nvmf_tgt/nvmf_tgt -c nvmf.conf.in
Starting SPDK v19.01-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: nvmf --no-shconf -c 0x1 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid36939 ]
EAL: Detected 44 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
app.c: 612:spdk_app_start: *NOTICE*: Total cores available: 1
app.c: 538:spdk_app_setup_trace: *NOTICE*: Tracepoint Group Mask 0x01 specified.
app.c: 542:spdk_app_setup_trace: *NOTICE*: Use 'spdk_trace -s nvmf -p 36939' to capture a snapshot of events at runtime.
app.c: 544:spdk_app_setup_trace: *NOTICE*: Or copy /dev/shm/nvmf_trace.pid36939 for offline analysis/debug.
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
EAL: PCI device 0000:03:00.0 on NUMA socket 0
EAL:   probe driver: 8086:2701 spdk_nvme
EAL: PCI device 0000:06:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:07:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:08:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:09:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:0a:00.0 on NUMA socket 0
EAL:   probe driver: 8086:2701 spdk_nvme
EAL: PCI device 0000:0c:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:0d:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:10:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:11:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
ctrlr.c:1620:spdk_nvmf_ctrlr_process_admin_cmd: *ERROR*: Admin command sent to disabled controller
```

## Expected Behavior
No error message

## Current Behavior
ctrlr.c:1620:spdk_nvmf_ctrlr_process_admin_cmd: *ERROR*: Admin command sent to disabled controller

## Steps to Reproduce

nvmf.conf.in ：
```
[Global]
 TpointGroupMask 0x01
 
[Bdev]

[Malloc]
  NumberOfLuns 8
  LunSizeInMB 64

[AIO]

[Pmem]

[Nvmf]
  AcceptorPollRate 10000

[Transport]
  Type RDMA

[Nvme]
  TransportID "trtype:PCIe traddr:0000:06:00.0" Nvme0
  RetryCount 4
  TimeoutUsec 0
  ActionOnTimeout None
  AdminPollRate 100000
  HotplugEnable No

[Subsystem1]
  NQN nqn.2016-06.io.spdk:cnode1
  Listen RDMA 192.168.1.3:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000001
  MaxNamespaces 20
  Namespace Nvme0n1 1
```
 ./app/nvmf_tgt/nvmf_tgt -c nvmf.conf.in

test case :
`./examples/nvme/perf/perf -q 32 -o 4096 -w randrw -M 50 -t 10 -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.1.3 trsvcid:4420'`

## Environment
target:  
commit id: d1399f44
OS: Ubuntu 18.04
kernel:4.16.7

initiator:
commit id: 7fecba0c
OS: Fedora release 27 
kernel: 4.16.7

**Comment by optimistyzy** [comment] 2019-01-11 04:00
@fshenx Could you try the following patch: https://review.gerrithub.io/438164

**Comment by optimistyzy** [comment] 2019-01-11 05:55
@fshenx  Sorry this patch is not for this issue. Is this issue only related with real NVMe device? Can you replace with the backend device with malloc device to run the test again.

**Comment by fshenx** [comment] 2019-01-11 06:06
@optimistyzy 
I have tried the malloc device , but it also has the problem.

**Comment by optimistyzy** [comment] 2019-01-11 06:17
@fshenx I cannot reproduce this issue with latest master with TCP transport.  I see your version is not the latest one in both initiator and target. Whether you could update it to the latest master

**Comment by optimistyzy** [comment] 2019-01-11 07:48
It is only related with rdma transport, need to dig more to find the reason. The invalid admin cmd opc=0xc, means it is SPDK_NVME_OPC_ASYNC_EVENT_REQUEST type.

**Comment by changpe1** [comment] 2019-01-11 07:48
Yes, it's a bug, thanks for submitting. I'll provide a patch to fix it.

**Comment by optimistyzy** [comment] 2019-01-11 08:07
I found the root cause,may provide a patch later if anyone.does not provide it

**Comment by changpe1** [comment] 2019-01-11 08:15
@optimistyzy , go ahead to submit your patch, thanks.

**Comment by optimistyzy** [comment] 2019-01-11 10:51
See this patch:  https://review.gerrithub.io/c/spdk/spdk/+/440014. We may re-use some existing flags, e.g., is_resetting, is_failed. or the ctrlr->state. But it seems that all of them have special meanings.

**Comment by optimistyzy** [comment] 2019-01-14 02:45
@fshenx  You can also validate this patch: https://review.gerrithub.io/#/c/spdk/spdk/+/440132/

**Comment by fshenx** [comment] 2019-01-14 06:03
@optimistyzy 
This patch doesn't work.

**Comment by changpe1** [comment] 2019-01-14 06:38
@fshenx , can you double check with the patch, I can't see the error log in my local environment with this patch. Thanks.

**Comment by fshenx** [comment] 2019-01-15 00:54
@changpe1 
Thanks. I double checked with the patch, to fix this bug, I need to cherry-pick the patch on the initiator.
It doesn't work if I just cherry-pick the patch on the target.

**Comment by optimistyzy** [comment] 2019-01-15 03:46
@fshenx You can download the whole branch, then you do not need to cherry-pick the patch.

**Comment by changpe1** [comment] 2019-01-18 07:54
closing the issue, as patch has been merged.

**Closed by changpe1** 2019-01-18 07:54 UTC
Labels: bug
