### ISSUE TITLE
Data inconsistency for SPDK+UIO using NVMe

### ISSUE THREAD

**Issue by ufo19890607** [spdk/spdk#1738] opened 2021-01-11 14:15 UTC
## Abnormal Behavior
I find md5sum value is changed when copying one bigfile with 100G size from one nvme device to another.

## Possible Solution
Bind nvme devices with vfio driver rather than UIO driver.

### Scenario 1
1. Bind 2 NVMe P5510 or P4510 with UIO driver
```
modprobe uio_pci_generic
echo 0000:3b:00.0 >/sys/bus/pci/drivers/nvme/unbind
echo uio_pci_generic > /sys/bus/pci/devices/0000\:3b\:00.0/driver_override
echo 0000:3b:00.0 >/sys/bus/pci/drivers/uio_pci_generic/bind
```
2. Boot SPDK with the following command:
```
./build/bin/vhost  -m 0x1000010 -S /var/run/spdk/ -s 2048 --iova-mode=pa
```
3. Create 2 nvme bdevs and vhost_controllers.
```
./scripts/rpc.py bdev_nvme_attach_controller -b nvme0 -t PCIe -a 0000:3b:00.0
./scripts/rpc.py vhost_create_blk_controller vhost_socket-nvme0n1 nvme0n1
./scripts/rpc.py bdev_nvme_attach_controller -b nvme1 -t PCIe -a 0000:3c:00.0
./scripts/rpc.py vhost_create_blk_controller vhost_socket-nvme1n1 nvme1n1
```
4. Startup VM with these 2 vhost_controllers for step1. 
The number of vcpus and memory size are not important, the only thing you should care is that the number of blk-queues is 4, below is the VM's xml for vhost_controllers.
```
    <disk type='network' device='disk'>
      <driver name='qemu' type='raw' cache='none'/>
      <source protocol='vhost' name='/var/run/spdk/vhost_socket-nvme0n1'/>
      <blockio logical_block_size='512' physical_block_size='512'/>
      <target dev='vdf' bus='virtio' queues='4' reconnect='0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </disk>
```
5. Make xfs file system for those 2 vbdevs in the VM and then mount them for 2 dirs.
```
mkfs.xfs -f /dev/vdb
mkfs.xfs -f /dev/vdc
mount /dev/vdb vdb
mount /dev/vdc vdc
```
6. Enter one of the dir for step3 and create a bigfile of 100G.
```
cd vdb
create a random big file of 100G.
```
7. Copy that bigfile from dir1 to dir2. 
```
cp vdb/bigfile vdc/
```
8. Md5sum for those 2 bigfiles.
```
md5sum vdb/bigfile >vdb_md5sum.txt
md5sum vdc/bigfile >vdc_md5sum.txt
```
I find that md5 values for those 2 bigfiles are different.

### Scenario 2
step 1 ~ 4 is just as screnario 1.
5. Make xfs file system for those 2 vbdevs in the VM for 10 times
```
mkfs.xfs -f /dev/vdb
mkfs.xfs -f /dev/vdc
```
You will see the metadata corruption when doing xfs file system.
```
[root@VM_6_151_centos ~]# mkfs.xfs -f /dev/vdc
meta-data=/dev/vdc        isize=512    agcount=4, agsize=244188662 blks
                =                       sectsz=4096  attr=2, projid32bit=1
                =                       crc=1        finobt=0, sparse=0
data         =                       bsize=4096   blocks=976754646, imaxpct=5
                =                       sunit=0      swidth=0 blks
naming    =version 2         bsize=4096   ascii-ci=0 ftype=1
log           =internal log     bsize=4096   blocks=476930, version=2
                =                        sectsz=4096  sunit=1 blks, lazy-count=1
realtime =none                  extsz=4096   blocks=0, rtextents=0
bad magic number
bad magic number
Metadata corruption detected at xfs_sb block 0x0/0x1000
libxfs_writebufr: write verifer failed on xfs_sb bno 0x0/0x1000
releasing dirty buffer (bulk) to free list![root@VM_6_151_centos ~]#
```

## Context (Environment including OS version, SPDK version, etc.)
OS version for Host: 3.10.0-693
OS version for VM: 3.10.0-862.el7.x86_64(not important)
SPDK version: SPDK v21.01-pre git sha1 6d9d3f8
DPDK version: DPDK 20.08.0
NVMe module_number: INTEL SSDPF2KX038TZ(P5510), INTEL SSDPE2KX040T8(P4510)

**Comment by changpe1** [comment] 2021-01-12 03:26
@ufo19890607 Do you see any error log in SPDK vhost target ? is the issue still exist when switching to vfio driver?

**Comment by ufo19890607** [comment] 2021-01-12 03:49
> @ufo19890607 Do you see any error log in SPDK vhost target ? 
No, I don't find any error in spdk vhost log.
> is the issue still exist when switching to vfio driver?
No, this issue will disappear when binding vfio driver for NVMe P5510.

**Comment by changpe1** [comment] 2021-01-12 06:16
> > @ufo19890607 Do you see any error log in SPDK vhost target ?
> > No, I don't find any error in spdk vhost log.
> > is the issue still exist when switching to vfio driver?
> > No, this issue will disappear when binding vfio driver for NVMe P5510.

Is this issue only related with P5510 drives? Have you tried other drives?

**Comment by ufo19890607** [comment] 2021-01-12 06:34
> > > @ufo19890607 Do you see any error log in SPDK vhost target ?
> > > No, I don't find any error in spdk vhost log.
> > > is the issue still exist when switching to vfio driver?
> > > No, this issue will disappear when binding vfio driver for NVMe P5510.
> 
> Is this issue only related with P5510 drives? Have you tried other drives?

I only found this issue on P5510 driver , and P4510 is OK.

**Comment by changpe1** [comment] 2021-01-12 07:00
That's interesting, I have a patch https://review.spdk.io/gerrit/c/spdk/spdk/+/5857, can you try with it ?

**Comment by ufo19890607** [comment] 2021-01-12 07:03
> That's interesting, I have a patch https://review.spdk.io/gerrit/c/spdk/spdk/+/5857, can you try with it ?

Ok, I will try it later, thx.

**Comment by ufo19890607** [comment] 2021-01-12 09:05
> That's interesting, I have a patch https://review.spdk.io/gerrit/c/spdk/spdk/+/5857, can you try with it ?

Unfortunately, this issue still exists!

**Comment by changpe1** [comment] 2021-01-12 09:14
For the IO path, the only difference between P4510 and P5510 is SGL feature, you may hardcode sgl_supported in nvme_pcie_qpair_submit_request() in nvme_pcie.c to false, and see the result.

**Comment by ufo19890607** [comment] 2021-01-12 13:25
The md5 value is still different.  I've also found the same issue on P4510 drive.  Sorry for not providing the correct information. This issue seems to be not related to SGL feature but to UIO driver only.

**Comment by changpe1** [comment] 2021-01-14 03:00
> The md5 value is still different. I've also found the same issue on P4510 drive. Sorry for not providing the correct information. This issue seems to be not related to SGL feature but to UIO driver only.

OK, so for now the issue is only related with UIO, the issue didn't happen when using VFIO driver.
VFIO driver is more safe as it can pin the pages so that the pages can't be swapped during the IO processing, for the UIO driver, maybe you can try to use mlock() in SPDK to protect the memory:
In vhost_session_mem_register() add mlock before spdk_mem_register(), and munlock() before spdk_mem_unregister() to see if it fix the issue or not.

**Comment by wanghailiangx** [comment] 2021-01-27 08:47
@ufo19890607  pPlease try https://review.spdk.io/gerrit/c/spdk/spdk/+/6120, thanks. Added mlock and munlock according to changpe1.

**Comment by shuhei-matsumoto** [comment] 2021-01-28 22:41
Link to the patch to fix this issue: https://review.spdk.io/gerrit/c/spdk/spdk/+/5970

**Comment by changpe1** [comment] 2021-02-02 02:56
Patch has been merged, closing this issue now.

**Closed by changpe1** 2021-02-02 02:56 UTC
Labels: Sighting
