### ISSUE TITLE
[sw_hotplug] Expected inserts 12 != actual inserts 11

### ISSUE THREAD

**Issue by mgerdts** [spdk/spdk#2764] opened 2022-11-07 16:29 UTC
# CI Intermittent Failure

sw_hotplug failed with a [trivial mapfile cleanup commit](https://review.spdk.io/gerrit/c/spdk/spdk/+/14584).

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/88952/archive/nvme-phy-autotest/build.log

## Execution failed at

```
00:20:43.074  Attaching to 0000:d8:00.0
00:20:44.238  Attaching to 0000:d9:00.0
00:20:46.142  Attached to 0000:d8:00.0
00:20:46.710  Attached to 0000:d9:00.0
00:20:46.710  unregister_dev: INTEL SSDPE2KX020T8  (BTLJ126204352P0BGN  )
00:20:46.710  unregister_dev: INTEL SSDPE2MD400G4  (CVFT6176004P400GGN  )
00:20:46.710  unregister_dev: INTEL SSDPE2MD400G4  (CVFT6123001Z400GGN  )
00:20:47.648   08:26:44	-- nvme/sw_hotplug.sh@22 -- # (( hotplug_events-- ))
00:20:47.648   08:26:44	-- nvme/sw_hotplug.sh@84 -- # sleep 6
00:20:49.553  Expected inserts 12 != actual inserts 11
00:20:53.749   08:26:50	-- nvme/sw_hotplug.sh@86 -- # kill -0 1532058
00:20:53.749  test/nvme/sw_hotplug.sh: line 86: kill: (1532058) - No such process
```

**Comment by spdkci** [comment] 2022-11-07 16:31
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_88952.html

**Comment by jimharris** [comment] 2022-11-07 17:13
Thanks @mgerdts.  This is actually a duplicate of #2201 which was closed, making it hard to find.  There have been some other reports against #2201 recently as well.  I just reopened #2201, and copied your failing case over to that one.  So I'm going to close this issue.

**Closed by jimharris** 2022-11-07 17:13 UTC
Labels: Intermittent Failure

**Comment by spdkci** [comment] 2022-12-09 09:38
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_92339.html
