### ISSUE TITLE
Compared with V23.01, the latest SPDK code has a write performance degradation problem in RDMA scenarios

### ISSUE THREAD

**Issue by xupeng-mingtu** [spdk/spdk#3396] opened 2024-06-03 03:33 UTC
# Sighting report

Compared with V23.01, the latest SPDK code has a write performance degradation problem in RDMA scenarios

## Expected Behavior

The latest version of the code has the same write performance as v23.01 in RDMA scenarios

## Current Behavior

the write-avg-latency in nvmf-tgt is higher than v23.01

## Possible Solution

Not sure how to fix. But it may be introduced by this patch(https://review.spdk.io/gerrit/c/spdk/spdk/+/19125)

## Steps to Reproduce

Initiate io pressure to nvmf_tgt of v23.01 and v24.01, and ovserve the write io latency.
Maybe it's because fio's pressure mode is fixed, It is hard to reproduce this problem by fio. 
It can be reproduced using blktrace from online database scenarios.

## Context (Environment including OS version, SPDK version, etc.)
SPDK version：spdk-v24.01

**Comment by xupeng-mingtu** [comment] 2024-06-03 03:43
When I upgraded from v23.01 to v24.01, I found that the latency at the nvmf-tgt layer increased and there were many write io latency glitches. 

I reported this issue in [slack](https://spdk-team.slack.com/archives/CPQCY1XCL/p1715931041901839) and got a [fix patch](https://review.spdk.io/gerrit/c/spdk/spdk/+/23302), the patch really solves the problem of writing io latency glitches and decrease the avg latency, but the avg-latency in nvmf-tgt is still higher than v23.01.

**Comment by xupeng-mingtu** [comment] 2024-06-03 03:51
I did some test and I found that It seems that this patch(https://review.spdk.io/gerrit/c/spdk/spdk/+/19125) caused this problem. This is my test info:

1. I built a new patch which is based on (https://review.spdk.io/gerrit/c/spdk/spdk/+/23302) and revert (https://review.spdk.io/gerrit/c/spdk/spdk/+/19125)
2. I have a blktrace file which is record a disk serviced for PIKA database, I replayed this blktrace with fio to a bdev privided with both patch
3. When using https://review.spdk.io/gerrit/c/spdk/spdk/+/23302, the target latency is 120us+
![image](https://github.com/spdk/spdk/assets/144994281/403734f3-6f72-48bd-841b-db8e1c35227e)
4. When using new patch, the target latency is 45us+
![image](https://github.com/spdk/spdk/assets/144994281/91298fd7-81b6-43ca-b942-62e2d3c7f235)
5. When using v23.01, the target latency is 45us+
![image](https://github.com/spdk/spdk/assets/144994281/11fbdf2d-5d53-420c-9311-2547985f2ea7)

**Comment by AlekseyMarchuk** [comment] 2024-06-03 09:00
Hi, thanks for the detailed analysis!
The patch that you mentioned changes how target handles NVMF WRITE IO commands with SGL descriptor list. In my tests, depending on the number of SGL entries, the patch works either much faster or the same as parent version. Maybe the tool that you used produces some specific workload (e.g. various amount of SGL descriptors in every IO) and it causes latency increase. Is that possible that you add extra logs to `nvmf_rdma_request_fill_iovs_multi_sgl` function in `lib/nvmf/rdma.c` to understand what is the average IO pattern? E.g. the number of SGL descriptors and size of each descriptor, I guess short run (few seconds) would be enough. Without this data it is hard to debug this problem.

**Comment by xupeng-mingtu** [comment] 2024-06-04 03:50
> Hi, thanks for the detailed analysis! The patch that you mentioned changes how target handles NVMF WRITE IO commands with SGL descriptor list. In my tests, depending on the number of SGL entries, the patch works either much faster or the same as parent version. Maybe the tool that you used produces some specific workload (e.g. various amount of SGL descriptors in every IO) and it causes latency increase. Is that possible that you add extra logs to `nvmf_rdma_request_fill_iovs_multi_sgl` function in `lib/nvmf/rdma.c` to understand what is the average IO pattern? E.g. the number of SGL descriptors and size of each descriptor, I guess short run (few seconds) would be enough. Without this data it is hard to debug this problem.

**Comment by xupeng-mingtu** [comment] 2024-06-04 06:47
> Hi, thanks for the detailed analysis! The patch that you mentioned changes how target handles NVMF WRITE IO commands with SGL descriptor list. In my tests, depending on the number of SGL entries, the patch works either much faster or the same as parent version. Maybe the tool that you used produces some specific workload (e.g. various amount of SGL descriptors in every IO) and it causes latency increase. Is that possible that you add extra logs to `nvmf_rdma_request_fill_iovs_multi_sgl` function in `lib/nvmf/rdma.c` to understand what is the average IO pattern? E.g. the number of SGL descriptors and size of each descriptor, I guess short run (few seconds) would be enough. Without this data it is hard to debug this problem.

this is my LOG line:
![image](https://github.com/spdk/spdk/assets/144994281/92533fd7-1bdf-4b8e-bf38-f54746d2a166)
the log output is:
![image](https://github.com/spdk/spdk/assets/144994281/9ee07386-a40f-4a34-a43c-6c692ce0a9df)
the full log file is:
[nvmf-target.log](https://github.com/user-attachments/files/15543651/nvmf-target.log)

**Comment by AlekseyMarchuk** [comment] 2024-06-05 11:19
I tried to reproduce this issue using spdk_nvme_perf tool with `-O` option to split payload in 2 buffers. I got the same latency with/without https://review.spdk.io/gerrit/c/spdk/spdk/+/19125
As I wrote before, with number of SGL descriptors 2,4,8 there should be absolutely no difference vs v23.01 since in that case we fully utilize RDMA_READ queue and don't do partial sends.
```
# v24.01 + revert of https://review.spdk.io/gerrit/c/spdk/spdk/+/19125 QD 1
## 2 sgls
                                                                                                                Latency(us)
Device Information                                                          :       IOPS      MiB/s    Average        min        max
RDMA (addr:172.16.3.0 subnqn:nqn.2018-09.io.spdk:cnode0) NSID 1 from core  1:   40008.97    5001.12      24.98      23.78     145.56
## 1 sgl
                                                                                                                Latency(us)
Device Information                                                          :       IOPS      MiB/s    Average        min        max
RDMA (addr:172.16.3.0 subnqn:nqn.2018-09.io.spdk:cnode0) NSID 1 from core  1:   40001.27    5000.16      24.99      24.28     172.37

# v24.01 QD 1
## 2 sgls
                                                                                                                Latency(us)
Device Information                                                          :       IOPS      MiB/s    Average        min        max
RDMA (addr:172.16.3.0 subnqn:nqn.2018-09.io.spdk:cnode0) NSID 1 from core  1:   40008.57    5001.07      24.98      23.76     197.63
## 1 sgl 
                                                                                                                Latency(us)
Device Information                                                          :       IOPS      MiB/s    Average        min        max
RDMA (addr:172.16.3.0 subnqn:nqn.2018-09.io.spdk:cnode0) NSID 1 from core  1:   39740.80    4967.60      25.15      24.25     225.08
```

@xupeng-mingtu could you try the same tool on your setup to check if you can reproduce the latency issue? I used the following parameters:`spdk_nvme_perf -q 1 -o 131072 -O 65536  -w randwrite -t 30 -r 'trtype:RDMA adrfam:IPV4 traddr:172.16.3.0 trsvcid:4420' -c 0x2`
P.S. tried qdepth up to 64, results were the same. Target and initiator were running with mask 0x2, on different hosts connected via switch. HCA was ConnectX-7

**Comment by xupeng-mingtu** [comment] 2024-06-06 03:48
yes, I can reproduce the issue with your command: `spdk_nvme_perf -q 64 -o 131072 -O 65536 -w randwrite -t 30 -r 'trtype:RDMA adrfam:IPV4 traddr:10.1.57.37 trsvcid:12345' -c 0x2`, but it only can be reproduced with big qdepth, eg.64.

```shell
# (https://review.spdk.io/gerrit/c/spdk/spdk/+/23302) + revert of https://review.spdk.io/gerrit/c/spdk/spdk/+/19125 QD 64
## 2 sgls
                                                                                                                           Latency(us)
Device Information                                                                     :       IOPS      MiB/s    Average        min        max
RDMA (addr:10.1.57.37 subnqn:nqn.2022-08.io.spdk:vm1680-1029768-da) NSID 1 from core  1:   13288.60    1661.08    4811.91     130.05   63570.84
========================================================
Total                                                                                  :   13288.60    1661.08    4811.91     130.05   63570.84

the latency in nvmf-target
Device    tps       MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn  MB_dscd  qu-sz  aqu-sz  wareq-sz  rareq-sz  w_await(us)  r_await(us)  util
NVMe89n1  13279.21  0.00       1659.90    0.00       0.00     1673.25  0.00     2.00   1.77    256.00    0.00      80.54        0.00         0.60

# (https://review.spdk.io/gerrit/c/spdk/spdk/+/23302) QD 64
## 2 sgls
                                                                                                                           Latency(us)
Device Information                                                                     :       IOPS      MiB/s    Average        min        max
RDMA (addr:10.1.57.37 subnqn:nqn.2022-08.io.spdk:vm1680-1029768-da) NSID 1 from core  1:   13048.80    1631.10    4900.72     130.93   61890.00
========================================================
Total                                                                                  :   13048.80    1631.10    4900.72     130.93   61890.00

the latency in nvmf-target:

Device    tps       MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn  MB_dscd  qu-sz  aqu-sz  wareq-sz  rareq-sz  w_await(us)  r_await(us)  util
NVMe89n1  13148.23  0.00       1643.53    0.00       0.00     1656.75  0.00     0.00   4.73    256.00    0.00      202.82       0.00         0.57

```

**Comment by xupeng-mingtu** [comment] 2024-06-06 03:54
> yes, I can reproduce the issue with your command: `spdk_nvme_perf -q 64 -o 131072 -O 65536 -w randwrite -t 30 -r 'trtype:RDMA adrfam:IPV4 traddr:10.1.57.37 trsvcid:12345' -c 0x2`, but it only can be reproduced with big qdepth, eg.64.
> 
> ```shell
> # (https://review.spdk.io/gerrit/c/spdk/spdk/+/23302) + revert of https://review.spdk.io/gerrit/c/spdk/spdk/+/19125 QD 64
> ## 2 sgls
>                                                                                                                            Latency(us)
> Device Information                                                                     :       IOPS      MiB/s    Average        min        max
> RDMA (addr:10.1.57.37 subnqn:nqn.2022-08.io.spdk:vm1680-1029768-da) NSID 1 from core  1:   13288.60    1661.08    4811.91     130.05   63570.84
> ========================================================
> Total                                                                                  :   13288.60    1661.08    4811.91     130.05   63570.84
> 
> the latency in nvmf-target
> Device    tps       MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn  MB_dscd  qu-sz  aqu-sz  wareq-sz  rareq-sz  w_await(us)  r_await(us)  util
> NVMe89n1  13279.21  0.00       1659.90    0.00       0.00     1673.25  0.00     2.00   1.77    256.00    0.00      80.54        0.00         0.60
> 
> # (https://review.spdk.io/gerrit/c/spdk/spdk/+/23302) QD 64
> ## 2 sgls
>                                                                                                                            Latency(us)
> Device Information                                                                     :       IOPS      MiB/s    Average        min        max
> RDMA (addr:10.1.57.37 subnqn:nqn.2022-08.io.spdk:vm1680-1029768-da) NSID 1 from core  1:   13048.80    1631.10    4900.72     130.93   61890.00
> ========================================================
> Total                                                                                  :   13048.80    1631.10    4900.72     130.93   61890.00
> 
> the latency in nvmf-target:
> 
> Device    tps       MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn  MB_dscd  qu-sz  aqu-sz  wareq-sz  rareq-sz  w_await(us)  r_await(us)  util
> NVMe89n1  13148.23  0.00       1643.53    0.00       0.00     1656.75  0.00     0.00   4.73    256.00    0.00      202.82       0.00         0.57
> ```

my config.json in target:
```json
{
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "method": "bdev_nvme_attach_controller",
          "params": {
            "name": "NVMe89",
            "trtype": "PCIe",
            "traddr": "0000:89:00.0",
            "prchk_reftag": false,
            "prchk_guard": false,
            "ctrlr_loss_timeout_sec": 0,
            "reconnect_delay_sec": 0,

            "num_shared_buffers": 4095,
            "buf_cache_size": 32,
            "dif_insert_or_strip": false,
            "zcopy": false,
            "max_srq_depth": 4096,
            "no_srq": false,
            "acceptor_backlog": 100,
            "no_wr_batching": false,
            "abort_timeout_sec": 1,
            "ack_timeout": 0,
            "data_wr_pool_size": 4095
          }
        },
        {
          "method": "nvmf_create_subsystem",
          "params": {
            "nqn": "nqn.2022-08.io.spdk:vm1680-1029768-da",
            "allow_any_host": true,
            "serial_number": "SPDK00000000000001",
            "model_number": "SPDK_Controller",
            "max_namespaces": 32,
            "min_cntlid": 1,
            "max_cntlid": 65519,
            "ana_reporting": false
          }
        },
        {
          "method": "nvmf_subsystem_add_ns",
          "params": {
            "nqn": "nqn.2022-08.io.spdk:vm1680-1029768-da",
            "namespace": {
              "nsid": 1,
              "bdev_name": "7433140e-e7f2-4d0f-a12a-4732ffc1c81c",
              "nguid": "7433140EE7F24D0FA12A4732FFC1C81C",
              "uuid": "7433140e-e7f2-4d0f-a12a-4732ffc1c81c"
            }
          }
        },
        {
          "method": "nvmf_subsystem_add_listener",
          "params": {
            "nqn": "nqn.2022-08.io.spdk:vm1680-1029768-da",
            "listen_address": {
              "trtype": "RDMA",
              "adrfam": "IPv4",
              "traddr": "10.1.57.37",
              "trsvcid": "12345"
            },
            "secure_channel": false
          }
        }
      ]
    }
  ]
}
```
my target start command: `nvmf_tgt -c 0x2 --rpc-socket /var/run/nbs/nbs_89.sock --config ./config.json`
my test command: `spdk_nvme_perf -q 64 -o 131072 -O 65536 -w randwrite -t 30 -r 'trtype:RDMA adrfam:IPV4 traddr:10.1.57.37 trsvcid:12345' -c 0x2`

**Comment by xupeng-mingtu** [comment] 2024-06-18 04:23
@AlekseyMarchuk Hi Aleksey, I seem to have found the cause of the problem: although req_a is reinserted into the head of pending_rdma_read_queue when read is completed, but if there is another req_b in the subsequent wc that are also submitted read-op separately, then req_b will become the new head, causing req_a to not be processed quickly, may be the code can like this: https://review.spdk.io/gerrit/c/spdk/spdk/+/23748, I have test the patch, under the same test conditions, the target latency of this patch is at the same level as v2301.

**Comment by AlekseyMarchuk** [comment] 2024-06-18 05:26
@xupeng-mingtu cool idea, I think you are right!
I'll review your patch and trigger some additional tests

**Comment by AlekseyMarchuk** [comment] 2024-06-19 13:57
@xupeng-mingtu your patch is merged, thank you for fixing the issue!

**Closed by AlekseyMarchuk** 2024-06-19 13:57 UTC
Labels: bug, Medium

**Comment by mchomnic** [comment] 2024-06-19 14:13
@AlekseyMarchuk , shall I backport the patch to v24.01 and v24.05?

**Comment by AlekseyMarchuk** [comment] 2024-06-19 14:23
@mchomnic yes please backport this patch
