### ISSUE TITLE
spdk librararies are not recognized in the IDE

### ISSUE THREAD

**Issue by yasharzb** [spdk/spdk#2236] opened 2021-11-12 08:18 UTC
# Bug report

Recognized libraries

## Current Behavior

After configuring with shared libraries, I expected that developing a simple program would be easier with an IDE. But `spdk/*` libraries are not recognized.

![spdk_libraries](https://user-images.githubusercontent.com/45389623/141433963-3a771dec-f297-4e7d-b1af-631f1c36baf7.png)

## Possible Solution

Maybe one or two steps are missing from the instruction.

## Steps to Reproduce

All commands are executed with `sudo`
1. `./configure --with-shared`
2. `make`
3. `ldconfig -v -n ./build/lib`
4. `LD_LIBRARY_PATH=./build/lib/:./dpdk/build/lib/ ./build/bin/spdk_tgt`

I must say that the last command failed, because I am writing my program with a PC (which doesn't have NVMe family SSD, just a normal one.). After this, I'll build my program in an Ubuntu server which meets the hardware requirements. 

![image](https://user-images.githubusercontent.com/45389623/141433792-b3f1503a-21ef-4c15-9a36-c4ef6528c7f9.png)

## Context (Environment including OS version, SPDK version, etc.)

Ubuntu 21.10
SPDK 21.10 + [this patch](https://review.spdk.io/gerrit/c/spdk/spdk/+/10199)

**Comment by AlekseyMarchuk** [comment] 2021-11-12 08:32
Hi, it looks like the problem is not in shared libraries, your IDE can't find a path to SPDK includes. Usually each IDE can be configured with non-standard paths to include files (like -I compiler flag). Try to add path to spdk/include directory to your IDE

**Comment by jimharris** [comment] 2021-12-22 00:19
Closing, this looks like a problem with the submitter's IDE configuration.

**Closed by jimharris** 2021-12-22 00:19 UTC
Labels: 3rd party issue, Sighting
