### ISSUE TITLE
nvme discover shows all target subsystems, even those that are not accessible by the host

### ISSUE THREAD

**Issue by ShaharSalzman-K** [spdk/spdk#576] opened 2019-01-15 09:00 UTC
When using access control list from the nvmf subsystem, a host performing a discover to the given IP will receive information about all the subsystems on the IP, even those to which it does not have access.

## Expected Behavior
Only subsystems to which this host has access to, i.e. subsystems which allow all hosts, or subsystems to which this host has been added to the ACL.

## Current Behavior
The host can see all the subsystems on the IP

## Possible Solution
On response to discover command, check the access control list of the subsystem before returning its information

## Steps to Reproduce
1. Target - Create subsystem, do use the --allow-any-host flag
2. Target - Create access control list with nvmf_subsystem_add_host
3. Initiator - run "nvme discover" on the target IP (all the subsystems should be visible)

## Context (Environment including OS version, SPDK version, etc.)
Tested on spdk 18.10 compiled on RHEL 6.4 with kernel 4.9.102.
Initiator is RHEL versions 7.4, 7.5, 7.6 or RHEL 6.4 with kernel 4.9.6 with OFED NVMeF drivers.

**Comment by darsto** [comment] 2019-07-16 12:44
This is still reproducible

**Comment by yidong0635** [comment] 2019-07-17 06:14
issue can be traced，
out target  start with `spdk_add_nvmf_discovery_subsystem` which 
setting `spdk_nvmf_subsystem_set_allow_any_host(subsystem, true);`

without using conf file to start target ,but using rpc method to create subsystem.
"`./scripts/rpc.py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode2  -s SPDK00000000000002`"

nvme discovery report error about input/output errors:
target side: `ctrlr.c: 541:spdk_nvmf_ctrlr_connect: *ERROR*: Subsystem 'nqn.2014-08.org.nvmexpress.discovery' does not allow host 'nqn.2014-08.org.nvmexpress:uuid:f1fcc2fb-37a8-4fae-8074-28bf9f9f4cd2'`
that means if  there's one subsystem that not allowed to host , will report error about 
"Failed to write to /dev/nvme-fabrics: Input/output error“  if not do “`spdk_nvmf_subsystem_set_allow_any_host(subsystem, true);`”

**Comment by changpe1** [comment] 2019-07-18 06:23
I can take a look of this issue to see we can get it fixed before this release.

**Comment by changpe1** [comment] 2019-07-18 09:25
I posted  a patch https://review.gerrithub.io/c/spdk/spdk/+/462440 to fix the issue.

**Comment by yidong0635** [comment] 2019-07-23 01:47
I verify this issue on my side, it  looks good for me, maybe other peoples have more test requirements.

**Comment by changpe1** [comment] 2019-07-25 07:27
I post another patch to fix 2 Hosts issue, here is the patch https://review.gerrithub.io/c/spdk/spdk/+/463123, it will always update the discovery log if offset is not zero.

**Comment by changpe1** [comment] 2019-07-26 01:28
Patch has been merged, I'm going to close this issue for now.

**Closed by changpe1** 2019-07-26 01:28 UTC
Labels: Medium, bug, enhancement

**Comment by govind-rathod1987** [comment] 2019-12-03 12:18
Looks like the latest master branch does not have these changes. Can you please let me know which branch this fix is committed? can i get access to the branch ?

**Comment by tomzawadzki** [comment] 2019-12-17 16:21
@govind-rathod1987 Both of the linked patches were put onto SPDK master branch, just before SPDK 19.07 release. Are you still seeing this issue on current SPDK master ?

**Comment by Cindy-010** [comment] 2019-12-20 03:44
Hi guys,
Can you please let me know which branch? I used the latest branch v19.10x , but we didn't get the right code in branch
