### ISSUE TITLE
[N/A] tar: spdk/test/rpc_plugins: Directory renamed before its status could be extracted

### ISSUE THREAD

**Issue by slawekptak** [spdk/spdk#3521] opened 2024-09-06 09:46 UTC
```
Saving response body to /var/jenkins/workspace/vhost-phy-autotest/spdk_8cb1ee7bc5602763f60c19ede3926789446eb529.tar.gz
00:01:10.284  [Pipeline] }
00:01:10.301  [Pipeline] // retry
00:01:10.309  [Pipeline] sh
00:01:10.631  + tar --no-same-owner -xf spdk_8cb1ee7bc5602763f60c19ede3926789446eb529.tar.gz
00:01:13.186  tar: spdk/test/rpc_plugins: Directory renamed before its status could be extracted
00:01:13.186  tar: spdk/test/external_code/hello_world: Directory renamed before its status could be extracted
00:01:13.186  tar: spdk/test/external_code: Directory renamed before its status could be extracted
00:01:13.186  tar: Exiting with failure status due to previous errors
00:01:13.201  [Pipeline] }
00:01:13.218  [Pipeline] // stage
00:01:13.225  [Pipeline] }
00:01:13.242  [Pipeline] // wrap
00:01:13.248  [Pipeline] }
00:01:13.251  ERROR: script returned exit code 2
00:01:13.251  Setting overall build result to FAILURE
00:01:13.263  [Pipeline] // catchError
00:01:13.272  [Pipeline] stage
00:01:13.273  [Pipeline] { (Epilogue)
00:01:13.284  [Pipeline] catchError
00:01:13.285  [Pipeline] {
00:01:13.295  [Pipeline] echo
00:01:13.296  Cleanup processes
```

**Comment by spdkci** [comment] 2024-09-06 09:47
Another instance of this failure. Reported by @slawekptak. log: https://ci.spdk.io/public_build/autotest-per-patch_129366.html

**Comment by mikeBashStuff** [comment] 2024-09-09 08:29
This is peculiar, not sure what might have caused this. Will try to investigate.

**Comment by mikeBashStuff** [comment] 2024-09-12 11:53
Ok, so this stems from how our phy nodes are being set up in terms of the rootfs - all our phy nodes, which take part in per-patch, don't have an actual storage, everything is kept in memory. So for rootfs, we have an underlying squashfs image with an overlayfs on top. 

The reason why `tar` complained here is because, while it was extracting the archive, inodes of the target directories changed. This happened, most likely, because at the very same time kernel decided to reclaim memory used for inodes cache. Since there's no actual backing disk to read back inodes from, it's likely that we are hitting quirks specific to squashfs and at the end we get a completely fresh inode allocated for the very same file (directory, to be exact).

This can be quite easily reproduced actually:
```
# mkdir -p foo; ls -di foo; echo 2 >/proc/sys/vm/drop_caches; ls -di foo
16041 foo
16050 foo
# mkdir -p foo; ls -di foo; echo 2 >/proc/sys/vm/drop_caches; ls -di foo
16050 foo
16056 foo
```

and while extracting archive:
```
# tar -xzf ./spdk_8cb1ee7bc5602763f60c19ede3926789446eb529.tar.gz  & sleep 0.1; echo 2 >/proc/sys/vm/drop_caches
[1] 2338
# tar: spdk/test/rpc_plugins: Directory renamed before its status could be extracted
tar: spdk/test/external_code/hello_world: Directory renamed before its status could be extracted
tar: spdk/test/external_code: Directory renamed before its status could be extracted
tar: spdk/test: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
[1]+  Exit 2                  tar -xzf ./spdk_8cb1ee7bc5602763f60c19ede3926789446eb529.tar.gz
```

I don't believe there's an obvious way how we could "force" inode preservation here. We could tell kernel to try to retain cache for longer (or tell it to not clear it at all) but considering how rare this issue is I am not sure what value would be best for the appropriate knob (without introducing a risk of running out of memory for instance). 

I think the easiest solution is to simply make sure that `tar` is performing the extraction under different fs, like tmpfs and then we just mv the contents into the right place.

**Comment by mikeBashStuff** [comment] 2024-09-12 17:08
Actually, the reproducer should be more like this:

```
tar -xzf whatever & while echo 2 >/proc/sys/vm/drop_caches; do :; done
```

since all this is still a quite racy.

**Comment by mikeBashStuff** [comment] 2024-09-13 08:01
We put a workaround in place on the jenkins side, so closing this for now.

**Closed by mikeBashStuff** 2024-09-13 08:01 UTC
Labels: Intermittent Failure
