### ISSUE TITLE
RPM build library destinations inconsistent with generated pkgconfig

### ISSUE THREAD

**Issue by tanabarr** [spdk/spdk#2531] opened 2022-05-26 19:43 UTC
# Bug report

I trying to build SPDK RPM yields the following lint error:
`pkgconfig-invalid-libs-dir /usr/lib64/pkgconfig/spdk_accel.pc Libs: -L/usr/lib  -lspdk_accel`
This looks like a valid problem. libspdk_accel.so is actually in /usr/lib64 (which seems unusual as they should be in their own dir as they are not public libs) but /usr/lib64/pkgconfig/spdk_accel.pc is saying it is in /usr/lib:
```
Description: SPDK accel library
Name: spdk_accel
Version: 8.0
Libs: -L/usr/lib  -lspdk_accel
Requires: spdk_log spdk_util spdk_thread spdk_json spdk_accel_modules
Libs.private: 
Cflags: -I/usr/include

```
To see why it was supplying the /usr/lib dir and could only end up finding https://github.com/spdk/spdk/blob/v22.01.x/scripts/pc.sh#L6. I couldn't follow the trail back to see why $1 to that script was /usr when in fact it should probably be something like /usr/lib64/spdk/ and all of those private .so files should be in that dir.

Can anyone shed light on this? It may well be something incorrect with my spdk.spec: https://github.com/daos-stack/spdk/pull/47/files/fd3be59285e44b76d355e404162cfaf5088fe2c3#diff-ad3dcd634d075bdb3384fefa1b1436eb0c5aa384cd4bb8f310e121a802e2a1b1

## Expected Behavior

Build result location should align with pkgconfig descriptions.

## Current Behavior

As described above.

## Steps to Reproduce

Link to specfile used to build above.

## Context (Environment including OS version, SPDK version, etc.)

Rocky Linux 8.5 
SPDK 22.01.1
DPDK 21.11.1

**Comment by yidong0635** [comment] 2022-05-27 01:27
I'm not the expert, but I checked the local code:
```
Description: SPDK accel library
Name: spdk_accel
Version: 9.0
Libs: -L/usr/local/lib  -lspdk_accel
Requires: spdk_log spdk_util spdk_thread spdk_json spdk_accel_modules
Libs.private:
Cflags: -I/usr/local/include

```
It seems  you need to specify:
./configure -h
` --prefix=path             Configure installation prefix (default: /usr/local)`

**Comment by tanabarr** [comment] 2022-05-30 08:45
So I am working on the SPDK RPM that we build to satisfy our DAOS RPM requirements,  this is distinct from the DAOS source build.
The source build doesn't have this problem because we don't supply a pkgconfig file when building in scons and is configured as follows:
```
360     reqs.define('spdk',
361                 retriever=GitRepoRetriever('https://github.com/spdk/spdk.git', True),
362                 commands=[['./configure',
363                            '--prefix=$SPDK_PREFIX',
364                            '--disable-tests',
365                            '--disable-unit-tests',
366                            '--disable-apps',
367                            '--without-vhost',
368                            '--without-crypto',
369                            '--without-pmdk',
370                            '--without-rbd',
371                            '--with-rdma',
372                            '--without-iscsi-initiator',
373                            '--without-isal',
374                            '--without-vtune',
375                            '--with-shared'],
376                           ['make', 'CONFIG_ARCH={}'.format(spdk_arch)],
377                           ['make', 'install'],
378                           ['cp', '-r', '-P', 'dpdk/build/lib/', '$SPDK_PREFIX'],
379                           ['cp', '-r', '-P', 'dpdk/build/include/', '$SPDK_PREFIX/include/dpdk'],
380                           ['mkdir', '-p', '$SPDK_PREFIX/share/spdk'],
381                           ['cp', '-r', 'include', 'scripts', '$SPDK_PREFIX/share/spdk'],
382                           ['cp', 'build/examples/lsvmd', '$SPDK_PREFIX/bin/spdk_nvme_lsvmd'],
383                           ['cp', 'build/examples/nvme_manage', '$SPDK_PREFIX/bin/spdk_nvme_manage'],
384                           ['cp', 'build/examples/identify', '$SPDK_PREFIX/bin/spdk_nvme_identify'],
385                           ['cp', 'build/examples/perf', '$SPDK_PREFIX/bin/spdk_nvme_perf']],
386                 headers=['spdk/nvme.h', 'dpdk/rte_eal.h'],
387                 extra_include_path=['/usr/include/dpdk',
388                                     '$SPDK_PREFIX/include/dpdk',
389                                     # debian dpdk rpm puts rte_config.h here
390                                     '/usr/include/x86_64-linux-gnu/dpdk'],
391                 patch_rpath=['lib'])
```
As you can see here we are using in-tree dpdk build so things are a little different to the SPDK RPM build that uses a system installed DPDK (we also build DPDK RPMs).
The spdk.spec configure script is run as follows:
```
127 %build
128 ./configure --with-dpdk \
129             --prefix=%{_libdir} \
130             --disable-tests \
131             --disable-unit-tests \
132             --disable-apps \
133             --without-vhost \
134             --without-crypto \
135             --without-pmdk \
136             --without-rbd \
137             --with-rdma \
138             --without-iscsi-initiator \
139             --without-isal \
140             --without-vtune \
141             --with-shared
```
Changing the specfile `./configure --prefix` from `%{_prefix}` to `%{_libdir}` does seem to have helped. Thanks for the tip @yidong0635

**Comment by mikeBashStuff** [comment] 2022-05-30 09:05
Using `%{_libdir}` as a prefix looks a bit odd to me as it in context of the actual installation everything would be put under `/usr/lib{,64}` (or whatever `rpmbuild` evaluates this expr to, but for most rpm-based distros I believe it's indeed `/usr/lib64`). I am just wondering if maybe `mk/spdk.lib.mk -> pkgconfig_create` or `scripts/pc.sh` should dynamically determine the actual libdir (instead of hardcoding /lib as `CONFIG_PREFIX`'s basename). Or maybe we could just add support for setting `--libdir` (e.g. `CONFIG_LIBDIR`) via `./configure` and pass it then as a param to `pc.sh`.

**Comment by brianjmurrell** [comment] 2022-05-30 14:16
Indeed, `./configure --prefix=%{_libdir}` is **not** the correct solution.

It is not surprising that `./configure [--prefix=/usr/local`] works as expected because the problem is not the correct substitution of the `$prefix` but rather the hardcoded assumption that `$lib` under `$prefix` is always going to be `lib`.  On most distros, (at leas the RedHat flavours on 64-bit platforms) libraries are not put into `$prefix/lib` but rather `$prefix/lib64`.

If I am correctly locating the place where this happens we can see that the dir under `$prefix` is hardcoded to be `lib`: https://github.com/spdk/spdk/blob/c5c3dacca380e3016f65c9b4d6776fedebc50c18/scripts/pc.sh#L6

@tanabarr As a test/confirmation/workaround for this perhaps you can add this to your `spdk.spec`'s `%install` section:

```sh
sed -i -e 's/\(-L\$1\/\)lib/\1%{_lib}/' scripts/pc.sh
```

**Comment by tanabarr** [comment] 2022-05-30 17:13
workaround worked when placed in %prep, thanks

**Comment by tanabarr** [comment] 2022-05-30 17:14
passed build after reverting the prefix change and adding the workaround: commit https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fspdk/detail/PR-47/24/pipeline/186

**Comment by brianjmurrell** [comment] 2022-05-30 17:20
> passed build after reverting the prefix change and adding the workaround: commit https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fspdk/detail/PR-47/24/pipeline/186

Thanks for testing that @tanabarr.  This seems to confirm the issue of the `lib` dir being hard-coded in that script.

**Comment by jimharris** [comment] 2022-06-06 23:34
> Using `%{_libdir}` as a prefix looks a bit odd to me as it in context of the actual installation everything would be put under `/usr/lib{,64}` (or whatever `rpmbuild` evaluates this expr to, but for most rpm-based distros I believe it's indeed `/usr/lib64`). I am just wondering if maybe `mk/spdk.lib.mk -> pkgconfig_create` or `scripts/pc.sh` should dynamically determine the actual libdir (instead of hardcoding /lib as `CONFIG_PREFIX`'s basename). Or maybe we could just add support for setting `--libdir` (e.g. `CONFIG_LIBDIR`) via `./configure` and pass it then as a param to `pc.sh`.

Should we just go with this latter (--libdir/CONFIG_LIBDIR) option?

**Comment by brianjmurrell** [comment] 2022-06-08 03:06
> > Using `%{_libdir}` as a prefix looks a bit odd to me as it in context of the actual installation everything would be put under `/usr/lib{,64}` (or whatever `rpmbuild` evaluates this expr to, but for most rpm-based distros I believe it's indeed `/usr/lib64`). I am just wondering if maybe `mk/spdk.lib.mk -> pkgconfig_create` or `scripts/pc.sh` should dynamically determine the actual libdir (instead of hardcoding /lib as `CONFIG_PREFIX`'s basename). Or maybe we could just add support for setting `--libdir` (e.g. `CONFIG_LIBDIR`) via `./configure` and pass it then as a param to `pc.sh`.
> 
> Should we just go with this latter (--libdir/CONFIG_LIBDIR) option?

The disconnect here, it seems to me, is that the libraries are actually already put into a/the `--libdir` but it's just the _pkgconfig_ file(s) that are incorrectly saying they are somewhere else.  So this doesn't seem to me to be strictly just supporting a `--libdir` option but just being consistent between where the libs are being installed and where the _pkgconfig_ files say they are being installed.

Now that all said, **private** shared libs -- libs that are not intended to be consumed outside of spdk, shouldn't really be in `--libdir`'s location (i.e. `/usr/lib64`).  That location is for public (i.e. spdk ABI) libraries only and should represent stable interfaces verisoned with SOVERSION.  Internal-only shared libs should go into a private dir such as, perhaps, `/usr/lib64/spdk`.

**Comment by mikeBashStuff** [comment] 2022-06-08 13:08
Hmm. I think I am confused right now. So the more I look into the SPDK's .pc files, the less I see the actual issue discussed here. So the actual installation for the libs `libdir?=$(CONFIG_PREFIX)/lib` and .pc files also point at that very location. The problem occurs where someone overrides `libdir` upon installation (since we are discussing rpmbuild, I am guessing it happens through the environment). So in my mind, the request here is to make sure the libdir is picked up from said environment (or cmdline) while creating|installing .pc files. 

As for the private|public issue, I am completely out of my depth here. I can't really say, by looking through the repo, which libs should be considered as either private or public - under `./lib/*` I can see that all of the libs are SO_VERsioned so to me they are all public (including `./lib/accel/`) in that regard. For the rpmed dpdk I also don't see any lib landing in a private dir (so my guess would be that all its .sos are public as well) and its .pc files also point at a common dir locations. But again, I am not really sure how this should be handled so I am just thinking out loud here. :)

With all that said, here's the attempt to address some of what was discussed under this issue (currently marked as WIP): https://review.spdk.io/gerrit/c/spdk/spdk/+/12978 - any comments, suggestions are welcome there. :)

**Comment by brianjmurrell** [comment] 2022-06-09 00:36
I'm not surprised at your confusion.  It does seem confusing that there is no existing `-libdir` `configure` option and as such how can an RPM installation possibly be installing libraries in to `/usr/lib64/`.  It really does seem that there needs to be a `--libdir` `configure` option to align with _autotools_' `configure`.

In any case, here's our' [`specfile`](https://github.com/daos-stack/spdk/blob/master/spdk.spec) for reference.  I think perhaps the important part is https://github.com/daos-stack/spdk/blob/a546fbfcca8ef7069c376e8c922cd3138317f362/spdk.spec#L155.

I haven't had time to really study, or even _try out_ your proposed WIP but it appears to achieve the goal of implementing a `--libdir` `configure` option.

**Comment by tomzawadzki** [comment] 2022-06-14 15:12
Bug scrub: @mikeBashStuff Could you submit the https://review.spdk.io/gerrit/c/spdk/spdk/+/12978 patch for review (remove the WIP) ? It seems like a fine solution that we could go ahead with.

**Comment by mikeBashStuff** [comment] 2022-06-17 09:31
@tomzawadzki Sorry for the delay - I just rebased the patch and removed the WIP from the commit message as requested.

**Comment by ksztyber** [comment] 2022-07-26 10:35
@mikeBashStuff's patch was merged, @tanabarr does this solve your issue?

**Comment by tomzawadzki** [comment] 2022-08-23 14:57
Closing the issue since the patch was merged. @tanabarr Please feel free to re-open if the issue persists.

**Closed by tomzawadzki** 2022-08-23 14:57 UTC
Labels: bug, Low, Waiting on Submitter
