### ISSUE TITLE
nvmf_lvol failure - assert error

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#1181] opened 2020-02-04 17:29 UTC
Occasionally, on TP when running nvmf_lvol test following error is displayed:
  17:20:42	# /var/jenkins/workspace/NVMeOF_tests/nvmf_autotest/spdk/scripts/rpc.py bdev_lvol_snapshot 3010c18d-d7d1-4611-8fec-7d56d54d880b MY_SNAPSHOT
nvmf_tgt: blobstore.c:1170: _spdk_blob_serialize: Assertion `blob->state == SPDK_BLOB_STATE_DIRTY' failed.

Sample log: https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/59150/archive/nvmf_tcp_autotest/build.log

**Comment by spdkci** [comment] 2020-02-04 17:31
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59151.html

**Comment by spdkci** [comment] 2020-02-04 19:11
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59139.html

**Comment by jimharris** [comment] 2020-02-04 20:06
This is a duplicate of #1170 

I'll move these failures instances to that issue.

**Closed by jimharris** 2020-02-04 20:06 UTC
