### ISSUE TITLE
bdev_virtio_attach_controller with type user, dev_type blk  failed

### ISSUE THREAD

**Issue by jumpapex** [spdk/spdk#1316] opened 2020-03-25 14:09 UTC
bdev_virtio_attach_controller with type user, dev_type blk  failed

## Expected Behavior
It should succeed

## Current Behavior
It failed

## Possible Solution
N/A

## Steps to Reproduce
1. start vhost  (huge page size is 2 M)
    HUGEMEM=4096 scripts/setup.sh
    app/vhost/vhost -g -S /var/tmp
2.  scripts/rpc.py bdev_malloc_create 128 512 -b Malloc0
3.  scripts/rpc.py vhost_create_blk_controller --cpumask 0x1 vhost.1 Malloc0
4.  scripts/rpc.py  -s /var/tmp/spdk.sock bdev_virtio_attach_controller -t user -a /var/tmp/vhost.1 -d 
     blk virtioblk0
OUTPUT:
     request:
{
  "name": "virtioblk0",
  "trtype": "user",
  "traddr": "/var/tmp/vhost.1",
  "dev_type": "blk",
  "method": "bdev_virtio_attach_controller",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32602,
  "message": "Invalid argument"
}

at the same time: vhost will print:
VHOST_CONFIG: mmap region 1 failed. Cannot allocate memory
VHOST_CONFIG: Processing VHOST_USER_SET_MEM_TABLE failed.
VHOST_CONFIG: vhost message handling failed.

I add some debug message in vhost_user_set_mem_table, got the following message:
memory->nregions: 1
mmap_size: 494927872, fd: 21
memory->nregions: 2
mmap_size: 494927872, fd: 22
mmap_size: 494927872, fd: 23
memory->nregions: 2
mmap_size: 494927872, fd: 21
mmap_size: 989855744, fd: 24
memory->nregions: 2
mmap_size: 494927872, fd: 22
mmap_size: 1484783616, fd: 23
memory->nregions: 2
mmap_size: 494927872, fd: 21
mmap_size: 1979711488, fd: 24
memory->nregions: 2
mmap_size: 494927872, fd: 22
mmap_size: 2474639360, fd: 23
memory->nregions: 2
mmap_size: 494927872, fd: 21
mmap_size: 2969567232, fd: 24
memory->nregions: 2
mmap_size: 494927872, fd: 22
mmap_size: 3464495104, fd: 23
memory->nregions: 2
mmap_size: 494927872, fd: 21
mmap_size: 3959422976, fd: 24
It seems someone call vhost_user_set_mem_table again and again to exhaust the memory.

## Context (Environment including OS version, SPDK version, etc.)
CentOS 7.7 with 8G memory
dpdk version: 19.11
    make install T=x86_64-native-linux-gcc
spdk version: 20.01
    ./configure --with-vhost --with-virtio --with-dpdk=/root/source/dpdk-19.11/x86_64-native-linux-gcc
    make

**Comment by jumpapex** [comment] 2020-03-26 01:54
Further investigation:

**Comment by Donaim** [comment] 2020-03-26 16:26
This issue looks similar to #1206, but I doubt it is actually related.
I will investigate some more into this issue and try to reproduce on my setup.

**Comment by Comphix** [comment] 2020-04-01 03:53
@liang2yan , please also try to reproduce this one locally.

**Comment by liang2yan** [comment] 2020-04-01 05:08
I reproduced this issue with latest spdk master branch locally. The log is as below:

```
VHOST_CONFIG: mmap region 1 failed.
VHOST_CONFIG: Processing VHOST_USER_SET_MEM_TABLE failed.
VHOST_CONFIG: vhost message handling failed.
virtio_user/vhost_user.c:  97:vhost_user_read: *WARNING*: Failed to recv msg hdr: -1 instead of 12.
virtio_user/vhost_user.c: 393:vhost_user_sock: *WARNING*: Received msg failed: Connection reset by peer
virtio_user/vhost_user.c: 381:vhost_user_sock: *ERROR*: VHOST_SET_MEM_TABLE failed: Broken pipe
virtio_user/vhost_user.c: 381:vhost_user_sock: *ERROR*: VHOST_SET_MEM_TABLE failed: Broken pipe
virtio_user/vhost_user.c: 381:vhost_user_sock: *ERROR*: VHOST_SET_MEM_TABLE failed: Broken pipe
virtio_user/vhost_user.c: 381:vhost_user_sock: *ERROR*: VHOST_SET_MEM_TABLE failed: Broken pipe
virtio_user/vhost_user.c: 381:vhost_user_sock: *ERROR*: VHOST_SET_MEM_TABLE failed: Broken pipe
virtio_user/vhost_user.c: 381:vhost_user_sock: *ERROR*: VHOST_SET_MEM_TABLE failed: Broken pipe
virtio_user/vhost_user.c: 381:vhost_user_sock: *ERROR*: VHOST_SET_MEM_TABLE failed: Broken pipe
virtio_user/vhost_user.c: 381:vhost_user_sock: *ERROR*: VHOST_SET_MEM_TABLE failed: Broken pipe
virtio_user/vhost_user.c: 381:vhost_user_sock: *ERROR*: VHOST_SET_MEM_TABLE failed: Broken pipe
virtio_user/vhost_user.c: 381:vhost_user_sock: *ERROR*: VHOST_SET_MEM_TABLE failed: Broken pipe
virtio_user.c: 197:virtio_user_register_mem: *ERROR*: spdk_mem_map_alloc() failed
virtio.c: 315:virtio_dev_start: *ERROR*: Failed to set VIRTIO_CONFIG_S_DRIVER_OK status.
request:
{
  "name": "virtioblk0",
  "trtype": "user",
  "traddr": "/var/tmp/vhost.1",
  "dev_type": "blk",
  "method": "bdev_virtio_attach_controller",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32602,
  "message": "Invalid argument"
}
```
 
But if I increase the hugepage count("HUGEMEM=8192 ./scripts/setup.sh"), then this issue will disappear.

**Comment by Comphix** [comment] 2020-04-01 07:04
@jumpapex, will you first try the 8192 number of hugepages? Thanks.

**Comment by jumpapex** [comment] 2020-04-01 08:22
@Comphix, I think an enough large hugepage will shadow this issue, but not resolve it.

**Comment by Donaim** [comment] 2020-04-09 11:36
Issue also reproduces on my machine.
But here are some other observations:
- errors dissapear if we increase HUGEMEM count, BUT vhost app freezes and cannot be killed with SIGINT or SIGTERM.
- with 1GB hugepages, error messages do not show up at all, even if there is only 1 hugepage allocated, but instead freezes like in case of 2MB hugepages and HUGEMEM>4K

I will investigate further this week
Will check how VHOST_USER_SET_MEM_TABLE works

**Comment by changpe1** [comment] 2020-04-13 05:32
Looking more about this issue, we can update SPDK virtio-user library to eliminate this issue. Refer to DPDK commit 534bccbad17, http://git.dpdk.org/dpdk/commit/drivers/net/virtio/virtio_user/vhost_user.c?h=releases&id=534bccbad17bace0b899861652d0b89115b00a7e, we can refactoring the code to virtio_user_map_notify(), @Donaim do you want to a try?

**Comment by Donaim** [comment] 2020-04-13 12:36
@changpe1 yes, I will try that this week. Thanks!

**Comment by Donaim** [comment] 2020-04-17 13:35
Working on implementing referenced change for our virtio_user lib,
but I am not sure how using that change do the refactoring to remove `virtio_user_map_notify()`. 
Will carry this topic in next week

**Comment by changpe1** [comment] 2020-04-20 01:30
> Working on implementing referenced change for our virtio_user lib,
> but I am not sure how using that change do the refactoring to remove `virtio_user_map_notify()`.
> Will carry this topic in next week

virtio_user_map_notify() will be called several times so that we have several SET_MEM_TABLE messages received in the vhost target, I'm thinking we can just send 1 SET_MEM_TABLE message using the new DPDK API. The message should include all the memory segments in the DPDK.

**Comment by Donaim** [comment] 2020-04-24 11:09
Thanks @changpe1 
I was focusing on issue #1348 because that one is a blocker currenly
But I will come back to this issue next week

**Comment by Donaim** [comment] 2020-04-30 09:02
Working on this, but need more time.
Our `prepare_vhost_memory()` is different from that of DPDK, I need to study it more

**Comment by Donaim** [comment] 2020-05-08 10:10
Still working on this and will continue next week

**Comment by Donaim** [comment] 2020-05-15 11:35
Didn't make it this weak
Need to mention that I am going to be OOO starting tomorrow so won't be able to work on this during that time

**Comment by jimharris** [comment] 2020-05-15 15:29
Thanks for the update @Donaim.  We will keep this issue assigned to you for now.  You can pick it back up when you return.

**Comment by Donaim** [comment] 2020-07-17 11:51
I am working on bdevperf changes and don't have time to investigate this issue currently
But I will come back to this after bdevperf is done

**Comment by changpe1** [comment] 2020-09-27 05:09
I looked into this issue, the usage scenario is wrong, typically for virtio usage cases, we should start two processes, one is vhost target the other one can be spdk target, it's not correct to use them in the same process.

**Comment by changpe1** [comment] 2020-09-27 05:18
@jumpapex could you refer to test/vhost/initiator/blockdev.sh in SPDK as an example, there is detailed steps about run vhost user with two processes. I'm going to close this issue, you can reopen it if the issue still exist.

**Closed by changpe1** 2020-09-27 05:18 UTC
Labels: enhancement
