### ISSUE TITLE
OCF compilation fails

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1279] opened 2020-03-16 15:47 UTC
```
SPDK: v20.01-rc1-448-g62e0342ea
OCF: v18.12
OS: Debian 10 (kernel 4.19.67)
```
CONFIG:
```
CONFIG_PREFIX="/usr/local"
CONFIG_ARCH=native
CONFIG_CROSS_PREFIX=
CONFIG_DEBUG=n
CONFIG_LOG_BACKTRACE=n
CONFIG_WERROR=n
CONFIG_LTO=n
CONFIG_PGO_CAPTURE=n
CONFIG_PGO_USE=n
CONFIG_COVERAGE=y
CONFIG_ASAN=n
CONFIG_UBSAN=n
CONFIG_TSAN=n
CONFIG_TESTS=y
CONFIG_UNIT_TESTS=y
CONFIG_EXAMPLES=y
CONFIG_ENV=
CONFIG_DPDK_DIR=
CONFIG_FIO_PLUGIN=y
CONFIG_FIO_SOURCE_DIR=/usr/src/fio
CONFIG_RDMA=n
CONFIG_RDMA_SEND_WITH_INVAL=n
CONFIG_RDMA_SET_ACK_TIMEOUT=n
CONFIG_NVME_CUSE=y
CONFIG_FC=n
CONFIG_FC_PATH=
CONFIG_RBD=y
CONFIG_VHOST=y
CONFIG_VHOST_INTERNAL_LIB=n
CONFIG_VIRTIO=y
CONFIG_PMDK=n
CONFIG_PMDK_DIR=
CONFIG_REDUCE=n
CONFIG_VPP=n
CONFIG_VPP_DIR=
CONFIG_ISCSI_INITIATOR=n
CONFIG_CRYPTO=y
CONFIG_SHARED=n
CONFIG_VTUNE=n
CONFIG_VTUNE_DIR=
CONFIG_IGB_UIO_DRIVER=y
CONFIG_IPSEC_MB=n
CONFIG_OCF=y
CONFIG_OCF_PATH=/usr/src/ocf
CONFIG_CUSTOMOCF=n
CONFIG_ISAL=y
CONFIG_URING=n
CONFIG_URING_PATH=
CONFIG_FUSE=n
CONFIG_RAID5=n
```

An attempt to build SPDK with OCF (fetched by `vm_setup.sh`) fails with the following:

```ocf_env.h:213:45: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  213 |  return pthread_mutex_trylock(&mutex->m) ? -OCF_ERR_NO_LOCK : 0;
      |                                             ^~~~~~~~~~~~~~~
      |                                             OCF_ERR_NO_MEM
ocf_env.h:213:45: note: each undeclared identifier is reported only once for each function it appears in
ocf_env.h: In function ‘env_rwsem_down_read_trylock’:
ocf_env.h:287:47: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  287 |  return pthread_rwlock_tryrdlock(&s->lock) ? -OCF_ERR_NO_LOCK : 0;
      |                                               ^~~~~~~~~~~~~~~
      |                                               OCF_ERR_NO_MEM
ocf_env.h: In function ‘env_rwsem_down_write_trylock’:
ocf_env.h:302:47: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  302 |  return pthread_rwlock_trywrlock(&s->lock) ? -OCF_ERR_NO_LOCK : 0;
      |                                               ^~~~~~~~~~~~~~~
      |                                               OCF_ERR_NO_MEM
cc -g  -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wmissing-declarations -fno-strict-aliasing -I/root/git_repos/spdk_repo/spdk/include -march=native -Wformat -Wformat-security -D_GNU_SOURCE -fPIC -fstack-protector -fno-common -I/root/git_repos/spdk_repo/spdk/isa-l/.. -DNDEBUG -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -DSPDK_GIT_COMMIT=302f7aa6e -pthread -Wno-pointer-sign -Wstrict-prototypes -Wold-style-definition -std=gnu99 -I/root/git_repos/spdk_repo/spdk/dpdk/build/include -Wno-deprecated-declarations -I/root/git_repos/spdk_repo/spdk/lib/env_ocf -I/root/git_repos/spdk_repo/spdk/lib/env_ocf/include -w   -c -o src/ocf/engine/engine_bf.o src/ocf/engine/engine_bf.c
In file included from /root/git_repos/spdk_repo/spdk/lib/env_ocf/include/ocf/ocf_data_obj.h:15,
                 from /root/git_repos/spdk_repo/spdk/lib/env_ocf/include/ocf/ocf.h:21,
                 from src/ocf/cleaning/acp.c:6:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_mutex_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:213:45: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  213 |  return pthread_mutex_trylock(&mutex->m) ? -OCF_ERR_NO_LOCK : 0;
      |                                             ^~~~~~~~~~~~~~~
      |                                             OCF_ERR_NO_MEM
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:213:45: note: each undeclared identifier is reported only once for each function it appears in
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_rwsem_down_read_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:287:47: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  287 |  return pthread_rwlock_tryrdlock(&s->lock) ? -OCF_ERR_NO_LOCK : 0;
      |                                               ^~~~~~~~~~~~~~~
      |                                               OCF_ERR_NO_MEM
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_rwsem_down_write_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:302:47: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  302 |  return pthread_rwlock_trywrlock(&s->lock) ? -OCF_ERR_NO_LOCK : 0;
      |                                               ^~~~~~~~~~~~~~~
      |                                               OCF_ERR_NO_MEM
In file included from /root/git_repos/spdk_repo/spdk/lib/env_ocf/include/ocf/ocf_data_obj.h:15,
                 from /root/git_repos/spdk_repo/spdk/lib/env_ocf/include/ocf/ocf.h:21,
                 from src/ocf/cleaning/alru.c:6:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_mutex_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:213:45: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  213 |  return pthread_mutex_trylock(&mutex->m) ? -OCF_ERR_NO_LOCK : 0;
      |                                             ^~~~~~~~~~~~~~~
      |                                             OCF_ERR_NO_MEM
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:213:45: note: each undeclared identifier is reported only once for each function it appears in
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_rwsem_down_read_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:287:47: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  287 |  return pthread_rwlock_tryrdlock(&s->lock) ? -OCF_ERR_NO_LOCK : 0;
      |                                               ^~~~~~~~~~~~~~~
      |                                               OCF_ERR_NO_MEM
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_rwsem_down_write_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:302:47: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  302 |  return pthread_rwlock_trywrlock(&s->lock) ? -OCF_ERR_NO_LOCK : 0;
      |                                               ^~~~~~~~~~~~~~~
      |                                               OCF_ERR_NO_MEM
make[3]: *** [<builtin>: ocf_env.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /root/git_repos/spdk_repo/spdk/lib/env_ocf/include/ocf/ocf_data_obj.h:15,
                 from /root/git_repos/spdk_repo/spdk/lib/env_ocf/include/ocf/ocf.h:21,
                 from src/ocf/cleaning/alru_structs.h:8,
                 from src/ocf/cleaning/cleaning.h:9,
                 from src/ocf/cleaning/cleaning.c:6:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_mutex_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:213:45: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  213 |  return pthread_mutex_trylock(&mutex->m) ? -OCF_ERR_NO_LOCK : 0;
      |                                             ^~~~~~~~~~~~~~~
      |                                             OCF_ERR_NO_MEM
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:213:45: note: each undeclared identifier is reported only once for each function it appears in
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_rwsem_down_read_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:287:47: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  287 |  return pthread_rwlock_tryrdlock(&s->lock) ? -OCF_ERR_NO_LOCK : 0;
      |                                               ^~~~~~~~~~~~~~~
      |                                               OCF_ERR_NO_MEM
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_rwsem_down_write_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:302:47: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  302 |  return pthread_rwlock_trywrlock(&s->lock) ? -OCF_ERR_NO_LOCK : 0;
      |                                               ^~~~~~~~~~~~~~~
      |                                               OCF_ERR_NO_MEM
make[3]: *** [<builtin>: src/ocf/cleaning/acp.o] Error 1
make[3]: *** [<builtin>: src/ocf/cleaning/alru.o] Error 1
make[3]: *** [<builtin>: src/ocf/cleaning/cleaning.o] Error 1
In file included from /root/git_repos/spdk_repo/spdk/lib/env_ocf/include/ocf/ocf_data_obj.h:15,
                 from /root/git_repos/spdk_repo/spdk/lib/env_ocf/include/ocf/ocf.h:21,
                 from src/ocf/concurrency/../ocf_cache_priv.h:9,
                 from src/ocf/concurrency/ocf_concurrency.h:9,
                 from src/ocf/concurrency/ocf_cache_concurrency.c:6:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_mutex_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:213:45: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  213 |  return pthread_mutex_trylock(&mutex->m) ? -OCF_ERR_NO_LOCK : 0;
      |                                             ^~~~~~~~~~~~~~~
      |                                             OCF_ERR_NO_MEM
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:213:45: note: each undeclared identifier is reported only once for each function it appears in
In file included from /root/git_repos/spdk_repo/spdk/lib/env_ocf/include/ocf/ocf_data_obj.h:15,
                 from /root/git_repos/spdk_repo/spdk/lib/env_ocf/include/ocf/ocf.h:21,
                 from src/ocf/concurrency/../ocf_cache_priv.h:9,
                 from src/ocf/concurrency/ocf_concurrency.h:9,
                 from src/ocf/concurrency/ocf_concurrency.c:6:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_mutex_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:213:45: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  213 |  return pthread_mutex_trylock(&mutex->m) ? -OCF_ERR_NO_LOCK : 0;
      |                                             ^~~~~~~~~~~~~~~
      |                                             OCF_ERR_NO_MEM
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:213:45: note: each undeclared identifier is reported only once for each function it appears in
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_rwsem_down_read_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:287:47: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  287 |  return pthread_rwlock_tryrdlock(&s->lock) ? -OCF_ERR_NO_LOCK : 0;
      |                                               ^~~~~~~~~~~~~~~
      |                                               OCF_ERR_NO_MEM
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_rwsem_down_read_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:287:47: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  287 |  return pthread_rwlock_tryrdlock(&s->lock) ? -OCF_ERR_NO_LOCK : 0;
      |                                               ^~~~~~~~~~~~~~~
      |                                               OCF_ERR_NO_MEM
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_rwsem_down_write_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:302:47: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  302 |  return pthread_rwlock_trywrlock(&s->lock) ? -OCF_ERR_NO_LOCK : 0;
      |                                               ^~~~~~~~~~~~~~~
      |                                               OCF_ERR_NO_MEM
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_rwsem_down_write_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:302:47: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  302 |  return pthread_rwlock_trywrlock(&s->lock) ? -OCF_ERR_NO_LOCK : 0;
      |                                               ^~~~~~~~~~~~~~~
      |                                               OCF_ERR_NO_MEM
In file included from /root/git_repos/spdk_repo/spdk/lib/env_ocf/include/ocf/ocf_data_obj.h:15,
                 from /root/git_repos/spdk_repo/spdk/lib/env_ocf/include/ocf/ocf.h:21,
                 from src/ocf/engine/cache_engine.c:6:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_mutex_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:213:45: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  213 |  return pthread_mutex_trylock(&mutex->m) ? -OCF_ERR_NO_LOCK : 0;
      |                                             ^~~~~~~~~~~~~~~
      |                                             OCF_ERR_NO_MEM
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:213:45: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [<builtin>: src/ocf/concurrency/ocf_concurrency.o] Error 1
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_rwsem_down_read_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:287:47: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  287 |  return pthread_rwlock_tryrdlock(&s->lock) ? -OCF_ERR_NO_LOCK : 0;
      |                                               ^~~~~~~~~~~~~~~
      |                                               OCF_ERR_NO_MEM
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_rwsem_down_write_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:302:47: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  302 |  return pthread_rwlock_trywrlock(&s->lock) ? -OCF_ERR_NO_LOCK : 0;
      |                                               ^~~~~~~~~~~~~~~
      |                                               OCF_ERR_NO_MEM
In file included from /root/git_repos/spdk_repo/spdk/lib/env_ocf/include/ocf/ocf_data_obj.h:15,
                 from /root/git_repos/spdk_repo/spdk/lib/env_ocf/include/ocf/ocf.h:21,
                 from src/ocf/engine/engine_bf.c:6:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_mutex_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:213:45: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  213 |  return pthread_mutex_trylock(&mutex->m) ? -OCF_ERR_NO_LOCK : 0;
      |                                             ^~~~~~~~~~~~~~~
      |                                             OCF_ERR_NO_MEM
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:213:45: note: each undeclared identifier is reported only once for each function it appears in
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_rwsem_down_read_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:287:47: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  287 |  return pthread_rwlock_tryrdlock(&s->lock) ? -OCF_ERR_NO_LOCK : 0;
      |                                               ^~~~~~~~~~~~~~~
      |                                               OCF_ERR_NO_MEM
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h: In function ‘env_rwsem_down_write_trylock’:
/root/git_repos/spdk_repo/spdk/lib/env_ocf/ocf_env.h:302:47: error: ‘OCF_ERR_NO_LOCK’ undeclared (first use in this function); did you mean ‘OCF_ERR_NO_MEM’?
  302 |  return pthread_rwlock_trywrlock(&s->lock) ? -OCF_ERR_NO_LOCK : 0;
      |                                               ^~~~~~~~~~~~~~~
      |                                               OCF_ERR_NO_MEM
make[3]: *** [<builtin>: src/ocf/concurrency/ocf_cache_concurrency.o] Error 1
make[3]: *** [<builtin>: src/ocf/engine/cache_engine.o] Error 1
make[3]: *** [<builtin>: src/ocf/engine/engine_bf.o] Error 1
make[2]: *** [Makefile:76: all] Error 2
make[1]: *** [/root/git_repos/spdk_repo/spdk/mk/spdk.subdirs.mk:44: env_ocf] Error 2
make[1]: *** Waiting for unfinished jobs....
  LIB libspdk_vmd.a
  LIB libspdk_util.a
  LIB libspdk_env_dpdk.a
make: *** [/root/git_repos/spdk_repo/spdk/mk/spdk.subdirs.mk:44: lib] Error 2
```
Any hints on why this might be the case would be appreciated.

**Comment by mikeBashStuff** [comment] 2020-03-17 12:37
Having very same issue on our Fedora 31.

**Comment by Donaim** [comment] 2020-03-26 12:23
The cause of this issue has to be in the use of `vm_setup.sh` to install OCF which should have been deprecated long time ago since we switched to submodule.
I will submit a patch that removes OCF part from vm_setup script.

As for using non standard ocf path, it is user's responsibility ensure compatibilty with our submodule version.

**Comment by Donaim** [comment] 2020-03-26 16:46
Submitted a patch for `vm_setup.sh` bug: https://review.spdk.io/gerrit/c/spdk/spdk/+/1496
We should be done with this issue after it gets merged, do you agree @mikeBashStuff ?

**Comment by mikeBashStuff** [comment] 2020-03-26 17:41
@Donaim Agreed - compiling against the ocf submodule works like a charm.

**Comment by tomzawadzki** [comment] 2020-04-07 14:45
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/1496 is now merged, which should point users to the submodule. 
Thanks @Donaim !

**Closed by tomzawadzki** 2020-04-07 14:45 UTC
