### ISSUE TITLE
perf example hung at the process the RDMA CQ when we configure NVMeOF kernel target in Ubuntu VM with softRoCE

### ISSUE THREAD

**Issue by gwnet** [spdk/spdk#868] opened 2019-07-22 12:59 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Steps to Reproduce

1.
2.
3.
4.
sudo ./perf -q 128 -o 4096 -w read -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.147.130 trsvcid:4420' -t 300
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid17407 ]
EAL: No available hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 192.168.147.130:4420: testnqn
Attached to NVMe over Fabrics controller at 192.168.147.130:4420: testnqn
Associating RDMA (addr:192.168.147.130 subnqn:testnqn) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0

	==dead loop===
		while (status->done == false) {
		if (robust_mutex) {
			nvme_robust_mutex_lock(robust_mutex);
		}

		spdk_nvme_qpair_process_completions(qpair, 0);  ----- here dead loop

		if (robust_mutex) {
			nvme_robust_mutex_unlock(robust_mutex);
		}
	}
	
	=========================

**Comment by yidong0635** [comment] 2019-07-23 02:08
@gwnet , looks like  need to update your code .
The codes that  be listed here  are:

```
	while (status->done == false) {
		if (robust_mutex) {
			nvme_robust_mutex_lock(robust_mutex);
		}

		if (spdk_nvme_qpair_process_completions(qpair, 0) < 0) {
			status->done = true;
			status->cpl.status.sct = SPDK_NVME_SCT_GENERIC;
			status->cpl.status.sc = SPDK_NVME_SC_ABORTED_SQ_DELETION;
		}

		if (robust_mutex) {
			nvme_robust_mutex_unlock(robust_mutex);
		}
	}


```
Could you please help to check it again?

**Comment by darsto** [comment] 2019-07-30 15:43
Bug scrub: We believe this code part is fine. @gwnet could you provide reproduction steps, so we can pin down the exact issue?

**Comment by yidong0635** [comment] 2019-09-02 08:46
@gwnet  If you have any other question about this issue, please close this issue.

**Comment by jimharris** [comment] 2019-09-24 16:04
Closing this issue.  If there are additional questions, please reopen.

**Closed by jimharris** 2019-09-24 16:04 UTC
Labels: Waiting on Submitter, help wanted, question
