### ISSUE TITLE
bdevperf cannot show read and write BW result seperately when we run -w rw -M 50

### ISSUE THREAD

**Issue by gaowayne** [spdk/spdk#2535] opened 2022-05-30 11:29 UTC
# Bug report

bdevperf report missing detail BW number for read and write, there is only one total number for read/write mixed workload like rw.

## Expected Behavior

each workload need report separately 

## Current Behavior

report one global stat

## Steps to Reproduce

1. run bdevperf like below
```
[2022-05-30 13:17:38.250017] Starting SPDK v22.09-pre git sha1 faeee6301 / DPDK 22.03.0 initialization...
[2022-05-30 13:17:38.250165] [ DPDK EAL parameters: [2022-05-30 13:17:38.250184] bdevperf [2022-05-30 13:17:38.250197] --no-shconf [2022-05-30 13:17:38.250209] -c 3 [2022-05-30 13:17:38.250225] --huge-unlink [2022-05-30 13:17:38.250242] --log-level=lib.eal:6 [2022-05-30 13:17:38.250258] --log-level=lib.cryptodev:5 [2022-05-30 13:17:38.250272] --log-level=user1:6 [2022-05-30 13:17:38.250285] --base-virtaddr=0x200000000000 [2022-05-30 13:17:38.250299] --match-allocations [2022-05-30 13:17:38.250313] --file-prefix=spdk_pid1184680 [2022-05-30 13:17:38.250325] ]
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-05-30 13:17:38.342669] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 2
[2022-05-30 13:17:38.543696] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 1
[2022-05-30 13:17:38.543878] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
[2022-05-30 13:17:38.576400] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32601,
  "message": "Method not found"
}
[2022-05-30 13:17:38.584400] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32601,
  "message": "Method not found"
}
[2022-05-30 13:17:38.592401] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32601,
  "message": "Method not found"
}
[2022-05-30 13:17:38.600402] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32601,
  "message": "Method not found"
}
[2022-05-30 13:17:38.600423] accel_engine.c: 969:sw_accel_engine_init: *NOTICE*: Accel framework software engine initialized.
[2022-05-30 13:17:39.008799] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32601,
  "message": "Method not found"
}
[2022-05-30 13:17:39.016796] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32601,
  "message": "Method not found"
}
[2022-05-30 13:17:39.024812] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32601,
  "message": "Method not found"
}
[2022-05-30 13:17:39.032813] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32601,
  "message": "Method not found"
}
Running I/O for 60 seconds...
 Job: Nvme0n1 (Core Mask 0x1)
	 Nvme0n1             :  810800.52 IOPS    3167.19 MiB/s
 =============================================================
 Total                       :  810800.52 IOPS    3167.19 MiB/s

```
3. check the result row, only one row on detail read or write.
4.
5.

**Comment by tomzawadzki** [comment] 2022-05-31 15:35
Bug scrub: This behavior is as intended, showing the read and write separately is a feature request.

**Comment by Comphix** [comment] 2022-11-03 02:40
Take a look at this issue.

**Comment by Comphix** [comment] 2022-11-03 05:07
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/15235 is raised for this enhancement.

**Comment by jimharris** [comment] 2022-11-03 18:26
I have some concerns/questions about the patch, and this issue in general:

1) This adds a lot of extra clutter to the bdevperf output.  The vast majority of testing is done with non-mixed workloads - now all of those workloads will get all of these extra columns.
2) I don't think "Read" and "Other" names will work.  We need "Write" in there.  I think "Other" will make people think about I/O types like unmap or write zeroes.
3) Can't the Read v. Write output just be determined by multiplying the mix ratio by the total IOPs?  If we are doing a 50/50 mix, and we complete 20K IO/s, doesn't that mean that there were 10K reads/s and 10K writes/s?  Maybe it isn't *exactly* that number because of random variance, but it's going to be very close.

**Comment by Comphix** [comment] 2022-11-04 03:34
Thanks Jim, I've updated patch to dynamically display the Reads & Writes if configured. For Reads and Writes only, it will display as original.

**Comment by benlwalker** [comment] 2022-11-07 18:59
I agree with Jim's point number 3 there, for the record.

**Comment by jimharris** [comment] 2022-11-07 19:15
> I agree with Jim's point number 3 there, for the record.

@Comphix, @gaowayne, the patch looks fine, but it's 150 lines of extra code.  I just don't see the value in adding that extra code to maintain, test, etc. when the data requested can be gleaned from the current code without this patch.

**Comment by Comphix** [comment] 2022-11-08 01:22
Sure. We could just use the M parameter to calculate the separate Read and Write statistics. Let me close this issue. Thanks all.

**Closed by Comphix** 2022-11-08 01:22 UTC
Labels: enhancement, Patches out for review
