### ISSUE TITLE
iscsi_tgt_initiator test fails with a core dump

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1289] opened 2020-03-17 20:13 UTC
https://ci.spdk.io/results/autotest-per-patch/builds/6647/archive/vpp-autotest/build.log

This popped up while working on migrating .ini configuration to json as part of the https://review.spdk.io/gerrit/c/spdk/spdk/+/1335. This has an intermittent feel to it though since this autotest https://ci.spdk.io/results/autotest-per-patch/builds/6647/archive/iscsi-autotest/build.log, where `iscsi_tgt_initiator` is run as well (https://ci.spdk.io/public_build/autotest-per-patch_6647.html) , didn't fail at all.

**Comment by mikeBashStuff** [comment] 2020-03-18 13:32
Test is the same, but the type differs (`vpp` vs `posix`). That's most likely the damn factor here.

**Comment by mikeBashStuff** [comment] 2020-03-18 13:42
Assertion seems to be quite similar to the one from https://github.com/spdk/spdk/issues/1204

**Comment by mikeBashStuff** [comment] 2020-04-08 16:30
Ok, this is definitely not intermittent now. Whenever the test uses `vpp` and json config, `bdevperf` is always hit with a segfault after finishing the first 5s run. The json in question looks like the following:
```
{
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "method": "bdev_iscsi_create",
          "params": {
            "name": "iSCSI0",
            "url": "iscsi://10.0.0.1/iqn.2016-06.io.spdk:disk1/0",
            "initiator_iqn": "iqn.2016-06.io.spdk:disk1/0"
          }
        }
      ]
    }
  ]
}
```
I haven't noticed how frequent this is since locally I tested it only in `posix` mode, which works just fine. Another instance of this can be seen here (actually, after recent rebasing, all the   https://review.spdk.io/gerrit/c/spdk/spdk/+/1327/13 commits are failing because of this):

https://ci.spdk.io/results/autotest-per-patch/builds/9626/archive/vpp-autotest/build.log
https://ci.spdk.io/results/autotest-per-patch/builds/9626/archive/vpp-autotest/index.html

@tomzawadzki apologies for highlighting you like that (and sorry for not seeing this earlier) but I am afraid this will require some attention for the .ini->json migration to be completed.

**Comment by tomzawadzki** [comment] 2020-04-14 13:22
Hi @mikeBashStuff just coincidentally seems like fix was merged today. Please see https://review.spdk.io/gerrit/c/spdk/spdk/+/1590

From my local reproduction this is the one that changes from 100% occurrence to no longer appearing. You can rebase your patch on master and if CI reports a pass - this one can be closed.

**Comment by tomzawadzki** [comment] 2020-04-17 09:43
CI passed on the patch with changes to json configuration. This looks like it was resolved.

**Closed by tomzawadzki** 2020-04-17 09:43 UTC
Labels: Intermittent Failure
