### ISSUE TITLE
Issue with timeout check in the function nvme_ctrlr_process_init

### ISSUE THREAD

**Issue by aohzju** [spdk/spdk#1720] opened 2020-12-14 03:57 UTC
At the end of the function nvme_ctrlr_process_init, there is a timeout check:

```
init_timeout:
    if (ctrlr->state_timeout_tsc != NVME_TIMEOUT_INFINITE &&
        spdk_get_ticks() > ctrlr->state_timeout_tsc) {
        SPDK_ERRLOG("Initialization timed out in state %d\n", ctrlr->state);
        return -1;
    }    
    return rc;
```
This check may raise false alarm due to the multi-task environment nature. Imagine the spdk task is scheduled out for some seconds right at the "init_timeout" point, but meanwhile the device has just completed a status transition successfully (so no timeout actually). When the spdk task is resumed again, spdk_get_tickts may get a value greater then ctrlr->state_timeout_tsc, thus it will report the timeout error. 

## Possible Solution
Move spdk_get_ticks function call prior to each status check function call.

**Comment by shuhei-matsumoto** [comment] 2020-12-14 05:55
Hi @aohzju 

It is expected that we call nvme_ctrlr_process_init() repeatedly until the state of the ctrlr becomes ready.
If nvme_ctrlr_process_init() is called multiple times, there is no difference between the head or tail in a function as a place to check timeout.

nvme_ctrlr_process_init();
nvme_ctrlr_process_init();
nvme_ctrlr_process_init();

 (snip)

nvme_ctrlr_process_init().

But you have seen the SPDK task is scheduled out for a long time in any place in nvme_ctrlr_process_init().

Will you give more detailed information? SPDK usually does not use POSIX thread wait. 
In what function, the SPDK task is scheduled out for a long time?
How long the task is scheduled out in your environment?

**Comment by jimharris** [comment] 2020-12-14 14:19
Hi @aohzju,

I agree with Shuhei.  Moving the spdk_get_ticks() call could help you in some of your cases, but what happens if the task gets swapped out just *before* the spdk_get_ticks() call?

So I agree with Shuhei that I'd like to know more about your environment.  What is being scheduled on this system such that an SPDK process could be swapped out for 30 seconds at a time?

You can also set admin_timeout_us in spdk_nvme_ctrlr_opts to a bigger value if you have something in your environment that is swapping out an SPDK process for more than 30 seconds at a time.

-Jim

**Comment by aohzju** [comment] 2020-12-15 07:09
Hi, @shuhei-matsumoto , @jimharris ,
I gave an extreme example for illustrating the issue, not a real case.
I was running some tests on a QEMU guest OS against a simulated NVMe device (a home-grown NVMe simulator). Meanwhile, there was another machine interacting with the guest OS collecting testing log data. Intermittently, we saw NMVe init timed out at state 3 or 5 (NVME_CTRLR_STATE_DISABLE_WAIT_FOR_READY_0 or NVME_CTRLR_STATE_ENABLE_WAIT_FOR_READY_1). It looks like the timing is marginal in my case. When debugging and reviewing code, I thought there was a pitfall with nvme_ctrlr_process_init() function as I described. In my case, I guess there is a chance that my spdk test program is stuck for a while when the QEMU guest OS is busying with collecting the test log and transferring it.

To answer @jimharris ' question "but what happens if the task gets swapped out just before the spdk_get_ticks() call?":  Right after spdk_get_ticks() call, there is a state check. If the device state has moved forward successfully, the function should have reset the time out point according to the new state. Thus the chance for the false alarm can be eliminated.

Thanks
-Oscar

**Comment by shuhei-matsumoto** [comment] 2020-12-15 08:31
Hi @aohzju 

Thanks for the detailed explanation. Are you saying that we move the timeout check to the head of nvme_ctrlr_process_init() and return success regardless of timeout if state is moved to the next?

However, as you will find, we already have implemented similar solution. 
nvme_ctrlr_set_state() extends timeout if the state is changed.
This timeout extension serves the role to remove the false alarm.
It looks that there is a timeout check right after state transition.

Unfortunately your idea is not clear to me yet.

As Jim suggested, extending timeout interval or controlling thread affinity (dedicating CPU core to SPDK) may be practical solution.

If you have any patch to implement your idea, that will be definitely helpful.

-Shuhei

**Comment by aohzju** [comment] 2020-12-16 07:21
HI, @shuhei-matsumoto , let me create a patch and get back to you. Allow me some days as I'm tied up by some other things.

Thanks
-Oscar

**Comment by jimharris** [comment] 2020-12-17 00:53
Hi @aohzju,

Would this patch work?

https://review.spdk.io/gerrit/c/spdk/spdk/+/5596

-Jim

**Comment by aohzju** [comment] 2020-12-17 05:32
Hi, @jimharris ,
Thanks for the patch, but it does not fix the issue to my understanding. 
I attached my patch here for your reference. Hopefully it can make my point clear.

Thanks
-Oscar
[nvme_ctrlr.c_diff.txt](https://github.com/spdk/spdk/files/5707188/nvme_ctrlr.c_diff.txt)

**Comment by jimharris** [comment] 2020-12-17 21:38
> Hi, @jimharris ,
> Thanks for the patch, but it does not fix the issue to my understanding.
> I attached my patch here for your reference. Hopefully it can make my point clear.
> 
> Thanks
> -Oscar
> [nvme_ctrlr.c_diff.txt](https://github.com/spdk/spdk/files/5707188/nvme_ctrlr.c_diff.txt)

Hi @aohzju,

My concern with this approach is that now some case statements return, and others break.  That makes it more likely that you'd see regressions in the future.

Could you describe more why my patch would not work?  It has the advantage of being a much smaller patch.  It still calls spdk_get_ticks() after the state switch statement, but if the state changes it would now not cause a timeout.

Thanks,

Jim

**Comment by aohzju** [comment] 2020-12-18 02:41
Hi, @jimharris ,
Actually in the original implementation, some case statements do return after the nvme_ctrlr_set_state() call. Some don't, but I think they should. Think about the extreme case again, if they don't return immediately, and happen to be swapped out for seconds before init_timeout check, time-out may happen just in the current nvme_ctrlr_process_init cycle.

Regarding you patch, I hope I didn't misunderstand it. The thing is, the device may have changed the state between the switch statement and the init_timeout check, but the state change hasn't been captured by spdk , so old_state==ctrlr->state there. There is still a chance for the false alarm there. Does this make sense to you?

Thanks
-Oscar

**Comment by shuhei-matsumoto** [comment] 2020-12-18 05:19
Hi @aohzju 
A very simple preliminary question.
So what is the difference between your patch and infinite timeout (or timeout check is disabled) ?
Do you still have any error case you want to find by timeout?
Is it OK for you to disable timeout check?

**Comment by aohzju** [comment] 2020-12-18 07:55
Hi, @shuhei-matsumoto ,
My patch does not disable the timeout check. Basically it does this:

Get_Currrent_Time();
Check_Device_State();
Timeout_Check();

And yes, we still need timeout check.

Thanks
-Oscar

**Comment by shuhei-matsumoto** [comment] 2020-12-18 11:18
Hi @aohzju 

Thanks for your reply. Do you want to ignore intermittent spikes (i.e., large scheduling starvation) while polling ctrlr_process_init()?

How large is the spike compared with the timeout? 
How many times do you experience such spikes from state 1 to state 2?
Is it enough to extend timeout to timeout + spike_size * spike_count?

**Comment by shuhei-matsumoto** [comment] 2020-12-18 11:28
One more question.

Why can you say spike does not occur between the previous timeout_check() and the next get_current_time() ?

1. get_current_time()
2. check_device_state()
3. timeout_check()
4. get_current_time()
5. check_device_state()
6. timeout_check()

Why spike occurs only during between 1 and 3  or 4 and 6?
Why spike does not occur between 3 and 4?
Probability is just proportional to the code size?

**Comment by jimharris** [comment] 2020-12-18 15:42
> Hi, @jimharris ,
> Actually in the original implementation, some case statements do return after the nvme_ctrlr_set_state() call. Some don't, but I think they should. Think about the extreme case again, if they don't return immediately, and happen to be swapped out for seconds before init_timeout check, time-out may happen just in the current nvme_ctrlr_process_init cycle.

Yikes - I didn't look at the rest of this function before responding.  It is quite the mishmash of breaks and returns already.  I would still prefer to base the decisions here on the state changing.  Then as we add new states we are not worrying about whether to break or return from this switch statement.  Probably we should do some refactoring on this function to make it more consistent for the cases you've pointed out.

> 
> Regarding you patch, I hope I didn't misunderstand it. The thing is, the device may have changed the state between the switch statement and the init_timeout check, but the state change hasn't been captured by spdk , so old_state==ctrlr->state there. There is still a chance for the false alarm there. Does this make sense to you?

Can you describe more this case where state changed between the switch statement and the init_timeout check, but the state change hasn't been captured by SPDK?  I'm not understanding this.

For example, let's say we enter this function in NVME_CTRLR_STATE_IDENTIFY state.  We set old_state = NVME_CTRLR_STATE_IDENTIFY.  Then we call nvme_ctrlr_identify().  This function will submit the IDENTIFY command, and then change ctrlr->state to NVME_CTRLR_STATE_WAIT_FOR_IDENTIFY.

If process then gets swapped out here for 30 seconds, my patch will see that old_state != ctrlr->state and skip the timeout check.

Thanks,

-Jim

> 
> Thanks
> -Oscar

**Comment by shuhei-matsumoto** [comment] 2020-12-18 22:14
Thanks @jimharris 

I think you said Oscar’s issue would not be random but specific causal relationship, i.e., timeout occurred always at any specific state. Oh, that is our desire.

**Comment by aohzju** [comment] 2020-12-19 03:22
> Hi @aohzju
> 
> Thanks for your reply. Do you want to ignore intermittent spikes (i.e., large scheduling starvation) while moving state 1 to state 2?
> 
> How large is the spike compared with the timeout?
> How many times do you experience such spikes from state 1 to state 2?
> Is it enough to extend timeout to timeout + spike_size * spike_count?

Yes, we can extend the timeout threshold to avoid the issue. But my point is, this function itself can be polished to avoid the issue so that spdk users don't have to worry about the false alarm.

**Comment by aohzju** [comment] 2020-12-19 06:02
> One more question.
> 
> Why can you say spike does not occur between the previous timeout_check() and the next get_current_time() ?
> 
> 1. get_current_time()
> 2. check_device_state()
> 3. timeout_check()
> 4. get_current_time()
> 5. check_device_state()
> 6. timeout_check()
> 
> Why spike occurs only during between 1 and 3 or 4 and 6?
> Why spike does not occur between 3 and 4?
> Probability is just proportional to the code size?

Spike can happen anytime anywhere. If there is a spike between 3 and 4, and the device does have changed the state during the spike period, 5 will capture it and move forward one more state step, and reset ctrlr->state_timeout_tsc, so 6 won't fail. On the other hand, if the device does not change its state during the spike period, then it is a real timeout, 6 will fail.

**Comment by aohzju** [comment] 2020-12-19 06:16
> > Hi, @jimharris ,
> > Actually in the original implementation, some case statements do return after the nvme_ctrlr_set_state() call. Some don't, but I think they should. Think about the extreme case again, if they don't return immediately, and happen to be swapped out for seconds before init_timeout check, time-out may happen just in the current nvme_ctrlr_process_init cycle.
> 
> Yikes - I didn't look at the rest of this function before responding. It is quite the mishmash of breaks and returns already. I would still prefer to base the decisions here on the state changing. Then as we add new states we are not worrying about whether to break or return from this switch statement. Probably we should do some refactoring on this function to make it more consistent for the cases you've pointed out.
> 
> > Regarding you patch, I hope I didn't misunderstand it. The thing is, the device may have changed the state between the switch statement and the init_timeout check, but the state change hasn't been captured by spdk , so old_state==ctrlr->state there. There is still a chance for the false alarm there. Does this make sense to you?
> 
> Can you describe more this case where state changed between the switch statement and the init_timeout check, but the state change hasn't been captured by SPDK? I'm not understanding this.
 Let's take NVME_CTRLR_STATE_WAIT_FOR_IDENTIFY as an example, the device may have sent the CPL of Identify to the Admin cpl queue, but spdk won't know it until the next call to spdk_nvme_ctrlr_process_admin_completions is done. See the sequence below:
spdk_nvme_ctrlr_process_admin_completions ()   //called in the switch case, but Identify response not arrived yet. Note, in this case, your old_state==ctrlr->state
//The spdk task stalled for some time, and the device successfully submitted Identify completion to Admin Q during the period
init_timout_check()    //Though Identify CPL has arrived, but spdk_nvme_ctrlr_process_admin_completions hasn't been called again, so init_timeout check failed.

> 
> For example, let's say we enter this function in NVME_CTRLR_STATE_IDENTIFY state. We set old_state = NVME_CTRLR_STATE_IDENTIFY. Then we call nvme_ctrlr_identify(). This function will submit the IDENTIFY command, and then change ctrlr->state to NVME_CTRLR_STATE_WAIT_FOR_IDENTIFY.
> 
> If process then gets swapped out here for 30 seconds, my patch will see that old_state != ctrlr->state and skip the timeout check.
> 
> Thanks,
> 
> -Jim
> 
> > Thanks
> > -Oscar

**Comment by aohzju** [comment] 2020-12-19 06:18
> > Hi, @jimharris ,
> > Actually in the original implementation, some case statements do return after the nvme_ctrlr_set_state() call. Some don't, but I think they should. Think about the extreme case again, if they don't return immediately, and happen to be swapped out for seconds before init_timeout check, time-out may happen just in the current nvme_ctrlr_process_init cycle.
> 
> Yikes - I didn't look at the rest of this function before responding. It is quite the mishmash of breaks and returns already. I would still prefer to base the decisions here on the state changing. Then as we add new states we are not worrying about whether to break or return from this switch statement. Probably we should do some refactoring on this function to make it more consistent for the cases you've pointed out.
> 
> > Regarding you patch, I hope I didn't misunderstand it. The thing is, the device may have changed the state between the switch statement and the init_timeout check, but the state change hasn't been captured by spdk , so old_state==ctrlr->state there. There is still a chance for the false alarm there. Does this make sense to you?
> 
> Can you describe more this case where state changed between the switch statement and the init_timeout check, but the state change hasn't been captured by SPDK? I'm not understanding this.
> 
> For example, let's say we enter this function in NVME_CTRLR_STATE_IDENTIFY state. We set old_state = NVME_CTRLR_STATE_IDENTIFY. Then we call nvme_ctrlr_identify(). This function will submit the IDENTIFY command, and then change ctrlr->state to NVME_CTRLR_STATE_WAIT_FOR_IDENTIFY.
> 
> If process then gets swapped out here for 30 seconds, my patch will see that old_state != ctrlr->state and skip the timeout check.
> 
> Thanks,
> 
> -Jim
> 
> > Thanks
> > -Oscar

Let's take NVME_CTRLR_STATE_WAIT_FOR_IDENTIFY as an example, the device may have sent the CPL of Identify to the Admin cpl queue, but spdk won't know it until the next call to spdk_nvme_ctrlr_process_admin_completions is done. See the sequence below:
spdk_nvme_ctrlr_process_admin_completions () //called in the switch case, but Identify response not arrived yet. 
                                                                            //Note, in this case, your old_state==ctrlr->state
//The spdk task stalled for some time, and the device successfully submitted Identify completion to Admin Q during the period
init_timout_check() //Though Identify CPL has arrived, but spdk_nvme_ctrlr_process_admin_completions 
                               //hasn't been called again, so init_timeout check failed.

**Comment by jimharris** [comment] 2020-12-21 19:16
Ah, I see @aohzju.

Can you clarify why you change the breaks to returns in your patch?  For example, if we are in NVME_CTRLR_STATE_INIT, we call nvme_ctrlr_identify.  This will update the state_timeout_tsc.  If you already captured spdk_get_ticks() at the beginning of the function, and there is a very long delay, state_timeout_tsc will still be more than the ticks you captured, so we will not timeout this iteration.

I think the real problem would be in a function like nvme_ctrlr_identify.  It sets the state to WAIT_FOR_IDENTIFY *before* it actually submits the IDENTIFY_CTRLR command.  So this sequence would fail with either of our patches:

0) nvme_ctrlr_process_init() captures current tsc = X
1) nvme_ctrlr_process_init() calls nvme_ctrlr_identify()
2) nvme_ctrlr_identify() sets state to WAIT_FOR_IDENTIFY with timeout at X+30
3) process is swapped out for 45 seconds
4) nvme_ctrlr_identify() submits IDENTIFY_CTRLR command
5) nvme_ctrlr_identify() returns to nvme_ctrlr_process_init()
6) nvme_ctrlr_process_init() timeout does not trigger, since tsc capture at step 0 is less than X+30
7) next iteration of nvme_ctrlr_process_init() captures current tsc = X+45.001 (1 millisecond after previous iteration ended)
8) nvme_ctrlr_process_init() calls spdk_nvme_qpair_process_completions(), but the IDENTIFY_CTRLR command has not completed yet
9) nvme_ctrlr_process_init() now triggers the timeout

I think to really fix this to handle any kind of arbitrary swap out of the process, you would need to fix every one of these nvme_ctrlr_* functions to set the WAIT_FOR_XXX state after the associated command is submitted.

I'm open to reviewing and merging a patch that changed all of these if you submitted it.  It would also need unit and/or system tests that could verify this functionality stayed working to avoid regressions.

It looks like your originally issue was with the WAIT_FOR_READY states though.  This timeout is based on the CAP.TO specified by the controller.  What does this report in your QEMU setup?  I suspect that we just need to capture the spdk_get_ticks() at the beginning of the function to fix that case, which wouldn't require extra tests IMO.

**Comment by aohzju** [comment] 2020-12-22 00:05
Hi, @jimharris 
Yes, replacing breaks with returns in my patch is not necessary. And very good catch about the issue in nvme_ctrlr_identify functions. 

Yes, the most often seen false alarm is with WAIT_FOR_READY_0 and WAIT_FOR_READY_1 states. The reason is CAP.TO is usually marginal. Fortunately, nvme_ctrlr_process_init() disables/enables the controller before it calls nvme_ctrlr_set_state(). So an easy fix can be applied. See my new patch attached.

[nvme_ctrlr_diff.txt](https://github.com/spdk/spdk/files/5727066/nvme_ctrlr_diff.txt)

**Comment by changpe1** [comment] 2021-01-06 08:03
Patch has been merged, closing this issue now.

**Closed by changpe1** 2021-01-06 08:03 UTC
Labels: Sighting
