### ISSUE TITLE
incorrect time values in spdk_trace

### ISSUE THREAD

**Issue by jgrodman** [spdk/spdk#1678] opened 2020-11-11 09:52 UTC
I am filing this ticket at the request of @KariukiJ. The time values are sometimes very high. Here is a paste of our slack conversation:

```
John Kariuki  12 days ago
@Jesse Grodman Something is definitely broken, sometimes I see very high values but other times the number looks fine. Is that what you see in your environment:

John Kariuki  12 days ago
4: 1848687.750     RDMA_REQ_EXECUTED                     cmid:  0x18a86a0        id:    r2716            time:  107719.617
[root@spdk-icx-001 spdk]# build/bin/spdk_trace -s nvmf -p 28815 | grep r2716
 4:  43160.938     RDMA_REQ_NEW                          cmid:  0x15c8e90        id:    r2716
 4:  43160.953     RDMA_REQ_NEED_BUFFER                  cmid:  0x15c8e90        id:    r2716            time:  0.017
 4:  43160.992     RDMA_REQ_RDY_TO_EXECUTE               cmid:  0x15c8e90        id:    r2716            time:  0.057
 4:  43161.094     RDMA_REQ_EXECUTING                    cmid:  0x15c8e90        id:    r2716            time:  0.158
 4:  43171.145     RDMA_REQ_EXECUTED                     cmid:  0x15c8e90        id:    r2716            time:  10.203
 4:  43171.152     RDMA_REQ_TX_PENDING_C2H               cmid:  0x15c8e90        id:    r2716            time:  10.215
 4:  43171.164     RDMA_REQ_RDY_TO_COMPL                 cmid:  0x15c8e90        id:    r2716            time:  10.227
 4:  43171.176     RDMA_REQ_COMPLETING_C2H               cmid:  0x15c8e90        id:    r2716            time:  10.243
 4:  45716.379     RDMA_REQ_COMPLETED                    cmid:  0x18a86a0        id:    r2716            time:  2555.443
```

## Steps to Reproduce

I do not know what version / OS / HW John was using, but it was likely master as of the date of his comment, Oct 30, 2020.

**Comment by yidong0635** [comment] 2020-12-17 01:59
@mkenguva any update about this issue, does this related with async completion ?

**Comment by mkenguva** [comment] 2020-12-18 22:30
Hi  @yidong0635 , can you eloborate which async operation you are referring to, im new to the RDMA functionality here. 

Below is my steps i tried to reproduce this scenario. I have use v20.10 , not seen high number during tests. 
@jgrodman Could you let me know if your setup was similar to the below , if im missing any specific that might to your posted scenario , please let me know

sudo scripts/rpc.py nvmf_create_transport -t RDMA -u 8192 -m 4 -c 4096
sudo scripts/rpc.py bdev_malloc_create -b Malloc0 512 512
sudo scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1
sudo scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
sudo scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.8 -s 4420

sudo ./perf -q 128 -o 4096 -s 4096 -w randread -t 600 -r 'trtype:rdma adrfam:IPv4 traddr:192.168.100.8 trsvcid:4420'

/spdk$ sudo ./build/bin/spdk_trace -s nvmf -p 52809 |  grep r3429
 0: 842031.938     RDMA_REQ_NEW                          cmid:  0x5603f53449f0   id:    r3429
 0: 842032.000     RDMA_REQ_NEED_BUFFER                  cmid:  0x5603f53449f0   id:    r3429            time:  0.027
 0: 842032.062     RDMA_REQ_RDY_TO_EXECUTE               cmid:  0x5603f53449f0   id:    r3429            time:  0.103
 0: 842032.750     RDMA_REQ_EXECUTING                    cmid:  0x5603f53449f0   id:    r3429            time:  0.821
 0: 842086.188     RDMA_REQ_EXECUTED                     cmid:  0x5603f53449f0   id:    r3429            time:  54.154
 0: 842086.188     RDMA_REQ_TX_PENDING_C2H               cmid:  0x5603f53449f0   id:    r3429            time:  54.182
 0: 842086.188     RDMA_REQ_RDY_TO_COMPL                 cmid:  0x5603f53449f0   id:    r3429            time:  54.194
 0: 842086.250     RDMA_REQ_COMPLETING_C2H               cmid:  0x5603f53449f0   id:    r3429            time:  54.222
 0: 842123.062     RDMA_REQ_COMPLETED                    cmid:  0x5603f53449f0   id:    r3429            time:  91.102

**Comment by jgrodman** [comment] 2020-12-20 10:22
@mkenguva sorry, I don't remember the exact setup I used!

**Comment by yidong0635** [comment] 2020-12-21 03:02
I have tried this:
```
[root@waikikibeach45 spdk]# sudo ./build/bin/spdk_trace -s nvmf -p 455248 | grep r3523
 0: 1318706.125     RDMA_REQ_NEW                          cmid:  0x616000369380   id:    r3523
 0: 1318706.500     RDMA_REQ_NEED_BUFFER                  cmid:  0x616000369380   id:    r3523            time:  0.298
 0: 1318707.375     RDMA_REQ_RDY_TO_EXECUTE               cmid:  0x616000369380   id:    r3523            time:  1.227
 0: 1318725.500     RDMA_REQ_EXECUTING                    cmid:  0x616000369380   id:    r3523            time:  19.269
[root@waikikibeach45 spdk]# sudo ./build/bin/spdk_trace -s nvmf -p 455248 | grep r3523
 0: 1348674.125     RDMA_REQ_NEW                          cmid:  0x616000369380   id:    r3523
 0: 1348674.500     RDMA_REQ_NEED_BUFFER                  cmid:  0x616000369380   id:    r3523            time:  0.330
 0: 1348675.375     RDMA_REQ_RDY_TO_EXECUTE               cmid:  0x616000369380   id:    r3523            time:  1.074
 0: 1348694.250     RDMA_REQ_EXECUTING                    cmid:  0x616000369380   id:    r3523            time:  20.173
[root@waikikibeach45 spdk]# sudo ./build/bin/spdk_trace -s nvmf -p 455248 | grep r3523
 0: 1301560.375     RDMA_REQ_NEW                          cmid:  0x616000369380   id:    r3523
 0: 1301560.750     RDMA_REQ_NEED_BUFFER                  cmid:  0x616000369380   id:    r3523            time:  0.311
 0: 1301561.625     RDMA_REQ_RDY_TO_EXECUTE               cmid:  0x616000369380   id:    r3523            time:  1.240
 0: 1301580.125     RDMA_REQ_EXECUTING                    cmid:  0x616000369380   id:    r3523            time:  19.642
 0: 1327909.125     RDMA_REQ_EXECUTED                     cmid:  0x616000369380   id:    r3523            time:  26348.678
 0: 1327909.250     RDMA_REQ_TX_PENDING_C2H               cmid:  0x616000369380   id:    r3523            time:  26348.852
 0: 1327909.500     RDMA_REQ_RDY_TO_COMPL                 cmid:  0x616000369380   id:    r3523            time:  26348.992
 0: 1327910.000     RDMA_REQ_COMPLETING_C2H               cmid:  0x616000369380   id:    r3523            time:  26349.574
 0: 1328161.250     RDMA_REQ_COMPLETED                    cmid:  0x616000369380   id:    r3523            time:  26600.807
[root@waikikibeach45 spdk]# sudo ./build/bin/spdk_trace -s nvmf -p 455248 | grep r3523
 0: 1308427.125     RDMA_REQ_NEW                          cmid:  0x616000369380   id:    r3523
 0: 1308427.375     RDMA_REQ_NEED_BUFFER                  cmid:  0x616000369380   id:    r3523            time:  0.303
 0: 1308428.250     RDMA_REQ_RDY_TO_EXECUTE               cmid:  0x616000369380   id:    r3523            time:  1.118
 0: 1308446.625     RDMA_REQ_EXECUTING                    cmid:  0x616000369380   id:    r3523            time:  19.624
 0: 1310523.375     RDMA_REQ_EXECUTED                     cmid:  0x616000369380   id:    r3523            time:  2096.284
 0: 1310523.500     RDMA_REQ_TX_PENDING_C2H               cmid:  0x616000369380   id:    r3523            time:  2096.400
 0: 1310523.625     RDMA_REQ_RDY_TO_COMPL                 cmid:  0x616000369380   id:    r3523            time:  2096.531
 0: 1310524.250     RDMA_REQ_COMPLETING_C2H               cmid:  0x616000369380   id:    r3523            time:  2097.072
 0: 1341748.125     RDMA_REQ_COMPLETED                    cmid:  0x616000369380   id:    r3523            time:  33320.969
```
not sure this is a bug.

**Comment by yidong0635** [comment] 2020-12-21 05:47
sometimes :
[root@waikikibeach45 spdk]# sudo ./build/bin/spdk_trace -s nvmf -p 459375 | grep r2716
 ```
1: 684642.562     RDMA_REQ_NEW                          cmid:  0x61600122a680   id:    r2716
 1: 684642.812     RDMA_REQ_NEED_BUFFER                  cmid:  0x61600122a680   id:    r2716            time:  0.276
 1: 684643.625     RDMA_REQ_RDY_TO_EXECUTE               cmid:  0x61600122a680   id:    r2716            time:  1.118
 1: 684675.312     RDMA_REQ_EXECUTING                    cmid:  0x61600122a680   id:    r2716            time:  32.721
 1: 685554.250     RDMA_REQ_EXECUTED                     cmid:  0x61600122a680   id:    r2716            time:  911.765
 1: 685554.438     RDMA_REQ_TX_PENDING_C2H               cmid:  0x61600122a680   id:    r2716            time:  911.879
 1: 685554.500     RDMA_REQ_RDY_TO_COMPL                 cmid:  0x61600122a680   id:    r2716            time:  911.998
 1: 685554.812     RDMA_REQ_COMPLETING_C2H               cmid:  0x61600122a680   id:    r2716            time:  912.270
 1: 688657.500     RDMA_REQ_COMPLETED                    cmid:  0x61600122a680   id:    r2716            time:  4014.906
[root@waikikibeach45 spdk]# sudo ./build/bin/spdk_trace -s nvmf -p 459375 | grep r2716
 1: 681503.062     RDMA_REQ_NEW                          cmid:  0x61600122a680   id:    r2716
 1: 681503.375     RDMA_REQ_NEED_BUFFER                  cmid:  0x61600122a680   id:    r2716            time:  0.310
 1: 681504.375     RDMA_REQ_RDY_TO_EXECUTE               cmid:  0x61600122a680   id:    r2716            time:  1.282
 1: 681525.062     RDMA_REQ_EXECUTING                    cmid:  0x61600122a680   id:    r2716            time:  21.927
 1: 686161.625     RDMA_REQ_RDY_TO_COMPL                 cmid:  0x61600122a680   id:    r2716            time:  4658.529
 1: 686162.000     RDMA_REQ_COMPLETING_C2H               cmid:  0x61600122a680   id:    r2716            time:  4658.911
 1: 126687.469     RDMA_REQ_EXECUTED                     cmid:  0x61600122a680   id:    r2716            time:  7378697443082240.000
 1: 126687.594     RDMA_REQ_TX_PENDING_C2H               cmid:  0x61600122a680   id:    r2716            time:  7378697443082240.000
 1: 126687.727     RDMA_REQ_RDY_TO_COMPL                 cmid:  0x61600122a680   id:    r2716            time:  7378697443082240.000
 1: 126688.031     RDMA_REQ_COMPLETING_C2H               cmid:  0x61600122a680   id:    r2716            time:  7378697443082240.000
 1: 127167.281     RDMA_REQ_COMPLETED                    cmid:  0x61600122a680   id:    r2716            time:  7378697443082240.000

```
these values are so strange.

**Comment by yidong0635** [comment] 2020-12-22 10:10
using the latest code: 
`commit : 0dc567eb2d57b10ae554ff07667df5d8f84bc094`
At least we can see there's a narrow case about  time overflow, that is an issue of trace.cpp. 
like this : `time: 7378697443082240.000`
`get_us_from_tsc(`e->tsc - stats->start[e->object_id]`,  tsc_rate)`;
possible reasons lead to this:
1.  a new request is coming , but the time ticks are not recorded, d->new_object is assigned by trace record manually . .
2.  time record in stats->start[e->object_id] is abnormal.

```
diff --git a/app/trace/trace.cpp b/app/trace/trace.cpp
index 71350e85c..729f9904e 100644
--- a/app/trace/trace.cpp
+++ b/app/trace/trace.cpp
@@ -171,7 +171,7 @@ print_event(struct spdk_trace_entry *e, uint64_t tsc_rate,
        d = &g_histories->flags.tpoint[e->tpoint_id];
        stats = &g_stats[d->object_type];

-       if (d->new_object) {
+       if (d->new_object || stats->start[e->object_id] > e->tsc) {
                stats->index[e->object_id] = stats->counter++;
                stats->tpoint_id[e->object_id] = e->tpoint_id;
                stats->start[e->object_id] = e->tsc;

```
above can solve this  kind of issue.
but this : `time:  4014.906`  it seems right ,there're many requests in a queue to be finished async.
Any good advices ?
`

**Comment by mkenguva** [comment] 2021-01-06 23:45
using the latest master with the commit 45c42ac2f26d6f8ef484b32290791c659d9488f4 , i cannot reproduce this issue on my side

![image](https://user-images.githubusercontent.com/50601283/103833518-6fded100-503e-11eb-80f6-56a265bba3bd.png)

Please see if you see any different values with the suggestion you mentioned.

**Comment by jimharris** [comment] 2022-01-21 18:19
Closing this issue since it can't be reproduced.

**Closed by jimharris** 2022-01-21 18:19 UTC
Labels: bug, Low
