### ISSUE TITLE
run fio plugin fail : symbol lookup error

### ISSUE THREAD

**Issue by BlueParachute** [spdk/spdk#244] opened 2018-02-22 10:43 UTC
Hi,

I have followed all the steps in README.md of SPDK, DPDK and FIO plugin. 
After fully compiled (with "./configure --with-fio=/path/to/fio/repo") , I ran "sudo scripts/setup.sh", "Hello_World example" and "perf ", all of them work without problem.

But when I try to run FIO plugin, I got an error message like below :
LD_PRELOAD=/usr/src/test/spdk/examples/nvme/fio_plugin/fio_plugin fio example_config.fio 
/usr/bin/python3: symbol lookup error: /usr/src/test/spdk/examples/nvme/fio_plugin/fio_plugin: undefined symbol: unregister_ioengine

How can I fix this problem?

//--------------------------------------------------------------------------//
My test environment is as below : 
"ubuntu 16.04 LTS (kernel 4.10.0-28-generic)"
"SPDK 17.10"
"DPDK 17.08"
"FIO 2.21"

My FIO script content is as below :
[global]
ioengine=spdk
thread=1
group_reporting=1
direct=1
verify=0
time_based=1
ramp_time=0
runtime=2
iodepth=128
rw=randrw
bs=4k

[test]
numjobs=1
filename=trtype=PCIe traddr=0000.02.00.0 ns=1

**Comment by jimharris** [comment] 2018-02-22 15:14
Hi,

I am not able to reproduce this problem so will need some additional details.

First – can you confirm that the fio in your path matches the one built and installed from your fio repo?

Also – where does /usr/bin/python3 come in here?  fio is not a Python script.

Thanks,

-Jim

**Comment by dverkamp-intel** [comment] 2018-02-22 15:59
Please be sure that you are using the same version of fio that you compiled the plugin with, e.g. /path/to/fio/repo/fio rather than the system fio installed in $PATH.

**Comment by BlueParachute** [comment] 2018-02-23 07:54
Hi all, thanks for the reply.

Jimharris,
(1) My folder of FIO cloned from git is under "/usr/src/ ", and folder of SPDK cloned from git is also  
     under "/usr/src/ ".

(2) I am not sure why python showed up in error message.

Dverkamp-intel, 
I am using the FIO in SPDK fio_plugin folder.
( LD_PRELOAD=/usr/src/test/spdk/examples/nvme/fio_plugin/fio_plugin fio example_config.fio )

My FIO was cloned from FIO git, and the FIO folder is under "/usr/src/ ". 
When I was at configure step, the command line is as follow : "./configure --with-fio=/usr/src/fio/". Then I type "make" to compile SPDK.

**Comment by darsto** [comment] 2018-02-23 09:55
Hi,

> LD_PRELOAD=/usr/src/test/spdk/examples/nvme/fio_plugin/fio_plugin fio
example_config.fio

Are you sure the `fio` above is the one in /usr/src/fio/fio?
Can you try the following?

$ cd /usr/src/fio
$ ./configure
$ make
$ LD_PRELOAD=/usr/src/test/spdk/examples/nvme/fio_plugin/fio_plugin
/usr/src/fio/fio example_config.fio

Regards,
D.

2018-02-23 8:54 GMT+01:00 BlueParachute <notifications@github.com>:

**Comment by BlueParachute** [comment] 2018-02-23 10:42
Hi Darsto,

Great thanks!
After I followed your step, the FIO run well now, with SPDK engine.
By the way, where can I set the path for fio, so I don't have to assign which folder should fio_plugin looking for fio again.

**Comment by darsto** [comment] 2018-02-23 12:08
> By the way, where can I set the path for fio, so I don't have to assign
which folder should fio_plugin looking for fio again.

If you want it to be accessible as just `fio`, you should replace the
system fio binary, which can be located with:

$ which fio

Or you could rename it to e.g. `fio-3.3` and copy to one of the directories
in PATH:

$ echo $PATH

Regards,
D.


2018-02-23 11:42 GMT+01:00 BlueParachute <notifications@github.com>:

**Comment by dverkamp-intel** [comment] 2018-03-28 23:38
This looks like it was resolved by running the correct version of fio; I'm going to close it unless there are further issues.

**Closed by dverkamp-intel** 2018-03-28 23:38 UTC
