### ISSUE TITLE
SPDK perf can not connect to NVMe_OF target of kernel 5.3.18-95.54-default+ of SLES

### ISSUE THREAD

**Issue by sunmingbao** [spdk/spdk#1719] opened 2020-12-10 05:43 UTC
SPDK perf can not connect to NVMe_OF target of kernel 5.3.18-95.54-default+ of SLES.

## Current Behavior

create_qp failed in kernel-space at the target side.
## Steps to Reproduce

1. Setup a normal NVMe_OF target on HOST murray-dirt.
2. Connect to the above target from HOST lehi-dirt with the following command.
./perf -q 64 -P 1 -s 4096 -w read -t 300 -c 0x1 -o 4096 -r 'trtype:RDMA adrfam:IPv4 traddr:169.254.85.8 trsvcid:4420'

## Context (Environment including OS version, SPDK version, etc.)

Following are the logs of a reproduction:
```
HOST lehi-dirt:

lehi-dirt:/home/admin/NVMe_OF_test # ./perf -q 64 -P 1 -s 4096 -w read -t 300 -c 0x1 -o 4096 -r 'trtype:RDMA adrfam:IPv4 traddr:169.254.85.8 trsvcid:4420'
Starting SPDK v20.04.1 git sha1 c5f0959de / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 -m 4096 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid99132 ]
EAL: No available hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
Attached to NVMe over Fabrics controller at 169.254.85.8:4420: testnqn_1
Associating RDMA (addr:169.254.85.8 subnqn:testnqn_1) NSID 1 with lcore 0
Initialization complete. Launching workers.
nvme_rdma.c: 438:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_ESTABLISHED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = 28)
nvme_rdma.c: 933:nvme_rdma_connect: *ERROR*: RDMA connect error
nvme_rdma.c:1163:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
nvme_ctrlr.c: 434:spdk_nvme_ctrlr_alloc_io_qpair: *ERROR*: nvme_transport_ctrlr_connect_io_qpair() failed
ERROR: spdk_nvme_ctrlr_alloc_io_qpair failed
ERROR: init_ns_worker_ctx() failed
========================================================
                                                                                                 Latency(us)
Device Information                                           :       IOPS      MiB/s    Average        min        max
Segmentation fault (core dumped)


HOST murray-dirt:

murray-dirt:~ # ~/poll_dmesg.sh 
[59352.216049] nvmet: creating controller 1 for subsystem nqn.2014-08.org.nvmexpress.discovery for NQN 2014-08.org.nvmexpress:uuid:e042cf76-5e27-45cd-99a7-a637c4cc2c9b.
[59352.222697] nvmet: creating controller 2 for subsystem testnqn_1 for NQN 2014-08.org.nvmexpress:uuid:e042cf76-5e27-45cd-99a7-a637c4cc2c9b.
[59352.227717] nvmet_rdma: failed to create_qp ret= -12
[59352.227866] nvmet_rdma: nvmet_rdma_alloc_queue: creating RDMA queue failed (-12).
```

Environment info:

HOST lehi-dirt:

lehi-dirt:/home/admin # cat /etc/os-release 
NAME="SLES"
VERSION="12-SP4"
VERSION_ID="12.4"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp4"

lehi-dirt:/home/admin # uname -a
Linux lehi-dirt 5.3.18-95.54-default+ #1 SMP Thu Nov 19 10:05:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

murray-dirt:

murray-dirt:/home/admin # cat /etc/os-release 
NAME="SLES"
VERSION="12-SP4"
VERSION_ID="12.4"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp4"

murray-dirt:/home/admin # uname -a
Linux murray-dirt 5.3.18-95.54-default+ #1 SMP Thu Nov 19 10:09:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by changpe1** [comment] 2020-12-10 06:03
This should be related with NVMoF target
nvmet_rdma: failed to create_qp ret= -12, the errno is ENOMEM when creating IO queue pair in target, you may try with SPDK target to see the issue is still exist or not.

**Comment by sunmingbao** [comment] 2020-12-10 07:04
The error code -ENOMEM can not reflect the actual reason.
I had ever rebooted the 2 hosts, and re-execute the same command, and also got a fail result.
I have also tried to just create RDMA RC QPs using a test tool with the same target, and it works well.

I have also verified that the same perf command can work well with the target powered by MLNX_OFED_LINUX-4.9-0.1.7.0-sles12sp4-x86_64.tgz.

**Comment by sunmingbao** [comment] 2020-12-10 07:08
And the initiator of kernel-space can work well with the same target on the same 2 hosts.
Following are the logs:
lehi-dirt:/home/admin # nvme connect --transport=rdma --nqn=testnqn_1  --traddr=169.254.85.8 --trsvcid=4420
lehi-dirt:/home/admin #

**Comment by AlekseyMarchuk** [comment] 2020-12-10 09:01
Hi,

SPDK nvme perf tool sets io_queue_depth to UINT16_MAX. Later when NVME controller is created this value is decreased to 1024 (in my case). So SPDK RDMA initiator in fabric_connect command sends hrqsize=1024 and hsqsize=1023.
NVMEoF target can adjust these values requested by initiator to values supported by target/HW. SPDK target does so and sends adjusted io_size in RDMA_CM rdma_accept() private data.
I think that out-of-box kernel target doesn't adjust values reported by initiator and try to create qpair with recevied values. As we can see, it fails.

To check it, could you try to load kernel nvme module with io_queue_depth=1024 and try to connect to target. As I remember kernel nvme driver uses io_queue_depth=64 by default

**Comment by AlekseyMarchuk** [comment] 2020-12-10 09:22
I think that io_queue_depth in perf should be corrected. It should be aligned to queue_depth configured by the user and payload size/controller MDTS. I'll prepare a patch soon

**Comment by sunmingbao** [comment] 2020-12-10 10:05
@AlekseyMarchuk  I have tried the following steps, but still got a fail result.

Following are the logs:

murray-dirt:/sys/module # nvmetcli clear
murray-dirt:/sys/module # rmmod nvmet_rdma
murray-dirt:/sys/module # insmod /lib/modules/5.3.18-95.54-default+/kernel/drivers/nvme/target/nvmet-rdma.ko io_queue_depth=64

murray-dirt:/home/admin/NVMe_OF_test # ./setup_target.sh 
create target: testnqn_1 /dev/nvme0n1p1 169.254.85.8 4420 1
create target: testnqn_2 /dev/nvme1n1p1 169.254.85.8 4421 2
create target: testnqn_3 /dev/nvme2n1p1 169.254.85.8 4422 3
create target: testnqn_4  169.254.85.8 4423 4
create target: testnqn_5  169.254.85.8 4424 5

lehi-dirt:/home/admin/NVMe_OF_test # ./perf -q 64 -P 1 -s 4096 -w read -t 300 -c 0x1 -o 65536 -r 'trtype:RDMA adrfam:IPv4 traddr:169.254.85.8 trsvcid:4420'
Starting SPDK v20.04.1 git sha1 c5f0959de / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 -m 4096 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid41274 ]
EAL: No available hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
Attached to NVMe over Fabrics controller at 169.254.85.8:4420: testnqn_1
Associating RDMA (addr:169.254.85.8 subnqn:testnqn_1) NSID 1 with lcore 0
Initialization complete. Launching workers.
nvme_rdma.c: 438:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_ESTABLISHED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = 28)
nvme_rdma.c: 933:nvme_rdma_connect: *ERROR*: RDMA connect error
nvme_rdma.c:1163:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
nvme_ctrlr.c: 434:spdk_nvme_ctrlr_alloc_io_qpair: *ERROR*: nvme_transport_ctrlr_connect_io_qpair() failed
ERROR: spdk_nvme_ctrlr_alloc_io_qpair failed
ERROR: init_ns_worker_ctx() failed
========================================================
                                                                                                 Latency(us)
Device Information                                           :       IOPS      MiB/s    Average        min        max
Segmentation fault (core dumped)
lehi-dirt:/home/admin/NVMe_OF_test # 

murray-dirt:/home/admin/NVMe_OF_test # ~/poll_dmesg.sh 
[ 9259.318183] nvmet: creating controller 1 for subsystem nqn.2014-08.org.nvmexpress.discovery for NQN 2014-08.org.nvmexpress:uuid:5b9c1673-42a6-47bc-8bd0-ee72035369c4.
[ 9259.325316] nvmet: creating controller 2 for subsystem testnqn_1 for NQN 2014-08.org.nvmexpress:uuid:5b9c1673-42a6-47bc-8bd0-ee72035369c4.
[ 9259.330389] nvmet_rdma: failed to create_qp ret= -12
[ 9259.330510] nvmet_rdma: nvmet_rdma_alloc_queue: creating RDMA queue failed (-12).

**Comment by AlekseyMarchuk** [comment] 2020-12-10 10:25
@sunmingbao I think that there are 2 problems
1. perf tool uses very big queue_depth. It can be corrected, I'll prepare a patch
2. out of box RDMA nvmet doesn't adjust hsqsize received in RDMA_CM private data. I would say it is 3rd party issue and as you said nvmet from MOFED doesn't have such a problem

Regarding your results with nvme kernel initiator - I suggested to set `io_queue_depth=1024` to check if out of box RDMA nvmet also rejects the connection due to out of memory.

**Comment by AlekseyMarchuk** [comment] 2020-12-10 16:38
@sunmingbao could you try this patch https://review.spdk.io/gerrit/c/spdk/spdk/+/5529 ?

**Comment by sunmingbao** [comment] 2020-12-11 02:42
@AlekseyMarchuk I found that the NVMe_OF related modules from the mentioned kernel do not have the module param io_queue_depth, except for the host/nvme.ko (host/pci.c).
So my last try of loading module with io_queue_depth=64 is meaningless.
However, I will try changing  io_queue_depth from "nvme connect" command, and try the patch you provided, and upload the results later.

**Comment by sunmingbao** [comment] 2020-12-11 02:48
@AlekseyMarchuk
Good news.
By changing the queue-size in "nvme connect" command, the issue was reproduced with nvme kernel initiator.

Following are the logs:

lehi-dirt:/home/admin # nvme connect --transport=rdma --queue-size=1024 --nqn=testnqn_1  --traddr=169.254.85.8 --trsvcid=4420
Failed to write to /dev/nvme-fabrics: Connection reset by peer

murray-dirt:/home/admin/NVMe_OF_test # ~/poll_dmesg.sh 
[ 1088.158178] nvmet: creating controller 1 for subsystem testnqn_1 for NQN nqn.2014-08.org.nvmexpress:uuid:42151199-7094-470b-b264-fac6ac3c4ff3.
[ 1088.297458] nvmet_rdma: failed to create_qp ret= -12
[ 1088.297736] nvmet_rdma: nvmet_rdma_alloc_queue: creating RDMA queue failed (-12).

**Comment by sunmingbao** [comment] 2020-12-11 03:52
@AlekseyMarchuk 
Good news.
The issue was resolved by your patch.

Following are the logs:

lehi-dirt:/home/admin/NVMe_OF_test # ./perf -q 64 -P 1 -s 4096 -w read -t 5 -c 0x1 -o 4096 -r 'trtype:RDMA adrfam:IPv4 traddr:169.254.85.8 trsvcid:4420'
Starting SPDK v20.04.1 git sha1 c5f0959de / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 -m 4096 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid99216 ]
EAL: No available hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
Attached to NVMe over Fabrics controller at 169.254.85.8:4420: testnqn_1
Associating RDMA (addr:169.254.85.8 subnqn:testnqn_1) NSID 1 with lcore 0
Initialization complete. Launching workers.
========================================================
                                                                                                 Latency(us)
Device Information                                           :       IOPS      MiB/s    Average        min        max
RDMA (addr:169.254.85.8 subnqn:testnqn_1) NSID 1 from core  0:  289381.00    1130.39     221.15      48.26    5438.02
========================================================
Total                                                        :  289381.00    1130.39     221.15      48.26    5438.02

**Comment by sunmingbao** [comment] 2020-12-18 06:44
@AlekseyMarchuk 
Since this issue can be reproduced by the following command, I will report it to SUSE.

nvme connect --transport=rdma --queue-size=1024 --nqn=testnqn_1 --traddr=169.254.85.8 --trsvcid=4420

**Comment by AlekseyMarchuk** [comment] 2021-01-20 12:03
Hello @sunmingbao Since we found out that this is a problem in SUSE and patch in SPDK introduces another problem in kernel nvmf target, I think can we close this issue and #1722. Does that suit you?

**Comment by sunmingbao** [comment] 2021-01-22 02:53
@AlekseyMarchuk 
Yes, the root cause is the bug in the kernel of SUSE.
So both this issue and #1722 may be closed now.

Many thanks for supporting us.

**Comment by changpe1** [comment] 2021-01-22 05:58
Thanks @sunmingbao, closing this issue now.

**Closed by changpe1** 2021-01-22 05:58 UTC
Labels: 3rd party issue, Medium, bug
