### ISSUE TITLE
my machine is centos7.6 x86_64; when I config as the documentatio, after I  run "examples/nvme/identify/identify" ,the output is "No available hugepages reported in hugepages   No NVMe controllers found"

### ISSUE THREAD

**Issue by ywbgithub** [spdk/spdk#1080] opened 2019-11-27 09:12 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by yidong0635** [comment] 2019-11-27 09:49
@ywbgithub , please confirm you have done this:
 Firstly,to check you have  any nvme device:  `lspci | grep Non`.
 after finish compiling,do something like : `sudo HUGEMEM=4096 scripts/setup.sh `
you can refer to page: https://spdk.io/doc/getting_started.html

**Comment by ywbgithub** [comment] 2019-11-27 10:12
when I execute the command  "lspci | grep Non" , there is no nothing output

**Comment by ywbgithub** [comment] 2019-11-27 10:17
when I execute the command "lspci | grep Non" ,there is nothing output.
the following is the output of lspci:
00:00.0 Host bridge: Intel Corporation 8th Gen Core Processor Host Bridge/DRAM Registers (rev 08)
00:02.0 VGA compatible controller: Intel Corporation 8th Gen Core Processor Gaussian Mixture Model
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th Gen Core Processor Gaussian Mixture Model
00:14.0 USB controller: Intel Corporation 200 Series/Z370 Chipset Family USB 3.0 xHCI Controller
00:14.2 Signal processing controller: Intel Corporation 200 Series PCH Thermal Subsystem
00:16.0 Communication controller: Intel Corporation 200 Series PCH CSME HECI #1
00:17.0 SATA controller: Intel Corporation 200 Series PCH SATA controller [AHCI mode]
00:1b.0 PCI bridge: Intel Corporation 200 Series PCH PCI Express Root Port #17 (rev f0)
00:1b.4 PCI bridge: Intel Corporation 200 Series PCH PCI Express Root Port #21 (rev f0)
00:1c.0 PCI bridge: Intel Corporation 200 Series PCH PCI Express Root Port #1 (rev f0)
00:1c.3 PCI bridge: Intel Corporation 200 Series PCH PCI Express Root Port #4 (rev f0)
00:1f.0 ISA bridge: Intel Corporation Z370 Chipset LPC/eSPI Controller
00:1f.2 Memory controller: Intel Corporation 200 Series/Z370 Chipset Family Power Management Controller
00:1f.3 Audio device: Intel Corporation 200 Series PCH HD Audio
00:1f.4 SMBus: Intel Corporation 200 Series/Z370 Chipset Family SMBus Controller
02:00.0 Mass storage controller: Device 1cb0:d000 (rev 03)
04:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)

**Comment by benlwalker** [comment] 2019-11-27 16:43
You don't appear to have any NVMe devices on your system.

**Comment by ywbgithub** [comment] 2019-11-28 02:03
I have inserted a nvme pcie ssd card in the socket, it is displayed as ""02:00.0 Mass storage controller: Device 1cb0:d000 (rev 03)"" when I execute the command ""lspci""
what is the wrong

**Comment by yidong0635** [comment] 2019-11-28 03:24
from the pci_ids.h to lookup the class code/vid/pid of this device, it may not be recognized as Nvme device.

**Comment by ywbgithub** [comment] 2019-11-28 10:41
how to fix the problem

**Comment by wawryk** [comment] 2019-11-29 06:53
I think that is the same problem https://github.com/spdk/spdk/issues/1082
If it works for You please close both issues ;)

**Comment by ywbgithub** [comment] 2019-12-05 03:25
no, they are different problems

**Comment by glodfish-zg** [comment] 2019-12-05 08:07
Hi, @ywbgithub.
Just check that your NVMe SSD seems to come from Shannon Systems(Vendor:1cb0). Please lspci -x to check the class ID(Should be 0x010802) and check /sys/bus/pci/devices/0000\:02\:00.0/.

I guess it's the device issue as we don't have the same device we can't reproduce. You can use an intel NVMe SSD to test If you can confirm that I will close this issue.

**Comment by yidong0635** [comment] 2019-12-06 01:55
link issue to  #1094 . and can close this one.

**Comment by jimharris** [comment] 2020-01-08 21:16
Hi @ywbgithub,

Please see the comment from @glodfish-zg.  My guess is that this SSD is not reporting itself as an NVMe SSD (class/subclass/PI = 0x010802) so SPDK does not attach to it.

You could try modifying lib/env_dpdk/pci_nvme.c, adding a new entry in the nvme_pci_driver_id array with the vendor/device ID for your NVMe SSD.

-Jim

**Comment by jimharris** [comment] 2020-02-27 17:04
Closing this issue - looks like a 3rd party issue with this specific SSD.

@ywbgithub - if you are able, please report back if adding the new entry helped in your case.

Thanks,

-Jim

**Closed by jimharris** 2020-02-27 17:04 UTC
Labels: Waiting on Submitter
