### ISSUE TITLE
Random write IOPS by Perf is over than NVMe device spec.

### ISSUE THREAD

**Issue by tafukuyama** [spdk/spdk#297] opened 2018-05-14 04:11 UTC
We run spdk perf random write and found that reported IOPS is over than NVMe device spec.
We confirmed spdk perf random read looks reasonable IOPS.
This issue occurs only when random write.

We use  Intel® SSD DC P3700 Series 400GB for our test devices.
As far as looking below datasheet, random write IOPS for a single device is about 75KIOPS.
https://www.intel.com/content/dam/support/us/en/documents/ssdc/hpssd/sb/Intel_SSD_DC_P3700_Series_PCIe_Product_Specification-005.pdf

But we get 175KIOPS when using spdk + perf with # of cores=1, iodepth=128, # of NVMe=1.
We tested spdk + fio_pulgin for our reference and it scored reasonable value.(85KIOPS)
We also observed same result in spdk + perf + aio (*1) (117KIOPS)
*1: After executing "/root/spdk-master/scripts/setup.sh reset",  specify /dev/nvmeXn1 in pref command line.

![image](https://user-images.githubusercontent.com/29906937/39975713-3a67a908-576b-11e8-8d4c-826685a40285.png)

\# /root/spdk-master/examples/nvme/perf/perf -q 128 -s 4096 -w randwrtie -t 600 -c 0x0001 -D -LL -r 'trtype:PCIe traddr:0000.01.00.0'
Starting SPDK v18.04-pre / DPDK 18.02.1 initialization...
[ DPDK EAL parameters: perf -c 0x0001 --file-prefix=spdk_pid27748 ]
EAL: Multi-process socket /var/run/.spdk_pid27748_unix
EAL: Probing VFIO support...
Initializing NVMe Controllers
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
Attaching to NVMe Controller at 0000:01:00.0
Attached to NVMe Controller at 0000:01:00.0 [8086:0953]
Associating INTEL SSDPE2MD400G4  (CVFT4396003G400GGN  ) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0
\========================================================
                                                                                            Latency(us)
Device Information                                     :       IOPS       MB/s    Average        min        max
INTEL SSDPE2MD400G4  (CVFT4396003G400GGN  ) from core 0:  174892.30     683.17     731.81       4.69   21524.00
\========================================================
Total                                                  :  174892.30     683.17     731.81       4.69   21524.00

Summary latency data for INTEL SSDPE2MD400G4  (CVFT4396003G400GGN  ) from core 0:
\=================================================================================
  1.00000% :     6.918us
 10.00000% :    13.592us
 25.00000% :    33.646us
 50.00000% :   444.709us
 75.00000% :  1022.050us
 90.00000% :  2122.118us
 95.00000% :  2559.025us
 98.00000% :  3183.177us
 99.00000% :  3729.310us
 99.50000% :  4431.482us
 99.90000% :  6834.469us
 99.99000% :  9924.023us
 99.99900% : 12607.878us
 99.99990% : 20222.537us
 99.99999% : 21470.842us

![image](https://user-images.githubusercontent.com/29906937/39975769-833616a6-576b-11e8-9139-7993b24a9ff0.png)

\# /root/spdk-master/examples/nvme/perf/perf -q 128 -s 4096 -w randwrtie -t 600 -c 0x000f -D -LL -r 'trtype:PCIe traddr:0000.01.00.0' -r 'trtype:PCIe traddr:0000.03.00.0' -r 'trtype:PCIe traddr:0000.82.00.0' -r 'trtype:PCIe traddr:0000.84.00.0'
Starting SPDK v18.04-pre / DPDK 18.02.1 initialization...
[ DPDK EAL parameters: perf -c 0x000f --file-prefix=spdk_pid18218 ]
EAL: Multi-process socket /var/run/.spdk_pid18218_unix
EAL: Probing VFIO support...
Initializing NVMe Controllers
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
Attaching to NVMe Controller at 0000:01:00.0
Attached to NVMe Controller at 0000:01:00.0 [8086:0953]
EAL: PCI device 0000:03:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
Attaching to NVMe Controller at 0000:03:00.0
Attached to NVMe Controller at 0000:03:00.0 [8086:0953]
EAL: PCI device 0000:82:00.0 on NUMA socket 1
EAL:   probe driver: 8086:953 spdk_nvme
Attaching to NVMe Controller at 0000:82:00.0
Attached to NVMe Controller at 0000:82:00.0 [8086:0953]
EAL: PCI device 0000:84:00.0 on NUMA socket 1
EAL:   probe driver: 8086:953 spdk_nvme
Attaching to NVMe Controller at 0000:84:00.0
Attached to NVMe Controller at 0000:84:00.0 [8086:0953]
Associating INTEL SSDPE2MD400G4  (CVFT61220012400GGN  ) with lcore 3
Associating INTEL SSDPE2MD400G4  (CVFT4400002C400GGN  ) with lcore 2
Associating INTEL SSDPE2MD400G4  (CVFT7021006H400PGN  ) with lcore 1
Associating INTEL SSDPE2MD400G4  (CVFT4396003G400GGN  ) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 3
Starting thread on core 2
Starting thread on core 1
Starting thread on core 0
\========================================================
                                                                                            Latency(us)
Device Information                                     :       IOPS       MB/s    Average        min        max
INTEL SSDPE2MD400G4  (CVFT61220012400GGN  ) from core 3:  149532.80     584.11     855.93       5.04   21698.07
INTEL SSDPE2MD400G4  (CVFT4400002C400GGN  ) from core 2:  145423.03     568.06     880.12       5.07   19903.95
INTEL SSDPE2MD400G4  (CVFT7021006H400PGN  ) from core 1:  148992.53     582.00     859.01       4.70   19746.74
INTEL SSDPE2MD400G4  (CVFT4396003G400GGN  ) from core 0:  146920.86     573.91     871.14       4.72   19918.79
\========================================================
Total                                                  :  590869.23    2308.08     866.44       4.70   21698.07

Summary latency data for INTEL SSDPE2MD400G4  (CVFT61220012400GGN  ) from core 3:
\=================================================================================
  1.00000% :     7.467us
 10.00000% :    13.653us
 25.00000% :    31.451us
 50.00000% :   456.411us
 75.00000% :  1365.333us
 90.00000% :  2465.402us
 95.00000% :  2949.120us
 98.00000% :  3604.480us
 99.00000% :  4213.029us
 99.50000% :  4899.596us
 99.90000% :  7614.659us
 99.99000% : 10360.930us
 99.99900% : 13918.598us
 99.99990% : 19848.046us
 99.99999% : 21720.503us

Summary latency data for INTEL SSDPE2MD400G4  (CVFT4400002C400GGN  ) from core 2:
\=================================================================================
  1.00000% :     7.345us
 10.00000% :    12.739us
 25.00000% :    27.550us
 50.00000% :   470.065us
 75.00000% :  1435.550us
 90.00000% :  2527.817us
 95.00000% :  2995.931us
 98.00000% :  3635.688us
 99.00000% :  4275.444us
 99.50000% :  4930.804us
 99.90000% :  7458.621us
 99.99000% : 10298.514us
 99.99900% : 13544.107us
 99.99990% : 19348.724us
 99.99999% : 19723.215us

Summary latency data for INTEL SSDPE2MD400G4  (CVFT7021006H400PGN  ) from core 1:
\=================================================================================
  1.00000% :     6.888us
 10.00000% :    13.410us
 25.00000% :    33.890us
 50.00000% :   440.808us
 75.00000% :  1326.324us
 90.00000% :  2543.421us
 95.00000% :  3042.743us
 98.00000% :  3713.707us
 99.00000% :  4337.859us
 99.50000% :  4993.219us
 99.90000% :  7333.790us
 99.99000% : 10360.930us
 99.99900% : 14105.844us
 99.99990% : 19348.724us
 99.99999% : 19848.046us

Summary latency data for INTEL SSDPE2MD400G4  (CVFT4396003G400GGN  ) from core 0:
\=================================================================================
  1.00000% :     6.857us
 10.00000% :    13.166us
 25.00000% :    32.427us
 50.00000% :   452.510us
 75.00000% :  1388.739us
 90.00000% :  2527.817us
 95.00000% :  3011.535us
 98.00000% :  3698.103us
 99.00000% :  4337.859us
 99.50000% :  5024.427us
 99.90000% :  7583.451us
 99.99000% : 10485.760us
 99.99900% : 12857.539us
 99.99990% : 18474.910us
 99.99999% : 19972.876us

## Expected Behavior

We should get stable IOPS in specification.

## Current Behavior

Perf random write IOPS is over than NVMe device spec.

## Possible Solution

N/A

## Steps to Reproduce

1. Build SPDK with DPDK
We build SPDK & DPDK in reference to below pages.
https://github.com/spdk/spdk/blob/master/README.md
http://dpdk.org/doc/quick-start
2. Hugepages and Device Binding
HUGEMEM=20480 /root/spdk-master/scripts/setup.sh
3. Preconditioning of NVMe devices
/root/spdk-master/examples/nvme/perf/perf -q 32 -s 4096 -w randwrite -t 5400 -c 0xf
4. Run Perf
/root/spdk-master/examples/nvme/perf/perf -q ${IODEPTH} -s 4096 -w randwrtie -t 600 -c 0x${COREMASK} -D -LL -r 'trtype:PCIe traddr:0000.01.00.0' -r 'trtype:PCIe traddr:0000.03.00.0' -r 'trtype:PCIe traddr:0000.82.00.0' -r 'trtype:PCIe traddr:0000.84.00.0'

*We run perf repeatedly changing CPUMASK, IOPDEPTH parameters and the number of NVMe devices. EX: when the number of NVMe devices is 4, we adjust (CPUMASK : IODEPTH) as followings so that the value of "(# of cores) * IODEPTH / (# of NVMe)" set to be 128.
    (ffff:32)->(00ff:64)->(000f:128)->(0003:256)->(0001:512)
We run perf in order of the most NVMes first and reduce the number of NVMes in subsequent test so that the NVMes we are using can stay active. We have 4 NVMe devices so we changed the number of target NVMes as 4, 2, 1.

## Context (Environment including OS version, SPDK version, etc.)

OS: Red Hat Enterprise Linux 7.3
Linux Kernel: 4.15.1
SPDK: 18.04 (Unzip and build spdk-master.zip downloaded on April 24th, 2018 from SPDK github.)
DPDK: 18.02.1
Serve model: Supermicro® 6028R-TDWNR (M/B: X10DDW-iN)
Processor: Intel® Xeon® E5-2620v4 (8core/16thread/2.1GHz/20MB cache) x2
Memory: 64GiB (DDR4-2400 8GiB x 8DIMMs)
NVMe: Intel® SSD DC P3700 Series 400GB(2.5inch MLC PCIe NVMe 3.0) x4

**Comment by jaedan** [comment] 2018-05-14 14:16
It's especially critical that you precondition and then immediately run the benchmark - with no delay. The device will background defrag otherwise and undo the preconditioning.

**Comment by jimharris** [comment] 2018-05-14 14:47
@jaedan is exactly right.  Thank you for clarifying that.

**Comment by benlwalker** [comment] 2018-05-14 15:10
It is especially important that you run the benchmark immediately after precondition. The drive will undo the reconditioning via defrag otherwise.

**Comment by tafukuyama** [comment] 2018-05-15 00:59
Thank you for you comments.
More detailed our test procedure is below.

1. 90minutes random write ssd preconditioning
    /root/spdk-master/examples/nvme/perf/perf -q 32 -s 4096 -w randwrite -t 5400 -c 0xf
2. Wait for 3 minutes
3. Run perf random write
   We measured 81 test combinations of CPUMASK, IOPDEPTH and # of NVMe devices continuously.
   Runtime for each test condition is 10 minutes.
   We waited  for 10 sec between each test condition.
4. System reboot
   When we change IO tool (perf/fio_plugin/perf+aio), we reboot the system once and rerun from step1. ssd preconditioning.

So your suggestions are step2 is not necessary and runtime for each test condition should be 30 minutes? We're also wondering if one time ssd precondition is enough for following 81 test combinations.

Best Regards,
Taisuke Fukuyama

**Comment by tafukuyama** [comment] 2018-05-16 03:06
Regarding runtime,
we applied the following patch by whom perf becomes able to output aggregated IOPS data in any time interval during the test.

perf: Add option to get real time stats (exponential moving average)
https://review.gerrithub.io/#/c/spdk/spdk/+/411054/

Then we found IOPS is always over than NVMe device spec and no tendency observed like IOPS reduction by passage of time.
So changing runtime to 30 minutes seems to have no effect for our test result.

Regarding wait time after NVMe preconditioning,
do you think we should take no time waits after NVMe preconditioning not only for random write but also for random read?
We'd like to confirm again because we've configured our past performance test as taking these time waits.
We also want to know if 10 sec time waits between each test condition is unnecessary.

We're now planing to rerun perf random write following your suggestions.
It takes pretty long time to rerun the test, 
so before we start, we want your comment or advice.
Thanks!

Best Regards,
Taisuke Fukuyama

**Comment by jimharris** [comment] 2018-05-18 04:06
Great piece of data!

Could you try one of the fio tests again, but specify norandommap=1?

On May 17, 2018, at 8:21 PM, tafukuyama <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for your reply.

We've checked following test conditions and found same behavior can be seen only when using perf regardless of ioengine and NVMe driver.

Tool    ioengine        NVMe driver     Result
perf    aio (/dev/nvmeXn1)      nvme    Over than device spec IOPS
perf    spdk    uio_pci_generic Over than device spec IOPS
fio     aio (/dev/nvmeXn1)      nvme    Reasonable IOPS observed
fio_plugin      spdk    uio_pci_generic Reasonable IOPS observed

Test log of perf + aio + nvme is shown in below.

# Reset SPDK setting (Change the NVMe driver from uio_pci_generic to nvme.)
[root@dev16 ~]# /root/spdk-master/scripts/setup.sh reset
0000:01:00.0 (8086 0953): uio_pci_generic -> nvme
0000:03:00.0 (8086 0953): uio_pci_generic -> nvme
0000:82:00.0 (8086 0953): uio_pci_generic -> nvme
0000:84:00.0 (8086 0953): uio_pci_generic -> nvme
[root@dev16 ~]# lspci -k | grep Non-Volatile -A 3
01:00.0 Non-Volatile memory controller: Intel Corporation PCIe Data Center SSD (rev 01)
Subsystem: Intel Corporation DC P3700 SSD [2.5" SFF]
Kernel driver in use: nvme
Kernel modules: nvme
03:00.0 Non-Volatile memory controller: Intel Corporation PCIe Data Center SSD (rev 01)
Subsystem: Intel Corporation DC P3700 SSD [2.5" SFF]
Kernel driver in use: nvme
Kernel modules: nvme
--
82:00.0 Non-Volatile memory controller: Intel Corporation PCIe Data Center SSD (rev 01)
Subsystem: Intel Corporation DC P3700 SSD [2.5" SFF]
Kernel driver in use: nvme
Kernel modules: nvme
84:00.0 Non-Volatile memory controller: Intel Corporation PCIe Data Center SSD (rev 01)
Subsystem: Intel Corporation DC P3700 SSD [2.5" SFF]
Kernel driver in use: nvme
Kernel modules: nvme
[root@dev16 ~]#

# NVMe preconditioning
[root@dev16 ~]# /root/spdk-master/examples/nvme/perf/perf -q 32 -s 4096 -w randwrite -t 5400 -c 0x000f /dev/nvme0n1 /dev/nvme1n1 /dev/nvme2n1 /dev/nvme3n1

# Run perf random write using aio
[root@dev16 ~]# /root/spdk-master/examples/nvme/perf/perf -q 128 -s 4096 -w randwrite -t 600 -c 0x000f -D -L /dev/nvme0n1 /dev/nvme1n1 /dev/nvme2n1 /dev/nvme3n1
Starting SPDK v18.04-pre / DPDK 18.02.1 initialization...
[ DPDK EAL parameters: perf -c 0x000f --file-prefix=spdk_pid22193 ]
EAL: Multi-process socket /var/run/.spdk_pid22193_unix
EAL: Probing VFIO support...
Initializing NVMe Controllers
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL: probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:03:00.0 on NUMA socket 0
EAL: probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:82:00.0 on NUMA socket 1
EAL: probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:84:00.0 on NUMA socket 1
EAL: probe driver: 8086:953 spdk_nvme
Associating /dev/nvme3n1 with lcore 3
Associating /dev/nvme2n1 with lcore 2
Associating /dev/nvme1n1 with lcore 1
Associating /dev/nvme0n1 with lcore 0
Initialization complete. Launching workers.
Starting thread on core 3
Starting thread on core 2
Starting thread on core 1
Starting thread on core 0
========================================================
Latency(us)
Device Information : IOPS MB/s Average min max
/dev/nvme3n1 from core 3: 125862.52 491.65 1016.78 8.46 20642.89
/dev/nvme2n1 from core 2: 126463.94 494.00 1011.93 8.77 19390.04
/dev/nvme1n1 from core 1: 124665.71 486.98 1026.51 8.46 22424.84
/dev/nvme0n1 from core 0: 123550.96 482.62 1035.79 8.31 17892.64
========================================================
Total : 500543.13 1955.25 1022.67 8.31 22424.84

Summary latency data for /dev/nvme3n1 from core 3:
=================================================================================
1.00000% : 14.507us
10.00000% : 43.886us
25.00000% : 197.973us
50.00000% : 403.749us
75.00000% : 1295.116us
90.00000% : 2683.855us
95.00000% : 3760.518us
98.00000% : 5867.032us
99.00000% : 7333.790us
99.50000% : 8426.057us
99.90000% : 10173.684us
99.99000% : 12919.954us
99.99900% : 15728.640us

Summary latency data for /dev/nvme2n1 from core 2:
=================================================================================
1.00000% : 14.872us
10.00000% : 45.836us
25.00000% : 219.429us
50.00000% : 427.154us
75.00000% : 1380.937us
90.00000% : 2668.251us
95.00000% : 3542.065us
98.00000% : 5211.672us
99.00000% : 6522.392us
99.50000% : 7645.867us
99.90000% : 9487.116us
99.99000% : 12046.141us
99.99900% : 14792.411us
99.99990% : 16602.453us
99.99999% : 19473.554us

Summary latency data for /dev/nvme1n1 from core 1:
=================================================================================
1.00000% : 14.811us
10.00000% : 45.105us
25.00000% : 222.354us
50.00000% : 419.352us
75.00000% : 1365.333us
90.00000% : 2761.874us
95.00000% : 3698.103us
98.00000% : 5430.126us
99.00000% : 6709.638us
99.50000% : 7833.112us
99.90000% : 9861.608us
99.99000% : 12670.293us
99.99900% : 15728.640us
99.99990% : 19099.063us
99.99999% : 21595.672us

Summary latency data for /dev/nvme0n1 from core 0:
=================================================================================
1.00000% : 14.568us
10.00000% : 43.154us
25.00000% : 193.097us
50.00000% : 473.966us
75.00000% : 1474.560us
90.00000% : 2715.063us
95.00000% : 3557.669us
98.00000% : 5242.880us
99.00000% : 6584.808us
99.50000% : 7770.697us
99.90000% : 9674.362us
99.99000% : 12295.802us
99.99900% : 15166.903us
99.99990% : 16602.453us
99.99999% : 17975.589us

BR,
Taisuke Fukuyama

**Comment by tafukuyama** [comment] 2018-05-18 05:46
Hi Jim san,

We had run all of fio random write tests with norandommap option and got reasonable max IOPS(330K) using 4x NVMes.
Other fio settings are shown in below.

[root@dev16 ~]# cat config.fio 
[global]
rw=randwrite
bs=4096
numjobs=${numjobs_set} # 1 to 16
iodepth=${iodepth_set} # 32 to 512 (set to be numjobs*iodepth/#_of_dev=128)
runtime=600
group_reporting
name=test
direct=1
ioengine=${ioengine} #kernel: libaio, SPDK: spdk
time_based
loops=1
invalidate=1
ramp_time=60
randrepeat=0
norandommap
exitall
cpus_allowed_policy=split
thread=1

[job]
cpus_allowed=${CPUCORE} # Specify core IDs of the same number as numjobs. ex: "0,1,2,3" at numjobs=4
filename=/dev/nvme0n1:/dev/nvme1n1:/dev/nvme2n1:/dev/nvme3n1
[root@dev16 ~]#

BR,
Taisuke Fukuyama

**Comment by jimharris** [comment] 2018-05-22 00:11
I can confirm that the RNG period for rand_r is not good.  The number sequence repeats itself too quickly, so not enough LBAs on the SSD are written.  This keeps the background garbage collection inactive allowing better performance.

lrand48_r should work well here.  My initial testing indicates its RNG is much much better.

A few notes to whoever ends up implementing this:

While we are here, we need to make changes to account for >32-bit LBAs (rand_r also had this problem).  So we need to call lrand48_r twice to generate a number big enough to modulo by the number of LBAs on the device.

lrand48_r and friends are not part of FreeBSD but the gnulib package should have it.

So something like:

struct drand48_data seed;
long int randnum;

srand48_r(0, &seed);
lrand48_r(&seed, &randnum);
offset_in_ios = randnum << 31;
lrand48_t(&seed, &randnum);
offset_in_ios |= randnum;
offset_in_ios %= target->size_in_ios;


We should also have separate patches to do this for both nvme/perf and bdevperf.

**Comment by tafukuyama** [comment] 2018-05-23 07:44
Hi Jim san,

Thank you for your comments!
We've tried to rerun perf random write applying the following patch which changes the RNG to lrand48_r instead of rand_r. Then we found over spec IOPS can no longer be seen, but on the contrary, IOPS becomes very low. (38KIOPS at NVMe x4, 4K random write)
Please note that this is just a result of trial patch and it may have some bugs or too heavy processes.
Anyway just for your reference.
Thanks.

-----------------------------------------------------------
--- a/examples/nvme/perf/perf.c
+++ b/examples/nvme/perf/perf.c
@@ -43,6 +43,7 @@
 #include "spdk/histogram_data.h"
 #include "spdk/endian.h"
 #include "spdk/crc16.h"
+#include "stdlib.h"
 #if HAVE_LIBAIO
 #include <libaio.h>
@@ -627,9 +628,17 @@ submit_single_io(struct perf_task *task)
        int                     rc;
        struct ns_worker_ctx    *ns_ctx = task->ns_ctx;
        struct ns_entry         *entry = ns_ctx->entry;
+       struct drand48_data _seed = {};
+       long int randnum;
        if (g_is_random) {
-               offset_in_ios = rand_r(&seed) % entry->size_in_ios;
+               /* offset_in_ios = rand_r(&seed) % entry->size_in_ios; */
+               srand48_r(0, &_seed);
+               lrand48_r(&_seed, &randnum);
+               offset_in_ios = randnum << 31;
+               lrand48_r(&_seed, &randnum);
+               offset_in_ios |= randnum;
+               offset_in_ios %= entry->size_in_ios;
        } else {
                offset_in_ios = ns_ctx->offset_in_ios++;
                if (ns_ctx->offset_in_ios == entry->size_in_ios) {
------------------------------------------------------------


[root@dev16 ~]# /root/spdk-master/examples/nvme/perf/perf -q 128 -s 4096 -w randwrite -t 60 -c 0xf
Starting SPDK v18.07-pre / DPDK 18.02.1 initialization...
[ DPDK EAL parameters: perf -c 0xf --file-prefix=spdk_pid9456 ]
EAL: Detected 16 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Multi-process socket /var/run/.spdk_pid9456_unix
EAL: Probing VFIO support...
Initializing NVMe Controllers
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
Attaching to NVMe Controller at 0000:01:00.0
EAL: PCI device 0000:03:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
Attaching to NVMe Controller at 0000:03:00.0
EAL: PCI device 0000:82:00.0 on NUMA socket 1
EAL:   probe driver: 8086:953 spdk_nvme
Attaching to NVMe Controller at 0000:82:00.0
EAL: PCI device 0000:84:00.0 on NUMA socket 1
EAL:   probe driver: 8086:953 spdk_nvme
Attaching to NVMe Controller at 0000:84:00.0
Attached to NVMe Controller at 0000:01:00.0 [8086:0953]
Attached to NVMe Controller at 0000:03:00.0 [8086:0953]
Attached to NVMe Controller at 0000:82:00.0 [8086:0953]
Attached to NVMe Controller at 0000:84:00.0 [8086:0953]
Associating INTEL SSDPE2MD400G4  (CVFT61220012400GGN  ) with lcore 3
Associating INTEL SSDPE2MD400G4  (CVFT4400002C400GGN  ) with lcore 2
Associating INTEL SSDPE2MD400G4  (CVFT4396003G400GGN  ) with lcore 1
Associating INTEL SSDPE2MD400G4  (CVFT7021006H400PGN  ) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 3
Starting thread on core 2
Starting thread on core 1
Starting thread on core 0
========================================================
                                                                                            Latency(us)
Device Information                                     :       IOPS       MB/s    Average        min        max
INTEL SSDPE2MD400G4  (CVFT61220012400GGN  ) from core 3:    9584.53      37.44   13356.14     442.70   24227.34
INTEL SSDPE2MD400G4  (CVFT4400002C400GGN  ) from core 2:    9540.02      37.27   13418.49     425.07   22112.95
INTEL SSDPE2MD400G4  (CVFT4396003G400GGN  ) from core 1:    9585.40      37.44   13355.64     429.88   22561.67
INTEL SSDPE2MD400G4  (CVFT7021006H400PGN  ) from core 0:    9258.37      36.17   13827.20     415.33   22534.08
========================================================
Total                                                  :   37968.32     148.31   13486.55     415.33   24227.34

[root@dev16 ~]# 

BR,
Taisuke Fukuyama

**Comment by jimharris** [comment] 2018-05-23 16:20
I think you do not want to call srand48_r on each IO.  This will reinitialize the RNG, always with the same seed, meaning it will always write to the same LBA.

**Comment by shuhei-matsumoto** [comment] 2018-05-23 22:56
Hi Jim,

Yes, I suggested Taisuke defining _seed as thread local variable
`static __thread drand48_data _seed = {};`
and calling srand48_r(0, &_seed) once in work_fn().

He did but didn't see any difference.

Taisuke, will you try once again for just in case?

**Comment by tafukuyama** [comment] 2018-05-24 09:38
Hi Jim san,

Thank you for your advice!
We've confirmed offset_in_ios value becomes always the same by calling srand48_r on each IO.
   max_offset_in_ios= 11310718, min_offset_in_ios= 11310718, entry->size_in_ios= 97677846

So we modified the patch as follows to call srand48_r(0, &_seed) once in work_fn() as Matsumoto san mentioned.

```
--- a/examples/nvme/perf/perf.c
+++ b/examples/nvme/perf/perf.c
@@ -43,6 +43,7 @@
#include "spdk/histogram_data.h"
#include "spdk/endian.h"
#include "spdk/crc16.h"
+#include "stdlib.h"

 #if HAVE_LIBAIO
#include <libaio.h>
@@ -619,6 +620,7 @@
static void io_complete(void *ctx, const struct spdk_nvme_cpl *completion);

 static __thread unsigned int seed = 0;
+static __thread struct drand48_data _seed = {};

 static void
submit_single_io(struct perf_task *task)
@@ -627,9 +629,15 @@
        int                     rc;
        struct ns_worker_ctx    *ns_ctx = task->ns_ctx;
        struct ns_entry         *entry = ns_ctx->entry;
+       long int randnum;

        if (g_is_random) {
-               offset_in_ios = rand_r(&seed) % entry->size_in_ios;
+               /* offset_in_ios = rand_r(&seed) % entry->size_in_ios; */
+               lrand48_r(&_seed, &randnum);
+               offset_in_ios = randnum << 31;
+               lrand48_r(&_seed, &randnum);
+               offset_in_ios |= randnum;
+               offset_in_ios %= entry->size_in_ios;
        } else {
                offset_in_ios = ns_ctx->offset_in_ios++;
                if (ns_ctx->offset_in_ios == entry->size_in_ios) {
@@ -853,6 +861,7 @@
        struct ns_worker_ctx *ns_ctx = NULL;

        printf("Starting thread on core %u\n", worker->lcore);
+       srand48_r(0, &_seed);

        /* Allocate a queue pair for each namespace. */
        ns_ctx = worker->ns_ctx;

```

Before I rerun perf w/ new patch, I confirmed offset_in_ios values are covered almost same range as rand_r.
   rand_r: max_offset_in_ios= 97677811, min_offset_in_ios= 5, entry->size_in_ios= 97677846
   lrand48_r: max_offset_in_ios= 97677778, min_offset_in_ios= 66, entry->size_in_ios= 97677846

Test results of perf + lrand48_r (w/ enough precondition) are shown in below.
We got 108KIOPS at NVMe x1, single core, 4K random write.

![image](https://user-images.githubusercontent.com/29906937/40474266-861a3a94-5f79-11e8-8834-5e1bb0fcc48f.png)

[root@dev16 perf_lrand48_r]# /root/spdk-master/examples/nvme/perf/perf -q 128 -s 4096 -w randwrite -t 600 -c 0x0001 -r 'trtype:PCIe traddr:0000.01.00.0'
Starting SPDK v18.07-pre / DPDK 18.02.1 initialization...
[ DPDK EAL parameters: perf -c 0x0001 --file-prefix=spdk_pid5962 ]
EAL: Multi-process socket /var/run/.spdk_pid5962_unix
EAL: Probing VFIO support...
Initializing NVMe Controllers
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
Attaching to NVMe Controller at 0000:01:00.0
Attached to NVMe Controller at 0000:01:00.0 [8086:0953]
Associating INTEL SSDPE2MD400G4  (CVFT7021006H400PGN  ) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0
\========================================================
                                                                                            Latency(us)
Device Information                                     :       IOPS       MB/s    Average        min        max
INTEL SSDPE2MD400G4  (CVFT7021006H400PGN  ) from core 0:  107551.77     420.12    1190.07       4.76   23427.06
\========================================================
Total                                                  :  107551.77     420.12    1190.07       4.76   23427.06

\------------------------------------------------

So calling lrand48_r x2 on each IO made IOPS lower than calling rand_r.
However, the tendency of IOPS by increasing # of cores is more similar to perf + rand_r than fio_plugin, and IOPS is still over than NVMe device spec.
So we’re now just wondering if improving RNG quality solves this issue.

BR,
Taisuke Fukuyama

**Comment by jimharris** [comment] 2018-05-25 16:00
Hi Taisuke-san,

For the 108K data point – it looks like this was run for 10 minutes (-t 600)?  Was this also with 90 minutes pre-conditioning?  I just want to make sure the higher performance is not related to lack of preconditioning or that the test was not run long enough.

Note that even with using the stronger RNG – we still do not truly match fio’s randommap.  The randommap makes sure that every LBA is written to once, before any LBA is written to a second time.

So for this test below, it ran for 600 seconds at 107551 IO/s = 64.53M IO.  The disk size is 97.7M IO.  For fio, all 64.53M IO would be to different LBA – but for perf, at least some of those IO would be duplicates.  The duplicate I/O means the SSD has fewer LBAs to rearrange during garbage collection which could help performance.

The only way to confirm this is to write a randommap implementation for SPDK perf.  Is that something you or Shuhei-san would be interested in experimenting with?

-Jim

**Comment by tafukuyama** [comment] 2018-05-28 05:28
Hi Jim san,

Thank you for your explanation.

We got these test results with 90 minutes pre-conditioning by fio_plugin instead of perf.
The fio setting is below.

[root@dev16 ~]# LD_PRELOAD=/root/spdk-master/examples/nvme/fio_plugin/fio_plugin fio config_nvmex1.fio

[root@dev16 ~]# cat config_nvmex1.fio
[global]
rw=randwrite
bs=4096
numjobs=1
iodepth=32
runtime=5400
group_reporting
name=test
direct=1
ioengine=spdk
time_based
loops=1
invalidate=1
ramp_time=5
randrepeat=0
norandommap
exitall
cpus_allowed_policy=split
thread=1

[job]
cpus_allowed="0"
filename=trtype=PCIe traddr=0000.01.00.0 ns=1
[root@dev16 ~]#

We configured runtime to 10 minutes for each perf random write test.
As you explained, the total write size is less than the disk size in this condition.
However we also confirmed that IOPS is always over than NVMe device spec during the test 
and no tendency observed like IOPS reduction by passage of time.
So we think changing runtime to 30 minutes makes no difference for our test result.

Then, we'd like to confirm how to handle this issue from now on.
Thanks to your investigation, we could know the root cause of this issue and it becomes not critical for our SPDK evaluation now. So we don't mind to close this issue if you have no concern.

BR,
Taisuke Fukuyama

**Comment by shuhei-matsumoto** [comment] 2018-05-28 06:41
Hi Jim,

I would like to say thank you too. Your insight was very helpful for us.

Perfectly uniform random number generator is interesting but I understand that is not easy task (One reason may be that FIO and Linux kernel are GPL but SPDK is BSD license.).

We can still use SPDK perf random write to measure CPU utilization and now we could get enough answer for our question. Hence as Taisuke says, we can close this issue.

I can put random number generator into Trello's low hanging fruit or put the above patch to Gerrit if reasonable.

Thanks,
Shuhei

**Comment by jimharris** [comment] 2018-05-29 23:32
Hi Shuhei and Taisuke,

This was a very interesting debug effort.  I agree with closing the bug and adding something to the backlog.

Thanks,

-Jim

**Closed** 2018-05-30 05:13 UTC
Labels: question
