### ISSUE TITLE
bdev/iscsi should check for unmap support

### ISSUE THREAD

**Issue by ghost** [spdk/spdk#351] opened 2018-06-28 21:28 UTC
## Expected Behavior

The iSCSI bdev module should correctly report whether a bdev (LUN) supports UNMAP.

## Current Behavior

The iSCSI bdev module currently reports that all bdevs support UNMAP without checking.

## Possible Solution

Retrieve the Logical Block Provisioning VPD page for each LUN and check if the logical block provisioning UNMAP command (LBPU) bit is set in order to determine whether UNMAP is supported.

## Context (Environment including OS version, SPDK version, etc.)

UNMAP support for the iSCSI bdev module was introduced in commit 8b38468db4446c4cea3e6da422f55ecf45cde37c.

**Comment by dverkamp-intel** [comment] 2018-06-28 23:32
We should also be splitting large UNMAP requests, since the SCSI UNMAP command only supports 32-bit number of blocks, whereas the bdev layer unmap request has a 64-bit block count field.

See bdev_virtio_unmap() in lib/bdev/virtio/bdev_virtio_scsi.c for an example of how this should work (this file also has an example of how to check for UNMAP support in the VPD page).

**Comment by optimistyzy** [comment] 2018-07-02 05:36
@jessehui Can you look at this issue mentioned by @dverkamp-intel

**Comment by jessehui** [comment] 2018-07-04 07:16
Yep. Will look into this. Thank you.

**Comment by liang2yan** [comment] 2018-07-10 05:51
@jessehui , any patch about this issue?

**Comment by jessehui** [comment] 2018-07-17 05:17
https://review.gerrithub.io/#/c/spdk/spdk/+/419056/
https://review.gerrithub.io/#/c/spdk/spdk/+/419165/
Please feel welcome to review. Thanks

**Comment by optimistyzy** [comment] 2018-07-17 05:57
@jessehui，  the two patches fail the automation test. Could you check it first?

**Comment by jessehui** [comment] 2018-07-26 01:21
Patched updated: https://review.gerrithub.io/#/c/spdk/spdk/+/419974/
Already merged. You may test and close this @liang2yan @wanqunintel

**Comment by xuhuagen** [comment] 2018-07-26 02:36
@jessehui  when use null bdev
Target machine error occured and cored dump when Ctrl+C to kill it

```
conn.c: 325:spdk_iscsi_conn_construct: *NOTICE*: Launching connection on acceptor thread
conn.c: 325:spdk_iscsi_conn_construct: *NOTICE*: Launching connection on acceptor thread
iscsi.c:2032:spdk_iscsi_op_login_notify_session_info: *NOTICE*: Login from iqn.2016-06.io.spdk:init (192.168.11.2) on iqn.2016-06.io.spdk:disk1 tgt_node1 (192.168.11.11:3260,1), ISID=804bf9070000, TSIH=1, CID=0, HeaderDigest=off, DataDigest=off
iscsi.c:2032:spdk_iscsi_op_login_notify_session_info: *NOTICE*: Login from iqn.2016-06.io.spdk:init (192.168.11.2) on iqn.2016-06.io.spdk:disk2 tgt_node2 (192.168.11.11:3260,1), ISID=80b37e0f0000, TSIH=2, CID=0, HeaderDigest=off, DataDigest=off
scsi_bdev.c: 647:spdk_bdev_scsi_inquiry: *ERROR*: unsupported INQUIRY VPD page 0xb2
scsi_bdev.c: 647:spdk_bdev_scsi_inquiry: *ERROR*: unsupported INQUIRY VPD page 0xb2
conn.c: 452:spdk_iscsi_remove_conn: *NOTICE*: Terminating connections(tsih 1): 0
conn.c: 452:spdk_iscsi_remove_conn: *NOTICE*: Terminating connections(tsih 2): 0
^CSegmentation fault (core dumped)
```
dmesg 

`[260619.271038] reactor_0[23956]: segfault at 0 ip 000000000047a537 sp 00007fffaf2a57c0 error 6 in iscsi_tgt[400000+c2000]
`


coreed dump file

```
[root@waikikibeach35 spdk]# gdb -c /tmp/core-reactor_0-11-0-0-23956-1532572101 ./app/iscsi_tgt/iscsi_tgt
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/xuhuagen/spdk/app/iscsi_tgt/iscsi_tgt...done.

warning: core file may not match specified executable file.
[New LWP 23956]
[New LWP 23958]
[New LWP 23957]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./app/iscsi_tgt/iscsi_tgt -c ../target_config/iscsi.conf'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000000047a537 in malloc_elem_free ()
Missing separate debuginfos, use: debuginfo-install libibverbs-15-7.el7_5.x86_64 librdmacm-15-7.el7_5.x86_64 openssl-libs-1.0.2k-12.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x000000000047a537 in malloc_elem_free ()
#1  0x000000000047998f in rte_free ()
#2  0x0000000000464505 in spdk_free (buf=<optimized out>) at env.c:92
#3  0x00000000004645b5 in spdk_dma_free (buf=<optimized out>) at env.c:132
#4  0x000000000045fbf7 in spdk_bit_array_free (bap=<optimized out>) at bit_array.c:77
#5  0x000000000040b99a in _spdk_bs_dev_destroy (io_device=0x2478ee0) at blobstore.c:2253
#6  0x000000000045eeca in _finish_unregister (arg=0x2478ff0) at thread.c:358
#7  0x0000000000463242 in _spdk_event_queue_run_batch (reactor=0x1f05ac0, reactor=0x1f05ac0) at reactor.c:207
#8  _spdk_reactor_run (arg=0x1f05ac0) at reactor.c:506
#9  0x00000000004638ad in spdk_reactors_start () at reactor.c:692
#10 0x00000000004626f4 in spdk_app_start (opts=opts@entry=0x7fffaf2a5a30, start_fn=start_fn@entry=0x406ca0 <spdk_startup>,
    arg1=arg1@entry=0x0, arg2=arg2@entry=0x0) at app.c:575
#11 0x0000000000405989 in main (argc=3, argv=0x7fffaf2a5ba8) at iscsi_tgt.c:113
```

**Comment by jessehui** [comment] 2018-07-26 09:18
I can't really reproduce this under my server.

**Comment by xuhuagen** [comment] 2018-07-30 01:04
I also not reproduce this issue when I change a server.

**Comment by wanqunintel** [comment] 2018-07-31 05:13
Close due to environment issue, can not reproduce

**Closed by wanqunintel** 2018-07-31 05:13 UTC
Labels: bug
