### ISSUE TITLE
[nvmf_fio_host] timeout hit by bdev_lvol_delete followed by unresponsive nvmf_tgt

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#3405] opened 2024-06-12 12:58 UTC
# CI Intermittent Failure

https://ci.spdk.io/results/autotest-spdk-master-vs-dpdk-main/builds/3566/archive/nvmf-phy-autotest_74395/index.html

```
16:17:14   16:17:14 nvmf_rdma.nvmf_fio_host -- host/fio.sh@76 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py bdev_lvol_delete lvs_n_0/lbd_nest_0
16:18:21  Timeout while waiting for response:
16:18:21  
16:18:21  
16:18:21    16:18:14 nvmf_rdma.nvmf_fio_host -- host/fio.sh@76 -- # trap - ERR
16:18:21    16:18:14 nvmf_rdma.nvmf_fio_host -- host/fio.sh@76 -- # print_backtrace
16:18:21    16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@1152 -- # [[ ehxBET =~ e ]]
16:18:21    16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@1154 -- # args=('--transport=rdma')
16:18:21    16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@1154 -- # local args
16:18:21    16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@1156 -- # xtrace_disable
16:18:21    16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@10 -- # set +x
16:18:21  ========== Backtrace start: ==========
16:18:21  
16:18:21  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/nvmf/host/fio.sh:76 -> main(["--transport=rdma"])
16:18:21       ...
16:18:21     71  		traddr=$NVMF_FIRST_TARGET_IP trsvcid=$NVMF_PORT ns=1" --bs=4096
16:18:21     72  		$rpc_py nvmf_delete_subsystem nqn.2016-06.io.spdk:cnode3
16:18:21     73  	
16:18:21     74  		sync
16:18:21     75  		# Delete lvol_bdev and destroy lvol_store.
16:18:21  => 76  		$rpc_py bdev_lvol_delete lvs_n_0/lbd_nest_0
16:18:21     77  		$rpc_py bdev_lvol_delete_lvstore -l lvs_n_0
16:18:21     78  		$rpc_py bdev_lvol_delete lvs_0/lbd_0
16:18:21     79  		$rpc_py bdev_lvol_delete_lvstore -l lvs_0
16:18:21     80  		$rpc_py bdev_nvme_detach_controller Nvme0
16:18:21     81  	fi
16:18:21       ...
16:18:21  
16:18:21  ========== Backtrace end ==========
16:18:21    16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@1193 -- # return 0
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- host/fio.sh@1 -- # process_shm --id 0
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@807 -- # type=--id
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@808 -- # id=0
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@809 -- # '[' --id = --pid ']'
16:18:21    16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@813 -- # find /dev/shm -name '*.0' -printf '%f\n'
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@813 -- # shm_files=nvmf_trace.0
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@815 -- # [[ -z nvmf_trace.0 ]]
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@819 -- # for n in $shm_files
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@820 -- # tar -C /dev/shm/ -cvzf /var/jenkins/workspace/nvmf-phy-autotest/spdk/../output/nvmf_trace.0_shm.tar.gz nvmf_trace.0
16:18:21  nvmf_trace.0
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@822 -- # return 0
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- host/fio.sh@1 -- # nvmftestfini
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- nvmf/common.sh@488 -- # nvmfcleanup
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- nvmf/common.sh@117 -- # sync
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- nvmf/common.sh@119 -- # '[' rdma == tcp ']'
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- nvmf/common.sh@119 -- # '[' rdma == rdma ']'
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- nvmf/common.sh@120 -- # set +e
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- nvmf/common.sh@121 -- # for i in {1..20}
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- nvmf/common.sh@122 -- # modprobe -v -r nvme-rdma
16:18:21  rmmod nvme_rdma
16:18:21  rmmod nvme_fabrics
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- nvmf/common.sh@123 -- # modprobe -v -r nvme-fabrics
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- nvmf/common.sh@124 -- # set -e
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- nvmf/common.sh@125 -- # return 0
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- nvmf/common.sh@489 -- # '[' -n 452106 ']'
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- nvmf/common.sh@490 -- # killprocess 452106
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@949 -- # '[' -z 452106 ']'
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@953 -- # kill -0 452106
16:18:21    16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@954 -- # uname
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@954 -- # '[' Linux = Linux ']'
16:18:21    16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@955 -- # ps --no-headers -o comm= 452106
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@955 -- # process_name=reactor_0
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@959 -- # '[' reactor_0 = sudo ']'
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@967 -- # echo 'killing process with pid 452106'
16:18:21  killing process with pid 452106
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@968 -- # kill 452106
16:18:21   16:18:14 nvmf_rdma.nvmf_fio_host -- common/autotest_common.sh@973 -- # wait 452106
16:18:21  [2024-06-11 16:18:14.845207] lvol.c: 888:spdk_lvs_unload: *ERROR*: Cannot unload lvol store - operations on lvols pending
16:18:21  [2024-06-11 16:18:14.869325] bdev.c:2371:bdev_finish_unregister_bdevs_iter: *WARNING*: Unregistering claimed bdev 'e95480e9-bbad-44fe-b358-58828633b02f'!
16:20:47  Cancelling nested steps due to timeout
16:20:47  Sending interrupt signal to process
16:20:58  Terminated
16:20:58  script returned exit code 143
```

**Comment by tomzawadzki** [comment] 2024-07-09 13:19
This looks like a duplicate of https://github.com/spdk/spdk/issues/3295

**Closed by tomzawadzki** 2024-07-09 13:19 UTC
Labels: Intermittent Failure
