### ISSUE TITLE
[nvme_hotplug] assertion: Expected inserts 3 != actual inserts 2

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2383] opened 2022-02-18 17:01 UTC
00:05:20.061  QEMU NVMe Ctrl       (12341               ):      20892 I/Os completed (+4415)
00:05:20.061  
00:05:21.002  unregister_dev: QEMU NVMe Ctrl       (12341               )
00:05:21.002  Expected inserts 3 != actual inserts 2
00:05:21.002    21:15:10	-- nvme/hotplug.sh@52 -- # trap - ERR
00:05:21.002    21:15:10	-- nvme/hotplug.sh@52 -- # print_backtrace
00:05:21.002    21:15:10	-- common/autotest_common.sh@994 -- # [[ ehxBET =~ e ]]
00:05:21.002    21:15:10	-- common/autotest_common.sh@996 -- # args=()
00:05:21.002    21:15:10	-- common/autotest_common.sh@996 -- # local args
00:05:21.002    21:15:10	-- common/autotest_common.sh@998 -- # xtrace_disable
00:05:21.002    21:15:10	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:05:21.002    21:15:10	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:05:21.002    21:15:10	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:05:21.002    21:15:10	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:05:21.002    21:15:10	-- common/autotest_common.sh@19 -- # set +x
00:05:21.002  ========== Backtrace start: ==========
00:05:21.002  
00:05:21.002  in test/nvme/hotplug.sh:52 -> hotplug([])
00:05:21.002       ...
00:05:21.002     47  	
00:05:21.002     48  		remove_attach_helper "$hotplug_events" "$hotplug_wait" &
00:05:21.002     49  		hotplug_pid=$!
00:05:21.002     50  	
00:05:21.002     51  		"$SPDK_EXAMPLE_DIR/hotplug" \
00:05:21.002  => 52  			-i 0 \
00:05:21.002     53  			-t $((hotplug_events * hotplug_wait + hotplug_wait)) \
00:05:21.002     54  			-n $((hotplug_events * nvme_count)) \
00:05:21.002     55  			-r $((hotplug_events * nvme_count)) \
00:05:21.002     56  			-l warning
00:05:21.002     57  	}
00:05:21.002       ...
00:05:21.002  in test/nvme/hotplug.sh:68 -> main([])
00:05:21.002       ...
00:05:21.002     63  	cache_pci_bus_sysfs
00:05:21.002     64  	xtrace_restore
00:05:21.002     65  	
00:05:21.002     66  	trap "cleanup" EXIT
00:05:21.002     67  	
00:05:21.002  => 68  	hotplug
00:05:21.002       ...
00:05:21.002  
00:05:21.002  ========== Backtrace end ==========
00:05:21.002    21:15:10	-- common/autotest_common.sh@1034 -- # xtrace_enable
00:05:21.002    21:15:10	-- common/autotest_common.sh@1035 -- # return 0
00:05:21.002   21:15:10	-- nvme/hotplug.sh@1 -- # cleanup
00:05:21.002   21:15:10	-- nvme/hotplug.sh@10 -- # [[ -e /proc/17557/status ]]
00:05:21.002   21:15:10	-- nvme/hotplug.sh@11 -- # kill 17557
00:05:21.002    21:15:10	-- common/autotest_common.sh@966 -- # trap - ERR
00:05:21.002    21:15:10	-- common/autotest_common.sh@966 -- # print_backtrace
00:05:21.002    21:15:10	-- common/autotest_common.sh@994 -- # [[ ehxBET =~ e ]]
00:05:21.002    21:15:10	-- common/autotest_common.sh@996 -- # args=('test/nvme/hotplug.sh' 'nvme_hotplug' '/home/vagrant/autorun-spdk.conf')
00:05:21.002    21:15:10	-- common/autotest_common.sh@996 -- # local args
00:05:21.002    21:15:10	-- common/autotest_common.sh@998 -- # xtrace_disable
00:05:21.002    21:15:10	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:05:21.002    21:15:10	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:05:21.002    21:15:10	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:05:21.002    21:15:10	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:05:21.002    21:15:10	-- common/autotest_common.sh@19 -- # set +x
00:05:21.002  ========== Backtrace start: ==========
00:05:21.002  
00:05:21.002  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:966 -> run_test(["nvme_hotplug"],["test/nvme/hotplug.sh"])
00:05:21.002       ...

**Comment by spdkci** [comment] 2022-02-18 17:06
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_71646.html

**Comment by jimharris** [comment] 2022-02-18 18:00
Duplicate of #2201

**Closed by jimharris** 2022-02-18 18:00 UTC
Labels: Intermittent Failure

**Comment by spdkci** [comment] 2022-10-27 02:41
Another instance of this failure. Reported by @richael02. log: https://ci.spdk.io/public_build/autotest-per-patch_88325.html
