### ISSUE TITLE
[nvmf_multipath] nvmf-tcp-uring-vg-autotest CI test failure Intermittent Failure

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#1967] opened 2021-06-01 02:09 UTC
## Link to the failed CI build

http://10.211.11.56/results/autotest-per-patch/builds/48737/archive/nvmf-tcp-uring-vg-autotest/build.log

## Execution failed at

00:08:43.394  
00:08:43.394  in test/nvmf/target/multipath.sh:82 -> main(["--transport=tcp"])
00:08:43.394       ...
00:08:43.394     77  	$rpc_py nvmf_subsystem_listener_set_ana_state nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a "$NVMF_SECOND_TARGET_IP" -s "$NVMF_PORT" -n optimized
00:08:43.394     78  	
00:08:43.394     79  	sleep 1
00:08:43.394     80  	
00:08:43.394     81  	[ $(cat /sys/block/nvme"$subsys_id"c"$ctrl1_id"n1/ana_state) == "optimized" ]
00:08:43.394  => 82  	[ $(cat /sys/block/nvme"$subsys_id"c"$ctrl2_id"n1/ana_state) == "optimized" ]
00:08:43.394     83  	
00:08:43.394     84  	# Set IO policy to round-robin
00:08:43.394     85  	echo round-robin > /sys/class/nvme-subsystem/nvme-subsys$subsys_id/iopolicy
00:08:43.394     86  	
00:08:43.394     87  	$rootdir/scripts/fio-wrapper -p nvmf -i 4096 -d 128 -t randrw -r 6 -v &
00:08:43.394       ...
00:08:43.394  
00:08:43.394  ========== Backtrace end ==========
00:08:43.394    01:54:12	# xtrace_enable
00:08:43.394    01:54:12	# return 0
00:08:43.394   01:54:12	# process_shm --id 0
00:08:43.394   01:54:12	# type=--id
00:08:43.394   01:54:12	# id=0
00:08:43.394   01:54:12	# '[' --id = --pid ']'
00:08:43.394   01:54:12	# '[' --id = --id ']'
00:08:43.394   01:54:12	# id=0
00:08:43.395    01:54:12	# find /dev/shm -name '*.0' -printf '%f\n'
00:08:43.395   01:54:12	# shm_files=nvmf_trace.0
00:08:43.395   01:54:12	# [[ -z nvmf_trace.0 ]]
00:08:43.395   01:54:12	# for n in $shm_files
00:08:43.395   01:54:12	# tar -C /dev/shm/ -cvzf /home/vagrant/spdk_repo/spdk/../output/nvmf_trace.0_shm.tar.gz nvmf_trace.0
00:08:43.396  nvmf_trace.0
00:08:44.314   01:54:13	# return 0
00:08:44.314   01:54:13	# nvmftestfini
00:08:44.314   01:54:13	# nvmfcleanup
00:08:44.314   01:54:13	# sync
00:08:44.317   01:54:13	# '[' tcp == tcp ']'
00:08:44.317   01:54:13	# set +e
00:08:44.317   01:54:13	# for i in {1..20}
00:08:44.317   01:54:13	# modprobe -v -r nvme-tcp
00:08:44.319  rmmod nvme_tcp
00:08:44.375  rmmod nvme_fabrics
00:08:44.387   01:54:13	# modprobe -v -r nvme-fabrics
00:08:44.390   01:54:13	# set -e
00:08:44.390   01:54:13	# return 0
00:08:44.390   01:54:13	# '[' -n 51141 ']'
00:08:44.390   01:54:13	# killprocess 51141
00:08:44.390   01:54:13	# '[' -z 51141 ']'
00:08:44.390   01:54:13	# kill -0 51141
00:08:44.391    01:54:13	# uname
00:08:44.393   01:54:13	# '[' Linux = Linux ']'
00:08:44.393    01:54:13	# ps --no-headers -o comm= 51141
00:08:44.408  killing process with pid 51141
00:08:44.408   01:54:13	# process_name=reactor_0
00:08:44.408   01:54:13	# '[' reactor_0 = sudo ']'
00:08:44.408   01:54:13	# echo 'killing process with pid 51141'
00:08:44.408   01:54:13	# kill 51141
00:08:44.408   01:54:13	# wait 51141
00:08:44.707  EAL: device event monitor already stopped
00:08:44.737   01:54:14	# '[' '' == iso ']'
00:08:44.737   01:54:14	# [[ tcp == \t\c\p ]]
00:08:44.737   01:54:14	# nvmf_tcp_fini
00:08:44.737   01:54:14	# [[ nvmf_tgt_ns == \n\v\m\f\_\t\g\t\_\n\s ]]
00:08:44.737   01:54:14	# nvmf_veth_fini
00:08:44.737   01:54:14	# ip link set nvmf_init_br nomaster
00:08:44.751   01:54:14	# ip link set nvmf_tgt_br nomaster
00:08:44.762   01:54:14	# ip link set nvmf_tgt_br2 nomaster
00:08:44.775   01:54:14	# ip link set nvmf_init_br down
00:08:44.778   01:54:14	# ip link set nvmf_tgt_br down
00:08:44.781   01:54:14	# ip link set nvmf_tgt_br2 down
00:08:44.784   01:54:14	# ip link delete nvmf_br type bridge
00:08:44.823   01:54:14	# ip link delete nvmf_init_if
00:08:44.835   01:54:14	# ip netns exec nvmf_tgt_ns ip link delete nvmf_tgt_if
00:08:44.848   01:54:14	# ip netns exec nvmf_tgt_ns ip link delete nvmf_tgt_if2
00:08:44.862   01:54:14	# ip netns del nvmf_tgt_ns
00:08:44.864   01:54:14	# return 0
00:08:44.865    01:54:14	# trap - ERR
00:08:44.865    01:54:14	# print_backtrace
00:08:44.865    01:54:14	# [[ ehxBET =~ e ]]
00:08:44.866    01:54:14	# args=("${BASH_ARGV[@]}")
00:08:44.866    01:54:14	# local args
00:08:44.866    01:54:14	# xtrace_disable
00:08:44.866    01:54:14	# '[' no '!=' yes ']'
00:08:44.866    01:54:14	# PREV_BASH_OPTS=ehxBET
00:08:44.866    01:54:14	# [[ ehxBET == *\x* ]]
00:08:44.867    01:54:14	# XTRACE_DISABLED=yes
00:08:44.867    01:54:14	# set +x
00:08:44.867  ========== Backtrace start: ==========
00:08:44.867  
00:08:44.877  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:950 -> run_test(["nvmf_multipath"],["test/nvmf/target/multipath.sh"],["--transport=tcp"])
00:08:44.877       ...
00:08:44.877     945 		timing_enter $test_name
00:08:44.877     946 		echo "************************************"
00:08:44.877     947 		echo "START TEST $test_name"
00:08:44.877     948 		echo "************************************"
00:08:44.877     949 		xtrace_restore
00:08:44.877  => 950 		time "$@"
00:08:44.877     951 		xtrace_disable
00:08:44.877     952 		echo "************************************"
00:08:44.877     953 		echo "END TEST $test_name"
00:08:44.877     954 		echo "************************************"
00:08:44.877     955 		timing_exit $test_name
00:08:44.877       ...
00:08:44.884  in ./test/nvmf/nvmf.sh:56 -> main(["--transport=tcp"])
00:08:44.884       ...
00:08:44.884     51  		run_test "nvmf_shutdown" test/nvmf/target/shutdown.sh "${TEST_ARGS[@]}"
00:08:44.884     52  		#TODO: disabled due to intermittent failures. Need to triage.
00:08:44.884     53  		# run_test "nvmf_srq_overwhelm" test/nvmf/target/srq_overwhelm.sh $TEST_ARGS
00:08:44.884     54  	fi
00:08:44.884     55  	
00:08:44.884  => 56  	run_test "nvmf_multipath" test/nvmf/target/multipath.sh "${TEST_ARGS[@]}"
00:08:44.884     57  	
00:08:44.884     58  	timing_enter host
00:08:44.884     59  	
00:08:44.884     60  	run_test "nvmf_identify" test/nvmf/host/identify.sh "${TEST_ARGS[@]}"
00:08:44.884     61  	run_test "nvmf_perf" test/nvmf/host/perf.sh "${TEST_ARGS[@]}"
00:08:44.884       ...
00:08:44.884  
00:08:44.884  ========== Backtrace end ==========

**Comment by spdkci** [comment] 2021-06-01 02:11
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_48737.html

**Comment by karlatec** [comment] 2021-06-01 06:07
Duplicate of #1801

**Closed by karlatec** 2021-06-01 06:07 UTC
Labels: Intermittent Failure

**Comment by spdkci** [comment] 2021-06-19 15:38
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_50384.html

**Comment by spdkci** [comment] 2021-06-24 18:53
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_50852.html

**Comment by spdkci** [comment] 2021-07-05 16:11
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51673.html

**Comment by spdkci** [comment] 2021-07-05 16:18
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51677.html

**Comment by spdkci** [comment] 2022-11-21 05:03
Another instance of this failure. Reported by @richael02. log: https://ci.spdk.io/public_build/autotest-per-patch_89997.html
