### ISSUE TITLE
Error occurs when I use spdk_ioat to do memcpy concerning pmem

### ISSUE THREAD

**Issue by Lyhugo** [spdk/spdk#2305] opened 2021-12-29 09:04 UTC
I have successfully used spdk_ioat to do memcpy between buffer and the address of a regular file mmap.
In brief, I mmap a file with the flag of MAP_HUGETLB to use the 2MB-align page and then use `spdk_mem_register` to register the specified memory region.

Next, I would like to do some tests in pmem with a similar approach, but the results are different.
At first, I equipped ext4-DAX with 2MB hugepages by referring
> https://pmem.io/2018/05/15/using_persistent_memory_devices_with_the_linux_device_mapper.html#verifying-io-alignment

And then, I apply the `pmem_map_file` in libpmem to mmap pmem and register the address later.
But in the procedure of `spdk_mem_register`, I can not register successfully.

I have try a lot but it's not work. Is there any step that went wrong? What is a possible solution？
Thank you very much!

## Context (Environment including OS version, SPDK version, etc.)
ubuntu1~16.04.12
SPDK v21.10

**Comment by Lyhugo** [comment] 2021-12-29 09:05
Sorry to trouble you to change the label to the problem

**Comment by benlwalker** [comment] 2021-12-29 15:51
Linux does not support long term page pins for files in filesystems because it can prevent the filesystem from performing critical data movement operations. Because of this, you can only register pmem on a devdax mount, not fsdax. This is expected behavior.

Future platform DMA engines simply won't require the memory to be pinned, so this is only a temporary limitation with current generation hardware.

I'm going to close the issue since this is expected, but feel free to continue asking questions here.

**Closed by benlwalker** 2021-12-29 15:51 UTC
Labels: Sighting
