### ISSUE TITLE
nvme_autotest ftl/restore.sh SIGILL failure

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1053] opened 2019-11-13 15:25 UTC
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49583.html

 14:20:25	# (( i<=20 ))
 14:20:25	# dd if=/dev/nbd0 of=/tmp/nbdtest bs=4096 count=1 iflag=direct
1+0 records in
1+0 records out
4096 bytes (4.1 kB, 4.0 KiB) copied, 0.000846055 s, 4.8 MB/s
  14:20:25	# stat -c %s /tmp/nbdtest
 14:20:25	# size=4096
 14:20:25	# rm -f /tmp/nbdtest
 14:20:25	# '[' 4096 '!=' 0 ']'
 14:20:25	# return 0
 14:20:25	# mount /dev/nbd0 /tmp/tmp.ZR2lj1smEH
 14:20:25	# dd if=/dev/urandom of=/tmp/tmp.ZR2lj1smEH/testfile2 bs=4K count=256K
dd: error writing '/tmp/tmp.ZR2lj1smEH/testfile2': Read-only file system
191746+0 records in
191745+0 records out
785387520 bytes (785 MB, 749 MiB) copied, 5.0036 s, 157 MB/s
/var/jenkins/workspace/NVMe_tests/nvme_autotest/spdk/test/ftl/restore.sh: line 84: 2843077 Illegal instruction     (core dumped) $rootdir/app/spdk_tgt/spdk_tgt -L ftl_init
  14:20:30	# trap - ERR
  14:20:30	# print_backtrace
  14:20:30	# [[ ehxBE =~ e ]]
  14:20:30	# xtrace_disable
  14:20:30	# PREV_BASH_OPTS=ehxBE
  14:20:30	# set +x
========== Backtrace start: ==========

in /var/jenkins/workspace/NVMe_tests/nvme_autotest/spdk/test/ftl/restore.sh:84 -> main()
     ...
   79  	waitfornbd nbd0
   80  	
   81  	mount /dev/nbd0 $mount_dir
   82  	
   83  	# Write second file, to make sure writer thread has restored properly
=> 84  	dd if=/dev/urandom of=$mount_dir/testfile2 bs=4K count=256K
   85  	md5sum $mount_dir/testfile2 > $testdir/testfile2.md5
   86  	
   87  	# Make sure second file will be read from disk
   88  	echo 3 > /proc/sys/vm/drop_caches
   89  	
     ...

========== Backtrace end ==========
  14:20:30	# xtrace_enable
  14:20:30	# return 0
 14:20:30	# restore_kill
 14:20:30	# mount
 14:20:30	# grep /tmp/tmp.ZR2lj1smEH
/dev/nbd0 on /tmp/tmp.ZR2lj1smEH type ext4 (ro,relatime)
 14:20:30	# umount /tmp/tmp.ZR2lj1smEH
 14:20:59	# rm -rf /tmp/tmp.ZR2lj1smEH
 14:20:59	# rm -f /var/jenkins/workspace/NVMe_tests/nvme_autotest/spdk/test/ftl/testfile.md5
 14:20:59	# rm -f /var/jenkins/workspace/NVMe_tests/nvme_autotest/spdk/test/ftl/testfile2.md5
 14:20:59	# rm -f /var/jenkins/workspace/NVMe_tests/nvme_autotest/spdk/test/ftl/config/ftl.json
 14:20:59	# /var/jenkins/workspace/NVMe_tests/nvme_autotest/spdk/scripts/rpc.py bdev_ftl_delete -b nvme0
Traceback (most recent call last):
  File "/var/jenkins/workspace/NVMe_tests/nvme_autotest/spdk/scripts/rpc/client.py", line 40, in __init__
    self.sock.connect(addr)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

**Comment by jimharris** [comment] 2019-11-14 04:13
Bug scrub:  This has only been seen once.  @ksztyber - could you take a look?  Might be something we have to wait to see additional occurrences before we can make more progress.

**Comment by ksztyber** [comment] 2019-11-14 15:35
From what I could gather from the logs, it looks like the spdk_tgt was killed with SIGILL during `spdk_mmio_write_4` inside `nvme_pcie_qpair_ring_sq_doorbell`, but I have no idea what could have caused it.
Unfortunately, the coredump wasn't included with the logs (only the app that caused the crash was attached), so I couldn't check it for any more clues. I think we should make sure that if a coredump is generated, the CI always attaches it along with the logs.

**Comment by Seth5141** [comment] 2019-11-15 04:55
@ksztyber we typically cap the size of the core dumps that we copy to the public logs because they can take a prohibitively long time to copy and can tie up the network while trying to copy other logs. I can check to see if this core exists in the internal logs when I get into the office tomorrow and make it available to you if it's there.

**Comment by Seth5141** [comment] 2019-11-15 15:45
@ksztyber Sorry, the core was actually lost. It ran off the end of our local Jenkins storage backlog.

**Comment by ksztyber** [comment] 2019-11-18 13:21
That's a shame. Hopefully, the next time this failure happens the core dump will be saved.

**Comment by jimharris** [comment] 2019-11-18 14:58
@Seth5141 - I know that we can't keep core files indefinitely due to storage reasons.  Can you share the cutoff for when we start deleting cores (or the builds associated with cores)?  It looks like in this case, it was deleted within 2 days which in a lot of cases won't be enough time for someone to take an initial look.

**Comment by tomzawadzki** [comment] 2019-11-19 15:27
Bug scrub: Files over particular size are not copied over to AWS - which is what probably happens to the core dumps. Those are saved for some time on Jenkins. @ksztyber - lets try to catch such failure in the future and try to workout how to get the core dump.

**Comment by spdkci** [comment] 2019-11-29 13:58
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51054.html

**Comment by jimharris** [comment] 2019-12-03 22:06
@ksztyber - not sure if we can still get the core dump on this one, but the log does give us a valid backtrace for the SIGILL:

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/51054/archive/nvme_autotest/build.log

It's from writing the NVMe CQ doorbell?  It makes no sense to me, but you surely understand these scripts better than me and can maybe hazard a guess.

**Comment by jimharris** [comment] 2019-12-04 23:51
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51427.html

Program terminated with signal SIGILL, Illegal instruction.
#0 0x00000000005c6a45 in spdk_mmio_write_4 (addr=0x20100080100c, val=231) at /var/jenkins/workspace/NVMe_tests/nvme_autotest/spdk/include/spdk/mmio.h:94
94	*addr = val;
[Current thread is 1 (Thread 0x7f122b2e7a40 (LWP 746610))]

**Comment by Seth5141** [comment] 2019-12-06 03:08
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51605.html

@ksztyber I was able to get the coredump from this one. What's the easiest way to get it to you?

**Comment by ksztyber** [comment] 2019-12-06 07:47
@Seth5141 Thanks, I was able to get the coredump from internal servers by following the build number.

**Comment by spdkci** [comment] 2020-01-08 17:23
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55183.html

**Comment by spdkci** [comment] 2020-01-20 06:27
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_57093.html

**Comment by tomzawadzki** [comment] 2020-03-02 14:10
After reaching out to @ksztyber, it looks like the issue was not reproduced for long time either via manual attempt or CI.

Closing the issue, if it happens again - please re-open.

**Closed by tomzawadzki** 2020-03-02 14:10 UTC
Labels: Intermittent Failure
