### ISSUE TITLE
[blobstore] test output doesn't match expected

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2621] opened 2022-08-02 23:47 UTC
0:08:43.801  /var/jenkins/workspace/BlobFS-autotest/spdk/test/blobstore/btest.out:5         List bdevs:
00:08:43.801  /var/jenkins/workspace/BlobFS-autotest/spdk/test/blobstore/btest.out.match:6   	bdev Name: Nvme0n1
00:08:43.801  /var/jenkins/workspace/BlobFS-autotest/spdk/test/blobstore/btest.out:6         	bdev Name: Nvme0n1
00:08:43.801  /var/jenkins/workspace/BlobFS-autotest/spdk/test/blobstore/btest.out.match:7   	bdev Product Name: NVMe disk
00:08:43.801  /var/jenkins/workspace/BlobFS-autotest/spdk/test/blobstore/btest.out:7         	bdev Product Name: NVMe disk
00:08:43.801  /var/jenkins/workspace/BlobFS-autotest/spdk/test/blobstore/btest.out.match:8   SCRIPT NOW PROCESSING: -n 1
00:08:43.801  /var/jenkins/workspace/BlobFS-autotest/spdk/test/blobstore/btest.out:8         	bdev Name: Nvme1n1
00:08:43.801  FAIL: match: /var/jenkins/workspace/BlobFS-autotest/spdk/test/blobstore/btest.out.match:8 did not match pattern
00:08:43.801    17:38:44	-- blobstore/blobstore.sh@24 -- # trap - ERR
00:08:43.801    17:38:44	-- blobstore/blobstore.sh@24 -- # print_backtrace
00:08:43.801    17:38:44	-- common/autotest_common.sh@998 -- # [[ ehxBET =~ e ]]
00:08:43.801    17:38:44	-- common/autotest_common.sh@1000 -- # args=()
00:08:43.801    17:38:44	-- common/autotest_common.sh@1000 -- # local args
00:08:43.801    17:38:44	-- common/autotest_common.sh@1002 -- # xtrace_disable
00:08:43.801    17:38:44	-- common/autotest_common.sh@14 -- # '[' '' '!=' yes ']'
00:08:43.801    17:38:44	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:08:43.801    17:38:44	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:08:43.801    17:38:44	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:08:43.801    17:38:44	-- common/autotest_common.sh@19 -- # set +x
00:08:43.801  ========== Backtrace start: ==========
00:08:43.801

**Comment by spdkci** [comment] 2022-08-02 23:48
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_81684.html

**Comment by jimharris** [comment] 2022-08-02 23:59
Duplicate of #2603 which was recently fixed and closed.  Please rebase from latest master.

**Comment by jimharris** [comment] 2022-08-03 00:00
> Duplicate of #2603 which was recently fixed and closed. Please rebase from latest master.

Patch was merged last Wednesday.

**Closed by jimharris** 2022-08-02 23:59 UTC
Labels: Intermittent Failure
