### ISSUE TITLE
Error starting spdk on arm64

### ISSUE THREAD

**Issue by habeanf** [spdk/spdk#810] opened 2019-06-05 08:39 UTC
The spdk_tgt app crashes on start up on arm64.

## Expected Behavior
spdk_tgt should start on arm64

## Current Behavior
Getting the following error:
```amir@amir-desktop:~/spdk$ sudo app/spdk_tgt/spdk_tgt 
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid17973 ]
EAL: VFIO support initialized
EAL: WARNING! Base virtual address hint (0x200000005000 != 0x7f777ac000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
... removed for brevity ...
EAL: WARNING! Base virtual address hint (0x200002e1e000 != 0x6f77000000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
app.c: 628:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
iscsi_subsystem.c: 170:iscsi_initialize_pdu_pool: *ERROR*: create PDU immediate data pool failed
iscsi_subsystem.c:1309:iscsi_parse_globals: *ERROR*: spdk_initialize_all_pools() failed
iscsi_subsystem.c:1338:spdk_iscsi_init: *ERROR*: spdk_iscsi_parse_globals() failed
subsystem.c: 129:spdk_subsystem_init_next: *ERROR*: Init subsystem iscsi failed
app.c: 723:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero```
## Possible Solution
n/a

## Steps to Reproduce
1. compile on arm64
2. set ulimit -l 10240000
3. HUGEMEM=256 scripts/setup.sh config
4. run app/spdk_tgt/spdk_tgt

## Context (Environment including OS version, SPDK version, etc.)
<!--- Providing context helps us come up with a solution that is most useful in the real world -->
OS: Ubuntu 18.04
SPDK: 19.07-pre commit 7bb1c5735

**Comment by jimharris** [comment] 2019-06-05 14:54
Hi @habeanf,

Thanks for the report.  Could you try this with both SPDK 19.04 as well as 7bb1c57~1 (the commit before 7bb1c57).  You may have noticed that 7bb1c57 is the commit that switches the DPDK submodule from DPDK 19.02 to DPDK 19.05 - I'm curious if the new DPDK version is causing the problem here.

Please make sure to do a "git submodule update" when you go back to the older commits to make sure the DPDK submodule gets reverted to the DPDK 19.02 baseline.

Thanks,

-Jim

**Comment by habeanf** [comment] 2019-06-05 17:41
Sure. With commit 975e46149 which precedes 7bb1c57 spdk hangs on startup (compiled with `CONFIG_DEBUG=y` ):

```amir@amir-desktop:~/spdk$ sudo app/spdk_tgt/spdk_tgt -u
Starting SPDK v19.07-pre / DPDK 19.02.0 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid20070 ]
EAL: VFIO support initialized```

**Comment by habeanf** [comment] 2019-06-05 17:46
@jimharris If it helps, it should be worth mentioning that I'm not entirely sure how iommu/smmu works on the platform I'm compiling on. I can't find any exposed kernel parameters that can be enabled or disabled it.

**Comment by darsto** [comment] 2019-06-12 11:21
@habeanf just one more thing to try - on latest spdk master (w/ DPDK 19.05) could you run spdk_tgt with --mem-size param? e.g.:

`./spdk_tgt --mem-size 1G`

This should preallocate 1G of hugepages and maybe give you some specific error messages if it fails

**Comment by habeanf** [comment] 2019-06-12 16:55
@darsto Thanks for the help. I compiled and tried running it again with the latest spdk and dpdk 19.05. Now I get a different error:
```
root@amir-desktop:/home/amir/spdk# app/spdk_tgt/spdk_tgt --mem-size 1G
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 -m 1024 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid31411 ]
EAL: VFIO support initialized
EAL: WARNING! Base virtual address hint (0x200000005000 != 0x7faaa50000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
... skipping for brevity ...
EAL: WARNING! Base virtual address hint (0x200002e1e000 != 0x6fa3800000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: Not enough memory available! Requested: 1024MB, available: 512MB
EAL: FATAL: Cannot init memory
EAL: Cannot init memory
Failed to initialize DPDK
Unable to initialize SPDK env
```
Perhaps this is related to https://github.com/spdk/spdk/issues/226 ?

**Comment by habeanf** [comment] 2019-06-12 16:56
Doh, I just realized I didn't allocate enough huge pages. Let me retry

**Comment by habeanf** [comment] 2019-06-12 17:18
@darsto So `spdk_tgt --mem-size 1G` starts but it doesn't seem to be working properly. After starting up, I tried to `construct_malloc_bdev` but it fails on spdk_zmalloc:

```
root@amir-desktop:/home/amir/spdk# app/spdk_tgt/spdk_tgt --mem-size 1G          
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...           
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 -m 1024 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid9621 ]
EAL: VFIO support initialized      
EAL: WARNING! Base virtual address hint (0x200000005000 != 0x7fac313000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
... skipped ...
EAL: WARNING! Base virtual address hint (0x200002e1e000 != 0x6fabc00000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
app.c: 628:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
bdev_malloc.c: 419:create_malloc_disk: *ERROR*: malloc_buf spdk_zmalloc() failed
bdev_malloc.c: 419:create_malloc_disk: *ERROR*: malloc_buf spdk_zmalloc() failed
```

FYI the command I used was `scripts/rpc.py construct_malloc_bdev 512 4096`

**Comment by jimharris** [comment] 2019-09-24 16:08
Hi @habeanf - were you able to get this working?

**Comment by habeanf** [comment] 2019-09-24 16:18
Nope :frowning_face:

**Comment by jimharris** [comment] 2019-09-24 16:19
OK.  Is there anyone with an ARM platform that can help @habeanf with this issue?

**Comment by habeanf** [comment] 2019-09-24 16:22
TBH I gave up on it a couple of months ago. Would you like me to try again with the latest commit or release?

**Comment by jimharris** [comment] 2019-09-24 16:26
If you are able to retry on latest master, that would be great.  I'd expect that if someone with an ARM system steps up to try to reproduce and root cause, this is the first thing they will ask you to try.

**Comment by habeanf** [comment] 2019-09-27 09:35
I checked again, the issues persists in master HEAD as of this comment (commit de1f019edf309de1fa66cac45a8adea21ed89e96):
```$ sudo ./app/spdk_tgt --mem-size=1G
Starting SPDK v19.10-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 -m 1024 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid8168 ]    
EAL: VFIO support initialized
EAL: WARNING! Base virtual address hint (0x200000005000 != 0x7f7b2d0000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x20000000b000 != 0x7f7b26f000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x200000a0c000 != 0x7b7b200000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x200000c11000 != 0x7f7b20e000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x200001612000 != 0x777b000000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x200001817000 != 0x7b7b19f000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x200002218000 != 0x737ae00000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x20000241d000 != 0x7b7b13e000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x200002e1e000 != 0x6f7ac00000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: Not enough memory available! Requested: 1024MB, available: 512MB
EAL: FATAL: Cannot init memory
EAL: Cannot init memory
Failed to initialize DPDK
Unable to initialize SPDK env
reactor.c: 112:spdk_reactor_get: *WARNING*: Called spdk_reactor_get() while the g_reactors array was NULL!```
It may help that I'm getting this output when using `scripts/setup.sh` to (de)allocate huge pages:
```$ sudo HUGEMEM=0 scripts/setup.sh config

Current user memlock limit: 10000 MB

This is the maximum amount of memory you will be
able to use with DPDK and VFIO if run as current user.
To change this, please adjust limits.conf memlock limit for current user.
modprobe: FATAL: Module msr not found in directory /lib/modules/4.9.140-tegra```

**Comment by jimharris** [comment] 2019-09-27 14:44
Hi @habeanf,

What SPDK utility are you trying to run?  I notice the DPDK command line says -m 1024 - meaning it's trying to allocate 1GiB of huge pages.  Can you share the full command line you're using?

The debug output indicates there is only 512MiB of huge page memory available.  Is this a limitation on your system?  Or can you try:

sudo HUGEMEM=1024 scripts/setup.sh

-Jim

**Comment by habeanf** [comment] 2019-09-27 17:03
@jimharris Sorry, yes when changing to HUGEMEM=1024 and then --mem-size=1G the process starts up, although with the same warnings about `Base virtual address hint` as above.

There is still an issue, although I'm not sure if you'd prefer closing this one and creating a new one. To test out spdk on ARM, I created a malloc bdev of 128MB with a block size of 4096:
`rpc.py bdev_malloc_create -b test 128 4096`
I then created an nbd disk to play with the malloc bdev locally:
`rpc.py nbd_start_disk test /dev/nbd0`
Which seems to be fine when I try to format the nbd (`mkfs.ext3 /dev/nbd0` seems to run successfully, no errors from mkfs or in the spdk log).
When I try to mount the nbd disk I get:
```
$ sudo mount /dev/nbd0 /nbddisk0
mount: /nbddisk0: wrong fs type, bad option, bad superblock on /dev/nbd0, missing codepage or helper program, or other error.
```
Meanwhile, in the spdk log I see:
`nbd.c: 538: nbd_submit_bdev_io: *ERROR*: nbd io failed in nbd_queue_io, rc=-22`

The same series of commands works fine on my intel laptop.

**Comment by jimharris** [comment] 2019-09-27 17:06
Hi @habeanf,

Thanks for the update!  I'd suggest we close this issue, and open a new one with the mount issue that you're now observing.

-Jim

**Closed** 2019-09-27 17:06 UTC

**Comment by habeanf** [comment] 2019-09-27 17:16
@jimharris Ok, I opened https://github.com/spdk/spdk/issues/972 for the mount issue

**Comment by habeanf** [comment] 2019-09-27 17:19
@jimharris Sorry for the nudge but should anyone be worried or made aware of the warning messages by spdk when starting up on arm:
```
EAL: WARNING! Base virtual address hint (0x200000005000 != 0x7f7b2d0000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
...
```

**Comment by jimharris** [comment] 2019-09-27 17:20
do you only see this warning when you run on ARM?

**Comment by habeanf** [comment] 2019-09-27 17:25
Yeah, I've never seen them on my intel boxes

**Comment by jimharris** [comment] 2019-09-27 17:27
Not sure why those would show up on ARM.  You can ignore them unless you plan to attach to the same NVMe controller from multiple processes.
