### ISSUE TITLE
RPC error messages are not descriptive at all

### ISSUE THREAD

**Issue by pohly** [spdk/spdk#319] opened 2018-05-30 09:57 UTC
## Expected Behavior

When calling GetBDevs() with a name of a BDev and that BDev does not exist, the resulting error is rather generic:
```
response:
{
  "message": "Invalid parameters", 
  "code": -32602
}
```

It would be better to have a dedicated, documented error code for this situation.

I need this because I intend to use the name chosen by Kubernetes for a new volume also as the BDev name. Creating volumes must be idempotent, so when asked to create a volume "foo" I must first check whether there is already a BDev "foo".

## Possible Solution

As GetBDevs only takes one parameter,  one could make the assumption that the only reason for the current error is that the BDev does not exist. But that doesn't feel right.

**Comment by pawelwod** [comment] 2018-05-30 10:46
Don't think you need to check if volume exist. If bdev with the same name already exist RPC will simply fail. But yes, making those error messages more "user firendly" is something what need to be done.

**Comment by pohly** [comment] 2018-05-30 11:55
pawelwod <notifications@github.com> writes:
> Don't think you need to check if volume exist. If bdev with the same
> name already exist RPC will simply fail.

But then my code has the same problem again: how can it distinguish
between "could not create volume because the name was already taken" and
"out of resources, temporary error, whatever..."?

> But yes, making those error
> messages more "user firendly" is something what need to be done.

"user friendly" would imply having some better error messages. That's
worthwhile, but what I am after here is "program friendly": being able
to handle different error scenarios automatically in the code using the
JSON API.

**Comment by pawelwod** [comment] 2018-05-30 12:20
The current direction is to just show string representation of error just like calling `strerror(errno))` would do. As you already noticed this is not a rule yet as there is a lot of RPC code that just send `Invalid argument` message.

We try to be as verbose as we can but I think we never will make (much) more than just returning proper errno code from SPDK API and translating this error using `strerror()` for RPC calls. So, if you ever get `No such device` you can know that there is something wrong and some of required resource doesn't exist. Those errors will have to be documented... eventually.

Anyway I'm rally open to any changes that will make our life easier so if you have any idea how those error messages could look like to aid "automatic error handling" don't hesitate to share the idea :)

**Comment by dverkamp-intel** [comment] 2018-05-30 16:07
I think if we are going to send back strerror() results as the message, we could also at least send errno back as the `code` value - the error code is meant to be user-defined aside from a few specific pre-defined ones (one of which we are currently sending most places).  This should be a pretty easy change to the RPC methods that already use strerror messages.

**Comment by pohly** [comment] 2018-06-01 09:02
Should GetBDevs() really log "bdev ... does not exist" to the syslog? This is something that the user of the RPC call needs to know, but not the admin of the system.

I considered opening a separate issue for this, but it seems related to the entire "rethink JSON error reporting" aspect, so decided against a separate issue.

**Comment by pohly** [comment] 2018-06-01 10:28
Another call where I need to detect "bdev not found" is DeleteBDev.

That's again because deleting a volume is supposed to be idempotent. I could check for existence with GetBDev, but in this case directly calling DeleteBDev is simpler.

**Comment by jimharris** [comment] 2018-06-01 16:23
Hi Patrick,

Agreed – these are all valid issues that need to be addressed.  I think we can track all of them through this issue for now.

-Jim

**Comment by darsto** [comment] 2019-02-11 14:34
This is a common effort that's targeting 19.05. Let me reword the title a bit.

**Comment by darsto** [comment] 2019-02-11 14:40
@pawelwod can you give us an estimation of how much work is there to be done?

**Comment by pawelwod** [comment] 2019-02-12 07:44
> Steps to solve this issue:
> 
>  1. Add "data" field in JSON RPC error reponse. RPC methods can write
> usefull data there eg which parameter are missing. [WIP] patch here 
> https://review.gerrithub.io/#/c/spdk/spdk/+/439524/
> 
>  2. Replace usage of spdk_json_object_decode in JSON RPC methods with
> spdk_jsonrpc_decode_request() - this allows removing a lot of code that
> handle errors, unify JSON error handling and automaticaly produce some
> error responses.
> 
>  3. Change each component - one by one to produce additional "data"
> field in error response.
> 
>  4. Document changes.

Paweł

**Comment by darsto** [comment] 2019-03-12 15:31
Bug scrub: Hopefully we'll be able to improve the error messages for SPDK 19.07.

**Comment by gila** [comment] 2019-04-25 09:36
Hi all,

I'm glad others feel the need to provide more context around RPC error messages as it almost impossible to figure out why things failed if you do not have verbose logging enabled (or looking into the source ofcourse)

Adding error information to the JSON object seems a good way to do that for sure. There is one other thing I'd like to bring up here, let's take the `construct_aio_bdev` RPC call as an example:


```
..
spdk_rpc_construct_aio_bdev ..
{
...

bdev = create_aio_disk(....);
if bdev == NULL goto invalid;
...
```

in the context of the create_aio_disk, there is no way to get to the JSON error object (AFAIK). Are there any ideas about how to make that a feasible solution without needed to rewrite all the bdev methods? 

Ideally, I'd like to know in this example case, if the block device was not found if it failed to open, etc. 

Another aspect I've bumped into while implementing CSI for SPDK, is that in the case of using a lvol store, there is no way to determine if other examines are running for the bdev and thus potentially creating a lvol store. 

For example:

1) create aio bdev
2) create lvol_store

<for whatever reason a restart happens -- not using a config file only RPC>

1) create lvol store
2) list lvol_store 
3) if no lvol on bdev create new

The problem is with (2) there is no way for me to know its "ready" and that indeed there are no lvol stores or that they are loading. There are various ways to get around this ofcourse just wondering if it makes sense to have a common solution for this, as I can imagine similar problems may occur with OCF, RAID and what have you  -- as more complex topologies get constructed.


Thanks

**Comment by yangtianyu0706** [comment] 2019-04-25 13:40
> Hi all,
> 
> I'm glad others feel the need to provide more context around RPC error messages as it almost impossible to figure out why things failed if you do not have verbose logging enabled (or looking into the source ofcourse)
> 
> Adding error information to the JSON object seems a good way to do that for sure. There is one other thing I'd like to bring up here, let's take the `construct_aio_bdev` RPC call as an example:
> 
> ```
> ..
> spdk_rpc_construct_aio_bdev ..
> {
> ...
> 
> bdev = create_aio_disk(....);
> if bdev == NULL goto invalid;
> ...
> ```
> in the context of the create_aio_disk, there is no way to get to the JSON error object (AFAIK). Are there any ideas about how to make that a feasible solution without needed to rewrite all the bdev methods?
> 
> Ideally, I'd like to know in this example case, if the block device was not found if it failed to open, etc.
> 
> Another aspect I've bumped into while implementing CSI for SPDK, is that in the case of using a lvol store, there is no way to determine if other examines are running for the bdev and thus potentially creating a lvol store.
> 
> For example:
> 
> 1. create aio bdev
> 2. create lvol_store
> 
> <for whatever reason a restart happens -- not using a config file only RPC>
> 
> 1. create lvol store
> 2. list lvol_store
> 3. if no lvol on bdev create new
> 
> The problem is with (2) there is no way for me to know its "ready" and that indeed there are no lvol stores or that they are loading. There are various ways to get around this ofcourse just wondering if it makes sense to have a common solution for this, as I can imagine similar problems may occur with OCF, RAID and what have you -- as more complex topologies get constructed.
> 
> Thanks

I looked at the call place to create the Bdev function and found that it was called only when the RPC or parsing the configuration file. So I have an idea that all the create functions return the real error code, not the Bdev pointer, eg. int create_xx_bdev(parameters).

**Comment by jkryl** [comment] 2019-05-02 07:28
Hi @pawelwod , I'm somewhat confused how the final solution will look like. So instead of
```
response:
{
  "message": "Invalid parameters", 
  "code": -32602
}
```
we will have
```
response:
{
  "message": "Invalid parameters", 
  "code": -32602,
  "data": "some more details ..."
}
```
?
If that's the case, I'm still missing a simple error code which would tell what kind of error was encountered (i.e. something similar to ENOENT, EEXIST, ...). Looking at how i.e. grpc does it, they have:

1) a message (for human)
2) a code (for program - set of predefined and documented codes)
3) optional data (arbitrary json type depending on kind of error - could be a JSON object)

That would be an example worth following. For the record here is a doc describing grpc error codes: https://github.com/grpc/grpc/blob/master/doc/statuscodes.md, which we could get inspired by.

**Comment by pawelwod** [comment] 2019-05-06 07:24
Hi @jkryl, I can't answer to your question as I'm no longer engaged in SPDK project. I think @darsto can have aswers you are looking for :)

Paweł

**Comment by darsto** [comment] 2019-06-18 15:13
Bug scrub: Make sure we return c errnos instead of regular "error" messages as a first step.

**Comment by jkryl** [comment] 2019-06-24 20:52
With very little effort I was able to add following extra error codes (enoent & eexist) which we need the most to our fork of spdk:
```
diff --git a/include/spdk/jsonrpc.h b/include/spdk/jsonrpc.h
index 127e30d2b..b58837017 100644
--- a/include/spdk/jsonrpc.h
+++ b/include/spdk/jsonrpc.h
@@ -53,6 +53,8 @@ extern "C" {
 #define SPDK_JSONRPC_ERROR_METHOD_NOT_FOUND    -32601
 #define SPDK_JSONRPC_ERROR_INVALID_PARAMS      -32602
 #define SPDK_JSONRPC_ERROR_INTERNAL_ERROR      -32603
+#define SPDK_JSONRPC_ERROR_NOT_FOUND           -32604
+#define SPDK_JSONRPC_ERROR_ALREADY_EXISTS      -32605
```
then it's just a matter of starting using the new error codes at appropriate places and perhaps using error messages which are more to the point. It is more a continuous effort rather than a big fix which uses the new error codes everywhere where appropriate and changes all error messages. That makes it easy. Of course this is not the only possible approach. We could also return errno code in `data` member of the error. But I find the above more straightforward and easy.

**Comment by karlatec** [comment] 2019-07-09 15:22
For anyone interested, I started making some minor changes towards improving json-rpc error replies. Here's the start of the series: https://review.gerrithub.io/c/spdk/spdk/+/459948

**Comment by changpe1** [comment] 2020-12-10 03:01
Closing this issue as the RPC error response is much more descriptive.

**Closed by changpe1** 2020-12-10 03:01 UTC
Labels: enhancement
