### ISSUE TITLE
[nvmf_multipath] nvmf-tcp-vg-autotest CI test failure

### ISSUE THREAD

**Issue by krish-reddy** [spdk/spdk#1953] opened 2021-05-20 12:08 UTC
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/47853/archive/nvmf-tcp-vg-autotest/build.log

## Execution failed at

00:09:29.676  ========== Backtrace start: ==========
00:09:29.676  
00:09:29.690  in test/nvmf/target/multipath.sh:82 -> main(["--transport=tcp"])
00:09:29.690       ...
00:09:29.690     77  	$rpc_py nvmf_subsystem_listener_set_ana_state nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a "$NVMF_SECOND_TARGET_IP" -s "$NVMF_PORT" -n optimized
00:09:29.690     78  	
00:09:29.690     79  	sleep 1
00:09:29.690     80  	
00:09:29.690     81  	[ $(cat /sys/block/nvme"$subsys_id"c"$ctrl1_id"n1/ana_state) == "optimized" ]
00:09:29.690  => 82  	[ $(cat /sys/block/nvme"$subsys_id"c"$ctrl2_id"n1/ana_state) == "optimized" ]
00:09:29.690     83  	
00:09:29.690     84  	# Set IO policy to round-robin
00:09:29.690     85  	echo round-robin > /sys/class/nvme-subsystem/nvme-subsys$subsys_id/iopolicy
00:09:29.690     86  	
00:09:29.690     87  	$rootdir/scripts/fio-wrapper -p nvmf -i 4096 -d 128 -t randrw -r 6 -v &
00:09:29.690       ...
00:09:29.690  
00:09:29.690  ========== Backtrace end ==========
00:09:29.690    11:44:37	# xtrace_enable
00:09:29.690    11:44:37	# return 0
00:09:29.690   11:44:37	# process_shm --id 0
00:09:29.690   11:44:37	# type=--id
00:09:29.690   11:44:37	# id=0
00:09:29.690   11:44:37	# '[' --id = --pid ']'
00:09:29.690   11:44:37	# '[' --id = --id ']'
00:09:29.690   11:44:37	# id=0
00:09:29.691    11:44:37	# find /dev/shm -name '*.0' -printf '%f\n'
00:09:29.695   11:44:37	# shm_files=nvmf_trace.0
00:09:29.695   11:44:37	# [[ -z nvmf_trace.0 ]]
00:09:29.695   11:44:37	# for n in $shm_files
00:09:29.695   11:44:37	# tar -C /dev/shm/ -cvzf /home/vagrant/spdk_repo/spdk/../output/nvmf_trace.0_shm.tar.gz nvmf_trace.0
00:09:29.701  nvmf_trace.0
00:09:30.712   11:44:38	# return 0
00:09:30.712   11:44:38	# nvmftestfini
00:09:30.712   11:44:38	# nvmfcleanup
00:09:30.712   11:44:38	# sync
00:09:30.716   11:44:38	# '[' tcp == tcp ']'
00:09:30.716   11:44:38	# set +e
00:09:30.716   11:44:38	# for i in {1..20}
00:09:30.716   11:44:38	# modprobe -v -r nvme-tcp
00:09:30.718  rmmod nvme_tcp
00:09:30.781  rmmod nvme_fabrics
00:09:30.790   11:44:38	# modprobe -v -r nvme-fabrics
00:09:30.793   11:44:38	# set -e
00:09:30.793   11:44:38	# return 0
00:09:30.793   11:44:38	# '[' -n 28252 ']'
00:09:30.793   11:44:38	# killprocess 28252
00:09:30.793   11:44:38	# '[' -z 28252 ']'
00:09:30.793   11:44:38	# kill -0 28252
00:09:30.794    11:44:38	# uname
00:09:30.796   11:44:38	# '[' Linux = Linux ']'
00:09:30.797    11:44:38	# ps --no-headers -o comm= 28252
00:09:30.815  killing process with pid 28252
00:09:30.815   11:44:38	# process_name=reactor_0
00:09:30.815   11:44:38	# '[' reactor_0 = sudo ']'
00:09:30.815   11:44:38	# echo 'killing process with pid 28252'
00:09:30.815   11:44:38	# kill 28252
00:09:30.815   11:44:38	# wait 28252
00:09:31.155  EAL: device event monitor already stopped
00:09:31.194   11:44:38	# '[' '' == iso ']'
00:09:31.194   11:44:38	# [[ tcp == \t\c\p ]]
00:09:31.194   11:44:38	# nvmf_tcp_fini
00:09:31.194   11:44:38	# [[ nvmf_tgt_ns == \n\v\m\f\_\t\g\t\_\n\s ]]
00:09:31.194   11:44:38	# nvmf_veth_fini
00:09:31.194   11:44:38	# ip link set nvmf_init_br nomaster
00:09:31.204   11:44:38	# ip link set nvmf_tgt_br nomaster
00:09:31.213   11:44:38	# ip link set nvmf_tgt_br2 nomaster
00:09:31.226   11:44:38	# ip link set nvmf_init_br down
00:09:31.229   11:44:38	# ip link set nvmf_tgt_br down
00:09:31.232   11:44:38	# ip link set nvmf_tgt_br2 down
00:09:31.235   11:44:38	# ip link delete nvmf_br type bridge
00:09:31.258   11:44:38	# ip link delete nvmf_init_if
00:09:31.273   11:44:38	# ip netns exec nvmf_tgt_ns ip link delete nvmf_tgt_if
00:09:31.287   11:44:38	# ip netns exec nvmf_tgt_ns ip link delete nvmf_tgt_if2
00:09:31.304   11:44:38	# ip netns del nvmf_tgt_ns
00:09:31.307   11:44:38	# return 0
00:09:31.307   11:44:38	# exit 1
00:09:31.308    11:44:38	# trap - ERR
00:09:31.308    11:44:38	# print_backtrace
00:09:31.308    11:44:38	# [[ ehxBET =~ e ]]
00:09:31.308    11:44:38	# args=("${BASH_ARGV[@]}")
00:09:31.308    11:44:38	# local args
00:09:31.308    11:44:38	# xtrace_disable
00:09:31.308    11:44:38	# '[' no '!=' yes ']'
00:09:31.308    11:44:38	# PREV_BASH_OPTS=ehxBET
00:09:31.308    11:44:38	# [[ ehxBET == *\x* ]]
00:09:31.308    11:44:38	# XTRACE_DISABLED=yes
00:09:31.308    11:44:38	# set +x
00:09:31.308  ========== Backtrace start: ==========
00:09:31.308  
00:09:31.320  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:948 -> run_test(["nvmf_multipath"],["test/nvmf/target/multipath.sh"],["--transport=tcp"])
00:09:31.320       ...
00:09:31.320     943 		timing_enter $test_name
00:09:31.320     944 		echo "************************************"
00:09:31.320     945 		echo "START TEST $test_name"
00:09:31.320     946 		echo "************************************"
00:09:31.320     947 		xtrace_restore
00:09:31.320  => 948 		time "$@"
00:09:31.320     949 		xtrace_disable
00:09:31.320     950 		echo "************************************"
00:09:31.320     951 		echo "END TEST $test_name"
00:09:31.320     952 		echo "************************************"
00:09:31.320     953 		timing_exit $test_name
00:09:31.320       ...
00:09:31.329  in ./test/nvmf/nvmf.sh:56 -> main(["--transport=tcp"])
00:09:31.329       ...
00:09:31.329     51  		run_test "nvmf_shutdown" test/nvmf/target/shutdown.sh "${TEST_ARGS[@]}"
00:09:31.329     52  		#TODO: disabled due to intermittent failures. Need to triage.
00:09:31.329     53  		# run_test "nvmf_srq_overwhelm" test/nvmf/target/srq_overwhelm.sh $TEST_ARGS
00:09:31.329     54  	fi
00:09:31.329     55  	
00:09:31.329  => 56  	run_test "nvmf_multipath" test/nvmf/target/multipath.sh "${TEST_ARGS[@]}"
00:09:31.329     57  	
00:09:31.329     58  	timing_enter host
00:09:31.329     59  	
00:09:31.329     60  	run_test "nvmf_identify" test/nvmf/host/identify.sh "${TEST_ARGS[@]}"
00:09:31.329     61  	run_test "nvmf_perf" test/nvmf/host/perf.sh "${TEST_ARGS[@]}"
00:09:31.329       ...
00:09:31.329  
00:09:31.329  ========== Backtrace end ==========
00:09:31.329    11:44:38	# xtrace_enable
00:09:31.329    11:44:38	# return 0
00:09:31.329  
00:09:31.329  real	0m37.991s
00:09:31.329  user	2m28.160s
00:09:31.329  sys	0m5.036s
00:09:31.329   11:44:38	# exit 1
00:09:31.330    11:44:38	# trap - ERR
00:09:31.330    11:44:38	# print_backtrace
00:09:31.331    11:44:38	# [[ ehxBET =~ e ]]
00:09:31.331    11:44:38	# args=("${BASH_ARGV[@]}")
00:09:31.331    11:44:38	# local args
00:09:31.331    11:44:38	# xtrace_disable
00:09:31.331    11:44:38	# '[' no '!=' yes ']'
00:09:31.331    11:44:38	# PREV_BASH_OPTS=ehxBET
00:09:31.331    11:44:38	# [[ ehxBET == *\x* ]]
00:09:31.331    11:44:38	# XTRACE_DISABLED=yes
00:09:31.331    11:44:38	# set +x
00:09:31.331  ========== Backtrace start: ==========
00:09:31.331  
00:09:31.343  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:948 -> run_test(["nvmf_tcp"],["./test/nvmf/nvmf.sh"],["--transport=tcp"])
00:09:31.343       ...
00:09:31.343     943 		timing_enter $test_name
00:09:31.343     944 		echo "************************************"
00:09:31.343     945 		echo "START TEST $test_name"
00:09:31.343     946 		echo "************************************"
00:09:31.343     947 		xtrace_restore
00:09:31.343  => 948 		time "$@"
00:09:31.343     949 		xtrace_disable
00:09:31.343     950 		echo "************************************"
00:09:31.343     951 		echo "END TEST $test_name"
00:09:31.343     952 		echo "************************************"
00:09:31.343     953 		timing_exit $test_name
00:09:31.343       ...
00:09:31.351  in /home/vagrant/spdk_repo/spdk/autotest.sh:263 -> main(["/home/vagrant/autorun-spdk.conf"])
00:09:31.351       ...
00:09:31.351     258 				run_test "spdkcli_nvmf_rdma" ./test/spdkcli/nvmf.sh --transport=$SPDK_TEST_NVMF_TRANSPORT
00:09:31.351     259 			elif [ "$SPDK_TEST_NVMF_TRANSPORT" = "tcp" ]; then
00:09:31.351     260 				timing_enter tcp_setup
00:09:31.351     261 				tcp_device_init
00:09:31.351     262 				timing_exit tcp_setup
00:09:31.351  => 263 				run_test "nvmf_tcp" ./test/nvmf/nvmf.sh --transport=$SPDK_TEST_NVMF_TRANSPORT
00:09:31.351     264 				run_test "spdkcli_nvmf_tcp" ./test/spdkcli/nvmf.sh --transport=$SPDK_TEST_NVMF_TRANSPORT
00:09:31.351     265 				run_test "nvmf_identify_passthru" test/nvmf/target/identify_passthru.sh --transport=$SPDK_TEST_NVMF_TRANSPORT
00:09:31.351     266 				run_test "nvmf_dif" test/nvmf/target/dif.sh
00:09:31.351     267 			elif [ "$SPDK_TEST_NVMF_TRANSPORT" = "fc" ]; then
00:09:31.351     268 				run_test "nvmf_fc" ./test/nvmf/nvmf.sh --transport=$SPDK_TEST_NVMF_TRANSPORT
00:09:31.351       ...
00:09:31.351  
00:09:31.351  ========== Backtrace end ==========
00:09:31.351    11:44:38	# xtrace_enable
00:09:31.351    11:44:38	# return 0
00:09:31.351  
00:09:31.351  real	4m13.884s
00:09:31.351  user	15m8.034s
00:09:31.351  sys	0m53.653s

**Comment by spdkci** [comment] 2021-05-20 12:10
Another instance of this failure. Reported by @krish-reddy. log: https://ci.spdk.io/public_build/autotest-per-patch_47853.html

**Comment by mikeBashStuff** [comment] 2021-05-20 12:11
This is a duplicate of #1801, closing. :)

**Closed by mikeBashStuff** 2021-05-20 12:11 UTC
Labels: Intermittent Failure

**Comment by spdkci** [comment] 2021-08-02 20:06
Another instance of this failure. Reported by @yupeng0921. log: https://ci.spdk.io/public_build/autotest-per-patch_54754.html

**Comment by spdkci** [comment] 2021-08-02 23:49
Another instance of this failure. Reported by @yupeng0921. log: https://ci.spdk.io/public_build/autotest-per-patch_54863.html
