### ISSUE TITLE
[vfio-user-autotest] two few blocks in devices test

### ISSUE THREAD

**Issue by mgerdts** [spdk/spdk#2355] opened 2022-01-28 14:44 UTC
# CI Intermittent Failure

During devices, vfio-user-autotest fails while running `setup/devices.sh`.

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/69509/archive/vfio-user-autotest/build.log

## Execution failed at

```
00:01:42.151  ========== Backtrace start: ==========
00:01:42.151  
00:01:42.151  in /var/jenkins/workspace/vfio-user-autotest/spdk/test/setup/devices.sh:186 -> main([])
00:01:42.151       ...
00:01:42.151     181 		if ! block_in_use "${block##*/}" && (($(sec_size_to_bytes "${block##*/}") >= min_disk_size)); then
00:01:42.151     182 			blocks+=("${block##*/}")
00:01:42.151     183 			blocks_to_pci["${block##*/}"]=$pci
00:01:42.151     184 		fi
00:01:42.151     185 	done
00:01:42.151  => 186 	((${#blocks[@]} > 0))
00:01:42.151     187 	
00:01:42.151     188 	declare -r test_disk=${blocks[0]}
00:01:42.151     189 	
00:01:42.151     190 	run_test "nvme_mount" nvme_mount
00:01:42.151     191 	run_test "dm_mount" dm_mount
00:01:42.151       ...
00:01:42.151  
00:01:42.151  ========== Backtrace end ==========
```

**Comment by spdkci** [comment] 2022-01-28 14:45
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_69587.html

**Comment by jimharris** [comment] 2022-01-28 15:13
Duplicate of #2345.

**Closed by jimharris** 2022-01-28 15:13 UTC
Labels: Intermittent Failure
