### ISSUE TITLE
[nvmf_host_multipath_status] inaccessible port reported as current==true

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#3376] opened 2024-05-15 22:21 UTC
```
00:20:36.679   15:05:15 nvmf_tcp.nvmf_host_multipath_status -- host/multipath_status.sh@109 -- # sleep 1
00:20:37.616   15:05:16 nvmf_tcp.nvmf_host_multipath_status -- host/multipath_status.sh@110 -- # check_status false false true true false false
00:20:37.616   15:05:16 nvmf_tcp.nvmf_host_multipath_status -- host/multipath_status.sh@68 -- # port_status 4420 current false
00:20:37.616    15:05:16 nvmf_tcp.nvmf_host_multipath_status -- host/multipath_status.sh@64 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_get_io_paths
00:20:37.616    15:05:16 nvmf_tcp.nvmf_host_multipath_status -- host/multipath_status.sh@64 -- # jq -r '.poll_groups[].io_paths[] | select (.transport.trsvcid=="4420").current'
00:20:38.551   15:05:17 nvmf_tcp.nvmf_host_multipath_status -- host/multipath_status.sh@64 -- # [[ true == \f\a\l\s\e ]]
00:20:38.551    15:05:17 nvmf_tcp.nvmf_host_multipath_status -- host/multipath_status.sh@64 -- # trap - ERR
00:20:38.551    15:05:17 nvmf_tcp.nvmf_host_multipath_status -- host/multipath_status.sh@64 -- # print_backtrace
00:20:38.551    15:05:17 nvmf_tcp.nvmf_host_multipath_status -- common/autotest_common.sh@1149 -- # [[ ehxBET =~ e ]]
00:20:38.551    15:05:17 nvmf_tcp.nvmf_host_multipath_status -- common/autotest_common.sh@1151 -- # args=('false' 'current' '4420' 'false' 'false' 'true' 'true' 'false' 'false' '--transport=tcp')
00:20:38.551    15:05:17 nvmf_tcp.nvmf_host_multipath_status -- common/autotest_common.sh@1151 -- # local args
00:20:38.551    15:05:17 nvmf_tcp.nvmf_host_multipath_status -- common/autotest_common.sh@1153 -- # xtrace_disable
00:20:38.551    15:05:17 nvmf_tcp.nvmf_host_multipath_status -- common/autotest_common.sh@10 -- # set +x
00:20:38.551  ========== Backtrace start: ==========
00:20:38.551  
00:20:38.551  in /home/vagrant/spdk_repo/spdk/test/nvmf/host/multipath_status.sh:64 -> port_status(["4420"],["current"],["false"])
00:20:38.551       ...
00:20:38.551     59  		$rpc_py nvmf_subsystem_listener_set_ana_state $NQN -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_PORT -n $1
00:20:38.551     60  		$rpc_py nvmf_subsystem_listener_set_ana_state $NQN -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_SECOND_PORT -n $2
00:20:38.551     61  	}
00:20:38.551     62  	
00:20:38.551     63  	function port_status() {
00:20:38.551  => 64  		[[ $($rpc_py -s $bdevperf_rpc_sock bdev_nvme_get_io_paths | jq -r ".poll_groups[].io_paths[] | select (.transport.trsvcid==\"$1\").$2") == "$3" ]]
00:20:38.551     65  	}
00:20:38.551     66  	
00:20:38.551     67  	function check_status() {
00:20:38.551     68  		port_status $NVMF_PORT current $1
00:20:38.551     69  		port_status $NVMF_SECOND_PORT current $2
00:20:38.551       ...
00:20:38.551  in /home/vagrant/spdk_repo/spdk/test/nvmf/host/multipath_status.sh:68 -> check_status(["false"],["false"],["true"],["true"],["false"],["false"])
00:20:38.551       ...
00:20:38.551     63  	function port_status() {
00:20:38.551     64  		[[ $($rpc_py -s $bdevperf_rpc_sock bdev_nvme_get_io_paths | jq -r ".poll_groups[].io_paths[] | select (.transport.trsvcid==\"$1\").$2") == "$3" ]]
00:20:38.551     65  	}
00:20:38.551     66  	
00:20:38.551     67  	function check_status() {
00:20:38.552  => 68  		port_status $NVMF_PORT current $1
00:20:38.552     69  		port_status $NVMF_SECOND_PORT current $2
00:20:38.552     70  		port_status $NVMF_PORT connected $3
00:20:38.552     71  		port_status $NVMF_SECOND_PORT connected $4
00:20:38.552     72  		port_status $NVMF_PORT accessible $5
00:20:38.552     73  		port_status $NVMF_SECOND_PORT accessible $6
00:20:38.552       ...
00:20:38.552  in /home/vagrant/spdk_repo/spdk/test/nvmf/host/multipath_status.sh:110 -> main(["--transport=tcp"])
00:20:38.552       ...
00:20:38.552     105 	sleep 1
00:20:38.552     106 	check_status true false true true true false
00:20:38.552     107 	
00:20:38.552     108 	set_ANA_state inaccessible inaccessible
00:20:38.552     109 	sleep 1
00:20:38.552  => 110 	check_status false false true true false false
00:20:38.552     111 	
00:20:38.552     112 	set_ANA_state inaccessible optimized
00:20:38.552     113 	sleep 1
00:20:38.552     114 	check_status false true true true false true
00:20:38.552     115 	
00:20:38.552       ...
00:20:38.552  
00:20:38.552  ========== Backtrace end ==========
00:20:38.552    15:05:17 nvmf_tcp.nvmf_host_multipath_status -- common/autotest_common.sh@1190 -- # return 0
00:20:38.552   15:05:17 nvmf_tcp.nvmf_host_multipath_status -- host/multipath_status.sh@1 -- # cleanup
00:20:38.552   15:05:17 nvmf_tcp.nvmf_host_multipath_status -- host/multipath_status.sh@24 -- # process_shm --id 0
00:20:38.552   15:05:17 nvmf_tcp.nvmf_host_multipath_status -- common/autotest_common.sh@804 -- # type=--id
00:20:38.552   15:05:17 nvmf_tcp.nvmf_host_multipath_status -- common/autotest_common.sh@805 -- # id=0
00:20:38.552   15:05:17 nvmf_tcp.nvmf_host_multipath_status -- common/autotest_common.sh@806 -- # '[' --id = --pid ']'
00:20:38.552    15:05:17 nvmf_tcp.nvmf_host_multipath_status -- common/autotest_common.sh@810 -- # find /dev/shm -name '*.0' -printf '%f\n'
00:20:38.552   15:05:17 nvmf_tcp.nvmf_host_multipath_status -- common/autotest_common.sh@810 -- # shm_files=nvmf_trace.0
00:20:38.552   15:05:17 nvmf_tcp.nvmf_host_multipath_status -- common/autotest_common.sh@812 -- # [[ -z nvmf_trace.0 ]]
00:20:38.552   15:05:17 nvmf_tcp.nvmf_host_multipath_status -- common/autotest_common.sh@816 -- # for n in $shm_files
00:20:38.552   15:05:17 nvmf_tcp.nvmf_host_multipath_status -- common/autotest_common.sh@817 -- # tar -C /dev/shm/ -cvzf /home/vagrant/spdk_repo/spdk/../output/nvmf_trace.0_shm.tar.gz nvmf_trace.0
00:20:38.552  nvmf_trace.0
00:20:38.816   15:05:17 nvmf_tcp.nvmf_host_multipath_status -- common/autotest_common.sh@819 -- # return 0
00:20:38.816   15:05:17 nvmf_tcp.nvmf_host_multipath_status -- host/multipath_status.sh@25 -- # cat /home/vagrant/spdk_repo/spdk/test/nvmf/host/try.txt
00:20:38.816  [2024-05-15 15:04:57.197749] Starting SPDK v24.05-pre git sha1 c7a82f3a8 / DPDK 23.11.0 initialization...
00:20:38.816  [2024-05-15 15:04:57.197909] [ DPDK EAL parameters: bdevperf --no-shconf -c 0x4 --huge-unlink --no-telemetry --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid75825 ]
00:20:38.817  [2024-05-15 15:04:57.342334] app.c: 909:spdk_app_start: *NOTICE*: Total cores available: 1
00:20:38.817  [2024-05-15 15:04:57.450567] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 2
00:20:38.817  Running I/O for 90 seconds...
00:20:38.817  [2024-05-15 15:05:15.196757] nvme_qpair.c: 243:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:19 nsid:1 lba:68568 len:8 SGL DATA BLOCK OFFSET 0x0 len:0x1000
00:20:38.817  [2024-05-15 15:05:15.196839] nvme_qpair.c: 474:spdk_nvme_print_completion: *NOTICE*: ASYMMETRIC ACCESS INACCESSIBLE (03/02) qid:1 cid:19 cdw0:0 sqhd:003e p:0 m:0 dnr:0
00:20:38.817  [2024-05-15 15:05:15.196889] nvme_qpair.c: 243:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:110 nsid:1 lba:68576 len:8 SGL DATA BLOCK OFFSET 0x0 len:0x1000
00:20:38.817  [2024-05-15 15:05:15.196905] nvme_qpair.c: 474:spdk_nvme_print_completion: *NOTICE*: ASYMMETRIC ACCESS INACCESSIBLE (03/02) qid:1 cid:110 cdw0:0 sqhd:003f p:0 m:0 dnr:0
```
[TZ - formatted as code block for readability]

**Comment by spdkci** [comment] 2024-05-15 22:22
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_122925.html

**Comment by shuhei-matsumoto** [comment] 2024-05-24 12:43
Hi, I think this error occurred because io_path availability check was missing for this case.

Please check three patches starting from https://review.spdk.io/gerrit/c/spdk/spdk/+/23402/1.
I could not reproduce the error but verified the fix writing unit test.

**Comment by shuhei-matsumoto** [comment] 2024-05-24 21:02
Hi, as we start a anatt_timer when the ana state becomes inaccessible, the inaccessible state is very temporary. Hence, I did not think clearing nvme_bdev_channel::current_io_path via spdk_for_each_channel() was a good idea. Each I/O submission checks ana state anyway. Hence, fixing only JSON dump was good to me. Of course, I can be wrong.

**Comment by tomzawadzki** [comment] 2024-07-16 10:34
Closing this issue, since the patches were merged and no further occurrences were reported.

**Closed by tomzawadzki** 2024-07-16 10:34 UTC
Labels: bug, Intermittent Failure
