### ISSUE TITLE
FIO Plugin (bdev) with remote NVMe drives fails to finish with a large number of jobs

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#1021] opened 2019-10-31 17:46 UTC
## Expected Behavior
Even when run with a large number of jobs against a lot of bdevs, the SPDK FIO plugin should be able to complete properly.

## Current Behavior
When running a heavy workload using the SPDK bdev fio plugin to remote NVMe drives using the TCP NVMe-oF initiator as a backend, the fio job will hang indefinitely with 1 or two jobs outstanding.
From some of the debugging I have done, it appears that FIO is no longer submitting I/O, but is spinning waiting for the thread to finish. I don't know if that means there is still a request outstanding or something else.

## Possible Solution
WIP
I will see if I can replicate this with local malloc disks to remove the NVMe-oF initiator from the picture. If  I can, it will simplify the picture considerably.
If it cannot be reproduced locally, I will try using RDMA to replicate the failure.

## Steps to Reproduce
Please see the config files below.

Initiator:
fio.conf
~~~
[global]
ioengine=/home/sethhowe/Desktop/Development_Folders/spdk/examples/bdev/fio_plugin/fio_plugin
spdk_conf=/home/sethhowe/Desktop/Development_Folders/ziye_failure_repro/spdk_bdev.conf
thread=1
group_reporting=1
direct=1
norandommap=1
rw=randrw
#rwmixread={100, 70, 0}
rwmixread=50
bs=4k
iodepth=128
time_based=1
ramp_time=1
runtime=6
[test]
numjobs=32
filename=Nvme0n1
filename=Nvme0n2
filename=Nvme0n3
filename=Nvme0n4
filename=Nvme0n5
filename=Nvme0n6
filename=Nvme0n7
filename=Nvme0n8
filename=Nvme0n9
filename=Nvme0n10
filename=Nvme0n11
filename=Nvme0n12
filename=Nvme0n13
filename=Nvme0n14
filename=Nvme0n15
filename=Nvme0n16
filename=Nvme0n17
filename=Nvme0n18
filename=Nvme0n19
filename=Nvme0n20
filename=Nvme0n21
filename=Nvme0n22
filename=Nvme0n23
filename=Nvme0n24
filename=Nvme0n25
filename=Nvme0n26
filename=Nvme0n27
filename=Nvme0n28
filename=Nvme0n29
filename=Nvme0n30
filename=Nvme0n31
~~~

spdk_bdev.conf
~~~
[NVMe]
TransportId "trtype:TCP adrfam:IPv4 traddr:143.182.136.140 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode1" Nvme0
~~~

target:
nvmf.conf
~~~
[Global]

[Bdev]

[Null]
Dev Null0 64 4096
Dev Null1 64 4096
Dev Null2 64 4096
Dev Null3 64 4096
Dev Null4 64 4096
Dev Null5 64 4096
Dev Null6 64 4096
Dev Null7 64 4096
Dev Null8 64 4096
Dev Null9 64 4096
Dev Null10 64 4096
Dev Null11 64 4096
Dev Null12 64 4096
Dev Null13 64 4096
Dev Null14 64 4096
Dev Null15 64 4096
Dev Null16 64 4096
Dev Null17 64 4096
Dev Null18 64 4096
Dev Null19 64 4096
Dev Null20 64 4096
Dev Null21 64 4096
Dev Null22 64 4096
Dev Null23 64 4096
Dev Null24 64 4096
Dev Null25 64 4096
Dev Null26 64 4096
Dev Null27 64 4096
Dev Null28 64 4096
Dev Null29 64 4096
Dev Null30 64 4096
Dev Null31 64 4096

[Nvmf]

AcceptorPollRate 10000

[Transport]

Type TCP

[Subsystem1]
NQN nqn.2016-06.io.spdk:cnode1
Listen TCP 143.182.137.120:4420
AllowAnyHost Yes
SN SPDK00000000000001
MaxNamespaces 40
Namespace Null0
Namespace Null1
Namespace Null2
Namespace Null3
Namespace Null4
Namespace Null5
Namespace Null6
Namespace Null7
Namespace Null8
Namespace Null9
Namespace Null10
Namespace Null11
Namespace Null12
Namespace Null13
Namespace Null14
Namespace Null15
Namespace Null16
Namespace Null17
Namespace Null18
Namespace Null19
Namespace Null20
Namespace Null21
Namespace Null22
Namespace Null23
Namespace Null24
Namespace Null25
Namespace Null26
Namespace Null27
Namespace Null28
Namespace Null29
Namespace Null30
Namespace Null31
~~~

## Context (Environment including OS version, SPDK version, etc.)
This is reproducible on the latest master. My local kernel version is 4.19.13-200 running on fedora 28 although this should be irrelevant as we are using SPDK on both the initiator and target side.
This issue is related to #995 in that they both use the same configuration, but this job doesn't fail and produce a core dump like that issue did.

**Comment by wanqunintel** [comment] 2019-11-04 02:04
I see the same issue for NVME plugin for heavy workload

**Comment by wanqunintel** [comment] 2019-11-04 08:44
I am trying also with a 2nd fio job on another machine and it turns out that it will trigger the 1st fio job to start to run, but with very low IOPS result. when the 2nd job stops normally, if the 1st fio job not 100% complete, then it will hang again without any IO, if completed, it will reach a high IOPS.

**Comment by optimistyzy** [comment] 2019-11-07 02:26
@Seth5141 Any detailed log information of this issue.

**Comment by wanqunintel** [comment] 2019-11-14 01:10
@Seth5141 @optimistyzy i tried with this commit of spdk 4d0c5091a99adba3c51bceef39f67e5991131159, and run the config as above for more than 10 times, each time run with 10minutes and didn't see any error report out. i think the master has fixed this issue and we can close it.

**Comment by optimistyzy** [comment] 2019-11-14 02:57
@Seth5141 Close this issue according to @wanqunintel 's comments. If you can reproduce this issue, please do open this again.

**Closed by optimistyzy** 2019-11-14 02:57 UTC
