### ISSUE TITLE
[setup/acl] setup.sh failed to rebind driver

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#3147] opened 2023-10-06 10:54 UTC
The point of failure doesn't show much:
```
00:03:23.688  START TEST allowed
00:03:23.688  ************************************
00:03:23.688   09:41:09	-- common/autotest_common.sh@1078 -- # allowed
00:03:23.688   09:41:09	-- setup/acl.sh@45 -- # PCI_ALLOWED=0000:d8:00.0
00:03:23.688   09:41:09	-- setup/acl.sh@45 -- # setup output config
00:03:23.688   09:41:09	-- setup/acl.sh@46 -- # grep -E '0000:d8:00.0 .*: nvme -> .*'
00:03:23.688   09:41:09	-- setup/common.sh@9 -- # [[ output == output ]]
00:03:23.688   09:41:09	-- setup/common.sh@10 -- # /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/setup.sh config
00:03:25.600    09:41:11	-- setup/acl.sh@46 -- # trap - ERR
00:03:25.600    09:41:11	-- setup/acl.sh@46 -- # print_backtrace
00:03:25.600    09:41:11	-- common/autotest_common.sh@1106 -- # [[ ehxBET =~ e ]]
00:03:25.600    09:41:11	-- common/autotest_common.sh@1108 -- # args=('allowed' 'allowed')
00:03:25.600    09:41:11	-- common/autotest_common.sh@1108 -- # local args
00:03:25.600    09:41:11	-- common/autotest_common.sh@1110 -- # xtrace_disable
00:03:25.600    09:41:11	-- common/autotest_common.sh@10 -- # set +x
00:03:25.600  ========== Backtrace start: ==========
00:03:25.600  
00:03:25.600  in /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/setup/acl.sh:46 -> allowed([])
00:03:25.600       ...
00:03:25.600     41  		setup reset
00:03:25.600     42  	}
00:03:25.600     43  	
00:03:25.600     44  	allowed() {
00:03:25.600     45  		PCI_ALLOWED="${devs[0]}" setup output config \
00:03:25.600  => 46  			| grep -E "${devs[0]} .*: ${drivers["${devs[0]}"]} -> .*"
00:03:25.600     47  		verify "${devs[@]:1}"
00:03:25.600     48  		setup reset
00:03:25.600     49  	}
00:03:25.600     50  	
00:03:25.600     51  	setup reset
```

But later on, the logs show that there's data on the drive we're trying to bind, so that's probably why the test failed:
```
00:03:43.712  0000:d8:00.0 (8086 0a54): Active devices: data@nvme0n1, so not binding PCI dev
```

Happened on WFP22.

## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/110767/archive/nvmf-tcp-phy-autotest_53401/build.log
https://ci.spdk.io/public_build/autotest-per-patch_110767.html

**Comment by spdkci** [comment] 2023-10-06 10:55
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_110767.html

**Comment by ksztyber** [comment] 2023-10-11 10:55
Hasn't happen for a last few days, so I think it's safe to say it's fine. Closing.

**Comment by spdkci** [comment] 2024-05-21 10:51
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_123290.html

**Comment by spdkci** [comment] 2024-05-21 10:58
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_123288.html

**Comment by ksztyber** [comment] 2024-05-21 11:00
Re-opening, as it happened again, twice.

**Comment by spdkci** [comment] 2024-05-21 11:04
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_123291.html

**Comment by mikeBashStuff** [comment] 2024-05-21 11:19
CYP9, WFP19 (so far) had dirty nvmes (they were recently connected back to the pool) - both cleaned up. Waiting a bit before closing to see if similar issue doesn't occur on other nodes.

**Comment by spdkci** [comment] 2024-05-21 11:36
Another instance of this failure. Reported by @KGoreczny. log: https://ci.spdk.io/public_build/autotest-per-patch_123292.html

**Comment by spdkci** [comment] 2024-05-21 11:41
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_123295.html

**Comment by spdkci** [comment] 2024-05-21 12:05
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_123299.html

**Comment by mchomnic** [comment] 2024-05-21 16:25
the issue is no longer reproducible on WFP19, closing.

**Closed by mchomnic** 2024-05-21 16:25 UTC
Labels: Infrastructure, Intermittent Failure

**Comment by spdkci** [comment] 2024-05-22 06:50
Another instance of this failure. Reported by @mchomnic. log: https://ci.spdk.io/public_build/autotest-per-patch_123297.html
