### ISSUE TITLE
hotplug for a single device does not work in multi devices environment

### ISSUE THREAD

**Issue by songyangeric** [spdk/spdk#2593] opened 2022-07-18 09:47 UTC
# Bug report

I changed the hotplug example under example/nvme/hotplug for single device hotplug test.  Default `NULL` is replaced by a specific trid so that a single device can be tested.
```c
spdk_nvme_probe(&g_trid, NULL, probe_cb, attach_cb, remove_cb) != 0
```
In my test environment, there are mulitiple nvme devices and I chose only one for test. When hotplug is executed, error messages are shown below (I added several log for analysis).
```c
build/examples/hotplug -n 1 -r 1 -t 180
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
Initializing NVMe Controllers
Attaching to 0000:3d:00.0
Attached to 0000:3d:00.0
Initialization complete. Starting I/O...
[2022-07-18 17:18:02.760464] pci.c: 657:spdk_pci_device_attach: *ERROR*: dev already attached
[2022-07-18 17:18:02.760509] nvme.c: 838:nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
[2022-07-18 17:18:02.760521] nvme.c:1524:spdk_nvme_probe_async: *ERROR*: nvme_probe_internal failed
[2022-07-18 17:18:02.760532] nvme.c: 915:spdk_nvme_probe: *ERROR*: Create probe context failed
spdk_nvme_probe() failed
unregister_dev: INTEL SSDPE2KE020T7  (PHLE811201ZF2P0DGN  )
```

I dug into the source code and found there is a little difference between `NULL` and a spcefic `spdk_nvme_transport_id` for `spdk_nvme_probe`. It seems if trid is specified, `spdk_nvme_probe` cannot be called again for this device as `-1` will be returned which indicates an error occurs. 
```c
int
spdk_pci_enumerate(struct spdk_pci_driver *driver,
           spdk_pci_enum_cb enum_cb,
           void *enum_ctx)
{
    ...

    TAILQ_FOREACH(dev, &g_pci_devices, internal.tailq) {
        if (dev->internal.attached ||
            dev->internal.driver != driver ||
            dev->internal.pending_removal) {
            continue;
        }
     ...
}

int
spdk_pci_device_attach(struct spdk_pci_driver *driver,
               spdk_pci_enum_cb enum_cb,
               void *enum_ctx, struct spdk_pci_addr *pci_address)
{
    ...

    if (dev != NULL && dev->internal.driver == driver) {
        pthread_mutex_lock(&g_pci_mutex);
        if (dev->internal.attached || dev->internal.pending_removal) {
            pthread_mutex_unlock(&g_pci_mutex);
            SPDK_ERRLOG("dev already attached\n");
            return -1;
        }
    
    ...
}
```

Is this a bug or designed like this? Hope for your response.

## Expected Behavior

Hotplug for a single device should work in multi devices environment.

## Current Behavior

Hotplug for a single device does not work in multi devices environment.

## Steps to Reproduce

1. Change example/nvme/hotplug/hotplug.c，replace NULL with a spcefic trid when calling `spdk_nvme_probe`
2. Run example hotplug

## Context (Environment including OS version, SPDK version, etc.)

OS: CentOS8 with kernel version 4.18.0-193.28.1
SPDK version:  v22.01

**Comment by jimharris** [comment] 2022-07-18 18:15
Hi @songyangeric,

This is intended.  spdk_nvme_probe with NULL trio will attempt to probe (and attach) any NVMe devices that are not currently attached.  If there are no such devices, spdk_nvme_probe will just return immediately.

But if you pass a trid to spdk_nvme_probe, and the device is already attached, it will generate the errors as indicated in your report.

The hotplug test could be modified to specify a trid, but it would need to wait to call spdk_nvme_probe until after it detected that the device was removed.

Closing this issue since this is intended behavior, but please post additional questions here if you have any.

-Jim

**Closed by jimharris** 2022-07-18 18:15 UTC
Labels: Sighting

**Comment by songyangeric** [comment] 2022-07-19 07:08
Hi, @jimharris 
      Thanks for your reply.  I do have a question about hot remove. In our implementation, we bind each nvme device to an independent process and thereby a specific trid is paased to spdk_nvme_probe for each process. We are now testing single device failure by hot removing one device at a time.  By running hotplug example, we find that process still runs when device is hot removed. Either timeout or explicit spdk_nvme_probe call triggers device rescan to re-add device so as to continue hanged IO. What we want is when device gets removed, the process exits immediately or at least prints a fatal error so that we can detect such failure by some monitoring tools. Are there any possible solutions to detect a device gets removed while process is still running? An io hanged running process is not we want actually.
       Hope for your reply.

**Comment by jimharris** [comment] 2022-07-19 17:27
Hi @songyangeric,

The hotplug example is meant to show how hotplug works with SPDK, and to provide a means to do hotplug testing in CI.  I am not sure this example is well suited for your use case.

I would be fine with a command-line option for the hotplug example that causes a process exit (with error) if all devices get removed, but am not sure if that is what you are looking for here.

The typical way to get notification that an NVMe SSD has been removed is to do an spdk_nvme_probe() with the remove_cb specified.  This is how the hotplug example gets notifications of removed SSDs.

-Jim
