### ISSUE TITLE
Repeatable Defect: blk_update_request: I/O errors; lost async page write; nvme0: reconnecting in 10 seconds

### ISSUE THREAD

**Issue by matthew-hannon** [spdk/spdk#88] opened 2016-12-16 16:19 UTC
Hello,

We have been experimenting with SPDK and the Linux based kernel initiator. We have ran into a repeatable issue regarding the usage of non-direct I/O directly to a NVMeF block device. We also ran into similar issues when using a file system with direct I/O turned off. In any case lets focus on the case of I/Os to a raw block device as it seems easier to replicate the bug.

I have been unable to diagnose the root cause of the problem to fix it so I am posting here to hopefully get some help.

To replicate:
1) Get latest SPDK/DPDK sources and compile on target node with NVMe drives (note: we have two separate RNICs on the target, but have configured the SPDK configuration file to place the NVMe drives on the correct root complex for each RNIC - it is a two socket system... I don't think the RNICs are the issue just wanted to point that detail out in our configuration). Also we are using IB as the transport with Mellanox Connect-IB cards.

2) Do discovery and connect via the regular 'nvme' open source initiator package. Note: no file system involved at all with this test.

3) The following FIO command _**_does not_**_ cause the bug: 

fio --rw=randwrite --bs=128k --numjobs=1 --iodepth=256 --loops=1 --ioengine=libaio --direct=1 --invalidate=1 --fsync_on_close=1 --randrepeat=1 --norandommap --exitall --name test --filename=/dev/nvme0n1 --output=blah --time_based --runtime=60 --group_reporting --size=30G

4) The following FIO command **does** cause the bug:

fio --rw=randwrite --bs=128k --numjobs=1 --iodepth=256 --loops=1 --ioengine=libaio --direct=0 --invalidate=1 --fsync_on_close=1 --randrepeat=1 --norandommap --exitall --name test --filename=/dev/nvme0n1 --output=blah --time_based --runtime=60 --group_reporting --size=30G

Note: the only difference in the two commands is the --direct flag change.

5) If you run FIO command from step 4 you will see on the initiator in the dmesg things like the following:

[158052.975693] nvme nvme0: new ctrl: NQN "nqn.2014-08.org.nvmexpress.discovery", addr 192.168.4.74:4420
[158058.986892] nvme nvme0: creating 56 I/O queues.
[158061.990454] nvme nvme0: new ctrl: NQN "nqn.2016-06.io.spdk:cnode8", addr 192.168.4.74:4420
[158697.246241] blk_update_request: I/O error, dev nvme0n1, sector 207104
[158697.248259] Buffer I/O error on dev nvme0n1, logical block 25888, lost async page write
[158697.250775] Buffer I/O error on dev nvme0n1, logical block 25889, lost async page write
[158697.253274] Buffer I/O error on dev nvme0n1, logical block 25890, lost async page write
[158697.255779] Buffer I/O error on dev nvme0n1, logical block 25891, lost async page write

...

[158697.273322] blk_update_request: I/O error, dev nvme0n1, sector 207616
[158697.275357] blk_update_request: I/O error, dev nvme0n1, sector 208128
[158697.277395] blk_update_request: I/O error, dev nvme0n1, sector 208384
[158697.279431] blk_update_request: I/O error, dev nvme0n1, sector 209408
[158697.281473] blk_update_request: I/O error, dev nvme0n1, sector 209920

...

[158697.473874] nvme nvme0: reconnecting in 10 seconds
[158709.884153] nvme nvme0: Successfully reconnected
[158727.572304] blk_update_request: 29 callbacks suppressed
[158727.572311] blk_update_request: I/O error, dev nvme0n1, sector 228352
[158727.572388] nvme nvme0: reconnecting in 10 seconds
[158727.614845] buffer_io_error: 1238 callbacks suppressed
[158727.614849] Buffer I/O error on dev nvme0n1, logical block 28544, lost async page write
[158727.698281] Buffer I/O error on dev nvme0n1, logical block 28545, lost async page write

...

[158738.976347] nvme nvme0: Successfully reconnected

Please let me know if you require more information about how we have setup the SPDK configuration file as well as any other details related to our setup if you have issues replicating this bug.

Appreciate any help/advice you all can offer.

Thanks.
-Matt

**Comment by optimistyzy** [comment] 2016-12-19 04:06
Have you tried this test for kernel nvmf target?  When you use kernel nvmf target, is there similar issue?  Thanks.

**Comment by benlwalker** [comment] 2016-12-19 15:02
Matt - thank you for the detailed bug report. I was able to reproduce the problem on Friday. It does not occur with the kernel target. The problem happens after the fio run has completed when fio does a sync on the file descriptor. Some number of I/O hangs at that point. The SPDK target correctly has the I/O in its pending list, so it isn't lost, but it never completes. I will continue to investigate today.

**Comment by dverkamp-intel** [comment] 2017-03-17 23:21
I believe this should be resolved with the latest changes to the NVMe-oF target, especially commit 1db3a037121c1be44db858cb4174ea020f7b9b74.

Can you re-run your tests with the latest master and see if the bug still reproduces?

**Comment by l15k4** [comment] 2017-06-14 15:23
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1668129

**Comment by benlwalker** [comment] 2018-01-23 18:00
We believe this is fixed in SPDK 17.03 due to the commit above. The RDMA layer was rewritten to handle a corner case where RECV and SEND can be reordered. Please reopen if you are still experiencing an issue.

**Closed by benlwalker** 2018-01-23 18:00 UTC
Labels: bug
