### ISSUE TITLE
discovery controller should hande keep alive command (SPDK_NVME_OPC_KEEP_ALIVE)

### ISSUE THREAD

**Issue by eyuval** [spdk/spdk#1109] opened 2019-12-12 11:51 UTC
The discovery controller uses a fixed timeout and starts the keep alive timer in function spdk_nvmf_ctrlr_create. However, I see that the discovery controller does not handle keep alive command from the host. This results in keep alive timeout after 2minutes and disconnect, because the last_keep_alive_tick parameter is never update. I am using the nvme dem application. It opens a permanent connection to the discovery controller and then periodically sends keep alive to check whether the target is alive.
I think if the keep alive timer is started for the discovery controller it should also handle keep alive commands

**Comment by Comphix** [comment] 2019-12-13 07:31
@glodfish-zg , please take a look. Thanks.

**Comment by bharatpotnuri** [comment] 2019-12-13 08:41
#1089

**Comment by bharatpotnuri** [comment] 2019-12-13 08:43
#1089

**Comment by glodfish-zg** [comment] 2019-12-16 02:42
@eyuval. Sorry for the late response. Yes, you are right. We will fix this.

**Comment by shuhei-matsumoto** [comment] 2019-12-16 02:52
Hi @eyuval @glodfish-zg 

As @bharatpotnuri added reference, this issue is duplicated with #1089. We can close this and move to #1089.

I've got unit test failure to the patch to fix the issue.
If fixing the issue is the way to go for us, I will investigate and fix the unit test failure.

-Shuhei

**Comment by glodfish-zg** [comment] 2019-12-16 05:20
Here is the patch: https://review.gerrithub.io/c/spdk/spdk/+/478016. Thanks.

**Comment by tomzawadzki** [comment] 2019-12-17 13:12
This is duplicate of #1089.

@eyuval Fix is currently in review please see if this addresses what you see and let everyone know in #1089.

**Closed by tomzawadzki** 2019-12-17 13:12 UTC
