### ISSUE TITLE
[spdk_nvme_cli_plugin] nvme-cli's output differs between kernel/plugin

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#3146] opened 2023-10-06 10:42 UTC
The output looks the same, but seems like it was reordered.
```
00:09:36.983  --- /dev/fd/62	2023-10-06 10:34:18.052302634 +0200
00:09:36.983  +++ /dev/fd/61	2023-10-06 10:34:18.052302634 +0200
00:09:36.983  @@ -1,29 +1,58 @@
00:09:36.983   Node                  Generic               SN                   Model                                    Namespace  Usage                      Format           FW Rev  
00:09:36.983   --------------------- --------------------- -------------------- ---------------------------------------- ---------- -------------------------- ---------------- --------
00:09:36.983  +nvme0n1     nvme0n1     BTLJ913602XE1P0FGN   INTEL SSDPE2KX010T8                      0x1          1.00  TB /   1.00  TB    512   B +  0 B   VDV10184
00:09:36.983   nvme1n2          nvme1n2            21113Q900059         WZS4C8T1TDSP303                          0x2          0.00   B / 242.67  GB    512   B +  0 B   R6Z10009
00:09:36.983   nvme1n1          nvme1n1            21113Q900059         WZS4C8T1TDSP303                          0x1          1.05  MB /   2.15  GB    512   B +  0 B   R6Z10009
00:09:36.983  -nvme0n1          nvme0n1            BTLJ913602XE1P0FGN   INTEL SSDPE2KX010T8                      0x1          1.00  TB /   1.00  TB    512   B +  0 B   VDV10184
00:09:36.983   Subsystem        Subsystem-NQN                                                                                    Controllers
00:09:36.983   ---------------- ------------------------------------------------------------------------------------------------ ----------------
00:09:36.983  -nvme1     nvme1
00:09:36.983   nvme0     nvme0
00:09:36.983  +nvme1     nvme1
00:09:36.983   
00:09:36.983   Device   SN                   MN                                       FR       TxPort Address        Subsystem    Namespaces      
00:09:36.983   -------- -------------------- ---------------------------------------- -------- ------ -------------- ------------ ----------------
00:09:36.983  -nvme1    21113Q900059         WZS4C8T1TDSP303                          R6Z10009 pcie   0000:5f:00.0   nvme1 nvme1n2, nvme1n1
00:09:36.983   nvme0    BTLJ913602XE1P0FGN   INTEL SSDPE2KX010T8                      VDV10184 pcie   0000:5e:00.0   nvme0 nvme0n1
00:09:36.983  +nvme1    21113Q900059         WZS4C8T1TDSP303                          R6Z10009 pcie   0000:5f:00.0   nvme1 nvme1n2, nvme1n1
00:09:36.983   
00:09:36.983   Device       Generic      NSID       Usage                      Format           Controllers     
00:09:36.983   ------------ ------------ ---------- -------------------------- ---------------- ----------------
00:09:36.983  +nvme0n1 nvme0n1 0x1          1.00  TB /   1.00  TB    512   B +  0 B   nvme0
00:09:36.983   nvme1n2 nvme1n2   0x2          0.00   B / 242.67  GB    512   B +  0 B   nvme1
00:09:36.983   nvme1n1 nvme1n1   0x1          1.05  MB /   2.15  GB    512   B +  0 B   nvme1
00:09:36.983  -nvme0n1 nvme0n1   0x1          1.00  TB /   1.00  TB    512   B +  0 B   nvme0
00:09:36.983   {
00:09:36.983     "Devices":[
00:09:36.983       {
00:09:36.983         "HostNQN":"nqn.2014-08.org.nvmexpress:uuid:80b98b40-9a1d-eb11-906e-0017a4403562",
00:09:36.983         "Subsystems":[
00:09:36.983           {
00:09:36.983  +          "Subsystem":"nvme0",
00:09:36.983  +          
00:09:36.983  +          "Controllers":[
00:09:36.983  +            {
00:09:36.983  +              "Controller":"nvme0",
00:09:36.983  +              "SerialNumber":"BTLJ913602XE1P0FGN",
00:09:36.983  +              "ModelNumber":"INTEL SSDPE2KX010T8",
00:09:36.983  +              "Firmware":"VDV10184",
00:09:36.983  +              "Transport":"pcie",
00:09:36.983  +              "Address":"0000:5e:00.0",
00:09:36.983  +              "Namespaces":[
00:09:36.983  +                {
00:09:36.983  +                  "NameSpace":"nvme0n1",
00:09:36.983  +                  "Generic":"nvme0n1",
00:09:36.983  +                  "NSID":1,
00:09:36.983  +                  "UsedBytes":1000204886016,
00:09:36.983  +                  "MaximumLBA":1953525168,
00:09:36.983  +                  "PhysicalSize":1000204886016,
00:09:36.983  +                  "SectorSize":512
00:09:36.983  +                }
00:09:36.983  +              ],
00:09:36.983  +              "Paths":[
00:09:36.983  +              ]
00:09:36.983  +            }
00:09:36.983  +          ],
00:09:36.983  +          "Namespaces":[
00:09:36.983  +          ]
00:09:36.983  +        },
00:09:36.983  +        {
00:09:36.983             "Subsystem":"nvme1",
00:09:36.983             
00:09:36.983             "Controllers":[
00:09:36.983  @@ -60,43 +89,14 @@
00:09:36.983             ],
00:09:36.983             "Namespaces":[
00:09:36.983             ]
00:09:36.983  -        },
00:09:36.983  -        {
00:09:36.983  -          "Subsystem":"nvme0",
00:09:36.983  -          
00:09:36.983  -          "Controllers":[
00:09:36.983  -            {
00:09:36.983  -              "Controller":"nvme0",
00:09:36.984  -              "SerialNumber":"BTLJ913602XE1P0FGN",
00:09:36.984  -              "ModelNumber":"INTEL SSDPE2KX010T8",
00:09:36.984  -              "Firmware":"VDV10184",
00:09:36.984  -              "Transport":"pcie",
00:09:36.984  -              "Address":"0000:5e:00.0",
00:09:36.984  -              "Namespaces":[
00:09:36.984  -                {
00:09:36.984  -                  "NameSpace":"nvme0n1",
00:09:36.984  -                  "Generic":"nvme0n1",
00:09:36.984  -                  "NSID":1,
00:09:36.984  -                  "UsedBytes":1000204886016,
00:09:36.984  -                  "MaximumLBA":1953525168,
00:09:36.984  -                  "PhysicalSize":1000204886016,
00:09:36.984  -                  "SectorSize":512
00:09:36.984  -                }
00:09:36.984  -              ],
00:09:36.984  -              "Paths":[
00:09:36.984  -              ]
00:09:36.984  -            }
00:09:36.984  -          ],
00:09:36.984  -          "Namespaces":[
00:09:36.984  -          ]
00:09:36.984           }
00:09:36.984         ]
00:09:36.984       }
00:09:36.984     ]
00:09:36.984   }
00:09:36.984  -nvme1 - 
00:09:36.984  -\
00:09:36.984  - +- nvme1 pcie 0000:5f:00.0 live
00:09:36.984   nvme0 - 
00:09:36.984   \
00:09:36.984    +- nvme0 pcie 0000:5e:00.0 live
00:09:36.984  +nvme1 - 
00:09:36.984  +\
00:09:36.984  + +- nvme1 pcie 0000:5f:00.0 live
00:09:36.984    10:34:18	-- cuse/spdk_nvme_cli_plugin.sh@64 -- # trap - ERR
00:09:36.984    10:34:18	-- cuse/spdk_nvme_cli_plugin.sh@64 -- # print_backtrace
00:09:36.984    10:34:18	-- common/autotest_common.sh@1106 -- # [[ ehxBET =~ e ]]
00:09:36.984    10:34:18	-- common/autotest_common.sh@1108 -- # args=()
00:09:36.984    10:34:18	-- common/autotest_common.sh@1108 -- # local args
00:09:36.984    10:34:18	-- common/autotest_common.sh@1110 -- # xtrace_disable
00:09:36.984    10:34:18	-- common/autotest_common.sh@10 -- # set +x
00:09:36.984  ========== Backtrace start: ==========
00:09:36.984  
00:09:36.984  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/nvme/cuse/spdk_nvme_cli_plugin.sh:64 -> main([])
00:09:36.984       ...
00:09:36.984     59  	cuse_out[3]=$(nvme spdk list-subsys)
00:09:36.984     60  	
00:09:36.984     61  	# plugin does not support json output for the list-subsys
00:09:36.984     62  	[[ $(nvme spdk list-subsys -v -o json 2>&1) == "Json output format is not supported." ]]
00:09:36.984     63  	
00:09:36.984  => 64  	diff -ub \
00:09:36.984     65  		<(printf '%s\n' "${kernel_out[@]}") \
00:09:36.984     66  		<(printf '%s\n' "${cuse_out[@]}")
```

## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/110775/archive/nvme-phy-autotest_53424/build.log
https://ci.spdk.io/public_build/autotest-per-patch_110775.html

**Comment by spdkci** [comment] 2023-10-06 10:43
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_110775.html

**Comment by mikeBashStuff** [comment] 2023-10-06 10:50
Will take a look since this seems to relate to a particular nvme setup present under the affected node.

**Comment by mikeBashStuff** [comment] 2023-10-06 11:08
No immediate reproduction on the same node so I feel flakiness in the air (probably some sysfs wonkiness when the nvmes are being rebound between the kernel and us). Need to investigate.

**Comment by tomzawadzki** [comment] 2023-10-17 15:42
[Bug scrub] Besides looking into why the order changed (for curiosity ;)), @mikeBashStuff will take a look at sorting the compared data as this is not the crucial part of the test.

**Comment by spdkci** [comment] 2023-11-09 13:56
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_112204.html

**Comment by mikeBashStuff** [comment] 2023-11-09 14:00
Patch got merged, closing (last report comes from a series which were not rebased recently).

**Closed by mikeBashStuff** 2023-11-09 14:00 UTC
Labels: Intermittent Failure
