### ISSUE TITLE
[vhost_boot] Error: You requested a partition from 5368MB to 21.0GB (sectors 10483712..40959999).

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#3093] opened 2023-08-03 11:26 UTC
# CI Intermittent Failure

00:06:17.722    10:44:51	-- vhost/common.sh@311 -- # cat /root/vhost_test/vms/0/ssh_socket
00:06:17.722   10:44:51	-- vhost/common.sh@330 -- # sshpass -p root ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o User=root -p 10000 127.0.0.1 'parted -s /dev/sda mkpart primary 10483712s 100%; sleep 1; partprobe'
00:06:17.980  Warning: Permanently added '[127.0.0.1]:10000' (ED25519) to the list of known hosts.
00:06:17.980  Warning: Not all of the space available to /dev/sda appears to be used, you can fix the GPT to use all of the space (an extra 30474240 blocks) or continue with the current setting? 
00:06:17.980  Error: You requested a partition from 5368MB to 21.0GB (sectors 10483712..40959999).
00:06:17.980  The closest location we can manage is 5368MB to 5369MB (sectors 10483712..10485726).
00:06:19.357  Warning: Not all of the space available to /dev/sda appears to be used, you can fix the GPT to use all of the space (an extra 30474240 blocks) or continue with the current setting? 
00:06:19.357   10:44:52	-- vhost_boot/vhost_boot.sh@121 -- # vm_exec 0 'mkfs.ext4 -F /dev/sda2; mkdir -p /mnt/sda2test; mount /dev/sda2 /mnt/sda2test;'
00:06:19.357   10:44:52	-- vhost/common.sh@325 -- # vm_num_is_valid 0
00:06:19.357   10:44:52	-- vhost/common.sh@298 -- # [[ 0 =~ ^[0-9]+$ ]]
00:06:19.357   10:44:52	-- vhost/common.sh@298 -- # return 0
00:06:19.357   10:44:52	-- vhost/common.sh@327 -- # local vm_num=0
00:06:19.357   10:44:52	-- vhost/common.sh@328 -- # shift
00:06:19.357    10:44:52	-- vhost/common.sh@330 -- # vm_ssh_socket 0
00:06:19.357    10:44:52	-- vhost/common.sh@308 -- # vm_num_is_valid 0
00:06:19.357    10:44:52	-- vhost/common.sh@298 -- # [[ 0 =~ ^[0-9]+$ ]]
00:06:19.357    10:44:52	-- vhost/common.sh@298 -- # return 0
00:06:19.357    10:44:52	-- vhost/common.sh@309 -- # local vm_dir=/root/vhost_test/vms/0
00:06:19.357    10:44:52	-- vhost/common.sh@311 -- # cat /root/vhost_test/vms/0/ssh_socket
00:06:19.357   10:44:52	-- vhost/common.sh@330 -- # sshpass -p root ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o User=root -p 10000 127.0.0.1 'mkfs.ext4 -F /dev/sda2; mkdir -p /mnt/sda2test; mount /dev/sda2 /mnt/sda2test;'
00:06:19.357  Warning: Permanently added '[127.0.0.1]:10000' (ED25519) to the list of known hosts.
00:06:19.357  mke2fs 1.46.5 (30-Dec-2021)
00:06:19.357  /dev/sda2 is mounted; will not make a filesystem here!
00:06:19.357   10:44:52	-- vhost_boot/vhost_boot.sh@122 -- # vm_exec 0 'fio --name=integrity --bsrange=4k-512k --iodepth=128 --numjobs=1 --direct=1  --thread=1 --group_reporting=1 --rw=randrw --rwmixread=70 --filename=/mnt/sda2test/test_file  --verify=md5 --do_verify=1 --verify_backlog=1024 --fsync_on_close=1 --runtime=20  --time_based=1 --size=1024m --verify_state_save=0'
00:06:19.357   10:44:52	-- vhost/common.sh@325 -- # vm_num_is_valid 0
00:06:19.357   10:44:52	-- vhost/common.sh@298 -- # [[ 0 =~ ^[0-9]+$ ]]
00:06:19.357   10:44:52	-- vhost/common.sh@298 -- # return 0
00:06:19.357   10:44:52	-- vhost/common.sh@327 -- # local vm_num=0
00:06:19.357   10:44:52	-- vhost/common.sh@328 -- # shift
00:06:19.357    10:44:52	-- vhost/common.sh@330 -- # vm_ssh_socket 0
00:06:19.357    10:44:52	-- vhost/common.sh@308 -- # vm_num_is_valid 0
00:06:19.357    10:44:52	-- vhost/common.sh@298 -- # [[ 0 =~ ^[0-9]+$ ]]
00:06:19.357    10:44:52	-- vhost/common.sh@298 -- # return 0
00:06:19.357    10:44:52	-- vhost/common.sh@309 -- # local vm_dir=/root/vhost_test/vms/0
00:06:19.357    10:44:52	-- vhost/common.sh@311 -- # cat /root/vhost_test/vms/0/ssh_socket
00:06:19.357   10:44:52	-- vhost/common.sh@330 -- # sshpass -p root ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o User=root -p 10000 127.0.0.1 'fio --name=integrity --bsrange=4k-512k --iodepth=128 --numjobs=1 --direct=1  --thread=1 --group_reporting=1 --rw=randrw --rwmixread=70 --filename=/mnt/sda2test/test_file  --verify=md5 --do_verify=1 --verify_backlog=1024 --fsync_on_close=1 --runtime=20  --time_based=1 --size=1024m --verify_state_save=0'
00:06:19.357  Warning: Permanently added '[127.0.0.1]:10000' (ED25519) to the list of known hosts.
00:06:19.357  integrity: (g=0): rw=randrw, bs=(R) 4096B-512KiB, (W) 4096B-512KiB, (T) 4096B-512KiB, ioengine=psync, iodepth=128
00:06:19.357  fio-3.28
00:06:19.357  Starting 1 thread
00:06:19.357  integrity: Laying out IO file (1 file / 1024MiB)
00:06:19.925  fio: ENOSPC on laying out file, stopping
00:06:19.925  fio: pid=0, err=28/file:filesetup.c:240, func=write, error=No space left on device
00:06:19.925  
00:06:19.925  
00:06:19.925  Run status group 0 (all jobs):
00:06:19.925    10:44:53	-- vhost/common.sh@330 -- # err_clean vm_exec 330
00:06:19.925    10:44:53	-- vhost_boot/vhost_boot.sh@18 -- # trap - ERR
00:06:19.925    10:44:53	-- vhost_boot/vhost_boot.sh@19 -- # print_backtrace
00:06:19.925    10:44:53	-- common/autotest_common.sh@1125 -- # [[ ehxBET =~ e ]]
00:06:19.925    10:44:53	-- common/autotest_common.sh@1127 -- # args=('330' 'vm_exec' 'fio --name=integrity --bsrange=4k-512k --iodepth=128 --numjobs=1 --direct=1  --thread=1 --group_reporting=1 --rw=randrw --rwmixread=70 --filename=/mnt/sda2test/test_file  --verify=md5 --do_verify=1 --verify_backlog=1024 --fsync_on_close=1 --runtime=20  --time_based=1 --size=1024m --verify_state_save=0' '0' '--vm_image=/var/spdk/dependencies/vhost/spdk_test_image.qcow2')
00:06:19.925    10:44:53	-- common/autotest_common.sh@1127 -- # local args
00:06:19.925    10:44:53	-- common/autotest_common.sh@1129 -- # xtrace_disable
00:06:19.925    10:44:53	-- common/autotest_common.sh@20 -- # '[' no '!=' yes ']'
00:06:19.925    10:44:53	-- common/autotest_common.sh@21 -- # PREV_BASH_OPTS=ehxBET
00:06:19.925    10:44:53	-- common/autotest_common.sh@22 -- # [[ ehxBET == *\x* ]]
00:06:19.925    10:44:53	-- common/autotest_common.sh@23 -- # XTRACE_DISABLED=yes
00:06:19.925    10:44:53	-- common/autotest_common.sh@25 -- # set +x

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_107574.html

## Execution failed at

00:06:19.925  ========== Backtrace start: ==========
00:06:19.925  
00:06:19.925  in /var/jenkins/workspace/vhost-phy-autotest/spdk/test/vhost/vhost_boot/vhost_boot.sh:330 -> err_clean(["vm_exec"],["330"])
00:06:19.925       ...
00:06:19.925  backtrace unavailable
00:06:19.925       ...
00:06:19.925  in /var/jenkins/workspace/vhost-phy-autotest/spdk/test/vhost/common.sh:330 -> vm_exec(["0"],["fio --name=integrity --bsrange=4k-512k --iodepth=128 --numjobs=1 --direct=1  --thread=1 --group_reporting=1 --rw=randrw --rwmixread=70 --filename=/mnt/sda2test/test_file  --verify=md5 --do_verify=1 --verify_backlog=1024 --fsync_on_close=1 --runtime=20  --time_based=1 --size=1024m --verify_state_save=0"])
00:06:19.925       ...
00:06:19.925     325 		vm_num_is_valid $1 || return 1
00:06:19.925     326 	
00:06:19.925     327 		local vm_num="$1"
00:06:19.925     328 		shift
00:06:19.925     329 	
00:06:19.925  => 330 		sshpass -p "$VM_PASSWORD" ssh \
00:06:19.925     331 			-o UserKnownHostsFile=/dev/null \
00:06:19.925     332 			-o StrictHostKeyChecking=no \
00:06:19.925     333 			-o User=root \
00:06:19.925     334 			-p $(vm_ssh_socket $vm_num) $VM_SSH_OPTIONS 127.0.0.1 \
00:06:19.925     335 			"$@"
00:06:19.925       ...
00:06:19.925  in /var/jenkins/workspace/vhost-phy-autotest/spdk/test/vhost/vhost_boot/vhost_boot.sh:122 -> main(["--vm_image=/var/spdk/dependencies/vhost/spdk_test_image.qcow2"])
00:06:19.925       ...
00:06:19.925     117 	((start_part_sector > 0)) && (((drive_size * 512) >> 20 == lvb_size))
00:06:19.925     118 	
00:06:19.925     119 	timing_enter run_vm_cmd
00:06:19.925     120 	vm_exec $vm_no "parted -s /dev/sda mkpart primary ${start_part_sector}s 100%; sleep 1; partprobe"
00:06:19.925     121 	vm_exec $vm_no "mkfs.ext4 -F /dev/sda2; mkdir -p /mnt/sda2test; mount /dev/sda2 /mnt/sda2test;"
00:06:19.925  => 122 	vm_exec $vm_no "fio --name=integrity --bsrange=4k-512k --iodepth=128 --numjobs=1 --direct=1 \
00:06:19.925     123 	 --thread=1 --group_reporting=1 --rw=randrw --rwmixread=70 --filename=/mnt/sda2test/test_file \
00:06:19.925     124 	 --verify=md5 --do_verify=1 --verify_backlog=1024 --fsync_on_close=1 --runtime=20 \
00:06:19.925     125 	 --time_based=1 --size=1024m --verify_state_save=0"
00:06:19.925     126 	vm_exec $vm_no "umount /mnt/sda2test; rm -rf /mnt/sda2test"
00:06:19.925     127 	alignment_offset=$(vm_exec $vm_no "cat /sys/block/sda/sda1/alignment_offset")
00:06:19.925       ...
00:06:19.925  
00:06:19.925  ========== Backtrace end ==========

**Comment by spdkci** [comment] 2023-08-03 11:27
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_107574.html

**Comment by mikeBashStuff** [comment] 2023-08-03 11:39
@shuhei-matsumoto Please, make sure your patches are rebased on top of the master and include the 5f6519d1ef patch.  Closing as this is a duplicate of https://github.com/spdk/spdk/issues/3087.

**Closed by mikeBashStuff** 2023-08-03 11:39 UTC
Labels: Intermittent Failure
