### ISSUE TITLE
iscsi_tgt: hotplug causes bdev_io leaks

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#248] opened 2018-02-28 07:14 UTC
Mem pool related error message will be printed while running test/iscsi_tgt/fio/fio.sh. 
The error message is as below:
# steps to reproduce this issue:
run spdk/test/iscsi_tgt/fio/fio.sh.

Error log:
 07:17:18	# rm -f /home/sys_sgsw/build_pool/agent/repo/test/iscsi_tgt/fio/iscsi.conf
 07:17:18	# killprocess 2674
 07:17:18	# '[' -z 2674 ']'
 07:17:18	# echo 'killing process with pid 2674'
killing process with pid 2674
 07:17:18	# kill 2674
 07:17:18	# wait 2674
**bdev.c: 620:spdk_bdev_module_finish_complete: *ERROR*: bdev IO pool count is 65515 but should be 65536**
 07:17:18	# /home/sys_sgsw/build_pool/agent/repo/scripts/setup.sh
 07:17:18	# timing_exit fio
 07:17:18	# set +x

**Comment by Comphix** [comment] 2018-02-28 07:28
What's the content for the iscsi.conf ?

**Comment by dverkamp-intel** [comment] 2018-03-02 00:09
This reproduces all the time in the test pool as well.  For example: https://ci.spdk.io/spdk/builds/release/master/4441/fedora-02/build.log

**Comment by jimharris** [comment] 2018-03-02 00:30
Yeah – this is all related to iSCSI hotplug.  There are some patches out to work towards getting this fixed, but it will be a non-trivial effort.

More details can be found here: https://trello.com/c/MCqjqMKX

**Comment by WenqianZong** [comment] 2018-04-19 01:40
I can't reproduce "*ERROR*: bdev IO pool count is 65515 but should be 65536" issue with latest SPDK version.

**Comment by wanqunintel** [comment] 2018-05-23 06:31
Is there any patch for it?

**Comment by optimistyzy** [comment] 2018-05-23 07:46
@wanqunintel  No useful patch can be provided yet. Currently hotplug test is disabled, I think that that there will be great efforts to reenable it. At least in a long time (at least 1 month), there will not have a very solid methods to solve this issue.

**Comment by shuhei-matsumoto** [comment] 2018-05-31 05:16
@optimistyzy  @jimharris @darsto 

This issue is covered in the today's bug scrub meeting. I think there are some gap about the policy of iscsi hot plug as in https://review.gerrithub.io/#/c/spdk/spdk/+/394699/ and https://trello.com/c/MCqjqMKX/8-proper-iscsi-hotplug.

Ziye's patch may be the shortest route to re-enable iscsi hotplug. But we may have to get consensus in the policy first.

Do you have any thought?

**Comment by optimistyzy** [comment] 2018-05-31 05:47
In my opinion, we can enable those patches and iteratively improve it. If
we want to solve it with a very perfect solution, I have concerns that
there are still lots of corner cases which may not be considered.

2018-05-31 13:16 GMT+08:00 shuhei-matsumoto <notifications@github.com>:

**Comment by shuhei-matsumoto** [comment] 2018-05-31 10:29
Your patch had got plus from Darek and I agree with your thought. I might give wrong feedback last week, sorry for that.

**Comment by shuhei-matsumoto** [comment] 2018-06-07 02:20
I also started to work on this issue from learning Ziye's patch.

**Comment by shuhei-matsumoto** [comment] 2018-06-13 07:13
Now the behavior is slightly different from before and looks closer to the root cause.

https://ci.spdk.io/spdk/builds/review/b037121971c6945414f7af5df23823a45e144e9d.1528872177/

I think this is already past half a year and not urgent. Hence I'm refactoring the iscsi and scsi code and trying to find the root cause and create the solution.

I will update if I get progress.

**Comment by shuhei-matsumoto** [comment] 2018-06-29 04:16
I submitted patch series and re-enabled hot removal test.

Hot removal test has passed as expected.
https://review.gerrithub.io/#/c/spdk/spdk/+/417200/

I hope we can start review process.

**Comment by wanqunintel** [comment] 2018-07-03 05:31
@liang2yan , as you mentioned that we need to add test cases, would you check with shuhei to add which test case

**Comment by liang2yan** [comment] 2018-07-18 04:16
@shuhei-matsumoto , were your iscsi hot-removal enabling patches all merged? Do we plan to add some new test cases for hot-removal?

**Comment by shuhei-matsumoto** [comment] 2018-07-18 04:36
@liang2yan library code was merged and test code is under the review. Adding test cases will be better but I don't have any actual plan yet.

**Comment by shuhei-matsumoto** [comment] 2018-07-18 07:10
@liang2yan 
I'm thinking a test case such as adding multiple LUNs to a iSCSI target, make a connection to each LUN and run some workload on each of them, and then hot remove LUNs one by one. 
But I can't promise if I'm sure to do or when I can do yet.

**Comment by liang2yan** [comment] 2018-07-25 13:53
Verified with latest codes, no mem leak while finishing the iscsi target hot-removal testing.

**Comment by shuhei-matsumoto** [comment] 2018-07-26 01:58
@liang2yan Thank you. Please close the issue.

**Closed** 2018-07-26 02:10 UTC
Labels: bug
