### ISSUE TITLE
[app_repeat] could not allocate spdk_bdev_io_pool

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#3262] opened 2024-02-12 18:01 UTC
```
00:05:41.983  ************************************
00:05:41.983  START TEST app_repeat
00:05:41.983  ************************************
00:05:41.983   17:40:13	-- common/autotest_common.sh@1102 -- # app_repeat_test
00:05:41.983   17:40:13	-- event/event.sh@12 -- # local rpc_server=/var/tmp/spdk-nbd.sock
00:05:41.983   17:40:13	-- event/event.sh@13 -- # nbd_list=('/dev/nbd0' '/dev/nbd1')
00:05:41.983   17:40:13	-- event/event.sh@13 -- # local nbd_list
00:05:41.983   17:40:13	-- event/event.sh@14 -- # bdev_list=('Malloc0' 'Malloc1')
00:05:41.983   17:40:13	-- event/event.sh@14 -- # local bdev_list
00:05:41.983   17:40:13	-- event/event.sh@15 -- # local repeat_times=4
00:05:41.983   17:40:13	-- event/event.sh@17 -- # modprobe nbd
00:05:41.983   17:40:13	-- event/event.sh@19 -- # repeat_pid=1621003
00:05:41.983   17:40:13	-- event/event.sh@18 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/event/app_repeat/app_repeat -r /var/tmp/spdk-nbd.sock -m 0x3 -t 4
00:05:41.983   17:40:13	-- event/event.sh@20 -- # trap 'killprocess $repeat_pid; exit 1' SIGINT SIGTERM EXIT
00:05:41.983   17:40:13	-- event/event.sh@21 -- # echo 'Process app_repeat pid: 1621003'
00:05:41.983  Process app_repeat pid: 1621003
00:05:41.983   17:40:13	-- event/event.sh@23 -- # for i in {0..2}
00:05:41.983   17:40:13	-- event/event.sh@24 -- # echo 'spdk_app_start Round 0'
00:05:41.983  spdk_app_start Round 0
00:05:41.983   17:40:13	-- event/event.sh@25 -- # waitforlisten 1621003 /var/tmp/spdk-nbd.sock
00:05:41.983   17:40:13	-- common/autotest_common.sh@817 -- # '[' -z 1621003 ']'
00:05:41.983   17:40:13	-- common/autotest_common.sh@821 -- # local rpc_addr=/var/tmp/spdk-nbd.sock
00:05:41.983   17:40:13	-- common/autotest_common.sh@822 -- # local max_retries=100
00:05:41.983   17:40:13	-- common/autotest_common.sh@824 -- # echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk-nbd.sock...'
00:05:41.983  Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk-nbd.sock...
00:05:41.983   17:40:13	-- common/autotest_common.sh@826 -- # xtrace_disable
00:05:41.983   17:40:13	-- common/autotest_common.sh@10 -- # set +x
00:05:41.983  [2024-02-12 17:40:13.087289] Starting SPDK v24.05-pre git sha1 cd1df22ad / DPDK 23.11.0 initialization...
00:05:41.983  [2024-02-12 17:40:13.087387] [ DPDK EAL parameters: app_repeat --no-shconf -c 0x3 --huge-unlink --no-telemetry --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid1621003 ]
00:05:41.983  EAL: No free 2048 kB hugepages reported on node 0
00:05:42.241  [2024-02-12 17:40:13.152592] app.c: 796:spdk_app_start: *NOTICE*: Total cores available: 2
00:05:42.241  [2024-02-12 17:40:13.339173] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 1
00:05:42.241  [2024-02-12 17:40:13.339177] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 0
00:05:42.499  [2024-02-12 17:40:13.482169] bdev.c:2178:spdk_bdev_initialize: *ERROR*: could not allocate spdk_bdev_io pool
00:05:42.499  [2024-02-12 17:40:13.482240] subsystem.c: 148:spdk_subsystem_init_next: *ERROR*: Init subsystem bdev failed
00:05:42.499  [2024-02-12 17:40:13.482258] app.c: 908:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
00:05:42.758  Failed to call spdk_app_start in Round 0.
00:05:42.758  /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/common/autotest_common.sh: line 832: kill: (1621003) - No such process
00:05:42.758  ERROR: process (pid: 1621003) is no longer running
00:05:42.758   17:40:13	-- common/autotest_common.sh@846 -- # (( i == 0 ))
00:05:42.758   17:40:13	-- common/autotest_common.sh@850 -- # return 1
00:05:42.758    17:40:13	-- event/event.sh@25 -- # trap - ERR
00:05:42.758    17:40:13	-- event/event.sh@25 -- # print_backtrace
00:05:42.758    17:40:13	-- common/autotest_common.sh@1130 -- # [[ ehxBET =~ e ]]
00:05:42.758    17:40:13	-- common/autotest_common.sh@1132 -- # args=('app_repeat_test' 'app_repeat')
00:05:42.758    17:40:13	-- common/autotest_common.sh@1132 -- # local args
00:05:42.758    17:40:13	-- common/autotest_common.sh@1134 -- # xtrace_disable
00:05:42.758    17:40:13	-- common/autotest_common.sh@10 -- # set +x
00:05:42.758  ========== Backtrace start: ==========
00:05:42.758  
00:05:42.758  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/event/event.sh:25 -> app_repeat_test([])
00:05:42.758       ...
00:05:42.758     20  		trap 'killprocess $repeat_pid; exit 1' SIGINT SIGTERM EXIT
00:05:42.758     21  		echo "Process app_repeat pid: $repeat_pid"
00:05:42.758     22  	
00:05:42.758     23  		for i in {0..2}; do
00:05:42.758     24  			echo "spdk_app_start Round $i"
00:05:42.758  => 25  			waitforlisten $repeat_pid $rpc_server
00:05:42.758     26  	
00:05:42.758     27  			$rootdir/scripts/rpc.py -s $rpc_server bdev_malloc_create 64 4096
00:05:42.758     28  			$rootdir/scripts/rpc.py -s $rpc_server bdev_malloc_create 64 4096
00:05:42.758     29  	
00:05:42.758     30  			nbd_rpc_data_verify $rpc_server "${bdev_list[*]}" "${nbd_list[*]}"
```

**Comment by mikeBashStuff** [comment] 2024-02-12 18:07
```
00:05:41.983  EAL: No free 2048 kB hugepages reported on node 0
```

Well, this is unexpected.

**Comment by mikeBashStuff** [comment] 2024-02-12 18:44
So this:

```
 3  0      0 49500160   1308 9244496    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:11 50266448 7813712 2048 1838 2048 (test:event.event_scheduler.scheduler_create_thread)
 2  0      0 53155812   1308 9244368    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:12 53942660 7813744 243 210 2048 (test:event.event_scheduler.scheduler_create_thread)
 0  1      0 53756676   1308 9239520    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:13 54523048 7809548 0 0 2048 (test:event.app_repeat) # This is where the test fails - something took our hp away
 3  0      0 53778116   1308 9239540    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:14 54546264 7809568 0 0 2048 (test:event.app_repeat)
 1  0      0 51684972   1308 9239620    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:15 52450940 7809648 1024 1024 2048 (test:event.app_repeat)
 2  0      0 51687616   1308 9239716    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:17 52456496 7809744 1024 1024 2048 (test:event.app_repeat)
 3  0      0 51681428   1308 9239736    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:18 52443364 7809764 1024 1024 2048 (test:event.app_repeat)
 2  0      0 51706828   1308 9239716    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:19 52473304 7809856 1024 1024 2048 (test:event.app_repeat)
 3  0      0 51708028   1308 9240168    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:20 52473984 7809956 1025 1025 2048 (test:event.app_repeat) # this looks like hugepages.sh work (odd_alloc() in particular) - separate instance of autotest.sh is running in the background then
 1  0      0 50637540   1308 9239980    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:21 51403236 7810032 1536 1536 2048 (test:event.app_repeat)
 1  0      0 50608448   1308 9239980    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:22 51374360 7810064 1536 1536 2048 (test:event.app_repeat)
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu----- -----timestamp-----     ----extra memory----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st                 CET     avail shmem hp_total hp_free hp_size
 2  0      0 51562972   1308 9240068    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:23 52326420 7810152 1024 1024 2048 (test:event.app_repeat)
 3  0      0 53653148   1308 9239984    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:24 54418900 7810228 0 0 2048 (test:event.app_repeat)
```
and the fact that two java instances were running on that box ([here](https://ci.spdk.io/results/autotest-per-patch/builds/117159/archive/nvmf-phy-autotest_63671/proc_list.txt)) makes me think that "rouge" jenkins accidently fired separate set of tests on that node (or same node was added as two different nodes).  I am 90% sure that was the case since based on number of hp reported right before they are zeroed out, it looks like `hugepages` (from the `test-setup.sh` suite) tests were running at the same time `app_repeat` was.

I double checked the affected node (GP11) and everything looks fine now. Note that we are still in the process of moving phy nodes between the labs so I guess this may be somewhat related.

**Comment by jimharris** [comment] 2024-02-12 18:54
> So this:
> 
> ```
>  3  0      0 49500160   1308 9244496    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:11 50266448 7813712 2048 1838 2048 (test:event.event_scheduler.scheduler_create_thread)
>  2  0      0 53155812   1308 9244368    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:12 53942660 7813744 243 210 2048 (test:event.event_scheduler.scheduler_create_thread)
>  0  1      0 53756676   1308 9239520    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:13 54523048 7809548 0 0 2048 (test:event.app_repeat) # This is where the test fails - something took our hp away
>  3  0      0 53778116   1308 9239540    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:14 54546264 7809568 0 0 2048 (test:event.app_repeat)
>  1  0      0 51684972   1308 9239620    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:15 52450940 7809648 1024 1024 2048 (test:event.app_repeat)
>  2  0      0 51687616   1308 9239716    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:17 52456496 7809744 1024 1024 2048 (test:event.app_repeat)
>  3  0      0 51681428   1308 9239736    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:18 52443364 7809764 1024 1024 2048 (test:event.app_repeat)
>  2  0      0 51706828   1308 9239716    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:19 52473304 7809856 1024 1024 2048 (test:event.app_repeat)
>  3  0      0 51708028   1308 9240168    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:20 52473984 7809956 1025 1025 2048 (test:event.app_repeat) # this looks like hugepages.sh work (odd_alloc() in particular) - separate instance of autotest.sh is running in the background then
>  1  0      0 50637540   1308 9239980    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:21 51403236 7810032 1536 1536 2048 (test:event.app_repeat)
>  1  0      0 50608448   1308 9239980    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:22 51374360 7810064 1536 1536 2048 (test:event.app_repeat)
> procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu----- -----timestamp-----     ----extra memory----
>  r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st                 CET     avail shmem hp_total hp_free hp_size
>  2  0      0 51562972   1308 9240068    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:23 52326420 7810152 1024 1024 2048 (test:event.app_repeat)
>  3  0      0 53653148   1308 9239984    0    0     0     0    2    1  0  0 100  0  0 2024-02-12 17:40:24 54418900 7810228 0 0 2048 (test:event.app_repeat)
> ```
> 
> and the fact that two java instances were running on that box ([here](https://ci.spdk.io/results/autotest-per-patch/builds/117159/archive/nvmf-phy-autotest_63671/proc_list.txt)) makes me think that "rouge" (i.e. some testing instance) jenkins accidently fired separate set of tests on that node (or same node was added as two different nodes). I am 90% sure that was the case since based on number of hp reported right before they are zeroed out again, it looks like `hugepages` (from the `test-setup.sh` suite) tests were running at the same time `app_repeat` was.
> 
> I double checked the affected node (GP11) and everything looks fine now. Note that we are still in the process of moving phy nodes between the labs so I guess this may be somewhat related.

Thanks for the quick analysis on this @mikeBashStuff. I'll assign this one to you for now, feel free to close once you think this can be closed.

**Comment by mikeBashStuff** [comment] 2024-02-13 08:45
Issue was indeed caused by misconfiguration after the lab migration. This should be fixed now, so closing this issue - in case more patches got affected, please don't hesitate to reopen it.

**Closed by mikeBashStuff** 2024-02-13 08:45 UTC
Labels: Intermittent Failure
