### ISSUE TITLE
failure observed while using perf access target with 24 name-spaces

### ISSUE THREAD

**Issue by sunmingbao** [spdk/spdk#1444] opened 2020-06-17 16:03 UTC
## Current Behavior
failure observed while using perf access a NVMe_OF target with 24 name-spaces.
note: in case the perf and NVMe_OF target are on the same host, the failure has not been observed.

## Steps to Reproduce

1. Deploy MOFED 4.7 on host-A.
2. setup a NVMe_OF target with 24 name-spaces on host-A.
3. Reserve 30720MB huge_page (use 2MB pages) memory for the test on host-B.
4. issue the following command on host-B (perf is from SPDK v20.04.1.):
perf -q 256 -P 4 -s 4096 -w rw -t 10 -c 0xf -o 131072 -M 50 -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.219.1 trsvcid:4423'

following are the logs:
sandy-rust:/home/admin/NVMe_OF_test # ./perf -q 256 -P 4 -s 4096 -w rw -t 10 -c 0xf -o 131072 -M 50 -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.219.1 trsvcid:4423'
Starting SPDK v20.04.1 git sha1 c5f0959de / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0xf -m 4096 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid51766 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
Initializing NVMe Controllers
Attached to NVMe over Fabrics controller at 192.168.219.1:4423: testnqn_4
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 24 with lcore 3
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 23 with lcore 2
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 22 with lcore 1
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 21 with lcore 0
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 20 with lcore 3
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 19 with lcore 2
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 18 with lcore 1
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 17 with lcore 0
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 16 with lcore 3
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 15 with lcore 2
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 14 with lcore 1
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 13 with lcore 0
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 12 with lcore 3
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 11 with lcore 2
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 10 with lcore 1
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 9 with lcore 0
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 8 with lcore 3
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 7 with lcore 2
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 6 with lcore 1
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 5 with lcore 0
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 4 with lcore 3
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 3 with lcore 2
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 2 with lcore 1
Associating RDMA (addr:192.168.219.1 subnqn:testnqn_4) NSID 1 with lcore 0
Initialization complete. Launching workers.
nvme_qpair.c: 497:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
nvme_ctrlr.c: 768:nvme_ctrlr_fail: *ERROR*: ctrlr 192.168.219.1 in failed state.
nvme_fabric.c: 119:nvme_fabric_prop_get_cmd: *ERROR*: Property Get failed
nvme_ctrlr.c: 311:nvme_ctrlr_create_io_qpair: *ERROR*: get_cc failed
ERROR: spdk_nvme_ctrlr_alloc_io_qpair failed
ERROR: init_ns_worker_ctx() failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
Read completed with error (sct=0, sc=8)
starting I/O failed
Read completed with error (sct=0, sc=8)
starting I/O failed
Read completed with error (sct=0, sc=8)
starting I/O failed
Read completed with error (sct=0, sc=8)
starting I/O failed
nvme_qpair.c: 497:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
NVMe io qpair process completion error

## Context (Environment including OS version, SPDK version, etc.)
sandy-rust:/home/admin/NVMe_OF_test # cat /etc/os-release 
NAME="SLES"
VERSION="12-SP4"
VERSION_ID="12.4"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp4"
sandy-rust:/home/admin/NVMe_OF_test # uname -a
Linux sandy-rust.west.isilon.com 4.12.14-95.48-default #1 SMP Thu Feb 27 07:40:02 UTC 2020 (ddfe57a) x86_64 x86_64 x86_64 GNU/Linux
sandy-rust:/home/admin/NVMe_OF_test # ibv_devinfo 
hca_id:	mlx5_bond_0
	transport:			InfiniBand (0)
	fw_ver:				14.26.6000
	node_guid:			9803:9b03:0078:6666
	sys_image_guid:			9803:9b03:0078:6666
	vendor_id:			0x02c9
	vendor_part_id:			4117
	hw_ver:				0x0
	board_id:			DEL2810000034
	phys_port_cnt:			1
	Device ports:
		port:	1
			state:			PORT_ACTIVE (4)
			max_mtu:		4096 (5)
			active_mtu:		4096 (5)
			sm_lid:			0
			port_lid:		0
			port_lmc:		0x00
			link_layer:		Ethernet

**Comment by AlekseyMarchuk** [comment] 2020-06-17 19:06
I'll look at this issue

**Comment by sunmingbao** [comment] 2020-06-18 08:06
supplement kernel logs corresponding to this issue:
`[ 3306.089987] nvmet: creating controller 1 for subsystem nqn.2014-08.org.nvmexpress.discovery for NQN 2014-08.org.nvmexpress:uuid:6fdc9c06-aab7-4c4b-a130-e1d854cbaff8.
[ 3306.093235] nvmet: creating controller 2 for subsystem testnqn_4 for NQN 2014-08.org.nvmexpress:uuid:6fdc9c06-aab7-4c4b-a130-e1d854cbaff8.
[ 3306.542120] nvmet_rdma: SEND for CQE 0xffff9c60010291f0 failed with status transport retry counter exceeded (12).
[ 3306.542124] nvmet: ctrl 2 fatal error occurred!`

**Comment by sunmingbao** [comment] 2020-06-18 08:07
supplement kernel logs corresponding to this issue:
[ 3306.089987] nvmet: creating controller 1 for subsystem nqn.2014-08.org.nvmexpress.discovery for NQN 2014-08.org.nvmexpress:uuid:6fdc9c06-aab7-4c4b-a130-e1d854cbaff8.
[ 3306.093235] nvmet: creating controller 2 for subsystem testnqn_4 for NQN 2014-08.org.nvmexpress:uuid:6fdc9c06-aab7-4c4b-a130-e1d854cbaff8.
[ 3306.542120] nvmet_rdma: SEND for CQE 0xffff9c60010291f0 failed with status transport retry counter exceeded (12).
[ 3306.542124] nvmet: ctrl 2 fatal error occurred!

**Comment by AlekseyMarchuk** [comment] 2020-06-19 12:18
Hi @sunmingbao 

I was able to reproduce your problem with SPDK target. I think that the problem is related to a huge amount of work requests generated by SPDK perf. You used queue depth 256, 24 namespace and 4 qpairs per namespace, it results in 256 * 24 * 4  = 24 576‬ requests in flight (if we don't take into account requests splitting). That might produce a lot of RNR (receiver not ready) events but SPDK RDMA initiator is configured with infinity RNR retries, so it doesn't abort the connection due to RNRs. At the same time RNRs delay transmission of admin commands such as keep alive command and in my case I received " abort requests after transport retry counter exceeded" due to SPDK target destroyed controller by keep alive timeout. By default SPDK perf uses keep alive timeout 10 seconds. I would recommend you to increase this value to e.g. 30 seconds by adding `-k 30000` parameter to your perf arguments.
Could you also share your RDMA target configuration? I would try to reproduce this problem with similar config

**Comment by sunmingbao** [comment] 2020-06-23 06:45
@AlekseyMarchuk 
The RDMA target configuration has been uploaded.

[nvmet_cfg_provo-rust.txt](https://github.com/spdk/spdk/files/4817543/nvmet_cfg_provo-rust.txt)

**Comment by sunmingbao** [comment] 2020-06-23 08:51
@AlekseyMarchuk 
I have made some verification.
It seems "-k 30000" does not have an effect on this issue.
But reduce parameter value of -q and -P is helpful.

**Comment by AlekseyMarchuk** [comment] 2020-08-11 17:07
Hi @sunmingbao 

I tried to reproduce this issue with kernel target, but everything worked fine (I ran 10 iterations).
I don't have a system with 24 nvme disks, so I used 16 nvme disks and 8 ram disks. Here is how I started nvmet:
```
#!/bin/bash

ADDR="1.1.1.1"
PORT="4420"
PORT_ID="1"
NAME="nvmet_tgt"

modprobe nvmet-rdma

mkdir /sys/kernel/config/nvmet/subsystems/$NAME
echo 1 > /sys/kernel/config/nvmet/subsystems/$NAME/attr_allow_any_host

nsid=1

for ((nvme_id=0;nvme_id < 16; nvme_id++))
do
        nvme_name="/dev/nvme${nvme_id}n1"
        echo "Adding $nvme_name with nsid $nsid"
        mkdir /sys/kernel/config/nvmet/subsystems/$NAME/namespaces/$nsid
        echo -n $nvme_name > /sys/kernel/config/nvmet/subsystems/$NAME/namespaces/$nsid/device_path
        echo 1 > /sys/kernel/config/nvmet/subsystems/$NAME/namespaces/$nsid/enable
        nsid="$(($nsid + 1))"
done

modprobe brd rd_nr=8 rd_size=262144

for ((ram_id=0;ram_id < 8; ram_id++))
do
        ram_path="/dev/ram${ram_id}"

        echo "Adding $ram_path with nsid $nsid"
        mkdir /sys/kernel/config/nvmet/subsystems/$NAME/namespaces/$nsid
        echo -n $ram_path > /sys/kernel/config/nvmet/subsystems/$NAME/namespaces/$nsid/device_path
        echo 1 > /sys/kernel/config/nvmet/subsystems/$NAME/namespaces/$nsid/enable

        nsid="$(($nsid + 1))"

done

mkdir /sys/kernel/config/nvmet/ports/$PORT_ID
echo $PORT > /sys/kernel/config/nvmet/ports/$PORT_ID/addr_trsvcid
echo $ADDR > /sys/kernel/config/nvmet/ports/$PORT_ID/addr_traddr
echo "rdma" > /sys/kernel/config/nvmet/ports/$PORT_ID/addr_trtype
echo "ipv4" > /sys/kernel/config/nvmet/ports/$PORT_ID/addr_adrfam
ln -s /sys/kernel/config/nvmet/subsystems/$NAME/ /sys/kernel/config/nvmet/ports/$PORT_ID/subsystems/$NAME

```
perf output:
```
sudo ./install/bin/spdk_nvme_perf -q 256 -P 4 -s 4096 -w rw -t 10 -c 0xf -o 131072 -M 50 -r 'trtype:RDMA adrfam:IPv4 traddr:1.1.1.1 trsvcid:4420'
Starting SPDK v20.10-pre git sha1 809ab04 / DPDK 20.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0xf -m 4096 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --fi
le-prefix=spdk_pid295570 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
EAL: No legacy callbacks, legacy socket not created
Initializing NVMe Controllers
Attached to NVMe over Fabrics controller at 1.1.12.1:4420: nvmet_tgt
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 24 with lcore 3
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 23 with lcore 2
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 22 with lcore 1
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 21 with lcore 0
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 20 with lcore 3
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 19 with lcore 2
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 18 with lcore 1
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 17 with lcore 0
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 16 with lcore 3
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 15 with lcore 2
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 14 with lcore 1
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 13 with lcore 0
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 12 with lcore 3
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 11 with lcore 2
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 10 with lcore 1
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 9 with lcore 0
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 8 with lcore 3
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 7 with lcore 2
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 6 with lcore 1
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 5 with lcore 0
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 4 with lcore 3
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 3 with lcore 2
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 2 with lcore 1
Associating RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 1 with lcore 0
Initialization complete. Launching workers.
========================================================
                                                                                              Latency(us)
Device Information                                        :       IOPS      MiB/s    Average        min        max
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 4  from core  3:    1588.10     198.51  162556.10      99.87 4184328.49
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 8  from core  3:    2484.60     310.57  103307.88      98.65  399074.44
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 12 from core  3:    1614.80     201.85  158866.71     100.42 4071564.28
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 16 from core  3:    2450.70     306.34  104860.12      96.24  449837.35
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 20 from core  3:    2475.40     309.43  103666.71      62.29  510837.91
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 24 from core  3:    1902.60     237.82  134494.17      64.84 2949989.80
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 3  from core  2:    2512.20     314.02  102102.08      97.31  415195.69
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 7  from core  2:    2511.50     313.94  102451.17      96.65  450960.63
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 11 from core  2:    2496.80     312.10  103028.60     100.59  501382.99
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 15 from core  2:    2492.40     311.55  103082.49      99.30  354168.04
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 19 from core  2:    1571.90     196.49  162743.34      62.25 4202601.95
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 23 from core  2:    2495.40     311.93  102876.21      66.50  519762.76
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 2  from core  1:    1928.90     241.11  133612.38      97.21 2911308.25
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 6  from core  1:    1912.70     239.09  134329.80      99.30 3002960.35
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 10 from core  1:    2477.40     309.68  103780.40      96.64  625963.29
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 14 from core  1:    2490.80     311.35  103038.28      97.34  393128.83
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 18 from core  1:    2492.30     311.54  103160.00      64.01  580602.94
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 22 from core  1:    2532.90     316.61  101940.83      68.17  599719.69
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 1  from core  0:    2485.90     310.74  104202.91      96.35  618177.72
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 5  from core  0:    2491.30     311.41  103104.83      99.03  428892.44
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 9  from core  0:    2489.30     311.16  103514.83      98.95  542378.84
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 13 from core  0:    2451.90     306.49  104956.41      98.45  491194.73
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 17 from core  0:    2467.00     308.38  103871.32      74.78  333460.67
RDMA (addr:1.1.1.1 subnqn:nvmet_tgt) NSID 21 from core  0:    2477.30     309.66  103833.92      65.20  399823.87
========================================================
Total                                                     :   55294.10    6911.76  111575.90      62.25 4202601.95

```

Hosts info:
Initiator:
Intel(R) Xeon(R) Silver 4116 CPU @ 2.10GHz 48 cores (with hyper threading)
CentOS Linux release 7.5.1804 3.10.0-862.el7.x86_64
MLNX_OFED_LINUX-5.0-2.1.0.0
SPDK version: 99d3695c2
ibv_devinfo:
```
hca_id: mlx5_0
        transport:                      InfiniBand (0)
        fw_ver:                         18.28.0536
        node_guid:                      9803:9b03:0087:652a
        sys_image_guid:                 9803:9b03:0087:652a
        vendor_id:                      0x02c9
        vendor_part_id:                 41682
        hw_ver:                         0x0
        board_id:                       MSF0000000005
        phys_port_cnt:                  1
                port:   1
                        state:                  PORT_ACTIVE (4)
                        max_mtu:                4096 (5)
                        active_mtu:             1024 (3)
                        sm_lid:                 0
                        port_lid:               0
                        port_lmc:               0x00
                        link_layer:             Ethernet

```

Target:
Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz 48 cores (with hyper threading)
18.04.3 LTS (Bionic Beaver) 4.15.0-72-generic
MLNX_OFED_LINUX-4.7-1.0.0.1
ibv_devinfo:
```
hca_id: mlx5_2
        transport:                      InfiniBand (0)
        fw_ver:                         16.26.2000
        node_guid:                      b859:9f03:003e:a63e
        sys_image_guid:                 b859:9f03:003e:a63e
        vendor_id:                      0x02c9
        vendor_part_id:                 4119
        hw_ver:                         0x0
        board_id:                       MT_0000000008
        phys_port_cnt:                  1
        Device ports:
                port:   1
                        state:                  PORT_ACTIVE (4)
                        max_mtu:                4096 (5)
                        active_mtu:             1024 (3)
                        sm_lid:                 0
                        port_lid:               0
                        port_lmc:               0x00
                        link_layer:             Ethernet

```
modinfo nvmet-rdma: 
```
filename:       /lib/modules/4.15.0-72-generic/updates/dkms/nvmet-rdma.ko
alias:          nvmet-transport-1
license:        GPL v2
srcversion:     679E8D1F51A92873392F5EA
depends:        ib_core,nvme,mlx_compat,nvmet,rdma_cm
retpoline:      Y
name:           nvmet_rdma
vermagic:       4.15.0-72-generic SMP mod_unload
```

Will you have a chance to retest this scenario in another environment? E.g. use Ubuntu 18.04 as a target?

**Comment by jimharris** [comment] 2020-11-02 17:27
Closing this issue.  @sunmingbao if you are able to retest with instructions from @AlekseyMarchuk and still see issues, please reopen this issue with your results.

Thanks,

Jim

**Closed by jimharris** 2020-11-02 17:27 UTC
Labels: Low, Waiting on Submitter, bug
