### ISSUE TITLE
[nvmf_nvme_cli] missing libspdk_accel.so

### ISSUE THREAD

**Issue by jkalwas** [spdk/spdk#1483] opened 2020-07-08 13:23 UTC
Seems some dependency is missing on the CI image.

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/20803/archive/nvmf-phy-autotest/build.log

## Execution failed at

00:03:28.901   13:39:03	# ./nvme discover -t rdma -a 192.168.100.8 -s 4420
00:03:28.904  ./nvme: error while loading shared libraries: libspdk_accel.so.3.0: cannot open shared object file: No such file or directory

**Comment by spdkci** [comment] 2020-07-08 13:24
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_20808.html

**Comment by changpe1** [comment] 2020-07-09 04:11
[Bug Scrub] @Seth5141 Assign the shared library issue to you now, :)

**Comment by spdkci** [comment] 2020-07-09 07:37
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_20917.html

**Comment by tomzawadzki** [comment] 2020-07-09 09:33
This is duplicate of https://github.com/spdk/spdk/issues/1469, please rebase on latest SPDK.

**Closed by tomzawadzki** 2020-07-09 09:33 UTC
Labels: Intermittent Failure
