### ISSUE TITLE
iscsi: intermittent hotplug failure during high QD large read I/O

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1004] opened 2019-10-24 22:54 UTC
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_47794.html
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/47794/archive/RBD_autotest/index.html

Test fails during the hotplug portion of the iscsi_tgt/fio/fio.sh test script.

The log seems to indicate the iSCSI errors occur before we try to delete the malloc bdev while it is in use.  So it is possible this is not actually hotplug related.  I haven't studied the log long yet to tell.

**Comment by shuhei-matsumoto** [comment] 2019-10-24 23:06
@jimharris it looks that URLs are not public. Will you share the one we can access?

**Comment by jimharris** [comment] 2019-10-24 23:12
My mistake.  Thanks for noticing.

https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_47794.html
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/47794/archive/RBD_autotest/index.html

**Comment by jimharris** [comment] 2019-10-24 23:29
Just saw another case:
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_47801.html
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/47801/archive/RBD_autotest/index.html

**Comment by shuhei-matsumoto** [comment] 2019-10-24 23:44
@jimharris 

I saw the difference between before and after the refactoring.
Before refactoring, when we detect LUN removal, we send R2T before completing the task.
But after refactoring, when we detect LUN removal, we complete the task without sending R2T.

I followed NVMe-TCP target about the role division between header handling and payload handing.
NVMe-TCP target sends R2T in payload handling.

But the design of hotplug is different between iSCSI and NVMe-oF.

So I will move sending R2T from payload handling to header handling to restore the original design.

Unfortunately it's difficult to reproduce hotplug issue locally and so I may use test pool after simple local test. Please stay tune.

**Comment by shuhei-matsumoto** [comment] 2019-10-25 07:31
I added a patch https://review.gerrithub.io/c/spdk/spdk/+/472308 to fix this issue. This issue has not been reproduced by SPDK with this patch (more than 10 times run).

**Comment by shuhei-matsumoto** [comment] 2019-10-28 02:03
The above patch doesn't fix this issue. I saw the same failure in a patch following it.

https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_47972.html

The above patch should be merged but I continue investigating this issue.

**Comment by shuhei-matsumoto** [comment] 2019-10-28 02:40
I found another bug and added a fix to it. https://review.gerrithub.io/c/spdk/spdk/+/472507
I confirmed that this patch works locally, I will see if the issue is fixed by having more experience.

**Comment by shuhei-matsumoto** [comment] 2019-10-28 05:38
By using two patches, I haven't reproduced this issue for almost 10 runs, and looks good to me for now.
Further simplification may be possible but hotplug is very subtle and I don't want to do large change if not required.

**Comment by benlwalker** [comment] 2019-10-28 21:45
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/48046/archive/RBD_autotest/index.html

**Closed** 2019-10-30 08:27 UTC
Labels: Intermittent Failure
