### ISSUE TITLE
[question] SPDK accel framework, can it run in separated reactor and CPU core, currently accel poller just run inside current spdk_thread that may belong to another components and reactor 

### ISSUE THREAD

**Issue by gaowayne** [spdk/spdk#2164] opened 2021-09-19 04:16 UTC
# Bug report

SPDK accel framework, can it run in separated reactor and CPU core, currently accel poller just run inside current spdk_thread that may belong to another components and reactor

## Expected Behavior

for example, if we create one SPDK module called A, in this module A, we create our own spdk_thread that sit on our own cpu core. if our module A use the SPDK accel DSA, SPDK accel register ixid_poller inside our A's spdk_thread, then SPDK accel DSA poller share the same cpu core with our own A module. 

## Current Behavior

we want there is one option that SPDK accel DSA can configured run in another reactor and CPU cores for our testing purpose.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by KKaras169169** [comment] 2021-09-20 07:58
Hello @gaowayne, could you describe in detail what problem did you encounter in the above form, not just in GitHub issue title? Also if this is a question and not a bug or a problem with SPDK, please add a label _**question**_  (you can select it on the right side panel, under "Labels").

**Comment by changpe1** [comment] 2021-09-23 06:20
I think you are asking that starting a separate thread to poll IDXD completions while submitting new requests in your own module A.  The thread model for NVMe and acceleration framework is same, we will use the IO channel concept(poll group or poller inside)  for most of the usage scenarios.  Your described scenario isn't recommended.  Please continue to ask question in slack channel, I'm going to close this one.

**Closed by changpe1** 2021-09-23 06:20 UTC
Labels: question

**Comment by gaowayne** [comment] 2021-09-23 07:04
@changpe1 thank you so much changpeng. so it is by design IDXD accel run inside parent spdk_thread. by design it is not best practice we take IDXD completion pollers out of spdk_thread. we just need IDXD compete the same CPU core with parent spdk_thread.

**Comment by optimistyzy** [comment] 2021-09-24 05:14
@gaowayne We now have the independent idxd_perf tool with some basic functions, which can run without using spdk application work.

**Comment by gaowayne** [comment] 2021-09-24 06:49
> @gaowayne We now have the independent idxd_perf tool with some basic functions, which can run without using spdk application work.

thank you so much ziye. @uubs we will research idxd_perf. :)
