### ISSUE TITLE
Error in nvme_ctrlr_init_ana_log_page() when oversized_sgl is not supported

### ISSUE THREAD

**Issue by rsb-oss** [spdk/spdk#2584] opened 2022-07-12 23:12 UTC
# Bug report

According to the NVMe specification revision 1.4, Section 5.15.2.2 Identify Controller data structure (CNS 01h), Figure 251: Bytes 539:536 represent the SGL Support provided by the controller.  Within this byte range, Bit 18 indicates “If set to ‘1’, then the controller supports commands that contain a data or metadata SGL of a length larger than the amount of data to be transferred. If cleared to ‘0’, then the SGL length shall be equal to the amount of data to be transferred.”

Currently the SPDK maintains this information in the “nvme_spec.h::struct spdk_nvme_cdata_sgls.oversized_sgl” field.  However, this field is not used anywhere in the code, except for displaying its value in examples/nvme/identify/identify.c.

I encountered a problem when issuing the Get Log Page (05h) command, specifically in the function nvme_ctrlr_init_ana_log_page().  In this function, the ana_log_page_size is currently calculated based on the maximum number of namespaces the controller supports instead of the active number of namespaces.  This “Get Log Page” command resulted in a Completion queue entry status field with sct 0 (Generic Command Status) and sc 15 (Data SGL Length Invalid).

## Expected Behavior

nvme_ctrlr_init_ana_log_page() should succeed without error when the target indicates in the Identify Controller Data Structure that the SGL length shall be equal to the amount of data to be transferred.

## Current Behavior

nvme_ctrlr_init_ana_log_page() results in an error when the target clears Bit 18 in the SGL Support (SGLS) field of Identify Controller Data Structure.

## Possible Solution

When I changed the code in my local repo to use the active number of namespaces instead of the maximum supported number, the Get Log Page command completed successfully.  I believe the function nvme_ctrlr_init_ana_log_page() should not send a buffer larger than the required size if cdata.oversized_sgl flag is not set.  There may be other places in code where cdata.oversized_sgl flag should be checked to determine the SGL size.

## Steps to Reproduce

I believe the occurrence of this bug is dependent on the specific NVMe-oF target.  The error manifests as a failed bdev_nvme_attach_controller command.

E.x.:
spdk_rpc.py  -b Nvme0 -t rdma -a 192.168.110.2 -f ipv4 -s 4420 -n "nqn.1986-03.com.ibm:nvme:2145.000002042140992C" -q "nqn.2014-08.org.nvmexpress:uuid:f73a32d9-0018-46e6-92d0-cd14c0b2229b" -i 192.168.110.3
request:
{
  "name": "Nvme0",
  "trtype": "rdma",
  "traddr": "192.168.110.2",
  "hostnqn": "nqn.2014-08.org.nvmexpress:uuid:f73a32d9-0018-46e6-92d0-cd14c0b2229b",
  "hostaddr": "192.168.110.3",
  "adrfam": "ipv4",
  "trsvcid": "4420",
  "subnqn": "nqn.1986-03.com.ibm:nvme:2145.000002042140992C",
  "method": "bdev_nvme_attach_controller",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32602,
  "message": "Invalid parameters"
}

## Context (Environment including OS version, SPDK version, etc.)
SPDK 22.01
Initiator:  Ubuntu 20.04 on aarch64
Transport:  RoCEv2
Target:  IBM Flash System 9200

**Comment by Comphix** [comment] 2022-07-13 01:25
@rsb-oss thanks for reporting this issue, reading through the "Possible Solution" field, looks like you've already made some changes and verified. Would you like to raise a patch to SPDK Gerrit first to have more review and discussion on your changes?
Thanks.

**Comment by changpe1** [comment] 2022-07-13 01:39
In `nvme_ctrlr_alloc_ana_log_page` SPDK is using `ctrlr->active_ns_count` to allocate the log buffer, can you check with your NVMeoF target to see if this value isn't correct?

**Comment by changpe1** [comment] 2022-07-13 01:44
And SPDK will not block the initialization process even with that error, can you enable SPDK nvme log to see where the RPC exits?

**Comment by changpe1** [comment] 2022-07-13 01:55
I see where is the error now, the error is in nvme bdev module not the nvme driver layer.

**Comment by rsb-oss** [comment] 2022-07-13 04:36
> @rsb-oss thanks for reporting this issue, reading through the "Possible Solution" field, looks like you've already made some changes and verified. Would you like to raise a patch to SPDK Gerrit first to have more review and discussion on your changes? Thanks.

In my temporary fix I hardcoded the # active namespaces value, which is not a real solution.  I could not find an easy way to read the active_ns_count in the nvme_ctrlr_init_ana_log_page() function in bdev_nvme.c.  I am just getting familiar with the SPDK codebase, so I may have missed an easy solution if that is possible.

**Comment by rsb-oss** [comment] 2022-07-13 04:38
> I see where is the error now, the error is in nvme bdev module not the nvme driver layer.

Yes, it is in module/bdev/nvme/bdev_nvme.c:: nvme_ctrlr_init_ana_log_page() function.  Thank you for you comments and quick response!

**Comment by changpe1** [comment] 2022-07-13 04:47
> > @rsb-oss thanks for reporting this issue, reading through the "Possible Solution" field, looks like you've already made some changes and verified. Would you like to raise a patch to SPDK Gerrit first to have more review and discussion on your changes? Thanks.
> 
> In my temporary fix I hardcoded the # active namespaces value, which is not a real solution. I could not find an easy way to read the active_ns_count in the nvme_ctrlr_init_ana_log_page() function in bdev_nvme.c. I am just getting familiar with the SPDK codebase, so I may have missed an easy solution if that is possible.

That's OK, I will take a look of this issue.

**Comment by shuhei-matsumoto** [comment] 2022-07-13 05:04
Hi @rsb-oss

Thanks for finding and reporting this bug.
If the root cause is the number of active namespaces, I think the following should fix the issue.

https://review.spdk.io/gerrit/c/spdk/spdk/+/13653

Will you try the patch?

**Comment by rsb-oss** [comment] 2022-07-14 03:23
Hi @shuhei-matsumoto , thank you for the patch.  I will test it tomorrow USA EDT time zone) and let you know the result.

**Comment by rsb-oss** [comment] 2022-07-17 23:21
Hi @shuhei-matsumoto , I tested the patch on our system and it works!  Sorry for the delay.

I have one suggestion for the commit message --  I think "set" should be changed to "cleared" as in the following message:
`caused an issue when the corresponding NVMe-oF target set the bit 18 of the SGL support field in the Identify Controller Data structure.`
should be changed to
`caused an issue when the corresponding NVMe-oF target cleared the bit 18 of the SGL support field in the Identify Controller Data structure.`

**Comment by shuhei-matsumoto** [comment] 2022-07-18 00:04
Hi @rsb-oss Thank you so much for your careful test and code review.

Sorry, I don't know how I update the commit message of the merged patch.
So I saved the fix into the https://review.spdk.io/gerrit/c/spdk/spdk/+/13653 as what I can do at most.

Thanks again for your expertise.

**Closed by shuhei-matsumoto** 2022-07-18 00:04 UTC
Labels: bug, Sighting, Patches out for review
