### ISSUE TITLE
Probe fails and device does not show up anymore, even after reboot, after resetting to nvme.

### ISSUE THREAD

**Issue by hfingler** [spdk/spdk#105] opened 2017-01-31 06:16 UTC
Clean DPDK/SPDK checkouts. 
 Ran setup.sh script.
 Ran hello_world example and this is the output, returned instantly.
```
EAL: Detected 16 lcore(s)
EAL: Auto-detected process type: PRIMARY
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: PCI device 0000:82:00.0 on NUMA socket 1
EAL:   probe driver: 1b85:6018 spdk_nvme
Initializing NVMe Controllers
EAL: PCI device 0000:82:00.0 on NUMA socket 1
EAL:   probe driver: 1b85:6018 spdk_nvme
Attaching to 0000:82:00.0
nvme_ctrlr.c:1096:nvme_ctrlr_process_init: ***ERROR*** get registers failed
spdk_nvme_probe() failed
```
 Ran it again and it hangs:
```
...
Attaching to 0000:82:00.0
Attached to 0000:82:00.0
Using controller TOSHIBA-RD400        (        X63S1007TPEV) with 1 namespaces.
  Namespace ID: 1 size: 256GB
Initialization complete.
^C
```
Third time:
```
..
EAL: PCI device 0000:82:00.0 on NUMA socket 1
EAL:   probe driver: 1b85:6018 spdk_nvme
Attaching to 0000:82:00.0
nvme_ctrlr.c:1211:nvme_ctrlr_process_init: ***ERROR*** Initialization timed out in state 2
nvme_ctrlr.c: 403:nvme_ctrlr_shutdown: ***ERROR*** did not shutdown within 5 seconds
spdk_nvme_probe() failed
```

At this point SPDK doesn't work, device is still listed in /dev as uio0.
So I tried resetting to nvme, ran the script and the device is gone, no nvme* nor uio in /dev.

Rebooted the machine, device is still gone, no nvme in /dev and it doesn't even show in lspci anymore. We found two solutions for this: turn off the machine and switch PCI ports or cut the power of the machine for a few seconds and power it back on.

 Kernel version:
`Linux version 4.8.12 (***) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) ) #20 SMP Mon Jan 30 19:40:03 CST 2017`

 What is this? Is it a kernel or SPDK issue?

 Right now we are considering moving to older versions, 16.06 segfaults but 16.08 seems to work (at least the examples), it just sucks that a lot of code needs to be modified all over again and we will need to rollback DPDK also.

 Thank you.

**Comment by jimharris** [comment] 2017-01-31 15:46
Hi Henrique,

Do you have an NVMe SSD from another vendor (preferably Intel) that you could test with?  The SPDK NVMe driver should work with any NVMe compliant SSD but it is possible there is a quirk with Toshiba SSDs that we need to account for.

Could you also apply the attached patch and rebuild SPDK with CONFIG_DEBUG=y, then retest?  This will give us more details on the initialization process when the failures/hangs occur.

Thanks,

-Jim

**Comment by hfingler** [comment] 2017-01-31 20:41
> Do you have an NVMe SSD from another vendor (preferably Intel) that you could test with?  The SPDK NVMe driver should work with any NVMe compliant SSD but it is possible there is a quirk with Toshiba SSDs that we need to account for.

We ordered a Intel SSD but it's not here yet, I'll test with it when it arrives. It's weird that we've been using SPDK for a few months on this SSD already, but I was using some older commit and never updating because I knew something would break.

> Could you also apply the attached patch and rebuild SPDK with CONFIG_DEBUG=y, then retest?  This will give us more details on the initialization process when the failures/hangs occur.

 What patch? I'll do it as soon as I can and let you know.

 Thanks!

**Comment by benlwalker** [comment] 2017-01-31 20:47
Do you happen to know which commit you were using? That may help us narrow down where the problem is. It is very likely something to do with our recent addition of hotplug support, but we need more information to proceed. Unfortunately, we don't currently have access to the Toshiba RD400 to reproduce the problem ourselves. We don't have any problem on Intel SSDs - we were able to confirm that at least.

**Comment by benlwalker** [comment] 2017-01-31 20:49
Also, this is the patch Jim wanted you to try out. It will enable significantly more logging. It was just buried in his email response and the GitHub UI doesn't display it nicely.

```
diff --git a/examples/nvme/hello_world/hello_world.c b/examples/nvme/hello_world/hello_world.c
index db9111b..ec3e44f 100644
--- a/examples/nvme/hello_world/hello_world.c
+++ b/examples/nvme/hello_world/hello_world.c
@@ -41,6 +41,7 @@

 #include "spdk/nvme.h"
 #include "spdk/env.h"
+#include "spdk/log.h"

 struct ctrlr_entry {
 	struct spdk_nvme_ctrlr	*ctrlr;
@@ -333,6 +334,8 @@ int main(int argc, char **argv)

 	printf("Initializing NVMe Controllers\n");

+	spdk_log_set_trace_flag("nvme");
+
 	/*
 	 * Start the SPDK NVMe enumeration process.  probe_cb will be called
 	 *  for each NVMe controller found, giving our application a choice on
```

**Comment by dverkamp-intel** [comment] 2017-01-31 21:27
If SPDK 16.08 worked and 16.12 (or latest master) fails, the likely culprit is the switch from libpciaccess to DPDK PCI.  This is not easy to test, since the libpciaccess option was removed, but it's a place to start.

The first thing to verify is that we are actually mapping the NVMe registers correctly; we don't have any debug prints for this currently, but you can add this (in addition to Jim's patch that enables the nvme trace flag):

```
diff --git a/lib/nvme/nvme_pcie.c b/lib/nvme/nvme_pcie.c
index 739ac17..4b36d30 100644
--- a/lib/nvme/nvme_pcie.c
+++ b/lib/nvme/nvme_pcie.c
@@ -533,6 +533,10 @@ nvme_pcie_ctrlr_allocate_bars(struct nvme_pcie_ctrlr *pctrlr)
        }
 
        pctrlr->regs_size = size;
+
+       SPDK_TRACELOG(SPDK_TRACE_NVME, "regs mapped at %p (%" PRIu64 " bytes)\n",
+                     pctrlr->regs, pctrlr->regs_size);
+
        nvme_pcie_ctrlr_map_cmb(pctrlr);
 
        return 0;
```

What we're looking for here is a sane-looking pointer (should be caught by the existing code) but also a sensible size - the BAR should be at least 8K.

Another possibility is that the device is not ready when we start bringup; this should be clarified by enabling the nvme trace flag, but another thing to try would be to add a delay before touching the hardware (this is not a real fix, but it will help us figure out what is actually going wrong):

```
diff --git a/lib/nvme/nvme.c b/lib/nvme/nvme.c
index fa5404f..0f4bf63 100644
--- a/lib/nvme/nvme.c
+++ b/lib/nvme/nvme.c
@@ -342,6 +342,7 @@ nvme_init_controllers(void *cb_ctx, spdk_nvme_attach_cb attach_cb)
                         *  can assume it is held.
                         */
                        nvme_robust_mutex_unlock(&g_spdk_nvme_driver->lock);
+                       sleep(1);
                        start_rc = nvme_ctrlr_process_init(ctrlr);
                        nvme_robust_mutex_lock(&g_spdk_nvme_driver->lock);
 ```

Additionally, the only way that you should see the "get registers failed" error from the first run is if the controller returns all 0xF's (this would point toward the controller not being ready yet when we look at CSTS), but we can verify that by adding a log in those cases:

```
diff --git a/lib/nvme/nvme_pcie.c b/lib/nvme/nvme_pcie.c
index 739ac17..783ea4a 100644
--- a/lib/nvme/nvme_pcie.c
+++ b/lib/nvme/nvme_pcie.c
@@ -349,6 +349,7 @@ nvme_pcie_ctrlr_get_reg_4(struct spdk_nvme_ctrlr *ctrlr, uint32_t offset, uint32
        *value = spdk_mmio_read_4(nvme_pcie_reg_addr(ctrlr, offset));
        g_thread_mmio_ctrlr = NULL;
        if (~(*value) == 0) {
+               SPDK_ERRLOG("Got all 0xF's (offset %u)\n", offset);
                return -1;
        }
 
@@ -366,6 +367,7 @@ nvme_pcie_ctrlr_get_reg_8(struct spdk_nvme_ctrlr *ctrlr, uint32_t offset, uint64
        *value = spdk_mmio_read_8(nvme_pcie_reg_addr(ctrlr, offset));
        g_thread_mmio_ctrlr = NULL;
        if (~(*value) == 0) {
+               SPDK_ERRLOG("Got all 0xF's (offset %u)\n", offset);
                return -1;
        }
```

It also looks like the IOMMU is enabled (based on the DPDK "VFIO support initialized" message); it might be worth trying with the same hardware but IOMMU disabled (e.g. intel_iommu=off on the kernel command line). Is the NVMe device managed by the vfio driver? From your original message, it sounds like it's using uio, but if you are using scripts/setup.sh from the SPDK repository, it should detect the existence of the IOMMU and use vfio instead.

**Comment by fzheart** [comment] 2017-02-03 17:20
Hello, 

I am Youngjin Kwon, a PhD. student in UT austin. I am working with Henrique who started this issue.
The SSD we are using is TOSHIBA OCZ RD400, complying NVMe 1.1b.
We are using kernel 4.8.12 running on Xeon E5-2640.

The issue was 
```c
int
nvme_pcie_ctrlr_get_reg_4(struct spdk_nvme_ctrlr *ctrlr, uint32_t offset, uint32_t *value)
{
    struct nvme_pcie_ctrlr *pctrlr = nvme_pcie_ctrlr(ctrlr);

    assert(offset <= sizeof(struct spdk_nvme_registers) - 4);
    assert(value != NULL);
    g_thread_mmio_ctrlr = pctrlr;
    *value = spdk_mmio_read_4(nvme_pcie_reg_addr(ctrlr, offset));
    g_thread_mmio_ctrlr = NULL;
#if 0 // This makes OCZ ssd offline
    if (~(*value) == 0) {
        return -1;
    }
#endif
    return 0;
}

int
nvme_pcie_ctrlr_get_reg_8(struct spdk_nvme_ctrlr *ctrlr, uint32_t offset, uint64_t *value)
{
    struct nvme_pcie_ctrlr *pctrlr = nvme_pcie_ctrlr(ctrlr);

    assert(offset <= sizeof(struct spdk_nvme_registers) - 8);
    assert(value != NULL);
    g_thread_mmio_ctrlr = pctrlr;
    *value = spdk_mmio_read_8(nvme_pcie_reg_addr(ctrlr, offset));
    g_thread_mmio_ctrlr = NULL;
#if 0 // This makes OCZ ssd offline
    if (~(*value) == 0) {
        return -1;
    }
#endif
    return 0;
}
```

To get around the initialization problem, I just simply comment out and it works for our experiment.

I have two questions.

First, About IOMMU, I turned off intel_iommu and check no device is in /sys/kernel/iommu_groups/. But DPDK initializes VFIO. Does it make potential problems?
```
EAL: No free hugepages reported in hugepages-1048576kB
**EAL: VFIO support initialized**
Initializing NVMe Controllers
Attaching to 0000:82:00.0
[nvme] nvme_ctrlr.c: 491:nvme_ctrlr_set_state: setting state to init (no timeout)
[nvme] nvme_ctrlr.c:1111:nvme_ctrlr_process_init: CC.EN = 1
[nvme] nvme_ctrlr.c:1125:nvme_ctrlr_process_init: Setting CC.EN = 0
[nvme] nvme_ctrlr.c: 495:nvme_ctrlr_set_state: setting state to disable and wait for CSTS.RDY = 0 (timeout 20000 ms)
[nvme] nvme_ctrlr.c:1182:nvme_ctrlr_process_init: CC.EN = 0 && CSTS.RDY = 0 - enabling controller
[nvme] nvme_ctrlr.c:1184:nvme_ctrlr_process_init: Setting CC.EN = 1
[nvme] nvme_ctrlr.c: 495:nvme_ctrlr_set_state: setting state to enable and wait for CSTS.RDY = 1 (timeout 20000 ms)
[nvme] nvme_ctrlr.c:1193:nvme_ctrlr_process_init: CC.EN = 1 && CSTS.RDY = 1 - controller is ready
[nvme] nvme_ctrlr.c: 583:nvme_ctrlr_identify: transport max_xfer_size 2072576
[nvme] nvme_ctrlr.c: 662:nvme_ctrlr_set_keep_alive_timeout: Controller KAS is 0 - not enabling Keep Alive
[nvme] nvme_ctrlr.c: 491:nvme_ctrlr_set_state: setting state to ready (no timeout)
Attached to 0000:82:00.0
Using controller TOSHIBA-RD400        (        X63S1007TPEV) with 1 namespaces.
  Namespace ID: 1 size: 256GB
Initialization complete.
Hello world!
[nvme] nvme_ctrlr.c: 395:nvme_ctrlr_shutdown: shutdown complete
```

Second, when there is a problem like the first posting, it seems like the SSD device goes offline.
It is shown at lscpi list at that time and after reboot (not power off), it disappears.
The only way I can make it online is cutting off power and turning the machine on again.

When the device has a problem, kernel cannot  probe it (I change it from uio to nvme with the setup.sh)
Kern.log like this:
```
Feb  3 08:45:33 mozart kernel: [30185.156876] nvme nvme0: pci function 0000:82:00.0
Feb  3 08:45:33 mozart kernel: [30185.514589] igb 0000:07:00.0: DCA enabled
Feb  3 08:45:33 mozart kernel: [30185.514606] igb 0000:07:00.1: DCA enabled
Feb  3 08:45:34 mozart kernel: [30186.309008] pcieport 0000:00:1c.4: bridge has subordinate 07 but max busn 08
Feb  3 08:45:34 mozart kernel: [30186.309100] pci 0000:05:00.0: PCI bridge to [bus 06]
Feb  3 08:45:34 mozart kernel: [30186.309104] pci 0000:05:00.0:   bridge window [io  0x6000-0x6fff]
Feb  3 08:45:34 mozart kernel: [30186.309110] pci 0000:05:00.0:   bridge window [mem 0xc6000000-0xc70fffff]
Feb  3 08:45:53 mozart kernel: [30205.677341] nvme nvme0: Device not ready; aborting reset
Feb  3 08:45:53 mozart kernel: [30205.678836] nvme nvme0: Removing after probe failure status: -19
Feb  3 10:24:40 mozart kernel: [36132.467309] ioatdma 0000:00:04.0: Removing dma and dca services
```
nvme list shows nothing. pci rescan (/sys/bus/pci/rescan) does not work.

Is there a way to make device usable without power-off? It will greatly boost problem diagnostics.

I will post the nvme_ctrlr log once the problem happens again.

**Comment by benlwalker** [comment] 2017-02-03 21:50
Focusing on just the problem where the device is returning all 0xFs for the register reads for a moment, I traced that back to its likely source. You, as the user, called spdk_nvme_probe(), which scanned the PCI bus and found the set of devices to attach to. Once the list is built, nvme_init_controllers() begins walking through a state machine on each device to bring it online (we do parallel bring up on the whole list). For each device, the state machine advances by calling nvme_ctrlr_process_init() on each controller to check if it can enter the next state. The state machine is defined by the NVMe specification.

It appears that your Toshiba RD-400 is exhibiting a behavior we haven't encountered before during this initialization. If a device is already in the enabled state (CC.EN == 1) when we start our state machine, we disable it (write CC.EN = 0). Disabling a controller triggers a device reset. My best guess is that there is a brief period during that reset process where the Toshiba RD-400 stops responding to MMIO reads, which results in the all 0xFs values you are seeing. Returning all 0xFs is not valid for those registers and we use that as an indication that the device was hot removed (which is new in SPDK 16.12).

I also think I can explain why this worked on an earlier version of SPDK. Prior to our hotplug code, we didn't check the register reads for the all 0xF signal value. Instead, we just blindly moved ahead, assuming all 0xFs was a valid value for that register. The next step in the state machine is to wait until CSTS.RDY becomes 0 (meaning the device is now disabled). A few erroneous all 0xF reads during that waiting period doesn't hurt anything. Clearly, this was working by accident.

I also walked through the Linux kernel NVMe driver and it works for exactly the same reason - they blindly interpret the CSTS read as valid while waiting for CSTS.RDY to become 0 and don't notice a brief period of all 0xF reads. The kernel checks in other locations for all 0xF reads as an indication of device removal, but not in this particular spot.

Attached is a patch that attempts to work around the issue. Can you give that a try and let me know how it goes? Remove any other modifications you made locally before attempting.

[0001-nvme-Handle-failing-MMIO-reads-while-resetting.txt](https://github.com/spdk/spdk/files/751629/0001-nvme-Handle-failing-MMIO-reads-while-resetting.txt)

**Comment by dverkamp-intel** [comment] 2017-02-21 23:46
A variant of Ben's fix was merged as commit 08c69c9cc5a0d41209dc218d4198bb34fff51c63.

Can you check if your device initializes reliably with this version?

Also, note that the failure where the device is totally gone (not reported in sysfs) and is only recoverable with a reboot will not be resolved by this issue - that sounds like a device firmware bug.  However, with this patch applied, the device will hopefully no longer get stuck part of the way through initialization and get into the hung state.

**Comment by hfingler** [comment] 2017-02-28 19:16
@dverkamp-intel It works. Just finished running a long write benchmark that toggled constantly between nvme/uio and didn't get any errors. Thank you!

**Comment by dverkamp-intel** [comment] 2017-02-28 19:56
Great to hear, thanks for testing - sounds like this issue is resolved, so I am closing it.

**Closed by dverkamp-intel** 2017-02-28 19:56 UTC
