### ISSUE TITLE
dynamically added vfio devices doesn't register memory with iommu

### ISSUE THREAD

**Issue by jlevon** [spdk/spdk#2086] opened 2021-08-12 09:10 UTC
Using an SPDK based on 153f03cf42880f083dad9de71bc73e287bf7f997
we observed the following issue.

We've set up SPDK such that it is using vfio-user with a qemu client, and the VM
using nvmf's virtual NVMe controller.
During start of the VM, each guest memory region is mapped in the DMA callback
via spdk_mem_register(). In `lib/env_dpdk/memory.c`, it then attempts to register
that memory with the VFIO container via the `MAP_DMA` ioctl. This fails, as we have
not yet added any vfio groups to the DPDK container (EINVAL case).

Next, we hotplug a real NVMe PCI device into the backend of nvmf:

```
/root/spdk/scripts/rpc.py -s /var/lib/libvirt/qemu/domain-690c5a37-a6f6-4028-9c38-3465531d845d/rpc.sock bdev_nvme_attach_controller -b NVMe1 -t PCIe -a 0000:86:00.0
/root/spdk/scripts/rpc.py -s /var/lib/libvirt/qemu/domain-690c5a37-a6f6-4028-9c38-3465531d845d/rpc.sock nvmf_subsystem_add_ns nqn.2014-08.org.nvmexpress:uuid:690c5a37-a6f6-4028-9c38-3465531d845d NVMe1n1
```

Note this is *not* a kernel-level hotplug: the device already exists on the system.

The problem/bug is that nothing ever triggers another vfio MAP_DMA call, now that the 
VFIO container has a group. And thus, any attempt to use the PCI device will fail, because
the IOMMU hasn't been programmed with this guest memory region.

This is all in iova-mode=va

@changpe1 pointed me to https://review.spdk.io/gerrit/c/spdk/spdk/+/3560
but this didn't help.

I haven't tested, but I suspect that if I hand-coded a call to `vtophys_iommu_device_event`
in the controller attach code above, then we would reach this code:

```
1200                         /* This is the first device registered. This means that the first
1201                          * IOMMU group might have been just been added to the DPDK vfio container.
1202                          * From this point it is certain that the memory can be mapped now.
1203                          */                                                      
1204                         TAILQ_FOREACH(dma_map, &g_vfio.maps, tailq) {            
1205                                 ret = ioctl(g_vfio.fd, VFIO_IOMMU_MAP_DMA, &dma_map->map);
1206                                 if (ret) {                                       
1207                                         DEBUG_PRINT("Cannot update DMA mapping, error %d\n", errno);
1208                                         break;                                   
1209                                 }                                                
1210                         }                                                        
```

and things would work.

We confirmed that if we attach the controller/namespace *first*, then start the VM, there is no problem. In this case, spdk_mem_register() can see an VFIO group when it calls the MAP_DMA ioctl.

**Comment by antroseco** [comment] 2021-08-13 17:25
I've managed to narrow this down to two distinct issues.

## DPDK does not process event callbacks after hotplug

SPDK's `vtophys_iommu_device_event` is supposed to remap memory (sometimes) after a `RTE_DEV_EVENT_ADD` event.
`spdk_pci_device_attach()` calls `rte_eal_hotplug_add()` to attach our PCIe drive, but `rte_eal_hotplug_add()` doesn't call `rte_dev_event_callback_process()` so `vtophys_iommu_device_event()` never gets called and memory is never remapped.

Adding the missing call to DPDK is enough to fix this issue, but I don't know if that's the best place to put it or if that's even expected behaviour (maybe SPDK is using DPDK incorrectly here).

```diff
diff --git a/lib/librte_eal/common/eal_common_dev.c b/lib/librte_eal/common/eal_common_dev.c
index 8a3bd3100..1d57c3efd 100644
--- a/lib/librte_eal/common/eal_common_dev.c
+++ b/lib/librte_eal/common/eal_common_dev.c
@@ -123,6 +123,8 @@ rte_eal_hotplug_add(const char *busname, const char *devname,
        ret = rte_dev_probe(devargs);
        free(devargs);

+       rte_dev_event_callback_process(devname, RTE_DEV_EVENT_ADD);
+
        return ret;
 }
```

## VFIO does not imply a DPDK device


`vtophys_iommu_init()` assumes that all devices with the VFIO driver loaded are being actively managed by DPDK.

```c
	/* If the IOMMU is enabled, we need to track whether there are any devices present because
	 * it's only valid to perform vfio IOCTLs to the containers when there is at least
	 * one device. The device may be a DPDK device that SPDK doesn't otherwise know about, but
	 * that's ok.
	 */
	RTE_DEV_FOREACH(dev, "bus=pci", &dev_iter) {
		struct rte_pci_device *pci_dev = RTE_DEV_TO_PCI(dev);

#if RTE_VERSION < RTE_VERSION_NUM(20, 11, 0, 0)
		if (pci_dev->kdrv == RTE_KDRV_VFIO) {
#else
		if (pci_dev->kdrv == RTE_PCI_KDRV_VFIO) {
#endif
			/* This is a PCI device using vfio */
			g_vfio.device_ref++;
		}
	}
```

In our environment, we have other drives present with the VFIO driver that are not managed by DPDK.

```c
if (g_vfio.device_ref == 1) {
    struct spdk_vfio_dma_map *dma_map;
    int ret;

    /* This is the first device registered. This means that the first
        * IOMMU group might have been just been added to the DPDK vfio container.
        * From this point it is certain that the memory can be mapped now.
        */
    TAILQ_FOREACH(dma_map, &g_vfio.maps, tailq) {
        ret = ioctl(g_vfio.fd, VFIO_IOMMU_MAP_DMA, &dma_map->map);
        if (ret) {
            DEBUG_PRINT("Cannot update DMA mapping, error %d\n", errno);
            break;
        }
    }
}
```

These other devices confuse `vtophys_iommu_device_event()` which thinks that there already some DPDK devices registered, and concludes that it doesn't need to update the DMA mappings.
An `strace` confirms that DPDK never opened any VFIO group other than that of the hotplugged drive, so all previous attempts to map memory failed (as expected).
Commenting out the above `if` statement (and hence updating DMA mappings every time a device is attached) is enough to get this working.

**Comment by jlevon** [comment] 2021-08-16 11:42
For the second problem, I think the code is just trying to check for a transition from 0 right?

So it should be something like:

```
    case RTE_DEV_EVENT_ADD: {
           bool vfio_seen = (g_vfio.device_ref == 0);
           ...

           if (!vfio_seen && g_vfio.device_ref > 0) {
                ... ioctl(MAP_DMA) ...
           }
```

That's presuming that we don't have an issue with REMOVE (where we'll never fall to 0 in our case).

**Comment by jlevon** [comment] 2021-08-16 12:16
As @antroseco points out, that won't work because we've already enumerated devices in `vtophys_iommu_init()`

**Comment by jimharris** [comment] 2021-08-16 17:37
@changpe1 - are you already looking at this or should we assign to someone else during next bug scrub?

**Comment by changpe1** [comment] 2021-08-17 01:22
> @changpe1 - are you already looking at this or should we assign to someone else during next bug scrub?

Hi Jim, I've started to investigate this issue, just return back from another vfio-user issue.

**Comment by changpe1** [comment] 2021-08-17 05:08
The hotplug doesn't work in DPDK.

This is the uevent messages when bind a NVMe controller to vfio-pci driver,  DPDK only parse the first message, but it requires the PCI_SLOT_NAME's value in the second message.

add@/devices/virtual/vfio/79
ACTION=add
DEVPATH=/devices/virtual/vfio/79
SUBSYSTEM=vfio
MAJOR=234
MINOR=4
DEVNAME=vfio/79
SEQNUM=10270

bind@/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0
ACTION=bind
DEVPATH=/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0
SUBSYSTEM=pci
DRIVER=vfio-pci
PCI_CLASS=10802
PCI_ID=8086:0953
PCI_SUBSYS_ID=8086:3703
PCI_SLOT_NAME=0000:d8:00.0
MODALIAS=pci:v00008086d00000953sv00008086sd00003703bc01sc08i02
SEQNUM=10122

SPDK implemented the uevent listening first, DPDK copied part of this code but not include all. we can revert patch 8f7d9ec2f
in SPDK or we need to update DPDK to fix this issue.

**Comment by changpe1** [comment] 2021-08-17 07:23
There is patch https://review.spdk.io/gerrit/c/spdk/spdk/+/8346 is working on this part, but I'm not sure it can work as expected.

**Comment by changpe1** [comment] 2021-08-17 07:30
> There is patch https://review.spdk.io/gerrit/c/spdk/spdk/+/8346 is working on this part, but I'm not sure it can work as expected.

this patch doesn't fix this issue.

**Comment by antroseco** [comment] 2021-08-17 12:05
@changpe1 are we supposed to be getting uevents though? As @jlevon said at the beginning of the thread, “this is _not_ a kernel-level hotplug: the device already exists on the system.” That device is already using the vfio driver (`spdk/scripts/setup.sh`).

**Comment by changpe1** [comment] 2021-08-17 14:20
@antroseco I need to clarify that from my tests, if there was valid IOMMU group(not the device you added later) in the vfio container at the beginning, I didn't find any issues with that.  Here is the failure case I reproduced in my local environment.

1. start vhost application, no PCI device are bind to vfio-pci driver now.
2. create a vhost scsi controller, but don't assign a block device, we will add a NVMe bdev to LUN0 after start VM sucessfully.
3. start QEMU
4. Bind a NVMe SSD to vfio-pci driver and then attach the NVMe SSD to SPDK.

Here is the issue for step 4, no RTE event is detected, so SPDK has no chance to register existing memory regions to vfio container.

The code is there, but it doesn't work for this case.

**Comment by changpe1** [comment] 2021-08-17 14:25
@antroseco You may try to revert commit 8f7d9ec2f to see if it can fix your issue or not.

**Comment by antroseco** [comment] 2021-08-18 12:39
@changpe1 thanks for the suggestion, reverting that commit fixes the issue.

To clarify, we had no IOMMU group set in the VFIO container at the beginning, and our setup is slightly different that your failure case.

We've had 5 PCIe devices initially, all bound to vfio-pci but none were used by SPDK or DPDK (so SPDK incorrectly believes there's 5 DPDK devices i.e. 5 IOMMU groups are already attached to the VFIO container).
And when the NVMe SSD was attached to SPDK, it was already using the vfio-pci driver, so no BIND uevent is generated (as expected).

**Comment by changpe1** [comment] 2021-08-19 07:15
OK, I see where is your issue now, actually they are two separate issues, but reverting commit 8f7d9ec is the right fix for both.

The code in SPDK vtophys_iommu_init() is actually wrong, because it counts the number of devices that bind to vfio-pci driver, we should count it by another condition, e.g: increase it only if it has a valid NVMe or IOAT driver(probed).  Even we use DPDK hotplug library in future we should not remove vfio container check in vtophys_pci_device_added().

	RTE_DEV_FOREACH(dev, "bus=pci", &dev_iter) {
		struct rte_pci_device *pci_dev = RTE_DEV_TO_PCI(dev);

#if RTE_VERSION < RTE_VERSION_NUM(20, 11, 0, 0)
		if (pci_dev->kdrv == RTE_KDRV_VFIO) {
#else
		if (pci_dev->kdrv == RTE_PCI_KDRV_VFIO) {
#endif
			/* This is a PCI device using vfio */
			g_vfio.device_ref++;
		}
	}

@jimharris @benlwalker I think we need to revert commit 8f7d9ec, fix uevent in DPDK doesn't fix this issue.

**Comment by changpe1** [comment] 2021-08-20 02:13
Here is the revert patch https://review.spdk.io/gerrit/c/spdk/spdk/+/9236

**Comment by changpe1** [comment] 2021-09-02 04:38
[Bug Scrub] @Maciej-Szwed any progress on this issue? thanks.

**Comment by changpe1** [comment] 2021-09-26 00:43
patch has been merged, so closing this issue for now.

**Closed by changpe1** 2021-09-26 00:43 UTC
Labels: bug, High, Patches out for review
