### ISSUE TITLE
error log reported with vfio driver when we register devdax device into SPDK

### ISSUE THREAD

**Issue by gaowayne** [spdk/spdk#2511] opened 2022-05-13 09:45 UTC
# Bug report

we see one error log, when we create one simple bdev to talk devdax with idxd driver, we register spdk mem then unregister when free bdev. but do not know why vfio layer report this error log, it does not impact anything else

## Expected Behavior

if any workaround can swallow this error if is reported by mistake

## Current Behavior

check below error reported in VFIO layer.
```
[root@localhost drivers.storage.thirdparty.write-shaping-raid.wsr]# ./test/bdev/bdevperf/bdevperf --json ./perfwsrpmemdsa4G.json --json-ignore-init-errors -r /var/tmp/spdk.sock -m 1 -q 128  -o 4096 -w randwrite  -t 60
[2022-05-12 23:35:03.428800] Starting SPDK v22.05-pre git sha1 95f3ea9e7 / DPDK 21.11.0 initialization...
[2022-05-12 23:35:03.428840] [ DPDK EAL parameters: [2022-05-12 23:35:03.428846] bdevperf [2022-05-12 23:35:03.428848] --no-shconf [2022-05-12 23:35:03.428852] -c 1 [2022-05-12 23:35:03.428856] --huge-unlink [2022-05-12 23:35:03.428858] --log-level=lib.eal:6 [2022-05-12 23:35:03.428862] --log-level=lib.cryptodev:5 [2022-05-12 23:35:03.428864] --log-level=user1:6 [2022-05-12 23:35:03.428868] --base-virtaddr=0x200000000000 [2022-05-12 23:35:03.428871] --match-allocations [2022-05-12 23:35:03.428874] --file-prefix=spdk_pid2972272 [2022-05-12 23:35:03.428877] ]
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-05-12 23:35:03.450857] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 1
[2022-05-12 23:35:03.541987] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
[2022-05-12 23:35:03.546172] accel_engine_idxd_rpc.c:  70:rpc_idxd_scan_accel_engine: *NOTICE*: Enabling IDXD user-mode
[2022-05-12 23:35:03.574192] accel_engine.c: 548:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2022-05-12 23:35:04.925577] accel_engine_idxd.c: 422:accel_engine_idxd_init: *NOTICE*: Accel engine updated to use IDXD DSA engine.
[2022-05-12 23:35:20.203885] bdev_wsrpmem.c: 489:create_wsrpmem_disk: *NOTICE*:  wsrpmem spdk_mem_register at: 0x0x7e32c0000000
[2022-05-12 23:35:20.204082] json_config.c: 155:rpc_client_check_timeout: *WARNING*: RPC client command timeout.
Running I/O for 60 seconds...
 Job: WSRPMEM0 (Core Mask 0x1)
	 WSRPMEM0            : 3049092.45 IOPS   11910.52 MiB/s
 =============================================================
 Total                       : 3049092.45 IOPS   11910.52 MiB/s
[2022-05-12 23:36:27.028016] bdev_wsrpmem.c: 154:wsrpmem_disk_free: *NOTICE*:  wsrpmem spdk_mem_unregister at: 0x0x7e32c0000000
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
EAL: Unexpected size 115343360 of DMA remapping cleared instead of 2097152
```

## Steps to Reproduce

1. create one simple bdev on devdax with idxd driver with accel_engine
2. check above error log
3.
4.

**Comment by jimharris** [comment] 2022-05-16 16:36
This is a duplicate of #2512.

I'm going to close this one, even though it was filed earlier, since #2511 has some additional discussion on it already.

**Closed by jimharris** 2022-05-16 16:36 UTC
Labels: Sighting
