### ISSUE TITLE
Iscsi target intermittent failure

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#1098] opened 2019-12-06 10:09 UTC
In test ./test/iscsi_tgt/calsoft/calsoft.sh sometimes occurs following error:
```
/var/jenkins/workspace/RBD_BlobFS_tests/RBD_autotest/spdk/test/iscsi_tgt/calsoft/calsoft.py /var/jenkins/workspace/RBD_BlobFS_tests/RBD_autotest/spdk/../output
iscsi.c:4642:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=1
iscsi.c:4973:iscsi_read_pdu: *ERROR*: pdu received after logout
iscsi.c:4642:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=1
iscsi.c:4973:iscsi_read_pdu: *ERROR*: pdu received after logout
iscsi.c:4427:iscsi_pdu_hdr_op_data: *ERROR*: the dataout pdu data length is larger than the value sent by R2T PDU
iscsi.c:4752:iscsi_pdu_hdr_handle: *ERROR*: processing PDU header (opcode=5) failed on iqn.2016-06.io.spdk:Target3,t,0x0001(iqn.1994-05.com.redhat:b3283535dc3b,i,0x00230d030000)
iscsi.c:4894:iscsi_read_pdu: *ERROR*: Critical error is detected. Close the connection
iscsi.c:4632:iscsi_update_cmdsn: *ERROR*: CmdSN(0) ignore (ExpCmdSN=4, MaxCmdSN=66)
iscsi.c:4642:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=5
iscsi.c:4973:iscsi_read_pdu: *ERROR*: pdu received after logout
iscsi.c:4632:iscsi_update_cmdsn: *ERROR*: CmdSN(341) ignore (ExpCmdSN=8, MaxCmdSN=71)
iscsi.c:4632:iscsi_update_cmdsn: *ERROR*: CmdSN(8) ignore (ExpCmdSN=9, MaxCmdSN=71)
iscsi.c:4642:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=12
iscsi.c:4973:iscsi_read_pdu: *ERROR*: pdu received after logout
iscsi.c:4642:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=9
iscsi.c:4973:iscsi_read_pdu: *ERROR*: pdu received after logout
iscsi.c:4642:iscsi_update_cmdsn: *ERROR*: CmdSN(3) error ExpCmdSN=4
iscsi.c:4642:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=4
iscsi.c:4973:iscsi_read_pdu: *ERROR*: pdu received after logout
iscsi.c:4632:iscsi_update_cmdsn: *ERROR*: CmdSN(0) ignore (ExpCmdSN=4, MaxCmdSN=67)
iscsi.c:4642:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=5
iscsi.c:4973:iscsi_read_pdu: *ERROR*: pdu received after logout
iscsi.c:4642:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=1
iscsi.c:4973:iscsi_read_pdu: *ERROR*: pdu received after logout
iscsi.c:4799:iscsi_pdu_payload_handle: *ERROR*: processing PDU payload (opcode=3) failed on iqn.2016-06.io.spdk:Target3,t,0x0001(iqn.1994-05.com.redhat:b3283535dc3b,i,0x00023d030000)
iscsi.c:4973:iscsi_read_pdu: *ERROR*: pdu received after logout
iscsi.c:4632:iscsi_update_cmdsn: *ERROR*: CmdSN(0) ignore (ExpCmdSN=4, MaxCmdSN=67)
iscsi.c:4642:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=5
iscsi.c:4973:iscsi_read_pdu: *ERROR*: pdu received after logout
iscsi.c:4632:iscsi_update_cmdsn: *ERROR*: CmdSN(3) ignore (ExpCmdSN=4, MaxCmdSN=67)
iscsi.c:4632:iscsi_update_cmdsn: *ERROR*: CmdSN(4) ignore (ExpCmdSN=5, MaxCmdSN=67)
iscsi.c:4642:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=6
iscsi.c:4973:iscsi_read_pdu: *ERROR*: pdu received after logout
iscsi.c:4632:iscsi_update_cmdsn: *ERROR*: CmdSN(0) ignore (ExpCmdSN=4, MaxCmdSN=67)
iscsi.c:4642:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=5
iscsi.c:4973:iscsi_read_pdu: *ERROR*: pdu received after logout
iscsi.c:4642:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=4
iscsi.c:4973:iscsi_read_pdu: *ERROR*: pdu received after logout
iscsi.c:4973:iscsi_read_pdu: *ERROR*: pdu received after logout
iscsi.c:4642:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=6
iscsi.c:4973:iscsi_read_pdu: *ERROR*: pdu received after logout
iscsi.c:4642:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=1
iscsi.c:4973:iscsi_read_pdu: *ERROR*: pdu received after logout
iscsi.c:4632:iscsi_update_cmdsn: *ERROR*: CmdSN(3) ignore (ExpCmdSN=4, MaxCmdSN=67)
iscsi.c:4642:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=5
iscsi.c:4973:iscsi_read_pdu: *ERROR*: pdu received after logout
iscsi_tgt: conn.c:313: spdk_iscsi_conn_free_pdu: Assertion `conn->data_in_cnt > 0' failed.
Skipping tc_ffp_15_2. It is known to fail.
Skipping tc_ffp_29_2. It is known to fail.
Skipping tc_ffp_29_3. It is known to fail.
Skipping tc_ffp_29_4. It is known to fail.
Skipping tc_err_1_1. It is known to fail.
Skipping tc_err_1_2. It is known to fail.
Skipping tc_err_2_8. It is known to fail.
Skipping tc_err_3_1. It is known to fail.
Skipping tc_err_3_2. It is known to fail.
Skipping tc_err_3_3. It is known to fail.
Skipping tc_err_3_4. It is known to fail.
Skipping tc_err_5_1. It is known to fail.
Skipping tc_login_3_1. It is known to fail.
Skipping tc_login_11_2. It is known to fail.
Skipping tc_login_11_4. It is known to fail.
Skipping tc_login_2_2. It is known to fail.
Test case tc_login_20_14 failed.
Test case tc_login_20_26 failed.
Test case tc_login_20_6 failed.
Test case tc_login_19_1 failed.
Test case tc_login_11_3 failed.
Test case tc_ffp_7_3_4 failed.
Test case tc_login_20_29 failed.
Test case tc_ffp_20_1 failed.
Test case tc_login_5_3 failed.
Test case tc_ffp_12_3_11 failed.
Test case tc_login_26_1 failed.
Test case tc_ffp_7_4 failed.
Test case tc_login_28_2 failed.
Test case tc_login_27_3 failed.
Test case tc_login_24_4 failed.
Test case tc_login_20_21 failed.
Test case tc_login_20_4 failed.
Test case tc_login_17_1 failed.
Test case tc_login_27_9 failed.
Test case tc_ffp_12_1 failed.
Test case tc_ffp_11_2 failed.
Test case tc_login_27_7 failed.
Test case tc_login_20_8 failed.
Test case tc_login_20_15 failed.
Test case tc_ffp_10_1 failed.
Test case tc_ffp_12_3_1 failed.
Test case tc_ffp_7_2_1 failed.
Test case tc_login_20_10 failed.
Test case tc_login_28_4 failed.
Test case tc_ffp_10_2 failed.
Test case tc_login_20_12 failed.
Test case tc_ffp_7_1_3 failed.
Test case tc_ffp_12_3_5 failed.
Test case tc_ffp_7_5_1 failed.
Test case tc_ffp_19_4 failed.
Test case tc_login_16_1 failed.
Test case tc_login_32_1 failed.
Test case tc_login_20_19 failed.
Test case tc_ffp_7_1_2 failed.
Test case tc_login_18_1 failed.
Test case tc_ffp_7_6_3 failed.
Test case tc_login_20_11 failed.
Test case tc_ffp_12_3_12 failed.
Test case tc_ffp_12_3_8 failed.
Test case tc_login_20_1 failed.
Test case tc_login_20_20 failed.
Test case tc_login_27_6 failed.
Test case tc_login_28_3 failed.
Test case tc_login_27_4 failed.
Test case tc_login_20_28 failed.
Test case tc_login_11_1 failed.
Test case tc_login_30_2 failed.
Test case tc_login_29_1 failed.
Test case tc_login_20_23 failed.
Test case tc_login_24_3 failed.
Test case tc_ffp_7_1 failed.
Test case tc_ffp_12_3_13 failed.
Test case tc_login_20_5 failed.
Test case tc_ffp_19_2 failed.
Test case tc_ffp_7_5 failed.
Test case tc_login_20_18 failed.
Test case tc_ffp_7_7_4 failed.
Test case tc_ffp_7_3_3 failed.
Test case tc_login_27_5 failed.
Test case tc_login_20_31 failed.
Test case tc_ffp_7_1_4 failed.
Test case tc_ffp_7_6_2 failed.
Test case tc_ffp_7_3_1 failed.
Test case tc_ffp_12_3_4 failed.
Test case tc_ffp_12_3_6 failed.
Test case tc_ffp_7_7_2 failed.
Test case tc_ffp_12_2 failed.
Test case tc_login_27_1 failed.
Test case tc_login_27_10 failed.
Test case tc_login_27_8 failed.
Test case tc_login_24_1 failed.
Test case tc_ffp_7_4_3 failed.
Test case tc_ffp_2_1 failed.
Test case tc_ffp_7_4_2 failed.
Test case tc_login_6_1 failed.
Test case tc_login_20_17 failed.
Test case tc_login_23_1 failed.
Test case tc_ffp_7_7 failed.
Test case tc_login_2_5 failed.
Test case tc_ffp_7_4_4 failed.
Test case tc_ffp_7_1_1 failed.
Test case tc_login_5_4 failed.
Test case tc_ffp_7_5_2 failed.
Test case tc_ffp_12_3_3 failed.
Test case tc_login_20_9 failed.
Test case tc_login_24_2 failed.
Test case tc_login_20_30 failed.
Test case tc_login_27_2 failed.
Test case tc_login_20_3 failed.
Test case tc_login_20_13 failed.
Test case tc_ffp_7_2_3 failed.
Test case tc_login_30_1 failed.
Test case tc_ffp_2_2 failed.
Test case tc_ffp_7_6_4 failed.
Test case tc_ffp_7_7_5 failed.
Test case tc_login_15_1 failed.
Test case tc_ffp_7_2 failed.
Test case tc_login_25_1 failed.
Test case tc_login_10_1 failed.
Test case tc_ffp_19_5 failed.
Test case tc_login_20_27 failed.
Test case tc_ffp_7_7_1 failed.
Test case tc_login_26_2 failed.
Test case tc_login_2_4 failed.
Test case tc_ffp_26_2 failed.
Test case tc_ffp_25_3 failed.
Test case tc_ffp_7_7_3 failed.
Test case tc_login_28_1 failed.
Test case tc_login_7_2 failed.
Test case tc_ffp_7_5_4 failed.
Test case tc_ffp_4_1 failed.
Test case tc_login_1_1 failed.
Test case tc_ffp_16_1 failed.
Test case tc_ffp_12_3_7 failed.
Test case tc_err_2_3 failed.
Test case tc_ffp_2_1_7 failed.
Test case tc_ffp_2_1_5 failed.
Test case tc_login_14_1 failed.
Test case tc_err_2_7 failed.
Test case tc_ffp_2_1_3 failed.
Test case tc_ffp_18_1 failed.
Test case tc_login_20_24 failed.
Test case tc_ffp_7_3_2 failed.
Test case tc_ffp_7_6_1 failed.
Test case tc_ffp_7_3 failed.
Test case tc_err_7_1 failed.
Test case tc_ffp_5_1 failed.
Test case tc_ffp_1_2 failed.
Test case tc_err_6_1 failed.
Test case tc_ffp_2_1_10 failed.
Test case tc_ffp_26_1 failed.
Test case tc_err_8_2 failed.
Test case tc_err_2_2 failed.
Test case tc_ffp_1_4 failed.
Test case tc_ffp_2_1_8 failed.
Test case tc_ffp_25_4 failed.
Test case tc_ffp_17_1 failed.
Test case tc_err_2_1 failed.
Test case tc_err_8_1 failed.
Test case tc_err_2_4 failed.
Test case tc_ffp_14_1 failed.
Test case tc_ffp_6_1 failed.
Test case tc_ffp_1_3 failed.
Test case tc_ffp_13_1 failed.
Test case tc_ffp_15_1 failed.
Test case tc_ffp_8_2 failed.
Test case tc_ffp_2_1_2 failed.
Test case tc_ffp_25_2 failed.
Test case tc_ffp_2_1_11 failed.
Test case tc_ffp_2_1_4 failed.
Test case tc_ffp_2_1_9 failed.
Test case tc_ffp_8_1 failed.
Test case tc_ffp_2_1_1 failed.
Test case tc_ffp_2_1_6 failed.
Test case tc_ffp_14_2 failed.
Test case tc_err_2_5 failed.
./test/iscsi_tgt/calsoft/calsoft.sh: line 64: 3583937 Aborted                 (core dumped) $ISCSI_APP -m 0x1 --wait-for-rpc
```

**Comment by spdkci** [comment] 2019-12-06 10:12
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51568.html

**Comment by spdkci** [comment] 2019-12-06 10:12
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51566.html

**Comment by tomzawadzki** [comment] 2019-12-06 10:12
This is duplicate of #1074, which was already fixed. Please rebase your patches on master and if it sill occurs - reopen that issue.

**Closed by tomzawadzki** 2019-12-06 10:12 UTC
