### ISSUE TITLE
[vg-autotest] logs have not been generated

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#2268] opened 2021-12-06 03:03 UTC
# CI Intermittent Failure

```
[autotest-per-patch] $ /usr/bin/env bash /tmp/jenkins777260840659526605.sh
+ echo 'Start stage post_gen_coverage.sh'
Start stage post_gen_coverage.sh
+ cd /var/jenkins/workspace/autotest-per-patch
+ rm -rf /var/jenkins/workspace/autotest-per-patch/spdk/doc
+ s_opt=
+ [[ '' == true ]]
++ find ./runID.info ./spdk ./spdk@tmp -mindepth 1 -type d -name output
+ out_dirs=
++ find ./runID.info ./spdk ./spdk@tmp -mindepth 1 -name cov_total.info
+ cov_files=
+ sed -i 's#--show-details#--show-details --ignore-errors source#g' spdk/autorun_post.py
+ array=($(find $WORKSPACE -type f -name 'timing.txt'))
++ find /var/jenkins/workspace/autotest-per-patch -type f -name timing.txt
+ timing_dir=/var/jenkins/workspace/autotest-per-patch/post_process
+ mkdir -p /var/jenkins/workspace/autotest-per-patch/post_process
+ timing_file=/var/jenkins/workspace/autotest-per-patch/post_process/total_timing.txt
+ /usr/local/FlameGraph/flamegraph.pl --title 'Build Timing' --nametype Step: --countname seconds /var/jenkins/workspace/autotest-per-patch/post_process/total_timing.txt
Can't open /var/jenkins/workspace/autotest-per-patch/post_process/total_timing.txt: No such file or directory at /usr/local/FlameGraph/flamegraph.pl line 606.
ERROR: No stack counts found
```

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_63110.html

## Execution failed at

```
quiet period for unittest-vg-autotest is 0 seconds.quiet period for autobuild-vg-autotest is 0 seconds.quiet period for scanbuild-vg-autotest is 0 seconds.Finished Build : #333 of Job : unittest-vg-autotest with status : FAILURE at 01:59:46
Scanning failed job console output using parsing rule file /var/jenkins_home/retry_rules/unexpected_termination_of_channel.
Failed the build, the failure doesn't match the rules.
Finished Build : #334 of Job : autobuild-vg-autotest with status : FAILURE at 01:59:46
Scanning failed job console output using parsing rule file /var/jenkins_home/retry_rules/unexpected_termination_of_channel.
Failed the build, the failure doesn't match the rules.
Finished Build : #335 of Job : scanbuild-vg-autotest with status : FAILURE at 01:59:46
Scanning failed job console output using parsing rule file /var/jenkins_home/retry_rules/unexpected_termination_of_channel.
Failed the build, the failure doesn't match the rules.
Build step 'Conditional step (single)' marked build as failure
```

**Comment by spdkci** [comment] 2021-12-06 03:06
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_63110.html

**Comment by spdkci** [comment] 2021-12-06 14:04
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_63164.html

**Comment by spdkci** [comment] 2021-12-15 21:45
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_63790.html

**Comment by spdkci** [comment] 2021-12-22 21:49
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_64458.html

**Comment by spdkci** [comment] 2022-01-14 12:51
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_68193.html

**Comment by spdkci** [comment] 2022-01-14 23:59
Another instance of this failure. Reported by @mkenguva. log: https://ci.spdk.io/public_build/autotest-per-patch_68100.html

**Comment by spdkci** [comment] 2022-01-17 10:36
Another instance of this failure. Reported by @rafalste. log: https://ci.spdk.io/public_build/autotest-per-patch_68342.html

**Comment by spdkci** [comment] 2022-01-17 13:46
Another instance of this failure. Reported by @rafalste. log: https://ci.spdk.io/public_build/autotest-per-patch_68372.html

**Comment by spdkci** [comment] 2022-01-25 12:00
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_69139.html

**Comment by spdkci** [comment] 2022-01-25 12:01
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_69133.html

**Comment by spdkci** [comment] 2022-01-25 12:01
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_69134.html

**Comment by spdkci** [comment] 2022-01-25 12:03
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_69136.html

**Comment by spdkci** [comment] 2022-01-25 12:03
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_69135.html

**Comment by spdkci** [comment] 2022-01-25 12:04
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_69137.html

**Comment by spdkci** [comment] 2022-01-27 16:18
Another instance of this failure. Reported by @spdkci. log: https://ci.spdk.io/public_build/autotest-per-patch_69463.html

**Comment by xjjx** [comment] 2022-02-02 06:59
it happens when test (jenkins build) fails on early stage e.g. fetching sources - in most cases it's a network issue.
Some initial work on this issue has been made - patch for CI is in progress.

**Comment by spdkci** [comment] 2022-02-04 13:42
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_70524.html

**Comment by spdkci** [comment] 2022-02-04 22:34
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_70534.html

**Comment by ksztyber** [comment] 2022-02-08 15:33
[Bug scrub] Patches that fix the "logs have not been generated" are still under review. Once they're merged the fail will still occur (the root cause is the network issue), but the logs will indicate that. Once we change the way sources are checked out (single check out and gzipped them to all the machines), the network situation should improve.

**Comment by xjjx** [comment] 2022-02-18 09:09
patches for CI has been merged. I'll keep issue open for a while to prove that problem is gone.

**Comment by xjjx** [comment] 2022-02-22 13:00
I believe that problem has gone away.

**Closed by xjjx** 2022-02-22 13:00 UTC
Labels: Infrastructure, Intermittent Failure

**Comment by spdkci** [comment] 2022-06-08 09:19
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_78398.html

**Comment by spdkci** [comment] 2022-06-08 09:20
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_78401.html

**Comment by spdkci** [comment] 2022-06-08 09:57
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_78411.html

**Comment by spdkci** [comment] 2024-08-01 15:22
Another instance of this failure. Reported by @anton-nayshtut. log: https://ci.spdk.io/public_build/autotest-per-patch_127526.html
