### ISSUE TITLE
START TEST nvmf_nmic: 

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1297] opened 2020-03-20 14:24 UTC
I haven't seen this kind of claim ordering issue in a while.

bdev.c:5230:bdev_open: *ERROR*: Could not open Malloc0 - NVMe-oF Target module already claimed it
subsystem.c:1190:spdk_nvmf_subsystem_add_ns: *ERROR*: Subsystem nqn.2016-06.io.spdk:cnode2: bdev Malloc0 cannot be opened, error=-1
nvmf_rpc.c: 988:nvmf_rpc_ns_paused: *ERROR*: Unable to add namespace
request:
{
  "nqn": "nqn.2016-06.io.spdk:cnode2",
  "namespace": {
    "bdev_name": "Malloc0"
  },
  "method": "nvmf_subsystem_add_ns",
  "req_id": 1
}
Got JSON-RPC error response

**Comment by spdkci** [comment] 2020-03-20 14:25
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_7005.html

**Comment by spdkci** [comment] 2020-03-23 01:34
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_7076.html

**Comment by changpe1** [comment] 2020-03-23 01:39
@glodfish-zg Could you take a look? Thanks.

**Comment by glodfish-zg** [comment] 2020-03-23 02:20
ok， got it.

**Comment by changpe1** [comment] 2020-03-23 04:15
> ok， got it.
rdma.c:2748:spdk_nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 192.168.100.9 port 4420 ***
 04:47:26	# nvme connect -t rdma -n nqn.2016-06.io.spdk:cnode1 -a 192.168.100.8 -s 4420
 04:47:26	# nvme connect -t rdma -n nqn.2016-06.io.spdk:cnode1 -a 192.168.100.9 -s 4420
Failed to write to /dev/nvme-fabrics: Invalid argument

Here is the log from dmesg.log
[  303.211544] nvme nvme1: rdma_connect failed (-22).
[  303.218823] nvme nvme1: rdma connection establishment failed (-22)

Maybe there were errors before this tests.

**Comment by spdkci** [comment] 2020-03-23 07:49
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_7422.html

**Comment by spdkci** [comment] 2020-03-23 14:14
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_7467.html

**Comment by spdkci** [comment] 2020-03-24 06:51
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_7568.html

**Comment by spdkci** [comment] 2020-03-24 16:35
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_7656.html

**Comment by spdkci** [comment] 2020-03-24 16:35
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_7644.html

**Comment by glodfish-zg** [comment] 2020-03-25 02:13
The issue should be：
test case2: host connect to nvmf target in multiple paths
 09:41:23	# '[' -n 192.168.100.9 ']'
 09:41:23	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.9 -s 4420
rdma.c:2748:spdk_nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 192.168.100.9 port 4420 ***
 09:41:23	# nvme connect -t rdma -n nqn.2016-06.io.spdk:cnode1 -a 192.168.100.8 -s 4420
 09:41:24	# nvme connect -t rdma -n nqn.2016-06.io.spdk:cnode1 -a 192.168.100.9 -s 4420
Failed to write to /dev/nvme-fabrics: Invalid argument

in test/nvmf/target/nmic.sh:45 -> main(["--transport=rdma"])
     ...
   40  	echo "test case2: host connect to nvmf target in multiple paths"
   41  	if [ -n "$NVMF_SECOND_TARGET_IP" ]; then
   42  		$rpc_py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a $NVMF_SECOND_TARGET_IP -s $NVMF_PORT
   43  	
   44  		nvme connect -t $TEST_TRANSPORT -n "nqn.2016-06.io.spdk:cnode1" -a "$NVMF_FIRST_TARGET_IP" -s "$NVMF_PORT"
=> 45  		nvme connect -t $TEST_TRANSPORT -n "nqn.2016-06.io.spdk:cnode1" -a "$NVMF_SECOND_TARGET_IP" -s "$NVMF_PORT"
   46  	
   47  		waitforserial "$NVMF_SERIAL"
   48  	
   49  		$rootdir/scripts/fio.py -p nvmf -i 4096 -d 1 -t write -r 1 -v
   50  	fi

Changpeng supply the dmesg log:
[ 303.211544] nvme nvme1: rdma_connect failed (-22).
[ 303.218823] nvme nvme1: rdma connection establishment failed (-22)

The first IP connect successfully but the second failed.

**Comment by optimistyzy** [comment] 2020-03-25 02:26
Is it related with this issue:  https://lore.kernel.org/linux-nvme/20191018091016.GA25478@lst.de/T/ ?

**Comment by optimistyzy** [comment] 2020-03-25 05:04
Suggest to add this check: To make sure every time the controller is removed: https://review.spdk.io/gerrit/c/spdk/spdk/+/1447

**Comment by spdkci** [comment] 2020-03-25 08:26
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_7767.html

**Comment by spdkci** [comment] 2020-03-25 14:23
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_7738.html

**Comment by glodfish-zg** [comment] 2020-03-27 05:40
@Seth5141.  could you help to take a look, you are more familiar with rdma. Thanks.

**Comment by spdkci** [comment] 2020-03-30 06:01
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_8210.html

**Comment by spdkci** [comment] 2020-03-30 07:30
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_8222.html

**Comment by spdkci** [comment] 2020-04-01 10:17
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_8683.html

**Comment by spdkci** [comment] 2020-04-01 13:34
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_8722.html

**Comment by Seth5141** [comment] 2020-04-01 22:05
Hi all,

I did some looking into this and can confirm that it's failing in response to a call to rdma_connect within the kernel. See the kernel source at drivers/infiniband/core/cma.h:rdma_connect. Unfortunately, within that function there are lots of possible reasons for -EINVAL to be returned. None of them print any debug information so it doesn't really help us when trying to figure out where the failure is. Unless I can get a consistent reproduction such that I can rebuild a kernel with more debug prints, this may be a dead end.

I also notice something interesting about the machines reporting this error. We only see this on WP4 and GP14, but there are 4 machines running the NVMe-oF physical tests.

I noticed that the two machines that don't ever show this error are running either newer or older kernels than the ones that do.

For example, GP2 appears to be running 5.5.10. @karlatec I wanted to check with you to make sure it would be OK to upgrade the kernel on WP4 and GP14 to see if that makes this error go away.

**Comment by changpe1** [comment] 2020-04-02 04:32
[Bug Scrub] Let see if the issue still exist or not after updating to a new kernel version.

**Comment by spdkci** [comment] 2020-04-02 07:31
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_8751.html

**Comment by karlatec** [comment] 2020-04-02 07:48
@Seth5141 
Updated kernel to 5.5.10 on GP14 and WP4. See if that helps.

**Comment by spdkci** [comment] 2020-04-03 06:42
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_8939.html

**Comment by spdkci** [comment] 2020-04-06 08:11
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_9137.html

**Comment by spdkci** [comment] 2020-04-07 22:16
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_9438.html

**Comment by spdkci** [comment] 2020-04-07 22:32
Another instance of this failure. Reported by @benlwalker. log: https://ci.spdk.io/public_build/autotest-per-patch_9437.html

**Comment by spdkci** [comment] 2020-04-09 08:08
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_9715.html

**Comment by spdkci** [comment] 2020-04-09 12:18
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_9818.html

**Comment by spdkci** [comment] 2020-04-15 14:18
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_10578.html

**Comment by spdkci** [comment] 2020-04-15 14:18
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_10553.html

**Comment by spdkci** [comment] 2020-04-19 15:02
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_11061.html

**Comment by spdkci** [comment] 2020-04-21 06:21
Another instance of this failure. Reported by @liang2yan. log: https://ci.spdk.io/public_build/autotest-per-patch_11260.html

**Comment by spdkci** [comment] 2020-04-23 08:29
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_11570.html

**Comment by spdkci** [comment] 2020-04-23 15:53
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_11638.html

**Comment by spdkci** [comment] 2020-04-23 16:28
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_11640.html

**Comment by spdkci** [comment] 2020-04-23 18:15
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_11642.html

**Comment by spdkci** [comment] 2020-04-29 05:14
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_12013.html

**Comment by spdkci** [comment] 2020-04-30 15:28
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_12230.html

**Comment by spdkci** [comment] 2020-04-30 15:29
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_12223.html

**Comment by spdkci** [comment] 2020-05-06 07:53
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_12430.html

**Comment by spdkci** [comment] 2020-05-08 00:02
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_11870.html

**Comment by spdkci** [comment] 2020-05-08 08:54
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_12733.html

**Comment by spdkci** [comment] 2020-05-08 10:25
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_12740.html

**Comment by spdkci** [comment] 2020-05-12 15:05
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_13530.html

**Comment by spdkci** [comment] 2020-05-14 01:03
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_13771.html

**Comment by spdkci** [comment] 2020-05-26 04:37
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_14871.html

**Comment by spdkci** [comment] 2020-05-27 04:59
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_14876.html

**Comment by spdkci** [comment] 2020-05-28 22:21
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_15178.html

**Comment by spdkci** [comment] 2020-05-29 13:29
Another instance of this failure. Reported by @tkulasek. log: https://ci.spdk.io/public_build/autotest-per-patch_15281.html

**Comment by spdkci** [comment] 2020-06-01 07:50
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_15630.html

**Comment by spdkci** [comment] 2020-06-15 08:49
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_18275.html

**Comment by spdkci** [comment] 2020-06-18 15:35
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_18625.html

**Comment by spdkci** [comment] 2020-06-20 11:53
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_18894.html

**Comment by spdkci** [comment] 2020-06-26 06:21
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_19367.html

**Comment by spdkci** [comment] 2020-06-26 06:41
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_19305.html

**Comment by spdkci** [comment] 2020-06-26 06:42
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_19307.html

**Comment by spdkci** [comment] 2020-06-26 09:20
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_18894.html

**Comment by spdkci** [comment] 2020-07-09 10:21
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_20973.html

**Comment by spdkci** [comment] 2020-07-14 21:21
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_21296.html

**Comment by spdkci** [comment] 2020-07-30 05:33
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_23360.html

**Comment by yidong0635** [comment] 2020-07-30 07:01
Just reproduced the same issue,  the first target IP is the same with the second one. that leads to this issue.
https://review.spdk.io/gerrit/c/spdk/spdk/+/3590

**Comment by spdkci** [comment] 2020-08-05 06:11
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_23704.html

**Comment by spdkci** [comment] 2020-08-05 06:11
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_23703.html

**Comment by spdkci** [comment] 2020-08-05 13:48
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_23714.html

**Comment by spdkci** [comment] 2020-08-05 17:10
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_23712.html

**Comment by spdkci** [comment] 2020-08-06 18:06
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_23815.html

**Comment by spdkci** [comment] 2020-08-06 18:07
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_23813.html

**Comment by spdkci** [comment] 2020-08-10 05:18
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_23936.html

**Comment by spdkci** [comment] 2020-08-10 13:09
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_23960.html

**Comment by yidong0635** [comment] 2020-08-14 04:41
test has been changed to different ports to test multi-paths, maybe this issue can be closed.

**Comment by tomzawadzki** [comment] 2020-08-19 09:17
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/3590 has been merged a week ago, since then no new reports showed up.
Thank you @yidong0635 for resolving this long standing and often occurring issue !

**Closed by tomzawadzki** 2020-08-19 09:17 UTC
Labels: Infrastructure, Intermittent Failure
