### ISSUE TITLE
[nvmf_filesystem_no_incapsule] Failed to write to /dev/nvme-fabrics: Connection timed out

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#1913] opened 2021-04-26 12:14 UTC
[nvmf-tcp-phy-autotest] -> [nvmf_filesystem_no_incapsule] Ci reports connection time out after listening on 10.0.0.2 port 4420

## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/43310/archive/nvmf-tcp-phy-autotest/build.log

## Execution failed at

00:04:39.831   18:50:50	# /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001
00:04:40.043   18:50:50	# /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc1
00:04:40.256   18:50:50	# /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 10.0.0.2 -s 4420
00:04:40.419  [2021-04-23 18:50:50.959702] tcp.c: 745:nvmf_tcp_listen: *NOTICE*: *** NVMe/TCP Target Listening on 10.0.0.2 port 4420 ***
00:04:40.433   18:50:50	# nvme connect -t tcp -n nqn.2016-06.io.spdk:cnode1 -a 10.0.0.2 -s 4420
**00:04:43.530  Failed to write to /dev/nvme-fabrics: Connection timed out**
00:04:43.531    18:50:54	# trap - ERR
00:04:43.531    18:50:54	# print_backtrace
00:04:43.531    18:50:54	# [[ ehxBET =~ e ]]
00:04:43.531    18:50:54	# args=("${BASH_ARGV[@]}")
00:04:43.532    18:50:54	# local args
00:04:43.532    18:50:54	# xtrace_disable
00:04:43.532    18:50:54	# '[' no '!=' yes ']'
00:04:43.532    18:50:54	# PREV_BASH_OPTS=ehxBET
00:04:43.532    18:50:54	# [[ ehxBET == *\x* ]]
00:04:43.532    18:50:54	# XTRACE_DISABLED=yes
00:04:43.532    18:50:54	# set +x
00:04:43.532  ========== Backtrace start: ==========
00:04:43.532  
00:04:43.540  in test/nvmf/target/filesystem.sh:55 -> nvmf_filesystem_part(["0"])
00:04:43.540       ...
00:04:43.541     50  		$rpc_py bdev_malloc_create $MALLOC_BDEV_SIZE $MALLOC_BLOCK_SIZE -b Malloc1
00:04:43.541     51  		$rpc_py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s $NVMF_SERIAL
00:04:43.541     52  		$rpc_py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc1
00:04:43.541     53  		$rpc_py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_PORT
00:04:43.541     54  	
00:04:43.541  => 55  		nvme connect -t $TEST_TRANSPORT -n "nqn.2016-06.io.spdk:cnode1" -a "$NVMF_FIRST_TARGET_IP" -s "$NVMF_PORT"

**Comment by spdkci** [comment] 2021-04-26 12:16
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_43310.html

**Comment by karlatec** [comment] 2021-04-26 12:37
Looks like a duplicate of #1900

**Closed** 2021-04-27 16:38 UTC
Labels: Intermittent Failure
