### ISSUE TITLE
SPDK  has no better performance than libaio according to fio test

### ISSUE THREAD

**Issue by lh2debug** [spdk/spdk#517] opened 2018-11-26 09:31 UTC
## Questions

I used fio to test the performance of SPDK and libaio in different threads, different io modes(randread, etc). I did not find the performance advantages of SPDK.

How can I use the SPDK or in what scenarios can reflect the performance advantages of SPDK? 

Thanks!!

The test result using libaio is as follows:
```


Raw test
IO Depth vary in 1  4  16  64
rw mode randrw
Throughput(MB/s) 1885 1887 1886 1888 
Latency(us) 63 257 1037 4127 
rw mode read
Throughput(MB/s) 2274 2280 2282 2281 
Latency(us) 52.83 209.79 857.66 3457.37 
rw mode randread
Throughput(MB/s) 2281 2282 2281 2283 
Latency(us) 52.60 211.39 857.58 3438.33 
rw mode write
Throughput(MB/s) 1483 2126 2126 2134 
Latency(us) 82.06 227.41 921.25 3689.52 
rw mode randwrite
Throughput(MB/s) 2129 2135 2131 2136 
Latency(us) 56.19 224.84 914.99 3651.44 

Number of threads vary in 1 4 16 64
rw mode randrw
Throughput(MB/s) 875 1852 1871 1886 
Latency(us) 142 263 1038 4111 
rw mode read
Throughput(MB/s) 941 2197 2274 2281 
Latency(us) 132.28 222.77 860.53 3442.80 
rw mode randread
Throughput(MB/s) 912 1819 2280 2281 
Latency(us) 136.45 211.63 861.33 3438.68 
rw mode write
Throughput(MB/s) 885 1489 2117 2119 
Latency(us) 140.59 330.51 927.10 3694.44 
rw mode randwrite
Throughput(MB/s) 629 2025 2133 2135 
Latency(us) 198.13 235.78 927.24 3640.62 

Blocksize vary in 4k  16k  64k  256k
rw mode randrw
Throughput(MB/s) 1874 2024 2178 2270 
Latency(us) 2066 6805 26077 96840 
rw mode read
Throughput(MB/s) 2280 2353 2515 2550 
Latency(us) 1725.74 5826.72 21466.54 82190.21 
rw mode randread
Throughput(MB/s) 2279 2354 2491 2544 
Latency(us) 1737.95 5738.57 21368.24 83798.11 
rw mode write
Throughput(MB/s) 2110 2150 2116 2139 
Latency(us) 1866.79 6674.61 26649.79 101908.60 
rw mode randwrite
Throughput(MB/s) 2135 2148 2127 2139 
Latency(us) 1833.25 6678.23 26192.84 107960.02 
READ(%) percent of mix read/write vary in 0 25 50 75 100
Throughput(MB/s) 2138 1892 1877 1989 2267 
Latency(us) 1848 2066 2076 1971 1726 
```

The test result using SPDK is as follows:

```
SPDK test
IO Depth vary in 1  4  16  64
rw mode randrw
Throughput(MB/s) 1892 1900 1900 1900 
Latency(us) 62 253 1018 4078 
rw mode read
Throughput(MB/s) 2280 2282 2285 2284 
Latency(us) 52.39 211.57 847.34 3393.04 
rw mode randread
Throughput(MB/s) 2284 2285 2284 2283 
Latency(us) 52.20 211.20 847.67 3394.16 
rw mode write
Throughput(MB/s) 2132 2163 2160 2153 
Latency(us) 56.05 223.21 896.39 3598.55 
rw mode randwrite
Throughput(MB/s) 2152 2173 2174 2174 
Latency(us) 55.48 222.12 890.37 3564.45 

Number of threads vary in 1 4 16 64
rw mode randrw
Throughput(MB/s) 1882 1890 1896 1900 
Latency(us) 66 264 1054 2038 
rw mode read
Throughput(MB/s) 1776 1549 2089 2283 
Latency(us) 70.05 322.39 957.08 1696.15 
rw mode randread
Throughput(MB/s) 1814 2283 2284 2284 
Latency(us) 68.56 218.67 875.17 1695.53 
rw mode write
Throughput(MB/s) 2120 462 353 2153 
Latency(us) 58.60 1081.22 5667.93 1799.36 
rw mode randwrite
Throughput(MB/s) 2160 2166 2169 2171 
Latency(us) 57.50 230.47 921.48 1784.37 

Blocksize vary in 4k  16k  64k 256k
rw mode randrw
Throughput(MB/s) 1902 2047 2243 2298 
Latency(us) 2037 7569 27636 107 
rw mode read
Throughput(MB/s) 2275 2356 2525 2554 
Latency(us) 1702.72 6577.05 24552.36 97102.31 
rw mode randread
Throughput(MB/s) 2285 2353 2528 2559 
Latency(us) 1695.13 6586.20 24527.32 96896.07 
rw mode write
Throughput(MB/s) 2169 2192 2035 2167 
Latency(us) 1785.31 7070.78 30461.29 114422.41 
rw mode randwrite
Throughput(MB/s) 2158 2183 2163 2161 
Latency(us) 1794.43 7100.56 28658.64 114.76 
READ percent of mix read/write vary in 0 25 50 75 100
Throughput(MB/s) 2172 1918 1901 2005 2284 
Latency(us) 1783 2020 2037 1931 1695 


```

The fio default arguments are as follows:

```

direct=1
iodepth=32
ioengine=spdk
bs=4K
size=2G
numjobs=31
runtime=100
name=mytest


```

## Context (Environment including OS version, SPDK version, etc.)

**My OS version is Centos 7.4 running on a physical machine and my SPDK/DPDK version is SPDK v18.10-pre / DPDK 18.08.0.**

```
[root@localhost spdk]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core) 

```
**My NVMe drivers are one intel optane SSD DC P4800X SERIES.**

**Comment by ak-gh** [comment] 2018-11-26 10:35
Fio doesn't have an option named 'isdirect'. If your goal is to bypass the kernel buffer cache, use 'direct=1'.

Regards,
Andrey

**Comment by lh2debug** [comment] 2018-11-26 10:41
Thanks. I actually use "direct=1" argument, the key point is that SPDK has no better performance than libaio according to fio test and my goal is to know why ?

**Comment by peluse** [comment] 2018-11-26 13:10
As @ak-gh requested, please include everything needed to reproduce your results including:
* your fio version
* your compete fio config file
* the exact cmd line you are using to drive the test
The first step many of us would take, besides examining the supplied config for obvious issues would be to reproduce so the more information you can provide the better.  Thanks!

**Comment by jimharris** [comment] 2018-11-26 15:22
Hi @lh2debug,

Are you using the SPDK nvme fio plugin or bdev fio plugin?  If it's the bdev fio plugin, please also provide the SPDK config file you are using.

-Jim

**Comment by jrgruher** [comment] 2018-11-26 16:09
If I can throw in my two cents here, I think the problem is really the premise of the question.  

If you're running FIO against a single NVMe device using libaio with significant number of jobs and/or a significant queue depth, you're going to be able to saturate the NVMe device and get the maximum performance it can offer.  SPDK cannot somehow make that single NVMe device go faster than libaio if the device is already reaching its maximum performance with libaio.  The device only goes so fast at the end of the day.  It is just not correct to assume SPDK should always be able to make your device go faster.

Examples of the possible benefits of SPDK as I understand them, rather than just "should go faster" are:
--potentially lower IO latency
--potentially lower IO latency jitter (better 90% and 99% latency in FIO for example)
--potentially less CPU utilization relatively to IOPS/bandwidth
--potentially higher performance in some scenarios, like low load scenarios where the NVMe device is not being saturated, or if your CPU is saturated when not using SPDK

This performance report, while for NVMeoF instead of local NVMe, I think has some helpful guidance on how to look at SPDK benefits for latency and for CPU utilization:
https://ci.spdk.io/download/performance-reports/SPDK_nvmeof_perf_report_18.04.pdf
(Test case 3 for latency and test case 4 for performance relative to CPU utilization)

**Comment by lh2debug** [comment] 2018-11-27 12:29
Thanks. @ak-gh @peluse 

### FIO config

The fio command of raw test is as follows:


```
fio -filename=/dev/nvme0n1 -direct=1 -norandommap -iodepth $iodp -thread -rw=$iomode -ioengine=libaio -bs=$bsz -size=2G -numjobs=$numj -runtime=100 -group_reporting -name=mytest
```
$iodp, $bsz, $numj, $iomode change in different tests.

The fio command of spdk test is as follows:

```
env LD_PRELOAD=/root/lab505/lhh/src/spdk_src/spdk/examples/nvme/fio_plugin/fio_plugin fio ./sam_config.fio -norandommap -ioengine=spdk -thread -iodepth=$iodp -bs=$bsz -rw=$iomode -runtime=100 -numjobs=$numj
```
$iodp, $bsz, $numj, $iomode change in different tests.

The content of sam_config.fio is as follows:

```

[global]
group_reporting=1
direct=1
verify=0
time_based=1
ramp_time=0

filename=trtype=PCIe traddr=0000.04.00.0 ns=1

[test]

```
### fio version
v 3.3

@jimharris 
I used the SPDK nvme fio plugin.

**Comment by lh2debug** [comment] 2018-11-27 12:31
Thanks @jrgruher 

According to the report you offered, we can find that nvme-of has lower latency than linux kernel. But for the local nvme interface of spdk, according to the test result, spdk has no higher throughput and no lower lantency than libaio. But spdk has a higher cpu utilization(libaio 's idle is about 70%. spdk 's idle is about 30%). It is hard to see the benefits of the local nvme interface of spdk.

**Comment by peluse** [comment] 2018-11-27 14:35
Didn't mean to hit the close button... oops.  @vermavis is there a general kernel vs spdk local nvme interface report somewhere that can help save further Q&A here - would be great to have data from a controlled test like the one @jrgruher referenced above?

**Comment by vermavis** [comment] 2018-11-27 14:42
Yes-  we definitely have kernel vs. SPDK local I/O performance data which we plan to publish soon @KariukiJ Do you know the latest on that one?

**Comment by KariukiJ** [comment] 2018-11-27 15:15
The local NVMe kernel vs SPDK report is published at https://ci.spdk.io/download/performance-reports/SPDK_nvme_bdev_perf_report_18.04.pdf

**Comment by lh2debug** [comment] 2018-11-28 07:36
Thanks, @KariukiJ 


According to the report you offered, compared with LIBAIO, one of the advantages of SPDK is that there is higher IOPS when accessing multiple SSDs concurrently. SPDK's iops does not show an advantage when accessing a single SSD.

And SPDK has a lower latency than LIBAIO, which is not consistent with my test results and should be related to the kernel mode(classic polling, hybrid polling, default).


I do not have other questions, if there is no doubt then we can close this issue.

**Comment by vermavis** [comment] 2018-11-28 15:57
@lh2debug 
I missed what is your backend storage? If you are using NAND device, then the media latency is very high compared to the S/W latency. 
 
However, if you were to use a very low latency drive like Optane  you should see substantial difference in latency b/w SPDK vs. libaio (especially for lower iodepths).

**Comment by KariukiJ** [comment] 2018-11-28 22:29
@lh2debug 
I need some help understanding your results. 
Looking at SPDK test results
---------------------------------------------------------------------------------------------------------
IO Depth vary in 1  4  16  64
rw mode randrw
Throughput(MB/s) 1892 1900 1900 1900 
Latency(us) 62 253 1018 4078
--------------------------------------------------------------------------------------------------------- 
So does this mean that for QD=1, throughput = 1892 MB/s and Latency= 62 usec. Is that data for a 4K block size?

Looks like your using an Intel Optane SSD DC P4800X. The latency we see in our testing for 4K Rand Read (QD=1) with Optane P4800 SSDs and SPDK are usually in the 7 - 8 usecs and the Kernel with libaio numbers are usually around 15 usecs. I looked at the data from my last test on Optane I see that I got latency of about 56 usecs at about QD=16, which compares to the latency numbers your showing. Can you double check your queue depth settings?

Also, looking at your Throughput numbers I see something pretty interesting, it looks like the throughput peaked right away at around 1900 MB/s so it sounds like your hitting some kind of saturation point right away. Note with Optane SSDs the IOPS saturate at queue depth as low as 8, so doing the test with a queue depth higher than 8 just indicates the device is saturated.

**Comment by lh2debug** [comment] 2018-11-29 02:38
The parameters that affect the latency are numjobs and queue depth. The reason for the high latency of my test is that the default numjobs=31, even if the queue depth is small(QD=1).
When I set numjobs=1 and queue depth=1, the average latency of spdk is  7 - 8 us. The throughput of spdk is 496MB/s. the average lantency of libaio is 26 - 27 us. The throughput of libaio is 133MB/s.


**Can we get the following conclusions?
For accessing single nvme device, when the numjobs and queue depth are small. spdk have great advantage over libaio on the latency and throughput. But when the numjobs and queue depth are big, spdk do not show too much advantages.** 



spdk test result is as follow:
```
[root@ceph-master spdk_test]# env LD_PRELOAD=/root/lab505/lhh/src/spdk_src/spdk/examples/nvme/fio_plugin/fio_plugin fio ./sam_config.fio -norandommap -ioengine=spdk -thread -iodepth=1 -bs=4K -rw=randread -runtime=10 -numjobs=1
test: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk, iodepth=1
fio-3.3
Starting 1 thread
Starting SPDK v19.01-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 512 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid96235 ]
EAL: Detected 24 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Probing VFIO support...
EAL: PCI device 0000:04:00.0 on NUMA socket 0
EAL:   probe driver: 8086:2701 spdk_nvme
Jobs: 1 (f=1): [r(1)][100.0%][r=497MiB/s,w=0KiB/s][r=127k,w=0 IOPS][eta 00m:00s]
test: (groupid=0, jobs=1): err= 0: pid=96263: Thu Nov 29 09:59:06 2018
   read: IOPS=127k, BW=496MiB/s (520MB/s)(4963MiB/10000msec)
    slat (nsec): min=134, max=12425, avg=156.56, stdev=40.93
    clat (usec): min=3, max=158, avg= 7.36, stdev= 1.31
     lat (usec): min=6, max=158, avg= 7.51, stdev= 1.31
    clat percentiles (nsec):
     |  1.00th=[ 6944],  5.00th=[ 7072], 10.00th=[ 7072], 20.00th=[ 7136],
     | 30.00th=[ 7200], 40.00th=[ 7200], 50.00th=[ 7264], 60.00th=[ 7264],
     | 70.00th=[ 7328], 80.00th=[ 7328], 90.00th=[ 7392], 95.00th=[ 7456],
     | 99.00th=[ 8640], 99.50th=[14784], 99.90th=[31616], 99.95th=[34560],
     | 99.99th=[36608]
   bw (  KiB/s): min=499944, max=511472, per=100.00%, avg=508252.63, stdev=2333.68, samples=19
   iops        : min=124986, max=127868, avg=127063.26, stdev=583.40, samples=19
  lat (usec)   : 4=0.01%, 10=99.26%, 20=0.58%, 50=0.17%, 100=0.01%
  lat (usec)   : 250=0.01%
  cpu          : usr=100.00%, sys=0.00%, ctx=4, majf=0, minf=1
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=1270604,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=496MiB/s (520MB/s), 496MiB/s-496MiB/s (520MB/s-520MB/s), io=4963MiB (5204MB), run=10000-10000msec

[root@ceph-master spdk_test]# cat sam_config.fio

[global]
group_reporting=1
direct=1
verify=0
time_based=1
ramp_time=0



filename=trtype=PCIe traddr=0000.04.00.0 ns=1
```


libaio test result is as follow:
```
[root@ceph-master ~]# fio -filename=/dev/nvme0n1 -direct=1 -norandommap -iodepth 1 -thread -rw=randread -ioengine=libaio -bs=4K -size=2G -numjobs=1 -runtime=10 -group_reporting -name=mytest
mytest: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
fio-3.3
Starting 1 thread
Jobs: 1 (f=1): [r(1)][100.0%][r=167MiB/s,w=0KiB/s][r=42.7k,w=0 IOPS][eta 00m:00s]
mytest: (groupid=0, jobs=1): err= 0: pid=5468: Thu Nov 29 10:20:49 2018
   read: IOPS=34.1k, BW=133MiB/s (139MB/s)(1330MiB/10001msec)
    slat (usec): min=2, max=225, avg= 7.83, stdev= 5.09
    clat (nsec): min=767, max=645060, avg=18680.93, stdev=7332.83
     lat (usec): min=10, max=650, avg=26.82, stdev= 9.70
    clat percentiles (nsec):
     |  1.00th=[10176],  5.00th=[10432], 10.00th=[10560], 20.00th=[12352],
     | 30.00th=[13888], 40.00th=[15552], 50.00th=[17024], 60.00th=[18816],
     | 70.00th=[20608], 80.00th=[25472], 90.00th=[29824], 95.00th=[31872],
     | 99.00th=[35584], 99.50th=[39680], 99.90th=[58624], 99.95th=[73216],
     | 99.99th=[98816]
   bw (  KiB/s): min=110184, max=243920, per=100.00%, avg=137502.84, stdev=34137.13, samples=19
   iops        : min=27546, max=60980, avg=34375.68, stdev=8534.23, samples=19
  lat (nsec)   : 1000=0.01%
  lat (usec)   : 2=0.07%, 4=0.06%, 10=0.31%, 20=67.07%, 50=32.30%
  lat (usec)   : 100=0.18%, 250=0.01%, 750=0.01%
  cpu          : usr=21.68%, sys=44.05%, ctx=339740, majf=0, minf=53
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=340600,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=133MiB/s (139MB/s), 133MiB/s-133MiB/s (139MB/s-139MB/s), io=1330MiB (1395MB), run=10001-10001msec

Disk stats (read/write):
  nvme0n1: ios=337280/0, merge=0/0, ticks=3780/0, in_queue=3672, util=36.80%

```

**Comment by lh2debug** [comment] 2018-11-29 02:38
@KariukiJ
I set numjobs=31, and I monitored the CPU status through **iostat** and found that the CPU became a bottleneck.

```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          99.98    0.00    0.02    0.00    0.00    0.00
```

**Comment by KariukiJ** [comment] 2018-11-29 15:35
@lh2debug 
Thanks for the information. I understand your test set up and results. Your test set up is storage limitted. Once you hit the limits of what your storage device is capable, there is nothing that software can do to improve performance. At QD=1 you saturate your Optane device by scaling the number of threads: for 4K random read a single thread shows 496 MB/s throughput and your storage device maximum throughput is 1900 MB/s so the device will saturate at approx 4 threads ( 1900 / 496 ) at QD=1 and any additional threads just increase the latency (with no further throughput gains).
SPDK improves CPU efficiency. You can see some efficiency gains with a single P4800x SSD by increasing the queue depth at numjob=1, SPDK saturates the Optane SSD using a single job but you need 2 job to saturate an Optane with the Kernel driver. You get better CPU efficiency as you increase the number of Optane SSDs in your system.

**Comment by jimharris** [comment] 2018-12-13 01:45
Closing this issue - observed behavior is expect.  Thanks @lh2debug for the report and @KariukiJ for the explanations.

**Closed by jimharris** 2018-12-13 01:45 UTC
Labels: question
