### ISSUE TITLE
Can a LUN be added to more than one spdk_scsi_dev ?

### ISSUE THREAD

**Issue by naresh-gottumukkala** [spdk/spdk#100] opened 2017-01-17 09:17 UTC
Hi,

From the code it looks like we can not add a lun (i.e a bdev like /dev/ram0) to more than one spdk_scsi_dev.  But the spdk_scsi_dev_add_lun function in lib/dev.c is not checking for return status of spdk_scsi_lun_claim(lun) before updating dev and id  fields in spdk_scsi_lun structure. Because of this dev and id values of previous spdk_scsi_dev are overwritten by new  spdk_scsi_dev and when user tries to add lun to second spdk_scsi_dev it succeeds.

Since most of the other code depends on lun->dev field like for example spdk_bdev_scsi_report_luns, wrong values are returned. 

Our iscsi.conf

[TargetNode1]
  TargetName disk1
  Mapping PortalGroup1 InitiatorGroup1
  LUN0 Malloc0
  LUN1 Malloc1       

[TargetNode2]
  TargetName disk2
  Mapping PortalGroup2 InitiatorGroup2
  LUN0 Malloc1       # Please note **Malloc1 bdev reused**
  
Can some one please confirm the expected behaviour ?

Thanks & Regards,
Naresh

**Comment by jimharris** [comment] 2017-01-17 16:33
On Jan 17, 2017, at 2:17 AM, naresh-gottumukkala <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

From the code it looks like we can not add a lun (i.e a bdev like /dev/ram0) to more than one spdk_scsi_dev. But the spdk_scsi_dev_add_lun function in lib/dev.c is not checking for return status of spdk_scsi_lun_claim(lun) before updating dev and id fields in spdk_scsi_lun structure. Because of this dev and id values of previous spdk_scsi_dev are overwritten by new spdk_scsi_dev and when user tries to add lun to second spdk_scsi_dev it succeeds.


Hi Naresh,

This is a bug.  The spdk_scsi_dev code should be checking return status when claiming LUNs.

-Jim


Since most of the other code depends on lun->dev field like for example spdk_bdev_scsi_report_luns, wrong values are returned.

Our iscsi.conf

[TargetNode1]
TargetName disk1
Mapping PortalGroup1 InitiatorGroup1
LUN0 Malloc0
LUN1 Malloc1

[TargetNode2]
TargetName disk2
Mapping PortalGroup2 InitiatorGroup2
LUN0 Malloc1 # Please note Malloc1 bdev reused

Can some one please confirm the expected behaviour ?

Thanks & Regards,
Naresh

**Comment by naresh-gottumukkala** [comment] 2017-01-17 16:37
Hi Jim,

Thanks for confirming. Does that mean a lun can not be added to more than one spdk_scsi_dev ?

**Comment by benlwalker** [comment] 2017-01-30 17:09
To confirm - with our current design a LUN cannot be added to more than one spdk_scsi_dev. We do not support "shared LUNs" currently, which would require us to emulate SCSI reservations. This is not to say that it would be impossible to do so in the future.

**Comment by naresh-gottumukkala** [comment] 2017-01-31 08:16
Thanks a lot Ben.

**Comment by benlwalker** [comment] 2018-02-01 04:57
We now support creating multiple luns that point at the same bdev, which is mostly the same thing that was requested here. We still do not emulate SCSI or NVMe reservations in the iSCSI and NVMe-oF targets. I'm going to close this bug out. If SCSI or NVMe reservation emulation is necessary, please open a new issue to request it.

**Closed by benlwalker** 2018-02-01 04:57 UTC
Labels: bug
