### ISSUE TITLE
no request available for FABRICS/CONNECT when running bdevperf w/ ultra high queue depth

### ISSUE THREAD

**Issue by MengjinWu** [spdk/spdk#2371] opened 2022-02-10 09:19 UTC
# Bug report

Using Nvmf over TCP Target to provide   

## Current Behavior

Use one NVmf target to provide multiple blk devices, when testing performance with bdevperf, a lot of error messages appear, and prompt qpair disconnected
After successful reconnection, there are always failed IOs 

Some error messages

> [2022-02-10 08:54:02.859378] nvme_qpair.c: 273:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:4 cid:0 nsid:4 lba:206181408 len:16 PRP1 0x0 PRP2 0x0
> [2022-02-10 08:54:02.859384] nvme_qpair.c: 456:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:4 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
> [2022-02-10 08:54:02.859391] bdev_nvme.c:4523:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
> [2022-02-10 08:54:02.859396] nvme_qpair.c: 559:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
> [2022-02-10 08:54:02.859402] nvme_qpair.c: 537:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
> [2022-02-10 08:54:02.859407] nvme_qpair.c: 273:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:4 cid:0 nsid:4 lba:249832800 len:16 PRP1 0x0 PRP2 0x0
> [2022-02-10 08:54:02.859414] nvme_qpair.c: 456:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:4 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
> [2022-02-10 08:54:02.859420] bdev_nvme.c:4523:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
> [2022-02-10 08:54:02.859426] nvme_qpair.c: 559:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
> [2022-02-10 08:54:02.859431] nvme_qpair.c: 537:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
> [2022-02-10 08:54:02.859438] nvme_qpair.c: 273:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:4 cid:0 nsid:4 lba:2706011424 len:16 PRP1 0x0 PRP2 0x0
> [2022-02-10 08:54:02.859443] nvme_qpair.c: 456:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:4 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
> [2022-02-10 08:54:02.859449] bdev_nvme.c:4523:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
> [2022-02-10 08:54:02.859455] nvme_qpair.c: 559:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
> [2022-02-10 08:54:02.859461] nvme_qpair.c: 537:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
> [2022-02-10 08:54:02.859467] nvme_qpair.c: 273:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:4 cid:0 nsid:4 lba:2015078384 len:16 PRP1 0x0 PRP2 0x0
> [2022-02-10 08:54:02.859473] nvme_qpair.c: 456:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:4 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
> [2022-02-10 08:54:02.859479] bdev_nvme.c:4523:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
> [2022-02-10 08:54:02.859485] nvme_qpair.c: 559:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
> [2022-02-10 08:54:02.859490] nvme_qpair.c: 537:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
> [2022-02-10 08:54:02.859496] nvme_qpair.c: 273:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:4 cid:0 nsid:4 lba:3258553312 len:16 PRP1 0x0 PRP2 0x0
> [2022-02-10 08:54:02.859502] nvme_qpair.c: 456:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:4 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
> [2022-02-10 08:54:02.859509] bdev_nvme.c:4523:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
> [2022-02-10 08:54:02.859516] nvme_qpair.c: 754:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 4
> [2022-02-10 08:54:02.859522] bdev_nvme.c:1082:bdev_nvme_disconnected_qpair_cb: *NOTICE*: qpair 0x110a9e0 is disconnected, free the qpair and reset controller.
> [2022-02-10 08:54:02.859531] bdev_nvme.c:1466:bdev_nvme_reset: *NOTICE*: Unable to perform reset, already in progress.
> [2022-02-10 08:54:02.859574] nvme_ctrlr.c:1640:spdk_nvme_ctrlr_disconnect: *NOTICE*: [nqn.2016-06.io.spdk:cnode2] resetting controller
> [2022-02-10 08:54:02.863302] bdev_nvme.c:1307:_bdev_nvme_reset_complete: *NOTICE*: Resetting controller successful.
> 

Test result:

```
 Job: Nvme0n1 (Core Mask 0x1)
         Nvme0n1             :   41911.17 IOPS     327.43 MiB/s
                             :      17.07 Fail/s     0.00 TO/s
 Job: Nvme0n2 (Core Mask 0x1)
         Nvme0n2             :   40966.17 IOPS     320.05 MiB/s
                             :      17.07 Fail/s     0.00 TO/s
 Job: Nvme0n3 (Core Mask 0x1)
         Nvme0n3             :   40379.50 IOPS     315.46 MiB/s
                             :      17.07 Fail/s     0.00 TO/s
 Job: Nvme0n4 (Core Mask 0x1)
         Nvme0n4             :   39986.10 IOPS     312.39 MiB/s
                             :      17.07 Fail/s     0.00 TO/s
 =============================================================
 Total                       :  163242.93 IOPS    1275.34 MiB/s
                             :      68.27 Fail/s     0.00 TO/s
```

## Steps to Reproduce

target rpc:

```
sudo ./build/bin/nvmf_tgt -m 0x4 -r /tmp/spdk1.sock & 
sleep 2
scripts/rpc.py -s /tmp/spdk1.sock nvmf_create_transport -t TCP -u 8192 -c 8192
scripts/rpc.py -s /tmp/spdk1.sock bdev_nvme_attach_controller -b NVMe1 -t PCIe -a 0000:d8:00.0
scripts/rpc.py -s /tmp/spdk1.sock bdev_nvme_attach_controller -b NVMe2 -t PCIe -a 0000:d9:00.0
scripts/rpc.py -s /tmp/spdk1.sock bdev_nvme_attach_controller -b NVMe3 -t PCIe -a 0000:da:00.0
scripts/rpc.py -s /tmp/spdk1.sock bdev_nvme_attach_controller -b NVMe4 -t PCIe -a 0000:2a:00.0
scripts/rpc.py -s /tmp/spdk1.sock nvmf_create_subsystem nqn.2016-06.io.spdk:cnode2 -a -s SPDK00000000000001 -d SPDK_Controller1
scripts/rpc.py -s /tmp/spdk1.sock nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode2 NVMe1n1
scripts/rpc.py -s /tmp/spdk1.sock nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode2 NVMe2n1
scripts/rpc.py -s /tmp/spdk1.sock nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode2 NVMe3n1
scripts/rpc.py -s /tmp/spdk1.sock nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode2 NVMe4n1
scripts/rpc.py -s /tmp/spdk1.sock nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode2 -t tcp -a 10.0.0.1 -s 4420 -f IPv4
```
bdevperf:
```
./test/bdev/bdevperf/bdevperf -z -r /tmp/spdk2.sock -q 1024 -o 8192 -w randwrite -C -t 30 -f -S 3 &
sleep 2
scripts/rpc.py -s /tmp/spdk2.sock bdev_nvme_attach_controller -b Nvme0 -t tcp -f IPv4 -n nqn.2016-06.io.spdk:cnode2 -a 10.0.0.1 -s 4420
./test/bdev/bdevperf/bdevperf.py -s /tmp/spdk2.sock perform_tests
```

**Comment by jimharris** [comment] 2022-02-10 20:57
This issue isn't specific to nvme on the target, nor multiple devices.  It can happen with a single null block device.  Note also that it fails at QD512, but not QD511.  Here's what is happening with the failing QD512 case.

1) IO queues are created with default number of 512 requests
2) Async connect process starts for TCP IO queue by sending icreq PDU to target.
3) Control returns to bdevperf.  Bdevperf sends 512 I/O.  These 512 I/O consume all of the request objects in the nvme IO qpair.  All of these requests are queued, waiting for the qpair to complete the connect process.
4) bdevperf starts polling the I/O queue
5) we get the completion event for the icreq, and then try to send the FABRICS_CONNECT
6) we cannot allocate a request for the FABRICS_CONNECT since all requests objects are consumed by the queued I/O

@MengjinWu - can you please write a test based on this simpler configuration, that reproduces this issue?  And run it through CI to show that it reproduces there, so that we can check the test in for regular testing.

Working through a couple of ideas on how to fix this...

**Comment by jimharris** [comment] 2022-02-10 22:37
@MengjinWu - can you also retry your test with this series?   https://review.spdk.io/gerrit/c/spdk/spdk/+/11515

**Comment by MengjinWu** [comment] 2022-02-14 02:55
> 

OK I will try to write a test.

**Comment by MengjinWu** [comment] 2022-02-22 09:55
This test shows that patch (https://review.spdk.io/gerrit/c/spdk/spdk/+/11515) fixed this problem. I think I can close the issue now. @jimharris 
https://review.spdk.io/gerrit/c/spdk/spdk/+/11598

**Comment by jimharris** [comment] 2022-02-22 18:41
Thanks @MengjinWu!  Can you fix this patch up so that we could check this test into the repository?  Reopening for now - let's wait to close until the test is merged.

**Comment by jimharris** [comment] 2022-03-31 21:03
> This test shows that patch (https://review.spdk.io/gerrit/c/spdk/spdk/+/11515) fixed this problem. I think I can close the issue now. @jimharris
> 
> Test patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/11598

This patch looks good - I added my +2.  Once we get another maintainer +2 and it's merged, we can close this issue.

**Closed** 2022-03-31 22:53 UTC
Labels: bug, High
