### ISSUE TITLE
[interrupt_mode] cheduler/interrupt.sh@41 -- # (( is_idle[cpu] == 1 ))

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2597] opened 2022-07-21 23:13 UTC
00:09:27.404   00:17:57	-- scheduler/interrupt.sh@37 -- # (( cpu == spdk_main_core ))
00:09:27.404   00:17:57	-- scheduler/interrupt.sh@40 -- # (( cpu != spdk_main_core ))
00:09:27.404   00:17:57	-- scheduler/interrupt.sh@41 -- # (( is_idle[cpu] == 1 ))
00:09:27.404    00:17:57	-- scheduler/interrupt.sh@41 -- # trap - ERR
00:09:27.404    00:17:57	-- scheduler/interrupt.sh@41 -- # print_backtrace
00:09:27.404    00:17:57	-- common/autotest_common.sh@998 -- # [[ ehxBET =~ e ]]
00:09:27.404    00:17:57	-- common/autotest_common.sh@1000 -- # args=()
00:09:27.404    00:17:57	-- common/autotest_common.sh@1000 -- # local args
00:09:27.404    00:17:57	-- common/autotest_common.sh@1002 -- # xtrace_disable
00:09:27.404    00:17:57	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:09:27.404    00:17:57	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:09:27.404    00:17:57	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:09:27.404    00:17:57	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:09:27.404    00:17:57	-- common/autotest_common.sh@19 -- # set +x
00:09:27.404  ========== Backtrace start: ==========
00:09:27.404  
00:09:27.404  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/scheduler/interrupt.sh:41 -> interrupt([])
00:09:27.404       ...
00:09:27.404     36  		for cpu in "${!is_idle[@]}"; do
00:09:27.404     37  			if ((cpu == spdk_main_core)); then
00:09:27.404     38  				((is_idle[cpu] == 0)) # main cpu must not be idle
00:09:27.405     39  			fi
00:09:27.405     40  			if ((cpu != spdk_main_core)); then
00:09:27.405  => 41  				((is_idle[cpu] == 1)) # all cpus except the main cpu must be idle
00:09:27.405     42  			fi
00:09:27.405     43  		done
00:09:27.405     44  	
00:09:27.405     45  		# select 3 cpus except the main one
00:09:27.405     46  		busy_cpus=("${cpus[@]:1:3}") threads=()
00:09:27.405       ...
00:09:27.707  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/scheduler/interrupt.sh:77 -> main([])
00:09:27.707       ...
00:09:27.707     72  		done
00:09:27.707     73  	}
00:09:27.707     74  	
00:09:27.707     75  	exec_under_dynamic_scheduler "$scheduler" -m "$spdk_cpumask" --main-core "$spdk_main_core"
00:09:27.707     76  	
00:09:27.707  => 77  	interrupt
00:09:27.707       ...
00:09:27.707  
00:09:27.707  ========== Backtrace end ==========
00:09:27.707    00:17:57	-- common/autotest_common.sh@1038 -- # xtrace_enable
00:09:27.707    00:17:57	-- common/autotest_common.sh@1039 -- # return 0
00:09:27.707   00:17:57	-- scheduler/interrupt.sh@1 -- # killprocess 243650
00:09:27.707   00:17:57	-- common/autotest_common.sh@822 -- # '[' -z 243650 ']'
00:09:27.707   00:17:57	-- common/autotest_common.sh@826 -- # kill -0 243650
00:09:27.707    00:17:57	-- common/autotest_common.sh@827 -- # uname
00:09:27.707   00:17:57	-- common/autotest_common.sh@827 -- # '[' Linux = Linux ']'
00:09:27.707    00:17:57	-- common/autotest_common.sh@828 -- # ps --no-headers -o comm= 243650
00:09:27.707   00:17:57	-- common/autotest_common.sh@828 -- # process_name=reactor_1
00:09:27.707   00:17:57	-- common/autotest_common.sh@832 -- # '[' reactor_1 = sudo ']'
00:09:27.707   00:17:57	-- common/autotest_common.sh@840 -- # echo 'killing process with pid 243650'
00:09:27.707  killing process with pid 243650
00:09:27.707   00:17:57	-- common/autotest_common.sh@841 -- # kill 243650
00:09:27.707  [2022-07-22 00:17:57.335120] scheduler.c: 359:test_shutdown: *NOTICE*: Scheduler test application stopped.
00:09:27.707   00:17:57	-- common/autotest_common.sh@846 -- # wait 243650
00:09:27.985  POWER: Power management governor of lcore 1 has been set to 'userspace' successfully
00:09:27.985  POWER: Power management of lcore 1 has exited from 'performance' mode and been set back to the original
00:09:27.985  POWER: Power management governor of lcore 2 has been set to 'userspace' successfully
00:09:27.985  POWER: Power management of lcore 2 has exited from 'performance' mode and been set back to the original
00:09:27.985  POWER: Power management governor of lcore 3 has been set to 'userspace' successfully
00:09:27.985  POWER: Power management of lcore 3 has exited from 'performance' mode and been set back to the original
00:09:27.985  POWER: Power management governor of lcore 4 has been set to 'userspace' successfully
00:09:27.985  POWER: Power management of lcore 4 has exited from 'performance' mode and been set back to the original
00:09:27.985  POWER: Power management governor of lcore 37 has been set to 'userspace' successfully
00:09:27.985  POWER: Power management of lcore 37 has exited from 'performance' mode and been set back to the original
00:09:27.986  POWER: Power management governor of lcore 38 has been set to 'userspace' successfully
00:09:27.986  POWER: Power management of lcore 38 has exited from 'performance' mode and been set back to the original
00:09:27.986  POWER: Power management governor of lcore 39 has been set to 'userspace' successfully
00:09:27.986  POWER: Power management of lcore 39 has exited from 'performance' mode and been set back to the original
00:09:27.986  POWER: Power management governor of lcore 40 has been set to 'userspace' successfully
00:09:27.986  POWER: Power management of lcore 40 has exited from 'performance' mode and been set back to the original
00:09:27.986    00:17:57	-- common/autotest_common.sh@970 -- # trap - ERR
00:09:27.986    00:17:57	-- common/autotest_common.sh@970 -- # print_backtrace
00:09:27.986    00:17:57	-- common/autotest_common.sh@998 -- # [[ ehxBET =~ e ]]
00:09:27.986    00:17:57	-- common/autotest_common.sh@1000 -- # args=('/var/jenkins/workspace/nvme-phy-autotest/spdk/test/scheduler/interrupt.sh' 'interrupt_mode')
00:09:27.986    00:17:57	-- common/autotest_common.sh@1000 -- # local args
00:09:27.986    00:17:57	-- common/autotest_common.sh@1002 -- # xtrace_disable
00:09:27.986    00:17:57	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:09:27.986    00:17:57	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:09:27.986    00:17:57	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:09:27.986    00:17:57	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:09:27.986    00:17:5

**Comment by spdkci** [comment] 2022-07-21 23:14
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_80947.html

**Comment by jimharris** [comment] 2022-07-21 23:29
Duplicate of #1950.

I updated the title of #1950 to include part of the failure string.

**Closed by jimharris** 2022-07-21 23:29 UTC
Labels: Intermittent Failure

**Comment by spdkci** [comment] 2022-11-04 15:31
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_88827.html
