### ISSUE TITLE
[env_dpdk] spdk_zmalloc doesn't return zeroed buffer causing the initiator connect attempt to fail

### ISSUE THREAD

**Issue by ZivHirsch13** [spdk/spdk#2106] opened 2021-08-18 17:25 UTC
# Bug report

When trying to connect to SPDK NVMe-oF target with TCP transport, the connection fails and we see in the target: "spdk_sock_readv() failed".

## Expected Behavior

Connect successfully.

## Current Behavior

Fails to connect because _nvmf_tcp_qpair_init_mem_resource_ calls _spdk_dma_zmalloc_, which doesn't return zeroed buffer.

## Possible Solution

I added a debug log right after that zmalloc, and I saw that _tqpair->pdus[i + 1].dif_ctx_ is **not** NULL.
This is why __nvme_tcp_sgl_append_multi_with_md_ is called, instead of __nvme_tcp_sgl_append_multi_.
I fixed it locally by reverting https://github.com/spdk/spdk/commit/d20f41881b35b13959692b3c37522860277e2d52

## Steps to Reproduce

Target:
1. Start NVMF target with the latest SPDK master (v21.07 is also good)
2. Start TCP transport

Initiator:
1. Use 'nvme discover' or 'nvme connect'

**Comment by jimharris** [comment] 2021-08-18 18:17
Hi @ZivHirsch13,

I'm not able to reproduce this with the basic reproduction steps listed.  If you can provide exact repro steps that would be helpful.  Also anything else that might be unique to your environment, including Linux distro and kernel version.

rte_zmalloc_socket() returning a buffer that isn't zeroed is definitely a problem.  We'll want to root cause that in DPDK or the Linux kernel before considering a revert of d20f418.

Thanks,

Jim

**Comment by ZivHirsch13** [comment] 2021-08-19 06:31
@jimharris 
It took some attempts to reproduce it. It doesn't always happen, and it seems that if it doesn't happen on the first attempt (discover or connect), then it won't happen, so I restarted the SPDK app every attempt.
It makes sense because DPDK zeroes memory in rte_free() (eventually calls memset(ptr, MALLOC_POISON, data_len)). In rte_zmalloc_socket() it zeroes memory only if RTE_MALLOC_DEBUG is set, as you can see from the code there.
I think that this is the idea behind https://github.com/spdk/spdk/commit/d20f41881b35b13959692b3c37522860277e2d52, but maybe the problem is allocating memory that wasn't freed before.

Added a debug log:
```
diff --git a/lib/nvmf/tcp.c b/lib/nvmf/tcp.c
index 20dfdbb..3d0e314 100644
--- a/lib/nvmf/tcp.c
+++ b/lib/nvmf/tcp.c
@@ -951,6 +951,7 @@ nvmf_tcp_qpair_init_mem_resource(struct spdk_nvmf_tcp_qpair *tqpair)
                SPDK_ERRLOG("Unable to allocate pdu pool on tqpair =%p.\n", tqpair);
                return -1;
        }
+       SPDK_NOTICELOG("(*****) pdu_in_progress->dif_ctx: %p\n", tqpair->pdus[tqpair->resource_count + 1].dif_ctx);
 
        for (i = 0; i < tqpair->resource_count; i++) {
                struct spdk_nvmf_tcp_req *tcp_req = &tqpair->reqs[i];
```

# Expected Behavior
No discovery log entries to fetch. # Host is not allowed

# Current Behavior
1. Sometimes, as expected, and in the target we see:
`tcp.c: 954:nvmf_tcp_qpair_init_mem_resource: *NOTICE*: (*****) pdu_in_progress->dif_ctx: (nil)
`
2. Sometimes the initiator gets:
Failed to write to /dev/nvme-fabrics: Connection reset by peer

And in the target we see:
```
tcp.c: 954:nvmf_tcp_qpair_init_mem_resource: *NOTICE*: (*****) pdu_in_progress->dif_ctx: 0x2031128cf2a8
nvme_tcp.h: 423:nvme_tcp_read_data: *ERROR*: spdk_sock_recv() failed, errno 22: Invalid argument

```
3. Sometimes the initiator gets:
Failed to write to /dev/nvme-fabrics: Resource temporarily unavailable

The target crashes because of segfault (similar to https://github.com/spdk/spdk/issues/1996), and the last log we see:
`tcp.c: 954:nvmf_tcp_qpair_init_mem_resource: *NOTICE*: (*****) pdu_in_progress->dif_ctx: 0x2031064be928
`

# Steps:
Target:
1. configure && make # nothing special
2. build/bin/nvmf_tgt &
3. scripts/rpc.py nvmf_create_transport -t TCP
4. scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -s SPDK00000000000001 -d SPDK_Controller1
5. scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a <IP> -s 4420

Initiator:
1. nvme discover -t tcp -s 4420 -a <IP>

If it doesn't fail, and in the target you see
`tcp.c: 954:nvmf_tcp_qpair_init_mem_resource: *NOTICE*: (*****) pdu_in_progress->dif_ctx: (nil)`
Then restart the SPDK app in the target and redo the steps.

# Context:
SPDK: v21.07
OS: CentOS Linux release 7.6.1810 (Core) 
Kernel: 3.10.0-957.el7.x86_64

**Comment by Comphix** [comment] 2021-09-01 01:50
@yidong0635 , please take a look at this issue and we will need first to reproduce it in our own environment. Thanks, Gang.

**Comment by jimharris** [comment] 2021-09-01 01:54
> @jimharris
> It took some attempts to reproduce it. It doesn't always happen, and it seems that if it doesn't happen on the first attempt (discover or connect), then it won't happen, so I restarted the SPDK app every attempt.
> It makes sense because DPDK zeroes memory in rte_free() (eventually calls memset(ptr, MALLOC_POISON, data_len)). In rte_zmalloc_socket() it zeroes memory only if RTE_MALLOC_DEBUG is set, as you can see from the code there.
> I think that this is the idea behind [d20f418](https://github.com/spdk/spdk/commit/d20f41881b35b13959692b3c37522860277e2d52), but maybe the problem is allocating memory that wasn't freed before.

I agree that this issue probably only happens with memory that is allocated for the first time.  The kernel is supposed to zero any hugepages before mapping them into the DPDK process, so zeroing the original allocation isn't required.  DPDK and hence SPDK rely on this behavior.

@yidong0635 is going to try to reproduce this here.

**Comment by yidong0635** [comment] 2021-09-01 03:16
Tried this for several times , I can reproduce this on centos 3.10.0-1160.31.1.el7.x86_64 with error:
`Failed to write to /dev/nvme-fabrics: Invalid argument.`
@jimharris @Comphix   Does this kernel version support tcp transport?

**Comment by Comphix** [comment] 2021-09-01 03:18
@ZivHirsch13 ， could you confirm the kernel version for this issue?

**Comment by changpe1** [comment] 2021-09-01 03:26
> Tried this for several times , I can reproduce this on centos 3.10.0-1160.31.1.el7.x86_64 with error:
> `Failed to write to /dev/nvme-fabrics: Invalid argument.`
> but without error on the target side in tcp.c
> @jimharris @Comphix Does this kernel version support tcp transport?

@yidong0635 according to Jim's comments, you may write a simple test application to verify the behavior of spdk_dma_zmalloc(), it's better to know the kernel version when this issue happened.

**Comment by ZivHirsch13** [comment] 2021-09-01 06:17
@jimharris - you were right not to revert.
I encountered another issue that was caused because rte_zmalloc_socket() returned non-zeroed memory.
This time I had a PANIC from DPDK in rte_eal_remote_launch() (not related to TCP).
Full path that led to the PANIC:
`spdk_app_start --> app_setup_env --> spdk_env_init --> rte_eal_init --> rte_service_start_with_defaults --> rte_service_lcore_start --> rte_eal_remote_launch --> rte_panic("cannot read on configuration pipe\n")`
Note: I work with a single core (coremask is 0x20), so rte_service_lcore_start() shouldn't even be called.

@Comphix - I'm using 3.10.0-957.el7.x86_64 (like I wrote in the "Context" section in the second comment here)

**Comment by yidong0635** [comment] 2021-09-01 07:18
Found a nit.  the patch d20f418 has been merged, but the spdk_zmalloc  in test/common/lib/test_env.c keeps the old one with memset.  That maybe leads to unit test can't  discovery any issues about the change.

**Comment by jimharris** [comment] 2021-09-01 15:00
> Found a nit. the patch [d20f418](https://github.com/spdk/spdk/commit/d20f41881b35b13959692b3c37522860277e2d52) has been merged, but the spdk_zmalloc in test/common/lib/test_env.c keeps the old one with memset. That maybe leads to unit test can't discovery any issues about the change.

The unit tests are correct.  patch d20f418 removed the memset because DPDK already ensures the buffer was zeroed.  In the unit tests we have no such guarantee, so we must still memset.

**Comment by yidong0635** [comment] 2021-09-03 04:37
I am going to keep both functions in env.c  and using memcmp to check the spdk_zmalloc, and rename the former function
naming spdk_zmalloc_memset without changing any paramerters, that I can loop comparation with any times , how do you think?

**Comment by yidong0635** [comment] 2021-09-06 04:53
@changpe1 @jimharris  @Comphix  @ZivHirsch13  I have a patch to reproduce this issue, https://review.spdk.io/gerrit/c/spdk/spdk/+/9386 . I ran this locally also . but can't reproduced until now. 
Maybe there are some improvements about these reproduced steps.

**Comment by changpe1** [comment] 2021-09-06 05:43
> @changpe1 @jimharris @Comphix @ZivHirsch13 I have a patch to reproduce this issue, https://review.spdk.io/gerrit/c/spdk/spdk/+/9386 . I ran this locally also . but can't reproduced until now.
> Maybe there are some improvements about these reproduced steps.

Thanks Yidong, if can't reproduce this issue, maybe we can change the `spdk_dma_zmalloc` with `calloc` as a workaround, I don't see any reasons that the `tqpair->pdus` should use dma memory.

**Comment by yidong0635** [comment] 2021-09-14 09:20
Are there any different ideas about this issue?. If not, just change the code according to @changpe1 's idea. @jimharris @Comphix @ZivHirsch13 .

**Comment by jimharris** [comment] 2021-09-14 17:42
> Are there any different ideas about this issue?. If not, just change the code according to @changpe1 's idea. @jimharris @Comphix @ZivHirsch13 .

@changpe1's idea will not work - @ZivHirsch13 indicated other places (not TCP related) that panicked due to non-zeroed memory.

@yidong0635 - can you confirm that you are testing with CentOS Linux release 7.6.1810 (Core)?

**Comment by yidong0635** [comment] 2021-09-15 03:30
@jimharris , tried this on CentOS Linux release 7.6.1810 (Core) again .  still can get such panicked error.  Just report invalid arguments ,AS I known, TCP transport can be supported on a very later kernel version. @ZivHirsch13 what are your `modprobe steps` ?

**Comment by changpe1** [comment] 2021-09-16 04:17
@ZivHirsch13 Do you run your tests on a ARM platform?

**Comment by ZivHirsch13** [comment] 2021-09-16 05:04
@yidong0635 - I use SPDK only on target side. There isn't a problem there related to TCP transport.
The problem is zmalloc doesn't return zeroed memory.
I don't run `modprobe` on the target (I do run `modprobe nvme-tcp` on the initiator).

@changpe1 - No, regular x86.

**Comment by yidong0635** [comment] 2021-09-16 05:25
@ZivHirsch13  Thanks, I can try this with a different initiator with 5.x.x kernel later to see if can reproduce this issue .

**Comment by ZivHirsch13** [comment] 2021-09-16 05:37
@yidong0635 why? The problem is in the target (only target side uses SPDK).

> @jimharris - you were right not to revert.
> I encountered another issue that was caused because rte_zmalloc_socket() returned non-zeroed memory.
> This time I had a PANIC from DPDK in rte_eal_remote_launch() (not related to TCP).
> Full path that led to the PANIC:
> `spdk_app_start --> app_setup_env --> spdk_env_init --> rte_eal_init --> rte_service_start_with_defaults --> rte_service_lcore_start --> rte_eal_remote_launch --> rte_panic("cannot read on configuration pipe\n")`
> Note: I work with a single core (coremask is 0x20), so rte_service_lcore_start() shouldn't even be called.
> 
> @Comphix - I'm using 3.10.0-957.el7.x86_64 (like I wrote in the "Context" section in the second comment here)

As I wrote here - the problem exists also when just starting the SPDK app (don't even need initiator).
Why don't you just do some zmallocs and verify that all the memory you got is zeroed?

**Comment by yidong0635** [comment] 2021-09-16 06:17
I have done that, but can't got the error. From manual testing to using some code testing. I have no way to reproduce it.

**Comment by changpe1** [comment] 2021-09-16 06:19
@ZivHirsch13 We can't reproduce this issue locally, since SPDK uses the API from DPDK directly, I suggest you may narrow down this issue with a simple test tool which just call DPDK APIs directly and then ask help from DPDK guys.

**Comment by jimharris** [comment] 2021-09-16 17:42
> @ZivHirsch13 We can't reproduce this issue locally, since SPDK uses the API from DPDK directly, I suggest you may narrow down this issue with a simple test tool which just call DPDK APIs directly and then ask help from DPDK guys.

Yeah, this looks like a DPDK, Linux kernel or system configuration issue (or combination thereof).

@ZivHirsch13, you could use test/env/mem_callbacks/mem_callbacks.c as a template for creating a focused DPDK-only test case that reproduces the problem on your setup.  Assuming that you get that test to reproduce the issue, posting something on dev@dpdk.org would be the best next step.  Let's keep this issue open here for now, but I'm going to assign it back to you for these next steps.

**Comment by Comphix** [comment] 2021-11-16 04:53
@ZivHirsch13 , any further update on this issue from your side?

**Comment by jimharris** [comment] 2022-06-02 21:38
@ZivHirsch13, please feel free to reopen this issue if you are able to reproduce this in a way that indicates SPDK is the culprit here instead of DPDK or the kernel.

**Closed by jimharris** 2022-06-02 21:38 UTC
Labels: bug, Medium, 3rd party issue, Waiting on Submitter
