### ISSUE TITLE
construct_nvme_bdev timeout if nvmf target and host in the same spdk instance

### ISSUE THREAD

**Issue by wuzhouhui** [spdk/spdk#587] opened 2019-01-18 01:10 UTC
RPC method `construct_nvme_bdev` timeout if nvmf target and host in the same spdk instance

## Expected Behavior

RPC method `construct_nvme_bdev` exited successfully

## Current Behavior

RPC method `construct_nvme_bdev` timeout

## Steps to Reproduce

1. Start nvmf target `./nvmf_tgt`
2. Construct a malloc bdev `python rpc.py construct_malloc_bdev -b malloc0 16 512`
3. Expose malloc0 via nvmf/tcp
  3.1 `python rpc.py nvmf_create_transport -t tcp -p 4`
  3.2 `python rpc.py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -a`
  3.3 `python rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 malloc0`
  3.4 `python rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 10.0.0.70 -s 4420`
4. Construct nvme bdev exposed by nvmf/tcp in the same host `python rpc.py construct_nvme_bdev -b nvme0 -t tcp -a 10.0.0.70 -f ipv4 -s 4420 -n nqn.2016-06.io.spdk:cnode1`. However, rpc method timeout and nvmf target doesn't break following loop in `nvme_tcp_qpair_icreq_send()`:
```
while (tqpair->state == NVME_TCP_QPAIR_STATE_INVALID) {
        nvme_tcp_qpair_process_completions(&tqpair->qpair, 0);
}
```

## Context (Environment including OS version, SPDK version, etc.)

OS: CentOS 7.3
SPDK: 42aa5a262bc in master

**Comment by optimistyzy** [comment] 2019-01-18 06:20
@wuzhouhui In my mind, there will be same issue with RDMA transport. When the client uses the spdk_nvme_probe to connect the remote target. The client needs to obtain some info and then go through down. For example, if you use RDMA transport, it also have the loop to get some info.  Even if you can pass this.  In nvme_fabric_qpair_connect, which can be either called by RDMA and NVMe TCP, there is also for loop.

**Comment by sashakot** [comment] 2019-01-18 09:01
@optimistyzy
Is it a bug or design issue? I mean, if nvmf target (RDMA or TCP) and host are the same instance, is dynamic adding/removing namespaces supported by design?

**Comment by changpe1** [comment] 2019-01-23 09:16
@optimistyzy , I believe this is a bug, can you take a look? thanks.

**Comment by pawelwod** [comment] 2019-01-23 10:17
> Curently，I do not have an idea on this. It is a paradox，if you can create a dev by this by nvme host driver ，then you have a new dev named as nvme0n1 （for example）， then you construct this into a new subsystem， and create a new dev again by nvme host driver，this will cause an inufinite loop

This is separate issue.

Main issue is that the `nvme_tcp_qpair_icreq_send` is blocking the while loop:

```
	while (tqpair->state == NVME_TCP_QPAIR_STATE_INVALID) {
		nvme_tcp_qpair_process_completions(&tqpair->qpair, 0);
	}
```

So if you have target and initiator running on the same SPDK core, target is unable to read the request so no way to answer it.

This is quite important implementation issue because if target is slow or hang without closing connection initiator will also hang. This **must** be changed into asynchronouse way + adding some timeout in this loop.

Please prioritize this.

**Comment by optimistyzy** [comment] 2019-01-23 14:31
@jimharris @benlwalker design issue for both rdma and tcp transport。 There is also simliar while loop in common fabrics code.

**Comment by optimistyzy** [comment] 2019-01-23 14:37
@pawelwod I can add a timeout

**Comment by pawelwod** [comment] 2019-01-23 14:46
Timeout is a workaround here.
Final fix must make probe code into async way as the timeout is not responding (how long the timout should be?).

**Comment by optimistyzy** [comment] 2019-01-23 14:55
async is not ok for the initiator since we cannot use thread model（to spawn
a thread and use a poller）， so who will call the async？SInce  initiator
call spdk_nvme_probe to get the the controller，it is a single function call

在 2019年1月23日星期三，pawelwod <notifications@github.com> 写道：

**Comment by pawelwod** [comment] 2019-01-23 15:00
> SInce initiator call spdk_nvme_probe to get the the controller，it is a single function call

I don't have the answer. This is a design problem that need to be fixed :) But for sure it shouldn't block.

**Comment by optimistyzy** [comment] 2019-01-23 15:03
So timeout could be the solution，like rdma event handling tiemout，or the
timeout in local nvme driver

在 2019年1月23日星期三，pawelwod <notifications@github.com> 写道：

**Comment by sashakot** [comment] 2019-01-23 15:06
Hi, 

We have customers that count on this functionality. So we're interesting in fixing.
How long the timeout can be? Is it possible any other solution which is not based on timeouts?

BR
Sasha

**Comment by sashakot** [comment] 2019-01-23 16:37
@jimharris , we're evaluating to run SPDK target process as an mediator for processing IO (in bdev layer, for example) and forwarding it to final destination. I don't think, it can be described as "loopback". Will SPDK target support dynamic adding/removing nvmf subsystems is this scenario?

**Comment by jimharris** [comment] 2019-01-23 16:42
Hi @sashakot - it should work OK in this kind of mediator use case.  You have both the NVMe-oF target and initiator running in the same SPDK process, but it doesn't sound like you'd have the initiator connecting to an NVMf subsystem served by the target running in the same process.

But the async model is still best.  @changpe1's work was to avoid these types of while loops, so the CPU running the initiator code can go do other work while waiting for the controller initialization to progress.  For PCIe, that means not polling waiting for the SSD to set its RDY bit, for RDMA/TCP, it means not polling waiting for the target to respond.

**Comment by benlwalker** [comment] 2019-01-23 18:21
Agree with Jim. To summarize, the bug occurs when you have the SPDK NVMe-oF initiator attempt to connect to an SPDK NVMe-oF target running on the same **thread in the same process**. The SPDK NVMe-oF initiator does a blocking connect operation, which blocks the thread that is also responsible for accepting the connection.

* This isn't a paradox or some infinite loop by configuration, but it is a corner case that I don't ever expect to see in a production system. It's fine to run the NVMe-oF initiator and the NVMe-oF target in the same process, even on the same thread, as long as the initiator doesn't loop back and connect to a target accepting connections on the exact same thread. If you hit this bug, you're very likely doing something that doesn't make sense anyway.
* A timeout doesn't help. It will make it not hang, but it won't make it work.
* Asynchronous connect fixes the problem.@changpe1's patch series is the right solution.

**Comment by optimistyzy** [comment] 2019-01-24 02:02
@benlwalker  The paradox means that if the instance provides NVMe-oF target service, and there is an initiator inside the process connects itself. For example, it got an bdev. Then the users can construct another NVMe-oF subsystem and export the dev again, and the user can construct the a new subsystem again. So it means, we can infinitely build subsystems on an bdev, so do we really want to users do that?

**Comment by jimharris** [comment] 2019-01-24 18:16
I don't think we should do anything to disallow it.  This would not be an endless loop so I don't see a problem.  If we make the connect asynchronous to allow remote namespace A to be exported as namespace B, then this should work fine if the user wants to then export namespace B as namespace C, etc.  It's not recommended to do deep nesting, but trying to detect and disallow it seems like extra work that's not needed.

**Comment by changpe1** [comment] 2019-03-18 09:03
Since asynchronous probe and connect API were added for now, I debugged the issue for a while, since SPDK NVMe-oF initiator attempt to connect to an SPDK NVMe-oF target running on the same thread in the same process, so we MUST remove all the synchronous call during the whole initialization, include:

1. Broken up nvme_transport_ctrlr_construct(), and add a new nvme_transport_ctrlr_construct_admin_qpair() with a new state, existing code mixed the two steps together.

2. nvme_fabric_prop_set_cmd()/nvme_fabric_prop_get_cmd() should be changed to add similar APIs like:
nvme_fabric_prop_get_cmd_async() and nvme_fabric_prop_set_cmd_async();

The will involve some additional state, I'm wondering do we still need to address this issue? @jimharris @benlwalker throughts ?

**Comment by jimharris** [comment] 2019-03-18 15:06
Making this asynchronous helps more than just the loopback issue.  It also reduces time spent spinning when connecting to a remote target.  This time spent spinning keeps any other work from happening on that core.

**Comment by jimharris** [comment] 2019-03-18 16:07
Note that creating and deleting I/O qpairs are also completely synchronous right now.  Making these asynchronous should go on our backlog as well.

**Comment by peluse** [comment] 2019-04-09 15:39
bug scrub, moving to low.  Don't recommend this as a use case

**Comment by changpe1** [comment] 2019-12-17 01:38
Closing this issue as this is not recommended way to use SPDK.

**Closed by changpe1** 2019-12-17 01:38 UTC
Labels: Low, bug
