### ISSUE TITLE
[opal_revert_cleanup] SPDK process can't open RPC socket

### ISSUE THREAD

**Issue by AlekseyMarchuk** [spdk/spdk#1726] opened 2020-12-22 16:54 UTC
## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_32761.html

## Execution failed at
```
00:01:21.321  [2020-12-22 16:43:26.093818] Starting SPDK v21.01-pre git sha1 6c5c1bc63 / DPDK 20.08.0 initialization...
00:01:21.322  [2020-12-22 16:43:26.094023] [ DPDK EAL parameters: [2020-12-22 16:43:26.094049] spdk_tgt [2020-12-22 16:43:26.094085] --no-shconf [2020-12-22 16:43:26.094104] -c 0x1 [2020-12-22 16:43:26.094125] --log-level=lib.eal:6 [2020-12-22 16:43:26.094141] --log-level=lib.cryptodev:5 [2020-12-22 16:43:26.094175] --log-level=user1:6 [2020-12-22 16:43:26.094199] --base-virtaddr=0x200000000000 [2020-12-22 16:43:26.094229] --match-allocations [2020-12-22 16:43:26.094251] --file-prefix=spdk_pid2034340 [2020-12-22 16:43:26.094276] ]
00:01:21.369  EAL: No free hugepages reported in hugepages-2048kB
00:01:21.369  EAL: No available hugepages reported in hugepages-1048576kB
00:01:21.380  EAL: No legacy callbacks, legacy socket not created
00:01:21.450  [2020-12-22 16:43:26.222560] app.c: 537:spdk_app_start: *NOTICE*: Total cores available: 1
00:01:21.760  [2020-12-22 16:43:26.532233] reactor.c: 699:reactor_run: *NOTICE*: Reactor started on core 0
00:01:21.765  [2020-12-22 16:43:26.537480] accel_engine.c: 692:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:01:22.043  [2020-12-22 16:43:26.815740] rpc.c: 176:spdk_rpc_listen: *ERROR*: Cannot open lock file /var/tmp/spdk.sock.lock: Permission denied
00:01:22.043  [2020-12-22 16:43:26.815870] rpc.c:  71:spdk_rpc_initialize: *ERROR*: Unable to start RPC service at /var/tmp/spdk.sock
00:01:49.838   16:43:54	# xtrace_enable
00:01:49.839   16:43:54	# (( i == 0 ))
00:01:49.839   16:43:54	# echo 'ERROR: timeout while waiting for process (pid: 2034340) to start listening on '\''/var/tmp/spdk.sock'\'''
00:01:49.839  ERROR: timeout while waiting for process (pid: 2034340) to start listening on '/var/tmp/spdk.sock'
00:01:49.839   16:43:54	# ret=1
00:01:49.839   16:43:54	# return 1
00:01:49.839    16:43:54	# trap - ERR
00:01:49.839    16:43:54	# print_backtrace
00:01:49.839    16:43:54	# [[ ehxBET =~ e ]]
00:01:49.840    16:43:54	# args=("${BASH_ARGV[@]}")
00:01:49.840    16:43:54	# local args
00:01:49.840    16:43:54	# xtrace_disable
00:01:49.840    16:43:54	# '[' no '!=' yes ']'
00:01:49.840    16:43:54	# PREV_BASH_OPTS=ehxBET
00:01:49.840    16:43:54	# [[ ehxBET == *\x* ]]
00:01:49.840    16:43:54	# XTRACE_DISABLED=yes
00:01:49.841    16:43:54	# set +x
00:01:49.841  ========== Backtrace start: ==========
00:01:49.841  
00:01:49.849  in /var/jenkins/workspace/vhost-autotest/spdk/test/common/autotest_common.sh:1348 -> opal_revert_cleanup([])
00:01:49.849       ...
00:01:49.849     1343			return 0
00:01:49.849     1344		fi
00:01:49.849     1345	
00:01:49.849     1346		$SPDK_BIN_DIR/spdk_tgt &
00:01:49.849     1347		spdk_tgt_pid=$!
00:01:49.849     1348		waitforlisten $spdk_tgt_pid
00:01:49.849     1349	
00:01:49.849     1350		bdf_id=0
00:01:49.849     1351		for bdf in "${bdfs[@]}"; do
00:01:49.849     1352			$rootdir/scripts/rpc.py bdev_nvme_attach_controller -b "nvme"${bdf_id} -t "pcie" -a ${bdf}
00:01:49.849     1353			# Ignore if this fails.
00:01:49.849       ...
00:01:49.855  in /var/jenkins/workspace/vhost-autotest/spdk/autotest.sh:170 -> main(["/home/sys_sgci/autorun-spdk.conf"])
00:01:49.855       ...
00:01:49.855     165 		fi
00:01:49.855     166 	fi
00:01:49.855     167 	
00:01:49.855     168 	# Revert existing OPAL to factory settings that may have been left from earlier failed tests.
00:01:49.855     169 	# This ensures we won't hit any unexpected failures due to NVMe SSDs being locked.
00:01:49.855  => 170 	opal_revert_cleanup
00:01:49.855     171 	
00:01:49.855     172 	#####################
00:01:49.855     173 	# Unit Tests
00:01:49.855     174 	#####################
00:01:49.855     175 	
00:01:49.855       ...
00:01:49.855  
00:01:49.855  ========== Backtrace end ==========
```

**Comment by spdkci** [comment] 2020-12-22 16:55
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_32761.html

**Comment by spdkci** [comment] 2020-12-22 17:07
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_32758.html

**Comment by jimharris** [comment] 2020-12-22 17:28
Both failures are on the vhost_autotest job running on GP11.  @karlatec do you know of any recent changes on that system or that job?  This opal_revert_cleanup gets called in autotest.sh before we even start running any tests.  I haven't been able to find any recent script changes in this area.

**Comment by karlatec** [comment] 2020-12-22 18:09
No recent changes that I remember. I **might** have replaced an NVMe drive and it might not be OPAL-enabled, but this would be quite a while back and I doubt that it could be the root cause - we'd hit that error sooner. 
I saw that there was /var/tmp/spdk.sock.lock even though no builds were running in the background, I removed it.

This one failed too, and it wasn't vhost test: https://ci.spdk.io/public_build/autotest-per-patch_32769.html

Also - currently we don't have OPAL tests enabled in per-patch and nightly tests, so I am wondering if not to comment out this block or put it under "if".

**Comment by jimharris** [comment] 2020-12-22 18:15
Thanks @karlatec.  That failure was also on GP11, so let's see if removing the lock changes things.  

If this happens again, could you run "lsof /var/tmp/spdk.sock.lock" before removing the lock file?  It will show you a PID if some process have the lock file open.  Maybe there were no builds running, but some other process still running in the background?

**Comment by karlatec** [comment] 2020-12-22 18:15
> Maybe there were no builds running, but some other process still running in the background?

i'll check, but there shouldn't be. We have a power cycle on failures.

**Comment by karlatec** [comment] 2020-12-22 18:26
Just finished a manual vhost-autotest build on GP11 and it passed just fine. I think this was just a leftover file not cleaned up after application exit during a previous (probably failed) build.

I think we could add a `lsof /var/tmp/spdk.sock` and `lsof /var/tmp/spdk.sock.lock`  to the beginning of autotest.sh and delete them if no associated process is detected.

**Comment by changpe1** [comment] 2021-01-07 04:09
[Bug Scrub] closing this issue now.

**Closed by changpe1** 2021-01-07 04:09 UTC
Labels: Intermittent Failure
