### ISSUE TITLE
child_length 968 not even multiple of lba_size 512

### ISSUE THREAD

**Issue by skypexu** [spdk/spdk#2678] opened 2022-09-01 10:46 UTC
I got error message "child_length 968 not even multiple of lba_size 512", why ?

I have passed two io_vec to the spdk bdev interface:

[{35467842110264, 968}, {35467842261152, 3128}]

**Comment by jimharris** [comment] 2022-09-01 16:03
Hi @skypexu,

Please, when filing bug reports add a lot more detail.  What kind of bdev are you using?  What application is generating these io_vecs - is it one of the SPDK in-tree applications, or something custom that you have developed?  If custom, what is that application try to do?  What version of SPDK are you using?  Pasting the full log file rather than just one substring from the log is also helpful.

A lot of these details were requested in the template that you saw when opening this issue.  We don't ask for those details to make it harder to file issues.  We ask for those details to make it easier for contributors to take time to answer your question.  This is not an SPDK only thing either, bug reports in general for any project should be submitted with these kinds of details.

Thankfully in this case, just this small bit of data was enough to help answer your question.  Some SSDs do not support full SGL - they only support a more limited version of expressing scattered data called PRP.

PRP requires that all segments except the first *must* start on a 4KiB boundary.  All segments except the last *must* end on a 4KiB boundary.  All segments except the first and last are implicitly 4KiB in size (there is no way to express segment size in PRP).  See the NVMe specification for more details on PRP.

So in your case, the io_vecs in hex are:

0x204200214338, 0x3C8
0x2042002390A0, 0xC38

This cannot be expressed using PRP since the first io_vec does not end on a 4KiB boundary, and the second io_vec does not start on a 4KiB boundary.  The NVMe driver is trying to split those two io_vecs into two separate I/O operations that might be expressible using PRP, but the first iovec is not an even multiple of the 512 byte block size, so that cannot be done either.

So you need to either create your io_vecs in a PRP-compliant way, or use an SSD that supports SGL (which do not have these alignment restrictions).  The examples/bin/identify utility can be used to show what your SSDs support.

Closing this issue, since this is not a bug and the question has been answered, but please feel free to ask more questions on this issue if you have any.

Thanks,

Jim

**Closed by jimharris** 2022-09-01 16:03 UTC
Labels: Sighting
