### ISSUE TITLE
rpc.py bdev_raid_create argument parsing problem

### ISSUE THREAD

**Issue by cfourteen** [spdk/spdk#3244] opened 2024-01-22 21:48 UTC
# Sighting report

rpc.py not parsing arguments correctly when creating a RAID using _**bdev_raid_create**_

## Expected Behavior

Args are parsed correctly

## Current Behavior

```
[ja32802@gist spdk]$ cd scripts
[ja32802@gist scripts]$ odus ./gen_nvme.sh
{
"subsystem": "bdev",
"config": [
{
"method": "bdev_nvme_attach_controller",
"params": {
"trtype": "PCIe",
"name":"Nvme0",
"traddr":"0000:03:00.0"
}
},{
"method": "bdev_nvme_attach_controller",
"params": {
"trtype": "PCIe",
"name":"Nvme1",
"traddr":"0000:04:00.0"
}
}
]
}
[ja32802@gist scripts]$ odus ./rpc.py bdev_raid_create --name FUATHYRIO -z 64 -r raid5f --base-bdevs "nvme0n1" "nvme1n1"
usage: rpc.py [options]
rpc.py: error: unrecognized arguments: nvme1n1

```

## Steps to Reproduce

1. Create nvme bdevs using rpc.py
2. Try to create a  RAID from them with rpc.py using cmd  bdev_raid_create 

## Context (Environment including OS version, SPDK version, etc.)

RHEL 8

**Comment by mmkayPL** [comment] 2024-01-22 22:21
Bdev names are case sensitive - you should use Nvme0n1 and Nvme1n1. Also, as is gen_nvme only generates the RPC calls, it doesn't send them - you should load the generated config to the target app (assuming you're not doing it already).

**Comment by mmkayPL** [comment] 2024-01-23 07:48
Oh, I've noticed one more error (and the one that actually causes the printed error log): your bdev name list should be within one quotation, i.e. **--base-bdevs "Nvme0n1 Nvme1n1"**

**Comment by cfourteen** [comment] 2024-01-23 14:29
I did as you suggested no change. The LC bdev names seem to work for others SPDK RAID evaluation and improvement | Blog | Xinnor <https://xinnor.io/blog/spdk-raid-evaluation-and-improvement/> 

***@***.*** scripts]$ odus ./rpc.py bdev_raid_create --name FUATHYRIO -z 64 -r raid0 --base-bdevs "Nvme0n1 Nvme1n1"

usage: rpc.py [options]

rpc.py: error: unrecognized arguments: Nvme1n1

 

From: Mateusz Kozlowski ***@***.***> 
Sent: Monday, January 22, 2024 5:22 PM
To: spdk/spdk ***@***.***>
Cc: Read, Jackson - 0333 - MITLL ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [spdk/spdk] rpc.py bdev_raid_create argument parsing problem (Issue #3244)

 

Bdev names are case sensitive - you should use Nvme0n1 and Nvme1n1. Also, as is gen_nvme only generates the RPC calls, it doesn't send them - you should load the generated config to the target app (assuming you're not doing it already). —Reply 

ZjQcmQRYFpfptBannerStart




This Message Is From an External Sender 


This message came from outside the Laboratory. 

ZjQcmQRYFpfptBannerEnd

Bdev names are case sensitive - you should use Nvme0n1 and Nvme1n1. Also, as is gen_nvme only generates the RPC calls, it doesn't send them - you should load the generated config to the target app (assuming you're not doing it already).

**Comment by apaszkie** [comment] 2024-01-25 09:30
Even if the specified base bdevs don't exist when creating the raid bdev, the RPC should succeed and a message like this will be shown in the application log:
`*NOTICE*: Currently unable to find bdev with name: Nvme1n1`
When a bdev with such name appears, it will be claimed be the raid bdev.

In your case, it is most likely that the problem is what @mmkayPL described:

> your bdev name list should be within one quotation, i.e. **--base-bdevs "Nvme0n1 Nvme1n1"**

Please double check that the argument passed to --base-bdevs is a single string. And since it contains whitespace, it must be enclosed in quotes. Otherwise, the shell will split it into more arguments.

**Comment by jimharris** [comment] 2024-02-07 16:28
Closing this issue, @cfourteen please reply again here if you still have questions.

**Closed by jimharris** 2024-02-07 16:28 UTC
Labels: question, Waiting on Submitter
