### ISSUE TITLE
virt_addr  not dword aligned

### ISSUE THREAD

**Issue by skypexu** [spdk/spdk#2673] opened 2022-08-29 02:29 UTC
# Bug report

"virt_addr xxx not dword aligned", I got this error.
However there is no document said virtual address must be double word aligned!

**Comment by Comphix** [comment] 2022-08-29 03:07
Please Changpeng give some feedback. Thanks, Gang.

**Comment by changpe1** [comment] 2022-08-29 03:14
I've replied this via https://github.com/spdk/spdk/issues/1454#issuecomment-1229675475. it's not a bug.

**Comment by changpe1** [comment] 2022-08-29 08:48
closing it now, @skypexu you can re-open it if can reproduce with SPDK applications.

**Closed by changpe1** 2022-08-29 08:48 UTC
Labels: Sighting
