### ISSUE TITLE
 always show "no NVMe controllers found" even load uio_pci_generic module

### ISSUE THREAD

**Issue by konili** [spdk/spdk#318] opened 2018-05-29 23:43 UTC
I have followed the guidance of spdk then build the nvme example code: "hello_world and "identify".
Always encounter the error of "no NVMe controller found" even load the uio_pci_generic module.

Could some expert help debug this problem? no idea what I was miss... :(

It's the configuration on my system:
- OS: Ubuntu 18.04 LTS 64bit
- Platform: Intel Skylake PCH / CPU i7-7600 / 8GB RAM
- NVMe: Intel 256GB NVMe (6000p M.2 PCIe Gen3)
- SPDK: v18.07
- DPDK: v18.02.0

**

> Starting SPDK v18.07-pre / DPDK 18.02.0 initialization...
> [ DPDK EAL parameters: hello_world -c 0x1 --file-prefix=spdk0 --base-virtaddr=0x1000000000 --proc-type=auto ]
> EAL: Detected 4 lcore(s)
> EAL: Auto-detected process type: PRIMARY
> EAL: No free hugepages reported in hugepages-1048576kB
> EAL: Multi-process socket /var/run/.spdk0_unix
> EAL: Probing VFIO support...
> EAL: VFIO support initialized
> Initializing NVMe Controllers
> EAL: PCI device 0000:3c:00.0 on NUMA socket 0
> EAL:   probe driver: 8086:f1a5 spdk_nvme
> No NVMe controllers found

**

**Comment by jimharris** [comment] 2018-05-29 23:47
Hi,

Have you run the scripts/setup.sh script?  Loading uio_pci_generic is not enough – the NVMe device also needs to be bound to uio_pci_generic.  You can do that manually, or let the scripts/setup.sh script do it for you.

Regards,

-Jim

**Comment by dverkamp-intel** [comment] 2018-05-29 23:48
You can also run `scripts/setup.sh status`, which will show any NVMe devices detected on your system and which driver is active (`nvme` or `uio_pci_generic`/`vfio-pci`).  Posting the output of this command would be useful if you did in fact run setup.sh already and it didn't work for some reason.

**Comment by konili** [comment] 2018-05-29 23:54
yes, I have ran the ./scripts/setup.sh. It's the output from "setup.sh status":

> Hugepages
> node     hugesize     free /  total
> node0   1048576kB        0 /      0
> node0      2048kB        0 /   1024
> NVMe devices
> BDF		Numa Node	Driver name		Device name
> 0000:3c:00.0	0		nvme			nvme0
> I/OAT DMA
> BDF		Numa Node	Driver Name
> virtio
> BDF		Numa Node	Driver Name		Device Name

Looks like the NVMe controller present on 3c:00.00 but still shows "no NVMe controller found".

attached lspci for reference as well:

> 00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers (rev 02)
> 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)
> 00:13.0 Non-VGA unclassified device: Intel Corporation Sunrise Point-LP Integrated Sensor Hub (rev 21)
> 00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)
> 00:14.2 Signal processing controller: Intel Corporation Sunrise Point-LP Thermal subsystem (rev 21)
> 00:15.0 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #0 (rev 21)
> 00:15.1 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #1 (rev 21)
> 00:15.2 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #2 (rev 21)
> 00:16.0 Communication controller: Intel Corporation Sunrise Point-LP CSME HECI #1 (rev 21)
> 00:16.3 Serial controller: Intel Corporation Device 9d3d (rev 21)
> 00:1c.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port (rev f1)
> 00:1c.4 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #5 (rev f1)
> 00:1c.5 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #6 (rev f1)
> 00:1d.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #9 (rev f1)
> 00:1f.0 ISA bridge: Intel Corporation Device 9d4e (rev 21)
> 00:1f.2 Memory controller: Intel Corporation Sunrise Point-LP PMC (rev 21)
> 00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
> 00:1f.4 SMBus: Intel Corporation Sunrise Point-LP SMBus (rev 21)
> 00:1f.7 Non-Essential Instrumentation [1300]: Intel Corporation Device 9d26 (rev 21)
> 3a:00.0 Network controller: Intel Corporation Wireless 8265 / 8275 (rev 78)
> 3b:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS522A PCI Express Card Reader (rev 01)
> 3c:00.0 Non-Volatile memory controller: Intel Corporation Device f1a5 (rev 03)
>

**Comment by konili** [comment] 2018-05-30 02:02
oops.. you are right.
The Ubuntu OS was loaded on the filesystem and it mounted on this NVMe drive. Is it the reason why it failed?

> NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
> loop0         7:0    0  86.6M  1 loop /snap/core/4486
> loop1         7:1    0  12.2M  1 loop /snap/gnome-characters/69
> loop2         7:2    0   2.3M  1 loop /snap/gnome-calculator/167
> loop3         7:3    0    21M  1 loop /snap/gnome-logs/25
> loop4         7:4    0  86.6M  1 loop /snap/core/4571
> loop5         7:5    0 139.5M  1 loop /snap/gnome-3-26-1604/64
> loop6         7:6    0   3.3M  1 loop /snap/gnome-system-monitor/36
> loop7         7:7    0  21.6M  1 loop /snap/gnome-logs/31
> loop8         7:8    0   140M  1 loop /snap/gnome-3-26-1604/59
> loop9         7:9    0    13M  1 loop /snap/gnome-characters/86
> loop10        7:10   0   3.7M  1 loop /snap/gnome-system-monitor/39
> loop11        7:11   0   1.6M  1 loop /snap/gnome-calculator/154
> loop12        7:12   0  86.6M  1 loop /snap/core/4650
> nvme0n1     259:0    0 238.5G  0 disk 
> ├─nvme0n1p1 259:1    0   512M  0 part /boot/efi
> └─nvme0n1p2 259:2    0   238G  0 part /

**Comment by wanqunintel** [comment] 2018-05-30 05:11
@konili , so shall we close it

**Comment by konili** [comment] 2018-05-30 11:36
Not sure if it’s the root cause. Let me try with using NVMe drive as data drive, to check the result.

Is it an known limitation is spdk?

**Comment by konili** [comment] 2018-05-30 16:01
Hi,
Thanks all of your comments, I will try on another host system since there’s only one storage (m.2) slot on this machine...too bad.

It’s a big help to point the problem. Big thanks guys :) 
Will keep post the result later.

Koni.

**Comment by jimharris** [comment] 2018-06-05 21:22
Closing issue since submitter confirmed boot OS was mounted on NVMe SSD.

**Closed by jimharris** 2018-06-05 21:22 UTC

**Comment by konili** [comment] 2018-06-20 07:10
Sorry for the late response.

The cause of this issue as mentioned, some reason it could not be work if nvme mount as system drive.
I used another system which installed on SATA SSD and the example code work well of NVMe storage detection.

Thanks for your great help :)

-Koni

**Comment by jimharris** [comment] 2018-06-20 15:28
No problem Koni.  Thank you for following up.

**Comment by xxks-kkk** [comment] 2018-08-23 22:41
Hello,

@konili  I'm facing the same issue. In order to fix the issue, I need to unmount the file system?

Thanks much!

**Comment by pawelwod** [comment] 2018-08-24 08:16
@xxks-kkk  yes, you need to umount it. Devices with mounted filesystems won't be used by `setup.sh`

**Comment by konili** [comment] 2018-08-24 08:35
Yes, it’s right.
If you have multiple drives on your system, do not use NVMe driver as OS drive also can fix this error.

**Comment by XYT874264076** [comment] 2021-06-25 12:49
This issue help me solve my problem, thanks~

**Comment by sadmankiba** [comment] 2023-01-05 16:25
Hi, my root filesystem (`/`) is mounted on a logical volume in the NVMe drive. I think unmounting `/` does not work since it's root. How can I use SPDK with this NVMe device?
