### ISSUE TITLE
Segmentation fault (core dumped) when running fio plugin with bs=1M

### ISSUE THREAD

**Issue by huiminglai** [spdk/spdk#467] opened 2018-10-19 08:12 UTC
When running the fio plugin with "bs=1M", I get a segmentation fault error, and this error will happen when set bs=512k too.
I also test "bs=4k" and fio job can run successfully.

## Expected Behavior
When set "bs=4k" and fio job can runs successfully.

fio --numjobs=1 --iodepth=128 --bs=4k --name=SWPre --filename="trtype=PCIe traddr=0000.86.00.0 ns=1" --thread=1 --rw=randwrite --direct=1 --ioengine=/root/Desktop/spdk-master/examples/nvme/fio_plugin/fio_plugin --time_based --runtime=60 

SWPre: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk, iodepth=128
fio-3.11
Starting 1 thread

SWPre: (groupid=0, jobs=1): err= 0: pid=58911: Fri Oct 19 15:57:33 2018
  write: IOPS=397k, BW=1550MiB/s (1625MB/s)(90.8GiB/60001msec)
    slat (nsec): min=100, max=34231, avg=174.19, stdev=59.34
    clat (usec): min=3, max=1336.5k, avg=322.03, stdev=2923.31
     lat (usec): min=4, max=1336.5k, avg=322.20, stdev=2923.31
    clat percentiles (usec):
     |  1.00th=[   10],  5.00th=[   21], 10.00th=[   32], 20.00th=[   64],
     | 30.00th=[  135], 40.00th=[  204], 50.00th=[  285], 60.00th=[  379],
     | 70.00th=[  433], 80.00th=[  490], 90.00th=[  586], 95.00th=[  734],
     | 99.00th=[ 1090], 99.50th=[ 1270], 99.90th=[ 3064], 99.95th=[ 5080],
     | 99.99th=[ 7701]
   bw (  MiB/s): min=  164, max= 1672, per=100.00%, avg=1576.45, stdev=170.49, samples=117
   iops        : min=42150, max=428158, avg=403572.19, stdev=43644.99, samples=117
  lat (usec)   : 4=0.01%, 10=1.20%, 20=3.80%, 50=11.69%, 100=9.18%
  lat (usec)   : 250=20.41%, 500=35.35%, 750=13.74%, 1000=3.12%
  lat (msec)   : 2=1.33%, 4=0.12%, 10=0.06%, 20=0.01%, 250=0.01%
  cpu          : usr=100.00%, sys=0.00%, ctx=73, majf=0, minf=5415
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwts: total=0,23805560,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=128

Run status group 0 (all jobs):
  WRITE: bw=1550MiB/s (1625MB/s), 1550MiB/s-1550MiB/s (1625MB/s-1625MB/s), io=90.8GiB (97.5GB), run=60001-60001msec

## Current Behavior
When set "bs=1M", fio job can not run successfully and return "Segmentation fault (core dumped)".

fio --numjobs=1 --iodepth=128 --bs=1M --name=SWPre --filename="trtype=PCIe traddr=0000.86.00.0 ns=1" --thread=1 --rw=randwrite --direct=1 --ioengine=/root/Desktop/spdk-master/examples/nvme/fio_plugin/fio_plugin --time_based --runtime=60 

Starting SPDK v18.10-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 512 --legacy-mem --file-prefix=spdk_pid58991 ]
EAL: Detected 56 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: Could not open fbarray file: No such file or directory
EAL: Could not open fbarray file: No such file or directory
EAL: Could not open fbarray file: No such file or directory
EAL: Could not open fbarray file: No such file or directory
EAL: Could not open fbarray file: No such file or directory
EAL: Could not open fbarray file: No such file or directory
EAL: Could not open fbarray file: No such file or directory
EAL: PCI device 0000:86:00.0 on NUMA socket 1
EAL:   probe driver: 8086:953 spdk_nvme
Segmentation fault (core dumped)

## Context (Environment including OS version, SPDK version, etc.)
OS:  RHEL7.4 (kernel3.10.0-693.el7.x86_64
SSD: Intel® P3600 1.6TB
Hugepage Size: 1 GB

**Comment by pelplinski** [comment] 2018-10-19 14:58
Tried to replicate on Fedora 27 with P3700 drive.
Issue is not present on my system.

**Comment by xuhuagen** [comment] 2018-10-23 03:01
@huiminglai  
I try reproduce on Centos 7.5 with P3700 drive
I set bs=1M/2M/,fio job can run successfully.  if bs more bigger, 
`fio: pid=36576, err=12/file:memory.c:332, func=iomem allocation, error=Cannot allocate memory
` 
fio exit normally.
This should relate on the size of memory in machine.

**Comment by huiminglai** [comment] 2018-10-23 03:19
Thanks for your test, I can run fio job with bs=1M  after add below text in grub (enabled iommu).
intel_iommu=on iommu=pt

**Comment by wanqunintel** [comment] 2018-10-25 04:17
@huiminglai , shall we close this issue since it's fixed with configuration.

**Comment by jimharris** [comment] 2018-12-12 16:45
Closing this as a configuration issue.

**Closed by jimharris** 2018-12-12 16:45 UTC
Labels: question
