### ISSUE TITLE
[Rlease Docs] Duplicate paragraphs exist in the 24.01 release feature description

### ISSUE THREAD

**Issue by liuqinfei** [spdk/spdk#3248] opened 2024-02-01 07:31 UTC
# Sighting report
Duplicate paragraphs exist in the version feature description of 24.01.
https://github.com/spdk/spdk/releases/tag/v24.01
![微信截图_20240201153556](https://github.com/spdk/spdk/assets/42903181/0d22ecb2-a4ab-43c7-82b0-6fac5288f66a)

## Expected Behavior
Accurate and non-redundant description.

## Current Behavior
NA

## Possible Solution
NA
## Steps to Reproduce
NA

## Context (Environment including OS version, SPDK version, etc.)
SPDK24.01

**Comment by tomzawadzki** [comment] 2024-02-01 08:31
@liuqinfei Thank you for reporting !

The issue is now fixed in GitHub release notes. Meanwhile a fix was pushed to v24.01.x branch https://review.spdk.io/gerrit/c/spdk/spdk/+/21694.

**Comment by jimharris** [comment] 2024-02-26 20:21
Patches merged.

**Closed by jimharris** 2024-02-26 20:21 UTC
Labels: bug, Low, Patches out for review
