### ISSUE TITLE
Misuse of DPDK event framework in SPDK

### ISSUE THREAD

**Issue by Maciej-Szwed** [spdk/spdk#1785] opened 2021-02-05 10:08 UTC
In SPDK we are using DPDK event monitor framework by registering pci_device_rte_dev_event() function (pci.c) through rte_dev_event_callback_register(). Unfortunately this event callback is never being called due to missing rte_dev_event_monitor_start() call in SPDK that would start DPDK event monitor.

Here is note from DPDK patch that implements event monitor framework:

```
This patch aims to add a general device event monitor framework at
EAL device layer, for device hotplug awareness and actions adopted
accordingly. It could also expand for all other types of device event
monitor, but not in this scope at the stage.

To get started, users firstly call below new added APIs to enable/disable
the device event monitor mechanism:
  - rte_dev_event_monitor_start
  - rte_dev_event_monitor_stop

Then users shell register or unregister callbacks through the new added
APIs. Callbacks can be some device specific, or for all devices.
  -rte_dev_event_callback_register
  -rte_dev_event_callback_unregister

Use hotplug case for example, when device hotplug insertion or hotplug
removal, we will get notified from kernel, then call user's callbacks
accordingly to handle it, such as detach or attach the device from the
bus, and could benefit further fail-safe or live-migration.

```

I've created fix for that: https://review.spdk.io/gerrit/c/spdk/spdk/+/6197 but with the fix applied hotplug test fails on CI: https://ci.spdk.io/results/autotest-per-patch/builds/35661/archive/nvme-phy-autotest/build.log

**Comment by jimharris** [comment] 2021-02-05 15:21
Hi @Maciej-Szwed,

It is not clear from the title nor description why starting the event monitor is important.  Could you update the title and the description?

Thanks,

-Jim

**Comment by Maciej-Szwed** [comment] 2021-02-23 12:55
Description and title updated.

**Comment by jimharris** [comment] 2021-04-06 15:14
Possibly related to #1816.

**Comment by tomzawadzki** [comment] 2021-05-18 15:17
[Bug scrub] This issue will be closed as duplicate of https://github.com/spdk/spdk/issues/1816

**Closed by tomzawadzki** 2021-05-18 15:17 UTC
Labels: Sighting
