### ISSUE TITLE
bdevperf randwrite is not uniform random write

### ISSUE THREAD

**Issue by gaowayne** [spdk/spdk#2908] opened 2023-02-10 14:14 UTC
# Sighting report

bdevperf randwrite is not uniform random write
when I run randwrite on nvme drive long time, I expect WAF grows and performance drops 2-3 times if randwrite is very uniform write

## Expected Behavior

can bdevperf randwrite be a very uniform rand write?

## Current Behavior

currently I test bdevperf randwrite on 800G TLC drive, its performance is same with seq write for more than one hour. if I use fio randwrite to test on it, its performance can drop after less than 10 min.
below is fio iostat data after randwrite cause WAF, nvme3n1 shows 1200MiB/s, if spdk bdevperf randwrite, I cannot see WAF happen. perf maintain the seqwrite level.
```
Device            r/s     rMB/s   rrqm/s  %rrqm r_await rareq-sz     w/s     wMB/s   wrqm/s  %wrqm w_await wareq-sz     d/s     dMB/s   drqm/s  %drqm d_await dareq-sz     f/s f_await  aqu-sz  %util
dm-0             0.00      0.00     0.00   0.00    0.00     0.00    0.40      0.10     0.00   0.00    0.00   246.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    0.00   0.02
nvme0n1          0.00      0.00     0.00   0.00    0.00     0.00    1.20      0.10     0.00   0.00    0.17    82.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    0.00   0.02
nvme1n1          0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    0.00   0.00
nvme2n1          0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    0.00   0.00
nvme3n1          0.00      0.00     0.00   0.00    0.00     0.00 312712.60   1221.53     0.00   0.00    0.02     4.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    7.67 100.00
nvme4n1          0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    0.00   0.00
sda              0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    0.00   0.00
zram0            0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    0.00   0.00
```

## Steps to Reproduce

1. just run bdevperf randwrite for example below
2. nohup build/examples/bdevperf --json ../json/only.json --json-ignore-init-errors -r /var/tmp/spdk.sock -m 2 -q 128 -o 4096 -w randwrite -t 7200 > perfr.log 2>&1 &
3.
4.

here is my json, it is just 800G TLC drive.
```
        {
          "method": "bdev_nvme_attach_controller",
          "params": {
            "name": "Nvme0",
            "trtype": "PCIe",
            "traddr": "0000:6e:00.0",
            "prchk_reftag": false,
            "prchk_guard": false,
            "ctrlr_loss_timeout_sec": 0,
            "reconnect_delay_sec": 0,
            "fast_io_fail_timeout_sec": 0
          }
        },
```
## Context (Environment including OS version, SPDK version, etc.)
OS: FedoraOS3.4   
Linux fedora 5.13.8-200.fc34.x86_64 #1 SMP Wed Aug 4 19:59:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
SPDK master last commit ID below
```
commit 120eb844545891077a97dec001c8d0a89d08b0e0 (HEAD -> master, origin/master, origin/HEAD)
    ublk: update func ublk_try_close_dev
```

**Comment by jimharris** [comment] 2023-02-10 15:14
@gaowayne, you've been using SPDK and filing issues for a long time, you know this isn't how to submit a GitHub issue.  :).

You need to provide details about the hardware you're using, the json config file, etc.  Please also provide supporting data that this specific workload should show a performance drop.  For example, do you see performance drops with this same workload and hardware when using other performance tools such as fio (including fio w/ SPDK bdev plugin).

bdevperf uses rand_r() which returns pseudo-random numbers which should have a uniform distribution.  I've looked at the bdevperf.c code just now and see no evidence that its mapping of the rand_r() values to LBA would result in an uneven distribution if rand_r() is uniform.  If you require something different than rand_r(), I would suggest using fio instead.

**Comment by jimharris** [comment] 2023-02-10 15:42
I have found a bug in the bdevperf code though.  rand_r() returns number between 0 and RAND_MAX, and RAND_MAX is only INT32_MAX.

This could cause some non-uniform distribution if the SSD was sufficiently large (>64TB).  So please post your hardware details so we can understand if this is potentially the issue.

Please also try https://review.spdk.io/gerrit/c/spdk/spdk/+/16768 to see if it fixes your issue.

**Comment by gaowayne** [comment] 2023-02-11 15:16
> # Sighting report
> bdevperf randwrite is not uniform random write when I run randwrite on nvme drive long time, I expect WAF grows and performance drops 2-3 times if randwrite is very uniform write
> 
> ## Expected Behavior
> can bdevperf randwrite be a very uniform rand write?
> 
> ## Current Behavior
> currently I test bdevperf randwrite on 800G TLC drive, its performance is same with seq write for more than one hour. if I use fio randwrite to test on it, its performance can drop after less than 10 min.
> 
> ## Possible Solution
> ## Steps to Reproduce
> 1. just run bdevperf randwrite for example below
> 2. nohup build/examples/bdevperf --json ../json/only.json --json-ignore-init-errors -r /var/tmp/spdk.sock -m 2 -q 128 -o 4096 -w randwrite -t 7200 > perfr.log 2>&1 &
> 
> here is my json, it is just 800G TLC drive.
> 
> ```
>         {
>           "method": "bdev_nvme_attach_controller",
>           "params": {
>             "name": "Nvme0",
>             "trtype": "PCIe",
>             "traddr": "0000:6e:00.0",
>             "prchk_reftag": false,
>             "prchk_guard": false,
>             "ctrlr_loss_timeout_sec": 0,
>             "reconnect_delay_sec": 0,
>             "fast_io_fail_timeout_sec": 0
>           }
>         },
> ```
> 
> ## Context (Environment including OS version, SPDK version, etc.)
> OS: FedoraOS3.4 Linux fedora 5.13.8-200.fc34.x86_64 #1 SMP Wed Aug 4 19:59:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux SPDK master last commit ID below
> 
> ```
> commit 120eb844545891077a97dec001c8d0a89d08b0e0 (HEAD -> master, origin/master, origin/HEAD)
>     ublk: update func ublk_try_close_dev
> ```



> @gaowayne, you've been using SPDK and filing issues for a long time, you know this isn't how to submit a GitHub issue. :).
> 
> You need to provide details about the hardware you're using, the json config file, etc. Please also provide supporting data that this specific workload should show a performance drop. For example, do you see performance drops with this same workload and hardware when using other performance tools such as fio (including fio w/ SPDK bdev plugin).
> 
> bdevperf uses rand_r() which returns pseudo-random numbers which should have a uniform distribution. I've looked at the bdevperf.c code just now and see no evidence that its mapping of the rand_r() values to LBA would result in an uneven distribution if rand_r() is uniform. If you require something different than rand_r(), I would suggest using fio instead.

sorry, Jim. I updated the ticket to include the more detail. I will verify it with fio plugin, this is great suggestion. I should check this. 
I am sorry Jim, I know fio can do the thing, but I do like bdevperf is much easy use for quick testing.

**Comment by gaowayne** [comment] 2023-02-11 15:41
@jimharris as you suggested I run fio plugin. yes it can quickly create WAF as below on 800G drive. bdevperf is more simple and direct tool to run than fio plugin. if it can emulate the uniform random create WAF for SSD, it will be helpful. but this is not very urgent. just for me, the ftl with fio plugin function is broken, but I think Mateusz can fix it next month. :)
```
[root@fedora spdk]# LD_PRELOAD=/root/wayne/spdk/build/fio/spdk_bdev /root/wayne/fio/fio /root/wayne/json/xxx_rand.fio
test: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk_bdev, iodepth=128
fio-3.33-80-gf0c8
Starting 1 thread
TELEMETRY: No legacy callbacks, legacy socket not created
^Cbs: 1 (f=1): [w(1)][0.2%][w=1493MiB/s][w=382k IOPS][eta 11h:58m:29s]
fio: terminating on signal 2

test: (groupid=0, jobs=1): err= 0: pid=466136: Sun Feb 12 07:30:41 2023
  write: IOPS=380k, BW=1483MiB/s (1555MB/s)(133GiB/91858msec); 0 zone resets
    slat (nsec): min=142, max=9287, avg=244.68, stdev=24.08
    clat (usec): min=4, max=9371, avg=332.28, stdev=330.23
     lat (usec): min=4, max=9371, avg=332.52, stdev=330.23
    clat percentiles (usec):
     |  1.00th=[    6],  5.00th=[   10], 10.00th=[   16], 20.00th=[   28],
     | 30.00th=[   50], 40.00th=[  118], 50.00th=[  241], 60.00th=[  363],
     | 70.00th=[  502], 80.00th=[  627], 90.00th=[  791], 95.00th=[  930],
     | 99.00th=[ 1287], 99.50th=[ 1450], 99.90th=[ 1844], 99.95th=[ 2024],
     | 99.99th=[ 2442]
   bw (  MiB/s): min= 1261, max= 1692, per=99.99%, avg=1482.56, stdev=59.69, samples=183
   iops        : min=322938, max=433160, avg=379534.09, stdev=15281.06, samples=183
  lat (usec)   : 10=5.08%, 20=8.76%, 50=16.40%, 100=7.90%, 250=12.45%
  lat (usec)   : 500=19.39%, 750=18.07%, 1000=8.37%
  lat (msec)   : 2=3.54%, 4=0.05%, 10=0.01%
  cpu          : usr=99.88%, sys=0.00%, ctx=230, majf=0, minf=0
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=97.2%, 8=1.3%, 16=1.0%, 32=0.4%, 64=0.1%, >=64=0.1%
     issued rwts: total=0,34868432,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=128

Run status group 0 (all jobs):
  WRITE: bw=1483MiB/s (1555MB/s), 1483MiB/s-1483MiB/s (1555MB/s-1555MB/s), io=133GiB (143GB), run=91858-91858msec
```

**Comment by jimharris** [comment] 2023-02-11 17:42
Can you try fio, but with norandommap=1 option?

**Comment by gaowayne** [comment] 2023-02-12 02:32
> Can you try fio, but with norandommap=1 option?

Jim great suggestion. below is my fio randrepeat=0 and norandommap enabled
I found randrepeat and norandommap matters. 
if randrepeat=1 and nonrandommap=0, looks like not fully uniform random, there is no big WAF penalty
for other situation, it will create WAF penalty within couple of minutes.

Could you please assign this to me, next week later time, I will debug more to see if I can prepare a patch. 

```
[global]
ioengine=spdk_bdev
spdk_json_conf=/root/wayne/json/slconly.json
filename=Nvme0n1
#spdk_core_mask=fff
#cpumask=ffff
cpus_allowed=12-17
cpus_allowed_policy=split
direct=1
thread=1
buffered=0
size=100%
randrepeat=0
#allrandrepeat=1
time_based
norandommap=1
refill_buffers
group_reporting

[test]
stonewall
bs=4k
#random_distribution=zipf:1.2
numjobs=1
rw=randwrite
iodepth=128
runtime=43200
```

**Comment by jimharris** [comment] 2023-02-12 15:20
Thanks Wayne, this is what I expected. Just to clarify, rand_r is uniform, it’s actually fio’s randommap that is not uniform - it keeps track of which blocks were read or written and uses that to influence future random offsets to ensure that every block is read or written.

You should be careful with randommap, there is non trivial overhead to maintain that map, which itself can lead you to think that IO performance is degrading when actually fio is spending too much time finding random numbers that haven’t been used yet.

**Comment by jimharris** [comment] 2023-02-13 17:05
Marking this as an enhancement request.

A relatively simple way to implement randommap-like behavior in bdevperf would be to add an spdk_bit_array to each bdevperf_job.  Add some new command line parameter to enable the randommap.  Note this will have opposite default as fio - by default we would *not* enable randommap.

If randommap is enabled, the bit array is created with size job->size_in_ios.

Note that bit array today only supports size UINT32_MAX - 1, so if size_in_ios is greater than this, we need to report an error to the user.

When randommap is enabled, after getting rand_r value, check if the corresponding bit is already set in the bit array.  If not, use spdk_bit_array_find_first_clear() to find the next bit that is not set, passing the rand_r value as start_bit_index.  If it returns UINT32_MAX, we need to call spdk_bit_array_find_first_clear again with start_bit_index = 0.  One we find a clear bit, spdk_bit_array_set on that bit, and use that value as offset_in_ios.  Note that if the second spdk_bit_array_find_first_clear returns UINT32_MAX, it means we have accessed every block in the bdev, so call spdk_bit_array_clear_mask and start all over.

**Comment by gaowayne** [comment] 2023-02-14 03:55
> Thanks Wayne, this is what I expected. Just to clarify, rand_r is uniform, it’s actually fio’s randommap that is not uniform - it keeps track of which blocks were read or written and uses that to influence future random offsets to ensure that every block is read or written.
> 
> You should be careful with randommap, there is non trivial overhead to maintain that map, which itself can lead you to think that IO performance is degrading when actually fio is spending too much time finding random numbers that haven’t been used yet.

got it. Jim. thank you so much.

**Comment by gaowayne** [comment] 2023-02-14 04:01
> Marking this as an enhancement request.
> 
> A relatively simple way to implement randommap-like behavior in bdevperf would be to add an spdk_bit_array to each bdevperf_job. Add some new command line parameter to enable the randommap. Note this will have opposite default as fio - by default we would _not_ enable randommap.
> 
> If randommap is enabled, the bit array is created with size job->size_in_ios.
> 
> Note that bit array today only supports size UINT32_MAX - 1, so if size_in_ios is greater than this, we need to report an error to the user.
> 
> When randommap is enabled, after getting rand_r value, check if the corresponding bit is already set in the bit array. If not, use spdk_bit_array_find_first_clear() to find the next bit that is not set, passing the rand_r value as start_bit_index. If it returns UINT32_MAX, we need to call spdk_bit_array_find_first_clear again with start_bit_index = 0. One we find a clear bit, spdk_bit_array_set on that bit, and use that value as offset_in_ios. Note that if the second spdk_bit_array_find_first_clear returns UINT32_MAX, it means we have accessed every block in the bdev, so call spdk_bit_array_clear_mask and start all over.

this is great idea!~ I fixed the fio on FTL issue, I can continue my work. if there is a patch for this, I can help verify. if not design very complex testing senario, bdevperf still favorite one to get started. :)

**Comment by tomzawadzki** [comment] 2023-02-21 15:00
Linking to the patch addressing this issue https://review.spdk.io/gerrit/c/spdk/spdk/+/16865.
Thank you @slawekptak !

**Comment by jimharris** [comment] 2023-02-21 15:16
> Linking to the patch addressing this issue https://review.spdk.io/gerrit/c/spdk/spdk/+/16865.
> Thank you @slawekptak !

Thanks @slawekptak - I posted a few comments, but overall this looks great.

**Comment by gaowayne** [comment] 2023-02-22 10:32
> > Linking to the patch addressing this issue https://review.spdk.io/gerrit/c/spdk/spdk/+/16865.
> > Thank you @slawekptak !
> 
> Thanks @slawekptak - I posted a few comments, but overall this looks great.

@slawekptak @jimharris thank you so much. I did a quick test, new method also cannot trigger drive GC and WAF. :(
maybe let us lower priority for this. use fio plugin instead.
```
Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
Nvme0n1  716165.30  0.00       2797.52    0.00       0.00     56019.86  0.00   

cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
           1.04%      0.00%      0.00%        0.00%        0.00%       98.96%   

Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
Nvme0n1  716586.61  0.00       2799.17    0.00       0.00     56052.86  0.00   

cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
           1.04%      0.00%      0.00%        0.00%        0.00%       98.96%   

Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
Nvme0n1  717690.70  0.00       2803.48    0.00       0.00     56139.20  0.00   

cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
           1.04%      0.00%      0.00%        0.00%        0.00%       98.96%   

Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
Nvme0n1  716126.04  0.00       2797.37    0.00       0.00     56016.84  0.00   

cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
           1.04%      0.00%      0.00%        0.00%        0.00%       98.96%
```

**Comment by jimharris** [comment] 2023-02-22 14:33
> > > Linking to the patch addressing this issue https://review.spdk.io/gerrit/c/spdk/spdk/+/16865.
> > > Thank you @slawekptak !
> > 
> > 
> > Thanks @slawekptak - I posted a few comments, but overall this looks great.
> 
> @slawekptak @jimharris thank you so much. I did a quick test, new method also cannot trigger drive GC and WAF. :( maybe let us lower priority for this. use fio plugin instead.
> 
> ```
> Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
> Nvme0n1  716165.30  0.00       2797.52    0.00       0.00     56019.86  0.00   
> 
> cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
>            1.04%      0.00%      0.00%        0.00%        0.00%       98.96%   
> 
> Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
> Nvme0n1  716586.61  0.00       2799.17    0.00       0.00     56052.86  0.00   
> 
> cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
>            1.04%      0.00%      0.00%        0.00%        0.00%       98.96%   
> 
> Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
> Nvme0n1  717690.70  0.00       2803.48    0.00       0.00     56139.20  0.00   
> 
> cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
>            1.04%      0.00%      0.00%        0.00%        0.00%       98.96%   
> 
> Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
> Nvme0n1  716126.04  0.00       2797.37    0.00       0.00     56016.84  0.00   
> 
> cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
>            1.04%      0.00%      0.00%        0.00%        0.00%       98.96%
> ```

@gaowayne - as I mentioned earlier, you need to be careful about assuming that fio showing a slowdown is due to GC, and not due to CPU spending extra time searching through the map for untouched blocks.  The log you've posted here is not helpful - it has no explanation of how it was collected and doesn't provide any guidance for anyone else to reproduce your results.  You have been filing issues here for a long time - you know we always ask for this information, please start adding it proactively without making us always ask for it.  :)

**Comment by gaowayne** [comment] 2023-02-22 15:12
> > > > Linking to the patch addressing this issue https://review.spdk.io/gerrit/c/spdk/spdk/+/16865.
> > > > Thank you @slawekptak !
> > > 
> > > 
> > > Thanks @slawekptak - I posted a few comments, but overall this looks great.
> > 
> > 
> > @slawekptak @jimharris thank you so much. I did a quick test, new method also cannot trigger drive GC and WAF. :( maybe let us lower priority for this. use fio plugin instead.
> > ```
> > Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
> > Nvme0n1  716165.30  0.00       2797.52    0.00       0.00     56019.86  0.00   
> > 
> > cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
> >            1.04%      0.00%      0.00%        0.00%        0.00%       98.96%   
> > 
> > Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
> > Nvme0n1  716586.61  0.00       2799.17    0.00       0.00     56052.86  0.00   
> > 
> > cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
> >            1.04%      0.00%      0.00%        0.00%        0.00%       98.96%   
> > 
> > Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
> > Nvme0n1  717690.70  0.00       2803.48    0.00       0.00     56139.20  0.00   
> > 
> > cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
> >            1.04%      0.00%      0.00%        0.00%        0.00%       98.96%   
> > 
> > Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
> > Nvme0n1  716126.04  0.00       2797.37    0.00       0.00     56016.84  0.00   
> > 
> > cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
> >            1.04%      0.00%      0.00%        0.00%        0.00%       98.96%
> > ```
> 
> @gaowayne - as I mentioned earlier, you need to be careful about assuming that fio showing a slowdown is due to GC, and not due to CPU spending extra time searching through the map for untouched blocks. The log you've posted here is not helpful - it has no explanation of how it was collected and doesn't provide any guidance for anyone else to reproduce your results. You have been filing issues here for a long time - you know we always ask for this information, please start adding it proactively without making us always ask for it. :)

sorry Jim, I updated above comment, please let me know if that clarify things. so sorry about any inconvenient caused. I understand the slowdown you mentioned CPU spending extra time searching through map. based on above log, the drop is not big. if SSD internal WAF and GC happening under uniform random write, SSD perf will drop couple of times based on different OP value. at least WAF is 2, perf drop half. that means if iostat still shows it is close 3GB/s, that means SSD internal WAF is not happening.  maybe I schedule a short 1:1 with Slawomir to explain things if that helps.

**Comment by jimharris** [comment] 2023-02-22 15:42
> 
> sorry Jim, I updated above comment, please let me know if that clarify things. so sorry about any inconvenient caused. I understand the slowdown you mentioned CPU spending extra time searching through map. based on above log, the drop is not big. if SSD internal WAF and GC happening under uniform random write, SSD perf will drop couple of times based on different OP value. at least WAF is 2, perf drop half. that means if iostat still shows it is close 3GB/s, that means SSD internal WAF is not happening. maybe I schedule a short 1:1 with Slawomir to explain things if that helps.

I still don't see the bdevperf command line used to start the workload, nor the iostat.py parameters.  If iostat.py was shown with 1 second interval, then showing a few seconds of output doesn't really prove anything.

**Comment by gaowayne** [comment] 2023-02-23 08:08
> > sorry Jim, I updated above comment, please let me know if that clarify things. so sorry about any inconvenient caused. I understand the slowdown you mentioned CPU spending extra time searching through map. based on above log, the drop is not big. if SSD internal WAF and GC happening under uniform random write, SSD perf will drop couple of times based on different OP value. at least WAF is 2, perf drop half. that means if iostat still shows it is close 3GB/s, that means SSD internal WAF is not happening. maybe I schedule a short 1:1 with Slawomir to explain things if that helps.
> 
> I still don't see the bdevperf command line used to start the workload, nor the iostat.py parameters. If iostat.py was shown with 1 second interval, then showing a few seconds of output doesn't really prove anything.

I see. sorry jim. let me re-write the steps below

**Comment by gaowayne** [comment] 2023-02-23 08:21
to try the new distribution parameter follow below steps.
1. seq precondition the nvme drive(2 round seq write)
```
fio -filename=/dev/nvme3n1 --time_based --buffered=0 --norandommap --refill_buffers --stonewall --randrepeat=0 -direct=1 -iodepth 128 -thread -rw=write -ioengine=libaio -bs=128k -size=100% -numjobs=1 -group_reporting -name=mytest
```
2. run bdevperf with randwrite specify -D
```
build/examples/bdevperf --json ../json/slconly.json --json-ignore-init-errors -r /var/tmp/spdk.sock -m 2 -q 128 -o 4096 -w randwrite -t 3600 -D
```
3. run iostat to monitor BW for more than 20 mins(duration can be different based on your drive size, I am 800G TLC drive), if we can see BW drops dramatically that means WAF happening. if very long run, still keep the same perf with seq write perf, that means no WAF in drive internally happened.
scripts/iostat.py -i 20 -t 6000000000000 -m
```
Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
Nvme0n1  716165.30  0.00       2797.52    0.00       0.00     56019.86  0.00   

cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
           1.04%      0.00%      0.00%        0.00%        0.00%       98.96%   

Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
Nvme0n1  716586.61  0.00       2799.17    0.00       0.00     56052.86  0.00   

cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
           1.04%      0.00%      0.00%        0.00%        0.00%       98.96%   

Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
Nvme0n1  717690.70  0.00       2803.48    0.00       0.00     56139.20  0.00   

cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
           1.04%      0.00%      0.00%        0.00%        0.00%       98.96%   

Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
Nvme0n1  716126.04  0.00       2797.37    0.00       0.00     56016.84  0.00   

cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
           1.04%      0.00%      0.00%        0.00%        0.00%       98.96%
```

**Comment by gaowayne** [comment] 2023-02-23 08:21
to try the new distribution parameter follow below steps.
1. seq precondition the nvme drive(2 round seq write)
```
fio -filename=/dev/nvme3n1 --time_based --buffered=0 --norandommap --refill_buffers --stonewall --randrepeat=0 -direct=1 -iodepth 128 -thread -rw=write -ioengine=libaio -bs=128k -size=100% -numjobs=1 -group_reporting -name=mytest
```
2. run bdevperf with randwrite specify -D
```
build/examples/bdevperf --json ../json/slconly.json --json-ignore-init-errors -r /var/tmp/spdk.sock -m 2 -q 128 -o 4096 -w randwrite -t 3600 -D
```
3. run iostat to monitor BW for more than 20 mins(duration can be different based on your drive size, I am 800G TLC drive), if we can see BW drops dramatically that means WAF happening. if very long run, still keep the same perf with seq write perf, that means no WAF in drive internally happened.
scripts/iostat.py -i 20 -t 6000000000000 -m
```
Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
Nvme0n1  716165.30  0.00       2797.52    0.00       0.00     56019.86  0.00   

cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
           1.04%      0.00%      0.00%        0.00%        0.00%       98.96%   

Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
Nvme0n1  716586.61  0.00       2799.17    0.00       0.00     56052.86  0.00   

cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
           1.04%      0.00%      0.00%        0.00%        0.00%       98.96%   

Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
Nvme0n1  717690.70  0.00       2803.48    0.00       0.00     56139.20  0.00   

cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
           1.04%      0.00%      0.00%        0.00%        0.00%       98.96%   

Device   tps        MB_read/s  MB_wrtn/s  MB_dscd/s  MB_read  MB_wrtn   MB_dscd
Nvme0n1  716126.04  0.00       2797.37    0.00       0.00     56016.84  0.00   

cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
           1.04%      0.00%      0.00%        0.00%        0.00%       98.96%
```

**Comment by jimharris** [comment] 2023-02-24 21:00
Patch has been merged - thanks @slawekptak!

I'd like to close this issue, bdevperf can now do randommap based distribution just like fio.

@gaowayne, if you are able to demonstrate conclusively that SPDK is not doing I/O similarly to fio, you can file a new issue.  It is still not clear that fio slowdowns are not due to extra CPU overhead of fio's randommap implementation.  You may need to use CPU profiler to determine for sure.

For example, I ran an fio test with bdev plugin and null bdev.  This is with release SPDK build, on Xeon server.  Without randommap, perf is at 4M IO/s.  With randommap, perf starts at 2.9M, and slowly degrades to 2.7M, then more sharply degrades to 2.6M as the map gets full.  After full device has been read, randommap gets reset and it goes back to 2.9M.

So we can't just assume that I/O degradation == GC and increased WAF.  Please think of other mechanisms you can use with your devices to gather this information, maybe also discuss with people there like @mmkayPL.

**Closed by jimharris** 2023-02-24 21:00 UTC
Labels: enhancement, Patches out for review

**Comment by gaowayne** [comment] 2023-02-25 02:09
> Patch has been merged - thanks @slawekptak!
> 
> I'd like to close this issue, bdevperf can now do randommap based distribution just like fio.
> 
> @gaowayne, if you are able to demonstrate conclusively that SPDK is not doing I/O similarly to fio, you can file a new issue. It is still not clear that fio slowdowns are not due to extra CPU overhead of fio's randommap implementation. You may need to use CPU profiler to determine for sure.
> 
> For example, I ran an fio test with bdev plugin and null bdev. This is with release SPDK build, on Xeon server. Without randommap, perf is at 4M IO/s. With randommap, perf starts at 2.9M, and slowly degrades to 2.7M, then more sharply degrades to 2.6M as the map gets full. After full device has been read, randommap gets reset and it goes back to 2.9M.
> 
> So we can't just assume that I/O degradation == GC and increased WAF. Please think of other mechanisms you can use with your devices to gather this information, maybe also discuss with people there like @mmkayPL.

thank you so much for your help!~ @jimharris and @slawekptak that make sense.
