### ISSUE TITLE
rpc_client_test: server thread failed to exit in 1 sec: (rc: -1)

### ISSUE THREAD

**Issue by darsto** [spdk/spdk#839] opened 2019-06-24 07:28 UTC
Happened on nightly:

```
************************************
START TEST SUITE test/rpc_client/rpc_client.sh
************************************
 05:48:28	# xtrace_enable
 05:48:28	# test/rpc_client/rpc_client.sh
  05:48:28	# xtrace_enable
 05:48:28	# timing_enter rpc_client
 05:48:28	# xtrace_disable
 05:48:28	# PREV_BASH_OPTS=ehxBE
 05:48:28	# set +x
 05:48:28	# xtrace_enable
 05:48:28	# /var/jenkins/workspace/RBD_BlobFS_tests/RBD_autotest/spdk/test/rpc_client/rpc_client_test
rpc_client_test.c: 136:spdk_jsonrpc_client_check_rpc_method: *NOTICE*: get_spdk_version
rpc_client_test.c: 136:spdk_jsonrpc_client_check_rpc_method: *NOTICE*: get_rpc_methods
rpc_client_test.c: 136:spdk_jsonrpc_client_check_rpc_method: *NOTICE*: rpc_get_methods
rpc_client_test.c: 136:spdk_jsonrpc_client_check_rpc_method: *NOTICE*: hook_conn_close
rpc_client_test.c: 136:spdk_jsonrpc_client_check_rpc_method: *NOTICE*: test_method_runtime
rpc_client_test.c: 136:spdk_jsonrpc_client_check_rpc_method: *NOTICE*: test_method_startup
server thread failed to exit in 1 sec: (rc: -1)
FAILED
  05:48:30	# trap - ERR
  05:48:30	# print_backtrace
  05:48:30	# [[ ehxBE =~ e ]]
  05:48:30	# xtrace_disable
  05:48:30	# PREV_BASH_OPTS=ehxBE
  05:48:30	# set +x
========== Backtrace start: ==========

in test/rpc_client/rpc_client.sh:8 -> main()
     ...
   3   	testdir=$(readlink -f $(dirname $0))
   4   	rootdir=$(readlink -f $testdir/../..)
   5   	source $rootdir/test/common/autotest_common.sh
   6   	
   7   	timing_enter rpc_client
=> 8   	$rootdir/test/rpc_client/rpc_client_test
   9   	timing_exit rpc_client
   10  	
   11  	trap - SIGINT SIGTERM EXIT
     ...

========== Backtrace end ==========
```

https://10.102.17.104:8080/job/RBD_BlobFS_tests/job/RBD_autotest/29733/console
(intel-only, sorry)

D.

**Comment by tomzawadzki** [comment] 2019-06-24 07:49
@darsto FYI nightly jobs have logs on cloudfront - see [job logs](https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-spdk-master-vs-dpdk-master.html) -> [job run status](https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-spdk-master-vs-dpdk-master_198.html) -> [build.log](https://dqtibwqq6s6ux.cloudfront.net/results/autotest-spdk-master-vs-dpdk-master/builds/198/archive/RBD_autotest/build.log)

**Comment by darsto** [comment] 2019-06-24 16:00
Sure, I'm just too lazy to find the corresponding cloudfront link.

**Comment by karlatec** [comment] 2019-07-16 15:22
@darsto @tomzawadzki any repro steps?

**Comment by darsto** [comment] 2019-07-16 16:48
Nope - we only know this test sometimes fails on nightly.

**Comment by tomzawadzki** [comment] 2019-10-22 15:17
[Bug scrub]  Have not been seen for long period of time and unable to reproduce.

**Comment by jimharris** [comment] 2019-10-25 21:11
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_47847.html
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/47847/archive/event_autotest/build.log

**Comment by spdkci** [comment] 2019-11-05 12:06
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48842.html

**Comment by spdkci** [comment] 2019-11-06 10:06
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48922.html

**Comment by spdkci** [comment] 2019-11-06 12:52
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48935.html

**Comment by spdkci** [comment] 2019-11-06 13:02
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48937.html

**Comment by spdkci** [comment] 2019-11-06 22:05
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49028.html

**Comment by jimharris** [comment] 2019-11-06 22:45
I noticed that all of these failures are from running on VMs.  We run this test on every system, and it's never hit on a physical system.

I think we're hitting a CI-related issue, where a thread gets scheduled out just long enough that it results in the 1 second timeout.

I don't really see a need for this 1 second timeout.  Just do the pthread_join() to wait for the server thread to complete.  If it takes more than 1 second, so be it.  We don't want to be fighting unrelated CI peculiarities here.

Patch coming...

**Comment by jimharris** [comment] 2019-11-06 22:52
https://review.gerrithub.io/c/spdk/spdk/+/473490

**Comment by spdkci** [comment] 2019-11-07 16:03
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49150.html

**Comment by jimharris** [comment] 2019-11-07 22:54
Patch merged.

**Closed by jimharris** 2019-11-07 22:54 UTC
Labels: Intermittent Failure, bug
