### ISSUE TITLE
Cloning SPDK repo took over 5 minutes leading to build timeout

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1686] opened 2020-11-18 10:31 UTC
https://ci.spdk.io/results/autotest-per-patch/builds/30440/archive/crypto-autotest/build.log

At first glance, all the tests were passing just fine, however, the build didn't finish. At the very top, it can be seen that cloning the spdk repo took over 5 minutes which definitely could cause an overall timeout of the build (even though it's not seen in the log since it suddenly cuts on the run of the bdevperf).

Note the timestamps:
```
00:00:01.078  Cloning into '/var/jenkins/workspace/crypto-autotest/spdk'...
00:00:05.162  warning: redirecting to https://review.spdk.io/gerrit/spdk/spdk/
00:05:33.215  git version 2.26.2
00:05:35.287  warning: redirecting to https://review.spdk.io/gerrit/spdk/spdk/
```

Most likely just a network hiccup.

**Comment by spdkci** [comment] 2020-11-18 10:32
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_30440.html

**Comment by spdkci** [comment] 2020-11-18 11:08
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_30444.html

**Comment by spdkci** [comment] 2020-11-18 11:09
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_30443.html

**Comment by spdkci** [comment] 2020-11-18 14:17
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_30459.html

**Comment by karlatec** [comment] 2020-11-19 07:26
Already updated local mirror repositories to speed up git fetch/clone operations.

**Comment by spdkci** [comment] 2020-11-19 08:32
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_30488.html

**Comment by spdkci** [comment] 2021-01-08 06:51
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_33568.html

**Comment by karlatec** [comment] 2021-01-08 07:30
@shuhei-matsumoto @AlekseyMarchuk  these reported fails indeed timed out at one of the tests, but are not caused by long SPDK sources checkout. These timeouts are caused by `blob_io_wait` test which should be reported here: https://github.com/spdk/spdk/issues/1675

**Comment by karlatec** [comment] 2021-01-08 07:31
btw @mikeBashStuff  it's been some time since November and no new matching fails are reported. Can we close the issue?

**Comment by tomzawadzki** [comment] 2021-01-12 10:01
Last reported failure was almost two months ago, lets close this issue.

**Comment by spdkci** [comment] 2021-01-20 14:35
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_34550.html

**Comment by spdkci** [comment] 2021-01-20 20:32
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_34606.html

**Comment by spdkci** [comment] 2021-01-20 20:35
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_34611.html

**Comment by spdkci** [comment] 2021-01-20 22:04
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_34633.html

**Comment by spdkci** [comment] 2021-01-21 13:56
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_34819.html

**Comment by jimharris** [comment] 2021-02-03 23:54
Another instance of this failure. https://ci.spdk.io/public_build/autotest-per-patch_35760.html

**Comment by spdkci** [comment] 2021-02-04 05:46
Another instance of this failure. Reported by @AlekseyMarchuk. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_35765.html

**Comment by spdkci** [comment] 2021-02-04 09:50
Another instance of this failure. Reported by @mikeBashStuff. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_35784.html

**Comment by spdkci** [comment] 2021-02-04 10:53
Another instance of this failure. Reported by @tomzawadzki. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_35783.html

**Comment by spdkci** [comment] 2021-02-05 13:55
Another instance of this failure. Reported by @shuhei-matsumoto. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_35782.html

**Comment by spdkci** [comment] 2021-02-08 18:07
Another instance of this failure. Reported by @AlekseyMarchuk. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36092.html

**Comment by spdkci** [comment] 2021-02-08 18:08
Another instance of this failure. Reported by @AlekseyMarchuk. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36093.html

**Comment by spdkci** [comment] 2021-02-09 11:18
Another instance of this failure. Reported by @mikeBashStuff. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36178.html

**Comment by jimharris** [comment] 2021-02-09 14:27
Another instance of this failure. Reported by @floatious. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36198.html

**Comment by spdkci** [comment] 2021-02-09 14:33
Another instance of this failure. Reported by @AlekseyMarchuk. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36206.html

**Comment by spdkci** [comment] 2021-02-09 15:06
Another instance of this failure. Reported by @mikeBashStuff. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36205.html

**Comment by spdkci** [comment] 2021-02-09 16:28
Another instance of this failure. Reported by @floatious. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36217.html

**Comment by spdkci** [comment] 2021-02-09 17:58
Another instance of this failure. Reported by @mikeBashStuff. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36227.html

**Comment by spdkci** [comment] 2021-02-09 18:15
Another instance of this failure. Reported by @floatious. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36212.html

**Comment by spdkci** [comment] 2021-02-10 08:22
Another instance of this failure. Reported by @tomzawadzki. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36176.html

**Comment by spdkci** [comment] 2021-02-18 12:27
Another instance of this failure. Reported by @KKaras169169. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36828.html

**Comment by spdkci** [comment] 2021-03-03 12:32
Another instance of this failure. Reported by @KKaras169169. log: Not Found

**Comment by spdkci** [comment] 2021-03-04 11:14
Another instance of this failure. Reported by @KKaras169169. log: Not Found

**Comment by xjjx** [comment] 2021-03-09 14:50
Today we implemented improvement for cloning submodules.
Previously we used git reference repository only for selected submodules, now we'll cache all submodules.
Also for some jobs (e.g. this crypto-autotest which often failed) we didn't use reference repository at all.
Hopefully problem is solved now :-)

**Closed** 2021-03-22 09:21 UTC
Labels: Infrastructure, Intermittent Failure
