### ISSUE TITLE
setup.sh: error occurred while loading module contigmem.ko

### ISSUE THREAD

**Issue by ankit-sam** [spdk/spdk#3567] opened 2024-10-30 10:52 UTC
Subjob: Freebsd-vg-autotest

```
00:03:38.172   09:38:16  -- spdk/autotest.sh@25 -- # source /home/vagrant/spdk_repo/spdk/test/nvmf/common.sh
00:03:38.172     09:38:16  -- nvmf/common.sh@7 -- # uname -s
00:03:38.172    09:38:16  -- nvmf/common.sh@7 -- # [[ FreeBSD == FreeBSD ]]
00:03:38.172    09:38:16  -- nvmf/common.sh@7 -- # return 0
00:03:38.172   09:38:16  -- spdk/autotest.sh@27 -- # '[' 0 -ne 0 ']'
00:03:38.172    09:38:16  -- spdk/autotest.sh@32 -- # uname -s
00:03:38.172   09:38:16  -- spdk/autotest.sh@32 -- # '[' FreeBSD = Linux ']'
00:03:38.172   09:38:16  -- spdk/autotest.sh@53 -- # start_monitor_resources
00:03:38.172   09:38:16  -- pm/common@17 -- # local monitor
00:03:38.172   09:38:16  -- pm/common@19 -- # for monitor in "${MONITOR_RESOURCES[@]}"
00:03:38.172   09:38:16  -- pm/common@25 -- # sleep 1
00:03:38.172    09:38:16  -- pm/common@21 -- # date +%s
00:03:38.172   09:38:16  -- pm/common@21 -- # /home/vagrant/spdk_repo/spdk/scripts/perf/pm/collect-vmstat -d /home/vagrant/spdk_repo/spdk/../output/power -l -p monitor.autotest.sh.1730281096
00:03:38.172  Redirecting to /home/vagrant/spdk_repo/spdk/../output/power/monitor.autotest.sh.1730281096_collect-vmstat.pm.log
00:03:39.105   09:38:17  -- spdk/autotest.sh@55 -- # trap 'autotest_cleanup || :; exit 1' SIGINT SIGTERM EXIT
00:03:39.105   09:38:17  -- spdk/autotest.sh@57 -- # timing_enter autotest
00:03:39.105   09:38:17  -- common/autotest_common.sh@724 -- # xtrace_disable
00:03:39.105   09:38:17  -- common/autotest_common.sh@10 -- # set +x
00:03:39.105   09:38:17  -- spdk/autotest.sh@59 -- # create_test_list
00:03:39.105   09:38:17  -- common/autotest_common.sh@750 -- # xtrace_disable
00:03:39.105   09:38:17  -- common/autotest_common.sh@10 -- # set +x
00:03:39.105     09:38:17  -- spdk/autotest.sh@61 -- # dirname /home/vagrant/spdk_repo/spdk/autotest.sh
00:03:39.105    09:38:17  -- spdk/autotest.sh@61 -- # readlink -f /home/vagrant/spdk_repo/spdk
00:03:39.105   09:38:17  -- spdk/autotest.sh@61 -- # src=/home/vagrant/spdk_repo/spdk
00:03:39.105   09:38:17  -- spdk/autotest.sh@62 -- # out=/home/vagrant/spdk_repo/spdk/../output
00:03:39.105   09:38:17  -- spdk/autotest.sh@63 -- # cd /home/vagrant/spdk_repo/spdk
00:03:39.105   09:38:17  -- spdk/autotest.sh@65 -- # freebsd_update_contigmem_mod
00:03:39.105    09:38:17  -- common/autotest_common.sh@1455 -- # uname
00:03:39.105   09:38:17  -- common/autotest_common.sh@1455 -- # '[' FreeBSD = FreeBSD ']'
00:03:39.105   09:38:17  -- common/autotest_common.sh@1456 -- # kldunload contigmem.ko
00:03:39.105  kldunload: can't find file contigmem.ko
00:03:39.105   09:38:17  -- common/autotest_common.sh@1456 -- # true
00:03:39.105   09:38:17  -- common/autotest_common.sh@1457 -- # '[' -n '' ']'
00:03:39.105   09:38:17  -- common/autotest_common.sh@1463 -- # cp -f /home/vagrant/spdk_repo/spdk/dpdk/build/kmod/contigmem.ko /boot/modules/
00:03:39.364   09:38:17  -- common/autotest_common.sh@1464 -- # cp -f /home/vagrant/spdk_repo/spdk/dpdk/build/kmod/contigmem.ko /boot/kernel/
00:03:39.364   09:38:17  -- common/autotest_common.sh@1465 -- # cp -f /home/vagrant/spdk_repo/spdk/dpdk/build/kmod/nic_uio.ko /boot/modules/
00:03:39.364   09:38:17  -- common/autotest_common.sh@1466 -- # cp -f /home/vagrant/spdk_repo/spdk/dpdk/build/kmod/nic_uio.ko /boot/kernel/
00:03:39.364   09:38:17  -- spdk/autotest.sh@66 -- # freebsd_set_maxsock_buf
00:03:39.364    09:38:17  -- common/autotest_common.sh@1475 -- # uname
00:03:39.364   09:38:17  -- common/autotest_common.sh@1475 -- # [[ FreeBSD = FreeBSD ]]
00:03:39.364    09:38:17  -- common/autotest_common.sh@1475 -- # sysctl -n kern.ipc.maxsockbuf
00:03:39.364   09:38:17  -- common/autotest_common.sh@1475 -- # (( 2097152 < 4194304 ))
00:03:39.364   09:38:17  -- common/autotest_common.sh@1476 -- # sysctl kern.ipc.maxsockbuf=4194304
00:03:39.364  kern.ipc.maxsockbuf: 2097152 -> 4194304
00:03:39.364   09:38:17  -- spdk/autotest.sh@68 -- # [[ y == y ]]
00:03:39.364   09:38:17  -- spdk/autotest.sh@70 -- # lcov --rc lcov_branch_coverage=1 --rc lcov_function_coverage=1 --rc genhtml_branch_coverage=1 --rc genhtml_function_coverage=1 --rc genhtml_legend=1 --rc geninfo_all_blocks=1 --rc geninfo_unexecuted_blocks=1 --gcov-tool /home/vagrant/spdk_repo/spdk/test/fuzz/llvm/llvm-gcov.sh --version
00:03:39.364  lcov: LCOV version 1.15
00:03:39.364   09:38:17  -- spdk/autotest.sh@72 -- # lcov --rc lcov_branch_coverage=1 --rc lcov_function_coverage=1 --rc genhtml_branch_coverage=1 --rc genhtml_function_coverage=1 --rc genhtml_legend=1 --rc geninfo_all_blocks=1 --rc geninfo_unexecuted_blocks=1 --gcov-tool /home/vagrant/spdk_repo/spdk/test/fuzz/llvm/llvm-gcov.sh -q -c --no-external -i -t Baseline -d /home/vagrant/spdk_repo/spdk -o /home/vagrant/spdk_repo/spdk/../output/cov_base.info
00:03:43.550  geninfo: WARNING: GCOV did not produce any data for /home/vagrant/spdk_repo/spdk/lib/nvmf/mdns_server.gcno
00:03:53.599   09:38:30  -- spdk/autotest.sh@76 -- # timing_enter pre_cleanup
00:03:53.599   09:38:30  -- common/autotest_common.sh@724 -- # xtrace_disable
00:03:53.599   09:38:30  -- common/autotest_common.sh@10 -- # set +x
00:03:53.599   09:38:30  -- spdk/autotest.sh@78 -- # rm -f
00:03:53.599   09:38:30  -- spdk/autotest.sh@81 -- # /home/vagrant/spdk_repo/spdk/scripts/setup.sh reset
00:03:53.599  kldunload: can't find file contigmem.ko
00:03:53.599  kldunload: can't find file nic_uio.ko
00:03:53.599   09:38:30  -- spdk/autotest.sh@83 -- # get_zoned_devs
00:03:53.599   09:38:30  -- common/autotest_common.sh@1655 -- # zoned_devs=()
00:03:53.599   09:38:30  -- common/autotest_common.sh@1655 -- # local -gA zoned_devs
00:03:53.599   09:38:30  -- common/autotest_common.sh@1656 -- # local nvme bdf
00:03:53.599   09:38:30  -- spdk/autotest.sh@85 -- # (( 0 > 0 ))
00:03:53.599   09:38:30  -- spdk/autotest.sh@97 -- # for dev in /dev/nvme*n!(*p*)
00:03:53.599   09:38:30  -- spdk/autotest.sh@99 -- # [[ -z '' ]]
00:03:53.599   09:38:30  -- spdk/autotest.sh@100 -- # block_in_use /dev/nvme0ns1
00:03:53.599   09:38:30  -- scripts/common.sh@381 -- # local block=/dev/nvme0ns1 pt
00:03:53.599   09:38:30  -- scripts/common.sh@390 -- # /home/vagrant/spdk_repo/spdk/scripts/spdk-gpt.py /dev/nvme0ns1
00:03:53.599  nvme0ns1 is not a block device
00:03:53.599    09:38:30  -- scripts/common.sh@394 -- # blkid -s PTTYPE -o value /dev/nvme0ns1
00:03:53.599  /home/vagrant/spdk_repo/spdk/scripts/common.sh: line 394: blkid: command not found
00:03:53.599   09:38:30  -- scripts/common.sh@394 -- # pt=
00:03:53.599   09:38:30  -- scripts/common.sh@395 -- # return 1
00:03:53.599   09:38:30  -- spdk/autotest.sh@101 -- # dd if=/dev/zero of=/dev/nvme0ns1 bs=1M count=1
00:03:53.599  1+0 records in
00:03:53.599  1+0 records out
00:03:53.599  1048576 bytes transferred in 0.006905 secs (151857693 bytes/sec)
00:03:53.599   09:38:30  -- spdk/autotest.sh@105 -- # sync
00:03:53.599   09:38:31  -- spdk/autotest.sh@107 -- # xtrace_disable_per_cmd reap_spdk_processes
00:03:53.599   09:38:31  -- common/autotest_common.sh@22 -- # eval 'reap_spdk_processes 12> /dev/null'
00:03:53.599    09:38:31  -- common/autotest_common.sh@22 -- # reap_spdk_processes
00:03:53.858    09:38:32  -- spdk/autotest.sh@111 -- # uname -s
00:03:53.858   09:38:32  -- spdk/autotest.sh@111 -- # [[ FreeBSD == Linux ]]
00:03:53.858   09:38:32  -- spdk/autotest.sh@115 -- # /home/vagrant/spdk_repo/spdk/scripts/setup.sh status
00:03:53.858  Contigmem (not present)
00:03:53.858  Buffer Size: not set
00:03:53.858  Num Buffers: not set
00:03:53.858  
00:03:53.858  
00:03:53.858  Type     BDF             Vendor Device Driver          
00:03:53.858  NVMe     0:16:0          0x1b36 0x0010 nvme0           
00:03:53.858    09:38:32  -- spdk/autotest.sh@117 -- # uname -s
00:03:53.858   09:38:32  -- spdk/autotest.sh@117 -- # [[ FreeBSD == Linux ]]
00:03:53.858   09:38:32  -- spdk/autotest.sh@122 -- # timing_exit pre_cleanup
00:03:53.858   09:38:32  -- common/autotest_common.sh@730 -- # xtrace_disable
00:03:53.858   09:38:32  -- common/autotest_common.sh@10 -- # set +x
00:03:53.858   09:38:32  -- spdk/autotest.sh@125 -- # timing_enter afterboot
00:03:53.858   09:38:32  -- common/autotest_common.sh@724 -- # xtrace_disable
00:03:53.858   09:38:32  -- common/autotest_common.sh@10 -- # set +x
00:03:53.858   09:38:32  -- spdk/autotest.sh@126 -- # /home/vagrant/spdk_repo/spdk/scripts/setup.sh
00:03:54.118  hw.nic_uio.bdfs="0:16:0"
00:03:54.118  hw.contigmem.num_buffers="8"
00:03:54.118  hw.contigmem.buffer_size="268435456"
00:03:54.686  kldload: an error occurred while loading module contigmem.ko. Please check dmesg(8) for more details.
00:03:54.686    09:38:33  -- spdk/autotest.sh@126 -- # trap - ERR
00:03:54.686    09:38:33  -- spdk/autotest.sh@126 -- # print_backtrace
00:03:54.686    09:38:33  -- common/autotest_common.sh@1155 -- # [[ ehxBET =~ e ]]
00:03:54.686    09:38:33  -- common/autotest_common.sh@1157 -- # args=('/home/vagrant/spdk_repo/autorun-spdk.conf')
00:03:54.686    09:38:33  -- common/autotest_common.sh@1157 -- # local args
00:03:54.686    09:38:33  -- common/autotest_common.sh@1159 -- # xtrace_disable
00:03:54.686    09:38:33  -- common/autotest_common.sh@10 -- # set +x
```

BT
```
[00:03:54.686  ========== Backtrace start: ==========
00:03:54.686  
00:03:54.686  in /home/vagrant/spdk_repo/spdk/autotest.sh:126 -> main(["/home/vagrant/spdk_repo/autorun-spdk.conf"])
00:03:54.686       ...
00:03:54.686     121 	
00:03:54.686     122 	timing_exit pre_cleanup
00:03:54.686     123 	
00:03:54.686     124 	# set up huge pages
00:03:54.686     125 	timing_enter afterboot
00:03:54.686  => 126 	$rootdir/scripts/setup.sh
00:03:54.686     127 	timing_exit afterboot
00:03:54.686     128 	
00:03:54.686     129 	# Revert existing OPAL to factory settings that may have been left from earlier failed tests.
00:03:54.686     130 	# This ensures we won't hit any unexpected failures due to NVMe SSDs being locked.
00:03:54.686     131 	opal_revert_cleanup
00:03:54.686       ...
00:03:54.686  
00:03:54.686  ========== Backtrace end ==========
00:03:54.686    09:38:33  -- common/autotest_common.sh@1196 -- # return 0
00:03:54.686   09:38:33  -- spdk/autotest.sh@1 -- # autotest_cleanup
00:03:54.686   09:38:33  -- common/autotest_common.sh@1394 -- # local autotest_es=1
00:03:54.686   09:38:33  -- common/autotest_common.sh@1395 -- # xtrace_disable
00:03:54.686   09:38:33  -- common/autotest_common.sh@10 -- # set +x
00:04:06.880  kldunload: can't find file contigmem.ko
00:04:06.880  setup.sh cleanup function not yet supported on FreeBSD
00:04:06.880   09:38:44  -- common/autotest_common.sh@1451 -- # return 1
00:04:06.880   09:38:44  -- spdk/autotest.sh@1 -- # :
00:04:06.880   09:38:44  -- spdk/autotest.sh@1 -- # exit 1
00:04:06.880    09:38:44  -- spdk/autorun.sh@27 -- $ trap - ERR
00:04:06.880    09:38:44  -- spdk/autorun.sh@27 -- $ print_backtrace
00:04:06.880    09:38:44  -- common/autotest_common.sh@1155 -- $ [[ ehxBET =~ e ]]
00:04:06.880    09:38:44  -- common/autotest_common.sh@1157 -- $ args=('/home/vagrant/spdk_repo/autorun-spdk.conf')
00:04:06.880    09:38:44  -- common/autotest_common.sh@1157 -- $ local args
00:04:06.880    09:38:44  -- common/autotest_common.sh@1159 -- $ xtrace_disable
00:04:06.880    09:38:44  -- common/autotest_common.sh@10 -- $ set +x
00:04:06.880  ========== Backtrace start: ==========
00:04:06.880  
00:04:06.880  in spdk/autorun.sh:27 -> main(["/home/vagrant/spdk_repo/autorun-spdk.conf"])
00:04:06.880       ...
00:04:06.880     22  	trap 'timing_finish || exit 1' EXIT
00:04:06.880     23  	
00:04:06.880     24  	# Runs agent scripts
00:04:06.880     25  	$rootdir/autobuild.sh "$conf"
00:04:06.880     26  	if ((SPDK_TEST_UNITTEST == 1 || SPDK_RUN_FUNCTIONAL_TEST == 1)); then
00:04:06.880  => 27  		sudo -E $rootdir/autotest.sh "$conf"
00:04:06.880     28  	fi
00:04:06.880       ...
00:04:06.880  
00:04:06.880  ========== Backtrace end ==========]
```

[SPDK CI Jenkins link](https://ci.spdk.io/public_build/autotest-per-patch_131943.html)

**Comment by spdkci** [comment] 2024-10-30 10:54
Another instance of this failure. Reported by @ankit-sam. log: https://ci.spdk.io/public_build/autotest-per-patch_131943.html

**Comment by jimharris** [comment] 2024-10-30 14:45
Note, this is a duplicate of #2694.

**Closed** 2024-10-30 14:50 UTC
Labels: Intermittent Failure
