### ISSUE TITLE
Rpc method run save_config failed.

### ISSUE THREAD

**Issue by ChenBo2333** [spdk/spdk#1421] opened 2020-05-29 08:29 UTC
When run save_config in spdkcli , hung up unexpectedly.

## Expected Behavior
run successfully without errors.

## Current Behavior
/iscsi/target_nodes> create alias_name=disk1 name=iqn.2016-06.io.spdk:disk1 bdev_name_id_pairs=Malloc0:0 pg_ig_mappings=1:1 queue_depth=64
bdev_name_id_pairs: Malloc0:0
pg_ig_mappings: 1:1
/iscsi/target_nodes> cd /
/> save_config filename=dddd.json
Timeout while waiting for response:

## Possible Solution
N/A

## Steps to Reproduce
./app/iscsi_tgt/iscsi_tgt
./spdkcli.py
/iscsi/auth_groups> cd /bdevs/malloc
/bdevs/malloc> create block_size=512 name=Malloc0 size=128
Malloc0
/bdevs/malloc> cd /iscsi/portal_groups
/iscsi/initiator_groups> create initiator_list=ANY netmask_list=ip_address/24 tag=1
/iscsi/initiator_groups> cd ../target_nodes
/iscsi/target_nodes> create alias_name=disk1 name=iqn.2016-06.io.spdk:disk1 bdev_name_id_pairs=Malloc0:0 pg_ig_mappings=1:1 queue_depth=64
bdev_name_id_pairs: Malloc0:0
pg_ig_mappings: 1:1
/iscsi/target_nodes> cd /
/> save_config filename=dddd.json

{"jsonrpc":"2.0","id":83,"result":}

**Comment by yidong0635** [comment] 2020-06-02 06:38
This issue is caused by commit: fad052b0cb156afb876c0bcf68111b6882df7ed7,
with accel always on, but  method of write_config json not good.

**Comment by optimistyzy** [comment] 2020-06-02 06:49
@yidong0635  Do you mean that if we disable IOAT(accel module), this issue will disappear?

**Comment by yidong0635** [comment] 2020-06-02 07:00
@optimistyzy I don't know how to disable accel now, but before this patch it's ok. And these json related functions have not been registered.

**Comment by tomzawadzki** [comment] 2020-06-02 15:48
Following patch resolves this issue:
https://review.spdk.io/gerrit/c/spdk/spdk/+/2550

**Comment by tomzawadzki** [comment] 2020-06-03 07:46
Previously [linked](https://review.spdk.io/gerrit/c/spdk/spdk/+/2550) patch is now merged, the issue should no longer be occurring.

@ChenBo2333 Does the current master work for you ?

**Comment by ChenBo2333** [comment] 2020-06-03 07:54
@tomzawadzki It works,thanks.

**Closed** 2020-06-03 07:55 UTC
Labels: bug
