### ISSUE TITLE
iscsi_tgt reported *ERROR* StatSN(99/227) QCmdSN(127) error

### ISSUE THREAD

**Issue by luzhipeng-zte** [spdk/spdk#590] opened 2019-01-19 02:28 UTC
## Current problem：
1、using spdk iscsi_tgt with nvme ssd for bdev on one host A.
2、Using nvmf-tgt of spdk with bdev by  iSCSI initiator module on another host B  and spdk iscsi initiator connect iscsi target server of host A
3、host C connect  nvmf target of host B

host A spdk print error
iscsi.c:4285:spdk_iscsi_execute: *ERROR*: StatSN(99/227) QCmdSN(127) error
conn.c:1319:spdk_iscsi_conn_handle_incoming_pdus: *ERROR*: spdk_iscsi_execute() fatal error on .....
.....

spdk and dpdk version
spdk v19.01-pre DPDK 18.08.0

**Comment by jimharris** [comment] 2019-01-24 22:31
Closing this issue - let's track progress on #600.  Please see the updates on #600 - we've made good progress on root cause.

**Closed by jimharris** 2019-01-24 22:31 UTC
