### ISSUE TITLE
NVMf/vfio-user: NVMe namespace is unusable in Windows

### ISSUE THREAD

**Issue by tmakatos** [spdk/spdk#2009] opened 2021-06-23 20:09 UTC
## Expected Behavior

Windows should be able to initialize and format the NVMe namespace.

## Current Behavior

Windows fails to initialize the NVMe namespace.

## Steps to Reproduce

Boot a Windows guest from a regular disk with an NVMf/vfio-user disk as secondary and install all available Windows updates. Then try to initialize the disk from the Computer Management utility.

Log collection is tricky in Windows, if you can't repro it I'll look into collecting the relevant logs, however I believe it should be straightforward to repro.

Possibly related:
- #2008 
- #2007 
- #2004 
- #2000

**Comment by jimharris** [comment] 2021-06-23 20:11
Can you post a log from the vfio-user target?  I'd like to see the sequence of commands sent by Windows, including whether it's actually sending any I/O commands.

**Comment by tmakatos** [comment] 2021-06-23 20:12
Sure, gimme a few moments.

**Comment by tmakatos** [comment] 2021-06-24 08:16
Attached log.
[win.zip](https://github.com/spdk/spdk/files/6707508/win.zip)

**Comment by jimharris** [comment] 2021-06-24 15:28
Thanks @tmakatos!  Could you also post a log for a Linux guest when you have a chance?

**Comment by tmakatos** [comment] 2021-06-24 16:10
> Thanks @tmakatos! Could you also post a log for a Linux guest when you have a chance?

Attached.
[debian.zip](https://github.com/spdk/spdk/files/6710685/debian.zip)

**Comment by tmakatos** [comment] 2021-06-25 11:11
Attached Linux and Windows logs with 1 CPU / 1 core.
[logs.zip](https://github.com/spdk/spdk/files/6715760/logs.zip)

**Comment by tmakatos** [comment] 2021-07-19 20:08
With the latest vfio-user patches (https://patchew.org/QEMU/cover.1626675354.git.elena.ufimtseva@oracle.com/) applied on master QEMU I can start a Windows VM as follows:

```
qemu-system-x86_64 -cpu host -enable-kvm -smp 8 -m 2G -object memory-backend-file,id=mem0,size=2G,mem-path=/dev/hugepages,share=on,prealloc=yes, -numa node,memdev=mem0 -hda win10_professional_vdisk.qcow2 -device vfio-user-pci,socket=/var/run/vfio-user.sock,x-enable-migration=on -machine pc-q35-3.1 -vnc :0
```

I accidentally discovered that `-machine pc-q35-3.1 -vnc :0` is essential for Windows to work. Then I get the same errros I've previously reported.

**Comment by changpe1** [comment] 2021-07-20 02:35
Thanks, I will download this QEMU version and try with Windows image.

**Comment by changpe1** [comment] 2021-07-21 02:39
I tested Window10 with QEMU emulated NVMe and it can start successfully, while when I switched to vfio-user emualted NVMe device, it will fail to start, and Windows will issue controller reset several times, so I think this issue most likely related with SPDK vfio-user,  there are some responses don't meet Windows NVMe driver.

**Comment by changpe1** [comment] 2021-07-21 02:44
[windows_qemu_nvme.txt](https://github.com/spdk/spdk/files/6852421/windows_qemu_nvme.txt)

**Comment by tmakatos** [comment] 2021-07-21 08:24
> there are some responses don't meet Windows NVMe driver.

Do you mean that Windows issues NVMe requests that SPDK never processes and issues responses? If so, can you show which requests are those?

**Comment by changpe1** [comment] 2021-07-23 02:15
I think this issue is related with the IRQ setting, I can only see 1 IO command sent from Windows, here is the test scenarios I tried:

1. SPDK enable Write Cache by default, Windows will submit a FLUSH command, and SPDK return the successful response, controller will reset after 40 seconds.
2. Disable Write cache in SPDK, Windows will submit a READ command, and SPDK return the successful response, controller will reset after 10 seconds.

I guess Windows didn't get the correct IRQ, so it got timeout for FLUSH and READ command, and the two commands are with different timeout value.

**Comment by tmakatos** [comment] 2021-07-27 13:50
One other thing I noticed is that under Disk Drives in Device Manager I see 64 "NVMe SPDK bdev Contro" disks instead of 1. I set the max number of namespaces to 1 via  `nvmf_create_subsystem nqn.2019-07.io.spdk:cnode0 --max-namespaces=1 ...` and then get the right number of disks.

**Comment by tmakatos** [comment] 2021-07-27 14:50
Another test we can try is to pass through a physical NVMe controller to Windows and compare the VFIO trace with ours. We might have to disable `-enable-kvm` to make sure we can track the interrupts. @changpe1 what do you think?

**Comment by changpe1** [comment] 2021-07-27 14:57
> Another test we can try is to pass through a physical NVMe controller to Windows and compare the VFIO trace with ours. We might have to disable `-enable-kvm` to make sure we can track the interrupts. @changpe1 what do you think?

I used the same QEMU version as yours, but this QEMU can't start Window if I removed 'enable-kvm' option(no vfio-user-pci at all).

**Comment by tmakatos** [comment] 2021-07-27 14:58
> I used the same QEMU version as yours, but this QEMU can't start Window if I removed 'enable-kvm' option(no vfio-user-pci at all).

OK, then can we try with `-enable-kvm` and see how it differs?

**Comment by changpe1** [comment] 2021-07-27 14:59
> > I used the same QEMU version as yours, but this QEMU can't start Window if I removed 'enable-kvm' option(no vfio-user-pci at all).
> 
> OK, then can we try with `-enable-kvm` and see how it differs?

Yeah, I will try that.

**Comment by changpe1** [comment] 2021-07-28 02:17
[windows_qemu_vfio.txt](https://github.com/spdk/spdk/files/6889813/windows_qemu_vfio.txt)
[windows_qemu_vfio_user.txt](https://github.com/spdk/spdk/files/6889814/windows_qemu_vfio_user.txt)

Here are the vfio trace when staring vfio-user-pci and vfio-pci, I don't see obvious difference between the two devices.

**Comment by changpe1** [comment] 2021-07-28 06:31
I used the trapped MMIO and INTx interrupt to print the vfio trace, and got the following trace at last:

Get Log Page:
vfio_region_write  (VFIO user </var/run/muser/domain/muser1/9/cntrl>:region0+0x1000, 0x14, 4)
vfio_intx_interrupt  (VFIO user </var/run/muser/domain/muser1/9/cntrl>) Pin A
vfio_region_mmaps_set_enabled Region VFIO user </var/run/muser/domain/muser1/9/cntrl> BAR 0 mmaps enabled: 0
vfio_region_mmaps_set_enabled Region VFIO user </var/run/muser/domain/muser1/9/cntrl> BAR 4 mmaps enabled: 0
vfio_region_mmaps_set_enabled Region VFIO user </var/run/muser/domain/muser1/9/cntrl> BAR 5 mmaps enabled: 0
vfio_region_write  (VFIO user </var/run/muser/domain/muser1/9/cntrl>:region0+0xc, 0x1, 4)
vfio_intx_eoi  (VFIO user </var/run/muser/domain/muser1/9/cntrl>) EOI
**vfio_region_write  (VFIO user </var/run/muser/domain/muser1/9/cntrl>:region0+0x1004, 0x10, 4)**
vfio_region_write  (VFIO user </var/run/muser/domain/muser1/9/cntrl>:region0+0x10, 0x1, 4)

Flush:
vfio_region_write  (VFIO user </var/run/muser/domain/muser1/9/cntrl>:region0+0x1008, 0x1, 4)
vfio_intx_interrupt  (VFIO user </var/run/muser/domain/muser1/9/cntrl>) Pin A
vfio_region_mmaps_set_enabled Region VFIO user </var/run/muser/domain/muser1/9/cntrl> BAR 0 mmaps enabled: 0
vfio_region_mmaps_set_enabled Region VFIO user </var/run/muser/domain/muser1/9/cntrl> BAR 4 mmaps enabled: 0
vfio_region_mmaps_set_enabled Region VFIO user </var/run/muser/domain/muser1/9/cntrl> BAR 5 mmaps enabled: 0
vfio_region_write  (VFIO user </var/run/muser/domain/muser1/9/cntrl>:region0+0xc, 0x2, 4)
vfio_intx_eoi  (VFIO user </var/run/muser/domain/muser1/9/cntrl>) EOI
vfio_region_write  (VFIO user </var/run/muser/domain/muser1/9/cntrl>:region0+0x10, 0x2, 4)

For the Get Log Page command, we can get the Completion Head Doorbell MMIO write from Guest, and for the following Flush command, the Completion Head Doorbell MMIO write is missed, but accesses to Interrupt Mask Set/Clear are there.

**Comment by changpe1** [comment] 2021-07-28 06:43
Another exception here is for INTx mode, there is only one Pin A, but for Interrupt Mask Set/Clear accesses, we can see for ADMIN command the value is 0x1, while for Flush command, the value is 0x2.

There might something wrong for the configuration, I would suggest also to check the QEMU driver code.

**Comment by tmakatos** [comment] 2021-07-28 16:04
I had a quick look (I haven't checked all your comments yet). One thing I noticed is that the physical NVMe uses 32 MSI-X (we use 64), so I tested with 32 but no difference. I also disabled mmap'ing BAR0 and it didn't make a difference.

**Comment by tmakatos** [comment] 2021-07-28 16:35
> For the Get Log Page command, we can get the Completion Head Doorbell MMIO write from Guest, and for the following Flush command, the Completion Head Doorbell MMIO write is missed, but accesses to Interrupt Mask Set/Clear are there.

I get what you're saying: the host wrote HDBL which means it know about the request completing. Can we disable flush to further simplify things? Also, use only one queue instead of 64. And maybe use a minimal queue depth, e.g. just 1?

**Comment by changpe1** [comment] 2021-07-29 01:27
> > For the Get Log Page command, we can get the Completion Head Doorbell MMIO write from Guest, and for the following Flush command, the Completion Head Doorbell MMIO write is missed, but accesses to Interrupt Mask Set/Clear are there.
> 
> I get what you're saying: the host wrote HDBL which means it know about the request completing. I think the next step is to check whether any other request after the first fails or is it a flush request specifically that fails. Can we disable flush to further simplify things? Also, can we use only one queue instead of 64? And maybe use a minimal queue depth, e.g. just 1?

I already tried to set SPDK that can support only one IO queue, also I disabled the Write Cache feature in SPDK, and the first command sent from Windows is a READ command, it's same as the FLUSH command, but timeout value is about 10 seconds for READ command.

**Comment by changpe1** [comment] 2021-07-29 02:54
The Windows event reviewer reported that "ERROR – stornvme – Event ID 11: The driver detected a controller error on \Device\RaidPort0", so I guess it maybe still a controller error from the Windows driver's view.

**Comment by changpe1** [comment] 2021-07-29 06:47
Following the direction to check the completion response again, I root cause the issue is that we didn't set the SQID in the completion correctly, Linux driver is using queue pair way and doesn't check that, while Windows driver is checking it, after set it the Windows can work now.

**Comment by changpe1** [comment] 2021-07-29 08:34
here is the patch https://review.spdk.io/gerrit/c/spdk/spdk/+/8971 to fix the issue.

**Comment by jimharris** [comment] 2021-07-30 00:27
Ah, good find @changpe1!

**Comment by changpe1** [comment] 2021-08-09 01:54
patch has been merged, so closing it for now.

**Closed by changpe1** 2021-08-09 01:54 UTC
Labels: bug, Patches out for review
