### ISSUE TITLE
[nvmf-tcp-uring-vg-autotest] spdk_nvme_qpair_process_completion - CQ error - nvmf_target_disconnect test case

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1479] opened 2020-07-08 04:12 UTC
```
00:06:04.290  [2020-07-08 02:59:40.511868] nvme_qpair.c: 558:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
00:06:04.290  Received an unknown error processing completions.
00:06:04.291  starting I/O failed
00:06:04.291  Read completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Read completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Write completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Write completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Read completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Read completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Read completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Write completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Read completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Write completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Write completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Read completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Read completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Read completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Write completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Write completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Read completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Write completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Read completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Write completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Read completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Write completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Read completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Read completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Write completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Read completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Read completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Read completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Write completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  Read completed with error (sct=0, sc=8)
00:06:04.291  starting I/O failed
00:06:04.291  [2020-07-08 02:59:40.512703] nvme_qpair.c: 558:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
00:06:04.291  [2020-07-08 02:59:40.512883] uring.c: 472:uring_sock_create: *ERROR*: connect() failed, errno = 111
00:06:04.291  [2020-07-08 02:59:40.513017] posix.c: 517:posix_sock_create: *ERROR*: connect() failed, errno = 111
00:06:04.291  [2020-07-08 02:59:40.513040] nvme_tcp.c:1626:nvme_tcp_ctrlr_connect_qpair: *ERROR*: sock connection error of tqpair=0x7fecd0000ba0 with addr=127.0.0.1, port=4420
00:06:04.291  qpair failed and we were unable to recover it.
00:06:04.291  [2020-07-08 02:59:40.513158] uring.c: 472:uring_sock_create: *ERROR*: connect() failed, errno = 111
00:06:04.292  [2020-07-08 02:59:40.513248] posix.c: 517:posix_sock_create: *ERROR*: connect() failed, errno = 111
00:06:04.292  [2020-07-08 02:59:40.513274] nvme_tcp.c:1626:nvme_tcp_ctrlr_connect_qpair: *ERROR*: sock connection error of tqpair=0x7fecd0000ba0 with addr=127.0.0.1, port=4420
00:06:04.292  qpair failed and we were unable to recover it.
00:06:04.292  [2020-07-08 02:59:40.513368] uring.c: 472:uring_sock_create: *ERROR*: connect() failed, errno = 111
00:06:04.292  [2020-07-08 02:59:40.513452] posix.c: 517:posix_sock_create: *ERROR*: connect() failed, errno = 111
00:06:04.292  [2020-07-08 02:59:40.513473] nvme_tcp.c:1626:nvme_tcp_ctrlr_connect_qpair: *ERROR*: sock connection error of tqpair=0x7fecd0000ba0 with addr=127.0.0.1, port=4420
00:06:04.292  qpair failed and we were unable to recover it.
00:06:04.292  [2020-07-08 02:59:40.513574] uring.c: 472:uring_sock_create: *ERROR*: connect() failed, errno = 111
00:06:04.292  [2020-07-08 02:59:40.513667] posix.c: 517:posix_sock_create: *ERROR*: connect() failed, errno = 111
00:06:04.292  [2020-07-08 02:59:40.513684] nvme_tcp.c:1626:nvme_tcp_ctrlr_connect_qpair: *ERROR*: sock connection error of tqpair=0x7fecd0000ba0 with addr=127.0.0.1, port=4420
00:06:04.292  qpair failed and we were unable to recover it.
00:06:04.293  [2020-07-08 02:59:40.513776] uring.c: 472:uring_sock_create: *ERROR*: connect() failed, errno = 111
00:06:04.293  [2020-07-08 02:59:40.513877] posix.c: 517:posix_sock_create: *ERROR*: connect() failed, errno = 111
00:06:04.293  [2020-07-08 02:59:40.513895] nvme_tcp.c:1626:nvme_tcp_ctrlr_connect_qpair: *ERROR*: sock connection error of tqpair=0x7fecd0000ba0 with addr=127.0.0.1, port=4420
00:06:04.293  qpair failed and we were unable to recover it.
00:06:04.293  [2020-07-08 02:59:40.514004] uring.c: 472:uring_sock_create: *ERROR*: connect() failed, errno = 111
00:06:04.293  [2020-07-08 02:59:40.514109] posix.c: 517:posix_sock_create: *ERROR*: connect() failed, errno = 111
00:06:04.293  [2020-07-08 02:59:40.514134] nvme_tcp.c:1626:nvme_tcp_ctrlr_connect_qpair: *ERROR*: sock connection error of tqpair=0x7fecd0000ba0 with addr=127.0.0.1, port=4420
00:06:04.293  qpair failed and we were unable to recover it.

```
## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_20744.html

## Execution failed at

```
00:06:09.211  ========== Backtrace start: ==========
00:06:09.211  
00:06:09.224  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:910 -> run_test(["nvmf_target_disconnect"],["test/nvmf/host/target_disconnect.sh"],["--transport=tcp"])
00:06:09.224       ...
00:06:09.224     905 		timing_enter $test_name
00:06:09.224     906 		echo "************************************"
00:06:09.224     907 		echo "START TEST $test_name"
00:06:09.224     908 		echo "************************************"
00:06:09.224     909 		xtrace_restore
00:06:09.224  => 910 		time "$@"
00:06:09.224     911 		xtrace_disable
00:06:09.224     912 		echo "************************************"
00:06:09.224     913 		echo "END TEST $test_name"
00:06:09.224     914 		echo "************************************"
00:06:09.224     915 		timing_exit $test_name
00:06:09.224       ...
00:06:09.232  in ./test/nvmf/nvmf.sh:54 -> main(["--transport=tcp"])
00:06:09.232       ...
00:06:09.232     49  	
00:06:09.232     50  	# TODO: disabled due to intermittent failures (RDMA_CM_EVENT_UNREACHABLE/ETIMEDOUT)
00:06:09.232     51  	#run_test test/nvmf/host/identify_kernel_nvmf.sh $TEST_ARGS
00:06:09.232     52  	run_test "nvmf_aer" test/nvmf/host/aer.sh "${TEST_ARGS[@]}"
00:06:09.232     53  	run_test "nvmf_fio" test/nvmf/host/fio.sh "${TEST_ARGS[@]}"
00:06:09.232  => 54  	run_test "nvmf_target_disconnect" test/nvmf/host/target_disconnect.sh "${TEST_ARGS[@]}"
00:06:09.232     55  	
00:06:09.232     56  	timing_exit host
00:06:09.232     57  	
00:06:09.232     58  	trap - SIGINT SIGTERM EXIT
00:06:09.232     59  	revert_soft_roce
00:06:09.232       ...
00:06:09.232  
00:06:09.232  ========== Backtrace end ==========
```

**Comment by spdkci** [comment] 2020-07-08 04:14
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_20744.html

**Comment by optimistyzy** [comment] 2020-07-08 06:01
Hi Shuhei, this may be related with your patch.  Currently, I see from the pool, the stable reproduced issue with uring is the perf test  with 256 KB I/O size. Let's keep this open and see whether there are same issues with other patches (unrelated with the change on uring)

**Comment by changpe1** [comment] 2020-07-09 04:23
[Bug Scrub] let's keep it open for another week.

**Comment by optimistyzy** [comment] 2020-07-16 02:20
@shuhei-matsumoto  Also close this issue since we did not see the similar log shown in the CI.

**Closed by optimistyzy** 2020-07-16 02:20 UTC
Labels: Intermittent Failure
