### ISSUE TITLE
build failure spdk/dpdk 

### ISSUE THREAD

**Issue by chuckylilin** [spdk/spdk#825] opened 2019-06-17 08:37 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior
build success of spdk/dpdk

## Current Behavior
build failure of spdk/dpdk 
fatal error: rte_hash.h: No such file or directory

## Steps to Reproduce
1. git submodule init
2. git submodule update
3. cd spdk/dpdk
4. make config T=x86_64-native-linuxapp-gcc  && make && make install T=x86_64-native-linuxapp-gcc

## Context (Environment including OS version, SPDK version, etc.)
dpdk: 19.05
centos 7u6

**Comment by Comphix** [comment] 2019-06-17 09:44
Yujin is looking at this issue to clarify some questions and looks like currently the issue is solved.

Thanks,
Gang

**Comment by Yash3667** [comment] 2019-06-17 18:59
Hi, has the updated solution been pushed? I'm also having trouble compiling SPDK.

Steps Taken:
git clone https://github.com/spdk.spdk
cd spdk
git submoule update --init
sudo scripts/pkgdep.sh
./configure
make

I receive an error for dpdk/lib/librte_vhost/vhost_crypto.c:5:10 (fata error: rte_hash.h not found).

**Comment by Comphix** [comment] 2019-06-18 08:41
Close this issue as it has been solved. Please re-open it if you are still seeing problems.

Thanks, Gang

**Comment by glodfish-zg** [comment] 2019-09-03 07:43
can use make -j or in the VM add more cores for example 4 vcpus.

**Comment by jkryl** [comment] 2019-10-23 10:21
Hey @Comphix , could you share more details about the root cause and how it was fixed? The claim that it has been fixed without knowing what was the problem in the first place, does not really help. thanks

**Comment by glodfish-zg** [comment] 2019-10-23 10:52
@jkryl, I guess the DPDK uses more than one thread to compile. So when we set more than 1 vcpu in VM  or use the make -j can solve this issue.

**Comment by jkryl** [comment] 2019-10-23 11:08
@glodfish-zg: I just submitted a ticket for dpdk: https://bugs.dpdk.org/show_bug.cgi?id=356 .  I think that is the true root cause. By playing with -j option you may or may not reverse the order which libraries are built in. But it is far from a decent workaround. So I'm wondering what has been fixed if @Comphix claims that the issue has been fixed. But from the ticket description it is hard to tell what was the problem. I'm missing any kind of analysis.

**Comment by jimharris** [comment] 2019-10-23 12:15
Reopening for now. We should probably pull a patch for this into our DPDK submodule until it is fixed upstream.

**Comment by glodfish-zg** [comment] 2019-10-24 05:10
@jkryl I just replicated this issue and your solution can fix. So could you submit a patch to DPDK to fix this issue?

**Comment by jimharris** [comment] 2019-10-24 12:48
@glodfish-zg Could you create a patch for this for our DPDK submodule?  Would like to get it in for upcoming 19.10 release. Thanks.

**Comment by glodfish-zg** [comment] 2019-10-24 13:36
https://review.gerrithub.io/c/spdk/dpdk/+/472258.
@jimharris  Patch is here. You can check. Thanks.

**Comment by jimharris** [comment] 2019-10-25 15:01
Hi @jkryl - I'll admit I don't prefer e-mail for code reviews either.

@glodfish-zg - can you work on getting your patch pushed upstream?

**Comment by glodfish-zg** [comment] 2019-10-28 04:34
@jkryl  @jimharris 
Understand， I will push it to DPDK.

**Comment by glodfish-zg** [comment] 2019-11-04 01:46
closed. As patch has been merged. Please reopen it if you find this issue again.

**Closed by glodfish-zg** 2019-11-04 01:46 UTC
Labels: help wanted
