### ISSUE TITLE
Hotremove for bdevperf with '-w randwrite' causes that machine freezes

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#1162] opened 2020-01-23 13:33 UTC
Steps to reproduce:
1. Download patch https://review.gerrithub.io/c/spdk/spdk/+/464450
2. Edit test/vhost/hotplug/virtio_hotremove.sh and for bdevperf commands replace "-w verify" with "-w randwrite".
3. Run ./test/vhost/hotplug/virtio_hotremove.sh

**Comment by pawelkax** [comment] 2020-01-27 23:39
Sample script to reproduce this issue:
```
testdir=$(readlink` -f $(dirname $0))
rootdir=$(readlink -f $testdir/../../..)
source $rootdir/test/common/autotest_common.sh
source $rootdir/test/vhost/common.sh
source $rootdir/test/vhost/hotplug/common.sh

vhost_run 0
traddr=$($rpc_py bdev_get_bdevs -b "Nvme0n1" | jq -r '.[].driver_specific.nvme.pci_address')
$rpc_py bdev_split_create Nvme0n1 2
$rpc_py vhost_create_scsi_controller scsi_ctrl
$rpc_py vhost_scsi_controller_add_target scsi_ctrl 0 Nvme0n1p0
$rpc_py vhost_create_blk_controller blk_ctrl Nvme0n1p1

$rootdir/test/bdev/bdevperf/bdevperf -g -q 128 -o 4096 -w randwrite -z -t 15 -r /var/tmp/spdk1.sock &
bdevperf_pid=$!
waitforlisten $bdevperf_pid /var/tmp/spdk1.sock
$rpc_py -s /var/tmp/spdk1.sock bdev_virtio_attach_controller -t user -d scsi -a $(get_vhost_dir 0)/scsi_ctrl VirtioUser0
$rootdir/test/bdev/bdevperf/bdevperf.py -s /var/tmp/spdk1.sock perform_tests &
perftest_pid=$!
sleep 5

$rpc_py bdev_nvme_detach_controller "Nvme0"
sleep 10

wait $perftest_pid
killprocess $bdevperf_pid
vhost_kill 0
```

**Comment by shuhei-matsumoto** [comment] 2020-01-28 00:03
@pawelkax Did you collect any log when the issue occurred?

**Comment by pawelkax** [comment] 2020-01-28 10:41
@shuhei-matsumoto 
Sample logs from this test:
 05:36:17       # /root/spdk/scripts/rpc.py -s /root/vhost_test/vhost/0/rpc.sock -s /var/tmp/spdk1.sock bdev_virtio_attach_controller -t user -d scsi -a /root/vhost_test/vhost/0/scsi_ctrl VirtioUser0
VirtioUser0t0
 05:36:19       # perftest_pid=14088
 05:36:19       # sleep 5
 05:36:19       # /root/spdk/test/bdev/bdevperf/bdevperf.py -s /var/tmp/spdk1.sock perform_tests
Running I/O for 15 seconds...
 05:36:24       # /root/spdk/scripts/rpc.py -s /root/vhost_test/vhost/0/rpc.sock bdev_nvme_detach_controller Nvme0
vhost_blk.c: 682:bdev_remove_cb: *WARNING*: blk_ctrl: hot-removing bdev - all further requests will fail.
Timeout while waiting for response:


Timeout while waiting for response:

**Comment by pawelkax** [comment] 2020-01-28 13:09
I can add that machine freezes for about 40 seconds.

**Comment by pawelkax** [comment] 2020-01-28 13:47
I run this test several times today. My filesystem got broken.

**Comment by shuhei-matsumoto** [comment] 2020-01-29 11:53
Hi @pawelkax 
Thank you for the detailed information and I hope you could restore file systems.
I started but don’t have vhost environment yet. I checked the source code today but could not find anything yet. I’ll continue tomorrow.

Thanks 
Shuhei

**Comment by pawelkax** [comment] 2020-01-29 23:44
Hi @shuhei-matsumoto @tkulasek 
I tried to reproduce this issue today, but I wasn't able.
I was running this test several times but with no efffect.

**Comment by pawelkax** [comment] 2020-01-30 10:48
I can confirm that this issue is not reproducible now.

**Comment by tkulasek** [comment] 2020-01-30 10:54
@shuhei-matsumoto @pawelkax I've tried to reproduce it on fedora 28 VM running tests for several hours in a loop and nothing happen. Logs seems to be clean.

**Comment by pawelkax** [comment] 2020-01-30 12:32
@shuhei-matsumoto @tkulasek 
I also cannot reproduce this issue on ubuntu18 VM. I think we can close this issue now.

**Comment by shuhei-matsumoto** [comment] 2020-01-31 03:53
Thank you for your investigation. Let's close this for now. Please re-open if  reproduced.

**Closed by shuhei-matsumoto** 2020-01-31 03:53 UTC
Labels: Bug Scrub
