### ISSUE TITLE
data errors and addresses in sg list exceeding max MR address

### ISSUE THREAD

**Issue by jonathanrichardson** [spdk/spdk#902] opened 2019-08-08 21:19 UTC
I'm seeing data errors in 19.04 with Intel Optane SSD 900P Series and Express Flash NVMe P4500 drives. They occur almost immediately when the initiator is run. When it happens the initiator hangs and stops sending data. 

## Expected Behavior
No data errors.

## Current Behavior
Data errors occur almost immediately on 128k block size data transfers. It always happens on post_send and seems to occur from the call in request_transfer_out() from lib/nvmf/rdma.c. Our h/w detects the error when ibv_poll_cq is called later and prints out the qp in error. It seems to be in a state where the address used in the sg list exceeds the the max address of the MR. It was suggested that the address came from spdk. I'm trying to prove this but don't have code yet to detect this in spdk. In our verbs lib I don't see ibv_send_wr* modified from the spdk value when ibv_post_send was called. The size of the MR is 0x400000 and seems to be the one registered with resources->cmds_mr.

If I use 4k reads I don't see the problem. Note that I'm using non-default values for InCapsuleDataSize,  MaxIOSize, and IOUnitSize (below). If I use the default I don't see the errors either. It seems to have something to do with these settings. In this code in request_transfer_out() I see no errors in the nvme status, though I do see req-xfer (data transfer nvme opcode) is not always set to 2:
	if (rsp->status.sc == SPDK_NVME_SC_SUCCESS &&
	    req->xfer == SPDK_NVME_DATA_CONTROLLER_TO_HOST) {
		send_wr = &rdma_req->data.wr;
		*data_posted = 1;
		num_outstanding_data_wr = rdma_req->num_outstanding_data_wr;
	}

The target reports the errors below and then the initiator hangs. The target still sends RDMA WRITE's to the initiator which aren't acted upon.

rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200019fff000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200019ffc000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200019ffc000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200019ff9000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200019ff9000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200019ff6000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200019ff6000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200019ff3000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200019ff3000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200019ff0000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x200019ff0000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a051000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a051000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a04e000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a04e000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a04b000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a04b000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a048000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a048000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a045000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a045000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a042000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a042000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a03f000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a03f000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a03b000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a03b000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a038000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a038000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a035000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a035000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a032000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a032000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a02f000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a02f000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a02c000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a02c000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a029000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a029000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a026000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a026000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a023000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a023000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a020000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a020000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a01d000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a01d000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a01a000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a01a000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a017000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a017000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a014000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a014000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a011000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a011000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a00e000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a00e000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a00b000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a00b000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a008000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a008000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a005000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a005000 length=8192
rdma.c:3301:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a002000 length=8192
rdma.c:3248:spdk_nvmf_rdma_poller_poll: *ERROR*: data=0x20001a002000 length=8192 

## Steps to Reproduce

1. On target I use the following config:
[Transport]
  Type RDMA
  MaxQueuesPerSession 64
  MaxQueueDepth 256
  InCapsuleDataSize 4096
  MaxIOSize 8192
  IOUnitSize 8192
  AcceptorCore 0
  NumSharedBuffers 512

[Subsystem0]                                         
  NQN nqn.2016-06.io.spdk:cnode0                     
  Listen RDMA 192.168.2.10:4420                      
  SN SPDK00000000000001                              
  Namespace nvme0n1                                  
  Namespace nvme4n1                                   
  Namespace nvme8n1                                   
  Namespace nvme12n1                                  

2. On initiator:
perf -r "trtype:RDMA adrfam:IPv4 traddr:192.168.2.10 trsvcid:4420" -q 8 -o 131072  -w randread -s 2048 -t 15 -c 0xfff

## Context (Environment including OS version, SPDK version, etc.)
spdk 19.04, dpdk 18.11

**Comment by jonathanrichardson** [comment] 2019-08-10 00:15
Please ignore this for now. There is a discussion with my colleague on the list regarding "Data buffer split over multiple RDMA Memory Regions". We reverted commit 37b7a308941b996f0e69049358a6119ed90d70a2 "memory: fix contiguous memory calculation for unaligned buffers" as a fix but I think it just caused the issue I described here. Since the error happens quickly it seems unlikely no one else has seen it. Time to upgrade DPDK from 18.11 before anything else and then read through Seth's explanation of this change.

**Comment by darsto** [comment] 2019-08-28 05:50
Yes, the data errors are most likely caused by reverting that patch.

As for reaching the max memory registration limit, SPDK with DPDK older than 19.02 puts a few limitations on RDMA. They can be mitigated, quoting from NVMe-oF doc: ( https://spdk.io/doc/nvmf.html#nvmf_rdma_limitations )

`
As RDMA NICs put a limitation on the number of memory regions registered, the SPDK NVMe-oF target application may eventually start failing to allocate more DMA-able memory. This is an imperfection of the DPDK dynamic memory management and is most likely to occur with too many 2MB hugepages reserved at runtime. One type of memory bottleneck is the number of NIC memory regions, e.g., some NICs report as many as 2048 for the maximum number of memory regions. This gives us a 4GB memory limit with 2MB hugepages for the total memory regions. It can be overcome by using 1GB hugepages or by pre-reserving memory at application startup with --mem-size or -s option. All pre-reserved memory will be registered as a single region, but won't be returned to the system until the SPDK application is terminated.
`

DPDK 19.02+ does a much better job at aggregating adjacent memory regions, so it's very likely that you won't reach the limit in your default configuration.

I'm going to close it for now. Please ping me and I'll reopen if needed.

**Closed by darsto** 2019-08-28 05:50 UTC
