### ISSUE TITLE
pci device handling on spdk based applications

### ISSUE THREAD

**Issue by jkalwas** [spdk/spdk#1594] opened 2020-09-15 14:54 UTC
PCI Device attached to vfio-pci driver cannot be unbind if SPDK based app enumerated other PCI Device under the same bus.
Devices are on separate IOMMU groups.

e.g.
Device X with BB:00.1, Device Y with BB:00.2 - both bind to vfio-pci driver.
SPDK X app attached Device X during enumeration.

Two possible issues
* unbind BB:00.2 from vfio-pci fails with 
`[1254279.970475] vfio-pci 0000:BB:00.2: Device is currently in use, task "bash" (6835) blocked until device is released`
* SPDK Y app tries to attach Device Y during enumeration
`EAL: Cannot open /dev/vfio/72: Device or resource busy
EAL: Failed to open group 72
EAL: Driver cannot attach the device (0000:BB:00.2)`

Workaround is to pass Device Y with given BDF to denylist when running SPDK X app.
I'm not sure if this behavior is by design or it is an issue.

## Expected Behavior

After Device X attached with X app it shall be possible to attach Device Y with Y app.

## Current Behavior

Device Y seems busy / claimed despite of the fact it is not used (explicitly) by X app.

## Possible Solution

Use denylist as a workaround.

## Context (Environment including OS version, SPDK version, etc.)

SPDK v20.10-pre git sha1 70a20639985 / DPDK 20.05.0

**Comment by jimharris** [comment] 2020-09-15 15:19
I think this behavior is by design, but will check the DPDK code to confirm.  Either way, we should add some documentation to clarify this behavior for SPDK.

**Comment by jimharris** [comment] 2020-10-27 23:33
This behavior is by design.  There might be a couple of ways to fix it or workaround it, but let me explain first what's happening here.

There are two ways to attach an SPDK driver to a PCI device - spdk_pci_enumerate() and spdk_pci_device_attach().  The problem that @jkalwas describes here is when we use spdk_pci_enumerate().  In this case, DPDK will probe every device that matches the PCI device/vendor/cc of any driver that we've registered (nvme, ioat, idxd, virtio).  SPDK *always* returns success (0) for these probe calls, even if the spdk_pci_enumerate() is for ioat and the probe call is for an nvme device.  We create a local object for this nvme device, and then use it later to satisfy a later spdk_pci_enumerate() call for nvme devices.

The problem is that now even though the SPDK app hasn't explicitly attached to the nvme device, DPDK has, and it means you can't unbind it from vfio-pci, nor can you try to use it in a second SPDK application.

One possible solution which I've prototyped is to actually return failure from the DPDK probe callback for devices not associated with the specific device type we are trying to enumerate.  This works great...except for the DPDK error message you see from the returned error code.  So one possible solution would be squashing this error message, but that may be difficult to get upstream since our use of the DPDK PCI enumeration routines is pretty crazy (in my opinion).

Another solution is to not use spdk_pci_enumerate().  Today we use it for attaching all ioat devices at app startup, and also in the bdev nvme hotplug poller (indirectly through calling spdk_nvme_probe with a NULL transport ID).  I don't think this is really feasible to get away from using spdk_pci_enumerate() though.

The third solution is Jacek's suggestion to just use the allowlist/denylist.

I think the suggested solution for now is the allowlist/denylist.  From talking with Jacek offline this seems OK with him.  Jacek - if you can confirm, we can close this issue now, and reassess solution #1 if needed in the future.

**Comment by jkalwas** [comment] 2020-10-28 09:46
Thank you @jimharris for your investigation.
I confirm that WA proposed here is good enough for now, we can always go back to what you suggested within 1st solution.

> DPDK will probe every device that matches the PCI device/vendor/cc of any driver that we've registered (nvme, ioat, idxd, virtio). 

This means that problem raised initially is slightly more extensive i.e. having registered device X, Y and enumerating X, device Y are getting "blocked". Did I get it right?

**Comment by jimharris** [comment] 2020-10-28 14:21
That is correct Jacek.  Y is blocked because X was attached using spdk_pci_enumerate.

If you used spdk_pci_device_attach to attach X, then Y would not be affected.

**Comment by jkalwas** [comment] 2020-10-29 09:47
Thank you for confirmation - let's follow your recommendation and close for now with known workarounds.
Do you see a value in documenting this behavior? I put proposal here https://review.spdk.io/gerrit/c/spdk/spdk/+/4962.

**Comment by tomzawadzki** [comment] 2020-11-03 15:13
[bug scrub] Patch documenting the behavior was merged.

**Closed by tomzawadzki** 2020-11-03 15:13 UTC
Labels: Sighting
