### ISSUE TITLE
bdevperf exits with active accel channel

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1288] opened 2020-03-17 16:45 UTC
The following error came from https://review.spdk.io/gerrit/c/spdk/spdk/+/1220/8

thread.c: 358:spdk_thread_exit: *ERROR*: thread bdevperf_tg_1 still has active channel for io_device sw_accel_engine

Investigating...

**Comment by shuhei-matsumoto** [comment] 2020-03-19 07:08
Hi @peluse I started investigating this issue too.

**Comment by optimistyzy** [comment] 2020-03-19 07:25
This issue does not only affect bdevperf but every application built on SPDK using IOAT. For example, if you start NVM-oF target with IOAT enabling in the configuration file, and shut down the app, we can also see this issue. According to analysis, the accel engine will free the io channel by calling spdk device unregister function during the accel module destroy routine while the app is shutting down. So my suggestion is that we should create spdk thread in accel module, and let the poller register on the thread in accel module, then this thread can recycle the poller function.   Since NVMe-of Subsystem will be closed first.    @peluse  @shuhei-matsumoto

**Comment by shuhei-matsumoto** [comment] 2020-03-19 07:30
@optimistyzy @peluse This is not poller but IO channel, and IO channel is nested. We have to wait until all nested IO channel are freed. We may be able to use SPDK message as a work around because we can run spdk_thread_poll() by repeating spdk_send_msg().

**Comment by shuhei-matsumoto** [comment] 2020-03-19 09:08
Hi @peluse @optimistyzy 

This is more like a workaround but I created a simple patch to fix the issue.
Will you take a look?
Formal solution may be to manage nesting of I/O channel, to know if I/O channel is got in the parent channel's callback.

**Comment by shuhei-matsumoto** [comment] 2020-03-19 09:42
The following is another idea to fix the issue. https://review.spdk.io/gerrit/c/spdk/spdk/+/1372
Will you take a look too?

I like the latter 1372 because it is completed only in SPDK thread library.
I admit no comment is bad and the patch is not functionally complete.
The patch do not have any awareness about bdev layer's complex I/O channel management. (bdev layer's I/O channel allocates bdev module's I/O channel in the middle.)

I will refine the patch tomorrow and next week.

**Comment by shuhei-matsumoto** [comment] 2020-03-19 10:05
For Ziye’s suggestion, io channel is resource for the caller thread. So the thread have to manage its io channels by itself.
My idea is to improve thread library based on the knowledge of nesting

**Comment by peluse** [comment] 2020-03-19 11:29
@shuhei-matsumoto thanks! I guess I'm leaning towards the first one, seems like its bdevperf's responsibility and if we take care of this kind of cleanup in the thread lib we're opening the dorr for others to do things incorrectly as well and not realize it.  Am I understanding things correctly?

**Comment by shuhei-matsumoto** [comment] 2020-03-19 12:04
Hi @peluse 

Thanks for your reply. Yes I think you understand correctly. 

I found a bug in the latter that it didn’t remove io channel check from thread_exit(), and I will fix it tomorrow.

Honestly I’m leaning toward the lattter because the upper layer cannot know the nesting in the bdev layer such that bdev layer’s callback to get io channel gets bdev module’s io channel.

Thread library can know the nesting instead.

I will complete the latter and want to get competition between these if anyone is not negative. That will provide good perspective to you too.

See you later in your afternoon

**Comment by peluse** [comment] 2020-03-19 13:10
Sounds good, I'll look forward to the next patch. I believe accel_perf probably suffers from the same issue but I haven't looked it (I modeled it after bdevperf though). Will decide what to do there based on your direction with this one.  Thanks @shuhei-matsumoto !

**Comment by optimistyzy** [comment] 2020-03-20 05:41
> Hi @peluse @optimistyzy
> 
> This is more like a workaround but I created a simple patch to fix the issue https://review.spdk.io/gerrit/c/spdk/spdk/+/1370.
> Will you take a look?
> Formal solution may be to manage nesting of I/O channel, to know if I/O channel is got in the parent channel's callback.

@shuhei-matsumoto  You are right, it creates the I/O channel, and there is a poller created in the I/O channel context. But in the spdk_thread_exit, we only check the active pollers, this is why trigger this issue.

**Comment by shuhei-matsumoto** [comment] 2020-03-24 00:13
Hi @peluse 

I created the patch series (6 patches) starting from https://review.spdk.io/gerrit/c/spdk/spdk/+/1390 to fix this issue.

Please take a look or try.

Previously I/O channel and poller which are allocated in the callback to spdk_get_io_channel() (QoS or bdev module) had been freed when finishing bdev library.

But I/O channel and poller are of SPDK thread. So ensuring they are freed at thread exit will be helpful for clarification and will make the operation more deterministic (complete within finite step).

**Comment by spdkci** [comment] 2020-03-24 07:01
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_7570.html

**Comment by spdkci** [comment] 2020-03-26 01:26
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_7831.html

**Comment by jimharris** [comment] 2020-03-30 15:11
Hi @shuhei-matsumoto,

I have reviewed the patches.  The code itself looks OK, but the new nest_level I think will be challenging for new readers to understand.

Can you or @peluse list the specific steps that are causing this issue?  @optimistyzy describes it a little bit earlier in this thread, but a more formal, detailed description would help me understand it more clearly.

Thanks,

-Jim

**Comment by shuhei-matsumoto** [comment] 2020-03-30 22:52
Hi @jimharris @peluse 

Thanks for your review. Your question is very reasonable. I will try to give such explanation. Please stay tune.

**Comment by spdkci** [comment] 2020-03-31 01:42
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_8305.html

**Comment by shuhei-matsumoto** [comment] 2020-03-31 05:30
Hi @jimharris 

Would you check the following?

### bdev I/O channel
For each bdev, a single bdev module is associated.

Each I/O channel has extra resource associated with a particular I/O device.

Each bdev is registered as two I/O devices nestedly, the first I/O device is of the generic bdev layer and the second I/O device is of the associated bdev module.


### Create bdev I/O channel

For a bdev, a user obtains a I/O channel by spdk_bdev_get_io_channel() with a bdev descriptor.

spdk_bdev_get_io_channel() calls spdk_get_io_channel() by extracting the bdev pointer from the descriptor

The spdk_get_io_channel() calls the callback of the generic bdev layer, bdev_channel_create() to create the context of the allocating I/O channel.

bdev_channel_creates() obtains a I/O channel of the associated bdev module by bdev->fn_table->get_io_channel() and includes the obtained I/O channel into the context.

spdk_get_io_channel() is synchronous and so a single call of spdk_bdev_get_io_channel() obtains
both a I/O channel of the generic bdev layer and a I/O channel of the associated bdev module.


### Delete bdev I/O channel

When a user deletes the I/O channel of the bdev, it calls spdk_put_io_channel() with the deleting
I/O channel.

spdk_put_io_channel() decrements reference count of the deleting I/O channel and if it becomes zero, send a message to the caller thread to call _spdk_put_io_channel(), and then return.

_spdk_put_io_channel() calls the callback of the generic bdev layer, bdev_channel_destroy() to delete the context of the deleting I/O channel.

bdev_channel_destroy() deletes the I/O channel of the associated bdev module by spdk_put_io_channel().

This spdk_put_io_channel() call also just decrement the reference count of the I/O channel, sends a message to the caller thread to call _spdk_put_io_channel() to the caller thread, and then return.

The next _spdk_put_io_channel() calls the callback of the associated bdev module to delete the context.


So to delete a bdev I/O channel, at least two messages are necessary to call _spdk_put_io_channel()
for the generic bdev layer and then the associated bdev module. So the reactor has to call spdk_thread_poll() at least twice to complete deleting the bdev I/O channel.

When the first spdk_put_io_channel() returns, the progress is that the reference count of the first I/O channel becomes zero and a single message to call _spdk_put_io_channel() for the first I/O channel is pending at the maximum.

Hence if the user calls spdk_thread_exit() immediately after spdk_put_io_channel() for the bdev I/O channel, the spdk_thread_exit() would fail becaues spdk_thread_exit() requires reference count of all I/O channels are zero.

On the other hand, if the context of the I/O channel does not have any I/O channel, spdk_thread_exit() will succeed even now.

The flow is the following.

1. user calls spdk_put_io_channel() for ch, the bdev I/O channel.
2. spdk_put_io_channel() decrements ch->ref and sends a message to call _spdk_put_io_channel(ch) if ch->ref becomes 0.
3. return to the caller.

4. thread processes the message and calls _spdk_put_io_channel(ch).
5. _spdk_put_io_channel(ch) calls ch->destroy_cb(). The ch->destroy_cb() is bdev_channel_destroy().
6. bdev_channel_destroy() calls spdk_put_io_channel() for ch->channel, the I/O channel of the associated bdev module.
7. spdk_put_io_channel() decrements ch->channel->ref and sends a message to call _spdk_put_io_channel(ch->channel) if ch->channel->ref becomes 0.
8. The spdk_put_io_channel() and then the _spdk_put_io_channel() return.

9. thread processes the message and calls _spdk_put_io_channel(ch).
10. _spdk_put_io_channel(ch) calls ch->destroy_cb(). The ch->destroy_cb() is the callback to the associated bdev module.

If the user calls spdk_thread_exit() after the step #8, the spdk_thread_exit() will succeed.

SPDK thread library can know if the thread passes the step #8 by excluding the check for bdev module's I/O channel from spdk_thread_exit().

**Comment by spdkci** [comment] 2020-03-31 12:25
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_8536.html

**Comment by spdkci** [comment] 2020-03-31 12:54
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_8528.html

**Comment by spdkci** [comment] 2020-03-31 13:41
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_8549.html

**Comment by spdkci** [comment] 2020-03-31 14:36
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_8537.html

**Comment by jimharris** [comment] 2020-03-31 17:58
Thanks @shuhei-matsumoto!  This explanation helped me a lot.

I have an alternate idea - let me know if this would help fix this issue.  I have only compile-tested this RFC patch.

https://review.spdk.io/gerrit/c/spdk/spdk/+/1608

**Comment by peluse** [comment] 2020-03-31 18:06
Phew, good stuff @shuhei-matsumoto!

**Comment by shuhei-matsumoto** [comment] 2020-03-31 20:22
Hi @jimharris 

I replied to your RFC patch. Callback to I/O channel can allocate not only I/O channel but also poller. That says we have to move pending message check to the head of spdk_thread_exit(). This is too relaxed and does little? So I think we need to introduce some tree concept into I/O channel and poller as I figured out by my patches.

**Comment by spdkci** [comment] 2020-04-01 08:16
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_8581.html

**Comment by spdkci** [comment] 2020-04-01 14:52
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_8730.html

**Comment by spdkci** [comment] 2020-04-01 14:53
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_8732.html

**Comment by spdkci** [comment] 2020-04-01 15:03
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_8735.html

**Comment by spdkci** [comment] 2020-04-02 07:35
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_8804.html

**Comment by spdkci** [comment] 2020-04-02 07:37
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_8805.html

**Comment by spdkci** [comment] 2020-04-02 07:37
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_8803.html

**Comment by spdkci** [comment] 2020-04-02 08:03
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_8750.html

**Comment by shuhei-matsumoto** [comment] 2020-04-02 12:51
Hi @jimharris 

The patch series are ready to review again. I knew that bdev QoS channel is not released by nested call as demonstrated by basic_qos test case in test/unit/bdev/mt/bdev.c/bdev_ut.

So some heuristics are necessary and polling until all resource are free or ready to free after calling spdk_thread_exit() looks good idea.

I inserted a patch to hold nested relationship but it is only usable for debug. I'm fine to remove it from the series.

-Shuhei

**Comment by shuhei-matsumoto** [comment] 2020-04-02 14:54
Additional findings.
I knew that I did not check return code of spdk_thread_exit() in bdevperf tool.
blob_io_wait test case in the test pool always fails spdk_thread_exit() because active poller is still registered.

```
thread.c: 337:spdk_thread_exit: *ERROR*: thread bdevperf_reactor_0 still has active poller 0x72bd1e
bdevperf: thread.c:339: spdk_thread_exit: Assertion `false' failed.
./test/blobstore/blob_io_wait/blob_io_wait.sh: line 45: 1192381 Aborted                 (core dumped) $rootdir/test/bdev/bdevperf/bdevperf -c $testdir/bdevperf.conf -q 128 -o 4096 -w write -t 5 -r /var/tmp/spdk.sock

```

I think this result also shows the idea, thread_exit; while (!thread_is_exited) { thread_poll; }; thread_destroy is good.

Thanks for your great insight Jim! See you later.

**Comment by Seth5141** [comment] 2020-04-07 06:49
We should disposition the severity of this bug at the next bug scrub.

**Comment by spdkci** [comment] 2020-04-07 12:53
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_9337.html

**Comment by spdkci** [comment] 2020-04-08 07:47
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_9370.html

**Comment by spdkci** [comment] 2020-04-08 07:48
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_9374.html

**Comment by shuhei-matsumoto** [comment] 2020-04-10 02:20
Thank you. Patch has been merged. Please re-open if reproduced after rebasing to the latest master.

**Closed by shuhei-matsumoto** 2020-04-10 02:20 UTC
Labels: High, Intermittent Failure, bug
