### ISSUE TITLE
[lvol-vg-autotest] Libvirt failure

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#1525] opened 2020-08-01 00:55 UTC
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/23537/archive/lvol-vg-autotest/build.log

## Execution failed at
00:01:05.243  ==> default:  -- Command line args: 
00:01:05.244  ==> default:     -> value=-drive, 
00:01:05.244  ==> default:     -> value=format=raw,file=/var/lib/libvirt/images/backends/ex7-nvme.img,if=none,id=nvme-0, 
00:01:05.244  ==> default:     -> value=-device, 
00:01:05.244  ==> default:     -> value=nvme,drive=nvme-0,serial=12340, 
00:01:05.245  ==> default:     -> value=-drive, 
00:01:05.245  ==> default:     -> value=format=raw,file=/var/lib/libvirt/images/backends/ex7-nvme-multi.img,if=none,id=nvme-1, 
00:01:05.246  ==> default:     -> value=-device, 
00:01:05.246  ==> default:     -> value=nvme,drive=nvme-1,serial=12341,namespaces=3, 
00:01:05.246  ==> default:     -> value=-drive, 
00:01:05.246  ==> default:     -> value=format=raw,file=/var/lib/libvirt/images/backends/ex7-nvme-zero.img,if=none,id=nvme-2, 
00:01:05.247  ==> default:     -> value=-device, 
00:01:05.247  ==> default:     -> value=nvme,drive=nvme-2,serial=12342,namespaces=0, 
00:01:05.248  ==> default:     -> value=-drive, 
00:01:05.248  ==> default:     -> value=format=raw,file=/var/lib/libvirt/images/backends/ex7-nvme-ocssd.img,if=none,id=ocssd-3, 
00:01:05.248  ==> default:     -> value=-device, 
00:01:05.249  ==> default:     -> value=nvme,drive=ocssd-3,serial=deadbeef,oacs=0,namespaces=1,lver=2,lba_index=4,mdts=10,lnum_lun=8,lnum_pln=2,lpgs_per_blk=1536,lsecs_per_pg=2,lblks_per_pln=45,metadata=/var/lib/libvirt/images/backends/ex7-nvme-ocssd.img_ocssd_md,nsdatafile=/var/lib/libvirt/images/backends/ex7-nvme-ocssd.img_ocssd_blknvme.ns,laer_thread_sleep=3000,stride=4, 
00:01:05.869  ==> default: Creating shared folders metadata...
00:01:05.900  ==> default: Starting domain.
00:01:07.158  There was an error talking to Libvirt. The error message is shown
00:01:07.158  below:
00:01:07.158  
00:01:07.158  Call to virDomainCreateWithFlags failed: internal error: process exited while connecting to monitor: qemu-system-x86_64: -realtime mlock=off: warning: '-realtime mlock=...' is deprecated, please use '-overcommit mem-lock=...' instead
00:01:07.158  ioctl(KVM_CREATE_VM) failed: 12 Cannot allocate memory
00:01:07.158  2020-07-31T17:42:03.860761Z qemu-system-x86_64: failed to initialize kvm: Cannot allocate memory
00:01:07.191  + cd fedora31-libvirt
00:01:07.192  + vagrant destroy -f
00:01:10.862  ==> default: Removing domain...
00:01:10.972  Build step 'Execute shell' marked build as failure
00:01:11.060  [PostBuildScript] - [INFO] Executing post build scripts.
00:01:11.072  [lvol-vg-autotest@3] $ /usr/bin/env bash /tmp/jenkins7129280875465278808.sh
00:01:11.075  + mv /var/jenkins/workspace/lvol-vg-autotest@3/fedora31-libvirt/output /var/jenkins/workspace/lvol-vg-autotest@3/output
00:01:11.095  [lvol-vg-autotest@3] $ /usr/bin/env bash /tmp/jenkins2143015027073458336.sh

**Comment by spdkci** [comment] 2020-08-01 00:55
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_23537.html

**Comment by karlatec** [comment] 2020-08-04 07:52
Duplicate of https://github.com/spdk/spdk/issues/1474

**Closed** 2020-08-04 07:52 UTC
Labels: Intermittent Failure, duplicate
