### ISSUE TITLE
SPDK NVMe-oF TCP Target latency increase 

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1867] opened 2021-03-29 16:26 UTC
## Current Behavior

NVMe-oF latency increased due to recent merges on master branch.
Between `b33da506b5` and `346c43edd32` commits average TCP latency using SPDK Target and Initiator increased from ~40-45usec to ~75-80usec.

## Possible Solution

Bisecting leads to this commit as the one resulting in increased latency:
https://review.spdk.io/gerrit/c/spdk/spdk/+/6746
`b67aa514a48baa1b8ed34e315c6b3fa817333418 sock/posix: No longer remove sockets from pending_recv in poll`

## Steps to Reproduce

No exact steps at the moment, but here's a configuration which I use to run the tests:

- SPDK Target:
  -  1 CPU Core
  -  1 nvmf-tcp subsystem
  -  1 nvmf-tcp subsystem namespace (single null_bdev)

- SPDK Initiator:
   -  spdk fio bdev plugin
   - 4k randread QD=1 workload, 60 seconds

- 100G Mellanox ConnectX-5 NIC used to connect systems

## Context (Environment including OS version, SPDK version, etc.)

SPDK 059dcf1da
Fedora 32 5.10.16-100.fc32.x86_64 (both target and initiator)

**Comment by karlatec** [comment] 2021-04-08 11:25
Changed title to `SPDK NVMe-oF TCP Target latency increase` because I will create another TCP latency related issue in a moment

**Comment by benlwalker** [comment] 2021-04-22 21:23
This patch fixes it, but we cannot figure out why. This patch should be doing absolutely nothing.

https://review.spdk.io/gerrit/c/spdk/spdk/+/7479

**Comment by benlwalker** [comment] 2021-04-26 21:02
On the latest master we can't reproduce the latency increase anymore. Closing this out. We can re-open it if it shows up again.

**Closed by benlwalker** 2021-04-26 21:02 UTC
Labels: Sighting
