### ISSUE TITLE
Vhost migration test in NIGHTLY hangs due to NVMf failures

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#506] opened 2018-11-20 08:10 UTC
spdk_vhost.sh --migration run timeout in "fedora-05" for several days, key logs as below:
START TEST SUITE ./test/vhost/spdk_vhost.sh --migration
......
VHOST_CONFIG: /home/sys_sgsw/build_pool/agent/vhost0/naa.VhostScsi0.1: read message VHOST_USER_SET_LOG_BASE
vhost.c: 977:_spdk_vhost_event_send: *ERROR*: Timeout waiting for event: stop device.

## Expected Behavior
spdk_vhost.sh --migration run pass.

## Current Behavior
spdk_vhost.sh --migration run timeout.

## Possible Solution
check spdk_vhost.sh --migration and environment.

## Steps to Reproduce
1. cd SPDK dir
2. run test/vhost/spdk_vhost.sh --migration
3. or look at logs in "fedora-05", https://ci.spdk.io/spdk/builds/review/21e7bbc4d78d512f3095435705ab47c3f8839b2b.1542284466/fedora-05/build.log (search "Timeout waiting for event")

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit 3126157a219271cb4b8cff3b05ac791345e38671

**Comment by darsto** [comment] 2018-11-20 10:08
Looks like it's caused by NVMf failure.

Right after creating the nvmf bdev I see:
`rdma.c: 526:spdk_nvmf_rdma_set_ibv_state: *NOTICE*: IBV QP#1 changed to: IBV_QPS_ERR`

The bdev is created successfully though and can be attached to a vhost scsi controller just fine.

The test hangs on:
`vhost.c: 977:_spdk_vhost_event_send: *ERROR*: Timeout waiting for event: stop device.`

which means there's some outstanding, never-ending I/O

**Comment by benlwalker** [comment] 2018-11-21 17:07
On Tue, 2018-11-20 at 02:08 -0800, Darek Stojaczyk wrote:
> Looks like it's caused by NVMf failure.
> Right after creating the nvmf bdev I see:
> rdma.c: 526:spdk_nvmf_rdma_set_ibv_state: *NOTICE*: IBV QP#1 changed to:
> IBV_QPS_ERR

I need to change this print message because it isn't clear right now. This is
printed out every time a connection drops. Usually that happens after the
discovery connection finishes during probe. It's almost never indicative of an
actual problem.

**Comment by wanqunintel** [comment] 2018-11-23 02:09
@wanghailiangx , would you check about the failure if it's vhost or nvmf related? thanks.

**Comment by darsto** [comment] 2019-02-12 15:32
Bug scrub: We haven't seen those recently and a lot of code has changed. I'm closing this - if it comes back, please ping me and I'll reopen.

**Closed** 2019-02-26 08:36 UTC
Labels: Low, bug
