### ISSUE TITLE
Creating connection got timeout or failed.

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1227] opened 2020-02-25 01:19 UTC
https://ci.spdk.io/results/autotest-per-patch/builds/4622/archive/nvmf-autotest/build.log

```
accel_engine.c: 181:accel_engine_create_cb: *NOTICE*: Acceleration framework using module: SOFTWARE
 01:26:26	# /var/jenkins/workspace/nvmf-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 10.102.17.184 -s 4420
rdma.c:2751:spdk_nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 10.102.17.184 port 4420 ***
 01:26:26	# '[' 0 -eq 1 ']'
 01:26:26	# num_iterations=10
 01:26:26	# set +x
NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
========== Backtrace start: ==========

in test/nvmf/target/connect_disconnect.sh:35 -> main(["--transport=rdma"])
     ...
   30  	fi
   31  	
   32  	set +x
   33  	for i in $(seq 1 $num_iterations); do
   34  		nvme connect -t $TEST_TRANSPORT -n "nqn.2016-06.io.spdk:cnode1" -a "$NVMF_FIRST_TARGET_IP" -s "$NVMF_PORT" $IO_QUEUES
=> 35  		waitforserial "$NVMF_SERIAL"
   36  		nvme disconnect -n "nqn.2016-06.io.spdk:cnode1"
   37  		waitforserial_disconnect "$NVMF_SERIAL"
   38  	done
   39  	set -x
   40  	
```

**Comment by spdkci** [comment] 2020-02-25 01:20
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4622.html

**Comment by spdkci** [comment] 2020-02-25 01:24
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4626.html

**Comment by changpe1** [comment] 2020-02-25 07:23
> Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4626.html

This log shows that it's same with #1228, I've post a fix patch.

**Comment by Comphix** [comment] 2020-02-27 01:33
Duplicate of #1228

**Comment by changpe1** [comment] 2020-02-28 01:18
https://ci.spdk.io/public_build/autotest-per-patch_4974.html, identified this is a different issue.

**Comment by Seth5141** [comment] 2020-04-01 19:16
Closing this as a duplicate of #1252. They exhibit the exact same stack trace.

**Closed by Seth5141** 2020-04-01 19:16 UTC
Labels: Intermittent Failure
