### ISSUE TITLE
IO Errors witnessed on Thin Provisioned Volumes

### ISSUE THREAD

**Issue by SavanAnjaria** [spdk/spdk#906] opened 2019-08-12 05:30 UTC
IO Errors are witnessed on Thin provisioned volumes occupying entire LVS size.
(4k size IO and block size on NVMe bdev as well as LVOL is 512bytes)

## Expected Behavior
NO IO Errors should be seen

## Current Behavior
We are seeing IO errors on the host issuing fio
fio: io_u error on file /dev/nvme4n2: Input/output error: write offset=320041287680, buflen=4096
fio: io_u error on file /dev/nvme4n2: Input/output error: write offset=93405941760, buflen=4096
fio: io_u error on file /dev/nvme4n2: Input/output error: write offset=77231087616, buflen=4096
fio: io_u error on file /dev/nvme4n2: Input/output error: write offset=161028874240, buflen=4096
fio: pid=47807, err=5/file:io_u.c:1756, func=io_u error, error=Input/output error
fio: io_u error on file /dev/nvme4n2: Input/output error: write offset=77231046656, buflen=4096
fio: io_u error on file /dev/nvme4n2: Input/output error: write offset=198169952256, buflen=4096
fio: io_u error on file /dev/nvme4n2: Input/output error: write offset=192772927488, buflen=4096
fio: pid=47808, err=5/file:io_u.c:1756, func=io_u error, error=Input/output error
fio: io_u error on file /dev/nvme4n2: Input/output error: write offset=343717310464, buflen=4096
fio: pid=47812, err=5/file:io_u.c:1756, func=io_u error, error=Input/output error
fio: io_u error on file /dev/nvme4n2: Input/output error: write offset=313703907328, buflen=4096
fio: io_u error on file /dev/nvme4n2: Input/output error: write offset=59138150400, buflen=4096
fio: pid=47803, err=5/file:io_u.c:1756, func=io_u error, error=Input/output error
fio: io_u error on file /dev/nvme4n2: Input/output error: write offset=275997929472, buflen=4096
fio: io_u error on file /dev/nvme4n2: Input/output error: write offset=100051390464, buflen=4096
fio: io_u error on file /dev/nvme4n2: Input/output error: write offset=60763860992, buflen=4096
fio: pid=47813, err=5/file:io_u.c:1756, func=io_u error, error=Input/output error
fio: pid=47816, err=5/file:io_u.c:1756, func=io_u error, error=Input/output error
fio: io_u error on file /dev/nvme4n2: Input/output error: write offset=1276628992, buflen=4096

## Possible Solution
I believe this issue happens when the IOs span across cluster boundaries and we split the IOs in blobstore module. Looks to be some issue with LBA calculation in blobstore.

## Steps to Reproduce
1. Create NVMe Bdev (~350GB) and LVS on top of that
2. Create one large thin provisioned volume occupying the entire LVS size
3. Create another thin provisioned volume occupying the entire LVS size
4. Create NVMf subsystem and attach that with an initiator
5. Start fio random writes on one of the volume exposed to the initiator
fio --name=random-writers --ioengine=libaio --rw=randwrite --bs=4k --iodepth=16 --direct=1 --size=100% --numjobs=16 --filename=/dev/nvme0n1 --time_based --runtime=1200
6. Wait for 2-3 minutes and if IO errors are not seen, switch to running IOs on another volume that was created.

**Comment by SavanAnjaria** [comment] 2019-08-12 05:41
[SPDK_Thin_Prov_IO_Errors.txt](https://github.com/spdk/spdk/files/3491100/SPDK_Thin_Prov_IO_Errors.txt)

**Comment by SavanAnjaria** [comment] 2019-08-12 05:42
I have made sure that, we are not running out of clusters. So, the IO errors seen here are the actual IO errors.
@darsto @jimharris @tomzawadzki

**Comment by tomzawadzki** [comment] 2019-08-13 14:35
Hi @SavanAnjaria 
Please see patch that tries to replicate this issue running on SPDK CI - [here](https://review.gerrithub.io/c/spdk/spdk/+/465075). Pending in CI queue as of this post, awaiting results.

Couple questions to clarify:
1. SPDK NVMe-oF target uses single core?
2. Can you please run with -L flags to see where the EIO error comes from ?
3. Does this happen when fio bs is set to 512 ?
4. Does the linked patch follow the reproduction steps ?
5. Since it wasn't listed in the issue above, just making sure. This is for SPDK master, right ?

**Comment by SavanAnjaria** [comment] 2019-08-13 14:51
@tomzawadzki:
Looked at the script. It will run IOs on both the lvols right? I used to run that on one lvol at a time and wait for the errors to be reported. If I don't see errors on that lvol, I used to switch to another lvol. What's the block size being reported by the lvol info?

Answers to your queries:
1. SPDK NVMe-oF target uses 8 cores in my case. Haven't tried using one core.
2. I have tried using -L blob -L blob_rw -L nvme -L bdev_nvme but, that just says error happened. Not the place from where it is originated. But, I'll keep a trace point and try to capture BT when the first failure is observed.
3. I haven't tried with bs=512bytes yet. I can try and provide the observations.
4. Yes the linked patch follow reproduction steps
5. Yes, this issue is observed on SPDK master.

**Comment by tomzawadzki** [comment] 2019-08-14 13:47
I've changed the [patch](https://review.gerrithub.io/c/spdk/spdk/+/465075) to more closely follow your description:
- changed SPDK NVMe-oF target to use 8 cores
- done 3 minutes of FIO randwrites to first lvol, then proceeded with second.
- added get_bdevs/get_lvol_stores to verify block size of devices. They are 512bytes same as in your scenario.

No reproduction on I/O errors reported in this issue. Please let me know if you've got some suggestions on differences between reproduction steps and the patch.
You might be able to run the test on your machine downloading the patch and calling `sudo ./test/nvmf/target/repro_906.sh --iso --transport=rdma`

PS. Turns out the patch reproduces issue #691 - [link](https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/39949/archive/nvmf_phy_autotest/build.log).

**Comment by SavanAnjaria** [comment] 2019-08-15 11:17
@tomzawadzki : Sure I'll check this from my end and provide an update from my end.

**Comment by SavanAnjaria** [comment] 2019-08-15 11:38
@tomzawadzki : One suspect here is, when the logical to physical block address calculation happens, the physical address goes beyond the Drive's total capacity. Say we are using a 20GB drive to create NVMe Bdev, LVS and LVOLs on that. Now, when the random write knocks an LBA which converts to the offset_blocks that's beyond 20GB range, we may end up seeing IO errors.

I have seen this issue being reproduced in 1-3 minutes time on smaller capacity drives say 300GB but, haven't hit this on larger capacity drives which are in TBs in the same time frame. That's why I suspect the above mentioned scenario.

Can you please verify your script from this angle?

**Comment by SavanAnjaria** [comment] 2019-08-23 03:12
As discussed earlier with @tomzawadzki on slack, I could figure out the area which is responsible for witnessing IO errors.

In _spdk_blob_persist_start,
/* Assign this metadata to pages. This requires two passes -
    * one to verify that there are enough pages and a second
    * to actually claim them. */
   page_num = 0;
   /* Note that this loop starts at one. The first page location is fixed by the blobid. */
   for (i = 1; i < blob->active.num_pages; i++) {
       page_num = spdk_bit_array_find_first_clear(bs->used_md_pages, page_num);
       **if (page_num == UINT32_MAX) {**
           **_spdk_blob_persist_complete(seq, ctx, -ENOMEM);**
           return;
       }
       page_num++;
   }
We are actually hitting a case where the page_num passed in spdk_bit_array_find_first_clear exceeds the array capacity and we are returning -ENOMEM over here. Which would ultimately abort the IO and the same is visible as an IO error on the initiator side

We are not calling spdk_bit_array_clear(bs->used_md_pages, page_num) [which generally happens in _spdk_blob_persist_zero_pages_cpl] the equal number of times as that of the spdk_bit_array_set(bs->used_md_pages, page_num) on a regular interval.

Moreover, we are skipping few page numbers while doing spdk_bit_array_clear. For example we have done spdk_bit_array_set for page number range 1-20. But, while doing spdk_bit_array_clear, we clear the bits for only 10-20 page number ranges.

This results in array bit leakages (some metadata page numbers are already processed but, the corresponding bits are not cleared and are just lying there as Set. Likewise, we are exhausting the entire used_md_pages array (which should never happens if bit_count for this array is equivalent to the number of clusters in the blobstore)

I suspect following things based on this observations:
1. pages[] array of active/clean copy of the blob metadata gets overwritten with a new set of page numbers prior to clearing the bits (corresponding to the pages) in _spdk_blob_persist_zero_pages_cpl.

2. We are somehow missing one batch of pages while writing the blob metadata and finally completing that. Due to that, we are not clearing corresponding bits in used_md_pages when used_md_pages is called.

**Comment by SavanAnjaria** [comment] 2019-09-07 11:11
@tomzawadzki @jimharris 
_spdk_blob_persist_zero_pages_cpl doesn't get called always because when we do spdk_bs_batch_close from _spdk_blob_persist_zero_pages, SPDK finds u.batch.outstanding_ops to be non-zero for some instances. As a result, we aren't able to do spdk_bit_array_clear(bs->used_md_pages, page_num) for some of the batches of metadata pages and run out the metadata pages eventually

**Comment by SavanAnjaria** [comment] 2019-09-12 03:53
@tomzawadzki @jimharris 
Based on all the experiments I did, I could conclude on the following scenario to be happening that causes this issue:
1. As a part of _spdk_blob_persist_start, we populate both blob->active.pages and ctx->pages page arrays with the same page numbers.
2. Here, ctx (spdk_blob_persist_ctx) is going to be the same until we write the metadata pages and zero them out at the end of metadata writes. But, blob->active and blob->clean can change asynchronously as a part of _spdk_blob_mark_clean operation.
3. Now, when the batch of writes completes and _spdk_blob_persist_zero_pages_cpl is called at the end, we are referring to blob->clean.pages while clearing used_md_pages bitmap. But, in some scenarios, blob->clean.pages gets changed (as a part of _spdk_blob_mark_clean) and we end up clearing bits associated with different set of pages.
4. Due to this, bits in used_md_pages bitmap related to a set of pages always remain uncleared we kind of loose them from an inventory of metadata pages. This scenario happens for multiple batches of metadata pages and eventually we run out of the metadata pages which results into returning from _spdk_blob_persist_start with -ENOMEM.
5. We see the corresponding IO being aborted due to that.

Since, spdk_blob_persist_ctx remains same across all these operations, I thought of changing following piece of code
_spdk_blob_persist_zero_pages_cpl() {
...
    for (i = 1; i < blob->clean.num_pages; i++) {
        spdk_bit_array_clear(bs->used_md_pages, **blob->clean.pages[i]**);
    }
...
}

with:
_spdk_blob_persist_zero_pages_cpl() {
...
    for (i = 1; i < blob->clean.num_pages; i++) {
        spdk_bit_array_clear(bs->used_md_pages, **ctx->pages[i - 1].next**);
    }
...
}

And I could see the IO errors issue being fixed. Can you please provide your feedback on this change?

**Comment by SavanAnjaria** [comment] 2019-09-16 06:12
@tomzawadzki @jimharris: Can you please take a look at this?

**Comment by jimharris** [comment] 2019-09-25 06:03
Hi @SavanAnjaria - sorry for the long delay.  Tomek and I have both been swamped the last couple of weeks - I should have time to dig into this later this week.  Thanks for all of your analysis!

**Comment by SavanAnjaria** [comment] 2019-09-26 13:32
@jimharris : No problem Jim. Inputs from you and @tomzawadzki would be really helpful over here.

**Comment by tomzawadzki** [comment] 2019-10-01 08:41
> @tomzawadzki @jimharris
> Based on all the experiments I did, I could conclude on the following scenario to be happening that causes this issue:
> 
> 1. As a part of _spdk_blob_persist_start, we populate both blob->active.pages and ctx->pages page arrays with the same page numbers.

This is right, we create a series of pages containing current md and put in ctx->pages. Assigning new page numbers to both, ctx->pages.next and blob->active.pages. At this point it is known that there is enough place for new md, which now starts being written to the device.
> 2. Here, ctx (spdk_blob_persist_ctx) is going to be the same until we write the metadata pages and zero them out at the end of metadata writes. But, blob->active and blob->clean can change asynchronously as a part of _spdk_blob_mark_clean operation.

Yes, ctx->pages do not change, because it contains new md to be written. What is zeroed out are 'old' md pages from blob->clean.pages. _spdk_blob_mark_clean() happens at the very end of persisting the md, and main point is to assign (now written to disk) blob->active.pages to the blob->clean.pages (which should have been cleared). ctx->pages should not be cleared, since its exactly those pages that are being persisted.
Can you expand a bit what you mean that "blob->active and blob->clean can change asynchronously as a part of _spdk_blob_mark_clean operation" ? **Do you see multiple _spdk_blob_sync_md() going on at the same time for single blob ?**
> 3. Now, when the batch of writes completes and _spdk_blob_persist_zero_pages_cpl is called at the end, we are referring to blob->clean.pages while clearing used_md_pages bitmap. But, in some scenarios, blob->clean.pages gets changed (as a part of _spdk_blob_mark_clean) and we end up clearing bits associated with different set of pages.


> 4. Due to this, bits in used_md_pages bitmap related to a set of pages always remain uncleared we kind of loose them from an inventory of metadata pages. This scenario happens for multiple batches of metadata pages and eventually we run out of the metadata pages which results into returning from _spdk_blob_persist_start with -ENOMEM.


> 5. We see the corresponding IO being aborted due to that.

It makes sense that ENOMEM would not be seen, as any new md that was written to disk is cleared from bit array immediately. **Doesn't the suggested change break loading of blobs or integrity/persistence of thin provisioned data on blobs ?**

From previous posts it seems that issue stems from running out free of entries in used_md_pages. My concern right now are multiple md syncs being issued during cluster allocation. Since allocations are queued up on per channel basis (_spdk_bs_allocate_and_copy_cluster(), ch->need_cluster_alloc), and then the cluster insert/sync is done on md_thread.

**Comment by SavanAnjaria** [comment] 2019-10-01 09:01
@tomzawadzki 
> > @tomzawadzki @jimharris
> > Based on all the experiments I did, I could conclude on the following scenario to be happening that causes this issue:
> > 
> > 1. As a part of _spdk_blob_persist_start, we populate both blob->active.pages and ctx->pages page arrays with the same page numbers.
> 
> This is right, we create a series of pages containing current md and put in ctx->pages. Assigning new page numbers to both, ctx->pages.next and blob->active.pages. At this point it is known that there is enough place for new md, which now starts being written to the device.
> 
> > 1. Here, ctx (spdk_blob_persist_ctx) is going to be the same until we write the metadata pages and zero them out at the end of metadata writes. But, blob->active and blob->clean can change asynchronously as a part of _spdk_blob_mark_clean operation.
> 
> Yes, ctx->pages do not change, because it contains new md to be written. What is zeroed out are 'old' md pages from blob->clean.pages. _spdk_blob_mark_clean() happens at the very end of persisting the md, and main point is to assign (now written to disk) blob->active.pages to the blob->clean.pages (which should have been cleared). ctx->pages should not be cleared, since its exactly those pages that are being persisted.
> Can you expand a bit what you mean that "blob->active and blob->clean can change asynchronously as a part of _spdk_blob_mark_clean operation" ? **Do you see multiple _spdk_blob_sync_md() going on at the same time for single blob ?**
> 
**[Savan]: blob_persist (writing zeros) flow and blob_sync_md flow goes asynchronously I believe. So, I am afraid if by the time _spdk_blob_persist_zero_pages_cpl is called, the blob_sync_md would have happened for another set of pages and hence clean.pages array would be containing different set of pages to be freed.**
> > 1. Now, when the batch of writes completes and _spdk_blob_persist_zero_pages_cpl is called at the end, we are referring to blob->clean.pages while clearing used_md_pages bitmap. But, in some scenarios, blob->clean.pages gets changed (as a part of _spdk_blob_mark_clean) and we end up clearing bits associated with different set of pages.
> 
> > 1. Due to this, bits in used_md_pages bitmap related to a set of pages always remain uncleared we kind of loose them from an inventory of metadata pages. This scenario happens for multiple batches of metadata pages and eventually we run out of the metadata pages which results into returning from _spdk_blob_persist_start with -ENOMEM.
> 
> > 1. We see the corresponding IO being aborted due to that.
> 
> It makes sense that ENOMEM would not be seen, as any new md that was written to disk is cleared from bit array immediately. **Doesn't the suggested change break loading of blobs or integrity/persistence of thin provisioned data on blobs ?**
**[Savan]: I have verified the data as well as metadata integrity across the reboot after making this change.**
> 
> From previous posts it seems that issue stems from running out free of entries in used_md_pages. My concern right now are multiple md syncs being issued during cluster allocation. Since allocations are queued up on per channel basis (_spdk_bs_allocate_and_copy_cluster(), ch->need_cluster_alloc), and then the cluster insert/sync is done on md_thread.

**Comment by tomzawadzki** [comment] 2019-10-08 15:36
[Bug scrub] After short discussion, it looks like we need to make sure that there is just a single md sync for a blob at a time. I'll look at forwarding a test/asserts along with a fix.

**Comment by jimharris** [comment] 2020-01-09 04:26
Bug scrub: @tomzawadzki is there any update on this issue?  Need any help?

**Comment by tomzawadzki** [comment] 2020-02-11 14:25
This issue as previously discussed is related to multiple md syncs going on at the same.
Result of that is clearing incorrect md pages or running out of md pages.

Reproduction of this issue in UT by checking if we are clearing md pages:
https://review.spdk.io/gerrit/c/spdk/spdk/+/774/

Possible fix can be seen here:
https://review.spdk.io/gerrit/c/spdk/spdk/+/776/

**Comment by SavanAnjaria** [comment] 2020-02-18 05:17
@tomzawadzki 
Had a chance to take a look at the code review. If I understand it correctly, we are allowing only 1 persist request at a time and queue the successive requests until the prior one is completed. Once the prior one is completed, we dequeue the next item from the queue.

I just had one suggestion for this approach (couldn't mention that in the review since I don't have permission to do so probably). Please check if it looks feasible and makes sense to you.

Instead of dequeuing just one persist operation on the completion of prior persist operation, can't we club all the persist operations present in the queue at that time and shoot that as a single persist operation? Anyway, we follow cluster allocated bitmap while populating number of pages to be persisted. This will help optimizing the number of persist operations we need to perform against the cluster allocations.

**Comment by jimharris** [comment] 2020-02-27 17:45
@SavanAnjaria - good suggestion.  You should have the ability to review any of the SPDK patches once you set up your account on review.spdk.io - please let us know if you have any problems with that.

@tomzawadzki - can you make a Trello card for this optimization?

Closing this issue since the original problem has been fixed.

**Closed by jimharris** 2020-02-27 17:45 UTC
Labels: High, bug

**Comment by tomzawadzki** [comment] 2020-03-02 12:27
@jimharris @SavanAnjaria Please see Trello card for the mentioned optimization https://trello.com/c/0oiXG9Lt/67-improve-blob-persist-queue-execution
