### ISSUE TITLE
ftl write error with spdk 3.0.0

### ISSUE THREAD

**Issue by john4477** [spdk/spdk#1692] opened 2020-11-19 09:49 UTC
## Expected Behavior

When I run test/ftl/restore.sh, it is successful to write ppa sequentially.
## Current Behavior

ppa from 0 to f is written successfully.
After a few batch of writes(ppa : 1000000 ~ 100000f , 2000000 ~ 200000f ,~, 700000 ~ 700000f) are performed,
writing ppa : 10 is failed.

VM side
```C
Creating filesystem with 80530636 4k blocks and 20135936 inodes
Filesystem UUID: 238d9069-b17a-4ee7-a1ec-7bbf0fd5fbca
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208,
        4096000, 7962624, 11239424, 20480000, 23887872, 71663616, 78675968
Allocating group tables: done
Writing inode tables: done
Creating journal (262144 blocks): done
Writing superblocks and filesystem accounting information: [2020-11-19 17:55:16.149106] nvme_qpair.c: 272:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:189 nsid:1 lba:16 len:16 PRP1 0x200031870000 PRP2 0x2000311fd048
[2020-11-19 17:55:16.149147] nvme_qpair.c: 454:spdk_nvme_print_completion: *NOTICE*: ABORTED - MISSING FUSED (00/0a) qid:1 cid:189 cdw0:ffff sqhd:0009 p:1 m:0 dnr:1
spdk_tgt: ftl_band.c:506: ftl_band_from_addr: Assertion `band_id < ftl_get_num_bands(dev)' failed.
```

qemu (spdk-3.0.0) side
```C
nand_rule: previous page state(W) is not (W) for ppa(0x000000000000000f)
lnvm_rwc: set written + meta status failed with psl[0] = ppa: ch(0), lun(0), blk(0), pg(1), pl(0), sec(0)
```
## Possible Solution
nand rule is that ppa must be written sequentially and qemu(spdk-3.0.0) checks if the previous ppa(present ppa-1) is written before writing the present ppa.
I printed the logs which represent metadata of ppa.
When writing ppa, the corresponding metadata also correctly stores the state. (state : 57 represents LNVM_SEC_WRITTEN).
```C

ppa: ch(0), lun(0), blk(0), pg(0), pl(3), sec(1) /ppa : d, state : 57
ppa: ch(0), lun(0), blk(0), pg(0), pl(3), sec(2) /ppa : e, state : 57
ppa: ch(0), lun(0), blk(0), pg(0), pl(3), sec(3) /ppa : f, state : 57
ppa: ch(0), lun(1), blk(0), pg(0), pl(0), sec(0) /ppa : 1000000, state : 57
ppa: ch(0), lun(1), blk(0), pg(0), pl(0), sec(1) /ppa : 1000001, state : 57
ppa: ch(0), lun(1), blk(0), pg(0), pl(0), sec(2) /ppa : 1000002, state : 57
ppa: ch(0), lun(1), blk(0), pg(0), pl(0), sec(3) /ppa : 1000003, state : 57
ppa: ch(0), lun(1), blk(0), pg(0), pl(1), sec(0) /ppa : 1000004, state : 57

```
However when I write ppa : 10 (next pg or next page),
It shows that the previous metadata has been erased.
```C
nand_rule: previous page state(W) is not (W) for ppa(0x000000000000000f)
prev_ppa: ch(0), lun(0), blk(0), pg(0), pl(3), sec(3) / ppa : f, state : 0
```
The problem may have the following causes.
1. metadata could be erased or reset when write new page.
2. size of metadata is not enough to store a lot of status.

## Steps to Reproduce

1. qemu (spdk-3.0.0) configuration 
```C
./x86_64-softmmu/qemu-system-x86_64 -hda /home/yohan/etc/images2/ubuntu.img -m 32G -smp 4 -cpu host \
        -net user,hostfwd=tcp::3000-:22 \
        -net nic,model=virtio \
        -enable-kvm \
        -display none \
        -device intel-iommu,intremap=on,x-aw-bits=48 -M q35,accel=kvm,kernel-irqchip=split \
        -drive format=raw,file=/home/yohan/etc/images2/myocssd-datafile,if=none,id=myocssd \
        -device nvme,drive=myocssd,serial=deadbeef,lba_index=3,lver=2,lnum_ch=1,lnum_lun=8,lnum_pln=4,lblks_per_pln=512,lpgs_per_blk=1536,lsecs_per_pg=4,metadata=/home/yohan/etc/images2/myocssd-datafile \
        -drive format=raw,file=/home/yohan/etc/images2/restorenvme,if=none,id=mynvme\
        -device nvme,drive=mynvme,serial=deadbeef,lba_index=4,metadata=/home/yohan/etc/images2/myocssd-datafile2
```
2. sudo ./scripts/setup.py
3. sudo ./test/ftl/restore.sh

## Context (Environment including OS version, SPDK version, etc.)
spdk v20.10.x , Ubuntu 18.04.5 , Linux  5.2.0-rc5+

**Comment by gwnet** [comment] 2020-11-25 02:36
@john4477 could you please help reproduce this without qemu? that will be easy for us to debug.

**Comment by tomzawadzki** [comment] 2020-12-01 12:57
@john4477 Latest branch of patches for QEMU that supports open channel emulation are based on QEMU 5.0.0 - see https://github.com/spdk/qemu/commits/spdk-5.0.0. This is what Jenkins CI runs FTL tests on currently. Could you please check if that version reproduces this issue too ?

@gwnet Considering the general lack of available open channel devices, OC emulation in QEMU is easiest way to reproduce and debug FTL at this time. If I've misunderstood, please clarify the request.

**Comment by gaowayne** [comment] 2020-12-14 04:04
@tomzawadzki actually we do not need real open channel device to debug and run ftl device. we can just use malloc, null, nvme, even raid device, ftl can be top of it.

**Comment by Comphix** [comment] 2021-08-19 12:44
@john4477 , from last comments, looks like there is an ask to reproduce the issue? Any updates here? This issue has been opened for more than half year and with no updates recently.

**Comment by jimharris** [comment] 2021-08-19 14:26
Closing this issue.  There are no plans to do any further work with Open Channel in SPDK.

**Closed by jimharris** 2021-08-19 14:26 UTC
Labels: Sighting
