### ISSUE TITLE
nvmf test fails with adq enabled

### ISSUE THREAD

**Issue by wawryk** [spdk/spdk#2113] opened 2021-08-20 08:00 UTC
# Bug report

I made a lot of tries, to find minimal config to reproduce this bug.
The error occurs on both physical disks and null block devices.
I attach matrix screens with the tests performed:
Six null block devices:
![image](https://user-images.githubusercontent.com/15612188/130200247-82210f87-1e3e-4f66-89ca-cb3c86f49911.png)

Six Intel p4610 disks:
![image](https://user-images.githubusercontent.com/15612188/130200472-d1ee1d13-2ffe-4498-bb4b-67e326890b90.png)

Four null block devices:
![image](https://user-images.githubusercontent.com/15612188/130200627-4d830a7f-1ead-421b-865c-c57ac258714e.png)

## Current Behavior
Fails with no results on:
```
fio: io engine spdk_bdev init failed. Perhaps try reducing io depth?
```

## Steps to Reproduce

1. Configure systems and nics
```
configure services: 
sudo systemctl stop firewalld
sudo systemctl stop irqbalance
sudo systemctl stop lldpad.service
sudo systemctl stop lldpad.socket

sysctl tuning on target: 
net.core.busy_poll = 0
net.core.busy_read = 1
net.core.somaxconn = 4096
net.core.netdev_max_backlog = 8192
net.ipv4.tcp_max_syn_backlog = 16384
net.core.rmem_max = 268435456
net.core.wmem_max = 268435456
net.ipv4.tcp_mem = 268435456 268435456 268435456
net.ipv4.tcp_rmem = 8192 1048576 33554432
net.ipv4.tcp_wmem = 8192 1048576 33554432
net.ipv4.route.flush = 1
vm.overcommit_memory = 1

Set cpu governor to performance: 
sudo cpupower frequency-set -g performance

Setting NIC irq affinity:
sudo /usr/src/local/mlnx-tools/ofed_scripts/set_irq_affinity.sh ens786f0

Disabled transparent hugepages
echo never > /sys/kernel/mm/transparent_hugepage/enabled

Configure NIC:
sudo rmmod ice
sudo modprobe ice
sudo ethtool -K ens786f0 hw-tc-offload on
sudo ethtool --set-priv-flags ens786f0 channel-inline-flow-director on
sudo ethtool --set-priv-flags ens786f0 fw-lldp-agent off
sudo ethtool --set-priv-flags ens786f0 channel-pkt-inspect-optimize off
sudo ethtool --set-priv-flags ens786f0 channel-pkt-clean-bp-stop on
sudo ethtool --set-priv-flags ens786f0 channel-pkt-clean-bp-stop-cfg on
sudo tc qdisc add dev ens786f0 root mqprio num_tc 2 map 0 1 queues 2@0 1@2 hw 1 mode channel
sudo tc qdisc add dev ens786f0 ingress
sudo tc filter add dev ens786f0 protocol ip ingress prio 1 flower dst_ip 20.0.0.2/32 ip_proto tcp src_port 4420 skip_sw hw_tc 1
```
2. Build spdk and prepare disks on target side:
```
sudo ./build/bin/nvmf_tgt &
sudo ./scripts/rpc.py nvmf_create_transport -t tcp -u 8192 -m 4 -c 0
sudo ./scripts/rpc.py bdev_malloc_create -b Malloc0 512 512
sudo ./scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1
sudo ./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
sudo scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 20.0.0.1 -s 4420
```
3. Connect disks on initiator side
4. Run fio test on initiator side
Example fio conf:
```
[global]
ioengine=/tmp/spdk/build/fio/spdk_bdev
spdk_json_conf=/tmp/spdk/bdev.conf
thread=1
group_reporting=1
direct=1
percentile_list=50:90:99:99.5:99.9:99.99:99.999

norandommap=1
rw=randwrite
rwmixread=100
bs=4k
time_based=1
ramp_time=10
runtime=60
rate_iops=0
numjobs=3

[filename0]
filename=Nvme0n1
iodepth=21
[filename1]
filename=Nvme1n1
iodepth=21
[filename2]
filename=Nvme2n1
iodepth=21
[filename3]
filename=Nvme3n1
iodepth=21
[filename4]
filename=Nvme4n1
iodepth=21
[filename5]
filename=Nvme5n1
iodepth=21
```

## Context (Environment including OS version, SPDK version, etc.)

NIC: Intel(R) Ethernet Network Adapter E810-CQDA2
ICE driver version: 1.6.4
fio version: fio-3.19
nvme version 1.10.1

**Comment by tomzawadzki** [comment] 2021-08-24 13:08
@wawryk Can you provide all the logs from the fio ?
> fio: io engine spdk_bdev init failed. Perhaps try reducing io depth?

The spdk_bdev fio plugin in almost all error cases in `spdk_fio_init()` prints SPDK_ERRLOG.

**Comment by wawryk** [comment] 2021-08-24 14:51
whole fio log from my last run:
```
fio: io engine spdk_bdev init failed. Perhaps try reducing io depth?
fio: pid=667109, err=-1/
```

**Comment by optimistyzy** [comment] 2021-08-25 09:20
@wawryk If you do not enable adq,will it have same error?

**Comment by wawryk** [comment] 2021-08-25 11:50
@optimistyzy when adq is not enabled, then all test cases pass correct.

Found some extra logs:
```
posix.c:1284:posix_sock_group_impl_add_sock: *ERROR*: Failed to insert sock group into map: -22
tcp.c:2657:nvmf_tcp_poll_group_add: *ERROR*: Could not add sock to sock_group: No such file or directory (2)
nvmf.c: 839:_nvmf_poll_group_add: *ERROR*: Unable to add the qpair to a poll group.

nvme_qpair.c: 720:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 1
nvme_tcp.c:1826:nvme_tcp_qpair_icreq_send: *ERROR*: Failed to construct the tqpair=0x7f6e40041240 via correct icresp
nvme_tcp.c:1934:nvme_tcp_ctrlr_connect_qpair: *ERROR*: Unable to connect the tqpair
bdev_nvme.c: 430:bdev_nvme_create_qpair: *ERROR*: Unable to connect I/O qpair.
common.c: 235:bdev_nvme_create_bdev_channel_cb: *ERROR*: Failed to alloc io_channel.
fio_plugin.c: 552:spdk_fio_bdev_open: *ERROR*: Unable to get I/O channel for bdev.
fio: io engine spdk_bdev init failed. Perhaps try reducing io depth?
nvme_fabric.c: 452:nvme_fabric_qpair_connect: *ERROR*: Connect command failed, rc -125, trtype:TCP adrfam:IPv4 traddr:20.0.1.1 trsvcid:4420 subnqn:nqn.2018-09.io.spdk:cnode3
nvme_tcp.c:1940:nvme_tcp_ctrlr_connect_qpair: *ERROR*: Failed to send an NVMe-oF Fabric CONNECT command
bdev_nvme.c: 430:bdev_nvme_create_qpair: *ERROR*: Unable to connect I/O qpair.
common.c: 235:bdev_nvme_create_bdev_channel_cb: *ERROR*: Failed to alloc io_channel.
fio_plugin.c: 552:spdk_fio_bdev_open: *ERROR*: Unable to get I/O channel for bdev.
fio: io engine spdk_bdev init failed. Perhaps try reducing io depth?
```

**Comment by optimistyzy** [comment] 2021-08-30 07:43
@wawryk You try to enable the ADQ in the target side, right?  
If you try to enable adq in the target side.
1 I think that firstly, you need to enable: enable_placement_id setting in your rpc, e.g.,  sock_impl_set_options --enable_placement_id=1
2  For using NVMe-of tcp,  I did not see use: "sudo ./scripts/rpc.py nvmf_create_transport -t tcp -u 8192 -m 4 -c 0".  So what's the socket priority setting.  With   -y SOCK_PRIORITY  You should set it to 1 (traffic class = 1), right? 
3 secondly,  if you use only one CPU for the target side,  I think that whatever you use adq or not, you will use one CPU core to drive all the queues.  And in your configuration, you used 1 queues for TC class = 1. This is right.

**Comment by wawryk** [comment] 2021-08-31 07:19
@optimistyzy 
I try to enable it on both, target and initiator side.
In tests presented above, I have set:
sock_impl_set_options:
```
enable_placement_id=1
```
bdev_nvme_set_options:
```
timeout_us=0
action_on_timeout=None
nvme_adminq_poll_period_us=100000
retry_count=4
```
nvmf_set_config:
```
acceptor_poll_rate=10000
```
Transport settings: 
```
SPDK NVMeOF transport layer:
[
  {
    "trtype": "TCP",
    "max_queue_depth": 128,
    "max_io_qpairs_per_ctrlr": 127,
    "in_capsule_data_size": 4096,
    "max_io_size": 131072,
    "io_unit_size": 131072,
    "max_aq_depth": 128,
    "num_shared_buffers": 4096,
    "buf_cache_size": 32,
    "dif_insert_or_strip": false,
    "c2h_success": true,
    "sock_priority": 1,
    "abort_timeout_sec": 1
  }
]
```

**Comment by wawryk** [comment] 2021-09-08 13:24
@optimistyzy 
sorry for my late response but I had few vacation days :) 

Can You tell me how to check this:
```
you need kernel support in adq part to support So_Mark based scheduling
```
and, how can I use `you should use another value 3 for placement id` for fio plugin on initiator side ?

**Comment by wawryk** [comment] 2021-09-13 07:58
@optimistyzy 
when adq is enabled only on target side it works fine

**Comment by tomzawadzki** [comment] 2021-10-05 07:55
After some further testing this look like a target issue. Initiator failures are seen due to failing to connect the NVMe-oF qpairs.

Adding a bit of [logs ](https://review.spdk.io/gerrit/c/spdk/spdk/+/9669)around the sock_map placement it seems that issue stems from `spdk_sock_map_lookup()` being done on different thread than `spdk_sock_map_insert()`. More importantly resulting in race between lookup and insert of matching poll_group into the sock_map.

Please see below from the patch above that shows two lookups first, then followed up with two inserts to different poll groups.
```
22:06:39 [2021-10-04 22:06:25.297969] sock.c: 152:spdk_sock_map_lookup: *ERROR*: For placement_id:11589 optimal group is (nil). rc:0
...
22:06:39 [2021-10-04 22:06:25.298126] sock.c: 152:spdk_sock_map_lookup: *ERROR*: For placement_id:11589 optimal group is (nil). rc:0
...
22:06:39 [2021-10-04 22:06:25.298376] sock.c:  75:spdk_sock_map_insert: *ERROR*: placement_id:11589 was assigned a NULL group. Replacing with 0x7f43f0011170
...
22:06:39 [2021-10-04 22:06:25.299246] sock.c:  77:spdk_sock_map_insert: *ERROR*: Cannot put placement_id:11589 to sock_group 0x7f43dc011170, it was already matched with 0x7f43f0011170
22:06:39 [2021-10-04 22:06:25.299273] posix.c:1224:posix_sock_group_impl_add_sock: *ERROR*: Failed to insert sock group into map: -22
22:06:39 [2021-10-04 22:06:25.299282] tcp.c:2661:nvmf_tcp_poll_group_add: *ERROR*: Could not add sock to sock_group: Resource temporarily unavailable (11)
22:06:39 [2021-10-04 22:06:25.299288] nvmf.c: 831:_nvmf_poll_group_add: *ERROR*: Unable to add the qpair to a poll group.
```

Interesting part is error handling for insert during `posix_sock_group_impl_add_sock()`
```
rc = spdk_sock_map_insert(&g_map, sock->placement_id, &group->base);
if (rc != 0) {
	SPDK_ERRLOG("Failed to insert sock group into map: %d\n", rc);
	/* Do not treat this as an error. The system will continue running. */
}
```
The above reports the `rc` up the stack, resulting in failure to create the new qpair. A workaround for the errors seen in this GH issue would be to set the rc to 0 and allow for the qpair to be placed on the poll group. In the end that would mean that all priority_id's encountering this race, would have at least one qpair placed on sub-optimal poll group. This obviously is not the resolution.

The solution would be to assign the poll_group right after the lookup (or during if we consider more than one nvmf_tgt).

**Comment by karlatec** [comment] 2022-03-04 10:23
@tomzawadzki  I was able to test https://review.spdk.io/gerrit/c/spdk/spdk/+/10271/ on one of our setups.

I tested with:
* TCP transport layer
* 40CPU SPDK Target
* 14 NVMes / subsystems on Target side
* 2 SPDK initiators (each running IO using 21 threads)
* 4k randread, QD=256, runtime=60

Without ADQ IOPS ~= 7.7-8.3M
With ADQ on Target only IOPS ~= 8.3~9.0M
With ADQ on both Target and Initiators IOPS ~= 1.5M
(result spread is quite large because I did not precondition the drives).

I did not experience any crashes or issues like in previous comments.

**Comment by jimharris** [comment] 2022-03-04 15:35
Thanks @karlatec!  Last comment from @tomzawadzki on that patch was:

"MaciekW reported nvmf_perf with ADQ enabled, encountering issues. Will be debugging to see if the cause is this patch, or something different."

Based on your tests, can we move forward with getting this patch reviewed and merged, and then close this issue?

**Comment by tomzawadzki** [comment] 2022-03-07 07:40
@jimharris that's correct, I've not updated the patch removing the -1.
https://review.spdk.io/gerrit/c/spdk/spdk/+/10271/

**Comment by karlatec** [comment] 2022-03-08 06:52
> Based on your tests, can we move forward with getting this patch reviewed and merged, and then close this issue?

I think so. Gave my +1 on the patch

**Closed** 2022-04-01 12:41 UTC
Labels: bug, Medium, Patches out for review
