### ISSUE TITLE
Intermittent failure: aio_bdev0 not found in bdev_lvol_get_lvstores

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#1035] opened 2019-11-06 09:10 UTC
Error when creating lvol store:
INFO: RPC COMMAND bdev_lvol_get_lvstores
FAILED: UUID: lvol store request:
{
  "method": "bdev_lvol_create_lvstore",
  "req_id": 1,
  "bdev_name": "aio_bdev0",
  "lvs_name": "lvs_test_1M",
  "cluster_sz": 1048576
}
Got JSON-RPC error response
response:
{
  "code": 19,
  "message": "Unknown error -19"
} on base_bdev: aio_bdev0 not found in bdev_lvol_get_lvstores()

Log: https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/48911/archive/lvol_autotest/build.log

**Comment by spdkci** [comment] 2019-11-06 09:11
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48911.html

**Comment by jimharris** [comment] 2019-11-06 23:47
This is actually a duplicate of #1017.  If you scroll further up in the log from what was posted here, you'll see an exact match of #1017 

Closing this issue, and will copy this log URL to #1017

**Closed by jimharris** 2019-11-06 23:47 UTC
Labels: Intermittent Failure
