### ISSUE TITLE
[nvmf-phy-autotest] Build timeout due to keep alive timeout inside nvmf_abort test

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2102] opened 2021-08-17 13:01 UTC
Build timed out during "Disconnecting host..." step in nvmf_abort test.

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/56269/archive/nvmf-phy-autotest/build.log

## Execution failed at

**_00:09:58.876_**  [2021-08-17 14:24:01.146974] ctrlr.c: 185:nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host nqn.2014-08.org.nvmexpress:uuid:86fe52ac-799c-4c9e-9a99-cd66fdb65059 from subsystem nqn.2016-06.io.spdk:cnode0 due to keep alive timeout.
**_00:16:49.393_**  Build timed out (after 15 minutes). Marking the build as failed.
00:16:49.492  Build was aborted
00:16:49.493  [PostBuildScript] - [INFO] Executing post build scripts.

**Comment by spdkci** [comment] 2021-08-17 13:02
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_56269.html

**Comment by spdkci** [comment] 2021-08-17 13:03
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_56263.html

**Comment by spdkci** [comment] 2021-08-17 14:04
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_56275.html

**Comment by spdkci** [comment] 2021-08-18 07:19
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_56306.html

**Comment by ksztyber** [comment] 2021-08-18 08:46
I think this might be fixed by 5b2e9b229c8c2845637e2cdf37f6a2289268104e. Could you rebase your patches and check if it happens again?

**Comment by spdkci** [comment] 2021-08-19 21:00
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_56207.html

**Comment by spdkci** [comment] 2021-08-19 21:00
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_56208.html

**Comment by spdkci** [comment] 2021-08-23 02:27
Another instance of this failure. Reported by @richael02. log: https://ci.spdk.io/public_build/autotest-per-patch_56647.html

**Comment by spdkci** [comment] 2021-08-24 02:12
Another instance of this failure. Reported by @richael02. log: https://ci.spdk.io/public_build/autotest-per-patch_56648.html

**Comment by ksztyber** [comment] 2021-08-24 07:06
Hi @richael02, these two failures aren't related to this issue. I think they're caused by the recent markdownlint changes and should disappear if you rebase your patches on top of current master branch.

**Comment by tomzawadzki** [comment] 2021-08-24 15:08
[Bug scrub] The fix has been merged and no failure should occur after rebases. Let's wait couple days and close the issue if that's the case.

**Comment by spdkci** [comment] 2021-08-31 08:46
Another instance of this failure. Reported by @matthewburbridge. log: https://ci.spdk.io/public_build/autotest-per-patch_57196.html

**Comment by spdkci** [comment] 2021-09-07 06:19
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_57692.html

**Comment by tomzawadzki** [comment] 2021-09-07 15:40
[Bug scrub] Log from @matthewburbridge looks similar, but occurred in different test than the original one. Let's close this one, and if the other one is need a new issue should be opened.

**Closed by tomzawadzki** 2021-09-07 15:40 UTC
Labels: Waiting on Submitter, Intermittent Failure
