### ISSUE TITLE
[iscsi-vg-autotest] Cluster with name=0x88a570 is still used and we cannot delete it

### ISSUE THREAD

**Issue by wawryk** [spdk/spdk#2069] opened 2021-08-05 05:19 UTC
## Link to the failed CI build
https://ci.spdk.io/public_build/autotest-per-patch_55196.html

## Execution failed at

```
00:08:45.027  Cleaning up iSCSI connection
00:08:45.027   22:20:27	-- common/autotest_common.sh@842 -- # iscsiadm -m node --logout
00:08:45.070  Logging out of session [sid: 30, target: iqn.2016-06.io.spdk:Target3, portal: 10.0.0.1,3260]
00:08:45.070  Logout of [sid: 30, target: iqn.2016-06.io.spdk:Target3, portal: 10.0.0.1,3260] successful.
00:08:45.071   22:20:27	-- common/autotest_common.sh@843 -- # iscsiadm -m node -o delete
00:08:45.078   22:20:27	-- common/autotest_common.sh@844 -- # rm -rf '/var/lib/iscsi/nodes/*'
00:08:45.080   22:20:27	-- iscsi_tgt/rbd/rbd.sh@68 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py bdev_rbd_delete Ceph0
00:08:45.214  [2021-08-04 22:20:27.666356] lun.c: 403:bdev_event_cb: *NOTICE*: bdev name (Ceph0) received event(SPDK_BDEV_EVENT_REMOVE)
00:08:45.231   22:20:27	-- iscsi_tgt/rbd/rbd.sh@69 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py bdev_rbd_unregister_cluster iscsi_rbd_cluster
00:08:45.374  [2021-08-04 22:20:27.826330] bdev_rbd.c:1116:bdev_rbd_unregister_cluster: *ERROR*: Cluster with name=0x88a570 is still used and we cannot delete it
00:08:45.379  request:
00:08:45.379  {
00:08:45.379    "name": "iscsi_rbd_cluster",
00:08:45.379    "method": "bdev_rbd_unregister_cluster",
00:08:45.379    "req_id": 1
00:08:45.379  }
00:08:45.379  Got JSON-RPC error response
00:08:45.379  response:
00:08:45.379  {
00:08:45.379    "code": -1,
00:08:45.379    "message": "Operation not permitted"
00:08:45.379  }
00:08:45.388    22:20:27	-- iscsi_tgt/rbd/rbd.sh@69 -- # trap - ERR
00:08:45.388    22:20:27	-- iscsi_tgt/rbd/rbd.sh@69 -- # print_backtrace
00:08:45.389    22:20:27	-- common/autotest_common.sh@985 -- # [[ ehxBET =~ e ]]
00:08:45.389    22:20:27	-- common/autotest_common.sh@987 -- # args=("${BASH_ARGV[@]}")
00:08:45.389    22:20:27	-- common/autotest_common.sh@987 -- # local args
00:08:45.389    22:20:27	-- common/autotest_common.sh@989 -- # xtrace_disable
00:08:45.389    22:20:27	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:08:45.389    22:20:27	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:08:45.389    22:20:27	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:08:45.389    22:20:27	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:08:45.389    22:20:27	-- common/autotest_common.sh@19 -- # set +x
00:08:45.390  ========== Backtrace start: ==========
00:08:45.390  
00:08:45.403  in ./test/iscsi_tgt/rbd/rbd.sh:69 -> main([])
00:08:45.403       ...
00:08:45.404     64  	
00:08:45.404     65  	trap - SIGINT SIGTERM EXIT
00:08:45.404     66  	
00:08:45.404     67  	iscsicleanup
00:08:45.404     68  	$rpc_py bdev_rbd_delete $rbd_bdev
00:08:45.404  => 69  	$rpc_py bdev_rbd_unregister_cluster $rbd_cluster_name
00:08:45.404     70  	killprocess $pid
00:08:45.404     71  	rbd_cleanup
00:08:45.404     72  	
00:08:45.404     73  	iscsitestfini
00:08:45.404       ...
```

**Comment by spdkci** [comment] 2021-08-05 05:20
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_55196.html

**Comment by optimistyzy** [comment] 2021-08-05 06:33
I think that this issue is caused by line 68. If we could use rpc_bdev_get_bdevs to check between line 68 and 69. Then this issue should be solved. Not sure whether there are some already provided shell script function to do this.

**Comment by jimharris** [comment] 2021-08-05 16:50
@optimistyzy - could you dig into this further?  Assigning to you for now.

**Comment by optimistyzy** [comment] 2021-08-06 04:38
> I think that this issue is caused by line 68. If we could use rpc_bdev_get_bdevs to check between line 68 and 69. Then this issue should be solved. Not sure whether there are some already provided shell script function to do this.

Hi 

> @optimistyzy - could you dig into this further? Assigning to you for now.

Hi Jim,

bdev_rbd_delete is async, So if we call line 69, there could be cases that the rbd is not finishing the delete operation.  So I suggest whether we will have functions to check whether an rbd device is exist. Then we can call bdev_rbd_unregister_cluster.

**Comment by jimharris** [comment] 2021-08-06 14:29
Hi Ziye,

I think it would be better to defer completion of the RPC until the delete operation is fully complete.  I don't think polling on the bdev like in patch 9105 will fix the problem.  I've added comments to the patch to explain why.

Thanks,

Jim

**Comment by jimharris** [comment] 2021-08-06 21:36
This patch should ensure we don't complete the bdev_rpc_delete RPC until after all of the asynchronous delete operations are completed:

https://review.spdk.io/gerrit/c/spdk/spdk/+/9115

**Comment by optimistyzy** [comment] 2021-08-09 04:25
> This patch should ensure we don't complete the bdev_rpc_delete RPC until after all of the asynchronous delete operations are completed:
> 
> https://review.spdk.io/gerrit/c/spdk/spdk/+/9115

Hi Jim,

I think that there is sync related issue on your patch. Could you review my comments?  Thanks.

**Comment by tomzawadzki** [comment] 2021-09-07 14:49
Patch fixing this issue has been merged https://review.spdk.io/gerrit/c/spdk/spdk/+/9115.

**Closed by tomzawadzki** 2021-09-07 14:49 UTC
Labels: Intermittent Failure
