### ISSUE TITLE
I can use nvme-cli to find the nvme subsystem,but can not use nvme-cli tool to connect it

### ISSUE THREAD

**Issue by chwlouluo** [spdk/spdk#608] opened 2019-01-24 02:45 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

use nvme-cli to connect the nvme subsystem at initiator

When I use nvme-cli to connect the nvme subsystem at spdk tafget ,I should finally find the nvme ssd devices at initiator
## Current Behavior

When I use nvme-cli to connect the nvme subsystem at initiator,it doesn't work and cause the initiator OS dead
## Possible Solution

I don't know what cause the problem,because I used the tcp transport to test my spdk environment
## Steps to Reproduce

1.use /app/nvmf_tgt/nvmf_tgt to start spdk nvmf_tgt
2.use /scripts/rpc.py to configure a tcp transport nvme subsystem ...
3.at the initiator use nvme-cli-1.7 version to discover the nvme subsystem
4.at the initiator use nvme-cli-1.7 version to dconnect the nvme subsystem

## Context (Environment including OS version, SPDK version, etc.)

OS version is redhat7.4 with 5.0.0-rc2(suport kernel nvme-tcp)
SPDK version is v19.01-pre
DPDK version is 18.08.0

**Comment by darsto** [comment] 2019-01-29 15:56
Bug scrub: This seems to be a duplicate of #576. "nvme discover shows all target subsystems, even those that are not accessible by the host". @ShaharSalzman-K is already working on the fix.

I'm closing this issue. If this is an unrelated bug, please give me a note and I'll reopen.

**Closed by darsto** 2019-01-29 15:56 UTC
