### ISSUE TITLE
[ubuntu16-vg-autotest] no build log 

### ISSUE THREAD

**Issue by jiaqizho** [spdk/spdk#1649] opened 2020-10-26 01:52 UTC
## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_29435.html
https://ci.spdk.io/results/autotest-per-patch/builds/29435/archive/ubuntu16-vg-autotest/index.html
## Execution failed at

no build output ...

**Comment by karlatec** [comment] 2020-10-26 15:48
Duplicate of #1495, closing

**Closed by karlatec** 2020-10-26 15:48 UTC
Labels: Intermittent Failure
