### ISSUE TITLE
Fix of blob overlapping open case failed

### ISSUE THREAD

**Issue by zRegle** [spdk/spdk#1937] opened 2021-05-11 11:30 UTC
## Expected Behavior

If a blob is opened, then before the previous open operation has completed, a new open operation occurs, we should just increase the ref_count of the blob in the latter operation.

## Current Behavior

If lvols(including clones and snapshots) are recovered by `vbdev_lvs_examine`, some duplicated blobs may be created.

## Possible Solution

After I carefully check the code, in `blob_lookup`, if the bit of `blob->open_blobids` is clear, it will return `NULL`. 

However, in `bs_open_blob_cpl`, `blob->open_blobids` is set after checking duplicated blobs. 

Therefore, everytime we execute `blob_lookup`, the return value of `existing` is always `NULL`

A simple solution is that we don't check `blob->open_blobids` in `blob_lookup`, just iterate through the `bs->blobs` list.

## Steps to Reproduce

1.create an aio bdev,  `bdev_aio_create /dev/sdk aio0`

2.create an lvs based on the aio bdev `bdev_lvol_create_lvstore aio0 lvs0`

3.create a lvol A, a snapshot of lvol A, and clone of lvol A 
`bdev_lvol_create -l lvs0 l0 16`
`bdev_lvol_snapshot lvs0/l0 sp_l0`
`bdev_lvol_clone lvs0/sp_l0 l1`

4.delete aio bdev `bdev_aio_delete aio0`

5.recover the aio bdev `bdev_aio_create /dev/sdk aio0`

## Context (Environment including OS version, SPDK version, etc.)

I'm using the SPDK v21.04

**Comment by changpe1** [comment] 2021-05-12 06:55
@tomzawadzki could you take a look? thanks.

**Comment by tomzawadzki** [comment] 2021-05-21 11:36
@zRegle Thank you for such an in-depth analysis ! This was very helpful.

The suggested approach would work, but the reason for introducing the open_blobids was to speed up the lookup. See 30ee8137cf808454af7ad2dd273106aa4033aaa6.

I believe that the superfluous blob pointers is resolved with this patch https://review.spdk.io/gerrit/c/spdk/spdk/+/7998.

I'm just curious about the reproduction steps. From my testing there was nothing incorrect in regards to what's available via RPC, ex the number of lvols was correct. Only adding more logging around blobid's and blob pointers I was able to observe that we had too many.
Have I missed some outward facing issue here, or you've observed it while debugging as well ?

**Closed** 2021-05-25 07:18 UTC
Labels: Medium, Patches out for review, bug
