### ISSUE TITLE
[ vfio-user-phy-autotest] Cannot create lock on device

### ISSUE THREAD

**Issue by ehaligow** [spdk/spdk#3127] opened 2023-09-12 07:46 UTC
# CI Intermittent Failure

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/109372/archive/vfio-user-phy-autotest_4993/build.log

**Comment by mikeBashStuff** [comment] 2023-09-12 07:54
This is a duplicate of #3067.

**Closed by mikeBashStuff** 2023-09-12 07:54 UTC
Labels: Intermittent Failure
