### ISSUE TITLE
SPDK test apps (identify / perf / fio) not freeing hugepages when exiting

### ISSUE THREAD

**Issue by anji1921389** [spdk/spdk#2267] opened 2021-12-03 09:46 UTC
# Bug report

On an ARM board with cross compiled SPDK, identify / perf / fio apps are not releasing the hugepages

## Expected Behavior

When the test app exits, it should release the hugepages back and the free hugepage count should match with the free hugepage count before running the app

## Current Behavior

The free hugepage count captured after running the test apps was less than the free hugepages count before running the app. There were few observations,
- Observed 2 hugepage files in hugetlbfs, removing them manually, incremented free hugepage count by 1 and not all hugepages were released. So, ddded --huge-unlink dpdk eal parameters, to check if that helps, the issue wasn't resolved

- To rule out DPDK, Tested DPDK hugepages handling with a test app which just allocs & frees hugepages memory, all the hugepages were released successfully 
- Tetsted spdk_zmalloc / spdk_free with a simple test app that again allocs / frees hugepage memory (without touching any spdk core), all the hugepages were released

- Running identify test app, reduced the free hugepage count by 1
- The un-freed hugepage count differs for fio test cases, with change in the number of target namespaces (nvmf test case)

## Steps to Reproduce

1. Cross compile SPDK for ARM board -- The custom embedded board i've allowed me to configure only 200 - 2MB hugepages
2. Check free hugepage count, run identify app and check the free page count after test

## Context (Environment including OS version, SPDK version, etc.)
- SPDK Version : v21.10 release tag
- Linux kernel v5.10
- Embedded ARM based board with 4-ARM Cortex A53 cores running at 1.5GHz
- SPDK, DPDK, fio are cross compiled

**Comment by peluse** [comment] 2021-12-03 15:19
@anji1921389 do you know if this only happens with Arm (did you/can you test your steps on IA?)

**Comment by anji1921389** [comment] 2021-12-04 05:09
@peluse Did you mean x86 by IA? If yes, it works fine.

**Comment by AlekseyMarchuk** [comment] 2021-12-04 13:15
@anji1921389 Have you tried to cross compile SPDK using spdk/scripts/arm_cross_compile.sh?
I tested this script but didn't pay attention if huge pages were released or not.

**Comment by peluse** [comment] 2021-12-04 19:12
Yes, sorry IA = Intel Architecture.  @AlekseyMarchuk do you by any chance have any ideas on this what appears to be an Arm specific mem leak of some kind?

**Comment by anji1921389** [comment] 2021-12-06 05:49
@AlekseyMarchuk, my ARM board doesn't have enough memory to build ARM natively, as it requires a lot of tool support.
So far, i've not used the script that you've pointed out, i kind of have my own script similar to scripts/arm_cross_compile.sh to build the SPDK and DPDK.

PS: I cross compile libnuma, fio, DPDK, SPDK using the rootfs generated by yocto build system for ARM

**Comment by changpe1** [comment] 2021-12-29 04:20
My identify binary shows that there is one hugepage file left when exiting the application, if you are talking about this, here is the fix patch, because SPDK doesn't call `rte_eal_cleanup` when exiting.

https://review.spdk.io/gerrit/c/spdk/spdk/+/10904

**Comment by changpe1** [comment] 2022-01-04 02:53
For dynamic memory model(default mode), SPDK applications will leave one hugepage file after exiting the processes, for static memory model(-m 1024), SPDK applications will leave all the hugepage files when exiting, my above patch serial can fix this issue.

**Comment by jimharris** [comment] 2022-01-06 16:02
This phenomena is not specific to ARM, it reproduces on x86 platforms as well.  Calling rte_eal_cleanup() does not actually fix the problem, since there is a small memzone allocated by the SPDK nvme driver that doesn't get freed before exiting the application.  rte_eal_cleanup() will only release hugepages that have no outstanding allocations.  (Note: it might be nice at some point to figure out a way to release this memzone, but it's not trivial.)

This is relatively harmless though, because DPDK will clean up these unused Hugepages next time it runs. So you don't end up leaking a huge page each time a process runs.

SPDK applications like nvmf_tgt take an -R/--huge-unlink option which tells DPDK to automatically unlink the Hugepages files once created.  This is not enabled by default since it breaks multi-process.  But the env_dpdk layer knows if the user wants to use multi-process by looking at the opts->shm_id.

So https://review.spdk.io/gerrit/c/spdk/spdk/+/10991 should fix this issue for the default cases where these applications are not using multi-process.  The env_dpdk library will see during spdk_env_init() that the application is not requesting multi-process initialization, and will tell DPDK to unlink the hugepages after mmapping them.  Then when the process exits, the hugepages automatically get released.

**Comment by anji1921389** [comment] 2022-01-06 16:53
@jimharris I already tried passing huge-unlink option to the eal (I made changes to the code such that the flag gets passed), that didn’t solve my issue. 
Also, with each test run the number of huge pages count went down, so for some reason the dpdk couldn’t free them up on my ARM board.

**Comment by jimharris** [comment] 2022-01-06 16:58
> @jimharris I already tried passing huge-unlink option to the eal (I made changes to the code such that the flag gets passed), that didn’t solve my issue.
> Also, with each test run the number of huge pages count went down, so for some reason the dpdk couldn’t free them up on my ARM board.

Sorry @anji1921389, I missed that in your original description.

When you use the huge-unlink option, do you still see hugepage file entries in your hugepage mount directory?

**Comment by anji1921389** [comment] 2022-01-06 17:09
> 

Yes @jimharris.
I ran fio initiator on board & my observation (when huge-unlink option not used) was the number of huge pages left un-freed were somehow related to the number of target namespaces. When I tried with 1 namespace, there were 2 - 2MB huge page files in hugetlbfs and removing them only freed 1 hugepage. Also when I ran the test targeting 8 namespaces there were many huge page file seen, removing them didn’t release all the hugepages. After which I tried with huge-unlink option & didn’t see any huge page files in hugetlbfs but the free hugepage count kept going down.

**Comment by anji1921389** [comment] 2022-01-06 17:18
@jimharris Though I didn’t modify any dpdk core that would have these kind of effects, am I the only one seeing these issues? 

Since my RNIC requires non-cacheable memory (hugepage memory writes were cached) I had to register few IO memory regions as external memory and used them where I needed (I’m pretty sure these didn’t cause the issue, because I also tried a different approach to get the required non-cacheable IO memory without using external memory registrations) and faced the same issue

**Comment by jimharris** [comment] 2022-01-06 18:00
> @jimharris Though I didn’t modify any dpdk core that would have these kind of effects, am I the only one seeing these issues?

I haven't seen or heard of anyone else reporting these kinds of issues.  I'm not sure how many people are trying this on ARM though.

If you use this "different approach to get the required non-cacheable IO memory", with current master + the 10991 patch above, do you still see the problem?  If not, then it could be something related to your extra IO memory regions that you've allocated.

> 
> Since my RNIC requires non-cacheable memory (hugepage memory writes were cached) I had to register few IO memory regions as external memory and used them where I needed (I’m pretty sure these didn’t cause the issue, because I also tried a different approach to get the required non-cacheable IO memory without using external memory registrations) and faced the same issue

**Comment by anji1921389** [comment] 2022-01-07 04:35
@jimharris, I observed the same issue even with huge-unlink eal flag when external memory regions were not registered

**Comment by AlekseyMarchuk** [comment] 2022-01-13 11:31
@jimharris I noticed that commit 8b81801e2dc0bfc00a4d3de0ef52c3d600523d1c leads to core dump when fio with bdev plugin finishes. It is easy to reproduce, I used 1 core and bdev_nvme with RDMA transport. The callstack is following:
```
#0  0x00007fbb35a5ded7 in rte_ring_dequeue_burst_elem (available=0x0, n=8, esize=8, obj_table=0x7fbb15608220, r=0x20000cc80840) at /alexeymar/repo/spdk/dpdk/build/include/rte_ring_elem.h:684
#1  rte_ring_dequeue_burst (available=0x0, n=8, obj_table=0x7fbb15608220, r=0x20000cc80840) at /alexeymar/repo/spdk/dpdk/build/include/rte_ring.h:801
#2  spdk_ring_dequeue (ring=0x20000cc80840, objs=0x7fbb15608220, count=8) at env.c:442
#3  0x00007fbb35b2fab9 in msg_queue_run_batch (thread=0x7fbb1c000bb0, max_msgs=8) at thread.c:694
#4  0x00007fbb35b3242a in thread_poll (thread=0x7fbb1c000bb0, max_msgs=0, now=701588330654036) at thread.c:926
#5  0x00007fbb35b328cd in spdk_thread_poll (thread=0x7fbb1c000bb0, max_msgs=0, now=701588330654036) at thread.c:986
#6  0x00007fbb357fdd83 in spdk_fio_poll_thread (fio_thread=0x7fbb1c000b60) at fio_plugin.c:831
#7  0x00007fbb357fa18a in spdk_init_thread_poll (arg=0x55cba02846a0) at fio_plugin.c:342
#8  0x00007fbb3efb0609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007fbb3eca2293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

It looks like rte_eal_cleanup is called too early while fio continues to poll spdk threads in frame `7`.
I added a print to dpdk_cleanup() and the output is following:
```

filename0: (groupid=0, jobs=1): err= 0: pid=875603: Thu Jan 13 13:30:02 2022
  write: IOPS=251k, BW=982MiB/s (1030MB/s)(9821MiB/10001msec); 0 zone resets
    slat (nsec): min=1723, max=217968, avg=1794.82, stdev=233.05
    clat (usec): min=15, max=570, avg=53.22, stdev=12.54
     lat (usec): min=17, max=571, avg=55.01, stdev=12.53
    clat percentiles (usec):
     |  1.00th=[   30],  5.00th=[   36], 10.00th=[   41], 20.00th=[   44],
     | 30.00th=[   47], 40.00th=[   49], 50.00th=[   53], 60.00th=[   57],
     | 70.00th=[   60], 80.00th=[   64], 90.00th=[   69], 95.00th=[   71],
     | 99.00th=[   76], 99.50th=[   77], 99.90th=[  223], 99.95th=[  239],
     | 99.99th=[  253]
   bw (  KiB/s): min=1000272, max=1009888, per=100.00%, avg=1005762.15, stdev=2176.05, samples=20
   iops        : min=250068, max=252472, avg=251440.50, stdev=543.98, samples=20
  lat (usec)   : 20=0.15%, 50=43.81%, 100=55.93%, 250=0.11%, 500=0.01%
  lat (usec)   : 750=0.01%
  cpu          : usr=99.99%, sys=0.00%, ctx=11, majf=0, minf=423
  IO depths    : 1=0.1%, 2=0.3%, 4=13.2%, 8=67.3%, 16=19.1%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=93.7%, 8=2.4%, 16=3.9%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,2514103,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
  WRITE: bw=982MiB/s (1030MB/s), 982MiB/s-982MiB/s (1030MB/s-1030MB/s), io=9821MiB (10.3GB), run=10001-10001msec
[2022-01-13 13:30:02.152010] init.c: 628:dpdk_cleanup: *NOTICE*: calling rte_eal_cleanup

Segmentation fault
```

**Comment by jimharris** [comment] 2022-01-13 12:57
Thanks for the report @AlekseyMarchuk, I’ll take a look.

**Comment by jimharris** [comment] 2022-01-13 21:02
> @jimharris I noticed that commit [8b81801](https://github.com/spdk/spdk/commit/8b81801e2dc0bfc00a4d3de0ef52c3d600523d1c) leads to core dump when fio with bdev plugin finishes. It is easy to reproduce, I used 1 core and bdev_nvme with RDMA transport. The callstack is following:

Can you try https://review.spdk.io/gerrit/c/spdk/spdk/+/11085?

**Comment by AlekseyMarchuk** [comment] 2022-01-14 06:47
Thanks @jimharris this patch fixes this problem

**Comment by changpe1** [comment] 2022-01-20 02:56
The issues observed from our side have been fixed, closing it for now.

**Closed by changpe1** 2022-01-20 02:56 UTC
Labels: bug, Medium, Patches out for review
