### ISSUE TITLE
Linux kernel >= 4.18.0-rc5 - fail to bind NVMe device to UIO module

### ISSUE THREAD

**Issue by pawelwod** [spdk/spdk#399] opened 2018-08-10 12:56 UTC
Trying to NVMe device to UIO module fail on kernel >= 4.18.0-rc5. This is not SPDK issue but lets have it here just to track it.

## Expected Behavior
It must be able to bind NVMe device to UIO module.

## Current Behavior
Fail with dmesg:

```
[  336.221585] genirq: Threaded irq requested with handler=NULL and !ONESHOT for irq 33
[  336.221681] uio_pci_generic: probe of 0000:04:00.0 failed with error -22
[  336.221866] genirq: Threaded irq requested with handler=NULL and !ONESHOT for irq 33
[  336.221950] uio_pci_generic: probe of 0000:04:00.0 failed with error -22
[  338.814508] genirq: Threaded irq requested with handler=NULL and !ONESHOT for irq 33
[  338.814597] uio_pci_generic: probe of 0000:04:00.0 failed with error -22
[  338.814699] genirq: Threaded irq requested with handler=NULL and !ONESHOT for irq 34
[  338.814781] uio_pci_generic: probe of 0000:05:00.0 failed with error -22
[  338.814956] genirq: Threaded irq requested with handler=NULL and !ONESHOT for irq 34
[  338.815039] uio_pci_generic: probe of 0000:05:00.0 failed with error -22
```

```
# /root/spdk/scripts/setup.sh status
Hugepages
node     hugesize     free /  total
node0   1048576kB        0 /      0
node0      2048kB      512 /    512
node1   1048576kB        0 /      0
node1      2048kB      512 /    512
NVMe devices
BDF             Numa Node       Driver name             Device name
0000:04:00.0    0                               -
0000:05:00.0    0                               -
I/OAT DMA
BDF             Numa Node       Driver Name
virtio
BDF             Numa Node       Driver Name             Device Name

```

## Possible Solution
Use kernel < 4.18.0-rc5

## Steps to Reproduce
1. Build & boot into mainline kernel >= 4.18.0-rc5
2. Invoke `spdk/scripts/setup.sh`

## Context (Environment including OS version, SPDK version, etc.)
Kernel >= 4.18.0-rc5
SPDK master.

**Comment by jimharris** [comment] 2018-08-10 16:07
Hi @pawelwod,

Do you have the test system that reproduces this error?  I know another team at Intel report this and just wanted to make sure it's not system-specific.

Can we have someone try to bisect between 4.18.0-rc4 and -rc5 to narrow this down to a specific commit?

-Jim

**Comment by jimharris** [comment] 2018-08-10 16:09
This is almost certainly the cause of the failures:

https://github.com/torvalds/linux/commit/9421e45f5ff3d558cf8b75a8cc0824530caf3453#diff-f8c4bf947cbbef4f6cc9d168af57c347

**Comment by jimharris** [comment] 2018-08-10 17:01
I think it's possible this bug has been fixed:

https://github.com/torvalds/linux/commit/d1f0301b3333eef5efbfa1fe0f0edbea01863d5d

**Comment by pawelwod** [comment] 2018-08-13 07:33
LKML thread
https://lkml.org/lkml/2018/8/10/624

Waiting for fix to be merged into mainline.

**Comment by liang2yan** [comment] 2018-08-28 05:49
@pawelwod @jimharris , was the kernel patch merged? Then we can close this issue.

**Comment by pawelwod** [comment] 2018-08-28 10:15
yes, patch merged.

**Comment by liang2yan** [comment] 2018-08-29 05:28
Close this issue since patch merged.

**Closed by liang2yan** 2018-08-29 05:28 UTC
