### ISSUE TITLE
bdev_malloc_unmap fill also MD with zeroes

### ISSUE THREAD

**Issue by moshe-shahar** [spdk/spdk#3156] opened 2023-10-19 07:36 UTC
https://github.com/spdk/spdk/blob/631e75fc03a79bb5fe45a53d293e30bfabd947d8/module/bdev/malloc/bdev_malloc.c#L350

From spec:
> The values read from a deallocated or unwritten logical block’s protection information field shall:
> • have each byte in the Guard field value set to FFh or set to the CRC for the value read from the deallocated logical block and its metadata (excluding protection information) (e.g., cleared to 0h if the value read is all bytes cleared to 0h); and
> • have each byte in the Application Tag field, Storage Tag field, if defined, and the Logical Block Reference Tag value set to FFh (indicating the protection information shall not be checked).

When dif_type != SPDK_DIF_DISABLE, on an unmapped block, the ref tag should be 0xFFFFFFFF to pass `malloc_verify_pi`.

**Comment by changpe1** [comment] 2023-10-31 07:49
@moshe-shahar You are right, SPDK doesn't process this case for UNMAP, same for WRITE ZEROES. let me add it.

**Comment by changpe1** [comment] 2023-11-09 06:09
Patches https://review.spdk.io/gerrit/c/spdk/spdk/+/20492 and https://review.spdk.io/gerrit/c/spdk/spdk/+/20493 can fix this issue, malloc is not the only module that has this issue, bdev_nvme also doesn't respect WRITE ZEROES and UNMAP.

**Comment by moshe-shahar** [comment] 2023-11-09 09:09
@changpe1,
Thank you!

**Comment by jimharris** [comment] 2023-12-19 15:21
Patches were merged.

**Closed by jimharris** 2023-12-19 15:21 UTC
Labels: Patches out for review

**Comment by winglq** [comment] 2024-04-11 08:09
After this change a read request from zeroed range will get the following error messages if type 1 is used:
```
dif.c: 815:_dif_verify: *ERROR*: Failed to compare Ref Tag: LBA=0, Expected=0, Actual=ffffffff
bdev_malloc.c:  97:malloc_verify_pi: *ERROR*: DIF/DIX verify failed: lba 0, num_blocks 1, err_type 1, expected 0, actual 4294967295, err_offset 0
```
I think this is due to bdev_malloc does not known wether the reading area is deallocated or not.

**Comment by winglq** [comment] 2024-04-11 08:14
should I open a new issue to track this?

**Comment by changpe1** [comment] 2024-04-11 08:16
> should I open a new issue to track this?

I think the behavior is expected, it's the caller's responsibility to know this information.

**Comment by winglq** [comment] 2024-04-11 08:55
> > should I open a new issue to track this?
> 
> I think the behavior is expected, it's the caller's responsibility to know this information.

It's hard to the caller figure out whether a failure (success == false) is caused by deallocated, what if an error is caused by hardware with its APP/REFTAG filled with FFFF...

According to spec
```
Using the Error Recovery feature (refer to section 5.21.1.5), host software may enable an error to be
returned if a deallocated or unwritten logical block is read. If this error is supported for the namespace and
enabled, then a Read, Verify, or Compare command that includes a deallocated or unwritten logical block
shall fail with the Unwritten or Deallocated Logical Block status code. Note: Legacy software may not handle
an error for this case.
```
If Error Recovery feature is enabled, caller can determine whether a failure is caused by Unwritten or Deallocated by status code. But bdev_malloc doesn't have a clear code to distinguish the error type.
If Error Recovery feature is not enabled, I think success should be true.
How is bdev_malloc been designed, with or without Error Recovery enabled?

**Comment by changpe1** [comment] 2024-04-12 01:33
> > > should I open a new issue to track this?
> > 
> > 
> > I think the behavior is expected, it's the caller's responsibility to know this information.
> 
> It's hard to the caller figure out whether a failure (success == false) is caused by deallocated, what if an error is caused by hardware with its APP/REFTAG filled with FFFF...
> 
> According to spec
> 
> ```
> Using the Error Recovery feature (refer to section 5.21.1.5), host software may enable an error to be
> returned if a deallocated or unwritten logical block is read. If this error is supported for the namespace and
> enabled, then a Read, Verify, or Compare command that includes a deallocated or unwritten logical block
> shall fail with the Unwritten or Deallocated Logical Block status code. Note: Legacy software may not handle
> an error for this case.
> ```
> 
> If Error Recovery feature is enabled, caller can determine whether a failure is caused by Unwritten or Deallocated by status code. But bdev_malloc doesn't have a clear code to distinguish the error type. If Error Recovery feature is not enabled, I think success should be true. How is bdev_malloc been designed, with or without Error Recovery enabled?

I see what's your question. SPDK nvmf library doesn't support Error Recovery feature.

**Comment by shuhei-matsumoto** [comment] 2024-10-24 03:36
@winglq 

> After this change a read request from zeroed range will get the following error messages if type 1 is used:
> 
> ```
> dif.c: 815:_dif_verify: *ERROR*: Failed to compare Ref Tag: LBA=0, Expected=0, Actual=ffffffff
> bdev_malloc.c:  97:malloc_verify_pi: *ERROR*: DIF/DIX verify failed: lba 0, num_blocks 1, err_type 1, expected 0, actual 4294967295, err_offset 0
> ```
> 
> I think this is due to bdev_malloc does not known wether the reading area is deallocated or not.

You may already fixed by yourself but I fixed this problem.
https://review.spdk.io/gerrit/c/spdk/spdk/+/25323
https://review.spdk.io/gerrit/c/spdk/spdk/+/25324/2
If not yet and you still have problem, will you check?

**Comment by winglq** [comment] 2025-01-03 05:42
Sorry for the late reply. Currently I don't have an environtment for the verification due to my work area change.
