### ISSUE TITLE
[default_setup] assert on expected num of huge pages

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2613] opened 2022-07-28 23:39 UTC
0:01:19.219   00:02:54	-- setup/hugepages.sh@91 -- # echo nr_hugepages=1024
00:01:19.219  nr_hugepages=1024
00:01:19.219   00:02:54	-- setup/hugepages.sh@92 -- # (( 1704 == nr_hugepages ))
00:01:19.219    00:02:54	-- setup/hugepages.sh@92 -- # trap - ERR
00:01:19.219    00:02:54	-- setup/hugepages.sh@92 -- # print_backtrace
00:01:19.219    00:02:54	-- common/autotest_common.sh@998 -- # [[ ehxBET =~ e ]]
00:01:19.219    00:02:54	-- common/autotest_common.sh@1000 -- # args=('default_setup' 'default_setup')
00:01:19.219    00:02:54	-- common/autotest_common.sh@1000 -- # local args
00:01:19.219    00:02:54	-- common/autotest_common.sh@1002 -- # xtrace_disable
00:01:19.219    00:02:54	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:01:19.219    00:02:54	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:01:19.219    00:02:54	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:01:19.219    00:02:54	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:01:19.219    00:02:54	-- common/autotest_common.sh@19 -- # set +x
00:01:19.219  ========== Backtrace start: ==========

**Comment by spdkci** [comment] 2022-07-28 23:40
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_81516.html

**Comment by spdkci** [comment] 2022-07-28 23:43
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_81513.html

**Comment by spdkci** [comment] 2022-08-01 07:24
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_81525.html

**Comment by spdkci** [comment] 2022-08-01 07:24
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_81524.html

**Comment by jimharris** [comment] 2022-08-01 22:03
This looks CI related, but can't be sure.  3 of the failures were on WFP9 running Fedora 35, the other was on GFP1 running Fedora 34.

Assigning to @mikeBashStuff for initial triage.

**Comment by mikeBashStuff** [comment] 2022-08-02 11:10
@jimharris Here's an attempt to mitigate this issue: https://review.spdk.io/gerrit/c/spdk/spdk/+/13826. I can't really pinpoint what exactly is causing this overcommit (the surplus or transparent hugepages) as unfortunately the affected nodes are always rebooted in case any of the jobs fails. I am trying here to accommodate for all, though I recall from the past that the extra number of hugepages was actually coming from the transparent ones (not 100% sure though) - we could try to disable them but I am not sure how it could affect the overall performance. This patch also adds some debug so in case the test fails again we should have some clearer picture as to what happened - and if it does, I can remove the affected node for testing to see if disabling transparent hugepages has any major impact on the system.

**Comment by mikeBashStuff** [comment] 2022-08-02 11:52
Hmm, it seems that what I wrote about transparent hugepages is not correct considering how my patch had failed here: https://ci.spdk.io/public_build/autotest-per-patch_81675.html

**Comment by jimharris** [comment] 2022-08-02 14:37
@mikeBashStuff - maybe we should just relax the comparison to make sure that enough huge pages were reserved, instead of exactly 1024?

**Comment by mikeBashStuff** [comment] 2022-08-02 14:56
@jimharris I updated a patch a bit to exclude the anon hugepages from the calculation (this was a bug on its own as meminfo doesn't show the number of those but rather their total size) so now it should be ok. 

As to relaxing the condition - I guess we could do that. The only problem I have with this is that under "clean" conditions (i.e. idle system, no processes requesting hugepages, etc.) running `setup.sh` should guarantee that user gets the exact amount of hugepages and any other scenario should be considered as faulty (this is what these tests are aiming for) - this becomes especially relevant in context of `CLEAR_HUGE` option when it's really peculiar to get more hugepages than requested (that said,  this particular assumption could've been wrong all along due to the surplus|reserved hugepages the above patch is now trying to take into the account).

**Comment by spdkci** [comment] 2022-08-09 14:00
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_82214.html

**Comment by mikeBashStuff** [comment] 2022-08-16 14:00
Hopefully this should be gone after recent changes in the test suite.

**Comment by jimharris** [comment] 2022-08-16 14:13
Thanks @mikeBashStuff.  It doesn't look like we've seen this again after the patch was merged, so I'm going to close it.

**Comment by spdkci** [comment] 2022-08-30 09:24
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_84065.html

**Comment by spdkci** [comment] 2022-08-30 09:48
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_84063.html

**Comment by mikeBashStuff** [comment] 2022-08-30 09:58
This started happening on systems which were not properly rebooted upon job failure (we are having an ongoing issue with power switches in the lab) - the extra number of hugepages comes from processes which still have some allocated, probably SPDK processes that are not properly killed when failure occurs. I am preparing patch which will dump some extra processes-related info when the autotest suite fails: https://review.spdk.io/gerrit/c/spdk/spdk/+/14261 to narrow it down a bit.

**Comment by spdkci** [comment] 2022-08-30 10:19
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_84070.html

**Comment by mikeBashStuff** [comment] 2022-08-30 10:23
Confirmed that for WFP16 this was a lingering vhost and qemu processes (both using hugepages).

**Comment by spdkci** [comment] 2022-08-30 10:58
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_84075.html

**Comment by spdkci** [comment] 2022-08-30 11:00
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_84076.html

**Comment by spdkci** [comment] 2022-08-30 11:02
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_84074.html

**Comment by spdkci** [comment] 2022-09-01 21:40
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_84421.html

**Comment by spdkci** [comment] 2022-09-01 21:41
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_84417.html

**Comment by spdkci** [comment] 2022-09-01 21:41
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_84418.html

**Comment by spdkci** [comment] 2022-09-01 21:42
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_84413.html

**Comment by spdkci** [comment] 2022-09-01 21:43
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_84414.html

**Comment by spdkci** [comment] 2022-09-01 21:43
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_84410.html

**Comment by jimharris** [comment] 2022-09-01 21:56
This recent deluge of false positives were all on WFP12.

**Comment by spdkci** [comment] 2022-09-02 02:53
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_84429.html

**Comment by spdkci** [comment] 2022-09-02 03:20
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_84431.html

**Comment by spdkci** [comment] 2022-09-02 04:29
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_84435.html

**Comment by karlatec** [comment] 2022-10-03 11:28
This issue was (most probably) caused by WFP12 test system not rebooting properly after a failed build due to power switch issue in our lab. We've added additional routines to our CI scripts to ensure that the system is rebooted properly.

This has not been reported for a month now, so I suggest closing it.

**Comment by mikeBashStuff** [comment] 2022-10-03 11:33
This can be closed - issue with rebooting the nodes was indeed the culprit here.

**Closed by mikeBashStuff** 2022-10-03 11:33 UTC
Labels: Infrastructure, Intermittent Failure, Patches out for review

**Comment by spdkci** [comment] 2022-10-26 11:20
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_88321.html
