### ISSUE TITLE
[nvmf-tcp-phy-autotest] Build failed

### ISSUE THREAD

**Issue by sun-mingbao** [spdk/spdk#1879] opened 2021-04-07 07:51 UTC
https://ci.spdk.io/public_build/autotest-per-patch_41082.html

The above web page has failures of:

- nvmf-tcp-phy-autotest 
- vhost-autotest

However, I could not see any relationship between my push review and the failures.

**Comment by spdkci** [comment] 2021-04-07 07:56
Another instance of this failure. Reported by @sun-mingbao. log: https://ci.spdk.io/public_build/autotest-per-patch_41082.html

**Comment by mikeBashStuff** [comment] 2021-04-07 08:06
Duplicate of #1870

**Closed by mikeBashStuff** 2021-04-07 08:06 UTC
Labels: Intermittent Failure
