### ISSUE TITLE
nvmf/rdma: Errors are logged when perf is aborted during run with ctrlr-c

### ISSUE THREAD

**Issue by mhae** [spdk/spdk#1549] opened 2020-08-13 13:55 UTC
I'm running perf aganist a number of subsystems. Each subsystem contains one NVMe drive and perf connects to all of the subsystem. When I hit ctrlr-c during the perf run, the target sometimes logs these errors:
```
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
0000001f 00000000 00000000 00000000
00000000 00008813 08028f15 25322bd3
[2020-08-11 06:53:47.169719] rdma.c:3858:nvmf_rdma_log_wc_status: *ERROR*: Error on CQ 0x1fec4e0, (qp state 3 ibv_state 6) request 0x139641767983056, type DATA, status: (10): remote access error
```

If they are harmless, we could make them INFO, or WARN. Or turn them into something more useful, indicating that the initiator went away. I don't think we should just suppress them since they can help in production debugging.
Further, are these errors handled correctly? I'm worried about potential leaks/corruptions in this error path.

## Context (Environment including OS version, SPDK version, etc.)
20.07, CentOS8

**Comment by yidong0635** [comment] 2020-09-24 02:53
@AlekseyMarchuk  Are you still checking this issue, maybe there're leaks/corruptions, I had ever checked the multi-machine testing 
of a big file, I got the results, but I didn't check the data.  There're  error reports there, but it doesn't prevent testing finished.

**Comment by AlekseyMarchuk** [comment] 2020-09-24 06:49
@yidong0635 Sorry, didn't have time to check this issue. Plan to do it next week. I appreciate if your share more info on your environment and steps to reproduce since I never met such errors

**Comment by jimharris** [comment] 2020-11-02 18:34
@mhae - could you provide some more info on your environment and reproduction steps for @AlekseyMarchuk?

Thanks,

Jim

**Comment by mhae** [comment] 2020-11-02 21:13
@jimharris , I'll try with the latest bits when I have a breather. The scenario was fairly simple. Nvmf_tgt with at least 20 subsystems with bdev_nvme and a remote setup with CX5. Run perf and then hit ctrlr-c after a while.

**Comment by jimharris** [comment] 2020-11-02 21:15
Thanks @mhae.  No rush on this.  Just wanted to check in since it had been open for a while.

**Comment by mhae** [comment] 2020-11-03 17:40
@jimharris @AlekseyMarchuk , I just reproduce it while testing Ben's fixes. This is main with Ben's subsystem changes.
I was running perf to all subsystems (24), then I pressed ctrlr-C to stop perf and got these reported by the target:
```
mlx5: localhost.localdomain: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000022 00000000 00000000 00000000
00000000 00008813 08000a9b 25f668d2
[2020-11-03 09:31:34.905174] rdma.c:3857:nvmf_rdma_log_wc_status: *ERROR*: Error on CQ 0x6160002d9980, (qp state 3 ibv_state 6) request 0x140253263333632, type DATA, status: (10): remote access error
mlx5: localhost.localdomain: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
0000001b 00000000 00000000 00000000
00000000 00008813 08000a8d 2604b4d2
[2020-11-03 09:31:34.905513] rdma.c:3857:nvmf_rdma_log_wc_status: *ERROR*: Error on CQ 0x6160002d9980, (qp state 3 ibv_state 6) request 0x140253263504544, type DATA, status: (10): remote access error
```

**Comment by AlekseyMarchuk** [comment] 2021-01-11 16:16
Hi @mhae 

I apologize for so long delay. I checked this problem, it happens due to perf tool doesn't have signal handlers so when you kill it with ctlr-c, all resources are destroyed ungracefully. For RDMA that means that all resources (memory regions, protection domains and qpairs) are cleaned by the kernel. RDMA CM notifies target that the qpair is being destroyed but we may have some IO requests in flight and the following may occur:
1. Target starts RDMA operation
2. perf tool is killed, kernel destroys resources
3. Local driver receives RDMA request but the corresponding Memory Region is destroyed by the kernel
4. Driver sends completion with error to requester (SPDK target)
5. Driver on requester side dumps error completion
6. SPDK target receives completion with error and also prints error log

Such errors are not harmful but we can't remove them since we can differentiate such "false positive" errors and real errors.
I prepared a patch https://review.spdk.io/gerrit/c/spdk/spdk/+/5869 that adds handlers for SIGINT and SIGTERM signals to perf tool. With this patch perf will shutdown gracefully when you kill it with ctrl-c and no errors will be generated. 
Will you have a chance to test this patch?

**Comment by mhae** [comment] 2021-01-11 17:04
Hi Aleksey, I'll give it a try asap.

**Comment by mhae** [comment] 2021-01-11 22:54
@AlekseyMarchuk , I can't repro this anymore with the fix.

**Comment by AlekseyMarchuk** [comment] 2021-01-20 12:00
Patch is merged, closing this issue

**Closed by AlekseyMarchuk** 2021-01-20 12:00 UTC
Labels: Low, bug
