### ISSUE TITLE
bdev_nvme: Hot remove causes core dump in debug mode

### ISSUE THREAD

**Issue by mhae** [spdk/spdk#2632] opened 2022-08-05 17:35 UTC
# Bug report

Doing a hot remove of a bdev_nvme NVMe device hits this assertion point:
`nvmf_tgt_22_01: bdev_nvme.c:1584: bdev_nvme_reset_ctrlr: Assertion 'rc == 0' failed.`

## Expected Behavior

No core dump.

## Current Behavior

Here's the full log when I do a hot remove in SPDK 22.01:
```
[2022-08-05 11:23:18.557902] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2022-08-05 11:23:18.557902] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2022-08-05 11:23:18.557902] bdev_nvme.c:1101:bdev_nvme_disconnected_qpair_cb: *NOTICE*: qpair 0x200014cefc60 is disconnected, free the qpair and reset controller.
[2022-08-05 11:23:18.557903] bdev_nvme.c:1101:bdev_nvme_disconnected_qpair_cb: *NOTICE*: qpair 0x200014e00ca0 is disconnected, free the qpair and reset controller.
[2022-08-05 11:23:18.558012] nvme_qpair.c: 274:nvme_io_qpair_print_command: *NOTICE*: READ sqid:2 cid:191 nsid:1 lba:94868809 len:1 SGL DATA BLOCK ADDRESS 0x773e2e000 len:0x208 key:0x0
[2022-08-05 11:23:18.558022] bdev_nvme.c:1617:bdev_nvme_reset: *NOTICE*: Unable to perform reset, already in progress.
[2022-08-05 11:23:18.558048] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:2 cid:191 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
[2022-08-05 11:23:18.558087] bdev_nvme.c:1101:bdev_nvme_disconnected_qpair_cb: *NOTICE*: qpair 0x2000156dfe60 is disconnected, free the qpair and reset controller.
[2022-08-05 11:23:18.558110] bdev_nvme.c:1617:bdev_nvme_reset: *NOTICE*: Unable to perform reset, already in progress.
[2022-08-05 11:23:18.559973] nvme_qpair.c: 252:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) qid:0 cid:22 nsid:0 cdw10:00000000 cdw11:00000000
[2022-08-05 11:23:18.559991] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:22 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
[2022-08-05 11:23:18.560027] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2022-08-05 11:23:18.560042] nvme_qpair.c: 252:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) qid:0 cid:21 nsid:0 cdw10:00000000 cdw11:00000000
[2022-08-05 11:23:18.560059] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:21 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
[2022-08-05 11:23:18.560074] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2022-08-05 11:23:18.560092] nvme_qpair.c: 252:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) qid:0 cid:20 nsid:0 cdw10:00000000 cdw11:00000000
[2022-08-05 11:23:18.560118] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:20 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
[2022-08-05 11:23:18.560150] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2022-08-05 11:23:18.560165] nvme_qpair.c: 252:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) qid:0 cid:19 nsid:0 cdw10:00000000 cdw11:00000000
[2022-08-05 11:23:18.560180] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:19 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
[2022-08-05 11:23:18.560195] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2022-08-05 11:23:18.560209] nvme_qpair.c: 252:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) qid:0 cid:18 nsid:0 cdw10:00000000 cdw11:00000000
[2022-08-05 11:23:18.560223] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:18 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
[2022-08-05 11:23:18.560239] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2022-08-05 11:23:18.560255] nvme_qpair.c: 252:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) qid:0 cid:17 nsid:0 cdw10:00000000 cdw11:00000000
[2022-08-05 11:23:18.560269] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:17 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
[2022-08-05 11:23:18.560283] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2022-08-05 11:23:18.560298] nvme_qpair.c: 252:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) qid:0 cid:16 nsid:0 cdw10:00000000 cdw11:00000000
[2022-08-05 11:23:18.560313] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:16 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
[2022-08-05 11:23:18.560328] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2022-08-05 11:23:18.560343] nvme_qpair.c: 252:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) qid:0 cid:15 nsid:0 cdw10:00000000 cdw11:00000000
[2022-08-05 11:23:18.560357] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:15 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
[2022-08-05 11:23:18.560371] nvme_ctrlr.c:1052:nvme_ctrlr_fail: *ERROR*: [0000:b5:00.0] in failed state.
[2022-08-05 11:23:18.631648] bdev_nvme.c:1101:bdev_nvme_disconnected_qpair_cb: *NOTICE*: qpair 0x200006effc20 is disconnected, free the qpair and reset controller.
[2022-08-05 11:23:18.631785] bdev_nvme.c:3176:aer_cb: *WARNING*: AER request execute failed[2022-08-05 11:23:18.631807] bdev_nvme.c:3176:aer_cb: *WARNING*: AER request execute failed[2022-08-05 11:23:18.631822] bdev_nvme.c:3176:aer_cb: *WARNING*: AER request execute failed[2022-08-05 11:23:18.631838] bdev_nvme.c:3176:aer_cb: *WARNING*: AER request execute failed[2022-08-05 11:23:18.631851] bdev_nvme.c:3176:aer_cb: *WARNING*: AER request execute failed[2022-08-05 11:23:18.631866] bdev_nvme.c:3176:aer_cb: *WARNING*: AER request execute failed[2022-08-05 11:23:18.631881] bdev_nvme.c:3176:aer_cb: *WARNING*: AER request execute failed[2022-08-05 11:23:18.631894] bdev_nvme.c:3176:aer_cb: *WARNING*: AER request execute failednvmf_tgt_22_01: bdev_nvme.c:1584: bdev_nvme_reset_ctrlr: Assertion `rc == 0' failed.
Aborted (core dumped)
```

Here's the 22.01 code for reference: https://github.com/spdk/spdk/blob/47737f16b47522cbc41b5106c69598cd7ff1a76a/module/bdev/nvme/bdev_nvme.c#L1584

## Possible Solution

It's unclear if this assert can be removed.

## Steps to Reproduce

- Compile 22.01 target
- Have NVMe devices on system
- nvmf_tgt -m 0xf
- Config:
```
scripts/rpc.py bdev_nvme_set_hotplug -e
sleep 2
# scripts/rpc.py nvmf_create_transport -t RDMA -u 8192 -p 4 -c 0
scripts/rpc.py nvmf_create_transport -t RDMA -u 8192 -c 0
scripts/rpc.py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -m 1
scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.1.2 -s 4420
scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 HotInNvme0n1
```

- Hot remove the device corresponding do HotInNvme0n1

## Context (Environment including OS version, SPDK version, etc.)

SPDK 22.01, Debian

Note, I can't switch to a later version. I'd like to stay on the LTS.

**Comment by jimharris** [comment] 2022-08-05 18:21
HI @mhae,

I'll take an initial look at this code path.  In the meantime I have a few questions:

* Can I assume that the device being hot removed doesn't have to be one that was hot inserted?
* Does this require a certain number of cores on the target?  If you can reproduce this w/ just one core on the target that would be a great simplification
* How frequently do you see this failure when running the steps you've listed?

-Jim

**Comment by mhae** [comment] 2022-08-05 19:12
Hey @jimharris,
-  I always let bdev_nvme hot insert. I don't explicitly add a device via RPC. In my test, I just start the app and then call the bdev_nvme_set_hotplug -e. This will discover and add all VFIO devices
- Yes! I just noticed that the # of cores needs to be > 1.
- Every time. With or without IO.

**Comment by jimharris** [comment] 2022-08-05 20:13
> * Every time. With or without IO.

So it doesn't need to be under load?

**Comment by mhae** [comment] 2022-08-05 20:27
@jimharris , correct. No load is needed. Just more than 1 core.

**Comment by jimharris** [comment] 2022-08-05 20:31
> @jimharris , correct. No load is needed. Just more than 1 core.

Thanks @mhae - this is a great simplification.  I updated the issue title and removed the perf step from the reproduction steps.

**Comment by jimharris** [comment] 2022-08-05 20:46
Added https://review.spdk.io/gerrit/c/spdk/spdk/+/13888 to add the newline in the aer_cb (see last line in @mhae's log).

Tagging @shuhei-matsumoto to get his input here...

So this assert doesn't exist on latest master.  Shuhei's done some work in the rest area since the 22.01 release, see commits aca0d56, fe9a8fab, fcf52fb.

The 22.01 code has a comment right before the assert saying:

1583         /* Disconnect fails if ctrlr is already resetting or removed. Both cases are
1584          * not possible. Reset is controlled and the callback to hot remove is called
1585          * when ctrlr is hot removed.
1586          */

But @mhae if you run in release mode, you see no ill effects?  I am wondering if this assert should just be removed on the 22.01 branch, along with an adjustment to that comment.

**Comment by mhae** [comment] 2022-08-05 21:37
I haven't tried release mode... I'm too chicken to remove an assert (-;

**Comment by shuhei-matsumoto** [comment] 2022-08-08 07:04
Hi @mhae 

Thanks for finding the way to hit this assert. I could not handle this assert because I could not hit this assert. Please take a look at the patch https://review.spdk.io/gerrit/c/spdk/spdk/+/13892

**Comment by mhae** [comment] 2022-08-08 13:22
Hey @shuhei-matsumoto, thanks for the quick fix. I think I need it for 22.01 since this is the LTS that we're currently using. 
Would we just make a similar check in bdev_nvme_reset_ctrlr like you did in 13892?

**Comment by shuhei-matsumoto** [comment] 2022-08-08 20:42
Hi @mhae OK. Sounds very reasonable. I will write a patch for 22.01 too.

**Comment by shuhei-matsumoto** [comment] 2022-08-08 20:51
Hi @mhae 

The patch for 22.01 is out for review too.
https://review.spdk.io/gerrit/c/spdk/spdk/+/13907
Please review and have a try to check if your issue is fixed.

**Comment by mhae** [comment] 2022-08-08 21:49
I tested https://review.spdk.io/gerrit/c/spdk/spdk/+/13907 (22.01) and it looks good.

```
 root@localhost:~# /tmp/nvmf_tgt_22_01 -m0xf
[2022-08-08 15:41:04.229126] Starting SPDK v22.01 git sha1 47737f16b / DPDK 21.11.0 initialization...
[2022-08-08 15:41:04.229229] [ DPDK EAL parameters: [2022-08-08 15:41:04.229244] nvmf [2022-08-08 15:41:04.229255] --no-shconf [2022-08-08 15:41:04.229267] -c 0xf [2022-08-08 15:41:04.229286] --log-level=lib.eal:6 [2022-08-08 15:41:04.229299] --log-level=lib.cryptodev:5 [2022-08-08 15:41:04.229314] --log-level=user1:6 [2022-08-08 15:41:04.229330] --iova-mode=pa [2022-08-08 15:41:04.229345] --iova-mode=pa [2022-08-08 15:41:04.229356] --base-virtaddr=0x200000000000 [2022-08-08 15:41:04.229370] --match-allocations [2022-08-08 15:41:04.229386] --file-prefix=spdk_pid11707 [2022-08-08 15:41:04.229404] ]
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-08-08 15:41:04.324395] app.c: 601:spdk_app_start: *NOTICE*: Total cores available: 4
[2022-08-08 15:41:04.435010] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 1
[2022-08-08 15:41:04.435077] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 2
[2022-08-08 15:41:04.435152] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 3
[2022-08-08 15:41:04.435154] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 0
[2022-08-08 15:41:04.435375] accel_engine.c: 510:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2022-08-08 15:42:01.651604] rdma.c:2318:nvmf_rdma_create: *WARNING*: In capsule data size is set to 256, this is minimum size required to support msdbd=16
[2022-08-08 15:42:01.907698] rdma.c:2668:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 192.168.1.2 port 4420 ***
[2022-08-08 15:42:06.061896] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2022-08-08 15:42:06.061897] bdev_nvme.c:1101:bdev_nvme_disconnected_qpair_cb: *NOTICE*: qpair 0x200014cefc60 is disconnected, free the qpair and reset controller.
[2022-08-08 15:42:06.061897] bdev_nvme.c:1101:bdev_nvme_disconnected_qpair_cb: *NOTICE*: qpair 0x2000156dfe60 is disconnected, free the qpair and reset controller.
[2022-08-08 15:42:06.061897] bdev_nvme.c:1101:bdev_nvme_disconnected_qpair_cb: *NOTICE*: qpair 0x200014e00ca0 is disconnected, free the qpair and reset controller.
[2022-08-08 15:42:06.061992] bdev_nvme.c:1621:bdev_nvme_reset: *NOTICE*: Unable to perform reset, already in progress.
[2022-08-08 15:42:06.062006] bdev_nvme.c:1621:bdev_nvme_reset: *NOTICE*: Unable to perform reset, already in progress.
[2022-08-08 15:42:06.062035] nvme_qpair.c: 252:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) qid:0 cid:22 nsid:0 cdw10:00000000 cdw11:00000000
[2022-08-08 15:42:06.062086] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:22 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
[2022-08-08 15:42:06.062115] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2022-08-08 15:42:06.062139] nvme_qpair.c: 252:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) qid:0 cid:21 nsid:0 cdw10:00000000 cdw11:00000000
[2022-08-08 15:42:06.062162] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:21 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
[2022-08-08 15:42:06.062186] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2022-08-08 15:42:06.062209] nvme_qpair.c: 252:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) qid:0 cid:20 nsid:0 cdw10:00000000 cdw11:00000000
[2022-08-08 15:42:06.062229] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:20 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
[2022-08-08 15:42:06.062250] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2022-08-08 15:42:06.062273] nvme_qpair.c: 252:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) qid:0 cid:19 nsid:0 cdw10:00000000 cdw11:00000000
[2022-08-08 15:42:06.062296] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:19 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
[2022-08-08 15:42:06.062316] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2022-08-08 15:42:06.062337] nvme_qpair.c: 252:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) qid:0 cid:18 nsid:0 cdw10:00000000 cdw11:00000000
[2022-08-08 15:42:06.062360] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:18 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
[2022-08-08 15:42:06.062381] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2022-08-08 15:42:06.062400] nvme_qpair.c: 252:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) qid:0 cid:17 nsid:0 cdw10:00000000 cdw11:00000000
[2022-08-08 15:42:06.062425] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:17 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
[2022-08-08 15:42:06.062447] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2022-08-08 15:42:06.062470] nvme_qpair.c: 252:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) qid:0 cid:16 nsid:0 cdw10:00000000 cdw11:00000000
[2022-08-08 15:42:06.062493] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:16 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
[2022-08-08 15:42:06.062515] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2022-08-08 15:42:06.062538] nvme_qpair.c: 252:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) qid:0 cid:15 nsid:0 cdw10:00000000 cdw11:00000000
[2022-08-08 15:42:06.062562] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:15 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
[2022-08-08 15:42:06.062587] nvme_ctrlr.c:1052:nvme_ctrlr_fail: *ERROR*: [0000:b5:00.0] in failed state.
[2022-08-08 15:42:06.098875] bdev_nvme.c:1101:bdev_nvme_disconnected_qpair_cb: *NOTICE*: qpair 0x200006effc20 is disconnected, free the qpair and reset controller.
[2022-08-08 15:42:06.099039] bdev_nvme.c:3180:aer_cb: *WARNING*: AER request execute failed[2022-08-08 15:42:06.099065] bdev_nvme.c:3180:aer_cb: *WARNING*: AER request execute failed[2022-08-08 15:42:06.099089] bdev_nvme.c:3180:aer_cb: *WARNING*: AER request execute failed[2022-08-08 15:42:06.099111] bdev_nvme.c:3180:aer_cb: *WARNING*: AER request execute failed[2022-08-08 15:42:06.099132] bdev_nvme.c:3180:aer_cb: *WARNING*: AER request execute failed[2022-08-08 15:42:06.099155] bdev_nvme.c:3180:aer_cb: *WARNING*: AER request execute failed[2022-08-08 15:42:06.099176] bdev_nvme.c:3180:aer_cb: *WARNING*: AER request execute failed[2022-08-08 15:42:06.099199] bdev_nvme.c:3180:aer_cb: *WARNING*: AER request execute failed[2022-08-08 15:42:06.099268] bdev_nvme.c:1440:_bdev_nvme_reset_complete: *ERROR*: Resetting controller failed.
```

**Comment by shuhei-matsumoto** [comment] 2022-08-09 00:53
Thank you @mhae !

**Comment by changpe1** [comment] 2022-09-01 03:23
Patches for master and 22.01 are merged, closing this issue.

**Closed by changpe1** 2022-09-01 03:23 UTC
Labels: bug, Medium, Patches out for review
