### ISSUE TITLE
Race condition in bdev_nvme triggers assertion

### ISSUE THREAD

**Issue by gnif** [spdk/spdk#979] opened 2019-10-07 21:13 UTC
When using the raid0 bdev with two nvme bdevs a race condition exists. Under certain
circumstances the `bio->iovpos` assertion in `bdev_nvme_queued_next_sge` triggers due
to multiple threads updating this value, in all instances leaving the value == to
`bio->iovcont`. As I am new to this codebase I am not sure of the appropriate method to
correct this. Running the vhost application with a single core corrects this issue. The
following configuration seems to trigger this crash about 80% of the time during a Windows
10 installation at the partitioning phase:

```
vhost -m 0x3 -S /var/tmp --huge-dir /mnt/hugepages1G -R -L bdev_raid -L vhost_blk &
vhost_pid=$!
sleep 1

rpc.py bdev_raid_create -n WinRaid0 -z 512 -r 0 -b "NVMe1n1 NVMe2n1"
rpc.py bdev_nvme_attach_controller -b NVMe1 -t PCIe -a ${DEVLIST[0]}
rpc.py bdev_nvme_attach_controller -b NVMe2 -t PCIe -a ${DEVLIST[1]}
rpc.py construct_vhost_blk_controller vhost.0 WinRaid0
```

Qemu configured with:

```
-chardev socket,id=char0,path=/var/tmp/vhost.0
-device vhost-user-blk-pci,id=blk0,chardev=char0
```

Running 7ed0ec6832d9a5cf49bdc35f8e9c00fa80a5f67b on Debian 10 x64.

**Comment by optimistyzy** [comment] 2019-10-07 21:32
Just guess from the experience: when the bdev IO is splitted into two, and when the child I/O completed, it should send an asynchronous event, and let the parent thread to update it. If it is updated by the child thread by itself. I would see similar issues in vbdev_compress.c. Currently, it let the original thread to complete this.

**Comment by peluse** [comment] 2019-10-07 21:40
@ZiyeYang I'm not sure I understand your comment so I'm guessing @gnif doesn't either.  In your first comment are you talking about a potential issue in the bdev IO splitting code? An what does your second comment wrt compress mean? Does it mean that you'd expect to see issues there? It doesn't split IOs either but does funnel all IO's to one channel so the completion routines send async messages to what we call the reduce. Were you trying to explain that this is the right way to handle such completions or trying to imply that there is an issue there?

**Comment by optimistyzy** [comment] 2019-10-07 21:44
@peluse  I mean the possible solution should refer the code in vbdev compress, we solved this issue in vbdev. If my guess is right, we should use the way. I did not mean there is any issue  in vbdev_compress.

**Comment by peluse** [comment] 2019-10-07 21:46
@ZiyeYang OK thanks.  The purpose for what compress was doing was different but yes I see what you are saying wrt the potential problem.
@gnif I'll take a look and see if I can repro on my dev system but will try multi-thread fio or something first so I don't have to install Windows, even on a VM :)

**Comment by jimharris** [comment] 2019-10-07 21:50
The submitter's configuration is using NVMe only.  The bdev nvme driver doesn't do any kind of message passing between cores when doing I/O.  So I'm struggling to draw a correlation between this issue and the kind of message passing we do in the compress bdev module.

**Comment by optimistyzy** [comment] 2019-10-07 22:03
@jimharris It is easy to detect. And the thread check to check whether the child I/O's I/O thread is equal to original bdev I/O's thread. From this issue if caused by multiple thread, it should be different.

**Comment by peluse** [comment] 2019-10-08 01:12
@ZiyeYang cool.  @gnif i can't even try to repro until tomorrow (missing equipment) so let me know if you get a chance to test with Ziye's test code.

**Comment by gnif** [comment] 2019-10-08 04:17
I have reproduced it with @ZiyeYang's patch but the assertion never triggers, here is the debug output.

```
vhost_scsi.c: 736:process_requestq: *DEBUG*: ====== Starting processing request idx 1======
bdev_raid.c: 787:_raid_bdev_submit_null_payload_request: *DEBUG*: raid_bdev: type 3, range (0x109000, 0x32000)
bdev_raid.c: 685:_raid0_split_io_range: *DEBUG*: raid_bdev (strip_size 0x80) splits IO to base_bdev (0) at (0x84800, 0x19000).
bdev_raid.c: 685:_raid0_split_io_range: *DEBUG*: raid_bdev (strip_size 0x80) splits IO to base_bdev (1) at (0x84800, 0x19000).
vhost_scsi.c: 762:process_requestq: *DEBUG*: ====== Task 0x20216b479e30 req_idx 1 submitted ======
vhost_scsi.c: 331:submit_completion: *DEBUG*: Finished task (0x20216b479e30) req_idx=1
vhost_scsi.c: 736:process_requestq: *DEBUG*: ====== Starting processing request idx 1======
vhost_scsi.c: 762:process_requestq: *DEBUG*: ====== Task 0x20216b479e30 req_idx 1 submitted ======
vhost_scsi.c: 331:submit_completion: *DEBUG*: Finished task (0x20216b479e30) req_idx=1
vhost_scsi.c: 736:process_requestq: *DEBUG*: ====== Starting processing request idx 1======
vhost_scsi.c: 762:process_requestq: *DEBUG*: ====== Task 0x20216b479e30 req_idx 1 submitted ======
vhost_scsi.c: 331:submit_completion: *DEBUG*: Finished task (0x20216b479e30) req_idx=1
vhost_scsi.c: 736:process_requestq: *DEBUG*: ====== Starting processing request idx 1======
vhost_scsi.c: 762:process_requestq: *DEBUG*: ====== Task 0x20216b479e30 req_idx 1 submitted ======
vhost_scsi.c: 331:submit_completion: *DEBUG*: Finished task (0x20216b479e30) req_idx=1
vhost_scsi.c: 736:process_requestq: *DEBUG*: ====== Starting processing request idx 1======
vhost_scsi.c: 762:process_requestq: *DEBUG*: ====== Task 0x20216b479e30 req_idx 1 submitted ======
vhost_scsi.c: 331:submit_completion: *DEBUG*: Finished task (0x20216b479e30) req_idx=1
vhost_scsi.c: 736:process_requestq: *DEBUG*: ====== Starting processing request idx 1======
vhost_scsi.c: 762:process_requestq: *DEBUG*: ====== Task 0x20216b479e30 req_idx 1 submitted ======
vhost_scsi.c: 736:process_requestq: *DEBUG*: ====== Starting processing request idx 0======
vhost_scsi.c: 762:process_requestq: *DEBUG*: ====== Task 0x20216b479500 req_idx 0 submitted ======
vhost_scsi.c: 331:submit_completion: *DEBUG*: Finished task (0x20216b479500) req_idx=0
vhost_scsi.c: 331:submit_completion: *DEBUG*: Finished task (0x20216b479e30) req_idx=1
vhost_scsi.c: 736:process_requestq: *DEBUG*: ====== Starting processing request idx 1======
vhost: bdev_nvme.c:1810: bdev_nvme_queued_next_sge: Assertion `bio->iovpos < bio->iovcnt' failed.
```

You can clearly see that two tasks are finishing at the same time across the two separate threads.

**Comment by gnif** [comment] 2019-10-08 05:11
Adding a bit more logging and digging a bit deeper I don't think this is a race condition anymore, it is however random as to when it occurs which is a bit strange.

```
bdev_nvme_queued_reset_sgl thread:0x5633445d3f50, bio:0x202174bf65c8
bdev_nvme_queued_next_sge thread:0x5633445d3f50, bio:0x202174bf65c8
bdev_nvme_queued_next_sge thread:0x5633445d3f50, bio:0x202174bf65c8
bdev_nvme_queued_next_sge thread:0x5633445d3f50, bio:0x202174bf65c8
vhost: bdev_nvme.c:1813: bdev_nvme_queued_next_sge: Assertion `bio->iovpos < bio->iovcnt' failed.
```

```
spdk_bdev_writev_blocks (desc=0x5633449d46f0, ch=0x5633449c2990, iov=0x202174bf5fc0, iovcnt=2, offset_blocks=546176, num_blocks=54, cb=0x5633425a40f1 <raid_bdev_io_completion>, cb_arg=0x202174bf9b80) at bdev.c:3072
```

So `iovcnt == 2` yet the callback was called three times.

**Comment by gnif** [comment] 2019-10-08 13:26
Further tracing has shown that this occurs when `_spdk_bdev_io_split` runs out of `child_iov` space.

**Comment by peluse** [comment] 2019-10-08 13:55
@gnif great update, thanks.  So did you hit this assert in bdev.c then? assert(child_iovcnt == BDEV_IO_NUM_CHILD_IOV);

**Comment by gnif** [comment] 2019-10-08 14:07
no, `child_iovcnt` is correct at 32 when it reaches this point. I might be a little premature on the conclusion, staring at code for long periods like this can get mind boggling

**Comment by gnif** [comment] 2019-10-08 14:22
I am fairly certain the error is here:

https://github.com/spdk/spdk/blob/b422cee886c17a38222a020256bc2477796e7102/lib/bdev/bdev.c#L1701-L1703

I am not quite sure though on how to correct this. When I total up the iov lengths the total is not a multiple of the block size (512), for example:

```
payload_size: 43520
pos: 9
iov 0: 0x7fff1cd57510 2800
iov 1: 0x7fff18d58000 4096
iov 2: 0x7fff1cf59000 4096
iov 3: 0x7fff1415a000 4096
iov 4: 0x7fff1455b000 4096
iov 5: 0x7fff1cd5c000 8192
iov 6: 0x7fff1cf5e000 8192
iov 7: 0x7fff1a160000 4096
iov 8: 0x7fff16961000 3824
tot: 43488
```
43488 / 512 = 84.9375

**Comment by peluse** [comment] 2019-10-08 14:38
... with the goal, of course, to update/add a test to hit this condition then fix :)

**Comment by jimharris** [comment] 2019-10-08 14:46
Hi @gnif - could you print out the full iov array before you get into the while loop containing this code?  I suspect that the code just before this snippet you reference has the problem - if we run out of iov space, we can't end on an iov that leaves us with a non-512 byte multiple total.

**Comment by gnif** [comment] 2019-10-08 15:04
As requested here is the entire child_iov array just before the loop.

```
0: 0x7fff11f43f60 160
1: 0x7fff14944000 864
2: 0x7fff14944360 3232
3: 0x7fff12c91000 4096
4: 0x7fff10292000 4096
5: 0x7fff19e41000 4096
6: 0x7fff19842000 4096
7: 0x7fff1a343000 4096
8: 0x7fff1a444000 4096
9: 0x7fff1a545000 4096
10: 0x7fff19f46000 4096
11: 0x7fff19d47000 4096
12: 0x7fff1a548000 12288
13: 0x7fff1a24b000 8192
14: 0x7fff1a54d000 4096
15: 0x7fff1a24e000 864
16: 0x7fff1a24e360 3232
17: 0x7fff19e4f000 4096
18: 0x7fff1a350000 24576
19: 0x7fff19856000 16384
20: 0x7fff0365a000 12288
21: 0x7fff1a35d000 4096
22: 0x7fff09e5e000 864
23: 0x7fff09e5e360 3232
24: 0x7fff1a35f000 4096
25: 0x7fff19d60000 28672
26: 0x7fff1a367000 20480
27: 0x7fff19d6c000 4096
28: 0x7fff1a36d000 4960
29: 0x7fff1a36e360 7328
30: 0x7fff1a570000 4096
31: 0x7fff07b71000 4096
bdev_io->child_iov[child_iovpos].iov_len = 4096 - 352
to_next_boundary_bytes: 49152
payload_size: 15360
pos: 3
iov 0: 0x7fff1a36e360 7328
iov 1: 0x7fff1a570000 4096
iov 2: 0x7fff07b71000 3744
tot: 15168
```

**Comment by shuhei-matsumoto** [comment] 2019-10-08 23:43
Hi @gnif, @Donaim  and All,

I think how to rewind might be wrong. Of course I might be wrong though :-)
My today started earlier than Vitally and so I'm trying to create the UT code first too.

If the strategy
```
/* We had to stop this child I/O early because we ran out of
 * child_iov space.  Ensure the iovs to be aligned with block
 * size and then adjust to_next_boundary before starting the
 * child I/O.
 */

```
is correct, the amount of rewind should be the following?
```
to_last_block_bytes = to_next_boundary_bytes % blocklen;
if (to_last_block_bytes != 0) {
	to_last_block_bytes = blocklen - to_last_block_bytes;
	to_next_boundary_bytes += to_last_block_bytes;
}

```

Then the code should be the following?

```
	to_last_block_bytes = to_next_boundary_bytes % blocklen;
	if (to_last_block_bytes != 0) {
		uint32_t child_iovpos = child_iovcnt - 1;

		to_last_block_bytes = blocklen - to_last_block_bytes;
		to_next_boundary_bytes += to_last_block_bytes;
		while (to_last_block_bytes > 0 && iovcnt > 0) {
			iov_len = spdk_min(to_last_block_bytes,
					   bdev_io->child_iov[child_iovpos].iov_len);
			bdev_io->child_iov[child_iovpos].iov_len -= iov_len;
			if (bdev_io->child_iov[child_iovpos].iov_len == 0) {
				child_iovpos--;
				iovcnt--;
			}
			to_last_block_bytes -= iov_len;
		}

		assert(to_last_block_bytes == 0);
	}
	to_next_boundary -= to_next_boundary_bytes / blocklen;
```

**Comment by shuhei-matsumoto** [comment] 2019-10-08 23:48
@gnif The issue is not fixed yet but thank you so much for your great effort and insight.

**Comment by shuhei-matsumoto** [comment] 2019-10-09 03:15
@Donaim 
I'm working on UT too but please continue your work regardless of mine because I'm still debugging and working on the same goal is good for this case :-)

**Comment by shuhei-matsumoto** [comment] 2019-10-09 07:14
Hi @gnif @Donaim and All,

I posted a patch https://review.gerrithub.io/c/spdk/spdk/+/470806 .
The patch includes UT code too.
Will you test if the patch works to the issue you have observed, and review the patch?

Thanks,
Shuhei

**Comment by gnif** [comment] 2019-10-09 09:16
Patch looks good to me and I can no longer replicate the fault! Well done @shuhei-matsumoto and thanks!

**Comment by shuhei-matsumoto** [comment] 2019-10-09 09:58
Thank you again @gnif You brought us to the fix :)

**Comment by changpe1** [comment] 2019-10-11 00:13
Patch has been merged, thanks for @gnif and @shuhei-matsumoto 's great work. I'm going to close this issue for now.

**Closed by changpe1** 2019-10-11 00:13 UTC
Labels: bug

**Comment by shuhei-matsumoto** [comment] 2019-10-11 00:34
@changpe1 the patch is not merged yet? https://review.gerrithub.io/c/spdk/spdk/+/470806

**Comment by changpe1** [comment] 2019-10-11 00:36
> @changpe1 the patch is not merged yet? https://review.gerrithub.io/c/spdk/spdk/+/470806

I just merged, :).

**Comment by shuhei-matsumoto** [comment] 2019-10-11 00:45
Thank you @changpe1 !

**Comment by spdkci** [comment] 2020-02-24 08:12
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_4518.html
