### ISSUE TITLE
fio_plugin with prchk=GUARD is not performant

### ISSUE THREAD

**Issue by peterjweir** [spdk/spdk#473] opened 2018-10-23 16:48 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

When using fio plugin with 520-dif format, the crc16 being used to calculate the guard check is a major bottleneck to software performance

## Expected Behavior

Ideally, spdk would be able to perform the crc check fast enough to expose an nvme drives performance and not bottleneck it.

## Current Behavior

With the code that is in place, 520 dif format will cause an nvme drive to run at a few MB per second instead of the typical GB per second range. commenting out just the crc code allows performance to increase back to normal line speed.

## Possible Solution

I implemented a table driven crc in the code, and this did improve performance, but not enough, it is still a bottleneck, not sure if I'm making an invalid assumption, seems that crc16 should be faster than it is.

## Steps to Reproduce

1. Format an nvme drive that supports nvme format 512+8, extended lba, metadata at end. 
2. Run fio with spdk fio_plugin write only, any compatible block size, (I used 66560), PRACT=0, PRCHK=APP|GUARD|REF
3. (If this doesn't run, there is another bug, where the lba size is not recalculated when md functionality is enabled. this bug can be fixed by inserting the following
		block_size = spdk_nvme_ns_get_extended_sector_size(ns);
		lba = io_u->offset / block_size;
		lba_count = io_u->xfer_buflen / block_size;
inside of the fio_qpair->do_nvme_pi if statement found on approximately line 852 in fio_plugin.c
4. Observe performance with and without PRCHK=GUARD

## Context (Environment including OS version, SPDK version, etc.)

Running on Centos7 on E5-2687W v4 with 32gb of ram. SPDK is pulled from master branch. as of last week.

**Comment by shuhei-matsumoto** [comment] 2018-10-25 05:39
And I think the current implementation of PI on top of the SPDK NVMe driver is very preliminary and the performance may be lower even if this fix works.

**Comment by peterjweir** [comment] 2018-10-25 19:50
I will try that commit as well, where I am at today it is all technically working, just very slowly. I have done two things to try to figure this out, I commented out the guard check which allowed spdk to run at speeds comparable to doing a 512 format, and I also hardcoded an appropriate crc guard check value for a fixed pattern of data and ran with that fixed data pattern. that also ran at speeds comparable to 512. It appears that there are milliseconds being spent calculating the guard check per io, strangling throughput.

**Comment by ak-gh** [comment] 2018-10-25 19:56
On Thu, Oct 25, 2018 at 10:50 PM peterjweir <notifications@github.com>
wrote:

> I will try that commit as well, where I am at today it is all technically
> working, just very slowly. I have done two things to try to figure this
> out, I commented out the guard check which allowed spdk to run at speeds
> comparable to doing a 512 format, and I also hardcoded an appropriate crc
> guard check value for a fixed pattern of data and ran with that fixed data
> pattern. that also ran at speeds comparable to 512. It appears that there
> are milliseconds being spent calculating the guard check per io, strangling
> throughput.
>
Milliseconds sound (extremely) excessive, but it has already been mentioned
(in the email thread re iSCSI target) that built-in SPDK crc is way slower
than the SSE/AVS-aware optimized version shipping with the Intel Storage
Acceleration library (ISA-L).

Regards,
Andrey

**Comment by jimharris** [comment] 2018-10-25 20:07
Shuhei's patch should drastically improve the performance.  Maybe not to GB/s, but way better than you have now.

The code currently is getting the extended sector size very sub-optimally - it's issuing an IDENTIFY for every I/O!  So Shuhei's patch caches the IDENTIFY data which it should have been doing from the beginning.

**Comment by peterjweir** [comment] 2018-10-25 20:39
Thank you very much for all the quick help.

Returning and reporting, after applying the patch performance is unfortunately not significantly impacted. 

Here is some data that I've been gathering,
doing a sequential write workload., 64k block size.

512 format .   greater than 1000MBps
520 format starting point (default crc16 in spdk) ~ 7MBps
520 format 256 entry crc16 table implementation ~100MBps .  - pycrc implementation
520 format with crc16 calculation commented out and hardcoded to correct answer = greater than 1000MBps essentially the same as the 512 results.
there was less than a percent change when adding the nsdata patch recommended.
  
In these tests I only changed the crc16 call and algorithm used. I don't have any experience with the ISA-L but it sounds very promising. 

Peter

**Comment by jimharris** [comment] 2018-10-25 20:54
Hi @peterjweir,

Is the 520 format starting point (7MBps) with or without Shuhei's patch?

-Jim

**Comment by jimharris** [comment] 2018-10-25 20:55
Oh - never mind, I see now your comment about "less than a percent change".

Did you have Shuhei's patch applied for your crc16 table and crc16 hardcoded tests?

**Comment by jimharris** [comment] 2018-10-25 20:58
I looked at the fio_plugin further.  It was *not* issuing the identify on each I/O.  So that patch from Shuhei is not needed, and explains the results you see with the patch.

**Comment by jimharris** [comment] 2018-10-25 21:05
I just talked with our ISA-L expert Greg Tucker - he says crc16-t10dif calculations should be on the order of multiple GB/s per CPU core, exact numbers vary of course on a number of different variables.

**Comment by shuhei-matsumoto** [comment] 2018-10-25 23:39
@jimharris @peterjweir 

I apologize for my not-elaborated patch first. I think I could reproduce the issue https://github.com/spdk/spdk/issues/474. I will start investigation for these two issues and post any update.

**Comment by shuhei-matsumoto** [comment] 2018-10-26 02:13
I tried both PRACT=0 and PRACT=1 for the PI enabled NVMe namespace (512+8 and PI_type=1).
But I haven't observed any observed result yet. I'm afraid my operation is not correct, though.

NVMe format

```
[root@sophia-dev16 spdk]# nvme format /dev/nvme0n1 --lbaf 1 --pil 0 --pi 1 --ms 1
Success formatting namespace:1
[root@sophia-dev16 spdk]# nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     CVFT4400002C400GGN   INTEL SSDPE2MD400G4                      1         400.09  GB / 400.09  GB    512   B +  8 B   8DV101H0
/dev/nvme1n1     CVFT4396003G400GGN   INTEL SSDPE2MD400G4                      1         400.09  GB / 400.09  GB    512   B +  0 B   8DV101H0
/dev/nvme2n1     CVFT61220012400GGN   INTEL SSDPE2MD400G4                      1         400.09  GB / 400.09  GB    512   B +  0 B   8DV101H0
/dev/nvme3n1     CVFT7021006H400PGN   INTEL SSDPE2MD400G4                      1         400.09  GB / 400.09  GB    512   B +  0 B   8DV101H0

```

FIO configuration file

```
[root@sophia-dev16 spdk]# vim examples/nvme/fio_plugin/example_config.fio

[global]
ioengine=spdk
thread=1
group_reporting=1
direct=1
verify=0
time_based=1
ramp_time=0
runtime=60
iodepth=128
rw=randrw
bs=4k
numjobs=1

[job1]
filename=trtype=PCIe traddr=0000.01.00.0 ns=1 pi_act=0/1 pi_chk=GUARD|REFTAG|APPTAG

```


```
[root@sophia-dev16 spdk]# LD_PRELOAD=examples/nvme/fio_plugin/fio_plugin fio examples/nvme/fio_plugin/example_config.fio
job1: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk, iodepth=128
fio-3.3
Starting 1 thread
Starting SPDK v18.10-pre / DPDK 18.05.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 512 --legacy-mem --file-prefix=spdk_pid8185 ]
EAL: Detected 16 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/spdk_pid8185/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL:   using IOMMU type 1 (Type 1)
EAL: Releasing pci mapped resource for 0000:01:00.0/s][r=8386,w=8550 IOPS][eta 00m:00s]
EAL: Calling pci_unmap_resource for 0000:01:00.0 at 0x7f5c41600000

job1: (groupid=0, jobs=1): err= 0: pid=8207: Fri Oct 26 11:00:01 2018
   read: IOPS=89.8k, BW=351MiB/s (368MB/s)(20.5GiB/60003msec)
    slat (nsec): min=123, max=18101, avg=138.96, stdev=46.80
    clat (usec): min=2, max=8281, avg=128.67, stdev=390.95
     lat (usec): min=3, max=8281, avg=128.81, stdev=390.95
    clat percentiles (usec):
     |  1.00th=[    5],  5.00th=[    5], 10.00th=[    6], 20.00th=[    6],
     | 30.00th=[    7], 40.00th=[    8], 50.00th=[   10], 60.00th=[   13],
     | 70.00th=[   30], 80.00th=[   79], 90.00th=[  255], 95.00th=[  725],
     | 99.00th=[ 2311], 99.50th=[ 2507], 99.90th=[ 2868], 99.95th=[ 3097],
     | 99.99th=[ 4752]
   bw (  KiB/s): min=315336, max=399360, per=99.99%, avg=358966.86, stdev=18890.51, samples=120
   iops        : min=78834, max=99840, avg=89741.67, stdev=4722.62, samples=120
  write: IOPS=89.7k, BW=350MiB/s (367MB/s)(20.5GiB/60003msec)
    slat (nsec): min=131, max=18280, avg=292.41, stdev=94.20
    clat (usec): min=3, max=9643, avg=1297.09, stdev=1313.94
     lat (usec): min=5, max=9643, avg=1297.39, stdev=1313.95
    clat percentiles (usec):
     |  1.00th=[    8],  5.00th=[   10], 10.00th=[   11], 20.00th=[   15],
     | 30.00th=[   21], 40.00th=[   48], 50.00th=[ 1352], 60.00th=[ 1795],
     | 70.00th=[ 2180], 80.00th=[ 2704], 90.00th=[ 3097], 95.00th=[ 3359],
     | 99.00th=[ 4113], 99.50th=[ 4490], 99.90th=[ 5473], 99.95th=[ 7570],
     | 99.99th=[ 9241]
   bw (  KiB/s): min=309640, max=402432, per=99.99%, avg=358718.55, stdev=18806.19, samples=120
   iops        : min=77410, max=100608, avg=89679.62, stdev=4701.52, samples=120
  lat (usec)   : 4=0.03%, 10=30.97%, 20=16.49%, 50=10.32%, 100=4.45%
  lat (usec)   : 250=4.81%, 500=3.06%, 750=1.49%, 1000=0.95%
  lat (msec)   : 2=9.91%, 4=16.94%, 10=0.59%
  cpu          : usr=100.01%, sys=0.00%, ctx=22, majf=0, minf=4052
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwts: total=5385317,5381683,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=128

Run status group 0 (all jobs):
   READ: bw=351MiB/s (368MB/s), 351MiB/s-351MiB/s (368MB/s-368MB/s), io=20.5GiB (22.1GB), run=60003-60003msec

```

**Comment by peterjweir** [comment] 2018-10-26 17:22
the results that you get are comparable to when I don't do the crc at all.

My drive is formatted the same as yours, but with protection information type 2 instead of 1. I would have expected it to still do the guard check. Is it possible that the bdf doesn't match the drive that you have formatted?

the results when I comment out the crc and use the hardcoded answer look the same as your results above.

here are the results with the crc as implemented in spdk today and my fio file. I don't have the ability to do pract=1 with the equipment I have on hand.

```
[global]
direct=1
ioengine=spdk
numjobs=1
direct=0
group_reporting=1
log_avg_msec=1000
thread=1
ramp_time=0
shm_id=1

[0000:06:00.0]
filename=trtype=PCIe traddr=0000.06.00.0 ns=1
write_bw_log=0000.06.00.0
write_iops_log=0000.06.00.0
write_lat_log=0000.06.00.0
time_based=1
rw=randrw
bs=4k
iodepth=128
pi_act=0
pi_chk=GUARD|REFTAG|APPTAG
runtime=60
shm_id=1
```

```
Jobs: 1 (f=1): [m(1)][100.0%][r=6930KiB/s,w=6658KiB/s][r=1732,w=1664 IOPS][eta 00m:00s]
0000:06:00.0: (groupid=0, jobs=1): err= 0: pid=27421: Fri Oct 26 13:12:49 2018
   read: IOPS=1689, BW=6760KiB/s (6922kB/s)(396MiB/60025msec)
    slat (nsec): min=378, max=21977, avg=461.07, stdev=413.16
    clat (usec): min=13201, max=61603, avg=37801.13, stdev=1913.83
     lat (usec): min=13209, max=61603, avg=37801.59, stdev=1913.84
    clat percentiles (usec):
     |  1.00th=[34341],  5.00th=[35390], 10.00th=[35914], 20.00th=[36439],
     | 30.00th=[36439], 40.00th=[36963], 50.00th=[37487], 60.00th=[38011],
     | 70.00th=[38536], 80.00th=[39584], 90.00th=[40633], 95.00th=[41157],
     | 99.00th=[42206], 99.50th=[42730], 99.90th=[43779], 99.95th=[44303],
     | 99.99th=[57410]
   bw (  KiB/s): min= 6320, max= 7308, per=99.99%, avg=6758.00, stdev=172.25, samples=60
   iops        : min= 1580, max= 1827, avg=1689.50, stdev=43.05, samples=60
  write: IOPS=1686, BW=6748KiB/s (6910kB/s)(396MiB/60025msec)
    slat (usec): min=185, max=462, avg=196.89, stdev=12.32
    clat (usec): min=14283, max=61793, avg=37801.61, stdev=1915.76
     lat (usec): min=14514, max=61983, avg=37998.50, stdev=1921.45
    clat percentiles (usec):
     |  1.00th=[34341],  5.00th=[35390], 10.00th=[35914], 20.00th=[36439],
     | 30.00th=[36439], 40.00th=[36963], 50.00th=[37487], 60.00th=[38011],
     | 70.00th=[38536], 80.00th=[39584], 90.00th=[40633], 95.00th=[41157],
     | 99.00th=[42206], 99.50th=[42730], 99.90th=[43779], 99.95th=[44827],
     | 99.99th=[55313]
   bw (  KiB/s): min= 6492, max= 6956, per=99.99%, avg=6746.27, stdev=90.72, samples=60
   iops        : min= 1623, max= 1739, avg=1686.57, stdev=22.68, samples=60
  lat (msec)   : 20=0.02%, 50=99.96%, 100=0.02%
  cpu          : usr=100.00%, sys=0.00%, ctx=54, majf=0, minf=16
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwts: total=101435,101256,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=128

Run status group 0 (all jobs):
   READ: bw=6760KiB/s (6922kB/s), 6760KiB/s-6760KiB/s (6922kB/s-6922kB/s), io=396MiB (415MB), run=60025-60025msec
  WRITE: bw=6748KiB/s (6910kB/s), 6748KiB/s-6748KiB/s (6910kB/s-6910kB/s), io=396MiB (415MB), run=60025-60025msec
```

**Comment by peterjweir** [comment] 2018-10-26 18:29
I was able to get a hold of a P3700 drive, and I repeated your test with that drive as the only one attached to the system, here are the results.

```
Jobs: 1 (f=0): [f(1)][100.0%][eta 00m:00s]
0000:06:00.0: (groupid=0, jobs=1): err= 0: pid=31856: Fri Oct 26 14:28:54 2018
  write: IOPS=2538, BW=9.92MiB/s (10.4MB/s)(595MiB/60025msec)
    slat (usec): min=185, max=455, avg=196.78, stdev=11.86
    clat (usec): min=24319, max=72915, avg=50217.49, stdev=5602.23
     lat (usec): min=24509, max=73103, avg=50414.27, stdev=5604.76
    clat percentiles (usec):
     |  1.00th=[38011],  5.00th=[40109], 10.00th=[42206], 20.00th=[45351],
     | 30.00th=[48497], 40.00th=[49021], 50.00th=[50594], 60.00th=[51643],
     | 70.00th=[53216], 80.00th=[54789], 90.00th=[56886], 95.00th=[59507],
     | 99.00th=[62653], 99.50th=[64750], 99.90th=[67634], 99.95th=[67634],
     | 99.99th=[67634]
   bw (  KiB/s): min= 9948, max=10224, per=99.96%, avg=10148.65, stdev=57.02, samples=60
   iops        : min= 2487, max= 2556, avg=2537.17, stdev=14.26, samples=60
  lat (msec)   : 50=46.96%, 100=53.04%
  cpu          : usr=99.99%, sys=0.00%, ctx=98, majf=0, minf=13
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwts: total=0,152366,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=128

Run status group 0 (all jobs):
  WRITE: bw=9.92MiB/s (10.4MB/s), 9.92MiB/s-9.92MiB/s (10.4MB/s-10.4MB/s), io=595MiB (624MB), run=60025-60025msec
```

**Comment by shuhei-matsumoto** [comment] 2018-10-30 05:00
@peterjweir @jimharris

I could reproduced the low IOPS you have observed. I didn't see any difference between 512+8 and 512+16. The reason that I didn't see Peter's result was my error in the FIO config file. SPDK have another IO tool Perf (/example/nvme/perf/perf) and I could reproduced the same in the Perf.

Currently SPDK uses its own CRC library /lib/util/crc16.c and this performance is low. Hence I used ISA-L instead. As long as I used so far, ISA-L looks promising. Please see https://review.gerrithub.io/#/c/spdk/spdk/+/431243/ and the following results. 

For LIO, I'm investigating to compile fio_plugin with ISA-L. I'll update my progress later but I'm happy if you can.

@liang2yan Please categorize this into henhancement.


When using spdk_crc16_t10dif:

```
[root@sophia-dev16 spdk]# ./examples/nvme/perf/perf -q 128 -o 4096 -w write -t 10 -r 'trtype:PCIe traddr:0000.01.00.0' -e 'PRACT=0,PRCHK=GUARD|REFTAG'
Starting SPDK v18.10-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --file-prefix=spdk_pid10541 ]
EAL: Detected 16 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
Initializing NVMe Controllers
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL:   using IOMMU type 1 (Type 1)
Attaching to NVMe Controller at 0000:01:00.0
Attached to NVMe Controller at 0000:01:00.0 [8086:0953]
Associating INTEL SSDPE2MD400G4  (CVFT4400002C400GGN  ) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0
========================================================
                                                                                            Latency(us)
Device Information                                     :       IOPS       MB/s    Average        min        max
INTEL SSDPE2MD400G4  (CVFT4400002C400GGN  ) from core 0:   27955.20     109.20    4577.90      74.09    6677.47
========================================================
Total                                                  :   27955.20     109.20    4577.90      74.09    6677.47

EAL: Releasing pci mapped resource for 0000:01:00.0
EAL: Calling pci_unmap_resource for 0000:01:00.0 at 0x7feb55400000

```

```
[root@sophia-dev16 spdk]# ./examples/nvme/perf/perf -q 128 -o 4096 -w read -t 10 -r 'trtype:PCIe traddr:0000.01.00.0' -e 'PRACT=0,PRCHK
=GUARD|REFTAG'
Starting SPDK v18.10-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --file-prefix=spdk_pid10551 ]
EAL: Detected 16 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
Initializing NVMe Controllers
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL:   using IOMMU type 1 (Type 1)
Attaching to NVMe Controller at 0000:01:00.0
Attached to NVMe Controller at 0000:01:00.0 [8086:0953]
Associating INTEL SSDPE2MD400G4  (CVFT4400002C400GGN  ) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0
========================================================
                                                                                            Latency(us)
Device Information                                     :       IOPS       MB/s    Average        min        max
INTEL SSDPE2MD400G4  (CVFT4400002C400GGN  ) from core 0:   27750.50     108.40    4577.94     117.08    6758.02
========================================================
Total                                                  :   27750.50     108.40    4577.94     117.08    6758.02

EAL: Releasing pci mapped resource for 0000:01:00.0
EAL: Calling pci_unmap_resource for 0000:01:00.0 at 0x7feb55400000

```


When using crc16_t10dif in ISA-L

```
[root@sophia-dev16 spdk]# ./examples/nvme/perf/perf -q 128 -o 4096 -w write -t 10 -r 'trtype:PCIe traddr:0000.01.00.0' -e 'PRACT=0,PRCH
K=GUARD|REFTAG'
Starting SPDK v18.10-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --file-prefix=spdk_pid16768 ]
EAL: Detected 16 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
Initializing NVMe Controllers
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL:   using IOMMU type 1 (Type 1)
Attaching to NVMe Controller at 0000:01:00.0
Attached to NVMe Controller at 0000:01:00.0 [8086:0953]
Associating INTEL SSDPE2MD400G4  (CVFT4400002C400GGN  ) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0
========================================================
                                                                                            Latency(us)
Device Information                                     :       IOPS       MB/s    Average        min        max
INTEL SSDPE2MD400G4  (CVFT4400002C400GGN  ) from core 0:  268835.60    1050.14     476.11       4.90    7046.85
========================================================
Total                                                  :  268835.60    1050.14     476.11       4.90    7046.85

EAL: Releasing pci mapped resource for 0000:01:00.0
EAL: Calling pci_unmap_resource for 0000:01:00.0 at 0x7ff75b800000
```

```
[root@sophia-dev16 spdk]# ./examples/nvme/perf/perf -q 128 -o 4096 -w read -t 10 -r 'trtype:PCIe traddr:0000.01.00.0' -e 'PRACT=0,PRCHK
=GUARD|REFTAG'
Starting SPDK v18.10-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --file-prefix=spdk_pid16770 ]
EAL: Detected 16 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
Initializing NVMe Controllers
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL:   using IOMMU type 1 (Type 1)
Attaching to NVMe Controller at 0000:01:00.0
Attached to NVMe Controller at 0000:01:00.0 [8086:0953]
Associating INTEL SSDPE2MD400G4  (CVFT4400002C400GGN  ) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0
========================================================
                                                                                            Latency(us)
Device Information                                     :       IOPS       MB/s    Average        min        max
INTEL SSDPE2MD400G4  (CVFT4400002C400GGN  ) from core 0:  438142.20    1711.49     291.71      44.82    3112.54
========================================================
Total                                                  :  438142.20    1711.49     291.71      44.82    3112.54

EAL: Releasing pci mapped resource for 0000:01:00.0
EAL: Calling pci_unmap_resource for 0000:01:00.0 at 0x7f087d000000

```

**Comment by peterjweir** [comment] 2018-10-30 20:16
@shuhei-matsumoto I followed your isa-l implementation in your comment above and transplanted it into the fio-plugin, (after a fashion, my implementation isn't worth sharing) and the performance with ISA-L appears to be comparable to my performance with hard-coded values. It looks like this will fix it, I'm excited to see the finished implementation

**Comment by peterjweir** [comment] 2018-12-12 19:44
Are there any next steps to be able to include an ISA-L implementation into spdk as a feature and close this ticket?

**Comment by jimharris** [comment] 2018-12-13 16:08
ISA-L is coming very soon as a new git submodule in the SPDK repository.  That will make usage of ISA-L here much easier.

I've added a Trello card to track this feature request.  https://trello.com/c/XJKeDNo7/19-use-isa-l-for-prchkguard-calculations

Closing this issue - will track future progress on the feature through Trello.

-Jim

**Closed by jimharris** 2018-12-13 16:08 UTC
Labels: Medium, enhancement
