### ISSUE TITLE
An error occurs when multiple threads reading the file sequentially on blobfs

### ISSUE THREAD

**Issue by RongtongJin** [spdk/spdk#786] opened 2019-05-07 08:27 UTC
I wrote a program to test blobfs, but when multiple threads read the file sequentially, an error occurred and the program was abort occasionally.

I used Linux AIO bdev

## Expected Behavior

No error

## Current Behavior

Output information：
Starting SPDK v19.07-pre / DPDK 19.02.0 initialization...
[ DPDK EAL parameters: blobfs-test --no-shconf -c 0x1 --log-level=lib.eal:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid3107 ]
EAL: No free hugepages reported in hugepages-1048576kB
app.c: 628:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
using bdev AIO0
Generate a message.
msgContent=21ZntTAj9OU5vtpseasOZSCMgLv8fUa8LZj2HJbEnTAGdNZhNfWAVmcZXxX1fXZOL6GgDIKQr8ksL9AndkNYwOOh9z8dnVRWRo0k
thread-1 wirte start
thread-2 wirte start
thread-2 wirte done, writePos=1057000
thread-1 wirte done, writePos=2000000
Write done， write threads num = 2, cacheSize = 1024, msgSize = 100, msgTotalNum = 20000, cost time = 3469491
thread-3 random read start
thread-4 random read start
thread-3 random read done, check times = 10000
thread-4 random read done, check times = 10000
random read done， random read threads num = 2, random read time per thread = 10000, msgSize = 100, msgTotalNum = 20000, cost time = 443264
thread-5 sequential read start
**bdev.c: 611:spdk_bdev_io_get_buf: *ERROR*: Length + alignment 262656 is larger than allowed
benchmark: bdev.c:3516: spdk_bdev_io_complete: Assertion `bdev_ch->io_outstanding > 0' failed.
Aborted**

## Steps to Reproduce

This is the link of [program](https://github.com/RongtongJin/spdk/blob/blobfs-test/examples/blobfs/benchmark/main.c)

## Context (Environment including OS version, SPDK version, etc.)

Ubuntu 18.04
SPDK 19.01

**Comment by changpe1** [comment] 2019-05-07 08:34
@RongtongJin Thanks for submitting, can you try the following patch https://review.gerrithub.io/#/c/spdk/spdk/+/453491/ here, the root cause for this issue is obvious, and you can take issue 625 as reference.

**Comment by darsto** [comment] 2019-05-07 14:54
Bug scrub: The patch above fixes the segfault, but not the I/O error, which should not happen. Can you prepare a unit test that reproduces this? We'll move forward from there.

**Comment by changpe1** [comment] 2019-05-08 06:44
@darsto No, my patch is a serial to fix the issue, it's same issue with #625, existing code path didn't process big IO READ with unaligned buffer, so here take the failure 262656 bytes as an example, it will return error.

**Comment by RongtongJin** [comment] 2019-05-08 10:02
@changpe1 , Thanks for your reply. I tried your [patch](https://review.gerrithub.io/c/spdk/spdk/+/453491/), but the same error still existed.

**Comment by changpe1** [comment] 2019-05-09 00:41
@RongtongJin It's patch serial, not the only one I listed here.

**Comment by changpe1** [comment] 2019-07-10 01:24
@RongtongJin Can you try again with master branch? My patch set has been merged to address the aligned data buffer issue.

**Comment by changpe1** [comment] 2019-07-19 07:17
I'm going to close this issue for now, as SPDK will do the split first before getting data buffer from bdev layer, so even the IO size is much bigger than supported, it should be fine for now, you can reopen it again if your issue still exists. Thanks.

**Closed by changpe1** 2019-07-19 07:17 UTC
Labels: bug
