### ISSUE TITLE
[nvmf_multicontroller] Failed bdev_nvme_attach_controller

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1568] opened 2020-08-24 17:37 UTC
17:16:04	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe0 -t tcp -a 127.0.0.1 -s 4421 -f ipv4 -n nqn.2016-06.io.spdk:cnode1 -i 127.0.0.1 -c 60001
00:05:51.053  request:
00:05:51.053  {
00:05:51.053    "name": "NVMe0",
00:05:51.053    "trtype": "tcp",
00:05:51.053    "traddr": "127.0.0.1",
00:05:51.053    "hostaddr": "127.0.0.1",
00:05:51.053    "hostsvcid": "60001",
00:05:51.053    "adrfam": "ipv4",
00:05:51.053    "trsvcid": "4421",
00:05:51.053    "subnqn": "nqn.2016-06.io.spdk:cnode1",
00:05:51.053    "method": "bdev_nvme_attach_controller",
00:05:51.053    "req_id": 1
00:05:51.053  }
00:05:51.053  Got JSON-RPC error response
00:05:51.053  response:
00:05:51.053  {
00:05:51.053    "code": -22,
00:05:51.053    "message": "Invalid agrgument list. Existing controller name cannot be combined with host information or PI options.\n"
00:05:51.053  }
00:05:51.062   17:16:04	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe0 -t tcp -a 127.0.0.1 -s 4421 -f ipv4 -n nqn.2016-06.io.spdk:cnode1
00:05:51.280  NVMe0n1
00:05:51.291   17:16:04	# /home/vagrant/spdk_repo

**Comment by spdkci** [comment] 2020-08-24 17:38
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_24880.html

**Comment by mikeBashStuff** [comment] 2020-08-24 17:42
This is a duplicate of https://github.com/spdk/spdk/issues/1566. :)

**Comment by jimharris** [comment] 2020-08-24 17:44
1566 is a bdevperf verify error.  This one looks like an RPC failure.

It's the same test that's failing, but at least to me it seems like its failing for different reasons.

**Comment by peluse** [comment] 2020-08-24 17:53
agree

**Comment by mikeBashStuff** [comment] 2020-08-24 18:57
This one is the negative test which is meant to fail.

**Comment by peluse** [comment] 2020-08-24 19:04
With a Backtrace??

**Comment by mikeBashStuff** [comment] 2020-08-24 19:33
The piece of log which is included in the description shows output of the rpc call which doesn't fail the actual test (since we expect the failure here). The actual build failed on perform_tests call which raised the errexit trap, generating the backtrace.

**Comment by jimharris** [comment] 2020-08-24 19:58
I guess I'm confused about the original description on #1566.  It shows logs for data mismatches, but I can't find those mismatches anywhere in any of the CI logs.  It seems the logs from #1566 description were generated from some local repro steps.  @mikeBashStuff please correct me if I'm wrong here.

It still seems like there are two different issues here that need to be root caused separately.  Maybe they are the same issue, but that's not clear to me (yet).

1) the RPC issue that Paul reported here, this also seems to be the issue occurring in the CI related logs in #1566 
2) the data mismatch issue described in the #1566 description, it seems this issue was only reproduced locally when trying to debug one of the CI failures

**Comment by mikeBashStuff** [comment] 2020-08-24 20:19
The log about the mismatching data comes from the try.txt to which bdevperf writes its std{out,err}. It's missing from the CI since this file is not read at any point during the test and it's purged upon exiting from it. With that in mind, I had to reproduce it locally to see what's going on.

`test/nvmf/host/multicontroller.sh` is where these tests are coming from. The failure from the description of this issue is triggered as part of this particular set. The one that actually breaks the build concerns part where bdevperf actually starts to perform its own tests and can bee seen in the build.log as well.

**Comment by jimharris** [comment] 2020-08-24 20:21
Thanks @mikeBashStuff.

Could you add more to the #1566 description for this?  Otherwise I'm concerned we will get a bunch of duplicate issues like Paul's.  I'd suggest putting the primary failing signature (the RPC failure) first in the description so that it's more easily matched when people are looking for existing issues before filing a new one.

**Comment by spdkci** [comment] 2020-08-25 02:07
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_24896.html

**Comment by spdkci** [comment] 2020-08-25 02:32
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_24898.html

**Comment by spdkci** [comment] 2020-08-25 03:42
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_24902.html

**Comment by optimistyzy** [comment] 2020-08-25 06:44
The following shows the log for running: test/nvmf/host/multicontroller.sh --transport=tcp on my platform. It always fails.


 00:26:02       # /home/ziyeyang/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe0 -t tcp -a 127.0.0.1 -s 4420 -f ipv4 -n nqn.2016-06.io.spdk:cnode1 -i 127.0.0.1 -c 60000
NVMe0n1
 00:26:02       # /home/ziyeyang/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_get_controllers
 00:26:02       # grep -c NVMe
1
 00:26:02       # /home/ziyeyang/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe0 -t tcp -a 127.0.0.1 -s 4421 -f ipv4 -n nqn.2016-06.io.spdk:cnode1 -i 127.0.0.1 -c 60001
request:
{
  "name": "NVMe0",
  "trtype": "tcp",
  "traddr": "127.0.0.1",
  "hostaddr": "127.0.0.1",
  "hostsvcid": "60001",
  "adrfam": "ipv4",
  "trsvcid": "4421",
  "subnqn": "nqn.2016-06.io.spdk:cnode1",
  "method": "bdev_nvme_attach_controller",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -22,
  "message": "Invalid agrgument list. Existing controller name cannot be combined with host information or PI options.\n"
}
 00:26:02       # /home/ziyeyang/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe0 -t tcp -a 127.0.0.1 -s 4421 -f ipv4 -n nqn.2016-06.io.spdk:cnode1
NVMe0n1
 00:26:04       # /home/ziyeyang/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe1 -t tcp -a 127.0.0.1 -s 4421 -f ipv4 -n nqn.2016-06.io.spdk:cnode1 -i 127.0.0.1 -c 60001
NVMe1n1
  00:26:04      # /home/ziyeyang/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_get_controllers
  00:26:04      # grep -c NVMe
 00:26:04       # '[' 2 '!=' 2 ']'
 00:26:04       # /home/ziyeyang/spdk/test/bdev/bdevperf/bdevperf.py -s /var/tmp/bdevperf.sock perform_tests
request:
{
  "method": "perform_tests",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32603,
  "message": "bdevperf failed with error Operation not permitted"
}
  00:26:05      # trap - ERR
  00:26:05      # print_backtrace
  00:26:05      # [[ ehxBET =~ e ]]
  00:26:05      # args=("${BASH_ARGV[@]}")
  00:26:05      # local args
  00:26:05      # xtrace_disable
  00:26:05      # '[' no '!=' yes ']'
  00:26:05      # PREV_BASH_OPTS=ehxBET
  00:26:05      # [[ ehxBET == *\x* ]]
  00:26:05      # XTRACE_DISABLED=yes
  00:26:05      # set +x
========== Backtrace start: ==========

in test/nvmf/host/multicontroller.sh:69 -> main(["--transport=tcp"])
     ...
   64   if [ "$($rpc_py -s $bdevperf_rpc_sock bdev_nvme_get_controllers | grep -c NVMe)" != "2" ]; then
   65           echo "actual number of controllers is not equal to expected count."
   66           exit 1
   67   fi
   68
=> 69   $rootdir/test/bdev/bdevperf/bdevperf.py -s $bdevperf_rpc_sock perform_tests
   70
   71   killprocess $bdevperf_pid
   72
   73   $rpc_py nvmf_delete_subsystem nqn.2016-06.io.spdk:cnode1
   74
     ...

========== Backtrace end ==========
  00:26:05      # xtrace_enable
  00:26:05      # return 0
 00:26:05       # process_shm --id 0
 00:26:05       # type=--id
 00:26:05       # id=0
 00:26:05       # '[' --id = --pid ']'
 00:26:05       # '[' --id = --id ']'
 00:26:05       # id=0
  00:26:05      # find /dev/shm -name '*.0' -printf '%f\n'
 00:26:05       # shm_files=nvmf_trace.0
 00:26:05       # [[ -z nvmf_trace.0 ]]
 00:26:05       # for n in $shm_files
 00:26:05       # tar -C /dev/shm/ -cvzf /home/ziyeyang/spdk/../output/nvmf_trace.0_shm.tar.gz nvmf_trace.0
nvmf_trace.0
 00:26:06       # return 0
 00:26:06       # rm -f /home/ziyeyang/spdk/test/nvmf/host/try.txt
 00:26:06       # killprocess 19899
 00:26:06       # '[' -z 19899 ']'
 00:26:06       # kill -0 19899
  00:26:06      # uname
 00:26:06       # '[' Linux = Linux ']'
  00:26:06      # ps --no-headers -o comm= 19899
 00:26:06       # process_name=reactor_0
 00:26:06       # '[' reactor_0 = sudo ']'
 00:26:06       # echo 'killing process with pid 19899'
killing process with pid 19899

**Comment by tomzawadzki** [comment] 2020-08-25 15:31
[Bug scrub] Closing as duplicate of #1566. Still need address try.txt not getting saved - @mikeBashStuff introduced some patches to address it.

**Closed by tomzawadzki** 2020-08-25 15:31 UTC
Labels: Intermittent Failure
