### ISSUE TITLE
Different results from bdev_ocf_get_bdevs during ocf_persistent_metadata test

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1348] opened 2020-04-15 11:53 UTC
Reporting as a separate issue since it's a bit different from #1320. 

Linking latest comments from #1320 into here:

https://github.com/spdk/spdk/issues/1320#issuecomment-613943553
https://github.com/spdk/spdk/issues/1320#issuecomment-613991197

Failure occurs while diffing output from `bdev_ocf_get_bdevs`. The first call outputs the following:
```
  {
    "name": "ocfWT",
    "started": true,
    "cache": {
      "name": "Nvme0n1p0",
      "attached": true
    },
    "core": {
      "name": "Nvme0n1p1",
      "attached": true
    }
  },
  {
    "name": "ocfPT",
    "started": true,
    "cache": {
      "name": "Nvme0n1p2",
      "attached": true
    },
    "core": {
      "name": "Nvme0n1p3",
      "attached": true
    }
  },
  {
    "name": "ocfWB0",
    "started": true,
    "cache": {
      "name": "Nvme0n1p4",
      "attached": true
    },
    "core": {
      "name": "Nvme0n1p5",
      "attached": true
    }
  },
  {
    "name": "ocfWB1",
    "started": true,
    "cache": {
      "name": "Nvme0n1p4",
      "attached": true
    },
    "core": {
      "name": "Nvme0n1p6",
      "attached": true
    }
  }
]
```
After second, however, the output looks like this:
```
[
  {
    "name": "ocfWT",
    "started": false,
    "cache": {
      "name": "Nvme0n1p0",
      "attached": true
    },
    "core": {
      "name": "Nvme0n1p1",
      "attached": true
    }
  },
  {
    "name": "ocfPT",
    "started": false,
    "cache": {
      "name": "Nvme0n1p2",
      "attached": true
    },
    "core": {
      "name": "Nvme0n1p3",
      "attached": true
    }
  },
  {
    "name": "ocfWB0",
    "started": false,
    "cache": {
      "name": "Nvme0n1p4",
      "attached": true
    },
    "core": {
      "name": "Nvme0n1p5",
      "attached": true
    }
  },
  {
    "name": "ocfWB1",
    "started": false,
    "cache": {
      "name": "Nvme0n1p4",
      "attached": true
    },
    "core": {
      "name": "Nvme0n1p6",
      "attached": true
    }
  }
]
```
Both calls should return the same data. This doesn't happen at each test run - I was able to reproduce it locally, but after a 10th run or so (with a bit more distressing result as the actual app got hung, not responding to TERM, so `wait` called from `killprocess()` was not able to return blocking entire test from finishing). 

This is seen in builds for the following commits: https://review.spdk.io/gerrit/c/spdk/spdk/+/1327

**Comment by Donaim** [comment] 2020-04-15 12:17
Looking at the logs:
```
EAL:   using IOMMU type 1 (Type 1)
nvme_qpair.c: 499:spdk_nvme_qpair_process_completions: *ERROR*: Unable to resubmit as many requests as we completed.
vbdev_ocf.c:1587:metadata_probe_cores_construct: *NOTICE*: OCF metadata found on Nvme0n1 belongs to bdev named 'Nvme0n1p0'
```
reactor.c: 370:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
vbdev_ocf.c:1455:vbdev_ocf_construct: *NOTICE*: OCF bdev 'ocfWT' is waiting for core device 'Nvme0n1p1' to connect
nvme_qpair.c: 499:spdk_nvme_qpair_process_completions: *ERROR*: Unable to resubmit as many requests as we completed.
 13:21:46	# xtrace_enable
```
We are getting some errors from NVME device, which is probably the cause of issue.
I will try to reproduce this and investigate on what is happening to the NVME.

**Comment by mikeBashStuff** [comment] 2020-04-15 12:20
@Donaim Thanks, appreciate all the help. :)

**Comment by jimharris** [comment] 2020-04-15 19:27
The NVMe error is interesting.  @Seth5141 added that error message to indicate that something didn't work as expected, although by itself it shouldn't be a fatal error.

@mikeBashStuff or @Donaim - could one of you fill out the description above with some more detail?  It's a bit cryptic as it is currently written.

**Comment by mikeBashStuff** [comment] 2020-04-15 20:01
@jimharris Updated https://github.com/spdk/spdk/issues/1348#issue-600240413 with some additional info. Let me know if there's anything else needed.

**Comment by jimharris** [comment] 2020-04-15 20:38
Thanks @mikeBashStuff.

So looks like the difference is that the OCF bdevs aren't getting started?

We should update the title on this issue as well, to more closely specify the failure.  It would be hard for someone with an intermittent failure to match it to this issue solely based on the current title.

**Comment by mikeBashStuff** [comment] 2020-04-15 20:46
@jimharris That seems to be the case, yes.

Title updated as well.

**Comment by Donaim** [comment] 2020-04-16 08:51
OCF sends some IO requests on startup. Evidently those failed, but then OCF should have communicated an error. My guess is that NVME doesn't call finish_io callback, which would also explain the hung that @mikeBashStuff observed.
Will look at it in debugger today

**Comment by Donaim** [comment] 2020-04-17 08:30
I reproduced issued on my machine.
Not getting the NVME error at all, strange.
Tried updating OCF to 20.3 but it didn't help.
Will investigage further.

**Comment by Donaim** [comment] 2020-04-23 14:59
I made progress today
It seems that OCF is initializing correctly, but it takes really long time
I added a 200second sleep before doing `bdev_ocf_get_bdevs` from second run, and then results match
Questions that are still unanswered:
- why switching to JSON from INI format causes this behaviour? Here I observed that in case of JSON, the order of examines is different, which is probably more close to the root of issue
- why does OCF need so much time to initialize?

Will be investigating further

**Comment by Donaim** [comment] 2020-04-30 08:55
Newest OCF master shows this behaviour (very slow startup) for other tests too.
I will contact OCF team with this issue

**Comment by Donaim** [comment] 2020-05-15 08:30
I have been seeing very slow startup consitantly with 100% reproduction,
but it did not reproduce on @imjfckm environment. 
Then, at some point, I rebooted my machine, and after that I could not reproduce that behaviour to this day.
CI machines also don't seem to be able to reproduce it.
So I think I had something broken in my env.

What is left though is that test still fails.
But this can be fixed by adding a simple "sleep" after we wait for RPC.
That is because `waitforrpc` doesn't seem to guarantee that all devices will finish with async examine.

Not sure how that is related to switching to json config. Maybe it takes longer to do init with json, don't know.

So my proposed fix is adding "sleep 5" to the test.
It passes CI, and successfully ran on my machine for 1113 times.
https://review.spdk.io/gerrit/c/spdk/spdk/+/2430

**Comment by Donaim** [comment] 2020-06-10 08:16
The test has been fixed, doesn't fail anymore

**Closed by Donaim** 2020-06-10 08:16 UTC
Labels: Medium, bug
