### ISSUE TITLE
Unable to export FUSE through bdev_blobfs_mount

### ISSUE THREAD

**Issue by ChenBo2333** [spdk/spdk#988] opened 2019-10-17 01:48 UTC
When testing bdev_blobfs_mount command (./scripts/rpc.py blobfs_mount Malloc0 /root/nmbv/) , the response shows "message": "Method not found".

## Expected Behavior
The result returns true.

## Current Behavior
request:
{
  "method": "blobfs_mount",
  "req_id": 1,
  "bdev_name": "Malloc0",
  "mountpoint": "/root/nmbv/"
}
Got JSON-RPC error response
response:
{
  "code": -32601,
  "message": "Method not found"
}

## Possible Solution
Install fuse3-devel.x86_64 before compiling code.

## Steps to Reproduce
1. prepare a service with Fedora release 27, start spdk’s  bdev_svc;
2. use bdev_blobfs_detect with Malloc0, it returns false;
3. use bdev_blobfs_create with Malloc0, it returns true;
4. use bdev_blobfs_detect with Malloc0, it returns true;
5. use bdev_blobfs_mount with Malloc0.

## Context (Environment including OS version, SPDK version, etc.)

**Comment by dong-liuliu** [comment] 2019-10-17 01:54
hi, Bo
This probably caused by missing fuse enablement in ./confiure.
You need to run ./configure --enable-fuse before compiling.

**Comment by dong-liuliu** [comment] 2019-10-17 01:56
Since FUSE is optional to user, it will not be compiled defaultly. This is the reason why you can't find blobfs_mount RPC method.

**Comment by ChenBo2333** [comment] 2019-10-17 02:01
I think if there is no fuse, there should be no bdev_blobfs_mount command.

**Comment by jimharris** [comment] 2019-10-17 03:58
Hi @ChenBo2333,

I understand your point.  But this is how rpc.py help has worked for a long time.  For example, if you start up nvmf_tgt, and try to run any of the iscsi RPCs, they will fail the same way since the iscsi modules are not linked into nvmf_tgt.  There are many other combinations that are similar.

A nice feature enhancement could be for rpc.py --help to first do a "rpc_get_methods", and then only show help for the RPCs that are available.  Or show the help for unavailable methods, but with some kind of marker like "(unavailable)" to make it more clear.

My suggest would be to close this issue, since it is working as intended.  A separate issue can be filed for the feature enhancement (or it can be added as a Trello card in the backlog).

-Jim

**Comment by changpe1** [comment] 2019-10-17 04:40
@ChenBo2333 I'm going to close this issue for now and add a trello task in the backlog as the enhancement, thanks for submitting.

**Closed by changpe1** 2019-10-17 04:40 UTC
