### ISSUE TITLE
[vhost_scsi_lvol_integrity] ERROR: no test disk found!

### ISSUE THREAD

**Issue by AlekseyMarchuk** [spdk/spdk#1336] opened 2020-04-09 13:52 UTC
## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_9831.html

## Execution failed at

```
========== Backtrace start: ==========

in /var/jenkins/workspace/vhost-autotest/spdk/test/vhost/common.sh:1143 -> error_exit(["error"],["88"])
     ...
   1138	}
   1139	
   1140	function error_exit()
   1141	{
   1142		trap - ERR
   1143		print_backtrace
   1144		set +e
   1145		error "Error on $1 $2"
   1146	
   1147		at_app_exit
   1148		exit 1
     ...
in /var/jenkins/workspace/vhost-autotest/spdk/test/vhost/common.sh:88 -> error(["no test disk found!"])
     ...
   83  	{
   84  		echo "===========" >&2
   85  		message "ERROR" "$@" >&2
   86  		echo "===========" >&2
   87  		# Don't 'return 1' since the stack trace will be incomplete (why?) missing upper command.
=> 88  		false
   89  	}
   90  	
   91  	function warning()
   92  	{
   93  		message "WARN" "$@" >&2
     ...
in /var/jenkins/workspace/vhost-autotest/spdk/test/vhost/common.sh:1006 -> vm_check_scsi_location(["0"])
     ...
   1001		done'
   1002	
   1003		SCSI_DISK="$(echo "$script" | vm_exec $1 bash -s)"
   1004	
   1005		if [[ -z "$SCSI_DISK" ]]; then
   1006			error "no test disk found!"
   1007			return 1
   1008		fi
   1009	}
   1010	
   1011	# Script to perform scsi device reset on all disks in VM
     ...
in /var/jenkins/workspace/vhost-autotest/spdk/test/vhost/lvol/lvol_test.sh:236 -> main(["-x"],["--fio-bin=/home/sys_sgsw/fio_ubuntu"],["--ctrl-type=spdk_vhost_scsi"],["--thin-provisioning"])
     ...
   231 	    host_name="VM-$vm_num-${!qemu_mask_param}"
   232 	    vm_exec $vm_num "hostname $host_name"
   233 	    vm_start_fio_server $fio_bin $vm_num
   234 	
   235 	    if [[ "$ctrl_type" == "spdk_vhost_scsi" ]]; then
=> 236 	        vm_check_scsi_location $vm_num
   237 	    elif [[ "$ctrl_type" == "spdk_vhost_blk" ]]; then
   238 	        vm_check_blk_location $vm_num
   239 	    fi
   240 	
   241 	    fio_disks+=" --vm=${vm_num}$(printf ':/dev/%s' $SCSI_DISK)"
     ...

========== Backtrace end ==========
```

**Comment by spdkci** [comment] 2020-04-09 13:54
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_9831.html

**Comment by karlatec** [comment] 2020-04-14 06:50
Considering when this happened and on which particular node (GP15) I'd say the root cause of this issue is the same as here: https://github.com/spdk/spdk/issues/1339.
If this doesn't happen again in next few days then please close the issue.

**Comment by changpe1** [comment] 2020-04-16 03:17
Closing this issue for now, we can reopen it if it still exist.

**Closed by changpe1** 2020-04-16 03:17 UTC
Labels: Intermittent Failure
