### ISSUE TITLE
docker-compose build failed

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#2332] opened 2022-01-18 07:10 UTC
# Bug report
```
install -m 755 -d /usr/local/bin
install fio t/fio-genzipf t/fio-btrace2fio t/fio-dedupe t/fio-verify-state ./tools/fio_generate_plots ./tools/plot/fio2gnuplot ./tools/genfio ./tools/fiologparser.py ./tools/hist/fiologparser_hist.py ./tools/hist/fio-histo-log-pctiles.py ./tools/fio_jsonplus_clat2csv /usr/local/bin
install -m 755 -d /usr/local/man/man1
install -m 644 ./fio.1 /usr/local/man/man1
install -m 644 ./tools/fio_generate_plots.1 /usr/local/man/man1
install -m 644 ./tools/plot/fio2gnuplot.1 /usr/local/man/man1
install -m 644 ./tools/hist/fiologparser_hist.py.1 /usr/local/man/man1
install -m 755 -d /usr/local/share/fio
install -m 644 ./tools/plot/*gpm /usr/local/share/fio/
make: Leaving directory '/usr/src/fio'
* Starting rpmbuild...
setting SOURCE_DATE_EPOCH=1613433600
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.T098yd
+ umask 022
+ cd /
+ make clean
+ :
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.WOAnkb
+ umask 022
+ cd /
+ ./configure --disable-unit-tests --disable-tests --with-shared --with-virtio --with-fio
/var/tmp/rpm-tmp.WOAnkb: line 33: ./configure: No such file or directory


RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.WOAnkb (%build)
    Bad exit status from /var/tmp/rpm-tmp.WOAnkb (%build)
The command '/bin/sh -c /install' returned a non-zero code: 1
ERROR: Service 'build_base' failed to build

```

## Steps to Reproduce
these steps are following with spdk/docker/README.md. 
cd spdk/docker
......
docker login
sudo setenforce 0
docker-compose build --build-arg PROXY=$http_proxy

## Context (Environment including OS version, SPDK version, etc.)
commit 9d7e239f157a730de871d51a13b4212edac334f6

**Comment by changpe1** [comment] 2022-01-20 04:26
[Bug Scrub] @tomzawadzki can you take a look? thanks.

**Comment by mikeBashStuff** [comment] 2022-01-20 09:53
Caused by 47ee30d3e38af3001ca0866cb26fc6bb1361e7cc, potential fix here: https://review.spdk.io/gerrit/c/spdk/spdk/+/11174

@yidong0635 Would you kindly test the above fix on your end? You would need to rebuild the `spdk.tar.gz `to make sure the change this patch introduces is included inside.

I will try to add some tests covering the docker build stage to make sure similar issues are picked up under the CI.

**Comment by yidong0635** [comment] 2022-01-20 10:17
@mikeBashStuff  thanks, confirm it works for me.

**Comment by jimharris** [comment] 2022-01-21 15:59
Patch merged.  Thanks @mikeBashStuff!

**Closed by jimharris** 2022-01-21 15:59 UTC
Labels: bug, Low, Patches out for review
