### ISSUE TITLE
SPDK NVMe shows worse performance than libaio under 4K random read workload (perf tool)

### ISSUE THREAD

**Issue by jingliu9** [spdk/spdk#661] opened 2019-02-12 22:50 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

In terms of latency, SPDK NVMe Driver is supposed to be at least 3-4 us than libaio.

## Current Behavior

At small queue depth, it it is relatively the same as libaio. But with queue depth increasing, SPDK has higher latency than AIO.

Average Latency:

Queue Depth | 1 | 2 | 4 | 8 | 16 | 32 | 64 | 128 | 256
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
AIO (us) | 59.72 | 59.48 | 60.99 | 65.26 | 74.53 | 93.8 | 137.83 | 239.74 | 473.74
SPDK (us) | 57.39 | 57.21 | 59.36 | 64.66 | 77.3 | 104.58 | 182.12 | 364.33 | 729.95

IOPS:

Queue Depth | 1 | 2 | 4 | 8 | 16 | 32 | 64 | 128 | 256
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
AIO IOPS | 16736.06 | 33609.09 | 65548.66 | 122514.61 | 214558.88 | 340961.79 | 464158.58 | 533795.65 | 540321.32
SPDK IOPS | 17412.67 | 34932.58 | 67341.81 | 123649.23 | 206887.56 | 305877.41 | 351338.36 | 351288.95 | 350686.26

## Possible Solution

* probably the NVMe Driver not scale well for queue-depth
* probably report issue of perf 

## Steps to Reproduce

1. pre-condition the ssd using:  

```shell
 ./perf /dev/nvme0n1 -q 32 -s 131072 -w write -t 1200
```

2. for aio run scripts as:

```shell
for QD in 1 2 4 8 16 32 64 128 256
do
    sync; echo 3 > /proc/sys/vm/drop_caches
    echo "QD=${QD}"
    sleep 10
    ./perf /dev/nvme0n1 -L -q $QD -s 4096 -w randread -t 600 > aio_QD${QD}.log
    sleep 10
done

```

3. for spdk nvme driver, run:

```shell
for QD in 1 2 4 8 16 32 64 128 256
do
    sync; echo 3 > /proc/sys/vm/drop_caches
    echo "QD=${QD}"
    sleep 10
    ./perf -L -q ${QD} -s 4096 -w randread -r 'trtype:PCIe traddr:0000:01:00.0' -t 600 > spdk_QD${QD}.log
    sleep 10
done

```

## Context (Environment including OS version, SPDK version, etc.)

OS: Ubuntu 18.04 (linux 4.15.0-44-generic)
SPDK: 18.04.1
SSD: Samsung 970 pro, 1TB

**Comment by alekseymmm** [comment] 2019-02-13 08:54
SPDK nvme driver most likely will show better results than aio if you test with several io threads. Unfortunately you cannot do so with perf tool. Do you consider  performing the same tests with fio plugin and probably increase numjobs?

Nevertheless your results are still curious.

**Comment by pawelwod** [comment] 2019-02-13 12:09
Maybe kernel is using more than one queue pair to do IO? Or utilization more than one core for IO/irq. 
It also can merge IO that are close to each other.

You can try adding more CPU's at higher queuedepth (use check `./perf --help` for -c` param) and recheck results. Latency should drop.

**Comment by ak-gh** [comment] 2019-02-13 12:16
Preconditioning SSD with sequential write doesn't make much sense. To bring SSD into saturated mode, you need to write at least 2xcapacity with small block size (e.g., formatted 
SSD block size) __randomly__.

Regards,
Andrey

**Comment by ak-gh** [comment] 2019-02-13 12:28
Re the perf results, it looks like spdk nvme driver hits some bottleneck between qd=32 and 64, so that the bandwidth attained peaks out at 350K IOPS (while aio runs all the way up to 500K IOPS claimed by the SSD spec). It might be helpful to profile qd=64 run, to find out where the time is being spent.

**Comment by jimharris** [comment] 2019-02-13 14:55
> Preconditioning SSD with sequential write doesn't make much sense. To bring SSD into saturated mode, you need to write at least 2xcapacity with small block size (e.g., formatted
> SSD block size) **randomly**.
> 
> Regards,
> Andrey

No.  Preconditioning the SSD with sequential writes as @jingliu9 did is correct.

The only time small (4KiB) random writes should be used is when benchmarking small random writes, to get the SSD into a steady state for garbage collection.

**Comment by ak-gh** [comment] 2019-02-13 15:37
If SSD is preconditioned with large sequential writes, L2P will be compact and cheap to maintain. That's not what one would like to test against if one is looking for real-life saturated performance.

**Comment by jingliu9** [comment] 2019-02-13 16:45
> Re the perf results, it looks like spdk nvme driver hits some bottleneck between qd=32 and 64, so that the bandwidth attained peaks out at 350K IOPS (while aio runs all the way up to 500K IOPS claimed by the SSD spec). It might be helpful to profile qd=64 run, to find out where the time is being spent.

Thanks! Any suggestion on the how to *profile*? I tried the linux perf tool, which indicates that 70% time goes to spdk_nvme_qpair_process_completions().

**Comment by ak-gh** [comment] 2019-02-13 17:06
> Thanks! Any suggestion on the how to profile? I tried the linux perf tool, which indicates that 70% time goes to spdk_nvme_qpair_process_completions().

That's more or less expected, although it might be helpful to break that down to see if anything unexpected (such as waiting on some resource) occurs, and also compare linix perf top for qd 16 and 64,, to try to figure out where the bottleneck is.

Also, it might be helpful to check if this is a regression compared to 18.10 since attaining half a million read IOPS has never been a problem for SPDK NVMe driver in the past.

**Comment by benlwalker** [comment] 2019-02-13 17:53
I'm going to try to break down a bunch of these comments, plus give you some steps for the future.

> SPDK nvme driver most likely will show better results than aio if you test with several io threads.

No. SPDK should be showing better results in all circumstances always. And by a large margin.

> Maybe kernel is using more than one queue pair to do IO? Or utilization more than one core for IO/irq.
> It also can merge IO that are close to each other.

More queues don't provide additional performance at the device, they just allow for parallel submission of I/O without locks. By default, the kernel uses the 'nomerges' io scheduler for SSDs, so it isn't manipulating the I/O pattern at all. At <500k I/Ops, SPDK isn't remotely close to CPU bound, so the kernel leveraging more cores shouldn't matter.

I just ran some benchmarks on master and perf is able to do 4.1M random read I/O per second on a single core for me (using lots of SSDs of course). AIO caps out in the 450k range per core. Let's take the following steps to try to narrow this problem down:

1. Instead of preconditioning using large writes, can you precondition the drive by doing unmaps across the entire thing? Since you're doing randread, if you run them on a fully unmapped drive, you'll likely get extremely high performance at the device itself because there isn't actually any data to read and drives will often skip the DMA step. This is a fun trick for benchmarking the software side. This may not work with all devices.

2. Do you have any other SSDs available to use where you can verify that the result is SSD-independent? I only have variations of Intel SSDs at my desk at the moment. We've seen in the past that fast polling on some devices can expose timing issues in the device firmware that impact performance. If you don't have another SSD, you could try spinning for a microsecond in the perf tool prior to calling spdk_nvme_qpair_process_completions() each time and see if the performance improves.

3. Are you able to reproduce this problem on a more recent release of SPDK, such as 18.10, 19.01, or even the master branch? I don't think anything has changed here, but it's worth a try.

4. Can you provide the arguments you passed to SPDK's configure script? In particular, make sure you aren't using a debug build or have one of the sanitizers turned on.

**Comment by jingliu9** [comment] 2019-02-13 20:25
> I'm going to try to break down a bunch of these comments, plus give you some steps for the future.
> 
> > SPDK nvme driver most likely will show better results than aio if you test with several io threads.
> 
> No. SPDK should be showing better results in all circumstances always. And by a large margin.
> 
> > Maybe kernel is using more than one queue pair to do IO? Or utilization more than one core for IO/irq.
> > It also can merge IO that are close to each other.
> 
> More queues don't provide additional performance at the device, they just allow for parallel submission of I/O without locks. By default, the kernel uses the 'nomerges' io scheduler for SSDs, so it isn't manipulating the I/O pattern at all. At <500k I/Ops, SPDK isn't remotely close to CPU bound, so the kernel leveraging more cores shouldn't matter.
> 
> I just ran some benchmarks on master and perf is able to do 4.1M random read I/O per second on a single core for me (using lots of SSDs of course). AIO caps out in the 450k range per core. Let's take the following steps to try to narrow this problem down:
> 
>     1. Instead of preconditioning using large writes, can you precondition the drive by doing unmaps across the entire thing? Since you're doing randread, if you run them on a fully unmapped drive, you'll likely get extremely high performance at the device itself because there isn't actually any data to read and drives will often skip the DMA step. This is a fun trick for benchmarking the software side. This may not work with all devices.
> 
>     2. Do you have any other SSDs available to use where you can verify that the result is SSD-independent? I only have variations of Intel SSDs at my desk at the moment. We've seen in the past that fast polling on some devices can expose timing issues in the device firmware that impact performance. If you don't have another SSD, you could try spinning for a microsecond in the perf tool prior to calling spdk_nvme_qpair_process_completions() each time and see if the performance improves.
> 
>     3. Are you able to reproduce this problem on a more recent release of SPDK, such as 18.10, 19.01, or even the master branch? I don't think anything has changed here, but it's worth a try.
> 
>     4. Can you provide the arguments you passed to SPDK's configure script? In particular, make sure you aren't using a debug build or have one of the sanitizers turned on.

Thanks very much. I'm going to try the suggestions.
* But I'm not quite understanding the meaning of *doing unmaps across the entire SSD*. Can you give me an example or explain more about that.
* The arguments I passed into configure is "configure --with-fio=<pathtofio>/fio"

**Comment by benlwalker** [comment] 2019-02-13 21:11
unmap is a term from SCSI that's equivalent to ATA's trim or NVMe's deallocate. I use them interchangeably - sorry about that. I guess we don't have unmap support in the NVMe perf tool. You could use standard fio (with the libaio engine) I think to do it.

**Comment by jingliu9** [comment] 2019-02-14 02:43
@benlwalker 
I have tried trim through via and re-do the experiment.

Latency:

Queue Depth | 1 | 2 | 4 | 8 | 16 | 32 | 64 | 128 | 256
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
AIO (us) | 21.82 | 19.34 | 22.12 | 25.34 | 33.11 | 58.37 | 115.8 | 231.16 | 461.91
SPDK (us) | 17.7 | 19.11 | 20.82 | 31.65 | 53.78 | 104.32 | 219 | 438.18 | 876.04


IOPS:


Queue Depth | 1 | 2 | 4 | 8 | 16 | 32 | 64 | 128 | 256
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
AIO IOPS | 45785.89 | 103332.37 | 180662.93 | 315422.81 | 482940.15 | 548030.47 | 552570.95 | 553683.2 | 554197.33
SPDK IOPS | 56435.64 | 104576.89 | 191975.13 | 252603.28 | 297446.47 | 306696.7 | 292212 | 292103.37 | 292220.71

And When I use spdknvme's perf with '-c 3' (starting 2 lcores) w/ queue depth 32, I can only get 290k IOPS and nealy 2x latency as single core result.

I have no idea why this result. It seems spdk reaches IOPS limit more quickly and CPU is not the bottleneck. I'm wondering if this because I install the SSD into M2 slot instead of PCIe slot?

**Comment by Comphix** [comment] 2019-02-14 05:23
Hi Jing,

Do you also have Intel NVMe SSD on hand for the testing besides the Samsung SSD used for the testing?

Thanks,
Gang

**Comment by jingliu9** [comment] 2019-02-14 05:54
@Comphix At this time, I do not have Intel NVMe SSD for testing.

**Comment by optimistyzy** [comment] 2019-02-14 08:49
@jingliu9  Can you describe the SPDK version you used?  I remembered that for the large IO size (Since you use 128KB for test), previously @changpe1 has submitted a fix for the entries number for the qpair. With this fix, we can guarantee the real entry number for each qpair. Without this patch, the I/O entries will not be enough). According to your test script, your perf tool is old with -S to describe the iosize. So it means that your spdk version is far from this fix. And I think that you use the latest spdk version to test.

**Comment by optimistyzy** [comment] 2019-02-14 08:54
In the new perf tool, there are the following statements:

 max_xfer_size = spdk_nvme_ns_get_max_io_xfer_size(ns);
        spdk_nvme_ctrlr_get_default_io_qpair_opts(ctrlr, &opts, sizeof(opts));
        /* NVMe driver may add additional entries based on
         * stripe size and maximum transfer size, we assume
         * 1 more entry be used for stripe.
         */
        entries = (g_io_size_bytes - 1) / max_xfer_size + 2;
        if ((g_queue_depth * entries) > opts.io_queue_size) {
                printf("controller IO queue size %u less than required\n",
                       opts.io_queue_size);
                printf("Consider using lower queue depth or small IO size because "
                       "IO requests may be queued at the NVMe driver.\n");
                g_warn = true;
        }
        /* For requests which have children requests, parent request itself
         * will also occupy 1 entry.
         */
        entries += 1;

It means that if the tested I/O size is larger than max io size supported by the name space. We need to allocate more entries for the underlying io qpair.  Otherwise, with the old version, the allocated entries for the I/O qpairs are not enough, so with bigger I/O depth, the performance will be decreased. Since some I/Os need to wait. Since in our NVMe driver, we have split I/Os

**Comment by ak-gh** [comment] 2019-02-14 10:04
It would be informative to check what this specific controller reports under default qpair options. If the io indeed gets queued up for insufficient controller resources, that would easily explain the performance stall at higher queue depths being observed.

**Comment by jingliu9** [comment] 2019-02-14 13:18
> @jingliu9 Can you describe the SPDK version you used? I remembered that for the large IO size (Since you use 128KB for test), previously @changpe1 has submitted a fix for the entries number for the qpair. With this fix, we can guarantee the real entry number for each qpair. Without this patch, the I/O entries will not be enough). According to your test script, your perf tool is old with -S to describe the iosize. So it means that your spdk version is far from this fix. And I think that you use the latest spdk version to test.

**Comment by jingliu9** [comment] 2019-02-14 13:47
> In the new perf tool, there are the following statements:
> 
> max_xfer_size = spdk_nvme_ns_get_max_io_xfer_size(ns);
> spdk_nvme_ctrlr_get_default_io_qpair_opts(ctrlr, &opts, sizeof(opts));
> /* NVMe driver may add additional entries based on
> * stripe size and maximum transfer size, we assume
> * 1 more entry be used for stripe.
> _/ entries = (g_io_size_bytes - 1) / max_xfer_size + 2; if ((g_queue_depth * entries) > opts.io_queue_size) { printf("controller IO queue size %u less than required\n", opts.io_queue_size); printf("Consider using lower queue depth or small IO size because " "IO requests may be queued at the NVMe driver.\n"); g_warn = true; } /_ For requests which have children requests, parent request itself
> * will also occupy 1 entry.
> */
> entries += 1;
> 
> It means that if the tested I/O size is larger than max io size supported by the name space. We need to allocate more entries for the underlying io qpair. Otherwise, with the old version, the allocated entries for the I/O qpairs are not enough, so with bigger I/O depth, the performance will be decreased. Since some I/Os need to wait. Since in our NVMe driver, we have IO splitting mechanism if there are large I/Os.
> So it is better to know the max_xfer_size of your nvme device.

@optimistyzy 
* For the read after trim experiment suggested, I already switch to v19.01, the latest version.
* max_xfer_size:2072576    opts.io_queue_size:2796951264

**Comment by ak-gh** [comment] 2019-02-14 19:23
The io_queue_size as reported by the controller doesn't look legitimate, so my guess is the that sodk nvme driver, being fooled by this, limits the queue depth to 128k (its default maximum transfer size)/4k=32. Hence, you are witnessing no bandwidth improvement at qd > 32.

**Comment by jingliu9** [comment] 2019-02-14 21:49
Hi,

I'm wondering what is the best SSD for spdk?

Thanks

**Comment by jingliu9** [comment] 2019-02-15 05:10
> Hi Jing,
> 
> Do you also have Intel NVMe SSD on hand for the testing besides the Samsung SSD used for the testing?
> 
> Thanks,
> Gang

@Comphix 
Any suggestion on which Intel SSD is better? Like more suitable to be used w/ SPDK.

Thanks

**Comment by optimistyzy** [comment] 2019-02-15 06:55
@jingliu9  this value reported "* opts.io_queue_size:2796951264"  is sounds not make sense.  
In our code line 1662:  we have set
opts->io_queue_size = UINT16_MAX,  but you finally get  opts.io_queue_size:2796951264.  According to our code, the io_queue_size should be less than 65536

**Comment by ak-gh** [comment] 2019-02-15 07:12
Yup. So my suggestion is to guard against faulty controller by setting queue size to the minimum of the value returned and 65535, and rerun tje tests for high queue depths.

**Comment by optimistyzy** [comment] 2019-02-15 07:41
@ak-gh  The value provided by @jingliu9  is very strange.

**Comment by jingliu9** [comment] 2019-02-15 13:35
@ak-gh 
I re-check the line I put the print(), yeah, it is not initialized at that point that is right before spdk_nvme_ctrlr_get_default_io_qpair_opts(). The value is 16384 actually.

**Comment by jingliu9** [comment] 2019-02-28 12:33
Hi,

I have gotten an optane SSD to test. It looks using all the above experiment setting, SPDK could get better performance (latency, IOPS, though in some cases not that much). I think this somehow indicates my 970 SSD + SPDK probably results in some wired issues.

Thank you all.

**Comment by jimharris** [comment] 2019-03-01 22:23
Thanks @jingliu9!

I'm going to mark this issue as a 3rd party issue and close it.  If you (or anyone else) is interested in debugging this 970 issue further, I would be happy to provide some guidance and then accept patches.

**Closed by jimharris** 2019-03-01 22:23 UTC
Labels: 3rd party issue
