### ISSUE TITLE
iscsi_tgt: ip_migration.sh test is failing in NIGHTLY test

### ISSUE THREAD

**Issue by luleilei1** [spdk/spdk#544] opened 2018-12-17 07:13 UTC
spdk_vhost.sh --migration run timeout in "fedora-06" for several days, key logs as below:
START TEST SUITE  ./test/iscsi_tgt/ext4test/ext4test.sh

iscsi_subsystem.c: 165:spdk_iscsi_initialize_pdu_pool: *ERROR*: create PDU pool failed
iscsi_subsystem.c:1311:spdk_iscsi_parse_globals: *ERROR*: spdk_initialize_all_pools() failed
iscsi_subsystem.c:1336:spdk_iscsi_init: *ERROR*: spdk_iscsi_parse_globals() failed
subsystem.c: 120:spdk_subsystem_init_next: *ERROR*: Init subsystem iscsi failed
app.c: 697:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero

Exception:
Connection closed with partial response:

iscsi_tgt.c: 114:main: *ERROR*: Start iscsi target daemon:  spdk_app_start() retn non-zero

=> 26  	$rpc_py start_subsystem_init
=> 49              run_test suite ./test/iscsi_tgt/ext4test/ext4test.sh
=> 151 		run_test suite ./test/iscsi_tgt/iscsi_tgt.sh posix

## Expected Behavior
./test/iscsi_tgt/ext4test/ext4test.sh can run passed.

## Current Behavior
./test/iscsi_tgt/ext4test/ext4test.sh run failed.

## Possible Solution
N/A

## Steps to Reproduce
1.cd SPDK dir
2.run ./test/iscsi_tgt/ext4test/ext4test.sh
3.or look at logs in "fedora-06",
 https://ci.spdk.io/spdk/builds/review/7f8d0ab611b93bf5e406939482df2444c3f5ef1e.1544961671/fedora-06/build.log (search "test/iscsi_tgt/ext4test/ext4test.sh").

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit 04d09f920731e1978d58d7c57b8142d1d83a536f

**Comment by jimharris** [comment] 2018-12-17 14:44
The problem is the ip_migration.sh test case just before this one:

Requested queue_depth 128 but only 128 is supported.
job0: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=32
fio-3.3
Starting 1 thread
 07:16:27	# /home/sys_sgsw/build_pool/agent/repo/scripts/rpc.py -s /var/tmp/spdk0.sock kill_instance SIGTERM
iscsi_tgt: iscsi.c:3228: spdk_iscsi_conn_abort_queued_datain_tasks: Assertion `pdu != NULL' failed.
 07:16:28	# rpc_second_addr=/var/tmp/spdk1.sock
 07:16:28	# rpc_add_target_node /var/tmp/spdk1.sock
 07:16:28	# /home/sys_sgsw/build_pool/agent/repo/scripts/rpc.py -s /var/tmp/spdk1.sock add_ip_address 1 127.0.0.2
./test/iscsi_tgt/ip_migration/ip_migration.sh: line 31: 129849 Aborted                 (core dumped) $ISCSI_APP -r $rpc_addr -s 1000 -i $i -m $ISCSI_TEST_CORE_MASK --wait-for-rpc
 07:16:28	# /home/sys_sgsw/build_pool/agent/repo/scripts/rpc.py -s /var/tmp/spdk1.sock add_portal_group 1 127.0.0.2:3260
 07:16:28	# /home/sys_sgsw/build_pool/agent/repo/scripts/rpc.py -s /var/tmp/spdk1.sock construct_target_node target1 target1_alias Malloc0:0 1:2 64 -d
 07:16:28	# wait 129955


So there are two issues here.  One is the assert.  The other is that the test did not stop at this point - it continued on to the ext4test.

@optimistyzy - can you take a look?

**Comment by shuhei-matsumoto** [comment] 2018-12-25 06:38
@ZiyeYang I'll look at the issue.

**Comment by optimistyzy** [comment] 2018-12-25 06:41
@shuhei-matsumoto  Currently, I checked the code. Firstly, the assert should not occur. It seems that the pdu is freed,  but I did not find the free path yet...

**Comment by shuhei-matsumoto** [comment] 2018-12-25 06:50
@ZiyeYang 

Thanks for your update. I can remove assert but this free is unexpected and it's fine if we can know the path to this issue. I've not found the path yet too.

**Comment by shuhei-matsumoto** [comment] 2018-12-25 07:10
@ZiyeYang @jimharris (sorry for your winter vacation),


The following path is probable? The abort task is not bind to any connection, hence the following path might cause the issue. I don't find error log related with my estimation yet.

1. shutdown path starts, that is, spdk_shutdown_iscsi_conns() is called.
2. the poller g_shutdown_timer starts and spdk_iscsi_conn_check_shutdown() is called repeatedly.
3. spdk_iscsi_conn_check_shutdown() doesn't find any active connection, and call spdk_iscsi_conn_check_shutdown_cb().
4. spdk_shutdown_iscsi_conns_done() is called in spdk_iscsi_conn_check_shutdown_cb().
5. spdk_iscsi_conn_check_shutdown_cb calls spdk_iscsi_fini_done() on each thread.
6. spdk_iscsi_fini_done() frees iscsi->task_pool even if the abort task is still outstanding.

I'll continue code inspection.

**Comment by shuhei-matsumoto** [comment] 2018-12-25 07:18
We may have to manage all pending tasks and wait their completion before starting pool free. I'll create a patch if possible. I can't access the log from outside of Intel and so your any support is appreciated.

**Comment by optimistyzy** [comment] 2018-12-25 07:38
@shuhei-matsumoto  However, for the iSCSI connection free, it will check the pending tasks of the connection, I think that mangement tasks are also belonging to this connection. If there is still tasks, the connections will not be destroyed.

**Comment by optimistyzy** [comment] 2018-12-25 07:45
@shuhei-matsumoto  I mean that the step 3 will not be completed since you still have pending tasks for the conn. I did not see that spdk_iscsi_conn_free_tasks will free the management task.

**Comment by shuhei-matsumoto** [comment] 2018-12-25 07:52
@ZiyeYang 

My patch will suspend mgmt tasks until all related datain tasks are aborted
suspended mgmt tasks don't belong to any connection until they are submitted to scsi.
So, I have to add an new linked list to manage those mgmt tasks.

This suspend was added to fix issues.

**Comment by shuhei-matsumoto** [comment] 2018-12-25 07:58
Thank you, my estimation was wrong, and you are correct.

**Comment by shuhei-matsumoto** [comment] 2018-12-25 08:57
@ZiyeYang 

I found pdu is freed even if mgmt task refers the pdu in the case that the issue have occurred.

the mgmt task continues access the associated pdu even after the pdu is freed.

_spdk_iscsi_op_abort_task_set() is called repeatedly by the poller, and _spdk_iscsi_op_abort_task_set() continues to access task->pdu.

The task->pdu is freed immediately after returning spdk_iscsi_execute().

Please see spdk_iscsi_conn_handle_incoming_pdus() in lib/iscsi/conn.c.

We have to extract CmdSN from the PDU at least before the PDU is freed, and hold it.


This is memory leak and should be fixed, but I have not found the path that results in the issue yet.

Thanks,
Shuhei

**Comment by shuhei-matsumoto** [comment] 2018-12-25 09:05
@ZiyeYang 

Just adding a note. I'm reading the path that spdk_iscsi_conn_flush_pdus() is called when spdk_iscsi_conn_handle_incoming_pdus() fails, and will continue tomorrow.

**Comment by shuhei-matsumoto** [comment] 2018-12-25 09:13
Hi @liang2yan @luleilei1 

This issue is solid (i.e. this issue occurs for every run) or intermittent?
Will you let me know if you know?

**Comment by ZiyeYang** [comment] 2018-12-25 10:32
Hi Shuhei,

You are right,  one reference of pdu is freed immediately after executing spdk_iscsi_execute()., however there is a reference of pdu by task, so the pdu will not be freed.



Best Regards
Ziye Yang

**Comment by shuhei-matsumoto** [comment] 2018-12-25 10:56
@ZiyeYang

Thank you for giving lecture to me. I understood this is also OK.

**Comment by shuhei-matsumoto** [comment] 2018-12-26 00:12
@ZiyeYang 

I observed unexpected reuse of iscsi_task.

iscsi_task for TMF is reused for SCSI read before TMF completes.
I added an assert if any iscsi task with mgmt_poller is freed.

I haven't found any logic why this unexpected reuse occurs.

https://ci.spdk.io/spdk/builds/review/db371318ee17076ac0d9800e77dd397ebf38bf03.1545781397/fedora-02/build.log

**Comment by luleilei1** [comment] 2018-12-26 01:05
Hi all,
the issue is solid.
It appears in the NIGHTLY test log every day.

**Comment by optimistyzy** [comment] 2018-12-26 02:54
@shuhei-matsumoto  Thanks for your patch, but you do not need to disable the test, if only happens in nightly test.

**Comment by optimistyzy** [comment] 2018-12-26 05:32
@jimharris I can confirm that this patch:  https://review.gerrithub.io/#/c/spdk/spdk/+/438223/ provided by @shuhei-matsumoto  finds the root cause, and the bug can be solved.  @luleilei1  @liang2yan  Can you retest it?

**Closed** 2018-12-31 06:36 UTC
Labels: bug
