### ISSUE TITLE
fio bdev plugin does not work in client-server mode; server bad crc on command error

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1118] opened 2019-12-18 08:27 UTC
## Current Behavior
Cannot run fio bdev plugin in client-server mode.
Attempt to do so results in 
```
fio: server bad crc on command (got 702d, wanted f767)
fio: server bad crc on command (got 702d, wanted f767)
client: host=127.0.0.1 disconnected
fio: server bad crc on command (got 6169, wanted 7e2d)
fio: server bad crc on command (got 6169, wanted 7e2d)
```

## Steps to Reproduce
1. Compile SPDK with --with-fio option
2. Run Vhost. Create NVMe bdev, scsi controller, attach a LUN
```
/home/klateck/work/spdk/app/vhost/vhost -p 0 -m '[0]'
/home/klateck/work/spdk/scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t pcie -a 0000:84:00.0
/home/klateck/work/spdk/scripts/rpc.py  vhost_create_scsi_controller naa.0.0
/home/klateck/work/spdk/scripts/rpc.py  vhost_scsi_controller_add_target naa.0.0 0 Nvme0n1p0
```
3. Start a VM and attach to controlelr socket
```
taskset -a -c 12-23 qemu-system-x86_64   -m 8192 --enable-kvm -cpu host -smp 12 -vga std -vnc :100 -daemonize 
-object memory-backend-file,id=mem,size=8192M,mem-path=/dev/hugepages,share=on,prealloc=yes,host-nodes=1,policy=bind   
-snapshot -monitor telnet:127.0.0.1:10002,server,nowait  
-numa node,memdev=mem  
-pidfile /home/klateck/vhost_test/vms/0/qemu.pid  
-serial file:/home/klateck/vhost_test/vms/0/serial.log  
-D /home/klateck/vhost_test/vms/0/qemu.log  
-chardev file,path=/home/klateck/vhost_test/vms/0/seabios.log,id=seabios 
-device isa-debugcon,iobase=0x402,chardev=seabios  

-net user,hostfwd=tcp::10000-:22,hostfwd=tcp::10001-:8765 
-net nic 

-drive file=/home/sys_sgci/fedora29.qcow2,if=none,id=os_disk  
-device ide-hd,drive=os_disk,bootindex=0  
-chardev socket,id=char_0,path=/home/klateck/vhost_test/vhost/0/naa.0.0  
-device vhost-user-scsi-pci,id=scsi_0,num_queues=12,chardev=char_0
```

4. Copy SPDK and FIO source to the VM.
Compile SPDK with --with-fio option.
Compile FIO and make sure it's the same version as on host server.

5. Prepare configuration files in VM for fio-bdev:
fio.conf:
```
[global]
ioengine=/root/spdk/examples/bdev/fio_plugin/fio_plugin
spdk_conf=/root/spdk/bdev.conf
thread=1
group_reporting=1
direct=1

norandommap=1
rw=randread
rwmixread=70
bs=4k
iodepth=32
time_based=1
ramp_time=0
runtime=30

[test]
filename=VirtioScsi0t0
```

bdev.conf:
```
[VirtioPci]
  Enable Yes
```

6. Run fio-bdev loclly in the VM to confirm configs are OK:
```
[root@VM-0 spdk]# sudo scripts/setup.sh
0000:00:04.0 (1af4 1004): virtio-pci -> uio_pci_generic

[root@VM-0 spdk]# sudo /root/fio/fio fio.conf
filename0: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk_bdev, iodepth=16
fio-3.15
Starting 1 thread
Starting SPDK v19.10-pre / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid357227 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL:   Invalid NUMA socket, default to 0
Jobs: 1 (f=1): [r(1)][100.0%][r=1737MiB/s][r=445k IOPS][eta 00m:00s]
filename0: (groupid=0, jobs=1): err= 0: pid=357231: Wed Dec 18 09:15:56 2019
  read: IOPS=447k, BW=1746MiB/s (1830MB/s)(25.6GiB/15001msec)
    slat (nsec): min=357, max=579364, avg=1008.74, stdev=1245.22
    clat (usec): min=3, max=633, avg=24.06, stdev= 9.32
     lat (usec): min=7, max=634, avg=25.07, stdev= 9.42

[etc, etc... it works]
```

7. In VM start fio in server/daemonized mode. Then try running client command from host.
```
[root@VM-0 spdk]# sudo /root/fio/fio --version
fio-3.15
[root@VM-0 spdk]# sudo /root/fio/fio --eta=never --server --daemonize=/root/fio.pid

[klateck@GrizzlyPass8 spdk]$ sudo /usr/src/fio/fio --version
fio-3.15
[klateck@GrizzlyPass8 spdk]$ sudo /usr/src/fio/fio --client=127.0.0.1,10001 --remote-config /root/spdk/fio.conf
hostname=VM-0, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-3.15, flags=1
<VM-0> filename0: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk_bdev, iodepth=16
<VM-0> Starting 1 thread
fio: server bad crc on command (got 702d, wanted f767)
fio: server bad crc on command (got 702d, wanted f767)
client: host=127.0.0.1 disconnected
fio: server bad crc on command (got 6169, wanted 7e2d)
fio: server bad crc on command (got 6169, wanted 7e2d)
```

8. Running the client from inside the guest VM has the same effect:
```
[root@VM-0 spdk]# sudo /root/fio/fio --client=127.0.0.1,8765 /root/spdk/fio.conf
hostname=VM-0, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-3.15, flags=1
<VM-0> filename0: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk_bdev, iodepth=16
<VM-0> Starting 1 thread
fio: server bad crc on command (got 702d, wanted f767)
fio: server bad crc on command (got 702d, wanted f767)
client: host=127.0.0.1 disconnected
fio: server bad crc on command (got 6169, wanted 7e2d)
fio: server bad crc on command (got 6169, wanted 7e2d)
```

9. Confirm that Fio 3.15 works in client-server mode w/o spdk plugin
```
[root@VM-0 spdk]# sudo scripts/setup.sh reset
0000:00:04.0 (1af4 1004): uio_pci_generic -> virtio-pci


[root@VM-0 spdk]# cat fio2.conf
[global]
ioengine=libaio

thread=1
group_reporting=1
direct=1

norandommap=1
rw=randread
rwmixread=70
bs=4k
iodepth=16
time_based=1
ramp_time=0
runtime=15

[filename0]
filename=/dev/sdb

[klateck@GrizzlyPass8 spdk]$ sudo /usr/src/fio/fio --client=127.0.0.1,10001 --remote-config /root/spdk/fio2.co
nf
hostname=VM-0, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-3.15, flags=1
<VM-0> filename0: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=16
<VM-0> Starting 1 thread
<VM-0>  (f=1): [r(1)][100.0%][r=414M][r=104k IOPS][eta 00m:00s]
filename0: (groupid=0, jobs=1): err= 0: pid=357688: Wed Dec 18 09:20:54 2019
  read: IOPS=111k, BW=434MiB/s (455MB/s)(6514MiB/15001msec)
    slat (usec): min=2, max=545, avg= 5.45, stdev= 2.88
    clat (usec): min=15, max=697, avg=135.93, stdev=19.58
     lat (usec): min=20, max=700, avg=141.82, stdev=20.37
[etc,etc...]

```

**Comment by peluse** [comment] 2020-01-06 22:25
Just curious if you tried this with vhost and the VM out of the picture?  So just fio in c/s mode w/SPDK on bare metal

**Comment by karlatec** [comment] 2020-01-08 10:42
@peluse TBH - can't remember :) I'm pretty sure I did. Can try again, but I think it will have the same result as doing this scenario inside a VM

**Comment by jimharris** [comment] 2020-01-09 04:18
Bug scrub: @jimharris will take ownership on this - may not get to it until after the 20.01 release though

I just need to build fio from scratch and walk through how it calculates the CRCs to see how the SPDK plugin affects it.

**Comment by jimharris** [comment] 2020-01-16 04:22
[Bug scrub]. This is very likely some kind of bug in the fio plugin.  More investigation still needed.  Marking as low for now since it only affects client/server mode.

**Comment by darsto** [comment] 2020-01-30 16:08
@jimharris Could I take over this?

**Comment by jimharris** [comment] 2020-02-03 14:40
Absolutely!  I'll assign it to you now.

**Comment by darsto** [comment] 2020-02-05 14:53
Reproduced, debugging now.

**Comment by darsto** [comment] 2020-02-05 15:29
The CRC failure occurs on some fio metadata, SPDK fio_plugin doesn't even get to send any I/O before the fio client exits.

Workaround: don't use --daemonize. Looking at the code, this param just makes fio go through an additional fork(). Why this matters? Still looking, although I'm changing this github issue's priority to low

**Comment by darsto** [comment] 2020-02-05 16:19
Daemonized fio does:

```
close(STDIN_FILENO);
close(STDOUT_FILENO);
close(STDERR_FILENO);
```

And then starts opens a few sockets which get assigned fds 0, 1, 2, and so on:
```
$  strace -f ./fio/fio ~/data/spdk/fio_test.fio --eta=never --server --daemonize=/tmp/fio.pid
  461 111780 close(0)                         = 0
  462 111780 close(1)                         = 0
  463 111780 close(2)                         = 0
  464 111780 socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 0
```

FIO tries not to print any messages as a server, but still fails at it:
`111788 write(2, "Loading ioengines so_path=/home/"..., 104) = -1 EBADF (Bad file descriptor)`

Later on it's SPDK's fio_plugin that writes some messages to fd 1 and 2 and server picks it up as a FIO commands.

```
111780 accept(0, {sa_family=AF_INET, sin_port=htons(60632), sin_addr=inet_addr("127.0.0.1")}, [16]) = 1
13101 111877 write(2, "EAL: No available hugepages repo"..., 60) = -1 EBADF (Bad file descriptor)
13111 111877 write(1, "EAL: VFIO support initialized\n", 30) = -1 EPIPE (Broken pipe)
```

Workaround? Open 3 dummy fds before initializing spdk in fio_plugin.

**Comment by darsto** [comment] 2020-02-06 09:13
@karlatec while I'm at it, could you run your tests with the following patch and verify everything works?
https://review.spdk.io/gerrit/c/spdk/spdk/+/575/2

**Comment by darsto** [comment] 2020-02-12 10:08
FIO can sometimes open fd 2 even before loading our fio_plugin, so the patch won't work.

A clean solution here would be to redirect SDPK logs to fio logging function which knows if we're running as a server and can even send the msg to the client. But that doesn't cover DPDK yet, which prints messages locally anyway.

I pushed another revision to exit fio clients with a nice error message "SPDK FIO plugin won't work with daemonized FIO server". That should be good enough for now.

**Comment by darsto** [comment] 2020-02-12 10:09
Closing this for now - supporting fio daemon mode could be an enhancement later on.

**Closed by darsto** 2020-02-12 10:09 UTC
Labels: 3rd party issue, Low, bug

**Comment by jlevon** [comment] 2021-08-16 17:01
> FIO can sometimes open fd 2 even before loading our fio_plugin, so the patch won't work.

We came across this issue. I'm curious when fio would do this?

**Comment by jimharris** [comment] 2021-08-16 17:34
> > FIO can sometimes open fd 2 even before loading our fio_plugin, so the patch won't work.
> 
> We came across this issue. I'm curious when fio would do this?

We only saw that fio would do this if you run it in daemonized mode.  Is that what you are seeing too?

**Comment by jlevon** [comment] 2021-08-16 18:02
I don't think we've seen an fd be open *before* the setup callback, but @antroseco could confirm.

**Comment by antroseco** [comment] 2021-08-31 14:22
FIO now redirects `stdout` and `stderr` to `/dev/null` instead of closing them (see https://github.com/axboe/fio/commit/d6096098275fb0bc4331b40a6d6f6f82d11c7fc1), so daemon mode can be re-enabled (with a version check).

**Comment by jimharris** [comment] 2021-08-31 14:42
> FIO now redirects `stdout` and `stderr` to `/dev/null` instead of closing them (see [axboe/fio@d609609](https://github.com/axboe/fio/commit/d6096098275fb0bc4331b40a6d6f6f82d11c7fc1)), so daemon mode can be re-enabled (with a version check).

Thanks @antroseco!
