### ISSUE TITLE
Jenkins IO exception failure and subsequent missing log

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#652] opened 2019-02-05 18:49 UTC
Exception happened during FreeBSD tests, the local architraves do not include the failure log for some reason but it is available from the console output for the autopatch job

https://10.102.17.104:8080/job/Other_systems/job/freebsd_autotest/14723/

**Comment by peluse** [comment] 2019-02-05 19:11
Some general info on this kind of failure: https://wiki.jenkins.io/display/JENKINS/Remoting+issue

**Comment by darsto** [comment] 2019-02-26 15:37
Bug scrub: First try to provide a descriptive error message rather than 404 on logs. 

For the BSD issue itself - let's reboot the FreeBSD VM after every test - the crash can be caused by subsequent attempts to load/unload the contigmem driver.

**Comment by darsto** [comment] 2019-03-12 15:22
@pawelkax is still working on this

**Comment by karlatec** [comment] 2019-03-26 11:32
@darsto @peluse Patch from @pawelkax was merged, so you should no longer see "404" error when trying to access the missing logs. In case any logs are missing we disable the link and inform about the problem prior to accessing the link.
Closing. @darsto about this freebsd reboot on every patch - I'll create a separate issue for that.

**Closed by karlatec** 2019-03-26 11:32 UTC
Labels: Infrastructure
