### ISSUE TITLE
delete_aio_bdev rpc does not send any reply

### ISSUE THREAD

**Issue by jkryl** [spdk/spdk#604] opened 2019-01-23 08:25 UTC
I'm using delete_aio_bdev rpc method with my own json-rpc client and this particular method unlike others is failing due to closing the connection without sending any reply. json response parser then fails because empty payload is not a valid json.

## Expected Behavior

the method should return valid json-rpc response (defined in json-rpc spec) with additional boolean data (true if aio bdev was successfully deleted, false otherwise)

## Current Behavior

the connection is closed with no data being sent.

## Possible Solution

Not a possible solution but a root cause analysis:

If we look at the code in `lib/bdev/aio/bdev_aio_rpc.c` and scroll all the way down there is a handler for the rpc method (https://github.com/spdk/spdk/blob/master/lib/bdev/aio/bdev_aio_rpc.c#L130). The function starts constructing the json response, however the response is not sent until `_spdk_rpc_delete_aio_bdev_cb` callback is called which happens asynchronously. Before the async callback is called, the connection to client is closed, hence no data are sent later in the callback.

## Steps to Reproduce

I think it can be easily reproduced with any client, but the python json-rpc client in the repo (rpc.py), does not even attempt to parse the response, hence it does not fail. My client implementation closes the connection for writing (from client's POV) right after sending the request to the server. Then it expects to receive reply on half-closed connection. Though there is nothing wrong with this and the server should function correctly in either case.

## Context (Environment including OS version, SPDK version, etc.)

I'm testing with stable version 18.10, however looking at the source code, the same problem appears to be in master (though I haven't verified that).

**Comment by pawelwod** [comment] 2019-01-23 08:46
I think we don't have tests (or any scripts) with half closed connections. Typical flow is that the client is closing connection when response is received. I think the issue is here:
https://github.com/spdk/spdk/blob/master/lib/jsonrpc/jsonrpc_server_tcp.c#L275

Someone writing server side code decided that `recv() == 0` mean that connection is fully closed. This not true, as connection can be half-closed (as you already noted).

I can fix this as already working in this area but it won't happen soon.

For now my advice is to hold connection till you get response.

**Comment by jkryl** [comment] 2019-01-23 12:52
Thanks for your quick response! Based on your comment I have put together a quick fix which works for me, though I haven't tested it thoroughly. There is already `outstanding request count` in json-rpc connection structure so it is quite easy to close the connection only when 1) there are no queued requests and 2) the conn has been closed from the client's side. I'm quoting the diff here just as an inspiration for the final fix:

```
diff --git a/lib/jsonrpc/jsonrpc_internal.h b/lib/jsonrpc/jsonrpc_internal.h
index 87355fdb..1902f855 100644
--- a/lib/jsonrpc/jsonrpc_internal.h
+++ b/lib/jsonrpc/jsonrpc_internal.h
@@ -71,6 +71,7 @@ struct spdk_jsonrpc_server_conn {
        struct spdk_jsonrpc_server *server;
        int sockfd;
        bool closed;
+       bool half_closed;
        struct spdk_json_val values[SPDK_JSONRPC_MAX_VALUES];
        size_t recv_len;
        uint8_t recv_buf[SPDK_JSONRPC_RECV_BUF_SIZE];
diff --git a/lib/jsonrpc/jsonrpc_server_tcp.c b/lib/jsonrpc/jsonrpc_server_tcp.c
index c69d7483..b8212b18 100644
--- a/lib/jsonrpc/jsonrpc_server_tcp.c
+++ b/lib/jsonrpc/jsonrpc_server_tcp.c
@@ -150,6 +150,7 @@ spdk_jsonrpc_server_accept(struct spdk_jsonrpc_server *server)
                conn->server = server;
                conn->sockfd = rc;
                conn->closed = false;
+               conn->half_closed = false;
                conn->recv_len = 0;
                conn->outstanding_requests = 0;
                pthread_spin_init(&conn->queue_lock, PTHREAD_PROCESS_PRIVATE);
@@ -234,7 +235,7 @@ spdk_jsonrpc_server_conn_recv(struct spdk_jsonrpc_server_conn *conn)

        if (rc == 0) {
                SPDK_DEBUGLOG(SPDK_LOG_RPC, "remote closed connection\n");
-               return -1;
+               return 1;
        }

        conn->recv_len += rc;
@@ -383,10 +384,17 @@ spdk_jsonrpc_server_poll(struct spdk_jsonrpc_server *server)
                        continue;
                }

+               if (conn->half_closed) {
+                       if (conn->outstanding_requests == 0) {
+                               spdk_jsonrpc_server_conn_close(conn);
+                       }
+                       continue;
+               }
                rc = spdk_jsonrpc_server_conn_recv(conn);
-               if (rc != 0) {
+               if (rc < 0) {
                        spdk_jsonrpc_server_conn_close(conn);
-                       continue;
+               } else if (rc > 0) {
+                       conn->half_closed = true;
                }
        }
```

**Comment by pawelwod** [comment] 2019-01-23 14:57
@jkryl Thx, I made quick fix from your comment. I can't test it with the half closed connection case. Can you try this patch https://review.gerrithub.io/#/c/spdk/spdk/+/441718/ ?

**Closed as completed** 2019-01-23 22:27 UTC

**Comment by jkryl** [comment] 2019-01-24 12:00
works fine. Thanks for the prompt fix!
