### ISSUE TITLE
Cannot contact WFP8: java.lang.InterruptedException

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#3256] opened 2024-02-08 09:57 UTC
Looks like a problem with CI infra:
```
00:09:50.765   10:09:44	-- common/autotest_common.sh@10 -- # set +x
00:10:11.018  Cannot contact WFP8: java.lang.InterruptedException
00:16:22.799  [Pipeline] }
00:16:22.820  [Pipeline] // stage
00:16:22.827  [Pipeline] }
00:16:22.848  [Pipeline] // timeout
00:16:22.856  [Pipeline] }
00:16:22.859  ERROR: missing workspace /var/jenkins/workspace/nvmf-tcp-phy-autotest on WFP8
00:16:22.876  [Pipeline] // catchError
00:16:22.881  [Pipeline] }
00:16:22.899  [Pipeline] // wrap
00:16:22.905  [Pipeline] }
00:16:22.920  [Pipeline] // catchError
00:16:22.937  [Pipeline] stage
00:16:22.938  [Pipeline] { (Epilogue)
00:16:22.948  [Pipeline] catchError
00:16:22.949  [Pipeline] {
00:16:22.959  [Pipeline] echo
00:16:22.960  Cleanup processes
00:16:22.964  [Pipeline] sh
00:16:23.869  + sudo pgrep -af /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk
00:16:23.869  3847 sudo pgrep -af /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk
00:16:23.888  [Pipeline] sh
00:16:24.187  ++ sudo pgrep -af /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk
00:16:24.187  ++ grep -v 'sudo pgrep'
00:16:24.187  ++ awk '{print $1}'
00:16:24.187  + sudo kill -9
00:16:24.187  + true
00:16:24.201  [Pipeline] sh
00:16:24.495  + jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh
00:16:24.495  /var/jenkins/workspace/nvmf-tcp-phy-autotest_tmp/durable-4277628c/script.sh: line 1: jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh: No such file or directory
```

## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/116926/archive/nvmf-tcp-phy-autotest_63272/build.log
https://ci.spdk.io/public_build/autotest-per-patch_116926.html

**Comment by mikeBashStuff** [comment] 2024-02-08 10:57
This was most likely caused by a power mishap in the lab (several other WFP nodes from the same location got affected too).

**Comment by spdkci** [comment] 2024-02-08 12:59
Another instance of this failure. Reported by @sberbz. log: Not Found

**Comment by mikeBashStuff** [comment] 2024-02-19 08:23
> Almost certainly this was caused by accidental AC disconnection in lab. Lab techs were working on assembling adjacent rack and said that they interrupted AC in at least 1 system in this rack. I already know @mikeBashStuff saw similar issue on his patches, so expecting more intermittent failure reports here.

Confirmed, closing.

**Closed by mikeBashStuff** 2024-02-19 08:23 UTC
Labels: Intermittent Failure
