### ISSUE TITLE
nvmf_shutdown_tc3 gets timeout due to repeated spdk_nvme_qpair_process_completions failure

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1302] opened 2020-03-23 03:52 UTC
https://ci.spdk.io/results/autotest-per-patch/builds/7401/archive/nvmf-tcp-autotest/build.log

**Comment by AlekseyMarchuk** [comment] 2020-03-27 08:18
Repeated spdk_nvme_qpair_process_completions failures were not the cause of timeout, nvmf_shutdown_tc3 test finished in 3 seconds:
```
 04:14:15	# set +x
************************************
START TEST nvmf_shutdown_tc3
************************************
 04:14:15	# xtrace_enable

....

 04:14:18	# set +x
************************************
END TEST nvmf_shutdown_tc3
************************************
 04:14:18	# xtrace_enable
```
The test suite started at 04:11:02 and the last command before timeout was 
```
04:15:09	# /usr/src/fio/fio /var/jenkins/workspace/nvmf-tcp-autotest/spdk/examples/nvme/fio_plugin/mock_sgl_config.fio '--filename=trtype=tcp adrfam=IPv4 traddr=127.0.0.1 trsvcid=4420 ns=1'
test: (g=0): rw=randrw, bs=(R) 16.0KiB-16.0KiB, (W) 16.0KiB-16.0KiB, (T) 16.0KiB-16.0KiB, ioengine=spdk, iodepth=128
fio-3.15
Starting 1 thread
Starting SPDK v20.04-pre git sha1 7a113957f / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid613068 ]
EAL: No available hugepages reported in hugepages-1048576kB
Build timed out (after 15 minutes). Marking the build as failed.
Build was aborted
```
This issue is similar to #1283. I'm closing this one as a duplicate

**Closed by AlekseyMarchuk** 2020-03-27 08:18 UTC
Labels: Intermittent Failure
