### ISSUE TITLE
bdev stuck when IOs are in nomem list

### ISSUE THREAD

**Issue by amirharoush-huawei** [spdk/spdk#3141] opened 2023-09-26 07:06 UTC
# Sighting report

in **bdev.c** which run the IOs for all bdev's, there are special mechanism for IOs returned with **NOMEM** error, we not failing the IO yet, instead we put them in **nomem** list so we can try to re-submit them later (hoping that the memory will be freed and the IO will succeed).
there are some cases when we poll that nomem list to check if we need to re-submit some IOs
the problem is that in some scenarios, none of those cases happens and no one checking this nomem list.
so the IOs in there will **stuck forever** causing the user to wait on an IO forever.
this also happened when running simple bdevperf with queue-depth (QD) 1, and of course we have to inject **SPDK_BDEV_IO_STATUS_NOMEM** error.
this also occur in a real virtio controller attached to QEMU VM on a real scenario (same issue, IOs stuck on nomem list)

## Expected Behavior

bdev must re-submit or fail the IOs in nomem list in all scenarios.

## Current Behavior

IOs stuck in the nomem list forever and will never handled, causing the user to wait on the IO

## Possible Solution

add poller for each bdev and poll this nomem list every 1s (for example)

## Steps to Reproduce

add this **nomem** injection failure
```
diff --git a/lib/bdev/bdev.c b/lib/bdev/bdev.c
index 6ba846959..40705d937 100644
--- a/lib/bdev/bdev.c
+++ b/lib/bdev/bdev.c
@@ -7091,6 +7091,12 @@ spdk_bdev_io_complete(struct spdk_bdev_io *bdev_io, enum spdk_bdev_io_status sta
                            bdev_io_status_get_string(bdev_io->internal.status));
                assert(false);
        }
+    {
+        static uint32_t cnt = 0;
+        cnt++;
+        if (cnt % 11 == 0)
+            status = SPDK_BDEV_IO_STATUS_NOMEM;
+    }
        bdev_io->internal.status = status;
 
        if (spdk_unlikely(bdev_io->type == SPDK_BDEV_IO_TYPE_RESET)) {
```
conf_null_bsl.json
```
{
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "method": "bdev_null_create",
          "params": {
            "name": "frontend",
            "num_blocks": 1048576,
            "block_size": 512
          }
        }
      ]
    }
  ]
}
```
and run the following bdevperf command
`sudo build/examples/bdevperf -q 1 -o 4096 -w read --json path/to/conf_null_bsl.json -S 1 -t 3`

**NOTE** if we use **-q 2** this will not happen, because the 2nd IO will trigger poll to nomem list and release the 1st one.

## Context (Environment including OS version, SPDK version, etc.)

I ran this on this commit, but it will probably will be reproduced on any version.
`8ef5cfc6a - vhost: restart device when memory region changed (16 hours ago) <Changpeng Liu>`

**Comment by apaszkie** [comment] 2023-09-26 07:37
I think that the assumption with SPDK_BDEV_IO_STATUS_NOMEM is that it should be used in case of a lack of resources associated with the current channel. So a situation like this, when there are no outstanding I/Os on the channel and submitting the first one fails with SPDK_BDEV_IO_STATUS_NOMEM is not realistic. It would mean, for example, that a mempool was created with zero elements. In case some external or global resource may be unavailable, I think it should be handled specifically in the bdev module.

**Comment by amirharoush-huawei** [comment] 2023-09-26 07:55
there are more examples of when this can happen.
this error might come from the specific bdev implementation.
for example, when the Q is full it will return NOMEM because he knows that the bdev infra will re-submit it later
this is happens in a real QEMU+VM+VIRTIO situation with normal IOs running inside the VM

**Comment by apaszkie** [comment] 2023-09-26 08:00
Can you provide more details how to reproduce this with qd > 1?

**Comment by amirharoush-huawei** [comment] 2023-09-26 08:03
yes, I can reproduce it with QD=2 (and more), one can use this patch below and run with **-q 2**
```
diff --git a/lib/bdev/bdev.c b/lib/bdev/bdev.c
index 6ba846959..25b715acc 100644
--- a/lib/bdev/bdev.c
+++ b/lib/bdev/bdev.c
@@ -7091,6 +7091,12 @@ spdk_bdev_io_complete(struct spdk_bdev_io *bdev_io, enum spdk_bdev_io_status sta
                            bdev_io_status_get_string(bdev_io->internal.status));
                assert(false);
        }
+    {
+        static uint32_t cnt = 0;
+        cnt++;
+        if (cnt % 11 >= 9)
+            status = SPDK_BDEV_IO_STATUS_NOMEM;
+    }
        bdev_io->internal.status = status;
 
        if (spdk_unlikely(bdev_io->type == SPDK_BDEV_IO_TYPE_RESET)) {
```

**Comment by amirharoush-huawei** [comment] 2023-09-26 08:11
BTW, this error was found in AIO bdev.
in AIO APIs we initialized the AIO context with Q-size.
and if one create many async IOs on that Q, `io_submit` will return `EAGAIN`
in that case, `bdev_aio.c` will call to spdk_bdev_io_complete with SPDK_BDEV_IO_STATUS_NOMEM so the upper layer (i.e. bdev infra) will re-submit it later

**Comment by apaszkie** [comment] 2023-09-26 08:19
> BTW, this error was found in AIO bdev. in AIO APIs we initialized the AIO context with Q-size. and if one create many async IOs on that Q, `io_submit` will return `EAGAIN` in that case, `bdev_aio.c` will call to spdk_bdev_io_complete with SPDK_BDEV_IO_STATUS_NOMEM so the upper layer (i.e. bdev infra) will re-submit it later

This looks like https://github.com/spdk/spdk/issues/3076 which was fixed by https://github.com/spdk/spdk/commit/8cfa8ac42e0f2e19c46fd8ccf8098631d20fb420. Are you still able to reproduce the issue with AIO bdev after that commit?

**Comment by AlekseyMarchuk** [comment] 2023-09-26 09:14
I hit the same issue with some custon block device which has shared resource among all instances. That is possible to get ENOMEM error for the first IO submitted to a channel in that case. All other IOs are put into nomem list too and since there are no IO completions on the channel, all IO are stuck. I fixed it in our fork by creating a poller for this specific case. I can push a patch to review

**Comment by amirharoush-huawei** [comment] 2023-09-26 09:45
It would be great to see your fix
I also fixed it with a poller, I'll try to push a patch as well.

**Comment by amirharoush-huawei** [comment] 2023-09-26 09:46
> > BTW, this error was found in AIO bdev. in AIO APIs we initialized the AIO context with Q-size. and if one create many async IOs on that Q, `io_submit` will return `EAGAIN` in that case, `bdev_aio.c` will call to spdk_bdev_io_complete with SPDK_BDEV_IO_STATUS_NOMEM so the upper layer (i.e. bdev infra) will re-submit it later
> 
> This looks like #3076 which was fixed by [8cfa8ac](https://github.com/spdk/spdk/commit/8cfa8ac42e0f2e19c46fd8ccf8098631d20fb420). Are you still able to reproduce the issue with AIO bdev after that commit?

I'll try to reproduce it with that fix
IMO it will be reproduced because the bounce will not be called in that situation

**Comment by tomzawadzki** [comment] 2023-09-26 15:07
[Community call] @mmkayPL Brought to attention that https://github.com/spdk/spdk/issues/3055 is related to this one.

**Comment by amirharoush-huawei** [comment] 2023-09-26 19:33
@apaszkie I've reproduced the issue with your commit, actually I just noticed that when I was debug the issue your commit was in.

**Comment by AlekseyMarchuk** [comment] 2023-12-06 15:18
Patches merged, closing this issue

**Closed by AlekseyMarchuk** 2023-12-06 15:18 UTC
Labels: bug, Medium, Patches out for review
