### ISSUE TITLE
[Autotest-nightly] Some errors witnessed on nvme_phy_autotest

### ISSUE THREAD

**Issue by ChenBo2333** [spdk/spdk#926] opened 2019-08-23 07:08 UTC
In recent autotest-nightly nvme_phy_autotest's build.log , after using 'make -j48' command , we can see some errors. 

## Expected Behavior
Compile succeessfully without errors.

## Current Behavior
make[3]: *** No rule to make target '/tmp/tmp.WoHFDgCB36/spdk-2019_08_22/build/lib/libspdk_ocfenv.a', needed by '/tmp/tmp.WoHFDgCB36/spdk-2019_08_22/build/lib/libspdk_bdev_ocf.a'.  Stop.
make[3]: *** Waiting for unfinished jobs....
  CC lib/bdev//vbdev_ocf.o
  CC lib/bdev//vbdev_ocf_rpc.o
  CC lib/bdev//volume.o
data.c:34:10: fatal error: ocf/ocf.h: No such file or directory
 #include <ocf/ocf.h>
          ^~~~~~~~~~~
compilation terminated.
make[3]: *** [/tmp/tmp.WoHFDgCB36/spdk-2019_08_22/mk/spdk.common.mk:367: data.o] Error 1
ctx.c:33:10: fatal error: ocf/ocf.h: No such file or directory
 #include <ocf/ocf.h>
          ^~~~~~~~~~~
compilation terminated.
In file included from stats.c:34:
ctx.h:37:10: fatal error: ocf/ocf.h: No such file or directory
 #include <ocf/ocf.h>
          ^~~~~~~~~~~
compilation terminated.
vbdev_ocf.c:34:10: fatal error: ocf/ocf.h: No such file or directory
 #include <ocf/ocf.h>
          ^~~~~~~~~~~
compilation terminated.
make[3]: *** [/tmp/tmp.WoHFDgCB36/spdk-2019_08_22/mk/spdk.common.mk:367: ctx.o] Error 1
make[3]: *** [/tmp/tmp.WoHFDgCB36/spdk-2019_08_22/mk/spdk.common.mk:367: stats.o] Error 1
volume.c:34:10: fatal error: ocf/ocf.h: No such file or directory
 #include <ocf/ocf.h>
          ^~~~~~~~~~~
compilation terminated.
make[3]: *** [/tmp/tmp.WoHFDgCB36/spdk-2019_08_22/mk/spdk.common.mk:367: vbdev_ocf.o] Error 1
In file included from vbdev_ocf_rpc.c:34:
vbdev_ocf.h:37:10: fatal error: ocf/ocf.h: No such file or directory
 #include <ocf/ocf.h>
          ^~~~~~~~~~~
compilation terminated.
make[3]: *** [/tmp/tmp.WoHFDgCB36/spdk-2019_08_22/mk/spdk.common.mk:367: volume.o] Error 1
make[3]: *** [/tmp/tmp.WoHFDgCB36/spdk-2019_08_22/mk/spdk.common.mk:367: vbdev_ocf_rpc.o] Error 1

## Steps to Reproduce
1. view build log on nvme_phy_autotest server,
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/604/archive/nvme_phy_autotest/build.log (search "No rule")

## Context (Environment including OS version, SPDK version, etc.)

**Comment by jimharris** [comment] 2019-08-23 15:11
This is a duplicate of issue #918.

**Closed by jimharris** 2019-08-23 15:11 UTC
