### ISSUE TITLE
CI machines crash randomly

### ISSUE THREAD

**Issue by darsto** [spdk/spdk#729] opened 2019-03-28 09:28 UTC
Some of our test machines randomly get kernel panics and fail the tests. If you're seeing "logs have not been generated" for a specific test, then it's likely caused by such kernel panic.

This is just an information and a placeholder to track this issue.

**Comment by jimharris** [comment] 2019-04-29 22:55
Can we close this issue?  We had the kernel soft lockup issues due to NFS which would hang a test (but not crash the system) - that's been resolved.

I've seen a lot of the Jenkins java.io.IOException issues - but I think those are different.

**Comment by jimharris** [comment] 2019-05-07 02:45
Closing this issue.  @darsto - if we start seeing more of these, we can reopen it.

**Comment by darsto** [comment] 2019-06-04 15:38
Bug scrub: Could it be QEMU crashing?

Seth suggests to check if any physical machines "crash" as well, that would rule out QEMU theory.

I suggest to automatically retrigger the test if it did not generate any logs. For now we can retrigger the entire autotest-per-patch.

**Comment by karlatec** [comment] 2019-06-05 07:20
@darsto I think the initial Github issue was caused by SSH connection drop in Jenkins due to very rapid prints to console log (there was a JIRA issue for that but I can't find it at the moment), but that's not the case anymore after @jimharris "fixed" the NVMe reset test case.

I am pretty sure that now Qemu crashes are the root cause. From servers hosting the VMs:
```
$ dmesg | grep segfault
[70186.519718] CPU 0/KVM[3795]: segfault at 28 ip 0000565253296530 sp 00007f8b54c16638 error 4 in qemu-system-x86_64[565252be9000+aa8000]

# dmesg | grep segfault
[12627.617888] CPU 0/KVM[3563]: segfault at 28 ip 0000558e0a038120 sp 00007f8a81e07638 error 4 in qemu-system-x86_64[558e0998b000+aad000]
[43686.016710] CPU 0/KVM[19508]: segfault at 28 ip 000055a302c92120 sp 00007f694262a638 error 4 in qemu-system-x86_64[55a3025e5000+aad000]
[161080.644685] CPU 0/KVM[52654]: segfault at 28 ip 000055a38a73f120 sp 00007f6ca6cdc638 error 4 in qemu-system-x86_64[55a38a092000+aad000]
```

**Comment by pawelkax** [comment] 2019-06-14 12:04
It looks like vm stop responding at deffirent stage of test execution. We will try to retry such build in sitruation when vm stop responding.

**Comment by jimharris** [comment] 2019-09-24 16:09
Closing this issue.  I'd suggest we open a new issue with more specifics if we see QEMU crashes in the future.

**Closed by jimharris** 2019-09-24 16:09 UTC
Labels: Infrastructure, Intermittent Failure, Medium
