### ISSUE TITLE
Bug for vhost_controller_set_coalescing RPC

### ISSUE THREAD

**Issue by ufo19890607** [spdk/spdk#2135] opened 2021-08-27 09:04 UTC
# Bug report
Hi, guys.  I recently found an obvious bug when testing vhost_controller_set_coalescing RPC.  We hope to reduce the irq costs when enabling this feature, but in fact, set_coalescing RPC will limit spdk to send irqs even if IOPS(req_cnt) does not reach the irq_threshold.  

## Expected Behavior
IOPS for fio test in the VM should not be limited if IOPS does not reach the io_threshold.

## Current Behavior
IO performance is limited even if it does not reach the io_threshold. 

## Bug Location
There are 2 problems that needed to fixed for this RPC.
1. It just counts the io_ops(req_cnt) for only one virtqueue rather than all of them for a certain vhost_blk device.
2. We should count the io_ops for a fixed period(eg. every 10ms) instead of all the io_ops for continuous time.

## Steps to Reproduce
SPDK will meet a serious IO performance regression when enabling
IRQ coalescing feature. We can reproduce this issue by the following
scenario.
	1. create a spdk null/malloc bdev and its vhost_blk_controller.
	2. attach this vhost_blk_controller to a VM.
	3. compare the fio test result in the VM when enabling and disabling IRQ coalescing.
​
NOTE:
	1. just run fio with 1 thread and 1 iodepth to get a lowest IO latency.
	2. create a VM with 16 vcpu and 8GB memory and attach a vhost_blk with 4 virtqueues.
	3. set IRQ coalescing threshold to 400K and delay_us to 500us. I'm sure fio test with 1thread and 1 iodepth in the VM cannot get the IOPS up to 400K.
	./scripts/rpc.py set_vhost_controller_coalescing $vhost_blk_controller 500 400000

Below is the test result that I have conducted.
1. fio result when enabling set_vhost_controller_coalescing (1.png).
![1](https://user-images.githubusercontent.com/10803380/131102233-e32004bd-375f-4cd8-ac0e-b2ea7f8956d1.png)
2. fio result when disabling set_vhost_controller_coalescing (2.png).
![2](https://user-images.githubusercontent.com/10803380/131102290-38ca2d64-2683-40e8-b9ec-3cea9ea46fff.png)

## Context (Environment including OS version, SPDK version, etc.)
Host OS version: centos7.4
VM OS verison： centos7.4 
fio version: any version is OK.
SPDK version: 21.10, upstream newest.

## Fix method
https://review.spdk.io/gerrit/c/spdk/spdk/+/9305

**Comment by changpe1** [comment] 2021-08-30 07:57
https://github.com/spdk/spdk/commit/ff1863f428f9174ab625bcdaa5c0649f3d5b370a#diff-6d59a554ed7cf417e690a668d061c53c198179792fd068474bb94edf9b8f73ae, this is the initial commit which introduced the coalescing feature, so the bug was introduced during the code refactoring.

I'm OK to restore the code to the original implementation, but I think it would be nice just removed the IOPS setting,  very high jitter when enabling this setting.

**Comment by changpe1** [comment] 2021-08-30 08:01
For 1) it's a bug, for 2) maybe a more robust algorithm is required, existing implementation is very easy, and also cause high jitter in practice.

**Comment by ufo19890607** [comment] 2021-08-30 08:13
> [ff1863f#diff-6d59a554ed7cf417e690a668d061c53c198179792fd068474bb94edf9b8f73ae](https://github.com/spdk/spdk/commit/ff1863f428f9174ab625bcdaa5c0649f3d5b370a#diff-6d59a554ed7cf417e690a668d061c53c198179792fd068474bb94edf9b8f73ae), this is the initial commit which introduced the coalescing feature, so the bug was introduced during the code refactoring.
> 
> I'm OK to restore the code to the original implementation, but I think it would be nice just removed the IOPS setting, very high jitter when enabling this setting.

Hi ChangPeng,
This bug has existed since  vhost_controller_set_coalescing  feature was merged, rather than the code refactoring. It's just that it is easy to fix the bug with the earlier code. 

>  think it would be nice just removed the IOPS setting, very high jitter when enabling this setting.
I do not get your point?

**Comment by ufo19890607** [comment] 2021-08-30 08:27
> For 1) it's a bug, for 2) maybe a more robust algorithm is required, existing implementation is very easy, and also cause high jitter in practice.

I think existing implementation for vdev_worker is good, but session_vq_io_stats_update and session_vq_io_stats_update should handle all the virtqueue of a target spdk_vhost_session. Or else we will miss io requests on other virtqueues.

**Comment by jimharris** [comment] 2021-08-30 14:43
Hi,

This feature was always intended to only operate on a per queue basis.  I'm concerned about doing this at a device level for a couple of reasons:

1) if VM has 2 queues, 1 is heavily loaded with background I/O and 1 with high priority latency sensitive I/O, then enabling coalescing at device level will impact the latency sensitive queue unnecessarily
2) in the future, especially for vhost-blk, we may want to process queues from the same session on different cores - when every call to vhost_session_vq_used_signal has to iterate through all of the virtqueues this will become more costly

I am mostly concerned about #1.

I do agree there are some changes needed on how the I/Os are counted to determine when to enable the coalescing.  We should do that separately from changing the coalescing from a per-queue to per-device level.

-Jim

**Comment by ufo19890607** [comment] 2021-08-31 03:49
Hi Jim
> 1. if VM has 2 queues, 1 is heavily loaded with background I/O and 1 with high priority latency sensitive I/O, then enabling coalescing at device level will impact the latency sensitive queue unnecessarily.

I've done a simple test: run 2 VMs and each one has a certain vhost_blk target with NVMe. One VM runs fio with heavy workload and the other runs fio with latency sensitive workload.  I open coalescing  for heavy loaded vhost_blk target, but  fio with latency sensitive workload runs normal.  I think vhost_controller_set_coalescing  RPC is intended to limite IO speed on a vhost_blk target  rather than a certain queue of it. 

> 2. in the future, especially for vhost-blk, we may want to process queues from the same session on different cores - when every call to vhost_session_vq_used_signal has to iterate through all of the virtqueues this will become more costly.

We have implemented this feature(process queues from the same session on different cores), we call it Multi-queue IO dispersion. And we do not modify the code for vhost_controller_set_coalescing, just as you said,  vhost_session_vq_used_signal has to iterate through all of the virtqueues for a device. But I do not find any significant performance regression when enabling vhost_controller_set_coalescing.  I think check_session_vq_io_stats is not a time-comsuming operation, it just do collect req_cnt for all the virtqueues. 

Thanks Wind

**Comment by jimharris** [comment] 2021-08-31 18:22
> Hi Jim
> 
> > 1. if VM has 2 queues, 1 is heavily loaded with background I/O and 1 with high priority latency sensitive I/O, then enabling coalescing at device level will impact the latency sensitive queue unnecessarily.
> 
> I've done a simple test: run 2 VMs and each one has a certain vhost_blk target with NVMe. One VM runs fio with heavy workload and the other runs fio with latency sensitive workload. I open coalescing for heavy loaded vhost_blk target, but fio with latency sensitive workload runs normal. I think vhost_controller_set_coalescing RPC is intended to limite IO speed on a vhost_blk target rather than a certain queue of it.

Hi Wind,

Could you provide more details on this test?  If the IRQ delay is set to 500us, and the NVMe latency for a random read is 100us, then if coalescing gets enabled for the latency-sensitive queue, it would certainly experience a performance delay, since the interrupts would be delayed much longer than the media latency.

-Jim

**Comment by ufo19890607** [comment] 2021-09-01 03:49
Hi Jim
Below is the steps I conducted.
1. Create 2 VMs that has its 16 vcpus 32G memory and its own vhost_blk target(Intel P4510 NVMe) with 4 virtqueues.
```
# VM 1
qemu-system-x86_64 
     .......
    -chardev socket,id=drive-virtio-disk5,path=/var/run/spdk/vhost_blk_socket-5911f9f2-f462-41e0-bb92-d3baa4a8b5b0-nvme,reconnect=10 
    -device vhost-user-blk-pci,chardev=drive-virtio-disk5,num-queues=4,bus=pci.0,addr=0x5,id=virtio-disk5
     ........
# VM 2
qemu-system-x86_64 
    .........
    -chardev socket,id=drive-virtio-disk5,path=/var/run/spdk/vhost_blk_socket-272869e5-3721-463e-9d5b-d7ab22f7fbf7-nvme,reconnect=10 
    -device vhost-user-blk-pci,chardev=drive-virtio-disk5,num-queues=4,bus=pci.0,addr=0x5,id=virtio-disk5
   .........
```
2. Enable coalescing feature for the second VM
```
./scripts/rpc.py set_vhost_controller_coalescing vhost_blk_socket-272869e5-3721-463e-9d5b-d7ab22f7fbf7-nvme 500 400000
```
3. Run latency sensitive workload on the first VM and run heavy workload on the second VM.
```
# VM1 fio config, Note I run fio with 1 thread and 1 iodpeth using sequence read method to simulate latency sensitive workload
[global]  
ioengine=libaio
direct=1
thread=0
norandommap=1  
randrepeat=0  
group_reporting   
log_avg_msec=1
rw=read
percentile_list=60:65:70:75:76:77:78:79:80:85:90:95:96:97:98:99:99.50:99.90:99.95:99.99
iomem_align=4096
bs=4k
numjobs=1
iodepth=1
group_reporting=1  
time_based  
runtime=60
size=4000g

[testfile1]
filename=/dev/vdb

# VM2 fio config.  Note I run fio with 8 threads and 128 iodpeth using randread method to simulate heavy workload. 
[global]
ioengine=libaio
direct=1
thread=0
norandommap=1
randrepeat=0
group_reporting
log_avg_msec=10
rw=randread
iomem_align=4096
bs=4k
numjobs=8
iodepth=128
group_reporting=1
percentile_list=60:65:70:75:76:77:78:79:80:85:90:95:96:97:98:99:99.50:99.90:99.95:99.99
time_based
runtime=60
size=4000G

[testfile1]
filename=/dev/vdb
```
4. Disable coalescing feature for the second VM
```
./scripts/rpc.py set_vhost_controller_coalescing vhost_blk_socket-272869e5-3721-463e-9d5b-d7ab22f7fbf7-nvme 0 60000
```
5. Re-run test for step 3.

The result of  latency sensitive workload is below.
1. enabling coalescing
```
testfile1: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
fio-3.7
Starting 1 process
Jobs: 1 (f=1): [r(1)][100.0%][r=214MiB/s,w=0KiB/s][r=54.7k,w=0 IOPS][eta 00m:00s]
testfile1: (groupid=0, jobs=1): err= 0: pid=3096: Wed Sep  1 11:21:01 2021
   read: IOPS=53.3k, BW=208MiB/s (218MB/s)(6245MiB/30001msec)
    slat (nsec): min=2274, max=188220, avg=3034.41, stdev=641.76
    clat (nsec): min=955, max=2133.1k, avg=13462.82, stdev=3177.19
     lat (usec): min=12, max=2137, avg=17.00, stdev= 3.33
    clat percentiles (nsec):
     | 60.00th=[13504], 65.00th=[13632], 70.00th=[13760], 75.00th=[13888],
     | 76.00th=[13888], 77.00th=[13888], 78.00th=[14016], 79.00th=[14016],
     | 80.00th=[14144], 85.00th=[14400], 90.00th=[14912], 95.00th=[15296],
     | 96.00th=[15424], 97.00th=[15552], 98.00th=[15808], 99.00th=[17792],
     | 99.50th=[19328], 99.90th=[21632], 99.95th=[22400], 99.99th=[38144]
   bw (  KiB/s): min=189248, max=231048, per=99.93%, avg=213017.49, stdev=9795.99, samples=59
   iops        : min=47312, max=57762, avg=53254.37, stdev=2449.00, samples=59
  lat (nsec)   : 1000=0.01%
  lat (usec)   : 2=0.01%, 4=0.01%, 10=0.12%, 20=99.53%, 50=0.33%
  lat (usec)   : 100=0.01%, 250=0.01%, 500=0.01%, 750=0.01%
  lat (msec)   : 2=0.01%, 4=0.01%
  cpu          : usr=10.41%, sys=42.29%, ctx=1598615, majf=0, minf=37
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=1598792,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=208MiB/s (218MB/s), 208MiB/s-208MiB/s (218MB/s-218MB/s), io=6245MiB (6549MB), run=30001-30001msec

Disk stats (read/write):
  vdb: ios=1592972/0, merge=0/0, ticks=16356/0, in_queue=16069, util=53.59%
```
2. disabling coalescing
```
testfile1: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
fio-3.7
Starting 1 process
Jobs: 1 (f=1): [r(1)][100.0%][r=215MiB/s,w=0KiB/s][r=54.9k,w=0 IOPS][eta 00m:00s]
testfile1: (groupid=0, jobs=1): err= 0: pid=3305: Wed Sep  1 11:23:33 2021
   read: IOPS=52.9k, BW=207MiB/s (217MB/s)(6203MiB/30001msec)
    slat (nsec): min=2268, max=39127, avg=3192.29, stdev=607.59
    clat (nsec): min=941, max=203779, avg=13347.34, stdev=1234.39
     lat (usec): min=12, max=207, avg=17.06, stdev= 1.54
    clat percentiles (nsec):
     | 60.00th=[13504], 65.00th=[13632], 70.00th=[13632], 75.00th=[13760],
     | 76.00th=[13760], 77.00th=[13760], 78.00th=[13760], 79.00th=[13760],
     | 80.00th=[13760], 85.00th=[13888], 90.00th=[14144], 95.00th=[14400],
     | 96.00th=[14656], 97.00th=[14912], 98.00th=[15296], 99.00th=[17024],
     | 99.50th=[19072], 99.90th=[20864], 99.95th=[21632], 99.99th=[46848]
   bw (  KiB/s): min=199080, max=229336, per=99.78%, avg=211255.92, stdev=6490.53, samples=59
   iops        : min=49770, max=57334, avg=52814.00, stdev=1622.58, samples=59
  lat (nsec)   : 1000=0.01%
  lat (usec)   : 2=0.01%, 4=0.01%, 10=0.16%, 20=99.60%, 50=0.22%
  lat (usec)   : 100=0.01%, 250=0.01%
  cpu          : usr=10.63%, sys=42.51%, ctx=1587636, majf=0, minf=36
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=1587900,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=207MiB/s (217MB/s), 207MiB/s-207MiB/s (217MB/s-217MB/s), io=6203MiB (6504MB), run=30001-30001msec

Disk stats (read/write):
  vdb: ios=1581771/0, merge=0/0, ticks=19432/0, in_queue=19151, util=63.86%
```
3. the result for heavy workload is almost same.
```
testfile1: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=128
...
fio-3.7
Starting 8 processes
Jobs: 8 (f=8): [r(8)][100.0%][r=2553MiB/s,w=0KiB/s][r=654k,w=0 IOPS][eta 00m:00s]
testfile1: (groupid=0, jobs=8): err= 0: pid=1729: Wed Sep  1 11:23:33 2021
   read: IOPS=649k, BW=2534MiB/s (2657MB/s)(74.2GiB/30001msec)
    slat (usec): min=2, max=25047, avg= 8.17, stdev=113.83
    clat (usec): min=79, max=35580, avg=1567.49, stdev=1603.10
     lat (usec): min=197, max=35583, avg=1576.25, stdev=1610.01
    clat percentiles (usec):
     | 60.00th=[ 1188], 65.00th=[ 1254], 70.00th=[ 1336], 75.00th=[ 1467],
     | 76.00th=[ 1500], 77.00th=[ 1532], 78.00th=[ 1582], 79.00th=[ 1631],
     | 80.00th=[ 1680], 85.00th=[ 2040], 90.00th=[ 2638], 95.00th=[ 4080],
     | 96.00th=[ 4621], 97.00th=[ 5473], 98.00th=[ 6456], 99.00th=[ 9503],
     | 99.50th=[13042], 99.90th=[15795], 99.95th=[17957], 99.99th=[22938]
   bw (  KiB/s): min=67920, max=533437, per=12.50%, avg=324293.80, stdev=80800.18, samples=474
   iops        : min=16980, max=133359, avg=81073.36, stdev=20200.04, samples=474
  lat (usec)   : 100=0.01%, 250=0.01%, 500=0.01%, 750=3.10%, 1000=36.07%
  lat (msec)   : 2=45.39%, 4=10.24%, 10=4.29%, 20=0.89%, 50=0.02%
  cpu          : usr=16.94%, sys=63.67%, ctx=221703, majf=0, minf=1310
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwts: total=19460740,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=128

Run status group 0 (all jobs):
   READ: bw=2534MiB/s (2657MB/s), 2534MiB/s-2534MiB/s (2657MB/s-2657MB/s), io=74.2GiB (79.7GB), run=30001-30001msec

Disk stats (read/write):
  vdb: ios=19393135/0, merge=0/0, ticks=9750549/0, in_queue=9914283, util=100.00%
```

VM OS kernel version : 3.10.0-1127.13.1.el7.x86_64
Host OS kernel verseion : 3.10.0-693

Thanks Wind

**Comment by ufo19890607** [comment] 2021-09-01 04:03
We can see that enabling coalescing does not make the sensitive latency worse.

**Comment by changpe1** [comment] 2021-09-01 05:12
Thanks @ufo19890607 .  There is one comment from me(latest one), otherwise it's OK.

**Comment by changpe1** [comment] 2021-09-01 06:15
@jimharris I think we should remove the IOPS limitation in vhost, it doesn't make sense to add delayed response in this way, if users wanted to limit each VM's IOPS, they can use the QoS feature in the bdev layer.  The coalescing feature can take effect when `used_req_cnt` hit a threshold e.g: 50% of the queue depth or every 10 ms set by users.  What do you think?

**Comment by dong-liuliu** [comment] 2021-09-02 06:41
Coalescing is one optimization for high concurrent workload. Worse latency for lighten workload is the side-effect of coalescing.
So it met expectation, was not a bug.

**Comment by ufo19890607** [comment] 2021-09-02 06:55
@dong-liuliu @changpe1 
Hi, dong, I don't think so. If enabling coalescing has to effect latency sensitive workload, we cannot use this feature any more.  Besides, We still want to use this feature with IOPS limtation. Actually, I still do not find any bad effects with my fixed patch. 
Thanks, Wind.

**Comment by ufo19890607** [comment] 2021-09-07 02:54
ping~

**Comment by jimharris** [comment] 2021-09-08 23:43
The reason this RPC was added was to help the case where one vCPU was receiving too many interrupts from the vhost backend and wasting CPU cycles.  The vCPU would get an interrupt, schedule some completion processing, then while that completion processing was happening, it would get another interrupt.  This significantly reduced the amount of time the vCPU could do that actual completion processing.  So we added the RPC to throttle the interrupt rate to reduce the number of interrupts.  This in turn boosted the I/O throughput of that vCPU.  Since this was on a per queue basis, it meant that another vCPU that had a much lower I/O rate would not be affected.

So the better test would be differentiating the I/O workload between multiple vCPUs/virtqueues in the same VM.

Another way to put it is that if the coalescing is set to 500us, and we apply the coalescing to a vCPU/virtqueue that does not need it, it could unnecessarily delay completion of I/O on that vCPU/virtqueue up to 500us.

The most important part is knowing the correct parameters to use when enabling the coalescing.  If the IO/s rate is set to low, and/or the IRQ delay time is set too high, it will definitely decrease performance.  Some tuning is required.  Note that these performance effects happen whether the coalescing is done on a per-queue or per-device basis.

**Comment by ufo19890607** [comment] 2021-09-09 12:02
Hi, Jim
It sounds like that coalescing feature can be used only on per-queue basis rather than multi-queue basis.  But most of vhost_blk targets in the cloud environment are equipped with muti-queue, so I think limiting the number of interrupts for vhost-blks using coalescing will be a mainstream demand. 

What was worse,  just as you said, if the IO/s rate is set to low, and/or the IRQ delay time is set too high, it will definitely decrease performance even if IOPS does not reach the threshold.   I think this feature can be used for IO test rather than the real production environment.

BTW, I still don't know why my solution cannot be used.

**Comment by jimharris** [comment] 2021-09-09 17:15
Hi Wind,

Coalescing will still work with multi-queue virtio devices.  For example, if the virtio device has 4 virtqueues, and each virtqueue exceeds the IO/s rate specified by the RPC, then coalescing will be enabled for every virtqueue.

It would be better not to add a second coalescing RPC that is per-device.  The existing per-queue RPC should be sufficient.  If there is a specific workload or configuration where you see the per-queue RPC is not working, let's discuss that here and make any necessary adjustments to the existing RPC.

I would suggest maybe changing your tests to use a smaller IRQ delay value.  500us is pretty high - it means you'll effectively get a max 2K interrupts/second which could definitely hurt performance.  If you are running high queue depth workloads in your VM with coalescing disabled, what kind of interrupt rate are you seeing in the VM?

-Jim

**Comment by ufo19890607** [comment] 2021-09-11 04:36
Hi Jim,
> if the virtio device has 4 virtqueues, and each virtqueue exceeds the IO/s rate specified by the RPC, then coalescing will be enabled for every virtqueue.

We have different opinions for this point. I think coalescing is used to limit the IO threshold for a whole device rather than each virtqueue. 

> It would be better not to add a second coalescing RPC that is per-device. The existing per-queue RPC should be sufficient. If there is a specific workload or configuration where you see the per-queue RPC is not working, let's discuss that here and make any necessary adjustments to the existing RPC.

I do need an coalescing RPC that is per-device in the cloud environment. SPDK should not limit the IOPS for a vhost-blk target when users run some sensitive IO workload in the VM, but if users want to get the highest IOPS for each NVMe device, SPDK can reduce the time cost for sending interrupts for VMs though coalescing RPC. According to our experience, we can get the extreme performance(630K IOPS for one NVMe and 1260K for 2 NVMe) when setting the irq coalescing for each vhost-blk target with 500us delay and 400 000 IOPS threshold. Well, maybe we can also get the best performance using SPDK with upstream version even if we disable coalescing,  but it does not make sence to upgrade SPDK to the newest version for our tens of thousands of server clusters. So we need this kind of coalescing RPC.

>  If you are running high queue depth workloads in your VM with coalescing disabled, what kind of interrupt rate are you seeing in the VM?

There are more interrupts in the VM when disabling coalescing. And we can just get 500K IOPS for one NVMe and 1000K for two of them.

Thanks Wind.

**Comment by ufo19890607** [comment] 2021-09-30 03:35
PING

**Comment by jimharris** [comment] 2021-10-04 17:40
> Hi Jim,
> 
> > if the virtio device has 4 virtqueues, and each virtqueue exceeds the IO/s rate specified by the RPC, then coalescing will be enabled for every virtqueue.
> 
> We have different opinions for this point. I think coalescing is used to limit the IO threshold for a whole device rather than each virtqueue.
> 
> > It would be better not to add a second coalescing RPC that is per-device. The existing per-queue RPC should be sufficient. If there is a specific workload or configuration where you see the per-queue RPC is not working, let's discuss that here and make any necessary adjustments to the existing RPC.
> 
> I do need an coalescing RPC that is per-device in the cloud environment. SPDK should not limit the IOPS for a vhost-blk target when users run some sensitive IO workload in the VM, but if users want to get the highest IOPS for each NVMe device, SPDK can reduce the time cost for sending interrupts for VMs though coalescing RPC. According to our experience, we can get the extreme performance(630K IOPS for one NVMe and 1260K for 2 NVMe) when setting the irq coalescing for each vhost-blk target with 500us delay and 400 000 IOPS threshold. Well, maybe we can also get the best performance using SPDK with upstream version even if we disable coalescing, but it does not make sence to upgrade SPDK to the newest version for our tens of thousands of server clusters. So we need this kind of coalescing RPC.

If you have 4 virtqueues, then you can set the IOPs threshold to 100K IOPs.  This basically has the same effect as if you have a per-device coalescing RPC set with a 400K IOPs limit.

The per-queue coalescing has been in place for a long time, so we cannot simply change it to per-device.  So the question is really if we need a per-device coalescing RPC.  In the examples you've shown above, it seems you can just use the existing RPC, with per-queue IOPs threshold of 100K IOPs and 500us delay and get the same effects as if a per-device RPC was added.

-Jim

**Comment by jimharris** [comment] 2022-01-28 23:37
Closing this issue.  It seems the existing RPC can be used to still obtain the effects of the original request for a per-device coalescing RPC.

**Closed by jimharris** 2022-01-28 23:37 UTC
Labels: Sighting
