### ISSUE TITLE
Nvme of rdma host CQ error

### ISSUE THREAD

**Issue by dashan8020** [spdk/spdk#961] opened 2019-09-18 02:25 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

no error happen
## Current Behavior

CQ error, log as below, it is a RDMA local protection error
it seems that SPDK Nvme Host has some issue to handle RDMA PD or memory register.

issue LOG:
mlx5: ogden-rust.west.isilon.com: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
000000b3 00000000 00000000 00000000
00000000 93005204 0a0019a1 c0921cd2
nvme_rdma.c:1748:nvme_rdma_qpair_process_completions: *ERROR*: CQ error on Queue Pair 0x7efd94490ac0, Opcode 128, Response Index 139627583889688 (4): local protection error
nvme_qpair.c: 453:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded

## Possible Solution

no
## Steps to Reproduce

1.run nvme host with kernel target for several hours with IO
2.
3.
4.

**Comment by Comphix** [comment] 2019-09-18 02:32
@dashan8020 could you give more details on the testing environment like OS, kernel, NVMe-oF target configuration, NVMe-oF host configuration, testing method. This will help us to reproduce this issue first to better understand. Thanks, Gang

**Comment by yidong0635** [comment] 2019-09-18 07:05
append error explanation here:
`This event is generated when a user attempts to access an address outside of the registered memory region. For example, this may happen if the lkey does not match the address in the WR.`

**Comment by changpe1** [comment] 2019-09-19 04:09
[Bug Scrub] Can you provide more information about how to reproduce this issue?

**Comment by AlekseyMarchuk** [comment] 2019-09-24 09:36
Could you also provide information about OFED version and NIC model?

**Comment by jimharris** [comment] 2019-09-24 15:17
Bug scrub 09/24: Duplicate of #964?  @gwnet @dashan8020 are these the same issue?

**Closed** 2019-10-17 14:13 UTC
