### ISSUE TITLE
Intermitent test failure on vhost hotremove test

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#843] opened 2019-07-01 11:55 UTC
See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Most of daily vhost-hotremove tests on jenkins are failing.

## Expected Behavior
Test should finish with success.

## Current Behavior
Test are failing very often.

## Possible Solution
None

## Steps to Reproduce
1. Run:
 a. spdk/test/vhost/manual.sh -shr
 b. spdk/test/vhost/manual.sh -bhr

## Context (Environment including OS version, SPDK version, etc.)
VM with fedora28

**Comment by tomzawadzki** [comment] 2019-07-02 15:19
Bug scrub: @pawelkax will attach dmesg logs

**Comment by darsto** [comment] 2019-07-08 07:07
There's nothing interesting in the logs. @pawelkax could you try to reproduce this with https://review.gerrithub.io/c/spdk/spdk/+/447060 ? Those tests were passing few months ago, but since we haven't merged them I would be curious if they pass now.

**Comment by pawelkax** [comment] 2019-07-08 09:09
Logs that I noticed on VM:
[2174254.023583] WARNING: CPU: 1 PID: 0 at /build/linux-fQ94TU/linux-4.4.0/net/sched/sch_generic.c:306 dev_watchdog+0x23d/0x250()
[2174254.023584] NETDEV WATCHDOG: ens3 (e1000): transmit queue 0 timed out
[2174254.023585] Modules linked in: rpcsec_gss_krb5 auth_rpcgss nfsv4 nfs lockd grace fscache snd_hda_codec_generic snd_hda_intel snd_hda_codec snd_hda_core snd_hwdep ppdev snd_pcm snd_timer snd soundcore parport_pc input_leds joydev parport 8250_fintek serio_raw i2c_piix4 mac_hid ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi sunrpc autofs4 btrfs raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear 8139too hid_generic usbhid hid crct10dif_pclmul crc32_pclmul ghash_clmulni_intel qxl ttm aesni_intel drm_kms_helper aes_x86_64 syscopyarea lrw gf128mul sysfillrect glue_helper sysimgblt ablk_helper fb_sys_fops cryptd 8139cp psmouse drm mii e1000 pata_acpi floppy
[2174254.023620] CPU: 1 PID: 0 Comm: swapper/1 Not tainted 4.4.0-116-generic #140-Ubuntu
[2174254.023621] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.10.2-1.fc26 04/01/2014
[2174254.023623]  0000000000000286 dd7c226563686024 ffff88043fc43d98 ffffffff813ffc13
[2174254.023624]  ffff88043fc43de0 ffffffff81d73198 ffff88043fc43dd0 ffffffff810830f2
[2174254.023626]  0000000000000000 ffff880427350280 0000000000000001 ffff8804261c8000
[2174254.023627] Call Trace:
[2174254.023628]  <IRQ>  [<ffffffff813ffc13>] dump_stack+0x63/0x90
[2174254.023634]  [<ffffffff810830f2>] warn_slowpath_common+0x82/0xc0
[2174254.023636]  [<ffffffff8108318c>] warn_slowpath_fmt+0x5c/0x80
[2174254.023638]  [<ffffffff817694fd>] dev_watchdog+0x23d/0x250
[2174254.023639]  [<ffffffff817692c0>] ? qdisc_rcu_free+0x40/0x40
[2174254.023641]  [<ffffffff810ef897>] call_timer_fn+0x37/0x130
[2174254.023642]  [<ffffffff817692c0>] ? qdisc_rcu_free+0x40/0x40
[2174254.023644]  [<ffffffff810f025d>] run_timer_softirq+0x23d/0x2f0
[2174254.023646]  [<ffffffff81087c16>] __do_softirq+0x106/0x2a0
[2174254.023647]  [<ffffffff81087f23>] irq_exit+0xa3/0xb0
[2174254.023650]  [<ffffffff818525f8>] smp_apic_timer_interrupt+0x48/0x60
[2174254.023651]  [<ffffffff8184ff7f>] apic_timer_interrupt+0xbf/0xd0
[2174254.023652]  <EOI>  [<ffffffff81038fe0>] ? idle_notifier_unregister+0x20/0x20
[2174254.023656]  [<ffffffff810656d6>] ? native_safe_halt+0x6/0x10
[2174254.023658]  [<ffffffff81038ffe>] default_idle+0x1e/0xe0
[2174254.023659]  [<ffffffff81039875>] arch_cpu_idle+0x15/0x20
[2174254.023662]  [<ffffffff810c6cca>] default_idle_call+0x2a/0x40
[2174254.023664]  [<ffffffff810c7037>] cpu_startup_entry+0x2f7/0x350
[2174254.023666]  [<ffffffff81052562>] start_secondary+0x172/0x1b0
[2174254.023667] ---[ end trace c9e0b0d11815e521 ]---
[2174254.023679] e1000 0000:00:03.0 ens3: Reset adapter
[2174256.084111] e1000: ens3 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[2249547.402313] EXT4-fs (vdb): error count since last fsck: 176
[2249547.402322] EXT4-fs (vdb): initial error at time 1545456318: ext4_lookup:1601: inode 5505038
[2249547.402325] EXT4-fs (vdb): last error at time 1545510320: ext4_lookup:1601: inode 5505028
[2336056.857271] EXT4-fs (vdb): error count since last fsck: 176
[2336056.857306] EXT4-fs (vdb): initial error at time 1545456318: ext4_lookup:1601: inode 5505038
[2336056.857317] EXT4-fs (vdb): last error at time 1545510320: ext4_lookup:1601: inode 5505028
[2422566.484381] EXT4-fs (vdb): error count since last fsck: 176
[2422566.484394] EXT4-fs (vdb): initial error at time 1545456318: ext4_lookup:1601: inode 5505038
[2422566.484398] EXT4-fs (vdb): last error at time 1545510320: ext4_lookup:1601: inode 5505028
but Darek said they are useless.
I will try to reproduce this issue locally with patch 447060.

**Comment by pawelkax** [comment] 2019-07-23 12:23
Cannot get useful errors on VM when it freezes. Need talk to Darek how to debug this issue.

**Comment by pawelkax** [comment] 2019-08-02 13:21
On VM that freezed I noticed follwing errors:
[   64.276031] NMI watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [systemd-udevd:959]
[   68.696031] INFO: rcu_sched detected stalls on CPUs/tasks:
[   68.696031]  0-...: (0 ticks this GP) idle=099/140000000000000/0 softirq=2548/2548 fqs=0
[   68.696031]  (detected by 1, t=15002 jiffies, g=367, c=366, q=559)
[   68.696031] rcu_sched kthread starved for 15002 jiffies! g367 c366 f0x0 s3 ->state=0x1
[   96.276031] NMI watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [systemd-udevd:959]
[  124.276033] NMI watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [systemd-udevd:959]
[  152.276033] NMI watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [systemd-udevd:959]
[  180.276031] NMI watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [systemd-udevd:959]

**Comment by darsto** [comment] 2019-08-05 08:32
The last dmesg looks suspicious, but in general we can't get any more detailed logs from the VM side. Have you tried reproducing it with the patch I linked before? https://review.gerrithub.io/c/spdk/spdk/+/447060

**Comment by pawelkax** [comment] 2019-08-06 09:27
@darsto I tried to reproduce this issue with 447060 but with no effect (tests passed).

**Comment by pawelkax** [comment] 2019-08-14 12:56
Hi,
I changed qemu version from 2.11.2 to 3.0.0 and also I changed kernel for ubuntu 16.04 to version 4.19. It helped. But now I get following error:
Begin: Will now check root file system ... fsck from util-linux 2.27.1
[/sbin/fsck.ext4 (1) -- /dev/sda1] fsck.ext4 -a -C0 /dev/sda1 
/dev/sda1: clean, 129147/196608 files, 537811/785920 blocks
done.
[   57.940841] EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
done.
Begin: Running /scripts/local-bottom ... done.
Begin: Running /scripts/init-bottom ... done.
[   59.704931] general protection fault: 0000 [#1] SMP PTI
[   59.705015] CPU: 0 PID: 1 Comm: systemd Not tainted 4.19.0-041900-generic #201810221809
[   59.705015] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.11.2-0-gf9626ccb91-prebuilt.qemu-project.org 04/01/2014
[   59.705015] RIP: 0010:__kmalloc_track_caller+0xaf/0x220
[   59.705015] Code: 79 62 49 83 78 10 00 4d 8b 38 0f 84 03 01 00 00 4d 85 ff 0f 84 fa 00 00 00 41 8b 59 20 49 8b 39 48 8d 4a 01 4c 89 f8 4c 01 fb <48> 33 1b 49 33 99 38 01 00 00 65 48 0f c7 0f 0f 94 c0 84 c0 74 b2
[   59.705015] RSP: 0018:ffffb696801979f0 EFLAGS: 00010202
[   59.705015] RAX: 2d1aa67ed2ce6cc4 RBX: 2d1aa67ed2ce6cc4 RCX: 000000000000510c
[   59.705015] RDX: 000000000000510b RSI: 00000000006000c0 RDI: 0000000000028080
[   59.705015] RBP: ffffb69680197a28 R08: ffff8d11bea28080 R09: ffff8d11be403980
[   59.705015] R10: 8080808080808080 R11: 0000000000000018 R12: 00000000006000c0
[   59.705015] R13: 0000000000000012 R14: ffff8d11be403980 R15: 2d1aa67ed2ce6cc4
[   59.705015] FS:  00007fd1e89078c0(0000) GS:ffff8d11bea00000(0000) knlGS:0000000000000000
[   59.705015] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   59.705015] CR2: 000055f6a4ecd088 CR3: 000000003d004002 CR4: 0000000000760ef0
[   59.705015] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[   59.705015] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[   59.705015] PKRU: 55555554
[   59.705015] Call Trace:
[   59.705015]  ? kstrdup_const+0x24/0x30
[   59.705015]  kstrdup+0x31/0x60
[   59.705015]  kstrdup_const+0x24/0x30
[   59.705015]  __kernfs_new_node+0x48/0x1d0
[   59.705015]  ? __radix_tree_replace+0x9a/0x120
[   59.705015]  kernfs_new_node+0x26/0x50
[   59.705015]  __kernfs_create_file+0x34/0xc0
[   59.705015]  cgroup_addrm_files+0x141/0x340
[   59.705015]  ? radix_tree_iter_tag_clear+0x1c/0x20
[   59.705015]  ? idr_alloc_u32+0xc0/0xf0
[   59.705015]  ? _cond_resched+0x19/0x30
[   59.705015]  ? kmem_cache_alloc_trace+0x1c8/0x1e0
[   59.705015]  css_populate_dir+0x11f/0x140
[   59.705015]  cgroup_setup_root+0x15b/0x300
[   59.705015]  cgroup1_mount+0x17e/0x46f
[   59.705015]  cgroup_mount+0x9e/0x370
[   59.705015]  ? alloc_pages_current+0x81/0xe0
[   59.705015]  mount_fs+0x3d/0x155
[   59.705015]  vfs_kern_mount.part.37+0x5d/0x110
[   59.705015]  do_mount+0x213/0xcf0
[   59.705015]  ksys_mount+0xbf/0xe0
[   59.705015]  __x64_sys_mount+0x25/0x30
[   59.705015]  do_syscall_64+0x5a/0x110
[   59.705015]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[   59.705015] RIP: 0033:0x7fd1e6f02b5a
[   59.705015] Code: 48 8b 0d 41 c3 2b 00 f7 d8 64 89 01 48 83 c8 ff c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 49 89 ca b8 a5 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 0e c3 2b 00 f7 d8 64 89 01 48
[   59.705015] RSP: 002b:00007ffc32498488 EFLAGS: 00000246 ORIG_RAX: 00000000000000a5
[   59.705015] RAX: ffffffffffffffda RBX: 00007ffc324984c0 RCX: 00007fd1e6f02b5a
[   59.705015] RDX: 000055f6a4b9a7a7 RSI: 000055f6a4ec3790 RDI: 000055f6a4b9a7a7
[   59.705015] RBP: 00000000fffffffe R08: 000055f6a4ec52a0 R09: 0000000000000001
[   59.705015] R10: 000000000000000e R11: 0000000000000246 R12: 0000000000000001
[   59.705015] R13: 000055f6a4ec5380 R14: 000055f6a4ec3790 R15: 0000000000000000
[   59.705015] Modules linked in: autofs4 btrfs zstd_compress raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear crct10dif_pclmul crc32_pclmul ghash_clmulni_intel pcbc aesni_intel aes_x86_64 crypto_simd ide_pci_generic piix cryptd glue_helper psmouse floppy virtio_scsi e1000 ide_core pata_acpi
[   59.997132] ---[ end trace 49ba4a227a380e4d ]---

**Comment by pawelkax** [comment] 2019-08-27 14:41
On Test Pool we upgraded Ubuntu 16.06 with kernel 4.4 to kernel 4.19. It works now.

**Closed** 2019-08-27 14:41 UTC
Labels: Intermittent Failure, Medium, bug
