### ISSUE TITLE
Intermitten failure: Build timeout but test not started

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#1045] opened 2019-11-08 19:19 UTC
Log to this failure:
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/49288/archive/centos7_autotest/build.log

**Comment by spdkci** [comment] 2019-11-08 19:20
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49288.html

**Comment by jimharris** [comment] 2019-11-14 04:29
Bug scrub: this looks like a duplicate of #1007

**Closed by jimharris** 2019-11-14 04:29 UTC
Labels: Intermittent Failure
