### ISSUE TITLE
spdk.io website font changed when clicking "DOCUMENTATION" and then "CI STATUS"

### ISSUE THREAD

**Issue by wanqunintel** [spdk/spdk#556] opened 2018-12-24 05:47 UTC
Go to spdk.io webpage
1. When clicking "DOCUMENTATION" button, it shows as follows
![image](https://user-images.githubusercontent.com/18566118/50391635-54b80600-0782-11e9-89d8-ed16b9830269.png)
2. Then clicking "CI STATUS" button, it shows as follows
![image](https://user-images.githubusercontent.com/18566118/50391642-626d8b80-0782-11e9-8a08-b541903eb7d5.png)

It expect to have the same sytle or font of words for both Buttons.

**Comment by Comphix** [comment] 2018-12-28 08:12
@wanqunintel , what internet explorer are you using? Seems on the IE (v11) and Google chrome (v71), this issue is not seen. First click "DOCUMENTATION", then click "CI STATUS".

Thanks, Gang

**Comment by wanqunintel** [comment] 2019-01-03 03:16
@Comphix , i am using Version 71.0.3578.98 (Official Build) (64-bit) for Google Chrome, i tried on my IE(v11.846) and no issue, but i retested on latest Google Chrome Version 71.0.3578.98 (Official Build) (64-bit) ,it still happens when first click "DOCUMENTATION", then click "CI STATUS".

**Comment by Seth5141** [comment] 2019-01-03 17:50
@wanqunintel, @Comphix It looks like the second link that @wanqunintel provided is from ci.spdk.io and not spdk.io/ci. It is possible that there is a difference between these two sites (spdk.io and ci.spdk.io) since they are served from two different places and the sources for both of them are controlled separately. I looked at the source between the two pages, and the only difference I could find between the two headers was a line related to viewport scaling in ci.spdk.io. I removed that line from ci.spdk.io. Please let me know if that fixed the issue for you (as I cannot reproduce it locally).

**Comment by Comphix** [comment] 2019-01-21 07:56
@wanqunintel , could have another try after Seth's change. Thanks.

**Comment by benlwalker** [comment] 2019-01-23 19:42
Fixed, so closing issue.

**Closed by benlwalker** 2019-01-23 19:42 UTC
Labels: Medium, bug
