### ISSUE TITLE
Cannot contact agt-r_autotest_XXXX-YYYY: hudson.remoting.RequestAbortedException

### ISSUE THREAD

**Issue by ehaligow** [spdk/spdk#3114] opened 2023-08-31 14:11 UTC
# CI Intermittent Failure

```
00:06:50.006    LINK nvme_quirks_ut
00:06:50.643    LINK perf
00:06:50.643    CC test/unit/lib/util/crc32_ieee.c/crc32_ieee_ut.o
00:06:55.620    LINK scsi_pr_ut
00:06:57.846    LINK pci_event_ut
00:06:59.156    LINK init_grp_ut
00:06:59.914    LINK cpuset_ut
00:07:06.172  Cannot contact agt-r_autotest_4630-17008: hudson.remoting.RequestAbortedException: java.nio.channels.ClosedChannelException
00:19:19.532  Cancelling nested steps due to timeout
00:19:19.532  Could not connect to agt-r_autotest_4630-17008 to send interrupt signal to process
00:19:19.538  [Pipeline] }
00:19:19.559  [Pipeline] // timeout
00:19:19.566  [Pipeline] }
[...]
00:24:45.120  Processing file module/vfu_device/vfu_virtio_rpc.c
00:24:45.120  Processing file xnvme/include/libxnvme.h
00:24:45.120  Writing directory view page.
00:24:45.120  Overall coverage rate:
00:24:45.120    lines......: 36.1% (39636 of 109651 lines)
00:24:45.120    functions..: 39.3% (3559 of 9062 functions)
00:24:45.120   11:38:17	-- unit/unittest.sh@301 -- # set +x
00:24:45.120  
00:24:45.120  
00:24:45.120  =====================
00:24:45.120  All unit tests passed
00:24:45.120  =====================
00:24:45.120  Note: coverage report is here: /var/jenkins/workspace/unittest-main-docker-autotest/spdk//var/jenkins/workspace/unittest-main-docker-autotest/spdk/../output/ut_coverage
00:24:45.120  
00:24:45.120  
00:24:45.129  [Pipeline] }
00:24:45.148  [Pipeline] // timeout
00:24:45.154  [Pipeline] }
00:24:45.171  [Pipeline] // stage
00:24:45.175  [Pipeline] }
00:24:45.192  [Pipeline] // catchError
```

**Comment by spdkci** [comment] 2023-08-31 17:31
Another instance of this failure. Reported by @ehaligow. log: https://ci.spdk.io/public_build/autotest-per-patch_108536.html

**Comment by spdkci** [comment] 2023-09-01 08:43
Another instance of this failure. Reported by @slawekptak. log: https://ci.spdk.io/public_build/autotest-per-patch_108529.html

**Comment by spdkci** [comment] 2023-09-01 08:44
Another instance of this failure. Reported by @slawekptak. log: https://ci.spdk.io/public_build/autotest-per-patch_108532.html

**Comment by spdkci** [comment] 2023-09-13 12:22
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_109586.html

**Comment by spdkci** [comment] 2023-09-19 09:50
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_110061.html

**Comment by spdkci** [comment] 2023-09-19 10:09
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_110060.html

**Comment by spdkci** [comment] 2023-09-20 09:51
Another instance of this failure. Reported by @tomzawadzki. log: Not Found

**Comment by spdkci** [comment] 2023-09-21 11:30
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_110065.html

**Comment by spdkci** [comment] 2023-10-17 07:24
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_111113.html

**Comment by mikeBashStuff** [comment] 2023-10-17 07:29
[The ](https://github.com/spdk/spdk/issues/3114#issuecomment-1765820608) - this was probably caused by my own jenkins that I wanted to connect to swarm for  a quick test (and then of course I forgot to disconnect it).

**Comment by tomzawadzki** [comment] 2023-10-17 15:39
[Bug scrub] Besides the last report, prior occurrence was ~month ago. The job retries the container if the connection times out, so it might be possibly covered up in passing builds. The connecting issue is not related to SPDK tests most likely, but to the environment. Let's just make sure that this does not occur way more often than we see reports here. If not, then its fine to close.

**Comment by spdkci** [comment] 2023-11-06 08:14
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_111885.html

**Comment by jimharris** [comment] 2023-12-19 15:24
Looks like this was an intermittent CI issue, closing.

**Closed by jimharris** 2023-12-19 15:24 UTC
Labels: Infrastructure
