### ISSUE TITLE
When in IO test, blobstore creating a snapshot will cause an assertion error in assert(ctx->extent_page != 0) 

### ISSUE THREAD

**Issue by yanjiawei2** [spdk/spdk#3113] opened 2023-08-31 12:06 UTC
# Sighting report

The exchange of cluster_map is involved in creating a snapshot, which will cause an assertion error in assert(ctx->extent_page != 0) when copying and assigning a cluster when writing

## Expected Behavior

no coredump

## Current Behavior

assert error or may write error data to extent page 0

## Possible Solution

add an blob flag not doing swap cluster map in allocating cluster and extent page

## Steps to Reproduce

1. build with debug version ./configure --enable-debug
2. create an lvstore and lv
3. export the lv by iscsi_target and continuous IO on it
4. make some lvol_snapshot, it will assert failed in blob_insert_cluster_msg->assert(ctx->extent_page != 0);

## Context (Environment including OS version, SPDK version, etc.)
centos 8
current SPDK version

**Comment by arsiesys** [comment] 2024-03-25 14:20
Hi,

I just reproduced the exact same issue:
1) Create lvstore then lvol, connect it using rdma then running an intensive fio:
```fio --ioengine=libaio --bs=4k  --name=test --filename=/dev/nvme3n1 --rw=write  --direct=1 --numjobs=10 --iodepth=128```
2) Stop the fio
3) I created a first snapshot without fio running, ok
4) I create a second snapshot with fio running and I got the same crash as mentioned in the first post.

The next time I try to start spdk_tgt, once the disk hosting the lvstore is examined:
```
[2024-03-25 14:16:55.674791] blobstore.c:4728:bs_recover: *NOTICE*: Performing recovery on blobstore
[2024-03-25 14:16:55.674909] blobstore.c:4675:bs_load_replay_md_cpl: *NOTICE*: Recover: blob 0x0
[2024-03-25 14:16:55.674983] blobstore.c:4675:bs_load_replay_md_cpl: *NOTICE*: Recover: blob 0x1
[2024-03-25 14:16:55.675549] blobstore.c:4675:bs_load_replay_md_cpl: *NOTICE*: Recover: blob 0x34
[2024-03-25 14:16:55.678999] blobstore.c:4675:bs_load_replay_md_cpl: *NOTICE*: Recover: blob 0x67
[2024-03-25 14:16:55.679319] blobstore.c:4675:bs_load_replay_md_cpl: *NOTICE*: Recover: blob 0x6a
nvmf_tgt: blobstore.c:3437: blob_get_snapshot_and_clone_entries: Assertion `*clone_entry != NULL' failed.
Aborted (core dumped)
```

Spdk: 1895dabc3be431aae1abb523df3ce4326e8fb763

**Comment by arsiesys** [comment] 2024-03-25 14:39
Extra information, I may have understand better how to reproduce it.
It seems that, if I run consecutive snapshot while the fio is running doesn't create issue. However, if I stop the fio, and restart from the begining of the device and do a snap at that moment, then, I instantly crash.

So, it seems to crash while I run a snapshot while there is copy on write operations ?

**Comment by ksztyber** [comment] 2024-09-03 15:12
[Bug scrub] @jchachux could you test this according to the steps provided by @arsiesys?

**Comment by jchachux** [comment] 2024-09-10 14:55
@arsiesys 
We have been testing with @mikeBashStuff the scenario described, but we haven't been able to reproduce the crash. Tried on Rocky and Fedora.

It might be helpful to get more detailed information from your end. Could you provide a step-by-step breakdown, including specific commands from the build, setup, and actions leading up to the crash? This would give us a better chance of identifying the issue.

**Comment by arsiesys** [comment] 2024-09-11 23:53
Hi !

Since then my setup changed a lot. I do not seems to be able to reproduce anymore. I even tried to rollback to the same commit I used previously x_x.

**Comment by jimharris** [comment] 2024-09-12 00:36
> Hi !
> 
> Since then my setup changed a lot. I do not seems to be able to reproduce anymore. I even tried to rollback to the same commit I used previously x_x.

I'm closing the issue. @arsiesys, if you run into this again or are able to provide help on reproduction, please reopen.

Thanks,

Jim

**Closed by jimharris** 2024-09-12 00:36 UTC
Labels: Sighting
