### ISSUE TITLE
nvmf_nmic tests fails to access /dev/nvme-fabrics device

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1530] opened 2020-08-04 14:32 UTC
https://ci.spdk.io/results/autotest-per-patch/builds/23659/archive/nvmf-phy-autotest/build.log

Point of failure:
```
00:04:32.164  test case2: host connect to nvmf target in multiple paths
00:04:32.164   15:57:44	# '[' -n 192.168.100.9 ']'
00:04:32.164   15:57:44	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.9 -s 4420
00:04:32.353  [2020-08-04 15:57:44.842262] rdma.c:2677:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 192.168.100.9 port 4420 ***
00:04:32.364   15:57:44	# nvme connect -t rdma -n nqn.2016-06.io.spdk:cnode1 -a 192.168.100.8 -s 4420
00:04:32.870   15:57:45	# nvme connect -t rdma -n nqn.2016-06.io.spdk:cnode1 -a 192.168.100.9 -s 4420
00:04:32.894  Failed to write to /dev/nvme-fabrics: Invalid argument
00:04:32.894    15:57:45	# trap - ERR
00:04:32.894    15:57:45	# print_backtrace
00:04:32.894    15:57:45	# [[ ehxBET =~ e ]]
00:04:32.894    15:57:45	# args=("${BASH_ARGV[@]}")
00:04:32.894    15:57:45	# local args
00:04:32.894    15:57:45	# xtrace_disable
00:04:32.895    15:57:45	# '[' no '!=' yes ']'
00:04:32.895    15:57:45	# PREV_BASH_OPTS=ehxBET
00:04:32.895    15:57:45	# [[ ehxBET == *\x* ]]
00:04:32.895    15:57:45	# XTRACE_DISABLED=yes
00:04:32.895    15:57:45	# set +x
00:04:32.895  ========== Backtrace start: ==========
00:04:32.895  
00:04:32.903  in test/nvmf/target/nmic.sh:45 -> main(["--transport=rdma"])
00:04:32.903       ...
00:04:32.903     40  	echo "test case2: host connect to nvmf target in multiple paths"
00:04:32.903     41  	if [ -n "$NVMF_SECOND_TARGET_IP" ]; then
00:04:32.903     42  		$rpc_py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a $NVMF_SECOND_TARGET_IP -s $NVMF_PORT
00:04:32.903     43  	
00:04:32.903     44  		nvme connect -t $TEST_TRANSPORT -n "nqn.2016-06.io.spdk:cnode1" -a "$NVMF_FIRST_TARGET_IP" -s "$NVMF_PORT"
00:04:32.903  => 45  		nvme connect -t $TEST_TRANSPORT -n "nqn.2016-06.io.spdk:cnode1" -a "$NVMF_SECOND_TARGET_IP" -s "$NVMF_PORT"
00:04:32.903     46  	
00:04:32.903     47  		waitforserial "$NVMF_SERIAL"
00:04:32.903     48  	
00:04:32.903     49  		$rootdir/scripts/fio.py -p nvmf -i 4096 -d 1 -t write -r 1 -v
00:04:32.903     50  	fi
00:04:32.903       ...
00:04:32.903  
00:04:32.903  ========== Backtrace end ==========
```

**Comment by spdkci** [comment] 2020-08-04 14:33
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_23659.html

**Comment by changpe1** [comment] 2020-08-06 00:33
Here is the error log from kernel dmesg.log:

[ 3623.476490] nvme nvme1: rdma_connect failed (-22).
[ 3623.484720] nvme nvme1: rdma connection establishment failed (-22)

**Comment by Seth5141** [comment] 2020-08-06 18:06
duplicate of issue #1297

**Closed by Seth5141** 2020-08-06 18:06 UTC
Labels: Intermittent Failure, Sighting
