### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by Hansyangxingxiang** [spdk/spdk#2639] opened 2022-08-16 09:31 UTC
# Bug report

## Current Behavior
root@testr01n01:~/spdk# ./scripts/pkgdep.sh
/root/spdk/scripts/pkgdep/ubuntu.sh: line 1: debian.sh: command not found
Error!
root@testr01n01:~/spdk# ./configure
Notice: ISA-L, compression & crypto require NASM version 2.14 or newer. Turning off default ISA-L and crypto features.
Using default SPDK env in /root/spdk/lib/env_dpdk
Using default DPDK in /root/spdk/dpdk/build
Creating mk/config.mk...done.
Creating mk/cc.flags.mk...done.
Type 'make' to build.
root@testr01n01:~/spdk# make
Error during basic setup:

[Errno 2] No such file or directory: '/root/spdk/dpdk/build-tmp'
Makefile:171: recipe for target '/root/spdk/dpdk/build-tmp' failed
make[1]: *** [/root/spdk/dpdk/build-tmp] Error 1
/root/spdk/mk/spdk.subdirs.mk:16: recipe for target 'dpdkbuild' failed
make: *** [dpdkbuild] Error 2

## Steps to Reproduce

git clone https://github.com/spdk/spdk
cd spdk
git submodule update --init
scripts/pkgdep.sh
./configure
make

## Context (Environment including OS version, SPDK version, etc.)

root@testr01n01:~/spdk# cat /etc/issue
Ubuntu 16.04.5.3 LTS \n \l

root@testr01n01:~/spdk#

root@testr01n01:~/spdk# git branch
* master
root@testr01n01:~/spdk#

**Comment by mikeBashStuff** [comment] 2022-08-16 10:09
I can't really reproduce this - I quickly checked under `16.04.7` image and `pkgdep` doesn't fail like it does in the description. That said, our scripts don't provide support for xenial anymore (we test only the 18.04 and 20.04 releases for now), hence it's likely they won't be able to fully provision this particular version of the distro which already reached it's EOL.

**Comment by jimharris** [comment] 2022-08-16 17:32
> I can't really reproduce this - I quickly checked under `16.04.7` image and `pkgdep` doesn't fail like it does in the description. That said, our scripts don't provide support for xenial anymore (we test only the 18.04 and 20.04 releases for now), hence it's likely they won't be able to fully provision this particular version of the distro which already reached it's EOL.

Yeah, the build obviously failed because pkgdep.sh didn't work.

@Hansyangxingxiang, is there anything else abnormal about your environment?  This line is very confusing to me:

```
/root/spdk/scripts/pkgdep/ubuntu.sh: line 1: debian.sh: command not found
```

ubuntu.sh is not actually a script, it is a symlink to debian.sh.

**Comment by jimharris** [comment] 2022-08-16 20:56
> @Hansyangxingxiang, is there anything else abnormal about your environment? This line is very confusing to me:
> 
> ```
> /root/spdk/scripts/pkgdep/ubuntu.sh: line 1: debian.sh: command not found
> ```
> 
> ubuntu.sh is not actually a script, it is a symlink to debian.sh.

So git actually just puts the name of the target file in the object for the symlink, but then with type information to indicate it is a symlink and not just text.  That explains the "command not found" error at some level.

But it's still not clear why in the filesystem it is not a symlink.  Unless you have core.symlinks = false in your git config?  That would result in ubuntu.sh getting created as a file with just a single line "debian.sh" instead of an actual symlink to debian.sh.

If I set core.symlinks = false in my .gitconfig, do a fresh clone, and then run scripts/pkgdep.sh, I get this exact same error.

**Comment by Hansyangxingxiang** [comment] 2022-08-17 03:55
I git cloned on the window, and then copied to Linux
$ git config --list |grep core.symlinks
core.symlinks=false

$ git clone -c core.symlinks=true https://github.com/spdk/spdk                  Cloning into 'spdk'...
remote: Enumerating objects: 160204, done.
remote: Counting objects: 100% (1365/1365), done.
remote: Compressing objects: 100% (716/716), done.
remote: Total 160204 (delta 782), reused 1116 (delta 645), pack-reused 158839
Receiving objects: 100% (160204/160204), 69.11 MiB | 8.52 MiB/s, done.
Resolving deltas: 100% (125304/125304), done.
error: unable to create symlink scripts/pkgdep/centos.sh: Permission denied
error: unable to create symlink scripts/pkgdep/fedora.sh: Permission denied
error: unable to create symlink scripts/pkgdep/ubuntu.sh: Permission denied
error: unable to create symlink test/common/config/pkgdep/os/centos: Permission denied
error: unable to create symlink test/common/config/pkgdep/os/debian: Permission denied
error: unable to create symlink test/common/config/pkgdep/os/fedora: Permission denied
error: unable to create symlink test/external_code/hello_world/hello_bdev.c: Permission denied
error: unable to create symlink test/rpc_plugins/rpc_plugin.py: Permission denied
error: unable to create symlink test/rpc_plugins/scheduler_plugin.py: Permission denied
Updating files: 100% (1732/1732), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

I have solved it by direct git clone on Linux

**Comment by jimharris** [comment] 2022-08-17 04:05
Thanks for the update @Hansyangxingxiang.  Closing this issue now.

**Closed by jimharris** 2022-08-17 04:05 UTC
Labels: Waiting on Submitter
