### ISSUE TITLE
nvme bdev module segfaults if NVMe-oF TCP target becomes initially unreachable, then reachable again

### ISSUE THREAD

**Issue by jonathan-teh** [spdk/spdk#1716] opened 2020-12-08 18:03 UTC
When using the nvme bdev module configured to abort on timeout with an NVMf TCP target, if the target becomes unreachable and the initiator (i.e. the nvme bdev) tries to reset the controller at least twice, then once the target becomes reachable again the initiator crashes with a segfault (or assertion failure in a debug build).

## Expected Behavior

The application using nvme bdev should continue running.

## Current Behavior

The application using nvme bdev crashes with a segfault (or assertion failure in a debug build).

## Possible Solution

Unknown.

## Steps to Reproduce

This can be reproduced with `bdevperf` as the application using the nvme bdev and `nvmf_tgt` as the NVMf target. The nvme bdev module is configured to abort on timeout with a timeout of 10s and a KATO of 5s.
I've attached [spdkjson.zip](https://github.com/spdk/spdk/files/5660905/spdkjson.zip) containing the JSON files for the SPDK apps. SPDK is built with the `--enable-debug` option.

1. Run the NVMf target:
```
$ sudo ./build/bin/nvmf_tgt -c ./nvmft.json
[2020-12-08 17:28:29.755593] Starting SPDK v21.01-pre git sha1 46a348597 / DPDK 20.08.0 initialization...
[2020-12-08 17:28:29.755719] [ DPDK EAL parameters: [2020-12-08 17:28:29.755744] nvmf [2020-12-08 17:28:29.755761] --no-shconf [2020-12-08 17:28:29.755777] -c 0x1 [2020-12-08 17:28:29.755793] --log-level=lib.eal:6 [2020-12-08 17:28:29.755810] --log-level=lib.cryptodev:5 [2020-12-08 17:28:29.755826] --log-level=user1:6 [2020-12-08 17:28:29.755842] --iova-mode=pa [2020-12-08 17:28:29.755858] --base-virtaddr=0x200000000000 [2020-12-08 17:28:29.755874] --match-allocations [2020-12-08 17:28:29.755889] --file-prefix=spdk_pid71145 [2020-12-08 17:28:29.755905] ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No legacy callbacks, legacy socket not created
[2020-12-08 17:28:29.885629] app.c: 466:spdk_app_start: *NOTICE*: Total cores available: 1
[2020-12-08 17:28:30.045308] reactor.c: 699:reactor_run: *NOTICE*: Reactor started on core 0
[2020-12-08 17:28:30.061653] accel_engine.c: 692:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2020-12-08 17:28:30.194364] tcp.c: 532:nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
[2020-12-08 17:28:30.214221] tcp.c: 721:nvmf_tcp_listen: *NOTICE*: *** NVMe/TCP Target Listening on 127.0.0.1 port 4420 ***
```
2. Run `bdevperf` as a user of the nvme bdev module:
```
$ sudo test/bdev/bdevperf/bdevperf --json ./bdperf.json -q 128 -o 4096 -w randread -m 0x8 -t 300
[2020-12-08 17:30:03.524014] Starting SPDK v21.01-pre git sha1 46a348597 / DPDK 20.08.0 initialization...
[2020-12-08 17:30:03.524134] [ DPDK EAL parameters: [2020-12-08 17:30:03.524167] bdevperf [2020-12-08 17:30:03.524195] --no-shconf [2020-12-08 17:30:03.524223] -c 0x8 [2020-12-08 17:30:03.524249] --log-level=lib.eal:6 [2020-12-08 17:30:03.524276] --log-level=lib.cryptodev:5 [2020-12-08 17:30:03.524303] --log-level=user1:6 [2020-12-08 17:30:03.524329] --iova-mode=pa [2020-12-08 17:30:03.524354] --base-virtaddr=0x200000000000 [2020-12-08 17:30:03.524380] --match-allocations [2020-12-08 17:30:03.524406] --file-prefix=spdk_pid71201 [2020-12-08 17:30:03.524433] ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No legacy callbacks, legacy socket not created
[2020-12-08 17:30:03.653899] app.c: 466:spdk_app_start: *NOTICE*: Total cores available: 1
[2020-12-08 17:30:03.803519] reactor.c: 699:reactor_run: *NOTICE*: Reactor started on core 3
[2020-12-08 17:30:03.819812] accel_engine.c: 692:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
Running I/O for 300 seconds...
```
3. Send `SIGSTOP` to `nvmf_tgt`, or use Ctrl-Z.
4. Wait for `bdevperf` to log at least 2 timeout warnings:
```
[2020-12-08 17:30:18.900306] bdev_nvme.c:1232:timeout_cb: *WARNING*: Warning: Detected a timeout. ctrlr=0x55becd2d0920 qpair=(nil) cid=2
[2020-12-08 17:30:23.897586] bdev_nvme.c:1232:timeout_cb: *WARNING*: Warning: Detected a timeout. ctrlr=0x55becd2d0920 qpair=(nil) cid=0
```
5. Send `SIGCONT` to `nvmf_tgt`.
6. `bdevperf` notes that a reset is already in progress, then fails an assertion:
```
[2020-12-08 17:30:25.788369] bdev_nvme.c: 493:_bdev_nvme_reset: *NOTICE*: Unable to perform reset, already in progress.
bdevperf: nvme_tcp.c:1552: nvme_tcp_qpair_check_timeout: Assertion `tcp_req->req != NULL' failed.
Aborted
```
In a release build, a "Segmentation fault" is the result.

## Context (Environment including OS version, SPDK version, etc.)

Ubuntu 20.04, kernel 5.4.0-56-generic
SPDK git revision 46a34859 (originally observed on 20.10)

**Comment by jimharris** [comment] 2020-12-09 21:35
I've reproduced this locally.  Debugging now.

(Fantastic repo steps by the way...)

**Comment by jimharris** [comment] 2020-12-10 00:13
https://review.spdk.io/gerrit/c/spdk/spdk/+/5513

Root cause starts with the KATO command timing out.  Currently when we get a timeout, we try to read CSTS to see if CFS (Controller Fatal Status) bit is set.  But if you do that when you get a fabrics admin command timeout, you're now submitting another fabrics admin command and recursively checking for admin cmd completions and timeouts.  So this patch only tries to read CSTS if the timed out command is associated with a PCIe controller or a fabrics I/O queue.

Note that this means we will now reset the controller when we get the timeout on the KATO command.  This will fail all of the outstanding I/O and cause bdevperf to exit.

I also tested this same scenario, with the fix, in the nvmf_tgt itself.  Started target #1 as specified above.  Started target #2 with same settings as applied to bdevperf (KATO, abort, 10s timeout) and creates a subsystem backed by the subsystem from target #1.  Then started bdevperf against target #2.  Paused target #1 and see timeouts in target #2, but everything keeps running and once target #1 is resumed we see all of the I/O pick back up in bdevperf.

Incidentally, found a small bug in the JSON generation in the bdev_nvme module while debugging this.  There's a patch to fix it in the same series as the patch linked above.

**Comment by jonathan-teh** [comment] 2020-12-10 11:30
Thanks for the fix, I can confirm that the controller is now reset when the timeout occurs.

**Comment by tomzawadzki** [comment] 2020-12-15 12:19
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/5513 fixing this issue was merged.

**Closed by tomzawadzki** 2020-12-15 12:19 UTC
Labels: Sighting
