### ISSUE TITLE
bdev_null_create with metadata error

### ISSUE THREAD

**Issue by slawekptak** [spdk/spdk#3194] opened 2023-11-17 10:40 UTC
# Sighting report

The following RPC fails:
./scripts/rpc.py bdev_null_create Test 100 512 -m 8 -t 1

with an error message:
response:
{
  "code": -22,
  "message": "Data block size 512 is not a multiple of 512"
}

## Expected Behavior

Similar to bdev malloc, the null bdev should be created with the block size = 512 + 8.

## Current Behavior

bdev_null_create fails. If the block size provided covers the metadata (e.g. 520) it succeeds.

**Comment by mikeBashStuff** [comment] 2023-11-17 10:46
isn't that a duplicate of #3191?

**Comment by ksztyber** [comment] 2023-11-17 11:08
@slawekptak, is this about aligning block_size/md_size in bdev_malloc_create/bdev_null_create RPCs? If so, then I think @mikeBashStuff is right and it is a duplicate and @changpe1 already said he'll take care of it. I'm going to close the issue, please re-open if there's something more to this issue.

**Closed by ksztyber** 2023-11-17 11:08 UTC
Labels: Sighting
