### ISSUE TITLE
nvme device with 0 default namespace

### ISSUE THREAD

**Issue by jparairo** [spdk/spdk#466] opened 2018-10-18 23:30 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

no error

## Current Behavior

nvme_ctrlr.c: 906:nvme_ctrlr_identify_active_ns: *ERROR*: Failed to allocate active_ns_list!
nvme.c: 423:nvme_init_controllers: *ERROR*: Failed to initialize SSD: 0000:64:00.0
spdk_nvme_probe() failed

## Possible Solution

in the meantime, I added 

        if (nn == 0) {
            SPDK_WARNLOG("Controller has 0 namespaces\n");
            return 0;
        }

outside "if (nn != ctrlr->num_ns)" condition and see if it cause some issues down the line.

## Steps to Reproduce

1. NVMe device without namespace
2. 
3.
4.

## Context (Environment including OS version, SPDK version, etc.)

SPDK ver 18.07
Ubuntu 16.04.4 LTS kernel 4.4.0-116-generic

**Comment by jimharris** [comment] 2018-10-18 23:52
Hi @jparairo,

I've walked through the nvme_ctrlr.c state machine - I think everything there is fine, but I don't have a setup available with a 0 namespace controller at the moment.

But lib/bdev/nvme/bdev_nvme.c looks suspect.  Both create_ctrlr() and nvme_ctrlr_create_bdevs() will bail early if the ctrlr has no namespaces.

Is this something you'd be interested in looking into further?  I would also like to know if this issue occurs on latest master as well.  I suspect you should see the same behavior but would be good to confirm.

-Jim

**Comment by jparairo** [comment] 2018-10-19 01:35
hi @jimharris,

Yes, it's the same behavior as the master.

I tried running hello_world, identify, and nvme_manage in the ./examples/nvme using Intel SSD:
**Model Number:                          INTEL SSDPE2MX400G4**

and always during nvme_ctrlr_construct_namespaces, before if (nn != ctrlr->num_ns),
ctrlr->cdata.nn = 1
ctrlr->num_ns = 0

running the same tests with a  device that has NO namespace,
ctrlr->cdata.nn = 0
ctrlr->num_ns = 0

thus bypassing the checking of "if (nn==0)" and goes to proceed with nvme_ctrlr_update_namespaces without a valid namespace. This is where I think the failure happens.

your thoughts?

-joevanni

**Comment by dong-liuliu** [comment] 2018-10-29 23:37
@jimharris , @jparairo  
Let me try it with a D3600 device later to confirm and then fix the problem~

**Comment by dong-liuliu** [comment] 2018-10-29 23:39
Or add some change to QEMU nvme part to verify it

**Comment by dong-liuliu** [comment] 2018-11-01 19:47
@jparairo 
Raised one patch set to fix the problem caused by 0 namespace.
https://review.gerrithub.io/c/spdk/spdk/+/431701 

Even one controller has no namespace, it still can be retained inside SPDK app.
With this patch set, it can be verifeid by:
./scripts/rpc.py get_nvme_controllers

**Comment by jparairo** [comment] 2018-11-03 02:00
I am still getting the same error.

I would like to add that I am not using NVMof. I am developing an application for a NVMe character device, thus with no namespace. 

From what i've read, part of every application should have spdk_nvme_probe for NVMe enumeration process... This is here where I am getting the error...

> Initializing NVMe Controllers
> EAL: PCI device 0000:64:00.0 on NUMA socket 0
> EAL:   probe driver: 192a:7 spdk_nvme
> Attaching to 0000:64:00.0
> nvme_ctrlr.c: 925:nvme_ctrlr_identify_active_ns: *ERROR*: Failed to allocate active_ns_list!
> nvme.c: 423:nvme_init_controllers: *ERROR*: Failed to initialize SSD: 0000:64:00.0
> spdk_nvme_probe() failed

**Comment by jparairo** [comment] 2018-11-05 22:32
@jimharris 

in the master branch, during nvme_ctrlr_process_init, when namespace is 0,  should we just bypass NVME_CTRLR_STATE_IDENTIFY_ACTIVE_NS state and go directly to NVME_CTRLR_STATE_CONFIGURE_AER if namespace is 0 during nvme_ctrlr_construct_namespaces same as in 18.07?

**Comment by dong-liuliu** [comment] 2018-11-05 23:34
@jparairo 
Cdata.nn defines the maximum number of namespaces supported by the controller. If your device directly shows cdata.nn = 0, it means the device can't have any namespace during its lifecycle.
A normal NVMe device, with namespace management ability and 0 namespace, should have 0 active namespace and also cdata.nn > 0.

I didn't realized the special situation you met.
Let me check whether extra modification is required, besides passing nn == 0.
--

**Comment by jparairo** [comment] 2018-11-06 00:21
@dong-liuliu 

My requirement does not include namespaces so you may call it a not-normal NVMe device.
 
I was initially thinking of having cdata.nn > 0 and just not have any active namespace for the sake of satisfying your condition above and working around the issue. 

But adding the code that I mentioned above works well for my application. The only question is whether it has any negative effects on normal NVMe devices.

**Comment by dong-liuliu** [comment] 2018-11-06 17:09
hi,  @jparairo 
I've added modification to accept abnormal NVMe device which can only be a char dev.
Please get and try the patch from:
https://review.gerrithub.io/c/spdk/spdk/+/432191

**Comment by jimharris** [comment] 2018-11-06 17:16
I see nothing in the spec that says cdata.nn must be greater than zero.  This is extremely not-normal, but see no reason why we can't support it in the code.

@dong-liuliu - could we add a NOTICELOG for this case when it occurs?

**Comment by dong-liuliu** [comment] 2018-11-06 17:49
@jimharris Yes, of course, already added support to it.
Let's wait for @jparairo 's feedback

**Comment by jparairo** [comment] 2018-11-06 19:31
the latest patch does it for me. 

Also, I accidentally posted a comment(which I don't think I'm supposed to). My apologies for that.

**Comment by jimharris** [comment] 2018-11-06 19:46
Hi @jparairo,

No apologies necessary!  You absolutely should post comments if you see improvements that can be made to the code.  You can also vote +1 on the patch to signal that the patch is working for you (or -1 if it is not).

Thanks,

-Jim

**Comment by dong-liuliu** [comment] 2018-11-06 19:48
@jparairo 
Don't care about it. Just post comments as you like.

**Comment by liang2yan** [comment] 2018-11-13 05:37
@jparairo , since patch merged, can we close this issue?

**Closed** 2018-11-13 18:59 UTC
Labels: Medium, bug
