### ISSUE TITLE
nvmf/rdma: "nvmf_rdma_destroy transport wr pool count mismatch" after port down

### ISSUE THREAD

**Issue by mhae** [spdk/spdk#3290] opened 2024-03-04 23:04 UTC
# Sighting report

After bringing a port down and then up, we're seeing this message when the target exits:

```
nvmf_rdma_destroy transport wr pool count is 184312 but should be 184320
```

Somewhere we must be skipping some clean up. A debug version did not hit any asserts.

What would be good instrumentation points to narrow down the issue?

## Steps to Reproduce

- 2 RDMA ports connected
- Bring one port down and then up while under load
- Exit the target (i.e. ctrl-c)

## Context (Environment including OS version, SPDK version, etc.)

SPDK 23.01 with the latest patches in rdma.c

**Comment by AlekseyMarchuk** [comment] 2024-03-05 06:36
Hi @mhae could you clarify how you bring the port up and down? As I remember, it can be done in several ways and result might be different

**Comment by mhae** [comment] 2024-03-05 13:16
Via switch reboot. This results in keep alive timeouts of the impacted
qpairs and triggers the disconnect flow.

**Comment by mhae** [comment] 2024-03-20 16:36
I believe this is not related to bring a port down. It happens occasionally when I run a workload and the stop the target. The target  removes all subsystems before it exits. So maybe we're not cleaning outstanding IOs when we shutdown the RDMA stack?

**Comment by AlekseyMarchuk** [comment] 2024-03-20 17:09
Hi @mhae 
I haven't looked at this issue yet. I'll be OOO next 2 weeks, I'll check this issue once I return

**Comment by AlekseyMarchuk** [comment] 2024-03-22 14:32
I spent some time trying to reproduce this issue, but without any success. I think it is related to #3284, but there we have assert that `qpair->qd != 0` after cleanup but you said you didn't hit any asserts. If you can share more details on how to increase chance of reproduction, please let me know

**Comment by mhae** [comment] 2024-04-09 15:40
@AlekseyMarchuk, I think the issue is caused by not properly cleaning up the rdma_req when we free the request.
The WRs in remaining_transfer_in_wrs are not freed/put back to the pool in nvmf_rdma_request_free_data. We only free the rdma_req->transfer_wr but not any remaining WRs.

Here's a trace that shows the problem:
- The alloc_wrs is a counter I added that gets incremented with the entries we get from spdk_mempool_get_bulk(rtransport->data_wr_pool, ...) and decremented when we put them back (spdk_mempool_get_bulk(rtransport->data_wr_pool, ...))
- In _nvmf_rdma_request_free I'm counting the number of entries of remaining_tranfer_in_wrs
```
2024-04-09 09:26:35.554 MDT {2001957} W {nvmf_tgt_app_mem_leak} rdma.c:1069:nvmf_rdma_qpair_destroy Destroying qpair when queue depth is 4: device=rocep197s0f0 qpair=0x7f2b7c1cc650, qid=0x0001, qpair.state=3
2024-04-09 09:26:35.554 MDT {2001957} E {nvmf_tgt_app_mem_leak} rdma.c:843:nvmf_rdma_dump_qpair_contents Dumping contents of queue pair (QID 1)
2024-04-09 09:26:35.554 MDT {2001957} E {nvmf_tgt_app_mem_leak} rdma.c:822:nvmf_rdma_dump_request               Request Data From Pool: 1
2024-04-09 09:26:35.554 MDT {2001957} E {nvmf_tgt_app_mem_leak} rdma.c:826:nvmf_rdma_dump_request               Request opcode=1 req=0x2000389e7ff8 req_state=13 qpair=0x7f2b7c1cc650 qid=0x01 ibv_state=6, alloc_wrs=15, num_outstanding_data_wr=0, num_remaining_data_wr=14
2024-04-09 09:26:35.554 MDT {2001957} E {nvmf_tgt_app_mem_leak} rdma.c:834:nvmf_rdma_dump_request               Request recv wr_id35185321949320
2024-04-09 09:26:35.554 MDT {2001957} E {nvmf_tgt_app_mem_leak} rdma.c:822:nvmf_rdma_dump_request               Request Data From Pool: 1
2024-04-09 09:26:35.554 MDT {2001957} E {nvmf_tgt_app_mem_leak} rdma.c:826:nvmf_rdma_dump_request               Request opcode=1 req=0x2000389ef618 req_state=13 qpair=0x7f2b7c1cc650 qid=0x01 ibv_state=6, alloc_wrs=15, num_outstanding_data_wr=0, num_remaining_data_wr=11
2024-04-09 09:26:35.554 MDT {2001957} E {nvmf_tgt_app_mem_leak} rdma.c:834:nvmf_rdma_dump_request               Request recv wr_id35185321944744
2024-04-09 09:26:35.554 MDT {2001957} E {nvmf_tgt_app_mem_leak} rdma.c:822:nvmf_rdma_dump_request               Request Data From Pool: 1
2024-04-09 09:26:35.554 MDT {2001957} E {nvmf_tgt_app_mem_leak} rdma.c:826:nvmf_rdma_dump_request               Request opcode=1 req=0x2000389f9d70 req_state=13 qpair=0x7f2b7c1cc650 qid=0x01 ibv_state=6, alloc_wrs=15, num_outstanding_data_wr=0, num_remaining_data_wr=15
2024-04-09 09:26:35.554 MDT {2001957} E {nvmf_tgt_app_mem_leak} rdma.c:834:nvmf_rdma_dump_request               Request recv wr_id35185321965024
2024-04-09 09:26:35.554 MDT {2001957} E {nvmf_tgt_app_mem_leak} rdma.c:822:nvmf_rdma_dump_request               Request Data From Pool: 1
2024-04-09 09:26:35.554 MDT {2001957} E {nvmf_tgt_app_mem_leak} rdma.c:826:nvmf_rdma_dump_request               Request opcode=1 req=0x2000389fbaf8 req_state=13 qpair=0x7f2b7c1cc650 qid=0x01 ibv_state=6, alloc_wrs=15, num_outstanding_data_wr=0, num_remaining_data_wr=0
2024-04-09 09:26:35.554 MDT {2001957} E {nvmf_tgt_app_mem_leak} rdma.c:834:nvmf_rdma_dump_request               Request recv wr_id35185321951296
2024-04-09 09:26:35.554 MDT {2001957} I {nvmf_tgt_app_mem_leak} rdma.c:1087:nvmf_rdma_qpair_destroy ??? qpair=0x7f2b7c1cc650, req=0x2000389e7ff8

// Here I'm detecting that alloc_wrs is not 0. This request has 14 WRs left. This correlates to num_remaining_data_wr
2024-04-09 09:26:35.554 MDT {2001957} I {nvmf_tgt_app_mem_leak} rdma.c:2309:_nvmf_rdma_request_free ??? wrs not 0: req=0x2000389e7ff8, left=14
// Now I'm actually counting the WRs on remaining_tranfer_in_wrs which also corresponds to 14
2024-04-09 09:26:35.554 MDT {2001957} I {nvmf_tgt_app_mem_leak} rdma.c:777:x ??? req=0x2000389e7ff8: num_wrs=14
2024-04-09 09:26:35.554 MDT {2001957} I {nvmf_tgt_app_mem_leak} rdma.c:1087:nvmf_rdma_qpair_destroy ??? qpair=0x7f2b7c1cc650, req=0x2000389ef618
2024-04-09 09:26:35.554 MDT {2001957} I {nvmf_tgt_app_mem_leak} rdma.c:2309:_nvmf_rdma_request_free ??? wrs not 0: req=0x2000389ef618, left=11
2024-04-09 09:26:35.554 MDT {2001957} I {nvmf_tgt_app_mem_leak} rdma.c:777:x ??? req=0x2000389ef618: num_wrs=11
2024-04-09 09:26:35.554 MDT {2001957} I {nvmf_tgt_app_mem_leak} rdma.c:1087:nvmf_rdma_qpair_destroy ??? qpair=0x7f2b7c1cc650, req=0x2000389f9d70
2024-04-09 09:26:35.554 MDT {2001957} I {nvmf_tgt_app_mem_leak} rdma.c:2309:_nvmf_rdma_request_free ??? wrs not 0: req=0x2000389f9d70, left=15
2024-04-09 09:26:35.554 MDT {2001957} I {nvmf_tgt_app_mem_leak} rdma.c:777:x ??? req=0x2000389f9d70: num_wrs=15

2024-04-09 09:26:41.908 MDT {2001957} E {nvmf_tgt_app_mem_leak} rdma.c:3377:nvmf_rdma_destroy transport wr pool count is 184280 but should be 184320

// 40 unaccounted WRs correspond to the num_remaining_data_wr.
```

**Comment by AlekseyMarchuk** [comment] 2024-04-09 15:42
@mhae thank you for your finding. I'll take closer look tomorrow

**Comment by AlekseyMarchuk** [comment] 2024-04-10 13:22
@mhae I think.I found the root cause. Fix is here https://review.spdk.io/gerrit/c/spdk/spdk/+/22720/1
I'd be glad if you can verify it. Thanks one more time for your analysis!

**Comment by AlekseyMarchuk** [comment] 2024-04-24 09:11
The fix is merged, closing this issue

**Closed by AlekseyMarchuk** 2024-04-24 09:11 UTC
Labels: bug, Medium, Patches out for review
