### ISSUE TITLE
nvmf/rdma: Bogus? error message when initiator is killed

### ISSUE THREAD

**Issue by mhae** [spdk/spdk#1504] opened 2020-07-21 21:36 UTC
With 20.07-pre, killing an initiator like perf against a RDMA subsystem logs the following error messages:
```
2020-21-07 01:21:23.708 PDT {22189} E {nvmf_tgt_app} rdma.c:3129:nvmf_process_ib_event Failed to send LAST_WQE_REACHED event for rqpair 0x7f6d60dd05d0 (rc=22)
2020-21-07 01:21:23.748 PDT {22189} E {nvmf_tgt_app} rdma.c:3129:nvmf_process_ib_event Failed to send LAST_WQE_REACHED event for rqpair 0x7f6d60dc17a0 (rc=22)
2020-21-07 01:21:23.758 PDT {22189} E {nvmf_tgt_app} rdma.c:3129:nvmf_process_ib_event Failed to send LAST_WQE_REACHED event for rqpair 0x7f6d60dcd680 (rc=22)
2020-21-07 01:21:23.768 PDT {22189} E {nvmf_tgt_app} rdma.c:3129:nvmf_process_ib_event Failed to send LAST_WQE_REACHED event for rqpair 0x7f6d60dcda00 (rc=22)
2020-21-07 01:21:23.778 PDT {22189} E {nvmf_tgt_app} rdma.c:3129:nvmf_process_ib_event Failed to send LAST_WQE_REACHED event for rqpair 0x7f6d60dcddd0 (rc=22)
2020-21-07 01:21:23.788 PDT {22189} E {nvmf_tgt_app} rdma.c:3129:nvmf_process_ib_event Failed to send LAST_WQE_REACHED event for rqpair 0x7f6d60ea8260 (rc=22)
2020-21-07 01:21:23.798 PDT {22189} E {nvmf_tgt_app} rdma.c:3129:nvmf_process_ib_event Failed to send LAST_WQE_REACHED event for rqpair 0x7f6d60e87e00 (rc=22)
2020-21-07 01:21:23.808 PDT {22189} E {nvmf_tgt_app} rdma.c:3129:nvmf_process_ib_event Failed to send LAST_WQE_REACHED event for rqpair 0x7f6d60ea85e0 (rc=22)
2020-21-07 01:21:23.848 PDT {22189} E {nvmf_tgt_app} rdma.c:3129:nvmf_process_ib_event Failed to send LAST_WQE_REACHED event for rqpair 0x7f6d60dabc80 (rc=22)
2020-21-07 01:21:23.858 PDT {22189} E {nvmf_tgt_app} rdma.c:3129:nvmf_process_ib_event Failed to send LAST_WQE_REACHED event for rqpair 0x7f6d60db7cc0 (rc=22)
2020-21-07 01:21:23.868 PDT {22189} E {nvmf_tgt_app} rdma.c:3129:nvmf_process_ib_event Failed to send LAST_WQE_REACHED event for rqpair 0x7f6d60dcd300 (rc=22)
```

It is unclear if these messages are benign or represent an actual issue. At a minimum these messages should be a warning with additional text that clarifies the issue (like a remote connection terminated unexpectedly).

## Steps to Reproduce

0. CX5 and 2 systems, connected with a patch cable (direct connection)
1. nvmf_target with RDMA transport
2. run perf on the other system and hit ctrl-c 

## Context (Environment including OS version, SPDK version, etc.)
20.07-pre (as of today), CX5, CentOS, 2 systems

**Comment by AlekseyMarchuk** [comment] 2020-07-22 05:12
I'll try to reproduce this issue. I've never seen it in my practice. But I agree, it should be a warning with clear description

**Comment by AlekseyMarchuk** [comment] 2020-07-22 06:36
That is strange but now these errors occur very often. As I said, I've never seen them before. I'll try to find why they started to appear

**Comment by AlekseyMarchuk** [comment] 2020-07-22 07:56
This happens due to patch which set `qpair.group = NULL` when the qpair is removed from a poll group, so we can't get a thread when we are handling LAST_WQE_REACHED.
As I see, we can get an access to the poll group in a bit longer way, at least this pointer is not zerofied while we are destroying qpair.
I prepared a patch to address this problem https://review.spdk.io/gerrit/c/spdk/spdk/+/3475, it has [RFC] label since I want to discuss other possible alternatives. Anyway, it worth having this fixed in 20.07

**Comment by Seth5141** [comment] 2020-07-22 16:49
@AlekseyMarchuk I like your solution. I have an additional alternative that I mentioned in the comments of your change, but am happy to merge your change as is.

**Comment by spdkci** [comment] 2020-07-22 17:23
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_22091.html

**Comment by AlekseyMarchuk** [comment] 2020-07-23 06:28
I updated my patch with new solution

**Comment by AlekseyMarchuk** [comment] 2020-07-28 10:18
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/3475 merged, closing this issue

**Closed by AlekseyMarchuk** 2020-07-28 10:18 UTC
Labels: Low, bug
