### ISSUE TITLE
SPDK iscsi target reported coredump in the CI nightly testing

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#793] opened 2019-05-16 13:32 UTC
the SPDK iSCSI Target reported coredump in the nightly RBD_autotest. The test suite is test/iscsi_tgt/trace_record/trace_record.sh. The detailed log is as below:
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/503/archive/RBD_autotest/build.log

```
Core was generated by `./app/iscsi_tgt/iscsi_tgt -m 0xf --num-trace-entries 4096 --tpoint-group-mask 0'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f33be74deab in raise () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f33b048d700 (LWP 2012279))]

Thread 5 (Thread 0x7f33b1c90700 (LWP 2012276)):
#0  0x00007f33be81118f in epoll_wait () from /lib64/libc.so.6
No symbol table info available.
#1  0x0000000000769b49 in eal_intr_handle_interrupts (pfd=5, totalfds=1) at /var/jenkins/workspace/RBD_BlobFS_tests/RBD_autotest/spdk/dpdk/lib/librte_eal/linuxapp/eal/eal_interrupts.c:853
        events = {{events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}}
        nfds = 0
#2  0x0000000000769d28 in eal_intr_thread_main (arg=0x0) at /var/jenkins/workspace/RBD_BlobFS_tests/RBD_autotest/spdk/dpdk/lib/librte_eal/linuxapp/eal/eal_interrupts.c:937
        pipe_event = {events = 3, data = {ptr = 0x3, fd = 3, u32 = 3, u64 = 3}}
        src = 0x0
        numfds = 1
        pfd = 5
        ev = {events = 32563, data = {ptr = 0x7ffc09cad11e, fd = 164286750, u32 = 164286750, u64 = 140720472772894}}
        __func__ = "eal_intr_thread_main"
#3  0x0000000000778a53 in rte_thread_init (arg=0x1d0cc00) at /var/jenkins/workspace/RBD_BlobFS_tests/RBD_autotest/spdk/dpdk/lib/librte_eal/common/eal_common_thread.c:163
        ret = 0
        params = 0x1d0cc00
        start_routine = 0x769bab <eal_intr_thread_main>
        routine_arg = 0x0
#4  0x00007f33beadd594 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f33be810e6f in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 4 (Thread 0x7f33b0c8e700 (LWP 2012278)):
#0  0x00007f33be81118f in epoll_wait () from /lib64/libc.so.6
No symbol table info available.
#1  0x00000000005ee079 in spdk_posix_sock_group_impl_poll (_group=0x7f33a0000e10, max_events=32, socks=0x7f33b0c8b030) at posix.c:561
        group = 0x7f33a0000e10
        num_events = 0
        i = 0
        events = {{events = 351745472, data = {ptr = 0x1d62dc000002000, fd = 8192, u32 = 8192, u64 = 132343541710987264}}, {events = 0, data = {ptr = 0x200014f735c0, fd = 351745472, u32 = 351745472, u64 = 35184723834304}}, {events = 30813632, data = {ptr = 0xb0c8aec000000000, fd = 0, u32 = 0, u64 = 12738623685674401792}}, {events = 32563, data = {ptr = 0x722665 <spdk_sock_recv+263>, fd = 7480933, u32 = 7480933, u64 = 7480933}}, {events = 2965941872, data = {ptr = 0x3000007f33, fd = 32563, u32 = 32563, u64 = 206158462771}}, {events = 0, data = {ptr = 0x200014f735c0, fd = 351745472, u32 = 351745472, u64 = 35184723834304}}, {events = 30813632, data = {ptr = 0xb0c8ae7000000000, fd = 0, u32 = 0, u64 = 12738623342077018112}}, {events = 32563, data = {ptr = 0x30, fd = 48, u32 = 48, u64 = 48}}, {events = 2965942032, data = {ptr = 0x665ac500007f33, fd = 32563, u32 = 32563, u64 = 28810249779576627}}, {events = 0, data = {ptr = 0x200014c84080, fd = 348668032, u32 = 348668032, u64 = 35184720756864}}, {events = 351745472, data = {ptr = 0x100002000, fd = 8192, u32 = 8192, u64 = 4294975488}}, {events = 48, data = {ptr = 0x7f33ae304c00, fd = -1372566528, u32 = 2922400768, u64 = 139859942460416}}, {events = 2965942032, data = {ptr = 0x6c879900007f33, fd = 32563, u32 = 32563, u64 = 30548388684529459}}, {events = 4294967295, data = {ptr = 0x200014f735c0, fd = 351745472, u32 = 351745472, u64 = 35184723834304}}, {events = 48, data = {ptr = 0xb0c8af7000000000, fd = 0, u32 = 0, u64 = 12738624441588645888}}, {events = 32563, data = {ptr = 0x675ac5 <spdk_iscsi_read_pdu+929>, fd = 6773445, u32 = 6773445, u64 = 6773445}}, {events = 2965942168, data = {ptr = 0xae304c0000007f33, fd = 32563, u32 = 32563, u64 = 12551615724365315891}}, {events = 32563, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 351745472, data = {ptr = 0xb0c8af7000002000, fd = 8192, u32 = 8192, u64 = 12738624441588654080}}, {events = 0, data = {ptr = 0x200014f735c0, fd = 351745472, u32 = 351745472, u64 = 35184723834304}}, {events = 351745472, data = {ptr = 0x100002000, fd = 8192, u32 = 8192, u64 = 4294975488}}, {events = 0, data = {ptr = 0x7ffc09cad23e, fd = 164287038, u32 = 164287038, u64 = 140720472773182}}, {events = 164287039, data = {ptr = 0xb0c8afb000007ffc, fd = 32764, u32 = 32764, u64 = 12738624716466585596}}, {events = 32563, data = {ptr = 0x66b577 <iscsi_conn_handle_incoming_pdus+60>, fd = 6731127, u32 = 6731127, u64 = 6731127}}, {events = 732128448, data = {ptr = 0xae304c0000000002, fd = 2, u32 = 2, u64 = 12551615724365283330}}, {events = 32563, data = {ptr = 0x1, fd = 1, u32 = 1, u64 = 1}}, {events = 0, data = {ptr = 0xae77500000000000, fd = 0, u32 = 0, u64 = 12571604845758251008}}, {events = 32563, data = {ptr = 0x66b9aa <iscsi_conn_sock_cb>, fd = 6732202, u32 = 6732202, u64 = 6732202}}, {events = 2965942256, data = {ptr = 0x66bae100007f33, fd = 32563, u32 = 32563, u64 = 28915923154927411}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 30813632, data = {ptr = 0xa0000df000000000, fd = 0, u32 = 0, u64 = 11529230370511781888}}, {events = 32563, data = {ptr = 0x7f33ae304c00, fd = -1372566528, u32 = 2922400768, u64 = 139859942460416}}}
#2  0x0000000000723ffb in spdk_sock_group_impl_poll_count (group_impl=0x7f33a0000e10, group=0x7f33a0000df0, max_events=32) at sock.c:297
        socks = {0x1d62dc0, 0x20002ba364c0, 0xcb2840 <g_devs+41440>, 0x20002ba364c0, 0x7f33b0c8b080, 0x6de273 <spdk_scsi_lun_complete_task+1191>, 0x20002ba364c0, 0x1d4c6b0, 0x6eb1bd <bdev_scsi_task_complete_cmd>, 0x20002ba364c0, 0x7f33b0c8b0d0, 0x8, 0x7f33b0c8b190, 0x2000074ffe80, 0xc1b0c8b0b0, 0x7d0a6c0, 0x8, 0x100000001, 0x1, 0x800000001, 0x7f33b0c8b160, 0x63d1ed <_spdk_bdev_io_complete+9996>, 0xc1000000c0, 0x8, 0x2000074ffe80, 0x7f33b0c8b190, 0x0, 0x2000074ffe80, 0x7f33b0c8b190, 0x0, 0x2000074ffe80, 0x7f33b0c8b0a4}
        num_events = 0
        i = 0
        __PRETTY_FUNCTION__ = "spdk_sock_group_impl_poll_count"
#3  0x00000000007243ff in spdk_sock_group_poll_count (group=0x7f33a0000df0, max_events=32) at sock.c:331
        group_impl = 0x7f33a0000e10
        rc = 32563
        final_rc = 0
        __func__ = "spdk_sock_group_poll_count"
#4  0x0000000000723e95 in spdk_sock_group_poll (group=0x7f33a0000df0) at sock.c:282
No locals.
#5  0x00000000006d1402 in iscsi_poll_group_poll (ctx=0x1cf19b0) at iscsi_subsystem.c:1168
        group = 0x1cf19b0
        conn = 0x0
        tmp = 0x1
        rc = 0
        __func__ = "iscsi_poll_group_poll"
#6  0x00000000006ff205 in spdk_thread_poll (thread=0x1cfd990, max_msgs=0, now=374779564029622) at thread.c:469
        poller_rc = 0
        msg_count = 0
        orig_thread = 0x0
        poller = 0x7f33a0000e40
        tmp = 0x0
        rc = 0
        __func__ = "spdk_thread_poll"
#7  0x00000000005f6176 in _spdk_reactor_run (arg=0x1cfd580) at reactor.c:271
        now = 374779564029622
        reactor = 0x1cfd580
        thread = 0x1cfd990
        last_rusage = 374779563475744
        lw_thread = 0x1cfda18
        tmp = 0x0
        thread_name = "reactor_2", '\000' <repeats 15 times>, "\254i\256\276\063\177\000"
        __func__ = "_spdk_reactor_run"
#8  0x000000000076036b in eal_thread_loop (arg=0x0) at /var/jenkins/workspace/RBD_BlobFS_tests/RBD_autotest/spdk/dpdk/lib/librte_eal/linuxapp/eal/eal_thread.c:153
        fct_arg = 0x1cfd580
        c = 0 '\000'
        n = 1
        ret = 0
        lcore_id = 2
        thread_id = 139859986016000
        m2s = 12
        s2m = 15
        cpuset = "2", '\000' <repeats 254 times>
        __func__ = "eal_thread_loop"
#9  0x00007f33beadd594 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#10 0x00007f33be810e6f in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 3 (Thread 0x7f33c1de7200 (LWP 2012270)):
#0  0x00000000005f6147 in _spdk_reactor_run (arg=0x1cfd400) at reactor.c:268
        now = 374779564005010
        reactor = 0x1cfd400
        thread = 0x1cfd8f0
        last_rusage = 374779563324754
        lw_thread = 0x1cfd978
        tmp = 0x0
        thread_name = "reactor_0\000@\000\000\000\000\000 \327\312\t\374\177\000\000\000\000\000\000\000\000\000"
        __func__ = "_spdk_reactor_run"
#1  0x00000000005f6c37 in spdk_reactors_start () at reactor.c:374
        reactor = 0x1cfd400
        tmp_cpumask = 0x1ce42d0
        i = 4294967295
        current_core = 0
        rc = 0
        thread_name = "reactor_3\000\000\000\001\000\000\000\000\001\303\003\000 \000\000\000\000\000\000\000\000\000"
        __func__ = "spdk_reactors_start"
        __PRETTY_FUNCTION__ = "spdk_reactors_start"
#2  0x00000000005f251f in spdk_app_start (opts=0x7ffc09cad590, start_fn=0x4076fc <spdk_startup>, arg1=0x0) at app.c:688
        config = 0x1d05770
        rc = 0
        tty = 0x0
        tmp_cpumask = 0x1cfd760
        __func__ = "spdk_app_start"
#3  0x0000000000407907 in main (argc=7, argv=0x7ffc09cad728) at iscsi_tgt.c:112
        rc = 1
        opts = {name = 0x79a48f "iscsi", config_file = 0x0, json_config_file = 0x0, rpc_addr = 0x7b7c71 "/var/tmp/spdk.sock", reactor_mask = 0x7ffc09caf5f5 "0xf", tpoint_group_mask = 0x7ffc09caf626 "0xf", shm_id = -1, shutdown_cb = 0x0, usr1_handler = 0x407516 <spdk_sigusr1>, enable_coredump = true, mem_channel = -1, master_core = -1, mem_size = -1, no_pci = false, hugepage_single_segments = false, unlink_hugepage = false, hugedir = 0x0, print_level = SPDK_LOG_INFO, num_pci_addr = 0, pci_blacklist = 0x0, pci_whitelist = 0x0, max_delay_us = 0, delay_subsystem_init = false, num_entries = 4096, env_context = 0x0}
        __func__ = "main"

Thread 2 (Thread 0x7f33b148f700 (LWP 2012277)):
#0  0x00007f33be81118f in epoll_wait () from /lib64/libc.so.6
No symbol table info available.
#1  0x00000000005ee079 in spdk_posix_sock_group_impl_poll (_group=0x7f33a8000e10, max_events=32, socks=0x7f33b148c030) at posix.c:561
        group = 0x7f33a8000e10
        num_events = 0
        i = 0
        events = {{events = 351629888, data = {ptr = 0x1d5ded000002000, fd = 8192, u32 = 8192, u64 = 132256749011869696}}, {events = 0, data = {ptr = 0x200014f57240, fd = 351629888, u32 = 351629888, u64 = 35184723718720}}, {events = 30793424, data = {ptr = 0xb148bec000000000, fd = 0, u32 = 0, u64 = 12774670074879410176}}, {events = 32563, data = {ptr = 0x722665 <spdk_sock_recv+263>, fd = 7480933, u32 = 7480933, u64 = 7480933}}, {events = 2974334576, data = {ptr = 0x3000007f33, fd = 32563, u32 = 32563, u64 = 206158462771}}, {events = 0, data = {ptr = 0x200014f57240, fd = 351629888, u32 = 351629888, u64 = 35184723718720}}, {events = 30793424, data = {ptr = 0xb148be7000000000, fd = 0, u32 = 0, u64 = 12774669731282026496}}, {events = 32563, data = {ptr = 0x30, fd = 48, u32 = 48, u64 = 48}}, {events = 2974334736, data = {ptr = 0x665ac500007f33, fd = 32563, u32 = 32563, u64 = 28810249779576627}}, {events = 0, data = {ptr = 0x200014c81040, fd = 348655680, u32 = 348655680, u64 = 35184720744512}}, {events = 351629888, data = {ptr = 0x100002000, fd = 8192, u32 = 8192, u64 = 4294975488}}, {events = 48, data = {ptr = 0x7f33ae303a00, fd = -1372571136, u32 = 2922396160, u64 = 139859942455808}}, {events = 2974334736, data = {ptr = 0x6c879900007f33, fd = 32563, u32 = 32563, u64 = 30548388684529459}}, {events = 4294967295, data = {ptr = 0x200014f57240, fd = 351629888, u32 = 351629888, u64 = 35184723718720}}, {events = 48, data = {ptr = 0xb148bf7000000000, fd = 0, u32 = 0, u64 = 12774670830793654272}}, {events = 32563, data = {ptr = 0x675ac5 <spdk_iscsi_read_pdu+929>, fd = 6773445, u32 = 6773445, u64 = 6773445}}, {events = 2974334872, data = {ptr = 0xae303a0000007f33, fd = 32563, u32 = 32563, u64 = 12551595933156015923}}, {events = 32563, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 351629888, data = {ptr = 0xb148bf7000002000, fd = 8192, u32 = 8192, u64 = 12774670830793662464}}, {events = 0, data = {ptr = 0x200014f57240, fd = 351629888, u32 = 351629888, u64 = 35184723718720}}, {events = 351629888, data = {ptr = 0x100002000, fd = 8192, u32 = 8192, u64 = 4294975488}}, {events = 0, data = {ptr = 0x7ffc09cad23e, fd = 164287038, u32 = 164287038, u64 = 140720472773182}}, {events = 164287039, data = {ptr = 0xb148bfb000007ffc, fd = 32764, u32 = 32764, u64 = 12774671105671593980}}, {events = 32563, data = {ptr = 0x66b577 <iscsi_conn_handle_incoming_pdus+60>, fd = 6731127, u32 = 6731127, u64 = 6731127}}, {events = 732049536, data = {ptr = 0xae303a0000000001, fd = 1, u32 = 1, u64 = 12551595933155983361}}, {events = 32563, data = {ptr = 0x1, fd = 1, u32 = 1, u64 = 1}}, {events = 0, data = {ptr = 0xae77500000000000, fd = 0, u32 = 0, u64 = 12571604845758251008}}, {events = 32563, data = {ptr = 0x66b9aa <iscsi_conn_sock_cb>, fd = 6732202, u32 = 6732202, u64 = 6732202}}, {events = 2974334960, data = {ptr = 0x66bae100007f33, fd = 32563, u32 = 32563, u64 = 28915923154927411}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 30793424, data = {ptr = 0xa8000df000000000, fd = 0, u32 = 0, u64 = 12105691122815205376}}, {events = 32563, data = {ptr = 0x7f33ae303a00, fd = -1372571136, u32 = 2922396160, u64 = 139859942455808}}}
#2  0x0000000000723ffb in spdk_sock_group_impl_poll_count (group_impl=0x7f33a8000e10, group=0x7f33a8000df0, max_events=32) at sock.c:297
        socks = {0x1d5ded0, 0x20002ba23080, 0xcb1cb0 <g_devs+38480>, 0x20002ba23080, 0x7f33b148c080, 0x6de273 <spdk_scsi_lun_complete_task+1191>, 0x20002ba23080, 0x1d4baf0, 0x6eb1bd <bdev_scsi_task_complete_cmd>, 0x20002ba23080, 0x7f33b148c0d0, 0x8, 0x7f33b148c190, 0x2000072ffe80, 0xc1b148c0b0, 0x7cc6280, 0x8, 0x100000001, 0x1, 0x800000001, 0x7f33b148c160, 0x63d1ed <_spdk_bdev_io_complete+9996>, 0xc1000000c0, 0x8, 0x2000072ffe80, 0x7f33b148c190, 0x0, 0x2000072ffe80, 0x7f33b148c190, 0x0, 0x2000072ffe80, 0x7f33b148c0a4}
        num_events = 0
        i = 0
        __PRETTY_FUNCTION__ = "spdk_sock_group_impl_poll_count"
#3  0x00000000007243ff in spdk_sock_group_poll_count (group=0x7f33a8000df0, max_events=32) at sock.c:331
        group_impl = 0x7f33a8000e10
        rc = 32563
        final_rc = 0
        __func__ = "spdk_sock_group_poll_count"
#4  0x0000000000723e95 in spdk_sock_group_poll (group=0x7f33a8000df0) at sock.c:282
No locals.
#5  0x00000000006d1402 in iscsi_poll_group_poll (ctx=0x1cf1980) at iscsi_subsystem.c:1168
        group = 0x1cf1980
        conn = 0x0
        tmp = 0x1
        rc = 0
        __func__ = "iscsi_poll_group_poll"
#6  0x00000000006ff205 in spdk_thread_poll (thread=0x1ce45f0, max_msgs=0, now=374779564018614) at thread.c:469
        poller_rc = 0
        msg_count = 0
        orig_thread = 0x0
        poller = 0x7f33a8000e40
        tmp = 0x0
        rc = 0
        __func__ = "spdk_thread_poll"
#7  0x00000000005f6176 in _spdk_reactor_run (arg=0x1cfd4c0) at reactor.c:271
        now = 374779564018614
        reactor = 0x1cfd4c0
        thread = 0x1ce45f0
        last_rusage = 374779563455094
        lw_thread = 0x1ce4678
        tmp = 0x0
        thread_name = "reactor_1", '\000' <repeats 15 times>, "\254i\256\276\063\177\000"
        __func__ = "_spdk_reactor_run"
#8  0x000000000076036b in eal_thread_loop (arg=0x0) at /var/jenkins/workspace/RBD_BlobFS_tests/RBD_autotest/spdk/dpdk/lib/librte_eal/linuxapp/eal/eal_thread.c:153
        fct_arg = 0x1cfd4c0
        c = 0 '\000'
        n = 1
        ret = 0
        lcore_id = 1
        thread_id = 139859994408704
        m2s = 8
        s2m = 11
        cpuset = "1", '\000' <repeats 254 times>
        __func__ = "eal_thread_loop"
#9  0x00007f33beadd594 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#10 0x00007f33be810e6f in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 1 (Thread 0x7f33b048d700 (LWP 2012279)):
#0  0x00007f33be74deab in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f33be7385b9 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007f33bed0ffb2 in __sanitizer::Abort() () from /lib64/libubsan.so.1
No symbol table info available.
#3  0x00007f33bed1890c in __sanitizer::Die() () from /lib64/libubsan.so.1
No symbol table info available.
#4  0x00007f33becfc0e6 in __ubsan::ScopedReport::~ScopedReport() () from /lib64/libubsan.so.1
No symbol table info available.
#5  0x00007f33becff51c in handleTypeMismatchImpl(__ubsan::TypeMismatchData*, unsigned long, __ubsan::ReportOptions) () from /lib64/libubsan.so.1
No symbol table info available.
#6  0x00007f33becffb25 in __ubsan_handle_type_mismatch_v1 () from /lib64/libubsan.so.1
No symbol table info available.
#7  0x00000000006689e5 in iscsi_get_pdu_length (pdu=0x0, header_digest=0, data_digest=0) at conn.c:1079
        data_len = 0
        enable_digest = 1
        total = 408
#8  0x00000000006699a7 in iscsi_conn_flush_pdus_internal (conn=0x7f33ae305e00) at conn.c:1208
        num_iovs = 32
        iovs = {{iov_base = 0x200014f3aec0, iov_len = 48}, {iov_base = 0x1d60680, iov_len = 360}, {iov_base = 0x7f33fbad8001, iov_len = 8}, {iov_base = 0x7f33b048a200, iov_len = 35184374648624}, {iov_base = 0x7f33a4001a50, iov_len = 35184374648624}, {iov_base = 0x7f33a4001a71, iov_len = 139859771529808}, {iov_base = 0x7f33a4001a71, iov_len = 0}, {iov_base = 0x0, iov_len = 0}, {iov_base = 0x0, iov_len = 0}, {iov_base = 0x80b0489da0, iov_len = 7201395}, {iov_base = 0x20002ba40000, iov_len = 0}, {iov_base = 0x0, iov_len = 0}, {iov_base = 0xffffffffffffffff, iov_len = 0}, {iov_base = 0x20002ba47e00, iov_len = 30716048}, {iov_base = 0x45ffffffff, iov_len = 374776850148576}, {iov_base = 0x7f33b0489de0, iov_len = 7541282}, {iov_base = 0x7f33b0489df0, iov_len = 7541135}, {iov_base = 0x7f33b0489e00, iov_len = 7629968}, {iov_base = 0x7f33b0489e70, iov_len = 7293150}, {iov_base = 0x7f33b0489ff0, iov_len = 374776850151692}, {iov_base = 0x7f33b0489e30, iov_len = 7541282}, {iov_base = 0x7f33b0489e40, iov_len = 7541135}, {iov_base = 0x7f33b0489e50, iov_len = 7504935946477799168}, {iov_base = 0x7f33b0489ec0, iov_len = 7293150}, {iov_base = 0x7f33ae775000, iov_len = 1}, {iov_base = 0xfe, iov_len = 35184720732160}, {iov_base = 0x7f33b0489f40, iov_len = 7626994}, {iov_base = 0x200014f8f780, iov_len = 7504935946477799168}, {iov_base = 0x300000001, iov_len = 4294967297}, {iov_base = 0x200014f8f780, iov_len = 35184720731968}, {iov_base = 0x200014c7df40, iov_len = 13318155}, {iov_base = 0x200014c7df40, iov_len = 35184720769216}}
        iov = 0x7f33b0489ce0
        iovcnt = 2
        bytes = 408
        total_length = 408
        mapped_length = 408
        pdu = 0x0
        pdu_length = 32563
        __func__ = "iscsi_conn_flush_pdus_internal"
#9  0x000000000066a755 in iscsi_conn_flush_pdus (_conn=0x7f33ae305e00) at conn.c:1273
        conn = 0x7f33ae305e00
        rc = -1
#10 0x000000000066bb67 in iscsi_conn_sock_cb (arg=0x7f33ae305e00, group=0x7f33a4000df0, sock=0x1d5e410) at conn.c:1402
        conn = 0x7f33ae305e00
        rc = -1
        __PRETTY_FUNCTION__ = "iscsi_conn_sock_cb"
#11 0x00000000007242ab in spdk_sock_group_impl_poll_count (group_impl=0x7f33a4000e10, group=0x7f33a4000df0, max_events=32) at sock.c:306
        sock = 0x1d5e410
        socks = {0x1d5e410, 0x62baa7 <spdk_bdev_channel_create>, 0x7f33b048a0a0, 0x704bd4 <spdk_get_io_channel+3625>, 0x3000000003, 0x1d4c291, 0x0, 0x7f33a4001ab0, 0x1d4c850, 0x1cee3a0, 0x7f33b048a0d0, 0x8, 0x7f33b048a190, 0x2000076ffe80, 0x9101d5e410, 0xa4000e10, 0x8, 0x100000001, 0x1, 0x800000001, 0x1b048a100, 0x1d5e410, 0x7ffc09cad240, 0x8, 0x2000076ffe80, 0x7f33b048a190, 0x0, 0x2000076ffe80, 0x7f33b048a190, 0x0, 0x2000076ffe80, 0x7f33b048a0a4}
        num_events = 1
        i = 0
        __PRETTY_FUNCTION__ = "spdk_sock_group_impl_poll_count"
#12 0x00000000007243ff in spdk_sock_group_poll_count (group=0x7f33a4000df0, max_events=32) at sock.c:331
        group_impl = 0x7f33a4000e10
        rc = 32563
        final_rc = 0
        __func__ = "spdk_sock_group_poll_count"
#13 0x0000000000723e95 in spdk_sock_group_poll (group=0x7f33a4000df0) at sock.c:282
No locals.
#14 0x00000000006d1402 in iscsi_poll_group_poll (ctx=0x1cf19e0) at iscsi_subsystem.c:1168
        group = 0x1cf19e0
        conn = 0x0
        tmp = 0x1
        rc = 0
        __func__ = "iscsi_poll_group_poll"
#15 0x00000000006ff205 in spdk_thread_poll (thread=0x1cee3a0, max_msgs=0, now=374776850133986) at thread.c:469
        poller_rc = 0
        msg_count = 0
        orig_thread = 0x0
        poller = 0x7f33a4000e40
        tmp = 0x0
        rc = 0
        __func__ = "spdk_thread_poll"
#16 0x00000000005f6176 in _spdk_reactor_run (arg=0x1cfd640) at reactor.c:271
        now = 374776850133986
        reactor = 0x1cfd640
        thread = 0x1cee3a0
        last_rusage = 374776849445008
        lw_thread = 0x1cee428
        tmp = 0x0
        thread_name = "reactor_3", '\000' <repeats 15 times>, "\254i\256\276\063\177\000"
        __func__ = "_spdk_reactor_run"
#17 0x000000000076036b in eal_thread_loop (arg=0x0) at /var/jenkins/workspace/RBD_BlobFS_tests/RBD_autotest/spdk/dpdk/lib/librte_eal/linuxapp/eal/eal_thread.c:153
        fct_arg = 0x1cfd640
        c = 0 '\000'
        n = 1
        ret = 0
        lcore_id = 3
        thread_id = 139859977623296
        m2s = 16
        s2m = 19
        cpuset = "3", '\000' <repeats 254 times>
        __func__ = "eal_thread_loop"
#18 0x00007f33beadd594 in start_thread () from /lib64/libpthread.so.0

```

**Comment by jimharris** [comment] 2019-05-29 03:38
I'm 99% sure this is a duplicate of issue #785.  So I'm going to close this issue.

**Closed by jimharris** 2019-05-29 03:38 UTC
Labels: bug
