### ISSUE TITLE
WARN: timeout waiting for machines to boot

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#1084] opened 2019-11-28 21:17 UTC
When running test:
**test/vhost/vhost_boot/vhost_boot.sh --vm_image=/home/sys_sgci/vhost_vm_image.qcow2**
got following error:
```
   Running VM in /home/sys_sgci/vhost_test/vms/0
   Waiting for QEMU pid file
   vhost: rte_vhost_compat.c:103: vhost_session_mem_unregister: Assertion `false' failed.
   === qemu.log ===
   qemu-system-x86_64: Failed to read from slave.
   === qemu.log ===
```

**Comment by spdkci** [comment] 2019-11-28 21:23
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50979.html

**Comment by tomzawadzki** [comment] 2019-11-29 08:28
Duplicate of #1085 
The other one got more traction already.

**Closed by tomzawadzki** 2019-11-29 08:28 UTC
