### ISSUE TITLE
Nvme-cli 1.8.1 fails 

### ISSUE THREAD

**Issue by wawryk** [spdk/spdk#1112] opened 2019-12-16 16:23 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

Tests should pass
## Current Behavior

Tests fails on: 
```
ctrlr.c: 297:spdk_nvmf_ctrlr_create: *ERROR*: Discovery controller don't accept keep-alive timeout
ctrlr.c: 616:spdk_nvmf_ctrlr_connect: *ERROR*: spdk_nvmf_ctrlr_create() failed
Failed to write to /dev/nvme-fabrics: Input/output error

```

## Possible Solution

Not so good solution is back to nvme-cli 1.6
## Steps to Reproduce

1. Run some autotests with nvme-cli 1.8.1

## Context (Environment including OS version, SPDK version, etc.)

OS: Fedora 31
Kernel: 5.4.2-300.fc31.x86_64
gcc (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)
nvme-cli 1.8.1

**Comment by tomzawadzki** [comment] 2019-12-17 09:36
This is duplicate of #1089 with fix here:
https://review.gerrithub.io/c/spdk/spdk/+/476810

**Closed by tomzawadzki** 2019-12-17 09:36 UTC
