### ISSUE TITLE
[nvmf_async_init] Multiple errors ultimately end up in core dump

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2609] opened 2022-07-27 17:50 UTC
00:10:23.600   19:09:53	-- common/autotest_common.sh@846 -- # wait 502772
00:10:23.600  [2022-07-27 19:09:53.401798] thread.c:2374:spdk_for_each_channel: *ERROR*: could not find io_device 0x13daa30
00:10:23.600  nvmf_tgt: thread.c:2375: spdk_for_each_channel: Assertion `false' failed.
00:10:25.506  /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/common/autotest_common.sh: line 846: 502772 Aborted                 (core dumped) "${NVMF_APP[@]}" "$@"
00:10:25.506    19:09:55	-- common/autotest_common.sh@846 -- # trap - ERR
00:10:25.506    19:09:55	-- common/autotest_common.sh@846 -- # print_backtrace
00:10:25.506    19:09:55	-- common/autotest_common.sh@998 -- # [[ ehxBET =~ e ]]
00:10:25.506    19:09:55	-- common/autotest_common.sh@1000 -- # args=('502772' '--transport=rdma')
00:10:25.506    19:09:55	-- common/autotest_common.sh@1000 -- # local args
00:10:25.506    19:09:55	-- common/autotest_common.sh@1002 -- # xtrace_disable
00:10:25.506    19:09:55	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:10:25.506    19:09:55	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:10:25.506    19:09:55	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:10:25.506    19:09:55	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:10:25.506    19:09:55	-- common/autotest_common.sh@19 -- # set +x
00:10:25.506  ========== Backtrace start: ==========

**Comment by spdkci** [comment] 2022-07-27 17:51
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_81344.html

**Comment by mikeBashStuff** [comment] 2022-07-27 17:55
This is a duplicate of #2601 which essentially is a duplicate of #2596.

**Comment by Comphix** [comment] 2022-07-28 06:31
Close as the dup of #2596 .

**Closed by Comphix** 2022-07-28 06:31 UTC
Labels: Intermittent Failure
