### ISSUE TITLE
[ocf_fio_modes]   dd: error writing '/dev/nvme0n1': Operation not supported

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1581] opened 2020-08-30 16:18 UTC
dd: error writing '/dev/nvme0n1': Operation not supported
00:06:38.721  1+0 records in
00:06:38.721  0+0 records out
00:06:38.721  0 bytes copied, 0.00109391 s, 0.0 kB/s
00:06:38.721    02:17:15	# trap - ERR
00:06:38.721    02:17:15	# print_backtrace
00:06:38.721    02:17:15	# [[ ehxBET =~ e ]]
00:06:38.722    02:17:15	# args=("${BASH_ARGV[@]}")
00:06:38.722    02:17:15	# local args
00:06:38.722    02:17:15	# xtrace_disable
00:06:38.722    02:17:15	# '[' '' '!=' yes ']'
00:06:38.722    02:17:15	# PREV_BASH_OPTS=ehxBET
00:06:38.722    02:17:15	# [[ ehxBET == *\x* ]]
00:06:38.723    02:17:15	# XTRACE_DISABLED=yes
00:06:38.723    02:17:15	# set +x
00:06:38.723  ========== Backtrace start: ==========

**Comment by spdkci** [comment] 2020-08-30 16:19
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_25148.html

**Comment by tomzawadzki** [comment] 2020-08-31 08:46
Duplicate of #1456

**Closed by tomzawadzki** 2020-08-31 08:46 UTC
Labels: Intermittent Failure
