### ISSUE TITLE
[autotest-spdk-vs-dpdk-main] compilation fail when building with compress and crypto

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1671] opened 2020-11-03 11:48 UTC
## Current Behavior

When building current SPDK master vs current DPDK main branch there is a compilation fail related to crypto and compress libraries.
Example failing build: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_358.html
Last successful build: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_335.html (this is just before SPDK 20.10 release)

Unfortunately fix for this issue may need a port to 20.10.x branch, as this issue first appeared just before SPDK 20.10 release.

## Steps to Reproduce

1. Clone & build DPDK main from github
2. Clone & build SPDK master, use DPDK build from point 1.
```
./configure --enable-debug --enable-werror --with-rdma --with-idxd --with-fio=/usr/src/fio --with-iscsi-initiator --disable-unit-tests --with-reduce --with-crypto --enable-ubsan --enable-coverage --with-dpdk=/spdk-temp/dpdk/build --with-shared

make -j100
```

3. SPDK compilation fails with:
```
00:04:46.615 vbdev_compress.c: In function ‘_setup_compress_mbuf’:
00:04:46.615 vbdev_compress.c:460:20: error: ‘struct rte_mbuf’ has no member named ‘userdata’
00:04:46.615   460 |   mbufs[mbuf_index]->userdata = reduce_cb_arg;
00:04:46.615       |                    ^~
00:04:46.615 vbdev_compress.c:487:21: error: ‘struct rte_mbuf’ has no member named ‘userdata’
00:04:46.615   487 |    mbufs[mbuf_index]->userdata = reduce_cb_arg;
00:04:46.615       |                     ^~
00:04:46.615 vbdev_compress.c: In function ‘comp_dev_poller’:
00:04:46.615 vbdev_compress.c:659:68: error: ‘struct rte_mbuf’ has no member named ‘userdata’
00:04:46.615   659 |   reduce_args = (struct spdk_reduce_vol_cb_args *)deq_ops[i]->m_src->userdata;
00:04:46.615       |                                                                    ^~
00:04:46.616 make[3]: *** [/var/jenkins/workspace/crypto-nightly-autotest/spdk/mk/spdk.common.mk:370: vbdev_compress.o] Error 1
00:04:46.617 make[2]: *** [/var/jenkins/workspace/crypto-nightly-autotest/spdk/mk/spdk.subdirs.mk:44: compress] Error 2
00:04:46.617 make[2]: *** Waiting for unfinished jobs....
00:04:46.743 vbdev_crypto.c: In function ‘crypto_dev_poller’:
00:04:46.743 vbdev_crypto.c:589:63: error: ‘struct rte_mbuf’ has no member named ‘userdata’
00:04:46.743   589 |   bdev_io = (struct spdk_bdev_io *)dequeued_ops[i]->sym->m_src->userdata;
00:04:46.743       |                                                               ^~
00:04:46.743 vbdev_crypto.c:608:30: error: ‘struct rte_mbuf’ has no member named ‘userdata’
00:04:46.743   608 |   dequeued_ops[i]->sym->m_src->userdata = NULL;
00:04:46.743       |                              ^~
00:04:46.743 vbdev_crypto.c: In function ‘_crypto_operation’:
00:04:46.743 vbdev_crypto.c:779:26: error: ‘struct rte_mbuf’ has no member named ‘userdata’
00:04:46.743   779 |   src_mbufs[crypto_index]->userdata = bdev_io;
00:04:46.743       |                          ^~
00:04:46.744 make[3]: *** [/var/jenkins/workspace/crypto-nightly-autotest/spdk/mk/spdk.common.mk:370: vbdev_crypto.o] Error 1
00:04:46.745 make[2]: *** [/var/jenkins/workspace/crypto-nightly-autotest/spdk/mk/spdk.subdirs.mk:44: crypto] Error 2
00:04:46.745 make[1]: *** [/var/jenkins/workspace/crypto-nightly-autotest/spdk/mk/spdk.subdirs.mk:44: bdev] Error 2
00:04:46.746 make: *** [/var/jenkins/workspace/crypto-nightly-autotest/spdk/mk/spdk.subdirs.mk:44: module] Error 2
00:04:46.746 make: *** Waiting for unfinished jobs....
```

## Context (Environment including OS version, SPDK version, etc.)
Fedora 32 5.7.17-200.fc32.x86_64
gcc version 10.2.1 20200723 (Red Hat 10.2.1-1) (GCC)

**Comment by tomzawadzki** [comment] 2020-11-03 15:19
[Bug scrub] A fix will need to be posted to latest SPDK and then to v20.10.x branch. There will be no need to do 20.10.1 for this reason, but keeping patch there will allow for further testing against DPDK main.

**Comment by peluse** [comment] 2020-11-18 22:31
So here's why: https://github.com/DPDK/dpdk/commit/5284adad3e95025f9901869f581c8c04ea642d32#diff-dcdb3b94304fc6382b5be08f413c61223ad7377729841d5e2a0ac69dcd5ee746 

Should be a simple rename and its changed from a ptr to a u64.  Will take care of it shortly

**Comment by peluse** [comment] 2020-11-18 22:47
@karlatec can you try this one: https://review.spdk.io/gerrit/c/spdk/spdk/+/5159 I can't get my DPDK master configured/built right for some reason...

**Comment by peluse** [comment] 2020-11-19 17:32
@karlatec so I've got the info on what to change but I'm having "issues" building SPDK with out of tree DPDK.  I cloned a fresh DPDK repo and built using their standard directions here https://doc.dpdk.org/guides/linux_gsg/build_dpdk.html and DPDK builds OK but then when I try to build SPDK using --with-dpdk=<path to the build output dir> I get a shitload of errors mostly like these:

make[3]: *** No rule to make target '/home/peluse/dpdk/build/lib/librte_bus_pci.a', needed by 'memory_ut'.  Stop.

Can you provide some guidance for me on how to build an out of tree DPDK and then build SPDK with it?

**Comment by tomzawadzki** [comment] 2020-11-20 12:46
Maybe the way the vs_dpdk jobs build might be helpful. See https://github.com/spdk/spdk/blob/master/autobuild.sh#L50

Note that even if just standard build of DPDK should work, the `build_native_dpdk` aims for minimal required set of drivers/functionality. Similar to the way DPDK submodule in SPDK is compiled.

**Comment by karlatec** [comment] 2020-11-26 13:50
Hey @peluse, sorry missed the message.
To build SPDK with out of tree DPDK create a ~/autorun-spdk.conf file:
```
SPDK_RUN_FUNCTIONAL_TEST=1
SPDK_TEST_BLOCKDEV=1
SPDK_TEST_ISAL=1
SPDK_TEST_CRYPTO=1
SPDK_TEST_REDUCE=1
SPDK_RUN_UBSAN=1

RUN_NIGHTLY=0
SPDK_TEST_NATIVE_DPDK=main
SPDK_RUN_EXTERNAL_DPDK=/spdk-temp/dpdk/build (do not use /tmp here, DPDK build scripts will complain)
```
And then do `spdk/autorun.sh ~/autorun-spdk.conf` or  `spdk/autobuild.sh ~/autorun-spdk.conf` 
You do not need to clone or compile DPDK yourself, spdk/autobuild.sh will take care of that.

**Comment by peluse** [comment] 2021-01-05 20:02
OK, back from holidays and will get back on this soon.  It's a 3rd party change requiring us to do some different stuff, I have the info I need to make the changes just need to try and build w/the latest DPDK as mentioned above so I can write/test the updates...

**Comment by peluse** [comment] 2021-01-06 19:29
@karlatec NICE! I can repro now so will start working on the fix

**Comment by peluse** [comment] 2021-01-07 19:42
@karlatec I assume you have the failing CI test commented out for now.  Can you try this? https://review.spdk.io/gerrit/c/spdk/spdk/+/5799

**Comment by karlatec** [comment] 2021-01-08 07:18
Thanks Paul! Here are the results: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_803.html
(I think lvol fail is intermittent). It looks like the same needs to be done for compress & crypto UT.

**Comment by peluse** [comment] 2021-01-08 14:52
Cool, yeah I wanted to make sure this worked in CI before doing any more.  I'll update UT today, thanks!

**Comment by peluse** [comment] 2021-01-12 17:56
This should do it (famous last words): https://review.spdk.io/gerrit/c/spdk/spdk/+/5799

**Comment by karlatec** [comment] 2021-01-13 06:54
Re-run it, but there's still unittest compilation issues: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_833.html

**Comment by peluse** [comment] 2021-01-13 15:21
Oh for crying out loud :)  Will fix, missing the word 'static' on my decl

**Comment by karlatec** [comment] 2021-01-13 19:07
@peluse Seems like success https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_841.html :)
I used refs/changes/99/5799/13

**Comment by peluse** [comment] 2021-01-13 19:17
Nice!  Thanks for your help on this one (and Tomek)!!

**Comment by tomzawadzki** [comment] 2021-01-19 13:08
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/5799 is now merged, the issue is now resolved.

**Closed by tomzawadzki** 2021-01-19 13:08 UTC
Labels: Critical, bug
