### ISSUE TITLE
Coverage results nested too deep

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#778] opened 2019-04-30 20:00 UTC
This is mostly an enhancement request.  When downloading the coverage results, the actual results 10 directories deep.  It would be easier to view the results if this was reduced.  For example:

/var/www/html/build_pool/results/autotest-per-patch/builds/29728/archive/ut_coverage

Even if we just removed the /var/www/html/build_pool/results part, I'd be happy.  Everything starting with autotest-per-patch might be useful especially if you're looking at multiple sets of results.

Thanks,

-Jim

**Comment by Seth5141** [comment] 2019-05-01 20:55
Hi Jim, This was caused by the way we were calling tar in the python script that controls preparing and publishing logs. I have found a fix and submitted it for review on the internal git repository for that script. I'll close this once it gets merged and I confirm it works.

**Comment by Seth5141** [comment] 2019-05-02 16:04
The changes to the test pool have been merged. Now coverageand documentation TAR files have more descriptive names, and the actual files are not nested deep inside the archive. https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/29927/archive/ut_coverage_autotest-per-patch_29927.tar.gz

**Closed by Seth5141** 2019-05-02 16:04 UTC
Labels: 3rd party issue
