### ISSUE TITLE
[freebsd-vg-autotest] Build timed out

### ISSUE THREAD

**Issue by AlekseyMarchuk** [spdk/spdk#1508] opened 2020-07-25 18:38 UTC
## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_23105.html

## Execution failed at

```
00:00:53.635  ==> default: Pruning invalid NFS exports. Administrator privileges will be required...
00:00:55.687  ==> default: Creating shared folders metadata...
00:00:55.721  ==> default: Starting domain.
00:00:56.904  ==> default: Waiting for domain to get an IP address...
00:01:22.408  ==> default: Waiting for SSH to become available...
00:01:30.892      default: 
00:01:30.892      default: Inserting generated public key within guest...
00:01:31.893      default: Removing insecure key from the guest if it's present...
00:01:32.988      default: Key inserted! Disconnecting and reconnecting using new SSH key...
00:01:33.496  ==> default: Configuring and enabling network interfaces...
00:01:38.957  ==> default: Exporting NFS shared folders...
00:01:38.962  ==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
00:01:39.715  ==> default: Mounting NFS shared folders...
00:15:00.314  Build timed out (after 15 minutes). Marking the build as failed.
00:15:00.323  Build was aborted
00:15:00.324  [PostBuildScript] - [INFO] Executing post build scripts.
```

**Comment by karlatec** [comment] 2020-07-27 06:34
Duplicate of GH issue 1424

**Comment by tomzawadzki** [comment] 2020-07-27 07:12
Closing as duplicate of #1424

**Closed by tomzawadzki** 2020-07-27 07:12 UTC
Labels: Intermittent Failure, duplicate

**Comment by spdkci** [comment] 2020-07-31 17:11
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_23521.html
