### ISSUE TITLE
Vagrant VM startup failure (libvirt)

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1639] opened 2020-10-20 18:11 UTC
Failure log shows:

00:00:31.690  ==> default:     -> value=-drive, 
00:00:31.690  ==> default:     -> value=format=raw,file=/var/lib/libvirt/images/backends/ex0-nvme-zero.img,if=none,id=nvme-2, 
00:00:31.690  ==> default:     -> value=-device, 
00:00:31.690  ==> default:     -> value=nvme,drive=nvme-2,serial=12342,namespaces=0, 
00:00:31.691  ==> default:     -> value=-drive, 
00:00:31.691  ==> default:     -> value=format=raw,file=/var/lib/libvirt/images/backends/ex0-nvme-ocssd.img,if=none,id=ocssd-3, 
00:00:31.692  ==> default:     -> value=-device, 
00:00:31.692  ==> default:     -> value=nvme,drive=ocssd-3,serial=deadbeef,oacs=0,namespaces=1,lver=2,lba_index=4,mdts=10,lnum_lun=8,lnum_pln=2,lpgs_per_blk=1536,lsecs_per_pg=2,lblks_per_pln=45,metadata=/var/lib/libvirt/images/backends/ex0-nvme-ocssd.img_ocssd_md,nsdatafile=/var/lib/libvirt/images/backends/ex0-nvme-ocssd.img_ocssd_blknvme.ns,laer_thread_sleep=3000,stride=4, 
00:00:32.501  ==> default: Creating shared folders metadata...
00:00:32.536  ==> default: Starting domain.
00:00:32.943  There was an error talking to Libvirt. The error message is shown
00:00:32.943  below:
00:00:32.943  
00:00:32.943  Call to virDomainCreateWithFlags failed: internal error: process exited while connecting to monitor: qemu-system-x86_64: -realtime mlock=off: warning: '-realtime mlock=...' is deprecated, please use '-overcommit mem-lock=...' instead
00:00:32.943  2020-10-20T17:47:47.443254Z qemu-system-x86_64: unable to map backing store for guest RAM: Cannot allocate memory
00:00:32.963  + cd fedora31-libvirt
00:00:32.963  + vagrant destroy -f
00:00:35.969  ==> default: Removing domain...
00:00:36.032  Build step 'Execute shell' marked build as failure
00:00:36.102  [PostBuildScript] - [INFO] Executing post build scripts.
00:00:36.108  [nvmf-tcp-uring-vg-autotest] $ /usr/bin/env bash /tmp/jenkins9062853704202237667.sh
00:00:36.112  + [[ -n fedora31 ]]
00:00:36.112  + mv /var/jenkins/workspace/nvmf-tcp-uring-vg-autotest/fedora31-libvirt/output /var/jenkins/workspace/nvmf-tcp-uring-vg-autotest/output
00:00:36.129  [nvmf-tcp-uring-vg-autotest] $ /usr/bin/env bash /tmp/jenkins7126983447848921706.sh

**Comment by spdkci** [comment] 2020-10-20 18:12
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_29074.html

**Comment by jimharris** [comment] 2020-10-20 18:13
It seems these failures are all occurring on VM-host-WFP1.

**Comment by spdkci** [comment] 2020-10-20 18:14
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_29075.html

**Comment by spdkci** [comment] 2020-10-20 18:15
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_29066.html

**Comment by spdkci** [comment] 2020-10-20 18:20
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_29060.html

**Comment by spdkci** [comment] 2020-10-20 18:59
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_29081.html

**Comment by spdkci** [comment] 2020-10-20 19:44
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_29085.html

**Comment by spdkci** [comment] 2020-10-21 05:29
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_29058.html

**Comment by spdkci** [comment] 2020-10-21 05:46
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_29067.html

**Comment by spdkci** [comment] 2020-10-21 08:05
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_29080.html

**Comment by spdkci** [comment] 2020-10-23 00:34
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_29362.html

**Comment by spdkci** [comment] 2020-10-23 04:43
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_29394.html

**Comment by spdkci** [comment] 2020-10-23 04:46
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_29387.html

**Comment by spdkci** [comment] 2020-10-23 04:46
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_29390.html

**Comment by spdkci** [comment] 2020-10-23 05:37
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_29408.html

**Comment by spdkci** [comment] 2020-10-23 14:45
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_29420.html

**Comment by spdkci** [comment] 2020-10-23 14:47
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_29424.html

**Comment by jimharris** [comment] 2020-11-02 17:17
I know @karlatec made some CI changes that fixed this on the host that was exhibiting the problem.  We haven't seen the problem again in 10 days so closing.

**Comment by jimharris** [comment] 2020-11-03 16:27
Seeing this issue pop up again.

**Comment by jimharris** [comment] 2020-11-03 16:28
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_29934.html
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_29933.html

**Comment by karlatec** [comment] 2020-11-16 12:09
The error message:

```
00:00:32.943 Call to virDomainCreateWithFlags failed: internal error: process exited while connecting to monitor: qemu-system-x86_64: -realtime mlock=off: warning: '-realtime mlock=...' is deprecated, please use '-overcommit mem-lock=...' instead
00:00:32.943 2020-10-20T17:47:47.443254Z qemu-system-x86_64: unable to map backing store for guest RAM: Cannot allocate memory
```

suggests that the issue may have been occurring because the system hosting the VMs had been overprovisioned. While this is partly true, the issue was mostly caused by a different CI job, not related to per patch testing. This job was also spawning VMs for test, but because of misconfiguration they were not destroyed properly after the test and were hogging up the memory. This was fixed in job configuration.

**Comment by tomzawadzki** [comment] 2020-11-17 15:20
[Bug scrub] The change mentioned by Karol was merged a week ago, let's close the issue.

**Closed by tomzawadzki** 2020-11-17 15:20 UTC
Labels: Infrastructure, Intermittent Failure

**Comment by spdkci** [comment] 2021-03-04 11:46
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_37970.html
