### ISSUE TITLE
[vagrant] Mounting NFS shared folders...

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#1597] opened 2020-09-18 06:22 UTC
/var/jenkins/workspace/freebsd-vg-autotest/freebsd11-libvirt /var/jenkins/workspace/freebsd-vg-autotest

## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/26317/archive/freebsd-vg-autotest/build.log

## Execution failed at
00:01:06.965  ==> default: Exporting NFS shared folders...
00:01:06.969  ==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
00:01:07.720  ==> default: Mounting NFS shared folders...
00:15:00.329  Build timed out (after 15 minutes). Marking the build as failed.
00:15:00.342  Build was aborted

SPDK commit 792807a444528e8c0a0bee7988de615f2358be79

**Comment by wanghailiangx** [comment] 2020-09-18 06:24
Maybe this link can help, https://github.com/geerlingguy/drupal-vm/issues/245.

**Comment by spdkci** [comment] 2020-09-18 06:49
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_26317.html

**Comment by jimharris** [comment] 2020-09-18 14:46
Duplicate of #1424

**Closed by jimharris** 2020-09-18 14:46 UTC
Labels: Intermittent Failure
