### ISSUE TITLE
nvmf_tcp: Failed to construct the tqpair at the abort test case

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1607] opened 2020-09-29 13:04 UTC
Example: https://ci.spdk.io/results/autotest-per-patch/builds/27032/archive/nvmf-tcp-vg-autotest/build.log

Point of failure:
```
00:04:47.174   12:37:13	# /home/vagrant/spdk_repo/spdk/build/examples/abort -r 'trtype:tcp adrfam:IPv4 traddr:10.0.0.2 trsvcid:4420' -c 0x1
00:04:47.191  [2020-09-29 12:37:13.207408] Starting SPDK v20.10-pre git sha1 a4d3c8298 / DPDK 20.08.0 initialization...
00:04:47.191  [2020-09-29 12:37:13.207543] [ DPDK EAL parameters: [2020-09-29 12:37:13.207556] abort [2020-09-29 12:37:13.207563] --no-shconf [2020-09-29 12:37:13.207569] -c 0x1 [2020-09-29 12:37:13.207576] --no-pci [2020-09-29 12:37:13.207582] --log-level=lib.eal:6 [2020-09-29 12:37:13.207589] --log-level=lib.cryptodev:5 [2020-09-29 12:37:13.207612] --log-level=user1:6 [2020-09-29 12:37:13.207620] --iova-mode=pa [2020-09-29 12:37:13.207627] --base-virtaddr=0x200000000000 [2020-09-29 12:37:13.207634] --match-allocations [2020-09-29 12:37:13.207640] --file-prefix=spdk_pid25855 [2020-09-29 12:37:13.207647] ]
00:04:47.194  EAL: No available hugepages reported in hugepages-1048576kB
00:04:47.299  EAL: No legacy callbacks, legacy socket not created
00:04:47.338  [2020-09-29 12:37:13.359137] nvme_tcp.c:1674:nvme_tcp_qpair_icreq_send: *ERROR*: Failed to construct the tqpair=0x15b7160 via correct icresp
00:04:47.338  [2020-09-29 12:37:13.359202] nvme_tcp.c:1764:nvme_tcp_ctrlr_connect_qpair: *ERROR*: Unable to connect the tqpair
00:04:47.338  [2020-09-29 12:37:13.359214] nvme_ctrlr.c: 455:spdk_nvme_ctrlr_alloc_io_qpair: *ERROR*: nvme_transport_ctrlr_connect_io_qpair() failed
00:04:47.338  spdk_nvme_ctrlr_alloc_io_qpair failed
00:04:47.340  Initializing NVMe Controllers
00:04:47.340  Attached to NVMe over Fabrics controller at 10.0.0.2:4420: nqn.2016-06.io.spdk:cnode0
00:04:47.340  controller IO queue size 128 less than required
00:04:47.340  Consider using lower queue depth or small IO size because IO requests may be queued at the NVMe driver.
00:04:47.340  Associating TCP (addr:10.0.0.2 subnqn:nqn.2016-06.io.spdk:cnode0) NSID 1 with lcore 0
00:04:47.340  Initialization complete. Launching workers.
00:04:47.340  NS: TCP (addr:10.0.0.2 subnqn:nqn.2016-06.io.spdk:cnode0) NSID 1 I/O completed: 0, failed: 0
00:04:47.340  CTRLR: TCP (addr:10.0.0.2 subnqn:nqn.2016-06.io.spdk:cnode0) abort submitted 0, failed to submit 0
00:04:47.340  	 success 0, unsuccess 0, failed 0
00:04:47.340  /home/vagrant/spdk_repo/spdk/build/examples/abort: errors occured
00:04:47.344    12:37:13	# trap - ERR
00:04:47.344    12:37:13	# print_backtrace
00:04:47.344    12:37:13	# [[ ehxBET =~ e ]]
00:04:47.344    12:37:13	# args=("${BASH_ARGV[@]}")
00:04:47.344    12:37:13	# local args
00:04:47.344    12:37:13	# xtrace_disable
00:04:47.344    12:37:13	# '[' no '!=' yes ']'
00:04:47.344    12:37:13	# PREV_BASH_OPTS=ehxBET
00:04:47.344    12:37:13	# [[ ehxBET == *\x* ]]
00:04:47.344    12:37:13	# XTRACE_DISABLED=yes
00:04:47.344    12:37:13	# set +x
00:04:47.344  ========== Backtrace start: ==========
00:04:47.344  
00:04:47.356  in test/nvmf/target/abort.sh:28 -> main(["--transport=tcp"])
00:04:47.356       ...
00:04:47.356     23  	$rpc_py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode0 -a -s SPDK0
00:04:47.356     24  	$rpc_py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode0 Delay0
00:04:47.356     25  	$rpc_py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode0 -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_PORT
00:04:47.356     26  	
00:04:47.356     27  	# Run abort application
00:04:47.356  => 28  	$SPDK_EXAMPLE_DIR/abort -r "trtype:$TEST_TRANSPORT adrfam:IPv4 traddr:$NVMF_FIRST_TARGET_IP trsvcid:$NVMF_PORT" -c 0x1
00:04:47.356     29  	
00:04:47.356     30  	# Clean up
00:04:47.356     31  	$rpc_py nvmf_delete_subsystem nqn.2016-06.io.spdk:cnode0
00:04:47.356     32  	
00:04:47.356     33  	trap - SIGINT SIGTERM EXIT
00:04:47.356       ...
00:04:47.356  
00:04:47.356  ========== Backtrace end ==========
```

**Comment by spdkci** [comment] 2020-09-29 13:05
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_27032.html

**Comment by shuhei-matsumoto** [comment] 2020-09-29 13:28
Hi @mikeBashStuff 

Thanks for filing this issue. It looks that 

```
00:04:47.338  [2020-09-29 12:37:13.359137] nvme_tcp.c:1674:nvme_tcp_qpair_icreq_send: *ERROR*: Failed to construct the tqpair=0x15b7160 via correct icresp
00:04:47.338  [2020-09-29 12:37:13.359202] nvme_tcp.c:1764:nvme_tcp_ctrlr_connect_qpair: *ERROR*: Unable to connect the tqpair
00:04:47.338  [2020-09-29 12:37:13.359214] nvme_ctrlr.c: 455:spdk_nvme_ctrlr_alloc_io_qpair: *ERROR*: nvme_transport_ctrlr_connect_io_qpair() failed
00:04:47.338  spdk_nvme_ctrlr_alloc_io_qpair failed

```

occurred before starting the abort test. So I changed the title. Please correct me if I miss something.

**Comment by spdkci** [comment] 2020-09-29 13:29
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_27030.html

**Comment by mikeBashStuff** [comment] 2020-09-29 13:39
@shuhei-matsumoto From the log it looks to me like these `ERROR`s are coming after `abort` is executed not before. But in all honesty I am not quite sure if they were actually returned by `abort` or maybe by the `nvmf_tgt` app? Other way, title looks way better now, thanks. :)

**Comment by spdkci** [comment] 2020-09-29 13:42
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_27037.html

**Comment by AlekseyMarchuk** [comment] 2020-09-29 13:50
That happens with TPC zcopy patches. I saw such an error in CI when I started review of those patches, but I fixed it. Anyway, I'll take a look this this problem

**Comment by spdkci** [comment] 2020-09-30 08:34
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_27048.html

**Comment by spdkci** [comment] 2020-09-30 08:35
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_27035.html

**Comment by spdkci** [comment] 2020-09-30 08:35
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_27042.html

**Comment by AlekseyMarchuk** [comment] 2020-09-30 10:02
TCP zcopy requires a qpair to be connected to a poll group. I naively assumed that all IO qpairs have poll group, I forgot about other applications such as abort. I prepared a patch which fixes it https://review.spdk.io/gerrit/c/spdk/spdk/+/4476
Also Jim pushed a patch to disable zcopy, so if you see a failure in abort test then please rebase your patches

**Comment by tomzawadzki** [comment] 2020-10-06 13:30
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/4476 fixing the issue is now merged.

**Closed by tomzawadzki** 2020-10-06 13:30 UTC
Labels: Intermittent Failure
