### ISSUE TITLE
SPDK iSCSI write performance is below expectation

### ISSUE THREAD

**Issue by alantu02** [spdk/spdk#429] opened 2018-09-07 00:07 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

The configuration is as such:
                SPDK v18.07
                16 Optane drives with 8 partitions each on the target
                2 Mellanox ConnectX-4 50GbE dual ported NIC
                2 initiators targeting 64 LUNs each
                64 iSCSI connections per initiator
 
Workload is:
                4K random, 64K sequential, rd/wr/mix, Q32, 1 thread per mount point

Small and large block 100% write workloads via FIO are below expected performance, and that attainable using LIO iSCSI.

## Expected Behavior
4K random rd/wr/mix with LIO is 2.5M/**1.7M**/2.0M IOPS.
64K sequential rd/wr/mix with LIO is 10.9/**10.8**/**20.3** GB/s.

Expectation is to get at least the same performance using SPDK.

## Current Behavior
4K random rd/wr/mix with SPDK iSCSI is 2.8M/**800K**/2.0M IOPS.
64K sequential rd/wr/mix with SPDK iSCSI is 11.1/**2.0**/**3.8** GB/s.

## Steps to Reproduce
1. Start iscsi_tgt
2. iSCSI discovery on initiator
3. Start FIO workload on initiator
4. Monitor performance throughput of FIO

## Context (Environment including OS version, SPDK version, etc.)
Ubuntu 17.10
kernel 4.13.0-16-generic
SPDK v18.07
fio-3.3-22-g702b

**Comment by liang2yan** [comment] 2018-09-11 05:41
@alantu02 , can you try with latest codes? Jim has submitted patch to fix related issue.

**Comment by jimharris** [comment] 2018-09-11 18:59
My patch only fixed https://github.com/spdk/spdk/issues/428 which affects reads.

@alantu02 - would you be able to rerun this at some point with malloc bdevs instead of NVMe?  Or even null bdevs.  @vermavis can help on this.

I am certain this is an iSCSI issue but testing with malloc or null would confirm it.

**Comment by optimistyzy** [comment] 2018-09-13 07:58
@alantu02  For the write performance, it may be affected by r2t value. The default value locate in lib/iscsi/iscsi.h is :
#define DEFAULT_MAXR2T 4

Could we increase this value to conduct some tests?

**Comment by alantu02** [comment] 2018-09-14 22:15
> @alantu02 For the write performance, it may be affected by r2t value. The default value locate in lib/iscsi/iscsi.h is :
> #define DEFAULT_MAXR2T 4
> 
> Could we increase this value to conduct some tests?

@optimistyzy I have tried with increased value at 8 and at 16 with no change. 4K writes are still ~800K IOPS.

@jimharris I have configured with same number of null bdevs and 4K writes are still ~800K IOPS.

Some good news, previously when testing a bug fix for #428, large block was working, but writes were also low. Since pulling the patch, large block writes are within expectation, but small block writes are still low.

Current perf with latest patch:
4K random rd/wr/mix with SPDK iSCSI is 2.8M/800K/2.0M IOPS.
64K sequential rd/wr/mix with SPDK iSCSI is 10.8/11.1/18.7 GB/s.

**Comment by jimharris** [comment] 2018-09-19 00:11
Tried to reproduce this locally with just a loopback configuration - but was unsuccessful.  Small write performance was inline with small read performance.

Could you try using null bdevs again, but create them with 512-byte block size (the last parameter to construct_null_bdev), and do 512-byte reads and writes?

Also try increasing DEFAULT_MAXOUTSTANDINGR2T from 1 to 16.  I really don't think this should make any difference - these are smaller than the immediate data size (8192) so R2T should never happen.  But if changing this makes a difference, we will know where to look next.

Could you also post the config file or RPC script you are using?

Thanks,

-Jim

**Comment by alantu02** [comment] 2018-09-20 20:35
@liang2yan The attached config files are using coremask 0xFFFFFF, with each portal group getting 6 cores. Once peak performance was measured under this config, my intent is to start scaling down cores to determine the minimum number needed to reach peak performance.

FIO jobfile looks like this:
[global]
blocksize=512B
rw=randrw
rwmixread=0
ioengine=libaio
direct=1
randrepeat=1
iodepth=32
ramp_time=30
runtime=180
time_based
thread
group_reporting
numjobs=1
[sdb]
filename=/dev/sdb
....................................
[sdbm]
filename=/dev/sdbm

**Comment by liang2yan** [comment] 2018-09-25 11:46
@alantu02 , I used same coremask and fiojob file. My result is as below:
```
512 Byte randread:  2022K IOPS
512 Byte randwrite:  991K IOPS
512 Byte randrw:     2159K IOPS
```

The randwrite is too low comparing to randread and randrw.

**Comment by jimharris** [comment] 2018-10-25 04:37
@alantu02 - could you re-run your test with the latest SPDK master when you have a chance?  We recently found an issue with setting O_NONBLOCK on iSCSI TCP sockets - it's possible this was affecting the random write performance.

**Comment by wanqunintel** [comment] 2018-11-01 04:53
@alantu02 , do you have time to test it, or we may ask @vermavis to retest it?

**Comment by alantu02** [comment] 2018-11-06 18:07
I pulled the latest 18.10 version and I'm not seeing much difference in 4K random write performance.

Current perf with 18.10:
4K random rd/wr/mix with SPDK iSCSI is 2.8M/840K/2.0M IOPS.
64K sequential rd/wr/mix with SPDK iSCSI is 11.1/11.1/19.0 GB/s.

**Comment by optimistyzy** [comment] 2018-12-24 04:31
@alantu02  @liang2yan  could you try the following patch:

https://review.gerrithub.io/#/c/spdk/spdk/+/438149 

I checked the code. For the small writes, it will be allocated the all the buffers from this pool, so change the cache size may help.

**Comment by optimistyzy** [comment] 2018-12-24 08:32
I think this is the root cause of small write i/o

**Comment by vermavis** [comment] 2018-12-24 18:41
Great! Thanks @optimistyzy for root causing and @liang2yan for verifying the fix!
@alantu02 could you also rerun and let us know how much you see in your configuration with Ziye's fix?

@optimistyzy Is there any trade-off when increasing the cache size of immediate data pool?

**Comment by optimistyzy** [comment] 2018-12-25 01:30
@vermavis  I checked the code, for other mempool, it all allocates the cache size. With the Cache, it could improve the performance.  Currently, I think that we can just use 256 as the default value, which is OK.

**Comment by darsto** [comment] 2019-01-02 11:12
Patch merged. Closing.

Thanks!

**Closed by darsto** 2019-01-02 11:12 UTC
Labels: Medium, bug

**Comment by jimharris** [comment] 2019-01-02 17:05
Should we wait for @alantu02's confirmation before closing?

This patch makes sense - @alantu02 was using a big core mask (24 cores total) so without a per-core cache, all 24 cores would be thrashing on the lock for the common pool.  I'd still feel more comfortable if @alantu02 was able to confirm the fix though.

**Comment by alantu02** [comment] 2019-01-02 17:53
Yes, this fixes the small block write IOPS issue. Performance is meeting expectation up to 2.0M IOPS. Thanks for all the support!

**Comment by vermavis** [comment] 2019-01-02 18:36
Thanks @alantu02 
I think you were getting 2.8M for 4K reads right? I'd expect writes to be close to reads, and what about 70-30 mix? Just want to be sure that performance matches expectations.


Thanks,
Vishal

**Comment by alantu02** [comment] 2019-01-03 06:02
Performance is with 16 NVMe, using all 24 physical cores of a 2S system: 2.8M Read, 2.3M write, 2.7M 7030.

**Comment by vermavis** [comment] 2019-01-03 16:17
OK- thanks @alantu02 for confirming!
I think the numbers are close to expectation in Alan's configuration with per-core cache patch from Ziye. Go ahead and close this issue.
