### ISSUE TITLE
[nvmf-tcp-phy-autotest] Failed to init the trace resource

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#2077] opened 2021-08-09 02:10 UTC
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/55332/archive/nvmf-tcp-phy-autotest/build.log

## Execution failed at

00:04:27.552  EAL: No available 1048576 kB hugepages reported
00:04:27.556  TELEMETRY: No legacy callbacks, legacy socket not created
00:04:27.589  [2021-08-09 03:40:07.151595] app.c: 540:spdk_app_start: *NOTICE*: Total cores available: 4
00:04:27.704  [2021-08-09 03:40:07.266747] trace.c: 188:spdk_trace_init: *ERROR*: could not shm_open spdk_trace
00:04:27.704  [2021-08-09 03:40:07.266827] trace.c: 189:spdk_trace_init: *ERROR*: errno=13 Permission denied
00:04:28.162  /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/common/autotest_common.sh: line 710: kill: (265977) - No such process
00:04:28.162  ERROR: process (pid: 265977) is no longer running
00:04:28.163   03:40:07	-- spdk/test/common/autotest_common.sh@723 -- # xtrace_enable
00:04:28.163   03:40:07	-- spdk/test/common/autotest_common.sh@724 -- # (( i == 0 ))
00:04:28.163   03:40:07	-- spdk/test/common/autotest_common.sh@728 -- # return 1
00:04:28.164    03:40:07	-- spdk/test/nvmf/common.sh@452 -- # trap - ERR
00:04:28.164    03:40:07	-- spdk/test/nvmf/common.sh@452 -- # print_backtrace
00:04:28.164    03:40:07	-- spdk/test/common/autotest_common.sh@985 -- # [[ ehxBET =~ e ]]
00:04:28.164    03:40:07	-- spdk/test/common/autotest_common.sh@987 -- # args=("${BASH_ARGV[@]}")
00:04:28.165    03:40:07	-- spdk/test/common/autotest_common.sh@987 -- # local args
00:04:28.165    03:40:07	-- spdk/test/common/autotest_common.sh@989 -- # xtrace_disable
00:04:28.165    03:40:07	-- spdk/test/common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:04:28.165    03:40:07	-- spdk/test/common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:04:28.165    03:40:07	-- spdk/test/common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:04:28.166    03:40:07	-- spdk/test/common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:04:28.166    03:40:07	-- spdk/test/common/autotest_common.sh@19 -- # set +x
00:04:28.166  ========== Backtrace start: ==========

**Comment by spdkci** [comment] 2021-08-09 02:15
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_55561.html

**Comment by tomzawadzki** [comment] 2021-08-09 11:41
Duplicate of #2041

**Closed by tomzawadzki** 2021-08-09 11:41 UTC
Labels: Intermittent Failure
