### ISSUE TITLE
[json_config] QAT failed to initialize

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1709] opened 2020-11-30 22:20 UTC
https://ci.spdk.io/public_build/autotest-per-patch_31217.html

00:02:49.994  ************************************
00:02:49.994  START TEST json_config
00:02:49.994  ************************************
00:02:49.994   22:53:12	# xtrace_enable
00:02:49.995   22:53:12	# ./test/json_config/json_config.sh
00:02:50.025    22:53:12	# xtrace_enable
00:02:50.025   22:53:12	# source /var/jenkins/workspace/crypto-autotest/spdk/test/nvmf/common.sh
00:02:50.025    22:53:12	# NVMF_PORT=4420
00:02:50.025    22:53:12	# NVMF_SECOND_PORT=4421
00:02:50.025    22:53:12	# NVMF_THIRD_PORT=4422
00:02:50.025    22:53:12	# NVMF_IP_PREFIX=192.168.100
00:02:50.026    22:53:12	# NVMF_IP_LEAST_ADDR=8
00:02:50.026    22:53:12	# NVMF_TCP_IP_ADDRESS=127.0.0.1
00:02:50.026    22:53:12	# NVMF_TRANSPORT_OPTS=
00:02:50.026    22:53:12	# NVMF_SERIAL=SPDK00000000000001
00:02:50.026    22:53:12	# : 0
00:02:50.026    22:53:12	# export NVMF_APP_SHM_ID
00:02:50.026    22:53:12	# build_nvmf_app_args
00:02:50.026    22:53:12	# '[' 0 -eq 1 ']'
00:02:50.026    22:53:12	# NVMF_APP+=(-i "$NVMF_APP_SHM_ID" -e 0xFFFF)
00:02:50.026    22:53:12	# have_pci_nics=0
00:02:50.027   22:53:12	# [[ 0 -eq 1 ]]
00:02:50.027   22:53:12	# [[ 0 -ne 1 ]]
00:02:50.027   22:53:12	# [[ 0 -eq 1 ]]
00:02:50.027   22:53:12	# (( SPDK_TEST_BLOCKDEV + 	SPDK_TEST_ISCSI + 	SPDK_TEST_NVMF + 	SPDK_TEST_VHOST + 	SPDK_TEST_VHOST_INIT + 	SPDK_TEST_PMDK + 	SPDK_TEST_RBD == 0 ))
00:02:50.027   22:53:12	# app_pid=([target]="" [initiator]="")
00:02:50.027   22:53:12	# declare -A app_pid
00:02:50.027   22:53:12	# app_socket=([target]='/var/tmp/spdk_tgt.sock' [initiator]='/var/tmp/spdk_initiator.sock')
00:02:50.027   22:53:12	# declare -A app_socket
00:02:50.028   22:53:12	# app_params=([target]='-m 0x1 -s 1024' [initiator]='-m 0x2 -g -u -s 1024')
00:02:50.028   22:53:12	# declare -A app_params
00:02:50.028   22:53:12	# configs_path=([target]="$rootdir/spdk_tgt_config.json" [initiator]="$rootdir/spdk_initiator_config.json")
00:02:50.028   22:53:12	# declare -A configs_path
00:02:50.028   22:53:12	# RE_UUID='[[:alnum:]-]+'
00:02:50.029   22:53:12	# last_event_id=0
00:02:50.029   22:53:12	# trap 'on_error_exit "${FUNCNAME}" "${LINENO}"' ERR
00:02:50.029   22:53:12	# echo 'INFO: JSON configuration test init'
00:02:50.029  INFO: JSON configuration test init
00:02:50.029   22:53:12	# json_config_test_init
00:02:50.029   22:53:12	# timing_enter json_config_test_init
00:02:50.029   22:53:12	# xtrace_disable
00:02:50.029   22:53:12	# '[' '' '!=' yes ']'
00:02:50.029   22:53:12	# PREV_BASH_OPTS=ehxBET
00:02:50.029   22:53:12	# [[ ehxBET == *\x* ]]
00:02:50.029   22:53:12	# XTRACE_DISABLED=yes
00:02:50.029   22:53:12	# set +x
00:02:50.030   22:53:12	# xtrace_enable
00:02:50.030   22:53:12	# timing_enter json_config_setup_target
00:02:50.030   22:53:12	# xtrace_disable
00:02:50.030   22:53:12	# '[' no '!=' yes ']'
00:02:50.030   22:53:12	# PREV_BASH_OPTS=ehxBET
00:02:50.030   22:53:12	# [[ ehxBET == *\x* ]]
00:02:50.030   22:53:12	# XTRACE_DISABLED=yes
00:02:50.030   22:53:12	# set +x
00:02:50.032   22:53:12	# xtrace_enable
00:02:50.032   22:53:12	# json_config_test_start_app target --wait-for-rpc
00:02:50.032   22:53:12	# local app=target
00:02:50.032   22:53:12	# shift
00:02:50.032   22:53:12	# [[ -n 22 ]]
00:02:50.032   22:53:12	# [[ -z '' ]]
00:02:50.032   22:53:12	# local app_extra_params=
00:02:50.032   22:53:12	# [[ 0 -eq 1 ]]
00:02:50.032   22:53:12	# [[ 0 -eq 1 ]]
00:02:50.032   22:53:12	# app_pid[$app]=381258
00:02:50.033   22:53:12	# echo 'Waiting for target to run...'
00:02:50.033  Waiting for target to run...
00:02:50.033   22:53:12	# waitforlisten 381258 /var/tmp/spdk_tgt.sock
00:02:50.033   22:53:12	# /var/jenkins/workspace/crypto-autotest/spdk/build/bin/spdk_tgt -m 0x1 -s 1024 -r /var/tmp/spdk_tgt.sock --wait-for-rpc
00:02:50.033   22:53:12	# '[' -z 381258 ']'
00:02:50.033   22:53:12	# local rpc_addr=/var/tmp/spdk_tgt.sock
00:02:50.033   22:53:12	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk_tgt.sock...'
00:02:50.033  Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk_tgt.sock...
00:02:50.033   22:53:12	# xtrace_disable
00:02:50.033   22:53:12	# '[' no '!=' yes ']'
00:02:50.033   22:53:12	# PREV_BASH_OPTS=ehxBET
00:02:50.033   22:53:12	# [[ ehxBET == *\x* ]]
00:02:50.034   22:53:12	# XTRACE_DISABLED=yes
00:02:50.034   22:53:12	# set +x
00:02:50.062  [2020-11-30 22:53:12.453054] Starting SPDK v21.01-pre git sha1 33f123b6a / DPDK 20.08.0 initialization...
00:02:50.062  [2020-11-30 22:53:12.453167] [ DPDK EAL parameters: [2020-11-30 22:53:12.453194] spdk_tgt [2020-11-30 22:53:12.453202] --no-shconf [2020-11-30 22:53:12.453208] -c 0x1 [2020-11-30 22:53:12.453215] -m 1024 [2020-11-30 22:53:12.453222] --log-level=lib.eal:6 [2020-11-30 22:53:12.453229] --log-level=lib.cryptodev:5 [2020-11-30 22:53:12.453236] --log-level=user1:6 [2020-11-30 22:53:12.453243] --base-virtaddr=0x200000000000 [2020-11-30 22:53:12.453250] --match-allocations [2020-11-30 22:53:12.453257] --file-prefix=spdk_pid381258 [2020-11-30 22:53:12.453263] ]
00:02:50.094  EAL: No free hugepages reported in hugepages-2048kB
00:02:50.094  EAL: No available hugepages reported in hugepages-1048576kB
00:02:50.619  CRYPTODEV: rte_cryptodev_pmd_create() line 110: Failed to allocate crypto device for 0000:84:01.0_qat_sym
00:02:50.619  qat_pci_probe(): Failed to create QAT SYM PMD on device 0000:84:01.0_qat
00:02:50.619  rte_compressdev_pmd_create(): Failed to allocate comp device 0000:84:01.0_qat_comp
00:02:50.619  qat_pci_probe(): Failed to create QAT COMP PMD on device 0000:84:01.0_qat
00:02:50.620  CRYPTODEV: rte_cryptodev_pmd_create() line 110: Failed to allocate crypto device for 0000:84:01.1_qat_sym
00:02:50.620  qat_pci_probe(): Failed to create QAT SYM PMD on device 0000:84:01.1_qat
00:02:50.620  rte_compressdev_pmd_create(): Failed to allocate comp device 0000:84:01.1_qat_comp
00:02:50.620  qat_pci_probe(): Failed to create QAT COMP PMD on device 0000:84:01.1_qat
00:02:50.620  CRYPTODEV: rte_cryptodev_pmd_create() line 110: Failed to allocate crypto device for 0000:84:01.2_qat_sym

This eventually results in this failure which results in the actual CI failure:

00:02:55.941   22:53:18	# tgt_rpc bdev_malloc_create 8 1024 --name MallocForCryptoBdev
00:02:55.941   22:53:18	# /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_malloc_create 8 1024 --name MallocForCryptoBdev
00:02:56.076  MallocForCryptoBdev
00:02:56.084    22:53:18	# lspci -d:37c8
00:02:56.084    22:53:18	# wc -l
00:02:56.106   22:53:18	# [[ 3 -eq 0 ]]
00:02:56.106   22:53:18	# local crypto_dirver=crypto_qat
00:02:56.106   22:53:18	# tgt_rpc bdev_crypto_create MallocForCryptoBdev CryptoMallocBdev crypto_qat 0123456789123456
00:02:56.107   22:53:18	# /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_crypto_create MallocForCryptoBdev CryptoMallocBdev crypto_qat 0123456789123456
00:02:56.265  [2020-11-30 22:53:18.655733] vbdev_crypto.c:1768:vbdev_crypto_claim: *NOTICE*: QAT in use: Required alignment set to 10
00:02:56.265  [2020-11-30 22:53:18.655793] vbdev_crypto.c:1771:vbdev_crypto_claim: *NOTICE*: QAT using cipher: AES_CBC
00:02:56.265  [2020-11-30 22:53:18.655811] vbdev_crypto.c:1830:vbdev_crypto_claim: *ERROR*: ERROR can't match crypto device driver to crypto vbdev!
00:02:56.269  request:
00:02:56.269  {
00:02:56.269    "base_bdev_name": "MallocForCryptoBdev",
00:02:56.269    "name": "CryptoMallocBdev",
00:02:56.269    "crypto_pmd": "crypto_qat",
00:02:56.269    "key": "0123456789123456",
00:02:56.269    "cipher": "AES_CBC",
00:02:56.269    "method": "bdev_crypto_create",
00:02:56.269    "req_id": 1
00:02:56.269  }
00:02:56.269  Got JSON-RPC error response
00:02:56.269  response:
00:02:56.269  {
00:02:56.269    "code": -22,
00

**Comment by spdkci** [comment] 2020-11-30 22:21
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_31217.html

**Comment by spdkci** [comment] 2020-12-01 04:36
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_31250.html

**Comment by spdkci** [comment] 2020-12-01 04:47
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_31248.html

**Comment by spdkci** [comment] 2020-12-01 05:22
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_31251.html

**Comment by spdkci** [comment] 2020-12-01 06:01
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_31241.html

**Comment by spdkci** [comment] 2020-12-01 06:52
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_31255.html

**Comment by spdkci** [comment] 2020-12-01 11:19
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_31257.html

**Comment by tomzawadzki** [comment] 2020-12-01 14:17
I just wonder if this is not a duplicate of #1347. The final result is the same, but qat_setup.sh is bit different:
```
00:02:39.513  modprobe: ERROR: could not insert 'usdm_drv': Unknown symbol in module, or unknown parameter (see dmesg)
00:02:39.529  Restarting all devices.
00:02:39.529  Failed to stop device 
00:02:39.532  enable sriov
00:02:39.554  Cannot enable SRIOV for qat_dev0. No sriov_numvs file
00:02:39.554  failed to start the qat service. Something may be wrong with your 01.org driver.
00:02:40.516  0000:84:00.0 set to 16 VFs
00:02:41.485  0000:85:00.0 set to 16 VFs
00:02:42.453  0000:86:00.0 set to 16 VFs
00:02:42.772  Properly configured the qat devic
```

This most likely should be resolved within same fixes as in #1347.

**Comment by spdkci** [comment] 2020-12-01 17:58
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_31353.html

**Comment by spdkci** [comment] 2020-12-01 18:00
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_31352.html

**Comment by jimharris** [comment] 2020-12-01 18:00
This is happening on multiple systems - I've seen failures on GP3, GP5 and GP6 so far.

**Comment by spdkci** [comment] 2020-12-04 02:41
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_31258.html

**Comment by mikeBashStuff** [comment] 2020-12-04 12:10
After some investigation, it seems that this issue differs from #1347. 

The problem seems to be related to the fact that on the affected systems, instead of the out-of-tree qat modules, upstream once were being loaded into the kernel early on, during the initramfs stage. However, when the rootfs is finally switched, modprobe sees out-of-tree modules in the dependencies and when `qat_service` attempts to load them, it simply fails: `modprobe: ERROR: could not insert 'usdm_drv': Unknown symbol in module, or unknown parameter` - this complains about missing symbols which are not compiled in the upstream `intel_qat`.  When I unloaded the `intel_qat` (and its holders) and then loaded the proper one, everything started to work again (`qat_service` was able to init all devices, load remaining qat modules, etc).

Now,  this `cannot enable SRIOV for qat_dev0. No sriov_numvs file` was a red herring returned by `qat_service` which was looking up improper pci addresses (`adf_ctl` was returning non-existent BDFs, probably due to wrong drivers being in place or the lack thereof). 

As this seems to be specific to Fedora (well, to be precise, to dracut), adding something like ` rd.driver.blacklist=qat_c62x` to kernel cmdline seems to prevent loading of the qat modules early on so when the actual init is execed, proper ones are loaded instead. Also, I committed the following patch as a mitigation: https://review.spdk.io/gerrit/c/spdk/spdk/+/5451 - this should reload `intel_qat` and remainig `qat_*` drivers to make sure out-of-tree ones are actually in use.

**Comment by spdkci** [comment] 2020-12-04 13:34
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_31566.html

**Comment by mikeBashStuff** [comment] 2020-12-06 22:25
Need to refine a bit my previous comment. The issue is not with dracut per se, but rather with contents of the initramfs on the affected system. This is basically what happens early on, inside initramfs (example from GP5):

```
[root@GrizzlyPass5 test]# lsinitrd --unpack /boot/initramfs-$(</proc/sys/kernel/osrelease).img
[root@GrizzlyPass5 test]# for v in {proc,dev,sys}; do mount --bind "/$v" "$v"; done
[root@GrizzlyPass5 test]# for d in /sys/bus/pci/drivers/c6xx/0000:*; do chroot . udevadm test --action=add "$d"; done |& grep kmod
# This is what early udev finds:
run: 'kmod load pci:v00008086d000037C8sv00008086sd00000002bc0Bsc40i00'
run: 'kmod load pci:v00008086d000037C8sv00008086sd00000002bc0Bsc40i00'
run: 'kmod load pci:v00008086d000037C8sv00008086sd00000002bc0Bsc40i00'
[root@GrizzlyPass5 test]# chroot . modprobe --show-depends "pci:v00008086d000037C8sv00008086sd00000002bc0Bsc40i00"
# And this is what it loads - these are the modules shipped with Fedora's kernel
insmod /lib/modules/5.7.17-200.fc32.x86_64/kernel/crypto/authenc.ko.xz
insmod /lib/modules/5.7.17-200.fc32.x86_64/kernel/drivers/crypto/qat/qat_common/intel_qat.ko.xz
insmod /lib/modules/5.7.17-200.fc32.x86_64/kernel/drivers/crypto/qat/qat_c62x/qat_c62x.ko.xz

# What we need, and what's seen after the final swith_root:
[root@GrizzlyPass5 test]# modprobe --show-depends "pci:v00008086d000037C8sv00008086sd00000002bc0Bsc40i00"
insmod /lib/modules/5.7.17-200.fc32.x86_64/kernel/drivers/uio/uio.ko.xz
insmod /lib/modules/5.7.17-200.fc32.x86_64/updates/drivers/crypto/qat/qat_common/intel_qat.ko 
insmod /lib/modules/5.7.17-200.fc32.x86_64/updates/drivers/crypto/qat/qat_c62x/qat_c62x.ko
 
```
So the mitigation on the system's side is to either rebuild the initrd to include `updates/drivers` (where the out-of-tree modules are stored) or use `rd.driver.blacklist` as mentioned in the previous comment.

**Comment by spdkci** [comment] 2020-12-07 05:59
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_31624.html

**Comment by spdkci** [comment] 2020-12-08 08:51
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_31649.html

**Comment by spdkci** [comment] 2020-12-08 23:24
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_31731.html

**Comment by changpe1** [comment] 2020-12-10 02:32
> Need to refine a bit my previous comment. The issue is not with dracut per se, but rather with contents of the initramfs on the affected system. This is basically what happens early on, inside initramfs (example from GP5):
> 
> ```
> [root@GrizzlyPass5 test]# lsinitrd --unpack /boot/initramfs-$(</proc/sys/kernel/osrelease).img
> [root@GrizzlyPass5 test]# for v in {proc,dev,sys}; do mount --bind "/$v" "$v"; done
> [root@GrizzlyPass5 test]# for d in /sys/bus/pci/drivers/c6xx/0000:*; do chroot . udevadm test --action=add "$d"; done |& grep kmod
> # This is what early udev finds:
> run: 'kmod load pci:v00008086d000037C8sv00008086sd00000002bc0Bsc40i00'
> run: 'kmod load pci:v00008086d000037C8sv00008086sd00000002bc0Bsc40i00'
> run: 'kmod load pci:v00008086d000037C8sv00008086sd00000002bc0Bsc40i00'
> [root@GrizzlyPass5 test]# chroot . modprobe --show-depends "pci:v00008086d000037C8sv00008086sd00000002bc0Bsc40i00"
> # And this is what it loads - these are the modules shipped with Fedora's kernel
> insmod /lib/modules/5.7.17-200.fc32.x86_64/kernel/crypto/authenc.ko.xz
> insmod /lib/modules/5.7.17-200.fc32.x86_64/kernel/drivers/crypto/qat/qat_common/intel_qat.ko.xz
> insmod /lib/modules/5.7.17-200.fc32.x86_64/kernel/drivers/crypto/qat/qat_c62x/qat_c62x.ko.xz
> 
> # What we need, and what's seen after the final swith_root:
> [root@GrizzlyPass5 test]# modprobe --show-depends "pci:v00008086d000037C8sv00008086sd00000002bc0Bsc40i00"
> insmod /lib/modules/5.7.17-200.fc32.x86_64/kernel/drivers/uio/uio.ko.xz
> insmod /lib/modules/5.7.17-200.fc32.x86_64/updates/drivers/crypto/qat/qat_common/intel_qat.ko 
> insmod /lib/modules/5.7.17-200.fc32.x86_64/updates/drivers/crypto/qat/qat_c62x/qat_c62x.ko
>  
> ```
> 
> So the mitigation on the system's side is to either rebuild the initrd to include `updates/drivers` (where the out-of-tree modules are stored) or use `rd.driver.blacklist` as mentioned in the previous comment.

Agreed.

[10178.545066] usdm_drv: loading out-of-tree module taints kernel.
[10178.545158] usdm_drv: module verification failed: signature and/or required key missing - tainting kernel
[10178.545281] usdm_drv: Unknown symbol qdm_iommu_unmap (err -2)
[10178.545429] usdm_drv: Unknown symbol qdm_iommu_map (err -2)
[10178.575622] QAT: Invalid ioctl

**Comment by spdkci** [comment] 2020-12-11 00:49
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_31860.html

**Comment by tomzawadzki** [comment] 2020-12-15 12:04
@mikeBashStuff patch https://review.spdk.io/gerrit/c/spdk/spdk/+/5451/ was merged.
 Does this resolve this particular issue fully ?

**Comment by spdkci** [comment] 2020-12-15 14:55
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_32284.html

**Comment by tomzawadzki** [comment] 2020-12-15 15:09
[Bug scrub] The above report is for patch that needs a rebase. As for the issue, let's leave it open till the end of the week.

**Comment by karlatec** [comment] 2021-01-14 12:37
> As for the issue, let's leave it open till the end of the week.

It's been a long week it seems ;) @tomzawadzki @mikeBashStuff  ok to close?

**Comment by mikeBashStuff** [comment] 2021-01-14 12:43
@karlatec Most definitely, yes! :)

**Closed** 2021-01-14 13:44 UTC
Labels: Intermittent Failure
