### ISSUE TITLE
[vhost-boot] Device reports MEDIUM NOT PRESENT

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2521] opened 2022-05-19 15:22 UTC
00:12:27.137  pci dev 00:04.0 virtio cap at 0x40 type 1 bar 4 at 0xfe000000 off +0x0000 [mmio]
00:12:27.137  pci dev 00:04.0 using modern (1.0) virtio mode
00:12:27.137  DVD/CD [ata1-0: QEMU DVD-ROM ATAPI-4 DVD/CD]
00:12:27.137  Searching bootorder for: /pci@i0cf8/*@1,1/drive@1/disk@0
00:12:27.137  Searching bios-geometry for: /pci@i0cf8/*@1,1/drive@1/disk@0
00:12:27.137  Device reports MEDIUM NOT PRESENT
00:12:27.137  Found 1 lpt ports
00:12:27.137  Found 1 serial ports
00:12:27.137  PS2 keyboard initialized
00:12:27.137  WARN: ================
00:12:27.137   20:21:41	-- vhost/common.sh@941 -- # xtrace_enable
00:12:27.137   20:21:41	-- vhost/common.sh@942 -- # return 1
00:12:27.137    20:21:41	-- vhost_boot/vhost_boot.sh@101 -- # err_clean '' 101
00:12:27.137    20:21:41	-- vhost_boot/vhost_boot.sh@14 -- # trap - ERR
00:12:27.137    20:21:41	-- vhost_boot/vhost_boot.sh@15 -- # print_backtrace
00:12:27.137    20:21:41	-- common/autotest_common.sh@998 -- # [[ ehxBET =~ e ]]
00:12:27.137    20:21:41	-- common/autotest_common.sh@1000 -- # args=('101' '' '--vm_image=/root/spdk_dependencies/spdk_test_image.qcow2')
00:12:27.137    20:21:41	-- common/autotest_common.sh@1000 -- # local args
00:12:27.137    20:21:41	-- common/autotest_common.sh@1002 -- # xtrace_disable
00:12:27.137    20:21:41	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:12:27.137    20:21:41	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:12:27.137    20:21:41	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:12:27.137    20:21:41	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:12:27.137    20:21:41	-- common/autotest_common.sh@19 -- # set +x
00:12:27.137  ========== Backtrace start: ==========
00:12:27.137  
00:12:27.137  in /var/jenkins/workspace/vhost-autotest/spdk/test/vhost/vhost_boot/vhost_boot.sh:15 -> err_clean([""],["101"])
00:12:27.137       ...
00:12:27.137     10  	rpc_py="$rootdir/scripts/rpc.py -s $(get_vhost_dir 0)/rpc.sock"
00:12:27.137     11  	vm_no="0"
00:12:27.137     12  	
00:12:27.137     13  	function err_clean() {
00:12:27.137     14  		trap - ERR
00:12:27.137  => 15  		print_backtrace

**Comment by spdkci** [comment] 2022-05-19 15:23
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_77547.html

**Comment by ksztyber** [comment] 2022-05-20 12:51
This is a duplicate of #2518. Closing.

**Closed by ksztyber** 2022-05-20 12:51 UTC
Labels: Intermittent Failure
