### ISSUE TITLE
SPDK NVMe-oF TCP Initiator latency increase

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1881] opened 2021-04-08 11:38 UTC
## Current Behavior

NVMe-oF latency increased due to recent merges on master branch.
Between de8f3a50ee and a620cd198f commits average TCP latency using SPDK Target and SPDK Initiator increased from ~35usec  to ~57usec.

Additional observations:
- IOPS in QD=1 latency test using this configuration are affected as well (50-70% drop)
- In case of higher QD tests (QD=128) and more CPUs, subsystems in configuration I noticed up to 10% IOPS drop

## Possible Solution

```
git log de8f3a50ee..a620cd198f --oneline
a620cd198 nvme/tcp: Fix the zero copy enablement issue.
48c057814 test/idxd: fix allocation issue with unit test
26fdb2d8b lib/idxd: remove unsed config elements and add a config print
```

`a620cd198 nvme/tcp: Fix the zero copy enablement issue.` seems to be the faulty change.

Test results:
```
(with a620cd198  in place)
IOPS       Bandwidth   AvgLat(usec)
3968.06    15872       251.76
3968.06    15872       251.77
3968.10    15872       251.78

(with a620cd198  reverted)
IOPS       Bandwidth   AvgLat(usec)
22042.56   88170       45.14
21980.23   87920       45.25
21509.51   86038       46.28

```

## Steps to Reproduce

1. Run SPDK NVMe-oF TCP Target - single core, single subsystem with single null bdev attached as subsystem
2. Run SPDK NVMe-oF TCP Initiator; using spdk fio bdev plugin here:
```
cat nvmf_perf/4k_1_randread_m_100_1CPU.fio

[global]
ioengine=/tmp/spdk/build/fio/spdk_bdev
spdk_json_conf=/tmp/spdk/bdev.conf
thread=1
group_reporting=1
direct=1
percentile_list=50:90:99:99.5:99.9:99.99:99.999

norandommap=1
rw=randread
rwmixread=100
bs=4k
time_based=1
ramp_time=0
runtime=30
numjobs=1

[filename0]
filename=Nvme0n1
iodepth=1
```

```
cat bdev.conf
{
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "method": "bdev_nvme_attach_controller",
          "params": {
            "name": "Nvme0",
            "trtype": "tcp",
            "traddr": "20.0.0.1",
            "trsvcid": "4420",
            "subnqn": "nqn.2018-09.io.spdk:cnode0",
            "adrfam": "IPv4"
          }
        }
      ]
    }
  ]
}

```

## Context (Environment including OS version, SPDK version, etc.)

SPDK `c3853598b` and `a620cd198 `

**Comment by AlekseyMarchuk** [comment] 2021-04-08 12:26
Hey @karlatec the patch a620cd198 fixed zcopy in TCP initiator, but with this patch zcopy works in a bit different way. Previously sockets were attached to a poll_group and `_sock_check_zcopy` function from posix.c was called once per poll_group poll. Now sockets are not attached to a poll_group and `_sock_check_zcopy` is called by every qpair. I think there is possible performance impact. Could you check performance with commit 2f1cd867f3dedb1213e700eb042ba8c62a2afe9f - this is a parent commit of 579a678a51d511a788fca8ed3e48064cd02cb724 which changed socket creation logic (it was fixed in a620cd198)
I also would expect some degradation on small payloads caused by zcopy itself but in that case you are running randread and it should be affected

**Comment by AlekseyMarchuk** [comment] 2021-04-08 13:06
Probably I was wrong, since just after creating a socket, it is added to a poll_group and everything should work as before
Could you add the following to bdev.conf and measure latency again?
```
    {
      "subsystem": "sock",
      "config": [
        {
          "method": "sock_impl_set_options",
          "params": {
            "impl_name": "posix",
            "recv_buf_size": 2097152,
            "send_buf_size": 2097152,
            "enable_recv_pipe": true,
            "enable_zerocopy_send": false,
            "enable_quickack": false,
            "enable_placement_id": 0
          }
        }
      ]
    }

```

**Comment by optimistyzy** [comment] 2021-04-09 05:58
> Probably I was wrong, since just after creating a socket, it is added to a poll_group and everything should work as before
> Could you add the following to bdev.conf and measure latency again?
> 
> ```
>     {
>       "subsystem": "sock",
>       "config": [
>         {
>           "method": "sock_impl_set_options",
>           "params": {
>             "impl_name": "posix",
>             "recv_buf_size": 2097152,
>             "send_buf_size": 2097152,
>             "enable_recv_pipe": true,
>             "enable_zerocopy_send": false,
>             "enable_quickack": false,
>             "enable_placement_id": 0
>           }
>         }
>       ]
>     }
> ```

Hi  @karlatec ,
 I agree with @AlekseyMarchuk . This patch will not change anything, the only thing to address is to change the configuration like Alex suggested.

**Comment by karlatec** [comment] 2021-04-13 09:13
@AlekseyMarchuk Checked with your config, IOPS and latency look better now. So as I understand disabling zcopy on the initiator side has an impact, right `"enable_zerocopy_send": false,`? I think it's the only line which is different than default settings for `scripts/rpc.py sock_impl_get_options -i posix`

**Comment by AlekseyMarchuk** [comment] 2021-04-13 09:41
Yes, my config disables zcopy in initiator.  I noticed some impact when I was implementing this feature, but it was rather small. In your case it is significant, I can't explain why. I would also expect similar effect on target side. Have your tried to compare performance with/without zero copy on target side?
I'm adding bug scrub label to discuss this issue, probably we should disable zero copy by default (again)

**Comment by karlatec** [comment] 2021-04-13 10:01
4k randread QD=1 workload

Zerocopy disabled on both target and initiator side:
```
IOPS      AvgLat(usec)
6238      159.7
6250      159.6
6436      155.4
```

Zerocopy disabled on target side, enabled on initiator side:
```
IOPS      AvgLat(usec)
3967      251.8
3970      250.2
3968      251.77
```

Zerocopy enabled on target side, disabled on initiator side:
```
IOPS      AvgLat(usec)
22800     43.6
21700     50.6
25800     40.1
```

Zerocopy enabled on both target and initiator side:
```
IOPS      AvgLat(usec)
3970      251.7
3967      251.7
3968      251.5
```

>  In your case it is significant, I can't explain why

Have you tested with QD=1? For higher queue depths, e.g. QD=128, I noticed visible but less drastic drop of about 10%.

**Comment by AlekseyMarchuk** [comment] 2021-04-13 10:17
Thanks @karlatec I need to investigate this performance degradation. I'm assigning this issue to myself.
As I remember I checked performance with higher queue depths like 64, 128

**Comment by AlekseyMarchuk** [comment] 2021-04-13 10:56
Hmm, I don't think that we need to investigate this degradation, zero copy on initiator side degrades performance due to the nature of NVMF protocol. IOPS statistics are reported by initiator when a request is completed. The request is completed when we receive 1. response from target 2. notification from error queue. 
That means that enabling zero copy send on target doesn't affect latency in both read and write flow. In read flow (target sends c2h) target uses `c2h_success` by default and adds a flag to c2h capsule indicating that the request can be completed. In write flow target sends a response and waiting for error queue notification doesn't affect initiator.
I think we should again disable zero copy send. Need to think how we can disable it for initiator only

**Comment by karlatec** [comment] 2021-04-13 13:25
@AlekseyMarchuk one important information which I see I've forgot to include in the original issue description. 

See that in the original description I wrote: `latency increased from ~35usec to ~57usec`, which doesn't match 250usec latency I mention later. I think I lost focus when creating this GH issue and must have switched test platforms to produce the results, so let me clear things up.

Original description (`Between de8f3a5 and a620cd1 commits average TCP latency using SPDK Target and SPDK Initiator increased from ~35usec to ~57usec.`)  was based on results produced on our performance regression setup running tests with ConnectX-5.
Here's how the results of various zcopy combinations look for NVMe-oF TCP when using ConnectX-5:

```
ConnectX-5 results
Target: Enabled, Initiator: Disabled
| IOPS  | AvgLat (usec) |
|-------|---------------|
| 22800 | 43.6          |
| 21700 | 50.6          |
| 25800 | 40.1          |

Target: Enabled, Initiator: Enabled
| IOPS | AvgLat (usec) |
|------|---------------|
| 3970 | 251.7         |
| 3967 | 251.7         |
| 3968 | 251.5         |

Target: Disabled, Initiator: Enabled
| IOPS | AvgLat (usec) |
|------|---------------|
| 3967 | 251.8         |
| 3970 | 250.2         |
| 3968 | 251.77        |

Target: Disabled, Initiator: Disabled
| IOPS | AvgLat (usec) |
|------|---------------|
| 6238 | 159.7         |
| 6250 | 159.6         |
| 6436 | 155.4         |
```

Like I said, I think I lost focus while creating the GH issue and switched to a setup which has Intel E810 NICs installed, which results for various zcopy configurations look like this (results from previous comment)

```
E810 Results
Target: Enabled, Initiator: Disabled
| IOPS  | AvgLat (usec) |
|-------|---------------|
| 33700 | 29.27         |
| 33200 | 29.72         |
| 32900 | 29.91         |

Target: Enabled, Initiator: Enabled
| IOPS  | AvgLat (usec) |
|-------|---------------|
| 29300 | 33.73         |
| 7645  | 130.01        |
| 15200 | 65.25         |
| 11800 | 84.00         |
| 28700 | 34.93         |

Target: Disabled, Initiator: Enabled
| IOPS  | AvgLat (usec) |
|-------|---------------|
| 15100 | 65.63         |
| 17200 | 57.83         |
| 13800 | 71.93         |

Target: Disabled, Initiator: Disabled
| IOPS  | AvgLat (usec) |
|-------|---------------|
| 33000 | 29.06         |
| 33800 | 29.18         |
| 35600 | 27.66         |
```

So it looks like that enabling zcopy results in performance degradation for both NIC models, with degradation being much more visible for E810.

Sorry for chaos, and I hope I didn't confuse you too much. From now on let's reference ConnectX-5 results only, so that we're on the same page :)

**Comment by tomzawadzki** [comment] 2021-04-13 15:06
[Community meeting] To avoid the degradation the zero copy on initiator shall be disabled for 21.04 release. @AlekseyMarchuk will take a look at further steps to take in order to resolve this degradation.

**Comment by AlekseyMarchuk** [comment] 2021-04-16 14:14
I pushed a patch https://review.spdk.io/gerrit/c/spdk/spdk/+/7457 to address this issue. The patch adds a new parameter to configure zero copy feature for client sockets. Existing parameter configures this feature for listen sockets

**Comment by karlatec** [comment] 2021-04-19 11:13
@AlekseyMarchuk tested your patch.
There were some changes done to the performance scripts that I use, so I checked out master `b07a04118`, used it as baseline and then cherry-picked your patch for comparison.

Zerocopy enabled on target side in all cases.

Baseline results, master:
```
Zerocopy disabled on initiator side (via JSON config)
IOPS          Bandwidth  AvgLatusec
31043.247838  124172.0   31.708660634
29844.40778   119377.0   33.058238300999996
34266.45      137065.0   28.737863483
28653.817309  114615.0   34.461773274
31525.923704  126103.0   31.240641602
28360.631968  113442.0   34.790449454000004
29247.437628  116989.0   33.636697931
30129.79351   120519.0   32.668357864
27994.60027   111978.0   35.187835889
31626.718664  126506.0   31.134840061


Zerocopy enabled on initiator side (via JSON config)
IOPS          Bandwidth  AvgLatusec
27635.6       110542.0   35.580225481
28650.867457  114603.0   34.38658904
29608.0       118432.0   33.325933719
24178.39108   96713.0    40.832505676000004
11359.882006  45439.0    87.356275861
7474.126294   29896.0    133.111593076
26895.505225  107582.0   36.675844746
14656.667167  58626.0    67.620955067
28036.848158  112147.0   35.186831817
26666.066697  106664.0   36.807036616
```

With your patch:
```
Zerocopy disabled on initiator side (via RPC param)
IOPS          Bandwidth  AvgLatusec
26684.3       106737.0   36.832160603999995
31081.345933  124325.0   31.693453661
29642.317884  118569.0   33.236017052
28642.2       114568.0   34.474027903
31292.9       125171.0   31.511875115
29683.915804  118735.0   33.196269998000005
28461.376931  113845.0   34.633561850999996
32284.235788  129136.0   30.568397677
29524.123794  118096.0   33.460751356
28371.05      113484.0   34.746377924
31970.301485  127881.0   30.798624096
33638.568072  134554.0   29.321084111
18757.65      75030.0    52.79778786
32872.556372  131490.0   29.903491995
32075.1       128300.0   30.770541816
28210.339483  112841.0   35.001120805999996
31615.669217  126462.0   31.157394713000002
30545.422729  122181.0   32.27061736
31074.79626   124299.0   31.676390902999998
14383.680816  57534.0    69.016595531

Zerocopy enabled on initiator side (via RPC param)
IOPS          Bandwidth  AvgLatusec
28120.493975  112481.0   35.083018288
31686.565672  126746.0   31.10564375
27857.907105  111431.0   35.404896471
30921.103945  123684.0   31.861282686
31271.486426  125085.0   31.518496722
28231.288436  112925.0   34.990568394
31182.55      124730.0   31.647215969
27893.755312  111575.0   35.434699043
13200.539973  52802.0    75.324084371
27606.85      110427.0   35.798425764
30081.545923  120326.0   32.760105922
27538.673066  110154.0   35.846037703
28437.028149  113748.0   34.705179268
31592.970351  126371.0   31.189807703
31715.814209  126863.0   31.073252082
27826.358682  111305.0   35.396873381999995
28153.242338  112612.0   35.047430012
31093.7       124374.0   31.68947608
27970.0015    111880.0   35.306416277
30698.1       122792.0   32.131025412
```

Interestingly enabling Zcopy for client sockets using RPC paramater does not result in performance drop / latency increase, unlike for case where we explicitly  enable zcopy on client side using JSON config.

**Comment by AlekseyMarchuk** [comment] 2021-04-19 12:06
@karlatec could you clarify how you enabled/disabled zcopy via RPC param? RPC `sock_imp_set_options` can be used in STARTUP state, so probably it was not applied. That can explain why you see different results between JSON and RPC. I would expect that results are the same

**Comment by karlatec** [comment] 2021-04-19 12:25
@AlekseyMarchuk I'm pretty sure it was applied. I started SPDK with `--wait-for-rpc`, then run `sock_impl_set_options` and finally `framework_start_init`. After that I called `sock_impl_get_options` and `enable_zerocopy_send_client` was set to `true`

**Comment by AlekseyMarchuk** [comment] 2021-04-19 14:17
@karlatec I'm terribly sorry, there was a typo in rpc.py and the new parameter was not applied at all. I updated my patch, could you verify it?

**Comment by karlatec** [comment] 2021-04-19 15:27
I think this change: https://review.spdk.io/gerrit/c/spdk/spdk/+/7457/1..2/scripts/rpc.py had no effect on my test :) I'm not using rpc.py, but scripts/rpc/sock.py directly, like this:

```
            rpc.sock.sock_impl_set_options(self.client, impl_name="posix",
                                           enable_zerocopy_send=True, enable_zerocopy_send_client=True)
```

**Comment by AlekseyMarchuk** [comment] 2021-04-20 14:22
@karlatec I collected performance metrics with this patch, I used nvme perf and bdevper
bdevperf doesn't show latency but we can see that IOPS/BW results with zcopy enabled have higher fluctuation
One interesting thing that I can't explain is that when zcopy is enabled and I ran perf (it shows statistics each second) then I can see, that if perf reported low IOPS from the start (let's say 14 KIOPS) then IOPS will never increase to normal level (e.g. 22 KIOPS), it will remain at the same level +- some fluctuation. But if perf reported normal IOPS from the start, it will never drop to 14 KIOPS. 

```
perf:
zcopy
| IOPS     | BW    | lat   | mode     | # |
| 18849.23 | 73.63 | 53.02 | randread | 0 |
| 23116.20 | 90.30 | 43.23 | randread | 1 |
| 16133.67 | 63.02 | 61.94 | randread | 2 |
| 25362.17 | 99.07 | 39.38 | randread | 3 |
| 14805.63 | 57.83 | 67.49 | randread | 4 |
| 15388.67 | 60.11 | 64.92 | randread | 5 |
| 23039.17 | 90.00 | 43.37 | randread | 6 |
| 23839.43 | 93.12 | 41.90 | randread | 7 |
| 22334.77 | 87.25 | 44.74 | randread | 8 |
| 24563.20 | 95.95 | 40.68 | randread | 9 |

avg
| 20743.21 | 81.02 | 50.06 | 


no zcopy 
| IOPS     | BW     | lat   | mode     | # |
| 25603.83 | 100.01 | 39.02 | randread | 0 |
| 26944.13 | 105.25 | 37.08 | randread | 1 |
| 24109.67 | 94.18  | 41.44 | randread | 2 |
| 26780.23 | 104.61 | 37.31 | randread | 3 |
| 24136.83 | 94.28  | 41.40 | randread | 4 |
| 31584.29 | 123.38 | 31.62 | randread | 5 |
| 27044.77 | 105.64 | 36.94 | randread | 6 |
| 28570.57 | 111.60 | 34.97 | randread | 7 |
| 27024.77 | 105.57 | 36.97 | randread | 8 |
| 23898.63 | 93.35  | 41.81 | randread | 9 |

avg
| 26465.7  | 103.38 | 38.022| 


bdevperf:
zcopy
17799.80 IOPS      69.53 MiB/s
21072.50 IOPS      82.31 MiB/s
17650.80 IOPS      68.95 MiB/s
16734.65 IOPS      65.37 MiB/s
22276.45 IOPS      87.02 MiB/s
17307.90 IOPS      67.61 MiB/s
16251.20 IOPS      63.48 MiB/s
21888.20 IOPS      85.50 MiB/s
20177.85 IOPS      78.82 MiB/s
24688.15 IOPS      96.44 MiB/s

avg
19584 IOPS         76.5 MiB/s

no zcopy
24123.85 IOPS      94.23 MiB/s
25227.70 IOPS      98.55 MiB/s
23934.00 IOPS      93.49 MiB/s
24243.20 IOPS      94.70 MiB/s
25216.35 IOPS      98.50 MiB/s
22870.95 IOPS      89.34 MiB/s
24107.00 IOPS      94.17 MiB/s
25811.45 IOPS     100.83 MiB/s
23992.05 IOPS      93.72 MiB/s
23826.60 IOPS      93.07 MiB/s

avg
24335 IOPS         95 MiB/s

```

**Comment by AlekseyMarchuk** [comment] 2021-04-27 16:31
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/7457 disables zcopy_send for client sockets, merged

**Closed by AlekseyMarchuk** 2021-04-27 16:31 UTC
Labels: Medium, bug
