### ISSUE TITLE
[vfio_user_virtio_bdevperf] timeout - test aborted

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2846] opened 2022-12-28 21:30 UTC
00:33:29.705   20:30:00	-- common/autotest_common.sh@809 -- # xtrace_enable
00:33:29.705   20:30:00	-- common/autotest_common.sh@810 -- # (( i == 0 ))
00:33:29.705   20:30:00	-- common/autotest_common.sh@814 -- # return 0
00:33:29.705   20:30:00	-- virtio/initiator_bdevperf.sh@44 -- # /var/jenkins/workspace/vfio-user-autotest/spdk/scripts/rpc.py -s /tmp/bdevperf.sock bdev_virtio_attach_controller --dev-type scsi --trtype vfio-user --traddr /tmp/vfu_devices/vfu.scsi VirtioScsi0
00:33:29.962  [2022-12-28 20:30:00.443073] tgt_endpoint.c: 165:tgt_accept_poller: *NOTICE*: /tmp/vfu_devices/vfu.scsi: attached successfully
00:33:29.962  [2022-12-28 20:30:00.507682] vfu_virtio.c: 277:virtio_dev_enable_vq: *ERROR*: Queue 0 failed to map
00:33:29.962  [2022-12-28 20:30:00.518768] vfu_virtio.c: 277:virtio_dev_enable_vq: *ERROR*: Queue 1 failed to map
00:33:29.962  [2022-12-28 20:30:00.529877] vfu_virtio.c: 277:virtio_dev_enable_vq: *ERROR*: Queue 2 failed to map
00:33:29.962  [2022-12-28 20:30:00.540986] vfu_virtio.c: 277:virtio_dev_enable_vq: *ERROR*: Queue 3 failed to map
00:34:37.646  Timeout while waiting for response:
00:34:37.646  
00:34:37.646  
00:34:37.646    20:31:00	-- virtio/initiator_bdevperf.sh@44 -- # trap - ERR
00:34:37.646    20:31:00	-- virtio/initiator_bdevperf.sh@44 -- # print_backtrace
00:34:37.646    20:31:00	-- common/autotest_common.sh@1088 -- # [[ ehxBET =~ e ]]

**Comment by spdkci** [comment] 2022-12-28 21:31
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_93657.html

**Comment by spdkci** [comment] 2023-01-04 07:46
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_93838.html

**Comment by spdkci** [comment] 2023-01-04 16:54
Another instance of this failure. Reported by @MengjinWu. log: https://ci.spdk.io/public_build/autotest-per-patch_93964.html

**Comment by spdkci** [comment] 2023-01-04 23:41
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_93990.html

**Comment by spdkci** [comment] 2023-01-04 23:42
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_93989.html

**Comment by spdkci** [comment] 2023-01-06 03:49
Another instance of this failure. Reported by @richael02. log: https://ci.spdk.io/public_build/autotest-per-patch_94163.html

**Comment by spdkci** [comment] 2023-01-06 03:50
Another instance of this failure. Reported by @richael02. log: https://ci.spdk.io/public_build/autotest-per-patch_94168.html

**Comment by spdkci** [comment] 2023-01-06 19:39
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_94235.html

**Comment by spdkci** [comment] 2023-01-10 09:59
Another instance of this failure. Reported by @krzysztofsmolinski. log: https://ci.spdk.io/public_build/autotest-per-patch_94438.html

**Comment by changpe1** [comment] 2023-01-12 05:55
For the failed cases, the vring physical address allocated via `spdk_zmalloc` is like `3f6600000`,

00:19:38.702  [2023-01-11 08:19:03.143607] virtio_vfio_user.c: 339:virtio_vfio_user_setup_queue: *DEBUG*: queue 0 addresses:
00:19:38.702  [2023-01-11 08:19:03.143640] virtio_vfio_user.c: 340:virtio_vfio_user_setup_queue: *DEBUG*: 	 desc_addr: 3f6600000

But for the successful cases, the vring physical address is like `200028600000`,

00:12:40.452  [2023-01-11 03:38:31.721539] virtio_vfio_user.c: 339:virtio_vfio_user_setup_queue: *DEBUG*: queue 0 addresses:
00:12:40.452  [2023-01-11 03:38:31.721561] virtio_vfio_user.c: 340:virtio_vfio_user_setup_queue: *DEBUG*: 	 desc_addr: 200028600000

although we've used `-g` parameter to use `single-file-segments`, but seems that the application is still invoking dynamic memory allocation in DPDK to get a memory region that isn't registered to remote target process.

**Comment by changpe1** [comment] 2023-01-12 07:21
Currently to use a big enough pre-allocated memory is preferred via https://review.spdk.io/gerrit/c/spdk/spdk/+/16141.

Another alterative solution could be in libvfio-user, currently it uses static array with 16 slots to save memory regions from initiator, if we use `-g` parameter in initiator, the target side should merge memory regions which is IOVA continuous.

**Comment by spdkci** [comment] 2023-01-12 14:17
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_95048.html

**Comment by changpe1** [comment] 2023-01-16 08:32
patch has been merged, keep it open for a while to see this issue can happen again or not.

**Comment by spdkci** [comment] 2023-01-16 09:48
Another instance of this failure. Reported by @richael02. log: https://ci.spdk.io/public_build/autotest-per-patch_95470.html

**Comment by changpe1** [comment] 2023-01-17 02:38
> Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_95476.html

this needs a rebase to latest code base.

**Comment by changpe1** [comment] 2023-01-17 02:39
> Another instance of this failure. Reported by @richael02. log: https://ci.spdk.io/public_build/autotest-per-patch_95470.html

irrelevant to this issue.

**Comment by spdkci** [comment] 2023-01-17 09:40
Another instance of this failure. Reported by @jlevon. log: https://ci.spdk.io/public_build/autotest-per-patch_95596.html

**Comment by spdkci** [comment] 2023-01-17 09:56
Another instance of this failure. Reported by @mikeBashStuff. log: Not Found

**Comment by spdkci** [comment] 2023-01-17 17:57
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_95750.html

**Comment by spdkci** [comment] 2023-01-18 07:56
Another instance of this failure. Reported by @richael02. log: https://ci.spdk.io/public_build/autotest-per-patch_95853.html

**Comment by spdkci** [comment] 2023-01-18 15:40
Another instance of this failure. Reported by @richael02. log: https://ci.spdk.io/public_build/autotest-per-patch_95944.html

**Comment by spdkci** [comment] 2023-01-18 16:16
Another instance of this failure. Reported by @jlevon. log: https://ci.spdk.io/public_build/autotest-per-patch_95935.html

**Comment by spdkci** [comment] 2023-01-18 17:31
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_95972.html

**Comment by changpe1** [comment] 2023-01-19 03:56
The issue is still happening, I will continue investigating how to resolve the dynamic memory allocation issue.

**Comment by spdkci** [comment] 2023-01-20 09:16
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_96288.html

**Comment by spdkci** [comment] 2023-01-20 19:45
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_96407.html

**Comment by spdkci** [comment] 2023-01-23 07:58
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_96445.html

**Comment by spdkci** [comment] 2023-01-27 04:33
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_97150.html

**Comment by spdkci** [comment] 2023-01-30 19:09
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_97315.html

**Comment by spdkci** [comment] 2023-02-01 14:57
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_97756.html

**Comment by spdkci** [comment] 2023-02-02 05:07
Another instance of this failure. Reported by @ankit-sam. log: https://ci.spdk.io/public_build/autotest-per-patch_97786.html

**Comment by changpe1** [comment] 2023-02-02 06:45
Raied another patch to fix this issue https://review.spdk.io/gerrit/c/spdk/spdk/+/16651

**Comment by spdkci** [comment] 2023-02-02 23:53
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_97894.html

**Comment by spdkci** [comment] 2023-02-07 12:13
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_98047.html

**Comment by spdkci** [comment] 2023-02-07 19:06
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_98140.html

**Comment by spdkci** [comment] 2023-02-07 19:46
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_98149.html

**Comment by spdkci** [comment] 2023-02-08 05:19
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_98166.html

**Comment by spdkci** [comment] 2023-02-08 08:18
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_98113.html

**Comment by spdkci** [comment] 2023-02-09 11:32
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_98237.html

**Comment by spdkci** [comment] 2023-02-09 11:32
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_98248.html

**Comment by spdkci** [comment] 2023-02-09 11:32
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_98233.html

**Comment by spdkci** [comment] 2023-02-09 15:10
Another instance of this failure. Reported by @xjjx. log: https://ci.spdk.io/public_build/autotest-per-patch_98291.html

**Comment by spdkci** [comment] 2023-02-09 15:11
Another instance of this failure. Reported by @KKaras169169. log: Not Found

**Comment by spdkci** [comment] 2023-02-09 15:11
Another instance of this failure. Reported by @KKaras169169. log: Not Found

**Comment by spdkci** [comment] 2023-02-09 23:45
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_98353.html

**Comment by spdkci** [comment] 2023-02-10 02:34
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_98364.html

**Comment by changpe1** [comment] 2023-02-13 04:31
patch has been merged, closing it now.

**Comment by spdkci** [comment] 2023-02-18 15:53
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_98821.html

**Comment by mgerdts** [comment] 2023-02-18 15:55
> Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_98821.html

This includes commit 56f238488e7465d68d626fc0d596e1e119f31c49 :

https://ci.spdk.io/results/autotest-per-patch/builds/97315/archive/vfio-user-autotest/build.log

I don't know what the policy is on reopening bugs vs. filing a new one.  Reopening, assuming that is the right thing to do.

**Comment by spdkci** [comment] 2023-02-19 22:47
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_98795.html

**Comment by jimharris** [comment] 2023-02-21 14:45
> > Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_98821.html
> 
> This includes commit [56f2384](https://github.com/spdk/spdk/commit/56f238488e7465d68d626fc0d596e1e119f31c49) and my log matches a failure diagnosed by Jim.
> 
> https://ci.spdk.io/results/autotest-per-patch/builds/97315/archive/vfio-user-autotest/build.log
> 
> I don't know what the policy is on reopening bugs vs. filing a new one. Reopening, assuming that is the right thing to do.

Thanks @mgerdts, reopening was the best course of action.

Assigning to @ksztyber for now.

**Comment by spdkci** [comment] 2023-02-27 10:57
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_99212.html

**Comment by spdkci** [comment] 2023-03-21 13:06
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_100468.html

**Comment by mgerdts** [comment] 2023-03-21 13:08
> Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_100468.html

I'm not certain this is the same issue.  It's a timeout in the same test, but at a different point.  I'm guessing there's one root cause for multiple symptoms.

**Comment by spdkci** [comment] 2023-05-17 07:01
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_104068.html

**Comment by jchachux** [comment] 2023-05-17 14:04
I encountered this issue with new servers being added to the CI, where the bug would reproduce 100% of the time when the VT-D flag in the BIOS was disabled. 

On the machine from previous instance (log: https://ci.spdk.io/public_build/autotest-per-patch_104068.html) the flag was also turned off.  After enabling this flag on the  server and conducting tests, the job proceeded without error.

**Closed** 2023-06-02 11:13 UTC
Labels: bug, Medium, Intermittent Failure
