### ISSUE TITLE
[nvmf_fio_target] timed out waiting for nvme disconnect

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#2884] opened 2023-01-27 10:27 UTC
Seems like the test timed out while waiting on `nvme disconnect`.
```
00:14:21.441  Run status group 0 (all jobs):
00:14:21.442     READ: bw=34.4MiB/s (36.1MB/s), 7764KiB/s-14.0MiB/s (7951kB/s-14.6MB/s), io=137MiB (144MB), run=2902-3982msec
00:14:21.442  
00:14:21.442  Disk stats (read/write):
00:14:21.442    nvme0n1: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
00:14:21.442    nvme0n2: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
00:14:21.442    nvme0n3: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
00:14:21.442    nvme0n4: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
00:14:21.700   16:26:47	-- target/fio.sh@65 -- # for malloc_bdev in $malloc_bdevs $raid_malloc_bdevs $concat_malloc_bdevs
00:14:21.700   16:26:47	-- target/fio.sh@66 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py bdev_malloc_delete Malloc2
00:14:21.957   16:26:47	-- target/fio.sh@65 -- # for malloc_bdev in $malloc_bdevs $raid_malloc_bdevs $concat_malloc_bdevs
00:14:21.957   16:26:47	-- target/fio.sh@66 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py bdev_malloc_delete Malloc3
00:14:22.214   16:26:47	-- target/fio.sh@65 -- # for malloc_bdev in $malloc_bdevs $raid_malloc_bdevs $concat_malloc_bdevs
00:14:22.214   16:26:47	-- target/fio.sh@66 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py bdev_malloc_delete Malloc4
00:14:22.474   16:26:48	-- target/fio.sh@65 -- # for malloc_bdev in $malloc_bdevs $raid_malloc_bdevs $concat_malloc_bdevs
00:14:22.474   16:26:48	-- target/fio.sh@66 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py bdev_malloc_delete Malloc5
00:14:23.042   16:26:48	-- target/fio.sh@65 -- # for malloc_bdev in $malloc_bdevs $raid_malloc_bdevs $concat_malloc_bdevs
00:14:23.042   16:26:48	-- target/fio.sh@66 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py bdev_malloc_delete Malloc6
00:14:23.363   16:26:48	-- target/fio.sh@69 -- # fio_status=0
00:14:23.363   16:26:48	-- target/fio.sh@70 -- # wait 62128
00:14:23.363   16:26:48	-- target/fio.sh@70 -- # fio_status=4
00:14:23.363   16:26:48	-- target/fio.sh@72 -- # nvme disconnect -n nqn.2016-06.io.spdk:cnode1
00:14:38.533  [2023-01-26 16:27:03.982865] ctrlr.c: 221:nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host nqn.2014-08.org.nvmexpress:uuid:c1a7c9ac-fe8a-494f-bfb5-82377bd0bf35 from subsystem nqn.2016-06.io.spdk:cnode1 due to keep alive timeout.
00:42:27.378  Cancelling nested steps due to timeout
00:42:27.381  Sending interrupt signal to process
00:42:31.084  script returned exit code 255
```
There doesn't appear to be anything interesting in the dmesg (the I/O errors are expected, as the test removes namespaces while doing I/O):
```
[Thu Jan 26 16:26:45 2023] nvme nvme0: rescanning namespaces.
[Thu Jan 26 16:26:45 2023] nvme0c0n3: I/O Cmd(0x2) @ LBA 94176, 8 blocks, I/O Error (sct 0x0 / sc 0xb) DNR 
[Thu Jan 26 16:26:45 2023] critical target error, dev nvme0c0n3, sector 94176 op 0x0:(READ) flags 0x4000000 phys_seg 1 prio class 2
[Thu Jan 26 16:26:46 2023] nvme0c0n1: I/O Cmd(0x2) @ LBA 63424, 8 blocks, I/O Error (sct 0x0 / sc 0xb) DNR 
[Thu Jan 26 16:26:46 2023] critical target error, dev nvme0c0n1, sector 63424 op 0x0:(READ) flags 0x4000000 phys_seg 1 prio class 2
[Thu Jan 26 16:26:46 2023] nvme0c0n2: I/O Cmd(0x2) @ LBA 78272, 8 blocks, I/O Error (sct 0x0 / sc 0xb) DNR 
[Thu Jan 26 16:26:46 2023] critical target error, dev nvme0c0n2, sector 78272 op 0x0:(READ) flags 0x4000000 phys_seg 1 prio class 2
[Thu Jan 26 16:26:48 2023] nvme nvme0: Removing ctrl: NQN "nqn.2016-06.io.spdk:cnode1"
```

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/97086/archive/nvmf-tcp-vg-autotest/build.log
https://ci.spdk.io/public_build/autotest-per-patch_97086.html

**Comment by spdkci** [comment] 2023-01-27 10:27
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_97086.html

**Comment by ksztyber** [comment] 2023-03-14 15:22
[Bug scrub] Happened only once and it was over a month ago, closing.

**Comment by spdkci** [comment] 2023-05-25 14:51
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_105041.html

**Comment by spdkci** [comment] 2023-09-06 14:49
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_109050.html

**Comment by spdkci** [comment] 2023-09-07 13:33
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_109114.html

**Comment by spdkci** [comment] 2023-12-12 14:26
Another instance of this failure. Reported by @eugene-kobyak. log: https://ci.spdk.io/public_build/autotest-per-patch_113726.html

**Comment by karlatec** [comment] 2024-02-28 07:35
Last instance of this issue reported by @eugene-kobyak does not actually match "nvme disconnect" issue, it's closer to https://github.com/spdk/spdk/issues/2961. Which means there were no new occurrences for almost last 6 months. During this time we had at least a few infra configuration changes, which is going to make reproducing this issue highly unlikely.
@ksztyber OK with closing, since this is no longer showing up?

**Comment by sberbz** [comment] 2024-04-24 11:47
The issue seems to be gone, there are no new reports since September 2023.

**Closed by sberbz** 2024-04-24 11:47 UTC
Labels: Intermittent Failure
