### ISSUE TITLE
[nvmf_async_init] assertion failed

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2617] opened 2022-08-01 20:00 UTC
00:25:37.914  killing process with pid 273011
00:25:37.914   19:00:49	-- common/autotest_common.sh@841 -- # kill 273011
00:25:37.914   19:00:49	-- common/autotest_common.sh@846 -- # wait 273011
00:25:37.914  [2022-08-01 19:00:49.387938] thread.c:2374:spdk_for_each_channel: *ERROR*: could not find io_device 0x9601b0
00:25:37.914  nvmf_tgt: thread.c:2375: spdk_for_each_channel: Assertion `false' failed.
00:25:39.823  /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/common/autotest_common.sh: line 846: 273011 Aborted                 (core dumped) "${NVMF_APP[@]}" "$@"
00:25:39.823    19:00:51	-- common/autotest_common.sh@846 -- # trap - ERR
00:25:39.823    19:00:51	-- common/autotest_common.sh@846 -- # print_backtrace
00:25:39.823    19:00:51	-- common/autotest_common.sh@998 -- # [[ ehxBET =~ e ]]
00:25:39.823    19:00:51	-- common/autotest_common.sh@1000 -- # args=('273011' '--transport=rdma')
00:25:39.823    19:00:51	-- common/autotest_common.sh@1000 -- # local args
00:25:39.824    19:00:51	-- common/autotest_common.sh@1002 -- # xtrace_disable
00:25:39.824    19:00:51	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:25:39.824    19:00:51	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:25:39.824    19:00:51	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:25:39.824    19:00:51	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:25:39.824    19:00:51	-- common/autotest_common.sh@19 -- # set +x
00:25:39.824  ========== Backtrace start: ==========

**Comment by spdkci** [comment] 2022-08-01 20:01
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_81620.html

**Comment by yidong0635** [comment] 2022-08-02 08:44
I suspect this issue is related with the timeout issue which maybe due to the admin queue polling rate.
`spdk_for_each_channel `with `io_device = nvme_ctrlr`, there maybe race condition with `bdev_nvme_failover` (nvme resetting timeout and delete ctrlr,  io_device  was  unregistered);
 and then `bdev_nvme_clear_io_path_caches(nvme_ctrlr, NULL)`  executes` io_device_get(io_device)` failed.

**Comment by Comphix** [comment] 2022-08-03 03:58
Went through the case and also mentioned by Yi Dong, there happens a delete ctrlr operation and triggers the qpair state change.

So that bdev_nvme_poll_adminq() is trying to clear the IO path caches.

I am thinking, shall we check ctrlr->is_disconnecting flag in this case:

```
static int
bdev_nvme_poll_adminq(void *arg)
{
	int32_t rc;
	struct nvme_ctrlr *nvme_ctrlr = arg;
	nvme_ctrlr_disconnected_cb disconnected_cb;

	assert(nvme_ctrlr != NULL);

	rc = spdk_nvme_ctrlr_process_admin_completions(nvme_ctrlr->ctrlr);
	if (rc < 0) {
		disconnected_cb = nvme_ctrlr->disconnected_cb;
		nvme_ctrlr->disconnected_cb = NULL;

		if (rc == -ENXIO && disconnected_cb != NULL) {
			bdev_nvme_change_adminq_poll_period(nvme_ctrlr,
							    g_opts.nvme_adminq_poll_period_us);
			disconnected_cb(nvme_ctrlr);
		} else {
			bdev_nvme_failover(nvme_ctrlr, false);
		}
	} else if (spdk_nvme_ctrlr_get_admin_qp_failure_reason(nvme_ctrlr->ctrlr) !=
		   SPDK_NVME_QPAIR_FAILURE_NONE) {
		bdev_nvme_clear_io_path_caches(nvme_ctrlr, NULL); <<<<<<

                // What about first check if (ctrlr->is_disconnecting == false) ??

	}

	return rc == 0 ? SPDK_POLLER_IDLE : SPDK_POLLER_BUSY;
}
```

**Comment by yidong0635** [comment] 2022-08-03 05:10
Thanks Gang, Add more conditions is needed here ,  need to talk about which ones are safe.

**Comment by Comphix** [comment] 2022-08-03 07:19
Trying to run locally below case which hit the issue on my system, so far does not see the same core dump. Will take a further notice on this issue.

```
run_test "nvmf_async_init" test/nvmf/host/async_init.sh "${TEST_ARGS[@]}"
```

**Comment by yidong0635** [comment] 2022-08-05 02:26
@Comphix would you like to  submit a patch that let CI can check it, and then other one can review this patch?

**Comment by Comphix** [comment] 2022-08-05 02:30
Not yet as have not reproduced locally. If you have a potential fix, please just go ahead to raise the patch. Thanks, Gang.

**Comment by spdkci** [comment] 2022-08-06 00:07
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_81969.html

**Comment by spdkci** [comment] 2022-08-06 00:08
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_81973.html

**Comment by Comphix** [comment] 2022-08-08 05:02
Raised patch here: https://review.spdk.io/gerrit/c/spdk/spdk/+/13893

**Comment by shuhei-matsumoto** [comment] 2022-08-08 21:32
Hi @Comphix @yidong0635 

Thank you for your investigation and patch. This may be very similar with an issue in the generic bdev layer a while ago.
We may have to defer io_device_unregister until spdk_for_each_channel completes. I will check more.

**Comment by yidong0635** [comment] 2022-08-09 01:27
Thanks @shuhei-matsumoto, I thinks some of the issues may owned the same solution. According to your idea,
defer  `io_device_unregister  `util `spdk_for_each_channel `completes is better ?

**Comment by shuhei-matsumoto** [comment] 2022-08-09 01:31
Hi @yidong0635 

Yes, that is more strict.

https://github.com/spdk/spdk/commit/494eb6e58b8e72762d0a2127f2657926298e2523
https://github.com/spdk/spdk/commit/7bcd316de1f71f5ca5303d08ac26df20dcd05669
https://github.com/spdk/spdk/commit/48ce2c978e1c3f0da66a2721d5a8bda4d53ab131

realized very similar idea in the generic bdev layer.

**Comment by shuhei-matsumoto** [comment] 2022-08-09 02:07
Hi @Comphix @yidong0635 

Will you take a look at the following?
https://review.spdk.io/gerrit/c/spdk/spdk/+/13923
https://review.spdk.io/gerrit/c/spdk/spdk/+/13924

Gang's patch is good but I think a little more strict fix is better.

**Comment by Comphix** [comment] 2022-08-09 02:21
Thanks Shuhei, will take a look for the fix. Just assigned the issue to you and l will abandon my patch.

**Comment by shuhei-matsumoto** [comment] 2022-08-09 07:57
This will be fixed by the same solution as https://github.com/spdk/spdk/issues/2631

@jimharris How about my two patches?
https://review.spdk.io/gerrit/c/spdk/spdk/+/13923
https://review.spdk.io/gerrit/c/spdk/spdk/+/13924

Historically, the NVMe bdev module had fixed the race between for_each_channel and io_device_unregister itself. 
The issue #2631 is caused by a iteration started outside the NVMe bdev module.

**Comment by spdkci** [comment] 2022-08-09 10:39
Another instance of this failure. Reported by @richael02. log: https://ci.spdk.io/public_build/autotest-per-patch_82210.html

**Comment by jimharris** [comment] 2022-08-09 14:02
> This will be fixed by the same solution as #2631
> 
> @jimharris How about my two patches? https://review.spdk.io/gerrit/c/spdk/spdk/+/13923 https://review.spdk.io/gerrit/c/spdk/spdk/+/13924

Hi @shuhei-matsumoto,

Is 13924 still needed now that we have merged my patch for issue #2631?

> 
> Historically, the NVMe bdev module had fixed the race between for_each_channel and io_device_unregister itself. The issue #2631 is caused by a iteration started outside the NVMe bdev module.

**Comment by shuhei-matsumoto** [comment] 2022-08-09 19:49
> Hi @shuhei-matsumoto,
> 
> Is 13924 still needed now that we have merged my patch for issue #2631?
> 
> > Historically, the NVMe bdev module had fixed the race between for_each_channel and io_device_unregister itself. The issue #2631 is caused by a iteration started outside the NVMe bdev module.

Hi @jimharris 

Your patch fixes this issue very nicely because this issue is made of only a single for_each_channel operation.

On the other hand, a single reset sequence has many operations and for_each_channel multiple times. After unregistration, subsequent delete operations are not stopped. Hence reset sequence and delete operation still have conflicts.

Updating ANA log page is almost same.

Hence, the NVMe bdev module still has to defer unregistration itself via nvme_ctrlr_can_be_unregistered().

This is my fault but all other cases are covered by nvme_ctrlr_can_be_unregistered(). It is confusing that only a race for I/O path cache clearing is handled by thread library.

Furthermore, while ago I proposed making spdk_put_io_channel asynchronous. However, it was not approved and the NVMe bdev module handled the case itself appropriately. This time, deferring unregistration was approved. The strategy is not consistent yet.

I cannot push my patches strongly because your patch fixed the issue nicely. But I hope it is accepted.

**Comment by jimharris** [comment] 2022-08-09 20:00
> Hi @jimharris
> 
> Your patch fixes this issue very nicely because this issue is made of only a single for_each_channel operation.
> 
> On the other hand, a single reset sequence has many operations and for_each_channel multiple times. After unregistration, subsequent delete operations are not stopped. Hence reset sequence and delete operation still have conflicts.
> 
> Updating ANA log page is almost same.
> 
> Hence, the NVMe bdev module still has to defer unregistration itself via nvme_ctrlr_can_be_unregistered().
> 
> This is my fault but all other cases are covered by nvme_ctrlr_can_be_unregistered(). It is confusing that only a race for I/O path cache clearing is handled by thread library.

This makes sense to me, that we should keep all of the cases consistent.

> Furthermore, while ago I proposed making spdk_put_io_channel asynchronous. However, it was not approved and the NVMe bdev module handled the case itself appropriately. This time, deferring unregistration was approved. The strategy is not consistent yet.

I understand your concern.  For the registration deferral, we were able to implement it with minimal code changes and no API changes, so there was minimal impact to the rest of the code base.  IIRC, async put_io_channel was more complicated which was why it did not move forward.  But maybe we need to revisit this again.

> I cannot push my patches strongly because your patch fixed the issue nicely. But I hope it is accepted.

Your explanation is helpful.  I will continue reviewing the patches.  Thanks!

**Comment by spdkci** [comment] 2022-08-11 21:39
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_82458.html

**Comment by shuhei-matsumoto** [comment] 2022-08-11 21:45
@jimharris Just FYI. This issue was reproduced on the latest master. spdk_for_each_channel() was called after completing spdk_io_device_unregister(). So the patch https://review.spdk.io/gerrit/c/spdk/spdk/+/13924 is still necessary if we do not remove the assert from spdk_for_each_channel().

**Comment by changpe1** [comment] 2022-08-18 03:48
Patches have been merged, closing this issue now.

**Closed by changpe1** 2022-08-18 03:48 UTC
Labels: bug, Intermittent Failure, Patches out for review
