### ISSUE TITLE
[OCF] fio_plugin fails when run with json configuration

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1287] opened 2020-03-17 14:33 UTC
```
SPDK: v20.01-rc1-471-gd3173a9e3
```
The `ocf_fio_modes` test fails when json configuration is used instead of the .ini. The json config looks like the following:
```
{
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "params": {
            "trtype": "PCIe",
            "name": "Nvme0",
            "traddr": "0000:87:00.0"
          },
          "method": "bdev_nvme_attach_controller"
        },
        {
          "method": "bdev_ocf_create",
          "params": {
            "name": "PT_Nvme",
            "mode": "pt",
            "cache_bdev_name": "Nvme0n1p0",
            "core_bdev_name": "Nvme0n1p1"
          }
        },
        {
          "method": "bdev_ocf_create",
          "params": {
            "name": "WT_Nvme",
            "mode": "wt",
            "cache_bdev_name": "Nvme0n1p2",
            "core_bdev_name": "Nvme0n1p3"
          }
        },
        {
          "method": "bdev_ocf_create",
          "params": {
            "name": "WB_Nvme0",
            "mode": "wb",
            "cache_bdev_name": "Nvme0n1p4",
            "core_bdev_name": "Nvme0n1p5"
          }
        },
        {
          "method": "bdev_ocf_create",
          "params": {
            "name": "WB_Nvme1",
            "mode": "wb",
            "cache_bdev_name": "Nvme0n1p6",
            "core_bdev_name": "Nvme0n1p7"
          }
        },
        {
          "method": "bdev_split_create",
          "params": {
            "base_bdev": "Nvme0n1",
            "split_count": 8,
            "split_size_mb": 101
          }
        }
      ]
    }
  ]
}
```
The above was generated based on the old .ini config which looked like so:
```
[Nvme]
  TransportID "trtype:PCIe traddr:0000:87:00.0" Nvme0

[Split]
  Split Nvme0n1 8 101

[OCF]
  OCF PT_Nvme  pt Nvme0n1p0 Nvme0n1p1
  OCF WT_Nvme  wt Nvme0n1p2 Nvme0n1p3
  OCF WB_Nvme0 wb Nvme0n1p4 Nvme0n1p5
  OCF WB_Nvme1 wb Nvme0n1p6 Nvme0n1p7
```
This is what's going in detail during the build which eventually hits a timeout:

http://10.102.17.111/results/autotest-per-patch/builds/6599/archive/nvme-phy-autotest/build.log

For a second I thought  cache|core bdevs needs to be created prior the `bdev_ocf_create` calls, but that ended up even worse:
 https://ci.spdk.io/results/autotest-per-patch/builds/6615/archive/nvme-phy-autotest/build.log

I am not really sure if this is a bug or just an improper config, hence the ticket. :) Any hints would be appreciated. 

This was noticed while working on .ini to json migration: https://review.spdk.io/gerrit/c/spdk/spdk/+/1327

**Comment by Donaim** [comment] 2020-03-26 13:24
I will investigate this issue this week

**Comment by Donaim** [comment] 2020-03-26 14:58
Issue does reproduce on my setup as well.
I will investigate if metadata has something to do with this, because configuration file in OCF had higher priority than disk metadata, which may not be true for json configuration.

**Comment by mikeBashStuff** [comment] 2020-03-27 09:17
@Donaim I don't really know what changed, but I can't see this issue anymore after a rebase I did recently. https://ci.spdk.io/results/autotest-per-patch/builds/7983/archive/nvme-autotest/build.log - the `ocf_fio_modes` now passes successfully with bunch of other ocf tests that have been moved to json.  That said, there's still a new issue with OCF that surfaced but under a different test so I will open a separate issue for that.

**Comment by mikeBashStuff** [comment] 2020-03-27 10:04
New issue under https://github.com/spdk/spdk/issues/1287, just fyi.

**Comment by Donaim** [comment] 2020-04-01 11:02
The issue still reproduces on my setup.
I am investigating.
Pretty sure that we need to do similar `dd` trick as in `ocf/management/persistant.sh`

**Comment by Donaim** [comment] 2020-04-01 12:15
Indeed it was the issue and `dd` trick helps.
I will submit a fix today.

The issue was that OCF prioritizes configuration file higher than disk metadata, so when we were using config file, metadata was not in the way. In case of json config, metadata is read first. So the fix is to clear metadata by erasing the disk.

Related to this fix - I will try to add a helper script that clears the disk and does it faster than
```console
setup.sh reset
dd if=/dev/zero of=/dev/nvme
setup.sh
```

**Comment by Donaim** [comment] 2020-04-01 15:19
Submited the fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/1628

**Comment by Donaim** [comment] 2020-04-15 12:54
Fix that was merged works on my setup and since issue doesn't reproduce for @mikeBashStuff as well, considering this solved

**Closed by Donaim** 2020-04-15 12:54 UTC
Labels: Low, bug
