### ISSUE TITLE
[FAQ] accel_perf tool only do copy for a limited fix number=qd memory location, this is only upper bound test

### ISSUE THREAD

**Issue by gaowayne** [spdk/spdk#2480] opened 2022-04-23 02:47 UTC
# Bug report

accel_perf have fixed number task, each task point to one buffer that is allocated at init phase. I suspect that the copy may be finished at the CPU cache, not really finished at the media(DRAM or pmem). if this is true, this is only upper bound test. it does not have meaning to estimate the media performance under accel_perf

## Expected Behavior

can we add random uniform destination as copy target, that may occupy CPU cache, then we have more stable and more close to real workload performance? or any suggestion on this?

## Current Behavior

please check below code, buffer is very fixed number, it is very locality test that is friendly to CPU cache
```
	task = worker->task_base;
	for (i = 0; i < num_tasks; i++) {
		TAILQ_INSERT_TAIL(&worker->tasks_pool, task, link);
		if (_get_task_data_bufs(task)) {
			fprintf(stderr, "Unable to get data bufs\n");
			goto error;
		}
		task++;
	}
```

## Steps to Reproduce

1. just code review
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.) master 

originally I would like add mem -> pmem copy to do more real testing for low speed media than DRAM

**Comment by peluse** [comment] 2022-04-23 03:17
@gaowayne thanks for the suggestion, I'v changed the label to enhancement from sighting as this is not a bug.  Please keep in mind that accel_perf is an example tool for how to use the accel framework not really intended to provide real life validation type data.  That said, there is a "-a" option that allows you to make the task pool as large as you like regardless of the queue depth to try and help minimize the cache effects that you mention.  I'd suggest trying that and if you still need something else and don't get any "takers" on you request that you submit a patch that meets with your requirements and if it makes sense for general purpose (sounds like it would) I'm sure it'd be welcomed.  You can also try Slack or a community meeting to see if anyone is interested in making these changes. I can certainly help you if you'd like.  Thanks!

**Comment by gaowayne** [comment] 2022-04-23 03:30
@peluse thank you so much Paul, I plan hack code for example random a pmem location before the copy on the fly, then I can continue my job in short term. I can share you my changes, if have any idea to help me upstream the changes, it will be great. or you plan to implement a total solution. then this is only for my testing only. :)

**Comment by peluse** [comment] 2022-04-23 13:54
@gaowayne sounds great, looking forward to a patch from you for sure! Hit me or anyone up on slack for help if needed.  As you're working on this I"m going to go ahead and close it.

**Closed by peluse** 2022-04-23 13:54 UTC
Labels: enhancement
