### ISSUE TITLE
SPDK fails to build with "usdt" and "unit-tests" enabled

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#2027] opened 2021-07-05 10:43 UTC
## Current Behavior

Building with `--with-usdt` and `--enable-unit-tests` (default) results in compilation failure.

## Possible Solution

Workaround: `--disable-unit-tests`.

## Steps to Reproduce

1. git submodule update --init
2. ./configure --enable-debug  --with-usdt
3. make -j100
```
  CXX test/cpp_headers/nbd.o
  LINK pipe_ut
  LINK ctrlr_discovery_ut
  LINK ftl_ppa_ut
  CXX test/cpp_headers/net.o
  LINK ctrlr_bdev_ut
  CXX test/cpp_headers/notify.o
  CXX test/cpp_headers/nvme.o
ctrlr_discovery_ut.o(.note.stapsdt+0x14): error: relocation refers to local symbol "" [102], which is defined in a discarded section
ctrlr_discovery_ut.o(.note.stapsdt+0x90): error: relocation refers to local symbol "" [108], which is defined in a discarded section
ctrlr_discovery_ut.o(.note.stapsdt+0xf8): error: relocation refers to local symbol "" [110], which is defined in a discarded section
ctrlr_discovery_ut.o(.note.stapsdt+0x15c): error: relocation refers to local symbol "" [112], which is defined in a discarded section
collect2: error: ld returned 1 exit status
make[5]: *** [/home/klateck/work/spdk/mk/spdk.unittest.mk:74: ctrlr_discovery_ut] Error 1
make[4]: *** [/home/klateck/work/spdk/mk/spdk.subdirs.mk:44: ctrlr_discovery.c] Error 2
make[4]: *** Waiting for unfinished jobs....
  CXX test/cpp_headers/nvme_intel.o
  CXX test/cpp_headers/nvme_ocssd.o
  CXX test/cpp_headers/nvme_ocssd_spec.o
[...]
  LINK nvme_pcie_ut
  LINK nvme_ns_cmd_ut
  LINK tcp_ut
  LINK nvme_tcp_ut
make[3]: *** [/home/klateck/work/spdk/mk/spdk.subdirs.mk:44: nvmf] Error 2
make[3]: *** Waiting for unfinished jobs....
  LINK vhost_ut
  LINK ftl_io_ut
  LINK bdev_ut
  LINK blob_ut
  LINK nvme_ctrlr_ut
make[2]: *** [/home/klateck/work/spdk/mk/spdk.subdirs.mk:44: lib] Error 2
make[1]: *** [/home/klateck/work/spdk/mk/spdk.subdirs.mk:44: unit] Error 2
make: *** [/home/klateck/work/spdk/mk/spdk.subdirs.mk:44: test] Error 2
```
4.  touch test/unit/lib/nvmf/ctrlr_discovery.c/ctrlr_discovery_ut.c && make -j10 Q=
```
[...]
echo "  LINK ctrlr_discovery_ut"; cc -o ctrlr_discovery_ut  -Wl,-z,relro,-z,now -Wl,-z,noexecstack -fuse-ld=gold -Wl,--wrap,calloc -Wl,--wrap,pthread_mutexattr_init -Wl,--wrap,pthread_mutex_init -Wl,--wrap,recvmsg -Wl,--wrap,sendmsg -Wl,--wrap,writev -Wl,--gc-sections ctrlr_discovery_ut.o  -lcunit /home/klateck/work/spdk/build/lib/libspdk_json.a /home/klateck/work/spdk/build/lib/libspdk_thread.a /home/klateck/work/spdk/build/lib/libspdk_util.a /home/klateck/work/spdk/build/lib/libspdk_log.a /home/klateck/work/spdk/build/lib/libspdk_trace.a -Wl,--whole-archive /home/klateck/work/spdk/build/lib/libspdk_ut_mock.a -Wl,--no-whole-archive  -L/home/klateck/work/spdk/isa-l/.libs -lisal -pthread -lrt -luuid -lcrypto -lm
  LINK ctrlr_discovery_ut
ctrlr_discovery_ut.o(.note.stapsdt+0x14): error: relocation refers to local symbol "" [102], which is defined in a discarded section
ctrlr_discovery_ut.o(.note.stapsdt+0x90): error: relocation refers to local symbol "" [108], which is defined in a discarded section
ctrlr_discovery_ut.o(.note.stapsdt+0xf8): error: relocation refers to local symbol "" [110], which is defined in a discarded section
ctrlr_discovery_ut.o(.note.stapsdt+0x15c): error: relocation refers to local symbol "" [112], which is defined in a discarded section
collect2: error: ld returned 1 exit status
make[5]: *** [/home/klateck/work/spdk/mk/spdk.unittest.mk:74: ctrlr_discovery_ut] Error 1
make[4]: *** [/home/klateck/work/spdk/mk/spdk.subdirs.mk:44: ctrlr_discovery.c] Error 2
make[3]: *** [/home/klateck/work/spdk/mk/spdk.subdirs.mk:44: nvmf] Error 2
make[2]: *** [/home/klateck/work/spdk/mk/spdk.subdirs.mk:44: lib] Error 2
make[1]: *** [/home/klateck/work/spdk/mk/spdk.subdirs.mk:44: unit] Error 2
make: *** [/home/klateck/work/spdk/mk/spdk.subdirs.mk:44: test] Error 2
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK 05dc895beaa57240c3157c878edc6d75f601cf53
Fedora 33 5.12.11-200
gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1)
libbpf.x86_64 2:0.3.0-1.fc33
bpftrace v0.13.0-1-gd4bb

**Comment by jimharris** [comment] 2021-07-05 17:39
I'm not able to reproduce this on my system, but I'm not surprised we would see different behavior with different toolchain versions.

We probably want include/spdk_internal/usdt.h to use empty macros when compiling unit tests, even if usdt was enabled.  Maybe something like:

```
#if defined(SPDK_CONFIG_USDT) && !defined(SPDK_UNIT_TEST)
```

Then add -DSPDK_UNIT_TEST to mk/spdk.unittest.mk.

**Comment by ksztyber** [comment] 2021-07-07 09:57
https://review.spdk.io/gerrit/c/spdk/spdk/+/8699

@karlatec  could you check if this fixes the issue on your end?

**Comment by karlatec** [comment] 2021-07-07 12:48
Was able to compile `./configure --enable-debug  --with-usdt && make -j100`, look good to me

**Comment by tomzawadzki** [comment] 2021-07-09 07:50
Patch fixing this issue has been merged.

**Closed by tomzawadzki** 2021-07-09 07:50 UTC
Labels: Low, Patches out for review, bug
