### ISSUE TITLE
[autobuild.sh] ABI tests fail with SPDK 20.04 reference build due to libspdk_bdev_raid.so SO_MINOR version

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1381] opened 2020-05-05 07:48 UTC
## Current Behavior

ABI tests fail when run against 20.04 SPDK reference build.
Error message:
```
08:30:28 ************************************
08:30:28 START TEST confirm_abi_deps
08:30:28 ************************************
08:30:29 No corresponding object for libspdk_bdev_compress.so in canonical directory. Skipping.
08:30:29 No corresponding object for libspdk_bdev_crypto.so in canonical directory. Skipping.
08:30:29 No corresponding object for libspdk_bdev_pmem.so in canonical directory. Skipping.
08:30:29 Please update the minor SO version for libspdk_bdev_raid.so. API functions or variables have been added since last release.
08:30:29 No corresponding object for libspdk_bdev_rbd.so in canonical directory. Skipping.
08:30:31 No corresponding object for libspdk_reduce.so in canonical directory. Skipping.
08:30:31 Processed 61 objects.
08:30:31 
08:30:31 real	0m2.900s
08:30:31 user	0m2.427s
08:30:31 sys	0m0.465s
08:30:31 ************************************
08:30:31 END TEST confirm_abi_deps
08:30:31 ************************************
08:30:31 ---------------------------------------------------------------------
08:31:43 Updated 1 path from the index
08:31:43 shared object test failed
```

SPDK 20.04 reference build was built using routine from this patch:
https://review.spdk.io/gerrit/c/spdk/spdk/+/1653/10

## Possible Solution

Find related API changes in commit history and bump up SO_MINOR numbers in Makefiles?
@Seth5141 already found a related change for NVMe-oF and changed the version in https://review.spdk.io/gerrit/c/spdk/spdk/+/2171/4 patch.
Increasing SO_MINOR for module/bdev/raid allowed to pass `confirm_abi_deps` test, but we couldn't find any related change that'd require changing SO_MINOR.

## Steps to Reproduce

1. Build reference spdk 20.04 build using this patch https://review.spdk.io/gerrit/c/spdk/spdk/+/1653/10
2. Run  ./autobuild.sh using commit: https://review.spdk.io/gerrit/c/spdk/spdk/+/2171/4 with following test flags:
```
SPDK_RUN_VALGRIND=1
SPDK_RUN_FUNCTIONAL_TEST=0
SPDK_TEST_AUTOBUILD=1
SPDK_TEST_UNITTEST=1
SPDK_TEST_BLOCKDEV=1
SPDK_TEST_PMDK=1
SPDK_TEST_ISAL=1
SPDK_TEST_REDUCE=1
SPDK_TEST_CRYPTO=1
SPDK_TEST_FTL=1
SPDK_TEST_OCF=1
SPDK_TEST_RAID5=1
SPDK_TEST_RBD=1
SPDK_RUN_ASAN=1
SPDK_RUN_UBSAN=1

RUN_NIGHTLY=0
```

**Comment by karlatec** [comment] 2020-05-05 10:52
Proposed fix in check_so_deps.sh file in commit: https://review.spdk.io/gerrit/c/spdk/spdk/+/2171/5/test/make/check_so_deps.sh
(thanks for help @Seth5141 !)

**Comment by Seth5141** [comment] 2020-05-05 20:58
Hi @karlatec I tried to reproduce this on fresh copies of the vagrant VMs and was unable to do so. I went ahead and updated the test pool VMs according to https://review.spdk.io/gerrit/c/spdk/spdk/+/1653/11 and the unittest job now passes on https://review.spdk.io/gerrit/c/spdk/spdk/+/2171/6. My best guess is that there was some kind of configuration issue leftover from an earlier version of the patch on your vagrant VM.

Since this is not reproducible and the patch has been demonstrated to work as expected without the bdev_raid modifications (minor version increment or abidiff exceptions), I am closing it. Please reopen it if I missed something.

**Closed by Seth5141** 2020-05-05 20:58 UTC
Labels: bug
