### ISSUE TITLE
[nvmf_multipath] subsystem reports inaccessible state

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1801] opened 2021-02-19 04:39 UTC
00:07:48.650   02:18:48	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py nvmf_subsystem_listener_set_ana_state nqn.2016-06.io.spdk:cnode1 -t tcp -a 10.0.0.2 -s 4420 -n optimized
00:07:48.875   02:18:48	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py nvmf_subsystem_listener_set_ana_state nqn.2016-06.io.spdk:cnode1 -t tcp -a 10.0.0.3 -s 4420 -n optimized
00:07:49.083   02:18:48	# sleep 1
00:07:50.087    02:18:49	# cat /sys/block/nvme2c2n1/ana_state
00:07:50.090   02:18:49	# '[' optimized == optimized ']'
00:07:50.091    02:18:49	# cat /sys/block/nvme2c3n1/ana_state
00:07:50.094   02:18:49	# '[' inaccessible == optimized ']'
00:07:50.094    02:18:49	# trap - ERR
00:07:50.094    02:18:49	# print_backtrace
00:07:50.094    02:18:49	# [[ ehxBET =~ e ]]
00:07:50.094    02:18:49	# args=("${BASH_ARGV[@]}")
00:07:50.094    02:18:49	# local args
00:07:50.094    02:18:49	# xtrace_disable
00:07:50.094    02:18:49	# '[' no '!=' yes ']'
00:07:50.094    02:18:49	# PREV_BASH_OPTS=ehxBET
00:07:50.094    02:18:49	# [[ ehxBET == *\x* ]]
00:07:50.094    02:18:49	# XTRACE_DISABLED=yes
00:07:50.094    02:18:49	# set +x
00:07:50.094  ========== Backtrace start: ==========
00:07:50.094  
00:07:50.107  in test/nvmf/target/multipath.sh:82 -> main(["--transport=tcp"])
00:07:50.107       ...
00:07:50.107     77  	$rpc_py nvmf_subsystem_listener_set_ana_state nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a "$NVMF_SECOND_TARGET_IP" -s "$NVMF_PORT" -n optimized
00:07:50.107     78  	
00:07:50.107     79  	sleep 1
00:07:50.107     80  	
00:07:50.107     81  	[ $(cat /sys/block/nvme"$subsys_id"c"$ctrl1_id"n1/ana_state) == "optimized" ]
00:07:50.107  => 82  	[ $(cat /sys/block/nvme"$subsys_id"c"$ctrl2_id"n1/ana_state) == "optimized" ]
00:07:50.107     83  	
00:07:50.107     84  	# Set IO policy to round-robin
00:07:50.107     85  	echo round-robin > /sys/class/nvme-subsystem/nvme-subsys$subsys_id/iopolicy
00:07:50.107     86  	
00:07:50.107     87  	$rootdir/scripts/fio.py -p nvmf -i 4096 -d 128 -t randrw -r 6 -v &
00:07:50.107       ...
00:07:50.107  
00:07:50.107  ========== Backtrace end ==========
00:07:50.107    02:18:49	# xtrace_enable
00:07:50.107    02:18:49	# return 0
00:07:50.107   02:18:49	# process_shm --id 0
00:07:50.107   02:18:49	# type=--id
00:07:50.107   02:18:49	# id=0
00:07:50.107   02:18:49	# '[' --id = --pid ']'
00:07:50.107   02:18:49	# '[' --id = --id ']'
00:07:50.107   02:18:49	# id=0
00:07:50.108    02:18:49	# find /dev/shm -name '*.0' -printf '%f\n'

**Comment by spdkci** [comment] 2021-02-19 04:40
Another instance of this failure. Reported by @jimharris. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36931.html

**Comment by yidong0635** [comment] 2021-02-20 01:58
Can anyone can clarify this?
   sometimes  non-optimized can't be configured on my side. but other states are ok. 
  and this issue is optimized state.

**Comment by shuhei-matsumoto** [comment] 2021-02-21 22:24
Hi @jimharris @yidong0635 

Is this issue one of CI intermittent failures?
Do you think this issue has occurred since months ago?
The multipath test was added before v20.10.

@yidong0635 
If you can reproduce very similar issue locally, will you share more detailed information?

The RPC nvmf_subsystem_listener_set_ana_state succeeded or failed when changing to the state, non-optimized? If failed, what is the return status?
If succeeded, what is the ANA state queried by the RPC nvmf_subsystem_get_listeners? The state was non-optimized?
The test test/nvmf/target/multipath.sh query the ANA state from the host side.

**Comment by yidong0635** [comment] 2021-02-22 02:43
sometimes fio keeps holding there:
```
 03:07:21       # '[' non-optimized == non-optimized ']'
  03:07:21      # cat /sys/block/nvme0c1n1/ana_state
 03:07:21       # '[' inaccessible == inaccessible ']'
 03:07:21       # wait 35960
Jobs: 1 (f=1): [m(1)][52.9%][eta 14m:30s]
```

**Comment by shuhei-matsumoto** [comment] 2021-02-22 03:09
Thanks for sharing the result. So it looks that application sometimes hung up when we change ANA state.

**Comment by jimharris** [comment] 2021-02-22 14:19
@shuhei-matsumoto I only saw this one time in CI last week.  It seems very intermittent.

**Comment by spdkci** [comment] 2021-02-24 07:41
Another instance of this failure. Reported by @optimistyzy. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_37245.html

**Comment by spdkci** [comment] 2021-04-07 21:43
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_41178.html

**Comment by spdkci** [comment] 2021-04-14 11:21
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_41750.html

**Comment by spdkci** [comment] 2021-04-22 03:05
Another instance of this failure. Reported by @dong-liuliu. log: https://ci.spdk.io/public_build/autotest-per-patch_43012.html

**Comment by spdkci** [comment] 2021-04-23 14:26
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_43288.html

**Comment by spdkci** [comment] 2021-05-04 09:16
Another instance of this failure. Reported by @floatious. log: https://ci.spdk.io/public_build/autotest-per-patch_44156.html

**Comment by spdkci** [comment] 2021-05-05 12:43
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_44166.html

**Comment by spdkci** [comment] 2021-05-07 12:36
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_44570.html

**Comment by spdkci** [comment] 2021-05-14 03:52
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_47291.html

**Comment by spdkci** [comment] 2021-05-14 05:44
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_47205.html

**Comment by spdkci** [comment] 2021-05-28 10:53
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_48587.html

**Comment by spdkci** [comment] 2021-05-28 12:22
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_48591.html

**Comment by spdkci** [comment] 2021-06-07 08:06
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_49152.html

**Comment by karlatec** [comment] 2021-06-28 07:59
Last instance was 21 days ago and it seems this no longer reproduces after upgrading our VM images from F31 to F33.
@jimharris @tomzawadzki we could probably close this one.

**Comment by shuhei-matsumoto** [comment] 2021-06-28 09:17
Thanks @karlatec for your check. I'm OK to close this but let's keep open another one https://github.com/spdk/spdk/issues/1819.
The issue @yidong0635 saw locally with the latest kernel is a different signature but we need to track it as a multipath issue.

**Comment by shuhei-matsumoto** [comment] 2021-07-27 21:19
The last report was a few months ago. Close this issue. Let's reopen if reported again.

**Closed by shuhei-matsumoto** 2021-07-27 21:19 UTC
Labels: Intermittent Failure
