### ISSUE TITLE
[FAQ]  accel_perf tool failed to parse the json config that is dumped by idxd_scan_accel_engine

### ISSUE THREAD

**Issue by gaowayne** [spdk/spdk#2468] opened 2022-04-14 13:27 UTC
# Bug report

[root@localhost spdk]# build/examples/accel_perf -q 8 -o 4096 -t 30 -w copy -c /root/wayne/dsa_2022.json
SPDK Configuration:
Core mask:      0x1

Accel Perf Configuration:
Workload Type:  copy
Transfer size:  4096 bytes
Queue depth:    8
Allocate depth: 8
# threads/core: 1
Run time:       30 seconds
Verify:         No

[2022-04-14 03:16:36.514938] Starting SPDK v22.05-pre git sha1 87cfed844 / DPDK 21.11.0 initialization...
[2022-04-14 03:16:36.515061] [ DPDK EAL parameters: [2022-04-14 03:16:36.515083] (null) [2022-04-14 03:16:36.515096] --no-shconf [2022-04-14 03:16:36.515108] -c 0x1 [2022-04-14 03:16:36.515124] --huge-unlink [2022-04-14 03:16:36.515136] --log-level=lib.eal:6 [2022-04-14 03:16:36.515152] --log-level=lib.cryptodev:5 [2022-04-14 03:16:36.515167] --log-level=user1:6 [2022-04-14 03:16:36.515182] --base-virtaddr=0x200000000000 [2022-04-14 03:16:36.515197] --match-allocations [2022-04-14 03:16:36.515213] --file-prefix=spdk_pid120812 [2022-04-14 03:16:36.515227] ]
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-04-14 03:16:36.605286] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 1
[2022-04-14 03:16:36.800716] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
[2022-04-14 03:16:36.813091] accel_engine_idxd_rpc.c:  60:rpc_idxd_scan_accel_engine: *ERROR*: spdk_json_decode_object() failed
[2022-04-14 03:16:36.817124] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32602,
  "message": "Invalid parameters"
}
[2022-04-14 03:16:36.817323] app.c: 693:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
[2022-04-14 03:16:36.817644] accel_perf.c: 767:main: *ERROR*: ERROR starting application
[root@localhost spdk]# 

## Expected Behavior

we should run accel_perf with the json file that is saved by idxd_scan_accel_engine

## Current Behavior

we can create one json from idxd_scan_accel_engine, but it cannot be parse correctly by accel_perf tool.

## Steps to Reproduce

1. start vhost build/bin/vhost --wait-for-rpc
2. start framework from RPC scripts/rpc.py framework_start_init
3. I can see idxd engine load well
```
[2022-04-14 03:08:29.275598] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 1
[2022-04-14 03:08:29.456440] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
[2022-04-14 03:08:37.412801] accel_engine_idxd_rpc.c:  70:rpc_idxd_scan_accel_engine: *NOTICE*: Enabling IDXD user-mode
[2022-04-14 03:13:27.525304] accel_engine.c: 548:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2022-04-14 03:13:28.877899] accel_engine_idxd.c: 422:accel_engine_idxd_init: *NOTICE*: Accel engine updated to use IDXD DSA engine.
```
4.  save the json config scripts/rpc.py save_config > /root/wayne/dsa_2022.json
```
{
  "subsystems": [
    {
      "subsystem": "scheduler",
      "config": [
        {
          "method": "framework_set_scheduler",
          "params": {
            "name": "static",
            "period": 1000000
          }
        }
      ]
    },
    {
      "subsystem": "accel",
      "config": [
        {
          "method": "idxd_scan_accel_engine",
          "params": {
            "config_kernel_mode": 0
          }
        }
      ]
    },
    {
      "subsystem": "vmd",
      "config": []
    },
    {
      "subsystem": "sock",
      "config": [
        {
          "method": "sock_impl_set_options",
          "params": {
            "impl_name": "posix",
            "recv_buf_size": 2097152,
            "send_buf_size": 2097152,
            "enable_recv_pipe": true,
            "enable_quickack": false,
            "enable_placement_id": 0,
            "enable_zerocopy_send_server": true,
            "enable_zerocopy_send_client": false
          }
        }
      ]
    },
    {
      "subsystem": "bdev",
      "config": [
        {
          "method": "bdev_set_options",
          "params": {
            "bdev_io_pool_size": 65535,
            "bdev_io_cache_size": 256,
            "bdev_auto_examine": true
          }
        },
        {
          "method": "bdev_nvme_set_options",
          "params": {
            "action_on_timeout": "none",
            "timeout_us": 0,
            "timeout_admin_us": 0,
            "keep_alive_timeout_ms": 10000,
            "transport_retry_count": 4,
            "arbitration_burst": 0,
            "low_priority_weight": 0,
            "medium_priority_weight": 0,
            "high_priority_weight": 0,
            "nvme_adminq_poll_period_us": 10000,
            "nvme_ioq_poll_period_us": 0,
            "io_queue_requests": 0,
            "delay_cmd_submit": true,
            "bdev_retry_count": 3,
            "transport_ack_timeout": 0,
            "ctrlr_loss_timeout_sec": 0,
            "reconnect_delay_sec": 0,
            "fast_io_fail_timeout_sec": 0
          }
        },
        {
          "method": "bdev_nvme_set_hotplug",
          "params": {
            "period_us": 100000,
            "enable": false
          }
        },
        {
          "method": "bdev_wait_for_examine"
        }
      ]
    },
    {
      "subsystem": "scsi",
      "config": null
    },
    {
      "subsystem": "nbd",
      "config": []
    },
    {
      "subsystem": "vhost",
      "config": []
    }
  ]
}
```

## Context (Environment including OS version, SPDK version, etc.)
fedoraOS33, SPDK master Starting SPDK v22.05-pre git sha1 87cfed844

https://spdk.io/doc/accel_fw.html
better more example json and helper steps in above manual

**Comment by peluse** [comment] 2022-04-14 13:46
A param was removed not too long ago and clearly the config_kernel got stepped on somehow.  I'll look at it today, thanks

**Comment by peluse** [comment] 2022-04-14 14:02
Not a bug actually, your JSON is off just a bit.

 "config_kernel_mode": 0

Should be:

 "config_kernel_mode": false

@gaowayne please try that and close this issue if it works for you

**Comment by gaowayne** [comment] 2022-04-14 14:24
> Not a bug actually, your JSON is off just a bit.
> 
> "config_kernel_mode": 0
> 
> Should be:
> 
> "config_kernel_mode": false
> 
> @gaowayne please try that and close this issue if it works for you

the config file is created by rpc save config command actually, I will verify this. if this is true. we just need fix save config part, I can try submit one patch if it is not too complex. :)

**Comment by gaowayne** [comment] 2022-04-14 14:27
@peluse  no, false does not work too. 
``` 
[root@localhost spdk]# build/examples/accel_perf -q 8 -o 4096 -t 30 -w copy -c /root/wayne/dsa_2022.json
SPDK Configuration:
Core mask:      0x1

Accel Perf Configuration:
Workload Type:  copy
Transfer size:  4096 bytes
Queue depth:    8
Allocate depth: 8
# threads/core: 1
Run time:       30 seconds
Verify:         No

[2022-04-14 04:27:42.969344] Starting SPDK v22.05-pre git sha1 87cfed844 / DPDK 21.11.0 initialization...
[2022-04-14 04:27:42.969486] [ DPDK EAL parameters: [2022-04-14 04:27:42.969508] (null) [2022-04-14 04:27:42.969521] --no-shconf [2022-04-14 04:27:42.969537] -c 0x1 [2022-04-14 04:27:42.969549] --huge-unlink [2022-04-14 04:27:42.969564] --log-level=lib.eal:6 [2022-04-14 04:27:42.969581] --log-level=lib.cryptodev:5 [2022-04-14 04:27:42.969595] --log-level=user1:6 [2022-04-14 04:27:42.969611] --base-virtaddr=0x200000000000 [2022-04-14 04:27:42.969625] --match-allocations [2022-04-14 04:27:42.969640] --file-prefix=spdk_pid121380 [2022-04-14 04:27:42.969655] ]
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-04-14 04:27:43.059573] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 1
[2022-04-14 04:27:43.252705] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
[2022-04-14 04:27:43.265122] accel_engine_idxd_rpc.c:  70:rpc_idxd_scan_accel_engine: *NOTICE*: Enabling IDXD user-mode
[2022-04-14 04:27:43.277155] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32601,
  "message": "Method not found"
}
[2022-04-14 04:27:43.277352] app.c: 693:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
[2022-04-14 04:27:43.277586] accel_perf.c: 767:main: *ERROR*: ERROR starting application
[root@localhost spdk]# 
```

**Comment by peluse** [comment] 2022-04-14 14:44
OK, different error (you are getting method error but a 0 will give you invalid parms). On my system on master I get the same failure as you when I provide 0 and it works fine when I provide false.  Here is my json file (file name is just j)
{
   "subsystems":[
      {
         "subsystem":"accel",
         "config":[
            {
               "params":{
		  "config_kernel_mode": false
               },
               "method":"idxd_scan_accel_engine"
            }
         ]
      }
   ]
}

and here is my cmd line

./accel_perf -w copy -c j
[2022-04-14 04:40:26.172810] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 1
[2022-04-14 04:40:26.392553] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
[2022-04-14 04:40:26.397444] accel_engine_idxd_rpc.c:  70:rpc_idxd_scan_accel_engine: *NOTICE*: Enabling IDXD user-mode
[2022-04-14 04:40:26.401484] accel_engine.c: 548:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2022-04-14 04:40:27.410713] accel_engine_idxd.c: 422:accel_engine_idxd_init: *NOTICE*: Accel engine updated to use IDXD DSA engine.
Running for 5 seconds..

Now if I change that "false" to 0:
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-04-14 04:41:33.137124] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 1
[2022-04-14 04:41:33.359866] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
[2022-04-14 04:41:33.364778] accel_engine_idxd_rpc.c:  60:rpc_idxd_scan_accel_engine: *ERROR*: spdk_json_decode_object() failed
[2022-04-14 04:41:33.368809] json_config.c: 221:rpc_client_poller: *ERROR*: error response:
{
  "code": -32602,
  "message": "Invalid parameters"
}

Might be easier for you to step through rpc_idxd_scan_accel_engine() and see what the problem is as opposed to me trying to repro with all of your RPC params.  Or, maybe try just using the simple case that I just described above and see if you get what I get

**Comment by peluse** [comment] 2022-04-14 15:06
@gaowayne re-reading this I might not have understood you specific report.  Are you saying that if you use wait-for-rpc and send the RPC commands in individually that things work but only after you save them to json and send that saved file in do you get this error?

Also looking at your output you get this line:

      rpc_idxd_scan_accel_engine: *NOTICE*: Enabling IDXD user-mod

which means you've processed the IDXD RPC just fine.  The "method not found" I'm assuming is coming from something else in your saved json file.

I'd suggest you look through each method in your json file and see if there's one that valid.  If so, there's likely a bug somehow in how it was saved but this is looking less and less like it has anything to do with IDXD.

**Comment by gaowayne** [comment] 2022-04-14 15:44
> @gaowayne re-reading this I might not have understood you specific report. Are you saying that if you use wait-for-rpc and send the RPC commands in individually that things work but only after you save them to json and send that saved file in do you get this error?

Wayne: yes, the error only happen, when I use accel_perf to parse the json file that is saved in one session that successfully scan the accel engine. I feel something wrong with json file. or can you give me one good json example file?
> 
> Also looking at your output you get this line:
> 
> ```
>   rpc_idxd_scan_accel_engine: *NOTICE*: Enabling IDXD user-mod
> ```
> 
> which means you've processed the IDXD RPC just fine. The "method not found" I'm assuming is coming from something else in your saved json file.
> 
> I'd suggest you look through each method in your json file and see if there's one that valid. If so, there's likely a bug somehow in how it was saved but this is looking less and less like it has anything to do with IDXD.

if I start one vhost, use rpc command(not json way), it works. but accel_perf need start from one json file. I remember this works last year. :) 
this json file is created by SPDK when I run save_config command. it should be parse correctly

**Comment by gaowayne** [comment] 2022-04-14 16:13
> > I'd suggest you look through each method in your json file and see if there's one that valid. If so, there's likely a bug somehow in how it was saved but this is looking less and less like it has anything to do with IDXD.
> 
> I think Paul meant 'invalid'.
> 
> I suspect that you have done a save_config while running something like nvmf_tgt or spdk_tgt. This will emit a lot of RPCs that are not valid for the accel_perf tool. For example, nvmf and bdev libraries are not linked into accel_perf, so any nvmf and bdev RPCs would fail with the "Method not found" error.
> 
> Please follow Paul's advice to go through your conf file in detail, removing anything not idxd related. That should get you unblocked for now. You may also try adding `--json-ignore-init-errors` to accel_perf command line.

thank you so much Jim, I understand now. I found below json works fine. I think you are right, save_config cannot directly be used by accel_perf I will try ignore next day too. I have to wrap up today. 
```
{
  "subsystems": [
    {
      "subsystem": "accel",
      "config": [
	    {
		  "method": "idxd_scan_accel_engine",        
		  "params": {
            "config_kernel_mode": false
          }          
        }
	  ]
    }
  ]
}
```

**Comment by peluse** [comment] 2022-04-14 17:32
BTW I also updated idxd to write a bool instead of 0 for that param.  See https://review.spdk.io/gerrit/c/spdk/spdk/+/12275

**Comment by peluse** [comment] 2022-04-14 17:33
@gaowayne I do not believe this is an accurate statement though "save_config cannot directly be used by accel_perf"

**Comment by jimharris** [comment] 2022-04-15 00:11
> @gaowayne I do not believe this is an accurate statement though "save_config cannot directly be used by accel_perf"

Agreed @peluse, if you save_config from accel_perf and reuse with accel_perf it should work fine.  I suspect @gaowayne may have done save_config from something like spdk_tgt which would then add a bunch of RPCs that accel_perf can't handle.  @gaowayne - can you confirm?

**Comment by gaowayne** [comment] 2022-04-15 00:15
> BTW I also updated idxd to write a bool instead of 0 for that param. See https://review.spdk.io/gerrit/c/spdk/spdk/+/12275

I add one plus for this patch, it looks great fix this issue.

**Comment by gaowayne** [comment] 2022-04-15 00:16
> > @gaowayne I do not believe this is an accurate statement though "save_config cannot directly be used by accel_perf"
> 
> Agreed @peluse, if you save_config from accel_perf and reuse with accel_perf it should work fine. I suspect @gaowayne may have done save_config from something like spdk_tgt which would then add a bunch of RPCs that accel_perf can't handle. @gaowayne - can you confirm?

I will confirm this today and keep you posted

**Comment by peluse** [comment] 2022-04-15 00:31
Great!

**Comment by gaowayne** [comment] 2022-04-15 12:10
> --json-ignore-init-errors
@jimharris  you are quite right, thank you so much for so clear explanation to me add ignore error flag helps. actually 0 or false is same thing in json. 
```
[root@localhost spdk]# build/examples/accel_perf -q 8 --json-ignore-init-errors -o 4096 -t 30 -w copy -c /root/wayne/dsa_2022.json
SPDK Configuration:
Core mask:      0x1

Accel Perf Configuration:
Workload Type:  copy
Transfer size:  4096 bytes
Queue depth:    8
Allocate depth: 8
# threads/core: 1
Run time:       30 seconds
Verify:         No

[2022-04-15 02:06:40.076837] Starting SPDK v22.05-pre git sha1 87cfed844 / DPDK 21.11.0 initialization...
[2022-04-15 02:06:40.076972] [ DPDK EAL parameters: [2022-04-15 02:06:40.076994] (null) [2022-04-15 02:06:40.077007] --no-shconf [2022-04-15 02:06:40.077024] -c 0x1 [2022-04-15 02:06:40.077036] --huge-unlink [2022-04-15 02:06:40.077052] --log-level=lib.eal:6 [2022-04-15 02:06:40.077064] --log-level=lib.cryptodev:5 [2022-04-15 02:06:40.077075] --log-level=user1:6 [2022-04-15 02:06:40.077091] --base-virtaddr=0x200000000000 [2022-04-15 02:06:40.077103] --match-allocations [2022-04-15 02:06:40.077116] --file-prefix=spdk_pid188018 [2022-04-15 02:06:40.077128] ]
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-04-15 02:06:40.168053] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 1
[2022-04-15 02:06:40.361663] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
[2022-04-15 02:06:40.374048] accel_engine_idxd_rpc.c:  70:rpc_idxd_scan_accel_engine: *NOTICE*: Enabling IDXD user-mode
[2022-04-15 02:06:40.386078] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32601,
  "message": "Method not found"
}
[2022-04-15 02:06:40.394078] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32601,
  "message": "Method not found"
}
[2022-04-15 02:06:40.402079] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32601,
  "message": "Method not found"
}
[2022-04-15 02:06:40.410080] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32601,
  "message": "Method not found"
}
[2022-04-15 02:06:40.418081] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32601,
  "message": "Method not found"
}
[2022-04-15 02:06:40.418095] accel_engine.c: 548:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2022-04-15 02:06:40.438340] accel_engine_idxd.c: 417:accel_engine_idxd_init: *NOTICE*: no available idxd devices
[2022-04-15 02:06:40.450399] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32601,
  "message": "Method not found"
}
[2022-04-15 02:06:40.458399] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32601,
  "message": "Method not found"
}
[2022-04-15 02:06:40.466399] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32601,
  "message": "Method not found"
}
[2022-04-15 02:06:40.474400] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32601,
  "message": "Method not found"
}
[2022-04-15 02:06:40.482401] json_config.c: 221:rpc_client_poller: *ERROR*: error response: 
{
  "code": -32601,
  "message": "Method not found"
}
Running for 30 seconds...

Core,Thread   Transfers     Bandwidth     Failed     Miscompares
------------------------------------------------------------------------
0,0         11370357/s    44415 MiB/s      0           0
=========================================================================
Total:       11370357/s    44415 MiB/s     0           0
```

**Comment by tomzawadzki** [comment] 2022-04-19 15:04
Bug scrub: The issue was due to the json_config entries not matching those handled by accel_perf. The issue can be closed.

**Closed by tomzawadzki** 2022-04-19 15:04 UTC
Labels: Sighting

**Comment by navya93900** [comment] 2025-03-19 06:59
*ERROR*: Failed to parse subsystem configuration
when i am try to use the spdkcli tool i am getting JSON  parse error 
{
    "subsystems": [
        {
            "name": "vhost-net",
            "params": {
                "socket_path": "/tmp/vhost_net.sock"
            }
        },
        {
            "name": "vhost-blk",
            "params": {
                "socket_path": "/tmp/vhost_blk.sock"
            }
        }
    ]
}

can any one help me
