### ISSUE TITLE
nvmf connect fail when setting`src_addr`

### ISSUE THREAD

**Issue by ShaoxunZeng** [spdk/spdk#2604] opened 2022-07-23 07:54 UTC
# Bug report

When using `rpc.py` to connect nvmf target, I want to use specific NIC, so I set `spdk_nvme_ctrlr_opts.src_addr` with an IP addr. But the host (`spdk_tgt`) fail, I suspect the problem is in the IP addr translation.

## Steps to Reproduce
First I start up target using ` ./build/bin/nvmf_tgt -c ./app/nvmf_tgt/config.json`, and in the host side I run `./build/bin/spdk_tgt` as RPC client, and `rpc.py` command as follows:
```sh
./scripts/rpc.py bdev_nvme_attach_controller -t RDMA -a 192.168.2.175 -s 4410 -n nqn.2016-06.io.spdk:cnode1 -b nvme0 -f ipv4 -i 192.168.2.172 -c 6000
```
where `192.168.2.175` is target's IP addr, and `192.168.2.172` is the host's specific NIC IP addr.

This command seems successful:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/35787647/180595802-983dd18c-6baf-4638-8c3e-d841e8121eea.png">
but when I check `./build/bin/spdk_tgt ` I find it's not OK:
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/35787647/180595870-49e41e63-8024-46e7-9747-2aff4bc106da.png">
And once I'm not setting `-i` and  `-c`, everything is OK.

I also try to write codes instead of using `rpc.py`:
```c
static bool
probe_cb(void *cb_ctx, const struct spdk_nvme_transport_id *trid,
	 struct spdk_nvme_ctrlr_opts *opts)
{
	printf("Attaching to %s\n", trid->traddr);
	snprintf(opts->src_addr, 256, "%s", "192.168.2.170");
	snprintf(opts->src_svcid, 32, "%s", "6000");
	return true;
}
```
but it is the same problem. And once I'm not setting `src_addr`, everything is OK.

## Possible Solution

I check the error code 98, it seems `rdma_resolve_addr` cannot resolve the IP addr, but it's fine running `ping 192.169.2.172` from both sides.

## Context (Environment including OS version, SPDK version, etc.)

OS: host side: ubuntu18, target side: ubuntu20
spdk 22.04

**Comment by yidong0635** [comment] 2022-07-25 03:54
hi @ShaoxunZeng , Have you filling this `struct sockaddr *src_addr` ? It seems you are only filling an IP address.
  rc = nvme_rdma_resolve_addr(rqpair,
                                    src_addr_specified ? (struct sockaddr *)&src_addr : NULL,
                                    (struct sockaddr *)&dst_addr);
For NULL, it always works.

**Comment by Comphix** [comment] 2022-07-25 06:27
@ShaoxunZeng could you also have a try with TCP transport instead of RDMA here? Let's check whether TCP works or not in your case.

I am using the master SPDK branch, with TCP in loopback mode, it works if host address is specified.

```
# ./scripts/rpc.py -s /var/tmp/spdk_host.sock bdev_nvme_attach_controller -t TCP -a 127.0.0.1 -s 4420 -n nqn.2016-06.io.spdk:cnode1 -b NVMe0 -f ipv4 -i 127.0.0.1 -c 6000
NVMe0n1
```

**Comment by ShaoxunZeng** [comment] 2022-07-27 10:00
> @ShaoxunZeng could you also have a try with TCP transport instead of RDMA here? Let's check whether TCP works or not in your case.
> 
> I am using the master SPDK branch, with TCP in loopback mode, it works if host address is specified.
> 
> ```
> # ./scripts/rpc.py -s /var/tmp/spdk_host.sock bdev_nvme_attach_controller -t TCP -a 127.0.0.1 -s 4420 -n nqn.2016-06.io.spdk:cnode1 -b NVMe0 -f ipv4 -i 127.0.0.1 -c 6000
> NVMe0n1
> ```

I try with a new machine, now it works fine for me. I guess there are some wrong configurations in my old machine.

**Comment by Comphix** [comment] 2022-07-27 10:03
Thanks. In this case, close this issue first.

**Comment by ShaoxunZeng** [comment] 2022-08-09 02:29
Sorry guys, I find it is still a problem when changing to a new machine.

**Comment by Comphix** [comment] 2022-08-09 04:53
> Sorry guys, I find it is still a problem when changing to a new machine.

So does it mean in the old and new machines, it could not work as previously it is mentioned on the new machine, it can work?

**Comment by ShaoxunZeng** [comment] 2022-08-09 06:54
> > Sorry guys, I find it is still a problem when changing to a new machine.
> 
> So does it mean in the old and new machines, it could not work as previously it is mentioned on the new machine, it can work?

No, I find it work occasionally, and I can not reproduce the successful one now.

**Comment by Comphix** [comment] 2022-08-10 08:02
Tried to use the loopback on my local environment as following, it looks like workable.

Target IP: 192.168.100.8
Host IP: 192.168.100.9
SPDK: master 
1. start spdk_tgt
2. configure NVMe-oF related with IP: 192.168.100.8
3. start bdevperf
4. RPC to attach with IP: 192.100.9
All these running on one machine

Will you also have a try with loopback?

```
root@storage35:/home/spdk# ./scripts/rpc.py -s /var/tmp/spdk_host.sock bdev_nvme_attach_controller -b NVMe0 -t tcp -a 192.168.100.8 -s 4420 -f ipv4 -n nqn.2016-06.io.spdk:cnode1 -i 192.168.100.9
NVMe0n1

root@storage35:/home/spdk# ./scripts/rpc.py -s /var/tmp/spdk_host.sock bdev_get_bdevs
[
  {
    "name": "NVMe0n1",
    "aliases": [
      "aae3ce38-9253-48e6-a7e4-c8db28d25ead"
    ],
    "product_name": "NVMe disk",
    "block_size": 512,
    "num_blocks": 131072,
    "uuid": "aae3ce38-9253-48e6-a7e4-c8db28d25ead",
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0
    },
    "claimed": false,
    "zoned": false,
    "supported_io_types": {
      "read": true,
      "write": true,
      "unmap": true,
      "write_zeroes": true,
      "flush": true,
      "reset": true,
      "nvme_admin": true,
      "nvme_io": true
    },
    "driver_specific": {
      "nvme": [
        {
          "trid": {
            "trtype": "TCP",
            "adrfam": "IPv4",
            "traddr": "192.168.100.8",
            "trsvcid": "4420",
            "subnqn": "nqn.2016-06.io.spdk:cnode1"
          },
          "ctrlr_data": {
            "cntlid": 2,
            "vendor_id": "0x8086",
            "model_number": "SPDK bdev Controller",
            "serial_number": "SPDK0001",
            "firmware_revision": "22.09",
            "subnqn": "nqn.2016-06.io.spdk:cnode1",
            "oacs": {
              "security": 0,
              "format": 0,
              "firmware": 0,
              "ns_manage": 0
            },
            "multi_ctrlr": true,
            "ana_reporting": false
          },
          "vs": {
            "nvme_version": "1.3"
          },
          "ns_data": {
            "id": 1,
            "can_share": true
          }
        }
      ],
      "mp_policy": "active_passive"
    }
  }
]
```

**Comment by ShaoxunZeng** [comment] 2022-08-10 10:23
> 

I try in two machines, one is target and one is host, and I find it works fine with trtype TCP.

**Comment by Comphix** [comment] 2022-08-10 11:05
TCP is ok, could be some issue with RDMA.

Besides the RDMA related log in the issue description, any more RDMA logs relating to this issue?

**Comment by ShaoxunZeng** [comment] 2022-08-16 13:09
> 

I don't see any new RDMA related logs. When I further run the code with gdb, I find it is pretty strange.
NVMF RDMA would call `rdma_resolve_addr` when probe nvme dev, and it is successful.
After probe, when create qp, spdk would call  `rdma_resolve_addr` again, and this time it failed, return the error above.

**Comment by Comphix** [comment] 2022-08-17 01:53
> > 
> 
> I don't see any new RDMA related logs. When I further run the code with gdb, I find it is pretty strange. NVMF RDMA would call `rdma_resolve_addr` when probe nvme dev, and it is successful. After probe, when create qp, spdk would call `rdma_resolve_addr` again, and this time it failed, return the error above.

#define EADDRINUSE  98  /* Address already in use */

This is the 98 error code noticed, in this case, it looks like the second rdma_resolve_addr call and failure is due to the address has been probed and in use?

**Comment by Comphix** [comment] 2022-08-17 04:26
Could you have a try with below change?

```
static int
nvme_rdma_resolve_addr(struct nvme_rdma_qpair *rqpair,
		       struct sockaddr *src_addr,
		       struct sockaddr *dst_addr)
{
	int ret;

	ret = rdma_resolve_addr(rqpair->cm_id, src_addr, dst_addr,
				NVME_RDMA_TIME_OUT_IN_MS);
	if (ret && ret != EADDRINUSE) {   <<<<<< Check the specific EADDRINUSE error here
		SPDK_ERRLOG("rdma_resolve_addr, %d\n", errno);
		return ret;
	}

	return nvme_rdma_process_event_start(rqpair, RDMA_CM_EVENT_ADDR_RESOLVED,
					     nvme_rdma_addr_resolved);
}
```

**Comment by shuhei-matsumoto** [comment] 2022-08-17 21:52
Hi @ShaoxunZeng Please give time. We will take a look.

**Comment by shuhei-matsumoto** [comment] 2022-08-19 06:34
Hi @ShaoxunZeng 

I used one server and hacked source address automatically resolved, and then added it manually via -i and -c. However, it failed by the same error code. I have not used two servers yet. In my case, even the bdev_nvme_attach_controller command failed. I guess -i and -c are not available for RDMA transport, but I need to get more information by myself or from expert. Please wait a little more.

**Comment by ShaoxunZeng** [comment] 2022-08-21 13:52
> Hi @ShaoxunZeng
> 
> I used one server and hacked source address automatically resolved, and then added it manually via -i and -c. However, it failed by the same error code. I have not used two servers yet. In my case, even the bdev_nvme_attach_controller command failed. I guess -i and -c are not available for RDMA transport, but I need to get more information by myself or from expert. Please wait a little more.

thx

**Comment by shuhei-matsumoto** [comment] 2022-08-24 08:24
Hi @ShaoxunZeng one small update. I could reproduce the same issue by using two different servers. More update will follow but it may take time. Thanks for your patience.

**Comment by shuhei-matsumoto** [comment] 2022-08-25 12:05
Hi @ShaoxunZeng Thanks again for finding this issue.

SPDK NVMe-RDMA initiator calls rdma_resolve_addr() for each qpair. If we specify a source address, the source address is passed to rdma_resolve_addr() calls.

rdma_resolve_addr() or rdma_bind_addr() limits a source address to one CM ID, i.e., one qpair.

When attaching a controller, admin qpair is created and connected first, then one or more I/O qpairs follow.
By the limitation of rdma_resolve_addr(), only admin qpair is successfully connected, and all I/O qpairs fail to connect.

Hence, source address is not supported for RDMA transport.
I will create a patch to guard us from errors you saw for RDMA transport.

For your use case, please omit -i and -c of bdev_nvme_attach_controller RPC for RDMA transport.

**Comment by ShaoxunZeng** [comment] 2022-08-25 13:32
> Hi @ShaoxunZeng Thanks again for finding this issue.
> 
> SPDK NVMe-RDMA initiator calls rdma_resolve_addr() for each qpair. If we specify a source address, the source address is passed to rdma_resolve_addr() calls.
> 
> rdma_resolve_addr() or rdma_bind_addr() limits a source address to one CM ID, i.e., one qpair.
> 
> When attaching a controller, admin qpair is created and connected first, then one or more I/O qpairs follow. By the limitation of rdma_resolve_addr(), only admin qpair is successfully connected, and all I/O qpairs fail to connect.
> 
> Hence, source address is not supported for RDMA transport. I will create a patch to guard us from errors you saw for RDMA transport.
> 
> For your use case, please omit -i and -c of bdev_nvme_attach_controller RPC for RDMA transport.

But how can I use tow RDMA NICs if I can not point out the IP address?

**Comment by shuhei-matsumoto** [comment] 2022-08-26 06:47
Your request is reasonable. I am investigating more. Please wait a little more.

**Comment by shuhei-matsumoto** [comment] 2022-08-26 07:59
Hi @ShaoxunZeng 

https://review.spdk.io/gerrit/c/spdk/spdk/+/14229 fixed the issue locally. REUSEADDR option worked as long as I tested. Will you try this patch in your system?

**Comment by Comphix** [comment] 2022-08-29 03:13
@ShaoxunZeng , any feedback on above change? Does it fix the issue?

**Comment by Comphix** [comment] 2022-09-05 02:22
Close this issue and if it is seen again with above fix (already merged in SPDK master), please re-open this issue. Thanks.

**Closed by Comphix** 2022-09-05 02:22 UTC
Labels: Sighting

**Comment by spdkci** [comment] 2022-09-17 23:23
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_85607.html
