### ISSUE TITLE
Run RDMA test with spdk's perf failed: trtype 1 not available

### ISSUE THREAD

**Issue by brave-hannah** [spdk/spdk#145] opened 2017-04-22 12:54 UTC
I have already run the nvmf_tgt exe on the target server, and both IP can ping each other. But when I use spdk's perf running RDMA test, it runs into an error like:
_EAL:XXX
EAL:XXX
Initializing NVMe Controllers
nvme.c: 410: spdk_nvme_probe: ***ERROR*** NVMe trtype 1 not available
spdk_nvme_probe() failed for transport address 'xxx.xxx.xxx.xxx'_
I guess I just misunderstood perf's usage again...
My command line is below
_./perf -q 1 -s 4096 -w read -M 100 -t 60 -r 'trtype:RDMA adrfam:IPv4 traddr:xxx.xxx.xxx.xxx trsvcid:1023 subnqn:nqn.2016-06.io.spdk:cnode1' -d 2048_
But can we use perf as a Host nvmf server to connect the target ? Then how ?

**Comment by benlwalker** [comment] 2017-04-22 15:13
When you compiled, did you add CONFIG_RDMA=y to the command line? RDMA requires extra dependencies so it isn't enabled by default. If you are using the latest release you'd build like this:

    make DPDK_DIR=... CONFIG_RDMA=y

If you are following the tip of master we've simplified it a little bit. You can do:

    ./configure --with-dpdk=... --with-rdma
    make

The way you are running perf otherwise seems fine.

**Comment by brave-hannah** [comment] 2017-04-24 02:29
The version I am using is  spdk-17.03. I have changed the RDMA setting of CONFIG file to 'CONFIG_RDMA?=y', before making the whole package as 'make DPDK_DIR=./dpdk-17.02/x86_64-native-linuxapp-gcc'. I will try what you suggests.

**Comment by brave-hannah** [comment] 2017-04-24 02:52
I change make command to 'make DPDK_DIR=... CONFIG_RDMA=y', but it still can't work. Always the same error.

**Comment by benlwalker** [comment] 2017-04-24 16:07
Please try the following from the root of the repository (this will destroy any changes you have locally and delete all uncommited files, so make a copy if you made changes):

    git clean -x -d -f -f
    git checkout v17.03
    make DPDK_DIR=<dpdk_path> CONFIG_RDMA=y
    ./examples/nvme/perf/perf -q 1 -s 4096 -w read -M 100 -t 60 -r 'trtype:RDMA adrfam:IPv4 traddr:<ip address of target> trsvcid:1023 subnqn:nqn.2016-06.io.spdk:cnode1' -d 2048

Attach a log of the output of this sequence of steps to this issue if any step fails. The problem is definitely that you don't have the RDMA libraries compiled into your `perf` binary.

**Comment by benlwalker** [comment] 2017-06-06 16:24
Did this end up fixing the problem? If I don't hear back in a few days I'm going to assume it did and close out the issue.

**Comment by ksubbiahx** [comment] 2017-06-20 07:36
Hi benlwalker,

I am running spdk's identify and perf example from host and I configured kernel nvme target and it is listening on address 1.1.1.1 and port 4420.
When I run spdk's identify example from host I am getting following error:

[root@localhost identify]# ./identify -r 'trtype:RDMA adrfam:IPv4 traddr:1.1.1.1 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:name1'
Starting DPDK 17.02.0 initialization...
[ DPDK EAL parameters: identify -c 0x1 -n 1 -m 64 --file-prefix=spdk_pid14818 ]
EAL: Detected 36 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
nvme.c: 417:spdk_nvme_probe: ***ERROR*** NVMe trtype 1 not available
spdk_nvme_probe() failed

Can you tell me what could be the issue?

Sometimes getting the error "NVMEoF connect command failed"

**Comment by Comphix** [comment] 2017-06-20 13:14
Hi, have you built the SPDK with “CONFIG_RDMA?=y” in the CONFIG file under the SPDK root folder. Or “export CONFIG_RDMA=y” before building.

Thanks,
Gang

**Comment by sudhesam** [comment] 2018-01-22 21:11
Hello,

Below is the details of my setup.

I have 2 Ubuntu VM's running as initiator (SudheUbu1) and target (SudheUbu2). I am using SoftRoCE based initiator -> target data transfer.

I have created an 'emulated' NVMe device on the target and exported the device as SPDK device. Below is the configuration file on the target:

root@SudheUbu2:/home/ssgroot/GIT_REPOS/spdk/etc/spdk# lspci | grep mem
0b:00.0 Non-Volatile memory controller: VMware Device 07f0

root@SudheUbu2:/home/ssgroot/GIT_REPOS/spdk/etc/spdk# grep Transport nvmf.conf
TransportId "trtype:PCIe traddr:0000:0b:00.0" Nvme1

Below is my subsystem configuration setting on the target :

Namespaces backed by physical NVMe devices
[Subsystem1]
NQN nqn.2016-06.io.spdk:cnode1
Listen RDMA 192.168.123.2:4420
AllowAnyHost Yes
Host nqn.2016-06.io.spdk:init
SN SPDK00000000000001
Namespace Nvme1n1 1

On the initiator side, I am able to see the device as SPDK target. Below is the output of 'nvme list' command :

root@SudheUbu1:/tmp/ssam# nvme list
Node SN Model Namespace Usage Format FW Rev

/dev/nvme0n1 VMWare NVME-0000 Virtual disk 1 10.74 GB / 10.74 GB 512 B + 0 B 1.0
/dev/nvme1n1 SPDK00000000000001 SPDK bdev Controller 1 10.74 GB / 10.74 GB 512 B + 0 B 18.01
root@SudheUbu1:/tmp/ssam#

Now, when I run 'identify' application, I get the following error :

root@SudheUbu1:/tmp/ssam# ./identify -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.123.2 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode1'
Starting DPDK 17.02.0 initialization...
[ DPDK EAL parameters: identify -c 0x1 -n 1 -m 64 --no-pci --file-prefix=spdk_pid4845 ]
EAL: Detected 2 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
nvme.c: 417:spdk_nvme_probe: ERROR: NVMe trtype 1 not available
spdk_nvme_probe() failed

But, when I run the 'perf' application, I get the following :

root@SudheUbu1:/tmp/ssam# ./perf -q 1 -s 4096 -w read -M 100 -t 60 -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.123.2 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode1' -d 2048
Ignoring -M option... Please use -M option only when using rw or randrw.
Starting DPDK 17.02.0 initialization...
[ DPDK EAL parameters: perf -c 0x1 -m 2048 --no-pci --file-prefix=spdk_pid4836 ]
EAL: Detected 2 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
**Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 192.168.123.2:4420: nqn.2016-06.io.spdk:cnode1
Attached to NVMe over Fabrics controller at 192.168.123.2:4420: nqn.2016-06.io.spdk:cnode1
Associating SPDK bdev Controller (SPDK00000000000001 ) with lcore 0
Initialization complete. Launching workers.**
Starting thread on core 0
nvme_rdma.c:1448:nvme_rdma_qpair_process_completions: ERROR: CQ error on Queue Pair 0x55fc1f04cbc0, Response Index 94541342743896 (12): transport retry counter exceeded
nvme_rdma.c:1448:nvme_rdma_qpair_process_completions: ERROR: CQ error on Queue Pair 0x55fc1f04cbc0, Response Index 1 (5): Work Request Flushed Error

Any help appreciated.

**Comment by dverkamp-intel** [comment] 2018-05-22 21:21
I think the original issue here was due to build configuration (trtype 1 is RDMA, which is only available when building with ./configure --with-rdma), so I'm going to close the issue.  If there are other problems still happening, please open a new issue to track them separately.

**Closed by dverkamp-intel** 2018-05-22 21:21 UTC
Labels: question
