### ISSUE TITLE
Not enough huge pages on CI machine

### ISSUE THREAD

**Issue by Maciej-Szwed** [spdk/spdk#1332] opened 2020-04-07 09:00 UTC
One of the machines run out of huge pages:
https://10.102.17.111:8080/job/vhost-initiator-autotest/9181/console

**Comment by spdkci** [comment] 2020-04-07 09:02
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_9306.html

**Comment by tomzawadzki** [comment] 2020-04-07 15:20
[Bug scrub]: Issue occurs due to machine being up for too long, and memory being fragmented. One way would be to reboot the machine after each build. Yet this will get addressed when we switch to Vagrant provisioning on each job run. Let's wait for the switch.

**Comment by spdkci** [comment] 2020-04-08 09:48
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_9585.html

**Comment by karlatec** [comment] 2020-04-08 09:51
@Maciej-Szwed In that case you should probably change the issue title. THe last occurence wasn't vhost initiaotr

**Comment by karlatec** [comment] 2020-04-08 09:51
@wawryk Can you please take a look at SM0 VM and memory configuration? Last occurence was on a VM hosted on SM0 which was set up recently

**Comment by wawryk** [comment] 2020-04-08 10:20
I removed one vm from SM0 and now we have 12 vm's witch 130 huge pages available.

**Comment by spdkci** [comment] 2020-04-08 14:10
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_9597.html

**Comment by spdkci** [comment] 2020-04-08 16:36
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_9656.html

**Comment by karlatec** [comment] 2020-04-08 16:45
There will be a lot of reports here from today.
Copying my message from Slack here.
```
 I just noticed that new VMs were not being reset properly.
The reason was misconfiguration of ssh daemon and Jenkins wasn't able to restart the VMs remotely. "failed hugepages" stuff was probably a result of previously failed builds which either didn't free hugepages or there was some other app running in the background.
```

**Comment by changpe1** [comment] 2020-04-16 02:46
issue #1309 is also related with this.

**Comment by changpe1** [comment] 2020-04-16 04:22
[Bug Scrub] keep it open for now.

**Comment by karlatec** [comment] 2020-04-16 05:44
> issue #1309 is also related with this.

#1309 only happens on one specific physical system (GP3) and always ends with assertion/coredump
#1332 happens only on VMs and is caused by lack of memory for reserving hugepages.

Totally unrelated issues in my opinion.
I hasn't happened for 8 days now. Personally I'd close it now, but I'm ok with waiting a bit longer to be sure.

**Comment by tomzawadzki** [comment] 2020-04-21 13:37
As per @karlatec comment https://github.com/spdk/spdk/issues/1332#issuecomment-611067371, this has been occurring due to machines not properly resetting after failures. After the fix 13 days ago, no new report since.

**Closed by tomzawadzki** 2020-04-21 13:37 UTC
Labels: Intermittent Failure
