### ISSUE TITLE
Nightly test machines kernel version should be updated due to changes in DPDK

### ISSUE THREAD

**Issue by Maciej-Szwed** [spdk/spdk#1859] opened 2021-03-26 09:25 UTC
Nightly tests (spdk-master-vs-dpdk-main and spdk-v21.01-LTS-vs-dpdk-main) fail due to dpdk governor test failure. It happens due to recent change in DPDK: https://git.dpdk.org/dpdk/commit/?id=4db9587bbf726a658807089e0af162208e9bd2ee
DPDK disables power management, when it finds a kernel bug. It is present in kernel versions < 5.8.7. Scheduler behaves correctly and disables governor functionality, but CI test do not discover that and try to test it anyway.

Suggestion: update kernel to version at lease 5.8.7 using command: sudo dnf update kernel kernel-core kernel-modules kernel-modules-extra kernel-tools kernel-tools-libs kernel-devel kernel-headers

**Comment by karlatec** [comment] 2021-03-26 09:28
@wawryk after you update the systems please remember to:
- rebuild fio in /usr/src/fio
- rebuild QAT driver (unfortunately youre going to cherry-pick this: https://review.spdk.io/gerrit/c/spdk/spdk/+/7010, it's not merged yet)

**Comment by mikeBashStuff** [comment] 2021-03-26 09:53
I don't think upgrading the kernel will help here in any way. From the patch it seems that the path which affects all the systems which run vs-dpdk jobs, and which are not suffering from the kernel bug dpdk is describing, is this:

`FOPEN_OR_ERR_RET(f_base, -1)`

governor now fails if `base_frequency` cpufreq attribute is not opened. This is also seen in the logs:
```
# not very useful as it doesn't show which file but it's definitely the base_frequency
POWER: File not opened
00:08:43.561  POWER: Cannot init for setting frequency for lcore 1
```

The problem is  that this attribute simply doesn't exist under `/cpufreq` for these particular cpus. So the base frequency in this case is always set to 0 so it cannot be greater than max base frequency the patch is describing as a kernel bug.

**Comment by mikeBashStuff** [comment] 2021-03-26 10:06
And to note, the `base_frequency` is present under `cpufreg` only if given cpu supports HWP feature and intel_pstate runs in an active state. The latter is in place on the fedora_phy_nightly boxes, but cpuid seems to say HWP is not supported there:
```
[root@lab-fedora3 ~]# hexdump -n16 -s $((16 * 6)) -vC /dev/cpu/1/cpuid
00000060  77 00 00 00 02 00 00 00  09 00 00 00 00 00 00 00  |w...............|
00000070
[root@lab-fedora3 ~]#
[root@spdk-fedora-03 ~]# hexdump -n16 -s$((16 * 6)) -vC /dev/cpu/1/cpuid
00000060  75 00 00 00 02 00 00 00  09 00 00 00 00 00 00 00  |u...............|
00000070
[root@spdk-fedora-03 ~]# ((0x75 & 1 << 7)); echo $?
1 # no HWP
[root@spdk-fedora-03 ~]# ((0x75 & 1 << 1)); echo $?
1 # no turbo. Just pointing out since most of our boxes does support it
[root@spdk-fedora-03 ~]#
```

**Comment by mikeBashStuff** [comment] 2021-03-29 09:57
Submitted issue on the DPDK side: https://bugs.dpdk.org/show_bug.cgi?id=668

**Comment by anatolyburakov** [comment] 2021-03-31 14:54
> The problem is that this attribute simply doesn't exist under `/cpufreq` for these particular cpus. So the base frequency in this case is always set to 0 so it cannot be greater than max base frequency the patch is describing as a kernel bug.

Just to provide some context: you're correct, `base_frequency` cannot be bigger than max frequency when it doesn't exist 😄 the original problem was that on some CPU's/kernel versions, the `base_frequency` reporting in the kernel seems to be broken (i have an old Broadwell-era Xeon that exhibits this behavior), which is why the fix was introduced in the first place. If you rely on this particular sysfs value anywhere in SPDK, you might want to double check your code.

and yes, the `FOPEN_OR_ERR_RET(f_base, -1)` seems like a copy-paste error. i didn't see this bug before today, but the patch i submitted earlier should address the bug 668 as well, so thanks for bringing it to our attention!

**Comment by mikeBashStuff** [comment] 2021-04-01 10:18
Just to confirm that patch from @anatolyburakov works, tested it against our vs-main-dpdk job.

**Comment by jimharris** [comment] 2021-04-06 15:12
Closed based on feedback from @mikeBashStuff

**Closed by jimharris** 2021-04-06 15:12 UTC
Labels: Sighting
