### ISSUE TITLE
freebsd-vg-autotest(SSH library)

### ISSUE THREAD

**Issue by glodfish-zg** [spdk/spdk#1645] opened 2020-10-23 05:44 UTC
Failure log:

00:03:25.180  + vagrant ssh -c 'git -C /home/vagrant/spdk_repo/spdk reset --hard'
00:03:43.999  Handy bash(1) prompt:  PS1="\u@\h \w \!$ "
00:03:43.999  		-- David Scheidt <dscheidt@tumbolia.com>
00:03:44.339  HEAD is now at 5bbc1617f bdev: fix md_buf split issue
00:03:44.413  + [[ -f /var/jenkins/workspace/freebsd-vg-autotest/autorun-spdk.conf ]]
00:03:44.413  + vagrant upload /var/jenkins/workspace/freebsd-vg-autotest/autorun-spdk.conf /home/vagrant/autorun-spdk.conf
00:03:47.469  Uploading /var/jenkins/workspace/freebsd-vg-autotest/autorun-spdk.conf to /home/vagrant/autorun-spdk.conf
00:04:02.711  An error occurred in the underlying SSH library that Vagrant uses.
00:04:02.711  The error message is shown below. In many cases, errors from this
00:04:02.711  library are caused by ssh-agent issues. Try disabling your SSH
00:04:02.711  agent or removing some keys and try again.
00:04:02.711  
00:04:02.711  If the problem persists, please report a bug to the net-ssh project.
00:04:02.711  
00:04:02.711  timeout during server version negotiating
00:04:02.736  + vagrant destroy -f
00:04:06.197  ==> default: Removing domain...
00:04:06.511  Build step 'Execute shell' marked build as failure
00:04:06.554  [PostBuildScript] - [INFO] Executing post build scripts.
00:04:06.561  [freebsd-vg-autotest] $ /usr/bin/env bash /tmp/jenkins7099267234952725816.sh
00:04:06.565  + [[ -n freebsd12 ]]
00:04:06.565  + mv /var/jenkins/workspace/freebsd-vg-autotest/freebsd12-libvirt/output /var/jenkins/workspace/freebsd-vg-autotest/output
00:04:06.583  [freebsd-vg-autotest] $ /usr/bin/env bash /tmp/jenkins813513827099754654.sh

**Comment by spdkci** [comment] 2020-10-23 05:45
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_29278.html

**Comment by spdkci** [comment] 2020-10-23 05:46
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_29410.html

**Comment by spdkci** [comment] 2020-10-23 10:44
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_29426.html

**Comment by spdkci** [comment] 2020-10-23 11:45
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_29382.html

**Comment by spdkci** [comment] 2020-10-23 13:13
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_29446.html

**Comment by spdkci** [comment] 2020-10-23 16:09
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_29492.html

**Comment by spdkci** [comment] 2020-10-26 06:30
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_29536.html

**Comment by spdkci** [comment] 2020-10-30 09:14
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_29873.html

**Comment by spdkci** [comment] 2020-10-30 12:55
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_29901.html

**Comment by tomzawadzki** [comment] 2020-12-01 14:41
This issue was not observed for over a month, closing.

**Comment by spdkci** [comment] 2020-12-17 07:37
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_32373.html

**Comment by spdkci** [comment] 2021-03-04 09:55
Another instance of this failure. Reported by @KKaras169169. log: Not Found

**Comment by spdkci** [comment] 2021-03-09 10:52
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_38153.html

**Comment by tomzawadzki** [comment] 2021-03-09 11:23
@mikeBashStuff the last report looks like something different:
```
00:01:46.412  + vagrant ssh -c 'git -C /home/vagrant/spdk_repo/spdk reset --hard'
00:01:49.523  fatal: Unable to create '/usr/home/vagrant/spdk_repo/spdk/.git/index.lock': Read-only file system
```
Could you create a fresh issue for it ?

**Comment by tomzawadzki** [comment] 2021-03-09 11:25
This issue is duplicate of #1792. Closing this one, since #1792 is more recent with better title and has fresh reports.

**Closed by tomzawadzki** 2021-03-09 11:25 UTC
Labels: Infrastructure, Intermittent Failure
