### ISSUE TITLE
FIO (with bdev plugin) to test against NVMe-TCP target.

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#995] opened 2019-10-23 17:20 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

Fio can successfully finish without error

## Current Behavior

Sometimes, fio did not finish or finish with printed error.  The code is still correct in the following branch:  447373239849b65b8f9f242256c9be833e78f88e.

## Steps to Reproduce

1. In the target side,  just run ./app/nvmf/nvmf_tgt -c tcp.conf
2. In the initiator side, you need to compile with fio-plugin enabled.  Then doing the fio test with following command:  LD_PRELOAD=/home/ziyeyang/spdk/examples/bdev/fio_plugin/fio_plugin /home/ziyeyang/fio/fio fio.conf

**Comment by optimistyzy** [comment] 2019-10-23 17:22
Target side, configuration file: 
# NVMf Target Configuration File
#
# Please write all parameters using ASCII.
# The parameter must be quoted if it includes whitespace.
#
# Configuration syntax:
# Leading whitespace is ignored.
# Lines starting with '#' are comments.
# Lines ending with '\' are concatenated with the next line.
# Bracketed ([]) names define sections

[Global]
  # Tracepoint group mask for spdk trace buffers
  # Default: 0x0 (all tracepoint groups disabled)
  # Set to 0xFFFF to enable all tracepoint groups.
  #TpointGroupMask 0x0

[Bdev]

[Null]
  Dev Null0 64 4096
  Dev Null1 64 4096
  Dev Null2 64 4096
  Dev Null3 64 4096
  Dev Null4 64 4096
  Dev Null5 64 4096
  Dev Null6 64 4096
  Dev Null7 64 4096
  Dev Null8 64 4096
  Dev Null9 64 4096
  Dev Null10 64 4096
  Dev Null11 64 4096
  Dev Null12 64 4096
  Dev Null13 64 4096
  Dev Null14 64 4096
  Dev Null15 64 4096
  Dev Null16 64 4096
  Dev Null17 64 4096
  Dev Null18 64 4096
  Dev Null19 64 4096
  Dev Null20 64 4096
  Dev Null21 64 4096
  Dev Null22 64 4096
  Dev Null23 64 4096
  Dev Null24 64 4096
  Dev Null25 64 4096
  Dev Null26 64 4096
  Dev Null27 64 4096
  Dev Null28 64 4096
  Dev Null29 64 4096
  Dev Null30 64 4096
  Dev Null31 64 4096

[Nvmf]
  # Set how often the acceptor polls for incoming connections. The acceptor is also
  # responsible for polling existing connections that have gone idle. 0 means continuously
  # poll. Units in microseconds.
  AcceptorPollRate 10000

# One valid transport type must be set in each [Transport].
# The first is the case of RDMA transport and the second is the case of TCP transport.
[Transport]
  # Set RDMA transport type.
  #Type TCP
  Type TCP

  # Set the maximum number of outstanding I/O per queue.
  #MaxQueueDepth 128

  # Set the maximum number of submission and completion queues per session.
  # Setting this to '8', for example, allows for 8 submission and 8 completion queues
  # per session.
  #MaxQueuesPerSession 4

  # Set the maximum in-capsule data size. Must be a multiple of 16.
  # 0 is a valid choice.
  #InCapsuleDataSize 4096

  # Set the maximum I/O size. Must be a multiple of 4096.
  #MaxIOSize 131072

  # Set the I/O unit size, and this value should not be larger than MaxIOSize
  #IOUnitSize 131072

  # Set the maximum number of IO for admin queue
  #MaxAQDepth 32

  # Set the number of pooled data buffers available to the transport
  # It is used to provide the read/write data buffers for the qpairs on this transport.
  NumSharedBuffers 4096
  # Set the number of shared buffers to be cached per poll group
  #BufCacheSize 32

[Subsystem1]
  NQN nqn.2016-06.io.spdk:cnode1
  #Listen TCP 192.168.2.11:4420
  #Listen TCP 192.168.4.11:4420
  Listen TCP 10.67.111.179:4420
  #Listen RDMA 192.168.2.11:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000001
  MaxNamespaces 40
  #Namespace Nvme0n1 1
  Namespace Null0
  Namespace Null1
  Namespace Null2
  Namespace Null3
  Namespace Null4
  Namespace Null5
  Namespace Null6
  Namespace Null7
  Namespace Null8
  Namespace Null9
  Namespace Null10
  Namespace Null11
  Namespace Null12
  Namespace Null13
  Namespace Null14
  Namespace Null15
  Namespace Null16
  Namespace Null17
  Namespace Null18
  Namespace Null19
  Namespace Null20
  Namespace Null21
  Namespace Null22
  Namespace Null23
  Namespace Null24
  Namespace Null25
  Namespace Null26
  Namespace Null27
  Namespace Null28
  Namespace Null29
  Namespace Null30
Namespace Null31

**Comment by optimistyzy** [comment] 2019-10-23 17:26
fio.conf in initiator side: 

[global]
ioengine=/home/ziyeyang/spdk/examples/bdev/fio_plugin/fio_plugin
spdk_conf=/home/ziyeyang/spdk/spdk_bdev.conf
thread=1
group_reporting=1
direct=1
norandommap=1
rw=randrw
#rwmixread={100, 70, 0}
rwmixread=50
bs=4k
iodepth=128
time_based=1
ramp_time=30
runtime=60
[test]
numjobs=32
filename=Nvme0n1
filename=Nvme0n2
filename=Nvme0n3
filename=Nvme0n4
filename=Nvme0n5
filename=Nvme0n6
filename=Nvme0n7
filename=Nvme0n8
filename=Nvme0n9
filename=Nvme0n10
filename=Nvme0n11
filename=Nvme0n12
filename=Nvme0n13
filename=Nvme0n14
filename=Nvme0n15
filename=Nvme0n16
filename=Nvme0n17
filename=Nvme0n18
filename=Nvme0n19
filename=Nvme0n20
filename=Nvme0n21
filename=Nvme0n22
filename=Nvme0n23
filename=Nvme0n24
filename=Nvme0n25
filename=Nvme0n26
filename=Nvme0n27
filename=Nvme0n28
filename=Nvme0n29
filename=Nvme0n30
filename=Nvme0n31

spdk_bdev.conf file:
[NVMe]
        TransportId "trtype:TCP adrfam:IPv4 traddr:10.67.111.179 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode1" Nvme0

**Comment by optimistyzy** [comment] 2019-10-23 17:34
@Seth5141 Assigned to this seth. According to my analysis, it is related with the recent factoring work in NVMe host side for re-connecting related task force.  Since I did some test in https://github.com/spdk/spdk/commit/447373239849b65b8f9f242256c9be833e78f88e this branch, it works in expected manner.

**Comment by Seth5141** [comment] 2019-10-24 01:41
@optimistyzy I have had a very different experience than you running this benchmark. I was getting very consistent failures on master with the following backtrace:

~~~
nvme_qpair.c: 453:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
nvme_fabric.c: 328:nvme_fabric_qpair_connect: *ERROR*: Connect command failed
bdev_nvme.c:1831:bdev_nvme_readv: *ERROR*: readv failed: rc = -6
bdev_nvme.c:1831:bdev_nvme_readv: *ERROR*: readv failed: rc = -6
bdev_nvme.c:1831:bdev_nvme_readv: *ERROR*: readv failed: rc = -6
bdev_nvme.c:1831:bdev_nvme_readv: *ERROR*: readv failed: rc = -6
bdev_nvme.c:1858:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
bdev_nvme.c:1831:bdev_nvme_readv: *ERROR*: readv failed: rc = -6
bdev_nvme.c:1858:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
bdev_nvme.c:1831:bdev_nvme_readv: *ERROR*: readv failed: rc = -6
bdev_nvme.c:1831:bdev_nvme_readv: *ERROR*: readv failed: rc = -6
bdev_nvme.c:1831:bdev_nvme_readv: *ERROR*: readv failed: rc = -6
bdev_nvme.c:1858:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
bdev_nvme.c:1858:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
nvme_tcp.c:1693:nvme_tcp_qpair_connect: *ERROR*: Failed to send an NVMe-oF Fabric CONNECT command
...
Run status group 0 (all jobs):
   READ: bw=188MiB/s (198MB/s), 188MiB/s-188MiB/s (198MB/s-198MB/s), io=1869MiB (1960MB), run=9917-9917msec
  WRITE: bw=188MiB/s (198MB/s), 188MiB/s-188MiB/s (198MB/s-198MB/s), io=1869MiB (1960MB), run=9917-9917msec
nvme_ctrlr.c: 574:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
~~~

with the following on the target side:

~~~
ctrlr.c: 143:spdk_nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host from subsystem nqn.2016-06.io.spdk:cnode1 due to keep alive timeout.
~~~

However, this error did not go away when running against 4473732. In fact, I did a bisect between master and 19.07 and came up with the following commit as the first one that broke this benchmark. 8a80461ac62c7c53c90caab04c48db9078d450cd. Now, I can consistently get this benchmark to fail on 8a80461ac62c7c53c90caab04c48db9078d450cd and fail on the patch right before it.

I am not sure why we got such diverging results. I have been running this benchmark in loopback, I assumed from your comments on slack that that is what you were doing as well. I copied your configuration files exactly. Can you think of any reasons that we would get such different results?

Thanks,

Seth

**Comment by shuhei-matsumoto** [comment] 2019-10-24 01:48
Hi Seth,

About the issue you are observing, Ziye is creating a patch for the another issue reported by Jim.
https://review.gerrithub.io/c/spdk/spdk/+/472047

**Comment by optimistyzy** [comment] 2019-10-24 04:17
@Seth5141 The difference is that: on the target side, I use the lastest master branch, and on the target side, I use different NVMe host version.

**Comment by wanqunintel** [comment] 2019-10-24 04:52
Commit(both target and initiator): ae3a9b8f08de94e95f6ee700d4901903bc898bd9
Target Kernel: 5.4.0-rc3
Initiator Kernel: 5.1.0

Target error:
![image](https://user-images.githubusercontent.com/18566118/67454540-18cd2600-f65d-11e9-91b2-7986513d8f7d.png)

Initiator error:
![image](https://user-images.githubusercontent.com/18566118/67454544-1ec30700-f65d-11e9-8f98-4a4df6b93763.png)

**Comment by wanqunintel** [comment] 2019-10-24 04:53
[Global]
[Bdev]

[Malloc]
  NumberOfLuns 32
  LunSizeInMB 64

[Nvmf]
  # Set how often the acceptor polls for incoming connections. The acceptor is also
  # responsible for polling existing connections that have gone idle. 0 means continuously
  # poll. Units in microseconds.
  AcceptorPollRate 10000

#ConnectionScheduler Transport

# One valid transport type must be set in each [Transport].
# The first is the case of RDMA transport and the second is the case of TCP transport.
[Transport]
  # Set RDMA transport type.
  #Type TCP
  Type TCP

  NumSharedBuffers 2048

[Subsystem1]
  NQN nqn.2016-06.io.spdk:cnode1
  #Listen TCP 192.168.2.11:4420
  #Listen TCP 192.168.4.11:4420
  Listen TCP 192.168.3.11:4420
  #Listen RDMA 192.168.2.11:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000001
  MaxNamespaces 64
  #Namespace Nvme0n1 1
  Namespace Malloc0
  Namespace Malloc1
  Namespace Malloc2
  Namespace Malloc3
  Namespace Malloc4
  Namespace Malloc5
  Namespace Malloc6
  Namespace Malloc7
  Namespace Malloc8
  Namespace Malloc9
  Namespace Malloc10
  Namespace Malloc11
  Namespace Malloc12
  Namespace Malloc13
  Namespace Malloc14
  Namespace Malloc15
  Namespace Malloc16
  Namespace Malloc17
  Namespace Malloc18
  Namespace Malloc19
  Namespace Malloc20
  Namespace Malloc21
  Namespace Malloc22
  Namespace Malloc23
  Namespace Malloc24
  Namespace Malloc25
  Namespace Malloc26
  Namespace Malloc27
  Namespace Malloc28
  Namespace Malloc29
  Namespace Malloc30
  Namespace Malloc31

**Comment by Seth5141** [comment] 2019-10-24 04:57
@wanqunintel Could you please retry the test with:
git fetch "https://review.gerrithub.io/spdk/spdk" refs/changes/47/472047/6 && git checkout FETCH_HEAD 

Based on the observations I made doing my bisect today, I think it is at least worth a try. When I run this test locally without the above change, it fails every time. When I test it with that change, it has passed every time I run the test, about 6 times. I understand that running with two systems is different, but seeing the output from testing with this fix will at least give me a place to continue looking when I get into the office tomorrow.

Thank you,

Seth

**Comment by wanqunintel** [comment] 2019-10-24 05:40
@Seth5141 , i tried with this patch and tested with 1 minute, it passed.

**Comment by Seth5141** [comment] 2019-10-24 05:47
@wanqunintel Thank you for testing it.

**Comment by Seth5141** [comment] 2019-10-24 23:06
@wanqunintel @optimistyzy How frequesntly can you get this to reproduce on a two system setup? I have been trying to reproduce this consistently on different patches, but I can't get it to hit every time on any patch. So far, I got one failure on 447373239, several on master before 2ec99adad90f was merged, and I still haven't gotten it to fail on 2ec99adad90f.
Because of the consistence with which I can get it to fail in loopback, I am leaning towards this being a variation on Jim's Seastar issue. When it fails in loopback for me, I consistently get a keep alive timeout. On the two system setup, I don't get that same error. The one part I still don't understand is the mechanis. Since we are only doing 4k writes, I wouldn't expect us to get hung up the way we do in Jims Seastar example, but the evidence points towards it so far.
I definitely need to do some more digging on this one, but I thought I'd share my thoughts so far.

**Comment by optimistyzy** [comment] 2019-10-29 07:57
@wanqunintel Can this issue reproduced with the master branch?

**Comment by jimharris** [comment] 2019-10-31 04:40
Bug scrub: @wanqunintel unable to reproduce with latest master branch..  @Seth5141 reports he can see the test run to completion, but one job is hanging at the end.  No core dump is seen so we think @Seth's observation is a different issue, and that this issue should be closed based on known fixes that have gone in around this condition.  @Seth5141 to close this issue and file a new one for the newly observed behavior.

**Closed** 2019-10-31 17:47 UTC
