### ISSUE TITLE
[nvmf/target/ns_masking] No controller was found after nvme connect

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#3337] opened 2024-04-11 01:02 UTC
[Error case]
00:14:57.793   17:38:48	-- target/ns_masking.sh@53 -- # connect
00:14:57.793   17:38:48	-- target/ns_masking.sh@18 -- # nvme connect -t tcp -n nqn.2016-06.io.spdk:cnode1 -q nqn.2016-06.io.spdk:host1 -I 33ed5e6e-10fa-451e-b53d-9a410090eff7 -a 10.0.0.2 -s 4420 -i 4
00:14:58.064   17:38:48	-- target/ns_masking.sh@20 -- # waitforserial SPDKISFASTANDAWESOME
00:14:58.064   17:38:48	-- common/autotest_common.sh@1184 -- # local i=0
00:14:58.064   17:38:48	-- common/autotest_common.sh@1185 -- # local nvme_device_counter=1 nvme_devices=0
00:14:58.064   17:38:48	-- common/autotest_common.sh@1186 -- # [[ -n '' ]]
00:14:58.064   17:38:48	-- common/autotest_common.sh@1191 -- # sleep 2
00:15:00.054   17:38:50	-- common/autotest_common.sh@1192 -- # (( i++ <= 15 ))
00:15:00.054    17:38:50	-- common/autotest_common.sh@1193 -- # lsblk -l -o NAME,SERIAL
00:15:00.054    17:38:50	-- common/autotest_common.sh@1193 -- # grep -c SPDKISFASTANDAWESOME
00:15:00.054   17:38:50	-- common/autotest_common.sh@1193 -- # nvme_devices=1
00:15:00.054   17:38:50	-- common/autotest_common.sh@1194 -- # (( nvme_devices == nvme_device_counter ))
00:15:00.054   17:38:50	-- common/autotest_common.sh@1194 -- # return 0
00:15:00.054    17:38:50	-- target/ns_masking.sh@22 -- # nvme list-subsys -o json
00:15:00.054    17:38:50	-- target/ns_masking.sh@22 -- # jq -r '.[0].Subsystems[] | select(.NQN=="nqn.2016-06.io.spdk:cnode1") | .Paths[0].Name'
00:15:00.054   17:38:50	-- target/ns_masking.sh@22 -- # ctrl_id=
00:15:00.054   17:38:50	-- target/ns_masking.sh@54 -- # ns_is_visible 0x1
00:15:00.054   17:38:50	-- target/ns_masking.sh@31 -- # nvme list-ns /dev/
00:15:00.054   17:38:50	-- target/ns_masking.sh@31 -- # grep 0x1
00:15:00.054  /dev is not a block or character device
00:15:00.054  [1mUsage: nvme list-ns <device> [OPTIONS][0m

[Normal case]
00:13:03.705   13:14:32	-- target/ns_masking.sh@53 -- # connect
00:13:03.705   13:14:32	-- target/ns_masking.sh@18 -- # nvme connect -t tcp -n nqn.2016-06.io.spdk:cnode1 -q nqn.2016-06.io.spdk:host1 -I 9631e564-4504-43b7-8ab0-aaced0d6c3b2 -a 10.0.0.2 -s 4420 -i 4
00:13:03.965   13:14:32	-- target/ns_masking.sh@20 -- # waitforserial SPDKISFASTANDAWESOME
00:13:03.965   13:14:32	-- common/autotest_common.sh@1172 -- # local i=0
00:13:03.965   13:14:32	-- common/autotest_common.sh@1173 -- # local nvme_device_counter=1 nvme_devices=0
00:13:03.965   13:14:32	-- common/autotest_common.sh@1174 -- # [[ -n '' ]]
00:13:03.965   13:14:32	-- common/autotest_common.sh@1179 -- # sleep 2
00:13:05.876   13:14:34	-- common/autotest_common.sh@1180 -- # (( i++ <= 15 ))
00:13:05.876    13:14:34	-- common/autotest_common.sh@1181 -- # lsblk -l -o NAME,SERIAL
00:13:05.876    13:14:34	-- common/autotest_common.sh@1181 -- # grep -c SPDKISFASTANDAWESOME
00:13:05.876   13:14:35	-- common/autotest_common.sh@1181 -- # nvme_devices=1
00:13:05.876   13:14:35	-- common/autotest_common.sh@1182 -- # (( nvme_devices == nvme_device_counter ))
00:13:05.876   13:14:35	-- common/autotest_common.sh@1182 -- # return 0
00:13:05.876    13:14:35	-- target/ns_masking.sh@22 -- # nvme list-subsys -o json
00:13:05.876    13:14:35	-- target/ns_masking.sh@22 -- # jq -r '.[0].Subsystems[] | select(.NQN=="nqn.2016-06.io.spdk:cnode1") | .Paths[0].Name'
00:13:05.876   13:14:35	-- target/ns_masking.sh@22 -- # ctrl_id=nvme0
00:13:05.876   13:14:35	-- target/ns_masking.sh@54 -- # ns_is_visible 0x1
00:13:05.876   13:14:35	-- target/ns_masking.sh@31 -- # grep 0x1
00:13:05.876   13:14:35	-- target/ns_masking.sh@31 -- # nvme list-ns /dev/nvme0
00:13:06.169  [   0]:0x1

**Comment by spdkci** [comment] 2024-04-11 01:04
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_119942.html

**Comment by spdkci** [comment] 2024-04-11 01:05
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_119962.html

**Comment by spdkci** [comment] 2024-04-11 01:59
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_119992.html

**Comment by spdkci** [comment] 2024-04-11 02:00
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_119994.html

**Comment by spdkci** [comment] 2024-04-11 02:01
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_120000.html

**Comment by jimharris** [comment] 2024-04-11 02:04
All of these failures are on WFP4. Looking at recent CI queue, only passing ones are running nvmf-tcp-phy on some other node.

Did something change recently with WFP4? Maybe we can take that system out of circulation for nvmf-tcp-phy for now.

I'll push a patch tomorrow that tries to get some more info on this - it's not clear whether nvme-cli doesn't see the subsystem at all, or if the JSON output differs in a way that the filter isn't matching.

**Comment by mikeBashStuff** [comment] 2024-04-11 07:31
> All of these failures are on WFP4. Looking at recent CI queue, only passing ones are running nvmf-tcp-phy on some other node.
> 
> Did something change recently with WFP4? Maybe we can take that system out of circulation for nvmf-tcp-phy for now.
> 
> I'll push a patch tomorrow that tries to get some more info on this - it's not clear whether nvme-cli doesn't see the subsystem at all, or if the JSON output differs in a way that the filter isn't matching.

if the filter didn't match the `jq` would most likely fail (complaining about iterating over nulls or similar), yet here we get an empty string so I would say the target subsystem simply is not on the list.

**Comment by mikeBashStuff** [comment] 2024-04-11 08:12
This issue also doesn't seem to be bound to a specific node since this failure occurred under WFP3 as well.

**Comment by spdkci** [comment] 2024-04-11 08:43
Another instance of this failure. Reported by @m-spiewak. log: https://ci.spdk.io/public_build/autotest-per-patch_119965.html

**Comment by spdkci** [comment] 2024-04-11 08:43
Another instance of this failure. Reported by @m-spiewak. log: https://ci.spdk.io/public_build/autotest-per-patch_119949.html

**Comment by spdkci** [comment] 2024-04-11 08:43
Another instance of this failure. Reported by @sberbz. log: https://ci.spdk.io/public_build/autotest-per-patch_119967.html

**Comment by spdkci** [comment] 2024-04-11 09:12
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_119981.html

**Comment by spdkci** [comment] 2024-04-11 09:12
Another instance of this failure. Reported by @ksztyber. log: Not Found

**Comment by spdkci** [comment] 2024-04-11 09:12
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_119970.html

**Comment by spdkci** [comment] 2024-04-11 11:12
Another instance of this failure. Reported by @sberbz. log: https://ci.spdk.io/public_build/autotest-per-patch_120035.html

**Comment by spdkci** [comment] 2024-04-11 11:35
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_120038.html

**Comment by spdkci** [comment] 2024-04-11 12:04
Another instance of this failure. Reported by @ankit-sam. log: https://ci.spdk.io/public_build/autotest-per-patch_119943.html

**Comment by spdkci** [comment] 2024-04-11 12:28
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_120043.html

**Comment by mikeBashStuff** [comment] 2024-04-11 13:22
I just wonder if this test shouldn't focus more on detecting namespaces based on their unique uuuids rather than nsids:

```
diff --git a/test/nvmf/target/ns_masking.sh b/test/nvmf/target/ns_masking.sh
index 9d69e4a2a..a7285b93c 100755
--- a/test/nvmf/target/ns_masking.sh
+++ b/test/nvmf/target/ns_masking.sh
@@ -14,6 +14,9 @@ SUBSYSNQN="nqn.2016-06.io.spdk:cnode1"
 HOSTNQN="nqn.2016-06.io.spdk:host1"
 HOSTID=$(uuidgen)

+ns_uuids[1]=$(uuidgen)
+ns_uuids[2]=$(uuidgen)
+
 function connect() {
        nvme connect -t $TEST_TRANSPORT -n $SUBSYSNQN -q $HOSTNQN -I $HOSTID \
                -a "$NVMF_FIRST_TARGET_IP" -s "$NVMF_PORT" -i 4
@@ -26,11 +29,12 @@ function disconnect() {
        nvme disconnect -n $SUBSYSNQN
 }

-# $1 == hex nsid
 function ns_is_visible() {
-       nvme list-ns /dev/$ctrl_id | grep "$1"
-       nguid=$(nvme id-ns /dev/$ctrl_id -n $1 -o json | jq -r ".nguid")
-       [[ $nguid != "00000000000000000000000000000000" ]]
+       waitforcondition "_ns_is_visible $*" 5
+}
+
+function _ns_is_visible() {
+       grep -sq "$1" /sys/block/nvme*c*/nguid
 }

 nvmftestinit
@@ -46,57 +50,57 @@ $rpc_py bdev_malloc_create $MALLOC_BDEV_SIZE $MALLOC_BLOCK_SIZE -b Malloc2

 # No masking (all namespaces automatically visible)
 $rpc_py nvmf_create_subsystem $SUBSYSNQN -a -s $NVMF_SERIAL
-$rpc_py nvmf_subsystem_add_ns $SUBSYSNQN Malloc1 -n 1
+$rpc_py nvmf_subsystem_add_ns $SUBSYSNQN Malloc1 -n 1 -g "${ns_uuids[1]//-/}"
 $rpc_py nvmf_subsystem_add_listener $SUBSYSNQN -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_PORT

 # Namespace should be visible
 connect
-ns_is_visible "0x1"
+ns_is_visible "${ns_uuids[1]}"

 # Add 2nd namespace and check visible
-$rpc_py nvmf_subsystem_add_ns $SUBSYSNQN Malloc2 -n 2
-ns_is_visible "0x1"
-ns_is_visible "0x2"
+$rpc_py nvmf_subsystem_add_ns $SUBSYSNQN Malloc2 -n 2 -g "${ns_uuids[2]//-/}"
+ns_is_visible "${ns_uuids[1]}"
+ns_is_visible "${ns_uuids[2]}"

 disconnect

 # Remove ns1 and re-add without auto visibility
 # Note: we will leave ns2 with auto-attach for rest of this test
 $rpc_py nvmf_subsystem_remove_ns $SUBSYSNQN 1
-$rpc_py nvmf_subsystem_add_ns $SUBSYSNQN Malloc1 -n 1 --no-auto-visible
+$rpc_py nvmf_subsystem_add_ns $SUBSYSNQN Malloc1 -n 1 -g "${ns_uuids[1]//-/}" --no-auto-visible

 # ns1 should be invisible
 connect 1
-NOT ns_is_visible "0x1"
-ns_is_visible "0x2"
+NOT ns_is_visible "${ns_uuids[1]}"
+ns_is_visible "${ns_uuids[2]}"

 # hot attach and check ns1 visible
 $rpc_py nvmf_ns_add_host $SUBSYSNQN 1 $HOSTNQN
-ns_is_visible "0x1"
-ns_is_visible "0x2"
+ns_is_visible "${ns_uuids[1]}"
+ns_is_visible "${ns_uuids[2]}"

 # hot detach and check ns1 invisible
 $rpc_py nvmf_ns_remove_host $SUBSYSNQN 1 $HOSTNQN
-NOT ns_is_visible "0x1"
-ns_is_visible "0x2"
+NOT ns_is_visible "${ns_uuids[1]}"
+ns_is_visible "${ns_uuids[2]}"

 disconnect

 # cold attach, connect and check ns1 visible
 $rpc_py nvmf_ns_add_host $SUBSYSNQN 1 $HOSTNQN
 connect 2
-ns_is_visible "0x1"
-ns_is_visible "0x2"
+ns_is_visible "${ns_uuids[1]}"
+ns_is_visible "${ns_uuids[2]}"

 # detach and check ns1 invisible
 $rpc_py nvmf_ns_remove_host $SUBSYSNQN 1 $HOSTNQN
-NOT ns_is_visible "0x1"
-ns_is_visible "0x2"
+NOT ns_is_visible "${ns_uuids[1]}"
+ns_is_visible "${ns_uuids[2]}"

 # hot detach ns2 should not work, since ns2 is auto-visible
 NOT $rpc_py nvmf_ns_remove_host $SUBSYSNQN 2 $HOSTNQN
-NOT ns_is_visible "0x1"
-ns_is_visible "0x2"
+NOT ns_is_visible "${ns_uuids[1]}"
+ns_is_visible "${ns_uuids[2]}"
 disconnect
```
Also, we probably should hook `connect()` into `waitforcondition()` to make sure `ctrl_id` is indeed set when the function returns.

**Comment by mikeBashStuff** [comment] 2024-04-11 13:25
And to note, I have been spinning this test on the affected WFP4 and under a VM and so far I haven't been able to reliably reproduce this issue.

**Comment by jimharris** [comment] 2024-04-11 15:25
> > This issue also doesn't seem to be bound to a specific node
> 
> That said, I just managed to trigger couple of MCEs under WFP4 by doing some light stress testing so in general this node doesn't seem to be stable (though these MCEs were not something that tripped the test here).

I'm still at a loss how this test was merged March 26, but these failures didn't start happening until yesterday.

We only run this test when SPDK_TEST_URING=0, is it possible config changed at all recently? I know we've been looking at changes around URING config (bdev_uring v. sock_uring), I thought maybe some tweaks or something were made.

Only recent patches that were of interest were:

cf9e9b2 ("test/nvmf: add waitforcondition function"): this doesn't touch the masking test at all though
4e34724 ("nvmf: add nvmf_ns_add_host() helper"): I though maybe we completely missed something on this seemingly simple patch, but I've reviewed it again and it looks fine

Maybe we need to just disable that test for now while we debug this further?

**Comment by jimharris** [comment] 2024-04-11 15:57
> > All of these failures are on WFP4. Looking at recent CI queue, only passing ones are running nvmf-tcp-phy on some other node.
> > Did something change recently with WFP4? Maybe we can take that system out of circulation for nvmf-tcp-phy for now.
> > I'll push a patch tomorrow that tries to get some more info on this - it's not clear whether nvme-cli doesn't see the subsystem at all, or if the JSON output differs in a way that the filter isn't matching.
> 
> if the filter didn't match the `jq` would most likely fail (complaining about iterating over nulls or similar), yet here we get an empty string so I would say the target subsystem simply is not on the list.

I agree it is more likely that the target subsystem isn't on the list. But if I change the test locally and filter on `.NN` instead of `.NQN` I get the exact same result as shown in the failing log messages. So we can't rule out a difference in JSON format.

I've pushed out https://review.spdk.io/gerrit/c/spdk/spdk/+/22743 so we can get the full JSON when the filter fails.

**Comment by jimharris** [comment] 2024-04-11 18:55
> > > All of these failures are on WFP4. Looking at recent CI queue, only passing ones are running nvmf-tcp-phy on some other node.
> > > Did something change recently with WFP4? Maybe we can take that system out of circulation for nvmf-tcp-phy for now.
> > > I'll push a patch tomorrow that tries to get some more info on this - it's not clear whether nvme-cli doesn't see the subsystem at all, or if the JSON output differs in a way that the filter isn't matching.
> > 
> > 
> > if the filter didn't match the `jq` would most likely fail (complaining about iterating over nulls or similar), yet here we get an empty string so I would say the target subsystem simply is not on the list.
> 
> I agree it is more likely that the target subsystem isn't on the list. But if I change the test locally and filter on `.NN` instead of `.NQN` I get the exact same result as shown in the failing log messages. So we can't rule out a difference in JSON format.
> 
> I've pushed out https://review.spdk.io/gerrit/c/spdk/spdk/+/22743 so we can get the full JSON when the filter fails.

And by a stroke of luck, my patch failed due to this exact issue.
https://ci.spdk.io/results/autotest-per-patch/builds/120105/archive/nvmf-tcp-phy-autotest_68801/build.log

In summary, we were filtering on only the first element in the list-subsys array, but that entry was for the system's hostnqn, not the hostnqn we used to connect in the test.  So we just needed to relax that filter to look at all entries in the array.

Fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/22747

I also modified the 22743 patch+commit message, I think it would still be useful to merge this in case some problem around this pops up again in the future.

**Comment by spdkci** [comment] 2024-04-12 06:02
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_120097.html

**Comment by spdkci** [comment] 2024-04-12 06:03
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_120094.html

**Comment by spdkci** [comment] 2024-04-12 06:03
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_120081.html

**Comment by spdkci** [comment] 2024-04-12 06:04
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_120073.html

**Comment by spdkci** [comment] 2024-04-12 07:34
Another instance of this failure. Reported by @m-spiewak. log: https://ci.spdk.io/public_build/autotest-per-patch_120045.html

**Comment by spdkci** [comment] 2024-04-12 09:08
Another instance of this failure. Reported by @mchomnic. log: https://ci.spdk.io/public_build/autotest-per-patch_120137.html

**Comment by mikeBashStuff** [comment] 2024-04-16 13:54
I believe this one could be closed now.

**Closed** 2024-04-16 13:55 UTC
Labels: bug, Medium, Intermittent Failure, Patches out for review
