### ISSUE TITLE
The 4K random write fio failed when use 32MB/64MB/128MB cluster size with thin provision

### ISSUE THREAD

**Issue by ChenWang01** [spdk/spdk#382] opened 2018-07-31 09:14 UTC
The 4K random write fio failed when use 32MB/64MB/128MB cluster size with thin provision.
The 4MB and 16MB cluster size can run 4K random write cases, but the IOPS is lower when the qd=1

## Expected Behavior
The  4K random write fio case should pass

## Current Behavior
Fio log
```
job1: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
fio-2.99-12-ge1933
Starting 1 process
fio: io_u error on file /dev/sda: Input/output error: write offset=106771066880, buflen=4096
fio: pid=2729, err=5/file:io_u.c:1756, func=io_u error, error=Input/output error

job1: (groupid=0, jobs=1): err= 5 (file:io_u.c:1756, func=io_u error, error=Input/output error): pid=2729: Tue Jul 31 14:42:57 2018
  write: IOPS=785, BW=3142KiB/s (3217kB/s)(41.6MiB/13548msec)
    slat (nsec): min=4750, max=59294, avg=16153.61, stdev=7807.52
    clat (usec): min=17, max=16874, avg=1247.36, stdev=1415.48
     lat (usec): min=26, max=16889, avg=1264.17, stdev=1415.47
    clat percentiles (usec):
     |  1.00th=[   24],  5.00th=[   25], 10.00th=[   33], 20.00th=[   51],
     | 30.00th=[   90], 40.00th=[  119], 50.00th=[  693], 60.00th=[ 1385],
     | 70.00th=[ 1991], 80.00th=[ 2540], 90.00th=[ 2933], 95.00th=[ 3720],
     | 99.00th=[ 5735], 99.50th=[ 6587], 99.90th=[ 8160], 99.95th=[ 9503],
     | 99.99th=[10814]
   bw (  KiB/s): min= 1688, max= 7384, per=100.00%, avg=3148.44, stdev=1121.55, samples=27
   iops        : min=  422, max= 1846, avg=787.11, stdev=280.39, samples=27
    lat (usec) : 20=0.01%, 50=19.53%, 100=15.96%, 250=7.73%, 500=4.85%
    lat (usec) : 750=3.06%, 1000=2.90%
    lat (msec) : 2=16.01%, 4=25.74%, 10=4.13%, 20=0.05%
  cpu          : usr=1.23%, sys=2.13%, ctx=10643, majf=0, minf=71
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.1%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=0,10643,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1
Run status group 0 (all jobs):
  WRITE: bw=3142KiB/s (3217kB/s), 3142KiB/s-3142KiB/s (3217kB/s-3217kB/s), io=41.6MiB (43.6MB), run=13548-13548msec

Disk stats (read/write):
  sda: ios=61/10498, merge=0/0, ticks=2/12967, in_queue=12962, util=96.10%

```
Dmesg log:
```
[  248.573227] sd 2:0:0:0: [sda] CDB: Write(10) 2a 00 0b e6 02 75 00 00 01 00
[  248.573230] blk_update_request: I/O error, dev sda, sector 1596986280
[  248.578990] sd 2:0:0:0: [sda] FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[  248.578995] sd 2:0:0:0: [sda] Sense Key : Aborted Command [current]
[  248.578997] sd 2:0:0:0: [sda] Add. Sense: No additional sense information
[  248.578999] sd 2:0:0:0: [sda] CDB: Write(10) 2a 00 03 a9 10 aa 00 00 01 00
[  248.579001] blk_update_request: I/O error, dev sda, sector 491291984
[  248.606736] sd 2:0:0:0: [sda] FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[  248.606742] sd 2:0:0:0: [sda] Sense Key : Aborted Command [current]
[  248.606744] sd 2:0:0:0: [sda] Add. Sense: No additional sense information
[  248.606748] sd 2:0:0:0: [sda] CDB: Write(10) 2a 00 0e 38 a0 fc 00 00 01 00
[  248.606751] blk_update_request: I/O error, dev sda, sector 1908738016
[  248.612078] sd 2:0:0:0: [sda] FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[  248.612084] sd 2:0:0:0: [sda] Sense Key : Aborted Command [current]
[  248.612087] sd 2:0:0:0: [sda] Add. Sense: No additional sense information
[  248.612090] sd 2:0:0:0: [sda] CDB: Write(10) 2a 00 02 ee bd 6c 00 00 01 00
[  248.612093] blk_update_request: I/O error, dev sda, sector 393603936
[  248.618083] sd 2:0:0:0: [sda] FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[  248.618089] sd 2:0:0:0: [sda] Sense Key : Aborted Command [current]
[  248.618092] sd 2:0:0:0: [sda] Add. Sense: No additional sense information
[  248.618095] sd 2:0:0:0: [sda] CDB: Write(10) 2a 00 07 c8 21 f3 00 00 01 00
[  248.618098] blk_update_request: I/O error, dev sda, sector 1044451224
[  248.676337] sd 2:0:0:0: [sda] FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[  248.676342] sd 2:0:0:0: [sda] Sense Key : Aborted Command [current]
[  248.676344] sd 2:0:0:0: [sda] Add. Sense: No additional sense information
[  248.676346] sd 2:0:0:0: [sda] CDB: Write(10) 2a 00 02 fb 9b 09 00 00 01 00
[  248.676348] blk_update_request: I/O error, dev sda, sector 400349256
[  251.520018] sd 2:0:0:0: [sda] FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[  251.520024] sd 2:0:0:0: [sda] Sense Key : Aborted Command [current]
[  251.520026] sd 2:0:0:0: [sda] Add. Sense: No additional sense information
[  251.520029] sd 2:0:0:0: [sda] CDB: Write(10) 2a 00 02 da 5e 88 00 00 01 00
[  251.520031] blk_update_request: I/O error, dev sda, sector 382923840
[  252.127010] sd 2:0:0:0: [sda] FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[  252.127016] sd 2:0:0:0: [sda] Sense Key : Aborted Command [current]
[  252.127018] sd 2:0:0:0: [sda] Add. Sense: No additional sense information
[  252.127021] sd 2:0:0:0: [sda] CDB: Write(10) 2a 00 0d 13 d3 36 00 00 01 00
[  252.127023] blk_update_request: I/O error, dev sda, sector 1755224496

```

4MB randwrite | qd=1 | 4
-- | -- | --
numjobs=1 | 89 | 801
4 | 115 | 59.6k
8 | 247 | 225k
32 | 497 | 178k
64 | 643 | 194k

## Steps to Reproduce

```
1. ./app/vhost/vhost
2. ./rpc.py construct_nvme_bdev -b "nvme0" -t "PCIe" -a "0000:81:00.0"
3. id=`./rpc.py construct_lvol_store Nvme0n1 lvs_0 -c 134217728`
4. ./rpc.py construct_lvol_bdev -u ${id} lbd_vm_0 1048576 -t     
5. ./rpc.py construct_vhost_scsi_controller naa.0.0 --cpumask 0x1
6. ./rpc.py add_vhost_scsi_lun  naa.0.0 0 lvs_0/lbd_vm_0
7. ./qemu-system-x86_64 --enable-kvm  -cpu host -smp 4 -m 2G  \
-object memory-backend-file,id=mem0,size=2G,mem-path=/dev/hugepages,share=on \
-numa node,memdev=mem0 -drive file=centos.img,if=none,id=disk  \
-device ide-hd,drive=disk,bootindex=0  -net user,hostfwd=tcp::10022-:22  -net nic \
-vnc 0.0.0.0:1 -chardev socket,id=spdk_vhost_scsi0,path=./spdk/naa.0.0   \
-device vhost-user-scsi-pci,chardev=spdk_vhost_scsi0,num_queues=2
8. fio job
    [global]
    ioengine=libaio
    bs=4k
    offset=1GB
    iodepth=32
    direct=1
    time_based
    group_reporting=1
    runtime=300
    rw=randwrite
    numjobs=4
    [job1]
    filename=/dev/sda
```

## Context (Environment including OS version, SPDK version, etc.)

OS: Fedora release 27 (Twenty Seven)
Linux version: 4.17.3-100.fc27.x86_64
gcc version: 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)
SPDK: master (commit id: 9ecc3fef0962755e954d23c08d18ca9ef2f39c68)

**Comment by Maciej-Szwed** [comment] 2018-07-31 14:02
I played a little bit on my setup and I was able to get the same result when my lvol was bigger than lvolstore and we tried to allocate cluster for that additional space (and no free clusters left after previous writes). Could please run get_lvol_stores RPC command after FIO error and paste here full output?

**Comment by ChenWang01** [comment] 2018-08-01 03:11
@Maciej-Szwed  following is the full output.
```
[
  {
    "uuid": "343f21a4-586e-44a4-b2ab-f1f2b1e0e829",
    "base_bdev": "nvme0n1",
    "free_clusters": 0,
    "cluster_size": 134217728,
    "total_data_clusters": 5960,
    "block_size": 4096,
    "name": "lvs_0"
  }
]

```

**Comment by Maciej-Szwed** [comment] 2018-08-01 13:05
@ChenWang01 it looks like this is expected behavior. Here is why:
From output of get_lvol_store I see that your lvol store has size of 745 GB. You are creating lvol with size = 1 TB. In this case we can see that we are hitting end of space on lvol store and we are not able to allocate any new cluster ("free_clusters": 0). Error that you are getting is caused by SPDK sending EIO /* I/O error */. I'm wondering if we could get more graceful notification if we use other errno value. I'll check it.

**Comment by jimharris** [comment] 2018-08-01 17:28
Should this also fail for 4MB and 16MB cluster sizes?

@ChenWang01 - how long are you running the fio test?  I suspect that if you run the test longer for 4MB and 16MB cluster sizes, that it will fail there too.

**Comment by ChenWang01** [comment] 2018-08-02 01:26
@jimharris 
I run the 4MB and 16MB random write cases 5 minutes, it can pass but the IOPS is lower when the qd=1 and qd=4. I will test the 4MB and 16MB with longer time  and have a check.

**Comment by Maciej-Szwed** [comment] 2018-08-02 06:59
@ChenWang01 please try 16MB with higher qd and longer time. This configuration should fail faster than 4MB and lower qd.

**Comment by ChenWang01** [comment] 2018-08-02 07:01
@Maciej-Szwed  Yes you are right, i run the 16MB cases with 30 minutes, it's failed. And run the 4MB cases failed with 60 minutes.

**Comment by Maciej-Szwed** [comment] 2018-08-02 09:31
@ChenWang01 can we close this issue as expected behavior? Or would you like to track here my work on trying to find more appropriate errno which will be handled better by fio/OS (if it is possible at all)?

**Comment by jimharris** [comment] 2018-08-02 14:52
I doubt any errno will be better handled by FIO.  The I/O simply cannot be completed as requested - there's no way for fio to recover from that.

It might be worth checking at an lvol unit test level, that we get an -ENOSPC error when we cannot allocate a cluster.  But even -ENOSPC should result in the I/O error seen with fio.

I'm going to mark this as Low priority for now.  I'm not going to mark it Bug though, since this really looks like a test issue.

**Comment by ChenWang01** [comment] 2018-08-03 05:48
@Maciej-Szwed @jimharris 
Yeh, it seems the test issue. i used `./rpc.py construct_lvol_bdev -u ${id} lbd_vm_0 524288 -t  ` instead of step 4 and the 4K Rand write case can pass.
Can we find a way to remind the users when creating the lvol bdev using bigger size than actual lvol store size.

**Comment by Maciej-Szwed** [comment] 2018-08-03 06:49
@ChenWang01 I can add warning printed by SPDK, but user will have to track what SPDK is printing to see that information. I don't see any good method to return that information to user with creation completion response.

**Comment by jimharris** [comment] 2018-08-03 17:02
@Maciej-Szwed @ChenWang01 

I'm not sure we should do a warning message.  For thin provisioning, it is valid (although dangerous) to create a volume that's bigger than the backing capacity.  And @Maciej-Szwed makes a good point that there is no way to return this warning message over RPC.

**Comment by liang2yan** [comment] 2018-08-07 05:32
@jimharris , can we close this issue? Since this is not a bug.

**Closed** 2018-08-10 17:03 UTC
Labels: Low
