### ISSUE TITLE
nvme_ctrlr time out error when enable SPDK in Ceph

### ISSUE THREAD

**Issue by tone-zhang** [spdk/spdk#482] opened 2018-10-26 07:32 UTC
When enable SPDK in Ceph, observed nvme_ctrlr time out during start the ceph-osd daemon.

The Ceph version is master/LATEST.

## Expected Behavior
In general the Ceph cluster will start up normally.

## Current Behavior
Observed the error below:
starting osd.0 at - osd_data /home/ubuntu/tone/latest_ceph/ceph/build/dev/osd0 /home/ubuntu/tone/latest_ceph/ceph/build/dev/osd0/journal
Starting DPDK 17.11.0 initialization...
[ DPDK EAL parameters: nvme-device-manager -c 0x1 -m 512 --file-prefix=spdk_pid3057 ]
EAL: Detected 20 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: PCI device 0000:08:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL:   using IOMMU type 1 (Type 1)
nvme_ctrlr.c:1549:nvme_ctrlr_process_init: *ERROR*: Initialization timed out in state 4
nvme_ctrlr.c: 477:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:08:00.0 in failed state.
EAL: Releasing pci mapped resource for 0000:08:00.0
EAL: Calling pci_unmap_resource for 0000:08:00.0 at 0x7f260da00000
2018-10-26 13:57:45.012 7f260efb4700 -1 bdev operator() device probe nvme failed
2018-10-26 13:57:45.012 7f2620b0b200 -1 bdev() open failed to get nvme device with sn 55cd2e414d2c9d11

## Possible Solution
After debug, it seems the delay time in SPDK for NVMe device is not enough.

After change the delay in "https://github.com/spdk/spdk/blob/f60effdd75b782542a539eaad00d8f8f1d2df988/lib/nvme/nvme_ctrlr.c#L1619" from "spdk_delay_us(100);" to "spdk_delay_us(100000);".

## Context (Environment including OS version, SPDK version, etc.)
The kernel is 4.16.
The SPDK verison is "dc82989dd2747db0384cafb3b310f2e8792d5c24". 
There is one NVMe device in the test bed, the type is "Intel Corporation SSD 750 Series [Add-in Card]".

**Comment by darsto** [comment] 2018-10-26 07:53
This should be fixed on master. We've increased the sleep time after each PCI reset from 500ms to 2s. See the following patches:

https://github.com/spdk/spdk/commit/951bb3a458748ae419f6507c805f639295b296fa
https://github.com/spdk/spdk/commit/0258728f2baa795e438229565eb7e103ad56dceb

Can you try to reproduce this timeout with the above two?

**Comment by jimharris** [comment] 2018-10-30 14:43
Removing "bug" label for now, until this is reproduced on latest SPDK master.  The referenced commit is approximately 20 patches before v18.01 (late January 2018).

**Comment by tone-zhang** [comment] 2018-10-31 05:40
@darsto Thanks for the comments. I have merged the two patches manually and rerun the test, the "time out" issue disappeared. The bug should be fixed with the above patches. Thanks.

**Comment by tomzawadzki** [comment] 2018-10-31 07:13
@tone-zhang Thanks for verifying.
Closing, since this is fixed on master.

**Closed by tomzawadzki** 2018-10-31 07:13 UTC
