### ISSUE TITLE
Cmb_copy failed with Core dump error

### ISSUE THREAD

**Issue by raghukolagi** [spdk/spdk#2200] opened 2021-10-14 14:29 UTC
# Bug report
Cmb_copy failed with Core dump error

Testing cmb copy with 2 nvme disk and getting Coredump error
**Command**: ./cmb_copy -r 0000:00:0b.0-1-0-1 -w 0000:00:0c.0-1-0-1 -c 0000:00:0b.0
[2021-10-14 10:21:30.091158] Starting SPDK v21.10-pre git sha1 87e9ae403 / DPDK 21.08.0 initialization...
[2021-10-14 10:21:30.091741] [ DPDK EAL parameters: [2021-10-14 10:21:30.091767] cmb_copy [2021-10-14 10:21:30.091781] -c 0x1 [2021-10-14 10:21:30.091795] --log-level=lib.eal:6 [2021-10-14 10:21:30.091808] --log-level=lib.cryptodev:5 [2021-10-14 10:21:30.091827] --log-level=user1:6 [2021-10-14 10:21:30.091842] --iova-mode=pa [2021-10-14 10:21:30.091858] --base-virtaddr=0x200000000000 [2021-10-14 10:21:30.091884] --match-allocations [2021-10-14 10:21:30.091900] --file-prefix=spdk0 [2021-10-14 10:21:30.091915] --proc-type=auto [2021-10-14 10:21:30.091930] ]
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
probe_cb - not probed 0000:0b:00.0!
probe_cb - not probed 0000:0c:00.0!
**cmb_copy: nvme_ctrlr.c:310: spdk_nvme_ctrlr_get_default_io_qpair_opts: Assertion `ctrlr' failed.
Aborted (core dumped)**

## Expected Behavior
read/write should work with CMB_COPY

## Current Behavior
Core dump issue observed

## Steps to Reproduce

1. build the SPDK
2. goto build/examples
3. cmb_copy -r 0000:00:0b.0-1-0-1 -w 0000:00:0c.0-1-0-1 -c 0000:00:0b.0 (Varies on PCIE device)
4.

**Comment by changpe1** [comment] 2021-10-15 00:51
can you have a try using test/nvme/cmb/cmb.sh script, looks like your SSDs are not attached to the application.

**Comment by raghukolagi** [comment] 2021-10-18 05:36
> can you have a try using test/nvme/cmb/cmb.sh script, looks like your SSDs are not attached to the application.

I ran the cmb.sh script and below is the output of the script. I think SSD probing is success but later its not able to find SSD,  please let me know what could be an issue 

[root@fedora cmb]# ./cmb.sh
* Looking for test storage...
* Found test storage at /home/test/spdk/test/nvme/cmb
  00:55:04	-- common/autotest_common.sh@1417 -- # xtrace_enable
 00:55:04	-- ./cmb.sh@6 -- # shopt -s extglob nullglob
 00:55:04	-- ./cmb.sh@67 -- # /home/test/spdk/scripts/setup.sh reset
0000:0c:00.0 (144d a808): Already using the nvme driver
0000:16:00.0 (144d a808): Already using the nvme driver
0000:0b:00.0 (144d a808): Already using the nvme driver
0000:03:00.2 (8086 6f52): Already using the ioatdma driver
0000:03:00.3 (8086 6f53): Already using the ioatdma driver
0000:03:00.0 (8086 6f50): Already using the ioatdma driver
0000:03:00.1 (8086 6f51): Already using the ioatdma driver
 00:55:05	-- ./cmb.sh@69 -- # xtrace_disable
 00:55:05	-- common/autotest_common.sh@14 -- # '[' '' '!=' yes ']'
 00:55:05	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
 00:55:05	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
 00:55:05	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
 00:55:05	-- common/autotest_common.sh@19 -- # set +x
 00:55:05	-- ./cmb.sh@90 -- # xtrace_enable
 00:55:05	-- ./cmb.sh@92 -- # /home/test/spdk/scripts/setup.sh
0000:03:00.2 (8086 6f52): ioatdma -> uio_pci_generic
0000:03:00.3 (8086 6f53): ioatdma -> uio_pci_generic
0000:03:00.0 (8086 6f50): ioatdma -> uio_pci_generic
0000:03:00.1 (8086 6f51): ioatdma -> uio_pci_generic
0000:0c:00.0 (144d a808): nvme -> uio_pci_generic
0000:16:00.0 (144d a808): nvme -> uio_pci_generic
0000:0b:00.0 (144d a808): nvme -> uio_pci_generic
 00:55:05	-- ./cmb.sh@104 -- # (( 0 == 0 ))
 **00:55:05	-- ./cmb.sh@105 -- # printf 'No suitable nvme devices found, aborting CMB tests\n'
No suitable nvme devices found, aborting CMB tests
 00:55:05	-- ./cmb.sh@106 -- # exit 1**

**Comment by changpe1** [comment] 2021-10-18 05:49
we don't have a CMB enabled physical NVMe SSD environment, I don't know where the issue is.  You may debug the issue with cmb_copy example to see where this issue is.

**Comment by jimharris** [comment] 2021-10-18 17:07
Hi @raghukolagi,

Can you confirm that your SSD has a CMB?  You can run build/examples/identify to confirm.

@changpe1 - we also have a bug in this cmb_copy application - it needs to check that the read and write ctrlrs were successfully attached.  Otherwise it tries to alloc io qpairs for a NULL ctrlr (which triggers the assert in the original post).

-Jim

**Comment by changpe1** [comment] 2021-10-19 01:17
> Hi @raghukolagi,
> 
> Can you confirm that your SSD has a CMB? You can run build/examples/identify to confirm.
> 
> @changpe1 - we also have a bug in this cmb_copy application - it needs to check that the read and write ctrlrs were successfully attached. Otherwise it tries to alloc io qpairs for a NULL ctrlr (which triggers the assert in the original post).
> 
> -Jim

that's true, I will add a fix for it.

**Comment by changpe1** [comment] 2021-10-20 01:54
A patch is added via https://review.spdk.io/gerrit/c/spdk/spdk/+/9927

**Comment by changpe1** [comment] 2021-10-20 07:50
Patch has been merged, close this issue.

**Closed by changpe1** 2021-10-20 07:50 UTC
Labels: Sighting, Patches out for review
