### ISSUE TITLE
[vhost_blockdev] Timeouts result in aborted test

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2610] opened 2022-07-27 17:53 UTC
00:06:20.079  VHOST_CONFIG: (/home/vagrant/spdk_repo/spdk/naa.Malloc1.0) memory regions not changed
00:06:20.079  VHOST_CONFIG: (/home/vagrant/spdk_repo/spdk/naa.Malloc1.0) read message VHOST_USER_GET_FEATURES
00:06:20.079  VHOST_CONFIG: (/home/vagrant/spdk_repo/spdk/naa.Malloc1.0) vhost peer closed
00:18:56.167  Cancelling nested steps due to timeout
00:18:56.170  Sending interrupt signal to process
00:18:57.123  script returned exit code 255
00:18:57.129  [Pipeline] }
00:18:57.150  [Pipeline] // timeout
00:18:57.158  [Pipeline] }
00:18:57.181  [Pipeline] // stage
00:18:57.189  [Pipeline] }
00:18:57.192  Timeout has been exceeded
00:18:57.212  [Pipeline] // catchError
00:18:57.221  [Pipeline] stage
00:18:57.224  [Pipeline] { (Stop VM)
00:18:57.239  [Pipeline] sh
00:18:57.522  + vagrant halt
00:19:00.063  ==> default: Halting domain...
00:19:06.710  [Pipeline] sh
00:19:06.992  + vagrant destroy -f
00:19:10.289  ==> default: Removing domain...
00:19:10.303  [Pipeline] sh
00:19:10.587  + mv output /var/jenkins/workspace/vhost-initiator-vg-autotest/output
00:19:10.597  [Pipeline] }
00:19:10.616  [Pipeline] // stage
00:19:10.623  [Pipeline] }
00:19:10.641  [Pipeline] // dir
00:19:10.648  [Pipeline] }
00:19:10.665  [Pipeline] // catchError
00:19:10.675  [Pipeline] stage
00:19:10.678  [Pipeline] { (Epilogue)
00:19:10.692  [Pipeline] sh
00:19:10.976  + jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh
00:19:11.928  [Pipeline] archiveArtifacts
00:19:11.934  Archiving artifacts
00:19:11.970  [Pipeline] cleanWs
00:19:11.980  [WS-CLEANUP] Deleting project workspace...
00:19:11.980  [WS-CLEANUP] Deferred wipeout is used...
00:19:11.987  [WS-CLEANUP] done
00:19:11.989  [Pipeline] }
00:19:12.008  [Pipeline] // stage
00:19:12.015  [Pipeline] }
00:19:12.029  [Pipeline] // node
00:19:12.036  [Pipeline] End of Pipeline
00:19:12.061  Finished: ABORTED

**Comment by spdkci** [comment] 2022-07-27 17:54
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_81345.html

**Comment by jimharris** [comment] 2022-08-04 04:38
This is almost certainly related to issue #2596.

**Comment by karlatec** [comment] 2022-10-03 11:19
#2596 was fixed @ closed some time ago and #2610 was not reported again since August.
@jchachux please retest this using `vhost-initiator-vg-autotest` job in our CI using latest SPDK master branch (might be a good idea to run this test several times). Close the issue if it's not reproducible

**Comment by jchachux** [comment] 2022-10-04 10:41
Issue didn't reproduce after testing with SPDK master branch.

**Comment by spdkci** [comment] 2023-01-10 17:57
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_94568.html

**Closed** 2023-04-04 15:48 UTC
Labels: Intermittent Failure
