### ISSUE TITLE
vhost_autotest apparent latent failure

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#695] opened 2019-02-27 17:25 UTC
## Expected Behavior
This test should not fail on unrelated patches.

## Current Behavior
There is a timeout on this test that occured on three different patches that did not seem to me to be related to vhost.

## Possible Solution
Not sure yet

## Steps to Reproduce
https://ci.spdk.io/spdk-jenkins/public_build/autotest-per-patch_24148.html
https://ci.spdk.io/spdk-jenkins/public_build/autotest-per-patch_24143.html
https://ci.spdk.io/spdk-jenkins/public_build/autotest-per-patch_24142.html

## Context (Environment including OS version, SPDK version, etc.)
Jenkins test pool

**Comment by darsto** [comment] 2019-03-01 12:44
This might be caused by upgrading to qemu 3.0. We still need to debug it though...

**Comment by darsto** [comment] 2019-03-13 08:13
From the current logs I can tell that SPDK vhost does everything correctly. It looks like SeaBIOS has enumerated all the virtio drives, performed a clean virtio-pci shutdown, started booting up the OS and that's where it's stuck. The OS does not even get to the point where it initializes the virtio-pci devices, so it's either a SeaBIOS or Linux issue - we could use logs for both, currently we have none.

**Comment by darsto** [comment] 2019-03-18 07:12
Specifically, what we need is:
 * `console=ttyS0 earlyprintk=ttyS0` in the linux command line inside the VM
 * `-serial file:/path/to/console.log` in QEMU
 * `-chardev file,path=/path/to/seabios.log,id=seabios -device isa-debugcon,iobase=0x402,chardev=seabios` in QEMU
 * timeout for "Waiting for VMs to boot", so that all of the above can be printed

**Comment by karlatec** [comment] 2019-03-18 08:25
@darsto
```
This might be caused by upgrading to qemu 3.0. We still need to debug it though...
```
Not related IMO. Physical servers which run vhost tests have Qemu 3.0.0 installed, but still use 2.12 to run the test. You can see that https://review.gerrithub.io/437302 is not merged.

```
console=ttyS0 earlyprintk=ttyS0
-serial file:/path/to/console.log
```
These two are already in place, so just need to work on points 3 & 4.

**Comment by pawelkax** [comment] 2019-03-22 14:32
@darsto @karlatec Uploaded patch that should help to solve this intermittent failure:
https://review.gerrithub.io/#/c/spdk/spdk/+/448575/

**Comment by karlatec** [comment] 2019-03-26 13:33
@pawelkax Thanks Pawel! Your patch was very helpful. Using the output we were able to narrow down the problem to:
```
14:05:17 virtio-scsi vendor='INTEL' product='Logical Volume' rev='0001' type=0 removable=0
14:05:17 virtio-scsi: unsupported block size 4096
```
When running vhost_boot.sh test. Pretty sure that this is caused by replacing a fauly disk some time ago, most probably it's not formatted properly.

**Comment by karlatec** [comment] 2019-03-26 13:47
Just changed LBA to 512 on GP3. Let's be on a lookout if the problem is solved.

**Comment by darsto** [comment] 2019-03-26 14:01
Still, we can't have an implicit requirement of NVMe block size == 512 in our vhost tests. Let's keep this issue open until there's a patch out.

**Comment by jimharris** [comment] 2019-05-02 15:37
@darsto - do you just mean something in our vhost test scripts that explicitly check the NVMe block size, and fail the test immediately if it's not 512?

**Comment by darsto** [comment] 2019-06-05 10:21
@jimharris Yeah - at least

**Closed** 2019-07-23 22:53 UTC
Labels: Infrastructure
