### ISSUE TITLE
CAP.CSS not reporting support for NVM Command Set

### ISSUE THREAD

**Issue by KariukiJ** [spdk/spdk#829] opened 2019-06-18 20:20 UTC
The Command Sets Supported (CSS) field of the Controller Capabilities (CAP) register is not set correctly.

## Expected Behavior
CAP.CSS register field is set to ‘1’ to indicate that the NVM Command Set is supported by the controller

## Current Behavior
Found bit 37 of CAP = 0

## Steps to Reproduce

1. Configure the NVMe Host to read the CAP.CSS register field (bits 37:44) of the NVMe Controller. 
2. Verify that Bit 37 of the CAP.CSS register field is set to ‘1’ to indicate that the NVM Command Set is supported by the controller. 

Here are the test logs
Running test: 4.3.1
Running on device: /dev/nvme0
Setting device to /dev/nvme0

Finished getting/parsing controller data struct
Test 4.3.1 began at 16:16:44.666020082
CAP (Controller Capabilities) 0x101007f
CSS found: 0x0
Test 4.3.1 completed at 16:16:44.672182920
Total of 0 seconds elapsed for test 4.3.1
Found bit 37 of CAP = 0. All drives are required to support the NVM Command Set.

## Context (Environment including OS version, SPDK version, etc.)

Test Setup: SPDK NVMe-oF Target (8 Optane SSDs, 4 lvols per SSD exported over NVMe-oF via TCP, RNIC – Mellanox ConnectX5). Kernel v5.1.0 Host using Mellanox ConnectX4 RNIC.
SPDK Commit ID 8ac86b2

**Comment by changpe1** [comment] 2019-06-19 02:44
@KariukiJ Thanks John, I've root caused the issue, and it's one bug from Linux kernel, Linux ioctl always uses u32 to get the result for fabrics connect commands, I'll report this issue to Linux kernel community.

**Comment by changpe1** [comment] 2019-06-26 06:59
All ready submit a email to Linux block-nvme maillist, no body responded to my eamil, the change is quite straightforward, but it will break the uapi as well as nvme-cli.

**Comment by darsto** [comment] 2019-07-30 15:57
@changpe1 ping

**Comment by changpe1** [comment] 2019-07-31 04:27
> @changpe1 ping

No response from Linux block-nvme mainlist as well as nvme-cli community.

I can fix it too so set the issue with low priority and fix it later.

**Comment by jimharris** [comment] 2020-01-10 15:34
I think this has been fixed in v5.4.  This commit explicitly mentions this UNH test:

https://github.com/torvalds/linux/commit/65e68edce0db433aa0c2b26d7dc14fbbbeb89fbb

@KariukiJ - can you retry the UNH tests on a system with Linux 5.4 kernel?

**Comment by jimharris** [comment] 2020-02-27 16:56
Linux patch was merged so closing this issue.  @KariukiJ - if you still see problems when running UNH tests in the future, please reopen.

**Closed by jimharris** 2020-02-27 16:56 UTC
Labels: 3rd party issue, Low
