### ISSUE TITLE
test/scheduler/interrupt.sh: not all cpus are idle for idle spdk

### ISSUE THREAD

**Issue by krzysztofsmolinski** [spdk/spdk#2778] opened 2022-11-14 11:57 UTC
# CI Intermittent Failure

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_89506.html
https://ci.spdk.io/results/autotest-per-patch/builds/89506/archive/nvme-phy-autotest/build.log

## Execution failed at

> 00:27:09.572  ========== Backtrace start: ==========
00:27:09.572  
00:27:09.572  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/scheduler/interrupt.sh:41 -> interrupt([])
00:27:09.572       ...
00:27:09.572     36  		for cpu in "${!is_idle[@]}"; do
00:27:09.572     37  			if ((cpu == spdk_main_core)); then
00:27:09.572     38  				((is_idle[cpu] == 0)) # main cpu must not be idle
00:27:09.572     39  			fi
00:27:09.572     40  			if ((cpu != spdk_main_core)); then
00:27:09.572  => 41  				((is_idle[cpu] == 1)) # all cpus except the main cpu must be idle
00:27:09.572     42  			fi
00:27:09.572     43  		done
00:27:09.572     44  	
00:27:09.572     45  		# select 3 cpus except the main one
00:27:09.572     46  		busy_cpus=("${cpus[@]:1:3}") threads=()
00:27:09.572       ...
00:27:09.572  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/scheduler/interrupt.sh:77 -> main([])
00:27:09.572       ...
00:27:09.572     72  		done
00:27:09.572     73  	}
00:27:09.572     74  	
00:27:09.572     75  	exec_under_dynamic_scheduler "$scheduler" -m "$spdk_cpumask" --main-core "$spdk_main_core"
00:27:09.572     76  	
00:27:09.572  => 77  	interrupt
00:27:09.572       ...
00:27:09.572  
00:27:09.572  ========== Backtrace end ==========

**Comment by spdkci** [comment] 2022-11-14 11:58
Another instance of this failure. Reported by @krzysztofsmolinski. log: https://ci.spdk.io/public_build/autotest-per-patch_89506.html

**Comment by jimharris** [comment] 2022-11-14 15:35
This is a duplicate of #1950, which was recently fixed.  Please rebase patch set on latest master.  Thanks.

**Closed by jimharris** 2022-11-14 15:35 UTC
Labels: Intermittent Failure
