### ISSUE TITLE
NVMe-oF ERROR: NVMeoF uses extended controller data structure, please set EDS bit in cdw11 and try again

### ISSUE THREAD

**Issue by KariukiJ** [spdk/spdk#817] opened 2019-06-10 23:10 UTC
I was running test case 7.3.1 in the UNH-IOL compliance testing which test that our emulated NVMe Reservation handles Unregistering with the Reservation Register Command correctly. 
The test case is failing with error the errors reported in issue https://github.com/spdk/spdk/issues/812 plus the following new error:

subsystem.c:1973:nvmf_ns_reservation_report: *ERROR*: NVMeoF uses extended controller data structure, please set EDS bit in cdw11 and try again

## Expected Behavior
Successful completion of an unregister operation causes the host to no longer be a registrant of that namespace. 

## Current Behavior
The SPDK NVMe-oF Target throws the following errors

[tc_731_errors.txt](https://github.com/spdk/spdk/files/3274104/tc_731_errors.txt)

## Steps to Reproduce

1.  Configure the NVMe Host to issue a Reservation Register command with the Reservation Register Action (RREGA) field set to 000b (i.e. Register Reservation Key) and supplying a reservation key in the New Reservation Key (NRKEY) field to the NVMe Controller for the namespace in order to make the host a registrant of that namespace.

2. Configure the NVMe Host to issue a Reservation Register command with the Unregister Reservation Key action and supplying its current reservation key in the CRKEY field to the NVMe Controller for the namespace in order to unregister the host as a registrant of that namespace.

3. Configure the NVMe Host to issue a Reservation Report command to the NVMe Controller.

## Context (Environment including OS version, SPDK version, etc.)

Test Setup: SPDK NVMe-oF Target (8 Optane SSDs, 4 lvols per SSD exported over NVMe-oF via TCP, RNIC – Mellanox ConnectX5). Kernel v5.1.0 Host using Mellanox ConnectX4 RNIC.
SPDK Commit ID 8ac86b2

**Comment by changpe1** [comment] 2019-06-19 05:41
I checked the specification, 5.21.1.19 Host Identifier says NVMoF should use extended 128-bit Host Identifier, and NVMe Reservation Report command should set EDS(Extended Data Structure) to 1 to indicate the returned data should be extended data structure.

**Comment by darsto** [comment] 2019-08-27 15:56
Bug scrub: @benlwalker to confirm

**Comment by benlwalker** [comment] 2019-11-13 18:13
I can confirm that our code is correct. This is a test bug in the UNH suite.

**Comment by jimharris** [comment] 2019-11-13 18:24
Have we provided feedback to UNH so they can fix the test suite?

**Comment by jimharris** [comment] 2019-11-13 18:24
Reopening but assigning to @KariukiJ to confirm that UNH has our feedback.

**Comment by jimharris** [comment] 2020-02-20 04:59
Bug scrub: @KariukiJ - have you confirmed this issue with UNH?  Thanks.

**Comment by jimharris** [comment] 2020-02-27 16:57
@KariukiJ - ping

**Comment by tomzawadzki** [comment] 2020-06-16 16:03
@KariukiJ Has the feedback on test case in UNH test suite been provided ?

**Comment by jimharris** [comment] 2020-11-02 17:43
Hi @KariukiJ,

Can you provide an update on this issue?

Thanks,

Jim

**Comment by KariukiJ** [comment] 2020-11-13 16:59
I submitted an issue to UNH. UNH asked me to retest with the latest version of the tool iol_tcp-14.0a to make sure its still an issue. Verified the same issue happens on v14 of the UNH test tool.

**Comment by jimharris** [comment] 2021-05-13 23:55
Closing this issue since it's a 3rd party issue.

**Closed by jimharris** 2021-05-13 23:55 UTC
Labels: 3rd party issue
