### ISSUE TITLE
SPDK Host have remote memory access issue when work with Kernel target based on SLES12SP4

### ISSUE THREAD

**Issue by gwnet** [spdk/spdk#964] opened 2019-09-19 10:25 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Below is the request from one kernel dmesg issue. 
We are using SPDK host and kernel target. When SPDK host send write request to target, kernel target will do RDMA read to handle host side write request, but when RDMA NIC try to read the host memory, it failed with below yellow error code 13. That means remote access error.
Host memory is configured and allocated by SPDK host via huge page. This error should relate with host side. but we do not know how to debug the root cause at host side code level. can MLX assign one developer to give us some suggestion from developer point of view?

enum {
               MLX5_CQE_SYNDROME_REMOTE_ACCESS_ERR             = 0x13,

[Sep 2 06:28] mlx5_bond_0:dump_cqe:276:(pid 1436): dump error cqe
[  +0.000002] 00000000 00000000 00000000 00000000
[  +0.000001] 00000000 00000000 00000000 00000000
[  +0.000000] 00000000 00000000 00000000 00000000
[  +0.000001] 00000000 00008813 1001af37 115e97d3
[  +0.000005] nvmet_rdma: RDMA READ for CQE 0xffff9d8562295810 failed with status remote access error (10).
[  +0.000004] nvmet: ctrl 36 fatal error occurred!

## Expected Behavior

no kernel target side error.

## Current Behavior

sometimes we see this kernel dmesg error randomly.

## Steps to Reproduce

1. use our application that call SPDK lib to init the NVMeOF host
2. then add some time load
3. this issue will happen at kernel target,
4. SPDK host has no log for this error.

**Comment by AlekseyMarchuk** [comment] 2019-09-24 09:34
Hi,

Could you provide some details about MOFED version and NIC model so we can continue the analysis?

**Comment by gwnet** [comment] 2019-09-24 13:34
SPDK is 19.04, we did not install MLX OFED and we are CX-4 NIC, I will paste out the MLX NIC type next day.

**Comment by AlekseyMarchuk** [comment] 2019-09-24 13:51
Which version of OFED do you use?

**Comment by gwnet** [comment] 2019-09-24 14:13
we did not install any OFED, only SLES12SP4 kernel default drivers is used. we use default SPDK initiator parameters. our senario is distributed storage system will add incast network load. it only happen after some times like 4 hours if under low load. if under performance load, it can reproduce in 10 mins under our HW

**Comment by jimharris** [comment] 2019-09-24 15:13
Bug scrub 09/24: Assigned to Aleksey.  He will follow up with additional steps to root cause.

**Comment by AlekseyMarchuk** [comment] 2019-09-24 16:00
I want to reproduce this issue on my setup. Please provide SPDK version, nvme_perf command line parameters and kernel target parameters.

**Comment by gwnet** [comment] 2019-09-25 07:02
SPDK is 19.04, kernel target side parameter is default. 

and also we have another issue. I review the code, I feel SPDK host will not send all 0 command to target, from the code, it should be type is 0, subtype is 1, but target got one subtype is also 0. it is very strange kernel target got this command. 

[Sep 3 06:18] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.429688] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.111832] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.228752] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.081262] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.246301] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.073023] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.108202] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.030376] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.254119] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.149732] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.033568] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.221076] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.009124] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.585690] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.040728] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.000128] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.043132] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.400310] nvmet_rdma: invalid SGL subtype: 0x0
[  +1.114577] nvmet_rdma: invalid SGL subtype: 0x0
[Sep 3 07:02] nvmet_rdma: invalid SGL subtype: 0x0
[Sep 3 07:03] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.347318] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.249373] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.691690] nvmet_rdma: invalid SGL subtype: 0x0
[  +0.912708] nvmet_rdma: invalid SGL subtype: 0x0
[  +3.320910] nvmet_rdma: invalid SGL subtype: 0x0
[  +5.135038] nvmet_rdma: invalid SGL subtype: 0x0
[  +7.984048] nvmet_rdma: invalid SGL subtype: 0x0
[Sep 3 07:05] nvmet_rdma: invalid SGL subtype: 0x0

**Comment by AlekseyMarchuk** [comment] 2019-09-30 08:29
We don't have SLES12SP4 in our lab, so I used Fedora 27 with kernel 4.13.9-300. I started vanilla SPDK initiator (spdk_nvme_perf binary) for 72 hours and the issue didn't reproduce. I used 2 cores, IO unit_size 4k and qpdeth 16.
You mentioned that you used your own application that uses SPDK libraries. Could you clarify how your application allocates IO buffers?
Can you to update SPDK to 19.07.1 (that is the most recent release) and try to reproduce the issue with spdk_nvme_perf application to exclude possible bugs in your app?
Is it possible to reproduce this problem on another OS?

**Comment by gwnet** [comment] 2019-10-09 15:15
we failed to reproduce the issue with pure SPDK perf.
our application just call SPDK nvmeof host lib API. for 19.07, we will try.
for allocate IO buffers, for read path we allocate with spdk_dma_zmalloc API. for write path we did not call spdk_dma_zmalloc API, we just pass the buffer from network down to SPDK write API. is this OK?

no we cannot reproduce with another OS.

       read_buffer = (char *)spdk_dma_zmalloc(aligned_size, 512, nullptr);
       assert(read_buffer);
       /* record the aligned buffer in io_req */
       io_req->set_msg_data(read_buffer);

       ELOG_DEBUG << "aligned_offset=" << aligned_offset << " aligned_size = " << aligned_size;
       ret = nvme_dev->SubmitRead(qp_id,
                                  read_buffer,
                                  aligned_offset,
                                  aligned_size,
                                  OnReadDone,
                                  (void *)io_req);
       if (ret) {
         ELOG_ERROR << "SubmitRead failed";
         OnReadDone(-1, (void *)io_req);
       }
       return;

     case nvmf_host::NVMF_IO_WRITE:
       /* Update data length */
       io_req->set_data_len(hdr->data_len);
       ret = nvme_dev->SubmitWrite(qp_id,
                                   (void *)(const_cast<char *>(io_req->msg_data())),
                                   hdr->offset,
                                   hdr->data_len,
                                   OnWriteDone,
                                   (void *)io_req);

**Comment by AlekseyMarchuk** [comment] 2019-10-10 06:35
Could you clarify about network buffer which is used in write flow - who and how allocates and frees this buffer?
It is important for workflow since SPDK RDMA implementation subscribes for all DMA allocations created with spdk_dma* API and registers MR for each allocation. New MR is created with LOCAL_WRITE | REMOTE_READ | REMOTE_WRITE access, error that you observed means that some MR was created without REMOTE_READ permissions. Or it might be a side effect of the case when DMA allocation is freed (thereby MR is deregistered) before RDMA operation completes (it also looks like a cause of the error reported in https://github.com/spdk/spdk/issues/961)
In general it is Ok to use this buffer if it is allocated using spdk_dma* API and it is not freed until all RDMA operations which use this buffer completes.

**Comment by gwnet** [comment] 2019-10-11 12:25
hello @AlekseyMarchuk 
we highly possible got the root cause. our host process call the fork to create another process. as RDMA https://www.rdmamojo.com/2012/05/24/ibv_fork_init/ mentioned call the fork will change va pa mapping. I feel maybe this issue is highly related with this. how do you think about this?

**Comment by AlekseyMarchuk** [comment] 2019-10-11 13:30
Hi @gwnet 
Yes it looks like it is the root cause of your problem

**Comment by changpe1** [comment] 2019-10-17 02:24
@gwnet Can we close this issue for now?

**Comment by gwnet** [comment] 2019-10-17 14:12
yes, please.

**Closed** 2019-10-17 14:13 UTC
