### ISSUE TITLE
[nvme_phy_autotest] Failures in nvme_single_aen

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2564] opened 2022-06-22 19:45 UTC
Some errors like this:

START TEST nvme_single_aen
....
....

00:04:42.406  [2022-06-22 20:51:42.694654] nvme_ctrlr.c:1621:nvme_ctrlr_disconnect: *NOTICE*: [0000:84:00.0] resetting controller
00:04:42.406  [2022-06-22 20:51:42.694685] nvme_pcie_common.c: 292:nvme_pcie_qpair_insert_pending_admin_request: *ERROR*: The owning process (pid 547306) is not found. Dropping the request.
00:04:42.406  [2022-06-22 20:51:42.694729] nvme_pcie_common.c: 292:nvme_pcie_qpair_insert_pending_admin_request: *ERROR*: The owning process (pid 547306) is not found. Dropping the request.
00:04:42.406  [2022-06-22 20:51:42.694746] nvme_pcie_common.c: 292:nvme_pcie_qpair_insert_pending_admin_request: *ERROR*: The owning process (pid 547306) is not found. Dropping the request.
00:04:42.406  [2022-06-22 20:51:42.694759] nvme_pcie_common.c: 292:nvme_pcie_qpair_insert_pending_admin_request: *ERROR*: The owning process (pid 547306) is not found. Dropping the request.

Followed by thousands of these:

00:04:47.742  0000:84:00.0: Current Temperature:         308 Kelvin (35 Celsius)
00:04:47.742  0000:84:00.0: aer_cb for log page 2, aen_event_type: 0x01, aen_event_info: 0x01
00:04:47.742  aer_cb - Resetting Temp Threshold for device: 0000:84:00.0
00:04:47.742  0000:84:00.0: Current Temperature:         308 Kelvin (35 Celsius)
00:04:47.742  0000:84:00.0: aer_cb for log page 2, aen_event_type: 0x01, aen_event_info: 0x01
00:04:47.742  aer_cb - Resetting Temp Threshold for device: 0000:84:00.0
00:04:47.742  0000:84:00.0: Current Temperature:         308 Kelvin (35 Celsius)

and eventually the tests aborts

**Comment by spdkci** [comment] 2022-06-22 19:46
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_79008.html

**Comment by jimharris** [comment] 2022-06-22 20:15
Duplicate of #2559.

**Closed by jimharris** 2022-06-22 20:15 UTC
Labels: Intermittent Failure

**Comment by spdkci** [comment] 2022-06-27 09:07
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_79222.html
