### ISSUE TITLE
[nvmf_filesystem_no_in_capsule] could not shm_open spdk_trace

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#2483] opened 2022-04-25 12:26 UTC
```
00:03:30.425  Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
00:03:30.425   14:01:03	-- common/autotest_common.sh@718 -- # xtrace_disable
00:03:30.425   14:01:03	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:03:30.425   14:01:03	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:03:30.425   14:01:03	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:03:30.425   14:01:03	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:03:30.425   14:01:03	-- common/autotest_common.sh@19 -- # set +x
00:03:30.425  [2022-04-25 14:01:03.354224] Starting SPDK v22.05-pre git sha1 a921ff02127 / DPDK 21.11.0 initialization...
00:03:30.425  [2022-04-25 14:01:03.354314] [ DPDK EAL parameters: [2022-04-25 14:01:03.354329] nvmf [2022-04-25 14:01:03.354340] -c 0xF [2022-04-25 14:01:03.354349] --log-level=lib.eal:6 [2022-04-25 14:01:03.354358] --log-level=lib.cryptodev:5 [2022-04-25 14:01:03.354368] --log-level=user1:6 [2022-04-25 14:01:03.354377] --base-virtaddr=0x200000000000 [2022-04-25 14:01:03.354387] --match-allocations [2022-04-25 14:01:03.354396] --file-prefix=spdk0 [2022-04-25 14:01:03.354405] --proc-type=auto [2022-04-25 14:01:03.354415] ]
00:03:30.425  EAL: No free 2048 kB hugepages reported on node 1
00:03:30.425  EAL: No available 1048576 kB hugepages reported
00:03:30.425  TELEMETRY: No legacy callbacks, legacy socket not created
00:03:30.685  [2022-04-25 14:01:03.419254] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 4
00:03:30.686  [2022-04-25 14:01:03.505418] trace.c: 188:spdk_trace_init: *ERROR*: could not shm_open spdk_trace
00:03:30.686  [2022-04-25 14:01:03.505487] trace.c: 189:spdk_trace_init: *ERROR*: errno=13 Permission denied
```

## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/75967/archive/nvmf-phy-autotest/build.log
https://ci.spdk.io/public_build/autotest-per-patch_75967.html

**Comment by spdkci** [comment] 2022-04-25 12:26
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_75967.html

**Comment by spdkci** [comment] 2022-04-28 15:22
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_76256.html

**Comment by spdkci** [comment] 2022-04-29 11:21
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_76340.html

**Comment by spdkci** [comment] 2022-04-30 20:53
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_76374.html

**Comment by jimharris** [comment] 2022-05-03 15:26
[Bug scrub] @jimharris will take a look.  We know there are cases where /dev/shm can run out of space, but it is less clear how 'permission denied' could happen.

**Comment by spdkci** [comment] 2022-05-09 23:06
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_76754.html

**Comment by spdkci** [comment] 2022-05-12 12:02
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_77111.html

**Comment by spdkci** [comment] 2022-05-23 11:59
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_77817.html

**Comment by spdkci** [comment] 2022-06-02 14:53
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_78195.html

**Comment by spdkci** [comment] 2022-06-08 17:34
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_78427.html

**Comment by spdkci** [comment] 2022-06-09 13:01
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_78507.html

**Comment by spdkci** [comment] 2022-06-13 05:55
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_78653.html

**Comment by spdkci** [comment] 2022-06-15 15:39
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_78664.html

**Comment by spdkci** [comment] 2022-06-17 06:25
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_78824.html

**Comment by spdkci** [comment] 2022-06-18 09:42
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_78829.html

**Comment by spdkci** [comment] 2022-07-13 01:12
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_80165.html

**Comment by spdkci** [comment] 2022-07-15 11:57
Another instance of this failure. Reported by @kgodzwox. log: https://ci.spdk.io/public_build/autotest-per-patch_80513.html

**Comment by spdkci** [comment] 2022-07-18 01:50
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_80583.html

**Comment by spdkci** [comment] 2022-07-19 02:48
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_80615.html

**Comment by spdkci** [comment] 2022-07-19 06:27
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_80581.html

**Comment by spdkci** [comment] 2022-07-19 13:02
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_80707.html

**Comment by spdkci** [comment] 2022-07-27 12:30
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_81323.html

**Comment by spdkci** [comment] 2022-08-01 14:08
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_81572.html

**Comment by spdkci** [comment] 2022-08-02 11:53
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_81672.html

**Comment by tomzawadzki** [comment] 2022-08-02 15:31
[Bug scrub] @mikeBashStuff will try adding debugging info on the shared mem on failure.

**Comment by spdkci** [comment] 2022-08-03 11:46
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_81776.html

**Comment by mikeBashStuff** [comment] 2022-08-04 14:22
So I've run multiple nvmf-phy jobs with some debug from https://review.spdk.io/gerrit/c/spdk/spdk/+/13874 to target the potential out of space issue. So far, all the jobs finished without any problems, but under one I noticed something odd to me - this is how contents of the `/dev/shm` looked like:

```
15:55:17  Mounted on  Size Avail  Used Use% Inodes IFree IUsed IUse%
15:55:17  /dev/shm     32G   31G  1.2G   4%   7.9M  7.9M    11    1%
15:55:17    Opts -- 31 24 0:27 / /dev/shm rw,nosuid,nodev shared:10 - tmpfs tmpfs rw,inode64"
15:55:17    Files:
15:55:17    1.2G	/dev/shm
15:55:17    130M	/dev/shm/nvmf_trace.0
15:55:17    130M	/dev/shm/bdevperf_trace.pid3245395
15:55:17    84K	/dev/shm/libpod_rootless_lock_1001
15:55:17    130M	/dev/shm/(null)_trace.pid1533173
15:55:17    130M	/dev/shm/(null)_trace.pid1533153
15:55:17    130M	/dev/shm/(null)_trace.pid1449517
15:55:17    130M	/dev/shm/(null)_trace.pid1449497
15:55:17    130M	/dev/shm/(null)_trace.pid1152422
15:55:17    130M	/dev/shm/(null)_trace.pid1152400
15:55:17    130M	/dev/shm/bdev_svc_trace.1
15:55:17  
```
I am not sure under what condition the `opt->name` ends up as `(null)` but it doesn't look very healthy.

**Comment by jimharris** [comment] 2022-08-04 16:50
Thanks @mikeBashStuff!!!  That (null) finding I think points to the root cause.

I audited all of the in-tree applications that use spdk_app_opts_init() and noticed that accel_perf is not setting the opts->name.  The shm file always gets created (even if no events are enabled) but at app shutdown we unlink the file if there were no events generated.  But this also means if accel_perf crashes (which happens since accel_perf is under active development), it means those shm files wouldn't get unlinked since we don't go through an orderly shutdown.

And the cleanup_linux() function in setup.sh of course doesn't look for shm file names with "(null)" in them.  So this would explain why those get built up over time.

https://review.spdk.io/gerrit/c/spdk/spdk/+/13876 ensures that spdk_app_start() callers always set opts->name, and also populates a name for accel_perf.

https://review.spdk.io/gerrit/c/spdk/spdk/+/13877 adds 'accel_perf' and 'bdev_svc' to the list of shm files that we cleanup in setup.sh.  Probably the shm_file cleanup mechanism could be improved in the future, but this at least fixes this problem for now.

**Comment by jimharris** [comment] 2022-08-04 17:01
> Thanks @mikeBashStuff!!! That (null) finding I think points to the root cause.
> 
> I audited all of the in-tree applications that use spdk_app_opts_init() and noticed that accel_perf is not setting the opts->name. The shm file always gets created (even if no events are enabled) but at app shutdown we unlink the file if there were no events generated. But this also means if accel_perf crashes (which happens since accel_perf is under active development), it means those shm files wouldn't get unlinked since we don't go through an orderly shutdown.
> 
> And the cleanup_linux() function in setup.sh of course doesn't look for shm file names with "(null)" in them. So this would explain why those get built up over time.
> 
> https://review.spdk.io/gerrit/c/spdk/spdk/+/13876 ensures that spdk_app_start() callers always set opts->name, and also populates a name for accel_perf.
> 
> https://review.spdk.io/gerrit/c/spdk/spdk/+/13877 adds 'accel_perf' and 'bdev_svc' to the list of shm files that we cleanup in setup.sh. Probably the shm_file cleanup mechanism could be improved in the future, but this at least fixes this problem for now.

The one thing I can't explain though is why we are getting "Permission denied" (EACCES) error for this.  On my local VM, if I run out of /dev/shm space I get ENOMEM instead.  Can you check /proc/sys/kernel/{shmall, shmmax, shmmni} on this system?

**Comment by mikeBashStuff** [comment] 2022-08-04 20:47
@jimharris Updated  debug patch to get this info into build.log. But since we don't set any sysctls to some custom values, this should match the actual defaults (as declared in `linux/shm.h` and this is what I actually saw by quickly reviewing some of our phy nodes). I scheduled some extra jobs for a spin, targeting GP6 (since this is the node that pops up in most of the reports).

Regarding https://review.spdk.io/gerrit/c/spdk/spdk/+/13877 - I actually initially pushed an alternative together with the debug patch here: https://review.spdk.io/gerrit/c/spdk/spdk/+/13875. That said, I don't really have a preference so I just +1ed your patch. :)

**Comment by mikeBashStuff** [comment] 2022-08-04 23:11
Since shm_open(3) is not that helpful I decided to read through open(2) and see if there are some specific cases where `EACCESS` is returned (in general this man page is quite verbose so I reckoned it may hold some interesting details). And indeed here's an interesting note:

```
EACCES Where O_CREAT is specified, the protected_fifos or protected_regular sysctl is enabled, the file already exists
and is a FIFO or regular file, the owner of the file is neither the current user nor the owner of the containing
directory and the containing directory is both world- or group-writable and sticky.  For details, see the
descriptions of /proc/sys/fs/protected_fifos and /proc/sys/fs/protected_regular in proc(5).
```
So in general, there is a case when root can hit `EACCESS` while trying to open a file. Here's a small reproducer of the case described above:

```
[root@fedora35-cloud-21845 spdk]#  ./eaccess
* Running as root
* /dev/shm perms set to 1777
* /dev/shm owner set to 0
* /dev/shm/nvmf_trae.0 owner set to 1
* Flipping owner bits on /dev/shm/nvmf_trace.0 to 0
* shm_open will succeed
[2022-08-04 22:59:22.805337] Starting SPDK v22.09-pre / DPDK 22.03.0 initialization...
[2022-08-04 22:59:22.806172] [ DPDK EAL parameters: [2022-08-04 22:59:22.806228] nvmf [2022-08-04 22:59:22.806246] -c 0x1 [2022-08-04 22:59:22.806258] --log-level=lib.eal:6 [2022-08-04 22:59:22.806286] --log-level=lib.cryptodev:5 [2022-08-04 22:59:22.806306] --log-level=user1:6 [2022-08-04 22:59:22.806324] --iova-mode=pa [2022-08-04 22:59:22.806339] --base-virtaddr=0x200000000000 [2022-08-04 22:59:22.806353] --match-allocations [2022-08-04 22:59:22.806381] --file-prefix=spdk0 [2022-08-04 22:59:22.806416] --proc-type=auto [2022-08-04 22:59:22.806453] ]
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-08-04 22:59:22.971175] app.c: 575:spdk_app_start: *NOTICE*: Total cores available: 1
[2022-08-04 22:59:23.244245] app.c: 421:app_setup_trace: *NOTICE*: Tracepoint Group Mask 0xffff specified.
[2022-08-04 22:59:23.244434] app.c: 422:app_setup_trace: *NOTICE*: Use 'spdk_trace -s nvmf -i 0' to capture a snapshot of events at runtime.
[2022-08-04 22:59:23.244471] app.c: 427:app_setup_trace: *NOTICE*: Or copy /dev/shm/nvmf_trace.0 for offline analysis/debug.
[2022-08-04 22:59:23.244544] reactor.c: 919:reactor_run: *NOTICE*: Reactor started on core 0
[2022-08-04 22:59:23.244673] accel_engine.c: 943:sw_accel_engine_init: *NOTICE*: Accel framework software engine initialized.
[root@fedora35-cloud-21845 spdk]#  ./eaccess
* Running as root
* /dev/shm perms set to 1777
* /dev/shm owner set to 0
* /dev/shm/nvmf_trae.0 owner set to 0
* Flipping owner bits on /dev/shm/nvmf_trace.0 to 1
* Owner of /dev/shm/nvmf_trace.0 not matching current user
* Owner of /dev/shm/nvmf_trace.0 not matching owner of /dev/shm
* /dev/shm is world,group writtable
* /dev/shm has sticky bit set
* protected_regular enabled
* shm_open will fail
[2022-08-04 22:59:27.449664] Starting SPDK v22.09-pre / DPDK 22.03.0 initialization...
[2022-08-04 22:59:27.449811] [ DPDK EAL parameters: [2022-08-04 22:59:27.449835] nvmf [2022-08-04 22:59:27.449860] -c 0x1 [2022-08-04 22:59:27.449874] --log-level=lib.eal:6 [2022-08-04 22:59:27.449888] --log-level=lib.cryptodev:5 [2022-08-04 22:59:27.449902] --log-level=user1:6 [2022-08-04 22:59:27.449915] --iova-mode=pa [2022-08-04 22:59:27.449929] --base-virtaddr=0x200000000000 [2022-08-04 22:59:27.449951] --match-allocations [2022-08-04 22:59:27.449966] --file-prefix=spdk0 [2022-08-04 22:59:27.449980] --proc-type=auto [2022-08-04 22:59:27.449993] ]
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-08-04 22:59:27.602720] app.c: 575:spdk_app_start: *NOTICE*: Total cores available: 1
[2022-08-04 22:59:27.777057] trace.c: 160:spdk_trace_init: *ERROR*: could not shm_open spdk_trace
[2022-08-04 22:59:27.777163] trace.c: 161:spdk_trace_init: *ERROR*: errno=13 Permission denied
./eaccess: line 39: kill: (20164) - No such process
[root@fedora35-cloud-21845 spdk]#
```

Reproducer:
```
#!/usr/bin/env bash

if [[ ! -e /dev/shm/nvmf_trace.0 ]]; then
        echo "* trace file does not exist"
        exit 1
fi

echo "* Running as $(id -nu)"

perms=$(stat --print="%a" "/dev/shm")
owner=$(stat --print="%u" "/dev/shm")
ownerf=$(stat --print="%u" "/dev/shm/nvmf_trace.0")

permso=$(( 8#$perms ))

echo "* /dev/shm perms set to $perms"
echo "* /dev/shm owner set to $owner"
echo "* /dev/shm/nvmf_trae.0 owner set to $ownerf"
echo "* Flipping owner bits on /dev/shm/nvmf_trace.0 to $(( !ownerf ))"

chown $(( !ownerf )) "/dev/shm/nvmf_trace.0"
ownerf=$(stat --print="%u" "/dev/shm/nvmf_trace.0")

if ((owner != ownerf && ownerf != USER && permso & (1 << 1) && permso & (1 << 4)
        && permso & (1 << 9) && $(< /proc/sys/fs/protected_regular) == 1)); then
        echo "* Owner of /dev/shm/nvmf_trace.0 not matching current user"
        echo "* Owner of /dev/shm/nvmf_trace.0 not matching owner of /dev/shm"
        echo "* /dev/shm is world,group writtable"
        echo "* /dev/shm has sticky bit set"
        echo "* protected_regular enabled"
        echo "* shm_open will fail"
else
        echo "* shm_open will succeed"
fi


./build/bin/nvmf_tgt  -e 0xffff -i 0 &
sleep 2s
kill $!
wait

```
So this scenario basically requires the ownership on the trace file to change (which in theory should be always root). The only culprit here I can think of is the `nvmf-non-root` job. Looking at its history it's all green, meaning that the nodes that are selected to run it are not being rebooted, hence potentially leaving a trace file with different ownership - the reboot happens when nvmf-phy-autotest picks up the "affected" node (same labels are used for those two jobs). Also, the majority of its recent builds did run under GP nodes that are listed in the reports. Also, also, this job is not using autotest framework, it simply runs `host/perf.sh` as a non-root user, hence skipping the entire cleanup stage.

With all that in mind, I will look into adjusting that job to clean up after itself properly. If I am on the right track this should help to get rid of this issue.

**Comment by mikeBashStuff** [comment] 2022-08-05 06:55
I just run `nvmf-phy-autotest` right after `nvmf-non-root`, on the same node, and that confirmed the above theory - issue got immediately reproduced.

**Comment by mikeBashStuff** [comment] 2022-08-05 10:43
Fix on the `nvmf-non-root` was applied and tested. Issue should be gone now but let's leave it open till the end of the day just to make sure we catch all potential failures that might have happened till now.

**Comment by mikeBashStuff** [comment] 2022-08-05 14:43
I've reviewed all the `nvmf-phy-autotest` jobs from today and so far there haven't been any instances of this issue seen. Considering that the CI was already updated it should be safe to close it.

**Closed by mikeBashStuff** 2022-08-05 14:43 UTC
Labels: Infrastructure, Intermittent Failure, Patches out for review
