### ISSUE TITLE
[qemu] vhost_boot: vm_wait_for_boot timeout

### ISSUE THREAD

**Issue by kgodzwox** [spdk/spdk#2528] opened 2022-05-25 08:28 UTC
# vhost-vs-qemu
Similiar problem as #2518 in `vhost-vs-qemu` test job. Timeout on VM booting. After bisecting commits from the `263` job I found a faulty commit in `qemu` repository.
```
hw/virtio/vhost-user: don't suppress F_CONFIG when supported
56534930b5cd3a6c7259cfeba69f08ba28c8f62a
```

## Commits

Last good commit: `27351992bf238f669dd08655d31ad111905bf899`
First bad commit: `56534930b5cd3a6c7259cfeba69f08ba28c8f62a`

## Execution failed at

```
[2022-05-17T06:07:39.657Z]  08:07:39	-- vhost/common.sh@66 -- # echo -e 'INFO: running /root/vhost_test/vms/0/run.sh'
[2022-05-17T06:07:39.657Z] INFO: running /root/vhost_test/vms/0/run.sh
[2022-05-17T06:07:39.657Z]  08:07:39	-- vhost/common.sh@868 -- # /root/vhost_test/vms/0/run.sh
[2022-05-17T06:07:39.657Z] Running VM in /root/vhost_test/vms/0
[2022-05-17T06:07:40.238Z] VHOST_CONFIG: (/root/vhost_test/vhost/0/naa.vhost_vm.0) new vhost user connection is 186
[2022-05-17T06:07:40.238Z] VHOST_CONFIG: (/root/vhost_test/vhost/0/naa.vhost_vm.0) new device, handle is 0
[2022-05-17T06:07:40.238Z] VHOST_CONFIG: (/root/vhost_test/vhost/0/naa.vhost_vm.0) read message VHOST_USER_GET_FEATURES
[2022-05-17T06:07:40.238Z] VHOST_CONFIG: (/root/vhost_test/vhost/0/naa.vhost_vm.0) read message VHOST_USER_GET_PROTOCOL_FEATURES
[2022-05-17T06:07:40.507Z] VHOST_CONFIG: (/root/vhost_test/vhost/0/naa.vhost_vm.0) vhost peer closed
[2022-05-17T06:07:40.507Z] Waiting for QEMU pid file
[2022-05-17T06:07:41.496Z] === qemu.log ===
[2022-05-17T06:07:41.496Z] === qemu.log ===
[2022-05-17T06:07:41.496Z]  08:07:41	-- vhost_boot/vhost_boot.sh@101 -- # vm_wait_for_boot 300 0
[2022-05-17T06:07:41.496Z]  08:07:41	-- vhost/common.sh@904 -- # assert_number 300
[2022-05-17T06:07:41.496Z]  08:07:41	-- vhost/common.sh@257 -- # [[ 300 =~ [0-9]+ ]]
[2022-05-17T06:07:41.496Z]  08:07:41	-- vhost/common.sh@257 -- # return 0
[2022-05-17T06:07:41.496Z]  08:07:41	-- vhost/common.sh@906 -- # xtrace_disable
[2022-05-17T06:07:41.496Z]  08:07:41	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
[2022-05-17T06:07:41.496Z]  08:07:41	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
[2022-05-17T06:07:41.496Z]  08:07:41	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
[2022-05-17T06:07:41.496Z]  08:07:41	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
[2022-05-17T06:07:41.496Z]  08:07:41	-- common/autotest_common.sh@19 -- # set +x
[2022-05-17T06:07:41.496Z] INFO: Waiting for VMs to boot
[2022-05-17T06:07:41.496Z] INFO: waiting for VM0 (/root/vhost_test/vms/0)
[2022-05-17T06:07:41.496Z] kill: sending signal to 1943455 failed: No such process
[2022-05-17T06:07:41.496Z] WARN: VM 0 is not running
[2022-05-17T06:07:41.496Z] WARN: ================
[2022-05-17T06:07:41.496Z] WARN: QEMU LOG:
[2022-05-17T06:07:41.496Z] WARN: VM LOG:
[2022-05-17T06:07:41.496Z] WARN: SEABIOS LOG:
[2022-05-17T06:07:41.496Z] WARN: ================
[2022-05-17T06:07:41.496Z]  08:07:41	-- vhost/common.sh@934 -- # xtrace_enable
[2022-05-17T06:07:41.496Z]  08:07:41	-- vhost/common.sh@935 -- # return 1
[2022-05-17T06:07:41.496Z]   08:07:41	-- vhost_boot/vhost_boot.sh@101 -- # err_clean '' 101
[2022-05-17T06:07:41.496Z]   08:07:41	-- vhost_boot/vhost_boot.sh@14 -- # trap - ERR
[2022-05-17T06:07:41.496Z]   08:07:41	-- vhost_boot/vhost_boot.sh@15 -- # print_backtrace
[2022-05-17T06:07:41.496Z]   08:07:41	-- common/autotest_common.sh@998 -- # [[ ehxBET =~ e ]]
[2022-05-17T06:07:41.496Z]   08:07:41	-- common/autotest_common.sh@1000 -- # args=("${BASH_ARGV[@]}")
[2022-05-17T06:07:41.496Z]   08:07:41	-- common/autotest_common.sh@1000 -- # local args
[2022-05-17T06:07:41.496Z]   08:07:41	-- common/autotest_common.sh@1002 -- # xtrace_disable
[2022-05-17T06:07:41.496Z]   08:07:41	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
[2022-05-17T06:07:41.496Z]   08:07:41	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
[2022-05-17T06:07:41.496Z]   08:07:41	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
[2022-05-17T06:07:41.496Z]   08:07:41	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
[2022-05-17T06:07:41.496Z]   08:07:41	-- common/autotest_common.sh@19 -- # set +x
[2022-05-17T06:07:41.496Z] ========== Backtrace start: ==========
[2022-05-17T06:07:41.496Z] 
[2022-05-17T06:07:41.496Z] in /var/jenkins/workspace/vhost-vs-qemu/spdk/test/vhost/vhost_boot/vhost_boot.sh:15 -> err_clean([""],["101"])
[2022-05-17T06:07:41.496Z]      ...
[2022-05-17T06:07:41.496Z]    10  	rpc_py="$rootdir/scripts/rpc.py -s $(get_vhost_dir 0)/rpc.sock"
[2022-05-17T06:07:41.496Z]    11  	vm_no="0"
[2022-05-17T06:07:41.496Z]    12  	
[2022-05-17T06:07:41.496Z]    13  	function err_clean() {
[2022-05-17T06:07:41.496Z]    14  		trap - ERR
[2022-05-17T06:07:41.496Z] => 15  		print_backtrace
[2022-05-17T06:07:41.496Z]    16  		set +e
[2022-05-17T06:07:41.496Z]    17  		error "Error on $1 $2"
[2022-05-17T06:07:41.496Z]    18  		vm_kill_all
[2022-05-17T06:07:41.496Z]    19  		$rpc_py vhost_scsi_controller_remove_target naa.vhost_vm.$vm_no 0
[2022-05-17T06:07:41.496Z]    20  		$rpc_py vhost_delete_controller naa.vhost_vm.$vm_no
[2022-05-17T06:07:41.496Z]      ...
[2022-05-17T06:07:41.496Z] in /var/jenkins/workspace/vhost-vs-qemu/spdk/test/vhost/vhost_boot/vhost_boot.sh:101 -> main(["--vm_image=/root/spdk_dependencies/spdk_test_image.qcow2"])
[2022-05-17T06:07:41.496Z]      ...
[2022-05-17T06:07:41.496Z]    96  	timing_exit create_vhost_controller
[2022-05-17T06:07:41.496Z]    97  	
[2022-05-17T06:07:41.496Z]    98  	timing_enter setup_vm
[2022-05-17T06:07:41.496Z]    99  	vm_setup --disk-type=spdk_vhost_scsi --force=$vm_no --disks="vhost_vm" --spdk-boot="vhost_vm"
[2022-05-17T06:07:41.496Z]    100 	vm_run $vm_no
[2022-05-17T06:07:41.497Z] => 101 	vm_wait_for_boot 300 $vm_no
[2022-05-17T06:07:41.497Z]    102 	timing_exit setup_vm
[2022-05-17T06:07:41.497Z]    103 	
[2022-05-17T06:07:41.497Z]    104 	start_part_sector=0 drive_size=0
[2022-05-17T06:07:41.497Z]    105 	while IFS=":" read -r id start end _; do
[2022-05-17T06:07:41.497Z]    106 		start=${start%s} end=${end%s}
[2022-05-17T06:07:41.497Z]      ...
[2022-05-17T06:07:41.497Z] 
[2022-05-17T06:07:41.497Z] ========== Backtrace end ==========
[2022-05-17T06:07:41.497Z]   08:07:41	-- common/autotest_common.sh@1038 -- # xtrace_enable
[2022-05-17T06:07:41.497Z]   08:07:41	-- common/autotest_common.sh@1039 -- # return 0
[2022-05-17T06:07:41.497Z]   08:07:41	-- vhost_boot/vhost_boot.sh@16 -- # set +e
[2022-05-17T06:07:41.497Z]   08:07:41	-- vhost_boot/vhost_boot.sh@17 -- # error 'Error on  101'
[2022-05-17T06:07:41.497Z]   08:07:41	-- vhost/common.sh@77 -- # echo ===========
[2022-05-17T06:07:41.497Z] ===========
[2022-05-17T06:07:41.497Z]   08:07:41	-- vhost/common.sh@78 -- # message ERROR 'Error on  101'
[2022-05-17T06:07:41.497Z]   08:07:41	-- vhost/common.sh@55 -- # local verbose_out
[2022-05-17T06:07:41.497Z]   08:07:41	-- vhost/common.sh@56 -- # false
[2022-05-17T06:07:41.497Z]   08:07:41	-- vhost/common.sh@57 -- # verbose_out=
[2022-05-17T06:07:41.497Z]   08:07:41	-- vhost/common.sh@64 -- # local msg_type=ERROR
[2022-05-17T06:07:41.497Z]   08:07:41	-- vhost/common.sh@65 -- # shift
[2022-05-17T06:07:41.497Z]   08:07:41	-- vhost/common.sh@66 -- # echo -e 'ERROR: Error on  101'
[2022-05-17T06:07:41.497Z] ERROR: Error on  101
[2022-05-17T06:07:41.497Z]   08:07:41	-- vhost/common.sh@79 -- # echo ===========
[2022-05-17T06:07:41.497Z] ===========
```

**Comment by changpe1** [comment] 2022-05-25 08:40
let me take a look of this issue.

**Comment by karlatec** [comment] 2022-05-25 09:03
@changpe1 could you check if this is something to fix on our side, or should we raise an issue in Qemu bugtracker?

**Comment by changpe1** [comment] 2022-05-25 09:19
> @changpe1 could you check if this is something to fix on our side, or should we raise an issue in Qemu bugtracker?

I already root caused this issue, and I will provide fixes ASAP.

**Comment by changpe1** [comment] 2022-05-25 09:21
QEMU does has a bug, but it's not critical, the fact is that QEMU requires vhost-scsi in SPDK to support VHOST_USER_PROTOCOL_F_CONFIG as a mandatory option, so the big fix is in SPDK.

**Comment by karlatec** [comment] 2022-05-25 09:23
Great, thank you!

**Comment by changpe1** [comment] 2022-05-26 00:50
Here are the fix patches for QEMU, I investigated the QEMU vhost-user-scsi driver, it's OK for SPDK not to support VHOST_USER_PROTOCOL_F_CONFIG, because the driver itself doesn't allow to change configuration space(mainly for CDB_SIZE and SENSE_SIZE in the PCI configuration space), so this definitely is a QEMU bug.

https://lists.gnu.org/archive/html/qemu-devel/2022-05/msg05040.html
https://lists.gnu.org/archive/html/qemu-devel/2022-05/msg05039.html

**Comment by tomzawadzki** [comment] 2022-06-14 11:26
Thanks @changpe1 ! Patches linked are now part of the upstream QEMU.
If there any change on SPDK you've wanted to do regarding this issue, or can it be closed ?

**Comment by changpe1** [comment] 2022-06-14 14:02
> Thanks @changpe1 ! Patches linked are now part of the upstream QEMU. Are there any changes on SPDK you've wanted to do regarding this issue, or can it be closed ?

No patches are required from SPDK side, I think we can close this issue.

**Closed as completed** 2022-06-28 12:05 UTC
Labels: 3rd party issue, Patches out for review
