### ISSUE TITLE
"cpl does not map to outstanding cmd" errors or I/O hangs while running fio workload with GCP NVMe SSDs backend

### ISSUE THREAD

**Issue by rakeshranjan-gh** [spdk/spdk#1828] opened 2021-03-09 18:24 UTC
Hitting "cpl does not map to outstanding cmd" error or I/O hangs while running fio workload with GCP Local NVMe SSD.

kernel:Disabling IRQ #11
[2021-03-06 03:50:36.970514] nvme_pcie_common.c: 830:nvme_pcie_qpair_process_completions: ERROR: cpl does not map to outstanding cmd
[2021-03-06 03:50:36.970590] nvme_qpair.c: 455:spdk_nvme_print_completion: NOTICE: SUCCESS (00/00) qid:6 cid:176 cdw0:0 sqhd:0003 p:0 m:0 dnr:0

## Expected Behavior

We should see any I/O hang while running fio workload.

## Current Behavior

Hitting I/O hang while running fio workload

## Steps to Reproduce

1. One SPDK/DPDK primary and 4 secondary processes
2. 4 GCP Local NVMe SSDs (4 namespaces against a single controller), each being owned by a secondary process
3. Each secondary process creates/allocates an I/O queue pair against the shared controller 
4. Run I/O load within each secondary process and cpl error is observed after running it for some time. Just after seeing the cpl error, application I/O hang is observed.

## Context (Environment including OS version, SPDK version, etc.)

Environment:

- GCP Instance running with CentOS 8.2 and UIO driver. 
-  SPDK version v20.04, v20.10
- 4 Local SSD attached to the instance
- 4 SPDK/DPDK secondary process, each process owns a  namespace and allocates one I/O queue pair against that namespace

**Comment by jimharris** [comment] 2021-03-09 18:30
Hi @rakeshranjan-gh,

Can you provide more specifics on the steps to reproduce?  For example, fio config files, exact command lines used for the primary process, are you using bdev or nvme fio plugin, etc.

Does it require both a primary and secondary process to reproduce?  If yes, does it require 4 SSDs and 4 secondary processes to reproduce?  Anything you can do to reduce the scope of the problem would be helpful.

Thanks,

Jim

**Comment by rakeshranjan-gh** [comment] 2021-03-09 18:50
Hi @jimharris ,

Thanks for taking a look at this! Actually I don't have exact set of steps without our virtualization stack, which is using SPDK nvme driver and nvmf_tgt and exporting a pseudo volume. Let me see if I can find out a way to reproduce this issue without our virtualization stack in picture. I can try to simulate a primary process which only probes the controller and a secondary process which owns the controller and associated namespaces. Allocate just one I/O queue pair and pump the random write I/Os. 

One ask, in order to debug this issue further in my environment what all instrumentation I can do to find out what is causing the cpl error.

Thanks,
Rakesh

**Comment by jimharris** [comment] 2021-03-10 15:20
Hi @rakeshranjan-gh,

OK. It will be important to have reproduction steps that do not require your virtualization stack.  Otherwise it will be almost impossible for anyone to help debug the issue.

This issue will require some very careful debugging. The error message indicates that the controller completed an I/O with a cid tag that the driver does not think is valid. It could be a bug with the GCP implementation or a bug with how your secondary processes are using/sharing NVMe I/O queues.

Please also provide details on whether these errors are specific to GCP, or whether you also see them on bare metal with physical PCIe SSDs.

Thanks,

Jim

**Comment by rakeshranjan-gh** [comment] 2021-03-10 17:36
Hi @jimharris ,

Thanks for your input! As usual, I truly appreciate all of your help! We will work on the problem reproduction with SPDK and GCP stack in place. 

With the same build, we are not seeing this cpl error on bare metal nodes, where it is using physical PCIe SSDs. On Bare metal nodes, we have verified against both configuration i.e. a single controller with multiple namespaces as well as a single controller with single namespace. This issue is seen only when we run it on GCP using CentOS 8.2 instance provisioned with 4 Local SSD drives using NVMe interface. 

Thanks,
Rakesh

**Comment by rakeshranjan-gh** [comment] 2021-03-11 21:42
Hi @jimharris ,

After we applied the following SPDK patch, we didn't see the fio hang. Could you please verify this from your end?

`diff --git a/lib/nvme/nvme_pcie_common.c b/lib/nvme/nvme_pcie_common.c
index 0ef56cb9e..373d1c48c 100644
--- a/lib/nvme/nvme_pcie_common.c
+++ b/lib/nvme/nvme_pcie_common.c
@@ -586,6 +586,11 @@ nvme_pcie_qpair_submit_tracker(struct spdk_nvme_qpair *qpair, struct nvme_tracke
                nvme_pcie_copy_command(&pqpair->cmd[pqpair->sq_tail], &req->cmd);
        }

+    spdk_mb();

        if (spdk_unlikely(++pqpair->sq_tail == pqpair->num_entries)) {
                pqpair->sq_tail = 0;
        }`

Thanks,
Rakesh

**Comment by jimharris** [comment] 2021-03-11 22:14
Hi @rakeshranjan-gh,

I'm not able to verify this patch, since I'm still not able to reproduce any fio hangs.  Have you been able to create a reproducible test case that you can share?

This patch would be a big pessimization to the main I/O path for the nvme driver.  We cannot even consider merging it without a reproducible test case and full root cause on why it fixes your I/O hangs.

-Jim

**Comment by rakeshranjan-gh** [comment] 2021-03-12 14:57
Hi @jimharris ,

Thanks for your comment! No, I didn't get a chance to reproduce the I/O hang issue just with SPDK and GCP Local SSD NVMe devices. We instrumented spdk nvme driver code to see what is happening with the cpl and tracker. Based on the instrumentation log, we noticed a duplicate completion against a cid whereas there is no  pending tracker for that cid. For a pending tracker, there was no completion call against the cid associated with tracker. After adding the memory barrier call (as mentioned in the previous comment), just after queuing the nvme request into submission queue, we didn't see any I/O hang. We will try to learn more about the reason for cpl being called twice against a cid and no completion against the pending cid.  

I will update on the problem reproduction without our virtualization layer as soon that is done. Meanwhile since problem is being reproduced with our virtualization stack so trying to learn more about the duplicate completion call. 

Thanks,
Rakesh

**Comment by jimharris** [comment] 2021-04-26 23:08
Marking as third party issue for now, since there are other known issues with GCP's NVMe implementation and waiting for a reproducible test case with upstream SPDK.

**Comment by jimharris** [comment] 2021-05-17 20:11
Hi @rakeshranjan-gh,

Any update on this issue?  If not, let's close it for now, and you can reopen it once you're able to demonstrate the problem in a way that can be shared with the SPDK community and GCP.

Thanks,

-Jim

**Comment by rakeshranjan-gh** [comment] 2021-05-17 22:55
Hi @jimharris ,

Sorry for the delay in my response! Actually we didn't get a chance to reproduce this issue without proprietary storage stack in place. Couldn't reproduce the exact same issue using only SPDK code base. We checked the linux kernel driver source code and there also it uses memory barrier while submitting request into submission queue. At this moment, all I see that after applying the above mentioned fix, we never encountered this issue in last 2 months. 

Linux driver code snippet:

`
#define build_mmio_write(name, size, type, reg, barrier) \
static inline void name(type val, volatile void __iomem *addr) \
{ asm volatile("mov" size " %0,%1": :reg (val), \
"m" (*(volatile type __force *)addr) barrier); }



build_mmio_write(writeb, "b", unsigned char, "q", :"memory")
build_mmio_write(writew, "w", unsigned short, "r", :"memory")
build_mmio_write(writel, "l", unsigned int, "r", :"memory")


static void __nvme_submit_cmd(struct nvme_queue *nvmeq,
                                                struct nvme_command *cmd)
{
        u16 tail = nvmeq->sq_tail;

        if (nvmeq->sq_cmds_io)
                memcpy_toio(&nvmeq->sq_cmds_io[tail], cmd, sizeof(*cmd));
        else
                memcpy(&nvmeq->sq_cmds[tail], cmd, sizeof(*cmd));

        if (++tail == nvmeq->q_depth)
                tail = 0;
        writel(tail, nvmeq->q_db);
        nvmeq->sq_tail = tail;
}`

I would request you to take proper action/decision as per your understanding since we couldn't reproduce this issue without proprietary storage stack which leverages SPDK. 

Thanks,
Rakesh

**Comment by jimharris** [comment] 2021-05-17 23:27
Thanks for the update @rakeshranjan-gh.  Your explanation here led me down a new path.  Could you revert your local memory barrier patch and try https://review.spdk.io/gerrit/c/spdk/spdk/+/7905 instead?

I think we are missing a barrier but only in the shadow doorbell path - this patch will localize the extra barrier to only that path.

**Comment by rakeshranjan-gh** [comment] 2021-05-18 14:07
Hi @jimharris ,

Sure, we will try your patch "https://review.spdk.io/gerrit/c/spdk/spdk/+/7905" and will update you as soon as it's completed. Thanks for your help on this!

Thanks,
Rakesh

**Comment by jimharris** [comment] 2021-06-07 23:37
This patch has been merged, so closing this issue.

@rakeshranjan-gh, would still appreciate it if you could re-run your tests with this patch and confirm.  Please report back your results, and we can re-open if you still see any issues.

**Closed by jimharris** 2021-06-07 23:37 UTC
Labels: 3rd party issue, Waiting on Submitter

**Comment by rakeshranjan-gh** [comment] 2021-06-08 14:03
Thanks a lot @jimharris ! I will update as soon as I get a chance to verify this patch in our environment. Currently getting busy with other high priority items hence couldn't get chance to spend some cycles on this but will update here as soon as I get some time to verify this patch. Thanks once again!
