### ISSUE TITLE
Inconsistent results from spdk perf

### ISSUE THREAD

**Issue by ssampath** [spdk/spdk#1514] opened 2020-07-28 17:07 UTC
SPDK perf reports inconsistent results when performing random read/write test

## Expected Behavior

Report consistent result (even though latency between runs is different)

## Current Behavior

**_Run 1:_**

[root@SudheGary2 examples]# ./perf -o 4096 -w randrw  -M 70 -r 'trtype:RDMA adrfam:IPv4 traddr:12.12.12.201 trsvcid:4420' -q 8 -t 120 -c 0xff
Starting SPDK v20.07-pre git sha1 ed2a57a35 / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0xff --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid15357 ]
EAL: No available hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
Attached to NVMe over Fabrics controller at 12.12.12.201:4420: nqn.2016-06.io.spdk:S3VJNA0M835307
Associating RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 with lcore 7
Associating RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 with lcore 6
Associating RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 with lcore 5
Associating RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 with lcore 4
Associating RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 with lcore 3
Associating RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 with lcore 2
Associating RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 with lcore 1
Associating RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 with lcore 0
Initialization complete. Launching workers.
[2020-07-27 21:32:08.377488] nvme_rdma.c:1103:nvme_rdma_connect: *ERROR*: RDMA connect error -99
[2020-07-27 21:32:08.377699] nvme_rdma.c:1334:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
ERROR: unable to connect I/O qpair.
ERROR: init_ns_worker_ctx() failed
                                                                                                                          Latency(us)
Device Information                                                                    :       IOPS      MiB/s    Average        min        max
RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 from core  7:    8377.30      32.72     984.99      55.47 8449801.78
RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 from core  6:    8892.88      34.74     907.54      64.86 8593340.62
RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 from core  5:   13557.52      52.96     590.02      60.03 4295221.62
RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 from core  4:    1414.54       5.53    6055.56      84.70 12182744.99
RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 from core  3:   11340.79      44.30     705.36      55.05 8541475.67
RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 from core  1:   10048.31      39.25     815.96      63.84 4297519.72
RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 from core  0:    8748.39      34.17     914.43      55.94 6972754.37
Total                                                                                 :   62379.73     243.67     915.12      55.05 12182744.99

**_Run 2:_**

[root@SudheGary2 examples]# ./perf -o 4096 -w randrw  -M 70 -r 'trtype:RDMA adrfam:IPv4 traddr:12.12.12.201 trsvcid:4420' -q 8 -t 120 -c 0xff
Starting SPDK v20.07-pre git sha1 ed2a57a35 / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0xff --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid15785 ]
EAL: No available hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
Attached to NVMe over Fabrics controller at 12.12.12.201:4420: nqn.2016-06.io.spdk:S3VJNA0M835307
Associating RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 with lcore 7
Associating RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 with lcore 6
Associating RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 with lcore 5
Associating RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 with lcore 4
Associating RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 with lcore 3
Associating RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 with lcore 2
Associating RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 with lcore 1
Associating RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 with lcore 0
Initialization complete. Launching workers.
[2020-07-27 21:34:47.014186] nvme_rdma.c:1103:nvme_rdma_connect: *ERROR*: RDMA connect error -99
[2020-07-27 21:34:47.014347] nvme_rdma.c:1334:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
ERROR: unable to connect I/O qpair.
ERROR: init_ns_worker_ctx() failed
                                                                                                                          Latency(us)
Device Information                                                                    :       IOPS      MiB/s    Average        min        max
RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 from core  7:    8312.27      32.47     975.27      53.77 8584134.92
RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 from core  6:    8699.39      33.98     955.02      54.31 8370963.62
RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 from core  5:   11535.01      45.06     693.49      52.32 6575800.17
RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 from core  4:    1838.60       7.18    4407.10      79.60 12249378.71
RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 from core  3:   11113.09      43.41     719.81      52.37 6856916.42
RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 from core  2:   11625.02      45.41     699.38      55.45 7403770.94
RDMA (addr:12.12.12.201 subnqn:nqn.2016-06.io.spdk:S3VJNA0M835307) NSID 1 from core  0:    8888.07      34.72     900.05      64.08 4297613.15
Total                                                                                 :   62011.46     242.23     913.48      52.32 12249378.71

**_Some observations:_**

- I see 'lcore 4' always has the lowest IOPS, higher latency.  However, the RDMA connect error between the two trials occurred on 'lcore1 and lcore2' respectively.

- I did not see the RDMA connect error when I specified '-M 60' instead of '-M 70' in the perf commandline above.

## Steps to Reproduce

1. Export a NVMe target over the fabric.  The target system had 8 cores.  Run 'nvmf_tgt -m 0xff'
2. Run 'perf' from the client (also with 8 cores).  Perf command line used : 
(perf -o 4096 -w randrw -M 70 -r 'trtype:RDMA adrfam:IPv4 traddr:12.12.12.201 trsvcid:4420' -q 8 -t 10 -c 0xff)
3.
4.

## Context (Environment including OS version, SPDK version, etc.)

OS Version (Client) : Linux SudheGary2 4.9.78 #1 SMP Thu Jan 25 08:34:18 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
OS Version (Target): Linux sudhekvtarget 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

SPDK Version (Target):
Starting SPDK v20.07-pre git sha1 03fe6a7 / DPDK 20.05.0 initialization...

SPDK Version (Client):
Starting SPDK v20.07-pre git sha1 ed2a57a35 / DPDK 19.11.2 initialization...

**Comment by spdkci** [comment] 2020-07-28 20:04
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_23237.html

**Comment by Comphix** [comment] 2020-07-31 07:12
@ssampath , on the target side, how many device connectted to NVMe-oF Target?

"Export a NVMe target over the fabric"

**Comment by ssampath** [comment] 2020-07-31 18:35
Just one NVMe device.

**Comment by optimistyzy** [comment] 2020-08-18 03:01
@ssampath   in your both running:

"[2020-07-27 21:34:47.014186] nvme_rdma.c:1103:nvme_rdma_connect: ERROR: RDMA connect error -99
[2020-07-27 21:34:47.014347] nvme_rdma.c:1334:_nvme_rdma_ctrlr_connect_qpair: ERROR: Unable to connect the rqpair"

It seems that one connections fails, this may be root cause of the performance is not consistent.

**Comment by ssampath** [comment] 2020-08-19 04:10
Hmm..Not sure if I understand your comment above.  There is I/Os statistics being reported.  You mean the connection across one core is lost (core #2 in trial 1, core #1 in trial 2) given that the core-mask I specified is 0xff.

**Comment by Comphix** [comment] 2020-08-31 07:35
@ssampath , could you also have a try with NULL bdev at the SPDK NVMe-oF Target side instead of using the NVMe Bdev? This may help to narrow down the issue.

**Comment by jimharris** [comment] 2020-11-02 16:54
Closing issue.  @ssampath if you have a chance to try again with suggestion from @Comphix, please reopen this issue.

**Closed by jimharris** 2020-11-02 16:54 UTC
Labels: Sighting, Waiting on Submitter
