### ISSUE TITLE
[nvmf_multipath] wait for the io to switch to second port

### ISSUE THREAD

**Issue by mgerdts** [spdk/spdk#2869] opened 2023-01-13 05:06 UTC
# CI Intermittent Failure

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/95227/archive/nvmf-tcp-vg-autotest/build.log

## Execution failed at

```
00:17:17.508  ========== Backtrace start: ==========
00:17:17.508  
00:17:17.508  in test/nvmf/host/multipath.sh:62 -> confirm_io_on_port(["optimized"],["4421"])
00:17:17.508       ...
00:17:17.508     57  		dtrace_pid=$!
00:17:17.508     58  		sleep 6
00:17:17.508     59  		active_port=$($rpc_py nvmf_subsystem_get_listeners $NQN | jq -r '.[] | select (.ana_states[0].ana_state=="'$1'") | .address.trsvcid')
00:17:17.508     60  		cat $testdir/trace.txt
00:17:17.508     61  		port=$(cut < $testdir/trace.txt -d ']' -f1 | awk '$1=="@path['$NVMF_FIRST_TARGET_IP'," {print $2}' | sed -n '1p')
00:17:17.508  => 62  		[[ "$active_port" == "$port" ]]
00:17:17.508     63  		[[ "$port" == "$2" ]]
00:17:17.508     64  		kill $dtrace_pid
00:17:17.508     65  		rm -f $testdir/trace.txt
00:17:17.508     66  	}
00:17:17.508     67  	
00:17:17.508       ...
00:17:17.508  in test/nvmf/host/multipath.sh:105 -> main(["--transport=tcp"])
00:17:17.508       ...
00:17:17.508     100 	$rpc_py nvmf_subsystem_add_listener $NQN -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_SECOND_PORT
00:17:17.508     101 	$rpc_py nvmf_subsystem_listener_set_ana_state $NQN -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_SECOND_PORT -n optimized
00:17:17.508     102 	
00:17:17.508     103 	# wait for the io to switch to second port
00:17:17.508     104 	sleep 2
00:17:17.508  => 105 	confirm_io_on_port "optimized" $NVMF_SECOND_PORT
00:17:17.508     106 	
00:17:17.508     107 	wait $rpc_pid
00:17:17.508     108 	cat $testdir/try.txt
00:17:17.508     109 	
00:17:17.508     110 	killprocess $bdevperf_pid
00:17:17.508       ...
```

**Comment by spdkci** [comment] 2023-01-13 05:09
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_95227.html

**Comment by Comphix** [comment] 2023-01-13 06:30
Looks like duplicate of issue #2865

**Closed by Comphix** 2023-01-13 06:30 UTC
Labels: Intermittent Failure

**Comment by spdkci** [comment] 2023-02-27 09:34
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_99200.html

**Comment by spdkci** [comment] 2023-04-14 08:40
Another instance of this failure. Reported by @m-spiewak. log: https://ci.spdk.io/public_build/autotest-per-patch_101841.html
