### ISSUE TITLE
using ~ in --with-fio path breaks configure

### ISSUE THREAD

**Issue by tmakatos** [spdk/spdk#2487] opened 2022-04-26 16:16 UTC
Using master (ac7b9b7c6), using  '~' in the path supplied to `--with-fio` fails without an obvious error:
```
# ./configure  --disable-tests --disable-unit-tests --with-fio=~/src/fio --without-isal --without-crypto
Notice: ISA-L, compression & crypto require NASM version 2.14 or newer. Turning off default ISA-L and crypto features.

Configuration failed
```
While using a full path works fine:
```
# realpath ~/src/fio
/root/src/fio
# ./configure  --disable-tests --disable-unit-tests --with-fio=/root/src/fio --without-isal --without-crypto
...
Type 'make' to build.
```

**Comment by mikeBashStuff** [comment] 2022-04-26 16:39
This happens because `~` is passed as a literal to `./confgure` - this is actually expected as what happens follows the rules of ~ expansion in bash (any character preceding ~ will prevent the expansion (`--with-fio=~/foo`)). So considering the way how cmdline is parsed by ./configure, we would need to actually eval the rhs of the argument (e.g. `foo=--with-fio=~/fio; eval "foo=${foo#*=}"`) to get the `$HOME` in place. But that's not really the nicest  way.

I will try to figure out something simple to make sure we don't need to change the entire way how ./configure picks up its options to support this (because why one would be to use long options like `--with-fio ~/fio` instead, so dropping the use of `=` altogether).

**Comment by tmakatos** [comment] 2022-04-26 16:41
Didn't expect it to be that complicated! I guess at least printing an error message such as "can't find the fio directory you supplied" would help a bit.

**Comment by mikeBashStuff** [comment] 2022-04-26 16:48
This actually points out a slightly different problem - so in theory, `check_dir()` should say something but failure happens before it has a chance to run as errexit picks up on failing `readlink -f /this/path/does/not/exist` which runs first. So even `./configure --with-fio=/this/path/bad` will "silently" fail, i.e. we won't get a hint that the problem is with an actual path.

**Comment by mikeBashStuff** [comment] 2022-04-26 19:29
Here's a potential fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/12388

Tried to keep it as small as possible.

**Comment by ksztyber** [comment] 2022-05-19 08:16
Patch was merged, @tmakatos could you verify it works for you?

**Closed** 2022-05-19 13:39 UTC
Labels: enhancement, Patches out for review
