### ISSUE TITLE
[ubuntu18_vg_autotest] vagrant libvirt got undefined method `path' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1420] opened 2020-05-29 04:30 UTC
```
00:00:18.109  ++ grep -oP '(?<=refs/remotes/)origin/v.+(?=\))'
00:00:18.110  ++ head -1
00:00:18.261  + spdk_branch=
00:00:18.261  + [[ '' < origin/v20.04.x ]]
00:00:18.261  + cp -r /home/sys_sgci/spdk-20-04-ref/scripts/vagrant /var/jenkins/workspace/ubuntu18-vg-autotest/spdk/scripts
00:00:18.265  + trap 'cd ubuntu1804-libvirt; vagrant destroy -f' SIGTERM SIGINT EXIT
00:00:18.265  + cd /var/jenkins/workspace/ubuntu18-vg-autotest
00:00:18.265  + vagrant_start='./spdk/scripts/vagrant/create_vbox.sh -n 10 -s 12288 -x http://proxy-chain.intel.com:911 -p libvirt   --qemu-emulator=/usr/local/qemu/spdk-5.0.0/bin/qemu-system-x86_64   -b /var/lib/libvirt/images/backends/ex1-nvme.img,nvme,1'
00:00:18.266  + [[ ubuntu1804 =~ fedora ]]
00:00:18.266  + vagrant_start+=' -H -a -u -v ubuntu1804'
00:00:18.266  + ./spdk/scripts/vagrant/create_vbox.sh -n 10 -s 12288 -x http://proxy-chain.intel.com:911 -p libvirt --qemu-emulator=/usr/local/qemu/spdk-5.0.0/bin/qemu-system-x86_64 -b /var/lib/libvirt/images/backends/ex1-nvme.img,nvme,1 -H -a -u -v ubuntu1804
00:00:18.282  mkdir: created directory '/var/jenkins/workspace/ubuntu18-vg-autotest/ubuntu1804-libvirt'
00:00:18.285  /var/jenkins/workspace/ubuntu18-vg-autotest/ubuntu1804-libvirt /var/jenkins/workspace/ubuntu18-vg-autotest
00:00:19.225  vagrant-proxyconf already installed... skipping
00:00:21.433  Bringing machine 'default' up with 'libvirt' provider...
00:00:22.809  ==> default: Creating image (snapshot of base box volume).
00:00:22.914  /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_domain_volume.rb:37:in `call': undefined method `path' for nil:NilClass (NoMethodError)
00:00:22.914  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.914  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:00:22.914  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.914  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
00:00:22.914  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.914  	from /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/handle_box_image.rb:146:in `call'
00:00:22.914  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.914  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:00:22.914  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.914  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
00:00:22.914  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.914  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
00:00:22.914  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.914  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:00:22.914  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.914  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
00:00:22.914  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.914  	from /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/handle_storage_pool.rb:57:in `call'
00:00:22.914  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.914  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.915  	from /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:121:in `block in finalize_action'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builder.rb:116:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `block in run'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/util/busy.rb:19:in `busy'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `run'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/call.rb:53:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/box_check_outdated.rb:23:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.915  	from /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/vagrant-sshfs-1.3.4/lib/vagrant-sshfs/action_hostpath_fixup.rb:125:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.915  	from /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/vagrant-sshfs-1.3.4/lib/vagrant-sshfs/action_hostpath_fixup.rb:102:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builder.rb:116:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `block in run'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/util/busy.rb:19:in `busy'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `run'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/machine.rb:238:in `action_raw'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/machine.rb:209:in `block in action'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:615:in `lock'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/machine.rb:195:in `call'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/machine.rb:195:in `action'
00:00:22.915  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
00:00:22.981  + cd ubuntu1804-libvirt

```
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/15224/archive/ubuntu18-vg-autotest/build.log

## Execution failed at

00:00:22.914  /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_domain_volume.rb:37:in `call': undefined method `path' for nil:NilClass (NoMethodError)

**Comment by tomzawadzki** [comment] 2020-06-02 15:24
[Bug scrub] This looks as one time occurrence during VM maintenance on CI.

**Comment by tomzawadzki** [comment] 2020-06-16 11:40
As assessed on Bug Scrub, this was one time occurrence. Closing since it was not reproduced for two weeks.

**Closed by tomzawadzki** 2020-06-16 11:40 UTC
Labels: Infrastructure, Intermittent Failure
