### ISSUE TITLE
[vhost_boot] timed out waiting for vm to shut down

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#3264] opened 2024-02-15 10:13 UTC
Looks like qemu didn't stop before the timeout expired:
```
00:11:34.056    09:23:54	-- vhost/common.sh@370 -- # cat /root/vhost_test/vms/0/qemu.pid
00:11:34.056   09:23:54	-- vhost/common.sh@370 -- # vm_pid=1477690
00:11:34.056   09:23:54	-- vhost/common.sh@372 -- # /bin/kill -0 1477690
00:11:34.056   09:23:54	-- vhost/common.sh@373 -- # return 0
00:11:34.056   09:23:54	-- vhost/common.sh@497 -- # all_vms_down=0
00:11:34.056   09:23:54	-- vhost/common.sh@498 -- # break
00:11:34.056   09:23:54	-- vhost/common.sh@502 -- # [[ 0 == 1 ]]
00:11:34.056   09:23:54	-- vhost/common.sh@508 -- # (( timeo -= 1 ))
00:11:34.056    09:23:54	-- vhost/common.sh@508 -- # err_clean vm_shutdown_all 508
00:11:34.056    09:23:54	-- vhost_boot/vhost_boot.sh@18 -- # trap - ERR
00:11:34.056    09:23:54	-- vhost_boot/vhost_boot.sh@19 -- # print_backtrace
00:11:34.056    09:23:54	-- common/autotest_common.sh@1130 -- # [[ ehxBET =~ e ]]
00:11:34.056    09:23:54	-- common/autotest_common.sh@1132 -- # args=('508' 'vm_shutdown_all' '--vm_image=/var/spdk/dependencies/vhost/spdk_test_image.qcow2')
00:11:34.056    09:23:54	-- common/autotest_common.sh@1132 -- # local args
00:11:34.056    09:23:54	-- common/autotest_common.sh@1134 -- # xtrace_disable
00:11:34.316    09:23:54	-- common/autotest_common.sh@10 -- # set +x
00:11:34.316  ========== Backtrace start: ==========
00:11:34.316  
00:11:34.316  in /var/jenkins/workspace/vhost-phy-autotest/spdk/test/vhost/vhost_boot/vhost_boot.sh:508 -> err_clean(["vm_shutdown_all"],["508"])
00:11:34.316       ...
00:11:34.316  backtrace unavailable
00:11:34.316       ...
00:11:34.316  in /var/jenkins/workspace/vhost-phy-autotest/spdk/test/vhost/common.sh:508 -> vm_shutdown_all([])
00:11:34.316       ...
00:11:34.316     503 				notice "All VMs successfully shut down"
00:11:34.316     504 				xtrace_restore
00:11:34.316     505 				return 0
00:11:34.316     506 			fi
00:11:34.316     507 	
00:11:34.316  => 508 			((timeo -= 1))
00:11:34.316     509 			sleep 1
00:11:34.316     510 		done
00:11:34.316     511 	
00:11:34.316     512 		rm -rf $VM_DIR
00:11:34.316     513 	
00:11:34.316       ...
00:11:34.316  in /var/jenkins/workspace/vhost-phy-autotest/spdk/test/vhost/vhost_boot/vhost_boot.sh:136 -> main(["--vm_image=/var/spdk/dependencies/vhost/spdk_test_image.qcow2"])
00:11:34.316       ...
00:11:34.316     131 	vm_exec $vm_no "umount /mnt/sda${part_id}test; rm -rf /mnt/sda${part_id}test"
00:11:34.316     132 	alignment_offset=$(vm_exec $vm_no "cat /sys/block/sda/sda1/alignment_offset")
00:11:34.316     133 	echo "alignment_offset: $alignment_offset"
00:11:34.316     134 	timing_exit run_vm_cmd
00:11:34.316     135 	
00:11:34.316  => 136 	vm_shutdown_all
00:11:34.316     137 	
00:11:34.316     138 	timing_enter clean_vhost
00:11:34.316     139 	$rpc_py vhost_scsi_controller_remove_target naa.vhost_vm.$vm_no 0
00:11:34.316     140 	$rpc_py vhost_delete_controller naa.vhost_vm.$vm_no
00:11:34.316     141 	$rpc_py bdev_lvol_delete $lvb_u
```

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/117254/archive/vhost-phy-autotest_17660/build.log
https://ci.spdk.io/public_build/autotest-per-patch_117254.html

**Comment by spdkci** [comment] 2024-02-15 10:14
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_117254.html

**Comment by mikeBashStuff** [comment] 2024-02-15 15:45
This is awkward because there's no qemu around when `autotest_cleanup()` kicks in. I guess that's because its call to `vhost_reap()` finishes it off. 

There is some wonkiness going on while setting up the drive inside the testing VM which may have some bearing on VM's ability to  shutdown cleanly. But I would rather  stop being coy about the whole thing and replace `shutdown` with direct sysrq hit to kill the distro inside immediately (we are running there full-capable fedora instance so there's plenty of potential points of failure while gracefully shutting it down).

I've seen this only couple of times under nightly so it doesn't seem to be that frequent (hence low prio, will look into this next week).

**Comment by mikeBashStuff** [comment] 2024-03-22 12:00
I can't reliably reproduce this (i.e. at all) so considering the single report, will close this for now. If the issue pops again, feel free to reopen (will keep digging then).

**Comment by mikeBashStuff** [comment] 2024-04-29 15:53
Some debug series to try and narrow down the issue: https://review.spdk.io/gerrit/c/spdk/spdk/+/22993.  Hopefully this should help root cause the issue similarly to #3322.

**Comment by mikeBashStuff** [comment] 2024-06-28 08:26
Debug series merged, closing for now. When this resurfaces will pick it up again.

**Closed by mikeBashStuff** 2024-06-28 08:26 UTC
Labels: Intermittent Failure
