### ISSUE TITLE
[make] dpdk source file w/warning treated as error

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1774] opened 2021-01-28 15:55 UTC
Looks like junk in the source file??

00:02:47.489  /home/vagrant/spdk_repo/spdk/dpdk/kernel/linux/kni/kni_net.c:791:20: error: initialization of â€˜void (*)(struct net_device *, unsigned int)â€™ from incompatible pointer type â€˜void (*)(struct net_device *)â€™ [-Werror=incompatible-pointer-types]
00:02:47.489    .ndo_tx_timeout = kni_net_tx_timeout,

**Comment by spdkci** [comment] 2021-01-28 15:56
Another instance of this failure. Reported by @peluse. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_35456.html

**Comment by yidong0635** [comment] 2021-02-01 02:26
I have question that:
Do we need to filter this kind of error .incompatible-pointer-types was enable when gcc version >9 (install_qemu).
but for dpdk do we need to disable it?

**Comment by changpe1** [comment] 2021-02-04 04:33
@peluse let's keep this issue open for a while, some patches after rebase passed the failure VM.

**Comment by tomzawadzki** [comment] 2021-02-09 15:14
[Bug scrub] The issue has not been observed for over 12 days and since this is a build issue it should be reproducible more often if it was more than single occurrence. Closing as a one-time thing.

**Closed by tomzawadzki** 2021-02-09 15:14 UTC
Labels: Intermittent Failure
