### ISSUE TITLE
[nvme-phy-nightly-autotest] scheduler test "idle" failing due to not all threads becoming idle in time

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1761] opened 2021-01-25 08:33 UTC
## Current Behavior

"idle" test is failing for various nightly builds. 
https://ci.spdk.io/public_build/autotest-nightly_2287.html
https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_923.html

## Expected Behavior

Test should pass, obviously :)

## Possible Solution

I did not see it in per-patch tests, just nightly, so it's possible this could be related to nightly HW configuration.

## Steps to Reproduce

1. Check out `72eed604b lib/event: do not spawn a thread for each reactor` SPDK
2. Build SPDK with `./configure --enable-debug --enable-werror --with-rdma --with-idxd --with-fio=/usr/src/fio --with-iscsi-initiator --disable-unit-tests --with-nvme-cuse --with-ocf --enable-ubsan --enable-coverage --without-isal`
3. Run test `spdk/test/scheduler/idle.sh`
4. Results:
```
00:07:19.411  ************************************
00:07:19.411  START TEST idle
00:07:19.411  ************************************
00:07:19.412   23:05:30	# xtrace_enable
00:07:19.412   23:05:30	# /var/jenkins/workspace/nvme-phy-nightly-autotest/spdk/test/scheduler/idle.sh
00:07:19.479  * Purging old temporary test storage (/tmp/spdk.jmzAeu)
00:07:19.512  * Looking for test storage...
00:07:19.515  * Found test storage at /var/jenkins/workspace/nvme-phy-nightly-autotest/spdk/test/scheduler
00:07:19.516    23:05:30	# xtrace_enable
00:07:19.562   23:05:30	# source /var/jenkins/workspace/nvme-phy-nightly-autotest/spdk/test/scheduler/common.sh
00:07:19.562    23:05:30	# shopt -s nullglob extglob
00:07:19.562    23:05:30	# declare -r sysfs_system=/sys/devices/system
00:07:19.562    23:05:30	# declare -r sysfs_cpu=/sys/devices/system/cpu
00:07:19.562    23:05:30	# declare -r sysfs_node=/sys/devices/system/node
00:07:19.563   23:05:30	# trap 'killprocess "$spdk_pid"' EXIT
00:07:19.563   23:05:30	# idle
00:07:19.563   23:05:30	# local reactor_framework
00:07:19.563   23:05:30	# local reactors thread
00:07:19.563   23:05:30	# local cpusmask thread_cpumask
00:07:19.563   23:05:30	# local threads
00:07:19.563   23:05:30	# exec_under_dynamic_scheduler /var/jenkins/workspace/nvme-phy-nightly-autotest/spdk/build/bin/spdk_tgt -m 0x1e001e --main-core 1
00:07:19.564   23:05:30	# spdk_pid=50381
00:07:19.564   23:05:30	# waitforlisten 50381
00:07:19.564   23:05:30	# /var/jenkins/workspace/nvme-phy-nightly-autotest/spdk/build/bin/spdk_tgt -m 0x1e001e --main-core 1 --wait-for-rpc
00:07:19.564   23:05:30	# '[' -z 50381 ']'
00:07:19.564   23:05:30	# local rpc_addr=/var/tmp/spdk.sock
00:07:19.565   23:05:30	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
00:07:19.565  Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
00:07:19.565   23:05:30	# xtrace_disable
00:07:19.565   23:05:30	# '[' '' '!=' yes ']'
00:07:19.565   23:05:30	# PREV_BASH_OPTS=ehxBET
00:07:19.565   23:05:30	# [[ ehxBET == *\x* ]]
00:07:19.565   23:05:30	# XTRACE_DISABLED=yes
00:07:19.565   23:05:30	# set +x
00:07:19.565  [2021-01-24 23:05:30.763566] Starting SPDK v21.01-pre git sha1 72eed604b / DPDK 20.11.0 initialization...
00:07:19.565  [2021-01-24 23:05:30.763756] [ DPDK EAL parameters: [2021-01-24 23:05:30.763772] spdk_tgt [2021-01-24 23:05:30.763783] --no-shconf [2021-01-24 23:05:30.763793] -c 0x1e001e [2021-01-24 23:05:30.763803] --main-lcore=1 [2021-01-24 23:05:30.763820] --log-level=lib.eal:6 [2021-01-24 23:05:30.763830] --log-level=lib.cryptodev:5 [2021-01-24 23:05:30.763840] --log-level=user1:6 [2021-01-24 23:05:30.763850] --base-virtaddr=0x200000000000 [2021-01-24 23:05:30.763860] --match-allocations [2021-01-24 23:05:30.763870] --file-prefix=spdk_pid50381 [2021-01-24 23:05:30.763881] ]
00:07:19.575  EAL: No free hugepages reported in hugepages-2048kB
00:07:19.576  EAL: No available hugepages reported in hugepages-1048576kB
00:07:19.580  EAL: No legacy callbacks, legacy socket not created
00:07:19.608  [2021-01-24 23:05:30.821500] app.c: 538:spdk_app_start: *NOTICE*: Total cores available: 8
00:07:19.832  [2021-01-24 23:05:31.044871] reactor.c: 720:reactor_run: *NOTICE*: Reactor started on core 2
00:07:19.832  [2021-01-24 23:05:31.044958] reactor.c: 720:reactor_run: *NOTICE*: Reactor started on core 3
00:07:19.832  [2021-01-24 23:05:31.045163] reactor.c: 720:reactor_run: *NOTICE*: Reactor started on core 4
00:07:19.832  [2021-01-24 23:05:31.045185] reactor.c: 720:reactor_run: *NOTICE*: Reactor started on core 17
00:07:19.833  [2021-01-24 23:05:31.045209] reactor.c: 720:reactor_run: *NOTICE*: Reactor started on core 18
00:07:19.833  [2021-01-24 23:05:31.045288] reactor.c: 720:reactor_run: *NOTICE*: Reactor started on core 20
00:07:19.833  [2021-01-24 23:05:31.045232] reactor.c: 720:reactor_run: *NOTICE*: Reactor started on core 19
00:07:19.833  [2021-01-24 23:05:31.045299] reactor.c: 720:reactor_run: *NOTICE*: Reactor started on core 1
00:07:20.512   23:05:31	# xtrace_enable
00:07:20.512   23:05:31	# (( i == 0 ))
00:07:20.512   23:05:31	# return 0
00:07:20.512   23:05:31	# /var/jenkins/workspace/nvme-phy-nightly-autotest/spdk/scripts/rpc.py framework_set_scheduler dynamic
00:07:20.698  POWER: Env isn't set yet!
00:07:20.698  POWER: Attempting to initialise ACPI cpufreq power management...
00:07:20.698  POWER: File operations failed
00:07:20.698  POWER: Cannot set governor of lcore 1 to userspace
00:07:20.698  POWER: Attempting to initialise PSTAT power management...
00:07:20.708  POWER: Power management governor of lcore 1 has been set to performance successfully
00:07:20.720  POWER: Initialized successfully for lcore 1 power management
00:07:20.732  POWER: Power management governor of lcore 2 has been set to performance successfully
00:07:20.743  POWER: Initialized successfully for lcore 2 power management
00:07:20.755  POWER: Power management governor of lcore 3 has been set to performance successfully
00:07:20.767  POWER: Initialized successfully for lcore 3 power management
00:07:20.777  POWER: Power management governor of lcore 4 has been set to performance successfully
00:07:20.789  POWER: Initialized successfully for lcore 4 power management
00:07:20.803  POWER: Power management governor of lcore 17 has been set to performance successfully
00:07:20.816  POWER: Initialized successfully for lcore 17 power management
00:07:20.823  POWER: Power management governor of lcore 18 has been set to performance successfully
00:07:20.835  POWER: Initialized successfully for lcore 18 power management
00:07:20.856  POWER: Power management governor of lcore 19 has been set to performance successfully
00:07:20.867  POWER: Initialized successfully for lcore 19 power management
00:07:20.887  POWER: Power management governor of lcore 20 has been set to performance successfully
00:07:20.899  POWER: Initialized successfully for lcore 20 power management
00:07:20.910   23:05:32	# /var/jenkins/workspace/nvme-phy-nightly-autotest/spdk/scripts/rpc.py framework_start_init
00:07:21.065  [2021-01-24 23:05:32.278348] accel_engine.c: 692:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:07:21.287  [2021-01-24 23:05:32.499776] 'OCF Core' volume operations registered
00:07:21.294  [2021-01-24 23:05:32.507503] 'SPDK block device' volume operations registered
00:07:21.456   23:05:32	# local all_set
00:07:21.456   23:05:32	# xtrace_disable
00:07:21.456   23:05:32	# '[' no '!=' yes ']'
00:07:21.456   23:05:32	# PREV_BASH_OPTS=ehxBET
00:07:21.456   23:05:32	# [[ ehxBET == *\x* ]]
00:07:21.456   23:05:32	# XTRACE_DISABLED=yes
00:07:21.456   23:05:32	# set +x
00:07:21.691  SPDK cpumask: 1e001e Threads cpumask: 2
00:07:23.641  app_thread is idle
00:07:23.641  nvmf_tgt_poll_group_1 is idle
00:07:23.641  Waiting for nvmf_tgt_poll_group_2 to become idle
00:07:23.641  Waiting for nvmf_tgt_poll_group_3 to become idle
00:07:23.641  Waiting for nvmf_tgt_poll_group_4 to become idle
00:07:23.641  Waiting for nvmf_tgt_poll_group_17 to become idle
00:07:23.641  Waiting for nvmf_tgt_poll_group_18 to become idle
00:07:23.641  Waiting for nvmf_tgt_poll_group_19 to become idle
00:07:23.642  Waiting for nvmf_tgt_poll_group_20 to become idle
00:07:23.642  iscsi_poll_group_1 is idle
00:07:23.642  iscsi_poll_group_2 is idle
00:07:23.642  iscsi_poll_group_3 is idle
00:07:23.642  iscsi_poll_group_4 is idle
00:07:23.642  iscsi_poll_group_17 is idle
00:07:23.643  iscsi_poll_group_18 is idle
00:07:23.643  iscsi_poll_group_19 is idle
00:07:23.643  iscsi_poll_group_20 is idle
00:07:24.322  SPDK cpumask: 1e001e Threads cpumask: 1e001e
00:07:26.203  app_thread is idle
00:07:26.203  nvmf_tgt_poll_group_1 is idle
00:07:26.204  Waiting for nvmf_tgt_poll_group_2 to become idle
00:07:26.204  Waiting for nvmf_tgt_poll_group_3 to become idle
00:07:26.204  Waiting for nvmf_tgt_poll_group_4 to become idle
00:07:26.204  Waiting for nvmf_tgt_poll_group_17 to become idle
00:07:26.204  Waiting for nvmf_tgt_poll_group_18 to become idle
00:07:26.204  Waiting for nvmf_tgt_poll_group_19 to become idle
00:07:26.204  Waiting for nvmf_tgt_poll_group_20 to become idle
00:07:26.205  iscsi_poll_group_1 is idle
00:07:26.205  iscsi_poll_group_2 is idle
00:07:26.205  iscsi_poll_group_3 is idle
00:07:26.205  iscsi_poll_group_4 is idle
00:07:26.205  iscsi_poll_group_17 is idle
00:07:26.205  iscsi_poll_group_18 is idle
00:07:26.205  iscsi_poll_group_19 is idle
00:07:26.205  iscsi_poll_group_20 is idle
00:07:26.884  SPDK cpumask: 1e001e Threads cpumask: 1e001e
00:07:28.760  app_thread is idle
00:07:28.760  nvmf_tgt_poll_group_1 is idle
00:07:28.760  Waiting for nvmf_tgt_poll_group_2 to become idle
00:07:28.760  Waiting for nvmf_tgt_poll_group_3 to become idle
00:07:28.760  Waiting for nvmf_tgt_poll_group_4 to become idle
00:07:28.760  Waiting for nvmf_tgt_poll_group_17 to become idle
00:07:28.760  Waiting for nvmf_tgt_poll_group_18 to become idle
00:07:28.761  Waiting for nvmf_tgt_poll_group_19 to become idle
00:07:28.761  Waiting for nvmf_tgt_poll_group_20 to become idle
00:07:28.761  iscsi_poll_group_1 is idle
00:07:28.761  iscsi_poll_group_2 is idle
00:07:28.761  iscsi_poll_group_3 is idle
00:07:28.761  iscsi_poll_group_4 is idle
00:07:28.761  iscsi_poll_group_17 is idle
00:07:28.761  iscsi_poll_group_18 is idle
00:07:28.762  iscsi_poll_group_19 is idle
00:07:28.762  iscsi_poll_group_20 is idle
00:07:29.445  SPDK cpumask: 1e001e Threads cpumask: 1e001e
00:07:31.325  app_thread is idle
00:07:31.325  nvmf_tgt_poll_group_1 is idle
00:07:31.325  Waiting for nvmf_tgt_poll_group_2 to become idle
00:07:31.325  Waiting for nvmf_tgt_poll_group_3 to become idle
00:07:31.325  Waiting for nvmf_tgt_poll_group_4 to become idle
00:07:31.325  Waiting for nvmf_tgt_poll_group_17 to become idle
00:07:31.326  Waiting for nvmf_tgt_poll_group_18 to become idle
00:07:31.326  Waiting for nvmf_tgt_poll_group_19 to become idle
00:07:31.326  Waiting for nvmf_tgt_poll_group_20 to become idle
00:07:31.326  iscsi_poll_group_1 is idle
00:07:31.326  iscsi_poll_group_2 is idle
00:07:31.326  iscsi_poll_group_3 is idle
00:07:31.326  iscsi_poll_group_4 is idle
00:07:31.326  iscsi_poll_group_17 is idle
00:07:31.326  iscsi_poll_group_18 is idle
00:07:31.326  iscsi_poll_group_19 is idle
00:07:31.327  iscsi_poll_group_20 is idle
00:07:32.002  SPDK cpumask: 1e001e Threads cpumask: 1e001e
00:07:33.882  app_thread is idle
00:07:33.883  nvmf_tgt_poll_group_1 is idle
00:07:33.883  Waiting for nvmf_tgt_poll_group_2 to become idle
00:07:33.883  Waiting for nvmf_tgt_poll_group_3 to become idle
00:07:33.883  Waiting for nvmf_tgt_poll_group_4 to become idle
00:07:33.883  Waiting for nvmf_tgt_poll_group_17 to become idle
00:07:33.883  Waiting for nvmf_tgt_poll_group_18 to become idle
00:07:33.883  Waiting for nvmf_tgt_poll_group_19 to become idle
00:07:33.883  Waiting for nvmf_tgt_poll_group_20 to become idle
00:07:33.883  iscsi_poll_group_1 is idle
00:07:33.884  iscsi_poll_group_2 is idle
00:07:33.884  iscsi_poll_group_3 is idle
00:07:33.884  iscsi_poll_group_4 is idle
00:07:33.884  iscsi_poll_group_17 is idle
00:07:33.884  iscsi_poll_group_18 is idle
00:07:33.884  iscsi_poll_group_19 is idle
00:07:33.884  iscsi_poll_group_20 is idle
00:07:34.071  ========== Backtrace start: ==========
00:07:34.071  
00:07:34.071  in /var/jenkins/workspace/nvme-phy-nightly-autotest/spdk/test/scheduler/idle.sh:62 -> idle([])
00:07:34.072       ...
00:07:34.072     57  	
00:07:34.072     58  			printf 'SPDK cpumask: %x Threads cpumask: %x\n' "$spdk_cpusmask" "$cpusmask"
00:07:34.072     59  			thread_stats && ((cpusmask == spdk_cpusmask)) && all_set=1
00:07:34.072     60  		done
00:07:34.072     61  	
00:07:34.072  => 62  		((all_set == 1))
00:07:34.072     63  		xtrace_restore
00:07:34.072     64  	}
00:07:34.072     65  	
00:07:34.072     66  	idle
00:07:34.072       ...
00:07:34.072  in /var/jenkins/workspace/nvme-phy-nightly-autotest/spdk/test/scheduler/idle.sh:66 -> main([])
00:07:34.072       ...
00:07:34.072     61  	
00:07:34.072     62  		((all_set == 1))
00:07:34.072     63  		xtrace_restore
00:07:34.072     64  	}
00:07:34.072     65  	
00:07:34.072  => 66  	idle
00:07:34.072       ...
00:07:34.072  
00:07:34.072  ========== Backtrace end ==========
00:07:34.072  killing process with pid 50381
00:07:34.308  POWER: Power management governor of lcore 1 has been set back to powersave successfully
00:07:34.308  POWER: Power management of lcore 1 has exited from 'performance' mode and been set back to the original
00:07:34.308  POWER: Power management governor of lcore 2 has been set back to powersave successfully
00:07:34.308  POWER: Power management of lcore 2 has exited from 'performance' mode and been set back to the original
00:07:34.308  POWER: Power management governor of lcore 3 has been set back to powersave successfully
00:07:34.309  POWER: Power management of lcore 3 has exited from 'performance' mode and been set back to the original
00:07:34.309  POWER: Power management governor of lcore 4 has been set back to powersave successfully
00:07:34.309  POWER: Power management of lcore 4 has exited from 'performance' mode and been set back to the original
00:07:34.309  POWER: Power management governor of lcore 17 has been set back to powersave successfully
00:07:34.310  POWER: Power management of lcore 17 has exited from 'performance' mode and been set back to the original
00:07:34.310  POWER: Power management governor of lcore 18 has been set back to powersave successfully
00:07:34.310  POWER: Power management of lcore 18 has exited from 'performance' mode and been set back to the original
00:07:34.310  POWER: Power management governor of lcore 19 has been set back to powersave successfully
00:07:34.310  POWER: Power management of lcore 19 has exited from 'performance' mode and been set back to the original
00:07:34.310  POWER: Power management governor of lcore 20 has been set back to powersave successfully
00:07:34.310  POWER: Power management of lcore 20 has exited from 'performance' mode and been set back to the original
```

## Context (Environment including OS version, SPDK version, etc.)
SPDK `72eed604b lib/event: do not spawn a thread for each reactor` 
5.7.17-200.fc32.x86_64
gcc version 10.2.1 20200723 (Red Hat 10.2.1-1) (GCC)

**Comment by karlatec** [comment] 2021-01-25 08:33
@mikeBashStuff @Maciej-Szwed  fyi

**Comment by spdkci** [comment] 2021-01-25 10:00
Another instance of this failure. Reported by @mikeBashStuff. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_35142.html

**Comment by spdkci** [comment] 2021-01-25 11:31
Another instance of this failure. Reported by @mikeBashStuff. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_35149.html

**Comment by spdkci** [comment] 2021-01-25 18:14
Another instance of this failure. Reported by @tomzawadzki. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_35220.html

**Comment by mikeBashStuff** [comment] 2021-01-26 12:21
Ok, I managed to reproduce it, to some extent, by running stressors on the designated cpus, prior running the test. This is how idle|busy stats look on a first sample (so right after app is initialized) when the cpus are idle:

```
# thread name: idle busy
app_thread is idle: 2320385933 1953197518
nvmf_tgt_poll_group_1 is idle: 20602989 67690
nvmf_tgt_poll_group_2 is idle: 16376594 116852
nvmf_tgt_poll_group_3 is idle: 15108542 119486
nvmf_tgt_poll_group_4 is idle: 18638087 38716
nvmf_tgt_poll_group_25 is idle: 14787233 110370
nvmf_tgt_poll_group_26 is idle: 16419682 110268
nvmf_tgt_poll_group_27 is idle: 15363269 22314
nvmf_tgt_poll_group_28 is idle: 16180949 109138
iscsi_poll_group_1 is idle: 26452140 27674
iscsi_poll_group_2 is idle: 14430253 7240
iscsi_poll_group_3 is idle: 16019167 18100
iscsi_poll_group_4 is idle: 15839156 5844
iscsi_poll_group_25 is idle: 15554795 7256
iscsi_poll_group_26 is idle: 16234825 12596
iscsi_poll_group_27 is idle: 15311663 6300
iscsi_poll_group_28 is idle: 15748410 6250
```
Which is fine. However, if I stress each cpu thread so its load peaks to ~90% before starting the app, this is how first sample looks like:
```
# app name: idle busy
Waiting for app_thread to become idle: 7545918633 17274236355
nvmf_tgt_poll_group_1 is idle: 4743866391 157329
nvmf_tgt_poll_group_2 is idle: 16915069437 12734381079
nvmf_tgt_poll_group_3 is idle: 15237093594 12518578101
Waiting for nvmf_tgt_poll_group_4 to become idle: 6399042342 25985895579
Waiting for nvmf_tgt_poll_group_25 to become idle: 15813882381 16743082281
Waiting for nvmf_tgt_poll_group_26 to become idle: 15025902975 15546593919
Waiting for nvmf_tgt_poll_group_27 to become idle: 13509358380 15434418234
Waiting for nvmf_tgt_poll_group_28 to become idle: 15285079065 15470902365
iscsi_poll_group_1 is idle: 2857688046 36075
iscsi_poll_group_2 is idle: 2934790575 102606
iscsi_poll_group_3 is idle: 4810368141 65250
iscsi_poll_group_4 is idle: 1378956648 54942
iscsi_poll_group_25 is idle: 1649000640 66684
iscsi_poll_group_26 is idle: 1658621628 40023
iscsi_poll_group_27 is idle: 2726975001 31302
iscsi_poll_group_28 is idle: 2712176889 291093537
```
Number of the busy ticks is far greater than the idle ticks. Now, when test iterates further, each sample shows increase in idle ticks and busy ticks remain at their value from the first sample. However, the difference between busy|idle here is so big, e.g. `nvmf_tgt_poll_group_4 to idle: 6399042342 busy: 25985895579`, that the number of idle ticks have no chance of surpassing the busy ones within the time the test is running under.

My question would be, why the number of busy ticks, for the spdk thread, is so different for those two cases? Is it expected? This looks like the cpu speed was a core factor in determining the busy ticks for a given spdk thread (which in fact is doing completely nothing) even though that said cpu, initially is occupied by completely different processes.

If it is expected then either this test is foobar, and we shouldn't determine idleness of the spdk thread by comparing its idle ticks vs busy ticks but rather by some avg increase of the idle ticks (similar to what `test/scheduler/interrupt.sh` is doing, but for determining idleness of the given cpu) maybe?  Alternatively, isolating the cpus (moving away all other processes off of them and leaving them just for the spdk app) could also help (though this may simply hide some bigger issue here. I mean, if there is any)? 

@tomzawadzki @Maciej-Szwed Would you kindly advise how we could proceed with this one?

**Comment by mikeBashStuff** [comment] 2021-01-27 10:11
Interestingly, depending on which cpus from the mask are going to be overloaded prior running the test, results may differ a bit. For instance, this:

`stress-ng --all 8  --taskset 1-4,24-28 --class cpu --cpu-method loop` - targeting all cpus from the spdk's cpumask. Results are as posted above, `nvmf_*` threads having busy|idle disproportion favoring busy ts.

`stress-ng --all 8  --taskset 1 --class cpu --cpu-method loop` - putting all stressors on main cpu, app won't be able to even initialize in time (e.g. `waitforlisten()` hits a timeout while verifying if app is running). 

`stress-ng --all 8  --taskset 1-2 --class cpu --cpu-method loop` - putting all stressors on main cpu + extra cpu from the mask. The `app_thread` ends up with quite big disproportion between busy and idle ts, however, all other threads, including `nvmf_*`, are idle right off the bat. Example of a first sample:
```
Waiting for app_thread to become idle: 2591585004 70704876304
nvmf_tgt_poll_group_1 is idle: 2731916 71196
nvmf_tgt_poll_group_2 is idle: 1392080452 78360
nvmf_tgt_poll_group_3 is idle: 1381206748 115244
nvmf_tgt_poll_group_4 is idle: 1382211716 34188
nvmf_tgt_poll_group_25 is idle: 2152940 154336
nvmf_tgt_poll_group_26 is idle: 2131996 105088
nvmf_tgt_poll_group_27 is idle: 2189060 23116
nvmf_tgt_poll_group_28 is idle: 2122512 105780
iscsi_poll_group_1 is idle: 3310692 37040
iscsi_poll_group_2 is idle: 2308436 10160
iscsi_poll_group_3 is idle: 2267464 34044
iscsi_poll_group_4 is idle: 2297836 9388
iscsi_poll_group_25 is idle: 2261060 8632
iscsi_poll_group_26 is idle: 2292020 14852
iscsi_poll_group_27 is idle: 1305848088 9220
iscsi_poll_group_28 is idle: 2320224 12640
```

**Comment by spdkci** [comment] 2021-02-03 15:41
Another instance of this failure. Reported by @mikeBashStuff. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_35755.html

**Comment by spdkci** [comment] 2021-02-25 10:37
Another instance of this failure. Reported by @tomzawadzki. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_37296.html

**Comment by tomzawadzki** [comment] 2021-06-09 11:41
>Number of the busy ticks is far greater than the idle ticks. Now, when test iterates further, each sample shows increase in idle ticks and busy ticks remain at their value from the first sample. However, the difference between busy|idle here is so big, e.g. nvmf_tgt_poll_group_4 to idle: 6399042342 busy: 25985895579, that the number of idle ticks have no chance of surpassing the busy ones within the time the test is running under. 

This has been a problem when threads were placed on an reactor without threads or in interrupt mode.
[event_stats ](https://review.spdk.io/gerrit/q/topic:%22event_stats%22+status:merged) series addressed this problem, especially following patch:
[lib/event: fix tsc_last for first thread on reactor](https://review.spdk.io/gerrit/c/spdk/spdk/+/7845)

With the above this issue should no longer occur.

**Closed by tomzawadzki** 2021-06-09 11:41 UTC
Labels: Medium, bug
