### ISSUE TITLE
Logging error 19 when running nvme discovery after buliding a spdk-tcp-nvmf target

### ISSUE THREAD

**Issue by kevinnikki** [spdk/spdk#2142] opened 2021-09-02 14:20 UTC
# Bug report

I had created a nvme-oF target using tcp as transport, nvmf target and Initiator are on the same host,but when i run 'nvme discover', the results are"failed to add controller, error 19"

## Expected Behavior

After running 'nvme discover',results should be like this:

root@pve:~# nvme discover -t tcp -a 127.0.0.1 -s 4420 -C none

Discovery Log Number of Records 1, Generation counter 5
=====Discovery Log Entry 0======
trtype:  unrecognized
adrfam:  ipv4
subtype: nvme subsystem
treq:    unrecognized
portid:  1
trsvcid: 4420
subnqn:  nqn.2014-08.org.nvmexpress:nvmf:uuid:3c1fc56e-0bf1-484e-b6db-5ba92fad0a5a
traddr:  127.0.0.1
 

## Current Behavior

root@pve:~# nvme discover -t tcp -a 127.0.0.1 -s 4420 -C none
failed to add controller, error 19

And once i run 'nvme discover', the results of command 'dmseg' will add a line 'nvme nvme2: new ctrl: NQN "nqn.2014-08.org.nvmexpress.discovery", addr 127.0.0.1:4420'.

## Possible Solution

To solve this problem may need to understand the operating principle of the discovery subsystem

## Steps to Reproduce

1.install nvme-cli tools
2.# modprobe nvme-tcp  &&  modprobe nvme-fabrics
3.# cd /path/to/spdk/repo
4.# HUGEMEM=28672 ./scripts/setup.sh
5.# build/bin/nvmf_tgt &
6.# scripts/rpc.py nvmf_create_transport -t TCP -u 16384 -m 8 -c 8192
7.# scripts/rpc.py bdev_malloc_create -b Malloc0 512 2048
8.# scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1
9.# scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
10.# scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 127.0.0.1 -s 4420
11.#  nvme discover -t tcp -a 127.0.0.1 -s 4420

Operations are referred to SPDK official documents : https://spdk.io/doc/nvmf.html

## Context (Environment including OS version, SPDK version, etc.)
spdk version: v21.07
kernel version:linux 5.11.22-1-pve
OS version:Debian GNU/Linux 11

**Comment by peluse** [comment] 2021-09-02 14:27
@kevinnikki can you please fill out the template? We need to know all of the requested details including and especially detailed steps to reproduce and context.  A shorter title would be a little better too :)

**Comment by kevinnikki** [comment] 2021-09-02 15:09
> @kevinnikki can you please fill out the template? We need to know all of the requested details including and especially detailed steps to reproduce and context. A shorter title would be a little better too :)

Now i have fill it, thanks for reminding

**Comment by Comphix** [comment] 2021-09-06 04:52
error 19 is no such device
#define ENODEV      19  /* No such device */

I am not sure about the "-C None" parameter based on below nvme discover command usage.
https://www.mankier.com/1/nvme-discover

Also, could you also try other internal IP address like 192.168.0.1?

**Comment by kevinnikki** [comment] 2021-09-06 10:42
> error 19 is no such device
> #define ENODEV 19 /* No such device */
> 
> I am not sure about the "-C None" parameter based on below nvme discover command usage.
> https://www.mankier.com/1/nvme-discover
> 
> Also, could you also try other internal IP address like 192.168.0.1?

**Comment by kevinnikki** [comment] 2021-09-06 10:44
> error 19 is no such device
> #define ENODEV 19 /* No such device */
> 
> I am not sure about the "-C None" parameter based on below nvme discover command usage.
> https://www.mankier.com/1/nvme-discover
> 
> Also, could you also try other internal IP address like 192.168.0.1?

**Comment by kevinnikki** [comment] 2021-09-06 10:53
> error 19 is no such device
> #define ENODEV 19 /* No such device */
> 
> I am not sure about the "-C None" parameter based on below nvme discover command usage.
> https://www.mankier.com/1/nvme-discover
> 
> Also, could you also try other internal IP address like 192.168.0.1?

the parameter '-C none' doesn't affect results of 'nvme discover'. It means the nvme-cli won't find a file from the path '/etc/nvme/config.json'.You can find the details in 'fabrics.c' from nvme-cli source code.I haven't try other ip but i found that the 'nvme connect' command works, i can connect this nvme-oF target but can't discover it.

**Comment by Comphix** [comment] 2021-09-27 07:49
Looks like connect command works which means to directly connect a Known device. Discover command is to list related devices from the NVMe-oF Target. Maybe you could add a debugging break at nvmf_get_discovery_log_page() on the SPDK NVMe-oF Target side to debug whether the discover command is properly handled at the Target side.

**Comment by kevinnikki** [comment] 2021-09-28 06:33
> Looks like connect command works which means to directly connect a Known device. Discover command is to list related devices from the NVMe-oF Target. Maybe you could add a debugging break at nvmf_get_discovery_log_page() on the SPDK NVMe-oF Target side to debug whether the discover command is properly handled at the Target side.

thanks for your reply, i will try it later!

**Comment by jimharris** [comment] 2021-12-22 00:02
Closing.  @kevinnikki, please reopen if you are able to retest with latest master and still see a problem.

**Closed by jimharris** 2021-12-22 00:02 UTC
Labels: question, Waiting on Submitter
