### ISSUE TITLE
[nvmf-phy-autotest] SPDK CI jenkins - build timeout

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#2005] opened 2021-06-22 20:29 UTC
## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_50547.html

## Execution failed at

```
00:15:50.693  ************************************
00:15:50.693  START TEST nvmf_target_disconnect_tc3
00:15:50.693  ************************************
00:15:50.694   21:59:57	# xtrace_enable
00:15:50.694   21:59:57	# nvmf_target_disconnect_tc3
00:15:50.694   21:59:57	# reconnectpid=21646
00:15:50.694   21:59:57	# sleep 2
00:15:50.695   21:59:57	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/build/examples/reconnect -q 32 -o 4096 -w randrw -M 50 -t 10 -c 0xF -r 'trtype:rdma adrfam:IPv4 traddr:192.168.100.8 trsvcid:4420 alt_traddr:192.168.100.9'
00:15:50.711  [2021-06-22 21:59:57.612848] Starting SPDK v21.07-pre git sha1 0d68e8c11 / DPDK 21.05.0 initialization...
00:15:50.711  [2021-06-22 21:59:57.612941] [ DPDK EAL parameters: [2021-06-22 21:59:57.612954] reconnect [2021-06-22 21:59:57.612964] --no-shconf [2021-06-22 21:59:57.612972] -c 0xF [2021-06-22 21:59:57.612981] --log-level=lib.eal:6 [2021-06-22 21:59:57.612989] --log-level=lib.cryptodev:5 [2021-06-22 21:59:57.612997] --log-level=user1:6 [2021-06-22 21:59:57.613006] --iova-mode=pa [2021-06-22 21:59:57.613013] --base-virtaddr=0x200000000000 [2021-06-22 21:59:57.613021] --match-allocations [2021-06-22 21:59:57.613029] --file-prefix=spdk_pid21646 [2021-06-22 21:59:57.613037] ]
00:15:50.744  EAL: No free 2048 kB hugepages reported on node 1
00:15:50.744  EAL: No available 1048576 kB hugepages reported
00:15:50.747  TELEMETRY: No legacy callbacks, legacy socket not created
00:15:51.240  Build timed out (after 15 minutes). Marking the build as failed.
00:15:51.257  Build was aborted
00:15:51.259  [PostBuildScript] - [INFO] Executing post build scripts.
00:15:51.268  [nvmf-phy-autotest] $ /usr/bin/env bash /tmp/jenkins1211055520775986291.sh
00:15:51.274  Start stage post_get_build_log.sh
00:15:52.703   21:59:59	# kill -9 21601
00:15:52.703   21:59:59	# sleep 2
```

**Comment by spdkci** [comment] 2021-06-22 20:29
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_50547.html

**Comment by spdkci** [comment] 2021-06-23 00:40
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_50564.html

**Comment by spdkci** [comment] 2021-06-23 07:41
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_50622.html

**Comment by spdkci** [comment] 2021-06-23 12:27
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_50629.html

**Comment by spdkci** [comment] 2021-06-23 20:20
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_50692.html

**Comment by spdkci** [comment] 2021-06-23 21:48
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_50707.html

**Comment by karlatec** [comment] 2021-06-28 08:48
Note:
Log files show that this only happens on WFP9 test node.

In some nvmf tests `disconnect` seems to take a lot of time:
```
(~1 minute)
00:05:02.293  ************************************
00:05:02.293  END TEST filesystem_incapsule_xfs
00:05:02.293  ************************************
00:05:02.321   23:25:12	# xtrace_enable
00:05:02.321   23:25:12	# parted -s /dev/nvme0n1 rm 1
00:05:02.333   23:25:12	# sync
00:05:02.338   23:25:12	# nvme disconnect -n nqn.2016-06.io.spdk:cnode1
00:05:15.172  [2021-06-23 23:25:25.360998] ctrlr.c: 185:nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host nqn.2014-08.org.nvmexpress:uuid:67363ce608f44a64a054dc009bb4a1fe from subsystem nqn.2016-06.io.spdk:cnode1 due to keep alive timeout.
00:06:18.980  NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
```

```
(over 1 minute)
00:05:47.866  ************************************
00:05:47.866  END TEST filesystem_incapsule_xfs
00:05:47.866  ************************************
00:05:47.894   21:51:31	# xtrace_enable
00:05:47.895   21:51:31	# parted -s /dev/nvme0n1 rm 1
00:05:47.908   21:51:31	# sync
00:05:47.912   21:51:31	# nvme disconnect -n nqn.2016-06.io.spdk:cnode1
00:06:00.788  [2021-06-23 21:51:44.709447] ctrlr.c: 185:nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host nqn.2014-08.org.nvmexpress:uuid:67363ce608f44a64a054dc009bb4a1fe from subsystem nqn.2016-06.io.spdk:cnode1 due to keep alive timeout.
00:07:04.521  NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
00:07:04.522   21:52:48	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_delete_subsystem nqn.2016-06.io.spdk:cnode1
```

```
(~3-4 minutes!)
00:05:59.403  ************************************
00:05:59.403  START TEST nvmf_connect_disconnect
00:05:59.403  ************************************
[...]
00:06:01.226   21:50:08	# num_iterations=10
00:06:01.226   21:50:08	# set +x
00:06:20.018  NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
00:06:38.832  NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
00:06:44.589  Waiting for devices
00:06:58.651  NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
00:07:04.408  Waiting for devices
00:07:18.468  NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
00:07:37.301  NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
00:07:43.061  Waiting for devices
00:07:57.171  NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
00:08:15.961  NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
00:08:34.820  NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
00:08:40.578  Waiting for devices
00:08:54.633  NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
00:09:00.393  Waiting for devices
00:09:14.447  NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
00:09:14.463   21:53:21	# trap - SIGINT SIGTERM EXIT
00:09:14.463   21:53:21	# nvmftestfini
00:09:14.463   21:53:21	# nvmfcleanup
```

**Comment by spdkci** [comment] 2021-06-29 09:57
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51210.html

**Comment by spdkci** [comment] 2021-06-29 10:42
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_51204.html

**Comment by spdkci** [comment] 2021-07-06 07:08
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_51745.html

**Comment by spdkci** [comment] 2021-07-06 07:10
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_51732.html

**Comment by spdkci** [comment] 2021-07-06 07:10
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_51738.html

**Comment by karlatec** [comment] 2021-07-06 07:10
@optimistyzy this build failure is not related to this issue

**Comment by spdkci** [comment] 2021-07-06 08:30
Another instance of this failure. Reported by @spdkci. log: https://ci.spdk.io/public_build/autotest-per-patch_51784.html

**Comment by spdkci** [comment] 2021-07-06 08:44
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_51766.html

**Comment by spdkci** [comment] 2021-07-06 16:41
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51867.html

**Comment by spdkci** [comment] 2021-07-07 06:34
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_51895.html

**Comment by spdkci** [comment] 2021-07-07 06:41
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_52015.html

**Comment by KKaras169169** [comment] 2021-07-07 06:42
> Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_52015.html

This one actually failed even earlier - during  "nvmf_target_disconnect_tc2" test.

**Comment by spdkci** [comment] 2021-07-07 06:45
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_51995.html

**Comment by spdkci** [comment] 2021-07-07 07:13
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_52006.html

**Comment by spdkci** [comment] 2021-07-07 07:56
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_51878.html

**Comment by mikeBashStuff** [comment] 2021-07-07 07:59
All the reports still seem to point at WFP9. I am removing it from the pool until we understand the root cause.

**Comment by spdkci** [comment] 2021-07-07 07:59
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_51930.html

**Comment by spdkci** [comment] 2021-07-09 12:37
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_51974.html

**Comment by spdkci** [comment] 2021-07-09 12:39
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_51969.html

**Comment by spdkci** [comment] 2021-07-09 12:41
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_52001.html

**Comment by karlatec** [comment] 2021-07-13 13:08
So this seems to occur only on WFP9. I checked and tried a bunch of stuff:

- First I noticed WFP9 was not configured to use vfio-pci, so I fixed that, but no results.
- Updated NVMe drive FW, no results.
- Updated NIC (Mellanox ConnectX-4), no results.
- Set SELinux to "permissive", no results.
- Disable firewall, no results.

Other observations:

- Most of our systems which run nvmf-phy-autotest suite have Mellanox ConnectX-5 or ConnectX-4 LX on board. These do not cause problems. There are a few which have ConnectX-4 on board (WFP9 being among them), but WFP9 is the only one which has MCX416A-CCAT model. Others (which do not have issues) are MCX456A-ECAT. Not sure if and how that could be related.
- This SPDK notice message frequently show up when doing `nvme disconnect`:

  ```
  [2021-07-13 14:20:32.470869] ctrlr.c: 185:nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host nqn.2014-08.org.nvmexpress:uuid:67363ce608f44a64a054dc009bb4a1fe from subsystem nqn.2016-06.io.spdk:cnode1 due to keep alive timeout.
  ```

  at the same time disconnect takes a lot of time and this can be found in dmesg:

  ```
  [333109.119006] nvme nvme0: creating 63 I/O queues.
  [333115.442106] nvme nvme0: mapped 63/0/0 default/read/poll queues.
  [333115.455430] nvme nvme0: new ctrl: NQN "nqn.2016-06.io.spdk:cnode1", addr 192.168.100.8:4420
  [333115.461931]  nvme0n1:
  [333120.282546] nvme nvme0: Removing ctrl: NQN "nqn.2016-06.io.spdk:cnode1"
  [333197.835298] nvme nvme0: I/O 2 QID 0 timeout
  [333197.835837] nvme nvme0: Property Set error: 881, offset 0x14
  ```

- Changing the number of IO queues when connecting (--nr-io-queues=<NUM>) has effect on whether there will be a problem with disconnect or not. Keeping the number of IO queues below 64 seems to mitigate the issue. The number of IO queues in test script is not specified, so nvmecli uses cpu core count as default (which is 96 for WFP9 with HT enabled).


@mikeBashStuff  any tips or thoughts on checking other options or some sysfs tuning? I guess we could also try swapping out the NIC and see what happens...

**Comment by karlatec** [comment] 2021-07-13 13:12
@jimharris could you take a look at the dmesg output in the comment above?

**Comment by tomzawadzki** [comment] 2021-07-13 15:20
[Bug scrub] Try checking if this is directly related to particular NIC, @karlatec will check if swapping it would resolve it.

**Comment by karlatec** [comment] 2021-07-15 13:59
Swapped NIC and re-enabling WFP9 in the test pool. Let's see what happens.

**Comment by jimharris** [comment] 2021-07-16 22:18
> 
> Other observations:
> 
> * Most of our systems which run nvmf-phy-autotest suite have Mellanox ConnectX-5 or ConnectX-4 LX on board. These do not cause problems. There are a few which have ConnectX-4 on board (WFP9 being among them), but WFP9 is the only one which has MCX416A-CCAT model. Others (which do not have issues) are MCX456A-ECAT. Not sure if and how that could be related.

MCX416A-CCAT: ConnectX-4 EN network interface card, 100GbE single-port QSFP28, PCIe3.0 x16, tall bracket
MCX456A-ECAT: ConnectX®-4 VPI adapter card, EDR IB (100Gb/s) and 100GbE, dual-port QSFP28, PCIe3.0 x16, tall bracket

Not sure why only one of these would show a problem.  Tagging @AlekseyMarchuk in case he has any ideas...

>   at the same time disconnect takes a lot of time and this can be found in dmesg:
>   ```
>   [333109.119006] nvme nvme0: creating 63 I/O queues.
>   [333115.442106] nvme nvme0: mapped 63/0/0 default/read/poll queues.
>   [333115.455430] nvme nvme0: new ctrl: NQN "nqn.2016-06.io.spdk:cnode1", addr 192.168.100.8:4420
>   [333115.461931]  nvme0n1:
>   [333120.282546] nvme nvme0: Removing ctrl: NQN "nqn.2016-06.io.spdk:cnode1"
>   [333197.835298] nvme nvme0: I/O 2 QID 0 timeout

QID 0 means the initiator saw a timeout on the adminq.  Presumably it's the keep alive command that timed out.

>   [333197.835837] nvme nvme0: Property Set error: 881, offset 0x14
>   ```
> * Changing the number of IO queues when connecting (--nr-io-queues=) has effect on whether there will be a problem with disconnect or not. Keeping the number of IO queues below 64 seems to mitigate the issue. The number of IO queues in test script is not specified, so nvmecli uses cpu core count as default (which is 96 for WFP9 with HT enabled). This is less than what the disk (p4510 1TB) reports as being capable of:

Note that we use a 0xF0 core mask when starting the nvmf target, meaning only 4 cores are used.  Since we only allocate one qpair per thread in the bdev/nvme module, the number of supported qpairs on the SSD will be irrelevant for this test case.

But if reducing the number of qpairs from the initiator has an effect then that is very interesting.  When you say "has effect" does that mean that it never fails with 64 queues or fewer?

**Comment by karlatec** [comment] 2021-07-20 09:49
> But if reducing the number of qpairs from the initiator has an effect then that is very interesting. When you say "has effect" does that mean that it never fails with 64 queues or fewer?

I think so. I've run the test in a loop with `nvme connect -i={1 / 4 / 8 / 16 / 32 / 64}` and could not reproduce the issue. Which is weird for 64 actually because (looking at dmesg output) it's the same what nvme connect does without `-i` option. Could have just been lucky.

Anyways, swapping the NIC to more recent model - MCX516A-CDAT - seems to have solved the issue. Should I close the issue, or do we want to investigate further?

**Comment by AlekseyMarchuk** [comment] 2021-07-20 14:20
I didn't hear about problems with MCX416A-CCAT. I'll ask my colleagues if they know something

**Comment by AlekseyMarchuk** [comment] 2021-07-21 07:27
@karlatec We found MCX416A-CCAT: ConnectX-4 EN, I want to reproduce this issue on my setup. Could you clarify OS version and which rdma drivers are used- inbox or some ofed/mofed?

**Comment by karlatec** [comment] 2021-07-27 15:06
@AlekseyMarchuk  sorry I missed the question. OS is 5.11.22-100.fc32.x86_64 and driver is inbox from Fedora DNF

**Comment by spdkci** [comment] 2021-08-03 22:46
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_54921.html

**Comment by spdkci** [comment] 2021-11-16 13:47
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_61919.html

**Comment by tomzawadzki** [comment] 2021-11-30 10:50
The report above looks to be #2128, rather than this issue.

Outside of that, the issue has not occured for over 3 months. Closing this issue.

**Closed by tomzawadzki** 2021-11-30 10:50 UTC
Labels: 3rd party issue, Intermittent Failure
