### ISSUE TITLE
iscsi_autotest reports build timeout in CI

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1056] opened 2019-11-14 14:31 UTC
Hit while CI running on unrleated patch https://review.gerrithub.io/c/spdk/spdk/+/472202/3 

See https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/49619/archive/iscsi_autotest/build.log 

Snippet:

  00:01:58	# /var/jenkins/workspace/iSCSI_tests/iscsi_autotest/spdk/scripts/gen_nvme.sh --json
  00:01:58	# jq -r '.config[].params | select(.name=="Nvme0").traddr'
 00:01:58	# bdf=0000:82:00.0
 00:01:58	# /var/jenkins/workspace/iSCSI_tests/iscsi_autotest/spdk/scripts/rpc.py bdev_nvme_attach_controller -b nvme0 -t pcie -a 0000:82:00.0
EAL:   using IOMMU type 1 (Type 1)
nvme0n1
 00:02:02	# /var/jenkins/workspace/iSCSI_tests/iscsi_autotest/spdk/scripts/rpc.py bdev_nvme_opal_revert -b nvme0 -p test
vbdev_opal_rpc.c: 171:spdk_rpc_bdev_nvme_opal_revert: *ERROR*: nvme0 not support opal
request:
{
  "method": "bdev_nvme_opal_revert",
  "req_id": 1,
  "nvme_ctrlr_name": "nvme0",
  "password": "test"
}
Got JSON-RPC error response

**Comment by jimharris** [comment] 2019-11-14 14:49
This build actually failed due to build timeout.  The opal error reported is unfortunate but not the cause of this specific build failure.  (We try to revert any opal settings at the beginning of every test run, but if the SSD doesn't support opal, this RPC fails and we just continue.)

I'm assigning this to @Seth5141 to take a look if we need to extend iSCSI auto test build timeout.

@jessehui - we should also find a way to avoid calling bdev_nvme_opal_revert RPC on SSDs that don't support OPAL.  That will reduce confusion when reading the logs.  Thanks.

**Comment by peluse** [comment] 2019-11-14 15:01
@jimharris damn I usually catch the timeouts, where in the log did you spot it?  Thanks!

**Comment by jimharris** [comment] 2019-11-14 15:08
It's at the end of the log:

 00:08:51	$ xtrace_disable
 00:08:51	$ PREV_BASH_OPTS=ehxBE
 00:08:51	$ set +x
 00:08:51	$ xtrace_enable
 00:08:51	$ make clean
  00:08:55	$ git status --porcelain --ignore-submodules
  00:08:55	$ wc -l
Build timed out (after 10 minutes). Marking the build as failed.
 00:08:55	$ '[' 0 -ne 0 ']'
 00:08:55	$ timing_exit porcelain_check
 00:08:55	$ xtrace_disable
 00:08:55	$ PREV_BASH_OPTS=ehxBE
 00:08:55	$ set +x
Build was aborted
[PostBuildScript] - Executing post build scripts.
[iscsi_autotest] $ /bin/sh -xe /tmp/jenkins6574580322513447919.sh
+ set +x
 00:08:55	$ xtrace_enable
 00:08:55	$ [[ 0 -eq 0 ]]
 00:08:55	$ [[ 0 -eq 0 ]]
 00:08:55	$ timing_finish
 00:08:55	$ flamegraph=/usr/local/FlameGraph/flamegraph.pl
 00:08:55	$ '[' -x /usr/local/FlameGraph/flamegraph.pl ']'
 00:08:55	$ /usr/local/FlameGraph/flamegraph.pl --title 'Build Timing' --nametype Step: --countname seconds /var/jenkins/workspace/iSCSI_tests/iscsi_autotest/spdk/../output/timing.txt
spdk/autorun.sh: line 21: 2409934 Terminated              $rootdir/autopackage.sh "$conf"

**Comment by spdkci** [comment] 2019-11-14 21:45
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49619.html

**Comment by Seth5141** [comment] 2019-11-14 21:52
@jimharris  I don't think we need to update the timeout on this job, it looks like @peluse just ended up in the unlucky 99th percentile and hit an outlier. It usually only takes between 7-9 minutes to run. I have attached a screenshot showing the last 50 or so jobs with the time they took.

I think it's good to keep the timeout low so that it keeps us cognizant of introducing a test that balloons the time it takes to run.

![image](https://user-images.githubusercontent.com/20448512/68899009-f2dff200-06ed-11ea-9d75-e641b3fd0553.png)

**Comment by jessehui** [comment] 2019-11-15 01:59
Hi, @jimharris , thanks for this suggestion.
> @jessehui - we should also find a way to avoid calling bdev_nvme_opal_revert RPC on SSDs that don't support OPAL. That will reduce confusion when reading the logs. Thanks.

The thing is even if we call bdev_nvme_opal_revert for an SSD that does support OPAL, it can still give error response if the drive is already in default state. As calling this RPC is just for safe purpose, and I explicitely put `set +e` before this process, I am not sure what else I can do. Or maybe do you think I can just redirect the output?

**Comment by jimharris** [comment] 2019-11-15 14:54
Hi @jessehui - we should try to reduce confusion (like we saw above) when someone reads through the logs.  Anyone who is not familiar with SDPK OPAL functionality (which includes most people) will see this error and think that something was wrong.

I think we should do something like:

1) Use bdev_nvme_get_controllers RPC to see if the SSD supports OPAL
2) If it does support OPAL, then maybe bdev_nvme_opal_revert RPC should not return an error if there is nothing to revert

**Comment by jessehui** [comment] 2019-11-18 04:36
This should fix. If nvme ctrlr not support Opal, it will not send error response.
https://review.gerrithub.io/c/spdk/spdk/+/474911

**Comment by tomzawadzki** [comment] 2019-11-19 15:23
Looking at https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/49619/archive/iscsi_autotest/timing.txt it seems that it might be related to #1067

**Comment by jimharris** [comment] 2019-11-19 17:20
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/50155/archive/nvme_phy_autotest/index.html

This one is not iscsi_autotest - but is another general build timeout for some unknown reason.

**Comment by Seth5141** [comment] 2019-11-19 23:41
Closing this since the only occurrence of this timeout for iscsi was also related to #1067, the other occurrence will be moved to another issue.

**Closed by Seth5141** 2019-11-19 23:41 UTC
Labels: Intermittent Failure
