### ISSUE TITLE
[lib/vhost]   guest os  vring stop process after memory hot-plug

### ISSUE THREAD

**Issue by v1c77** [spdk/spdk#3150] opened 2023-10-10 12:38 UTC
# Sighting report

## Current Behavior

After a mem hot plug, the guest os may stop update the virtio avail_ring.

## Possible Solution

https://review.spdk.io/gerrit/c/spdk/spdk/+/20245/1

## Steps to Reproduce

1. setup a qemu vm with vhost-user-blk&scsi  backend,
2. setup some guest side io  process, like fio.
3. hotplug  ram

We can see the  requestq_poller kept running but no more new IO would detected from the avail_ring.

## Context (Environment including OS version, SPDK version, etc.)
spdk: master & v23.01
qemu: 2.12, master
guest os: fedora 37 & centos stream

**Comment by changpe1** [comment] 2023-10-11 02:29
@v1c77 can you provide the reproduce steps for the live migration case? from the code, we will try to send an interrupt to VM after start, this should not happen for migration case.

**Comment by v1c77** [comment] 2023-10-11 06:43
> @v1c77 can you provide the reproduce steps for the live migration case? from the code, we will try to send an interrupt to VM after start, this should not happen for migration case.

I tried to make some target& source spdk accident crash during  live migration to  reprodeuce but IO frozen not show up any more until now,  redescribed the issue.

**Comment by changpe1** [comment] 2023-10-11 07:38
> > @v1c77 can you provide the reproduce steps for the live migration case? from the code, we will try to send an interrupt to VM after start, this should not happen for migration case.
> 
> I tried to make some target& source spdk accident crash during live migration to reprodeuce but IO frozen not show up any more until now, redescribed the issue.

even for the memory hotplug case, this issue is still strange to me, because when stopping the vhost device, we will always flush the used vring, there is no need to send an interrupt to VM after started.

**Comment by v1c77** [comment] 2023-10-11 08:22
Yes, I'm still tring to find the reason why an additional interrupt is requied here.  But if you test with the steps above, it  reproduced quite sure.

The possible solution is inspired by comparing the old version spdk  v21.

Before patch https://review.spdk.io/gerrit/c/spdk/spdk/+/14928/13/lib/vhost/rte_vhost_user.c#b1059 , the `enable_device_vq` would kept sending an interrupt after device is started.

Currently only an VHOST_USER_SET_VRING_CALL will trigger a new interrupt.

**Comment by changpe1** [comment] 2023-10-11 08:28
> Yes, I'm still tring to find the reason why an additional interrupt is requied here. But if you test with the steps above, it reproduced quite sure.
> 
> The possible solution is inspired by comparing the old version spdk v21.
> 
> Before patch https://review.spdk.io/gerrit/c/spdk/spdk/+/14928/13/lib/vhost/rte_vhost_user.c#b1059 , the `enable_device_vq` would kept sending an interrupt after device is started.
> 
> Currently only an VHOST_USER_SET_VRING_CALL will trigger a new interrupt.

For the memory hotplug case, there is no VHOST_USER_SET_VRING_CALL message, but SPDK indeed flush used vring before stopping, you may restore back `q->used_req_cnt += 1` in `enable_device_vq` to see fix it or not.

**Comment by v1c77** [comment] 2023-10-11 10:12
> you may restore back q->used_req_cnt += 1 in enable_device_vq to see fix it or not.

Worked as expected.  can you please review the new patchet https://review.spdk.io/gerrit/c/spdk/spdk/+/20245/3.

```
	 * Not sure right now but this look like some kind of QEMU bug and guest IO
	 * might be frozed without kicking all queues after live-migration.
```
The comment inside the code is still confused me.  measuring live migration still...

**Comment by tomzawadzki** [comment] 2023-10-17 14:27
@v1c77 thank you for the submission ! Patch https://github.com/spdk/spdk/commit/dbe47004e57ddd50b6029958eaa792a8e500676b is now mereged. Is this issue resolved ?

**Comment by v1c77** [comment] 2023-10-18 02:27
> @v1c77 thank you for the submission ! Patch [dbe4700](https://github.com/spdk/spdk/commit/dbe47004e57ddd50b6029958eaa792a8e500676b) is now mereged. Is this issue resolved ?

The issue was fixed, thanks.

**Comment by changpe1** [comment] 2023-10-18 02:37
> > @v1c77 thank you for the submission ! Patch [dbe4700](https://github.com/spdk/spdk/commit/dbe47004e57ddd50b6029958eaa792a8e500676b) is now mereged. Is this issue resolved ?
> 
> The issue was fixed, thanks.

thanks, closing this issue now.

**Closed by changpe1** 2023-10-18 02:37 UTC
Labels: bug, Medium
