### ISSUE TITLE
[nvmf_perf_tc4] *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2693] opened 2022-09-14 12:39 UTC
```
SPDK: v22.09-pre-592-g2de485346
```

This error is seen during nvmf's TC4 benchmark test while configuring the target node (i.e. while enabling dynamic scheduler). Context below. Note that the actual test fails while creating tcp transport, however, it happens right after the aformentioned error is returned. Also worth mentioning, the very same setup works just fine under 22.05 release. As of now, I am not able to reproduce this issue manually (by simply reproducing commands that are executed in order by the `run_nvmf.py`). This may potentially block performance reports for new 22.09 release.

Essentially, the flow of the target setup looks like this:
```
nvmf_tgt --wait-for-rpc
#  run_nvmf.py uses spdk.rpc module so it doesn't use rpc.py directly but here's overall representation of the RPCs that are in use prior the failure
rpc.py sock_set_default_impl -i posix
rpc.py sock_impl_set_options --enable-zerocopy-send-server
rpc.py sock_impl_get_options -i posix # Note below that output from this rpc comes AFTER dynamic scheduler is enabled
rpc.py framework_set_scheduler --core-limit 80
rpc.py framework_start_init
rpc.py nvmf_create_transport --trtype tcp --num-shared-buffers 8192 --max-queue-depth 128 # <- here's where the test fails
```

```
3:59:17 + sudo PYTHONPATH=:/var/perf_jenkins/workspace/nvmf-perf/tc4-tcp-spdk/spdk/scripts scripts/perf/nvmf/run_nvmf.py --results=/var/perf_jenkins/workspace/nvmf-perf/tc4-tcp-spdk/results --csv-filename=tc4_tcp_spdk_NUMJOB_1_QD_32_RW_randread.csv
13:59:18 Using config file: scripts/perf/nvmf/config.json
13:59:18 [target] Zipping SPDK source directory
13:59:40 [target] Done zipping
13:59:40 [target] Configuring active services...
13:59:40 [target] Current state of firewalld service is inactive
13:59:40 [target] Current state of irqbalance service is inactive
13:59:40 [target] Tuning sysctl settings...
13:59:40 [target] net.core.busy_poll = 0
13:59:40 [target] net.core.busy_read = 0
13:59:40 [target] net.core.somaxconn = 4096
13:59:40 [target] net.core.netdev_max_backlog = 8192
13:59:40 [target] net.ipv4.tcp_max_syn_backlog = 16384
13:59:40 [target] net.core.rmem_max = 268435456
13:59:40 [target] net.core.wmem_max = 268435456
13:59:40 [target] net.ipv4.tcp_mem = 268435456 268435456 268435456
13:59:40 [target] net.ipv4.tcp_rmem = 8192 1048576 33554432
13:59:40 [target] net.ipv4.tcp_wmem = 8192 1048576 33554432
13:59:40 [target] net.ipv4.route.flush = 1
13:59:40 [target] vm.overcommit_memory = 1
13:59:40 [target] WARNING: Tuned profile not set in configuration file. Skipping configuration.
13:59:40 [target] Setting CPU governor to performance...
13:59:40 [target] Setting NIC irq affinity for NICs...
13:59:40 [target] ['sudo', '/usr/src/local/mlnx-tools/ofed_scripts/set_irq_affinity.sh', 'eth3']
13:59:40 [target] Changing directory to /usr/src/local/mlnx-tools/ofed_scripts
13:59:41 [target] Changing directory to /var/perf_jenkins/workspace/nvmf-perf/tc4-tcp-spdk/spdk
13:59:41 [target] ['sudo', '/usr/src/local/mlnx-tools/ofed_scripts/set_irq_affinity.sh', 'eth5']
13:59:41 [target] Changing directory to /usr/src/local/mlnx-tools/ofed_scripts
13:59:41 [target] Changing directory to /var/perf_jenkins/workspace/nvmf-perf/tc4-tcp-spdk/spdk
13:59:41 [target] ['sudo', '/usr/src/local/mlnx-tools/ofed_scripts/set_irq_affinity.sh', 'eth7']
13:59:41 [target] Changing directory to /usr/src/local/mlnx-tools/ofed_scripts
13:59:41 [target] Changing directory to /var/perf_jenkins/workspace/nvmf-perf/tc4-tcp-spdk/spdk
13:59:41 [target] ['sudo', '/usr/src/local/mlnx-tools/ofed_scripts/set_irq_affinity.sh', 'eth9']
13:59:41 [target] Changing directory to /usr/src/local/mlnx-tools/ofed_scripts
13:59:41 [target] Changing directory to /var/perf_jenkins/workspace/nvmf-perf/tc4-tcp-spdk/spdk
13:59:41 [target] ====Kernel release:====
13:59:41 [target] 5.15.11-200.fc35.x86_64
13:59:41 [target] ====Kernel command line:====
13:59:41 [target] BOOT_IMAGE=(hd0,gpt2)/vmlinuz-5.15.11-200.fc35.x86_64 root=/dev/mapper/fedora_spdk--sm--15-root ro rd.lvm.lv=fedora_spdk-sm-15/root rhgb quiet iommu=pt intel_iommu=on net.ifnames=0
13:59:41 
13:59:41 [target] ====sysctl conf:====
13:59:41 [target] 
13:59:41 [target] ====Cpu power info:====
13:59:41 [target] analyzing CPU 0:
13:59:41   driver: intel_cpufreq
13:59:41   CPUs which run at the same hardware frequency: 0
13:59:41   CPUs which need to have their frequency coordinated by software: 0
13:59:41   maximum transition latency: 20.0 us
13:59:41   hardware limits: 800 MHz - 3.50 GHz
13:59:41   available cpufreq governors: conservative ondemand userspace powersave performance schedutil
13:59:41   current policy: frequency should be within 3.50 GHz and 3.50 GHz.
13:59:41                   The governor "performance" may decide which speed to use
13:59:41                   within this range.
13:59:41   current CPU frequency: Unable to call hardware
13:59:41   current CPU frequency: 800 MHz (asserted by call to kernel)
13:59:41   boost state support:
13:59:41     Supported: yes
13:59:41     Active: yes
13:59:41 
13:59:41 [target] ====zcopy settings:====
13:59:41 [target] zcopy enabled: True
13:59:41 [target] ====Scheduler settings:====
13:59:41 [target] SPDK scheduler: dynamic
13:59:41 [target] ====DSA settings:====
13:59:41 [target] DSA enabled: False
13:59:42 [initiatorCYP1] Copying SPDK sources to initiator initiatorCYP1
13:59:47 [initiatorCYP1] Copied sources zip from target
13:59:51 [initiatorCYP1] Sources unpacked
13:59:52 [initiatorCYP1] WARNING: you have disabled intel_pstate and using default cpu governance.
13:59:52 [initiatorCYP1] Configuring active services...
13:59:52 [initiatorCYP1] Current state of firewalld service is inactive
13:59:52 [initiatorCYP1] Current state of irqbalance service is inactive
13:59:52 [initiatorCYP1] Tuning sysctl settings...
13:59:52 [initiatorCYP1] net.core.busy_poll = 0
13:59:52 [initiatorCYP1] net.core.busy_read = 0
13:59:52 [initiatorCYP1] net.core.somaxconn = 4096
13:59:52 [initiatorCYP1] net.core.netdev_max_backlog = 8192
13:59:52 [initiatorCYP1] net.ipv4.tcp_max_syn_backlog = 16384
13:59:52 [initiatorCYP1] net.core.rmem_max = 268435456
13:59:53 [initiatorCYP1] net.core.wmem_max = 268435456
13:59:53 [initiatorCYP1] net.ipv4.tcp_mem = 268435456 268435456 268435456
13:59:53 [initiatorCYP1] net.ipv4.tcp_rmem = 8192 1048576 33554432
13:59:53 [initiatorCYP1] net.ipv4.tcp_wmem = 8192 1048576 33554432
13:59:53 [initiatorCYP1] net.ipv4.route.flush = 1
13:59:53 [initiatorCYP1] vm.overcommit_memory = 1
13:59:53 [initiatorCYP1] WARNING: Tuned profile not set in configuration file. Skipping configuration.
13:59:53 [initiatorCYP1] Setting CPU governor to performance...
13:59:53 [initiatorCYP1] Setting NIC irq affinity for NICs...
13:59:53 [initiatorCYP1] ['sudo', '/usr/src/local/mlnx-tools/ofed_scripts/set_irq_affinity.sh', 'eth2']
13:59:53 [initiatorCYP1] ['sudo', '/usr/src/local/mlnx-tools/ofed_scripts/set_irq_affinity.sh', 'eth4']
13:59:54 [initiatorCYP1] ====Kernel release:====
13:59:54 [initiatorCYP1] 5.15.11-200.fc35.x86_64
13:59:54 
13:59:54 [initiatorCYP1] ====Kernel command line:====
13:59:54 [initiatorCYP1] BOOT_IMAGE=(hd1,gpt2)/vmlinuz-5.15.11-200.fc35.x86_64 root=/dev/mapper/fedora_fedora-root ro rd.lvm.lv=fedora_fedora/root rhgb quiet iommu=pt intel_iommu=on net.ifnames=0
13:59:54 [initiatorCYP1] ====sysctl conf:====
13:59:54 [initiatorCYP1] 
13:59:54 [initiatorCYP1] ====Cpu power info:====
13:59:54 [initiatorCYP1] analyzing CPU 0:
13:59:54   driver: intel_pstate
13:59:54   CPUs which run at the same hardware frequency: 0
13:59:54   CPUs which need to have their frequency coordinated by software: 0
13:59:54   maximum transition latency:  Cannot determine or is not supported.
13:59:54   hardware limits: 800 MHz - 3.50 GHz
13:59:54   available cpufreq governors: performance powersave
13:59:54   current policy: frequency should be within 800 MHz and 3.50 GHz.
13:59:54                   The governor "performance" may decide which speed to use
13:59:54                   within this range.
13:59:54   current CPU frequency: Unable to call hardware
13:59:54   current CPU frequency: 801 MHz (asserted by call to kernel)
13:59:54   boost state support:
13:59:54     Supported: yes
13:59:54     Active: yes
13:59:54 
13:59:54 [initiatorCYP2] Copying SPDK sources to initiator initiatorCYP2
13:59:59 [initiatorCYP2] Copied sources zip from target
14:00:03 [initiatorCYP2] Sources unpacked
14:00:04 [initiatorCYP2] WARNING: you have disabled intel_pstate and using default cpu governance.
14:00:04 [initiatorCYP2] Configuring active services...
14:00:04 [initiatorCYP2] Current state of firewalld service is inactive
14:00:04 [initiatorCYP2] Current state of irqbalance service is inactive
14:00:04 [initiatorCYP2] Tuning sysctl settings...
14:00:04 [initiatorCYP2] net.core.busy_poll = 0
14:00:04 [initiatorCYP2] net.core.busy_read = 0
14:00:04 [initiatorCYP2] net.core.somaxconn = 4096
14:00:04 [initiatorCYP2] net.core.netdev_max_backlog = 8192
14:00:04 [initiatorCYP2] net.ipv4.tcp_max_syn_backlog = 16384
14:00:04 [initiatorCYP2] net.core.rmem_max = 268435456
14:00:04 [initiatorCYP2] net.core.wmem_max = 268435456
14:00:05 [initiatorCYP2] net.ipv4.tcp_mem = 268435456 268435456 268435456
14:00:05 [initiatorCYP2] net.ipv4.tcp_rmem = 8192 1048576 33554432
14:00:05 [initiatorCYP2] net.ipv4.tcp_wmem = 8192 1048576 33554432
14:00:05 [initiatorCYP2] net.ipv4.route.flush = 1
14:00:05 [initiatorCYP2] vm.overcommit_memory = 1
14:00:05 [initiatorCYP2] WARNING: Tuned profile not set in configuration file. Skipping configuration.
14:00:05 [initiatorCYP2] Setting CPU governor to performance...
14:00:05 [initiatorCYP2] Setting NIC irq affinity for NICs...
14:00:05 [initiatorCYP2] ['sudo', '/usr/src/local/mlnx-tools/ofed_scripts/set_irq_affinity.sh', 'eth2']
14:00:05 [initiatorCYP2] ['sudo', '/usr/src/local/mlnx-tools/ofed_scripts/set_irq_affinity.sh', 'eth4']
14:00:06 [initiatorCYP2] ====Kernel release:====
14:00:06 [initiatorCYP2] 5.15.11-200.fc35.x86_64
14:00:06 
14:00:06 [initiatorCYP2] ====Kernel command line:====
14:00:06 [initiatorCYP2] BOOT_IMAGE=(hd2,gpt2)/vmlinuz-5.15.11-200.fc35.x86_64 root=/dev/mapper/fedora_fedora-root ro rd.lvm.lv=fedora_fedora/root rhgb quiet iommu=pt intel_iommu=on net.ifnames=0
14:00:06 [initiatorCYP2] ====sysctl conf:====
14:00:06 [initiatorCYP2] 
14:00:06 [initiatorCYP2] ====Cpu power info:====
14:00:06 [initiatorCYP2] analyzing CPU 0:
14:00:06   driver: intel_pstate
14:00:06   CPUs which run at the same hardware frequency: 0
14:00:06   CPUs which need to have their frequency coordinated by software: 0
14:00:06   maximum transition latency:  Cannot determine or is not supported.
14:00:06   hardware limits: 800 MHz - 3.50 GHz
14:00:06   available cpufreq governors: performance powersave
14:00:06   current policy: frequency should be within 800 MHz and 3.50 GHz.
14:00:06                   The governor "performance" may decide which speed to use
14:00:06                   within this range.
14:00:06   current CPU frequency: Unable to call hardware
14:00:06   current CPU frequency: 800 MHz (asserted by call to kernel)
14:00:06   boost state support:
14:00:06     Supported: yes
14:00:06     Active: yes
14:00:06 
14:00:06   14:00:06	-- common/autotest_common.sh@1565 -- # xtrace_enable
14:00:06  14:00:06	-- @1 -- # get_nvme_bdfs 01 08 02
14:00:06  14:00:06	-- common/autotest_common.sh@1380 -- # xtrace_disable
14:00:06  14:00:06	-- common/autotest_common.sh@14 -- # '[' '' '!=' yes ']'
14:00:06  14:00:06	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBETc
14:00:06  14:00:06	-- common/autotest_common.sh@16 -- # [[ ehxBETc == *\x* ]]
14:00:06  14:00:06	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
14:00:06  14:00:06	-- common/autotest_common.sh@19 -- # set +x
14:00:06  14:00:06	-- common/autotest_common.sh@1387 -- # xtrace_enable
14:00:06 Getting BDFs for NVMe section
14:00:06 Done getting BDFs
14:00:06 [target] Starting SPDK NVMeOF Target process
14:00:06 [target] SPDK NVMeOF Target PID=/var/perf_jenkins/workspace/nvmf-perf/tc4-tcp-spdk/spdk/nvmf.pid
14:00:06 [target] Waiting for spdk to initialize...
14:00:06 [2022-09-14 14:00:06.483503] Starting SPDK v22.09-pre git sha1 c8302d7b46f / DPDK 22.03.0 initialization...
14:00:06 [2022-09-14 14:00:06.483554] [ DPDK EAL parameters: [2022-09-14 14:00:06.483561] nvmf [2022-09-14 14:00:06.483566] --no-shconf [2022-09-14 14:00:06.483569] -l 0-11,28-39 [2022-09-14 14:00:06.483573] --huge-unlink [2022-09-14 14:00:06.483577] --log-level=lib.eal:6 [2022-09-14 14:00:06.483581] --log-level=lib.cryptodev:5 [2022-09-14 14:00:06.483584] --log-level=user1:6 [2022-09-14 14:00:06.483588] --base-virtaddr=0x200000000000 [2022-09-14 14:00:06.483592] --match-allocations [2022-09-14 14:00:06.483596] --file-prefix=spdk_pid41308 [2022-09-14 14:00:06.483599] ]
14:00:06 TELEMETRY: No legacy callbacks, legacy socket not created
14:00:06 [2022-09-14 14:00:06.543875] app.c: 586:spdk_app_start: *NOTICE*: Total cores available: 24
14:00:06 [2022-09-14 14:00:06.654838] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 1
14:00:06 [2022-09-14 14:00:06.654999] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 2
14:00:06 [2022-09-14 14:00:06.655111] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 3
14:00:06 [2022-09-14 14:00:06.655233] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 4
14:00:06 [2022-09-14 14:00:06.655328] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 5
14:00:06 [2022-09-14 14:00:06.655445] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 6
14:00:06 [2022-09-14 14:00:06.655498] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 7
14:00:06 [2022-09-14 14:00:06.655691] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 8
14:00:06 [2022-09-14 14:00:06.655743] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 9
14:00:06 [2022-09-14 14:00:06.655869] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 10
14:00:06 [2022-09-14 14:00:06.655931] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 11
14:00:06 [2022-09-14 14:00:06.655946] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 28
14:00:06 [2022-09-14 14:00:06.656025] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 29
14:00:06 [2022-09-14 14:00:06.656160] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 30
14:00:06 [2022-09-14 14:00:06.656283] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 31
14:00:06 [2022-09-14 14:00:06.656414] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 32
14:00:06 [2022-09-14 14:00:06.656464] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 33
14:00:06 [2022-09-14 14:00:06.656604] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 34
14:00:06 [2022-09-14 14:00:06.656666] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 35
14:00:06 [2022-09-14 14:00:06.656681] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 36
14:00:06 [2022-09-14 14:00:06.656803] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 37
14:00:06 [2022-09-14 14:00:06.656855] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 38
14:00:06 [2022-09-14 14:00:06.656873] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 39
14:00:06 [2022-09-14 14:00:06.656877] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 0
14:00:07 [target] Target socket options:
14:00:07 POWER: Env isn't set yet!
14:00:07 POWER: Attempting to initialise ACPI cpufreq power management...
14:00:07 POWER: Power management governor of lcore 0 has been set to 'userspace' successfully
14:00:07 POWER: failed to open /sys/devices/system/cpu/cpu%u/cpufreq/scaling_available_frequencies
14:00:07 POWER: Cannot get available frequencies of lcore 0
14:00:07 POWER: Attempting to initialise PSTAT power management...
14:00:07 POWER: Power management governor of lcore 0 has been set to 'performance' successfully
14:00:07 POWER: Initialized successfully for lcore 0 power management
14:00:07 POWER: Initialized successfully for lcore 1 power management
14:00:07 POWER: Initialized successfully for lcore 2 power management
14:00:07 POWER: Initialized successfully for lcore 3 power management
14:00:07 POWER: Initialized successfully for lcore 4 power management
14:00:07 POWER: Initialized successfully for lcore 5 power management
14:00:07 POWER: Initialized successfully for lcore 6 power management
14:00:07 POWER: Initialized successfully for lcore 7 power management
14:00:07 POWER: Initialized successfully for lcore 8 power management
14:00:07 POWER: Initialized successfully for lcore 9 power management
14:00:07 POWER: Initialized successfully for lcore 10 power management
14:00:07 POWER: Initialized successfully for lcore 11 power management
14:00:07 POWER: Initialized successfully for lcore 28 power management
14:00:07 POWER: Initialized successfully for lcore 29 power management
14:00:07 POWER: Initialized successfully for lcore 30 power management
14:00:07 POWER: Initialized successfully for lcore 31 power management
14:00:07 POWER: Initialized successfully for lcore 32 power management
14:00:07 POWER: Initialized successfully for lcore 33 power management
14:00:07 POWER: Initialized successfully for lcore 34 power management
14:00:07 POWER: Initialized successfully for lcore 35 power management
14:00:07 POWER: Initialized successfully for lcore 36 power management
14:00:07 POWER: Initialized successfully for lcore 37 power management
14:00:07 POWER: Initialized successfully for lcore 38 power management
14:00:07 POWER: Initialized successfully for lcore 39 power management
14:00:07 [2022-09-14 14:00:07.801497] scheduler_dynamic.c: 385:set_opts: *NOTICE*: Setting scheduler load limit to 20
14:00:07 [2022-09-14 14:00:07.801519] scheduler_dynamic.c: 387:set_opts: *NOTICE*: Setting scheduler core limit to 80
14:00:07 [2022-09-14 14:00:07.801525] scheduler_dynamic.c: 389:set_opts: *NOTICE*: Setting scheduler core busy to 95
14:00:07 [2022-09-14 14:00:07.805564] accel_sw.c: 377:sw_accel_engine_init: *NOTICE*: Accel framework software engine initialized.
14:00:07 [2022-09-14 14:00:07.847667] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_0) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.847692] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 [2022-09-14 14:00:07.847699] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_6) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.847705] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 [2022-09-14 14:00:07.847711] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_12) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.847716] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 [2022-09-14 14:00:07.847722] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_18) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.847727] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 [2022-09-14 14:00:07.848241] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_1) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.848269] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 [2022-09-14 14:00:07.848277] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_7) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.848282] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 [2022-09-14 14:00:07.848288] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_13) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.848294] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 [2022-09-14 14:00:07.848300] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_19) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.848306] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 [2022-09-14 14:00:07.848603] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_2) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.848626] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 [2022-09-14 14:00:07.848633] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_8) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.848639] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 [2022-09-14 14:00:07.848645] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_14) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.848651] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 [2022-09-14 14:00:07.848657] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_20) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.848663] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 [2022-09-14 14:00:07.848848] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_3) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.848869] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 [2022-09-14 14:00:07.848877] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_9) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.848882] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 [2022-09-14 14:00:07.848889] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_15) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.848895] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 [2022-09-14 14:00:07.848901] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_21) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.848907] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 [2022-09-14 14:00:07.849098] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_4) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.849123] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 [2022-09-14 14:00:07.849132] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_10) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.849138] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 [2022-09-14 14:00:07.849144] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_16) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.849150] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 [2022-09-14 14:00:07.849157] thread.c:1904:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (nvmf_tgt_poll_group_22) to intr mode from poll mode.
14:00:07 [2022-09-14 14:00:07.849163] thread.c:1887:poller_set_interrupt_mode: *ERROR*: Poller(nvmf_poll_group_poll) doesn't support set interrupt mode.
14:00:07 {
14:00:07   "recv_buf_size": 2097152,
14:00:07   "send_buf_size": 2097152,
14:00:07   "enable_recv_pipe": true,
14:00:07   "enable_quickack": false,
14:00:07   "enable_placement_id": 0,
14:00:07   "enable_zerocopy_send_server": true,
14:00:07   "enable_zerocopy_send_client": false,
14:00:07   "zerocopy_threshold": 0,
14:00:07   "tls_version": 0,
14:00:07   "enable_ktls": false
14:00:07 }
14:00:07 [target] Configuring SPDK NVMeOF target via RPC
14:00:07 [2022-09-14 14:00:07.853811] tcp.c: 613:nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
14:00:10 Traceback (most recent call last):
14:00:10   File "/var/perf_jenkins/workspace/nvmf-perf/tc4-tcp-spdk/spdk/scripts/perf/nvmf/run_nvmf.py", line 1531, in <module>
14:00:10     target_obj.tgt_start()
14:00:10   File "/var/perf_jenkins/workspace/nvmf-perf/tc4-tcp-spdk/spdk/scripts/perf/nvmf/run_nvmf.py", line 1271, in tgt_start
14:00:10     self.spdk_tgt_configure()
14:00:10   File "/var/perf_jenkins/workspace/nvmf-perf/tc4-tcp-spdk/spdk/scripts/perf/nvmf/run_nvmf.py", line 1139, in spdk_tgt_configure
14:00:10     rpc.nvmf.nvmf_create_transport(self.client, trtype=self.transport,
14:00:10   File "/var/perf_jenkins/workspace/nvmf-perf/tc4-tcp-spdk/spdk/scripts/perf/nvmf/../../../python/spdk/rpc/nvmf.py", line 131, in nvmf_create_transport
14:00:10     return client.call('nvmf_create_transport', params)
14:00:10   File "/var/perf_jenkins/workspace/nvmf-perf/tc4-tcp-spdk/spdk/scripts/perf/nvmf/../../../python/spdk/rpc/client.py", line 190, in call
14:00:10     raise e
14:00:10   File "/var/perf_jenkins/workspace/nvmf-perf/tc4-tcp-spdk/spdk/scripts/perf/nvmf/../../../python/spdk/rpc/client.py", line 183, in call
14:00:10     response = self.recv()
14:00:10   File "/var/perf_jenkins/workspace/nvmf-perf/tc4-tcp-spdk/spdk/scripts/perf/nvmf/../../../python/spdk/rpc/client.py", line 165, in recv
14:00:10     raise JSONRPCException("Connection closed with partial response:\n%s\n" % self._recv_buf)
14:00:10 spdk.rpc.client.JSONRPCException: Connection closed with partial response:
14:00:10 
14:00:10 
14:00:10 
14:00:10 Build step 'Execute shell' marked build as failure
14:00:10 Archiving artifacts
14:00:10 Finished: FAILURE
```

**Comment by changpe1** [comment] 2022-09-15 04:06
[Bug Scrub] @mikeBashStuff can we get the core dump information from target when getting this failure?

**Comment by mikeBashStuff** [comment] 2022-09-15 06:43
@changpe1 So the SPDK is not actually crashing in this scenario. I could force the core dump but I am not sure at which point I should signal the process - right after dynamic scheduler is being enabled? Or should I just attach gdb into the SPDK app and provide you with some trace output?

**Comment by changpe1** [comment] 2022-09-15 06:52
> @changpe1 So the SPDK is not actually crashing in this scenario. I could force the core dump but I am not sure at which point I should signal the process - right after dynamic scheduler is being enabled? Or should I just attach gdb into the SPDK app and provide you with some trace output?

we guess there was a coredump for this case, because there wasn't error log printed.
does this happen if we skip the dynamic scheduler?

**Comment by mikeBashStuff** [comment] 2022-09-19 15:20
> we guess there was a coredump for this case, because there wasn't error log printed.
does this happen if we skip the dynamic scheduler?

@changpe1 No, the test passes just fine under the static scheduler.

**Comment by tomzawadzki** [comment] 2022-09-20 14:49
This looks like a duplicate of #2670

**Comment by mikeBashStuff** [comment] 2022-09-30 14:48
After closer inspection it seems like the app indeed crashes in this scenario (this was missed due to the core setup on the benchmark systems). Attaching cores here:

[core_dynamic.zip](https://github.com/spdk/spdk/files/9685473/core_dynamic.zip)
[core_dynamic_lto_debug.zip](https://github.com/spdk/spdk/files/9685475/core_dynamic_lto_debug.zip)

@tomzawadzki pointed out a potential workaround for this issue (thanks!) which I pushed here: https://review.spdk.io/gerrit/c/spdk/spdk/+/14814

**Closed** 2022-09-30 16:14 UTC
Labels: bug, Medium
