### ISSUE TITLE
nvmf/bdev_nvme: Unable to remove device when cmd is queued in bdev nomem_io

### ISSUE THREAD

**Issue by mhae** [spdk/spdk#2484] opened 2022-04-25 15:22 UTC
# Bug report

This is a scenario with nvmf_tgt (NVMF/RDMA & bdev_nvme) and an unresponsive device.

When an admin/IO command is queued in bdev's nomem_io, it is no longer possible to remove the NVMe device.

This is due to the fact that the NVMF frontend is still tracking the cmd in mgmt_io_outstanding or io_outstanding which prevents the subsystem pause that is needed to fully remove the device (see nvmf_poll_group_pause_subsystem).

Since the cmd is stuck in the bdev layer and not tracked in the PCIe layer (nvme_pcie trackers), there is no way to manually abort it. The manual abort code lives in the nvme_pcie layer and is executed during a hot remove. But since the cmd is not tracked there, it can't be completed which in turn prevents the completion of the command in the NVMF layer (with subsequent decrement of mgmt_io_outstanding or io_outstanding).

The result is that the device can't be removed from the bdev_nvme layer.

## Context (Environment including OS version, SPDK version, etc.)

Debian 10, SPDK 21.04 (but is applicable to all versions).

**Comment by Comphix** [comment] 2022-04-27 01:55
Shuhei, please give some feedback on this issue.

In our latest SPDK code, is the admin IO on the bdev could be aborted?

**Comment by jimharris** [comment] 2022-04-27 02:24
> Shuhei, please give some feedback on this issue.
> 
> In our latest SPDK code, is the admin IO on the bdev could be aborted?

When a bdev is unregistered, we need to do an spdk_for_each_channel() and abort all of the nomem_io.  Not just nomem_io, but also queued_resets, need_buf_small and need_buf_large.

We do this in bdev_channel_destroy(), but that only gets called when the upper layer puts the channel.  In the nvmf case, it is waiting for all of the outstanding I/O to complete before it will put the channel.

Currently spdk_bdev_unregister() sets state to REMOVING, and then calls bdev_unregister_safe().  I think we need to do the spdk_for_each_channel() before bdev_unregister_safe() - don't call bdev_unregister_safe() until the spdk_for_each_channel() completion routine.

If someone would like to pick this up, that would be great, otherwise I can take a look at it in the next few days.

**Comment by shuhei-matsumoto** [comment] 2022-04-27 03:50
Thank you @jimharris I will start from checking your comment first. I do not say strongly I want to do and you will be better to do though :)

**Comment by Comphix** [comment] 2022-04-28 06:23
Looking at this issue.

**Comment by Comphix** [comment] 2022-05-06 14:25
WIP patch raised: https://review.spdk.io/gerrit/c/spdk/spdk/+/12573

**Comment by Comphix** [comment] 2022-05-10 01:04
Patch is under review. @mhae will you have a try to verify this. Thanks.

**Comment by mhae** [comment] 2022-05-10 02:39
Sure, do we think this is pretty close? It’s going to take quite a bit of time to integrate the patch and set up the test.

**Comment by jimharris** [comment] 2022-05-10 02:57
> Sure, do we think this is pretty close? It’s going to take quite a bit of time to integrate the patch and set up the test.
> […](#)

Hi @mhae I haven’t reviewed the patch yet, let me take a look first and will let you know when we think it’s ready for your integration and test.

**Comment by shuhei-matsumoto** [comment] 2022-05-10 04:23
Hi @jimharris I reviewed the patch today. The following is my feedback.
- we can exclude ch->queued_resets from abort iteration. ch->queued_resets is fixed by another patch https://github.com/spdk/spdk/commit/494eb6e58b8e72762d0a2127f2657926298e2523
- we can execute abort iteration after bdev_unregister_unsafe() returns 0.

Both are slightly different from your idea.

**Comment by Comphix** [comment] 2022-05-10 07:14
Thanks Shuhei for the comments. Let's wait Jim's feedback. For the abort of resets, it's slightly different, here related change is to handle the case that the reset is aborted due to the unregister operation.

**Comment by shuhei-matsumoto** [comment] 2022-05-10 07:36
Hi @Comphix It may be not intuitive. An outstanding reset request is also in the ch->queued_resets. The outstanding reset request is not queued but can complete by itself. So I think we do not need to abort the outstanding reset request. When the outstanding abort request completes, it aborts all pending reset requests. The unregister operation and the reset request do not need to stop each other. Hence I think we need to consider only queued I/Os as reported by Michael. Yes, let's wait for Jim's comment.

**Comment by jimharris** [comment] 2022-05-11 00:21
> Hi @Comphix It may be not intuitive. An outstanding reset request is also in the ch->queued_resets. The outstanding reset request is not queued but can complete by itself. So I think we do not need to abort the outstanding reset request. When the outstanding abort request completes, it aborts all pending reset requests. The unregister operation and the reset request do not need to stop each other. Hence I think we need to consider only queued I/Os as reported by Michael. Yes, let's wait for Jim's comment.

I agree, we don't need to abort the queued_resets in this path.  I posted some other comments too.  Ultimately we really need a unit test that exactly reproduces the scenario that @mhae has described here.

**Comment by Comphix** [comment] 2022-05-12 01:55
New patch updates have been raised and also covered the suggested unit tests.

**Comment by mhae** [comment] 2022-05-12 23:42
Thanks. I'll take a look Friday.

**Comment by shuhei-matsumoto** [comment] 2022-05-16 02:53
Hi @Comphix @mhae @jimharris 

If I understanding correctly, after the NVMF frontend got a notification for unregistration, it waits until all outstanding I/Os are returned and then it closes the bdev. However, I/Os queued in the nomem_io list were not aborted. Hence the NVMf frontend could not close the bdev.

Gang's patch will fix this issue. However I may find a small window to submit I/Os between the spdk_bdev_unregister() call and the unregistration notification. The user still can submit I/Os to the bdev even after spdk_bdev_unregister() is called, and these may be queued into the nomem_io list.

Should we prohibit the user to submit I/Os to the unregistering bdev? One idea is that bdev_channel_get_io() check if the channel is still available (spdk_bdev_unregister() is not called).

**Comment by Comphix** [comment] 2022-05-16 03:45
Or maybe check the SPDK_BDEV_STATUS_REMOVING state when submitting the IO?

**Comment by shuhei-matsumoto** [comment] 2022-05-16 03:56
I think adding BDEV_CH_UNREGISTERING or BDEV_CH_UNREGISTER_IN_PROGRESS (1 << 2) to struct spdk_bdev_channel::flags is a little more cache friendly idea.

**Comment by jimharris** [comment] 2022-05-16 18:38
> I think adding BDEV_CH_UNREGISTERING or BDEV_CH_UNREGISTER_IN_PROGRESS (1 << 2) to struct spdk_bdev_channel::flags is a little more cache friendly idea. But I want to get consensus about this point is reasonable or not.

This would require adding a new spdk_for_each_channel to set this flag.  That might be OK, but does add some additional complexity.

Another alternative would be to acquire the bdev's mutex when we receive NOMEM on a completion, check the bdev's status, and if it is REMOVING, then just immediately abort the I/O.

But I actually think the additional complexity is worth it.  If we have this flag on the bdev channel, we can actually abort the I/O immediately, rather than allowing it to be submitted and then waiting for it complete.  So I would vote for Shuhei's idea.

Let's add that in a separate patch though - not in the one posted earlier by @Comphix.

**Comment by shuhei-matsumoto** [comment] 2022-05-18 02:22
Hi @Comphix Please check my new comment on gerrit. I think adding a new status UNREGISTERING between READY and REMOVING may fix the error you saw very simply. Thanks for your patience and hard work.

**Comment by Comphix** [comment] 2022-05-20 00:45
Close this as patch merged. Please let us know if there is any further issue.

Thanks for reporting this.

**Closed by Comphix** 2022-05-20 00:45 UTC
Labels: bug, Medium, Patches out for review
