### ISSUE TITLE
the newly code  executes vm_setup.sh - i failed in VM

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#670] opened 2019-02-18 02:39 UTC
When I verify the newly code in VM , execute vm_setup.sh - i ,  there are several failures ..

## Expected Behavior
In VM , execute   vm_setup.sh - i  can pass.

## Current Behavior
 execute vm_setup.sh - i , blocked by several  failures  .

1. spdk code downloading may need run this command as root user.
2. OCF module need account or other.
3. some submodules in qemu git clone failed.
...

## Steps to Reproduce
create a vm fedora28 , and run vm_setup.sh - i.
or use other scripts to do this.

## Context (Environment including OS version, SPDK version, etc.)
commit 8ad0935b816ec6b65bcad29e2ca461ef16b1ffa1

**Comment by Donaim** [comment] 2019-02-19 08:51
Hi @yidong0635,
I investigated behavior you encountered and:
1. This was a bug, fix is proposed: [commit](https://review.gerrithub.io/c/spdk/spdk/+/445248) . The bug was caused by expectation that ~/spdk_repo is owned by user, which is not always the case.
2. Also a bug, [this patch](https://review.gerrithub.io/c/spdk/spdk/+/445249) fixes it. Issue was that script used worng for OCF repo, which made github prompt user login to see if that url points to a private repo.
3. qemu install is known to go wrong when proxy is used. Did you use proxy?

Did you have other observations? If so, feel free to post them here because it is most probable that those issues are not connected and need their own patch to be fixed.

**Comment by yidong0635** [comment] 2019-02-19 09:33
@Donaim ，thanks for your commits，
 1,2:  I will verify it several days later for I'm not in office.
 3.     Already use the proxy. I don't know if it  occurs only with our proxy.
I will continue to observe.

**Comment by yidong0635** [comment] 2019-02-22 05:21
hi    @Donaim:
1.  fail message 1

> _Connection to 127.0.0.1 closed.
>  12:37:30       # vagrant_run_cmd 'sudo spdk_repo/spdk/test/common/config/vm_setup.sh -i'
>   12:37:30      # vagrant_get_id
>   12:37:30      # vagrant global-status
>   12:37:30      # grep /home/yique/fedora28-virtualbox
>   12:37:30      # awk '{print $1}'
>  12:37:31       # vagrant ssh 8ebc490 -c 'sudo spdk_repo/spdk/test/common/config/vm_setup.sh -i'
> Last metadata expiration check: 0:08:20 ago on Thu 21 Feb 2019 08:29:14 PM PST.
> Package git-2.17.2-2.fc28.x86_64 is already installed, skipping.
> Dependencies resolved.
> Nothing to do.
> Complete!
> Cloning into 'spdk'...
> remote: Counting objects: 68365, done
> remote: Finding sources: 100% (68365/68365)
> fatal: The remote end hung up unexpectedly56 MiB | 35.00 KiB/s
> fatal: early EOF
> fatal: index-pack failed
> Connection to 127.0.0.1 closed._

2. apply your patch:  but add ` sudo su`   to work as a root user can pass  before git clone .  maybe some module like ISA-L  need root right, I'm not sure about it.

> Complete!
> Connection to 127.0.0.1 closed.
>  13:03:29       # vagrant_run_cmd 'sudo spdk_repo/spdk/test/common/config/vm_setup.sh -i'
>   13:03:29      # vagrant_get_id
>   13:03:29      # vagrant global-status
>   13:03:29      # grep /home/yique/fedora28-virtualbox
>   13:03:29      # awk '{print $1}'
>  13:03:30       # vagrant ssh 8ebc490 -c 'sudo spdk_repo/spdk/test/common/config/vm_setup.sh -i'
> Last metadata expiration check: 0:07:57 ago on Thu 21 Feb 2019 08:55:37 PM PST.
> Package git-2.17.2-2.fc28.x86_64 is already installed, skipping.
> Dependencies resolved.
> Nothing to do.
> Complete!
> stat: cannot stat 'spdk_repo': No such file or directory
> chown: cannot access 'spdk_repo': No such file or directory
> Connection to 127.0.0.1 closed.
>

**Comment by yidong0635** [comment] 2019-02-25 02:49
I  revised the scripts (add sudo before some git commands)and apply your patch:
```
sudo su &
mkdir -p spdk_repo/output

# Ensure spdk_repo is owned by user
# It is sometimes not when installing from vagrant script
if [[ "$USER" != "$(stat -c %U spdk_repo)" ]]; then
    sudo chown -R $USER:$USER spdk_repo
fi
if [ -d spdk_repo/spdk ]; then
    echo "spdk source already present, not cloning"
else
    sudo git -C spdk_repo clone "${GIT_REPO_SPDK}"
fi
sudo git -C spdk_repo/spdk config submodule.dpdk.url "${GIT_REPO_DPDK}"
sudo git -C spdk_repo/spdk config submodule.intel-ipsec-mb.url "${GIT_REPO_INTEL_IPSEC_MB}"
sudo git -C spdk_repo/spdk submodule update --init --recursive

```
 and found there were still qemu downloading issues:
make: Entering directory '/root/qemu/spdk-3.0.0' | 764.00 KiB/s
  GEN     x86_64-softmmu/config-devices.mak.tmp
  GEN     config-host.h
  GIT     ui/keycodemapdb dtc capstone
  GEN     qemu-options.def
  GEN     qapi-gen
  GEN     trace/generated-tcg-tracers.h
  GEN     trace/generated-helpers.h
  GEN     trace/generated-helpers-wrappers.h
  GEN     trace/generated-helpers.c
  GEN     module_block.h
  GEN     tests/test-qapi-gen
  GEN     trace-root.h
  GEN     accel/kvm/trace.h
  GEN     accel/tcg/trace.h
  GEN     audio/trace.h
  GEN     x86_64-softmmu/config-devices.mak
  GEN     block/trace.h
  GEN     chardev/trace.h
  GEN     crypto/trace.h
  GEN     hw/9pfs/trace.h
  GEN     hw/acpi/trace.h
  GEN     hw/alpha/trace.h7799/61875), 78.79 MiB | 797.00 KiB/s
  GEN     hw/arm/trace.h
  GEN     hw/audio/trace.h
  GEN     hw/block/trace.h
  GEN     hw/block/dataplane/trace.h
  GEN     hw/char/trace.h
  GEN     hw/display/trace.h
  GEN     hw/dma/trace.h
  GEN     hw/hppa/trace.h
  GEN     hw/i2c/trace.h
  GEN     hw/i386/trace.h
  GEN     hw/i386/xen/trace.h
  GEN     hw/ide/trace.h
  GEN     hw/input/trace.h
  GEN     hw/intc/trace.h
  GEN     hw/isa/trace.h
  GEN     hw/mem/trace.h
  GEN     hw/misc/trace.h
  GEN     hw/misc/macio/trace.h
  GEN     hw/net/trace.h
  GEN     hw/nvram/trace.h
  GEN     hw/pci/trace.h
  GEN     hw/pci-host/trace.h
  GEN     hw/ppc/trace.h
  GEN     hw/rdma/trace.h
  GEN     hw/rdma/vmw/trace.h
  GEN     hw/s390x/trace.h
  GEN     hw/scsi/trace.h
  GEN     hw/sd/trace.h
  GEN     hw/sparc/trace.h
  GEN     hw/sparc64/trace.h
  GEN     hw/timer/trace.h
Submodule 'capstone' (git://git.qemu.org/capstone.git) registered for path 'capstone'
Submodule 'dtc' (git://git.qemu-project.org/dtc.git) registered for path 'dtc'
  GEN     hw/tpm/trace.h
Submodule 'ui/keycodemapdb' (git://git.qemu.org/keycodemapdb.git) registered for path 'ui/keycodemapdb'
  GEN     hw/usb/trace.h
Cloning into '/root/qemu/spdk-3.0.0/capstone'...
  GEN     hw/vfio/trace.h
  GEN     hw/virtio/trace.h
  GEN     hw/xen/trace.h
  GEN     io/trace.h
18:09:09 libtsocks(49568): Could not open socks configuration file (/etc/tsocks.conf), assuming all networks local
  GEN     linux-user/trace.h
  GEN     migration/trace.h
  GEN     nbd/trace.h
  GEN     net/trace.h
  GEN     qapi/trace.h
  GEN     qom/trace.h
  GEN     scsi/trace.h
  GEN     target/arm/trace.h
  GEN     target/i386/trace.h
  GEN     target/mips/trace.h
  GEN     target/ppc/trace.h
  GEN     target/s390x/trace.h
  GEN     target/sparc/trace.h
  GEN     ui/trace.h
  GEN     util/trace.h
  GEN     trace-root.c
  GEN     accel/kvm/trace.c
  GEN     accel/tcg/trace.c
  GEN     audio/trace.c
  GEN     block/trace.c
  GEN     chardev/trace.c
  GEN     crypto/trace.c
  GEN     hw/9pfs/trace.c
  GEN     hw/acpi/trace.c
  GEN     hw/alpha/trace.c
  GEN     hw/arm/trace.c
  GEN     hw/audio/trace.c
  GEN     hw/block/trace.c
  GEN     hw/block/dataplane/trace.c
  GEN     hw/char/trace.c
  GEN     hw/display/trace.c
  GEN     hw/dma/trace.c
  GEN     hw/hppa/trace.c
  GEN     hw/i2c/trace.c
  GEN     hw/i386/trace.c
  GEN     hw/i386/xen/trace.c
  GEN     hw/ide/trace.c
  GEN     hw/input/trace.c
  GEN     hw/intc/trace.c
  GEN     hw/isa/trace.c
  GEN     hw/mem/trace.c
  GEN     hw/misc/trace.c
  GEN     hw/misc/macio/trace.c
  GEN     hw/net/trace.c
  GEN     hw/nvram/trace.c
  GEN     hw/pci/trace.c
  GEN     hw/pci-host/trace.c
  GEN     hw/ppc/trace.c
  GEN     hw/rdma/trace.c
  GEN     hw/rdma/vmw/trace.c
  GEN     hw/s390x/trace.c
  GEN     hw/scsi/trace.c
  GEN     hw/sd/trace.c
  GEN     hw/sparc/trace.c
  GEN     hw/sparc64/trace.c
  GEN     hw/timer/trace.c
  GEN     hw/tpm/trace.c
  GEN     hw/usb/trace.c
  GEN     hw/vfio/trace.c
  GEN     hw/virtio/trace.c
  GEN     hw/xen/trace.c
  GEN     io/trace.c
  GEN     linux-user/trace.c
  GEN     migration/trace.c
  GEN     nbd/trace.c
  GEN     net/trace.c
  GEN     qapi/trace.c
  GEN     qom/trace.c
  GEN     scsi/trace.c
  GEN     target/arm/trace.c
  GEN     target/i386/trace.c
  GEN     target/mips/trace.c
  GEN     target/ppc/trace.c
  GEN     target/s390x/trace.c
  GEN     target/sparc/trace.c
  GEN     ui/trace.c
  GEN     util/trace.c
  GEN     config-all-devices.mak
remote: Total 61875 (delta 46453), reused 61854 (delta 46453)
Receiving objects: 100% (61875/61875), 102.76 MiB | 791.00 KiB/s, done.
Resolving deltas: 100% (46453/46453), done.
Branch 'spdk-v5.6.1' set up to track remote branch 'spdk-v5.6.1' from 'origin'.
Switched to a new branch 'spdk-v5.6.1'
fatal: unable to connect to git.qemu.org:
git.qemu.org[0: 172.99.69.163]: errno=Connection timed out

fatal: clone of 'git://git.qemu.org/capstone.git' into submodule path '/root/qemu/spdk-3.0.0/capstone' failed
Failed to clone 'capstone'. Retry scheduled
Cloning into '/root/qemu/spdk-3.0.0/dtc'...
18:11:21 libtsocks(50338): Could not open socks configuration file (/etc/tsocks.conf), assuming all networks local
fatal: unable to connect to git.qemu-project.org:
git.qemu-project.org[0: 172.99.69.163]: errno=Connection timed out

fatal: clone of 'git://git.qemu-project.org/dtc.git' into submodule path '/root/qemu/spdk-3.0.0/dtc' failed
Failed to clone 'dtc'. Retry scheduled
Cloning into '/root/qemu/spdk-3.0.0/ui/keycodemapdb'...
18:13:32 libtsocks(50371): Could not open socks configuration file (/etc/tsocks.conf), assuming all networks local
fatal: unable to connect to git.qemu.org:
git.qemu.org[0: 172.99.69.163]: errno=Connection timed out

fatal: clone of 'git://git.qemu.org/keycodemapdb.git' into submodule path '/root/qemu/spdk-3.0.0/ui/keycodemapdb' failed
Failed to clone 'ui/keycodemapdb'. Retry scheduled
Cloning into '/root/qemu/spdk-3.0.0/capstone'...
18:15:43 libtsocks(50373): Could not open socks configuration file (/etc/tsocks.conf), assuming all networks local
fatal: unable to connect to git.qemu.org:
git.qemu.org[0: 172.99.69.163]: errno=Connection timed out

fatal: clone of 'git://git.qemu.org/capstone.git' into submodule path '/root/qemu/spdk-3.0.0/capstone' failed
Failed to clone 'capstone' a second time, aborting
./scripts/git-submodule.sh: failed to update modules

Unable to automatically checkout GIT submodules ' ui/keycodemapdb dtc capstone'.
If you require use of an alternative GIT binary (for example to
enable use of a transparent proxy), then please specify it by
running configure by with the '--with-git' argument. e.g.

 $ ./configure --with-git='tsocks git'

Alternatively you may disable automatic GIT submodule checkout
with:

 $ ./configure --disable-git-update

and then manually update submodules prior to running make, with:

 $ scripts/git-submodule.sh update  ui/keycodemapdb dtc capstone

make: *** [Makefile:45: git-submodule-update] Error 1
make: Leaving directory '/root/qemu/spdk-3.0.0'

**Comment by Donaim** [comment] 2019-02-27 09:02
1. Now it looks like you have issues with internet connection. This error is not reproducible on stable connection.
> fatal: The remote end hung up unexpectedly56 MiB | 35.00 KiB/s

2. This error is consequence of first step failure or of using sudo when running the script. Until you get success on cloning spdk_repo, following steps will almost definetely fail.
> stat: cannot stat 'spdk_repo': No such file or directory

Could you please show commands that you use prior to vm_setup.sh -i ? If you use vagrant script to build vm box, it also does some setup that is important. With [this patch](https://review.gerrithub.io/c/spdk/spdk/+/445248), the script should be run without sudo.

**Comment by yidong0635** [comment] 2019-02-27 09:26
@Donaim ,
Today ,I try it again, and the results as below:
1. confirm connection issue.
2. your patch need to revise a bit , but I'm not sure it's useful.
3. I already set the right proxy , otherwise, I can't download other parts.

**Comment by yidong0635** [comment] 2019-03-05 03:02
@Donaim , sorry for ignoring something:
2. let me explain, only clean code with your patch still report .
stat: cannot stat 'spdk_repo': No such file or directory
chown: cannot access 'spdk_repo': No such file or directory
maybe my comment is not right.
3. still blocked .

I use vagrant command to run this. I will check it again.
sudo spdk_repo/spdk/test/common/config/vm_setup.sh -i.

**Comment by yidong0635** [comment] 2019-03-05 03:21
@Donaim , 
you are right  with that the script should be run without sudo.
should we add some judgement for "using sudo report errors"?
and submodules are still failed

**Comment by yidong0635** [comment] 2019-03-05 05:06
collections:
Submodule 'capstone' (git://git.qemu.org/capstone.git) registered for path 'capstone'
  GEN     hw/usb/trace.h
Submodule 'dtc' (git://git.qemu-project.org/dtc.git) registered for path 'dtc'
Submodule 'ui/keycodemapdb' (git://git.qemu.org/keycodemapdb.git) registered for path 'ui/keycodemapdb'
  GEN     hw/vfio/trace.h
Cloning into '/home/vagrant/qemu/spdk-3.0.0/capstone'...
  GEN     hw/virtio/trace.h
  GEN     hw/xen/trace.h
  GEN     io/trace.h
**20:51:09 libtsocks(80222): Could not open socks configuration file (/etc/tsocks.conf), assuming all networks local**
GEN     linux-user/trace.h
  GEN     migration/trace.h
  GEN     nbd/trace.h
  GEN     net/trace.h
  GEN     qapi/trace.h
  GEN     qom/trace.h
  GEN     scsi/trace.h
  GEN     target/arm/trace.h
  GEN     target/i386/trace.h
  GEN     target/mips/trace.h
  GEN     target/ppc/trace.h
  GEN     target/s390x/trace.h
  GEN     target/sparc/trace.h
  GEN     ui/trace.h
  GEN     util/trace.h
  GEN     trace-root.c
  GEN     accel/kvm/trace.c
  GEN     accel/tcg/trace.c
  GEN     audio/trace.c
  GEN     block/trace.c
  GEN     chardev/trace.c
  GEN     crypto/trace.c
  GEN     hw/9pfs/trace.c
  GEN     hw/acpi/trace.c
  GEN     hw/alpha/trace.c
  GEN     hw/arm/trace.c
  GEN     hw/audio/trace.c
  GEN     hw/block/trace.c
  GEN     hw/block/dataplane/trace.c
  GEN     hw/char/trace.c
  GEN     hw/display/trace.c
  GEN     hw/dma/trace.c
  GEN     hw/hppa/trace.c
  GEN     hw/i2c/trace.c
  GEN     hw/i386/trace.c
  GEN     hw/i386/xen/trace.c
  GEN     hw/ide/trace.c
  GEN     hw/input/trace.c
  GEN     hw/intc/trace.c
  GEN     hw/isa/trace.c
  GEN     hw/mem/trace.c
  GEN     hw/misc/trace.c
  GEN     hw/misc/macio/trace.c
  GEN     hw/net/trace.c
  GEN     hw/nvram/trace.c
  GEN     hw/pci/trace.c
  GEN     hw/pci-host/trace.c
  GEN     hw/ppc/trace.c
  GEN     hw/rdma/trace.c
  GEN     hw/rdma/vmw/trace.c
  GEN     hw/s390x/trace.c
  GEN     hw/scsi/trace.c
  GEN     hw/sd/trace.c
  GEN     hw/sparc/trace.c
  GEN     hw/sparc64/trace.c
  GEN     hw/timer/trace.c
  GEN     hw/tpm/trace.c
  GEN     hw/usb/trace.c
  GEN     hw/vfio/trace.c
  GEN     hw/virtio/trace.c
  GEN     hw/xen/trace.c
  GEN     io/trace.c
  GEN     linux-user/trace.c
  GEN     migration/trace.c
  GEN     nbd/trace.c
  GEN     net/trace.c
  GEN     qapi/trace.c
  GEN     qom/trace.c
  GEN     scsi/trace.c
  GEN     target/arm/trace.c
  GEN     target/i386/trace.c
  GEN     target/mips/trace.c
  GEN     target/ppc/trace.c
  GEN     target/s390x/trace.c
  GEN     target/sparc/trace.c
  GEN     ui/trace.c
  GEN     util/trace.c
  GEN     config-all-devices.mak
fatal: unable to connect to git.qemu.org:
git.qemu.org[0: 172.99.69.163]: errno=Connection timed out

fatal: clone of 'git://git.qemu.org/capstone.git' into submodule path '/home/vagrant/qemu/spdk-3.0.0/capstone' failed
Failed to clone 'capstone'. Retry scheduled
Cloning into '/home/vagrant/qemu/spdk-3.0.0/dtc'...
20:53:18 libtsocks(80903): Could not open socks configuration file (/etc/tsocks.conf), assuming all networks local
fatal: unable to connect to git.qemu-project.org:
git.qemu-project.org[0: 172.99.69.163]: errno=Connection timed out

fatal: clone of 'git://git.qemu-project.org/dtc.git' into submodule path '/home/vagrant/qemu/spdk-3.0.0/dtc' failed
Failed to clone 'dtc'. Retry scheduled
Cloning into '/home/vagrant/qemu/spdk-3.0.0/ui/keycodemapdb'...
20:55:29 libtsocks(89872): Could not open socks configuration file (/etc/tsocks.conf), assuming all networks local
fatal: unable to connect to git.qemu.org:
git.qemu.org[0: 172.99.69.163]: errno=Connection timed out

fatal: clone of 'git://git.qemu.org/keycodemapdb.git' into submodule path '/home/vagrant/qemu/spdk-3.0.0/ui/keycodemapdb' failed
Failed to clone 'ui/keycodemapdb'. Retry scheduled
Cloning into '/home/vagrant/qemu/spdk-3.0.0/capstone'...

**Comment by Donaim** [comment] 2019-03-07 09:57
@yidong0635 is it correct that, at this point, the only failing step for you is QEMU submodules installation?
Regarding it, you have to configure your proxy on VM using tsocks conf file at /etc/tsocks.conf.

As for your suggestion about adding "using sudo report errors" - script already contains simmilar notice:
https://github.com/spdk/spdk/blob/master/test/common/config/vm_setup.sh#L305

**Comment by yidong0635** [comment] 2019-03-07 11:06
@Donaim  I use fedora28 ,  I try it as a non-root user.
1. there's no  this file :/etc/tsocks.conf. downloading failed. so qemu failed.   
2. vpp compile failed. already submit a patch about rpmbuild  command not found. and then compile VPP.
3.run as non-root user , why it still report  no pandas ? I run it before as root user , already 
 add python3-pandas package in list, test will not report error.

**Comment by darsto** [comment] 2019-03-26 15:48
Bug scrub: the initial patch is out, still has some VPP-related issues and @tkulasek is working on those.

**Comment by tkulasek** [comment] 2019-04-09 14:11
VPP 18.01.1 doesn't compile in Fedora 28. It is caused by glibc 2.27 incompatibilities, nasm 2.13 used here doesn't compile with gcc8 and some minor warnings treated as errors in gcc8.
Here is WIP patch to show the complexity to achieve compatibility of VPP 18.01.1 with Fedora 28: https://review.gerrithub.io/c/spdk/spdk/+/450238
Newer versions of VPP compiles well with Fedora 28. While we consider to move to the VPP 19.01.1 soon, It's worth to consider to disable VPP 18.01.1 for this case and mark as unsupported.

**Comment by yidong0635** [comment] 2019-04-17 05:30
@tkulasek , thanks for your efforts. And the WIP patch is ok.  
It seems install_vpp will install some old packages that will covered the new packages like python3-pandas/... .

**Comment by tkulasek** [comment] 2019-04-23 12:22
@yidong0635 @Donaim final version of vpp fix is here: https://review.gerrithub.io/c/spdk/spdk/+/450238

**Comment by yidong0635** [comment] 2019-04-28 10:53
@tkulasek thanks, this patch for vpp compiling is ok.
may need effort to  this :
        its environment dependency about vpp , installed some old packages on fedora which could covered the packages that installed by  "dnf install -y " .  we can leave this to another patch.

**Comment by darsto** [comment] 2019-05-21 15:08
Bug scrub: it's better to update to newer VPP version, which already works with gcc8 and glibc 2.27.

@tkulasek is already working on it.

**Comment by Donaim** [comment] 2019-06-03 08:32
@yidong0635 have you got other issues related to this topic other than QEMU install? I suggest closing this thread.

**Comment by yidong0635** [comment] 2019-06-03 08:49
ok , thanks for all your efforts.

**Closed** 2019-06-03 08:50 UTC
Labels: enhancement
