### ISSUE TITLE
Unable to create more than 63 namespaces in a subsystem using JSON RPC

### ISSUE THREAD

**Issue by aneeeshp3** [spdk/spdk#232] opened 2018-01-30 08:43 UTC
When trying to create a subsystem in nvmf target, the maximum number of namespaces that could be included in a subsystem is 63. When there are more namespaces in the list, then construct_nvmf_subsystem RPC method errors out with error 'Invalid parameters'. Debug log shows:

nvmf_rpc.c: 374:spdk_rpc_construct_nvmf_subsystem: *ERROR*: spdk_json_decode_object failed
jsonrpc_server_tcp.c: 234:spdk_jsonrpc_server_conn_recv: *INFO*: remote closed connection
jsonrpc_server_tcp.c: 346:spdk_jsonrpc_server_poll: *INFO*: all outstanding requests completed

Issue is observed in master as well as 17.10.x branch

**Comment by aneeeshp3** [comment] 2018-01-30 08:45
rpc.py command & response
--------------------------------
[root@localhost spdk]# python scripts/rpc.py -v construct_nvmf_subsystem -a -s SPDK00000000000010 -n 'Malloc0 Malloc1 Malloc2 Malloc3 Malloc4 Malloc5 Malloc6 Malloc7 Malloc8 Malloc9 Malloc10 Malloc11 Malloc12 Malloc13 Malloc14 Malloc15 Malloc16 Malloc17 Malloc18 Malloc19 Malloc20 Malloc21 Malloc22 Malloc23 Malloc24 Malloc25 Malloc26 Malloc27 Malloc28 Malloc29 Malloc30 Malloc31 Malloc32 Malloc33 Malloc34 Malloc35 Malloc36 Malloc37 Malloc38 Malloc39 Malloc40 Malloc41 Malloc42 Malloc43 Malloc44 Malloc45 Malloc46 Malloc47 Malloc48 Malloc49 Malloc50 Malloc51 Malloc52 Malloc53 Malloc54 Malloc55 Malloc56 Malloc57 Malloc58 Malloc59 Malloc60 Malloc61 Malloc62 Malloc63' nqn.2016-06.io.spdk:cnode3 'trtype:RDMA traddr:192.168.122.3 trsvcid:4423' nqn.2016-06.io.spdk:myhost
request:
{
  "params": {
    "listen_addresses": [
      {
        "trtype": "RDMA",
        "trsvcid": "4423",
        "traddr": "192.168.122.3"
      }
    ],
    "hosts": [
      "nqn.2016-06.io.spdk:myhost"
    ],
    "namespaces": [
      {
        "bdev_name": "Malloc0"
      },
      {
        "bdev_name": "Malloc1"
      },
      {
        "bdev_name": "Malloc2"
      },
      {
        "bdev_name": "Malloc3"
      },
      {
        "bdev_name": "Malloc4"
      },
      {
        "bdev_name": "Malloc5"
      },
      {
        "bdev_name": "Malloc6"
      },
      {
        "bdev_name": "Malloc7"
      },
      {
        "bdev_name": "Malloc8"
      },
      {
        "bdev_name": "Malloc9"
      },
      {
        "bdev_name": "Malloc10"
      },
      {
        "bdev_name": "Malloc11"
      },
      {
        "bdev_name": "Malloc12"
      },
      {
        "bdev_name": "Malloc13"
      },
      {
        "bdev_name": "Malloc14"
      },
      {
        "bdev_name": "Malloc15"
      },
      {
        "bdev_name": "Malloc16"
      },
      {
        "bdev_name": "Malloc17"
      },
      {
        "bdev_name": "Malloc18"
      },
      {
        "bdev_name": "Malloc19"
      },
      {
        "bdev_name": "Malloc20"
      },
      {
        "bdev_name": "Malloc21"
      },
      {
        "bdev_name": "Malloc22"
      },
      {
        "bdev_name": "Malloc23"
      },
      {
        "bdev_name": "Malloc24"
      },
      {
        "bdev_name": "Malloc25"
      },
      {
        "bdev_name": "Malloc26"
      },
      {
        "bdev_name": "Malloc27"
      },
      {
        "bdev_name": "Malloc28"
      },
      {
        "bdev_name": "Malloc29"
      },
      {
        "bdev_name": "Malloc30"
      },
      {
        "bdev_name": "Malloc31"
      },
      {
        "bdev_name": "Malloc32"
      },
      {
        "bdev_name": "Malloc33"
      },
      {
        "bdev_name": "Malloc34"
      },
      {
        "bdev_name": "Malloc35"
      },
      {
        "bdev_name": "Malloc36"
      },
      {
        "bdev_name": "Malloc37"
      },
      {
        "bdev_name": "Malloc38"
      },
      {
        "bdev_name": "Malloc39"
      },
      {
        "bdev_name": "Malloc40"
      },
      {
        "bdev_name": "Malloc41"
      },
      {
        "bdev_name": "Malloc42"
      },
      {
        "bdev_name": "Malloc43"
      },
      {
        "bdev_name": "Malloc44"
      },
      {
        "bdev_name": "Malloc45"
      },
      {
        "bdev_name": "Malloc46"
      },
      {
        "bdev_name": "Malloc47"
      },
      {
        "bdev_name": "Malloc48"
      },
      {
        "bdev_name": "Malloc49"
      },
      {
        "bdev_name": "Malloc50"
      },
      {
        "bdev_name": "Malloc51"
      },
      {
        "bdev_name": "Malloc52"
      },
      {
        "bdev_name": "Malloc53"
      },
      {
        "bdev_name": "Malloc54"
      },
      {
        "bdev_name": "Malloc55"
      },
      {
        "bdev_name": "Malloc56"
      },
      {
        "bdev_name": "Malloc57"
      },
      {
        "bdev_name": "Malloc58"
      },
      {
        "bdev_name": "Malloc59"
      },
      {
        "bdev_name": "Malloc60"
      },
      {
        "bdev_name": "Malloc61"
      },
      {
        "bdev_name": "Malloc62"
      },
      {
        "bdev_name": "Malloc63"
      }
    ],
    "allow_any_host": true,
    "serial_number": "SPDK00000000000010",
    "nqn": "nqn.2016-06.io.spdk:cnode3"
  },
  "jsonrpc": "2.0",
  "method": "construct_nvmf_subsystem",
  "id": 1
}
Got JSON-RPC error response
request:
{
  "jsonrpc": "2.0",
  "params": {
    "listen_addresses": [
      {
        "trtype": "RDMA",
        "trsvcid": "4423",
        "traddr": "192.168.122.3"
      }
    ],
    "hosts": [
      "nqn.2016-06.io.spdk:myhost"
    ],
    "namespaces": [
      {
        "bdev_name": "Malloc0"
      },
      {
        "bdev_name": "Malloc1"
      },
      {
        "bdev_name": "Malloc2"
      },
      {
        "bdev_name": "Malloc3"
      },
      {
        "bdev_name": "Malloc4"
      },
      {
        "bdev_name": "Malloc5"
      },
      {
        "bdev_name": "Malloc6"
      },
      {
        "bdev_name": "Malloc7"
      },
      {
        "bdev_name": "Malloc8"
      },
      {
        "bdev_name": "Malloc9"
      },
      {
        "bdev_name": "Malloc10"
      },
      {
        "bdev_name": "Malloc11"
      },
      {
        "bdev_name": "Malloc12"
      },
      {
        "bdev_name": "Malloc13"
      },
      {
        "bdev_name": "Malloc14"
      },
      {
        "bdev_name": "Malloc15"
      },
      {
        "bdev_name": "Malloc16"
      },
      {
        "bdev_name": "Malloc17"
      },
      {
        "bdev_name": "Malloc18"
      },
      {
        "bdev_name": "Malloc19"
      },
      {
        "bdev_name": "Malloc20"
      },
      {
        "bdev_name": "Malloc21"
      },
      {
        "bdev_name": "Malloc22"
      },
      {
        "bdev_name": "Malloc23"
      },
      {
        "bdev_name": "Malloc24"
      },
      {
        "bdev_name": "Malloc25"
      },
      {
        "bdev_name": "Malloc26"
      },
      {
        "bdev_name": "Malloc27"
      },
      {
        "bdev_name": "Malloc28"
      },
      {
        "bdev_name": "Malloc29"
      },
      {
        "bdev_name": "Malloc30"
      },
      {
        "bdev_name": "Malloc31"
      },
      {
        "bdev_name": "Malloc32"
      },
      {
        "bdev_name": "Malloc33"
      },
      {
        "bdev_name": "Malloc34"
      },
      {
        "bdev_name": "Malloc35"
      },
      {
        "bdev_name": "Malloc36"
      },
      {
        "bdev_name": "Malloc37"
      },
      {
        "bdev_name": "Malloc38"
      },
      {
        "bdev_name": "Malloc39"
      },
      {
        "bdev_name": "Malloc40"
      },
      {
        "bdev_name": "Malloc41"
      },
      {
        "bdev_name": "Malloc42"
      },
      {
        "bdev_name": "Malloc43"
      },
      {
        "bdev_name": "Malloc44"
      },
      {
        "bdev_name": "Malloc45"
      },
      {
        "bdev_name": "Malloc46"
      },
      {
        "bdev_name": "Malloc47"
      },
      {
        "bdev_name": "Malloc48"
      },
      {
        "bdev_name": "Malloc49"
      },
      {
        "bdev_name": "Malloc50"
      },
      {
        "bdev_name": "Malloc51"
      },
      {
        "bdev_name": "Malloc52"
      },
      {
        "bdev_name": "Malloc53"
      },
      {
        "bdev_name": "Malloc54"
      },
      {
        "bdev_name": "Malloc55"
      },
      {
        "bdev_name": "Malloc56"
      },
      {
        "bdev_name": "Malloc57"
      },
      {
        "bdev_name": "Malloc58"
      },
      {
        "bdev_name": "Malloc59"
      },
      {
        "bdev_name": "Malloc60"
      },
      {
        "bdev_name": "Malloc61"
      },
      {
        "bdev_name": "Malloc62"
      },
      {
        "bdev_name": "Malloc63"
      }
    ],
    "allow_any_host": true,
    "serial_number": "SPDK00000000000010",
    "nqn": "nqn.2016-06.io.spdk:cnode3"
  },
  "method": "construct_nvmf_subsystem",
  "id": 1
}
response:
{
  "message": "Invalid parameters",
  "code": -32602
}

**Comment by xuhuagen** [comment] 2018-01-31 07:45
With enough memory, the number of namespaces should be unlimited. I tried to create 100  nvmf subsystems ,no error occurred.
You can update your spdk and try again.

**Comment by aneeeshp3** [comment] 2018-01-31 08:17
It is not about more number of subsystems. It is about the number of namespaces in a subsystem. I am able to create namespaces using the config file, but it fails when using the construct_nvmf_subsystem RPC method.

I further debugged the issue and found some probable cause of error:

In lib/json/json_util.c, in spdk_json_decode_array(), there a check:

if (values->len > max_size) {
    return -1;
}

This condition does not seems to work as expected for array of objects.

In case of the RPC request given in by earlier comment, when there are 64 namespaces in the request, the value of values->len becomes 256. This is happening because the length of one name space object { "bdev_name": "Malloc0" } becomes 4 and 64*4=256 becomes the size of the array. But max_size is equal to RPC_MAX_NAMESPACES (255). So for more than 63 namespaces in request, the request parsing fails.

I think the correct condition should be some thing like:

if (values->len > (max_size * size of one element in array)) {
    return -1;
}

**Comment by darsto** [comment] 2018-01-31 09:14
Nice catch.
Can you check this patch? https://review.gerrithub.io/c/397488/

**Comment by aneeeshp3** [comment] 2018-01-31 09:24
This fix should work in most cases.

Is it possible to have objects of different sizes present in the same array? Some thing like:

"namespaces": [
  {
    "bdev_name": "Malloc0"
  },
  {
    "bdev_name": "Malloc1"
  },
  {
    "bdev_name": "Malloc2"
  },
  {
    "nsid":6,
    "bdev_name": "Malloc3"
  },
  {
    "nsid":7,
    "bdev_name": "Malloc4"
  }
]

If this is a possible scenario, then this fix will not work. Using a counter inside the loop below and comparing that with max_size as a loop condition should handle both cases.

**Comment by dverkamp-intel** [comment] 2018-01-31 16:55
Thanks for the report - this is definitely not working as intended.  It is definitely possible for JSON array elements to contain different numbers of nested JSON values, as you pointed out, so using the length of the first element isn't correct.

I've pushed an alternate fix; please review: https://review.gerrithub.io/397591

**Comment by dverkamp-intel** [comment] 2018-01-31 21:05
The patch mentioned above has been merged, so this should work (up to the intended limit of 255 namespaces) now.

Note that in addition to this fix, a new RPC method is going to be added soon that will allow addition of namespaces after the subsystem has been created, which will allow creating more than 255 total namespaces per subsystem: https://review.gerrithub.io/#/c/396696/

**Closed by dverkamp-intel** 2018-01-31 21:05 UTC
Labels: bug
