### ISSUE TITLE
[rpc] RPC Unix domain socket path /var/tmp/spdk.sock in use

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#1430] opened 2020-06-04 06:56 UTC
00:01:40.301  ************************************
00:01:40.301  START TEST rpc
00:01:40.301  ************************************

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/16777/archive/iscsi-autotest/build.log

## Execution failed at

```
00:01:40.302   10:08:47	# test/rpc/rpc.sh
00:01:40.351  * Looking for test storage...
00:01:40.355  * Found test storage at /var/jenkins/workspace/iscsi-autotest/spdk/test/rpc
00:01:40.355    10:08:47	# xtrace_enable
00:01:40.356   10:08:47	# spdk_pid=750899
00:01:40.356   10:08:47	# /var/jenkins/workspace/iscsi-autotest/spdk/app/spdk_tgt/spdk_tgt
00:01:40.356   10:08:47	# trap 'killprocess $spdk_pid; exit 1' SIGINT SIGTERM EXIT
00:01:40.356   10:08:47	# waitforlisten 750899
00:01:40.356   10:08:47	# '[' -z 750899 ']'
00:01:40.357   10:08:47	# local rpc_addr=/var/tmp/spdk.sock
00:01:40.357   10:08:47	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
00:01:40.357  Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
00:01:40.357   10:08:47	# xtrace_disable
00:01:40.357   10:08:47	# '[' '' '!=' yes ']'
00:01:40.357   10:08:47	# PREV_BASH_OPTS=ehxBET
00:01:40.357   10:08:47	# [[ ehxBET == *\x* ]]
00:01:40.358   10:08:47	# XTRACE_DISABLED=yes
00:01:40.358   10:08:47	# set +x
00:01:40.373  Starting SPDK v20.07-pre git sha1 1eef1881e / DPDK 19.11.0 initialization...
00:01:40.373  [ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid750899 ]
00:01:40.397  EAL: No available hugepages reported in hugepages-1048576kB
00:01:40.397  EAL: VFIO support initialized
00:01:40.428  [2020-06-04 10:08:47.711732] app.c: 644:spdk_app_start: *NOTICE*: Total cores available: 1
00:01:40.931  [2020-06-04 10:08:48.213610] reactor.c: 371:reactor_run: *NOTICE*: Reactor started on core 0
00:01:40.931  [2020-06-04 10:08:48.213757] accel_engine.c: 229:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:01:41.372  [2020-06-04 10:08:48.655443] rpc.c: 180:spdk_rpc_listen: *ERROR*: RPC Unix domain socket path /var/tmp/spdk.sock in use. Specify another.
00:01:41.372  [2020-06-04 10:08:48.655510] rpc.c:  72:spdk_rpc_initialize: *ERROR*: Unable to start RPC service at /var/tmp/spdk.sock
00:02:10.337   10:09:17	# xtrace_enable
00:02:10.338   10:09:17	# (( i == 0 ))
00:02:10.338   10:09:17	# echo 'ERROR: timeout while waiting for process (pid: 750899) to start listening on '\''/var/tmp/spdk.sock'\'''
00:02:10.338  ERROR: timeout while waiting for process (pid: 750899) to start listening on '/var/tmp/spdk.sock'
00:02:10.338   10:09:17	# ret=1
00:02:10.338   10:09:17	# return 1
00:02:10.338    10:09:17	# trap - ERR
00:02:10.338    10:09:17	# print_backtrace
00:02:10.338    10:09:17	# [[ ehxBET =~ e ]]
00:02:10.338    10:09:17	# args=("${BASH_ARGV[@]}")
00:02:10.339    10:09:17	# local args
00:02:10.339    10:09:17	# xtrace_disable
00:02:10.339    10:09:17	# '[' no '!=' yes ']'
00:02:10.339    10:09:17	# PREV_BASH_OPTS=ehxBET
00:02:10.339    10:09:17	# [[ ehxBET == *\x* ]]
00:02:10.339    10:09:17	# XTRACE_DISABLED=yes
00:02:10.339    10:09:17	# set +x
00:02:10.339  ========== Backtrace start: ==========
00:02:10.339  
00:02:10.348  in test/rpc/rpc.sh:43 -> main([])
00:02:10.348       ...
00:02:10.349     38  	}
00:02:10.349     39  	
00:02:10.349     40  	$rootdir/app/spdk_tgt/spdk_tgt &
00:02:10.349     41  	spdk_pid=$!
00:02:10.349     42  	trap 'killprocess $spdk_pid; exit 1' SIGINT SIGTERM EXIT
00:02:10.349  => 43  	waitforlisten $spdk_pid
00:02:10.349     44  	
00:02:10.349     45  	export PYTHONPATH=$PWD/test/rpc/
00:02:10.349     46  	
00:02:10.349     47  	# basic integrity test
00:02:10.349     48  	rpc="$rootdir/scripts/rpc.py"
00:02:10.349       ...
00:02:10.349  
00:02:10.349  ========== Backtrace end ==========
```

**Comment by spdkci** [comment] 2020-06-04 07:02
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_16777.html

**Comment by karlatec** [comment] 2020-06-08 08:39
Considering the time when this GH issue was created I think the root cause is the same as in #1429 
Jenkins instance was accidentally restarted while tests were running, which may have resulted in some leftover SPDK processes running on physical systems.

I think we can close this one.

**Closed** 2020-06-08 19:31 UTC
Labels: Intermittent Failure
