### ISSUE TITLE
[basic_test_spdk_upstream_ci] Fails with modprobe: FATAL: Module msr not found in directory

### ISSUE THREAD

**Issue by mpiszczek** [spdk/spdk#2211] opened 2021-10-21 14:48 UTC
# CI Intermittent Failure

Running basic_test_spdk_upstream_ci in script swx-spdk-verification/scripts/pci_hp.sh spdk-tgt-bw-04
The test fails because modprobe cannot find the msr module. This was seen is several jobs.

## Link to the failed CI build

https://swx-ci.mellanox.com/spdk-test/blue/organizations/jenkins/basic_test_spdk_upstream_ci/detail/basic_test_spdk_upstream_ci/20028/pipeline

## Execution failed at

[2021-10-21T06:38:03.797Z] 0000:07:00.0 (144d a822): nvme -> uio_pci_generic
[2021-10-21T06:38:03.798Z] 0000:09:00.0 (8086 0a54): nvme -> uio_pci_generic
[2021-10-21T06:38:03.798Z] modprobe: FATAL: Module msr not found in directory /lib/modules/5.4.44-mlnx.11.g591d139

**Comment by spdkci** [comment] 2021-11-02 15:39
Another instance of this failure. Reported by @spdkci. log: https://ci.spdk.io/public_build/autotest-per-patch_61371.html

**Comment by spdkci** [comment] 2021-11-02 16:20
Another instance of this failure. Reported by @spdkci. log: https://ci.spdk.io/public_build/autotest-per-patch_61378.html

**Comment by spdkci** [comment] 2021-11-02 16:29
Another instance of this failure. Reported by @spdkci. log: https://ci.spdk.io/public_build/autotest-per-patch_61379.html

**Comment by AlekseyMarchuk** [comment] 2021-11-11 06:16
Reported failures seems not related to this issue. The issue is specific for Mellanox CI. Actually this error is not fatal and can be ignored. I can't open original log (seems to be out dated) but I'm sure that the problem was not in this modprobe error. To re-trigger Mellanox CI, please add a comment with `Mellanox:retest` message. For now, I'm closing this issue, if you see another failures, please feel free to reopen it.

**Closed by AlekseyMarchuk** 2021-11-11 06:16 UTC
Labels: Intermittent Failure
