### ISSUE TITLE
[nvmf_bdev_io_wait] Job ended with error

### ISSUE THREAD

**Issue by mmkayPL** [spdk/spdk#3138] opened 2023-09-18 12:06 UTC
# CI Intermittent Failure

## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/109983/archive/nvmf-tcp-phy-autotest_51942/build.log

## Execution failed at
```
00:10:37.886  [2023-09-18 13:17:25.343997] nvme_qpair.c: 243:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:0 nsid:1 lba:1016 len:8 PRP1 0x0 PRP2 0x0
00:10:37.886  [2023-09-18 13:17:25.344011] nvme_qpair.c: 474:spdk_nvme_print_completion: *NOTICE*: ABORTED - SQ DELETION (00/08) qid:1 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
00:10:37.886  [2023-09-18 13:17:25.344074] bdev_nvme.c:1575:bdev_nvme_disconnected_qpair_cb: *NOTICE*: qpair 0x2137c10 was disconnected and freed. reset controller.
00:10:37.886  [2023-09-18 13:17:25.345582] nvme_ctrlr.c:1639:nvme_ctrlr_disconnect: *NOTICE*: [nqn.2016-06.io.spdk:cnode1] resetting controller
00:10:37.886  task offset: 0 on job bdev=Nvme1n1 fails
00:10:37.886  
00:10:37.886                                                                                                  Latency(us)
00:10:37.886  
 Device Information          : runtime(s)       IOPS      MiB/s     Fail/s     TO/s    Average        min        max
00:10:37.886  
 Job: Nvme1n1 (Core Mask 0x20)
00:10:37.886  
 Job: Nvme1n1 ended in about 0.04 seconds with error
00:10:37.886  	 Nvme1n1             :       0.04       0.00       0.00    3634.71     0.00   34659.75   34369.99   34758.35
00:10:37.886  
00:10:37.886  
 Total                       :                  0.00       0.00    3634.71     0.00   34659.75   34369.99   34758.35
00:10:37.886  [2023-09-18 13:17:25.347666] app.c: 898:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
00:10:37.886  [2023-09-18 13:17:25.347708] nvme_tcp.c:2130:nvme_tcp_qpair_process_completions: *ERROR*: Failed to flush tqpair=0x2118100 (9): Bad file descriptor
00:10:37.886  [2023-09-18 13:17:25.451512] bdev_nvme.c:2025:_bdev_nvme_reset_ctrlr_complete: *NOTICE*: Resetting controller successful.
00:10:38.823  
00:10:38.823                                                                                                  Latency(us)
00:10:38.823  
 Device Information          : runtime(s)       IOPS      MiB/s     Fail/s     TO/s    Average        min        max
00:10:38.823  
 Job: Nvme1n1 (Core Mask 0x10)
00:10:38.823  	 Nvme1n1             :       1.01   10894.68      42.56       0.00     0.00   11697.09    6602.15   22719.15
00:10:38.823  
00:10:38.823  
 Total                       :              10894.68      42.56       0.00     0.00   11697.09    6602.15   22719.15
00:10:38.823  
00:10:38.823                                                                                                  Latency(us)
00:10:38.823  
 Device Information          : runtime(s)       IOPS      MiB/s     Fail/s     TO/s    Average        min        max
00:10:38.823  
 Job: Nvme1n1 (Core Mask 0x40)
00:10:38.823  	 Nvme1n1             :       1.00  159414.03     622.71       0.00     0.00     799.03     374.71    1480.63
00:10:38.823  
00:10:38.823  
 Total                       :             159414.03     622.71       0.00     0.00     799.03     374.71    1480.63
00:10:38.823  
00:10:38.823                                                                                                  Latency(us)
00:10:38.823  
 Device Information          : runtime(s)       IOPS      MiB/s     Fail/s     TO/s    Average        min        max
00:10:38.823  
 Job: Nvme1n1 (Core Mask 0x80)
00:10:38.823  	 Nvme1n1             :       1.01    9615.82      37.56       0.00     0.00   13264.37    5995.33   24855.13
00:10:38.823  
00:10:38.823  
 Total                       :               9615.82      37.56       0.00     0.00   13264.37    5995.33   24855.13
00:10:38.823   13:17:26	-- target/bdev_io_wait.sh@38 -- # wait 3490565
00:10:38.823    13:17:26	-- target/bdev_io_wait.sh@38 -- # trap - ERR
00:10:38.823    13:17:26	-- target/bdev_io_wait.sh@38 -- # print_backtrace
00:10:38.823    13:17:26	-- common/autotest_common.sh@1100 -- # [[ ehxBET =~ e ]]
00:10:38.823    13:17:26	-- common/autotest_common.sh@1102 -- # args=('--transport=tcp')
00:10:38.823    13:17:26	-- common/autotest_common.sh@1102 -- # local args
00:10:38.823    13:17:26	-- common/autotest_common.sh@1104 -- # xtrace_disable
00:10:38.823    13:17:26	-- common/autotest_common.sh@10 -- # set +x
00:10:38.823  ========== Backtrace start: ==========
00:10:38.823  
00:10:38.823  in /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/nvmf/target/bdev_io_wait.sh:38 -> main(["--transport=tcp"])
00:10:38.823       ...
00:10:38.823     33  	"$rootdir/build/examples/bdevperf" -m 0x80 -i 4 --json <(gen_nvmf_target_json) -q 128 -o 4096 -w unmap -t 1 -s 256 &
00:10:38.823     34  	UNMAP_PID=$!
00:10:38.823     35  	sync
00:10:38.823     36  	
00:10:38.823     37  	wait $WRITE_PID
00:10:38.823  => 38  	wait $READ_PID
00:10:38.823     39  	wait $FLUSH_PID
00:10:38.823     40  	wait $UNMAP_PID
00:10:38.823     41  	
00:10:38.823     42  	$rpc_py nvmf_delete_subsystem nqn.2016-06.io.spdk:cnode1
00:10:38.823     43  	
00:10:38.823       ...
00:10:38.823  
00:10:38.823  ========== Backtrace end ==========```

**Comment by spdkci** [comment] 2023-09-18 12:07
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_109983.html

**Comment by apaszkie** [comment] 2023-09-19 08:01
Different test but judging from these messages it looks like a duplicate of #2955:
```
00:10:37.879  [2023-09-18 13:17:25.310800] ctrlr.c: 238:ctrlr_add_qpair_and_send_rsp: *WARNING*: Duplicate QID detected, re-check in 100us
00:10:37.879  [2023-09-18 13:17:25.310964] ctrlr.c: 231:ctrlr_add_qpair_and_send_rsp: *ERROR*: Got I/O connect with duplicate QID 1
00:10:37.879  [2023-09-18 13:17:25.311254] nvme_qpair.c: 218:nvme_admin_qpair_print_command: *NOTICE*: FABRIC CONNECT qid:1 cid:0 SGL DATA BLOCK OFFSET 0x0 len:0x400
00:10:37.879  [2023-09-18 13:17:25.311291] nvme_qpair.c: 474:spdk_nvme_print_completion: *NOTICE*: INVALID QUEUE IDENTIFIER (01/01) qid:1 cid:0 cdw0:0 sqhd:0001 p:0 m:0 dnr:0
00:10:37.879  [2023-09-18 13:17:25.311312] nvme_fabric.c: 598:nvme_fabric_qpair_connect_poll: *ERROR*: Connect command failed, rc -5, trtype:TCP adrfam:IPv4 traddr:10.0.0.2 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode1
00:10:37.879  [2023-09-18 13:17:25.311328] nvme_fabric.c: 609:nvme_fabric_qpair_connect_poll: *ERROR*: Connect command completed with error: sct 1, sc 1
00:10:37.879  [2023-09-18 13:17:25.311343] nvme_tcp.c:2380:nvme_tcp_ctrlr_connect_qpair_poll: *ERROR*: Failed to poll NVMe-oF Fabric CONNECT command
00:10:37.879  [2023-09-18 13:17:25.311357] nvme_tcp.c:2170:nvme_tcp_qpair_process_completions: *ERROR*: Failed to connect tqpair=0x2137c10
```

**Comment by tomzawadzki** [comment] 2023-09-19 14:07
Duplicate of #2955

**Closed by tomzawadzki** 2023-09-19 14:07 UTC
Labels: Intermittent Failure
