### ISSUE TITLE
Should ctrlr_lock be acquired when an admin command is submitted?

### ISSUE THREAD

**Issue by uchida2016** [spdk/spdk#75] opened 2016-11-18 22:32 UTC
Some functions get ctrlr_lock when they call nvme_ctrlr_submit_admin_request, but some functions don't.
Should we get ctrlr_lock in nvme_ctrlr_submit_admin_request function and change all caller functions not to get lock? 

Ex;
functions that get lock
spdk_nvme_ctrlr_cmd_admin_raw, nvme_ctrlr_cmd_attach_ns, etc

functions that don't get lock
nvme_ctrlr_cmd_identify_controller, nvme_ctrlr_cmd_identify_namespace, etc

**Comment by dverkamp-intel** [comment] 2016-12-06 00:34
Currently, we have a mix of two kinds of commands in nvme_ctrlr_cmd.c:
- Functions that are part of the public API (spdk/nvme.h) - these should take the ctrlr_lock.
- Functions that are only called internally by other NVMe driver code that should already hold ctrlr_lock. (e.g. nvme_ctrlr_cmd_identify_controller).

We should definitely do a better job of distinguishing between these types of commands, but that is the explanation for why some functions don't take the lock.

(We also have a few functions in nvme_ctrlr_cmd.c that are unused currently, like nvme_ctrlr_cmd_abort(); if these are ever actually exposed in the public API, they will need to be changed to take ctrlr_lock.)

**Comment by uchida2016** [comment] 2016-12-06 02:15
Both commands need to get the ctrlr_lock eventually. Would you tell me why you have two kinds of commands?

**Comment by dverkamp-intel** [comment] 2016-12-13 00:01
Originally, ctrlr_lock was a regular pthread mutex, which meant it could only be locked once at a time even from the same thread, and the internal functions that currently don't take ctrlr_lock are called by other library functions that are already holding ctrlr_lock.  Therefore, the internal ctrlr_cmd helpers couldn't take the ctrlr_lock since it would deadlock.

I suppose now that the ctrlr_lock is a recursive mutex, it would be possible to make the internal routines also take the ctrlr_lock for consistency.

**Comment by jimharris** [comment] 2018-12-20 00:15
Closing this issue based on Daniel's response.  There are some theoretical improvements that could be made here, but the code is functionally working as intended.

**Closed by jimharris** 2018-12-20 00:15 UTC
Labels: enhancement
