### ISSUE TITLE
[scheduler] Cpu other than the main cpu was not idle when switching into interrupt mode

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#2240] opened 2021-11-16 21:02 UTC
# CI Intermittent Failure

The following scenario was not satisfied.

        # Standard scenario - spdk app is idle, all cpus, except the main cpu, should be
        # switched into interrupt mode. main cpu should remain busy, all remaining cpus
        # should become idle.

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_61923.html

## Execution failed at

>00:09:57.694  ========== Backtrace start: ==========
00:09:57.694  
00:09:57.694  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/scheduler/interrupt.sh:41 -> interrupt([])
00:09:57.694       ...
00:09:57.694     36  		for cpu in "${!is_idle[@]}"; do
00:09:57.694     37  			if ((cpu == spdk_main_core)); then
00:09:57.694     38  				((is_idle[cpu] == 0)) # main cpu must not be idle
00:09:57.694     39  			fi
00:09:57.694     40  			if ((cpu != spdk_main_core)); then
00:09:57.694  => 41  				((is_idle[cpu] == 1)) # all cpus except the main cpu must be idle
00:09:57.694     42  			fi
00:09:57.694     43  		done
00:09:57.694     44  	
00:09:57.694     45  		# select 3 cpus except the main one
00:09:57.694     46  		busy_cpus=("${cpus[@]:1:3}") threads=()
00:09:57.694       ...
00:09:57.699  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/scheduler/interrupt.sh:77 -> main([])
00:09:57.699       ...
00:09:57.700     72  		done
00:09:57.700     73  	}
00:09:57.700     74  	
00:09:57.700     75  	exec_under_dynamic_scheduler "$scheduler" -m "$spdk_cpusmask" --main-core "$spdk_main_core"
00:09:57.700     76  	
00:09:57.700  => 77  	interrupt
00:09:57.700       ...
00:09:57.700  
00:09:57.700  ========== Backtrace end ==========

**Comment by spdkci** [comment] 2021-11-16 21:03
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_61923.html

**Comment by spdkci** [comment] 2021-11-18 14:00
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_62067.html

**Comment by mikeBashStuff** [comment] 2021-11-18 14:56
Just taking some snippets from the the last repo to better understand conditions under which given scenario fails:
```
# This is what we get by looking up cpu time as seen by the kernel. Clearly, the cpu thread is not fully idle
cpu9 idle samples: 56 51 49 58 53 (avg: 53%)
00:10:01.177   12:38:54	-- scheduler/common.sh@512 -- # (( samples[-1] >= 70 ))
00:10:01.177   12:38:54	-- scheduler/common.sh@516 -- # printf '*cpu%u is not idle\n' 9
00:10:01.177  *cpu9 is not idle

# This is what SPDK tells us - cpu9 is indeed idle:
00:10:01.244  {
00:10:01.244    "lcore": 9,
00:10:01.244    "busy": 0,
00:10:01.244    "idle": 3011721912,
00:10:01.244    "in_interrupt": true,
00:10:01.244    "core_freq": 2100,
00:10:01.244    "lw_threads": []
00:10:01.244  }
```
So the cpu9 schedules some other work, not-related to SPDK. I guess this is expected since we don't isolate cpus for these tests. That said, at the very beginning, when work under `test/scheduler` started, there was this idea of using cgroups to make sure SPDK spins on dedicated cpus to reduce the potential jitter coming from other processes. Something similar to: https://review.spdk.io/gerrit/c/spdk/spdk/+/5739/11 https://review.spdk.io/gerrit/c/spdk/spdk/+/5738/11. This was dropped along the way as deemed unnecessary in the scope of actual tests. I am not saying that we should resurrect this concept, although I think it should help to mitigate similar discrepancies. Alternatively, we could change the tests so that they depend only on data from SPDK rather then looking up actual system load that is seen on the selected cpus.

**Comment by ksztyber** [comment] 2021-11-19 08:16
@mikeBashStuff, I agree with you, we should either make sure the CPU load doesn't include background stuff or don't bother checking that at all. I feel like it is good to cross-check the SPDK scheduler stats with the kernel ones. I like the idea of using cgroups, but how exactly would that work? Would we be able to see the busy/idle stats for a cgroup?

Also, this is a duplicate of #1950, let's close this one and discuss it further there.

**Closed by ksztyber** 2021-11-19 08:16 UTC
Labels: Intermittent Failure
