### ISSUE TITLE
Nvme Drive hot insertion detection time 

### ISSUE THREAD

**Issue by nagendra-v** [spdk/spdk#589] opened 2019-01-19 00:28 UTC
If drive is hot inserted with nvmf_tgt running, it takes 2 to 10 minutes for new drives to be detected by utilities identify or nvme cli.

Getting error message "EAL: Cannot find resource for device" from utilities before drives are detected.

This issue seen with  SPDK v18.10.1 / DPDK 18.08.0 on CentOS 7.5.1804. I believe issue also present in SPDK 19.01

## Steps to Reproduce
1. Run "setup.sh" script, start nvmt_tgt
2. Insert drive
3. Run "setup.sh" for new drives to be detected by SPDK
4. Run identify/nvme list command to see error message

Any specific commands need to be executed after "setup.sh" ran, for new drive to be detected right away?

**Comment by changpe1** [comment] 2019-01-23 09:13
@nagendra-v , I'll take a look of the issue, BTW, what's the expected behavior for the scenario ?

**Comment by changpe1** [comment] 2019-02-21 01:55
@nagendra-v , I tested the cases, I enabled NVMe hotplug feature, then the new drives can be joined to SPDK automatically after setup.sh.  Of course, you should use RPC to add the block device to one NVMf subsystem.

**Comment by rajasekaranmam** [comment] 2019-02-22 10:51
FYI:
I have seen the similar issue (EAL print with NVMe SSD DBDF number in SPDK Target while unplugging NVMe SSD.
This print (EAL prints with 1st NVMe SSD DBDF number) even after you start hot-plug some more SSDs.

At this time, I have seen below observations in SPDK 19.01 with VFIO (hot-plug enabled in Config file).
1. EAL Can not handle hot unplug for device BDF will be printed continuously until killing the SPDK target.
2. RPC calls also fails (such as get_bdevs).
3. ./setup.sh script also hung some time.
I will attach all relevant snaps in below.

Is that fine, we can also consider these observations as part of this defect or do you suggest me to file a new defect?

16.04.5 LTS (Xenial Xerus)
4.15.0-38-generic
MLNX_OFED_LINUX-4.5-1.0.1.0
Community SPDK 19.01 with VFIO (vfio-pcie)
2 number of NVMe DC P4800X Optane 375GB SSDPE21K375GA

**Comment by rajasekaranmam** [comment] 2019-02-22 10:55
![inserted new nvme ssd placed in kernel and not moved to vfio pci userspace](https://user-images.githubusercontent.com/18207076/53238113-7d934380-36be-11e9-9d98-8caa4fc746c1.jpg)
![hot-plug error message](https://user-images.githubusercontent.com/18207076/53238115-7d934380-36be-11e9-9206-a0ff39856a10.jpg)
![eal can not handle hot unplug for device bdf while unplug nvme ssd in 19 01 with sigbus switch enable_hot plug enable in config](https://user-images.githubusercontent.com/18207076/53238116-7e2bda00-36be-11e9-830f-6de80e446abc.jpg)
![sigstp eal-init-thread_also setup reset hung](https://user-images.githubusercontent.com/18207076/53238117-7e2bda00-36be-11e9-9c23-3f27613d1b98.jpg)

**Comment by nagendra-v** [comment] 2019-03-01 02:40
@changpe1 Can you let me know what RPC call I need to execute to add block device to one NVMf subsystem

**Comment by changpe1** [comment] 2019-03-07 05:09
@nagendra-v I used uio_pci_generic driver instead of vfio-pci, I guess that's maybe the problem.

**Comment by changpe1** [comment] 2019-03-07 05:10
[Bug Scrub] @darsto Do you have any comments about the EAL error log when using vfio-pci driver ?

**Comment by darsto** [comment] 2019-03-12 11:59
Apparently our vfio-pci hotremove got completely broken after DPDK implemented its "vfio req notifier". DPDK will keep printing those error messages until we call the proper DPDK function.

There is a PoC fix for github issue #690 that could help here as well:
https://review.gerrithub.io/c/spdk/spdk/+/447410

**Comment by rajasekaranmam** [comment] 2019-04-03 06:30
@darsto If it ok here to ask as part of this relevant thread then which is the preferred one (UIO or VFIO) to test drive hot-plug tests?

**Comment by rajasekaranmam** [comment] 2019-04-03 09:02
@darsto Also based on the recent note from defect#527 (https://github.com/spdk/spdk/issues/527), UIO is the preferred method now since VFIO have some issues (due to DPDK).

**Comment by peluse** [comment] 2019-04-09 15:58
@nagendra-v can you please retry with the patch mentioned above?

**Comment by darsto** [comment] 2019-04-23 12:43
The patch above seems to be abandoned, but we've fixed VFIO hotremove [1] in a different one: https://review.gerrithub.io/c/spdk/spdk/+/448927

It is already merged, so VFIO hotremove on SPDK master should work fine. We'll continue adding dedicated VFIO automated tests for SPDK 19.07 to ensure this doesn't break anymore.

@rajasekaranmam could you try doing VFIO hotremove on latest SPDK master?

[1] github issue #595 and #690

**Comment by darsto** [comment] 2019-04-23 12:51
> @darsto If it ok here to ask as part of this relevant thread then which is the preferred one (UIO or VFIO) to test drive hot-plug tests?

@rajasekaranmam Sorry for the late answer. The ultimate SPDK goal is to support both, but for now we have automated tests only for UIO hotremove, which means only UIO hotremove should be considered stable.

**Comment by darsto** [comment] 2019-04-23 15:36
Bug scrub: @changpe1 have you reproduced the original hotplug issue (about hotplug taking 2 to 10 minutes?)

**Comment by glodfish-zg** [comment] 2019-04-25 09:09
For NVMe Drive hot insert with VFIO-PCI driver, it seems the UEVENT has changed.
At least in Fedora-release-28 it has changed.

**Comment by Maciej-Szwed** [comment] 2019-07-23 11:16
@rajasekaranmam have you tried running this scenario with darsto fix (https://review.gerrithub.io/c/spdk/spdk/+/448927)?

**Comment by Maciej-Szwed** [comment] 2019-07-24 07:32
I've run some tests and haven't seen any issue on latest master. I'm suggesting to close this github issue if there won't be any response here or on mailing list.

**Comment by Maciej-Szwed** [comment] 2019-07-29 08:29
Closing this issue as there is no confirmation that issue still exists.

**Closed by Maciej-Szwed** 2019-07-29 08:29 UTC
Labels: High, bug
