### ISSUE TITLE
Jenkins CI Networking Failures - No logs generated, or obvious failure before any test related activities start

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1007] opened 2019-10-25 23:32 UTC
These are actually happening fairly frequently right now.

https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_47951.html
No logs, but looking at Jenkins internally it timed out during the unittest build.

https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_47849.html
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/47847/archive/centos7_autotest/build.log

I think one is also related.
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/47846/archive/centos7_autotest/build.log

**Comment by shuhei-matsumoto** [comment] 2019-10-29 10:49
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48091.html

This is different different signature but looks related with test infrastructure. This give any hint? Please open an new issue if needed

**Comment by karlatec** [comment] 2019-10-30 10:14
Most of these fails seem to be caused by poor network connection to Gerrithub - cloning and/or fetching the sources seems to take too much time, or is even failed in the process.
This applies to the log posted by @shuhei-matsumoto as well.

In our CI we have mirrors of gerrithub repo, created with "git clone --mirror". This is done to speed up fetching the changes. Most of the source code is downloaded from this local mirror and the rest is fetched "from the internet".
Typically I try to update the mirrors every quarter, so that we don't need to download as much from Gerrithub and I think that updating the mirror repos would help a lot with these failures.

Unfortunately - there's a problem. "git clone --mirror" for spdk/spdk keeps failing for the last couple of days (and I think that's a global problem as I was unable to clone it on my personal PC as well, which is not behind proxy).

@jimharris could you or someone from your team contact Gerrithub support about this?

**Comment by karlatec** [comment] 2019-10-30 12:00
Also - I think this issue should be renamed to smth like "CI cloning intermittent failure", because it affects other jobs, not just Centos7 (just like shuhei linked).

And we could also close duplicates, which are starting to appear like this one:
https://github.com/spdk/spdk/issues/1015

**Comment by jimharris** [comment] 2019-10-30 17:18
The original issue that Shuhei and I saw was definitely Centos7 related.  We saw this on several patches last week but only on the Centos7 VM.

Can you double-check the git clone --mirror?  I just tried it on one of my system and seems to be working fine - it hasn't completed yet, but it's "Counting objects" successfully.

git clone --mirror ssh://jimharris@review.gerrithub.io:29418/spdk/spdk spdk-mirror

**Comment by karlatec** [comment] 2019-10-30 17:23
Here's a similar one to one that Shuhei posted. This time it's nvme tests, fedora OS and chandler-based.
https://10.102.17.104:8080/job/NVMe_tests/job/nvme_autotest_nightly/2843/console

> git clone --mirror ssh://jimharris@review.gerrithub.io:29418/spdk/spdk spdk-mirror
How about anonymous HTTPS clone? Problem with SSH is that we'd have to provision all the nodes and do some changes in CI config.

**Comment by jimharris** [comment] 2019-10-30 17:41
I also get errors when trying to do anonymous https.  So this is specific to anonymous https.

**Comment by jimharris** [comment] 2019-10-30 17:42
Does it work with authenticated https?  I just want to make sure we've triaged this as much as possible before contacting GerritForge support.

**Comment by Seth5141** [comment] 2019-10-30 22:49
In regards to this, the tcp tests started failing regularly this afternoon so I used the SSH method to update the mirror repos in those repositories. After that, they started passing again. I am in the process of doing that for the rest of the nightly machines.
Interesting sidenote - doing a git clone --mirror of spdk/dpdk using anonymous https works without a hitch. but doing the same on spdk/spdk doesn't work. Not sure if it's a timeout thing or what.
I also wonder if we could do something to trim down the number of refs we keep in GerritHub, like for merged changes?
@karlatec Once I have updates the remote repos for all of the nightly machines, won't we only have to do one more set, specifically the repos on the share drive for the Poland machines?

**Comment by karlatec** [comment] 2019-10-31 07:01
> @karlatec Once I have updates the remote repos for all of the nightly machines, won't we only have to do one more set, specifically the repos on the share drive for the Poland machines?

Will do. BTW --mirror started to work yesterday in our geo after Jim contacted the technical support:)

> I also wonder if we could do something to trim down the number of refs we keep in GerritHub, like for merged changes?

Well, one thing would be to use more branches than just master I guess. But I also sent you an e-mail yesterday about using --depth=1 for clones and fetches, which reduces the amount of downloaded stuff significantly. Unfortunately it causes "git describe --tags" in autobuild.sh to fail, so I still need to tackle that.

**Comment by spdkci** [comment] 2019-10-31 15:22
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48262.html

**Comment by spdkci** [comment] 2019-10-31 15:31
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48284.html

**Comment by tomzawadzki** [comment] 2019-10-31 21:01
Another possibly related instance - timeout during build with no logs for long period of time.
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48467.html

**Comment by spdkci** [comment] 2019-11-01 14:36
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48457.html

**Comment by spdkci** [comment] 2019-11-04 12:21
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48698.html

**Comment by pawelkax** [comment] 2019-11-04 12:25
No logs generated for autotest_per_patch_48698. The problem could be the test that caused machine freeze.

**Comment by spdkci** [comment] 2019-11-04 20:06
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48735.html

**Comment by spdkci** [comment] 2019-11-04 22:16
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48750.html

**Comment by karlatec** [comment] 2019-11-05 08:07
Reported failures which are not related to this github issue in my opinion, probably should not be reported here:

- https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48750.html (Timeout during VPP tests; logs present, no infrastructure errors)
- https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48284.html (NVMF tests fail; log file present and with a coredump too!)
- https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48262.html (Assertion fail in blobfs tests, logs present, looks like a legit fail)

**Comment by spdkci** [comment] 2019-11-05 11:18
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48829.html

**Comment by jimharris** [comment] 2019-11-05 14:47
@karlatec - for timeout during VPP tests, the test randomly timed out near the end of the test.  I debated whether this was a CI issue or not.  We have seen cases where some VMs randomly timeout, or show huge gaps in time during the test run.  Perhaps we should create a separate issue for this specific issue (timeouts that aren't related to the patch under test) but for now I decided to put it here.

**Comment by spdkci** [comment] 2019-11-07 12:08
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49115.html

**Comment by spdkci** [comment] 2019-11-07 17:58
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49158.html

**Comment by spdkci** [comment] 2019-11-07 18:01
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49154.html

**Comment by spdkci** [comment] 2019-11-07 18:09
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49160.html

**Comment by spdkci** [comment] 2019-11-08 19:58
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49316.html

**Comment by spdkci** [comment] 2019-11-08 22:58
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49255.html

**Comment by spdkci** [comment] 2019-11-08 22:59
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49254.html

**Comment by spdkci** [comment] 2019-11-08 23:10
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49250.html

**Comment by spdkci** [comment] 2019-11-14 14:52
Another instance of this failure. Reported by @Maciej-Szwed. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49695.html

**Comment by spdkci** [comment] 2019-11-14 21:15
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49751.html

**Comment by Seth5141** [comment] 2019-11-15 17:33
I figure here is the best place to post this:

@karlatec @jimharris @pawelkax 

I did a quick audit of the vm host machines and found the following:

WFP1 - 112 CPUs, 142-152 allocated for VMs - overprovisioned by 30 - 40 cores.
I think we could do th following to reduce the number of cores in use:
All of the fedora VMs on this machine are using 12 cores. I think that all 7 of them could be reduced to 8 cores.
All of the ubuntu and centos machines use 8 cores. I think they could be reduced to 4 cores
Freebsd machines are using 10 cores, they can be reduced to 4 each (currently only one is online).
Doing all of the above would would decrease the number of core in use by 64 cores and leave plenty of room.

PE1 - 56 CPUs - 52 allocated for VMs. Not overprovisioned

PE3 - 56 CPUs - 56 allocated for VMs. Overprovisioned by 0 cores.
The reason I say that this is overprovisioned is because there are no extra CPUs available for the QEMU process to run background tasks. I think that we could probably move a single fedora vm to wfp1 to free up 8 cores and give this machine some breathing room.

By freeing up some space on these host machines, we might help mitigate some of these seemingly random random CI failures.

**Comment by jimharris** [comment] 2019-11-15 17:36
Sounds like a great strategy @Seth5141.  I say we try this and see if/how much it affects these types of failures.

**Comment by spdkci** [comment] 2019-11-19 08:46
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50049.html

**Comment by spdkci** [comment] 2019-11-19 17:23
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50148.html

**Comment by Seth5141** [comment] 2019-11-19 21:45
As of now, all of these VMs are on underprovisioned hosts, both in terms of CPU and memory.
WFP1 - 100/112 CPUs allocated for VMs, 166 / 251 GiB Memory allocated for VMs
PE3 - 48/56 CPUs allocated for VMs, 70 / 125 GiB Memory allocated for VMs
PE1 - 52/56 CPUs allocated for VMs, 88 / 188 GiB Memory allocated for VMs

Let's see how these types of failures are affected by the new provisioning.

Some easy one liners for checking memory and cpu usage on the hosts for future reference.
~~~
i=0; for line in `virsh domstats --list-running --balloon | grep balloon.maximum | cut -d "=" -f 2`; do i=$(($i+$line)); done; echo $(($i/1024/1024))

i=0; for line in `virsh domstats --list-running --vcpu | grep vcpu.maximum | cut -d "=" -f 2`; do i=$(($i+$line)); done; echo $i
~~~

**Comment by spdkci** [comment] 2019-11-19 21:51
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50168.html

**Comment by spdkci** [comment] 2019-11-20 23:12
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50310.html

**Comment by spdkci** [comment] 2019-11-21 07:18
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50325.html

**Comment by karlatec** [comment] 2019-11-25 11:50
@Seth5141 @jimharris I've just changed another bit of config which may affect the results.
We currently run all our VMs in -snapshot mode to always have a clean VM copy after restart.

By default temporary files for -snapshot mode are stored in /tmp directory which is on the NAND SSD holding the OS installation. I've reconfigured the VMs to use a temporary location on a NVMe drive instead.
For now I've only done it for fedora_vm_(1-10) hosted on PE3 & WFP1

**Comment by jimharris** [comment] 2019-11-25 14:26
@karlatec - fantastic!  Seth and I were just chatting about this last week, whether the snapshot storage was part of the issue (especially if it was on the SATA SSDs).

**Comment by spdkci** [comment] 2019-11-25 17:51
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50627.html

**Comment by spdkci** [comment] 2019-11-25 20:56
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50622.html

**Comment by spdkci** [comment] 2019-11-25 21:10
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50621.html

**Comment by spdkci** [comment] 2019-11-25 21:12
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50641.html

**Comment by spdkci** [comment] 2019-11-25 22:39
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50640.html

**Comment by spdkci** [comment] 2019-11-25 23:29
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50664.html

**Comment by spdkci** [comment] 2019-11-25 23:42
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50550.html

**Comment by spdkci** [comment] 2019-11-26 14:09
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50638.html

**Comment by spdkci** [comment] 2019-11-26 14:10
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50582.html

**Comment by spdkci** [comment] 2019-12-02 10:36
Another instance of this failure. Reported by @Maciej-Szwed. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51058.html

**Comment by spdkci** [comment] 2019-12-02 10:38
Another instance of this failure. Reported by @Maciej-Szwed. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51059.html

**Comment by spdkci** [comment] 2019-12-03 03:07
Another instance of this failure. Reported by @yidong0635. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51227.html

**Comment by peluse** [comment] 2019-12-03 15:14
bug scrub - (@karlatec ) going to replace network cables and see if that helps.  VM's have been load balanced. May be related to post reset, on nightly another maint job was added that runs after reset job to check node connectivity. Karol to also try adding this to per patch.Note that this didn't resolve issues w/nightly but we'll try per patch anyway to see if we get a reduction.

**Comment by spdkci** [comment] 2019-12-04 21:39
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51411.html

**Comment by spdkci** [comment] 2019-12-04 21:39
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51410.html

**Comment by spdkci** [comment] 2019-12-05 13:16
Another instance of this failure. Reported by @karlatec. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51493.html

**Comment by spdkci** [comment] 2019-12-06 02:16
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51620.html

**Comment by spdkci** [comment] 2019-12-06 02:35
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51604.html

**Comment by spdkci** [comment] 2019-12-06 09:12
Another instance of this failure. Reported by @jkalwas. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50513.html

**Comment by spdkci** [comment] 2019-12-07 20:44
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51857.html

**Comment by spdkci** [comment] 2019-12-07 20:44
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51858.html

**Comment by spdkci** [comment] 2019-12-07 20:44
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51859.html

**Comment by spdkci** [comment] 2019-12-07 20:44
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51860.html

**Comment by spdkci** [comment] 2019-12-08 00:32
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51886.html

**Comment by spdkci** [comment] 2019-12-09 19:02
Another instance of this failure. Reported by @jkalwas. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52030.html

**Comment by spdkci** [comment] 2019-12-09 21:09
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52073.html

**Comment by spdkci** [comment] 2019-12-10 14:37
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52103.html

**Comment by spdkci** [comment] 2019-12-10 16:29
Another instance of this failure. Reported by @ksztyber. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52233.html

**Comment by spdkci** [comment] 2019-12-11 08:18
Another instance of this failure. Reported by @ksztyber. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52235.html

**Comment by spdkci** [comment] 2019-12-11 12:41
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52374.html

**Comment by spdkci** [comment] 2019-12-11 20:53
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52439.html

**Comment by spdkci** [comment] 2019-12-11 23:13
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52460.html

**Comment by spdkci** [comment] 2019-12-12 10:43
Another instance of this failure. Reported by @karlatec. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52509.html

**Comment by spdkci** [comment] 2019-12-12 14:28
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52533.html

**Comment by spdkci** [comment] 2019-12-13 20:27
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52713.html

**Comment by spdkci** [comment] 2019-12-13 23:02
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52754.html

**Comment by spdkci** [comment] 2019-12-14 00:12
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52762.html

**Comment by spdkci** [comment] 2019-12-18 09:39
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53148.html

**Comment by spdkci** [comment] 2019-12-18 20:55
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53201.html

**Comment by spdkci** [comment] 2019-12-19 10:22
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53276.html

**Comment by spdkci** [comment] 2019-12-27 17:29
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_54410.html

**Comment by spdkci** [comment] 2020-01-07 23:19
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55050.html

**Comment by spdkci** [comment] 2020-01-08 09:12
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55086.html

**Comment by spdkci** [comment] 2020-01-08 10:52
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55062.html

**Comment by spdkci** [comment] 2020-01-08 12:47
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55060.html

**Comment by spdkci** [comment] 2020-01-08 22:45
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55271.html

**Comment by spdkci** [comment] 2020-01-08 23:21
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55274.html

**Comment by spdkci** [comment] 2020-01-10 07:24
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55478.html

**Comment by spdkci** [comment] 2020-01-10 22:35
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55698.html

**Comment by spdkci** [comment] 2020-01-13 09:13
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55052.html

**Comment by spdkci** [comment] 2020-01-14 00:29
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_56292.html

**Comment by spdkci** [comment] 2020-01-14 14:11
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_56359.html

**Comment by spdkci** [comment] 2020-01-14 14:13
Another instance of this failure. Reported by @Maciej-Szwed. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_56452.html

**Comment by spdkci** [comment] 2020-01-16 15:13
Another instance of this failure. Reported by @Maciej-Szwed. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_56831.html

**Comment by spdkci** [comment] 2020-01-16 18:31
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_56864.html

**Comment by spdkci** [comment] 2020-01-17 13:24
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_57068.html

**Comment by spdkci** [comment] 2020-01-17 14:20
Another instance of this failure. Reported by @Maciej-Szwed. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_57092.html

**Comment by spdkci** [comment] 2020-01-21 13:05
Another instance of this failure. Reported by @karlatec. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_57457.html

**Comment by spdkci** [comment] 2020-01-23 11:28
Another instance of this failure. Reported by @Maciej-Szwed. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_57914.html

**Comment by spdkci** [comment] 2020-01-24 19:26
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58152.html

**Comment by spdkci** [comment] 2020-01-29 12:52
Another instance of this failure. Reported by @jkalwas. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58525.html

**Comment by spdkci** [comment] 2020-01-29 21:13
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58585.html

**Comment by spdkci** [comment] 2020-01-30 10:09
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58561.html

**Comment by spdkci** [comment] 2020-01-30 10:11
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58541.html

**Comment by spdkci** [comment] 2020-02-03 07:19
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58906.html

**Comment by spdkci** [comment] 2020-02-04 14:57
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59135.html

**Comment by spdkci** [comment] 2020-02-04 15:17
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59126.html

**Comment by spdkci** [comment] 2020-02-04 15:18
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59129.html

**Comment by spdkci** [comment] 2020-02-06 19:29
Another instance of this failure. Reported by @jkalwas. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60015.html

**Comment by spdkci** [comment] 2020-02-11 11:58
Another instance of this failure. Reported by @jkalwas. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60359.html

**Comment by spdkci** [comment] 2020-02-13 10:55
Another instance of this failure. Reported by @karlatec. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3237.html

**Comment by spdkci** [comment] 2020-02-13 11:31
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3243.html

**Comment by spdkci** [comment] 2020-02-13 16:47
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3292.html

**Comment by spdkci** [comment] 2020-02-14 15:41
Another instance of this failure. Reported by @ksztyber. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3585.html

**Comment by spdkci** [comment] 2020-02-21 10:15
Another instance of this failure. Reported by @pawelkax. log: https://ci.spdk.io/public_build/autotest-per-patch_4309.html

**Comment by karlatec** [comment] 2020-02-24 13:08
Quite a number of fails here are CentOS7 VM timeouts (usually vm 1 & 2). This issue is already reported in https://github.com/spdk/spdk/issues/1119 and  I am attempting to fix it so please use that number.

**Comment by tomzawadzki** [comment] 2020-02-25 16:04
[Bug scrub]
The CI Jenkins instance was switched recently to a new version, number of improvements have been done to that. This issue contains a lot of older comments that are no longer relevant.
To help with resolution of current and actual issues, I propose to close this one and report any new ones in separate issues.

Please note there are:
- #1207 for all failures with 'logs not generated'
- #1137 for failures related to NFS on VMs, which is soon to be solved by removing it from CI 

If there are any other issues, they should be created as new ones to help tackle them one by one.

**Closed by tomzawadzki** 2020-02-25 16:04 UTC
Labels: Infrastructure, Intermittent Failure
