### ISSUE TITLE
[spdk rdma]nvmf tgt transport retry counter exceeded when QD=16 with 32 nullbdev using fioplugin spdk bdev

### ISSUE THREAD

**Issue by wanqunintel** [spdk/spdk#1651] opened 2020-10-26 07:25 UTC
nvmf tgt transport retry counter exceeded when QD=16 with 32 nullbdev using fioplugin spdk bdev, with Mellanox ConnectX 5 NIC

## Expected Behavior
Test pass

## Current Behavior
Test failed

## Possible Solution
N/A

## Steps to Reproduce
Tgt:
**#./spdk/build/bin/nvmf_tgt -m 0x1F --json nvmf_tgt_full_speed.json**
failed log as follows
state 1 ibv_state 6) request 0x140642870038424, type SEND, status: (12): transport retry counter exceeded
[2020-10-26 10:42:50.011921] rdma.c:3857:nvmf_rdma_log_wc_status: *ERROR*: Error on CQ 0x25e11f0, (qp state 1 ibv_state 6) request 0x140642887071704, type SEND, status: (12): transport retry counter exceeded
[2020-10-26 10:42:54.316997] rdma.c:3857:nvmf_rdma_log_wc_status: *ERROR*: Error on CQ 0x7fe9ec122170, (qp state 1 ibv_state 6) request 0x140642650949528, type SEND, status: (12): transport retry counter exceeded
[2020-10-26 10:43:10.825756] rdma.c: 868:nvmf_rdma_qpair_destroy: *WARNING*: Destroying qpair when queue depth is 1
[2020-10-26 10:44:18.266030] rdma.c:3857:nvmf_rdma_log_wc_status: *ERROR*: Error on CQ 0x7fe9ec122170, (qp state 1 ibv_state 6) request 0x140642650838352, type DATA, status: (12): transport retry counter exceeded
[2020-10-26 10:44:26.876186] rdma.c:3857:nvmf_rdma_log_wc_status: *ERROR*: Error on CQ 0x25e11f0, (qp state 1 ibv_state 6) request 0x140642886971504, type DATA, status: (12): transport retry counter exceeded
[2020-10-26 10:47:55.671466] rdma.c:3857:nvmf_rdma_log_wc_status: *ERROR*: Error on CQ 0x7fe9ec122170, (qp state 1 ibv_state 6) request 0x140642650894800, type DATA, status: (12): transport retry counter exceeded
[2020-10-26 10:49:06.773900] rdma.c: 868:nvmf_rdma_qpair_destroy: *WARNING*: Destroying qpair when queue depth is 1
[2020-10-26 10:53:12.292470] rdma.c: 868:nvmf_rdma_qpair_destroy: *WARNING*: Destroying qpair when queue depth is 1
[2020-10-26 10:53:23.699327] rdma.c: 868:nvmf_rdma_qpair_destroy: *WARNING*: Destroying qpair when queue depth is 1

Host
**#fio fio_plugin_randread_qd16.job**
error log as follows
[2020-10-26 18:51:39.462145] accel_engine.c: 692:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
fio: io_u error on file Nvme0n13: Input/output error: read offset=982712320, buflen=4096
fio: io_u error on file Nvme0n14: Input/output error: read offset=272986112, buflen=4096
fio: io_u error on file Nvme0n15: Input/output error: read offset=280227840, buflen=4096
fio: io_u error on file Nvme0n16: Input/output error: read offset=108937216, buflen=4096
fio: io_u error on file Nvme0n17: Input/output error: read offset=48910336, buflen=4096
fio: io_u error on file Nvme0n18: Input/output error: read offset=801456128, buflen=4096
fio: io_u error on file Nvme0n19: Input/output error: read offset=521199616, buflen=4096
fio: io_u error on file Nvme0n20: Input/output error: read offset=673312768, buflen=4096
fio: io_u error on file Nvme0n21: Input/output error: read offset=103276544, buflen=4096
fio: io_u error on file Nvme0n22: Input/output error: read offset=516648960, buflen=4096
fio: io_u error on file Nvme0n23: Input/output error: read offset=129499136, buflen=4096
fio: io_u error on file Nvme0n24: Input/output error: read offset=1045028864, buflen=4096
fio: io_u error on file Nvme0n25: Input/output error: read offset=11567104, buflen=4096
fio: io_u error on file Nvme0n26: Input/output error: read offset=963260416, buflen=4096
fio: io_u error on file Nvme0n27: Input/output error: read offset=944652288, buflen=4096
fio: io_u error on file Nvme0n28: Input/output error: read offset=887029760, buflen=4096
fio: pid=29454, err=5/file:io_u.c:1806, func=io_u error, error=Input/output error

## Context (Environment including OS version, SPDK version, etc.)

commit: 214b9847d0fb37067f754f7481c4277c45525b8d

**Comment by AlekseyMarchuk** [comment] 2020-10-26 09:05
Hi @wanqunintel could you share your configuration files mentioned in the description? nvmf_tgt_full_speed.json and fio_plugin_randread_qd128.job

**Comment by wanqunintel** [comment] 2020-10-27 00:49
fio_plugin_randread_qd16.job file
[global]
ioengine=/spdk/build/fio/spdk_bdev
spdk_json_conf=spdk_bdev.json
ramp_time=10
runtime=100
numjobs=32
iodepth=16
thread=1
group_reporting=1
direct=1
norandommap=1
time_based=1
filename=Nvme0n1
filename=Nvme0n2
filename=Nvme0n3
filename=Nvme0n4
filename=Nvme0n5
filename=Nvme0n6
filename=Nvme0n7
filename=Nvme0n8
filename=Nvme0n9
filename=Nvme0n10
filename=Nvme0n11
filename=Nvme0n12
filename=Nvme0n13
filename=Nvme0n14
filename=Nvme0n15
filename=Nvme0n16
filename=Nvme0n17
filename=Nvme0n18
filename=Nvme0n19
filename=Nvme0n20
filename=Nvme0n21
filename=Nvme0n22
filename=Nvme0n23
filename=Nvme0n24
filename=Nvme0n25
filename=Nvme0n26
filename=Nvme0n27
filename=Nvme0n28
filename=Nvme0n29
filename=Nvme0n30
filename=Nvme0n31
filename=Nvme0n32
[4k_rd]
bs=4k
rw=randread

**Comment by wanqunintel** [comment] 2020-10-27 00:50
[nvmf_tgt_full_speed.log](https://github.com/spdk/spdk/files/5442241/nvmf_tgt_full_speed.log)

**Comment by AlekseyMarchuk** [comment] 2020-10-27 05:48
@wanqunintel
My first assumption is that there is not enough transport buffer in NVMEoF RDMA target. By default SPDK allocates 4096 buffers which are shared across all system threads. But according to your initiator configuration, you connect to a subsystem with 32 namespaces, run fio on 32 threads with queue depth = 16. it will produce about 32 * 32 * 16 = 16 384 requests inflight which is 4 times higher than SPDK target with default parameters can serve. Let's try to do a quick check, just increase the number of transport buffers at least to 16384 (-n parameter of nvmf_create_transport RPC method). Also in fio config you set bs=4k while io_unit_size in target is 24576, I think you can leave this parameter with default value (8192) and it will be enough for this payload.

**Comment by AlekseyMarchuk** [comment] 2021-03-09 12:02
I'll try to reproduce this problem with new SPDK, will update with results today

**Comment by AlekseyMarchuk** [comment] 2021-03-09 13:01
@wanqunintel I don't see any failures with your configuration even with default `num_shared_buffers` parameters. I used SPDK `13f868977` Could you check that MTU is configured to the same value on all RDMA ports? There was an issue with similar semantic and the problem was in wrong MTU setting

**Comment by tomzawadzki** [comment] 2021-05-18 14:13
@wanqunintel have you had a chance to check suggestion from Alexey ?

**Comment by jimharris** [comment] 2021-06-14 22:15
Closing issue.  @wanqunintel, please reopen if you are able to follow up on suggestions from Alexey and still see this issue.

**Closed by jimharris** 2021-06-14 22:15 UTC
Labels: Sighting, Waiting on Submitter
