### ISSUE TITLE
Vhost hotremove test random failure

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#993] opened 2019-10-23 12:56 UTC
Test from patch https://review.gerrithub.io/c/spdk/spdk/+/464450 sometimes fails.
Logs with failure: https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/47527/archive/vhost_initator_autotest/build.log

## Expected Behavior
Test should always pass.

## Current Behavior
When remove_vhost_controller rpc is called sometimes following error occurs:
request:
{
  "method": "vhost_delete_controller",
  "req_id": 1,
  "ctrlr": "naa.Nvme0n1_scsi0.0"
}
Got JSON-RPC error response
response:
{
  "code": -32602,
  "message": "Device or resource busy"
}

## Steps to Reproduce
1. Run:
   ./test/vhost/manual.sh -vhr
  several times until error occurs.

**Comment by Donaim** [comment] 2019-11-05 12:24
This is expected behaviour as for now because vhost cannot manage multiple management operations for particular bdev. In this case those events most likely were hotremove and regular delete_controller RPC, as result of doing [delete_nvme](https://review.gerrithub.io/c/spdk/spdk/+/464450/11/test/vhost/hotplug/virtio_hotremove.sh#24) followed by [$rpc_py remove_vhost_controller](https://review.gerrithub.io/c/spdk/spdk/+/464450/11/test/vhost/hotplug/virtio_hotremove.sh#33) .
We should improve error messages or implement better events handling in vhost (like use queueing which is not used at all right now) so that users don't get confused by behaviur like in this issue.
Better events handling would be implemented as part of vhost threading series that I am working on right now: https://review.gerrithub.io/c/spdk/spdk/+/471716/1 (inital steps are published).

**Comment by jimharris** [comment] 2019-11-07 00:39
@Donaim @pawelkax Can we modify the test then to ensure this issue doesn't occur?  But let's keep this issue open even if the test is modified, so that it gets tracked once the patch series mentioned is ready and merged.

**Comment by pawelkax** [comment] 2019-11-07 10:23
I commented out deleting controllers at the end of the tests.

**Comment by jimharris** [comment] 2019-11-07 17:34
Hi @pawelkax - is there a patch for this change?  Thanks.

**Comment by pawelkax** [comment] 2019-11-07 21:34
@jimharris Patch that detected this issue is https://review.gerrithub.io/c/spdk/spdk/+/464450. It has not been merged yet. I modified it to avoid this issue.
Should I create another patch that checks if this bug exists?

**Comment by jimharris** [comment] 2019-11-07 21:38
Oh - I missed that this was only found with a patch that hadn't been merged yet.  Then I don't think there's anything further to do here.  In fact we should probably close this issue now since your update patch won't hit this.

I noticed last revision of this patch failed the test pool due to an intermittent failure that was fixed yesterday.  Please try to remember to rebase patches from latest master before pushing new versions to GerritHub.

**Comment by tomzawadzki** [comment] 2019-11-19 15:48
Bug scrub: The issue is not expected to be hit on patch in review after the changes. Closing this issue.

**Closed by tomzawadzki** 2019-11-19 15:48 UTC
Labels: Bug Scrub
