### ISSUE TITLE
Lockup on handling of physical disk removal

### ISSUE THREAD

**Issue by baruch** [spdk/spdk#310] opened 2018-05-24 08:08 UTC
I have an application that uses SPDK for its local NVMe drive handling through `uio_pci_generic`, when the device is physically removed from the machine the process performs an `spdk_nvme_detach()` call and during that call the process locks up. Specifically it looks up when it tries to close the io qpair as there is no nvme device in the pcie bus to handle the request to the remove io qpair sq command.

## Expected Behavior

It is expected that the removal will finish sooner rather than later, preferably immediately but a few seconds for timeouts are acceptable as well.

## Current Behavior

Currently the process will just lock up waiting indefinitely in the `nvme_pcie_ctrlr_delete_io_qpair()` call, inside the loop that waits for the `status.done` to turn `true`. 

## Possible Solution

Either implement a timeout to handle any error case or check a register at shutdown to verify that the card is still there instead of waiting indefinitely. That is likely try for all such tight loops that wait for an admin command completion.

## Context (Environment including OS version, SPDK version, etc.)

This happened on multiple OSes, the latest of which that I can remember is CentOS 7.3 and Ubuntu 16. The SPDK version I am using is 17.03 but I also checked that the relevant code is unchanged in later versions.

**Comment by dverkamp-intel** [comment] 2018-05-24 20:32
`nvme_pcie_ctrlr_delete_io_qpair()` definitely needs a timeout added (as well as all other functions that have a 'poll until done'-style loop; we have a lot of these through lib/nvme).  We should probably also bail out of these style of loops if the controller gets marked as failed (`ctrlr->is_failed`), which should happen if a controller is hot-removed due to the SIGBUS handling and checking for registers returning 0xFFFFFFFF.  Maybe we can factor out these wait loops into a common function that does this kind of checking so we don't need to duplicate it all over the driver code.

**Comment by dverkamp-intel** [comment] 2018-05-25 22:51
I've posted a patch that changes all of these internal wait loops to use a single central helper function: https://review.gerrithub.io/#/c/spdk/spdk/+/412545/

The next step here would be to add a timeout parameter and pick reasonable values for each command (or maybe we can just hard-code a timeout for all command types).

However, the timeout needs to be implemented carefully to avoid introducing bugs: if we are going to abandon a command due to a timeout, we really have to disable the controller (assuming it is still plugged in and working at all) to avoid completions for the timed-out command being processed after we return from the function that issued the command, since the status variable we use for tracking the completion is on the stack and would clobber random stack data if the command ever did complete.

Concretely, I think the timeout handling should set ctrlr->is_failed, set CC.EN = 0, and only then return.  We might have to do something slightly different for NVMe-oF connections, since setting EN also requires a Set Properties command; maybe we can provide a transport hook that sets CC.EN = 0 for PCI -attached controllers and just forcibly closes the adminq connection for Fabrics transports.

**Comment by baruch** [comment] 2018-05-27 10:55
You can have a quick check at each loop if the registers are at all readable, if not the device is gone. This is simple to do in local NVMe, NVMe-oF requires separate handling. For NVMe-oF you may have an additional complication where the local communication controller dies for some reason but I don't know if you can easily detect that and may need to fallback to timeout.

**Comment by liang2yan** [comment] 2018-08-13 08:09
I think I reproduced this issue in my env.  The steps are as below:
1. run spdk hotplug tool. The command is as below:
./examples/hotplug/hotplug -n 5 -r 5  -t 4000
2. run following bash script:

```
for qwe in $(seq 1 7); do
        echo 1 >  /sys/bus/pci/devices/0000\:08\:00.0/remove
        sleep 10
        echo 1 > /sys/bus/pci/rescan
        ./scripts/setup.sh
done

```
Current behavior:
The hotplug tool will hung up at the last step, unregister_dev. I have checked the hotplug running status, it is in the spdk_nvme_wait_for_completion_robust_lock infinite loop.

**Comment by wanqunintel** [comment] 2018-08-14 05:17
@jimharris , Liang can reproduce it in our environment with a simple script, are you available to look at it

**Comment by jimharris** [comment] 2018-08-14 17:10
Let's discuss at next bug scrub.  I probably do not have bandwidth to look at it currently.

**Comment by changpe1** [comment] 2018-09-06 04:41
I'm adding a timeout parameter to Admin queues, this is the first patch https://review.gerrithub.io/#/c/spdk/spdk/+/424622/, with default polling timeout value, I think this issue can be fixed.

**Comment by wanqunintel** [comment] 2018-10-16 06:07
@liang2yan , would you verify this with Changpeng's patch

**Comment by liang2yan** [comment] 2018-10-17 05:17
verified this issue with patch https://review.gerrithub.io/#/c/spdk/spdk/+/424622/ . This issue still can be reproduced.

**Comment by glodfish-zg** [comment] 2018-10-30 06:54
https://review.gerrithub.io/c/spdk/spdk/+/430875  patch for this issue. @liang2yan  you can give some help to verify again.

**Comment by glodfish-zg** [comment] 2018-11-01 08:31
i think i get what you mean. maybe we need to update the .../example/nvme/hotplug case using event framework.  and is there a corner case in nvme_pcie_ctrlr_delete_io_qpair(), befor we run nvme_pcie_ctrlr_cmd_delete_io_sq(), the device has been removed?

**Comment by liang2yan** [comment] 2018-11-27 06:15
@glodfish-zg , what about your patch status?

**Comment by glodfish-zg** [comment] 2019-01-10 06:00
@liang2yan  Please use this patch https://review.gerrithub.io/c/spdk/spdk/+/439822 to verify again. you can use the latest SPDK version.

**Comment by darsto** [comment] 2019-02-12 15:16
Bug scrub: Let's discuss this on the next week's PRC bug scrub.

**Comment by jimharris** [comment] 2019-02-22 20:31
@changpe1, @baruch - can this issue be closed now?

I see the patch from @glodfish-zg - but that is separate from the original bug reported by @baruch.

**Comment by changpe1** [comment] 2019-02-25 04:30
@jimharris I think we can close this issue for now, @glodfish-zg 's patch can fix the hotplug test tool issue, and for the issue itself, users should enable hotplug feature first, and then it can cover the reported issue.

**Comment by changpe1** [comment] 2019-02-26 01:06
closing this issue for now, because if the hotplug option enabled with NVMe driver, existing driver can cover the scenario.

**Closed by changpe1** 2019-02-26 01:06 UTC
Labels: Waiting on Submitter, bug
