### ISSUE TITLE
iSCSI data corruption in ext4test in NIGHTLY

### ISSUE THREAD

**Issue by darsto** [spdk/spdk#821] opened 2019-06-12 11:30 UTC
ext4test.sh fails in nightly tests:

```
# rpc.py construct_target_node Target1 Target1_alias Nvme0n1p0:0 1:2 64 -d
[...]
# iscsiadm -m node --login -p 10.0.0.1:3260
[...]
# rsync -qav --exclude=.git '--exclude=*.o' /var/jenkins/[...]/spdk/ /mnt/sdbdir/spdk
[...]
# make -C /mnt/sdbdir/spdk -j16
[...]
  CC ethdev_profile.o
In file included from /mnt/sdbdir/spdk/dpdk/lib/librte_ethdev/rte_tm.c:8:
/mnt/sdbdir/spdk/dpdk/lib/librte_ethdev/rte_ethdev.h:3665:35: error: "/*" within comment [-Werror=comment]
  *   - (-ENODEV) if *port_id* inva/* SPDX-License-Identifier: BSD-3-Clause
```

**Comment by darsto** [comment] 2019-06-12 11:33
@Comphix

**Comment by darsto** [comment] 2019-06-13 07:22
Setting priority to high until investigation is done.

**Comment by Comphix** [comment] 2019-06-18 08:43
@darsto , is there a link to the failed testing log? Thanks, Gang

**Comment by darsto** [comment] 2019-06-18 10:11
http://10.102.17.206/results/autotest-nightly/builds/531/archive/RBD_autotest/build.log

**Comment by darsto** [comment] 2019-06-18 15:46
Bug scrub: Ben suggests to find out when this first happened. We know it started failing at least 2 weeks ago.

**Comment by shuhei-matsumoto** [comment] 2019-06-25 22:07
Another log says stray error occurred.

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/545/archive/RBD_autotest/build.log

 CC lib/bdev/malloc/bdev_malloc.o
iscsi.c: In function â€˜create_iscsi_sessâ€™:
iscsi.c:4749:35: error: stray â€˜\211â€™ in program
  sess->DefaultTime2Wait = g_spdkUH‰åATSHƒìH‰}èðHÿ    Hƒ}è u'ðHÿ    H     º¼  H5    H=    è    H‹EèHƒ}è tH‰ÂƒâH…ÒtH‰ÆH=    è    ðHÿ    H‹EèHPBHƒø¾rH‹EèH‰ÆH=    è    H‹Eè·@Bf…Àt'ðHÿ    H     º½  H5    H=    è    ðHÿ    H‹EèHƒ}è tH‰ÂƒâH…ÒtH‰ÆH=    è    ðHÿ    H‹EèH   H=pÿÿÿrH‹EèH‰ÆH=    è    H‹EèH‹€   H…Àu'ðHÿ    H     º¾  H5    H=    è    ðHÿ    H‹EèHƒ}è tH‰ÂƒâH…ÒtH‰ÆH=    è    ðHÿ    H‹EèH   H=pÿÿÿrH‹EèH‰ÆH=    è    ðHÿ    H‹EèH‹˜   H‰ÚH…ÛtH‰ÐƒàH…ÀtH‰ÖH=    è    ðHÿ    


The log Darek pasted is here.
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/531/archive/RBD_autotest/build.log


It looks that  both occurred at not ext4 test but make process?

**Comment by peluse** [comment] 2019-06-25 22:15
Oh I didn't see someone posted the log.  Just in case what I grabbed is different: https://gist.github.com/peluse/2e7a54e12023d7ae4ffc5d149ae188fd

**Comment by shuhei-matsumoto** [comment] 2019-06-25 22:23
The issue looks occurred when injecting error to malloc bdev.

Test error injection
 07:20:46	# /var/jenkins/workspace/RBD_BlobFS_tests/RBD_autotest/spdk/scripts/rpc.py bdev_inject_error EE_Malloc0 all failure -n 1000
  07:20:46	# iscsiadm -m session -P 3
  07:20:46	# grep 'Attached scsi disk'
  07:20:46	# awk '{print $4}'
 07:20:46	# dev=sdb
 07:20:46	# set +e
 07:20:46	# mkfs.ext4 -F /dev/sdb
mke2fs 1.44.2 (14-May-2018)
Warning: could not erase sector 2: Input/output error
Creating filesystem with 131072 4k blocks and 32768 inodes
Filesystem UUID: f8ab43ca-c1c9-4451-99bd-5b56c3e454ed
Superblock backups stored on blocks: 
	32768, 98304

Allocating group tables: 0/4   done                            
Warning: could not read block 0: Input/output error
Warning: could not erase sector 0: Input/output error
Writing inode tables: 0/4   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/4mkfs.ext4: Input/output error while writing out and closing file system
  07:20:47	# trap - ERR
  07:20:47	# print_backtrace
  07:20:47	# [[ hxBE =~ e ]]

**Comment by ak-gh** [comment] 2019-06-25 22:37
On Wed, Jun 26, 2019, 01:23 shuhei-matsumoto <notifications@github.com>
wrote:

> The issue looks occurred when injecting error to malloc bdev.
>

Those likely are expected errors, at least the error injection test
succeeds.

On a separate note, I have recently witnessed multihour iscsi target test
failing (the exact reason wasn't discovered) with LUNs being SPDK GPT
partitions on a single NVMe drive, and that same test succeeding when
reconfigured to run against that same NVMe exposed as a single LUN. Not
sure this is related to the case in question, but may be the issue in both
cases was due to partitions being used.

HTH,
Andrey

**Comment by shuhei-matsumoto** [comment] 2019-06-25 22:41
@ak-gh 

Thank you I was confused. You are correct. So we should return to our original findings, like stray error.
And thanks for sharing the issue you have seen.

**Comment by peluse** [comment] 2019-06-25 22:51
nice catch.  @darssto when you entered the issue is that what you were looking at? If not can you point to where you see the corruption, thanks!

**Comment by darsto** [comment] 2019-06-26 04:22
> It looks that both occurred at not ext4 test but make process?

@shuhei-matsumoto It's compilation of SPDK sources copied over to an SPDK iSCSI target.
Compilation fails, so data must have been corrupted during the copy. This tells us there's a bug somewhere in iSCSI data path. In the issue description I posted an outline of how the test works.

**Comment by shuhei-matsumoto** [comment] 2019-06-26 04:58
@darsto @ak-gh @peluse 

Thank you, I understand the issue now. As Andrey suggested, I will investigate partitioning with iSCSI target first.

**Comment by shuhei-matsumoto** [comment] 2019-06-26 06:08
I'm suspecting the patch https://github.com/spdk/spdk/commit/3cfb1fe8dd1bcf223a2407344c76cfbbaa8aa7f5

This patch was merged 16 days ago.

**Comment by darsto** [comment] 2019-06-26 07:25
We've seen it even earlier though. Here's the same failure from Wed Jun 5
05:02:55 UTC 2019:

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/520/archive/RBD_autotest/build.log

**Comment by shuhei-matsumoto** [comment] 2019-06-27 07:55
I noticed that spdk_bdev_reset is not isolated among multiple split bdevs, but I'm not sure if this is related with the issue.

**Comment by ak-gh** [comment] 2019-06-27 08:00
I guess that, to verify if the case is related to the split vbdev being
used, it's easiest to rerun the test against a non-split bdev first.

Regards,
Andrey

**Comment by shuhei-matsumoto** [comment] 2019-06-27 08:14
Yes, that is reasonable suggestion. I posted a patch to disable using split bdev https://review.gerrithub.io/c/spdk/spdk/+/459587 .

**Comment by ak-gh** [comment] 2019-07-03 20:56
Are there any special considerations to running spdk in a virtualized
environment such as ESX (cpus, polling control, memory reservation, nvme
passthrough)? Any suggestions/heads-ip/hints will be appreciated.

Thanks,
Andrey

**Comment by darsto** [comment] 2019-07-09 13:51
Changing prio to critical - we need to have this figured out before 19.07 release.

**Comment by ak-gh** [comment] 2019-07-10 12:02
I guess the issue is caused by buffer management (or, to the letter, lack of that) in the iscsi target/split bdev.

To my understanding, iSCSI target doesn't allocate buffers on read, delegating that to the bdev backing iSCSI LUN. In case of split bdev, neither vbdev_split_submit_request nor spdk_bdev_part_submit_request it calls do spdk_bdev_io_get_buf for the upper-level bdev io. The allocation therefore occurs at the downstream base bdev level (bdev_nvme in the case of the failing test), and it happens **for that layer's bdev_io** that is allocated to service the upper level io. Unfortunately, that bdev_io is usually freed when it completes, with its buffers put back into buf cache. 

Apparently, this can lead to data corruption if buffers the upper-level io believes it owns are reused by another I/O that has happened to get it from the buf pool concurrently with the initial upper-level I/O being processed by iSCSI target (say, while transmitting the data being read to the client).

To resolve this, split and/or part bdev should take care of calling spdk_bdev_io_get_buf for the submitted I/O, not delegating this to the downstream base bdev.

**Comment by shuhei-matsumoto** [comment] 2019-07-11 04:04
Hi @ak-gh ,

Thank you so much for your insight. I saw your point now.
part bdev calls spdk_bdev_free_io(bdev_io) just after calling the callback to SCSI layer. But SCSI layer calls callback to iSCSI layer and then iSCSI layer will call spdk_bdev_free_io(bdev_io) later after transferring read data to the initiator.

So as you suggest, part bdev will need to have get_buf and its callback in itself.

**Comment by shuhei-matsumoto** [comment] 2019-07-11 05:51
Hi @darsto @ak-gh 

I posted a patch according to Andrey's insight. https://review.gerrithub.io/c/spdk/spdk/+/461348

Will you take a look at it when you can?

-Shuhei

**Comment by ak-gh** [comment] 2019-07-11 07:37
Looks good to me.

**Comment by shuhei-matsumoto** [comment] 2019-07-11 07:51
Thank you Andrey.

I could reproduce the issue by reducing bdev_io buffer pool size to two, and delaying free buffer by cusotmizing bdevperf tool as follows:

Before fix verification failed
```
[root@localhost spdk]# ./test/bdev/bdevperf/bdevperf -c bdev.ini -m 0x4 -q 128 -o 16384 -w verify -t 30
Ignoring -m option. Verify can only run with a single core.
Starting SPDK v19.07-pre / DPDK 19.02.0 initialization...
[ DPDK EAL parameters: bdevperf --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid31737 ]
EAL: No free hugepages reported in hugepages-1048576kB
app.c: 627:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
Running I/O for 30 seconds...
Buffer mismatch! Disk Offset: 48960
Buffer mismatch! Disk Offset: 194880
Buffer mismatch! Disk Offset: 452416
```

But after fix, no error was observed.
```
[root@localhost spdk]# ./test/bdev/bdevperf/bdevperf -c bdev.ini -m 0x4 -q 128 -o 16384 -w verify -t 30
Ignoring -m option. Verify can only run with a single core.
Starting SPDK v19.07-pre / DPDK 19.02.0 initialization...
[ DPDK EAL parameters: bdevperf --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid6251 ]
EAL: No free hugepages reported in hugepages-1048576kB
app.c: 627:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
Running I/O for 30 seconds...
 Logical core: 0
 Nvme0n1p3           :    1757.70 IO/s      27.46 MB/s
 Nvme0n1p2           :    1755.87 IO/s      27.44 MB/s
 Nvme0n1p1           :    1754.80 IO/s      27.42 MB/s
 Nvme0n1p0           :    1753.60 IO/s      27.40 MB/s
 =====================================================
 Total               :    7021.97 IO/s     109.72 MB/s

```


```
diff --git a/lib/bdev/bdev.c b/lib/bdev/bdev.c
index 1dcc544..5022e63 100644
--- a/lib/bdev/bdev.c
+++ b/lib/bdev/bdev.c
@@ -60,8 +60,8 @@ int __itt_init_ittlib(const char *, __itt_group_id);

 #define SPDK_BDEV_IO_POOL_SIZE                 (64 * 1024 - 1)
 #define SPDK_BDEV_IO_CACHE_SIZE                        256
-#define BUF_SMALL_POOL_SIZE                    8191
-#define BUF_LARGE_POOL_SIZE                    1023
+#define BUF_SMALL_POOL_SIZE                    2
+#define BUF_LARGE_POOL_SIZE                    2
 #define NOMEM_THRESHOLD_COUNT                  8
 #define ZERO_BUFFER_SIZE                       0x100000

--- a/test/bdev/bdevperf/bdevperf.c
+++ b/test/bdev/bdevperf/bdevperf.c
@@ -433,9 +433,20 @@ end_run(void *arg1, void *arg2)
        }
 }

-static void
-bdevperf_complete(struct spdk_bdev_io *bdev_io, bool success, void *cb_arg)
+struct _comp_ctx {
+       struct spdk_bdev_io *bdev_io;
+       bool success;
+       void *cb_arg;
+       struct spdk_poller *poller;
+};
+
+static int
+_bdevperf_complete(void *arg1)
 {
+       struct _comp_ctx *ctx = arg1;
+       struct spdk_bdev_io *bdev_io = ctx->bdev_io;
+       bool success = ctx->success;
+       void *cb_arg = ctx->cb_arg;
        struct io_target        *target;
        struct bdevperf_task    *task = cb_arg;
        struct spdk_event       *complete;
@@ -443,6 +454,9 @@ bdevperf_complete(struct spdk_bdev_io *bdev_io, bool success, void *cb_arg)
        int                     iovcnt;
        bool                    md_check;

+       spdk_poller_unregister(&ctx->poller);
+       free(ctx);
+
        target = task->target;
        md_check = spdk_bdev_get_dif_type(target->bdev) == SPDK_DIF_DISABLE;

@@ -491,6 +505,22 @@ bdevperf_complete(struct spdk_bdev_io *bdev_io, bool success, void *cb_arg)
                        spdk_event_call(complete);
                }
        }
+
+       return 0;
+}
+
+static void
+bdevperf_complete(struct spdk_bdev_io *bdev_io, bool success, void *cb_arg)
+{
+       struct _comp_ctx *ctx;
+
+       ctx = calloc(1, sizeof(*ctx));
+
+       ctx->bdev_io = bdev_io;
+       ctx->success = success;
+       ctx->cb_arg = cb_arg;
+
+       ctx->poller = spdk_poller_register(_bdevperf_complete, ctx, 1);
 }

```

**Comment by ak-gh** [comment] 2019-07-11 07:54
Ok, looks like we've nailed it down :).

**Comment by ak-gh** [comment] 2019-07-11 18:50
Shuhei-san,

I believe you should submit the patch, for the issue to be verified and closed.

Regards,
Andrey

**Comment by shuhei-matsumoto** [comment] 2019-07-11 22:14
Thank you again Andrey. All will complete after getting another approval by Darek or Changpeng. -Shuhei

**Closed** 2019-07-12 02:37 UTC
Labels: Critical, bug
