### ISSUE TITLE
NVMe-TCP target failed to connect after shutdown test

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1210] opened 2020-02-17 23:04 UTC
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/3319/archive/nvmf-tcp-autotest/build.log

Extra sleep may be needed.

```
************************************
START TEST nvmf_target_disconnect_tc2
************************************
 18:01:45	# xtrace_enable
 18:01:45	# nvmf_target_disconnect_tc2
 18:01:45	# disconnect_init 127.0.0.1
 18:01:45	# nvmfappstart '-m 0xF0'
 18:01:45	# timing_enter start_nvmf_tgt
 18:01:45	# xtrace_disable
 18:01:45	# '[' no '!=' yes ']'
 18:01:45	# PREV_BASH_OPTS=ehxBET
 18:01:45	# [[ ehxBET == *\x* ]]
 18:01:45	# XTRACE_DISABLED=yes
 18:01:45	# set +x
 18:01:45	# xtrace_enable
 18:01:45	# nvmfpid=41833
 18:01:45	# trap 'process_shm --id $NVMF_APP_SHM_ID; nvmftestfini; exit 1' SIGINT SIGTERM EXIT
 18:01:45	# waitforlisten 41833
 18:01:45	# ./app/nvmf_tgt/nvmf_tgt -i 0 -e 0xFFFF -m 0xF0
 18:01:45	# '[' -z 41833 ']'
 18:01:45	# local rpc_addr=/var/tmp/spdk.sock
 18:01:45	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
 18:01:45	# xtrace_disable
 18:01:45	# '[' no '!=' yes ']'
 18:01:45	# PREV_BASH_OPTS=ehxBET
 18:01:45	# [[ ehxBET == *\x* ]]
 18:01:45	# XTRACE_DISABLED=yes
 18:01:45	# set +x
Starting SPDK v20.04-pre git sha1 4eb50bc6b8 / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: nvmf -c 0xF0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
EAL: No available hugepages reported in hugepages-1048576kB
app.c: 642:spdk_app_start: *NOTICE*: Total cores available: 4
app.c: 543:spdk_app_setup_trace: *NOTICE*: Tracepoint Group Mask 0xFFFF specified.
app.c: 547:spdk_app_setup_trace: *NOTICE*: Use 'spdk_trace -s nvmf -i 0' to capture a snapshot of events at runtime.
app.c: 549:spdk_app_setup_trace: *NOTICE*: Or copy /dev/shm/nvmf_trace.0 for offline analysis/debug.
reactor.c: 316:_spdk_reactor_run: *NOTICE*: Reactor started on core 5
reactor.c: 316:_spdk_reactor_run: *NOTICE*: Reactor started on core 6
reactor.c: 316:_spdk_reactor_run: *NOTICE*: Reactor started on core 7
reactor.c: 316:_spdk_reactor_run: *NOTICE*: Reactor started on core 4
 18:01:46	# xtrace_enable
 18:01:46	# ((  i == 0  ))
 18:01:46	# return 0
 18:01:46	# timing_exit start_nvmf_tgt
 18:01:46	# xtrace_disable
 18:01:46	# '[' no '!=' yes ']'
 18:01:46	# PREV_BASH_OPTS=ehxBET
 18:01:46	# [[ ehxBET == *\x* ]]
 18:01:46	# XTRACE_DISABLED=yes
 18:01:46	# set +x
 18:01:46	# xtrace_enable
 18:01:46	# /var/jenkins/workspace/nvmf-tcp-autotest/spdk/scripts/rpc.py bdev_malloc_create 64 512 -b Malloc0
Malloc0
 18:01:46	# /var/jenkins/workspace/nvmf-tcp-autotest/spdk/scripts/rpc.py nvmf_create_transport -t tcp -o
tcp.c: 478:spdk_nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
 18:01:46	# /var/jenkins/workspace/nvmf-tcp-autotest/spdk/scripts/rpc.py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001
nvmf_subsystem_create is deprecated, use nvmf_create_subsystem instead.
 18:01:46	# /var/jenkins/workspace/nvmf-tcp-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
 18:01:47	# /var/jenkins/workspace/nvmf-tcp-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 127.0.0.1 -s 4420
tcp.c: 667:spdk_nvmf_tcp_listen: *NOTICE*: *** NVMe/TCP Target Listening on 127.0.0.1 port 4420 ***
 18:01:47	# reconnectpid=41863
 18:01:47	# /var/jenkins/workspace/nvmf-tcp-autotest/spdk/examples/nvme/reconnect/reconnect -q 32 -o 4096 -w randrw -M 50 -t 10 -c 0xF -r 'trtype:tcp adrfam:IPv4 traddr:127.0.0.1 trsvcid:4420'
 18:01:47	# sleep 2
Starting SPDK v20.04-pre git sha1 4eb50bc6b8 / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: reconnect --no-shconf -c 0xF --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid41863 ]
EAL: No available hugepages reported in hugepages-1048576kB
 18:01:49	# kill -9 41833
 18:01:49	# sleep 2
nvme_qpair.c: 475:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
nvme_qpair.c: 475:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
nvme_qpair.c: 475:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
nvme_tcp.c:1469:nvme_tcp_qpair_icreq_send: *ERROR*: Failed to construct the tqpair=0x7f9724000b60 via correct icresp
nvme_tcp.c:1543:nvme_tcp_ctrlr_connect_qpair: *ERROR*: Unable to connect the tqpair
qpair failed and we were unable to recover it.
posix.c: 358:spdk_posix_sock_create: *ERROR*: connect() failed, errno = 111
nvme_tcp.c:1531:nvme_tcp_ctrlr_connect_qpair: *ERROR*: sock connection error of tqpair=0x7f9724000b60 with addr=127.0.0.1, port=4420
qpair failed and we were unable to recover it.
```

**Comment by spdkci** [comment] 2020-02-17 23:05
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3319.html

**Comment by spdkci** [comment] 2020-02-18 14:34
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3910.html

**Comment by spdkci** [comment] 2020-02-19 21:55
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4073.html

**Comment by jimharris** [comment] 2020-02-20 04:31
Bug scrub: assigning to @Seth5141 - he wants to investigate why the spdk_nvme_ctrlr_reconnect_io_qpair is returning something other than -ENXIO

**Comment by spdkci** [comment] 2020-02-21 10:14
Another instance of this failure. Reported by @pawelkax. log: https://ci.spdk.io/public_build/autotest-per-patch_4280.html

**Comment by spdkci** [comment] 2020-03-02 07:32
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_5127.html

**Comment by optimistyzy** [comment] 2020-03-10 07:53
> Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_5127.html

The issue reported by @tomzawadzki  is not related with the issue reported by @shuhei-matsumoto, it is generated by the "invalid test"

**Comment by spdkci** [comment] 2020-03-19 00:41
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_6903.html

**Comment by spdkci** [comment] 2020-03-20 09:36
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_7040.html

**Comment by spdkci** [comment] 2020-04-06 10:42
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_9159.html

**Comment by spdkci** [comment] 2020-04-30 23:20
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_12279.html

**Comment by Seth5141** [comment] 2020-06-03 21:44
I am closing this as a duplicate of #1318. With the exception of one log, all of these come from the NVMe-oF TCP target_disconnect test.

**Closed** 2020-06-03 21:44 UTC
Labels: Intermittent Failure
