### ISSUE TITLE
rocksdb.sh not working properly

### ISSUE THREAD

**Issue by jyizheng** [spdk/spdk#1488] opened 2020-07-09 22:56 UTC
Hi experts,

I am trying to run rocksdb with spdk. I downloaded rocksdb code and spdk code in my home directory.
Then I compiled spdk source code successfully. Then, I tried to run test/blobfs/rocksdb/rocksdb.sh.
However, I got an error message below: 

=================================================
ar: creating librocksdb.a
  CCLD     db_bench
  popd
~/spdk/test/blobfs/rocksdb
  timing_exit db_bench_build
  xtrace_disable
 '[' no '!=' yes ']'
 PREV_BASH_OPTS=ehxBET
  [[ ehxBET == *\x* ]]
 XTRACE_DISABLED=yes
  set +x
 xtrace_enable
  /home/betrfs/spdk/scripts/gen_nvme.sh
 echo '[Global]'
  echo 'TpointGroupMask 0x80'
 trap 'dump_db_bench_on_err; run_bsdump || :; rm -f $ROCKSDB_CONF; exit 1' SIGINT SIGTERM EXIT
  '[' -z '' ']'
 cat /home/betrfs/spdk/test/blobfs/rocksdb/rocksdb.conf
  run_test blobfs_mkfs /home/betrfs/spdk/test/blobfs/mkfs/mkfs /home/betrfs/spdk/test/blobfs/rocksdb/rocksdb.conf Nvme0n1
  '[' 4 -le 1 ']'
  xtrace_disable
  '[' no '!=' yes ']'
  PREV_BASH_OPTS=ehxBET
  [[ ehxBET == *\x* ]]
 XTRACE_DISABLED=yes
  set +x
************************************
START TEST blobfs_mkfs
************************************
  xtrace_enable
 /home/betrfs/spdk/test/blobfs/mkfs/mkfs /home/betrfs/spdk/test/blobfs/rocksdb/rocksdb.conf Nvme0n1
**[2020-07-09 18:40:13.266200] conf.c: 613:spdk_conf_read: *ERROR*: INI configuration has been deprecated and will be removed in a future release. Please switch to JSON-RPC.**
Starting SPDK v20.07-pre git sha1 055507496 / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: spdk_mkfs --no-shconf -c 0x3 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid25253 ]
EAL: No available hugepages reported in hugepages-1048576kB
[2020-07-09 18:40:13.272890] app.c: 652:spdk_app_start: *NOTICE*: Total cores available: 2
[2020-07-09 18:40:13.344054] app.c: 553:app_setup_trace: *NOTICE*: Tracepoint Group Mask 0x80 specified.
[2020-07-09 18:40:13.344113] app.c: 557:app_setup_trace: *NOTICE*: Use 'spdk_trace -s spdk_mkfs -p 25253' to capture a snapshot of events at runtime.
[2020-07-09 18:40:13.344123] app.c: 559:app_setup_trace: *NOTICE*: Or copy /dev/shm/spdk_mkfs_trace.pid25253 for offline analysis/debug.
[2020-07-09 18:40:13.344241] reactor.c: 371:reactor_run: *NOTICE*: Reactor started on core 1
[2020-07-09 18:40:13.344504] reactor.c: 371:reactor_run: *NOTICE*: Reactor started on core 0
[2020-07-09 18:40:13.344583] accel_engine.c: 245:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
Initializing filesystem on bdev Nvme0n1...[2020-07-09 18:40:13.359589] bdev.c:5645:spdk_bdev_open_ext: *ERROR*: Failed to find bdev with name: Nvme0n1

Failed to initialize filesystem on bdev Nvme0n1...done.
======================================================================

I debug the problem a little bit. It seems the reason is that INI configure file (rocksdb.conf) is no longer supported by SPDK. 
I found a similar problem here #1404 .

Is there any way to fix this problem?  

Thanks in advance.

**Comment by Comphix** [comment] 2020-07-13 01:55
The problem is that there is no bdev (Nvme0n1) found:

nitializing filesystem on bdev Nvme0n1...[2020-07-09 18:40:13.359589] bdev.c:5645:spdk_bdev_open_ext: ERROR: Failed to find bdev with name: Nvme0n1

You may check with you /home/betrfs/spdk/test/blobfs/rocksdb/rocksdb.conf file to see whether this is a Nvme0n1 device configured.

For example, below is my conf content:

cat ../spdk/etc/spdk/rocksdb.conf
[Nvme]
  TransportID "trtype:PCIe traddr:0000:0c:00.0" Nvme0

**Comment by changpe1** [comment] 2020-07-20 01:05
@Comphix is right. There is no PCIe based NVMe SSD in your system, you should use scripts/setup.sh to bind one PCIe SSD first. We are going to drop the configuration support in future but still can support it for now.  @jyizheng I'm going to close this issue.

**Closed by changpe1** 2020-07-20 01:05 UTC
Labels: Waiting on Submitter
