### ISSUE TITLE
[centos7-vg-autotest] SPDK CI Jenkins - build timed out

### ISSUE THREAD

**Issue by rafalste** [spdk/spdk#2002] opened 2021-06-22 08:47 UTC
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/50486/archive/centos7-vg-autotest/build.log

## Execution failed at

```00:15:40.902  + vagrant upload /var/jenkins/workspace/centos7-vg-autotest/autorun-spdk.conf /home/vagrant/autorun-spdk.conf
00:15:44.081  Uploading /var/jenkins/workspace/centos7-vg-autotest/autorun-spdk.conf to /home/vagrant/autorun-spdk.conf
00:15:52.259  Upload has completed successfully!
00:15:52.259  
00:15:52.259    Source: /var/jenkins/workspace/centos7-vg-autotest/autorun-spdk.conf
00:15:52.259    Destination: /home/vagrant/autorun-spdk.conf
00:15:52.285  + [[ -d /var/jenkins/workspace/centos7-vg-autotest/rocksdb.zip ]]
00:15:52.286  + vagrant ssh -c 'sudo chown vagrant /home/vagrant/spdk_repo'
00:15:59.478  + vagrant ssh -c 'nohup dmesg -w &> /home/vagrant/spdk_repo/output/dmesg.log &'
00:16:00.433  Build timed out (after 15 minutes). Marking the build as failed.
00:16:00.442  Build was aborted
00:16:00.443  [PostBuildScript] - [INFO] Executing post build scripts.

**Comment by spdkci** [comment] 2021-06-22 08:51
Another instance of this failure. Reported by @rafalste. log: https://ci.spdk.io/public_build/autotest-per-patch_50486.html

**Comment by spdkci** [comment] 2021-06-22 08:54
Another instance of this failure. Reported by @rafalste. log: https://ci.spdk.io/public_build/autotest-per-patch_50487.html

**Comment by jimharris** [comment] 2021-06-22 14:43
The problem really occurs a bit further up in the log (you can tell by the timestamps) - this is from the 50486 failure.  I've updated the title a bit to reflect the cause.

00:01:20.804  ==> default: Creating shared folders metadata...
00:01:20.822  ==> default: Starting domain.
00:01:22.731  ==> default: Waiting for domain to get an IP address...
00:01:32.919  ==> default: Waiting for SSH to become available...
00:04:05.094      default: 
00:04:05.094      default: Inserting generated public key within guest...
00:04:24.288      default: Removing insecure key from the guest if it's present...
00:04:43.729      default: Key inserted! Disconnecting and reconnecting using new SSH key...
00:04:47.817  ==> default: Configuring and enabling network interfaces...
00:05:41.156      default: SSH address: 192.168.121.78:22
00:05:41.156      default: SSH username: vagrant
00:05:41.156      default: SSH auth method: password
00:06:45.173  ==> default: Configuring proxy environment variables...
00:09:26.295  ==> default: Configuring proxy for Git...
00:11:21.772  ==> default: Configuring proxy for Yum...
00:13:13.094  ==> default: Rsyncing folder: /var/jenkins/workspace/centos7-vg-autotest/spdk/ => /home/vagrant/spdk_repo/spdk
00:14:23.487  ==> default: Mounting SSHFS shared folder...
00:14:53.823  ==> default: Mounting folder via SSHFS: /var/jenkins/workspace/centos7-vg-autotest/centos7-libvirt/output => /home/vagrant/spdk_repo/output
00:14:53.826  ==> default: Checking Mount..
00:15:18.621  ==> default: Folder Successfully Mounted!
00:15:18.680  
00:15:18.680    SUCCESS!
00:15:18.680  
00:15:18.680    cd to /var/jenkins/workspace/centos7-vg-autotest/centos7-libvirt and type "vagrant ssh" to use.
00:15:18.681    Use vagrant "suspend" and vagrant "resume" to stop and start.
00:15:18.681    Use vagrant "destroy" followed by "rm -rf /var/jenkins/workspace/centos7-vg-autotest/centos7-libvirt" to destroy all trace of vm.
00:15:18.681

**Comment by jimharris** [comment] 2021-06-22 14:45
The problem really occurs a bit further up in the log (you can tell by the timestamps) - this is from the 50486 failure.  The 50487 failure is basically the same.

00:01:20.804  ==> default: Creating shared folders metadata...
00:01:20.822  ==> default: Starting domain.
00:01:22.731  ==> default: Waiting for domain to get an IP address...
00:01:32.919  ==> default: Waiting for SSH to become available...
00:04:05.094      default: 
00:04:05.094      default: Inserting generated public key within guest...
00:04:24.288      default: Removing insecure key from the guest if it's present...
00:04:43.729      default: Key inserted! Disconnecting and reconnecting using new SSH key...
00:04:47.817  ==> default: Configuring and enabling network interfaces...
00:05:41.156      default: SSH address: 192.168.121.78:22
00:05:41.156      default: SSH username: vagrant
00:05:41.156      default: SSH auth method: password
00:06:45.173  ==> default: Configuring proxy environment variables...
00:09:26.295  ==> default: Configuring proxy for Git...
00:11:21.772  ==> default: Configuring proxy for Yum...
00:13:13.094  ==> default: Rsyncing folder: /var/jenkins/workspace/centos7-vg-autotest/spdk/ => /home/vagrant/spdk_repo/spdk
00:14:23.487  ==> default: Mounting SSHFS shared folder...
00:14:53.823  ==> default: Mounting folder via SSHFS: /var/jenkins/workspace/centos7-vg-autotest/centos7-libvirt/output => /home/vagrant/spdk_repo/output
00:14:53.826  ==> default: Checking Mount..
00:15:18.621  ==> default: Folder Successfully Mounted!
00:15:18.680  
00:15:18.680    SUCCESS!
00:15:18.680  
00:15:18.680    cd to /var/jenkins/workspace/centos7-vg-autotest/centos7-libvirt and type "vagrant ssh" to use.
00:15:18.681    Use vagrant "suspend" and vagrant "resume" to stop and start.
00:15:18.681    Use vagrant "destroy" followed by "rm -rf /var/jenkins/workspace/centos7-vg-autotest/centos7-libvirt" to destroy all trace of vm.
00:15:18.681

**Comment by jimharris** [comment] 2021-06-22 14:45
The 50487 failure is basically the same.

**Comment by mikeBashStuff** [comment] 2021-06-22 14:51
It seems like vagrant got stuck while executing from its proxyconf plugin. Since it's not needed I removed it from the affected host (will do the same for the remaining VM hosts later this week).

**Comment by spdkci** [comment] 2021-06-24 00:32
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_50485.html

**Comment by spdkci** [comment] 2021-08-03 07:52
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_54940.html

**Comment by jimharris** [comment] 2021-08-20 23:59
This issue seems to be fixed now.

**Closed by jimharris** 2021-08-20 23:59 UTC
Labels: Intermittent Failure
