### ISSUE TITLE
New build failure for release v21.07

### ISSUE THREAD

**Issue by stvml** [spdk/spdk#2222] opened 2021-11-01 20:21 UTC
# Bug report

We noticed a recent regression in the build for v21.07, first identified yesterday. I suspect it's related to the release of v21.10. Following the build steps which were successful before now results in a failure.

## Expected Behavior

Successful build.

## Current Behavior

When running `make`, we see this output:
```
Found ninja-1.10.2.git.kitware.jobserver-1 at /usr/local/bin/ninja
ninja: Entering directory `/spdk/dpdk/build-tmp'
[199/262] Generating drivers/rte_bus_vdev.pmd.c with a custom command
FAILED: drivers/rte_bus_vdev.pmd.c 
/usr/bin/python3.6 ../buildtools/gen-pmdinfo-cfile.py /spdk/dpdk/build-tmp/buildtools ar /spdk/dpdk/build-tmp/drivers/libtmp_rte_bus_vdev.a drivers/rte_bus_vdev.pmd.c /usr/bin/python3.6 ../buildtools/pmdinfogen.py elf
ar: `x' cannot be used on thin archives.
Traceback (most recent call last):
  File "../buildtools/gen-pmdinfo-cfile.py", line 17, in <module>
    run_ar("x")
  File "../buildtools/gen-pmdinfo-cfile.py", line 14, in <lambda>
    stdout=subprocess.PIPE, check=True, cwd=temp
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ar', 'x', '/spdk/dpdk/build-tmp/drivers/libtmp_rte_bus_vdev.a']' returned non-zero exit status 1.
[213/262] Compiling C object lib/librte_vhost.a.p/vhost_vhost_crypto.c.o
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:144: all] Error 1
make: *** [/spdk/mk/spdk.subdirs.mk:44: dpdkbuild] Error 2
```

## Possible Solution

**?**

## Steps to Reproduce

Build steps as follows:

```
git clone -b v21.07 https://github.com/spdk/spdk
cd spdk
git submodule update --init
./scripts/pkgdep.sh
./configure --with-idxd
make
```
It is at this point that the failure occurs.

## Context (Environment including OS version, SPDK version, etc.)

Running the build inside Docker, relevant `Dockerfile` excerpt as follows:
```
FROM centos:centos8.3.2011 As build
RUN yum install -y dnf-plugins-core
RUN dnf config-manager --set-enabled powertools
RUN yum install -y wget git diffutils nasm

ARG SPDK_VER=v21.07
ARG SPDK_REPO=https://github.com/spdk/spdk
RUN git clone -b ${SPDK_VER} ${SPDK_REPO} && \
    cd spdk && \
    git submodule update --init && \
    ./scripts/pkgdep.sh

RUN cd spdk && \
    mkdir /installer && \
    ./configure --with-idxd && \
    make && \
    make install DESTDIR=/installer
```

Replacing v21.07 with v21.10 in the above excerpt results in a successful build, FYI.

Happy to provide any additional information or assist in debugging as needed.

**Comment by mikeBashStuff** [comment] 2021-11-01 20:22
This is a duplicate of https://github.com/spdk/spdk/issues/2214.

**Comment by jimharris** [comment] 2021-11-01 21:30
This patch on the spdk-21.08 branch of the dpdk submodule fixed the issue, while we wait for the upstream DPDK fix:

https://github.com/spdk/dpdk/commit/22e79be44fd5609b7f43236d8be9b68303e99e81

You could try applying this patch to the spdk-21.05 branch (which SPDK 21.07 points to), but not sure if it applies cleanly.

**Closed** 2021-11-01 21:30 UTC
Labels: Sighting
