### ISSUE TITLE
regression/vhost: performance degradation detected

### ISSUE THREAD

**Issue by xjjx** [spdk/spdk#3249] opened 2024-02-01 07:39 UTC
![image](https://github.com/spdk/spdk/assets/4018904/06d20f43-129f-43db-91b5-dcf00c57ec4f)

Introduced by patch https://review.spdk.io/gerrit/c/spdk/spdk/+/20559

$ git log --oneline 355312bfc..b735c429b
b735c429b scsi: Improve child IO split mechanism

# Sighting report

## Steps to Reproduce

1.
2.
3.
4.

**Comment by tomzawadzki** [comment] 2024-02-06 15:13
[Bug scrub] @xjjx Please fill out bit more details of the test case shown from performance.spdk.io. @jimharris Agreed to take a look anyway.

**Comment by jimharris** [comment] 2024-02-07 15:17
@xjjx could you try reverting just that one patch, and confirm it brings performance back to normal?

I've been staring at this patch and still don't see how it could impact performance.

This whole code path is a bit complex, and it's all because it is trying to not call spdk_bdev_unmap_blocks() for 0 blocks. I haven't analyzed all of the bdevs, it's not clear that any of them would have problems with a 0-length unmap. Even if one of them did, we could easily put the 0-block handling in the bdev layer itself. Upper layers shouldn't have to deal with this.

**Comment by jimharris** [comment] 2024-02-07 16:26
https://review.spdk.io/gerrit/c/spdk/spdk/+/21773

Patch 1 handles 0-length unmap calls in the bdev layer. Patch 2 simplifies the scsi_bdev split path.  I'm not 100% convinced this will fix the regression, but let's see.

@xjjx, could you do two re-runs then?

1) master + reverting b735c429b9
2) my 21773 patches

**Comment by karlatec** [comment] 2024-02-14 07:37
Just scheduled builds in the CI. Will let you know when it's done!

**Comment by karlatec** [comment] 2024-02-15 07:40
Here you go @jimharris:
https://performance.spdk.io/d/0pDk4sO4k/spdk-vhost-performance?orgId=1&var-cpus=14&var-qd=64&var-rw=randread&var-manual_builds=true&from=1707892991425&to=1707982268833 (make sure to enable `manual_builds` and `Build annotations` options).
First one is the one with revert, second - using your patches.
Comparing the cases which were most affected during issue submission (cases with 14CPU Vhost + 28VMs and 18CPU VHost + 36 VMs) - I don't see any real performance difference:

![image](https://github.com/spdk/spdk/assets/28856727/c05d6e50-bc00-405b-a28a-8c7beb957e2f)

It might be hard investigating this using current master branch because...
If you change the time range in the dashboards to show[ range between Jan 28th and Feb 2nd](https://performance.spdk.io/d/0pDk4sO4k/spdk-vhost-performance?orgId=1&var-cpus=14&var-qd=64&var-rw=randread&var-manual_builds&from=1706425582595&to=1706855666003) you can see that some other change "improved" the performance by a bit, effectively taking it back to previous level.
![image](https://github.com/spdk/spdk/assets/28856727/e24331a4-379d-4c4e-ac5f-d290aad8d3b2)

Which is quite weird, because I don't see anything Vhost-related in this commit range.
```
[klateck@eagle2 spdk]$ git log --oneline 66ec2569b..158d15b74
158d15b74 util/pipe: Add spdk_pipe_group
94123731c pipe: return buffer when destroying pipe
f4cb9817e util/pipe: add pipe empty check
f506f14e6 nvme/opal: Fix parsing response status
40b0fa6b1 test/nvme/cuse: Fix typo
0f7bdc521 test/nvme: Set SEL only when the field is supported
e229a40f8 autotest: rename SPDK_TEST_ACCEL_IOAT flag
0568555a5 nvme: Add 'rdma_cm_event_timeout_ms' transport option
967ed8a7e bdev/nvme: Add missing fields to json configuration save
74c16d8e8 nvme/pcie: Force psdt to PRP on admin commands without payload
18d5de4a9 bdev_nvme: add hostaddr and hostsvcid in nvme_ctrlr_config_json
52e39fb7f test/packaging: Adjust vs-dpdk test
89d955ae7 rpmbuild: Remove DPDK's doc dir
42fd00131 Update isa-l submodule.
```

**Comment by jimharris** [comment] 2024-02-15 18:43
Thanks @karlatec. I agree it is quite weird, but I could never determine exactly why that suspected patch could have impacted performance either.  Nothing in that series of patches looks suspicious to me.

If I look at the vhost core scaling (SCSI/Split Nvme) now, performance seems back to where it was before all of this was originally reported.

I guess the only thing we could try is comparing b735c, b735c~1, and b735c+my patches. The first two are to effectively reproduce the earlier results, and the third one (with my patches) are just to show that alleviated the problem.

Either way, we should definitely merge https://review.spdk.io/gerrit/c/spdk/spdk/+/21773, it is an overall improvement.

**Comment by karlatec** [comment] 2024-02-20 12:57
> I guess the only thing we could try is comparing b735c, b735c~1, and b735c+my patches.
Sorry, I was out for a few days. Will definitely do that and will try to find the change which "brings back" missing performance after https://github.com/spdk/spdk/commit/b735c429b970b62a0bb813277ebf0ddead160bd2.

**Comment by karlatec** [comment] 2024-02-21 09:52
https://performance.spdk.io/d/0pDk4sO4k/spdk-vhost-performance?orgId=1&var-cpus=1&var-qd=64&var-rw=randread&var-manual_builds&from=1708179618938&to=1708508965473
![image](https://github.com/spdk/spdk/assets/28856727/46636fdc-b624-4b17-83a9-7960fcfa5b59)

From left side:
*[ b735c~1](https://review.spdk.io/gerrit/c/spdk/spdk/+/21582/4) - performance OK
* [b735c](https://review.spdk.io/gerrit/c/spdk/spdk/+/20559/5) - performance drop
* [b735c+my patches](https://review.spdk.io/gerrit/c/spdk/spdk/+/21884/1) (cherry picked changes from https://review.spdk.io/gerrit/c/spdk/spdk/+/21773 on top of b735c) - performance OK

Now let me find which of below changes caused performance to go up again:
```
[klateck@eagle2 spdk]$ git log --oneline 66ec2569b..158d15b74
158d15b74 util/pipe: Add spdk_pipe_group
94123731c pipe: return buffer when destroying pipe
f4cb9817e util/pipe: add pipe empty check
f506f14e6 nvme/opal: Fix parsing response status
40b0fa6b1 test/nvme/cuse: Fix typo
0f7bdc521 test/nvme: Set SEL only when the field is supported
e229a40f8 autotest: rename SPDK_TEST_ACCEL_IOAT flag
0568555a5 nvme: Add 'rdma_cm_event_timeout_ms' transport option
967ed8a7e bdev/nvme: Add missing fields to json configuration save
74c16d8e8 nvme/pcie: Force psdt to PRP on admin commands without payload
18d5de4a9 bdev_nvme: add hostaddr and hostsvcid in nvme_ctrlr_config_json
52e39fb7f test/packaging: Adjust vs-dpdk test
89d955ae7 rpmbuild: Remove DPDK's doc dir
42fd00131 Update isa-l submodule. 
```

**Comment by jimharris** [comment] 2024-02-21 14:20
I think it's only a nice-to-have to figure out which commit caused performance to go up again.

I propose we get https://review.spdk.io/gerrit/c/spdk/spdk/+/21773 merged and then we can close this issue. We can try to debug this more if needed, but I don't think it's critical (at least relative to other priorities).

**Comment by karlatec** [comment] 2024-02-27 14:17
Alright, so I finished the bisect, but I guess it's pretty useless.
So looks like the first commit which brings back the performance is... `21652: bdev/nvme: Add missing fields to json configuration save | https://review.spdk.io/gerrit/c/spdk/spdk/+/21652` 967ed8a7e3a249469f3fb4e0efebe070a1ffa540

https://performance.spdk.io/d/0pDk4sO4k/spdk-vhost-performance?orgId=1&var-cpus=14&var-qd=64&var-rw=randread&var-manual_builds&from=1708723356188&to=1708764644683

I'm pretty sure that my `git bisect bad/good` decisions were correct, which leads me to conclusion that there might be something wrong / not stable with this particular test case. It's always "the blue line" in the top-most chart which is Vhost SCSI+SplitNVMe, 14CPUs + 28 VMs. But not Vhost SCSI+Lvol, it's not affected. I am not sure what can cause instability for this particular datapoint.

I saw in git log that you're doing some more work for SCSI so we should keep our eyes open for performance changes in the dashboards, but any regression would quite probably manifest itself in more than 1 data point.

**Comment by karlatec** [comment] 2024-02-27 14:19
> I am not sure what can cause instability for this particular datapoint.

As another very recent example: https://performance.spdk.io/d/0pDk4sO4k/spdk-vhost-performance?orgId=1&var-cpus=14&var-qd=64&var-rw=randread&var-manual_builds=false&from=1708988417231&to=1709043468559
![image](https://github.com/spdk/spdk/assets/28856727/54dc83ab-a449-48b4-9d69-c039e874b0fb)

Dropped again to 17.5M IOPS for just this single datapoint, and there's no way any of these changes could have made this happen:
```
bb3749887 (HEAD -> master, origin/master, origin/HEAD) raid: adjust block size calculations to support interleaved md
1c0f35045 raid: fix checking base bdev blocklen when creating raid bdev
8aab02a72 doc/raid: update to reflect current state
```

**Comment by jimharris** [comment] 2024-02-27 16:51
Patches merged.

**Closed by jimharris** 2024-02-27 16:51 UTC
Labels: bug, Medium, Patches out for review
