### ISSUE TITLE
"rake" needed to run pkgdep.sh on RHEL 9.0

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2981] opened 2023-04-13 22:50 UTC
FYI fresh install of RHEL9.0, clone repo and run pkgdep.sh --all and get the output below. "dnf install rake" and re-running everything works fine.

Fetching shfmt_v3.1.0_linux_amd64...
shfmt-3.1.0 installed
'/home/peluse/spdk/scripts/bash-completion/spdk' -> '/etc/bash_completion.d/spdk'
Cloning into '/usr/src/markdownlint'...
remote: Enumerating objects: 2227, done.
remote: Counting objects: 100% (285/285), done.
remote: Compressing objects: 100% (175/175), done.
remote: Total 2227 (delta 133), reused 223 (delta 90), pack-reused 1942
Receiving objects: 100% (2227/2227), 522.56 KiB | 2.20 MiB/s, done.
Resolving deltas: 100% (1155/1155), done.
Note: switching to 'd9646f3b4ec3f9d6716dc84e92604c31ba148527'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

... <bunch of output from pkgdep.sh clipped>
Fetching rake-13.0.6.gem
Successfully installed rake-13.0.6
Parsing documentation for rake-13.0.6
Installing ri documentation for rake-13.0.6
Done installing documentation for rake after 0 seconds
1 gem installed
sudo: rake: command not found

**Comment by mikeBashStuff** [comment] 2023-04-14 07:40
The pkgdep attempts to install rake's gem when it's missing (this can be seen in the log above as well). The question is how default $PATH looks like under RHEL 9.0 and/or where the target rake script ends up at the end (it may differ across distros, some will just use /usr/bin, some /usr/local/bin (where some, for instance, did not include the latter under the $PATH. As far as I recall, that was the case for centos8 for instance. It's likely that RHEL 9.0 simply follows this trend)).

**Comment by ksztyber** [comment] 2023-04-18 15:21
[Bug scrub] @mikeBashStuff will take a look if we can use distro's package managers to install rake. That should fix the issue.

**Comment by peluse** [comment] 2023-06-05 23:00
Thanks guys, low priority of course at least from my view.  Just setting up RHEL 9 on SPR and ran into this one which is new (the missing crb thing)

Updating Subscription Management repositories.
Error: No matching repo to modify: crb.
Error!
[root@localhost spdk]# grep -r crb
grep: .git/objects/pack/pack-14f7be766af947bc04f176824d870442723a4bba.pack: binary file matches
scripts/pkgdep/rhel.sh:		enable+=("crb")

**Comment by mikeBashStuff** [comment] 2023-06-13 15:15
> Thanks guys, low priority of course at least from my view. Just setting up RHEL 9 on SPR and ran into this one which is new (the missing crb thing)
> 
> Updating Subscription Management repositories. Error: No matching repo to modify: crb. Error! [root@localhost spdk]# grep -r crb grep: .git/objects/pack/pack-14f7be766af947bc04f176824d870442723a4bba.pack: binary file matches scripts/pkgdep/rhel.sh: enable+=("crb")

I added this based on what I was working with years back when I had an active dev subscription to RHEL. Unfortunately, I don't have access to it anymore so I can't verify what changed exactly.

**Comment by mikeBashStuff** [comment] 2023-06-20 12:50
Here are some adjustments: https://review.spdk.io/gerrit/c/spdk/spdk/+/18760. Tested under RHEL9 image that I was able to fetch from the redhat's console.

**Comment by tomzawadzki** [comment] 2023-07-11 14:05
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/18760 was merged.

@peluse please let us know if the issue is now fixed on your end.

**Comment by tomzawadzki** [comment] 2023-07-25 14:40
@peluse Closing since the patch was merged, feel free to re-open if there is anything to fix here.

**Closed by tomzawadzki** 2023-07-25 14:40 UTC
Labels: enhancement, Low, Waiting on Submitter
