### ISSUE TITLE
iscsi target reported error if formating the nvme bdev which has been set the qos value

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#634] opened 2019-01-30 03:12 UTC
## Expected Behavior
No error messages or some notice messages.

## Current Behavior
iscsi target reported error messages.

## Steps to Reproduce
1. run iscsi target with malloc, nvme, raid and lvol bdev.
2. set the qos value on the bdevs, like below:

```
./scripts/rpc.py set_bdev_qos_limit --r_mbytes_per_sec 50 Malloc0
./scripts/rpc.py set_bdev_qos_limit --r_mbytes_per_sec 50 Nvme0n1
./scripts/rpc.py set_bdev_qos_limit --r_mbytes_per_sec 50 Raid0
./scripts/rpc.py set_bdev_qos_limit --r_mbytes_per_sec 50 3524164c-b2ae-485c-88f0-6c1502e51430
./scripts/rpc.py set_bdev_qos_limit --w_mbytes_per_sec 50 Malloc1
./scripts/rpc.py set_bdev_qos_limit --w_mbytes_per_sec 50 Nvme1n1
./scripts/rpc.py set_bdev_qos_limit --w_mbytes_per_sec 50 Raid1
./scripts/rpc.py set_bdev_qos_limit --w_mbytes_per_sec 50 a300acc1-5f87-4a0c-951d-b35f48ceb9e5

```
3. run formating the nvme bdev which have set the write bandwidth value.

4. the process is very slow, and iscsi target started to report error:
```

lun.c: 110:_spdk_scsi_lun_execute_mgmt_task: *ERROR*: ABORT_TASK failed
iscsi.c:3358:spdk_iscsi_op_task: *NOTICE*: ABORT_TASK
lun.c: 110:_spdk_scsi_lun_execute_mgmt_task: *ERROR*: ABORT_TASK failed
iscsi.c:3358:spdk_iscsi_op_task: *NOTICE*: ABORT_TASK
lun.c: 110:_spdk_scsi_lun_execute_mgmt_task: *ERROR*: ABORT_TASK failed
iscsi.c:3382:spdk_iscsi_op_task: *NOTICE*: LOGICAL_UNIT_RESET
nvme_ctrlr.c: 808:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
conn.c:1209:spdk_iscsi_conn_flush_pdus_internal: *ERROR*: spdk_sock_writev() failed, errno 104: Connection reset by peer
conn.c:1209:spdk_iscsi_conn_flush_pdus_internal: *ERROR*: spdk_sock_writev() failed, errno 32: Broken pipe
conn.c:1209:spdk_iscsi_conn_flush_pdus_internal: *ERROR*: spdk_sock_writev() failed, errno 104: Connection reset by peer
conn.c:1209:spdk_iscsi_conn_flush_pdus_internal: *ERROR*: spdk_sock_writev() failed, errno 32: Broken pipe
iscsi.c:3358:spdk_iscsi_op_task: *NOTICE*: ABORT_TASK
lun.c: 110:_spdk_scsi_lun_execute_mgmt_task: *ERROR*: ABORT_TASK failed
iscsi.c:3358:spdk_iscsi_op_task: *NOTICE*: ABORT_TASK
lun.c: 110:_spdk_scsi_lun_execute_mgmt_task: *ERROR*: ABORT_TASK failed
iscsi.c:3382:spdk_iscsi_op_task: *NOTICE*: LOGICAL_UNIT_RESET
nvme_ctrlr.c: 808:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
iscsi.c:3358:spdk_iscsi_op_task: *NOTICE*: ABORT_TASK
lun.c: 110:_spdk_scsi_lun_execute_mgmt_task: *ERROR*: ABORT_TASK failed
```

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit: abc156458fff4f25104604bf91b39651d9423a9a

**Comment by jimharris** [comment] 2019-01-30 03:15
Do you need to create all of these bdevs to reproduce the problem?

**Comment by changpe1** [comment] 2019-01-30 03:32
I think QOS should not count unmap/write zeroes bytes, because for format command, the initiator may only send one unmap command with very big LBA range.

**Comment by Comphix** [comment] 2019-01-30 06:49
@liang2yan , please have a verify with https://review.gerrithub.io/#/c/spdk/spdk/+/442673/ 

As Changpeng mentioned, the discard command has been limited by the QoS policy. I've removed the limitation on these kinds of IO like discard, write zeros, unmap.

**Comment by liang2yan** [comment] 2019-01-30 07:33
@Comphix , I have verified your patch. it can fix this issue.

**Comment by jimharris** [comment] 2019-01-30 16:41
Hi @liang2yan,

Could you please add more details on this issue?

1) Exactly what command are you running to "format"?
2) Are you formatting all of the bdevs - or only the NVMe bdevs?
3) What is the base device for the lvol store(s) containing the lvols?
4) What are the base devices for the RAID volumes?

Thanks,

-Jim

**Comment by jimharris** [comment] 2019-01-30 17:16
A few thoughts:

1) Even with a low (50MB/s) write limit, the format should still be able to make forward progress.  We need to understand why that is not happening.
2) I ran a similar test on my system - but creating a 1GB logical volume, and formatting using "mkfs.ext4 -F /dev/sdX" (sdb on my system).  Discard completed fairly quickly, but then I'm getting periodic aborts and LUN resets when writing the superblocks.  This is with a 10MB/s limit.

I think we need to think through this some more.  I'm really concerned that just removing unmap/write_zeroes from the write limits is not the correct solution.

-Jim

**Comment by jimharris** [comment] 2019-03-01 22:26
Closing this issue since patch from @Comphix has been merged.

@Comphix - please let's make sure we track the separate QoS limit for unmap/write_zeroes.

**Closed by jimharris** 2019-03-01 22:26 UTC
Labels: bug
