### ISSUE TITLE
libspdk_bdev.so SOVERSION bump?

### ISSUE THREAD

**Issue by brianjmurrell** [spdk/spdk#1217] opened 2020-02-19 18:12 UTC
Looking at https://github.com/spdk/spdk/commit/53b92a6c18f0c0f2e44575d259bea26ab546b014, it appears that this is breaking the API of `spdk_bdev_io_complete_nvme_status()`.  Is my understanding of this correct?

That would appear to have happened in v19.10 if I'm reading the [CHANGELOG.md](https://github.com/spdk/spdk/blob/53b92a6c18f0c0f2e44575d259bea26ab546b014/CHANGELOG.md) correctly, yes?

I believe this symbol is built into `libspdk_bdev.so", yet that shared library's version hasn't changed since at least 19.04.1 where I see it was (and is) still libspdk_bdev.so.1.0.

Shouldn't `libspdk_bdev.so.1.0`'s version have been updated to indicate the API breakage and prevent the use of an older `libspdk_bdev.so` by consumers that are using the new, updated version of that API?

**Comment by jimharris** [comment] 2020-02-19 19:05
SOVERSION should have been bumped.  We'll discuss this at tonight's bug scrub (including how to better catch these in the future.)

**Comment by brianjmurrell** [comment] 2020-02-19 21:30
Thanks much @jimharris.

Does this warrant a bug-fix point release, to get consumers using the correct version of shared library again?

**Comment by jimharris** [comment] 2020-02-19 21:34
That will be part of tonight's discussion.  We would certainly fix this in a v20.01.1 release - the question is whether we would do a v19.10.2 release as well.

**Comment by brianjmurrell** [comment] 2020-02-19 21:35
Ah, yes, indeed.  For us, at the moment, the v20.01.1 release would be the most important.  We never did jump on v19.10.x.  But I could see that some others might have.

**Comment by brianjmurrell** [comment] 2020-02-19 21:49
@jimharris What are the chances that any other shared libs missed SOVERSION bumps?  Would consideration of that in your meeting tonight and a rectification in a v20.01.1 be feasible if so?

Frankly, I'd love to get rid of our `Requires:` and `BuildRequires:` for `spdk` and `spdk-devel` versions and let RPM's _auto-{requires,provides}_ take care of finding the right RPM version of the needed spdk libraries.

Even if that only happened in v20.01.1, that's a good point to move forward from.

**Comment by tomzawadzki** [comment] 2020-02-25 16:09
[Bug scrub]:
First and last SOVERSION was set 2 years ago. With this in mind we will be updating minor version of SOVERSION for the v20.01.1 and master in all shared libraries.

Going forward the model would be to update each library separately as changes affecting ABI happen.
This would require addition of tests that will check the compatibility.

Together with @Seth5141 we will be forwarding patches for both of the above, updating this GH issue as they are completed.

**Comment by brianjmurrell** [comment] 2020-03-02 12:25
> we will be updating minor version of SOVERSION

Hopefully this is just a misunderstanding of what the above actually means, but if APIs have been broken in a library since the last SOVERSION setting, the SOVERSION **MUST** have a major version bump.  The shared library linker only considers the major version number for library compatibility.

On another note, not to seem impatient, but rather just for our own (DAOS) release planning, do you have any estimate on when this SOVERSION bump work will be complete and a v20.01.1 will be available with the fixes?

**Comment by jimharris** [comment] 2020-03-02 15:18
Seth and I talked Friday about this - we will be making a major version bump.

We are planning v20.01.1 for March 20th.  It will contain the SOVERSION bumps as well as other bug fixes since the v20.01 release.

**Comment by Seth5141** [comment] 2020-03-19 04:20
The major SO version has been bumped, and We have implemented a test to avoid regressions like this going forward. I'm going to close this issue for now since the remaining tasks like splitting out map files for individual libraries are really added features.

**Closed by Seth5141** 2020-03-19 04:20 UTC
Labels: Bug Scrub
