### ISSUE TITLE
[nvmf-vg-autotest] test hangs executing `rxe_cfg_small.sh stop`

### ISSUE THREAD

**Issue by AlekseyMarchuk** [spdk/spdk#1787] opened 2021-02-06 16:33 UTC
```

00:06:16.833  ************************************
00:06:16.833  END TEST nvmf_fio
00:06:16.833  ************************************
00:06:16.833  
00:06:16.833  real	0m7.993s
00:06:16.833  user	0m33.094s
00:06:16.833  sys	0m2.495s
00:06:16.833   19:04:30	# xtrace_disable
00:06:16.833   19:04:30	# '[' no '!=' yes ']'
00:06:16.833   19:04:30	# PREV_BASH_OPTS=ehxBET
00:06:16.833   19:04:30	# [[ ehxBET == *\x* ]]
00:06:16.833   19:04:30	# XTRACE_DISABLED=yes
00:06:16.833   19:04:30	# set +x
00:06:16.870   19:04:30	# xtrace_enable
00:06:16.871   19:04:30	# check_ip_is_soft_roce
00:06:16.871   19:04:30	# '[' rdma '!=' rdma ']'
00:06:16.872   19:04:30	# rxe_cfg status rxe
00:06:16.872   19:04:30	# grep -wq ''
00:06:16.872   19:04:30	# /home/vagrant/spdk_repo/spdk/scripts/rxe_cfg_small.sh status rxe
00:06:16.913   19:04:30	# timing_exit host
00:06:16.913   19:04:30	# xtrace_disable
00:06:16.913   19:04:30	# '[' no '!=' yes ']'
00:06:16.913   19:04:30	# PREV_BASH_OPTS=ehxBET
00:06:16.913   19:04:30	# [[ ehxBET == *\x* ]]
00:06:16.913   19:04:30	# XTRACE_DISABLED=yes
00:06:16.913   19:04:30	# set +x
00:06:16.950   19:04:30	# xtrace_enable
00:06:16.950   19:04:30	# trap - SIGINT SIGTERM EXIT
00:06:16.950   19:04:30	# revert_soft_roce
00:06:16.950   19:04:30	# rxe_cfg stop
00:06:16.950   19:04:30	# /home/vagrant/spdk_repo/spdk/scripts/rxe_cfg_small.sh stop
00:15:10.892  Build timed out (after 15 minutes). Marking the build as failed.
00:15:10.902  Build was aborted
00:15:10.903  [PostBuildScript] - [INFO] Executing post build scripts.
00:15:10.909  [nvmf-vg-autotest] $ /usr/bin/env bash /tmp/jenkins6362072358482656539.sh
00:15:10.914  + [[ -n fedora31 ]]
00:15:10.914  + mv /var/jenkins/workspace/nvmf-vg-autotest/fedora31-libvirt/output /var/jenkins/workspace/nvmf-vg-autotest/output
00:15:10.935  [nvmf-vg-autotest] $ /usr/bin/env bash /tmp/jenkins2331472607005349427.sh
00:15:10.939  Start stage post_get_build_log.sh
00:15:10.996  + vagrant destroy -f
```

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_35973.html

**Comment by spdkci** [comment] 2021-02-06 16:34
Another instance of this failure. Reported by @AlekseyMarchuk. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_35973.html

**Comment by mikeBashStuff** [comment] 2021-02-09 11:54
I am afraid I can't reproduce this on my local system. I used the same config as in `nvmf-vg-autotest`, with the same patchsets on top, same distro, etc. The `rxe_cfg_small.sh`'s stop routine simple removes the rxe drivers from the kernel and all the infiniband devices. So either modprobe blocked while unloading the modules or writes to infiniband class did. There's nothing interesting in the kernel log though to confirm if that's what actually happened. With higher reproducing rate it would be possible to simple trace the execution of the script, but since there's no clear way of triggering the issue it won't do much good.

let's leave this issue open for some time to make sure if this was just one-time occurrence.

**Comment by mikeBashStuff** [comment] 2021-02-15 08:16
Since this issue hasn't resurfaced for over a week let's close this issue. Will reopen it whenever needed.

**Closed by mikeBashStuff** 2021-02-15 08:16 UTC
Labels: Intermittent Failure
