### ISSUE TITLE
[nvmf_phy_autotest] nvmf_multipath - CQ transport error -6 (No such device or address) on qpair id 0

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2181] opened 2021-09-29 14:11 UTC
# CI Intermittent Failure

During nvmf_multipath test, system ran into an error with CQ transport.

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_59356.html

## Execution failed at

```
00:08:23.890  ************************************
00:08:23.890  START TEST nvmf_multipath
00:08:23.890  ************************************
...
00:08:55.783  Running I/O for 10 seconds...
00:08:55.783  [2021-09-29 15:33:35.147403] nvme_qpair.c: 752:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 0
00:08:55.783  [2021-09-29 15:33:35.147495] nvme_ctrlr.c:1029:nvme_ctrlr_fail: *ERROR*: [nqn.2016-06.io.spdk:cnode1] in failed state.
00:08:55.783  [2021-09-29 15:33:35.147515] bdev_nvme.c:1036:bdev_nvme_failover_start: *NOTICE*: Start failover from 192.168.100.8:4420 to 192.168.100.8:4421
00:08:55.783  [2021-09-29 15:33:35.147529] nvme_ctrlr.c:1023:nvme_ctrlr_fail: *NOTICE*: [nqn.2016-06.io.spdk:cnode1] already in failed state
00:08:55.783  [2021-09-29 15:33:35.211831] rdma_verbs.c: 111:spdk_rdma_qp_destroy: *WARNING*: Destroying qpair with queued Work Requests
00:08:55.783  [2021-09-29 15:33:35.212821] bdev_nvme.c:3782:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
00:08:55.783  [2021-09-29 15:33:35.212881] bdev_nvme.c:3782:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
00:08:55.783  [2021-09-29 15:33:35.212928] bdev_nvme.c:3782:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
00:08:55.783  [2021-09-29 15:33:35.212972] bdev_nvme.c:3782:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
...
00:08:55.784  [2021-09-29 15:33:35.218468] bdev_nvme.c:3782:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
00:08:55.784  [2021-09-29 15:33:35.218535] nvme_ctrlr.c:1546:nvme_ctrlr_reset_pre: *NOTICE*: [nqn.2016-06.io.spdk:cnode1] resetting controller
00:08:55.784  [2021-09-29 15:33:35.309846] bdev_nvme.c:1026:bdev_nvme_failover_start: *NOTICE*: Unable to perform reset, already in progress.
00:08:55.784  [2021-09-29 15:33:35.381030] bdev_nvme.c: 809:bdev_nvme_reset_complete: *NOTICE*: Resetting controller successful.
00:08:55.784  
 Job: NVMe0n1 (Core Mask 0x1)
00:08:55.784  	 Verification LBA range: start 0x0 length 0x4000
00:08:55.784  	 NVMe0n1             :    3275.70 IOPS      12.80 MiB/s
00:08:55.784  	                     :    8720.40 Fail/s     0.00 TO/s
00:08:55.784  
=============================================================
00:08:55.784  
 Total                       :    3275.70 IOPS      12.80 MiB/s
00:08:55.784            :    8720.40 Fail/s     0.00 TO/s
00:08:55.784  Received shutdown signal, test time was about 4758.067046 seconds
00:08:55.784  
=============================================================
00:08:55.784  
 Total                       :    3275.70 IOPS      12.80 MiB/s
00:08:55.784            :    8720.40 Fail/s     0.00 TO/s
00:08:55.784    15:33:43	-- host/multipath.sh@68 -- # grep -c 'Resetting controller successful'
00:08:55.787   15:33:43	-- host/multipath.sh@68 -- # count=1
00:08:55.788   15:33:43	-- host/multipath.sh@70 -- # (( count != 3 ))
00:08:55.788   15:33:43	-- host/multipath.sh@71 -- # false
00:08:55.788    15:33:43	-- host/multipath.sh@71 -- # trap - ERR
00:08:55.788    15:33:43	-- host/multipath.sh@71 -- # print_backtrace
00:08:55.789    15:33:43	-- common/autotest_common.sh@988 -- # [[ ehxBET =~ e ]]
00:08:55.789    15:33:43	-- common/autotest_common.sh@990 -- # args=("${BASH_ARGV[@]}")
00:08:55.789    15:33:43	-- common/autotest_common.sh@990 -- # local args
00:08:55.789    15:33:43	-- common/autotest_common.sh@992 -- # xtrace_disable
00:08:55.790    15:33:43	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:08:55.790    15:33:43	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:08:55.790    15:33:43	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:08:55.791    15:33:43	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:08:55.791    15:33:43	-- common/autotest_common.sh@19 -- # set +x
00:08:55.791  ========== Backtrace start: ==========
00:08:55.791  
00:08:55.795  in test/nvmf/host/multipath.sh:71 -> main(["--transport=rdma"])
00:08:55.796       ...
00:08:55.796     66  	cat $testdir/try.txt
00:08:55.796     67  	# if this test fails it means we didn't fail over to the second
00:08:55.796     68  	count="$(grep -c "Resetting controller successful" < $testdir/try.txt)"
00:08:55.796     69  	
00:08:55.796     70  	if ((count != 3)); then
00:08:55.796  => 71  		false
00:08:55.796     72  	fi
00:08:55.796     73  	
00:08:55.796     74  	# Part 2 of the test. Start removing ports, starting with the one we are connected to, confirm that the ctrlr remains active until the final trid is removed.
00:08:55.796     75  	$rootdir/test/bdev/bdevperf/bdevperf -z -r $bdevperf_rpc_sock -q 128 -o 4096 -w verify -t 1 -f &> $testdir/try.txt &
00:08:55.796     76  	bdevperf_pid=$!
00:08:55.796       ...
00:08:55.796  
00:08:55.796  ========== Backtrace end ==========
```

**Comment by spdkci** [comment] 2021-09-29 14:18
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59356.html

**Comment by spdkci** [comment] 2021-09-30 06:51
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59380.html

**Comment by ksztyber** [comment] 2021-09-30 07:17
This is a duplicate of #2128.

**Closed by ksztyber** 2021-09-30 07:17 UTC
Labels: Intermittent Failure

**Comment by spdkci** [comment] 2021-12-15 08:51
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_63865.html
