### ISSUE TITLE
Attaching a block device to vm  use too long time when use spdk vhost

### ISSUE THREAD

**Issue by windye** [spdk/spdk#894] opened 2019-08-02 04:15 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

Qemu communicate with vhost by vhost_user messgage when attach a block device,  this process complete quickly in normal case.
## Current Behavior

 Attach a one queue block device  spent up to 45s, when physical host use much memory(about 300GB). the time increase linearly when the block device queue number increase, so four queue block device use several minutes, which lead to vm start failed.

we have located the time-consuming function "spdk_mem_unregister" which seem like traverse all the memroy use 2M unit.
## Steps to Reproduce

1. Create several  64G-memory VM  to exhaust  the physical host memory which have 312 1G-hugepages.
2. Attach a block device to the VM  to test the complete time.

## Context (Environment including OS version, SPDK version, etc.)

spdk version 19.01
physical host use linux 4.14 kernel with iommu enbable

**Comment by darsto** [comment] 2019-08-08 05:47
SPDK < 19.07 used to repeatedly map/unmap memory during QEMU VM boot because of limitations in DPDK's vhost library. We have applied a few significant optimizations to this process in the latest SPDK version.

Could you try running SPDK 19.07 + DPDK 19.05? It should take much less amount of time to boot and should no longer scale with the amount of used queues.

D.

**Comment by changpe1** [comment] 2019-08-13 00:28
@darsto any update for the issue ? I don't see the improvement with latest SPDK.

**Comment by changpe1** [comment] 2019-10-17 02:55
@windye Can you try with latest SPDK version ? the issue should be fixed.

**Comment by changpe1** [comment] 2019-12-17 01:31
I've confirmed this issue has been fixed, closing it for now.

**Closed by changpe1** 2019-12-17 01:31 UTC
