### ISSUE TITLE
[nvmf-autotest] Build timed out, rxe not found

### ISSUE THREAD

**Issue by AlekseyMarchuk** [spdk/spdk#1352] opened 2020-04-17 07:04 UTC
Issue happens after nvmf_target_disconnect

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_10887.html

## Execution failed at
```
************************************
END TEST nvmf_target_disconnect
************************************
 08:39:25	# xtrace_enable
 08:39:25	# timing_exit host
 08:39:25	# xtrace_disable
 08:39:25	# '[' no '!=' yes ']'
 08:39:25	# PREV_BASH_OPTS=ehxBET
 08:39:25	# [[ ehxBET == *\x* ]]
 08:39:25	# XTRACE_DISABLED=yes
 08:39:25	# set +x
 08:39:25	# xtrace_enable
 08:39:25	# trap - SIGINT SIGTERM EXIT
 08:39:25	# revert_soft_roce
 08:39:25	# hash rxe_cfg
  08:39:25	# ip -o link
  08:39:25	# awk '{print $2}'
  08:39:25	# cut -d: -f1
 08:39:25	# interfaces='lo
ens3
ens4'
 08:39:25	# for interface in $interfaces
 08:39:25	# rxe_cfg remove lo
Use of uninitialized value $rxe in string eq at /usr/bin/rxe_cfg line 452.
Use of uninitialized value $rxe in pattern match (m//) at /usr/bin/rxe_cfg line 452.
Use of uninitialized value $rxe in concatenation (.) or string at /usr/bin/rxe_cfg line 471.
rxe instance  not found
 08:39:25	# for interface in $interfaces
 08:39:25	# rxe_cfg remove ens3
Build timed out (after 15 minutes). Marking the build as failed.
```

**Comment by spdkci** [comment] 2020-04-17 07:06
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_10887.html

**Comment by mikeBashStuff** [comment] 2020-04-21 16:30
The actual error about missing interface is an expected one since `rxe_cfg` doesn't consider net devs to be valid if they don't have a digit in their names (hilarious, I know). By default, `lo` would be skipped by `rxe_cfg` but since it's being explicitly added, you can see also the following (this happens for every build and it doesn't really affect anything):
```
# rxe_cfg add lo
eth_name (lo) looks bogus
```
When it's time to remove all rxeNs, we again pass all the net devs to `rxe_cfg` (instead of just issuing `stop` once).  This time, it's too much for `rxe_cfg` since it's not able to handle case where an interface to be `remove`d is not an `rxeN` id, a net dev that maps to some `rxeN` or a plain `all` arg. The `$rxe` is then left `undef()ined`, hence the exception. 

The timeout, however, probably happened while `rxe_cfg` made an attempt to remove `eno3`, i.e. writing to `/sys/module/rdma_rxe/parameters/remove` most likely blocked for too long. Kernel also spit this, as a last message: `[20127.272791] rdma_rxe: no qp matches qpn 0x1ae`. Not sure how that ties in with the rest though. 

@karlatec highlighting you as an fyi since you wanted to look into it.

**Comment by tomzawadzki** [comment] 2020-04-21 16:55
[Bug scrub] This occurred only in the instance of linked patches.
@karlatec suspects that other patches in review might have caused it, and will take a look at.

Yet as those were not merged, it should be fine to close this particular issue.

**Comment by tomzawadzki** [comment] 2020-05-05 10:12
@karlatec Have you had a chance to take a look to verify your assumption ? Can this issue be closed ?

**Comment by karlatec** [comment] 2020-05-05 11:22
Sorry, unfortunately not.

**Comment by karlatec** [comment] 2020-05-19 14:51
Late update: I looked a bit more through the logs but could not find anything related. Since this does not reproduce for quite some time now I think we can clsoe the issue.

**Closed** 2020-05-19 14:53 UTC
Labels: Intermittent Failure
