### ISSUE TITLE
【TcpOverNvme】No improve of fio performance when target cores are increased in the context of  testing data digest

### ISSUE THREAD

**Issue by ikernel-mryao** [spdk/spdk#2919] opened 2023-02-24 03:01 UTC
# Sighting report

Hi all,
we are testing  NVMe-oF TCP Performance with openEuler operation system in the context of testing data digest. And we find the SPDK NVMe-oF TCP Target IOPS throughput or bandwidth  does not improve while  Target CPU cores are increased.

## Expected Behavior

similer to https://ci.spdk.io/download/performance-reports/SPDK_tcp_perf_report_2110.pdf.    From Test Case 1: SPDK NVMe-oF TCP 
Target I/O core scaling Table 6 , we can see Bandwidth or IOPS will improve when Target  Cores increase. （i.e. change from 1cores to 4cores） 

## Current Behavior

the SPDK NVMe-oF TCP Target IOPS throughput or bandwidth does not improve while Target CPU cores are increased. 
[fio randread]
when the number of Target cores  is 1 , the fio result is IOPS = 17070.191,  bandwidth = 2185240 kB/s
when the number of Target cores  is 4 , the fio result is IOPS = 2186.779,  bandwidth =     280163 kB/s
## Steps to Reproduce

1.  Refer to https://ci.spdk.io/download/performance-reports/SPDK_tcp_perf_report_2110.pdf, like Figure 1: High-Level NVMe-oF TCP performance testing setup.  Here, we use one initiator and one NVMe-oF-Target， 4x Intel P4610 SSD.
2.   Install OS of openEuler-22.03-LTS-SP1 lastest version
3.   Install relevant dependent packages on both initiator and NVMe-oF-Target
yum -y install make automake gcc gcc-c++ kernel-devel
yum -y install gcc bc
yum -y install make
yum -y install openssl binutils bison flex
yum -y install libdb-devel
yum -y install pkg-config
yum -y install libbpf-devel
yum -y install libmnl-devel
yum -y install libcap-devel
yum -y install libcgroup-tools
yum -y install libcgroup-devel
yum -y install nvme-cli
yum -y install libaio-devel
yum -y install libibverbs-devel
yum -y install librdmacm-utils
yum -y install libpmemblk-devel
yum -y install libfdt-devel
yum -y install libarchive-devel
yum -y install jansson-devel
yum -y install libpcap-devel
yum -y install sphinx
yum -y install sysstat
yum -y install java
yum -y install java-devel
yum -y install jq
yum -y install python3-pip
yum -y install autoconf
yum -y install automake libtool
yum -y install pkgconf asciidoc xmlto
yum -y install libuuid-devel
yum -y install json-c-devel
yum -y install keyutils-libs-devel zlib-devel
yum -y install fakeroot asciidoctor
yum -y install file gnupg patch patchutils
yum -y install meson
pip3 install paramiko pandas
 【note 1: if pip3 install failed, we can do this:
 pip3 install paramiko -i [http://pypi.douban.com/simple --trusted-host pypi.douban.com](http://pypi.douban.com/simple%20--trusted-host%20pypi.douban.com)
pip3 install pandas -i [http://pypi.douban.com/simple --trusted-host pypi.douban.com](http://pypi.douban.com/simple%20--trusted-host%20pypi.douban.com)
】
4. download ice driver on  both initiator and NVMe-oF-Target
    downlod address: https://www.intel.com/content/www/us/en/download/19630/intel-network-adapter-driver-for-e810-series-devices-under-linux.html
    tar -xzvf ice-1.9.11.tar.gz
   【note 2:
      modify script name of  set_irq_affinity.
      mv ice/ice-1.9.11/scripts/set_irq_affinity   ice/ice-1.9.11/scripts/set_irq_affinity.sh
    】

5.  install iprouter2 on  both initiator and NVMe-oF-Target
   git clone
https://git.kernel.org/pub/scm/network/iproute2/iproute2.git
cd iproute2
./configure
  make DESTDIR=/opt/iproute2 install
6.  install Nvmetcli  on  both initiator and NVMe-oF-Target
git clone https://github.com/JunxiongGuan/nvmetcli
cd nvmetcli
git clone https://github.com/open-iscsi/configshell-fb
cd configshell-fb
  python3 setup.py install  
 【note 3：if this step fails , we can do this 
    download pyparsing-2.0.3.tar.gz  from https://pypi.org/simple/pyparsing/,
    tar -zxvf pyparsing-2.0.3.tar.gz
   cd  pyparsing-2.0.3
   python3 setup.py install
   cd ../../
  】
cd ..   (come to the level directory of nvmetci)
 python3 setup.py install

7.  install fio on  both initiator and NVMe-oF-Target
    git clone https://github.com/axboe/fio  
cd fio
make
make install

8.   install idxd-config on  both initiator and NVMe-oF-Target
git clone https://github.com/intel/idxd-config.git 
cd idxd-config
./autogen.sh
./configure CFLAGS='-g -O2' --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib64 
make
make check
sudo make install

9.  install spdk on  both initiator and NVMe-oF-Target
git clone https://github.com/spdk/spdk.git
cd spdk
git submodule update -init
【note 4:
  if this step fails, we can download these submodules
  and we should change dpdk version to branch 22.07】
scripts/pkgdep.sh --all
【note 5:
  change script name of openeuler.sh
  mv spdk/scripts/pkgdep/openeuler.sh  spdk/scripts/pkgdep/openEuler.sh
】
【note 6:
 if it appears ”WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None))“，
 we can do these:
 mkdir -p ~/.pip/
 touch ~/.pip/pip.conf
the content of ~/.pip/pip.conf： 
[global]
index-url = http://pypi.douban.com/simple
[install]
trusted-host=pypi.douban.com
】
./configure --with-fio=<path_to_fio>  --with-idxd
make
make install
10.  bios configure
1）	advance→ Socket Configuration → Uncore Configuration → 
Uncore General Configuration → Limit CPU PA to 46 bits  <Disable>
2）	Socket Configuration --> IIO Configuration --> Intel VT  for Direct I/O (VT-d)
->Intel VT  for Direct I/O (VT-d)  <Enable>
->Opt-out Illegal MSI Mitigation  <Enable> 
->PCIe ENQCMD/ENQCMDS                <Yes>

11. grub cmdline configure
vi  /etc/default/grub
GRUB_CMDLINE_LINUX=="intel_iommu=on,sm_on, iommu=pt"
grub2-mkconfig -o /boot/efi/EFI/xxx

12. NIC  1*100GbE
target ip : 192.168.100.1
initiator ip : 192.168.100.2

13、do these steps on initiator
modprobe nvme
modprobe nvme_tcp
cd <path_to_spdk>
HUGEMEM=16384 ./scripts/setup.sh

14、do these steps on target
modprobe ice
modprobe vfio
modprobe vfio-pci
modprobe sch_mqprio
modprobe act_mirred
modprobe cls_flower
modprobe nvme
modprobe nvme_tcp
modprobe idxd
cd <path_to_spdk>
HUGEMEM=16384 HUGE_EVEN_ALLOC=yes ./scripts/setup.sh
【note 7:
  if it appears "root user memlock limit : 0 MB",
we can increase limits, open /etc/security/limits.conf and add:
root soft memlock unlimited
root hard memlock unlimited 
】
【note 8:
 if it appears "ERROR： FIO process failed! Option  <numa_mem_policy>: Build fio with libnuma-dev(el) to enable this option"，
we can do these:
yum install -y numactl，
and do step 7 "install fio" again!
】
PYTHONPATH=$PYTHONPATH:$PWD/scripts scripts/perf/nvmf/run_nvmf.py -c /root/config.json
the content of /root/config.json is
{
  "general": {
    "username": "root",
    "password": "123456",
    "transport": "tcp",
    "skip_spdk_install": true
  },
  "target": {
    "nic_ips": ["192.168.100.1"],
    "mode": "spdk",
    "irq_scripts_dir": "/home/xxx/ice/ice-1.9.11/scripts",
    "sar_settings": [true, 60, 60, 3],
    "core_mask": "[2]",
    "zcopy_settings": true,
    "dsa_settings": false,
    "enable_pm": false,
    "enable_pcm": false,
    "enable_bandwidth":false,
    "enable_dpdk_memory":false,
    "num_shared_buffers": 4096
  },
    "initiator1": {
    "ip": "90.90.67.207",
    "nic_ips": ["192.168.100.2"],
    "target_nic_ips": ["192.168.100.1"],
    "mode": "spdk",
    "fio_bin": "/home/yyy/fio/fio/fio",
    "spdk_dir": "/home/yyy/spdk/spdk",
    "irq_scripts_dir": "/home/yyy/ice/ice-1.9.11/scripts",
    "enable_data_digest": true,
    "num_cores": 5
  },
  "fio": {
    "digest_enable": "DATA",
    "bs": ["128k"],
    "qd": [32],
    "rw": ["randread"],
    "rwmixread": 100,
    "run_time": 60,
    "ramp_time": 30,
    "run_num": 1,
    "num_jobs": 3
  }
}

15、we test with different /root/config.json  
    1 target core   
      --- "core_mask": "[2]",
    4  target cores
      --- "core_mask": "[0-3]",

## Context (Environment including OS version, SPDK version, etc.)

OS version: openEuler-22.03-LTS-SP1 lastest version 5.10
SPDK version: SPDK v23.05-pre git sha1 3c5a8ddc4
NIC：E810-CQDA2  1*100GbE  direct connection between initiator and target
CPU：Intel(R) Xeon(R) Platinum 8480
SSD: 4 * SSD  INTEL SSDPE2KE032T8

**Comment by jimharris** [comment] 2023-02-27 15:21
Hi,

Please update the title and beginning of description to mention that you are testing data digest.  This is a key difference between your tests and the performance report.

Can you please try the following experiments, to narrow the problem between general core scaling and data digest parameters:

1) Disable data digest.
2) Keep data digest enabled, but configure without `--with-idxd` option.  This will use SW to calculate crc32c digests instead.

Thanks,

Jim

**Comment by karlatec** [comment] 2023-02-27 15:29
```
when the number of Target cores is 1 , the fio result is IOPS = 17070.191, bandwidth = 2185240 kB/s
when the number of Target cores is 4 , the fio result is IOPS = 2186.779, bandwidth = 280163 kB/s
```
This is very, very low. I saw step 9 `install spdk on both initiator and NVMe-oF-Target`, but can we please confirm 100% that `--enable-debug` was not used for building SPDK? (or similar option for any other software used in the test)

```
NIC：E810-CQDA2 1*100GbE direct connection between initiator and target
```
I saw ICE 1.9.11 being used. Suggest moving to 1.10.1.2.2 for performance tests.
Also, what's the NVM version installed on NICs? (you can check this using `ethtool -i` command)

**Comment by yuntongjin** [comment] 2023-02-28 13:22
the root cause is found,  the E810 is working on safety model due a ICE driver issue in openEuler OS, hance there is only ~20 Gbps throughout on networking, we got performance 128k_256_randwrite IOPS 58075， bw：7438053 without DSA after fix ICE issue.

**Comment by tomzawadzki** [comment] 2023-02-28 15:16
[Community call] @yuntongjin do you still see an issue that needs attention after the ICE driver issue update ?

**Comment by yuntongjin** [comment] 2023-03-01 12:27
> 

as we see a good IOPS performance with DSA, i think this issue can be closed, thanks for your helping and quick response

**Closed** 2023-03-01 13:42 UTC
Labels: Sighting
