### ISSUE TITLE
Lost write when nvmf target is down in a two node setup

### ISSUE THREAD

**Issue by krchug** [spdk/spdk#2364] opened 2022-02-07 13:26 UTC
# Bug report

Running a nvmf target on 192.168.10.18. Exported one bdev out from this nvmf target.
```
sudo ./rpc.py nvmf_create_transport -t RDMA -u 16384 -m 64 -c 8192
sudo ./rpc.py bdev_nvme_attach_controller  --name NVMe0 --trtype pcie --traddr "0000:b1:00.0"
NVMe0n1
sudo ./rpc.py nvmf_create_subsystem nqn.2018-09.io.spdk:cnode1 -a -s SPDK0000000000001 -d SPDK_Controller1
sudo ./rpc.py nvmf_subsystem_add_ns nqn.2018-09.io.spdk:cnode1 NVMe0n1
sudo ./rpc.py nvmf_subsystem_add_listener nqn.2018-09.io.spdk:cnode1 -t rdma -a 192.168.10.18 -s 4420
```

Running nvmf target on machine 192.168.10.19 connecting to the nvmf target on .18.
```
sudo ./rpc.py nvmf_create_transport -t RDMA -u 16384 -m 64 -c 8192
sudo ./rpc.py bdev_nvme_attach_controller  --name NVMe0 --trtype rdma --traddr "192.168.10.18" --trsvcid 4420 --adrfam IPv4 --subnqn "nqn.2018-09.io.spdk:cnode1"
NVMe0n1
sudo ./rpc.py nvmf_create_subsystem nqn.2018-09.io.spdk:cnode2 -a -s SPDK0000000000001 -d SPDK_Controller1
sudo ./rpc.py nvmf_subsystem_add_ns nqn.2018-09.io.spdk:cnode2 NVMe0n1
sudo ./rpc.py nvmf_subsystem_add_listener nqn.2018-09.io.spdk:cnode2 -t rdma -a 192.168.10.19 -s 4420
```

Connected from client onto .19

```
sudo nvme discover -t rdma -a  192.168.10.19 -s 4420

Discovery Log Number of Records 1, Generation counter 1
=====Discovery Log Entry 0======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not required
portid:  0
trsvcid: 4420
subnqn:  nqn.2018-09.io.spdk:cnode2
traddr:  192.168.10.19
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
ngx@sn3:~/spdk/spdk/scripts$ sudo nvme connect -t rdma -n nqn.2018-09.io.spdk:cnode2 -a 192.168.10.19 -s 4420
ngx@sn3:~/spdk/spdk/scripts$ sudo nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev  
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     SPDK0000000000001    SPDK_Controller1                         1           3.84  TB /   3.84  TB    512   B +  0 B   22.01   
```

Did io as follows

Created a test file
ngx@sn3:~/spdk/spdk/scripts$ sudo dd if=/dev/urandom of=/tmp/kc bs=4K count=1
1+0 records in
1+0 records out
4096 bytes (4.1 kB, 4.0 KiB) copied, 0.000271864 s, 15.1 MB/s

Wrote the test file on .19's discovered bdev using oflag=direct
ngx@sn3:~/spdk/spdk/scripts$ sudo dd if=/tmp/kc  of=/dev/nvme0n1 bs=4K count=1 oflag=direct
1+0 records in
1+0 records out
4096 bytes (4.1 kB, 4.0 KiB) copied, 0.000361471 s, 11.3 MB/s

Read back
ngx@sn3:~/spdk/spdk/scripts$ sudo dd if=/dev/nvme0n1 of=/tmp/kcout bs=4K count=1
1+0 records in
1+0 records out
4096 bytes (4.1 kB, 4.0 KiB) copied, 0.000490688 s, 8.3 MB/s

Checksum match
ngx@sn3:~/spdk/spdk/scripts$ md5sum /tmp/kc*
78338a9521429bf7874047bc2dcda897  /tmp/kc
78338a9521429bf7874047bc2dcda897  /tmp/kcout

Created another file
ngx@sn3:~/spdk/spdk/scripts$ sudo dd if=/dev/urandom of=/tmp/kc2 bs=4K count=1
1+0 records in
1+0 records out
4096 bytes (4.1 kB, 4.0 KiB) copied, 0.00028698 s, 14.3 MB/s

Brought nvmf target on .18 down
Tried to write on .19 connected nvme device using oflag=direct.
As expected it failed
ngx@sn3:~/spdk/spdk/scripts$ sudo dd if=/tmp/kc2  of=/dev/nvme0n1 bs=4K count=1 oflag=direct
dd: error writing '/dev/nvme0n1': Input/output error
1+0 records in
0+0 records out
0 bytes copied, 0.00356249 s, 0.0 kB/s

Tried without oflag=direct and the command completed (This is lost write)
ngx@sn3:~/spdk/spdk/scripts$ sudo dd if=/tmp/kc2  of=/dev/nvme0n1 bs=4K count=1 
1+0 records in
1+0 records out
4096 bytes (4.1 kB, 4.0 KiB) copied, 0.00643824 s, 636 kB/s

Tried reading from the device, it failed (as expected)
ngx@sn3:~/spdk/spdk/scripts$ sudo dd if=/dev/nvme0n1 of=/tmp/kcout2 bs=4K count=1
dd: error reading '/dev/nvme0n1': Input/output error
0+0 records in
0+0 records out
0 bytes copied, 0.0140439 s, 0.0 kB/s

Bought the target up on .18 and tried to read again
ngx@sn3:~/spdk/spdk/scripts$ sudo dd if=/dev/nvme0n1 of=/tmp/kcout2 bs=4K count=1
1+0 records in
1+0 records out
4096 bytes (4.1 kB, 4.0 KiB) copied, 0.000583534 s, 7.0 MB/s

The md5sum shows the first write everywhere. Which means the write from /tmp/kc2 which succeded when the nvmf target
was down is lost.
ngx@sn3:~/spdk/spdk/scripts$ md5sum /tmp/kc*
78338a9521429bf7874047bc2dcda897  /tmp/kc
a92f1b6d5a0b6a26ee76a5096a498e0b  /tmp/kc2
78338a9521429bf7874047bc2dcda897  /tmp/kcout
78338a9521429bf7874047bc2dcda897  /tmp/kcout2

## Expected Behavior

Either the second write should fail or get queued and get completed once the nvmf target on .18 comes back online.

## Current Behavior

The dd write command is succesful even when nvmf target was down and even if the write was lost. On reading from the device after bringing up the nvmf target again and confguring it, recieved old data

## Steps to Reproduce

As mentioned above

## Context (Environment including OS version, SPDK version, etc.)

Ubuntu 20.04.1 LTS 
5.4.0-96-generic
SPDK v22.01

**Comment by changpe1** [comment] 2022-02-08 08:47
I don't think the issue is related with SPDK, it's system error.
You need to narrow down this issue to specific SPDK part, or we can't help you.

**Comment by shuhei-matsumoto** [comment] 2022-03-22 07:57
Hi @krchug 

How about enabling I/O error recovery for the target on .18?
We can add -l -1 -o 10 to the bdev_nvme_attach_controller RPC.
Then the expected behavior should happen.

Please have a try when you can.

**Comment by krchug** [comment] 2022-03-22 08:26
HI @shuhei-matsumoto I will give it a try

**Comment by tomzawadzki** [comment] 2023-07-11 14:34
No update for over a year, closing.

@krchug Please re-open if you encounter the issue with latest SPDK.

**Closed by tomzawadzki** 2023-07-11 14:34 UTC
Labels: Waiting on Submitter, Sighting
