### ISSUE TITLE
[reactor_set_interrupt] Timeout on reactor_set_interrupt_mode

### ISSUE THREAD

**Issue by apaszkie** [spdk/spdk#3234] opened 2024-01-15 15:44 UTC
## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_115064.html
https://ci.spdk.io/results/autotest-per-patch/builds/115064/archive/ubuntu22-vg-autotest_26601/build.log

## Execution failed at

```
00:32:19.574   15:01:15	-- interrupt/reactor_set_interrupt.sh@62 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py --plugin interrupt_plugin reactor_set_interrupt_mode 0
00:32:19.834  [2024-01-11 15:01:15.549418] interrupt_tgt.c:  61:rpc_reactor_set_interrupt_mode: *NOTICE*: RPC Start to enable interrupt mode on reactor 0.
00:32:19.834  [2024-01-11 15:01:15.553266] thread.c:2085:spdk_thread_set_interrupt_mode: *NOTICE*: Set spdk_thread (app_thread) to intr mode from poll mode.
00:32:19.834  [2024-01-11 15:01:15.553338] interrupt_tgt.c:  32:rpc_reactor_set_interrupt_mode_cb: *NOTICE*: complete reactor switch
00:33:27.557  Timeout while waiting for response:
00:33:27.557  
00:33:27.557  
00:33:27.557    15:02:15	-- interrupt/reactor_set_interrupt.sh@62 -- # trap - ERR
00:33:27.557    15:02:15	-- interrupt/reactor_set_interrupt.sh@62 -- # print_backtrace
00:33:27.557    15:02:15	-- common/autotest_common.sh@1129 -- # [[ ehxBET =~ e ]]
00:33:27.557    15:02:15	-- common/autotest_common.sh@1131 -- # args=('110587' '110587')
00:33:27.557    15:02:15	-- common/autotest_common.sh@1131 -- # local args
00:33:27.557    15:02:15	-- common/autotest_common.sh@1133 -- # xtrace_disable
00:33:27.557    15:02:15	-- common/autotest_common.sh@10 -- # set +x
00:33:27.557  ========== Backtrace start: ==========
00:33:27.557  
00:33:27.557  in /home/vagrant/spdk_repo/spdk/test/interrupt/reactor_set_interrupt.sh:62 -> reactor_set_intr_mode(["110587"])
00:33:27.557       ...
00:33:27.557     57  		fi
00:33:27.557     58  		# CPU utilization of reactor 2 should be idle
00:33:27.557     59  		reactor_is_idle $spdk_pid 2
00:33:27.557     60  	
00:33:27.557     61  		# Set reactor 0 back to intr mode
00:33:27.557  => 62  		$rpc_py --plugin interrupt_plugin reactor_set_interrupt_mode 0
00:33:27.557     63  		if [ "$without_thd"x != x ]; then
00:33:27.557     64  			# Schedule spdk_threads in thd2_ids back to reactor 0
00:33:27.557     65  			for i in "${thd0_ids[@]}"; do
00:33:27.557     66  				$rpc_py thread_set_cpumask -i $i -m $r0_mask
00:33:27.557     67  			done
00:33:27.557       ...
00:33:27.557  in /home/vagrant/spdk_repo/spdk/test/interrupt/reactor_set_interrupt.sh:81 -> reactor_set_mode_with_threads(["110587"])
00:33:27.557       ...
00:33:27.557     76  		reactor_set_intr_mode $1 "without_thd"
00:33:27.557     77  		return 0
00:33:27.557     78  	}
00:33:27.557     79  	
00:33:27.557     80  	function reactor_set_mode_with_threads() {
00:33:27.557  => 81  		reactor_set_intr_mode $1
00:33:27.557     82  		return 0
00:33:27.557     83  	}
00:33:27.557     84  	
00:33:27.557     85  	# Set reactors with intr_tgt without spdk_thread
00:33:27.557     86  	start_intr_tgt
00:33:27.557       ...
00:33:27.557  in /home/vagrant/spdk_repo/spdk/test/interrupt/reactor_set_interrupt.sh:101 -> main([])
00:33:27.557       ...
00:33:27.557     96  	# Set reactors with intr_tgt with spdk_thread
00:33:27.557     97  	start_intr_tgt
00:33:27.557     98  	setup_bdev_mem
00:33:27.557     99  	setup_bdev_aio
00:33:27.557     100 	
00:33:27.557  => 101 	reactor_set_mode_with_threads $intr_tgt_pid
00:33:27.557     102 	
00:33:27.557     103 	trap - SIGINT SIGTERM EXIT
00:33:27.557     104 	killprocess $intr_tgt_pid
00:33:27.557     105 	cleanup
00:33:27.557       ...
00:33:27.557  
00:33:27.557  ========== Backtrace end ==========
```

**Comment by mikeBashStuff** [comment] 2024-01-15 15:46
Duplicate of https://github.com/spdk/spdk/issues/2670. Closing this, reopening the old one.

**Closed by mikeBashStuff** 2024-01-15 15:46 UTC
Labels: Intermittent Failure
