### ISSUE TITLE
OCF performs really bad

### ISSUE THREAD

**Issue by USTCqzy** [spdk/spdk#2120] opened 2021-08-22 11:25 UTC
# Bug report

OCF perform really bad.

## Expected Behavior

OCF at least performs similar to core device.

## Current Behavior

OCF perform really bad. (e.g. 10 times worse than core device)

## Possible Solution

No idea.

## Steps to Reproduce

1. ./bdevperf -q "$io_depth" -t 300 -w "$read_type" -o 512 -m "$thread" -c test.json -C -F 1.0
test.json
```json
{
    "subsystems": [
      {
        "subsystem": "bdev",
        "config": [
          {
            "method": "bdev_malloc_create",
            "params": {
              "name": "Malloc0",
              "num_blocks": 30000000,
              "block_size": 512,
              "uuid": "a2e6d1bb-1cf5-484a-bd4a-ebbff0043c8b"
            }
          },
          {
            "method": "bdev_nvme_attach_controller",
            "params": {
              "name": "NVMe1",
              "trtype": "PCIe",
              "traddr": "0000:9b:00.0",
              "prchk_reftag": false,
              "prchk_guard": false
            }
          },
          {
            "method": "bdev_ocf_create",
            "params": {
              "name": "Cache1",
              "mode": "wt",
              "cache_bdev_name": "Malloc0",
              "core_bdev_name": "NVMe1n1"
            }
          }
        ]
      }
    ]
  }
```

As ocf homepage saying, 
"In Pass-Through mode, the cache engine will bypass the cache for all operations. This allows the user to enable and disable caching dynamically (by switching between Pass-Through and other cache modes) without need to manually alter I/O path in the application"
mode pt (the orange line) should perform similar to nvme.
![Figure_4_cache_512_randread_15G_zipf](https://user-images.githubusercontent.com/49378451/130353173-bcad1e30-4f52-4fb8-a819-cb18490ea4b2.png)
![Figure_3_nvme_512_randread](https://user-images.githubusercontent.com/49378451/130353254-d2ac0b3a-c8da-4f00-8238-72c63786014a.png)

## Context (Environment including OS version, SPDK version, etc.)

SPDK 21.07.x
Ubuntu 20.04.2

**Comment by Comphix** [comment] 2021-08-22 11:47
Assign to Wayne to do initial triage for OCF related. Thanks, Gang.

**Comment by USTCqzy** [comment] 2021-08-23 15:42
I would like to add more info from new experiments:
I combined a cache using both malloc bdev (to avoid influence from disks), and got stats (through get ocf stats)
```
Stats                   Count   %    
Read hits               5319141 99.99
Read partial misses     1       0.00 
Read full misses        31      0.00 
Read total              5319173 100.00
Pass-Through reads      0       0.00
```
High hit ratio in this experiment.
but got only ~2GB/s
```
Running I/O for 10 seconds...
 Job: Cache1 (Core Mask 0x1)
         Cache1              :   33100.30 IOPS     129.30 MiB/s
 Job: Cache1 (Core Mask 0x2)
         Cache1              :   32595.30 IOPS     127.33 MiB/s
 Job: Cache1 (Core Mask 0x4)
         Cache1              :   32723.10 IOPS     127.82 MiB/s
 Job: Cache1 (Core Mask 0x8)
         Cache1              :   32514.80 IOPS     127.01 MiB/s
 Job: Cache1 (Core Mask 0x10)
         Cache1              :   33000.50 IOPS     128.91 MiB/s
 Job: Cache1 (Core Mask 0x20)
         Cache1              :   33568.10 IOPS     131.13 MiB/s
 Job: Cache1 (Core Mask 0x40)
         Cache1              :   33554.20 IOPS     131.07 MiB/s
 Job: Cache1 (Core Mask 0x80)
         Cache1              :   33219.00 IOPS     129.76 MiB/s
 Job: Cache1 (Core Mask 0x100)
         Cache1              :   33236.50 IOPS     129.83 MiB/s
 Job: Cache1 (Core Mask 0x200)
         Cache1              :   33711.80 IOPS     131.69 MiB/s
 Job: Cache1 (Core Mask 0x400)
         Cache1              :   33784.50 IOPS     131.97 MiB/s
 Job: Cache1 (Core Mask 0x800)
         Cache1              :   33216.50 IOPS     129.75 MiB/s
 Job: Cache1 (Core Mask 0x1000)
         Cache1              :   33318.10 IOPS     130.15 MiB/s
 Job: Cache1 (Core Mask 0x2000)
         Cache1              :   33654.80 IOPS     131.46 MiB/s
 Job: Cache1 (Core Mask 0x4000)
         Cache1              :   33517.80 IOPS     130.93 MiB/s
 Job: Cache1 (Core Mask 0x8000)
         Cache1              :   33201.70 IOPS     129.69 MiB/s
 =============================================================
 Total                       :  531917.00 IOPS    2077.80 MiB/s
```
config:
```bash
$ ./bdevperf -q 1 -t 10 -w randread -o 4096 -m 0xFFFF -c test.json -C -F 1.0
```
test.json
```json
{
    "subsystems": [
      {
        "subsystem": "bdev",
        "config": [
          {
            "method": "bdev_malloc_create",
            "params": {
              "name": "Malloc0",
              "num_blocks": 51200,
              "block_size": 512,
              "uuid": "a2e6d1bb-1cf5-484a-bd4a-ebbff0043c8b"
            }
          },
          {
            "method": "bdev_malloc_create",
            "params": {
              "name": "Malloc1",
              "num_blocks": 51200,
              "block_size": 512,
              "uuid": "a86034db-d4cc-48e9-a3c8-abd2d8ea26e1"
            }
          },
          {
            "method": "bdev_ocf_create",
            "params": {
              "name": "Cache1",
              "mode": "wt",
              "cache_line_size": 4,
              "cache_bdev_name": "Malloc0",
              "core_bdev_name": "Malloc1"
            }
          }
        ]
      }
    ]
  }
```
but with same num of cores & randread, dram could get at least 50GB/s
```
Total                       : 15122719.50 IOPS   59073.12 MiB/s
```

**Comment by rafalste** [comment] 2021-09-01 15:03
Hi @USTCqzy,
I'm investigating this Pass-Through performance and my results are much better than yours. I'm not sure if I messed something up in my setup that is not reflecting yours or maybe you just misconfigured something.
In general the PT cache mode is intended to bypass the cache device but it will never be as fast as direct IO to raw core device as there is additional SPDK block layer on top of it and also OCF reads through metadata (for each request) to find out if corresponding cache line is not mapped into the cache. But nevertheless the PT performance should be better than WT.

Please run a test first with OCF in PT cache mode and then against raw core device with the exact same parameters. Then share your results along with corresponding config files, so I can reproduce it exactly the same in my environment (make sure you start OCF in PT cache mode, as your original config states that cache mode is set to WT).

And regarding the second part of your experiment:
The actual OCF performance is bound by processing power as it takes a lot of calculations to determine how IO should be handled by OCF. There is a lot going on under the hood, so you will never get performance of a raw cache device. In fact, the faster the device, the bigger performance gap between a raw and OCF-handled setup (unless you also radically increase your processing power).
So, keeping in mind that OCF will always be slower than raw cache device and assuming that we only read from this cache device (and not from core device as read hits are almost 100%), it doesn't matter what core device we attach to this setup and how fast it is.

Moreover, OCF caching only makes sense to some extent, until your processing power is enough to handle your device's performance. It is a matter of balance between those two. In case of such fast device like RAM disk, processing power should be ridiculously high to keep up with the disk performance.

**Comment by USTCqzy** [comment] 2021-09-03 03:36
Thx for your ans!!!

"as there is additional SPDK block layer on top of it and also OCF reads through metadata (for each request) to find out if corresponding cache line is not mapped into the cache"
Why do OCF **read** reqs have to access metadata in pt mode? Such reqs will not influence cache arrangement even when some of them are also in cache.

"Please run a test first with OCF in PT cache mode and then against raw core device with the exact same parameters. Then share your results along with corresponding config files"
For example,
ocf cache:
```bash
$ ./test/bdev/bdevperf/bdevperf -q 1 -t 10 -w randread -o 512 -m 0xFFFF -c test101.json -C
```
test101.json
```json
{
    "subsystems": [
      {
        "subsystem": "bdev",
        "config": [
          {
            "method": "bdev_malloc_create",
            "params": {
              "name": "Malloc0",
              "num_blocks": 31457280,
              "block_size": 512,
              "uuid": "a2e6d1bb-1cf5-484a-bd4a-ebbff0043c8b"
            }
          },
          {
            "method": "bdev_nvme_attach_controller",
            "params": {
              "name": "NVMe1",
              "trtype": "PCIe",
              "traddr": "0000:9b:00.0",
              "prchk_reftag": false,
              "prchk_guard": false
            }
          },
          {
            "method": "bdev_ocf_create",
            "params": {
              "name": "Cache1",
              "mode": "pt",
              "cache_line_size": 4,
              "cache_bdev_name": "Malloc0",
              "core_bdev_name": "NVMe1n1"
            }
          }
        ]
      }
    ]
  }
  
```
result:
```bash
[2021-09-03 03:29:42.181821] Starting SPDK v21.10-pre git sha1 1763a126c / DPDK 21.05.0 initialization...
[2021-09-03 03:29:42.181919] [ DPDK EAL parameters: [2021-09-03 03:29:42.181935] bdevperf [2021-09-03 03:29:42.181952] --no-shconf [2021-09-03 03:29:42.181967] -c 0xFFFF [2021-09-03 03:29:42.181982] --log-level=lib.eal:6 [2021-09-03 03:29:42.181996] --log-level=lib.cryptodev:5 [2021-09-03 03:29:42.182011] --log-level=user1:6 [2021-09-03 03:29:42.182025] --iova-mode=pa [2021-09-03 03:29:42.182041] --base-virtaddr=0x200000000000 [2021-09-03 03:29:42.182055] --match-allocations [2021-09-03 03:29:42.182069] --file-prefix=spdk_pid2301079 [2021-09-03 03:29:42.182085] ]
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
[2021-09-03 03:29:42.297979] app.c: 540:spdk_app_start: *NOTICE*: Total cores available: 16
[2021-09-03 03:29:42.573306] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 1
[2021-09-03 03:29:42.587066] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 2
[2021-09-03 03:29:42.587079] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 3
[2021-09-03 03:29:42.587166] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 4
[2021-09-03 03:29:42.587244] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 5
[2021-09-03 03:29:42.587338] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 6
[2021-09-03 03:29:42.587418] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 7
[2021-09-03 03:29:42.587496] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 8
[2021-09-03 03:29:42.587520] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 9
[2021-09-03 03:29:42.587601] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 10
[2021-09-03 03:29:42.587680] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 11
[2021-09-03 03:29:42.587763] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 12
[2021-09-03 03:29:42.588623] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 13
[2021-09-03 03:29:42.588710] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 14
[2021-09-03 03:29:42.588791] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 0
[2021-09-03 03:29:42.588792] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 15
[2021-09-03 03:29:42.589219] accel_engine.c: 988:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2021-09-03 03:29:42.893804] 'OCF Core' volume operations registered
[2021-09-03 03:29:42.896866] 'SPDK block device' volume operations registered
[2021-09-03 03:29:59.202788] json_config.c: 154:rpc_client_check_timeout: *WARNING*: RPC client command timeout.
[2021-09-03 03:29:59.328062] nvme_ctrlr.c:2742:nvme_ctrlr_construct_namespaces: *NOTICE*: nn 1, mem size 8256
[2021-09-03 03:29:59.363147] Inserting cache Cache1
[2021-09-03 03:29:59.363864] Cache1: Metadata initialized
[2021-09-03 03:29:59.363956] Cache1: Successfully added
[2021-09-03 03:29:59.363960] Cache1: Cache mode : pt
[2021-09-03 03:29:59.550165] Cache1: Super block config offset : 0 kiB
[2021-09-03 03:29:59.550184] Cache1: Super block config size : 2196 B
[2021-09-03 03:29:59.550186] Cache1: Super block runtime offset : 128 kiB
[2021-09-03 03:29:59.550188] Cache1: Super block runtime size : 4 B
[2021-09-03 03:29:59.550191] Cache1: Reserved offset : 256 kiB
[2021-09-03 03:29:59.550193] Cache1: Reserved size : 128 kiB
[2021-09-03 03:29:59.550195] Cache1: Part config offset : 384 kiB
[2021-09-03 03:29:59.550197] Cache1: Part config size : 48 kiB
[2021-09-03 03:29:59.550200] Cache1: Part runtime offset : 512 kiB
[2021-09-03 03:29:59.550202] Cache1: Part runtime size : 28 kiB
[2021-09-03 03:29:59.550204] Cache1: Core config offset : 640 kiB
[2021-09-03 03:29:59.550222] Cache1: Core config size : 484 kiB
[2021-09-03 03:29:59.550224] Cache1: Core runtime offset : 1152 kiB
[2021-09-03 03:29:59.550226] Cache1: Core runtime size : 1172 kiB
[2021-09-03 03:29:59.550228] Cache1: Core UUID offset : 2432 kiB
[2021-09-03 03:29:59.550230] Cache1: Core UUID size : 16384 kiB
[2021-09-03 03:29:59.550232] Cache1: Cleaning offset : 18816 kiB
[2021-09-03 03:29:59.550234] Cache1: Cleaning size : 45516 kiB
[2021-09-03 03:29:59.550236] Cache1: Eviction offset : 64384 kiB
[2021-09-03 03:29:59.550238] Cache1: Eviction size : 30312 kiB
[2021-09-03 03:29:59.550243] Cache1: Collision offset : 94720 kiB
[2021-09-03 03:29:59.550245] Cache1: Collision size : 45516 kiB
[2021-09-03 03:29:59.550247] Cache1: List info offset : 140288 kiB
[2021-09-03 03:29:59.550249] Cache1: List info size : 64668 kiB
[2021-09-03 03:29:59.550251] Cache1: Hash offset : 205056 kiB
[2021-09-03 03:29:59.550253] Cache1: Hash size : 3792 kiB
[2021-09-03 03:29:59.550255] Cache1: Cache line size: 4 kiB
[2021-09-03 03:29:59.550259] Cache1: Metadata capacity: 218 MiB
[2021-09-03 03:29:59.668498] Cache1: OCF metadata self-test PASSED
[2021-09-03 03:29:59.711526] Cache1: Policy 'always' initialized successfully
[2021-09-03 03:30:01.688795] Cache1: Done saving cache state!
[2021-09-03 03:30:01.698205] Cache1: Cache attached
[2021-09-03 03:30:01.698303] Cache1: Successfully attached
[2021-09-03 03:30:01.698503] Cache1: Inserting core NVMe1n1
[2021-09-03 03:30:01.698511] Cache1.NVMe1n1: Seqential cutoff init
[2021-09-03 03:30:01.723538] Cache1.NVMe1n1: Successfully added
Running I/O for 10 seconds...
job->size_in_ios: 195351723
 Job: Cache1 (Core Mask 0x1)
         Cache1              :   23678.40 IOPS      11.56 MiB/s
job->size_in_ios: 195351723
 Job: Cache1 (Core Mask 0x2)
         Cache1              :   24521.60 IOPS      11.97 MiB/s
job->size_in_ios: 195351723
 Job: Cache1 (Core Mask 0x4)
         Cache1              :   25292.80 IOPS      12.35 MiB/s
job->size_in_ios: 195351723
 Job: Cache1 (Core Mask 0x8)
         Cache1              :   25181.30 IOPS      12.30 MiB/s
job->size_in_ios: 195351723
 Job: Cache1 (Core Mask 0x10)
         Cache1              :   24960.60 IOPS      12.19 MiB/s
job->size_in_ios: 195351723
 Job: Cache1 (Core Mask 0x20)
         Cache1              :   24303.40 IOPS      11.87 MiB/s
job->size_in_ios: 195351723
 Job: Cache1 (Core Mask 0x40)
         Cache1              :   25337.80 IOPS      12.37 MiB/s
job->size_in_ios: 195351723
 Job: Cache1 (Core Mask 0x80)
         Cache1              :   25306.80 IOPS      12.36 MiB/s
job->size_in_ios: 195351723
 Job: Cache1 (Core Mask 0x100)
         Cache1              :   24734.10 IOPS      12.08 MiB/s
job->size_in_ios: 195351723
 Job: Cache1 (Core Mask 0x200)
         Cache1              :   24639.10 IOPS      12.03 MiB/s
job->size_in_ios: 195351723
 Job: Cache1 (Core Mask 0x400)
         Cache1              :   25298.50 IOPS      12.35 MiB/s
job->size_in_ios: 195351723
 Job: Cache1 (Core Mask 0x800)
         Cache1              :   25204.60 IOPS      12.31 MiB/s
job->size_in_ios: 195351723
 Job: Cache1 (Core Mask 0x1000)
         Cache1              :   24944.00 IOPS      12.18 MiB/s
job->size_in_ios: 195351723
 Job: Cache1 (Core Mask 0x2000)
         Cache1              :   24495.50 IOPS      11.96 MiB/s
job->size_in_ios: 195351723
 Job: Cache1 (Core Mask 0x4000)
         Cache1              :   25543.80 IOPS      12.47 MiB/s
job->size_in_ios: 195351723
 Job: Cache1 (Core Mask 0x8000)
         Cache1              :   25018.60 IOPS      12.22 MiB/s
 =============================================================
 Total                       :  398460.90 IOPS     194.56 MiB/s
[2021-09-03 03:30:11.815575] Cache1: Flushing cache
[2021-09-03 03:30:11.815596] Cache1: Flushing cache completed
[2021-09-03 03:30:11.815674] Cache1: Stopping cache
[2021-09-03 03:30:12.900599] Cache1: Done saving cache state!
[2021-09-03 03:30:13.026925] Cache Cache1 successfully stopped
EAL: device event monitor already stopped
```
nvme ssd:
```bash
$ ./test/bdev/bdevperf/bdevperf -q 1 -t 10 -w randread -o 512 -m 0xFFFF -c test001.json -C
```
test001.json
```json
{
    "subsystems": [
      {
        "subsystem": "bdev",
        "config": [
          {
            "method": "bdev_nvme_attach_controller",
            "params": {
              "name": "NVMe1",
              "trtype": "PCIe",
              "traddr": "0000:9b:00.0",
              "prchk_reftag": false,
              "prchk_guard": false
            }
          }
        ]
      }
    ]
  }
  
```
result:
```bash
[2021-09-03 03:30:48.456088] Starting SPDK v21.10-pre git sha1 1763a126c / DPDK 21.05.0 initialization...
[2021-09-03 03:30:48.456181] [ DPDK EAL parameters: [2021-09-03 03:30:48.456198] bdevperf [2021-09-03 03:30:48.456214] --no-shconf [2021-09-03 03:30:48.456230] -c 0xFFFF [2021-09-03 03:30:48.456246] --log-level=lib.eal:6 [2021-09-03 03:30:48.456260] --log-level=lib.cryptodev:5 [2021-09-03 03:30:48.456276] --log-level=user1:6 [2021-09-03 03:30:48.456291] --iova-mode=pa [2021-09-03 03:30:48.456306] --base-virtaddr=0x200000000000 [2021-09-03 03:30:48.456322] --match-allocations [2021-09-03 03:30:48.456338] --file-prefix=spdk_pid2301270 [2021-09-03 03:30:48.456353] ]
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
[2021-09-03 03:30:48.564617] app.c: 540:spdk_app_start: *NOTICE*: Total cores available: 16
[2021-09-03 03:30:48.865104] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 1
[2021-09-03 03:30:48.879064] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 2
[2021-09-03 03:30:48.879078] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 3
[2021-09-03 03:30:48.879126] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 4
[2021-09-03 03:30:48.879205] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 5
[2021-09-03 03:30:48.879283] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 6
[2021-09-03 03:30:48.879442] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 8
[2021-09-03 03:30:48.879362] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 7
[2021-09-03 03:30:48.879522] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 9
[2021-09-03 03:30:48.879614] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 10
[2021-09-03 03:30:48.879713] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 11
[2021-09-03 03:30:48.879791] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 12
[2021-09-03 03:30:48.879867] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 13
[2021-09-03 03:30:48.879947] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 14
[2021-09-03 03:30:48.880034] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 0
[2021-09-03 03:30:48.880034] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 15
[2021-09-03 03:30:48.880644] accel_engine.c: 988:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2021-09-03 03:30:49.177614] 'OCF Core' volume operations registered
[2021-09-03 03:30:49.180652] 'SPDK block device' volume operations registered
[2021-09-03 03:30:49.305218] nvme_ctrlr.c:2742:nvme_ctrlr_construct_namespaces: *NOTICE*: nn 1, mem size 8256
Running I/O for 10 seconds...
job->size_in_ios: 195351723
 Job: NVMe1n1 (Core Mask 0x1)
         NVMe1n1             :  119910.70 IOPS      58.55 MiB/s
job->size_in_ios: 195351723
 Job: NVMe1n1 (Core Mask 0x2)
         NVMe1n1             :  120066.70 IOPS      58.63 MiB/s
job->size_in_ios: 195351723
 Job: NVMe1n1 (Core Mask 0x4)
         NVMe1n1             :  121257.20 IOPS      59.21 MiB/s
job->size_in_ios: 195351723
 Job: NVMe1n1 (Core Mask 0x8)
         NVMe1n1             :  120276.70 IOPS      58.73 MiB/s
job->size_in_ios: 195351723
 Job: NVMe1n1 (Core Mask 0x10)
         NVMe1n1             :  240677.00 IOPS     117.52 MiB/s
job->size_in_ios: 195351723
 Job: NVMe1n1 (Core Mask 0x20)
         NVMe1n1             :  241098.80 IOPS     117.72 MiB/s
job->size_in_ios: 195351723
 Job: NVMe1n1 (Core Mask 0x40)
         NVMe1n1             :  244232.80 IOPS     119.25 MiB/s
job->size_in_ios: 195351723
 Job: NVMe1n1 (Core Mask 0x80)
         NVMe1n1             :  241197.20 IOPS     117.77 MiB/s
job->size_in_ios: 195351723
 Job: NVMe1n1 (Core Mask 0x100)
         NVMe1n1             :  240824.00 IOPS     117.59 MiB/s
job->size_in_ios: 195351723
 Job: NVMe1n1 (Core Mask 0x200)
         NVMe1n1             :  241200.80 IOPS     117.77 MiB/s
job->size_in_ios: 195351723
 Job: NVMe1n1 (Core Mask 0x400)
         NVMe1n1             :  244554.80 IOPS     119.41 MiB/s
job->size_in_ios: 195351723
 Job: NVMe1n1 (Core Mask 0x800)
         NVMe1n1             :  241355.20 IOPS     117.85 MiB/s
job->size_in_ios: 195351723
 Job: NVMe1n1 (Core Mask 0x1000)
         NVMe1n1             :  240729.30 IOPS     117.54 MiB/s
job->size_in_ios: 195351723
 Job: NVMe1n1 (Core Mask 0x2000)
         NVMe1n1             :  241123.00 IOPS     117.74 MiB/s
job->size_in_ios: 195351723
 Job: NVMe1n1 (Core Mask 0x4000)
         NVMe1n1             :  244328.30 IOPS     119.30 MiB/s
job->size_in_ios: 195351723
 Job: NVMe1n1 (Core Mask 0x8000)
         NVMe1n1             :  241284.50 IOPS     117.81 MiB/s
 =============================================================
 Total                       : 3384117.00 IOPS    1652.40 MiB/s
EAL: device event monitor already stopped
```

**Comment by USTCqzy** [comment] 2021-09-03 08:02
@rafalste 
"Moreover, OCF caching only makes sense to some extent, until your processing power is enough to handle your device's performance. It is a matter of balance between those two. In case of such fast device like RAM disk, processing power should be ridiculously high to keep up with the disk performance."

Maybe there is no such problem here, considering of cpu usage.
![image](https://user-images.githubusercontent.com/49378451/131971613-fa6094b2-19dd-4bb9-a16b-03cb475c55fc.png)
```bash
$ ./test/bdev/bdevperf/bdevperf -q 1 -t 10 -w randread -o 512 -m 0xFFFF -c test101.json -C
```
test101.json
```json
{
    "subsystems": [
      {
        "subsystem": "bdev",
        "config": [
          {
            "method": "bdev_malloc_create",
            "params": {
              "name": "Malloc0",
              "num_blocks": 31457280,
              "block_size": 512,
              "uuid": "a2e6d1bb-1cf5-484a-bd4a-ebbff0043c8b"
            }
          },
          {
            "method": "bdev_nvme_attach_controller",
            "params": {
              "name": "NVMe1",
              "trtype": "PCIe",
              "traddr": "0000:9b:00.0",
              "prchk_reftag": false,
              "prchk_guard": false
            }
          },
          {
            "method": "bdev_ocf_create",
            "params": {
              "name": "Cache1",
              "mode": "pt",
              "cache_line_size": 4,
              "cache_bdev_name": "Malloc0",
              "core_bdev_name": "NVMe1n1"
            }
          }
        ]
      }
    ]
  }
  
```

**Comment by rafalste** [comment] 2021-09-23 12:59
Hi @USTCqzy,
I just wanted to let you know, that I'm investigating the issue and will get back to you soon with some updates.

**Comment by rafalste** [comment] 2021-10-06 10:22
Hi @USTCqzy,
it turns out that the problem was related to sequential cutoff and its unoptimized implementation in OCF 20.12. This is already improved in OCF 21.6 but to resolve this issue it also needed a slight modification in OCF adapter in SPDK.
Moreover, OCF 21.6 is not yet available in upstream SPDK, so I will let you know when all of those changes will be merged in SPDK.
Let me know if this problem is crucial for your setup, so I could prepare a patch for you to test those improvements before they will be officially available in upstream SPDK.

**Comment by USTCqzy** [comment] 2021-10-06 12:46
@rafalste Thanks for your explanation!
Actually, this problem is crucial for my research. I am occupied by other things these days, so I plan to test more next week. If your optimizations cannot be officially available in a few days, I would be eager to get a patch in advance.
Btw, OCF is really crucial for my experiments. Thanks for your persistent development!!!

**Comment by rafalste** [comment] 2021-10-07 13:13
@USTCqzy here you have two patches that might resolve your issue:
https://review.spdk.io/gerrit/c/spdk/spdk/+/9129
https://review.spdk.io/gerrit/c/spdk/spdk/+/9786

The first one is OCF update, so you could take advantage of our (almost) latest improvements and the second one modifies the adapter a bit to set proper values for new parameters.
Please share your results after you take it for a test run.

Also you could test this new setup against your other issue:
https://github.com/spdk/spdk/issues/2134
I'm not sure, but this newer OCF might behave better in this scenario.

**Comment by tomzawadzki** [comment] 2021-11-30 10:41
Patches updating OCF to 21.6 have been merged, which should include resolution to issue.
@USTCqzy Please feel free to re-open the issue if you observe the original issue.

**Closed by tomzawadzki** 2021-11-30 10:41 UTC
Labels: Waiting on Submitter, Sighting
