### ISSUE TITLE
Failed to create FTL dev with spdk24.09

### ISSUE THREAD

**Issue by wangdbang** [spdk/spdk#3579] opened 2024-11-26 00:53 UTC
core dumped when i created the FTL dev with spdk24.09, logs as follow.
[2024-11-26 16:30:12.559854] ftl_layout.c: 130:dump_region: *NOTICE*: [FTL][ftl0] Region p2l_log_io1
[2024-11-26 16:30:12.559870] ftl_layout.c: 132:dump_region: *NOTICE*: [FTL][ftl0]       offset:                      8735.25 MiB
[2024-11-26 16:30:12.559888] ftl_layout.c: 134:dump_region: *NOTICE*: [FTL][ftl0]       blocks:                      1024.12 MiB
[2024-11-26 16:30:12.559910] ftl_layout.c: 130:dump_region: *NOTICE*: [FTL][ftl0] Region p2l_log_io2
[2024-11-26 16:30:12.559928] ftl_layout.c: 132:dump_region: *NOTICE*: [FTL][ftl0]       offset:                      9759.38 MiB
[2024-11-26 16:30:12.559945] ftl_layout.c: 134:dump_region: *NOTICE*: [FTL][ftl0]       blocks:                      1024.12 MiB
[2024-11-26 16:30:12.559964] ftl_layout.c: 775:ftl_layout_dump: *NOTICE*: [FTL][ftl0] Base device layout:
[2024-11-26 16:30:12.559981] ftl_layout.c: 130:dump_region: *NOTICE*: [FTL][ftl0] Region sb_mirror
[2024-11-26 16:30:12.560000] ftl_layout.c: 132:dump_region: *NOTICE*: [FTL][ftl0]       offset:                      0.00 MiB
[2024-11-26 16:30:12.560020] ftl_layout.c: 134:dump_region: *NOTICE*: [FTL][ftl0]       blocks:                      0.38 MiB
nvmf_tgt: ftl_layout.c:127: dump_region: Assertion `!(region->current.offset % superblock_region_blocks(dev))' failed.
Aborted (core dumped)

Steps to Reproduce
1.run the script ./scripts/setup.sh
2.run the app ./build/bin/nvmf_tgt
3.attach the nvmes devices
4../scripts/rpc.py bdev_raid_create -n raid1 -z 0 -r 1 -b "nvme0n1 nvme1n1"
5../scripts/rpc.py bdev_split_create raid1 -s 40960 1
6../scripts/rpc.py bdev_raid_create -n raid5f -z 128 -r 5f -b "nvme3n1 nvme4n1 nvme5n1 nvme6n1"
7../scripts/rpc.py bdev_ftl_create -b ftl0 -d raid5f -c raid1p0

**Comment by wangdbang** [comment] 2024-11-26 02:35
I changed the step 7, 
7../scripts/rpc.py bdev_split_create raid5f -s 10485760 1
8../scripts/rpc.py bdev_ftl_create -b ftl1 -d raid5fp0 -c raid1p0
and export the ftl1 dev to host with nvmf_tgt, run io with 4k rand-write, core dumped again.
here is the log.
[2024-11-26 18:06:39.115764] rdma.c:2588:create_ib_device: *NOTICE*: Create IB device mlx5_0(0x27a8d40/0x2bd0210) succeed.
[2024-11-26 18:06:39.153648] rdma.c:2588:create_ib_device: *NOTICE*: Create IB device mlx5_1(0x2bc0930/0x2c118a0) succeed.
[2024-11-26 18:06:54.595623] mngt/ftl_mngt_ioch.c:  58:io_channel_create_cb: *NOTICE*: [FTL][ftl1] FTL IO channel created on nvmf_tgt_poll_group_000
[2024-11-26 18:06:54.598508] mngt/ftl_mngt_ioch.c:  58:io_channel_create_cb: *NOTICE*: [FTL][ftl1] FTL IO channel created on nvmf_tgt_poll_group_001
[2024-11-26 18:06:54.601304] mngt/ftl_mngt_ioch.c:  58:io_channel_create_cb: *NOTICE*: [FTL][ftl1] FTL IO channel created on nvmf_tgt_poll_group_002
[2024-11-26 18:06:54.604065] mngt/ftl_mngt_ioch.c:  58:io_channel_create_cb: *NOTICE*: [FTL][ftl1] FTL IO channel created on nvmf_tgt_poll_group_003
[2024-11-26 18:06:54.606921] mngt/ftl_mngt_ioch.c:  58:io_channel_create_cb: *NOTICE*: [FTL][ftl1] FTL IO channel created on nvmf_tgt_poll_group_004
[2024-11-26 18:06:54.609713] mngt/ftl_mngt_ioch.c:  58:io_channel_create_cb: *NOTICE*: [FTL][ftl1] FTL IO channel created on nvmf_tgt_poll_group_005
[2024-11-26 18:06:54.612583] mngt/ftl_mngt_ioch.c:  58:io_channel_create_cb: *NOTICE*: [FTL][ftl1] FTL IO channel created on nvmf_tgt_poll_group_006
[2024-11-26 18:06:54.615385] mngt/ftl_mngt_ioch.c:  58:io_channel_create_cb: *NOTICE*: [FTL][ftl1] FTL IO channel created on nvmf_tgt_poll_group_007
[2024-11-26 18:07:00.775843] rdma.c:3043:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 192.10.1.140 port 4420 ***
[2024-11-26 18:08:46.827382] bdev.c:2816:bdev_io_do_submit: *ERROR*: IO num_blocks 32 does not match the write_unit_size 96
[2024-11-26 18:08:46.827647] bdev.c:2816:bdev_io_do_submit: *ERROR*: IO num_blocks 32 does not match the write_unit_size 96
[2024-11-26 18:08:46.828152] bdev.c:2816:bdev_io_do_submit: *ERROR*: IO num_blocks 64 does not match the write_unit_size 96
[2024-11-26 18:08:46.828748] bdev.c:2816:bdev_io_do_submit: *ERROR*: IO num_blocks 64 does not match the write_unit_size 96
nvmf_tgt: ftl_band_ops.c:35: write_rq_end: Assertion `false' failed.
Aborted (core dumped)

**Comment by mmkayPL** [comment] 2024-11-26 08:11
FTL currently has a write unit size requirement - it needs to be a power of 2, so for a raid5f the number of drives within would need to be (power_of_2 + 1, e.g. 3, 5, 9, etc).

**Comment by jimharris** [comment] 2024-11-26 15:03
> FTL currently has a write unit size requirement - it needs to be a power of 2, so for a raid5f the number of drives within would need to be (power_of_2 + 1, e.g. 3, 5, 9, etc).

Thanks @mmkayPL.

So it seems this is not a bug in FTL, but @mmkayPL said during bug scrub that this error could be detected earlier and provide a more clear explanation. So assigning to him for further work on this. Will keep this open for now.

**Comment by wangdbang** [comment] 2024-11-27 08:29
Thanks @mmkayPL.
I changed the raid5f configuration as follow, used 9 drivers, but issue still exist.
./scripts/rpc.py bdev_raid_create -n raid5f -z 128 -r 5f -b "nvme3n1 nvme4n1 nvme5n1 nvme6n1 nvme7n1 nvme8n1 nvme9n1 nvme10n1 nvme11n1"

When i run io with 4k random write , core dump occurred, log append
[2024-11-28 00:08:23.204323] bdev.c:2816:bdev_io_do_submit: *ERROR*: IO num_blocks 192 does not match the write_unit_size 256
[2024-11-28 00:08:23.204466] bdev.c:2816:bdev_io_do_submit: *ERROR*: IO num_blocks 64 does not match the write_unit_size 256
nvmf_tgt: ftl_band_ops.c:35: write_rq_end: Assertion `false' failed.
Aborted (core dumped)

**Comment by mmkayPL** [comment] 2024-11-27 09:46
I've added the early checks that should catch the invalid configuration early (https://review.spdk.io/gerrit/c/spdk/spdk/+/25476). Can you post your json and fio (if that's what you're using to generate the workload) configuration? I've checked a similar config to yours (I didn't have a machine with 10 drives, so I split one into multiple 100GiB partitions) on vhost and 4k workloads seem to be working fine, both short term and when the garbage collection is running:

Raid5/FTL part of the config:
>         {
>           "method": "bdev_raid_create",
>           "params": {
>             "name": "BaseRaid0",
>             "uuid": "e4fba8f2-d048-4469-9316-f234ae4941c1",
>             "strip_size_kb": 128,
>             "raid_level": "raid5f",
>             "base_bdevs": [
>               "Base0n1p0",
>               "Base0n1p1",
>                "Base0n1p2",
>                 "Base0n1p4",
>                  "Base0n1p5",
>                   "Base0n1p6",
>                    "Base0n1p7",
>                     "Base0n1p8",
>               "Base0n1p3"
>             ]
>           }
>         },
>         {
>           "method": "bdev_ftl_create",
>           "params": {
>             "name": "Ftl0",
>             "overprovisioning": 20,
>             "l2p_dram_limit": 2048,
>             "fast_shutdown": false,
>             "base_bdev": "BaseRaid0",
>             "cache": "Cache0n1p0"
>           }
>         },

fio:
> [global]
> ioengine=libaio
> iodepth=128
> direct=1
> readwrite=randwrite
> blocksize=4096
> size=53687091200
> numjobs=1
> serialize_overlap=1
> verify=md5
> verify_dump=1
> do_verify=0
> group_reporting
> norandommap
> group_reporting
> [job_1]
> filename=/dev/vda

**Closed** 2024-12-04 20:14 UTC
Labels: Sighting, Patches out for review

**Comment by wangdbang** [comment] 2024-12-05 02:46
I think the configuration could make sure through the command, and i could run it now, thanks.
