### ISSUE TITLE
Fail to use function in spdk/module/bdev/ocf

### ISSUE THREAD

**Issue by USTCqzy** [spdk/spdk#2109] opened 2021-08-19 12:37 UTC
# Bug report

Fail to use function in spdk/module/bdev/ocf/

## Expected Behavior

vbdev-relevant APIs (e.g. spdk/module/bdev/ocf/vbdev_ocf_rpc.c/rpc_bdev_ocf_get_stats) can be used.
**PS: My goal is to get stats in hello_bdev, like `bdev_ocf_get_stats` in scripts/rpc.py**

## Current Behavior

Added -L and link .a, still failed.

## Possible Solution

No idea.

## Steps to Reproduce

1. add #include "ocf/vbdev_ocf.h" in spdk/examples/bdev/hello_world/hello_bdev.c
2. add **-I$(PWD)/module/bdev/** -L$(PWD)/build/lib/ **-l:libspdk_bdev_ocf.a** in CFLAGS in spdk/examples/bdev/hello_world/Makefile
PS: libspdk_bdev_ocf.a contain .o that we need
3. spdk$ make

```bash
  LINK hello_bdev
/usr/bin/ld.bfd: hello_bdev.o: in function `perform_workload':
xxx/hello_bdev.c:135: undefined reference to `vbdev_ocf_get_by_name'
/usr/bin/ld.bfd: xxx/hello_bdev.c:136: undefined reference to `rpc_bdev_ocf_get_stats_cmpl'
/usr/bin/ld.bfd: xxx/hello_bdev.c:144: undefined reference to `vbdev_ocf_stats_get'
collect2: error: ld returned 1 exit status
```

but such functions is in vbdev_ocf_rpc.c whose .o has been linked by -l:libspdk_bdev_ocf.a

## Context (Environment including OS version, SPDK version, etc.)

SPDK 21.07.x
Ubuntu 20.04.2

**Comment by Comphix** [comment] 2021-08-19 12:40
OCF related. Assign to Wayne to do first triage.

**Comment by jimharris** [comment] 2021-08-19 14:32
Hi,

Closing this since this is more of a question, not an SPDK issue.  hello_bdev is not meant to support get_stats operations like this.  You can use one of the SPDK target applications to get stats though.

Someone here might be able to provide some help, but we will need you to post a complete patch that applies cleanly to SPDK master branch.  The reproduction steps listed above are unfortunately not enough to efficiently provide any kind of feedback.

Thanks,

Jim

**Comment by jimharris** [comment] 2021-08-19 14:32
@gwnet - there's nothing for you to investigate on this so I've unassigned you.  I've assigned it back to @USTCqzy while we wait for more detailed reproduction steps.

**Closed by jimharris** 2021-08-19 14:32 UTC
Labels: Sighting

**Comment by USTCqzy** [comment] 2021-08-19 16:46
@jimharris 
I produce a patch that can apply to v21.07 (for I am using v21.07 now). Sorry for failing to provide the exact clean codes. Btw, as I am kind of new here, I am not sure the right method to post the patch, so just attached it in zip form now. Sorry again.

[patch.diff.zip](https://github.com/spdk/spdk/files/7016281/patch.diff.zip)

**Comment by jimharris** [comment] 2021-08-19 17:41
Posting the hacked up patch like this is fine in this case.

Two problems I see:

1) Library info is added to CFLAGS which is for compilation.  You need to add it to LDFLAGS instead.
2) Patch adds call to rpc_bdev_ocf_get_stats_cmpl which is private/static.

**Comment by USTCqzy** [comment] 2021-08-21 05:16
@jimharris 
Thanks for your answer.
I add Library info to LDFLAGS and annotate `rpc_bdev_ocf_get_stats_cmpl` stuff for now.
```bash
LDFLAGS += -L$(PWD)/build/lib/ -l:libspdk_bdev_ocf.a
```
My reference to `vbdev_ocf_get_by_name` still failed. I still worry that some problems prevent us from calling vbdev-relevant functions.

```bash
/usr/bin/ld.bfd: hello_bdev.o: in function `perform_workload':
xxx/hello_bdev.c:135: undefined reference to `vbdev_ocf_get_by_name'
```
[patch.zip](https://github.com/spdk/spdk/files/7024904/patch.zip)

**Comment by Comphix** [comment] 2021-08-21 12:55
Hi @USTCqzy , could you follow below SPDK development guide to supply a patch for better discussion?

https://spdk.io/development/

Thanks, Gang.

**Comment by USTCqzy** [comment] 2021-08-23 13:00
@Comphix Thanks for your answer!
Actually, when I changed to master and tried to reproduce the bug (to submit patch), everything went smooth. (I have tried many times in v21.07.x, but not worked.) I still failed to figure out the reason.
However, problem vanished. Thanks again!!!
