### ISSUE TITLE
env_dpdk: support 4k granularity memory mapping in the SPDK userspace "page table"

### ISSUE THREAD

**Issue by nickyc975** [spdk/spdk#3570] opened 2024-11-06 13:19 UTC
# Sighting report

Currently, SPDK's userspace "page table" maps memory in a fixed granularity of 2 MiB. This granularity leads to known problems in two cases, as disscussed in #2973 :

1. When working with CMBs of NVMe SSDs, part of CMB could be wasted due to alignment requirment. In 2 MiB granularity, the wasted part could be as large as about 4 MiB per SSD in the worst case.
2. RDMA transport relies on the "page table" to mapping buffers to memory regions. Therefore, RDMA transport cannot be used without huge pages, even though RDMA itself does not require huge pages at all.

## Possible Solution

Supporting mapping memory in 4 KiB granularity is a reasonable solution. For the CMB case, CMB addresses should be always 4 KiB aligned according to the NVMe spec. Therefore, we will not waste any CMB space with 4 KiB granularity mapping. For the RDMA case, 4 KiB granularity mapping just fits the normal page size. Thus, we can enable RDMA transport without huge pages.

A straight-forward way to support 4 KiB granularity memory mapping is simply replacing the `{VALUE | MASK | SHIFT}_2MB` macros with corresponding variables, then provides startup arguments for specifying these variables, like `--mem-map-page-size <4k | 2m>`.

## Possible Drawbacks

Smaller mapping granularity consumes more space for the "page table". 2 MiB mapping consumes 4 KiB memory for 1 page table of 1 GiB memory, while 4 KiB mapping consumes 2 MiB memory in the same case.

Smaller mapping granularity also means more iterations to fill and query the page table, which might slow down the address translation.

I can submit a patch for the solution. But before that, discussions about the solution is welcomed.

**Comment by ksztyber** [comment] 2024-11-12 15:16
[Bug scrub] It seems that the cons of this proposal (i.e. larger memory consumption, possible performance degradation in "regular" case, incompatibility between RDMA and CMD) would outweigh the advantages.

**Comment by nickyc975** [comment] 2024-11-12 16:45
Hi, @ksztyber,

What is "incompatibility between RDMA and CMD"? Did I miss something?

Besides, I think adding a switch between 2 MiB mapping and 4 KiB mapping could be a good choice.

By default in 2 MiB mapping mode, everything works just as it is now. There will not be performance degradation or resource consumption addition.

If user chooses to use 4 KiB mapping mode, then there should be a reason and it's their duty to consider the disadvantages.

Thanks,
Jinlong

**Comment by ksztyber** [comment] 2024-11-13 13:00
> What is "incompatibility between RDMA and CMD"? Did I miss something?

@jimharris correct me if I'm wrong, but I think the issue is that you cannot use CMB for RDMA read/write operations.

**Comment by nickyc975** [comment] 2024-11-21 01:59
> > What is "incompatibility between RDMA and CMD"? Did I miss something?
> 
> @jimharris correct me if I'm wrong, but I think the issue is that you cannot use CMB for RDMA read/write operations.

There might be some missunderstanding. The proposal doesn't mean to use CMB for RDMA read/write operations. The CMB case and the RDMA case are two irrelevant cases, execept that both of them can benifit from 4-KiB memory mapping.

**Comment by jimharris** [comment] 2024-11-26 15:18
[Bug scrub] There is considerable work required to support 4KB mappings in the userspage Page Tables. Closing this issue, since the enhancement is already covered by issue #2526.

**Closed by jimharris** 2024-11-26 15:18 UTC
Labels: Sighting
