### ISSUE TITLE
[auto_test_per_patch] failed for an unrelated reason.

### ISSUE THREAD

**Issue by YafeiWangAlice** [spdk/spdk#2581] opened 2022-07-11 06:28 UTC
This patch is trying to fix a spdk_top bug. spdk_top can't collect the right poller count when thread count is more than core count. Max index of g_threads_info[] should be thread count NOT cores count.

## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/80094/archive/post_process/build.log

##patch link
https://review.spdk.io/gerrit/c/spdk/spdk/+/13574

## Execution failed at
...
...
00:17:30.304  vmd_identify
00:17:30.304  vmd_perf
00:17:30.304  zoned_fio
00:17:30.304  Not all tests were run. Failing the build.
00:17:30.304  ['accel_engine', 'alias_rpc', 'app_repeat', 'autobuild', 'autobuild_build_doc', 'autobuild_check_format', 'autobuild_check_so_deps', 'autobuild_external_code', 'autobuild_generated_files_check', 'autobuild_header_dependency_check', 'autobuild_make_install', 'autobuild_make_uninstall', 'bdev_bounds', 'bdev_fio', 'bdev_fio_rw_verify', 'bdev_fio_trim', 'bdev_hello_world', 'bdev_nbd', 'bdev_qd_sampling', 'bdev_qos', 'bdev_qos_bw', 'bdev_qos_iops', 'bdev_qos_ro_bw', 'bdev_raid', 'bdev_verify', 'bdev_write_zeroes', 'bdevperf_config', 'blob_io_wait', 'blobfs', 'blobfs_mkfs', 'blobstore', 'blobstore_grow', 'blockdev_crypto_aesni', 'blockdev_crypto_qat', 'blockdev_general', 'blockdev_nvme', 'blockdev_nvme_gpt', 'blockdev_pmem', 'blockdev_rbd', 'cmb_copy', 'compress_isal', 'compress_qat', 'confirm_abi_deps', 'confirm_makefile_deps', 'dd_bs_lt_native_bs', 'dd_copy_to_out_bdev', 'dd_flag_append', 'dd_flag_append_forced_aio', 'dd_flag_directory', 'dd_flag_directory_forced_aio', 'dd_flag_noatime', 'dd_flag_noatime_forced_aio', 'dd_flag_nofollow', 'dd_flag_nofollow_forced_aio', 'dd_flags_misc', 'dd_flags_misc_forced_aio', 'dd_inflate_file', 'dd_malloc_copy', 'dd_offset_magic', 'dd_rw', 'dd_rw_offset', 'dd_uring_copy', 'dma', 'dpdk_governor', 'dpdk_mem_utility', 'event', 'event_perf', 'event_reactor', 'event_reactor_perf', 'event_scheduler', 'external_make_hello_bdev_shared_combo', 'external_make_hello_bdev_shared_iso', 'external_make_hello_bdev_static', 'external_make_hello_no_bdev_shared_combo', 'external_make_hello_no_bdev_shared_iso', 'external_make_hello_no_bdev_static', 'external_make_nvme_shared', 'external_make_nvme_static', 'external_run_hello_bdev_shared_combo', 'external_run_hello_bdev_shared_iso', 'external_run_hello_bdev_static', 'external_run_hello_no_bdev_shared_combo', 'external_run_hello_no_bdev_shared_iso', 'external_run_hello_no_bdev_static', 'external_run_nvme_shared', 'external_run_nvme_static', 'filesystem_btrfs', 'filesystem_ext4', 'filesystem_in_capsule_btrfs', 'filesystem_in_capsule_ext4', 'filesystem_in_capsule_xfs', 'filesystem_xfs', 'fio_dif_1_default', 'fio_dif_1_multi_subsystems', 'fio_dif_digest', 'fio_dif_rand_params', 'ftl', 'hello_blob', 'idle', 'interrupt_mode', 'ioat', 'ioat_perf', 'ioat_verify', 'is_zoned', 'iscsi_tgt', 'iscsi_tgt_bdev_io_wait', 'iscsi_tgt_calsoft', 'iscsi_tgt_filesystem', 'iscsi_tgt_filesystem_btrfs', 'iscsi_tgt_filesystem_ext4', 'iscsi_tgt_filesystem_xfs', 'iscsi_tgt_fio', 'iscsi_tgt_initiator', 'iscsi_tgt_ip_migration', 'iscsi_tgt_iscsi_lvol', 'iscsi_tgt_login_redirection', 'iscsi_tgt_qos', 'iscsi_tgt_rbd', 'iscsi_tgt_reset', 'iscsi_tgt_resize', 'iscsi_tgt_rpc_config', 'iscsi_tgt_sock', 'iscsi_tgt_trace_record', 'json_config', 'json_config_extra_key', 'lvol', 'lvol_basic', 'lvol_hotremove', 'lvol_provisioning', 'lvol_rename', 'lvol_resize', 'lvol_snapshot_clone', 'lvol_tasting', 'make', 'nvme', 'nvme_arbitration', 'nvme_cli_cuse', 'nvme_cmb', 'nvme_cuse', 'nvme_cuse_app', 'nvme_cuse_rpc', 'nvme_deallocated_value', 'nvme_e2edp', 'nvme_err_injection', 'nvme_fio', 'nvme_hello_world', 'nvme_identify', 'nvme_multi_secondary', 'nvme_ns_manage_cuse', 'nvme_overhead', 'nvme_perf', 'nvme_pmr', 'nvme_pmr_persistence', 'nvme_reserve', 'nvme_reset', 'nvme_rpc', 'nvme_rpc_timeouts', 'nvme_sgl', 'nvme_smartctl_cuse', 'nvme_startup', 'nvme_zns', 'nvmf_abort', 'nvmf_aer', 'nvmf_async_init', 'nvmf_bdev_io_wait', 'nvmf_bdevio', 'nvmf_bdevperf', 'nvmf_connect_disconnect', 'nvmf_connect_stress', 'nvmf_delete_subsystem', 'nvmf_dif', 'nvmf_discovery', 'nvmf_example', 'nvmf_failover', 'nvmf_filesystem', 'nvmf_filesystem_in_capsule', 'nvmf_filesystem_no_in_capsule', 'nvmf_fio_host', 'nvmf_fio_target', 'nvmf_fused_ordering', 'nvmf_host_management', 'nvmf_identify', 'nvmf_identify_passthru', 'nvmf_invalid', 'nvmf_lvol', 'nvmf_multicontroller', 'nvmf_multipath', 'nvmf_multitarget', 'nvmf_nmic', 'nvmf_ns_hotplug_stress', 'nvmf_nvme_cli', 'nvmf_perf', 'nvmf_perf_adq', 'nvmf_queue_depth', 'nvmf_rdma', 'nvmf_rpc', 'nvmf_shutdown', 'nvmf_shutdown_tc1', 'nvmf_shutdown_tc2', 'nvmf_shutdown_tc3', 'nvmf_target_disconnect', 'nvmf_target_disconnect_tc1', 'nvmf_target_disconnect_tc2', 'nvmf_target_disconnect_tc3', 'nvmf_tcp', 'nvmf_timeout', 'nvmf_tls', 'nvmf_vfio_user', 'nvmf_vfio_user_fuzz', 'nvmf_vfio_user_nvme_compliance', 'nvmf_vhost', 'nvmf_zcopy', 'ocf', 'ocf_bdevperf_iotypes', 'ocf_configuration_change', 'ocf_create_destruct', 'ocf_fio_modes', 'ocf_multicore', 'ocf_persistent_metadata', 'ocf_remove', 'ocf_stats', 'pmem', 'reactor_set_interrupt', 'reap_unregistered_poller', 'rocksdb', 'rocksdb_insert', 'rocksdb_overwrite', 'rocksdb_randread', 'rocksdb_readwrite', 'rocksdb_writesync', 'rpc', 'rpc_client', 'rpc_daemon_integrity', 'rpc_integrity', 'rpc_plugins', 'scheduler_create_thread', 'spdk_dd', 'spdk_dd_basic_rw', 'spdk_dd_bdev_to_bdev', 'spdk_dd_malloc', 'spdk_dd_posix', 'spdk_dd_uring', 'spdkcli_iscsi', 'spdkcli_nvmf_rdma', 'spdkcli_nvmf_tcp', 'spdkcli_pmem', 'spdkcli_raid', 'spdkcli_rbd', 'spdkcli_tcp', 'spdkcli_vhost', 'spdkcli_virtio', 'sw_hotplug', 'test_bdev_lvol_delete_lvstore_with_clones', 'test_bdev_lvol_delete_ordering', 'test_clone_decouple_parent', 'test_clone_inflate', 'test_clone_snapshot_relations', 'test_construct_lvol', 'test_construct_lvol_alias_conflict', 'test_construct_lvol_fio_clear_method_none', 'test_construct_lvol_fio_clear_method_unmap', 'test_construct_lvol_full_lvs', 'test_construct_lvol_inexistent_lvs', 'test_construct_lvols_conflict_alias', 'test_construct_lvs', 'test_construct_lvs_clear_methods', 'test_construct_lvs_conflict_alias', 'test_construct_lvs_different_cluster_size', 'test_construct_lvs_nonexistent_bdev', 'test_construct_multi_lvols', 'test_construct_nested_lvol', 'test_construct_two_lvs_on_the_same_bdev', 'test_create_snapshot_of_snapshot', 'test_create_snapshot_with_io', 'test_delete_lvol_store_persistent_positive', 'test_delete_snapshot_with_clone', 'test_delete_snapshot_with_snapshot', 'test_destroy_after_bdev_lvol_resize_positive', 'test_hotremove_lvol_store', 'test_hotremove_lvol_store_base', 'test_hotremove_lvol_store_base_with_lvols', 'test_hotremove_lvol_store_multiple_lvols', 'test_lvol_bdev_readonly', 'test_lvol_rename_negative', 'test_rename_lvs_negative', 'test_rename_positive', 'test_resize_lvol', 'test_resize_lvol_negative', 'test_resize_lvol_with_io_traffic', 'test_sigterm', 'test_snapshot_compare_with_lvol_bdev', 'test_tasting', 'test_thin_lvol_check_integrity', 'test_thin_lvol_check_space', 'test_thin_lvol_check_zeroes', 'test_thin_lvol_resize', 'test_thin_overprovisioning', 'test_unregister_lvol_bdev', 'thread', 'thread_poller_perf', 'vfio_user_fio', 'vfio_user_qemu', 'vfio_user_restart_vm', 'vhost', 'vhost_blk_lvol_integrity', 'vhost_blk_packed_ring_integrity', 'vhost_blockdev', 'vhost_boot', 'vhost_fuzz', 'vhost_negative', 'vhost_scsi_lvol_integrity', 'vhost_shared']
00:17:30.321  [Pipeline] }
00:17:30.324  ERROR: script returned exit code 1
00:17:30.354  [Pipeline] // catchError
00:17:30.364  [Pipeline] catchError
00:17:30.366  [Pipeline] {
00:17:30.387  [Pipeline] dir
00:17:30.387  Running in /var/jenkins/workspace/autotest-per-patch@2/post_process
00:17:30.389  [Pipeline] {

**Comment by spdkci** [comment] 2022-07-11 06:29
Another instance of this failure. Reported by @YafeiWangAlice. log: https://ci.spdk.io/public_build/autotest-per-patch_80094.html

**Comment by spdkci** [comment] 2022-07-11 06:47
Another instance of this failure. Reported by @YafeiWangAlice. log: https://ci.spdk.io/public_build/autotest-per-patch_80103.html

**Comment by mikeBashStuff** [comment] 2022-07-11 07:04
Both reports here point at check_format issues, e.g.: https://ci.spdk.io/results/autotest-per-patch/builds/80094/archive/autobuild-vg-autotest/build.log

These should be addressed directly in the affected patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/13574

**Comment by spdkci** [comment] 2022-07-11 07:06
Another instance of this failure. Reported by @YafeiWangAlice. log: https://ci.spdk.io/public_build/autotest-per-patch_80104.html

**Comment by changpe1** [comment] 2022-07-11 07:14
@YafeiWangAlice please read the error log in your patch carefully, it already showed this failure was caused by code format. I'm going to close it.

**Closed by changpe1** 2022-07-11 07:14 UTC
Labels: Intermittent Failure

**Comment by spdkci** [comment] 2022-07-11 07:25
Another instance of this failure. Reported by @YafeiWangAlice. log: https://ci.spdk.io/public_build/autotest-per-patch_80107.html

**Comment by spdkci** [comment] 2022-07-11 08:49
Another instance of this failure. Reported by @YafeiWangAlice. log: https://ci.spdk.io/public_build/autotest-per-patch_80118.html

**Comment by spdkci** [comment] 2022-07-11 09:08
Another instance of this failure. Reported by @YafeiWangAlice. log: https://ci.spdk.io/public_build/autotest-per-patch_80120.html

**Comment by spdkci** [comment] 2022-07-11 09:27
Another instance of this failure. Reported by @YafeiWangAlice. log: https://ci.spdk.io/public_build/autotest-per-patch_80123.html

**Comment by spdkci** [comment] 2022-07-11 09:49
Another instance of this failure. Reported by @YafeiWangAlice. log: https://ci.spdk.io/public_build/autotest-per-patch_80126.html

**Comment by spdkci** [comment] 2022-07-19 13:20
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_80717.html
