### ISSUE TITLE
[blobfs_fuse_test] Mountpoint not found

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1572] opened 2020-08-25 13:41 UTC
https://ci.spdk.io/results/autotest-per-patch/builds/24918/archive/BlobFS-autotest/build.log

Seems like `fuse/fuse` didn't mount the filesystem at the expected path (` /tmp/spdk_tmp_mount`) as it was missing from `/proc/mounts`. 

```
00:06:11.459  [2020-08-25 14:32:43.178601] accel_engine.c: 500:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:06:11.913  Mounting filesystem on bdev BlobfsBdev to path /tmp/spdk_tmp_mount...
00:06:11.988   14:32:43	# xtrace_enable
00:06:11.988   14:32:43	# (( i == 0 ))
00:06:11.988   14:32:43	# return 0
00:06:11.988   14:32:43	# mount
00:06:11.988   14:32:43	# grep /tmp/spdk_tmp_mount
00:06:11.990    14:32:43	# trap - ERR
00:06:11.990    14:32:43	# print_backtrace
00:06:11.990    14:32:43	# [[ ehxBET =~ e ]]
00:06:11.990    14:32:43	# args=("${BASH_ARGV[@]}")
00:06:11.991    14:32:43	# local args
00:06:11.991    14:32:43	# xtrace_disable
00:06:11.991    14:32:43	# '[' no '!=' yes ']'
00:06:11.991    14:32:43	# PREV_BASH_OPTS=ehxBET
00:06:11.991    14:32:43	# [[ ehxBET == *\x* ]]
00:06:11.991    14:32:43	# XTRACE_DISABLED=yes
00:06:11.991    14:32:43	# set +x
00:06:11.991  ========== Backtrace start: ==========
00:06:11.991  
00:06:12.228  in ./test/blobfs/blobfs.sh:98 -> blobfs_fuse_test([])
00:06:12.228       ...
00:06:12.228     93  		# Currently blobfs fuse APP doesn't support specific path of RPC sock.
00:06:12.228     94  		# So directly use default sock path.
00:06:12.228     95  		waitforlisten $blobfs_pid /var/tmp/spdk.sock
00:06:12.228     96  	
00:06:12.228     97  		# check mount status
00:06:12.228  => 98  		mount | grep "$mount_dir"
00:06:12.228     99  	
00:06:12.228     100 		# create a rand file in mount dir
00:06:12.228     101 		dd if=/dev/urandom of=${mount_dir}/rand_file bs=4k count=32
00:06:12.228     102 	
00:06:12.228     103 		umount ${mount_dir}
00:06:12.228       ...
00:06:12.231  in ./test/blobfs/blobfs.sh:141 -> main([])
00:06:12.231       ...
00:06:12.231     136 	
00:06:12.231     137 	blobfs_create_test
00:06:12.231     138 	
00:06:12.231     139 	# Create dir for FUSE mount
00:06:12.231     140 	mkdir -p $mount_dir
00:06:12.231  => 141 	blobfs_fuse_test
00:06:12.231       ...
00:06:12.231  
00:06:12.231  ========== Backtrace end ==========
```

**Comment by spdkci** [comment] 2020-08-25 13:41
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_24918.html

**Comment by changpe1** [comment] 2020-09-16 06:29
I can't reproduce this issue in my local environment, but go through the test script, maybe we should add 1 second delay before check the mount point.

**Comment by changpe1** [comment] 2020-09-16 06:42
For this error case, only one notice log as follow:
Mounting filesystem on bdev BlobfsBdev to path /tmp/spdk_tmp_mount...

For normal cases, there are two notice messages:
Mounting filesystem on bdev BlobfsBdev to path /tmp/spdk_tmp_mount...
blobfs_fuse.c: 267:fuse_loop_new_thread: *NOTICE*: Start to loop blobfs on bdev BlobfsBdev mounted at /tmp/spdk_tmp_mount

So we do need extra sleep to wait for the loop thread to be started, I will push a fix.

**Comment by changpe1** [comment] 2020-09-16 06:55
This patch https://review.spdk.io/gerrit/c/spdk/spdk/+/4260 should fix the issue.

**Comment by changpe1** [comment] 2020-09-18 01:20
Closing this issue for now as the patch has been merged.

**Closed by changpe1** 2020-09-18 01:20 UTC
Labels: Intermittent Failure

**Comment by spdkci** [comment] 2021-01-11 12:17
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_33709.html
