### ISSUE TITLE
SPDK latency is higher than Linux direct IO when using multiple thread

### ISSUE THREAD

**Issue by cighao** [spdk/spdk#1027] opened 2019-11-01 13:37 UTC
When using `nvme_perf` to test my Samsung NVMe SSD, I got 9.7 us latency with one thread and 39us latency with 8 thread (by setting `-c ff`). But the latency of 8 threads (39us) is much bigger than the Linux direct io latency (29us,  by FIO with `numjobs=8`). Why does spdk perform worse than Linux direct io?

![image](https://user-images.githubusercontent.com/10767282/68028190-47827680-fcc5-11e9-8f22-a00e159ba767.png)

**Comment by optimistyzy** [comment] 2019-11-04 04:33
@cighao Can you use the spdk_nvme_perf to test the nvme device with AIO model directly? This could be much fair since it tested with the same tool.

**Comment by cighao** [comment] 2019-11-04 06:10
@optimistyzy I set `-D HAVE_AIO=true` in Makefile,  and get similar results.

**Comment by Comphix** [comment] 2019-11-06 02:50
@cighao , please refer to https://mp.weixin.qq.com/s?__biz=MzI3NDA4ODY4MA==&mid=2653334990&idx=1&sn=2b8cc25a6271e96ad0499fa805d34404&chksm=f0cb5a49c7bcd35f0f52da024484769b75be2aefc96de5f8b4ec0266c60fe8c0a8c175331c4f&token=431082989&lang=zh_CN#rd document where we have described SPDK perf tool

And also refer below command to test AIO in the nvme_perf tool for a fair comparison.

perf -q 32 -s 1024 -w randwrite -t 1200 -c 0xF -o 4096 /dev/nvme0n1

Thanks, Gang

**Comment by benlwalker** [comment] 2019-11-13 17:56
Which I/O engine are you using when you use fio to test through the kernel? What's the total I/Ops you see with fio through the kernel, vs. that same test with SPDK? It could be something as simple as SPDK just doing a lot more I/O than fio, even though they're both at queue depth 1, because fio is spending time with other overhead that isn't part of the latency calculation.

**Comment by cighao** [comment] 2019-11-14 12:39
@benlwalker I used libaio in FIO. And the IOPS in fio is still high than than in nvme_perf.
![image](https://user-images.githubusercontent.com/10767282/68857876-ddba9180-06f4-11ea-9167-c4622ad274a7.png)

**Comment by benlwalker** [comment] 2019-11-14 17:37
Can you provide your full fio configuration file? I can try to reproduce it (although I'll be using an Intel SSD). While I do that, are you able to try this on a different SSD? The main theoretical difference here is that SPDK is polling for completions and libaio is using interrupts, but I'd like to rule out that there isn't some other unintentional difference.

**Comment by cighao** [comment] 2019-11-14 20:33
@benlwalker this is the configuration:

```
[global]
name=fio-seq-write
ioengine=libaio
direct=1
thread=1
buffered=0
randrepeat=0
ramp_time=0
norandommap
refill_buffers
log_max_value=1
group_reporting
percentile_list=25.0:50.0:75.0:99.0
filename=/dev/nvme0n1

[file1]
bs=4k
iodepth=1
numjobs=1
rw=write
time_based
runtime=60
```

I also try this on Intel DC P4800X SSD. Under the same configurations, the latency of SPDK is much lower than that of FIO. This is different from the results on Samsung PM963.

**Comment by peluse** [comment] 2020-07-06 17:21
This is pretty old, @cighao are you still interested in moving forward on this?

**Comment by cighao** [comment] 2020-07-09 10:02
> This is pretty old, @cighao are you still interested in moving forward on this?
@peluse Yes. I'd like to. Do you have any suggestions?

**Comment by jimharris** [comment] 2020-11-02 17:41
The latest information here indicates that this issue is specific to the Samsung SSD, and is not seen with the Intel P4800X SSD.  Closing as a 3rd party issue.

@cighao - if you are still interested in debugging this, we can continue the discussion here.  It would be interesting to try 1 thread with QD=8 and compare to the 8 threads with QD=1.  This would affect the number of qpairs used for the test which may affect the results for the Samsung SSD.  For this case, it's most likely not SPDK itself that is causing the higher latency, but rather differences in how SPDK and the kernel driver submit I/O to the SSD and how the Samsung SSD reacts to those differences.

**Closed by jimharris** 2020-11-02 17:41 UTC
Labels: question
