### ISSUE TITLE
[nvme-hotplug] version `GLIBC_2.32' not found

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2185] opened 2021-09-30 08:08 UTC
# CI Intermittent Failure

During nvme-hotplug test, system reported that GLIBC_2.32 was not found.

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_59442.html

## Execution failed at

```
00:06:24.808  ************************************
00:06:24.808  START TEST nvme_hotplug
00:06:24.808  ************************************

...

00:06:50.706  build/examples/hotplug: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /root/dpdk/build/lib/librte_eal.so.21)
00:06:50.709  ========== Backtrace start: ==========
00:06:50.709  
00:06:50.724  in test/nvme/hotplug.sh:14 -> ssh_vm(["LD_LIBRARY_PATH=/root//build/lib:/root/dpdk/build/lib::/var/jenkins/workspace/nvme-phy-autotest/spdk/build/lib:/var/jenkins/workspace/nvme-phy-autotest/spdk/dpdk/build/lib:/var/jenkins/workspace/nvme-phy-autotest/spdk/build/lib:/var/jenkins/workspace/nvme-phy-autotest/spdk/dpdk/build/lib build/examples/hotplug -i 0 -t 25 -n 4 -r 8"])
00:06:50.724       ...
00:06:50.724     9   		exit 1
00:06:50.724     10  	fi
00:06:50.724     11  	
00:06:50.724     12  	function ssh_vm() {
00:06:50.724     13  		xtrace_disable
00:06:50.724  => 14  		sshpass -p "$password" ssh -o PubkeyAuthentication=no \
00:06:50.724     15  			-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 10022 root@localhost "$@"
00:06:50.724     16  		xtrace_restore
00:06:50.724     17  	}
00:06:50.724     18  	
00:06:50.724     19  	function monitor_cmd() {
00:06:50.724       ...
00:06:50.729  in test/nvme/hotplug.sh:118 -> main(["root"])
00:06:50.729       ...
00:06:50.730     113 	
00:06:50.730     114 	insert_devices
00:06:50.730     115 	
00:06:50.730     116 	timing_enter hotplug_test
00:06:50.730     117 	
00:06:50.730  => 118 	ssh_vm "LD_LIBRARY_PATH=/root//build/lib:/root/dpdk/build/lib:$LD_LIBRARY_PATH build/examples/hotplug -i 0 -t 25 -n 4 -r 8" &
00:06:50.730     119 	example_pid=$!
00:06:50.730     120 	
00:06:50.730     121 	sleep 6
00:06:50.730     122 	remove_devices
00:06:50.730     123 	sleep 4
00:06:50.730       ...
00:06:50.730  
00:06:50.730  ========== Backtrace end ==========
```

**Comment by spdkci** [comment] 2021-09-30 08:09
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59447.html

**Comment by spdkci** [comment] 2021-09-30 08:09
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59442.html

**Comment by mikeBashStuff** [comment] 2021-10-03 14:31
This is duplicate of #2150.

**Closed** 2021-10-04 08:01 UTC
Labels: Intermittent Failure
