### ISSUE TITLE
[test_name] dpdk_governor failed

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#1784] opened 2021-02-05 02:21 UTC
Waiting for samples...
00:09:06.788  MAIN DPDK cpu1 current frequency at 2578549 KHz (2700000 KHz), set frequency 2500000 KHz < 2600000 KHz
00:09:07.895  MAIN DPDK cpu1 current frequency at 2441213 KHz (2700000 KHz), set frequency 2400000 KHz < 2500000 KHz
00:09:08.593  MAIN DPDK cpu1 current frequency at 2534839 KHz (2700000 KHz), set frequency 2300000 KHz < 2400000 KHz
00:09:09.783  MAIN DPDK cpu1 current frequency at 2465728 KHz (2700000 KHz), set frequency 2200000 KHz < 2300000 KHz
00:09:10.752  MAIN DPDK cpu1 current frequency at 2414396 KHz (2700000 KHz), set frequency 2100000 KHz < 2200000 KHz
00:09:11.737  MAIN DPDK cpu1 current frequency at 2385324 KHz (2700000 KHz), set frequency 2000000 KHz < 2100000 KHz
00:09:12.726  MAIN DPDK cpu1 current frequency at 2384943 KHz (2700000 KHz), set frequency 1900000 KHz < 2000000 KHz
00:09:13.733  MAIN DPDK cpu1 current frequency at 2336041 KHz (2700000 KHz), set frequency 1800000 KHz < 1900000 KHz
00:09:14.623  MAIN DPDK cpu1 current frequency at 2691379 KHz (2700000 KHz), set frequency 1700000 KHz < 1800000 KHz
00:09:15.705  MAIN DPDK cpu1 current frequency at 2690577 KHz (2700000 KHz), set frequency 1600000 KHz < 1700000 KHz
00:09:16.788  MAIN DPDK cpu1 current frequency at 2690719 KHz (2700000 KHz), set frequency 1500000 KHz < 1600000 KHz
00:09:17.653  MAIN DPDK cpu1 current frequency at 2690048 KHz (2700000 KHz), set frequency 1400000 KHz < 1500000 KHz
00:09:18.519  ========== Backtrace start: ==========
00:09:18.519  
00:09:18.528  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/scheduler/governor.sh:127 -> verify_dpdk_governor([])
00:09:18.528       ...
00:09:18.528     122 			fi
00:09:18.528     123 	
00:09:18.528     124 			old_main_core_setspeed=$main_core_setspeed
00:09:18.528     125 		done
00:09:18.528     126 	
00:09:18.528  => 127 		((all_set == 1))
00:09:18.528     128 	
00:09:18.528     129 		xtrace_restore
00:09:18.528     130 	}
00:09:18.528     131 	
00:09:18.528     132 	map_cpufreq
00:09:18.528       ...
00:09:18.531  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/scheduler/governor.sh:136 -> main([])

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/35865/archive/nvme-phy-autotest/build.log

**Comment by spdkci** [comment] 2021-02-05 02:23
Another instance of this failure. Reported by @optimistyzy. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_35865.html

**Comment by Maciej-Szwed** [comment] 2021-02-05 08:03
@mikeBashStuff could you take a look at this?

**Comment by mikeBashStuff** [comment] 2021-02-05 09:53
@Maciej-Szwed Sure. At first glance either dpdk's governor didn't set frequency to the lowest supported value by given cpu or the list of said values was not properly generated. Will take a closer look.

**Comment by mikeBashStuff** [comment] 2021-02-05 10:48
Ok, here's the mitigation: https://review.spdk.io/gerrit/c/spdk/spdk/+/6283 - this is clearly a timing issue. Apparently, governor may need some more time to tweak proper sysfs knobs. Reproduced this on GP1 (it's where the initial report came from). Interestingly, GP1 also has SMT disabled as compared to other boxes from the CI pool. I would leave it like this though since it gives us additional use-case the governor|scheduler is tested under.

**Comment by spdkci** [comment] 2021-02-06 16:31
Another instance of this failure. Reported by @AlekseyMarchuk. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_35971.html

**Comment by spdkci** [comment] 2021-02-08 19:53
Another instance of this failure. Reported by @peluse. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36122.html

**Comment by tomzawadzki** [comment] 2021-02-09 14:34
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/6283 was merged. Lets wait for a week to see if there are any new reports before closing.

**Comment by mikeBashStuff** [comment] 2021-02-17 10:13
It seems like the issue is gone, let's close the issue. Will reopen if it resurfaces again.

**Closed by mikeBashStuff** 2021-02-17 10:13 UTC
Labels: Intermittent Failure

**Comment by spdkci** [comment] 2021-03-09 08:27
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_38410.html

**Comment by spdkci** [comment] 2021-05-19 12:04
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_47711.html
