### ISSUE TITLE
[bdev_write_zeroes] Build timed out

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1371] opened 2020-04-24 21:12 UTC

**Comment by spdkci** [comment] 2020-04-24 21:14
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_11821.html

**Comment by changpe1** [comment] 2020-04-30 02:56
************************************
START TEST bdev_write_zeroes
************************************
 21:40:55	# xtrace_enable

 21:40:57	# set +x
************************************
END TEST bdev_write_zeroes
************************************
 21:40:57	# /var/jenkins/workspace/nvme-autotest/spdk/scripts/setup.sh reset
Build timed out (after 15 minutes). Marking the build as failed.
0000:00:09.0 (8086 5845): uio_pci_generic -> nvme
Build was aborted

This just happened after the bdev_write_zeroes test, it should not related with this test.

**Comment by changpe1** [comment] 2020-04-30 04:16
@peluse Could you update the information, this is a build time out issue.

**Comment by changpe1** [comment] 2020-05-14 00:38
The failure is on fedora_vm_9.

**Comment by tomzawadzki** [comment] 2020-05-19 14:39
Duplicate of #1365

**Closed by tomzawadzki** 2020-05-19 14:39 UTC
Labels: Intermittent Failure
