### ISSUE TITLE
[Autotest-per-patch]nvmf_tcp_autotest failed to run

### ISSUE THREAD

**Issue by ChenBo2333** [spdk/spdk#1015] opened 2019-10-29 02:26 UTC
When run nvmf_tcp_autotest , the remote end hung up unexpectedly.

## Expected Behavior
run successfully without errors.

## Current Behavior
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
./copy_or_clone.sh: line 16: cd: spdk: No such file or directory
git version 2.17.2

## Possible Solution
N/A

## Steps to Reproduce
View build log on https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/48062/archive/nvmf_tcp_autotest/build.log

**Comment by Seth5141** [comment] 2019-10-29 22:47
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48150.html

**Comment by spdkci** [comment] 2019-10-29 23:35
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48112.html

**Comment by optimistyzy** [comment] 2019-10-30 05:40
It seems that this issue is not related with NVMe-oF tcp test workloads.

**Comment by karlatec** [comment] 2019-10-30 12:01
This seems to be related or a duplicate of #1007 - IMO these are issues with connectivity to Gerrithub.

**Comment by Seth5141** [comment] 2019-10-30 17:28
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48150.html

**Comment by Seth5141** [comment] 2019-10-30 17:28
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48112.html

**Comment by tomzawadzki** [comment] 2019-10-30 22:28
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/48263/archive/nvmf_tcp_autotest/build.log

**Comment by jimharris** [comment] 2019-10-31 04:19
Bug scrub: Seth to close this issue and change description on issue #1007 to characterize it more generally as Jenkins CI timeouts.

**Closed** 2019-10-31 15:06 UTC
Labels: Intermittent Failure
