### ISSUE TITLE
NVMe-oF TCP Target performance degradation

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#2934] opened 2023-03-03 14:19 UTC
# Sighting report

Performance degradation detected on [performance.spdk.io](https://performance.spdk.io/d/4tDkVyd4k/spdk-nvme-of-tcp-performance?orgId=1&from=now-30d&to=now&var-cpus=4&var-qd=128&var-rw=randread&refresh=5s).

On Feb 28th there was a bulk of patches merged which affect TCP Target performance:
![image](https://user-images.githubusercontent.com/28856727/222743271-1423548c-5804-46ff-8a0e-46216f406266.png)

In detail the difference for one of the test runs look like this:
![image](https://user-images.githubusercontent.com/28856727/222743390-f2b684f3-eea6-4649-b537-8c3c4d68acff.png)

Last good test result was with 2b772dbbbc6e6f5466faccc4c1c1be03c6aac16a and first bad results with 019cbb9335c016b86af0e1fa68303e4f34a27e5a.
Further bisecting leads to 019cbb9335c016b86af0e1fa68303e4f34a27e5a as first faulty commit.

This drop is visible only for Random Read workload. There is no noticeable degradation for Random Write and Random RW.

## Expected Behavior

N/A

## Current Behavior

N/A

## Context (Environment including OS version, SPDK version, etc.)

SPDK 019cbb9335c016b86af0e1fa68303e4f34a27e5a

**Comment by ksztyber** [comment] 2023-03-03 14:29
@karlatec, there's a series from @benlwalker [1] that replaces data mempool with iobuf. Could you check if it fixes this?

[1] https://review.spdk.io/gerrit/c/spdk/spdk/+/16297/14

**Comment by karlatec** [comment] 2023-03-06 12:27
It actually seems to be even worse then current master.

On example of 4k RandRead QD=128, 4 CPU Target Case (yellow line in the chart):
* Last good commit - ~2.6M IOPS
* Current master - ~2.1M IOPS
* Proposed patch - ~1.9M IOPS

FYI I had to increase iobuf large pool size to 4k, otherwise I could not start the test:
```
[2023-03-06T07:14:13.318Z] [target:spdk_tgt_configure:1154] Configuring SPDK NVMeOF target via RPC
[2023-03-06T07:14:13.318Z] [2023-03-06 08:14:13.222830] transport.c: 217:spdk_nvmf_transport_create: *ERROR*: Requested 4096 shared buffers but only 2047 in iobuf pool.
[2023-03-06T07:14:13.318Z] [2023-03-06 08:14:13.222854] nvmf_rpc.c:1996:rpc_nvmf_create_transport: *ERROR*: Transport type 'tcp' create failed
```

**Comment by jimharris** [comment] 2023-03-06 14:53
I think the problem is that default buf_cache_size is way too small for TCP - it's 32.

So before `019cbb9` the cache wasn't really doing anything.  We were only getting "good" performance because of the per-core cache in the mempool.

What are buf_cache_size and num_shared_buffers set to for these tests?  Can you try increasing buf_cache_size and do another test run?  We obviously need some more work around determining the correct buf_cache_size, but want to know for sure this is the problem before proceeding further.

**Comment by karlatec** [comment] 2023-03-07 08:02
Here are the full transport layer parameters:
```
[                                                                                                                                                                                                                    
  {                                                                                                                                                                                                                  
    "trtype": "TCP",                                                                                                                                                                                                 
    "max_queue_depth": 128,                                                                                                                                                                                          
    "max_io_qpairs_per_ctrlr": 127,                                                                                                                                                                                  
    "in_capsule_data_size": 4096,                                                                                                                                                                                    
    "max_io_size": 131072,                                                                                                                                                                                           
    "io_unit_size": 131072,                                                                                                                                                                                          
    "max_aq_depth": 128,                                                                                                                                                                                             
    "num_shared_buffers": 4096,                                                                                                                                                                                      
    "buf_cache_size": 32,                                                                                                                                                                                            
    "dif_insert_or_strip": false,                                                                                                                                                                                    
    "zcopy": false,                                                                                                                                                                                                  
    "c2h_success": true,                                                                                                                                                                                             
    "sock_priority": 0,                                                                                                                                                                                              
    "abort_timeout_sec": 1                                                                                                                                                                                           
  }                                                                                                                                                                                                                  
]  
```

And iobuf pool count params are set to 16383 and 2047 (4096 specifically for the last test run with Ben's patch). 

> Can you try increasing buf_cache_size and do another test run? 

Sure. Just to be clear - do you want me to run these test with current master branch and see if the results go back up, or should I keep using Ben's series?

**Comment by karlatec** [comment] 2023-03-07 11:57
I used https://review.spdk.io/gerrit/c/spdk/spdk/+/16297/14 and ran the test with iobuf pool count params set to 16383 and 8192, buf_cache_size = {64, 96, 128}. Can't really see any improvements in results.
For previously mentioned test case (4k RandRead QD=128, 4 CPU Target) for all three test runs the results were 1.85-2.00M IOPS, so lower than last good commit and lower than current master.

**Comment by karlatec** [comment] 2023-03-07 14:58
Had to increase num_shared_buffers from 4k to 8k for that. Still not seeing improvement with ~1.9M IOPS for this particular case.

**Comment by karlatec** [comment] 2023-03-08 12:02
Did 3 re-runs with https://review.spdk.io/gerrit/c/spdk/spdk/+/17084 `[RFC] Revert "nvmf: disable data buf mempool cache"`.

Results are much closer to last good commit:
* 2.4M IOPS
* 2.4M IOPS
* 2.2M IOPS

**Comment by jimharris** [comment] 2023-03-10 19:32
Could you try the faulty patch, and then change buf_cache_size to 544?  IIRC, when you changed buf_cache_size earlier, it was with the iobuf series from Ben, not master.

**Comment by karlatec** [comment] 2023-03-14 09:18
The average for beforementioned workload was ~2.6M IOPS before faulty patch. With faulty patch and buf_cache_size set to 544 I got an average of ~2.69M IOPS.

So as I understand the fix now would be to adjust the regression tests configuration and keep buf_cache_size at 544? We'd also need to increase num_shared_buffers to some high value, because it failed a couple of time when I was doing re-runs.
For example for 16 core SPDK Target it fails with:
```
[2023-03-14T07:01:24.696Z] [2023-03-14 08:01:24.548452] tcp.c: 707:nvmf_tcp_create: *ERROR*: There are not enough buffers to satisfy per-poll group caches for each thread. (8192) supplied. (8704) required
```

**Comment by ksztyber** [comment] 2023-03-14 15:12
[Bug scrub] @karlatec, let's increase this to 512 in the regression. But we should also increase the default in the TCP target to 512. @jimharris said he'll push a patch to do that.

**Comment by jimharris** [comment] 2023-03-14 15:34
Thanks @karlatec!

https://review.spdk.io/gerrit/c/spdk/spdk/+/17203

Once this is merged, let's wait to close until @karlatec observes the performance chart go back to "normal".

**Comment by karlatec** [comment] 2023-03-27 07:22
Tested new version of https://review.spdk.io/gerrit/c/spdk/spdk/+/17203, just the 4k random read workload for now - looks good. Will check 128k workloads and update later.

**Closed** 2023-03-28 23:03 UTC
Labels: bug, High, Patches out for review
