### ISSUE TITLE
ceph 14.2.3 not compatible with test scripts

### ISSUE THREAD

**Issue by wawryk** [spdk/spdk#980] opened 2019-10-09 09:25 UTC
RBD test fails.
Tested on Fedora30
Ceph version:
    ceph version 14.2.3 (0f776cf838a1ae3130b2b73dc26be9c95c6ccc39) nautilus (stable)

## Expected Behavior
Test should pass.

## Current Behavior
Test fail: 

> + ceph-authtool --create-keyring --gen-key --name=mon. /var/tmp/ceph/keyring --cap mon 'allow *'
> creating /var/tmp/ceph/keyring
> + ceph-authtool --gen-key --name=client.admin --set-uid=0 --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow *' --cap mgr 'allow *' /var/tmp/ceph/keyring
ceph-authtool: unexpected '/var/tmp/ceph/keyring'
usage: ceph-authtool keyringfile [OPTIONS]...
where the options are:
  -l, --list                    will list all keys and capabilities present in
                                the keyring
  -p, --print-key               will print an encoded key for the specified
                                entityname. This is suitable for the
                                'mount -o secret=..' argument
  -C, --create-keyring          will create a new keyring, overwriting any
                                existing keyringfile
  -g, --gen-key                 will generate a new secret key for the
                                specified entityname
  --gen-print-key               will generate a new secret key without set it
                                to the keyringfile, prints the secret to stdout
  --import-keyring FILE         will import the content of a given keyring
                                into the keyringfile
  -n NAME, --name NAME          specify entityname to operate on
  -a BASE64, --add-key BASE64   will add an encoded key to the keyring
  --cap SUBSYSTEM CAPABILITY    will set the capability for given subsystem
  --caps CAPSFILE               will set all of capabilities associated with a
                                given key, for all subsystems
  --mode MODE                   will set the desired file mode to the keyring
                                e.g: '0644', defaults to '0600'
  06:34:40      # trap - ERR
  06:34:40      # print_backtrace
  06:34:40      # [[ ehxBE =~ e ]]
  06:34:40      # xtrace_disable
  06:34:40      # PREV_BASH_OPTS=ehxBE
  06:34:40      # set +x
========== Backtrace start: ==========
in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:504 -> rbd_setup()
     ...
   499          if hash ceph; then
   500                  export PG_NUM=128
   501                  export RBD_POOL=rbd
   502                  export RBD_NAME=foo
   503                  $NS_CMD $rootdir/scripts/ceph/stop.sh || true
=> 504                  $NS_CMD $rootdir/scripts/ceph/start.sh $1
   505
   506                  $NS_CMD ceph osd pool create $RBD_POOL $PG_NUM || true
   507                  $NS_CMD rbd create $RBD_NAME --size 1000
   508          fi
   509  }
     ...
`

## Steps to Reproduce

1. Run RBD_autotest with newest ceph version (default in fedora30)

## Context (Environment including OS version, SPDK version, etc.)

Tested on Fedora30
Ceph version:
    ceph version 14.2.3 (0f776cf838a1ae3130b2b73dc26be9c95c6ccc39) nautilus (stable)

**Comment by yidong0635** [comment] 2019-10-10 07:30
new version ceph-authtool  remove this :
 -u AUID, --set-uid AUID       sets the auid (authenticated user id) for the
                                specified entityname
if remove --set-uid=0  ceph create OSD will hang.

**Comment by yidong0635** [comment] 2019-10-10 08:36
small changes work on 12.2.12  which not on fedora30 but using  "`yum update ceph`" ,
log as [ceph.txt](https://github.com/spdk/spdk/files/3711271/ceph.txt)
https://review.gerrithub.io/c/spdk/spdk/+/470915
there're still other issue on fedora30 with ceph version 14.2.3 ,and this version I found it's stable,
even can't well display "ceph -v".

**Comment by wawryk** [comment] 2019-10-14 14:14
In ceph version 14.2.3 it freeze on:
+ ceph -c /var/tmp/ceph/ceph.conf osd create d1109bab-0b0d-48ff-ae1b-1e0fb575fa8f 0

**Comment by changpe1** [comment] 2019-10-17 01:35
@yidong0635 can you confirm the issue is exist or not ? Thanks

**Comment by yidong0635** [comment] 2019-10-17 01:50
@changpe1  as I said, this is another issue, let's keep it. still need to investigate.

**Comment by wawryk** [comment] 2019-10-25 09:40
Tested today on:
Fedora30 kernel version: 
`5.3.6-200.fc30.x86_64`
Ceph version:
`ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)`
This small version update still freeze on: 
`ceph -c /var/tmp/ceph/ceph.conf osd create 71e3a0e8-2ff6-48d7-aa01-5d8052c61e18 0`

**Comment by tomzawadzki** [comment] 2019-11-05 15:39
Bug scrub: @yidong0635 as per @wawryk report it still seems to reproduce. Have you been able to take a look at it ?

**Comment by yidong0635** [comment] 2019-11-06 10:30
found somthing，before osd creation，ceph -s should be OK，but now it’s not. This may be the scripts compliance problem.

**Comment by yidong0635** [comment] 2019-11-08 10:21
I think I found the error, but now it's hard to add solution.
+ monmaptool --create --clobber --add a 172.0.0.1:12046 --print /var/tmp/ceph/monmap --set-min-mon-release 14
```
monmaptool: monmap file /var/tmp/ceph/monmap
monmaptool: generated fsid 6279e447-97a2-40f2-aed1-9c292431a69f
setting min_mon_release = 14
epoch 0
fsid 6279e447-97a2-40f2-aed1-9c292431a69f
last_changed 2019-11-09 09:12:15.945569
created 2019-11-09 09:12:15.945569
min_mon_release 14 (nautilus)
0: `v2:172.0.0.1:12046`/0 mon.a
```
binding addr is 172.0.0.1:12046 "v2:" is redundant .
we can add "` echo -e '\tmon addr = v2:172.0.0.1:12046'` " ceph -s is ok. but address translation meet issue later ,it can't recongnize " v2:" ,will discuss this  next week.

**Comment by wawryk** [comment] 2019-11-08 10:21
@yidong0635 have You any idea how to fix it ?

**Comment by yidong0635** [comment] 2019-11-08 10:32
@wawryk  now don't have the whole solution, in progress.

**Comment by yidong0635** [comment] 2019-11-11 08:19
patch : https://review.gerrithub.io/c/spdk/spdk/+/473831.

**Comment by jimharris** [comment] 2019-11-14 16:30
Patch merged.  Thanks!

**Closed by jimharris** 2019-11-14 16:30 UTC
