### ISSUE TITLE
rpc timeout in nvme_rpc test

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1255] opened 2020-03-04 12:29 UTC
https://ci.spdk.io/results/autotest-per-patch/builds/5477/archive/freebsd-autotest/build.log

It seems to be caused by the fact that upon calling `rpc.py` `/var/tmp/spdk.sock` was already in use.

**Comment by spdkci** [comment] 2020-03-04 12:29
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_5484.html

**Comment by mikeBashStuff** [comment] 2020-03-04 15:22
There's also this hidden segfault for which the core dump was not fetched as the host that was running the test didn't have `eu-readelf` installed and used `grep` without the support for perl regexes (`-P`) (that part actually caused `process_core()` to fail entirely).

**Comment by jimharris** [comment] 2020-03-05 04:14
Bug scrub: assigning to Gang - he will assign to someone from his team

**Comment by dong-liuliu** [comment] 2020-03-05 07:28
hi, @mikeBashStuff 
I've looked through related failure build.log. It seems to be caused by your own patch set.

**Comment by dong-liuliu** [comment] 2020-03-05 07:35
From the your build log and patch set, for freeBSD platform:
In `test/bdev/blockdev.sh`'s setup_gpt_conf function, when uname is freeBSD not Linux, the test would do `trap -SIGINT SIGTERM EXIT`.  This overrided  the trap operation of function `start_spdk_tgt()` 's trap which would kill SPDK process.

So your bdev gpt test left but without killing its SPDK process. Then latter test cases with spdk_tgt met conflict with previous unkilling one.

**Comment by mikeBashStuff** [comment] 2020-03-05 08:06
@dong-liuliu Ah, I must have dropped call to `killprocess()` from there after one of the rebases. :\ Thanks for checking it out! :)

Though I still wonder what to do about this one https://ci.spdk.io/public_build/autotest-per-patch_5484.html where the actual core dump was written out. Do you think it's worth looking into? If not, I guess we could proceed with closing this issue.

**Comment by dong-liuliu** [comment] 2020-03-06 00:46
Yes, Mike, we could close this issue.

what I'm thinking about this patch, maybe, you can add some `if` condition to trap, like `trap <if ?; then kill spdk> SIGINT SIGTERM EXIT`, in order to avoid unexpected trap overriding.

**Closed** 2020-03-06 00:46 UTC
Labels: Intermittent Failure
