### ISSUE TITLE
alias_rpc timeout (centos7 job)

### ISSUE THREAD

**Issue by jkalwas** [spdk/spdk#1197] opened 2020-02-11 13:25 UTC
example log:
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/60379/archive/centos7_autotest/build.log

**Comment by spdkci** [comment] 2020-02-11 13:29
Another instance of this failure. Reported by @jkalwas. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60379.html

**Comment by jimharris** [comment] 2020-02-20 04:36
Bug scrub: this looks like a real hang - let's continue to monitor to see if this hits again

**Comment by jimharris** [comment] 2020-02-20 15:47
Looking at this further - this test is only running the spdk_tgt, running a couple of deprecated RPCs, and then killing spdk_tgt.

So this did hang, but I'm less convinced that the application didn't respond to the kill.  It's possible this is more related to the general timeouts we see from time to time in the test pool.

Keeping this issue open for now - will continue to monitor.

**Comment by karlatec** [comment] 2020-02-25 08:54
Fortunately I still have a log from old CI for that build which includes Jenkins timestamps!
```
13:59:12 Started by upstream project "autotest-per-patch" build number 60379
13:59:12 originally caused by:
13:59:12  Started by user sys_sgci
13:59:12 [EnvInject] - Loading node environment variables.
13:59:12 Building remotely on centos7_vm_1 (Centos7_VM) in workspace /var/jenkins/workspace/Other_systems/centos7_autotest
13:59:12 Running Prebuild steps
13:59:12 [centos7_autotest] $ /bin/sh -xe /tmp/jenkins1162379286458118717.sh
13:59:12 + set +x
13:59:13 Success build forhudson.tasks.Shell@4bc28e1
13:59:13 provisioning config files...
13:59:13 copy managed file [copy_or_clone] to file:/var/jenkins/workspace/Other_systems/centos7_autotest/copy_or_clone.sh
13:59:14 [centos7_autotest] $ /bin/sh -xe /tmp/jenkins358111080324212028.sh
13:59:14 + export PATH=/usr/local/bin:/usr/bin:/usr/sbin
13:59:14 + PATH=/usr/local/bin:/usr/bin:/usr/sbin
13:59:14 + set +x
14:07:57 UPSTREAM, will not clone
14:07:59 0cac686 nvmf: remove redundant trid object copy
14:07:59 e97ad60 doc/jsonrpc.md: Fix missing closing quote
14:07:59 fc2dbea lib/ftl: Init/fini context moved from dev structure to init module
14:07:59 5780ad9 bdevperf: Change return type of bdevperf_test() to void and include its error handling
14:07:59 3673217 bdevperf: Move target management functions close to the caller
14:07:59 + cat
14:07:59 + unset CONFIG_DPDK_DIR
14:07:59 + [[ -n '' ]]
14:07:59 + [[ -n '' ]]
14:07:59 + cd /var/jenkins/workspace/Other_systems/centos7_autotest/spdk
14:07:59 + git submodule update --init
14:08:00 + cd /var/jenkins/workspace/Other_systems/centos7_autotest
```
Process froze somewhere around fetching the sources. This looks very similar to #1119 which was closed today. 

@darsto @jimharris IMO that's the same issue as #1119 and additionally there was no update since original issue submission. I think we can close this one.

**Comment by Seth5141** [comment] 2020-02-25 15:27
Bug Scrub: Closing this as a duplicate of #1119 Thanks @karlatec for the fix to the VMs.

**Closed by Seth5141** 2020-02-25 15:27 UTC
Labels: Intermittent Failure
