### ISSUE TITLE
[test_name] nvmf-phy-autotest build failure

### ISSUE THREAD

**Issue by krish-reddy** [spdk/spdk#2160] opened 2021-09-15 10:40 UTC
# CI Intermittent Failure

00:11:29.155  ************************************
00:11:29.155  START TEST nvmf_multipath
00:11:29.155  ************************************
00:11:29.156   12:16:57	-- common/autotest_common.sh@959 -- # xtrace_enable
00:11:29.156   12:16:57	-- common/autotest_common.sh@960 -- # test/nvmf/host/multipath.sh --transport=rdma

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/58327/archive/nvmf-phy-autotest/build.log

## Execution failed at

00:11:44.430  ========== Backtrace start: ==========
00:11:44.430  
00:11:44.435  in test/nvmf/host/multipath.sh:71 -> main(["--transport=rdma"])
00:11:44.435       ...
00:11:44.435     66  	cat $testdir/try.txt
00:11:44.435     67  	# if this test fails it means we didn't fail over to the second
00:11:44.435     68  	count="$(grep -c "Resetting controller successful" < $testdir/try.txt)"
00:11:44.435     69  	
00:11:44.435     70  	if ((count != 3)); then
00:11:44.435  => 71  		false
00:11:44.435     72  	fi
00:11:44.435     73  	
00:11:44.435     74  	# Part 2 of the test. Start removing ports, starting with the one we are connected to, confirm that the ctrlr remains active until the final trid is removed.
00:11:44.435     75  	$rootdir/test/bdev/bdevperf/bdevperf -z -r $bdevperf_rpc_sock -q 128 -o 4096 -w verify -t 1 -f &> $testdir/try.txt &
00:11:44.435     76  	bdevperf_pid=$!
00:11:44.436       ...
00:11:44.436  
00:11:44.436  ========== Backtrace end ==========

**Comment by spdkci** [comment] 2021-09-15 10:41
Another instance of this failure. Reported by @krish-reddy. log: https://ci.spdk.io/public_build/autotest-per-patch_58327.html

**Comment by mikeBashStuff** [comment] 2021-09-15 10:42
I think it's a duplicate of #2128

**Closed** 2021-09-15 10:56 UTC
Labels: Intermittent Failure
