### ISSUE TITLE
[vhost bug] Continuous stressful operations cause vhost app to crash or respond timeout

### ISSUE THREAD

**Issue by beef9999** [spdk/spdk#339] opened 2018-06-22 09:38 UTC
Hi, guys

I was running some stress tests before trying to deploy SPDK into production environment. Then I found the vhost app would occasionally crash or respond with connection timeout, when stress was high.

My test case is like this:
1. Setup vhost app
2. Create 10 SPDK volumes (construct_lvol_bdev, construct_vhost_scsi_controller, add_vhost_scsi_lun)
3. Create 10 QEMU guests
4. Attach the volumes to guests as non-bootable disks (vhost-user-scsi-pci)
5. Start the guests

Note for all the guests, the above operations are executed simultaneously.

And in the meantime while the guests starting, the vhost app would:
1. Segmentation fault (core dumped)
2. vhost.c: 928:spdk_vhost_event_send: *ERROR*: Timeout waiting for event: start device.
    Then the program changes to sleeping status, no longer occupy 100% CPU any more.

Test environment: SPDK 18.04, QEMU 2.12.0, CentOS 7.3 kernel

----
```
Core was generated by `/usr/local/bin/spdk_vhost -S /var/tmp -s 4096 -m 0x1'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000450609 in rte_vhost_enable_guest_notification (vid=vid@entry=0, queue_id=queue_id@entry=2, enable=enable@entry=0) at vhost.c:426
426		dev->virtqueue[queue_id]->used->flags = VRING_USED_F_NO_NOTIFY;

(gdb) bt
#0  0x0000000000450609 in rte_vhost_enable_guest_notification (vid=vid@entry=0, queue_id=queue_id@entry=2, enable=enable@entry=0) at vhost.c:426
#1  0x000000000043778a in start_device (vid=0) at vhost.c:1039
#2  0x000000000044ef91 in vhost_user_msg_handler (vid=<optimized out>, fd=fd@entry=27) at vhost_user.c:1346
#3  0x000000000044de9f in vhost_user_read_cb (connfd=27, dat=0x7fa5180008c0, remove=0x7fa51d3e0c58) at socket.c:293
#4  0x0000000000450ce0 in fdset_event_dispatch (arg=0x6ac140 <vhost_user+8192>) at fd_man.c:273
#5  0x00007fa5275d8e25 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fa52730634d in clone () from /lib64/libc.so.6
```

**Comment by ChenWang01** [comment] 2018-06-25 09:09
Hi, Bob 
I can reproduce this issue in our environment with the master branch. Thanks.
Steps for reproduce:
```
1. NRHUGE=12288 ./scripts/setup.sh
2. ./app/vhost/vhost
3. ./rpc.py construct_nvme_bdev -b "nvme0" -t "PCIe" -a "0000:81:00.0"
4. lsguid="$(./rpc.py construct_lvol_store 'nvme0n1' 'lvs0')"
5. for i in `seq 10`; do
           ./rpc.py construct_lvol_bdev -u $lsguid lbd$i 10240
           ./rpc.py construct_vhost_scsi_controller vhost.$i
           ./rpc.py add_vhost_scsi_lun vhost.$i 0 lvs0/lbd$i
    done
6. for i in `seq 10`; do
           qemu-system-x86_64 -cpu host -smp 8 -m 1024 \
           -object memory-backend- file,id=mem,size=1G,mem-path=/dev/hugepages,share=on \
          -numa node,memdev=mem -drive file=snapshot$i.img,if=none,id=disk \
          -device ide-hd,drive=disk,bootindex=0 -net nic -chardev socket,id=char0,path=vhost.$i \
          -device vhost-user-scsi-pci,chardev=char0 --enable-kvm 
   done
```

**Comment by darsto** [comment] 2018-06-25 12:44
This is related to [the very ugly workaround](https://review.gerrithub.io/c/spdk/spdk/+/408611) we crafted to support QEMU 2.12. We are currently in a middle of rewriting vhost initialization code, which should land in master in the upcoming weeks. That will fix this issue. Please assign this bug to me, I'll keep it updated.

**Comment by ChenWang01** [comment] 2018-07-26 05:22
@pawelwod 
I have checked this issue with your patch, and it can be fixed in my environment.

**Comment by pawelwod** [comment] 2018-07-26 08:42
Should be closed by commit, if not please close manually.

**Comment by liang2yan** [comment] 2018-07-26 11:05
Close this issue since patch merged.

**Closed by liang2yan** 2018-07-26 11:05 UTC
Labels: bug
