### ISSUE TITLE
[Fedora36] lib/librte_vhost.a.p/vhost_vhost_crypto.c.o 'outside array bounds'

### ISSUE THREAD

**Issue by kgodzwox** [spdk/spdk#2666] opened 2022-08-26 09:35 UTC
# Issue
`SPDK v22.05-rc1-426-gcd1b7ab0e`

Submodule DPDK compilation failed
`C compiler for the host machine: cc (gcc 12.1.1 "cc (GCC) 12.1.1 20220507 (Red Hat 12.1.1-1)")`
```
12:51:52  [270/273] Compiling C object lib/librte_vhost.a.p/vhost_virtio_net.c.o
12:51:57  [271/273] Compiling C object lib/librte_vhost.a.p/vhost_vhost_crypto.c.o
12:51:57  FAILED: lib/librte_vhost.a.p/vhost_vhost_crypto.c.o 
12:51:57  cc -Ilib/librte_vhost.a.p -Ilib -I../lib -Ilib/vhost -I../lib/vhost -I. -I.. -Iconfig -I../config -Ilib/eal/include -I../lib/eal/include -Ilib/eal/linux/include -I../lib/eal/linux/include -Ilib/eal/x86/include -I../lib/eal/x86/include -Ilib/eal/common -I../lib/eal/common -Ilib/eal -I../lib/eal -Ilib/kvargs -I../lib/kvargs -I../lib/metrics -Ilib/telemetry -I../lib/telemetry -Ilib/ethdev -I../lib/ethdev -Ilib/net -I../lib/net -Ilib/mbuf -I../lib/mbuf -Ilib/mempool -I../lib/mempool -Ilib/ring -I../lib/ring -Ilib/meter -I../lib/meter -Ilib/cryptodev -I../lib/cryptodev -Ilib/rcu -I../lib/rcu -Ilib/hash -I../lib/hash -Ilib/pci -I../lib/pci -Ilib/dmadev -I../lib/dmadev -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -O3 -include rte_config.h -Wcast-qual -Wdeprecated -Wformat -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpointer-arith -Wsign-compare -Wstrict-prototypes -Wundef -Wwrite-strings -Wno-address-of-packed-member -Wno-packed-not-aligned -Wno-missing-field-initializers -Wno-zero-length-bounds -D_GNU_SOURCE -fPIC -Werror -Wno-stringop-overflow -fcommon -Wno-stringop-overread -fPIC -march=native -DALLOW_EXPERIMENTAL_API -DALLOW_INTERNAL_API -Wno-format-truncation -DVHOST_GCC_UNROLL_PRAGMA -fno-strict-aliasing -DRTE_LOG_DEFAULT_LOGTYPE=lib.vhost -MD -MQ lib/librte_vhost.a.p/vhost_vhost_crypto.c.o -MF lib/librte_vhost.a.p/vhost_vhost_crypto.c.o.d -o lib/librte_vhost.a.p/vhost_vhost_crypto.c.o -c ../lib/vhost/vhost_crypto.c
12:51:57  In file included from /usr/lib/gcc/x86_64-redhat-linux/12/include/immintrin.h:43,
12:51:57                   from /usr/lib/gcc/x86_64-redhat-linux/12/include/x86intrin.h:32,
12:51:57                   from ../lib/eal/x86/include/rte_vect.h:31,
12:51:57                   from ../lib/eal/x86/include/rte_memcpy.h:17,
12:51:57                   from ../lib/mempool/rte_mempool.h:46,
12:51:57                   from ../lib/mbuf/rte_mbuf.h:38,
12:51:57                   from ../lib/vhost/vhost_crypto.c:7:
12:51:57  In function ‘_mm256_storeu_si256’,
12:51:57      inlined from ‘rte_mov32’ at ../lib/eal/x86/include/rte_memcpy.h:320:2,
12:51:57      inlined from ‘rte_mov128’ at ../lib/eal/x86/include/rte_memcpy.h:343:2,
12:51:57      inlined from ‘rte_memcpy_generic’ at ../lib/eal/x86/include/rte_memcpy.h:438:4,
12:51:57      inlined from ‘rte_memcpy’ at ../lib/eal/x86/include/rte_memcpy.h:882:10,
12:51:57      inlined from ‘copy_data’ at ../lib/vhost/vhost_crypto.c:588:2,
12:51:57      inlined from ‘vhost_crypto_process_one_req’ at ../lib/vhost/vhost_crypto.c:1256:6,
12:51:57      inlined from ‘rte_vhost_crypto_fetch_requests’ at ../lib/vhost/vhost_crypto.c:1656:8:
12:51:57  /usr/lib/gcc/x86_64-redhat-linux/12/include/avxintrin.h:935:8: error: array subscript ‘__m256i_u[2]’ is partly outside array bounds of ‘struct virtio_crypto_op_data_req[1]’ [-Werror=array-bounds]
12:51:57    935 |   *__P = __A;
12:51:57        |   ~~~~~^~~~~
12:51:57  ../lib/vhost/vhost_crypto.c: In function ‘rte_vhost_crypto_fetch_requests’:
12:51:57  ../lib/vhost/vhost_crypto.c:1178:42: note: at offset 64 into object ‘req’ of size 72
12:51:57   1178 |         struct virtio_crypto_op_data_req req;
12:51:57        |                                          ^~~
12:51:57  In function ‘_mm256_storeu_si256’,
12:51:57      inlined from ‘rte_mov32’ at ../lib/eal/x86/include/rte_memcpy.h:320:2,
12:51:57      inlined from ‘rte_mov128’ at ../lib/eal/x86/include/rte_memcpy.h:344:2,
12:51:57      inlined from ‘rte_memcpy_generic’ at ../lib/eal/x86/include/rte_memcpy.h:438:4,
12:51:57      inlined from ‘rte_memcpy’ at ../lib/eal/x86/include/rte_memcpy.h:882:10,
12:51:57      inlined from ‘copy_data’ at ../lib/vhost/vhost_crypto.c:588:2,
12:51:57      inlined from ‘vhost_crypto_process_one_req’ at ../lib/vhost/vhost_crypto.c:1256:6,
12:51:57      inlined from ‘rte_vhost_crypto_fetch_requests’ at ../lib/vhost/vhost_crypto.c:1656:8:
12:51:57  /usr/lib/gcc/x86_64-redhat-linux/12/include/avxintrin.h:935:8: error: array subscript 3 is outside array bounds of ‘struct virtio_crypto_op_data_req[1]’ [-Werror=array-bounds]
12:51:57    935 |   *__P = __A;
12:51:57        |   ~~~~~^~~~~
12:51:57  ../lib/vhost/vhost_crypto.c: In function ‘rte_vhost_crypto_fetch_requests’:
12:51:57  ../lib/vhost/vhost_crypto.c:1178:42: note: at offset 96 into object ‘req’ of size 72
12:51:57   1178 |         struct virtio_crypto_op_data_req req;
12:51:57        |                                          ^~~
12:51:57  In function ‘_mm256_storeu_si256’,
12:51:57      inlined from ‘rte_mov32’ at ../lib/eal/x86/include/rte_memcpy.h:320:2,
12:51:57      inlined from ‘rte_memcpy_generic’ at ../lib/eal/x86/include/rte_memcpy.h:450:4,
12:51:57      inlined from ‘rte_memcpy’ at ../lib/eal/x86/include/rte_memcpy.h:882:10,
12:51:57      inlined from ‘copy_data’ at ../lib/vhost/vhost_crypto.c:588:2,
12:51:57      inlined from ‘vhost_crypto_process_one_req’ at ../lib/vhost/vhost_crypto.c:1256:6,
12:51:57      inlined from ‘rte_vhost_crypto_fetch_requests’ at ../lib/vhost/vhost_crypto.c:1656:8:
12:51:57  /usr/lib/gcc/x86_64-redhat-linux/12/include/avxintrin.h:935:8: error: array subscript ‘__m256i_u[2]’ is partly outside array bounds of ‘void[72]’ [-Werror=array-bounds]
12:51:57    935 |   *__P = __A;
12:51:57        |   ~~~~~^~~~~
12:51:57  ../lib/vhost/vhost_crypto.c: In function ‘rte_vhost_crypto_fetch_requests’:
12:51:57  ../lib/vhost/vhost_crypto.c:1178:42: note: at offset [0, 64] into object ‘req’ of size 72
12:51:57   1178 |         struct virtio_crypto_op_data_req req;
12:51:57        |                                          ^~~
12:51:57  ../lib/vhost/vhost_crypto.c:1178:42: note: at offset [1, 72] into object ‘req’ of size 72
```
```
12:51:57  ========== Backtrace start: ==========
12:51:57  
12:51:57  in /home/vagrant/spdk_repo/spdk/autopackage.sh:126 -> main(["/home/vagrant/autorun-spdk.conf"])
12:51:57       ...
12:51:57     121 		./configure $config_params --enable-lto
12:51:57     122 	else
12:51:57     123 		# LTO needs a special compiler to work on BSD.
12:51:57     124 		./configure $config_params
12:51:57     125 	fi
12:51:57  => 126 	$MAKE ${MAKEFLAGS}
12:51:57     127 	$MAKE ${MAKEFLAGS} clean
12:51:57     128 	
12:51:57     129 	timing_exit build_release
12:51:57     130 	
12:51:57     131 	timing_finish
12:51:57       ...
12:51:57  
12:51:57  ========== Backtrace end ==========
```
Tested on the nonofficial Jenkins
Full log attached:
[build.log](https://github.com/spdk/spdk/files/9431987/build.log)
`

**Comment by Comphix** [comment] 2022-08-30 01:58
This looks like DPDK (rte vhost crypto) related

```
12:51:57  ../lib/vhost/vhost_crypto.c: In function ‘rte_vhost_crypto_fetch_requests’:
12:51:57  ../lib/vhost/vhost_crypto.c:1178:42: note: at offset [0, 64] into object ‘req’ of size 72
12:51:57   1178 |         struct virtio_crypto_op_data_req req;
12:51:57        |                                          ^~~
12:51:57  ../lib/vhost/vhost_crypto.c:1178:42: note: at offset [1, 72] into object ‘req’ of size 72
```

**Comment by yidong0635** [comment] 2022-08-31 07:44
Related with #2668.

**Comment by wanghailiangx** [comment] 2022-10-10 07:25
> Related with #2668.
@kgodzwox Since a fixing patch has been merged, can you reproduce this issue?

**Comment by KKaras169169** [comment] 2022-10-20 10:51
I have ran SPDK v22.05.x build on Fedora 36 and encountered no issues with DPDK . Closing the issue now.

**Closed by KKaras169169** 2022-10-20 10:51 UTC
Labels: duplicate, enhancement, 3rd party issue
