### ISSUE TITLE
aer hit by SIGABRT during nvme_multi_aen test (nvme_ctrlr_remove_process: Assertion `STAILQ_EMPTY(&proc->active_reqs)' failed)

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2674] opened 2022-08-29 12:57 UTC
https://ci.spdk.io/results/autotest-per-patch/builds/83948/archive/nvme-phy-autotest/build.log

Point of failure:
```
00:04:39.072  START TEST nvme_multi_aen
00:04:39.072  ************************************
00:04:39.072   14:22:59	-- common/autotest_common.sh@1018 -- # xtrace_enable
00:04:39.072   14:22:59	-- common/autotest_common.sh@1019 -- # /var/jenkins/workspace/nvme-phy-autotest/spdk/test/nvme/aer/aer -m -T -i 0 -L log
00:04:39.072  [2022-08-29 14:22:59.584717] Starting SPDK v22.09-pre git sha1 795d18b90 / DPDK 22.03.0 initialization...
00:04:39.072  [2022-08-29 14:22:59.584763] [ DPDK EAL parameters: [2022-08-29 14:22:59.584774] aer [2022-08-29 14:22:59.584781] -c 0x1 [2022-08-29 14:22:59.584787] --log-level=lib.eal:6 [2022-08-29 14:22:59.584793] --log-level=lib.cryptodev:5 [2022-08-29 14:22:59.584800] --log-level=user1:6 [2022-08-29 14:22:59.584806] --base-virtaddr=0x200000000000 [2022-08-29 14:22:59.584812] --match-allocations [2022-08-29 14:22:59.584818] --file-prefix=spdk0 [2022-08-29 14:22:59.584835] --proc-type=auto [2022-08-29 14:22:59.584842] ]
00:04:39.072  [2022-08-29 14:22:59.785871] nvme_ctrlr.c:1613:nvme_ctrlr_disconnect: *NOTICE*: [0000:84:00.0] resetting controller
00:04:39.072  [2022-08-29 14:22:59.785908] nvme_pcie_common.c: 292:nvme_pcie_qpair_insert_pending_admin_request: *ERROR*: The owning process (pid 1404003) is not found. Dropping the request.
00:04:39.072  [2022-08-29 14:22:59.785941] nvme_pcie_common.c: 292:nvme_pcie_qpair_insert_pending_admin_request: *ERROR*: The owning process (pid 1404003) is not found. Dropping the request.
00:04:39.072  [2022-08-29 14:22:59.785959] nvme_pcie_common.c: 292:nvme_pcie_qpair_insert_pending_admin_request: *ERROR*: The owning process (pid 1404003) is not found. Dropping the request.
00:04:39.072  [2022-08-29 14:22:59.785974] nvme_pcie_common.c: 292:nvme_pcie_qpair_insert_pending_admin_request: *ERROR*: The owning process (pid 1404003) is not found. Dropping the request.
00:04:39.072  [2022-08-29 14:22:59.787069] Starting SPDK v22.09-pre git sha1 795d18b90 / DPDK 22.03.0 initialization...
00:04:39.072  [2022-08-29 14:22:59.787136] [ DPDK EAL parameters: [2022-08-29 14:22:59.787148] aer [2022-08-29 14:22:59.787155] -c 0x2 [2022-08-29 14:22:59.787162] --log-level=lib.eal:6 [2022-08-29 14:22:59.787169] --log-level=lib.cryptodev:5 [2022-08-29 14:22:59.787176] --log-level=user1:6 [2022-08-29 14:22:59.787183] --base-virtaddr=0x200000000000 [2022-08-29 14:22:59.787195] --match-allocations [2022-08-29 14:22:59.787204] --file-prefix=spdk0 [2022-08-29 14:22:59.787211] --proc-type=auto [2022-08-29 14:22:59.787217] ]
00:04:39.072  Child process pid: 1404028
00:04:40.007  EAL: Driver cannot detach the device (0000:84:00.0)
00:04:40.007  EAL: Failed to hotplug remove device on secondary
00:04:40.007  EAL: Failed to hotplug remove device
00:04:40.007  aer: nvme_ctrlr.c:3324: nvme_ctrlr_remove_process: Assertion `STAILQ_EMPTY(&proc->active_reqs)' failed.
00:04:41.382  /var/jenkins/workspace/nvme-phy-autotest/spdk/test/common/autotest_common.sh: line 997: 1404027 Aborted                 (core dumped) "$@"
00:04:41.382    14:23:02	-- common/autotest_common.sh@1019 -- # trap - ERR
00:04:41.382    14:23:02	-- common/autotest_common.sh@1019 -- # print_backtrace
00:04:41.382    14:23:02	-- common/autotest_common.sh@1047 -- # [[ ehxBET =~ e ]]
00:04:41.382    14:23:02	-- common/autotest_common.sh@1049 -- # args=('log' '-L' '0' '-i' '-T' '-m' '/var/jenkins/workspace/nvme-phy-autotest/spdk/test/nvme/aer/aer' 'nvme_multi_aen')
00:04:41.382    14:23:02	-- common/autotest_common.sh@1049 -- # local args
00:04:41.382    14:23:02	-- common/autotest_common.sh@1051 -- # xtrace_disable
00:04:41.382    14:23:02	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:04:41.382    14:23:02	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:04:41.382    14:23:02	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:04:41.382    14:23:02	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:04:41.382    14:23:02	-- common/autotest_common.sh@19 -- # set +x
00:04:41.382  ========== Backtrace start: ==========
00:04:41.382  
00:04:41.382  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/common/autotest_common.sh:1019 -> run_test(["nvme_multi_aen"],["/var/jenkins/workspace/nvme-phy-autotest/spdk/test/nvme/aer/aer"],["-m"],["-T"],["-i"],["0"],["-L"],["log"])
00:04:41.382       ...
00:04:41.382     1014		timing_enter $test_name
00:04:41.382     1015		echo "************************************"
00:04:41.382     1016		echo "START TEST $test_name"
00:04:41.382     1017		echo "************************************"
00:04:41.382     1018		xtrace_restore
00:04:41.382     1019		time "$@"
00:04:41.382     1020		xtrace_disable
00:04:41.382     1021		echo "************************************"
00:04:41.382     1022		echo "END TEST $test_name"
00:04:41.382     1023		echo "************************************"
00:04:41.382     1024		timing_exit $test_name
00:04:41.382       ...
00:04:41.382  in test/nvme/nvme.sh:139 -> main([])
00:04:41.382       ...
00:04:41.382     134 	run_test "nvme_overhead" $testdir/overhead/overhead -s 4096 -t 1 -H -i 0
00:04:41.382     135 	run_test "nvme_arbitration" $SPDK_EXAMPLE_DIR/arbitration -t 3 -i 0
00:04:41.382     136 	run_test "nvme_single_aen" $testdir/aer/aer -T -i 0 -L log
00:04:41.382     137 	
00:04:41.382     138 	if [ $(uname) != "FreeBSD" ]; then
00:04:41.382  => 139 		run_test "nvme_multi_aen" $testdir/aer/aer -m -T -i 0 -L log
00:04:41.382     140 		run_test "nvme_startup" $testdir/startup/startup -t 1000000
00:04:41.383     141 		run_test "nvme_multi_secondary" nvme_multi_secondary
00:04:41.383     142 		trap - SIGINT SIGTERM EXIT
00:04:41.383     143 		kill_stub
00:04:41.383     144 	fi
00:04:41.383       ...
00:04:41.383  
00:04:41.383  ========== Backtrace end ==========
```

https://ci.spdk.io/results/autotest-per-patch/builds/83948/archive/nvme-phy-autotest/coredumps/index.html

**Comment by spdkci** [comment] 2022-08-29 14:04
Another instance of this failure. Reported by @xjjx. log: https://ci.spdk.io/public_build/autotest-per-patch_83948.html

**Comment by spdkci** [comment] 2022-08-29 14:04
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_83950.html

**Comment by spdkci** [comment] 2022-08-29 14:32
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_83957.html

**Comment by jimharris** [comment] 2022-08-29 15:40
I've pushed https://review.spdk.io/gerrit/c/spdk/spdk/+/14245 out for review to disable the AEN tests while this gets root caused.

**Comment by curtbruns** [comment] 2022-08-29 19:11
Frustrating - I'm looking at it. Again, only happens with P4510s and only if the stub app is also running.

**Comment by spdkci** [comment] 2022-08-29 23:06
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_83987.html

**Comment by spdkci** [comment] 2022-08-29 23:19
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_83989.html

**Comment by spdkci** [comment] 2022-08-29 23:20
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_83986.html

**Comment by spdkci** [comment] 2022-08-30 06:13
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_83985.html

**Comment by yidong0635** [comment] 2022-09-02 04:22
Is it allowed to run` stub` and` aer `(or multi_secondary(`perf`)) tests to be overlapped with binding  the same core ?

**Comment by jimharris** [comment] 2022-09-02 18:11
> Is it allowed to run` stub` and`aer`(or multi_secondary(`perf`)) tests to be overlapped with binding the same core ?

Yes, this is fine.  See `stub_start` in stub.c, it calls spdk_unaffinitize_thread() at its beginning, which will allow the scheduler to put that thread on another core if a secondary process comes up using the original stub core.

**Comment by yidong0635** [comment] 2022-09-05 02:35
> > Is it allowed to run` stub` and`aer`(or multi_secondary(`perf`)) tests to be overlapped with binding the same core ?
> 
> Yes, this is fine. See `stub_start` in stub.c, it calls spdk_unaffinitize_thread() at its beginning, which will allow the scheduler to put that thread on another core if a secondary process comes up using the original stub core.

Thanks Jim. Got it.

**Comment by yidong0635** [comment] 2022-09-09 01:55
This issue is easy to reproduced locally , and I add this fix:  https://review.spdk.io/gerrit/c/spdk/spdk/+/14433.
It's the app's defects.

**Comment by changpe1** [comment] 2022-09-15 03:33
patch has been merged, so closing it now.

**Closed by changpe1** 2022-09-15 03:33 UTC
Labels: Sighting
