### ISSUE TITLE
NVMe Hotplug example not working with VFIO driver

### ISSUE THREAD

**Issue by sydneyvanda** [spdk/spdk#1816] opened 2021-03-03 23:11 UTC
Seems that I misspoke in previous #1616 , and NVMe hotplug example is still failing with vfio-pci driver in CentOS 7.9 (kernel 3.10.0), CentoOS 8.2 (4.18.0), and openSUSE Leap 15 (kernel 5.3.18). 

## Expected Behavior

NVMe hotplug example script should detect the VFIO device hot removal (with ctrlr in failed state error), and then detect the hot plug event when the PCI bus is rescanned and the device is unbound again from the kernel (and attach the devices back) . 

## Current Behavior

Initial unbind of devices to the vfio-pci driver:
smvanda@wolf-168:~/SPDK> sudo PCI_ALLOWED="0000:84:00.0 0000:83:00.0" ./scripts/setup.sh
0000:83:00.0 (8086 0953): nvme -> vfio-pci
0000:84:00.0 (8086 0953): nvme -> vfio-pci

smvanda@wolf-168:~/SPDK> sudo app/spdk_lspci/spdk_lspci
Starting SPDK v20.01.1 git sha1 b90630a / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: spdk_lspci --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid18328 ]
EAL: No free hugepages reported in hugepages-2048kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
EAL:   using IOMMU type 1 (Type 1)

List of available PCI devices:
0000:83:00.0 (8086 953)
0000:84:00.0 (8086 953)

Start hotplug example
smvanda@wolf-168:~/SPDK> sudo examples/nvme/hotplug/hotplug -n 1 -r 1 -t 100
Starting SPDK v20.01.1 git sha1 b90630a / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: hotplug --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid18443 ]
EAL: No free hugepages reported in hugepages-2048kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
Initializing NVMe Controllers
EAL:   using IOMMU type 1 (Type 1)
Attaching to 0000:83:00.0
Attaching to 0000:84:00.0
Attached to 0000:83:00.0
Attached to 0000:84:00.0
Initialization complete. Starting I/O...
INTEL SSDPE2MD800G4  (CVFT6183002F800HGN  ):          0 I/Os completed (+0)
INTEL SSDPE2MD800G4  (CVFT6183002A800HGN  ):          0 I/Os completed (+0)
INTEL SSDPE2MD800G4  (CVFT6183002F800HGN  ):        240 I/Os completed (+240)
INTEL SSDPE2MD800G4  (CVFT6183002A800HGN  ):        240 I/Os completed (+240)

Emulate a hotremove event:
wolf-168:/home/smvanda/SPDK # echo 1 > /sys/bus/pci/devices/0000\:83\:00.0/remove
(never completes)

Hotplug example just prints the follow error continuously:
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:83:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:83:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:83:00.0/driver!
INTEL SSDPE2MD800G4  (CVFT6183002F800HGN  ):       1448 I/Os completed (+244)
INTEL SSDPE2MD800G4  (CVFT6183002A800HGN  ):       1448 I/Os completed (+244)
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:83:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:83:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:83:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:83:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:83:00.0/driver!
(eventually test will time out)

## Steps to Reproduce

See steps in "Current Behavior"

## Context (Environment including OS version, SPDK version, etc.)

(output above tested on:)
OS: openSUSE Leap 15 (kernel 5.3.18)
SPDK:
commit e7ab45baf7dbbce9685c04e206f13ffd9ed04da0 (HEAD -> master)
Author: Michal Berger <michalx.berger@intel.com>
Date:   Thu Jan 21 12:50:53 2021 +0100

Also tested on the following OS:
CentOS 7.9
CentOS 8.2

**Comment by sydneyvanda** [comment] 2021-03-03 23:16
@NiuYawei @jimharris was looking into this issue again recently and seems it was not resolved by the CentOS 8 kernel version, as it is currently reproducible in CentOS 8.2 (kernel 4.18.0) and also openSUSE Leap 15 (kernel 5.3.18).

**Comment by changpe1** [comment] 2021-03-04 02:17
The VFIO hotplug requires minimum kernel 4.0, I just tested on my 5.4 kernel, it works.

**Comment by yidong0635** [comment] 2021-03-04 04:14
I will try to reproduce this one.

**Comment by sydneyvanda** [comment] 2021-03-04 23:24
I just ran this example on Ubuntu 20.04 (kernel 5.4.0) and I still get the same errors. @changpe1 not sure what I am doing differently. At this point I don't think it is related to the kernel version.

**Comment by yidong0635** [comment] 2021-03-05 00:57
I tried this  hotplug  on several machines yesterday,  can't reproduce this until now. But I will continue to do this today according to your OS.

**Comment by sydneyvanda** [comment] 2021-03-09 22:06
@yidong0635 any updates on this? not sure if you had a chance to test it again or not.

**Comment by yidong0635** [comment] 2021-03-10 01:04
sudo examples/nvme/hotplug/hotplug -n 1 -r 1 -t 100
```
Starting SPDK v20.01.3-pre git sha1 3d1bbb273 / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: hotplug --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid1225433 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
Initializing NVMe Controllers
Attaching to 0000:81:00.0
Attaching to 0000:d8:00.0
Attaching to 0000:da:00.0
Attached to 0000:da:00.0
Attached to 0000:81:00.0
Attached to 0000:d8:00.0
Initialization complete. Starting I/O...
INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):          0 I/Os completed (+0)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):          0 I/Os completed (+0)
INTEL SSDPE2MD800G4  (PHFT639300E9800HGN  ):          0 I/Os completed (+0)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):        252 I/Os completed (+252)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):        252 I/Os completed (+252)
INTEL SSDPE2MD800G4  (PHFT639300E9800HGN  ):        252 I/Os completed (+252)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):        512 I/Os completed (+260)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):        512 I/Os completed (+260)
INTEL SSDPE2MD800G4  (PHFT639300E9800HGN  ):        512 I/Os completed (+260)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):        768 I/Os completed (+256)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):        768 I/Os completed (+256)
INTEL SSDPE2MD800G4  (PHFT639300E9800HGN  ):        768 I/Os completed (+256)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):       1024 I/Os completed (+256)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):       1024 I/Os completed (+256)
INTEL SSDPE2MD800G4  (PHFT639300E9800HGN  ):       1024 I/Os completed (+256)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):       1284 I/Os completed (+260)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):       1284 I/Os completed (+260)
INTEL SSDPE2MD800G4  (PHFT639300E9800HGN  ):       1284 I/Os completed (+260)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):       1540 I/Os completed (+256)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):       1540 I/Os completed (+256)
INTEL SSDPE2MD800G4  (PHFT639300E9800HGN  ):       1540 I/Os completed (+256)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):       1796 I/Os completed (+256)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):       1796 I/Os completed (+256)
INTEL SSDPE2MD800G4  (PHFT639300E9800HGN  ):       1796 I/Os completed (+256)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):       2056 I/Os completed (+260)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):       2056 I/Os completed (+260)
INTEL SSDPE2MD800G4  (PHFT639300E9800HGN  ):       2056 I/Os completed (+260)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):       2312 I/Os completed (+256)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):       2312 I/Os completed (+256)
INTEL SSDPE2MD800G4  (PHFT639300E9800HGN  ):       2312 I/Os completed (+256)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):       2572 I/Os completed (+260)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):       2572 I/Os completed (+260)
INTEL SSDPE2MD800G4  (PHFT639300E9800HGN  ):       2572 I/Os completed (+260)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):       2828 I/Os completed (+256)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):       2828 I/Os completed (+256)
INTEL SSDPE2MD800G4  (PHFT639300E9800HGN  ):       2828 I/Os completed (+256)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):       3088 I/Os completed (+260)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):       3088 I/Os completed (+260)
INTEL SSDPE2MD800G4  (PHFT639300E9800HGN  ):       3088 I/Os completed (+260)

EAL: eal_parse_sysfs_value(): cannot open sysfs value /sys/bus/pci/devices/0000:d8:00.0/vendor
EAL: Scan for (pci) bus failed.
nvme_ctrlr.c: 699:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:d8:00.0 in failed state.
Controller removed: INTEL SSDPE2MD800G4  (PHFT639300E9800HGN  )
nvme_ctrlr.c: 699:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:d8:00.0 in failed state.
Controller removed: INTEL SSDPE2MD800G4  (PHFT639300E9800HGN  )
nvme_pcie.c:1389:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
nvme_qpair.c: 133:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:891 nsid:1 lba:26624 len:8
nvme_qpair.c: 304:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:1 cid:891 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
nvme_pcie.c:1389:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
nvme_qpair.c: 133:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:892 nsid:1 lba:26632 len:8
nvme_qpair.c: 304:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:1 cid:892 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
nvme_pcie.c:1389:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
nvme_qpair.c: 133:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:894 nsid:1 lba:26640 len:8
nvme_qpair.c: 304:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:1 cid:894 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
nvme_pcie.c:1389:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
nvme_qpair.c: 133:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:895 nsid:1 lba:26648 len:8
nvme_qpair.c: 304:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:1 cid:895 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
nvme_ctrlr.c: 699:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:d8:00.0 in failed state.
Controller removed: INTEL SSDPE2MD800G4  (PHFT639300E9800HGN  )
unregister_dev: INTEL SSDPE2MD800G4  (PHFT639300E9800HGN  )
nvme_pcie.c:1389:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
nvme_qpair.c: 116:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) sqid:0 cid:94 nsid:0 cdw10:00000000 cdw11:00000000
nvme_qpair.c: 304:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:0 cid:94 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
nvme_ctrlr.c:1913:nvme_ctrlr_async_event_cb: *ERROR*: resubmitting AER failed!
nvme_pcie.c:1389:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
nvme_qpair.c: 116:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) sqid:0 cid:93 nsid:0 cdw10:00000000 cdw11:00000000
nvme_qpair.c: 304:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:0 cid:93 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
nvme_ctrlr.c:1913:nvme_ctrlr_async_event_cb: *ERROR*: resubmitting AER failed!
nvme_pcie.c:1389:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
nvme_qpair.c: 116:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) sqid:0 cid:92 nsid:0 cdw10:00000000 cdw11:00000000
nvme_qpair.c: 304:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:0 cid:92 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
nvme_ctrlr.c:1913:nvme_ctrlr_async_event_cb: *ERROR*: resubmitting AER failed!
nvme_pcie.c:1389:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
nvme_qpair.c: 116:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) sqid:0 cid:91 nsid:0 cdw10:00000000 cdw11:00000000
nvme_qpair.c: 304:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:0 cid:91 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
nvme_ctrlr.c:1913:nvme_ctrlr_async_event_cb: *ERROR*: resubmitting AER failed!
INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):       3344 I/Os completed (+256)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):       3344 I/Os completed (+256)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):       3604 I/Os completed (+260)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):       3604 I/Os completed (+260)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):       3860 I/Os completed (+256)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):       3860 I/Os completed (+256)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):       4120 I/Os completed (+260)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):       4120 I/Os completed (+260)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):       4376 I/Os completed (+256)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):       4376 I/Os completed (+256)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):       4636 I/Os completed (+260)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):       4636 I/Os completed (+260)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):       4896 I/Os completed (+260)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):       4896 I/Os completed (+260)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):       5156 I/Os completed (+260)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):       5156 I/Os completed (+260)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):       5412 I/Os completed (+256)
INTEL SSDPED1K375GA  (PHKS750500KV375AGN  ):       5412 I/Os completed (+256)

INTEL SSDPEDKE020T7  (PHLE807000XQ2P0IGN  ):       5672 I/Os completed (+260)

```
This is the result on Ubuntu20.04  when doing "`echo 1 > /sys/bus/pci/devices/0000:d8:00.0/remove`"
and and tried these with mixed operations. nothing abnormal can be found.

**Comment by yidong0635** [comment] 2021-03-15 06:22
@sydneyvanda  
 I can only reproduce this one
 `echo 1 > /sys/bus/pci/devices/0000:d8:00.0/remove`  has no response  while doing 
`sudo build/examples/hotplug  -n 1 -r 1 -t 100`  on some server, 
but still can't see below kind of error. 
```
"EAL: Unexpected device scan at /sys/bus/pci/devices/0000:83:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:83:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:83:00.0/driver! " 
```

**Comment by sydneyvanda** [comment] 2021-03-17 01:02
@yidong0635 ok here is what I found so far in doing some more testing:

Ubuntu 20.04:
       SPDK v20.01.1 = **FAIL** (this was the version I was using when filing the ticket, but seems to work in version 20.01.3)
       SPDK v20.01.3 = PASS
       SPDK v20.04.2-pre = PASS

CentOS 8.2:
        SPDK v20.01.3-pre = PASS
        SPDK v20.04.2-pre = PASS
        SPDK v21.01 = **FAIL** (hangs after device removal, seems there might be a regression with VFIO hold on the device?)

CentOS 7:
       SPDK v20.04.2-pre = **FAIL**

**Comment by jimharris** [comment] 2021-03-17 14:37
Hi @sydneyvanda,

Can you confirm that these PASS/FAIL results are 100% reproducible?

If so, could you do some git bisects to figure out when these switch between PASS and FAIL?

1) on Ubuntu 20.04 w/ SPDK v20.01.x branch, bisect between v20.01.1 and v20.01.3
2) on CentOS 8.2 w/ master, bisect between 597a7d08 (v20.04-rc1) and 312a9d6 (v21.01-rc1) - first make sure that v20.04-rc1 passes and v21.01-rc1 fails

Thanks,

Jim

**Comment by sydneyvanda** [comment] 2021-03-19 00:50
@jimharris ok I did some testing on CentOS 8.2 today:
- I confirmed that tag v20.04-rc1 passes
- I confirmed that tag v21.01-rc1 fails
- I found the conflicting commit to be the following: https://github.com/spdk/spdk/commit/8f7d9ec2f4775c5627265c3c5dcce96397598c8f
The issue that happens with the hotplug example is that when trying to remove a device, the command just hangs and does not complete until the hotplug example timesout or is terminated. Seems there is a hold on the VFIO device or something that will not allow the pci bus removal when the hotplug example is running.

I will continue investigation on Ubuntu 20.04, just wanted to give an update so far.

**Comment by jimharris** [comment] 2021-03-22 21:56
Thanks @sydneyvanda.

@Maciej-Szwed, the patch referenced above is "env/dpdk: Use the DPDK device count for IOMMU mapping".  Could you try to reproduce this issue in your environment?

**Comment by Maciej-Szwed** [comment] 2021-05-14 08:36
I run this using Ubuntu 20.10 and kernel 5.8.0-25 and I was unable to reproduce this on v21.01-rc1. I will try on Fedora 32 also.

**Comment by Maciej-Szwed** [comment] 2021-05-14 08:49
I was able to reproduce this with Fedora 32 and kernel 5.7.17-200. There was one difference from original issue description - I didn't get any error  - only PCIe remove command never completes.

**Comment by Maciej-Szwed** [comment] 2021-05-14 08:56
Everything works correctly when this line is removed:
lib/env_dpdk/memory.c:1377:             rc = rte_dev_event_monitor_start();
It looks like exactly same issue as #1785

**Comment by jimharris** [comment] 2021-05-14 15:28
Thanks @Maciej-Szwed!

So in this case, removing rte_dev_event_monitor_start() fixes this issue, but in #1785 the proposed patch adds a second call to rte_dev_event_monitor_start().  Am I reading that correctly?

**Comment by Maciej-Szwed** [comment] 2021-05-14 16:56
In #1785 I added rte_dev_event_monitor_start() before it was added with patch "env/dpdk: Use the DPDK device count for IOMMU mapping" and that caused failures on CI. I will investigate that further next week and let know know why running event monitor causes issues.

**Comment by Maciej-Szwed** [comment] 2021-05-25 13:04
I found the root cause:
rte_dev_event_monitor_start() creates and binds the same socket as we try to create and bind later in spdk_pci_event_listen() and bind() call fails there. My suggestion would be to remove spdk_pci_event_listen() function in SPDK and relay on DPDK dev event callback mechanism. That will require some work to be done (but it will simplify SPDK code).
We can probably change label of this issue to 'enhancement' as faulty patch was reverted, but we still should fix that possibly with my suggestion mentioned above.

**Comment by jimharris** [comment] 2021-05-25 14:57
Thanks for this update @Maciej-Szwed.  Just to confirm, you are working on the changes to remove spdk_pci_event_listen() and solely rely on the DPDK dev event callback mechanism?

**Comment by Maciej-Szwed** [comment] 2021-05-25 15:31
Yes, that's the idea I want to try. Are you OK with such approach?

**Comment by jimharris** [comment] 2021-05-25 15:33
It seems reasonable to me.

**Comment by Maciej-Szwed** [comment] 2021-06-21 07:53
I started working on fix. You can track work in this patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/8346

**Comment by Maciej-Szwed** [comment] 2021-07-07 22:06
Patch has been tested successfully and it's ready for review: https://review.spdk.io/gerrit/c/spdk/spdk/+/8346

**Comment by changpe1** [comment] 2021-09-16 02:03
Combine this issue with https://github.com/spdk/spdk/issues/2086, to address the two issues together, I think reverting commit 8f7d9ec is the correct way.

**Comment by tomzawadzki** [comment] 2021-10-05 10:44
The revert patch 7fed70f1bdcd491738211c726542446795606ec6 was merged, this issue can be closed.

**Closed by tomzawadzki** 2021-10-05 10:44 UTC
Labels: bug, Medium
