### ISSUE TITLE
[nvmf_multipath] *ERROR*: CQ transport error -6

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2152] opened 2021-09-08 17:34 UTC
First sign of failure that I can see:

00:09:39.323  EAL: No free 2048 kB hugepages reported on node 1
00:09:39.323  EAL: No available 1048576 kB hugepages reported
00:09:39.323  TELEMETRY: No legacy callbacks, legacy socket not created
00:09:39.323  [2021-09-08 19:18:38.626104] app.c: 541:spdk_app_start: *NOTICE*: Total cores available: 1
00:09:39.323  [2021-09-08 19:18:39.119277] reactor.c: 939:reactor_run: *NOTICE*: Reactor started on core 0
00:09:39.323  [2021-09-08 19:18:39.119445] accel_engine.c:1016:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:09:39.323  Running I/O for 10 seconds...
00:09:39.323  [2021-09-08 19:18:42.394100] nvme_qpair.c: 730:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 0
00:09:39.323  [2021-09-08 19:18:42.394190] nvme_ctrlr.c:1008:nvme_ctrlr_fail: *ERROR*: [nqn.2016-06.io.spdk:cnode1] in failed state.
00:09:39.323  [2021-09-08 19:18:42.394210] bdev_nvme.c: 965:bdev_nvme_failover_start: *NOTICE*: Start failover from 192.168.100.8:4420 to 192.168.100.8:4421
00:09:39.323  [2021-09-08 19:18:42.394224] nvme_ctrlr.c:1002:nvme_ctrlr_fail: *NOTICE*: [nqn.2016-06.io.spdk:cnode1] already in failed state
00:09:39.323  [2021-09-08 19:18:43.454020] bdev_nvme.c:3577:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
00:09:39.323  [2021-09-08 19:18:43.454088] bdev_nvme.c:3577:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
00:09:39.323  [2021-09-08 19:18:43.454136] bdev_nvme.c:3577:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
00:09:39.323  [2021-09-08 19:18:43.454181] bdev_nvme.c:3577:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
00:09:39.323  [2021-09-08 19:18:43.454226] bdev_nvme.c:3577:bdev_nvme_writev: *ERROR*: writev failed: rc = -6

**Comment by spdkci** [comment] 2021-09-08 17:35
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_57928.html

**Comment by jimharris** [comment] 2021-09-08 18:00
Looks like a duplicate of #2128.

**Closed by jimharris** 2021-09-08 18:00 UTC
Labels: Intermittent Failure
