### ISSUE TITLE
bdev_aio_group_poll lost events

### ISSUE THREAD

**Issue by benqwu** [spdk/spdk#626] opened 2019-01-28 09:09 UTC
## Expected Behavior

in bdev_aio_group_poll(), all aio events should be got.

## Current Behavior

I use 2 lcore and submit ios to the same aio bdev concurrently.
SPDK create 2 bdev_aio_io_channel(ch1 and ch2) for each lcore. 
Sometimes I found that io stream stopped, and ch1->io_inflight is not 0, and rc = epoll_wait is always 0, so it never call io_getevents again, which is the same to ch2.

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)

spdk 18.10

**Comment by benqwu** [comment] 2019-01-28 09:39
@optimistyzy CC

**Comment by jimharris** [comment] 2019-01-28 19:32
Hi @benqwu,

Can you provide more specifics on steps to reproduce?

Thanks,

-Jim

**Comment by optimistyzy** [comment] 2019-01-29 04:12
@benqwu  This is interesting. I can get the points on what you describe. Could you have more details for reproducing this issue

**Comment by benqwu** [comment] 2019-01-30 02:44
Hi @jimharris  @optimistyzy 
I developed an app on the upper level of bdev layer and  did not modify SPDK source code.
I used vdbench to generate IO streaming.

My simplified code is here:

1) init:
`struct spdk_bdev *bdev;`
`struct spdk_bdev_desc *desc;`
`struct spdk_io_channel *bdev_chs[2] = {};`
`bdev = spdk_bdev_get_by_name(name);`
`spdk_bdev_open(bdev, true, NULL, NULL, &desc);`

2) submit io:
`if (bdev_chs[rte_lcore_id()] == NULL) {`
`    bdev_chs[rte_lcore_id()] = spdk_bdev_get_io_channel(desc);`
`}`
`rc = spdk_bdev_read(desc, bdev_chs[rte_lcore_id()], buf, offset, len, cb, cb_arg);`


When IO streaming stopped, I dump some information of IO channel.
(gdb) p *bdev_chs[0]
$2 = {thread = 0x607000000480, dev = 0x607000000790, ref = 2, destroy_ref = 0, tailq = {tqe_next = 0x6080000002a0, tqe_prev = 0x6070000004a8}, destroy_cb = 0x7fe480 <spdk_bdev_channel_destroy>}
(gdb) p bdev_chs[0]
$3 = (struct spdk_io_channel *) 0x60e0000004a0
(gdb) p *(struct bdev_aio_io_channel *)(0x60e0000004a0 + 8)
$4 = {io_ctx = 0x607000000790, io_inflight = 2, group_ch = 0x6080000002a0, link = {tqe_next = 0x6070000004a8, tqe_prev = 0x7fe480 <spdk_bdev_channel_destroy>}, efd = 80}
(gdb) p *bdev_chs[1]
$5 = {thread = 0x607000003820, dev = 0x607000000790, ref = 1, destroy_ref = 0, tailq = {tqe_next = 0x608000006da0, tqe_prev = 0x60d000007ca8}, destroy_cb = 0x7fe480 <spdk_bdev_channel_destroy>}
(gdb) p bdev_chs[1]
$6 = (struct spdk_io_channel *) 0x60e00000ad80
(gdb) p *(struct bdev_aio_io_channel *)(0x60e00000ad80 + 8)
$7 = {io_ctx = 0x607000000790, io_inflight = 1, group_ch = 0x608000006da0, link = {tqe_next = 0x60d000007ca8, tqe_prev = 0x7fe480 <spdk_bdev_channel_destroy>}, efd = 80}

And I find some interesting things:
1) Single core has also problems. 
2) In bdev_aio_create_cb(), I modified code like this:
`- epevent.events = EPOLLIN | EPOLLET;`
`+ epevent.events = EPOLLIN;`
The problem seems to have disappeared.

Thanks~

**Comment by benqwu** [comment] 2019-01-30 03:06
Excuse me, I have to confirm the phenomenon of the problem, maybe the previous description is wrong.

**Comment by optimistyzy** [comment] 2019-01-30 04:46
@benqwu  Can you have a look at the **bdevperf** program (located in spdk/test/bdev/bdevperf/)? Which is an example to demonstrate how to use bdev layer to construct you own app. I tested with two cores, it seems that it works all correct.  

I am afraid that you did not use spdk's application framework, we need to call spdk_app_start, and the bdev_aio_group_poll  is registered as a poller, which will be scheduled by the reactor on each SPDK thread. So mostly likely, it is a wrong usage of SPDK code.

The following shows my command: 

./test/bdev/bdevperf/bdevperf -c bdev.conf -q 128 -o 4096 -t 10 -w randrw -M 10 -m 0x3
The following shows the configuration file
---------------------------

[AIO]
  AIO /root/tmp1 AIO0 2048
  AIO /root/tmp2 AIO1 2048

-----------------------------
For /root/tmp1 and /root/tmp2  you can create with dd command.

**Comment by benqwu** [comment] 2019-01-31 08:10
@optimistyzy  thx ~ I will try again later.

**Comment by jimharris** [comment] 2019-02-22 20:24
Hi @benqwu - any update on this issue?  Or should we close it?

**Comment by jimharris** [comment] 2019-03-01 22:28
Hi @benqwu - I'm going to close this issue since it sounds like maybe you're investigating the problem some more.  If your analysis indicates there's still a problem with SPDK, please feel free to re-open this issue, or file a new one.  Thanks!

**Comment by benqwu** [comment] 2019-03-11 09:49
@optimistyzy 
I am sorry. I have not tried to reproduce the problem on bdevperf, worried that it is difficult to occur.

I collected some information these days on my APP.
When the problem occured, I found two things:

- io_inflight is always 42.

> (gdb) p *(struct spdk_bdev_channel *)(0x60e000007580+48)
$9 = {bdev = 0x614000000050, channel = 0x6080000040a0, shared_resource = 0x607000005d50, stat = {bytes_read = 4702900224, num_read_ops = 1137183, bytes_written = 31970234368, 
    num_write_ops = 7775307, read_latency_ticks = 707541540023615, write_latency_ticks = 11097608121121578, ticks_rate = 2300000000}, io_outstanding = 42, queued_resets = {tqh_first = 0x0, 
    tqh_last = 0x60e000007608}, flags = 0}
(gdb) p *(struct bdev_aio_io_channel *)(0x6080000040a0+48)     
$10 = {io_ctx = 0x7ffff7e6f000, io_inflight = 42, group_ch = 0x606000003c20, link = {tqe_next = 0x0, tqe_prev = 0x0}, efd = 24}

- bdev_aio_group_poll is always running and rc is always 0.

> rc = epoll_wait(group_ch->epfd, epevents, MAX_EVENTS_PER_POLL, 0);


I am familiar with SPDK code, So I think that it should not be a configuration error.
Please help me~

**Comment by benqwu** [comment] 2019-03-11 09:50
@jimharris 
Please help reopen this issue.

**Comment by benqwu** [comment] 2019-03-11 09:54
@optimistyzy
I use spdk_bdev_read() to read SSD. No changes to SPDK bdev layer.

**Comment by benqwu** [comment] 2019-03-12 08:29
@benlwalker 

Is there a problem combining epoll_wait and io_getevents?
I found that this patch remove epoll_wait.
https://github.com/spdk/spdk/commit/7f534fca6ac7392f2c9e348be4cce02496dfd6b4#diff-e1d63411870fd5be37f7782a43dc0e0c

**Comment by darsto** [comment] 2019-03-12 15:10
Bug scrub: @benqwu The above patch was just an optimization. The AIO bdev was greatly refactored in the latest SPDK. Could you recheck the current master?

**Comment by benqwu** [comment] 2019-03-15 01:15
> Bug scrub: @benqwu The above patch was just an optimization. The AIO bdev was greatly refactored in the latest SPDK. Could you recheck the current master?

Thanks. My APP is developed on SPDK-18.10, so I may not use the latest code to experiment immediately.

**Comment by optimistyzy** [comment] 2019-03-16 00:29
The patch provided by Ben is correct, it will use group polling later. But
definitely, if you use the old one, you still need this if the group
polling is not enabled


在 2019年3月15日星期五，benqwu <notifications@github.com> 写道：

**Comment by darsto** [comment] 2019-03-26 15:21
@benqwu As a first step, could you provide steps to reproduce this using existing SPDK tools? If that's impossible, could you provide an exact application code to reproduce it?

**Comment by benlwalker** [comment] 2019-08-22 04:29
The aio bdev has been rewritten to use a different polling strategy since this bug was filed. If this problem still occurs on master, please reopen the issue.

**Closed by benlwalker** 2019-08-22 04:29 UTC
Labels: Low, Waiting on Submitter, bug
