### ISSUE TITLE
spdk compiles with warnings and error

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1650] opened 2020-10-26 04:19 UTC
# Issue
thread.c: In function ‘msg_queue_run_batch’:
thread.c:523:3: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
   read(thread->msg_fd, &notify, sizeof(notify));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
thread.c:528:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
   write(thread->msg_fd, &notify, sizeof(notify));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
thread.c: In function ‘spdk_thread_send_msg’:
thread.c:920:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
   write(thread->msg_fd, &notify, sizeof(notify));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
thread.c: In function ‘spdk_thread_send_critical_msg’:
thread.c:936:4: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
    write(thread->msg_fd, &notify, sizeof(notify));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  LIB libspdk_conf.a
  LIB libspdk_json.a
  CC lib/jsonrpc/jsonrpc_server.o
  CC lib/jsonrpc/jsonrpc_server_tcp.o
  CC lib/jsonrpc/jsonrpc_client.o
  CC lib/jsonrpc/jsonrpc_client_tcp.o
  LIB libspdk_thread.a
  CC lib/virtio/virtio.o
  CC lib/virtio/virtio_pci.o
  CC lib/virtio/virtio_user.o
  CC lib/virtio/vhost_user.o
  CC lib/blob/blobstore.o
  CC lib/blob/request.o
  CC lib/blob/zeroes.o
  CC lib/blob/blob_bs_dev.o
  CC lib/accel/accel_engine.o
  LIB libspdk_jsonrpc.a
  CC lib/rpc/rpc.o
  LIB libspdk_rpc.a
  LIB libspdk_virtio.a
  LIB libspdk_accel.a
  CC lib/trace/trace.o
  CC lib/trace/trace_rpc.o
  CC lib/trace/trace_flags.o
  CC lib/sock/sock.o
  CC lib/sock/sock_rpc.o
  CC lib/net/interface.o
  CC lib/net/net_rpc.o
  CC lib/notify/notify.o
  CC lib/notify/notify_rpc.o
  LIB libspdk_notify.a
  LIB libspdk_trace.a
  CC lib/bdev/bdev.o
  CC lib/bdev/bdev_rpc.o
  CC lib/bdev/bdev_zone.o
  CC lib/bdev/part.o
  CC lib/bdev/scsi_nvme.o
  CC lib/event/app.o
  CC lib/event/reactor.o
  CC lib/event/subsystem.o
  CC lib/event/rpc.o
  CC lib/event/json_config.o
  CC lib/event/log_rpc.o
  CC lib/event/subsystem_rpc.o
  CC lib/event/app_rpc.o
  CC lib/event/scheduler_static.o
  CC lib/event/dpdk_governor.o
  CC lib/event/gscheduler.o
  LIB libspdk_net.a
dpdk_governor.c:40:10: fatal error: rte_power.h: No such file or directory
 #include <rte_power.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [/home/yidong/spdk/mk/spdk.common.mk:374: dpdk_governor.o] Error 1
make[2]: *** Waiting for unfinished jobs....
  LIB libspdk_sock.a

# Step 
./configure
make -j10

## Context (Environment including OS version, SPDK version, etc.)

5.0.16-100.fc28.x86_64 
commit: 214b9847d0fb37067f754f7481c4277c45525b8d.

**Comment by optimistyzy** [comment] 2020-10-26 05:18
@dong-liuliu It is brought by your new interrupt patch. Can you check this?

**Comment by dong-liuliu** [comment] 2020-10-26 08:16
Ack.
Thanks for you notice, @yidong0635 & @optimistyzy 
Fixed warnings caused by thread's interrupt code at https://review.spdk.io/gerrit/c/spdk/spdk/+/4869

**Comment by yidong0635** [comment] 2020-10-26 08:33
thanks  xiaodong, fixes your warnings.

@Maciej-Szwed  there's  including file error. why not put it into lib/env_dpdk ?
```
 dpdk_governor.c:40:10: fatal error: rte_power.h: No such file or directory
#include <rte_power.h>
^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [/home/yidong/spdk/mk/spdk.common.mk:374: dpdk_governor.o] Error 1
make[2]: *** Waiting for unfinished jobs....
LIB libspdk_sock.a

```

**Comment by jimharris** [comment] 2020-10-26 21:54
Patch has been merged.

@yidong0635 - I think you forgot to update your DPDK submodule and then make clean and rebuild DPDK - that will get you the rte_power.h header file installed correctly

Closing issue, but @yidong0635 please confirm that updating the DPDK submodule fixed the complication error

**Closed by jimharris** 2020-10-26 21:54 UTC
Labels: Sighting

**Comment by yidong0635** [comment] 2020-10-27 02:02
@jimharris  oh, I forgot to `git submodule update --init`.  Verifed, every thing is ok now,
