### ISSUE TITLE
[build_rpm_from_gen_spec] Cancelling nested steps due to timeout

### ISSUE THREAD

**Issue by apaszkie** [spdk/spdk#3222] opened 2023-12-22 13:00 UTC
```
00:08:41.661   07:51:42	-- rpm/rpm.sh@27 -- # sudo rpm -i /root/rpmbuild/RPMS/x86_64/spdk-devel-test_gen_spec-1.x86_64.rpm /root/rpmbuild/RPMS/x86_64/spdk-dpdk-libs-test_gen_spec-1.x86_64.rpm /root/rpmbuild/RPMS/x86_64/spdk-libs-test_gen_spec-1.x86_64.rpm /root/rpmbuild/RPMS/x86_64/spdk-test_gen_spec-1.x86_64.rpm
00:13:15.468  Cancelling nested steps due to timeout
00:13:15.472  Sending interrupt signal to process
00:13:18.176  Terminated
00:13:21.455  Terminated
00:13:21.455    07:56:21	-- common/autotest_common.sh@1088 -- # trap - ERR
00:13:21.455    07:56:21	-- common/autotest_common.sh@1088 -- # print_backtrace
00:13:21.455    07:56:21	-- common/autotest_common.sh@1116 -- # [[ ehxBET =~ e ]]
00:13:21.455    07:56:21	-- common/autotest_common.sh@1118 -- # args=('/var/jenkins/workspace/packaging-docker-autotest/spdk/test/packaging/rpm/rpm.sh' 'rpm_packaging')
00:13:21.455    07:56:21	-- common/autotest_common.sh@1118 -- # local args
00:13:21.455    07:56:21	-- common/autotest_common.sh@1120 -- # xtrace_disable
00:13:21.455    07:56:21	-- common/autotest_common.sh@10 -- # set +x
00:13:21.455  ========== Backtrace start: ==========
00:13:21.455  
00:13:21.456  in /var/jenkins/workspace/packaging-docker-autotest/spdk/test/common/autotest_common.sh:1088 -> run_test(["rpm_packaging"],["/var/jenkins/workspace/packaging-docker-autotest/spdk/test/packaging/rpm/rpm.sh"])
00:13:21.456       ...
00:13:21.456     1083		timing_enter $test_name
00:13:21.456     1084		echo "************************************"
00:13:21.456     1085		echo "START TEST $test_name"
00:13:21.456     1086		echo "************************************"
00:13:21.456     1087		xtrace_restore
00:13:21.456     1088		time "$@"
00:13:21.456     1089		xtrace_disable
00:13:21.456     1090		echo "************************************"
00:13:21.456     1091		echo "END TEST $test_name"
00:13:21.456     1092		echo "************************************"
00:13:21.456     1093		timing_exit $test_name
00:13:21.456       ...
00:13:21.456  in /var/jenkins/workspace/packaging-docker-autotest/spdk/test/packaging/packaging.sh:11 -> main([])
00:13:21.456       ...
00:13:21.456     6   	
00:13:21.456     7   	testdir=$(readlink -f "$(dirname "$0")")
00:13:21.456     8   	rootdir=$(readlink -f "$testdir/../../")
00:13:21.456     9   	source "$rootdir/test/common/autotest_common.sh"
00:13:21.456     10  	
00:13:21.456  => 11  	run_test "rpm_packaging" "$testdir/rpm/rpm.sh"
00:13:21.456       ...
00:13:21.456  
00:13:21.456  ========== Backtrace end ==========
```

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/114380/archive/packaging-docker-autotest_9952/build.log

**Comment by spdkci** [comment] 2023-12-22 13:01
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_114380.html

**Comment by spdkci** [comment] 2023-12-22 13:03
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_114381.html

**Comment by spdkci** [comment] 2023-12-22 13:05
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_114385.html

**Comment by apaszkie** [comment] 2023-12-22 13:10
> Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_114385.html

This one is similar but instead of timeout there is an error:
```
00:12:31.967  meson.build:4:0: ERROR: Compiler cc cannot compile programs.
00:12:31.967  
00:12:31.967  A full log can be found at /root/rpmbuild/BUILD/spdk-test_gen_spec/dpdk/build-tmp/meson-logs/meson-log.txt
00:12:31.967  make[1]: *** [Makefile:212: /root/rpmbuild/BUILD/spdk-test_gen_spec/dpdk/build-tmp] Error 1
00:12:31.967  make: *** [/root/rpmbuild/BUILD/spdk-test_gen_spec/mk/spdk.subdirs.mk:16: dpdkbuild] Error 2
00:12:31.967  error: Bad exit status from /var/tmp/rpm-tmp.yYKFOn (%prep)
00:12:31.967  
00:12:31.967  RPM build errors:
00:12:31.967      Bad exit status from /var/tmp/rpm-tmp.yYKFOn (%prep)
```

**Comment by mikeBashStuff** [comment] 2023-12-22 13:13
Some bottleneck on the affected workers most likely. The only thing to do here is to increase job's timeout (which is quite optimistic right now as it's set to just 10m). Will increase it to 30m, since this job is already part of the main test phase.

**Comment by mikeBashStuff** [comment] 2023-12-22 13:16
> > Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_114385.html
> 
> This one is similar but instead of timeout there is an error:
> 
> ```
> 00:12:31.967  meson.build:4:0: ERROR: Compiler cc cannot compile programs.
> 00:12:31.967  
> 00:12:31.967  A full log can be found at /root/rpmbuild/BUILD/spdk-test_gen_spec/dpdk/build-tmp/meson-logs/meson-log.txt
> 00:12:31.967  make[1]: *** [Makefile:212: /root/rpmbuild/BUILD/spdk-test_gen_spec/dpdk/build-tmp] Error 1
> 00:12:31.967  make: *** [/root/rpmbuild/BUILD/spdk-test_gen_spec/mk/spdk.subdirs.mk:16: dpdkbuild] Error 2
> 00:12:31.967  error: Bad exit status from /var/tmp/rpm-tmp.yYKFOn (%prep)
> 00:12:31.967  
> 00:12:31.967  RPM build errors:
> 00:12:31.967      Bad exit status from /var/tmp/rpm-tmp.yYKFOn (%prep)
> ```

This error was caused by a `SIGTERM` that jenkins sent out due to the timeout (you can see proper message about canceling job's steps above that error).

**Comment by mikeBashStuff** [comment] 2024-01-05 13:20
No new reports were submitted since the timeout was increased so will go ahead and close this issue for now.

**Closed by mikeBashStuff** 2024-01-05 13:20 UTC
Labels: Intermittent Failure
