### ISSUE TITLE
Iscsi_autotest always fail to read pdu

### ISSUE THREAD

**Issue by ChenBo2333** [spdk/spdk#845] opened 2019-07-02 07:04 UTC
Lots of build logs of  iscsi_autotest report the same error message:
"iscsi_conn_handle_incoming_pdus: *ERROR*: Failed to read pdu, error=-1"

## Expected Behavior
Succeed to read pdu

## Current Behavior
Failed to read pdu

## Possible Solution
N/A

## Steps to Reproduce
View build log on iscsi_autotest server,
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/36365/archive/iscsi_autotest/build.log (search "pdu")

## Context (Environment including OS version, SPDK version, etc.)
Save as above.

**Comment by changpe1** [comment] 2019-07-02 07:15
It's not a bug, but we can improve the log message to make it more reasonable.

**Comment by changpe1** [comment] 2019-07-02 08:13
https://review.gerrithub.io/c/spdk/spdk/+/460110, I've posted a patch to fix the issue.

**Comment by changpe1** [comment] 2019-07-02 22:57
Patch was merged, I'm going to close this issue for now.

**Closed by changpe1** 2019-07-02 22:57 UTC
