### ISSUE TITLE
iscsi_tgt: conn.c:313: spdk_iscsi_conn_free_pdu: Assertion `conn->data_in_cnt > 0' failed.

### ISSUE THREAD

**Issue by benlwalker** [spdk/spdk#1074] opened 2019-11-21 20:18 UTC
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/50435/archive/RBD_autotest/failed_test.log

**Comment by spdkci** [comment] 2019-11-21 20:19
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50435.html

**Comment by shuhei-matsumoto** [comment] 2019-11-22 04:11
This occurred in the calsoft test suite and not related with LUN hotplug.
I'm investigating this but don't know much about ERL > 0 and so this may be difficult.

**Comment by tomzawadzki** [comment] 2019-11-25 12:22
For some reason the DPDK nightly jobs seem to trigger it pretty often:
[SPDK master vs DPDK 19.08](https://dqtibwqq6s6ux.cloudfront.net/results/autotest-spdk-master-vs-dpdk-19-08/builds/489/archive/RBD_autotest_nightly/build.log)
[SPDK master vs DPDK master](https://dqtibwqq6s6ux.cloudfront.net/results/autotest-spdk-master-vs-dpdk-master/builds/729/archive/RBD_autotest_nightly/build.log)

On job running SPDK 19.10 vs DPDK master, I've not seen it. This failure might have been introduced recently.

**Comment by shuhei-matsumoto** [comment] 2019-11-25 13:06
Hi @tomzawadzki 

Ziye kindly let me know the root cause and is creating the fix. 

Reverting https://github.com/spdk/spdk/commit/6e4e85dcef91e6793b554a5d15c72ba93e56a4ab#diff-a51387bcf4a14095dce0764100be7023 will reduce the frequency and Ziye’s future patch will fix the issue completely. So this will be fixed sooner or later

This was caused by my lack of knowledge. Sorry for that

**Comment by optimistyzy** [comment] 2019-11-25 13:14
@benlwalker @shuhei-matsumoto  my following series (the last one is:  https://review.gerrithub.io/c/spdk/spdk/+/475657)  can solve this issue. I also test with the calsoft several time (with --enable-debug compilation) and does not trigger this issue on my local platform. 
It makes the deferred PDU handling correct and update the unit test case to make it correctly simulate snack_pdu_handleing case. And the first two patches are making the data_in_cnt calculation easier to be understood (Only caculating the subtasks). And make alls the data_in_cnt decreasing only for sub read tasks.

**Comment by spdkci** [comment] 2019-11-25 20:55
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50636.html

**Comment by spdkci** [comment] 2019-11-25 21:11
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50639.html

**Comment by shuhei-matsumoto** [comment] 2019-11-25 22:01
Shame on me. This has been caused by my thoughtless fault. I added a patch to revert it. https://review.gerrithub.io/c/spdk/spdk/+/475791. Ziye's fix https://review.gerrithub.io/c/spdk/spdk/+/475657 is nice but separating my fault from his fix is easier to get review.
Please rebase your patch for Ziye, and please review both for all.

**Comment by shuhei-matsumoto** [comment] 2019-11-25 22:15
Sorry, Umm, I thought I should revert a patch but the patch looks necessary.

When I posted a patch https://review.gerrithub.io/c/spdk/spdk/+/475791 to revert the patch , I saw the failure.
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/50646/archive/RBD_autotest/failed_test.log

We have to investigate more.

**Comment by spdkci** [comment] 2019-11-26 16:29
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50672.html

**Comment by spdkci** [comment] 2019-11-27 02:54
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50764.html

**Comment by optimistyzy** [comment] 2019-11-27 02:58
> Sorry, Umm, I thought I should revert a patch but the patch looks necessary.
> 
> When I posted a patch https://review.gerrithub.io/c/spdk/spdk/+/475791 to revert the patch , I saw the failure.
> https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/50646/archive/RBD_autotest/failed_test.log
> 
> We have to investigate more.

We still need your revert patch. Yesterday, we have the intermittent failure for the event test, which is not related with our patches

**Comment by spdkci** [comment] 2019-11-29 10:15
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51045.html

**Comment by spdkci** [comment] 2019-12-02 07:06
Another instance of this failure. Reported by @karlatec. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51077.html

**Comment by spdkci** [comment] 2019-12-02 17:52
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51191.html

**Comment by spdkci** [comment] 2019-12-03 20:40
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51289.html

**Comment by spdkci** [comment] 2019-12-04 06:59
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51296.html

**Closed** 2019-12-04 15:35 UTC
Labels: Intermittent Failure
