### ISSUE TITLE
vhost intermittent failure: spdk_mem_unregister() failed in vhost_session_mem_unregister()

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1085] opened 2019-11-29 02:08 UTC
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51008.html

**Comment by spdkci** [comment] 2019-11-29 02:11
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51010.html

**Comment by spdkci** [comment] 2019-11-29 02:33
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51012.html

**Comment by spdkci** [comment] 2019-11-29 03:53
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51018.html

**Comment by spdkci** [comment] 2019-11-29 04:22
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51020.html

**Comment by spdkci** [comment] 2019-11-29 04:48
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51021.html

**Comment by spdkci** [comment] 2019-11-29 05:10
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51022.html

**Comment by spdkci** [comment] 2019-11-29 05:18
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51024.html

**Comment by spdkci** [comment] 2019-11-29 05:40
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51026.html

**Comment by spdkci** [comment] 2019-11-29 06:15
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51029.html

**Comment by spdkci** [comment] 2019-11-29 06:40
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51030.html

**Comment by shuhei-matsumoto** [comment] 2019-11-29 06:41
The object will never pass test pool. It's likely that SPDK binary size or location hits the issue.
I will stop rebasing until SPDK master branch is updated by merge :)

**Comment by karlatec** [comment] 2019-11-29 07:22
What's curious this only reproduces on one of the test platforms.
I've run vhost test a couple of times and it only failed on GP17.
If we take GP14 as a comparison then it has then it's the same platform model, same Qemu version, same NVMe model.
Investigating.

**Comment by karlatec** [comment] 2019-11-29 07:38
Looks like only platforms with QAT cards installed are affected by the issue.
@tomzawadzki suggests this commit is reponsible: https://review.gerrithub.io/c/spdk/spdk/+/475928

**Comment by shuhei-matsumoto** [comment] 2019-11-29 08:00
Thanks for the investigation @karlatec @tomzawadzki  It looks likely. I have more than 10 patches but only one hits this solidly. I want to investigate by using them next week but any small change may prevent this.

**Comment by karlatec** [comment] 2019-11-29 08:03
@shuhei-matsumoto For now I've disabled testing vhost_autotest on platforms with QAT cards, so you shouldn't see this issue anymore.

I'll revert the configuration once we fix or revert the faulty commit.

**Comment by shuhei-matsumoto** [comment] 2019-11-29 08:16
Thank you @karlatec 
I saw this by other patches. I will take a look at the log more

**Comment by spdkci** [comment] 2019-12-03 10:22
Another instance of this failure. Reported by @karlatec. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51249.html

**Comment by tomzawadzki** [comment] 2019-12-03 15:47
@peluse Details on the issue we have right now:
[Patch](https://review.gerrithub.io/c/spdk/spdk/+/475928) causing the failure was reverted for now.
The issue occurred on just subset of physical machines. All machines whether error occurred or not had IOMMU enabled. 

Bit of discussion from Slack:
```
Tomek Zawadzki 16:32
FYI the fail occured only on some physical machines, all of which I think had IOMMU enabled. Karol attributed that to those machines running QAT cards, but don't think thats releated - probably some setting on all of them is the same.
Ben Walker 16:34
I think DPDK stores the mode in two spots. One is what the user requested and one is what was actually used after the detection code runs. I may be looking at the user requested value, which could be "don't care"
I'm not sure the other value can be obtained from public function calls
But if it can be, the fix is to use that instead
```

**Comment by spdkci** [comment] 2019-12-05 22:56
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51064.html

**Comment by jimharris** [comment] 2019-12-13 16:00
The patch referenced above was reverted - so we can close this issue.

**Closed by jimharris** 2019-12-13 16:00 UTC
