### ISSUE TITLE
[spdk_top] Confusing location and historical cache errors in Fedora OS

### ISSUE THREAD

**Issue by ChengqiangMeng** [spdk/spdk#2053] opened 2021-07-23 06:39 UTC
When switching tabs, the error will be displayed in the Fedora OS environment, and Centos and Ubuntu are normal.

## Expected Behavior
![normal](https://user-images.githubusercontent.com/77378851/126741584-28d7f5e8-4e0d-4636-8974-fe2d0a6a23e9.JPG)

## Current Behavior

![spdk_top](https://user-images.githubusercontent.com/77378851/126741629-996ed2ee-0a75-46ef-8d78-a0d73649c414.JPG)

![spdk_top1](https://user-images.githubusercontent.com/77378851/126741611-53401425-a346-46ea-8059-d794fe642bc1.JPG)

## Possible Solution

The title may need to be refreshed.

## Steps to Reproduce

1. start a target, example:
`./build/bin/spdk_tgt&`
2. start spdk_top:
`./build/bin/spdk_top`

## Context (Environment including OS version, SPDK version, etc.)
os: fedora28 29 30 32 34
spdk version: 49ffdc18afc639a8f59e87e2e0945a379ced497b

**Comment by KKaras169169** [comment] 2021-07-27 09:45
I am unable to reproduce this on my setup with fedora 34. I used both newest master branch and branch with 49ffdc1 on top. I will try with the oldest Fedora version that you mentioned (28) now.

**Comment by KKaras169169** [comment] 2021-07-27 12:47
I still cannot reproduce it on Fedora 29. Tried the newest master and the 49ffdc1 as well with no change in spdk_top's behavior.

**Comment by KKaras169169** [comment] 2021-07-27 15:33
@ChengqiangMeng Could you also provide the version of NCURSES that you use?
I tested running spdk_top with v1.266 (Fedora 34), v1.257 (Fedora 28) and v1.263 (Fedora 29).

**Comment by ChengqiangMeng** [comment] 2021-07-28 02:32
@KKaras169169 I see that my version of NCURSES is v1.264 (Fedora 32)  v1.263 (Fedora 30)   v1.266 (Fedora 34)   v1.257 (Fedora 28)  and v1.263 (Fedora 29). I updated my code to the latest(95a59652f97ef12d680ec2125794831f7f471221, I also test with 49ffdc18afc639a8f59e87e2e0945a379ced497b) and this issue still occurs.

**Comment by KKaras169169** [comment] 2021-07-28 06:46
Okay. I have some questions regarding the error:
1) Does the error crash the application?
2) Is it appearing strictly when switching to CORES tab or just appears sometimes when switching to any tab?
3) Could you provide some logs or error message?

**Comment by ChengqiangMeng** [comment] 2021-07-28 07:25
1. The error dose not crash the application.
2. It seems to be characters cache problem. This phenomenon appears every time you switch tab. And when pressing enter to display detailed information, ‘esc’ cannot clear the screen .
3. The error screenshot is as follows：
![2error](https://user-images.githubusercontent.com/77378851/127281124-426d2050-1f70-479f-90cb-9dac46cd2119.JPG)
![error](https://user-images.githubusercontent.com/77378851/127281136-8606a7c6-22b5-4959-abb3-d3697e44653e.png)

**Comment by KKaras169169** [comment] 2021-07-28 08:17
@ChengqiangMeng Thank you for this picture! I have a guess, where the problem might be and I will keep trying to reproduce this on my side.

**Comment by ChengqiangMeng** [comment] 2021-07-28 08:34
@KKaras169169 You are welcome, I am glad to be able to help you! If you need other assistance, please feel free to let me know.

**Comment by KKaras169169** [comment] 2021-07-28 09:48
@ChengqiangMeng I'm going to take you up on that offer and ask some more questions:

1) What flags did you use to configure the SPDK target with ./configure script? (I know that --enable-debug sometimes messes with spdk_top's behavior, that is why I am asking)
2) Are those Fedoras that you use fresh systems? (I created a few VMs from scratch and could not make spdk_top break in this manner, and I am curious if perhaps some package or configuration might be affecting NCURSES display functions)

Thanks again!

**Comment by ChengqiangMeng** [comment] 2021-07-29 02:08
@KKaras169169 I am glad to answer for you:
1. I don't use any flags to configure the SPDK target with ./configure script.
2. These fedoras have existed before. And I tested on Vagrant Fedora31 and Fedora33, still have the same issue.

VM_OS_VERSION: 
> Linux fedora33.localdomain 5.11.11-200.fc33.x86_64 
> Linux fedora31.localdomain 5.8.18-100.fc31.x86_64

**Comment by KKaras169169** [comment] 2021-07-29 06:16
"I tested on Vagrant Fedora31 and Fedora33," I'll try with Vagrant environment next. Thanks again for your answers @ChengqiangMeng !

**Comment by ChengqiangMeng** [comment] 2021-07-29 06:33
@KKaras169169 You are welcome, please feel free to communicate if you have any questions.

**Comment by KKaras169169** [comment] 2021-07-29 09:06
I tried running spdk_top in Fedora 33 inside vagrant, but still no results. I am starting to think it might be something in linux configuration that is affecting the display. I'll stop testing with different Fedora VMs now and dig through the Internet to see if I can find a fix.

**Comment by KKaras169169** [comment] 2021-07-29 10:12
@ChengqiangMeng can you write the value of TERM variable? (echo $TERM)
I was able to reproduce the issue partially (remaining text from previous tab) when I set $TERM to "_ansi_" value. With values "_xterm_", "_gnome_", "_linux_" (and their variations like _xterm-256color_) everything seemed to work fine.

Also could you tell me what encoding does your terminal use?

**Comment by ChengqiangMeng** [comment] 2021-07-30 01:25
@KKaras169169 Your idea is great! My $TERM is "xterm" and encoding is 'en_US.UTF-8'. When I set it to "gnome", the display is normal. I tested other values and they all have problems.

"ansi" : I think it should be the same as your test result, the display looks terrible.
"xterm" and "xterm-256color" : Like in the picture above.
"linux" : The display is normal, but the screen cannot be cleared after exiting.

**Comment by KKaras169169** [comment] 2021-07-30 06:10
@ChengqiangMeng Excellent! I'll post an update inside spdk_top docs to let other people know about this issue with display and possible solution of changing TERM value. Thanks again for your cooperation!

**Comment by ChengqiangMeng** [comment] 2021-07-30 06:31
@KKaras169169 You are welcome. I have a thoughts:  through my test, when “TERM=gnome”, basically all os can display normally. Can we set TERM to "gnome" before starting spdk_top, and change it back to the previous value at the end of spdk_top?

**Comment by KKaras169169** [comment] 2021-07-30 06:51
@ChengqiangMeng I'll try to do that instead of putting it in the docs then. Thanks for suggestion!

**Comment by KKaras169169** [comment] 2021-07-30 11:19
> This [patch](https://review.spdk.io/gerrit/c/spdk/spdk/+/8993) fixed this issue on my end, but please confirm whether this works for your system as well @ChengqiangMeng.

Scratch that, we should not set system variables to run spdk_top and rely on different settings being present on user's machine. I'll have to do some more digging to maybe rework some of our functions in spdk_top to work on all terminals.

**Comment by ChengqiangMeng** [comment] 2021-08-02 01:26
@KKaras169169 Okay, I don’t have any good ideas about this at the moment, if you need help, please feel free to let me know.
> > This [patch](https://review.spdk.io/gerrit/c/spdk/spdk/+/8993) fixed this issue on my end, but please confirm whether this works for your system as well @ChengqiangMeng.
> 
> Scratch that, we should not set system variables to run spdk_top and rely on different settings being present on user's machine. I'll have to do some more digging to maybe rework some of our functions in spdk_top to work on all terminals.

**Comment by ChengqiangMeng** [comment] 2021-08-02 01:29
> This [patch](https://review.spdk.io/gerrit/c/spdk/spdk/+/8993) fixed this issue on my end, but please confirm whether this works for your system as well @ChengqiangMeng.

I testes it and the  [patch](https://review.spdk.io/gerrit/c/spdk/spdk/+/8993) has fixed this bug.

**Comment by KKaras169169** [comment] 2021-08-17 13:14
I am removing the label "Patches out for review" since I need to take a different approach and not force user to use a certain system setting. I am going to try and debug the application and aim to find what in Ncurses breaks terminal display and hopefully I will be able to make appropriate changes.

**Comment by KKaras169169** [comment] 2021-09-03 14:03
@ChengqiangMeng I have prepared a small [patch](https://review.spdk.io/gerrit/c/spdk/spdk/+/9389) to help with debugging of this issue. Could you apply it on your end and tell me if your application stops on an assert? Additionally I have disabled a few function calls to get rid of the border lines - if spdk_top performs OK without them, then I'll need to manually add those lines instead of relying on the box() function.

**Comment by ChengqiangMeng** [comment] 2021-09-06 02:00
@KKaras169169 I tested it with this patch and it worked fine. And the display effect is better than before. Thread details also will not be cached on the screen. Just no lines.

**Comment by KKaras169169** [comment] 2021-09-06 10:28
@ChengqiangMeng I have submitted a [patch](https://review.spdk.io/gerrit/c/spdk/spdk/+/9400) changing the way we display border lines. I would appreciate if you could apply it on your side and see if you still run into these display issues.

**Comment by ChengqiangMeng** [comment] 2021-09-07 06:21
@KKaras169169 It may not help the issue, the display cache still exists.
And I found a phenomenon as shown in the picture：
![b](https://user-images.githubusercontent.com/77378851/132293900-dfcbdd34-7ac2-4f36-834b-d4ab47c4bc8b.png)
When I press `2` or `3` twice, the green square will move from the right to the left. I'm not sure that will help you. This is just a strange phenomenon about the display.

**Comment by KKaras169169** [comment] 2021-09-07 06:35
@ChengqiangMeng since we now know that those functions responsible for drawing borderlines are probably the cause (because spdk_top was working fine with this [patch](https://review.spdk.io/gerrit/c/spdk/spdk/+/9389)), could you try debugging it on your end (or just comment out the changed lines from this [patch](https://review.spdk.io/gerrit/c/spdk/spdk/+/9400) one by one and launch spdk_top until you cannot see the issue) and seeing which one is causing the problems? If you could pinpoint the function then we can just get rid of it - it is still better than having spdk_top break inside some terminals.

**Comment by ChengqiangMeng** [comment] 2021-09-07 06:38
@KKaras169169 Ok, I will try to debug and feedback to you.

**Comment by ChengqiangMeng** [comment] 2021-09-07 08:17
@KKaras169169 I found that deleting the left line( `mvwvline(tab, 1, 0, ACS_VLINE, tab_height);` ) of `draw_tabs` function, display caching does not happen.

**Comment by KKaras169169** [comment] 2021-09-07 11:20
@ChengqiangMeng thanks for checking! I will post a patch disabling this line and hopefully this will be enough to fix the issue.

**Comment by KKaras169169** [comment] 2021-09-07 11:51
@ChengqiangMeng  I have prepared a [patch](https://review.spdk.io/gerrit/c/spdk/spdk/+/9415) deleting the vertical border lines inside tab window. Could you check it one more time on your side? If the issue was caused only by the left line, the spdk_top should work fine with this patch.

**Comment by ChengqiangMeng** [comment] 2021-09-08 00:58
@KKaras169169 The spdk_top now works normally with this [patch](https://review.spdk.io/gerrit/c/spdk/spdk/+/9415). Thanks for your fix!

**Comment by tomzawadzki** [comment] 2021-09-22 08:32
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/9415 is now merged, fixing this issue. Thank you @KKaras169169 !

**Closed by tomzawadzki** 2021-09-22 08:32 UTC
Labels: bug, Low, Patches out for review
