### ISSUE TITLE
[spdk_top] The display cannot be refreshed in time when the thread destroyed

### ISSUE THREAD

**Issue by ChengqiangMeng** [spdk/spdk#2071] opened 2021-08-05 08:15 UTC
When all threads are destroyed, the threads displayed on spdk_top will not be cleared.

## Current Behavior
Just CORES is normal, THREADS and POLLERS in error :

![image](https://user-images.githubusercontent.com/77378851/128313728-45915536-5392-4650-863c-4ed24dfd4d42.png)
![image](https://user-images.githubusercontent.com/77378851/128313764-e3dbe5a4-0f6f-455d-bb07-5059243f1db7.png)
![image](https://user-images.githubusercontent.com/77378851/128313964-bfbf1a30-f7f9-4ab3-8599-e589dbce170c.png)

## Expected Behavior
Exit spdk_top and rerun, it will work normally:

![image](https://user-images.githubusercontent.com/77378851/128314127-a3e4e92d-a438-44a8-aa79-6f5fa4fd93ff.png)

## Steps to Reproduce
1. `test/event/scheduler/scheduler -m 0xF -p 2 --wait-for-rpc&`
2. `scripts/rpc.py framework_set_scheduler dynamic`
3. `scripts/rpc.py framework_start_init`
4. `build/bin/spdk_top`
5. open another terminal and create thread :
 like this:
`rpc_cmd --plugin scheduler_plugin scheduler_thread_create -n busy0 -m 0x1 -a 100`
`rpc_cmd --plugin scheduler_plugin scheduler_thread_create -n busy1 -m 0x1 -a 100`
`rpc_cmd --plugin scheduler_plugin scheduler_thread_create -n busy2 -m 0x1 -a 100`
6. destroy all threads.

## Context (Environment including OS version, SPDK version, etc.)

SPDK VERSION: 49ffdc1
OS VERSION: 5.11.22-100.fc32.x86_64

**Comment by KKaras169169** [comment] 2021-08-17 08:57
I can confirm that threads are not removed from THREADS tab. However, pollers are being deleted appropriately on my machine.

**Comment by KKaras169169** [comment] 2021-08-17 10:31
I have uploaded a fix for this issue [here](https://review.spdk.io/gerrit/c/spdk/spdk/+/9199/1).

**Comment by ChengqiangMeng** [comment] 2021-08-18 01:55
Hi @KKaras169169 ,I tested it and the bug has been fixed. Thank you.

**Comment by KKaras169169** [comment] 2021-09-20 08:17
Closing, because fix has been merged.

**Closed by KKaras169169** 2021-09-20 08:17 UTC
Labels: bug, Low, Patches out for review
