### ISSUE TITLE
[test_name] Process leaked file descriptors.

### ISSUE THREAD

**Issue by glodfish-zg** [spdk/spdk#1878] opened 2021-04-07 07:24 UTC
00:01:25.612  START TEST devices
00:01:25.612  ************************************
00:01:25.613   09:00:49	# xtrace_enable
00:01:25.613   09:00:49	# /var/jenkins/workspace/vhost-autotest/spdk/test/setup/devices.sh
00:01:25.658  * Purging old temporary test storage (/tmp/spdk.MLutLA)
00:01:25.676  * Looking for test storage...
00:01:25.680  * Found test storage at /var/jenkins/workspace/vhost-autotest/spdk/test/setup
00:01:25.680     09:00:49	# xtrace_enable
00:01:25.680   09:00:49	# shopt -s nullglob
00:01:25.681   09:00:49	# trap cleanup EXIT
00:01:25.681   09:00:49	# setup reset
00:01:25.681   09:00:49	# [[ reset == output ]]
00:01:25.681   09:00:49	# /var/jenkins/workspace/vhost-autotest/spdk/scripts/setup.sh reset
00:01:26.060   09:00:50	# blocks=()
00:01:26.060   09:00:50	# declare -a blocks
00:01:26.060   09:00:50	# blocks_to_pci=()
00:01:26.060   09:00:50	# declare -A blocks_to_pci
00:01:26.060   09:00:50	# for block in "/sys/block/nvme"*
00:01:26.060    09:00:50	# readlink -f /sys/block/nvme0n1/device/device
00:01:26.063   09:00:50	# pci=/sys/devices/pci0000:80/0000:80:02.0/0000:82:00.0
00:01:26.063   09:00:50	# pci=0000:82:00.0
00:01:26.063   09:00:50	# blkid /dev/nvme0n1
00:01:26.070  /dev/nvme0n1: PTUUID="82d7197e-dc32-47d3-8aa5-acd63bc509bc" PTTYPE="gpt"
00:01:26.070   09:00:50	# (( 0 > 0 ))
00:01:26.070    09:00:50	# trap - ERR
00:01:26.070    09:00:50	# print_backtrace
00:01:26.071    09:00:50	# [[ ehxBET =~ e ]]
00:01:26.071    09:00:50	# args=("${BASH_ARGV[@]}")
00:01:26.071    09:00:50	# local args
00:01:26.071    09:00:50	# xtrace_disable
00:01:26.071    09:00:50	# '[' '' '!=' yes ']'
00:01:26.071    09:00:50	# PREV_BASH_OPTS=ehxBET
00:01:26.072    09:00:50	# [[ ehxBET == *\x* ]]
00:01:26.072    09:00:50	# XTRACE_DISABLED=yes
00:01:26.072    09:00:50	# set +x
00:01:26.072  ========== Backtrace start: ==========
00:01:26.072  
00:01:26.078  in /var/jenkins/workspace/vhost-autotest/spdk/test/setup/devices.sh:189 -> main([])
00:01:26.078       ...
00:01:26.078     184 		if ! blkid "/dev/${block##*/}"; then
00:01:26.078     185 			blocks+=("${block##*/}")
00:01:26.078     186 			blocks_to_pci["${block##*/}"]=$pci
00:01:26.078     187 		fi
00:01:26.078     188 	done
00:01:26.078  => 189 	((${#blocks[@]} > 0))
00:01:26.078     190 	
00:01:26.078     191 	declare -r test_disk=${blocks[0]}
00:01:26.078     192 	
00:01:26.078     193 	run_test "nvme_mount" nvme_mount
00:01:26.078     194 	run_test "dm_mount" dm_mount
00:01:26.078       ...
00:01:26.078  
00:01:26.078  ========== Backtrace end ==========
00:01:26.078    09:00:50	# xtrace_enable
00:01:26.078    09:00:50	# return 0
00:01:26.079   09:00:50	# cleanup
00:01:26.079   09:00:50	# cleanup_nvme
00:01:26.079   09:00:50	# mountpoint -q ''
00:01:26.080   09:00:50	# [[ -b /dev/ ]]
00:01:26.080   09:00:50	# [[ -b /dev/ ]]
00:01:26.080   09:00:50	# cleanup_dm
00:01:26.080   09:00:50	# mountpoint -q ''
00:01:26.082   09:00:50	# [[ -L /dev/mapper/ ]]
00:01:26.083   09:00:50	# [[ -b /dev/ ]]
00:01:26.083   09:00:50	# [[ -b /dev/ ]]
00:01:26.083   09:00:50	# [[ -b /dev/ ]]
00:01:26.083    09:00:50	# trap - ERR
00:01:26.083    09:00:50	# print_backtrace
00:01:26.083    09:00:50	# [[ ehxBET =~ e ]]
00:01:26.084    09:00:50	# args=("${BASH_ARGV[@]}")
00:01:26.084    09:00:50	# local args
00:01:26.084    09:00:50	# xtrace_disable
00:01:26.084    09:00:50	# '[' no '!=' yes ']'
00:01:26.084    09:00:50	# PREV_BASH_OPTS=ehxBET
00:01:26.084    09:00:50	# [[ ehxBET == *\x* ]]
00:01:26.084    09:00:50	# XTRACE_DISABLED=yes
00:01:26.085    09:00:50	# set +x
00:01:26.085  ========== Backtrace start: ==========
00:01:26.085  
00:01:26.090  in /var/jenkins/workspace/vhost-autotest/spdk/test/common/autotest_common.sh:944 -> run_test(["devices"],["/var/jenkins/workspace/vhost-autotest/spdk/test/setup/devices.sh"])
00:01:26.091       ...
00:01:26.091     939 		timing_enter $test_name
00:01:26.091     940 		echo "************************************"
00:01:26.091     941 		echo "START TEST $test_name"
00:01:26.091     942 		echo "************************************"
00:01:26.091     943 		xtrace_restore
00:01:26.091  => 944 		time "$@"
00:01:26.091     945 		xtrace_disable
00:01:26.091     946 		echo "************************************"
00:01:26.091     947 		echo "END TEST $test_name"
00:01:26.091     948 		echo "************************************"
00:01:26.091     949 		timing_exit $test_name
00:01:26.091       ...
00:01:26.095  in /var/jenkins/workspace/vhost-autotest/spdk/test/setup/test-setup.sh:11 -> main([])
00:01:26.095       ...
00:01:26.095     6   	[[ $(uname -s) == Linux ]] || exit 0
00:01:26.095     7   	
00:01:26.095     8   	run_test "acl" "$testdir/acl.sh"
00:01:26.095     9   	run_test "hugepages" "$testdir/hugepages.sh"
00:01:26.095     10  	run_test "driver" "$testdir/driver.sh"
00:01:26.095  => 11  	run_test "devices" "$testdir/devices.sh"
00:01:26.095       ...
00:01:26.095  
00:01:26.095  ========== Backtrace end ==========
00:01:26.095    09:00:50	# xtrace_enable
00:01:26.095    09:00:50	# return 0
00:01:26.096  
00:01:26.096  real	0m0.482s
00:01:26.096  user	0m0.230s
00:01:26.096  sys	0m0.270s
00:01:26.096    09:00:50	# trap - ERR
00:01:26.096    09:00:50	# print_backtrace
00:01:26.096    09:00:50	# [[ ehxBET =~ e ]]
00:01:26.097    09:00:50	# args=("${BASH_ARGV[@]}")
00:01:26.097    09:00:50	# local args
00:01:26.097    09:00:50	# xtrace_disable
00:01:26.097    09:00:50	# '[' no '!=' yes ']'
00:01:26.098    09:00:50	# PREV_BASH_OPTS=ehxBET
00:01:26.098    09:00:50	# [[ ehxBET == *\x* ]]
00:01:26.098    09:00:50	# XTRACE_DISABLED=yes
00:01:26.098    09:00:50	# set +x
00:01:26.098  ========== Backtrace start: ==========
00:01:26.098  
00:01:26.106  in /var/jenkins/workspace/vhost-autotest/spdk/test/common/autotest_common.sh:944 -> run_test(["setup.sh"],["/var/jenkins/workspace/vhost-autotest/spdk/test/setup/test-setup.sh"])
00:01:26.106       ...
00:01:26.106     939 		timing_enter $test_name
00:01:26.106     940 		echo "************************************"
00:01:26.106     941 		echo "START TEST $test_name"
00:01:26.106     942 		echo "************************************"
00:01:26.106     943 		xtrace_restore
00:01:26.106  => 944 		time "$@"
00:01:26.106     945 		xtrace_disable
00:01:26.106     946 		echo "************************************"
00:01:26.106     947 		echo "END TEST $test_name"
00:01:26.106     948 		echo "************************************"
00:01:26.106     949 		timing_exit $test_name
00:01:26.106       ...
00:01:26.110  in /var/jenkins/workspace/vhost-autotest/spdk/autotest.sh:128 -> main(["/var/jenkins/workspace/vhost-autotest/autorun-spdk.conf"])
00:01:26.111       ...
00:01:26.111     123 				./scripts/setup.sh
00:01:26.111     124 	
00:01:26.111     125 			# Export our blocked list so it will take effect during next setup.sh
00:01:26.111     126 			export PCI_BLOCKED
00:01:26.111     127 		fi
00:01:26.111  => 128 		run_test "setup.sh" "$rootdir/test/setup/test-setup.sh"
00:01:26.111     129 	fi
00:01:26.111     130 	
00:01:26.111     131 	./scripts/setup.sh status
00:01:26.111     132 	
00:01:26.111     133 	if [[ $(uname -s) == Linux ]]; then
00:01:26.111       ...
00:01:26.111  
00:01:26.111  ========== Backtrace end ==========
00:01:26.111    09:00:50	# xtrace_enable
00:01:26.111    09:00:50	# return 0
00:01:26.111  
00:01:26.111  real	0m11.151s
00:01:26.111  user	0m3.028s
00:01:26.111  sys	0m3.689s
00:01:26.112   09:00:50	# process_core
00:01:26.112   09:00:50	# local es=1
00:01:26.112   09:00:50	# (( es != 0 ))
00:01:26.112   09:00:50	# sleep 5s
00:01:31.112   09:00:55	# local coredumps core
00:01:31.112   09:00:55	# shopt -s nullglob
00:01:31.112   09:00:55	# coredumps=("$output_dir/coredumps/"*.bt.txt)
00:01:31.113   09:00:55	# shopt -u nullglob
00:01:31.113   09:00:55	# (( 0 > 0 ))
00:01:31.113   09:00:55	# return 0
00:01:31.113   09:00:55	# autotest_cleanup
00:01:31.113   09:00:55	# /var/jenkins/workspace/vhost-autotest/spdk/scripts/setup.sh reset
00:01:31.289  0000:82:00.0 (8086 0a54): Already using the nvme driver
00:01:31.301  0000:80:04.7 (8086 0e27): Already using the ioatdma driver
00:01:31.312  0000:80:04.6 (8086 0e26): Already using the ioatdma driver
00:01:31.323  0000:80:04.5 (8086 0e25): Already using the ioatdma driver
00:01:31.334  0000:80:04.4 (8086 0e24): Already using the ioatdma driver
00:01:31.345  0000:80:04.3 (8086 0e23): Already using the ioatdma driver
00:01:31.356  0000:80:04.2 (8086 0e22): Already using the ioatdma driver
00:01:31.367  0000:80:04.1 (8086 0e21): Already using the ioatdma driver
00:01:31.378  0000:80:04.0 (8086 0e20): Already using the ioatdma driver
00:01:31.389  0000:00:04.7 (8086 0e27): Already using the ioatdma driver
00:01:31.401  0000:00:04.6 (8086 0e26): Already using the ioatdma driver
00:01:31.412  0000:00:04.5 (8086 0e25): Already using the ioatdma driver
00:01:31.423  0000:00:04.4 (8086 0e24): Already using the ioatdma driver
00:01:31.434  0000:00:04.3 (8086 0e23): Already using the ioatdma driver
00:01:31.445  0000:00:04.2 (8086 0e22): Already using the ioatdma driver
00:01:31.456  0000:00:04.1 (8086 0e21): Already using the ioatdma driver
00:01:31.468  0000:00:04.0 (8086 0e20): Already using the ioatdma driver
00:01:31.531   09:00:55	# /var/jenkins/workspace/vhost-autotest/spdk/scripts/setup.sh cleanup
00:01:31.688  ls: cannot access '/dev/shm/*': No such file or directory
00:01:31.691  Clean
00:01:31.693    09:00:55	# uname -s
00:01:31.696   09:00:55	# '[' Linux = Linux ']'
00:01:31.696   09:00:55	# [[ 0 -eq 1 ]]
00:01:31.696   09:00:55	# modprobe -r uio_pci_generic
00:01:31.700   09:00:55	# rm -rf /var/tmp/asan_suppression_file
00:01:31.702   09:00:55	# [[ -n |/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h ]]
00:01:31.703   09:00:55	# echo '|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h'
00:01:31.703   09:00:55	# [[ -e /proc/22768/status ]]
00:01:31.703   09:00:55	# kill 22768
00:01:31.704   09:00:55	# revert_soft_roce
00:01:31.704   09:00:55	# rxe_cfg stop
00:01:31.704   09:00:55	# /var/jenkins/workspace/vhost-autotest/spdk/scripts/rxe_cfg_small.sh stop
00:01:31.721   09:00:55	# exit 1
00:01:41.733  Process leaked file descriptors. See https://jenkins.io/redirect/troubleshooting/process-leaked-file-descriptors for more information
00:01:41.745  Build step 'Execute shell' marked build as failure
00:01:42.685  [PostBuildScript] - [INFO] Executing post build scripts.
00:01:42.693  [vhost-autotest] $ /usr/bin/env bash

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/41080/archive/nvmf-tcp-phy-autotest/build.log
https://ci.spdk.io/results/autotest-per-patch/builds/41080/archive/vhost-autotest/build.log
https://ci.spdk.io/results/autotest-per-patch/builds/41080/archive/BlobFS-autotest/build.log

**Comment by spdkci** [comment] 2021-04-07 07:26
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_41080.html

**Comment by mikeBashStuff** [comment] 2021-04-07 08:05
Duplicate of #1870

**Closed by mikeBashStuff** 2021-04-07 08:05 UTC
Labels: Intermittent Failure
