### ISSUE TITLE
Building SPDK on Oracle Linux 8.4 with UEK + Mellanox OFED

### ISSUE THREAD

**Issue by AlexTalker** [spdk/spdk#2167] opened 2021-09-21 13:37 UTC
As title suggest, I'm trying to do some real necromancy here, i.e. building latest SPDK release in the following enviroment
1. Oracle Linux 8.4
2. Unbreakable Enterprise Kernel installed(v6)
3. For UEK, latest Mellanox OFED is re-built from sources

I'm trying to patch up SPEC file provided by SPDK repo to make it work and so far I encountered following issues:

# Oracle Linux is not supported

It seems that `pkgdep.sh` script fails due to the fact that Oracle Linux is not tested/supported, the same for `rpm-deps.sh`.
No big deal for me since I can just fill-in `BuildRequires` as I go anyway but generally might be worth paying attention to.

# Mellanox supplies mlnx-dpdk

Since SPEC file builds from release tarball, I decided to use supplied by Mellanox OFED `mlnx-dpdk` package.
And here's the trick. This package stores most of DPDK-related stuff in `/opt/mellanox/dpdk`, which has following folders:
1. `bin`
2. `include`
3. `lib64`

But when I supply `--with-dpdk=/opt/mellanox/dpdk/` to `./configure`, I end up with things like this one:
```
[perf]$ make
make: *** No rule to make target '/opt/mellanox/dpdk/lib/librte_eal.a', needed by '/project/rpm/BUILD/spdk.spec/spdk-21.07/build/examples/accel_perf'.  Stop.
```
I.e. building system tries to look for `lib/` instead of `lib64/` and I couldn't figure out how to tell it otherwise so I just made a symbolic link.

# DPDK has undefined symbols

This is the last issue and most hard for me to understand. After patching up previous error, I end up with following errors:
```
  LINK spdk_trace
/opt/mellanox/dpdk/lib/librte_ethdev.a(librte_ethdev_rte_sft.c.o): In function `sft_ipfrag_flush':
rte_sft.c:(.text+0x1a0b): undefined reference to `rte_ip_frag_release_collected'
/opt/mellanox/dpdk/lib/librte_ethdev.a(librte_ethdev_rte_sft.c.o): In function `sft_process_mbuf.constprop.20':
rte_sft.c:(.text+0x2148): undefined reference to `rte_ipv4_frag_process'
rte_sft.c:(.text+0x21f5): undefined reference to `rte_ip_frag_free_death_row'
rte_sft.c:(.text+0x2237): undefined reference to `rte_ipv6_frag_process'
/opt/mellanox/dpdk/lib/librte_ethdev.a(librte_ethdev_rte_sft.c.o): In function `sft_destroy_ipfrag.part.9':
rte_sft.c:(.text.unlikely+0x1ba): undefined reference to `rte_ip_frag_table_destroy'
/opt/mellanox/dpdk/lib/librte_ethdev.a(librte_ethdev_rte_sft.c.o): In function `rte_sft_drain_fragment_mbuf':
rte_sft.c:(.text.experimental+0x2005): undefined reference to `rte_ip_frag_release_collected'
/opt/mellanox/dpdk/lib/librte_ethdev.a(librte_ethdev_rte_sft.c.o): In function `rte_sft_init':
rte_sft.c:(.text.experimental+0x27eb): undefined reference to `rte_ip_frag_table_create'
collect2: error: ld returned 1 exit status
```
The trick is that `/opt/mellanox/dpdk/lib64/librte_ip_frag.so` is **exists** and provides these symbols. At least as far as I can tell with `strings` call.
And at this point I totally do not understand where problem lies, since `.so` files are present and `ldd` shows what seems to be normal dependencies.

# Side note

About a year ago or so I have successfully managed to build SPDK on CentOS 7.8 with kernel 3.10something
with Mellanox OFED DPDK package.
It only took specifying different path to DPDK and re-building it with some missing libraries.
I thought today it's gonna be the same but the old SPEC file is now removed and new one is a little bit hard to navigate.

So now that I finally hit some obstacle which I can't get my head around, I decided to ask for help here. 

Any support on this ongoing struggle would be appreciated!

**Comment by AlekseyMarchuk** [comment] 2021-09-21 13:54
Hi @AlexTalker 
Thanks for reporting this issue, I'll check it. Not sure that I can find the same environment but I believe that issue with undefined symbols in mofed dpdk can be reproduced in another env

**Comment by AlekseyMarchuk** [comment] 2021-09-23 16:19
I reproduced the same problem with undefined symbols, working on it

**Comment by AlekseyMarchuk** [comment] 2021-09-24 09:50
@AlexTalker could you clarify your Mellanox ofed version? I have a bit different result with `MLNX_OFED_LINUX-5.4-1.0.3.0`. Please also provide ofed installation options. If I understand correctly, you are using x86 machine, is it correct?

**Comment by AlexTalker** [comment] 2021-09-24 09:59
@AlekseyMarchuk sure, thing, I have the following in my building environment at the moment:
```
ibacm-54mlnx1-1.54103.x86_64
mlnx-tools-5.2.0-0.54103.x86_64
libibverbs-utils-54mlnx1-1.54103.x86_64
mlnx-dpdk-20.11.0-1.54103.x86_64
libibverbs-54mlnx1-1.54103.x86_64
librdmacm-54mlnx1-1.54103.x86_64
infiniband-diags-54mlnx1-1.54103.x86_64
mlnx-ethtool-5.10-1.54103.x86_64
librdmacm-utils-54mlnx1-1.54103.x86_64
rdma-core-54mlnx1-1.54103.x86_64
mlnx-ofa_kernel-5.4-OFED.5.4.1.0.3.1.ol8u4.x86_64
mlnx-ofa_kernel-devel-5.4-OFED.5.4.1.0.3.1.ol8u4.x86_64
mlnx-ofed-dpdk-5.4-1.0.3.0.ol8.3.noarch
mlnx-dpdk-devel-20.11.0-1.54103.x86_64
libibumad-54mlnx1-1.54103.x86_64
mlnx-iproute2-5.11.0-1.54103.x86_64
kmod-mlnx-ofa_kernel-5.4-OFED.5.4.1.0.3.1.ol8u3.x86_64
rdma-core-devel-54mlnx1-1.54103.x86_64
mlnx-ofa_kernel-modules-5.4-OFED.5.4.1.0.3.1.kver.5.4.17_2102.203.6.el8uek.x86_64.x86_64
```

So it seems like `5.4.1.0.3.1` is the answer.

I also have following kernel packages:
```
kernel-uek-debug-5.4.17-2102.203.6.el8uek.x86_64
kernel-headers-4.18.0-305.10.2.el8_4.x86_64
kernel-mft-4.17.0-5.4.17_2102.203.6.el8uek.x86_64.ol8u4.x86_64
mlnx-ofa_kernel-5.4-OFED.5.4.1.0.3.1.ol8u4.x86_64
mlnx-ofa_kernel-devel-5.4-OFED.5.4.1.0.3.1.ol8u4.x86_64
kmod-mlnx-ofa_kernel-5.4-OFED.5.4.1.0.3.1.ol8u3.x86_64
mlnx-ofa_kernel-modules-5.4-OFED.5.4.1.0.3.1.kver.5.4.17_2102.203.6.el8uek.x86_64.x86_64
```

Yes, I used x64 machine.

Regarding OFED installation I am not completely sure since we have it for the most part as a locally served RPM repository but I found following configuration options to be supplied:
```
--with-core-mod --with-user_mad-mod --with-user_access-mod --with-addr_trans-mod --with-mlxfw-mod --with-mlx5-mod --with-mlx5-ipsec --with-ipoib-mod
```

So `mlnx-dpdk` package is also built with these options.

Hope that helps!

**Comment by AlexTalker** [comment] 2021-10-01 09:24
@AlekseyMarchuk Any luck with debugging of the issue?
Can I help you out with it in any way?
Say, maybe you have some patches that fix the issue and I can test them out on my use-case.

**Comment by AlekseyMarchuk** [comment] 2021-10-02 12:39
Hi @AlexTalker 
I contacted people who are responsible for dpdk module, waiting for their response. For now I mark this problem as 3rd party. Probably this issue will be redirected to mofed.

**Comment by jimharris** [comment] 2022-02-03 23:46
Thanks @AlekseyMarchuk.  Looks like nothing further needed, so closing this issue.

**Closed by jimharris** 2022-02-03 23:46 UTC
Labels: 3rd party issue, Sighting
