### ISSUE TITLE
autotest failed but the result is pass in test pool 

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#747] opened 2019-04-09 01:07 UTC
when I tried to give a test package, in the test pool, I watched that on ubuntu17:
test report segfault ,
but the test result is pass.
[log.txt](https://github.com/spdk/spdk/files/3056766/log.txt)

## Expected Behavior
test is really pass.

## Current Behavior
failed at blockdev.sh ,and the result is pass

## Steps to Reproduce
watch test pool ubuntu17_autotest

## Context (Environment including OS version, SPDK version, etc.)
commit :bef5509d4f124ff7cdb909dadf7e549686563a5d

**Comment by yidong0635** [comment] 2019-04-09 02:20
related issue #710  , it exists a long time.

**Comment by yidong0635** [comment] 2019-04-09 07:31
@karlatec  @darsto  please help to check this.

**Comment by karlatec** [comment] 2019-04-09 11:01
Oh wow, I see that this actually happens on every build.
Thanks for noticint this, I will investigate why is this happening. Jenkins runs all autotest scripts with bash option "set -e" set, so any return code other than 0 should generate a fail.

**Comment by karlatec** [comment] 2019-04-09 11:37
By the way @yidong0635, great catch on that. Most of the times people don't look into "PASSED" results:)

All right, I can see that this job wasn't respecting the default "set -e" set by Jenkins process. Manually adding this option makes the job behave like it should - builds will fail.

@yidong0635 @darsto @jimharris @Seth5141 @peluse 
If I set "set -e" now in the job every build will fail. Should we disable something from autotest config for now?
```
SPDK_BUILD_DOC=0
SPDK_BUILD_IOAT_KMOD=1
SPDK_FEDORA_PACKAGING=0
SPDK_RUN_CHECK_FORMAT=0
SPDK_RUN_SCANBUILD=0
SPDK_RUN_VALGRIND=0
SPDK_TEST_UNITTEST=1
SPDK_TEST_ISCSI=0
SPDK_TEST_NVME=1
SPDK_TEST_BDEV_OCSSD=0
SPDK_TEST_FTL=1
SPDK_TEST_NVMF=0
SPDK_TEST_RBD=0
SPDK_TEST_VHOST=0
SPDK_TEST_BLOCKDEV=1
SPDK_TEST_IOAT=0
SPDK_TEST_EVENT=1
SPDK_TEST_BLOBFS=0
SPDK_TEST_NVML=0
SPDK_TEST_LVOL=0
SPDK_TEST_VPP=0
SPDK_TEST_CRYPTO=1
SPDK_TEST_REDUCE=0
SPDK_TEST_OCF=0
SPDK_RUN_ASAN=1
SPDK_RUN_UBSAN=1
SPDK_TEST_VHOST_INIT=0
RUN_NIGHTLY=$RUN_NIGHTLY
```

**Comment by peluse** [comment] 2019-04-23 23:22
The root cause to the failure was a combination of aesni, ipsec and dpdk latest greatest all needing to be lined up.  CI didn't catch this because it was only testing on QAT which was not affected.

Jim has this patch to address this issue: https://review.gerrithub.io/c/spdk/spdk/+/451784

**Comment by darsto** [comment] 2019-04-25 07:32
The patch above just adds an extra test, I believe the actual fix is here:
https://review.gerrithub.io/c/spdk/spdk/+/449357 ipsec: move to version 0.52
It's merged.


@karlatec can you add `set -e` to that job now?

**Comment by darsto** [comment] 2019-04-25 07:47
Uhh wait, our ubuntu17 machine uses an outdated nasm version and fails on compilation right now.

@karlatec could you update nasm on that machine to at least 2.13.03?

**Comment by darsto** [comment] 2019-04-25 09:03
> @karlatec could you update nasm on that machine to at least 2.13.03?

Assigning to @nedved1 . Pawel, can you take a look at that?

**Comment by nedved1** [comment] 2019-04-25 14:24
@darsto @karlatec I've installed nasm 2.14.02 and autotest passes on ubuntu17 machines. We might wait for some time before setting -e flag in ubuntu17 job so people could rebase on top of Pauls patch.

**Comment by darsto** [comment] 2019-04-25 16:01
Good call @nedved1 . Let's wait at least until Monday

**Comment by karlatec** [comment] 2019-04-26 08:09
@nedved1 Did you also update nasm on Ubuntu 18 VMs? Remember, once this bug is fixed we'd like to replace old Ubuntu 17 VMs.

**Comment by nedved1** [comment] 2019-04-26 08:20
@karlatec yup

**Comment by karlatec** [comment] 2019-04-26 08:21
@nedved1 Cool, thanks!

**Comment by wanghailiangx** [comment] 2019-04-29 08:45
Now all test results on ubuntu17 look good. This issue can be closed.

**Closed** 2019-04-29 11:13 UTC
Labels: High, Infrastructure, bug

**Comment by nedved1** [comment] 2019-05-06 13:10
Flag is set on Jenkins Ubuntu17 job.
