### ISSUE TITLE
huge files not be deleted when option -R specified

### ISSUE THREAD

**Issue by wuzhouhui** [spdk/spdk#427] opened 2018-09-06 09:44 UTC
Start vhost app with option -R specified, but huge files in hugetlbfs not be deleted after app initialized

## Expected Behavior

huge files in hugetlbfs be deleted after app initialized if option -R specified

## Current Behavior

huge files not be deleted if option -R specified

## Steps to Reproduce

1. Start vhost app with option -R specified: `./vhost -R`
2. Check if huge files  in hugetlbfs got deleted after vhost initialized

## Context (Environment including OS version, SPDK version, etc.)

SPDK: b98bbb18c6
OS: CentOS 7.4

**Comment by ChenWang01** [comment] 2018-09-12 05:44
I check this issue with master branch(43ab58b613373ac424bca82797827da0d040554a)
The huge files can't be deleted when start  Vhost and issci target with "-R".
And the huge files can't be deleted when start NVMf-oF target with "-R".

**Comment by pawelwod** [comment] 2018-09-14 10:12
It is broken in DPDK >= 18.05 by commit
> 66cc45e293ed ("mem: replace memseg with memseg lists")

I will send a fix to both DPDK community and SPDK fork.
Stay tuned :)

**Comment by liang2yan** [comment] 2018-09-20 04:52
@pawelwod , any patch link for this issue?

**Comment by pawelwod** [comment] 2018-09-20 08:15
yes, in review

https://review.gerrithub.io/#/c/425577/
https://review.gerrithub.io/#/c/425576/
https://review.gerrithub.io/#/c/425578/

Works for me, but I need to ask Anatoly if this is the right fix.

**Comment by ChenWang01** [comment] 2018-10-16 07:51
Since these patches have been merged into the spdk/dpdk repository, I use the "git submodule update --init" to download the DPDK code and checkout to the spdk-18.08 branch, but i can't find the changes in https://review.gerrithub.io/c/spdk/dpdk/+/425578

**Comment by pawelwod** [comment] 2018-10-17 08:51
I asked @jimharris on IRC about this some time ago. He told me that the is some issue with sync gerrit <-> github on this patch. I tought that this was fixed but apparently not :(

**Comment by wanqunintel** [comment] 2018-10-18 05:03
Hi, @jimharris , will this gerrit<->github sync issue be fixed?

**Comment by jimharris** [comment] 2018-10-18 23:03
This should be fixed now.

**Comment by ChenWang01** [comment] 2018-10-19 02:34
Yeh , the gerrit<->github sync issue has been fixed, and we can find the changes in the github.
I have cloned the spdk/dpdk code with spdk-18.08 branch and compiled with SPDK master branch. 
The huge files can be deleted when used the vhost application with "-R", but the Nvmf and Iscsi target started failed.
Nvmf-tgt:
```
[root@host spdk]# ./app/nvmf_tgt/nvmf_tgt -R
Starting SPDK v18.10-pre / DPDK 18.11.0-rc0 initialization...
[ DPDK EAL parameters: nvmf --no-shconf -c 0x1 --huge-unlink --legacy-mem --file-prefix=spdk_pid79374 ]
EAL: Detected 44 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: Could not open '/dev/hugepages/spdk_pid79374map_4087': Too many open files
EAL: Couldn't remap hugepage files into memseg lists
EAL: FATAL: Cannot init memory

EAL: Cannot init memory

Failed to initialize DPDK
Unable to initialize SPDK env
```
Iscsi-tgt:
```
[root@host spdk]# ./app/iscsi_tgt/iscsi_tgt -R
Starting SPDK v18.10-pre / DPDK 18.11.0-rc0 initialization...
[ DPDK EAL parameters: iscsi --no-shconf -c 0x1 --huge-unlink --legacy-mem --file-prefix=spdk_pid79386 ]
EAL: Detected 44 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: Could not open '/dev/hugepages/spdk_pid79386map_4087': Too many open files
EAL: Couldn't remap hugepage files into memseg lists
EAL: FATAL: Cannot init memory

EAL: Cannot init memory

Failed to initialize DPDK
Unable to initialize SPDK env
iscsi_tgt.c: 114:main: *ERROR*: Start iscsi target daemon:  spdk_app_start() retn non-zero
```

**Comment by ChenWang01** [comment] 2018-10-30 07:54
I have used the SPDK master branch(3e2297140ca17ff97bda235b2b5962ebf185953f) and "git submodule update --init" to download the dpdk(96fae0e24c9088d9690c38098b25646f861a664b).
This issue can't be reproduced. So it can be closed.

**Closed** 2018-10-30 07:55 UTC
Labels: Low, bug
