### ISSUE TITLE
rpc timeout in nvmf_multipath test

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1588] opened 2020-09-02 09:23 UTC
https://ci.spdk.io/results/autotest-per-patch/builds/25344/archive/nvmf-tcp-uring-vg-autotest/build.log

Point of failure:
```
00:05:14.658   08:49:20	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe0 -t tcp -a 127.0.0.1 -s 4420 -f ipv4 -n nqn.2016-06.io.spdk:cnode1
00:05:14.955  NVMe0n1
00:05:14.968   08:49:20	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe0 -t tcp -a 127.0.0.1 -s 4421 -f ipv4 -n nqn.2016-06.io.spdk:cnode1
00:05:16.220  NVMe0n1
00:05:16.233   08:49:22	# rpc_pid=25386
00:05:16.233   08:49:22	# sleep 1
00:05:16.233   08:49:22	# /home/vagrant/spdk_repo/spdk/test/bdev/bdevperf/bdevperf.py -s /var/tmp/bdevperf.sock perform_tests
00:05:17.236   08:49:23	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 127.0.0.1 -s 4420
00:05:17.416   08:49:23	# sleep 3
00:05:20.419   08:49:26	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe0 -t tcp -a 127.0.0.1 -s 4422 -f ipv4 -n nqn.2016-06.io.spdk:cnode1
00:06:16.355  Timeout while waiting for response:
00:06:16.355  
00:06:16.355  
00:06:20.632  Timeout while waiting for response:
00:06:20.632  
00:06:20.632  
00:06:20.646    08:50:26	# trap - ERR
00:06:20.646    08:50:26	# print_backtrace
00:06:20.646    08:50:26	# [[ ehxBET =~ e ]]
00:06:20.646    08:50:26	# args=("${BASH_ARGV[@]}")
00:06:20.646    08:50:26	# local args
00:06:20.646    08:50:26	# xtrace_disable
00:06:20.646    08:50:26	# '[' no '!=' yes ']'
00:06:20.646    08:50:26	# PREV_BASH_OPTS=ehxBET
00:06:20.646    08:50:26	# [[ ehxBET == *\x* ]]
00:06:20.646    08:50:26	# XTRACE_DISABLED=yes
00:06:20.646    08:50:26	# set +x
00:06:20.646  ========== Backtrace start: ==========
00:06:20.646  
00:06:20.658  in test/nvmf/host/multipath.sh:50 -> main(["--transport=tcp"])
00:06:20.658       ...
00:06:20.658     45  	
00:06:20.658     46  	$rpc_py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_PORT
00:06:20.658     47  	
00:06:20.658     48  	sleep 3
00:06:20.658     49  	
00:06:20.658  => 50  	$rpc_py -s $bdevperf_rpc_sock bdev_nvme_attach_controller -b NVMe0 -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_THIRD_PORT -f ipv4 -n nqn.2016-06.io.spdk:cnode1
00:06:20.658     51  	$rpc_py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_SECOND_PORT
00:06:20.658     52  	
00:06:20.658     53  	sleep 3
00:06:20.658     54  	
00:06:20.658     55  	# Give the admin qpair time to fail before we add the new listener in. This prevents us from trying to connect to the wrong trid.
00:06:20.658       ...
00:06:20.658  
00:06:20.658  ========== Backtrace end ==========
```

This caused `bdevperf` to hang what led to build timeout (`wait()` blocked for too long):
```
00:06:28.794    08:43:42	# xtrace_enable
00:06:28.794    08:43:42	# return 0
00:06:28.794   08:43:42	# process_shm --id 0
00:06:28.794   08:43:42	# type=--id
00:06:28.794   08:43:42	# id=0
00:06:28.794   08:43:42	# '[' --id = --pid ']'
00:06:28.794   08:43:42	# '[' --id = --id ']'
00:06:28.794   08:43:42	# id=0
00:06:28.794    08:43:42	# find /dev/shm -name '*.0' -printf '%f\n'
00:06:28.798   08:43:42	# shm_files=nvmf_trace.0
00:06:28.798   08:43:42	# [[ -z nvmf_trace.0 ]]
00:06:28.798   08:43:42	# for n in $shm_files
00:06:28.798   08:43:42	# tar -C /dev/shm/ -cvzf /home/vagrant/spdk_repo/spdk/../output/nvmf_trace.0_shm.tar.gz nvmf_trace.0
00:06:28.803  nvmf_trace.0
00:06:29.752   08:43:43	# return 0
00:06:29.752   08:43:43	# rm -f /home/vagrant/spdk_repo/spdk/test/nvmf/host/try.txt
00:06:29.753   08:43:43	# killprocess 25141
00:06:29.753   08:43:43	# '[' -z 25141 ']'
00:06:29.753   08:43:43	# kill -0 25141
00:06:29.754    08:43:43	# uname
00:06:29.755   08:43:43	# '[' Linux = Linux ']'
00:06:29.756    08:43:43	# ps --no-headers -o comm= 25141
00:06:29.765  killing process with pid 25141
00:06:29.765   08:43:43	# process_name=reactor_0
00:06:29.765   08:43:43	# '[' reactor_0 = sudo ']'
00:06:29.765   08:43:43	# echo 'killing process with pid 25141'
00:06:29.765   08:43:43	# kill 25141
00:06:29.765   08:43:43	# wait 25141
00:15:00.257  Build timed out (after 15 minutes). Marking the build as failed.
00:15:00.264  Build was aborted
```

**Comment by spdkci** [comment] 2020-09-02 09:24
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_25343.html

**Comment by spdkci** [comment] 2020-09-02 09:24
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_25344.html

**Comment by spdkci** [comment] 2020-09-02 11:41
Another instance of this failure. Reported by @Donaim. log: https://ci.spdk.io/public_build/autotest-per-patch_25355.html

**Comment by spdkci** [comment] 2020-09-02 15:33
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_25371.html

**Comment by spdkci** [comment] 2020-09-02 17:50
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_25379.html

**Comment by spdkci** [comment] 2020-09-02 23:23
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_25423.html

**Comment by changpe1** [comment] 2020-09-03 02:23
@yidong0635 could you take a look ? the issue is happening very frequently.

**Comment by spdkci** [comment] 2020-09-03 15:40
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_25457.html

**Comment by spdkci** [comment] 2020-09-03 16:57
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_25464.html

**Comment by spdkci** [comment] 2020-09-04 06:06
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_25511.html

**Comment by spdkci** [comment] 2020-09-04 07:07
Another instance of this failure. Reported by @Donaim. log: https://ci.spdk.io/public_build/autotest-per-patch_25496.html

**Comment by spdkci** [comment] 2020-09-04 08:22
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_25504.html

**Comment by spdkci** [comment] 2020-09-04 10:53
Another instance of this failure. Reported by @Donaim. log: https://ci.spdk.io/public_build/autotest-per-patch_25518.html

**Comment by spdkci** [comment] 2020-09-07 06:04
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_25550.html

**Comment by spdkci** [comment] 2020-09-07 13:03
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_25597.html

**Comment by spdkci** [comment] 2020-09-08 01:55
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_25585.html

**Comment by yidong0635** [comment] 2020-09-08 03:00
put test patch serials to address this:
 https://review.spdk.io/gerrit/c/spdk/spdk/+/4045
let us see what will happen, if this happens still frequently, need to simplify the test case.

**Comment by spdkci** [comment] 2020-09-08 09:56
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_25662.html

**Comment by spdkci** [comment] 2020-09-08 10:48
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_25666.html

**Comment by spdkci** [comment] 2020-09-08 11:57
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_25669.html

**Comment by spdkci** [comment] 2020-09-08 15:10
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_25682.html

**Comment by spdkci** [comment] 2020-09-08 21:19
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_25708.html

**Comment by spdkci** [comment] 2020-09-08 21:33
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_25710.html

**Comment by spdkci** [comment] 2020-09-08 22:17
Another instance of this failure. Reported by @benlwalker. log: https://ci.spdk.io/public_build/autotest-per-patch_25715.html

**Comment by spdkci** [comment] 2020-09-08 22:19
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_25714.html

**Comment by spdkci** [comment] 2020-09-09 00:04
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_25720.html

**Comment by spdkci** [comment] 2020-09-09 00:05
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_25726.html

**Comment by spdkci** [comment] 2020-09-09 01:18
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_25740.html

**Comment by spdkci** [comment] 2020-09-09 02:18
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_25742.html

**Comment by spdkci** [comment] 2020-09-09 11:21
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_25780.html

**Comment by spdkci** [comment] 2020-09-09 12:36
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_25792.html

**Comment by spdkci** [comment] 2020-09-09 15:34
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_25800.html

**Comment by spdkci** [comment] 2020-09-09 19:54
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_25813.html

**Comment by spdkci** [comment] 2020-09-10 04:40
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_25814.html

**Comment by spdkci** [comment] 2020-09-10 18:07
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_25863.html

**Comment by spdkci** [comment] 2020-09-10 18:48
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_25875.html

**Comment by spdkci** [comment] 2020-09-11 03:40
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_25897.html

**Comment by spdkci** [comment] 2020-09-11 07:55
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_25901.html

**Comment by spdkci** [comment] 2020-09-11 13:53
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_25934.html

**Comment by spdkci** [comment] 2020-09-14 04:21
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_25961.html

**Comment by spdkci** [comment] 2020-09-14 12:50
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_25985.html

**Comment by yidong0635** [comment] 2020-09-15 08:20
only one issue can be found util now , it has been resolved by Changpeng's patch which has already been merged:
 https://review.spdk.io/gerrit/c/spdk/spdk/+/4143/2
And no other issue can be found in normal path:
use this test : https://review.spdk.io/gerrit/c/spdk/spdk/+/4088/12

**Comment by spdkci** [comment] 2020-09-16 07:58
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_26022.html

**Comment by spdkci** [comment] 2020-09-16 09:43
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_26048.html

**Comment by spdkci** [comment] 2020-09-16 11:25
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_26062.html

**Comment by spdkci** [comment] 2020-09-16 12:23
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_26070.html

**Comment by spdkci** [comment] 2020-09-16 12:37
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_26074.html

**Comment by spdkci** [comment] 2020-09-16 19:36
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_26126.html

**Comment by jimharris** [comment] 2020-09-16 19:50
I'm able to reproduce this locally in a VM.  Will start debugging this further.

**Comment by jimharris** [comment] 2020-09-16 20:29
bdevperf is hung in an I/O abort loop.  We don't see this in any of the logs on this issue, since the bdevperf output is redirected to try.txt to do some grepping later in the test.

This just keeps continuing forever.  We get the RPC timeout since presumably this loop is preventing bdevperf from responding to the RPC sent by bdevperf.py.

Continuing to debug, but getting closer to root cause...

[2020-09-16 20:15:39.951869] nvme_qpair.c: 535:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
   1110 [2020-09-16 20:15:39.951877] nvme_qpair.c: 268:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:0 nsid:1 lba:45200 len:8 PRP1 0x0 PRP2 0x0
   1111 [2020-09-16 20:15:39.951884] nvme_qpair.c: 451:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:1 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
   1112 [2020-09-16 20:15:39.951893] nvme_qpair.c: 553:_nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
   1113 [2020-09-16 20:15:39.951904] nvme_qpair.c: 535:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
   1114 [2020-09-16 20:15:39.951912] nvme_qpair.c: 268:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:0 nsid:1 lba:45208 len:8 PRP1 0x0 PRP2 0x0
   1115 [2020-09-16 20:15:39.951919] nvme_qpair.c: 451:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:1 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
   1116 [2020-09-16 20:15:39.951927] nvme_qpair.c: 553:_nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
   1117 [2020-09-16 20:15:39.951935] nvme_qpair.c: 535:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
   1118 [2020-09-16 20:15:39.951942] nvme_qpair.c: 268:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:0 nsid:1 lba:45216 len:

**Comment by spdkci** [comment] 2020-09-16 21:18
Another instance of this failure. Reported by @benlwalker. log: https://ci.spdk.io/public_build/autotest-per-patch_26137.html

**Comment by spdkci** [comment] 2020-09-16 21:20
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_26135.html

**Comment by spdkci** [comment] 2020-09-16 21:53
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_26147.html

**Comment by spdkci** [comment] 2020-09-16 23:18
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_26161.html

**Comment by jimharris** [comment] 2020-09-16 23:29
Confirmed root cause and fix:  https://review.spdk.io/gerrit/c/spdk/spdk/+/4284

**Comment by spdkci** [comment] 2020-09-16 23:29
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_26165.html

**Comment by spdkci** [comment] 2020-09-17 00:40
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_26174.html

**Comment by spdkci** [comment] 2020-09-17 06:25
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_26184.html

**Comment by spdkci** [comment] 2020-09-17 09:22
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_26159.html

**Comment by spdkci** [comment] 2020-09-17 09:22
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_26145.html

**Comment by spdkci** [comment] 2020-09-17 15:27
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_26247.html

**Comment by spdkci** [comment] 2020-09-17 15:51
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_26175.html

**Comment by spdkci** [comment] 2020-09-17 21:28
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_26284.html

**Comment by spdkci** [comment] 2020-09-17 21:28
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_26290.html

**Comment by jimharris** [comment] 2020-09-17 21:35
Patch merged.

**Closed by jimharris** 2020-09-17 21:35 UTC
Labels: Intermittent Failure

**Comment by spdkci** [comment] 2020-09-17 22:33
Another instance of this failure. Reported by @floatious. log: https://ci.spdk.io/public_build/autotest-per-patch_26296.html
