### ISSUE TITLE
[nvmf_perf_adq] reads completed with errors

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2577] opened 2022-07-06 22:59 UTC
00:11:47.220  starting I/O failed
00:11:47.220  Read completed with error (sct=0, sc=8)
00:11:47.220  Read completed with error (sct=0, sc=8)
00:11:47.220  [2022-07-07 00:37:11.387009] nvme_qpair.c: 741:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 1
00:11:47.220  NVMe io qpair process completion error
00:11:47.220  Read completed with error (sct=0, sc=8)
00:11:47.220  Read completed with error (sct=0, sc=8)
00:11:47.220  Read completed with error (sct=0, sc=8)
00:11:47.220  starting I/O failed
00:11:47.220  Read completed with error (sct=0, sc=8)
00:11:47.220  Read completed with error (sct=0, sc=8)
00:11:47.220  Read completed with error (sct=0, sc=8)
00:11:47.220  Read completed with error (sct=0, sc=8)
00:11:47.220  starting I/O failed
00:11:47.220  Read completed with error (sct=0, sc=8)
00:11:47.221  Read completed with error (sct=0, sc=8)
00:11:47.221  Read completed with error (sct=0, sc=8)
00:11:47.221  Read completed with error (sct=0, sc=8)
00:11:47.221  starting I/O failed
00:11:47.221  Read completed with error (sct=0, sc=8)
00:11:47.221  Read completed with error (sct=0, sc=8)
00:11:47.221  Read completed with error (sct=0, sc=8)
00:11:47.221  Read completed with error (sct=0, sc=8)
00:11:47.221  starting I/O failed
00:11:47.221  Read completed with error (sct=0, sc=8)
00:11:47.221  [2022-07-07 00:37:11.387440] nvme_qpair.c: 741:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 5
00:11:47.221  NVMe io qpair process completion error
00:11:47.221  Read completed with error (sct=0, sc=8)
00:11:47.221  Read completed with error (sct=0, sc=8)
00:11:47.221  Initializing NVMe Controllers
00:11:47.221  Attached to NVMe over Fabrics controller at 10.0.0.2:4420: nqn.2016-06.io.spdk:cnode1
00:11:47.221  Associating TCP (addr:10.0.0.2 subnqn:nqn.2016-06.io.spdk:cnode1) NSID 1 with lcore 4
00:11:47.221  Associating TCP (addr:10.0.0.2 subnqn:nqn.2016-06.io.spdk:cnode1) NSID 1 with lcore 5
00:11:47.221  Associating TCP (addr:10.0.0.2 subnqn:nqn.2016-06.io.spdk:cnode1) NSID 1 with lcore 6
00:11:47.221  Initialization complete. Launching workers.
00:11:47.221  Read completed with error (sct=0, sc=8)
00:11:47.482   00:37:11	-- nvmf/common.sh@444 -- # '[' '' == iso ']'
00:11:47.482   00:37:11	-- nvmf/common.sh@447 -- # [[ tcp == \t\c\p ]]
00:11:47.482   00:37:11	-- nvmf/common.sh@448 -- # nvmf_tcp_fini
00:11:47.482   00:37:11	-- nvmf/common.sh@261 -- # [[ eth8_ns_spdk == \n\v\m\f\_\t\g\t\_\n\s ]]
00:11:47.482   00:37:11	-- nvmf/common.sh@265 -- # remove_spdk_ns
00:11:47.482   00:37:11	-- nvmf/common.sh@546 -- # local ns
00:11:47.482   00:37:11	-- nvmf/common.sh@547 -- # read -r ns _
00:11:47.482    00:37:11	-- nvmf/common.sh@545 -- # ip netns list
00:11:47.482   00:37:11	-- nvmf/common.sh@548 -- # [[ eth8_ns_spdk == *_spdk ]]
00:11:47.482   00:37:11	-- nvmf/common.sh@549 -- # ip netns delete eth8_ns_spdk
00:11:47.482   00:37:11	-- nvmf/common.sh@547 -- # read -r ns _
00:11:47.482   00:37:11	-- nvmf/common.sh@552 -- # sleep 1
00:11:48.424   00:37:12	-- nvmf/common.sh@266 -- # ip -4 addr flush eth9
00:11:48.424   00:37:12	-- target/perf_adq.sh@1 -- # exit 1
00:11:48.424    00:37:12	-- common/autotest_common.sh@970 -- # trap - ERR
00:11:48.424    00:37:12	-- common/autotest_common.sh@970 -- # print_backtrace
00:11:48.424    00:37:12	-- common/autotest_common.sh@998 -- # [[ ehxBET =~ e ]]
00:11:48.424    00:37:12	-- common/autotest_common.sh@1000 -- # args=('--transport=tcp' 'test/nvmf/target/perf_adq.sh' 'nvmf_perf_adq' '--transport=tcp')
00:11:48.424    00:37:12	-- common/autotest_common.sh@1000 -- # local args
00:11:48.424    00:37:12	-- common/autotest_common.sh@1002 -- # xtrace_disable
00:11:48.424    00:37:12	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:11:48.424    00:37:12	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:11:48.424    00:37:12	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:11:48.424    00:37:12	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:11:48.424    00:37:12	-- common/autotest_common.sh@19 -- # set +x
00:11:48.424  ========== Backtrace start: ==========

**Comment by spdkci** [comment] 2022-07-06 22:59
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_79904.html

**Comment by wanqunintel** [comment] 2022-07-07 00:24
@wanghailiangx , will you check this issue?

**Comment by wanghailiangx** [comment] 2022-07-07 02:18
@wanqunintel OK, but it's hard to reproduce locally.

**Comment by changpe1** [comment] 2022-07-07 04:10
00:11:52.412   01:27:59	-- target/perf_adq.sh@165 -- # [[ 1 -ne 2 ]]
00:11:52.412   01:27:59	-- target/perf_adq.sh@166 -- # echo 'ERROR: num_busy_count != tc1 queues of traffic classes! Testcase 2 failed.'
00:11:52.412  ERROR: num_busy_count != tc1 queues of traffic classes! Testcase 2 failed.
00:11:52.412   01:27:59	-- target/perf_adq.sh@167 -- # exit 1

The actual error is in above messages.

**Comment by Comphix** [comment] 2022-07-08 01:44
Hailiang, in our CI, do you know which firmware version is used? Looks like it is more relating to the firmware version?

**Comment by wanghailiangx** [comment] 2022-07-08 01:57
@Comphix I can push a test patch to look which firmware version is used in our CI, run a few more times and I'll find more machines. But I'd better confirm this locally first.

**Comment by changpe1** [comment] 2022-07-08 02:02
> @Comphix I can push a test patch to look which firmware version is used in our CI, run a few more times and I'll find more machines. But I'd better confirm this locally first.

Beside to root cause the issue, as Jim mentioned above, it's worth to add more comment to explain in detail the relationship with ADQ and core count.

**Comment by wanghailiangx** [comment] 2022-07-08 08:54
After upgrading the firmware from v1.40 to v2.30 or v3.20 on local, I tested it many times, this issue did not recur. It was effective. Next, I'll test it a few more times. In addition, I'm going to push a patch adding comments about num_busy_count() and look at the firmware version on CI.

**Comment by spdkci** [comment] 2022-07-13 17:39
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_80295.html

**Comment by spdkci** [comment] 2022-07-14 11:58
Another instance of this failure. Reported by @kgodzwox. log: https://ci.spdk.io/public_build/autotest-per-patch_80367.html

**Comment by spdkci** [comment] 2022-07-15 06:53
Another instance of this failure. Reported by @kgodzwox. log: https://ci.spdk.io/public_build/autotest-per-patch_80411.html

**Comment by spdkci** [comment] 2022-07-22 08:03
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_80985.html

**Comment by spdkci** [comment] 2022-07-23 16:29
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_81081.html

**Comment by spdkci** [comment] 2022-07-25 08:26
Another instance of this failure. Reported by @tae-kyung-kim. log: https://ci.spdk.io/public_build/autotest-per-patch_81096.html

**Comment by spdkci** [comment] 2022-07-26 04:11
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_81183.html

**Comment by spdkci** [comment] 2022-07-27 09:15
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_81309.html

**Comment by spdkci** [comment] 2022-07-28 12:11
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_81440.html

**Comment by spdkci** [comment] 2022-07-28 15:19
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_81482.html

**Comment by spdkci** [comment] 2022-07-28 15:21
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_81478.html

**Comment by spdkci** [comment] 2022-08-03 07:59
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_81739.html

**Comment by benlwalker** [comment] 2022-08-03 23:01
The bug here is that the assignment of connections to rx queues (i.e. NAPI ids) in the driver is not perfectly round-robin. But SPDK does not need to know the algorithm at all - instead we can verify that the connections are grouped into at most the same number of groups as traffic classes.

There's also a far easier way to examine how the connections have been assigned to poll groups using the `nvmf_get_stats` RPC. See https://review.spdk.io/gerrit/c/spdk/spdk/+/13833 for the fix.

**Comment by wanghailiangx** [comment] 2022-08-04 07:50
@benlwalker Thank you very much for finding `nvmf_get_stats` and submitting the patch. I have given some comments on it.
The results observed by this method are consistent with the RPC method.
watch -d "sudo ethtool -S $NVMF_TARGET_INTERFACE | grep -v \": 0\" | column"
So I suspect there is still something wrong with the ADQ hardware queue.

**Closed** 2022-08-12 09:00 UTC
Labels: bug, Low, Intermittent Failure, Patches out for review
