### ISSUE TITLE
[make test] ERROR: Clock skew detected. File /build-tmp/../meson.build has a time stamp 3194.0314s in the future.

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1796] opened 2021-02-17 04:55 UTC
```
00:03:46.873  Build targets in project: 125
00:03:46.873  
00:03:46.873  Found ninja-1.10.0.git.kitware.jobserver-1 at /usr/local/bin/ninja
00:03:46.873  
00:03:46.873  ERROR: Clock skew detected. File /home/vagrant/spdk_repo/spdk/dpdk/build-tmp/../meson.build has a time stamp 3194.0314s in the future.
00:03:46.873  
00:03:46.873  A full log can be found at /home/vagrant/spdk_repo/spdk/dpdk/build-tmp/meson-logs/meson-log.txt
00:03:46.935  make[1]: *** [/home/vagrant/spdk_repo/spdk/dpdk/build-tmp] Error 1
00:03:46.936  make: *** [dpdkbuild] Error 2
00:03:46.936    02:23:25	$ trap - ERR
00:03:46.936    02:23:25	$ print_backtrace
00:03:46.937    02:23:25	$ [[ ehxBE =~ e ]]
00:03:46.937    02:23:25	$ args=("${BASH_ARGV[@]}")
00:03:46.937    02:23:25	$ local args
00:03:46.937    02:23:25	$ xtrace_disable
00:03:46.937    02:23:25	$ '[' no '!=' yes ']'
00:03:46.938    02:23:25	$ PREV_BASH_OPTS=ehxBE
00:03:46.938    02:23:25	$ [[ ehxBE == *\x* ]]
00:03:46.938    02:23:25	$ XTRACE_DISABLED=yes
00:03:46.938    02:23:25	$ set +x
00:03:46.938  ========== Backtrace start: ==========
00:03:46.938  
00:03:46.954  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:925 -> run_test(["make"],["make"],["-j10"])
00:03:46.954       ...
00:03:46.954     920 		timing_enter $test_name
00:03:46.954     921 		echo "************************************"
00:03:46.954     922 		echo "START TEST $test_name"
00:03:46.954     923 		echo "************************************"
00:03:46.954     924 		xtrace_restore
00:03:46.954  => 925 		time "$@"
00:03:46.954     926 		xtrace_disable
00:03:46.954     927 		echo "************************************"
00:03:46.954     928 		echo "END TEST $test_name"
00:03:46.954     929 		echo "************************************"
00:03:46.954     930 		timing_exit $test_name
00:03:46.954       ...
00:03:46.963  in /home/vagrant/spdk_repo/spdk/autobuild.sh:293 -> main(["/home/vagrant/autorun-spdk.conf"])
00:03:46.963       ...
00:03:46.963     288 		if [ "$SPDK_TEST_OCF" -eq 1 ]; then
00:03:46.963     289 			run_test "autobuild_ocf_precompile" ocf_precompile
00:03:46.963     290 		fi
00:03:46.963     291 		# if we aren't testing the unittests, build with shared objects.
00:03:46.963     292 		./configure $config_params --with-shared
00:03:46.963  => 293 		run_test "make" $MAKE $MAKEFLAGS
00:03:46.963     294 	fi
00:03:46.963       ...
00:03:46.963  
00:03:46.963  ========== Backtrace end ==========
00:03:46.963    02:23:25	$ xtrace_enable
00:03:46.963    02:23:25	$ return 0
00:03:46.964   02:23:25	$ [[ -d /tmp/spdk_1613528599.eQ3Ua0 ]]
00:03:46.964   02:23:25	$ rm -rf /tmp/spdk_1613528599.eQ3Ua0
00:03:47.010  + vagrant destroy -f
00:03:49.884  If run with libvirt provider please execute create_nvme_img.sh
00:03:50.064  If run with libvirt provider please execute create_nvme_img.sh
00:03:50.261  If run with libvirt provider please execute create_nvme_img.sh
00:03:50.317  If run with libvirt provider please execute create_nvme_img.sh
00:03:50.343  If run with libvirt provider please execute create_nvme_img.sh
00:03:50.468  If run with libvirt provider please execute create_nvme_img.sh
00:03:50.537  If run with libvirt provider please execute create_nvme_img.sh
00:03:50.646  If run with libvirt provider please execute create_nvme_img.sh
00:03:51.389  ==> default: Removing domain...
00:03:51.693  Build step 'Execute shell' marked build as failure
00:03:51.758  [PostBuildScript] - [INFO] Executing post build scripts.
00:03:51.765  [centos7-vg-autotest] $ /usr/bin/env bash /tmp/jenkins18039750680842626410.sh
00:03:51.768  + [[ -n centos7 ]]
00:03:51.769  + mv /var/jenkins/workspace/centos7-vg-autotest/centos7-libvirt/output /var/jenkins/workspace/centos7-vg-autotest/output
00:03:51.787  [centos7-vg-autotest] $ /usr/bin/env bash /tmp/jenkins2856229667969807695.sh
00:03:51.790  Start stage post_get_build_log.sh

```

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_36675.html

## Execution failed at

See the above

**Comment by spdkci** [comment] 2021-02-17 05:55
Another instance of this failure. Reported by @shuhei-matsumoto. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36686.html

**Comment by spdkci** [comment] 2021-02-17 06:00
Another instance of this failure. Reported by @AlekseyMarchuk. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36649.html

**Comment by tomzawadzki** [comment] 2021-02-17 10:34
That's an interesting failure. Might be caused by patch https://review.spdk.io/gerrit/c/spdk/spdk/+/2693.
The time between Gerrit instance (that generates tar) and particular VM might be out of sync, which is most likely the reason for this failure.

Yet more worrying is how the patch could affect other builds. I was under assumption that data in VMs is not persisted between builds, especially under $rootdir [directory with SPDK repo for test]. @wawryk Any suggestions why this is the case ?

**Comment by wawryk** [comment] 2021-02-17 10:44
New centos boxes was deployed now to our CI servers. 
In every build we start new, fresh vm, and there should not be any old artifacts, will take a closer look on it.

**Comment by mikeBashStuff** [comment] 2021-02-17 10:53
Why do we suspect that it has anything to do with the leftovers artifacts inside the VM though? Is it something in the logs (like a file specific to that TEST patchset)? To me this looks like either a blip in the ntp sync (considering reported timestamp, VMs are kept in UTC and synced against our NTP pool so the difference between vhost and the VM should be of 1h right now. Maybe clock was adjusted right after the build started). or vhost's sys clock (from which repo is synced onto VM) is wonky maybe.

**Comment by mikeBashStuff** [comment] 2021-02-17 11:07
I just logged onto VM-host-SM9 and its sys clock is a bit off. Considering how off, it may explain the issue above as it matches, more or less, the clock skew reported above.

```
root@supermicro9:~# readlink -f /etc/localtime; date
/usr/share/zoneinfo/Poland
Wed Feb 17 13:00:19 CET 2021
root@supermicro9:~#
```

**Comment by wawryk** [comment] 2021-02-17 11:30
Time on sm9 synchronized

**Comment by tomzawadzki** [comment] 2021-03-09 11:28
Last I've heard, @mikeBashStuff was working on tuning up the NTP services across the servers. Is the work complete and the issue can be closed ?

**Comment by mikeBashStuff** [comment] 2021-03-09 13:36
@tomzawadzki I think this issue can be closed since sys clocks across most of the systems are currently in sync with the ntp pool. There's a patch on the jenkins side which introduces small adjustments for the `chrony` config (since this issue got opened, this was handled manually on SM9) but it hasn't been merged yet.

**Comment by spdkci** [comment] 2022-03-08 12:17
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_72913.html

**Comment by tomzawadzki** [comment] 2022-03-08 12:18
Failure above occurred on VM-host-PE1

**Comment by tomzawadzki** [comment] 2022-04-05 11:15
No new reports for a month, closing.

**Closed by tomzawadzki** 2022-04-05 11:15 UTC
Labels: Infrastructure, Intermittent Failure
