### ISSUE TITLE
crypto-autotest failed due to an unknown reason

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1762] opened 2021-01-25 15:44 UTC
https://ci.spdk.io/results/autotest-per-patch/builds/35196/archive/crypto-autotest/build.log

It seems like the job failed for no particular reason, can't find anything relevant in the log (no traces, no obvious indication of a timeout, etc.)

**Comment by spdkci** [comment] 2021-01-25 15:45
Another instance of this failure. Reported by @mikeBashStuff. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_35196.html

**Comment by tomzawadzki** [comment] 2021-01-26 09:20
The build was aborted:
```
00:15:00.356  Build timed out (after 15 minutes). Marking the build as failed.
00:15:00.365  Build was aborted
00:15:00.366  [PostBuildScript] - [INFO] Executing post build scripts.
```

This is due to cloning taking 2,5 min where the job itself is already pretty close to the timeout value of 15min:
```
00:00:00.389  Start stage copy_or_clone.sh
00:00:00.391  MANUAL, will clone
00:00:00.393  Cloning into '/var/jenkins/workspace/crypto-autotest/spdk'...
00:00:04.580  warning: redirecting to https://review.spdk.io/gerrit/spdk/spdk/
00:01:32.664  git version 2.26.2
00:01:35.542  warning: redirecting to https://review.spdk.io/gerrit/spdk/spdk/
00:02:29.544  remote: Counting objects: 1           
remote: Counting objects: 92, done        
```

As such this is duplicate of #1686

**Closed by tomzawadzki** 2021-01-26 09:20 UTC
Labels: Intermittent Failure
