### ISSUE TITLE
[nvmf-phy-autotest] nvmf_target_disconnect_tc3 lots of failures

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1973] opened 2021-06-02 00:59 UTC
00:15:23.078  ************************************
00:15:23.078  START TEST nvmf_target_disconnect_tc3
00:15:23.078  ************************************
00:15:23.079   01:54:27	# xtrace_enable
00:15:23.079   01:54:27	# nvmf_target_disconnect_tc3
00:15:23.079   01:54:27	# reconnectpid=288770
00:15:23.080   01:54:27	# sleep 2
00:15:23.080   01:54:27	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/build/examples/reconnect -q 32 -o 4096 -w randrw -M 50 -t 10 -c 0xF -r 'trtype:rdma adrfam:IPv4 traddr:192.168.100.8 trsvcid:4420 alt_traddr:192.168.100.9'
00:15:23.095  [2021-06-02 01:54:27.597399] Starting SPDK v21.07-pre git sha1 cbdbd2116 / DPDK 21.02.0 initialization...
00:15:23.095  [2021-06-02 01:54:27.597491] [ DPDK EAL parameters: [2021-06-02 01:54:27.597505] reconnect [2021-06-02 01:54:27.597514] --no-shconf [2021-06-02 01:54:27.597522] -c 0xF [2021-06-02 01:54:27.597530] --log-level=lib.eal:6 [2021-06-02 01:54:27.597537] --log-level=lib.cryptodev:5 [2021-06-02 01:54:27.597545] --log-level=user1:6 [2021-06-02 01:54:27.597554] --iova-mode=pa [2021-06-02 01:54:27.597561] --base-virtaddr=0x200000000000 [2021-06-02 01:54:27.597569] --match-allocations [2021-06-02 01:54:27.597577] --file-prefix=spdk_pid288770 [2021-06-02 01:54:27.597584] ]
00:15:23.127  EAL: No free 2048 kB hugepages reported on node 1
00:15:23.127  EAL: No available 1048576 kB hugepages reported
00:15:23.130  EAL: No legacy callbacks, legacy socket not created
00:15:25.082   01:54:29	# kill -9 288725
00:15:25.082   01:54:29	# sleep 2
00:15:26.247  [2021-06-02 01:54:30.749601] nvme_qpair.c: 717:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 on qpair id 0
00:15:26.247  [2021-06-02 01:54:30.749720] nvme_ctrlr.c: 923:nvme_ctrlr_fail: *ERROR*: [nqn.2016-06.io.spdk:cnode1] in failed state.
00:15:26.247  A controller has encountered a failure and is being reset.
00:15:26.247  Resorting to new failover address 192.168.100.9
00:15:26.247  [2021-06-02 01:54:30.749759] nvme_ctrlr.c: 917:nvme_ctrlr_fail: *NOTICE*: [nqn.2016-06.io.spdk:cnode1] already in failed state
00:15:26.247  [2021-06-02 01:54:30.749782] nvme_ctrlr.c:1398:spdk_nvme_ctrlr_reset: *NOTICE*: [nqn.2016-06.io.spdk:cnode1] resetting controller
00:15:26.249  [2021-06-02 01:54:30.751760] nvme_rdma.c: 529:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_ESTABLISHED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = 8)
00:15:26.249  [2021-06-02 01:54:30.751782] nvme_rdma.c:1081:nvme_rdma_connect: *ERROR*: RDMA connect error -74
00:15:26.249  [2021-06-02 01:54:30.751788] nvme_rdma.c:1189:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
00:15:27.085  test/nvmf/host/target_disconnect.sh: line 60: 288725 Killed                  "${NVMF_APP[@]}" "$@"
00:15:27.085   01:54:31	# disconnect_init 192.168.100.9
00:15:27.085   01:54:31	# nvmfappstart -m 0xF0
00:15:27.085   01:54:31	# timing_enter start_nvmf_tgt
00:15:27.086   01:54:31	# xtrace_disable
00:15:27.086   01:54:31	# '[' no '!=' yes ']'
00:15:27.086   01:54:31	# PREV_BASH_OPTS=ehxBET
00:15:27.086   01:54:31	# [[ ehxBET == *\x* ]]
00:15:27.086   01:54:31	# XTRACE_DISABLED=yes
00:15:27.087   01:54:31	# set +x
00:15:27.088   01:54:31	# xtrace_enable
00:15:27.088   01:54:31	# nvmfpid=288780
00:15:27.089   01:54:31	# waitforlisten 288780
00:15:27.089   01:54:31	# '[' -z 288780 ']'
00:15:27.089   01:54:31	# local rpc_addr=/var/tmp/spdk.sock
00:15:27.089   01:54:31	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/build/bin/nvmf_tgt -i 0 -e 0xFFFF -m 0xF0
00:15:27.090   01:54:31	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
00:15:27.090  Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
00:15:27.090   01:54:31	# xtrace_disable
00:15:27.090   01:54:31	# '[' no '!=' yes ']'
00:15:27.090   01:54:31	# PREV_BASH_OPTS=ehxBET
00:15:27.091   01:54:31	# [[ ehxBET == *\x* ]]
00:15:27.091   01:54:31	# XTRACE_DISABLED=yes
00:15:27.091   01:54:31	# set +x
00:15:27.122  [2021-06-02 01:54:31.624752] Starting SPDK v21.07-pre git sha1 cbdbd2116 / DPDK 21.02.0 initialization...
00:15:27.122  [2021-06-02 01:54:31.624820] [ DPDK EAL parameters: [2021-06-02 01:54:31.624829] nvmf [2021-06-02 01:54:31.624834] -c 0xF0 [2021-06-02 01:54:31.624840] --log-level=lib.eal:6 [2021-06-02 01:54:31.624846] --log-level=lib.cryptodev:5 [2021-06-02 01:54:31.624852] --log-level=user1:6 [2021-06-02 01:54:31.624857] --iova-mode=pa [2021-06-02 01:54:31.624862] --base-virtaddr=0x200000000000 [2021-06-02 01:54:31.624867] --match-allocations [2021-06-02 01:54:31.624872] --file-prefix=spdk0 [2021-06-02 01:54:31.624878] --proc-type=auto [2021-06-02 01:54:31.624883] ]
00:15:27.231  EAL: No free 2048 kB hugepages reported on node 1
00:15:27.231  EAL: No available 1048576 kB hugepages reported
00:15:27.231  EAL: No legacy callbacks, legacy socket not created
00:15:27.231  [2021-06-02 01:54:31.697619] app.c: 537:spdk_app_start: *NOTICE*: Total cores available: 4
00:15:27.253  [2021-06-02 01:54:31.755633] nvme_ctrlr.c:1414:spdk_nvme_ctrlr_reset: *ERROR*: [nqn.2016-06.io.spdk:cnode1] Controller reinitialization failed.
00:15:27.253  [2021-06-02 01:54:31.755683] nvme_ctrlr.c: 923:nvme_ctrlr_fail: *ERROR*: [nqn.2016-06.io.spdk:cnode1] in failed state.
00:15:27.253  Unable to reset the controller.
00:15:27.310  [2021-06-02 01:54:31.812839] app.c: 384:app_setup_trace: *NOTICE*: Tracepoint Group Mask 0xFFFF specified.
00:15:27.310  [2021-06-02 01:54:31.812895] app.c: 385:app_setup_trace: *NOTICE*: Use 'spdk_trace -s nvmf -i 0' to capture a snapshot of events at runtime.
00:15:27.310  [2021-06-02 01:54:31.812901] app.c: 390:app_setup_trace: *NOTICE*: Or copy /dev/shm/nvmf_trace.0 for offline analysis/debug.
00:15:27.311  [2021-06-02 01:54:31.813030] reactor.c: 939:reactor_run: *NOTICE*: Reactor started on core 5
00:15:27.311  [2021-06-02 01:54:31.813150] reactor.c: 939:reactor_run: *NOTICE*: Reactor started on core 6
00:15:27.311  [2021-06-02 01:54:31.813252] reactor.c: 939:reactor_run: *NOTICE*: Reactor started on core 4
00:15:27.311  [2021-06-02 01:54:31.813254] reactor.c: 939:reactor_run: *NOTICE*: Reactor started on core 7
00:15:27.311  [2021-06-02 01:54:31.813362] accel_engine.c: 885:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:15:27.403  Build timed out (after 15 minutes). Marking the build as failed.
00:15:27.421  Build was aborted
00:15:27.422  [PostBuildScript] - [INFO] Executing post build scripts.
00:15:27.431  [nvmf-phy-autotest] $ /usr/bin/env bash /tmp/jenkins2299813264066527735.sh
00:15:27.436  Start stage post_get_build_log.sh
00:15:27.872   01:54:32	# xtrace_enable
00:15:27.873   01:54:32	# (( i == 0 ))
00:15:27.873   01:54:32	# return 0
00:15:27.873   01:54:32	# timing_exit start_nvmf_tgt
00:15:27.873   01:54:32	# xtrace_disable
00:15:27.873   01:54:32	# '[' no '!=' yes ']'
00:15:27.873   01:54:32	# PREV_BASH_OPTS=ehxBET
00:15:27.873   01:54:32	# [[ ehxBET == *\x* ]]
00:15:27.873   01:54:32	# XTRACE_DISABLED=yes
00:15:27.873   01:54:32	# set +x
00:15:27.895   01:54:32	# xtrace_enable
00:15:27.895   01:54:32	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py bdev_malloc_create 64 512 -b Malloc0
00:15:28.047  Malloc0
00:15:28.056   01:54:32	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_create_transport -t rdma
00:15:28.258  Write completed with error (sct=0, sc=8)
00:15:28.258  starting I/O failed
00:15:28.258  Write completed with error (sct=0, sc=8)
00:15:28.258  starting I/O failed
00:15:28.258  Read completed with error (sct=0, sc=8)
00:15:28.258  starting I/O failed
00:15:28.258  Read completed with error (sct=0, sc=8)
00:15:28.258  starting I/O failed
00:15:28.258  Write completed with error (sct=0, sc=8)
00:15:28.258  starting I/O failed
00:15:28.258  Read completed with error (sct=0, sc=8)
00:15:28.258  starting I/O failed
00:15:28.258  Read completed with error (sct=0, sc=8)

**Comment by mikeBashStuff** [comment] 2021-06-02 07:19
Affected build: https://ci.spdk.io/public_build/autotest-per-patch_48832.html

**Comment by mikeBashStuff** [comment] 2021-06-02 07:42
The main reason why the build failed was the timeout it hit - there can be huge delays seen after, for instance, `filesystem_incapsule_xfs` test where `nvme disconnect ...` blocks for over a minute:

```
00:04:08.242   01:43:12	# nvme disconnect -n nqn.2016-06.io.spdk:cnode1
00:04:21.106  [2021-06-02 01:43:25.608095] ctrlr.c: 185:nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host nqn.2014-08.org.nvmexpress:uuid:67363ce608f44a64a054dc009bb4a1fe from subsystem nqn.2016-06.io.spdk:cnode1 due to keep alive timeout.
00:05:24.914  NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
```
Similar case is seen after `filesystem_xfs` test.

The errors from the description, mainly this:
```
00:15:23.080 01:54:27 # /var/jenkins/workspace/nvmf-phy-autotest/spdk/build/examples/reconnect -q 32 -o 4096 -w randrw -M 50 -t 10 -c 0xF -r 'trtype:rdma adrfam:IPv4 traddr:192.168.100.8 trsvcid:4420 alt_traddr:192.168.100.9'
00:15:23.095 [2021-06-02 01:54:27.597399] Starting SPDK v21.07-pre git sha1 cbdbd2116 / DPDK 21.02.0 initialization...
00:15:23.095 [2021-06-02 01:54:27.597491] [ DPDK EAL parameters: [2021-06-02 01:54:27.597505] reconnect [2021-06-02 01:54:27.597514] --no-shconf [2021-06-02 01:54:27.597522] -c 0xF [2021-06-02 01:54:27.597530] --log-level=lib.eal:6 [2021-06-02 01:54:27.597537] --log-level=lib.cryptodev:5 [2021-06-02 01:54:27.597545] --log-level=user1:6 [2021-06-02 01:54:27.597554] --iova-mode=pa [2021-06-02 01:54:27.597561] --base-virtaddr=0x200000000000 [2021-06-02 01:54:27.597569] --match-allocations [2021-06-02 01:54:27.597577] --file-prefix=spdk_pid288770 [2021-06-02 01:54:27.597584] ]
00:15:23.127 EAL: No free 2048 kB hugepages reported on node 1
00:15:23.127 EAL: No available 1048576 kB hugepages reported
00:15:23.130 EAL: No legacy callbacks, legacy socket not created
00:15:25.082 01:54:29 # kill -9 288725
00:15:25.082 01:54:29 # sleep 2
00:15:26.247 [2021-06-02 01:54:30.749601] nvme_qpair.c: 717:spdk_nvme_qpair_process_completions: ERROR: CQ transport error -6 on qpair id 0
00:15:26.247 [2021-06-02 01:54:30.749720] nvme_ctrlr.c: 923:nvme_ctrlr_fail: ERROR: [nqn.2016-06.io.spdk:cnode1] in failed state.
00:15:26.247 A controller has encountered a failure and is being reset.
00:15:26.247 Resorting to new failover address 192.168.100.9
00:15:26.247 [2021-06-02 01:54:30.749759] nvme_ctrlr.c: 917:nvme_ctrlr_fail: NOTICE: [nqn.2016-06.io.spdk:cnode1] already in failed state
00:15:26.247 [2021-06-02 01:54:30.749782] nvme_ctrlr.c:1398:spdk_nvme_ctrlr_reset: NOTICE: [nqn.2016-06.io.spdk:cnode1] resetting controller
00:15:26.249 [2021-06-02 01:54:30.751760] nvme_rdma.c: 529:nvme_rdma_validate_cm_event: ERROR: Expected RDMA_CM_EVENT_ESTABLISHED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = 8)
00:15:26.249 [2021-06-02 01:54:30.751782] nvme_rdma.c:1081:nvme_rdma_connect: ERROR: RDMA connect error -74
00:15:26.249 [2021-06-02 01:54:30.751788] nvme_rdma.c:1189:_nvme_rdma_ctrlr_connect_qpair: ERROR: Unable to connect the rqpair
00:15:27.085 test/nvmf/host/target_disconnect.sh: line 60: 288725 Killed "${NVMF_APP[@]}" "$@"
00:15:27.085 01:54:31 # disconnect_init 192.168.100.9
00:15:27.085 01:54:31 # nvmfappstart -m 0xF0
00:15:27.085 01:54:31 # timing_enter start_nvmf_tgt
00:15:27.086 01:54:31 # xtrace_disable
00:15:27.086 01:54:31 # '[' no '!=' yes ']'
00:15:27.086 01:54:31 # PREV_BASH_OPTS=ehxBET
00:15:27.086 01:54:31 # [[ ehxBET == \x ]]
00:15:27.086 01:54:31 # XTRACE_DISABLED=yes
00:15:27.087 01:54:31 # set +x
00:15:27.088 01:54:31 # xtrace_enable
00:15:27.088 01:54:31 # nvmfpid=288780
00:15:27.089 01:54:31 # waitforlisten 288780
00:15:27.089 01:54:31 # '[' -z 288780 ']'
00:15:27.089 01:54:31 # local rpc_addr=/var/tmp/spdk.sock
00:15:27.089 01:54:31 # /var/jenkins/workspace/nvmf-phy-autotest/spdk/build/bin/nvmf_tgt -i 0 -e 0xFFFF -m 0xF0
00:15:27.090 01:54:31 # echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
00:15:27.090 Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
00:15:27.090 01:54:31 # xtrace_disable
00:15:27.090 01:54:31 # '[' no '!=' yes ']'
00:15:27.090 01:54:31 # PREV_BASH_OPTS=ehxBET
00:15:27.091 01:54:31 # [[ ehxBET == \x ]]
00:15:27.091 01:54:31 # XTRACE_DISABLED=yes
00:15:27.091 01:54:31 # set +x
00:15:27.122 [2021-06-02 01:54:31.624752] Starting SPDK v21.07-pre git sha1 cbdbd2116 / DPDK 21.02.0 initialization...
00:15:27.122 [2021-06-02 01:54:31.624820] [ DPDK EAL parameters: [2021-06-02 01:54:31.624829] nvmf [2021-06-02 01:54:31.624834] -c 0xF0 [2021-06-02 01:54:31.624840] --log-level=lib.eal:6 [2021-06-02 01:54:31.624846] --log-level=lib.cryptodev:5 [2021-06-02 01:54:31.624852] --log-level=user1:6 [2021-06-02 01:54:31.624857] --iova-mode=pa [2021-06-02 01:54:31.624862] --base-virtaddr=0x200000000000 [2021-06-02 01:54:31.624867] --match-allocations [2021-06-02 01:54:31.624872] --file-prefix=spdk0 [2021-06-02 01:54:31.624878] --proc-type=auto [2021-06-02 01:54:31.624883] ]
00:15:27.231 EAL: No free 2048 kB hugepages reported on node 1
00:15:27.231 EAL: No available 1048576 kB hugepages reported
00:15:27.231 EAL: No legacy callbacks, legacy socket not created
00:15:27.231 [2021-06-02 01:54:31.697619] app.c: 537:spdk_app_start: NOTICE: Total cores available: 4
00:15:27.253 [2021-06-02 01:54:31.755633] nvme_ctrlr.c:1414:spdk_nvme_ctrlr_reset: ERROR: [nqn.2016-06.io.spdk:cnode1] Controller reinitialization failed.
00:15:27.253 [2021-06-02 01:54:31.755683] nvme_ctrlr.c: 923:nvme_ctrlr_fail: ERROR: [nqn.2016-06.io.spdk:cnode1] in failed state.
00:15:27.253 Unable to reset the controller.
```
and this
```
0:15:28.258 Write completed with error (sct=0, sc=8)
00:15:28.258 starting I/O failed
00:15:28.258 Write completed with error (sct=0, sc=8)
00:15:28.258 starting I/O failed
00:15:28.258 Read completed with error (sct=0, sc=8)
00:15:28.258 starting I/O failed
00:15:28.258 Read completed with error (sct=0, sc=8)
00:15:28.258 starting I/O failed
00:15:28.258 Write completed with error (sct=0, sc=8)
00:15:28.258 starting I/O failed
00:15:28.258 Read completed with error (sct=0, sc=8)
00:15:28.258 starting I/O failed
00:15:28.258 Read completed with error (sct=0, sc=8)
```
don't seem to be fatal since they can be also seen under other `nvmf-phy-autotest` builds  which complete their run successfully. So the question is if these can really be ignored and what was causing `nvme disconnect ...` timeouts in a first place.

**Comment by spdkci** [comment] 2021-06-17 08:58
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_50126.html

**Comment by spdkci** [comment] 2021-06-17 13:29
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_50141.html

**Comment by spdkci** [comment] 2021-06-22 07:32
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_50351.html

**Comment by karlatec** [comment] 2021-06-28 10:18
> The main reason why the build failed was the timeout it hit - there can be huge delays seen after, for instance, filesystem_incapsule_xfs test where nvme disconnect ... blocks for over a minute

Similar `disconnect` timeouts are seen in https://github.com/spdk/spdk/issues/2005. Issue can be related.
Removing `Infrastructure` label, it does not match here.

**Comment by spdkci** [comment] 2021-07-07 15:49
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_51948.html

**Comment by spdkci** [comment] 2021-07-12 04:57
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_52026.html

**Comment by tomzawadzki** [comment] 2021-07-13 15:24
[Bug scrub] This might be a duplicate of #2005, @karlatec will take a look at recent reports to confirm.

**Comment by karlatec** [comment] 2021-07-16 06:06
Most of the available reports, maybe except for one, seem to be the same issue as #2005. Closing.

**Closed by karlatec** 2021-07-16 06:06 UTC
Labels: Intermittent Failure
