### ISSUE TITLE
[dma] Test stuck after test_dma launch

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2969] opened 2023-03-30 09:23 UTC
# CI Intermittent Failure

```
00:16:09.422  ************************************
00:16:09.422  START TEST dma
00:16:09.422  ************************************
```

dma test times out after launching `test/dma/test_dma/test_dma`

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_100878.html

## Execution failed at

```
00:16:15.941  [2023-03-28 13:56:07.540382] Starting SPDK v23.05-pre git sha1 58d7b53fa / DPDK 22.11.1 initialization...
00:16:15.941  [2023-03-28 13:56:07.540436] [ DPDK EAL parameters: test_dma --no-shconf -c 0xc --huge-unlink --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid2330969 ]
00:16:15.941  EAL: No free 2048 kB hugepages reported on node 1
00:16:15.941  TELEMETRY: No legacy callbacks, legacy socket not created
00:16:15.941  [2023-03-28 13:56:07.614269] app.c: 730:spdk_app_start: *NOTICE*: Total cores available: 2
00:16:16.200  [2023-03-28 13:56:07.683247] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 3
00:16:16.200  [2023-03-28 13:56:07.683251] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 2
00:16:16.200  [2023-03-28 13:56:07.721435] accel_sw.c: 601:sw_accel_module_init: *NOTICE*: Accel framework software module initialized.
00:41:09.803  Cancelling nested steps due to timeout
00:41:09.815  Sending interrupt signal to process
00:41:28.069  Terminated
```

The following line can also be seen during the test (not sure if related):
`00:16:14.592  modprobe: ERROR: could not insert 'irdma': Unknown symbol in module, or unknown parameter (see dmesg)`

**Comment by mikeBashStuff** [comment] 2023-03-30 09:31
The error about `irdma` is expected and can be ignored - our per-patch images are shipped with oot `ice` driver so the upstream version of `irdma` won't find proper symbols (as the `ice` oot differs from the upstream `ice`). We have separate set of images, running outside of per-patch, which do build compatible oot `irdma` driver (targeted for the `cvl` nightly job).  

In any case, the more relevant part here is that this happened on the node which suffers from what was mentioned here: https://github.com/spdk/spdk/issues/2965 - there's a constant issue with overheating (or at least that's what kernel reports) mlx cards which leads to soft CPU lockups - this basically may lead to processes freezing and being completely unresponsive.

**Comment by KKaras169169** [comment] 2023-03-30 09:35
Thanks for the explanation! We could leave this issue open for a few days, so people can report this particular fail, or we can close it and just point to the #2965.

**Comment by spdkci** [comment] 2023-03-30 13:16
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_100878.html

**Comment by ksztyber** [comment] 2023-04-04 16:00
[Bug scrub] Since this is a duplicate of #2965, let's close this one.

**Closed by ksztyber** 2023-04-04 16:00 UTC
Labels: Intermittent Failure
