### ISSUE TITLE
[CI-Nightly]: Error "Process leaked file descriptors" is shown

### ISSUE THREAD

**Issue by Comphix** [spdk/spdk#973] opened 2019-09-29 05:05 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

For the nightly testing, it is failed with error like below:

Link here: https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly-failing/builds/453/archive/vhost_autotest_nightly/build.log

 23:21:47	# /var/jenkins/workspace/Vhost_tests/vhost_autotest_nightly/spdk/scripts/setup.sh cleanup
ls: cannot access '/dev/shm/*': No such file or directory
Clean
  23:21:47	# uname -s
 23:21:47	# '[' Linux = Linux ']'
 23:21:47	# grep -q '#define SPDK_CONFIG_IGB_UIO_DRIVER 1' /var/jenkins/workspace/Vhost_tests/vhost_autotest_nightly/spdk/include/spdk/config.h
 23:21:47	# modprobe -r uio_pci_generic
 23:21:47	# rm -rf /var/tmp/asan_suppression_file
 23:21:47	# exit 1
Process leaked file descriptors. See https://jenkins.io/redirect/troubleshooting/process-leaked-file-descriptors for more information
Build step 'Execute shell' marked build as failure
FATAL: Remote call on fedora_phy_nightly_1 failed

## Expected Behavior
No error from the test set

## Current Behavior
Process leaked file descriptors. See https://jenkins.io/redirect/troubleshooting/process-leaked-file-descriptors for more information

## Possible Solution
Is below a possible fix?
https://stackoverflow.com/questions/17024441/process-leaked-file-descriptors-error-on-jenkins

**Comment by Comphix** [comment] 2019-09-29 05:07
Please Karol to take a quick look whether this is relating to the Jenkins infrastructure. Thanks, Gang

**Comment by karlatec** [comment] 2019-09-30 09:54
@Comphix Yes, it's related to Jenkins.
Something didn't get killed properly in this failed test build. It can be even a simple thing like a bacground pipe from dmesg to a file, or something didn't get killed properly in spdk scripts (not likely).

The issue you're seeing here was not the root cause of the failed test. It was vhost migration test, you can see it if you scroll up a bit.
There's nothing to worry about, as for each failed build we reboot the test node, so the environment starts fresh for next test build.

**Comment by karlatec** [comment] 2019-10-01 13:10
@Comphix Can we close the issue?

**Comment by tomzawadzki** [comment] 2019-10-08 15:18
[Bug scrub] @Comphix Any updates ?

**Comment by changpe1** [comment] 2019-10-17 04:38
[Bug Scrub] @Comphix I'm going to close this issue for now.

**Closed by changpe1** 2019-10-17 04:38 UTC
Labels: Infrastructure, Waiting on Submitter
