### ISSUE TITLE
lvol_bdev errors in NIGHTLY master test 

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#396] opened 2018-08-09 09:12 UTC
These errors occur from 8/7/2018.

(1)bdev.c:3128:spdk_bdev_open: *ERROR*: Could not open db7f423b-d4ba-46d0-9a6d-ac99036ff380 - NVMe-oF Target module already claimed it
vbdev_lvol.c: 247:vbdev_lvs_create: *ERROR*: Cannot create blobstore device

(2)vhost_blk.c: 410:_bdev_remove_cb: *WARNING*: Controller naa.0.0: Hot-removing bdev - all further requests will fail.
Timeout while waiting for response.

## Expected Behavior
The NIGHTLY master test all passed.

## Current Behavior
These two cases test failed.

## Possible Solution
Check the relevant merged code on 8/7/2018.

## Steps to Reproduce
1. view https://review.gerrithub.io/#/c/spdk/spdk/+/393768/
2. view (1)https://ci.spdk.io/spdk/builds/review/5e6901fef6048c9ec854c7c052d93ad46981433b.1533729636/fedora-03/build.log
and
view (2)https://ci.spdk.io/spdk/builds/review/5e6901fef6048c9ec854c7c052d93ad46981433b.1533729636/fedora-05/build.log
(all search "Backtrace start")

## Context
SPDK Change-Id: 25a89b2ac3ce4a603f3a70cb5e7a29285cb3fd8a.

**Comment by jimharris** [comment] 2018-08-09 14:53
Hi Changpeng,

Could you take a look at the tests that are failing?  I know this is related to the NVMe-oF bdev claim patch that you developed.  Your patch is correct we will just need to look at and modify these tests.

You may need to consult with @pawelkax and/or Pawel N.

Thanks,

-Jim

**Comment by pawelkax** [comment] 2018-08-09 21:12
@changpe1 @nedved1 @jimharris 
Hi,
I think that this is problem with creating nested lvol store.
Such code fails:
1. ls_guid=$($rpc_py construct_lvol_store Nvme0n1 lvs_0)
2. get_lvs_free_mb $ls_guid
3. lb_guid=$($rpc_py construct_lvol_bdev -u $ls_guid lbd_0 $free_mb)
4. ls_nested_guid=$($rpc_py construct_lvol_store $lb_guid lvs_n_0)
and this code also fails:
1. ls_guid=$($rpc_py construct_lvol_store Nvme0n1 lvs_0)
2. get_lvs_free_mb $ls_guid
3. lb_guid=$($rpc_py construct_lvol_bdev -u $ls_guid lbd_0 $free_mb)
4. $rpc_py construct_nvmf_subsystem nqn.2016-06.io.spdk:cnode1 "trtype:RDMA traddr:$NVMF_FIRST_TARGET_IP trsvcid:4420" "" -a -s SPDK0000000000000$ -n "$lb_guid"
In both cases error message occures that lb_guid is already claimed by lvol module.

Probably it is caused by some patch related to lvols that was recently merged. Script ./test/nvmf/host/perf.sh was recently modified 26 July., but test started failing 7 July.
Maybe this path: https://review.gerrithub.io/#/c/spdk/spdk/+/420472/ causes the problem?

**Comment by changpe1** [comment] 2018-08-10 02:45
commit ff458be85 "nvmf: claim each bdev when constructing new Namespace" caused the issue, because nvmf target will claim each block device when constructing Namespaces, for nested blobstore, the parent block device is claimed by nvmf target, so it will fail for the nested case.

**Comment by wanghailiangx** [comment] 2018-08-15 08:34
Changpeng has submit a patch to fix perf.sh. https://review.gerrithub.io/#/c/spdk/spdk/+/421136/ (merged).  
But Hugen raised different opinion and sbumit a new patch. https://review.gerrithub.io/#/c/spdk/spdk/+/422194/

In addition, "test/vhost/spdk_vhost.sh" needs to be fixed, it also causes issues sometimes.
Refer to mentioned
(2)https://ci.spdk.io/spdk/builds/review/5e6901fef6048c9ec854c7c052d93ad46981433b.1533729636/fedora-05/build.log (search "Backtrace start")

**Comment by wanghailiangx** [comment] 2018-08-29 08:38
(2)vhost_blk.c error, the Poland team is working on it.

**Comment by jimharris** [comment] 2018-08-30 04:28
(2) is a different issue.  @wanghailiangx - can you create a new GitHub entry for it?

We should be able to get Huagen's 422194 patch merged - then we can close this issue.

**Comment by wanqunintel** [comment] 2018-09-06 04:03
close as patch https://review.gerrithub.io/#/c/spdk/spdk/+/422194/ has been merged

**Closed by wanqunintel** 2018-09-06 04:03 UTC
Labels: bug
