### ISSUE TITLE
Ceph RBD test: mknod /dev/ceph already exists when creating GPT partition

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1009] opened 2019-10-27 23:05 UTC
Please use the issue tracker only for reporting suspected issues.

I saw the following failure in per-patch test.
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_47850.html

```
+++ dirname /var/jenkins/workspace/RBD_BlobFS_tests/RBD_autotest/spdk/scripts/ceph/start.sh
++ readlink -f /var/jenkins/workspace/RBD_BlobFS_tests/RBD_autotest/spdk/scripts/ceph
+ script_dir=/var/jenkins/workspace/RBD_BlobFS_tests/RBD_autotest/spdk/scripts/ceph
+ base_dir=/var/tmp/ceph
+ mon_ip=10.0.0.1
+ mon_dir=/var/tmp/ceph/mon.a
+ pid_dir=/var/tmp/ceph/pid
+ ceph_conf=/var/tmp/ceph/ceph.conf
+ mnt_dir=/var/tmp/ceph/mnt
+ dev_backend=/dev/ceph
+ image=/var/tmp/ceph_raw.img
+ dev=/dev/loop200
+ umount /dev/loop200
umount: /dev/loop200: not mounted.
+ true
+ losetup -d /dev/ceph
losetup: /dev/ceph: detach failed: No such device or address
+ true
+ '[' -d /var/tmp/ceph ']'
+ mkdir /var/tmp/ceph
+ cp /var/jenkins/workspace/RBD_BlobFS_tests/RBD_autotest/spdk/scripts/ceph/ceph.conf /var/tmp/ceph/ceph.conf
+ '[' '!' -e /var/tmp/ceph_raw.img ']'
+ fallocate -l 4G /var/tmp/ceph_raw.img
+ mknod /dev/ceph b 7 200
mknod: /dev/ceph: File exists
+ true
+ losetup /dev/ceph /var/tmp/ceph_raw.img
+ PARTED='parted -s'
+ SGDISK=sgdisk
+ echo 'Partitioning /dev/loop200'
Partitioning /dev/loop200
+ parted -s /dev/loop200 mktable gpt
Error: Partition(s) 1 on /dev/loop200 have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.
  06:39:03	# trap - ERR
  06:39:03	# print_backtrace
  06:39:03	# [[ ehxBE =~ e ]]
  06:39:03	# xtrace_disable
  06:39:03	# PREV_BASH_OPTS=ehxBE
  06:39:03	# set +x
========== Backtrace start: ==========

in /var/jenkins/workspace/RBD_BlobFS_tests/RBD_autotest/spdk/test/common/autotest_common.sh:514 -> rbd_setup()
     ...
   509 		if hash ceph; then
   510 			export PG_NUM=128
   511 			export RBD_POOL=rbd
   512 			export RBD_NAME=foo
   513 			$NS_CMD $rootdir/scripts/ceph/stop.sh || true
=> 514 			$NS_CMD $rootdir/scripts/ceph/start.sh $1
   515 	
   516 			$NS_CMD ceph osd pool create $RBD_POOL $PG_NUM || true
   517 			$NS_CMD rbd create $RBD_NAME --size 1000
   518 		fi
   519 	}
     ...
in ./test/iscsi_tgt/rbd/rbd.sh:18 -> main()
     ...
   13  		echo "Ceph not detected on this system; skipping RBD tests"
   14  		exit 0
   15  	fi
   16  	
   17  	timing_enter rbd_setup
=> 18  	rbd_setup $TARGET_IP $TARGET_NAMESPACE
   19  	trap 'rbd_cleanup; exit 1' SIGINT SIGTERM EXIT
   20  	timing_exit rbd_setup
   21  	
   22  	timing_enter rbd
   23  	
     ...

```
## Expected Behavior
No error

## Current Behavior
The above error

## Possible Solution
None

## Steps to Reproduce
Per-patch test

## Context (Environment including OS version, SPDK version, etc.)
SPDK latest master.

**Comment by optimistyzy** [comment] 2019-10-28 06:36
I occasionally find another issue in the test log, and submitted a patch   https://review.gerrithub.io/c/spdk/spdk/+/472514 .

**Comment by Maciej-Szwed** [comment] 2019-10-28 11:35
Another one: https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/48013/archive/RBD_autotest/failed_test.log

**Comment by yidong0635** [comment] 2019-10-29 01:39
@Maciej-Szwed  the log that you pasted here is the old log, the only solution is to rebase code from master.

**Comment by Seth5141** [comment] 2019-10-31 20:33
After taking a look at the logs, I don't believe that the issue is related to the fact that /dev/cepph already exists. For reference, here is the successful log vs. the failed log.
Successful:
~~~
+ losetup -d /dev/ceph
losetup: /dev/ceph: detach failed: No such device or address
+ true
+ '[' -d /var/tmp/ceph ']'
+ mkdir /var/tmp/ceph
+ cp /var/jenkins/workspace/RBD_BlobFS_tests/RBD_autotest/spdk/scripts/ceph/ceph.conf /var/tmp/ceph/ceph.conf
+ '[' '!' -e /var/tmp/ceph_raw.img ']'
+ fallocate -l 4G /var/tmp/ceph_raw.img
+ mknod /dev/ceph b 7 200
mknod: /dev/ceph: File exists
+ true
+ losetup /dev/ceph /var/tmp/ceph_raw.img
+ PARTED='parted -s'
+ SGDISK=sgdisk
+ echo 'Partitioning /dev/loop200'
Partitioning /dev/loop200
+ parted -s /dev/loop200 mktable gpt
+ sleep 2
+ parted -s /dev/loop200 mkpart primary 0% 2GiB
+ parted -s /dev/loop200 mkpart primary 2GiB 100%
+ partno=0
+ echo 'Setting name on /dev/loop200'
Setting name on /dev/loop200
+ sgdisk -c 1:osd-device-0-journal /dev/loop200
Setting name!
partNum is 0
~~~

failed:
~~~
+ losetup -d /dev/ceph
losetup: /dev/ceph: detach failed: No such device or address
+ true
+ '[' -d /var/tmp/ceph ']'
+ mkdir /var/tmp/ceph
+ cp /var/jenkins/workspace/RBD_BlobFS_tests/RBD_autotest/spdk/scripts/ceph/ceph.conf /var/tmp/ceph/ceph.conf
+ '[' '!' -e /var/tmp/ceph_raw.img ']'
+ fallocate -l 4G /var/tmp/ceph_raw.img
+ mknod /dev/ceph b 7 200
mknod: /dev/ceph: File exists
+ true
+ losetup /dev/ceph /var/tmp/ceph_raw.img
+ PARTED='parted -s'
+ SGDISK=sgdisk
+ echo 'Partitioning /dev/loop200'
Partitioning /dev/loop200
+ parted -s /dev/loop200 mktable gpt
Error: Partition(s) 1 on /dev/loop200 have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.
~~~~

So the difference doesn't come until after the call to parted. The failure comes because partition 1 is still in use. From the logs, we know that /dev/loop200p2 is partition 1 (/dev/loop200p1 is partition 1). This means that we somehow still ahve /dev/loop200p2 mounted. This makes sense because the old version of the script was calling umount /dev/loop200 instead of umount /dev/loop200p2. I believe that Ziye's patch referenced above https://review.gerrithub.io/c/spdk/spdk/+/472514 . fixes this issue.

I will leave this open until we can discuss it at the next bug scrub, and to allow people to post any instances they may see of this specific failure (although I don't expect there to be any).

**Comment by optimistyzy** [comment] 2019-11-04 01:38
@Seth5141 @jimharris @shuhei-matsumoto  I will close this issue since my patch is merged. Let's see whether the same issue will happen again. If that, we can re-open this issue.

**Closed by optimistyzy** 2019-11-04 01:38 UTC
Labels: Bug Scrub, Intermittent Failure
