### ISSUE TITLE
Some rpc methods does not exist in FreeBSD

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#892] opened 2019-08-01 10:10 UTC
Nightly test reports that some rpc methods does not exist in FreeBSD. This is a low priority issue.
This log can't be found in other Linux OS(CentOS, Fedora, ubuntu), only in FreeBSD.

```
************************************
START TEST SUITE ./test/json_config/json_config.sh
************************************
......
 09:02:39	# waitforlisten 77675 /var/tmp/spdk_tgt.sock
 09:02:39	# '[' -z 77675 ']'
 09:02:39	# local rpc_addr=/var/tmp/spdk_tgt.sock
 09:02:39	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk_tgt.sock...'
Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk_tgt.sock...
 09:02:39	# xtrace_disable
 09:02:39	# PREV_BASH_OPTS=ehxBE
 09:02:39	# set +x
rpc.c: 277:spdk_rpc_register_alias_deprecated: *ERROR*: cannot create alias get_trace_flags - method get_log_flags does not exist
rpc.c: 277:spdk_rpc_register_alias_deprecated: *ERROR*: cannot create alias clear_trace_flag - method clear_log_flag does not exist
rpc.c: 277:spdk_rpc_register_alias_deprecated: *ERROR*: cannot create alias set_trace_flag - method set_log_flag does not exist
rpc.c: 277:spdk_rpc_register_alias_deprecated: *ERROR*: cannot create alias get_rpc_methods - method rpc_get_methods does not exist
```

## Expected Behavior
These rpc methods can  be found in FreeBSD.

## Current Behavior
These rpc methods can't  be found in FreeBSD.

## Possible Solution
These rpc_methods are defined in log_rpc.c

function waitforlisten() {
		if $rootdir/scripts/rpc.py -t 1 -s "$rpc_addr" rpc_get_methods &>/dev/null; then
			break
		fi
}
waitforlisten() and  event_perf, bdevperf can cause the error.

## Steps to Reproduce
1. Please view https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/580/archive/freebsd_autotest/build.log (search "cannot create alias")

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit dfe1678b7b1a63de8c452421473fecedcee410fe

**Comment by jimharris** [comment] 2019-08-01 14:31
I have a FreeBSD VM on my laptop - I'll take a look.

**Comment by jimharris** [comment] 2019-08-01 14:51
I'm not able to reproduce this on my FreeBSD VM - but it's FreeBSD 12 while CI is using FreeBSD 11.2.

But I think what's happening is that the constructor functions are running in a different order on FreeBSD 11.2 than they are on FreeBSD 12 (or Linux):

rpc.c: 277:spdk_rpc_register_alias_deprecated: *ERROR*: cannot create alias get_rpc_methods - method rpc_get_methods does not exist
rpc_client_test.c: 136:spdk_jsonrpc_client_check_rpc_method: *NOTICE*: test_method_startup
rpc_client_test.c: 136:spdk_jsonrpc_client_check_rpc_method: *NOTICE*: test_method_runtime
rpc_client_test.c: 136:spdk_jsonrpc_client_check_rpc_method: *NOTICE*: test_null_params
rpc_client_test.c: 136:spdk_jsonrpc_client_check_rpc_method: *NOTICE*: hook_conn_close
rpc_client_test.c: 136:spdk_jsonrpc_client_check_rpc_method: *NOTICE*: rpc_get_methods
rpc_client_test.c: 136:spdk_jsonrpc_client_check_rpc_method: *NOTICE*: get_spdk_version

Note that we get the error for the get_rpc_methods alias, saying that rpc_get_methods doesn't exist, but later we clearly see that the rpc_get_methods call was successfully executed.

I suspect that the older version of clang is executing the constructors in alphabetical order of the function name.

I think adding a priority to the __attribute__(constructor) will solve this - pushing a patch shortly to try it out.

**Comment by jimharris** [comment] 2019-08-01 16:07
https://review.gerrithub.io/c/spdk/spdk/+/463915 seems to fix the issue.

http://10.102.17.206/results/autotest-per-patch/builds/39142/archive/freebsd_autotest/index.html

**Comment by jimharris** [comment] 2019-08-05 18:51
Patch merged so closing this issue.  @wanghailiangx - please comment or reopen if you still see any problems like this.

**Closed by jimharris** 2019-08-05 18:51 UTC
Labels: Low, bug
