### ISSUE TITLE
Fio test fails verification when running on multi namespace NVMe and --spdk_mem=0

### ISSUE THREAD

**Issue by Maciej-Szwed** [spdk/spdk#948] opened 2019-09-05 09:43 UTC
Fio verification fails on multi namespace NVMe only when spdk_mem flag is set to 0. W/o this flag test passes.

Fail log:

verify: bad magic header 8256, wanted acca at file Nvme2n1 offset 842694656, length 4096
fio: pid=2641125, err=84/file:io_u.c:2108, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character
sha1: verify failed at file Nvme2n3 offset 184430592, length 4096
       Expected CRC: 12415a5d2cb71d0fdf7ebd0dfd88314c9e4fd722
       Received CRC: 6f80839a1dc650175fb895349a90a5fae64cf387
fio: pid=2641127, err=84/file:io_u.c:2108, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character
verify: bad magic header 19a3, wanted acca at file Nvme2n2 offset 2565406720, length 4096
fio: pid=2641126, err=84/file:io_u.c:2108, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character
Jobs: 19 (f=19): [V(1),w(1),V(1),w(4),V(1),w(2),V(1),w(1),V(1),w(1),V(1),w(1),X(3),w(2),V(1)][84.6%][r=308MiB/s,w=482MiB/s][r=78.8k,w=123k IOPS][eta 00m:02s]
job_Malloc0: (groupid=0, jobs=22): err=84 (file:io_u.c:2108, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character): pid=2641109: Thu Sep  5 10:38:15 2019

Steps to reproduce:
Run blockdev_autotest Jenkins job on VM with multi namespace NVMe present.

Setup used for tests:
fedora_5_vm

**Comment by yidong0635** [comment] 2019-09-06 01:47
Issue that was reported in #935 ,that is the same error.
It seems related to fio,  it has not been resolved yet.

**Comment by changpe1** [comment] 2019-09-19 05:06
@Maciej-Szwed Can you also list your SPDK commands so that someone else can also reproduce this issue?

**Comment by tomzawadzki** [comment] 2019-10-08 13:26
@Maciej-Szwed Any updates or information on relation to #935 ?

**Comment by changpe1** [comment] 2019-10-17 04:37
[Bug Scrub] @Maciej-Szwed Maybe you can use a small capacity NVMe block device to reproduce this issue, and take #935 as a reference.

**Comment by Comphix** [comment] 2019-10-17 23:37
Duplicate of #935

**Comment by Comphix** [comment] 2019-10-17 23:43
Looks like #935 is a different one. If I read the error log correctly, it is with 4K IO.

Do we have detailed FIO and Bdev configuration.

sha1: verify failed at file Nvme2n3 offset 184430592, length 4096 <<<
Expected CRC: 12415a5d2cb71d0fdf7ebd0dfd88314c9e4fd722
Received CRC: 6f80839a1dc650175fb895349a90a5fae64cf387

**Comment by Maciej-Szwed** [comment] 2019-10-22 12:43
Command used in automated tests:
LD_PRELOAD='spdk/examples/bdev/fio_plugin/fio_plugin' /usr/src/fio/fio --ioengine=spdk_bdev --iodepth=8 --bs=4k --runtime=10 spdk/test/bdev/bdev.fio --spdk_conf=./test/bdev/bdev.conf --spdk_mem=0

where bdev.conf looks like this:

[Passthru]
  # PT <bdev name> <vbdev name>
  PT Malloc3 TestPT

[Malloc]
  NumberOfLuns 8
  LunSizeInMB 32

[Split]
  # Split Malloc1 into two auto-sized halves
  Split Malloc1 2

  # Split Malloc2 into eight 4-megabyte pieces,
  # leaving the rest of the device inaccessible
  Split Malloc2 8 4

[AIO]
  AIO /tmp/aiofile AIO0 2048

[QoS]
  # QoS section defines limitation on performance
  # metric like IOPS and bandwidth
  #
  # Format: Limit_IOPS Bdev_Name IOPS_Limit_Value
  #
  # IOPS limit must be 10000 or greater and be multiple
  # of 10000
  #
  # Assign 20000 IOPS for the Malloc0 block device
  Limit_IOPS Malloc0 20000
  #
  # Bandwidth limit must be 10 (MB) or greater and be
  # multiple of 10
  # Assign 100 (MB) bandwidth for the Malloc3 block
  # device
  Limit_BPS Malloc3 100

[RAID0]
  Name raid0
  StripSize 64
  NumDevices 2
  RaidLevel 0
  Devices Malloc4 Malloc5
[Nvme]
  TransportID "trtype:PCIe traddr:0000:00:09.0" Nvme0
  TransportID "trtype:PCIe traddr:0000:00:0c.0" Nvme1
  TransportID "trtype:PCIe traddr:0000:00:0d.0" Nvme2
  TransportID "trtype:PCIe traddr:0000:00:0e.0" Nvme3
  TransportID "trtype:PCIe traddr:0000:00:0f.0" Nvme4
[Pmem]
  Blk /tmp/spdk-pmem-pool Pmem0

**Comment by darsto** [comment] 2020-01-30 14:42
It looks like the fix from #935 also applies here. Closing

**Closed by darsto** 2020-01-30 14:42 UTC
Labels: bug

**Comment by spdkci** [comment] 2020-02-20 04:43
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_4167.html
