### ISSUE TITLE
[SPDK v23.09] io_uring error in sock implementation

### ISSUE THREAD

**Issue by TheSSDGuy** [spdk/spdk#3275] opened 2024-02-27 07:55 UTC
# Sighting report

Hello community,

I'm trying to use io_uring on a Ubuntu 20.04 server provided with kernel version 5.4.0.171-generic. SPDK version is v23.09.
I would like to use io_uring only for bdevs acceleration and not for socket implementation so I've used `sock_set_default_impl ` rpc to set it to Posix.
However, as soon as I try to create a nvmf transport with the following command
`sudo ./scripts/rpc.py nvmf_create_transport -t TCP -u 131072 -m 127 -c 4096 -n 1023 -z`

I get the following error:
`uring.c:1701:uring_sock_group_impl_create: *ERROR*: Failed to create buffer ring. Your kernel is likely not new enough. Please switch to the POSIX sock implementation instead.`

and SPDK does not crash after the error reporting.

## Expected Behavior

When sock implementation is set to Posix, io_uring should be applied only to bdevs

## Current Behavior

rpc  `sock_set_default_impl ` does not differentiate between sock implementation and bdev attachment

**Comment by jimharris** [comment] 2024-02-27 15:50
@karlowich is going to take a look at this one.

**Comment by karlowich** [comment] 2024-03-08 12:07
Hi @TheSSDGuy,

Can you try this patchset: https://review.spdk.io/gerrit/c/spdk/spdk/+/22140/1
(Mentioned here: #3280)

Let me know, if it solves your problem :)

**Comment by karlowich** [comment] 2024-06-11 11:47
@jimharris I have started looking into this. I have added an option `--sock-impl` to `./scripts/rpc.py nvmf_create_transport`. However, when trying to figure out how to use it, I found that the transport isn't tied to a socket implementation. Perhaps it would be better to add it to `./scripts/rpc.py nvmf_subsystem_add_listener` or something else.
Let me know what you think.

**Comment by jimharris** [comment] 2024-06-11 14:55
> @jimharris I have started looking into this. I have added an option `--sock-impl` to `./scripts/rpc.py nvmf_create_transport`. However, when trying to figure out how to use it, I found that the transport isn't tied to a socket implementation. Perhaps it would be better to add it to `./scripts/rpc.py nvmf_subsystem_add_listener` or something else. Let me know what you think.

I like the idea of adding it to `nvmf_subsystem_add_listener`. We already have `--secure-channel` for that RPC, which effectively chooses the `ssl` sock_impl.

We may want to consider deprecating the `--secure-channel` parameter in that case, effectively replaced by `--sock-impl ssl`.

Please also watch out for case where user adds the same listener (i.e. IP/port) to two different subsystems, but with different sock_impls. We don't want to try to handle that.

**Comment by karlowich** [comment] 2024-06-24 11:52
### Patch
@jimharris The first version of the patch for adding `--sock-impl` is now on gerrit:
https://review.spdk.io/gerrit/c/spdk/spdk/+/23862

I tested my implementation by setting up a fabrics target:
```
scripts/rpc.py nvmf_create_transport -t TCP -u 16384 -m 8 -c 8192
scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1
scripts/rpc.py bdev_malloc_create -b Malloc0 512 512
scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 127.0.0.1 -s 4420 -S ssl
scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 127.0.0.1 -s 4421 -S posix 
```

Connecting to the listener with ssl (4420) behaves different to connecting to the listener with posix (4421).
As such, my implementation seems to work as intended.

### Next step
This still doesn't resolve this issue. I think we need to delay the initialization of the `sock_impl` until a listener asks for it.
My initial thought was to change `spdk_sock_group_create()` to create an empty `spdk_sock_group`. Then we could populate the `spdk_sock_group` in `nvmf_tcp_listen()`.
However, changing the behaviour of `spdk_sock_group_create()` seems to affect more than just the fabrics target - a workaround could be creating a new function, something like `spdk_sock_group_create_empty()`, and calling that from `nvmf_tcp_poll_group_create()`

**Comment by karlowich** [comment] 2024-06-24 12:11
> Please also watch out for case where user adds the same listener (i.e. IP/port) to two different subsystems, but with different sock_impls. We don't want to try to handle that.

Currently, it seems to simply ignore the  `sock_impl` specified on the second call to `nvmf_subsystem_add_listener`.
The following fabrics target: 
```
scripts/rpc.py nvmf_create_transport -t TCP -u 16384 -m 8 -c 8192
scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1
scripts/rpc.py bdev_malloc_create -b Malloc0 512 512
scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 127.0.0.1 -s 4420 -S posix

scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode2 -a -s SPDK00000000000002 -d SPDK_Controller2
scripts/rpc.py bdev_malloc_create -b Malloc1 512 512
scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode2 Malloc1
scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode2 -t tcp -a 127.0.0.1 -s 4420 -S ssl
```

Gives me this enumeration (using xNVMe):
```
 - {uri: '127.0.0.1:4420', dtype: 0x2, nsid: 0x1, csi: 0x0, subnqn: 'nqn.2016-06.io.spdk:cnode2'}
 - {uri: '127.0.0.1:4420', dtype: 0x2, nsid: 0x1, csi: 0x0, subnqn: 'nqn.2016-06.io.spdk:cnode1'}
```

If I flip the order of the `sock_impl` used for `nvmf_subsystem_add_listener` to `ssl` first, I get nothing back from enumerating, as I fail to connect correctly to `ssl` (which is expected).

I'm thinking this is the behaviour we want, but maybe we should add a message notifying that the second `sock_impl` was ignored?

**Comment by jimharris** [comment] 2024-06-28 14:31
> ### Patch
> @jimharris The first version of the patch for adding `--sock-impl` is now on gerrit: https://review.spdk.io/gerrit/c/spdk/spdk/+/23862
> 
> I tested my implementation by setting up a fabrics target:
> 
> ```
> scripts/rpc.py nvmf_create_transport -t TCP -u 16384 -m 8 -c 8192
> scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1
> scripts/rpc.py bdev_malloc_create -b Malloc0 512 512
> scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
> scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 127.0.0.1 -s 4420 -S ssl
> scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 127.0.0.1 -s 4421 -S posix 
> ```
> 
> Connecting to the listener with ssl (4420) behaves different to connecting to the listener with posix (4421). As such, my implementation seems to work as intended.
> 
> ### Next step
> This still doesn't resolve this issue. I think we need to delay the initialization of the `sock_impl` until a listener asks for it. My initial thought was to change `spdk_sock_group_create()` to create an empty `spdk_sock_group`. Then we could populate the `spdk_sock_group` in `nvmf_tcp_listen()`. However, changing the behaviour of `spdk_sock_group_create()` seems to affect more than just the fabrics target - a workaround could be creating a new function, something like `spdk_sock_group_create_empty()`, and calling that from `nvmf_tcp_poll_group_create()`

I think we can change module/sock/uring/uring.c to only register its net_impl if a test passes.

We have SPDK_NET_IMPL_REGISTER, which registers the uring impl with the sock subsystem. You can see its definition in include/spdk_internal/sock.h. It basically just defines a constructor function that calls spdk_net_impl_register().

So instead, add a constructor function in module/sock/uring/uring.c. Have it call uring_sock_group_impl_create(). If it returns a pointer, have it immediately call uring_sock_group_impl_close() and call spdk_net_impl_register() to register the impl. If it fails, then we know the kernel on that system does not support uring sockets, so skip calling spdk_net_impl_register().

Probably the error message in uring_sock_group_impl_create() should be modified, just something like "uring sock_impl not supported on this kernel".

**Comment by karlowich** [comment] 2024-07-01 13:56
@jimharris That is certainly a much simpler approach. I will go with that

**Comment by karlowich** [comment] 2024-07-11 11:31
@TheSSDGuy Your issue should now be fixed with the merge of this patch:
https://review.spdk.io/gerrit/c/spdk/spdk/+/23978/8

Can you try it out?

**Comment by jimharris** [comment] 2024-07-17 23:54
Closing this issue since the patches were merged. @TheSSDGuy, please report here if your testing indicates otherwise.

**Closed by jimharris** 2024-07-17 23:54 UTC
Labels: bug, Low, Waiting on Submitter
