### ISSUE TITLE
Intermittent failure :test/nvmf/host/target_disconnect.sh

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1026] opened 2019-11-01 08:44 UTC
# Issue
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/48559/archive/nvmf_autotest/build.log
trsvcid:4420'
Starting SPDK v19.10-pre / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: reconnect --no-shconf -c 0xF --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid847561 ]
EAL: No available hugepages reported in hugepages-1048576kB
 09:31:05	# kill -9 847528
 09:31:05	# sleep 2
nvme_qpair.c: 479:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
```
vme_ctrlr.c: 667:nvme_ctrlr_fail: *ERROR*: ctrlr 10.102.17.186 in failed state.
A controller has encountered a failure and is being reset.
nvme_ctrlr.c:1062:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
test/nvmf/host/target_disconnect.sh: line 42: 847528 Killed                  $NVMF_APP $1
test/nvmf/host/target_disconnect.sh: line 42: 847561 Segmentation fault      (core dumped) $rootdir/examples/nvme/reconnect/reconnect -q 32 -o 4096 -w randrw -M 50 -t 10 -c 0xF -r "trtype:$TEST_TRANSPORT adrfam:IPv4 traddr:$NVMF_FIRST_TARGET_IP trsvcid:$NVMF_PORT"
```
 09:31:07	# disconnect_init 10.102.17.186
 09:31:07	# nvmfappstart '-m 0xF0'
 09:31:07	# timing_enter start_nvmf_tgt
 09:31:07	# xtrace_disable

**Comment by jimharris** [comment] 2019-11-01 15:29
Hi @yidong0635 - thanks for the intermittent failure report!  Try to remember to also add the "Intermittent Failure" label - it makes it easier for others to find this issue in case it happens again.

**Comment by Seth5141** [comment] 2019-11-01 16:39
@yidong0635 Thanks for the report. This looks like a duplicate of #1005  That one was fixed with the following patch https://review.gerrithub.io/c/spdk/spdk/+/472960. I was looking at the change related to this log https://review.gerrithub.io/c/472916/2 and it looks like it's based on an older version of master. Once you rebase, the failure should go away.

**Comment by jimharris** [comment] 2019-11-01 16:50
I agree with Seth's assessment.

**Closed by jimharris** 2019-11-01 16:50 UTC
Labels: Intermittent Failure

**Comment by yidong0635** [comment] 2019-11-05 01:15
@jimharris  and @Seth5141  , sorry for not response  ,I don't have the rights to add label .
