### ISSUE TITLE
VMD backing devices disappear from lspci when bound to pci-vfio

### ISSUE THREAD

**Issue by tanabarr** [spdk/spdk#2273] opened 2021-12-09 10:38 UTC
# Bug report

lspci can normally be used to view NVMe device details even when bound to pci-vfio driver, this is not the case for VMD backing devices

## Expected Behavior

lspci shows details (of specific interest is device link width and speed) for VMD backing devices (PCI address beginning with domain 1000) even when devices are bound to pci-vfio driver.

## Current Behavior

```
daosfs09:~ # lspci | grep -c Samsung                                                                                        
16                                                                                                                          
daosfs09:~ # _PCI_ALLOWED="\" 0000:4a:00.5 0000:64:00.5 0000:97:00.5 0000:e2:00.5 \"" /usr/share/daos/control/setup_spdk.sh 
start of script: /usr/share/daos/control/setup_spdk.sh                                                                      
calling into script: /usr/share/daos/control/../../spdk/scripts/setup.sh                                                    
+ PCI_ALLOWED='" 0000:4a:00.5 0000:64:00.5 0000:97:00.5 0000:e2:00.5 "'                                                     
+ PCI_BLOCKED=                                                                                                              
+ NRHUGE=                                                                                                                   
+ TARGET_USER=                                                                                                              
+ DRIVER_OVERRIDE=                                                                                                          
+ PATH=/sbin:/sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/sysfwupdt:/usr/bin/syscfg      
+ /usr/share/daos/control/../../spdk/scripts/setup.sh                                                                       
10000:81:00.0 (144d a80a): Skipping denied controller at 10000:81:00.0                                                      
10000:83:00.0 (144d a80a): Skipping denied controller at 10000:83:00.0                                                      
10000:85:00.0 (144d a80a): Skipping denied controller at 10000:85:00.0                                                      
10000:87:00.0 (144d a80a): Skipping denied controller at 10000:87:00.0                                                      
10001:01:00.0 (144d a80a): Skipping denied controller at 10001:01:00.0                                                      
10001:03:00.0 (144d a80a): Skipping denied controller at 10001:03:00.0                                                      
10001:05:00.0 (144d a80a): Skipping denied controller at 10001:05:00.0                                                      
10001:07:00.0 (144d a80a): Skipping denied controller at 10001:07:00.0                                                      
10002:01:00.0 (144d a80a): Skipping denied controller at 10002:01:00.0                                                      
10002:03:00.0 (144d a80a): Skipping denied controller at 10002:03:00.0                                                      
10002:05:00.0 (144d a80a): Skipping denied controller at 10002:05:00.0                                                      
10002:07:00.0 (144d a80a): Skipping denied controller at 10002:07:00.0                                                      
10003:81:00.0 (144d a80a): Skipping denied controller at 10003:81:00.0                                                      
10003:83:00.0 (144d a80a): Skipping denied controller at 10003:83:00.0                                                      
10003:85:00.0 (144d a80a): Skipping denied controller at 10003:85:00.0                                                      
10003:87:00.0 (144d a80a): Skipping denied controller at 10003:87:00.0                                                      
0000:00:01.0 (8086 0b00): Skipping denied controller at 0000:00:01.0                                                        
0000:00:01.1 (8086 0b00): Skipping denied controller at 0000:00:01.1                                                        
0000:00:01.2 (8086 0b00): Skipping denied controller at 0000:00:01.2                                                        
0000:00:01.3 (8086 0b00): Skipping denied controller at 0000:00:01.3                                                        
0000:00:01.4 (8086 0b00): Skipping denied controller at 0000:00:01.4                                                        
0000:00:01.5 (8086 0b00): Skipping denied controller at 0000:00:01.5                                                        
0000:00:01.6 (8086 0b00): Skipping denied controller at 0000:00:01.6                                                        
0000:00:01.7 (8086 0b00): Skipping denied controller at 0000:00:01.7                                                        
0000:80:01.0 (8086 0b00): Skipping denied controller at 0000:80:01.0                                                        
0000:80:01.1 (8086 0b00): Skipping denied controller at 0000:80:01.1                                                        
0000:80:01.2 (8086 0b00): Skipping denied controller at 0000:80:01.2                                                        
0000:80:01.3 (8086 0b00): Skipping denied controller at 0000:80:01.3                                                        
0000:80:01.4 (8086 0b00): Skipping denied controller at 0000:80:01.4                                                        
0000:80:01.5 (8086 0b00): Skipping denied controller at 0000:80:01.5                                                        
0000:80:01.6 (8086 0b00): Skipping denied controller at 0000:80:01.6                                                        
0000:80:01.7 (8086 0b00): Skipping denied controller at 0000:80:01.7                                                        
0000:e2:00.5 (8086 28c0): vmd -> vfio-pci                                                                                   
0000:97:00.5 (8086 28c0): vmd -> vfio-pci                                                                                   
0000:64:00.5 (8086 28c0): vmd -> vfio-pci                                                                                   
0000:4a:00.5 (8086 28c0): vmd -> vfio-pci                                                                                   
+ set +x                                                                                                                    
RUN: ls -d /dev/hugepages | xargs -r chown -R                                                                               
ls: cannot access '/dev/uio*': No such file or directory                                                                    
ls: cannot access '/sys/class/uio/uio*/device/config': No such file or directory                                            
ls: cannot access '/sys/class/uio/uio*/device/resource*': No such file or directory                                         
Setting VFIO file permissions for unprivileged access                                                                       
RUN: chmod /dev/vfio                                                                                                        
OK                                                                                                                          
RUN: chmod /dev/vfio/*                                                                                                      
OK                                                                                                                          
daosfs09:~ # lspci | grep -c Samsung                                                                                        
0                                                                                                                           
```
Note that the issue is not specific to Samsung drives, have seen the same with Intel optane.

## Steps to Reproduce

follow the commands above

## Context (Environment including OS version, SPDK version, etc.)

OpenSUSE 15.2 & 15.3
SPDK 21.07

**Comment by ksztyber** [comment] 2021-12-09 14:36
When you unload the VMD driver (and load the vfio-pci in its place), the devices behind it will disappear from the system, as they're discovered through that driver. But I think you could use `spdk_lspci` to list them.

**Comment by jimharris** [comment] 2021-12-09 15:10
> When you unload the VMD driver (and load the vfio-pci in its place), the devices behind it will disappear from the system, as they're discovered through that driver. But I think you could use `spdk_lspci` to list them.

Konrad's right, this is expected behavior.  I'm thinking we can mark this as an enhancement request instead of a 3rd party issue though.

Here's an idea...

lspci has a -F option, which takes the name of a file which contains the output of a previous lspci -x execution.
The lspci -x output is pretty basic - we could easily generate the contents of such a file from the VMD library and even trigger generation of the file content from a new RPC.  The beautiful thing is that it seems as long as you put some name for the device after the PCI BDF, lspci will later look up the actual name of the device using the PCI vendor+device ID in the lspci output and look up the real name for the device.

So then the flow would look something like:

```
scripts/rpc.py vmd_lspci > /tmp/lspci.txt
lspci -F /tmp/lspci.txt
```

The only challenge here is that IIRC, DAOS (the application tanabarr is working on) doesn't expose the RPC interface, so they would need some kind of sideband mechanism to generate that lspci.txt file.  But the solution above would work well for anyone using VMD with an in-tree SPDK application.

**Comment by jimharris** [comment] 2021-12-09 15:27
We could also implement this at the env_dpdk layer, so that it covers all PCI devices claimed by the application, not just those behind VMD.  That would have the added benefit of being able to test this lspci functionality without a VMD system.

**Comment by bensallen** [comment] 2021-12-09 16:27
I wonder, long term, if it would be worth adding and trying to upstream a PCI access method, eg. lspci -A for SPDK?

```
~/ # lspci -A help 
Known PCI access methods:             
                                      
linux-sysfs                           
linux-proc                            
intel-conf1                           
intel-conf2                           
dump
```

These implementations can be found under https://github.com/pciutils/pciutils/tree/master/lib, like proc.c, sysfs.c, etc

**Comment by ksztyber** [comment] 2021-12-10 11:59
@jimharris, tyeah, we could definitely add something like this (and it doesn't seem like a lot of work either). I'll mark it as an enhancement then.

@bensallen, that is also a very interesting idea, it'd make the usage even more straight-forward. Once we have the RPC in place, we could call it from lspci directly.

**Comment by jimharris** [comment] 2021-12-13 17:47
> I've pushed a small series adding something like this: https://review.spdk.io/gerrit/c/spdk/spdk/+/10653

Thanks @ksztyber!  I separately created this series, since the spdk_pci_get_[first|next]_device isn't really safe for hotplug reasons:  https://review.spdk.io/gerrit/c/spdk/spdk/+/10655.  Could you rebase your series to use this new spdk_pci_for_each_device API instead?

**Comment by ksztyber** [comment] 2021-12-13 18:10
@jimharris, yeah, I was wondering about that API not being safe myself. I've just rebased my patches.

**Comment by tanabarr** [comment] 2021-12-14 11:44
> I've pushed a small series adding something like this: https://review.spdk.io/gerrit/c/spdk/spdk/+/10653
> 
> @tanabarr, I don't have a machine with VMD to test this, so could you check if it works on your end with the NVMe drives behind the VMD?

sorry I haven't been paying attention, what exactly should I test and expect to see @ksztyber ?

**Comment by tanabarr** [comment] 2021-12-14 11:50
My VMD system currently has openSUSE LEAP 15.2 and I have to call `/sbin/lspci`, hence the script fails as follows:
```
tanabarr@wolf-157:~/projects/spdk> scripts/lspci
scripts/lspci: line 6: lspci: command not found
tanabarr@wolf-157:~/projects/spdk> Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by ksztyber** [comment] 2021-12-15 09:11
> My VMD system currently has openSUSE LEAP 15.2 and I have to call /sbin/lspci, hence the script fails as follows:
>```
> tanabarr@wolf-157:~/projects/spdk> scripts/lspci
> scripts/lspci: line 6: lspci: command not found
> tanabarr@wolf-157:~/projects/spdk> Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
> BrokenPipeError: [Errno 32] Broken pipe
>```
Yeah, you need `lscpi` to be in your `PATH`. I think you should be able to do something like:
```
PATH=$PATH:/sbin scripts/lscpi
```
However, the script uses SPDK's RPC to retrieve the data, so you probably need to just run it as root anyway.

>…unless I run from within the scripts directory:
>```
> tanabarr@wolf-157:~/projects/spdk/scripts> sudo lspci
>0000:00:00.0 Host bridge: Intel Corporation Sky Lake-E DMI3 Registers (rev 06)
>```
You're using your system's lspci here. To use the SPDK's script from the `scripts/` directory, you'd have to use `./lspci`.

But, as you've noticed, it only lists devices that are attached by the SPDK process (not just unbound from the kernel's NVMe driver), so you'd need to attach them first (e.g. via `bdev_nvme_attach_controller`). Also, keep in mind that for VMD, you need to have it enabled in your config, e.g.:
```
$ cat config.json
{
  "subsystems": [
    {
      "subsystem": "vmd",
      "config": [
        {
          "method": "enable_vmd"
        }
      ]
    }
  ]
}
# build/bin/spdk_tgt -c config.json
```
As for the apps, you could use `spdk_lspci` to list the NVMe/PCI devices. It doesn't show everything `lspci` does, but should be enough to list the drives behind the VMD.

**Comment by jimharris** [comment] 2021-12-22 00:14
@tanabarr - can we close this issue?  I think SPDK has now provided what it can to support getting information about devices behind the VMD endpoint when the SPDK VMD driver owns the device.  I think there's still some plumbing work needed in DAOS, but if that's not going to be ready for a while, I'd prefer to close this issue now.  We can revisit down the road if a problem is found with the APIs that we've provided.

**Closed** 2022-02-03 23:35 UTC
Labels: enhancement, Patches out for review
