### ISSUE TITLE
[nvmf_ns_hotplug_stress] transport wr pool count is 4095 but should be 2048

### ISSUE THREAD

**Issue by DamiaSan** [spdk/spdk#3361] opened 2024-04-29 12:20 UTC
# CI Intermittent Failure

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/121373/archive/nvmf-phy-autotest_70580/build.log

## Execution failed at
```
00:15:21.990  ========== Backtrace start: ==========
00:15:21.990  
00:15:21.990  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/common/autotest_common.sh:1111 -> run_test(["nvmf_ns_hotplug_stress"],["/var/jenkins/workspace/nvmf-phy-autotest/spdk/test/nvmf/target/ns_hotplug_stress.sh"],["--transport=rdma"])
00:15:21.990       ...
00:15:21.990     1106		timing_enter $test_name
00:15:21.990     1107		echo "************************************"
00:15:21.990     1108		echo "START TEST $test_name"
00:15:21.990     1109		echo "************************************"
00:15:21.990     1110		xtrace_restore
00:15:21.990     1111		time "$@"
00:15:21.990     1112		xtrace_disable
00:15:21.990     1113		echo "************************************"
00:15:21.990     1114		echo "END TEST $test_name"
00:15:21.991     1115		echo "************************************"
00:15:21.991     1116		timing_exit $test_name
00:15:21.991       ...
00:15:21.991  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/nvmf/nvmf.sh:32 -> main(["--transport=rdma"])
00:15:21.991       ...
00:15:21.991     27  		run_test "nvmf_connect_disconnect" $rootdir/test/nvmf/target/connect_disconnect.sh "${TEST_ARGS[@]}"
00:15:21.991     28  		run_test "nvmf_multitarget" $rootdir/test/nvmf/target/multitarget.sh "${TEST_ARGS[@]}"
00:15:21.991     29  		run_test "nvmf_rpc" $rootdir/test/nvmf/target/rpc.sh "${TEST_ARGS[@]}"
00:15:21.991     30  		run_test "nvmf_invalid" $rootdir/test/nvmf/target/invalid.sh "${TEST_ARGS[@]}"
00:15:21.991     31  		run_test "nvmf_abort" $rootdir/test/nvmf/target/abort.sh "${TEST_ARGS[@]}"
00:15:21.991  => 32  		run_test "nvmf_ns_hotplug_stress" $rootdir/test/nvmf/target/ns_hotplug_stress.sh "${TEST_ARGS[@]}"
00:15:21.991     33  		run_test "nvmf_connect_stress" $rootdir/test/nvmf/target/connect_stress.sh "${TEST_ARGS[@]}"
00:15:21.991     34  		run_test "nvmf_fused_ordering" $rootdir/test/nvmf/target/fused_ordering.sh "${TEST_ARGS[@]}"
00:15:21.991     35  		run_test "nvmf_delete_subsystem" $rootdir/test/nvmf/target/delete_subsystem.sh "${TEST_ARGS[@]}"
00:15:21.991     36  		run_test "nvmf_ns_masking" test/nvmf/target/ns_masking.sh "${TEST_ARGS[@]}"
00:15:21.991     37  		if [[ $SPDK_TEST_NVME_CLI -eq 1 ]]; then
00:15:21.991       ...
00:15:21.991  
00:15:21.991  ========== Backtrace end ==========
```

**Comment by spdkci** [comment] 2024-04-29 12:21
Another instance of this failure. Reported by @DamiaSan. log: https://ci.spdk.io/public_build/autotest-per-patch_121373.html

**Comment by mikeBashStuff** [comment] 2024-04-29 12:24
Actual failure happens a bit above while calling the `nvmf_subsystem_remove_ns()`:

```
00:15:20.340   13:20:55	-- target/ns_hotplug_stress.sh@35 -- # kill -0 786987
00:15:20.340   13:20:55	-- target/ns_hotplug_stress.sh@36 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_remove_ns nqn.2016-06.io.spdk:cnode1 1
00:15:20.603  request:
00:15:20.603  {
00:15:20.603    "nqn": "nqn.2016-06.io.spdk:cnode1",
00:15:20.603    "nsid": 1,
00:15:20.603    "method": "nvmf_subsystem_remove_ns",
00:15:20.603    "req_id": 1
00:15:20.603  }
00:15:20.603  Got JSON-RPC error response
00:15:20.603  response:
00:15:20.603  {
00:15:20.603    "code": -32603,
00:15:20.603    "message": "subsystem busy, retry later.\n"
00:15:20.603  }
00:15:20.603    13:20:55	-- target/ns_hotplug_stress.sh@36 -- # trap - ERR
00:15:20.603    13:20:55	-- target/ns_hotplug_stress.sh@36 -- # print_backtrace
00:15:20.603    13:20:55	-- common/autotest_common.sh@1139 -- # [[ ehxBET =~ e ]]
00:15:20.603    13:20:55	-- common/autotest_common.sh@1141 -- # args=('--transport=rdma')
00:15:20.603    13:20:55	-- common/autotest_common.sh@1141 -- # local args
00:15:20.603    13:20:55	-- common/autotest_common.sh@1143 -- # xtrace_disable
00:15:20.603    13:20:55	-- common/autotest_common.sh@10 -- # set +x
00:15:20.603  ========== Backtrace start: ==========
00:15:20.603  
00:15:20.603  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/nvmf/target/ns_hotplug_stress.sh:36 -> main(["--transport=rdma"])
00:15:20.603       ...
00:15:20.603     31  	$SPDK_BIN_DIR/spdk_nvme_perf -c 0x1 -r "trtype:$TEST_TRANSPORT adrfam:IPv4 traddr:$NVMF_FIRST_TARGET_IP trsvcid:$NVMF_PORT" \
00:15:20.603     32  		-t 30 -q 128 -w randread -o 512 -Q 1000 "${NO_HUGE[@]}" &
00:15:20.603     33  	PERF_PID=$!
00:15:20.603     34  	
00:15:20.603     35  	while kill -0 $PERF_PID; do
00:15:20.603  => 36  		$rpc_py nvmf_subsystem_remove_ns nqn.2016-06.io.spdk:cnode1 1
00:15:20.603     37  		$rpc_py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Delay0
00:15:20.604     38  		# Also test bdev/namespace resizing here, since it has a similar
00:15:20.604     39  		# effect on subsystem/namespace handling in the nvmf target
00:15:20.604     40  		null_size=$((null_size + 1))
00:15:20.604     41  		$rpc_py bdev_null_resize NULL1 $null_size
00:15:20.604       ...
00:15:20.604  
00:15:20.604  ========== Backtrace end ==========
```

Which makes it a duplicate of https://github.com/spdk/spdk/issues/3079.

**Closed by mikeBashStuff** 2024-04-29 12:24 UTC
Labels: Intermittent Failure

**Comment by DamiaSan** [comment] 2024-04-29 12:30
Sorry Mike, I tried to search in the opened intermittent failures the test `nvmf_ns_hotplug_stress` but didn't find anything, so I opened this new issue. Only now I see that the title of #3079 is `nvmf/ns_hotplug_stress`.
Thanks.
