### ISSUE TITLE
hugepages/default_setup - nr_hugepages failed check

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1999] opened 2021-06-16 19:46 UTC
00:02:26.801  ************************************
00:02:26.801  START TEST default_setup
00:02:26.801  ************************************
00:02:26.801   20:53:18	# xtrace_enable
00:02:26.801   20:53:18	# default_setup
00:02:26.801   20:53:18	# get_test_nr_hugepages 8388608 0
00:02:26.802   20:53:18	# local size=8388608
00:02:26.802   20:53:18	# (( 2 > 1 ))
00:02:26.802   20:53:18	# shift
00:02:26.802   20:53:18	# node_ids=("$@")
00:02:26.802   20:53:18	# local node_ids
00:02:26.802   20:53:18	# (( size >= default_huges ))
00:02:26.802   20:53:18	# nr_hugepages=4096
00:02:26.802   20:53:18	# get_test_nr_hugepages_per_node 0
00:02:26.802   20:53:18	# user_nodes=("$@")
00:02:26.802   20:53:18	# local user_nodes
00:02:26.802   20:53:18	# local _nr_hugepages=4096
00:02:26.802   20:53:18	# local _no_nodes=2
00:02:26.802   20:53:18	# nodes_test=()
00:02:26.802   20:53:18	# local -g nodes_test
00:02:26.802   20:53:18	# (( 1 > 0 ))
00:02:26.802   20:53:18	# for _no_nodes in "${user_nodes[@]}"
00:02:26.802   20:53:18	# nodes_test[_no_nodes]=4096
00:02:26.802   20:53:18	# return 0
00:02:26.802   20:53:18	# setup
00:02:26.802   20:53:18	# [[ '' == output ]]
00:02:26.802   20:53:18	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/setup.sh
00:02:28.194   20:53:20	# verify_nr_hugepages
00:02:28.195   20:53:20	# local node
00:02:28.195   20:53:20	# local sorted_t
00:02:28.195   20:53:20	# local sorted_s
00:02:28.195   20:53:20	# echo nr_hugepages=4096
00:02:28.195  nr_hugepages=4096
00:02:28.196   20:53:20	# (( 4722 == nr_hugepages ))
00:02:28.196    20:53:20	# trap - ERR
00:02:28.196    20:53:20	# print_backtrace
00:02:28.196    20:53:20	# [[ ehxBET =~ e ]]
00:02:28.196    20:53:20	# args=("${BASH_ARGV[@]}")
00:02:28.197    20:53:20	# local args
00:02:28.197    20:53:20	# xtrace_disable
00:02:28.197    20:53:20	# '[' no '!=' yes ']'
00:02:28.197    20:53:20	# PREV_BASH_OPTS=ehxBET
00:02:28.197    20:53:20	# [[ ehxBET == *\x* ]]
00:02:28.197    20:53:20	# XTRACE_DISABLED=yes
00:02:28.198    20:53:20	# set +x
00:02:28.198  ========== Backtrace start: ==========
00:02:28.198  
00:02:28.204  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/setup/hugepages.sh:86 -> verify_nr_hugepages([])
00:02:28.204       ...
00:02:28.204     81  		local node
00:02:28.204     82  		local sorted_t
00:02:28.204     83  		local sorted_s
00:02:28.204     84  	
00:02:28.204     85  		echo "nr_hugepages=$nr_hugepages"
00:02:28.204  => 86  		(($(< "$default_huge_nr") == nr_hugepages))
00:02:28.204     87  		(($(< "$global_huge_nr") == nr_hugepages))
00:02:28.204     88  		(($(get_meminfo HugePages_Total) == nr_hugepages))
00:02:28.204     89  	
00:02:28.204     90  		get_nodes
00:02:28.204     91  	

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_50052.html
Two tests failed here - for same reason.

**Comment by spdkci** [comment] 2021-06-16 19:46
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_50052.html

**Comment by jimharris** [comment] 2021-06-16 19:47
https://ci.spdk.io/public_build/autotest-per-patch_50044.html
WFP9 and GP12 both failed here.  (same as 50052 above)

**Comment by jimharris** [comment] 2021-06-16 19:49
https://ci.spdk.io/results/autotest-per-patch/builds/50029/archive/nvmf-tcp-phy-autotest/build.log
also on WFP9

**Comment by spdkci** [comment] 2021-06-16 19:50
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_50040.html

**Comment by spdkci** [comment] 2021-06-17 06:34
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_49976.html

**Comment by spdkci** [comment] 2021-06-17 07:25
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_50023.html

**Comment by spdkci** [comment] 2021-06-17 08:06
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_50021.html

**Comment by mikeBashStuff** [comment] 2021-06-17 08:49
Since all (or at least vast majority) of these reports point at either GP12 or WFP9 I went there and did some cleaning - something nasty must have happened on those systems since even when idle there were lingering spdk processes spinning doing nothing (so hugetlbfs mounts were not cleaned up). Also, for some reason, even though we don't allow hugepages to be overcommitted, kernel allocated surplus portion and that was affecting the results of the test (even when you clear the hugepages on given node the nr_hugepages still shows value > 0 due the surplus being available. No idea why this happened under our setup) - the test was allocating 8GB (4096 2M hugepages) but the total amount of hp at the end was greater than that (+ surplus).  

Boxes should be stable now, so let's monitor for some time to see if something similar pops up. Normally, when the tests fail the phy system should be automatically rebooted but in this case it didn't happen. The only reason I can think of is that system got suddenly disconnected from the jenkins - considering recent network failures we were experiencing it is possible that this is what caused the issue to surface (and considering the number of lingering processes that were left out, not only spdk's, this is more than likely).

**Comment by spdkci** [comment] 2021-06-17 08:51
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_50124.html

**Comment by spdkci** [comment] 2021-06-18 07:30
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_50253.html

**Comment by spdkci** [comment] 2021-06-18 07:30
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_50245.html

**Comment by spdkci** [comment] 2021-06-18 07:47
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_50192.html

**Comment by spdkci** [comment] 2021-06-18 07:48
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_50236.html

**Comment by spdkci** [comment] 2021-06-18 08:34
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_50269.html

**Comment by mikeBashStuff** [comment] 2021-06-18 10:19
There's still something wrong with how failures are handled on GP12 WFP9 - machines are not being rebooted for some reason whenever the build fails and that leaves lots of garbage for the next runs.

**Comment by spdkci** [comment] 2021-06-18 11:13
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_50252.html

**Comment by spdkci** [comment] 2021-06-18 11:16
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_50284.html

**Comment by spdkci** [comment] 2021-06-18 13:04
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_50304.html

**Comment by spdkci** [comment] 2021-06-21 02:22
Another instance of this failure. Reported by @ChengqiangMeng. log: https://ci.spdk.io/public_build/autotest-per-patch_50260.html

**Comment by spdkci** [comment] 2021-06-21 04:40
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_50420.html

**Comment by spdkci** [comment] 2021-06-21 20:48
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_50462.html

**Comment by spdkci** [comment] 2021-06-22 19:31
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_50537.html

**Comment by spdkci** [comment] 2021-06-23 06:04
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_50520.html

**Comment by spdkci** [comment] 2021-06-23 06:21
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_50534.html

**Comment by spdkci** [comment] 2021-06-24 17:38
Another instance of this failure. Reported by @jonathan-teh. log: https://ci.spdk.io/public_build/autotest-per-patch_50831.html

**Comment by spdkci** [comment] 2021-06-24 17:44
Another instance of this failure. Reported by @jonathan-teh. log: https://ci.spdk.io/public_build/autotest-per-patch_50842.html

**Comment by spdkci** [comment] 2021-06-24 17:56
Another instance of this failure. Reported by @jonathan-teh. log: https://ci.spdk.io/public_build/autotest-per-patch_50844.html

**Comment by spdkci** [comment] 2021-06-24 18:00
Another instance of this failure. Reported by @jonathan-teh. log: https://ci.spdk.io/public_build/autotest-per-patch_50843.html

**Comment by spdkci** [comment] 2021-06-24 18:05
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_50845.html

**Comment by spdkci** [comment] 2021-06-24 18:24
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_50848.html

**Comment by spdkci** [comment] 2021-06-24 22:05
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_50882.html

**Comment by karlatec** [comment] 2021-06-28 08:59
There was some hiccup on the CI side and physical systems were not rebooted correctly. Already fixed.
Let's wait a couple more days before closing.

**Comment by spdkci** [comment] 2021-06-29 02:25
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_51150.html

**Comment by jimharris** [comment] 2021-06-29 15:22
[Bug Scrub] @karlatec did a bunch of fixes on CI side.  Haven't seen this issue again over last 5 days.  Closing.

**Comment by spdkci** [comment] 2021-08-02 06:57
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_54669.html

**Comment by tomzawadzki** [comment] 2021-09-07 14:41
Not observed for over a month, closing.

**Comment by spdkci** [comment] 2022-03-08 10:16
Another instance of this failure. Reported by @jlevon. log: https://ci.spdk.io/public_build/autotest-per-patch_72883.html

**Comment by spdkci** [comment] 2022-03-08 11:07
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_72903.html

**Comment by tomzawadzki** [comment] 2022-03-08 12:15
Two instances above occurred on WFP9.

**Comment by tomzawadzki** [comment] 2022-03-08 15:12
[Bug scrub] This issue was caused by WFP9 machine not restarting after a build failed. This has since been resolved. The status of jobs responsible for resetting physical nodes will now be more closes tracked.

@mikeBashStuff thanks for the suggestion, but it seems that was strictly infrastructure related. It might be better to catch such errors early, so keeping the test is beneficial.

**Closed by tomzawadzki** 2022-03-08 15:12 UTC
Labels: Infrastructure, Intermittent Failure

**Comment by jlevon** [comment] 2022-06-08 11:36
I'm still seeing this apparently? https://ci.spdk.io/results/autotest-per-patch/builds/78413/archive/crypto-autotest/build.log

**Comment by karlatec** [comment] 2022-06-08 12:57
@jlevon already resolved, minor glitch after changes on infrastructure side

**Comment by Comphix** [comment] 2022-10-26 12:17
Looks like this issue happened again:

https://ci.spdk.io/results/autotest-per-patch/builds/88319/archive/nvmf-phy-autotest/build.log

```
00:02:16.709   11:08:43	-- setup/hugepages.sh@100 -- # echo nr_hugepages=1024
00:02:16.709  nr_hugepages=1024
00:02:16.709   11:08:43	-- setup/hugepages.sh@101 -- # echo resv_hugepages=0
00:02:16.709  resv_hugepages=0
00:02:16.709   11:08:43	-- setup/hugepages.sh@102 -- # echo surplus_hugepages=2540
00:02:16.709  surplus_hugepages=2540
00:02:16.709   11:08:43	-- setup/hugepages.sh@103 -- # echo anon_hugepages=12288
00:02:16.709  anon_hugepages=12288
00:02:16.709   11:08:43	-- setup/hugepages.sh@105 -- # (( 2540 == nr_hugepages + surp + resv ))
00:02:16.709    11:08:43	-- setup/hugepages.sh@105 -- # trap - ERR
00:02:16.709    11:08:43	-- setup/hugepages.sh@105 -- # print_backtrace
00:02:16.709    11:08:43	-- common/autotest_common.sh@1083 -- # [[ ehxBET =~ e ]]
00:02:16.709    11:08:43	-- common/autotest_common.sh@1085 -- # args=('default_setup' 'default_setup')
00:02:16.709    11:08:43	-- common/autotest_common.sh@1085 -- # local args
00:02:16.709    11:08:43	-- common/autotest_common.sh@1087 -- # xtrace_disable
00:02:16.709    11:08:43	-- common/autotest_common.sh@16 -- # '[' no '!=' yes ']'
00:02:16.709    11:08:43	-- common/autotest_common.sh@17 -- # PREV_BASH_OPTS=ehxBET
00:02:16.709    11:08:43	-- common/autotest_common.sh@18 -- # [[ ehxBET == *\x* ]]
00:02:16.709    11:08:43	-- common/autotest_common.sh@19 -- # XTRACE_DISABLED=yes
00:02:16.709    11:08:43	-- common/autotest_common.sh@21 -- # set +x
00:02:16.709  ========== Backtrace start: ==========
00:02:16.709  
00:02:16.709  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/setup/hugepages.sh:105 -> verify_nr_hugepages([])
00:02:16.709       ...
00:02:16.709     100 		echo "nr_hugepages=$nr_hugepages"
00:02:16.709     101 		echo "resv_hugepages=$resv"
00:02:16.709     102 		echo "surplus_hugepages=$surp"
00:02:16.709     103 		echo "anon_hugepages=${anon:-disabled}"
00:02:16.709     104 	
00:02:16.709  => 105 		(($(< "$default_huge_nr") == nr_hugepages + surp + resv))
00:02:16.709     106 		# This knob doesn't account for the surp, resv hugepages
00:02:16.709     107 		(($(< "$global_huge_nr") == nr_hugepages))
00:02:16.709     108 		(($(get_meminfo HugePages_Total) == nr_hugepages + surp + resv))
00:02:16.709     109 	
00:02:16.709     110 		get_nodes
```

**Comment by mikeBashStuff** [comment] 2022-10-26 12:19
Yes, WFP9 was not being properly reset upon previous failures - there were lingering qemu and vhost instance still running which use hugepages. This can be seen here: https://ci.spdk.io/results/autotest-per-patch/builds/88319/archive/nvmf-phy-autotest/proc_list.txt.

This node was taken offline until issue with the APC is resolved.
