### ISSUE TITLE
Intermittent failure in OCF test

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1025] opened 2019-11-01 05:48 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/48532/archive/nvme_phy_autotest/failed_test.log

https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48532.html

```
/var/jenkins/workspace/NVMe_tests/nvme_phy_autotest/spdk/test/common/autotest_common.sh: line 381: kill: (2064058) - No such process
ERROR: process (pid: 2064058) is no longer running
 06:38:58	# xtrace_enable
 06:38:58	# ((  i == 0  ))
 06:38:58	# return 1
  06:38:58	# trap - ERR
  06:38:58	# print_backtrace
  06:38:58	# [[ ehxBE =~ e ]]
  06:38:58	# xtrace_disable
  06:38:58	# PREV_BASH_OPTS=ehxBE
  06:38:58	# set +x
========== Backtrace start: ==========

in /var/jenkins/workspace/NVMe_tests/nvme_phy_autotest/spdk/test/ocf/integrity/bdevperf-iotypes.sh:15 -> main()
     ...
   10  	$bdevperf -c $curdir/mallocs.conf -q 128 -o 4096 -t 4 -w flush
   11  	$bdevperf -c $curdir/mallocs.conf -q 128 -o 4096 -t 4 -w unmap
   12  	
   13  	$bdevperf -c $curdir/mallocs.conf -q 128 -o 4096 -t 4 -w write -r /var/tmp/spdk.sock &
   14  	bdev_perf_pid=$!
=> 15  	waitforlisten $bdev_perf_pid
   16  	sleep 1
   17  	$rpc_py bdev_ocf_get_stats MalCache1
   18  	wait $bdev_perf_pid
     ...
```

**Comment by jimharris** [comment] 2019-11-07 00:45
I think this is another one of the CI scheduling problems (like the rpc_client_test #839 issue).

I'd suggest that we change this test to:
1) just do a write test for 4 seconds, without running in the background
2) add a new test that runs for 120 seconds in the background, waitforlisten, bdev_ocf_get_stats and then just kill bdevperf

@Donaim - what do you think?  Can you take a look and create a patch?

**Comment by Donaim** [comment] 2019-11-08 08:50
@jimharris agree that is probably due to some CI problem, not caused by OCF module. I will investigate and implement your suggestion.

**Comment by spdkci** [comment] 2019-11-11 04:45
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49386.html

**Comment by spdkci** [comment] 2019-11-12 00:42
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49439.html

**Comment by jimharris** [comment] 2019-11-15 15:23
Patch merged.

**Closed by jimharris** 2019-11-15 15:23 UTC
Labels: Intermittent Failure
