### ISSUE TITLE
[nvme_err_injection] GET FEATURES NUMBER OF QUEUES timeout

### ISSUE THREAD

**Issue by mgerdts** [spdk/spdk#2856] opened 2023-01-05 19:18 UTC
# CI Intermittent Failure

nvme_err_injection

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/94115/archive/nvme-cmb-pmr-vg-autotest/build.log

## Execution failed at

```
00:06:14.189  ************************************
00:06:14.189  START TEST nvme_err_injection
00:06:14.189  ************************************
00:06:14.189   18:18:54	-- common/autotest_common.sh@1059 -- # xtrace_enable
00:06:14.189   18:18:54	-- common/autotest_common.sh@1060 -- # /home/vagrant/spdk_repo/spdk/test/nvme/err_injection/err_injection
00:06:14.448  [2023-01-05 18:18:55.001317] nvme_qpair.c: 558:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
00:06:14.448  [2023-01-05 18:18:55.001583] nvme_qpair.c: 213:nvme_admin_qpair_print_command: *NOTICE*: GET FEATURES NUMBER OF QUEUES cid:0 cdw10:00000007 PRP1 0x0 PRP2 0x0
00:06:14.448  [2023-01-05 18:18:55.001715] nvme_qpair.c: 474:spdk_nvme_print_completion: *NOTICE*: INVALID FIELD (00/02) qid:0 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
00:16:48.101  Cancelling nested steps due to timeout
00:16:48.105  Sending interrupt signal to process
00:16:51.252  script returned exit code 255
00:16:51.257  [Pipeline] }
00:16:51.281  [Pipeline] // timeout
00:16:51.290  [Pipeline] }
00:16:51.316  [Pipeline] // stage
00:16:51.327  [Pipeline] }
00:16:51.331  Timeout has been exceeded
00:16:51.353  [Pipeline] // catchError
00:16:51.366  [Pipeline] stage
00:16:51.369  [Pipeline] { (Stop VM)
00:16:51.387  [Pipeline] sh
00:16:51.666  + vagrant halt
00:16:55.858  ==> default: Halting domain...
00:17:01.143  [Pipeline] sh
00:17:01.422  + vagrant destroy -f
00:17:04.710  ==> default: Removing domain...
00:17:04.982  [Pipeline] sh
00:17:05.261  + mv output /var/jenkins/workspace/nvme-cmb-pmr-vg-autotest@2/output
00:17:05.270  [Pipeline] }
00:17:05.290  [Pipeline] // stage
00:17:05.297  [Pipeline] }
00:17:05.316  [Pipeline] // dir
00:17:05.323  [Pipeline] }
00:17:05.343  [Pipeline] // wrap
00:17:05.351  [Pipeline] }
00:17:05.367  [Pipeline] // catchError
00:17:05.378  [Pipeline] stage
00:17:05.380  [Pipeline] { (Epilogue)
00:17:05.397  [Pipeline] sh
00:17:05.678  + jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh
00:17:07.071  [Pipeline] catchError
00:17:07.074  [Pipeline] {
00:17:07.095  [Pipeline] sh
00:17:07.379  + jbp/jenkins/jjb-config/jobs/scripts/check_artifacts_size.sh
00:17:07.379  Artifacts sizes are good
00:17:07.389  [Pipeline] }
00:17:07.408  [Pipeline] // catchError
00:17:07.423  [Pipeline] archiveArtifacts
00:17:07.431  Archiving artifacts
00:17:07.503  [Pipeline] cleanWs
00:17:07.516  [WS-CLEANUP] Deleting project workspace...
00:17:07.516  [WS-CLEANUP] Deferred wipeout is used...
00:17:07.523  [WS-CLEANUP] done
00:17:07.527  [Pipeline] }
00:17:07.549  [Pipeline] // stage
00:17:07.557  [Pipeline] }
00:17:07.576  [Pipeline] // node
00:17:07.584  [Pipeline] End of Pipeline
00:17:07.605  Finished: ABORTED
```

**Comment by spdkci** [comment] 2023-01-05 19:19
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_94115.html

**Comment by Comphix** [comment] 2023-01-06 06:55
Raised a potential fix here: https://review.spdk.io/gerrit/c/spdk/spdk/+/16171

**Comment by Comphix** [comment] 2023-01-19 04:20
Looks like this issue is not seen recently. Will keep it open for some more time.

**Comment by jimharris** [comment] 2023-03-10 19:41
This hasn't occurred again for over 2 months.

**Comment by mikeBashStuff** [comment] 2023-12-18 08:53
This issue is still out there in the wild: https://ci.spdk.io/results/autotest-nightly-lts/builds/1237/archive/zns-vg-autotest_61419/build.log

**Comment by jchachux** [comment] 2024-05-09 10:44
We have not been able to reproduce this issue. As a result, we are closing this issue for now.

If someone encounters this issue again in the future, please don't hesitate to reopen it. Thank you for your understanding and cooperation.

**Closed by jchachux** 2024-05-09 10:44 UTC
Labels: Intermittent Failure
