### ISSUE TITLE
nvmf_bdev_io_wait test got stuck while waiting for bdevperf to finish

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2033] opened 2021-07-07 14:36 UTC
https://ci.spdk.io/results/autotest-per-patch/builds/52088/archive/nvmf-tcp-phy-autotest/index.html

```
00:04:09.341   16:12:04	# /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/bdev/bdevperf/bdevperf -m 0x80 -i 4 --json /dev/fd/63 -q 128 -o 4096 -w unmap -t 1
00:04:09.342    16:12:04	# gen_nvmf_target_json
00:04:09.342    16:12:04	# config=()
00:04:09.342    16:12:04	# local subsystem config
00:04:09.342    16:12:04	# for subsystem in "${@:-1}"
00:04:09.343    16:12:04	# config+=("$(
00:04:09.343  				cat <<- EOF
00:04:09.343  					{
00:04:09.343  					  "params": {
00:04:09.343  					    "name": "Nvme$subsystem",
00:04:09.343  					    "trtype": "$TEST_TRANSPORT",
00:04:09.343  					    "traddr": "$NVMF_FIRST_TARGET_IP",
00:04:09.343  					    "adrfam": "ipv4",
00:04:09.343  					    "trsvcid": "$NVMF_PORT",
00:04:09.343  					    "subnqn": "nqn.2016-06.io.spdk:cnode$subsystem",
00:04:09.343  					    "hostnqn": "nqn.2016-06.io.spdk:host$subsystem",
00:04:09.343  					    "hdgst": ${hdgst:-false},
00:04:09.343  					    "ddgst": ${ddgst:-false}
00:04:09.343  					  },
00:04:09.343  					  "method": "bdev_nvme_attach_controller"
00:04:09.343  					}
00:04:09.343  				EOF
00:04:09.343  			)")
00:04:09.343     16:12:04	# cat
00:04:09.343     16:12:04	# cat
00:04:09.343    16:12:04	# jq .
00:04:09.344    16:12:04	# jq .
00:04:09.344     16:12:04	# IFS=,
00:04:09.344     16:12:04	# IFS=,
00:04:09.344     16:12:04	# printf '%s\n' '{
00:04:09.344    "params": {
00:04:09.344      "name": "Nvme1",
00:04:09.344      "trtype": "tcp",
00:04:09.344      "traddr": "10.0.0.2",
00:04:09.344      "adrfam": "ipv4",
00:04:09.344      "trsvcid": "4420",
00:04:09.344      "subnqn": "nqn.2016-06.io.spdk:cnode1",
00:04:09.344      "hostnqn": "nqn.2016-06.io.spdk:host1",
00:04:09.344      "hdgst": false,
00:04:09.344      "ddgst": false
00:04:09.344    },
00:04:09.344    "method": "bdev_nvme_attach_controller"
00:04:09.344  }'
00:04:09.344     16:12:04	# printf '%s\n' '{
00:04:09.344    "params": {
00:04:09.344      "name": "Nvme1",
00:04:09.344      "trtype": "tcp",
00:04:09.344      "traddr": "10.0.0.2",
00:04:09.344      "adrfam": "ipv4",
00:04:09.344      "trsvcid": "4420",
00:04:09.344      "subnqn": "nqn.2016-06.io.spdk:cnode1",
00:04:09.344      "hostnqn": "nqn.2016-06.io.spdk:host1",
00:04:09.344      "hdgst": false,
00:04:09.344      "ddgst": false
00:04:09.344    },
00:04:09.344    "method": "bdev_nvme_attach_controller"
00:04:09.344  }'
00:04:09.345    16:12:04	# jq .
00:04:09.345    16:12:04	# jq .
00:04:09.345     16:12:04	# IFS=,
00:04:09.345     16:12:04	# printf '%s\n' '{
00:04:09.345    "params": {
00:04:09.345      "name": "Nvme1",
00:04:09.345      "trtype": "tcp",
00:04:09.345      "traddr": "10.0.0.2",
00:04:09.345      "adrfam": "ipv4",
00:04:09.345      "trsvcid": "4420",
00:04:09.345      "subnqn": "nqn.2016-06.io.spdk:cnode1",
00:04:09.345      "hostnqn": "nqn.2016-06.io.spdk:host1",
00:04:09.345      "hdgst": false,
00:04:09.345      "ddgst": false
00:04:09.345    },
00:04:09.345    "method": "bdev_nvme_attach_controller"
00:04:09.345  }'
00:04:09.345     16:12:04	# IFS=,
00:04:09.346     16:12:04	# printf '%s\n' '{
00:04:09.346    "params": {
00:04:09.346      "name": "Nvme1",
00:04:09.346      "trtype": "tcp",
00:04:09.346      "traddr": "10.0.0.2",
00:04:09.346      "adrfam": "ipv4",
00:04:09.346      "trsvcid": "4420",
00:04:09.346      "subnqn": "nqn.2016-06.io.spdk:cnode1",
00:04:09.346      "hostnqn": "nqn.2016-06.io.spdk:host1",
00:04:09.346      "hdgst": false,
00:04:09.346      "ddgst": false
00:04:09.346    },
00:04:09.346    "method": "bdev_nvme_attach_controller"
00:04:09.346  }'
00:04:09.350   16:12:04	# wait 2844993
00:04:09.362  [2021-07-07 16:12:04.631567] Starting SPDK v21.07-pre git sha1 dea7973c8 / DPDK 21.05.0 initialization...
00:04:09.362  [2021-07-07 16:12:04.631567] Starting SPDK v21.07-pre git sha1 dea7973c8 / DPDK 21.05.0 initialization...
00:04:09.362  [2021-07-07 16:12:04.631567] Starting SPDK v21.07-pre git sha1 dea7973c8 / DPDK 21.05.0 initialization...
00:04:09.362  [2021-07-07 16:12:04.631571] Starting SPDK v21.07-pre git sha1 dea7973c8 / DPDK 21.05.0 initialization...
00:04:09.363  [2021-07-07 16:12:04.631657] [ DPDK EAL parameters: [2021-07-07 16:12:04.631657] [ DPDK EAL parameters: [2021-07-07 16:12:04.631658] [ DPDK EAL parameters: [2021-07-07 16:12:04.631658] [ DPDK EAL parameters: [2021-07-07 16:12:04.631670] bdevperf [2021-07-07 16:12:04.631671] bdevperf [2021-07-07 16:12:04.631672] bdevperf [2021-07-07 16:12:04.631672] bdevperf [2021-07-07 16:12:04.631679] -c 0x40 [2021-07-07 16:12:04.631681] -c 0x80 [2021-07-07 16:12:04.631681] -c 0x20 [2021-07-07 16:12:04.631681] -c 0x10 [2021-07-07 16:12:04.631688] --log-level=lib.eal:6 [2021-07-07 16:12:04.631689] --log-level=lib.eal:6 [2021-07-07 16:12:04.631690] --log-level=lib.eal:6 [2021-07-07 16:12:04.631690] --log-level=lib.eal:6 [2021-07-07 16:12:04.631696] --log-level=lib.cryptodev:5 [2021-07-07 16:12:04.631697] --log-level=lib.cryptodev:5 [2021-07-07 16:12:04.631699] --log-level=lib.cryptodev:5 [2021-07-07 16:12:04.631699] --log-level=lib.cryptodev:5 [2021-07-07 16:12:04.631704] --log-level=user1:6 [2021-07-07 16:12:04.631705] --log-level=user1:6 [2021-07-07 16:12:04.631707] --log-level=user1:6 [2021-07-07 16:12:04.631708] --log-level=user1:6 [2021-07-07 16:12:04.631712] --base-virtaddr=0x200000000000 [2021-07-07 16:12:04.631713] --base-virtaddr=0x200000000000 [2021-07-07 16:12:04.631716] --base-virtaddr=0x200000000000 [2021-07-07 16:12:04.631716] --base-virtaddr=0x200000000000 [2021-07-07 16:12:04.631720] --match-allocations [2021-07-07 16:12:04.631721] --match-allocations [2021-07-07 16:12:04.631724] --match-allocations [2021-07-07 16:12:04.631724] --match-allocations [2021-07-07 16:12:04.631728] --file-prefix=spdk3 [2021-07-07 16:12:04.631729] --file-prefix=spdk4 [2021-07-07 16:12:04.631732] --file-prefix=spdk1 [2021-07-07 16:12:04.631733] --file-prefix=spdk2 [2021-07-07 16:12:04.631736] --proc-type=auto [2021-07-07 16:12:04.631737] --proc-type=auto [2021-07-07 16:12:04.631740] --proc-type=auto [2021-07-07 16:12:04.631741] --proc-type=auto [2021-07-07 16:12:04.631744] ]
00:04:09.363  [2021-07-07 16:12:04.631745] ]
00:04:09.363  [2021-07-07 16:12:04.631748] ]
00:04:09.363  [2021-07-07 16:12:04.631749] ]
00:04:09.438  EAL: No free 2048 kB hugepages reported on node 1
00:04:09.438  EAL: No available 1048576 kB hugepages reported
00:04:09.442  EAL: No free 2048 kB hugepages reported on node 1
00:04:09.442  EAL: No available 1048576 kB hugepages reported
00:04:09.446  EAL: No free 2048 kB hugepages reported on node 1
00:04:09.447  EAL: No available 1048576 kB hugepages reported
00:04:09.450  EAL: No free 2048 kB hugepages reported on node 1
00:04:09.451  EAL: No available 1048576 kB hugepages reported
00:04:09.455  TELEMETRY: No legacy callbacks, legacy socket not created
00:04:09.455  TELEMETRY: No legacy callbacks, legacy socket not created
00:04:09.456  TELEMETRY: No legacy callbacks, legacy socket not created
00:04:09.456  TELEMETRY: No legacy callbacks, legacy socket not created
00:04:09.565  [2021-07-07 16:12:04.787476] app.c: 537:spdk_app_start: *NOTICE*: Total cores available: 1
00:04:09.566  [2021-07-07 16:12:04.787550] app.c: 537:spdk_app_start: *NOTICE*: Total cores available: 1
00:04:09.566  [2021-07-07 16:12:04.787605] app.c: 537:spdk_app_start: *NOTICE*: Total cores available: 1
00:04:09.566  [2021-07-07 16:12:04.787609] app.c: 537:spdk_app_start: *NOTICE*: Total cores available: 1
00:04:09.780  [2021-07-07 16:12:05.049624] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 7
00:04:09.789  [2021-07-07 16:12:05.058491] accel_engine.c: 920:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:04:09.800  [2021-07-07 16:12:05.069211] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 5
00:04:09.809  [2021-07-07 16:12:05.078037] accel_engine.c: 920:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:04:09.813  [2021-07-07 16:12:05.082558] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 6
00:04:09.822  [2021-07-07 16:12:05.091393] accel_engine.c: 920:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:04:09.825  [2021-07-07 16:12:05.094693] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 4
00:04:09.834  [2021-07-07 16:12:05.103470] accel_engine.c: 920:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:04:10.099  Running I/O for 1 seconds...
00:04:10.119  Running I/O for 1 seconds...
00:04:10.119  Running I/O for 1 seconds...
00:04:10.119  Running I/O for 1 seconds...
00:04:11.107  
 Job: Nvme1n1 (Core Mask 0x80)
00:04:11.107  	 Nvme1n1             :   15532.00 IOPS      60.67 MiB/s
00:04:11.107  
 =============================================================
00:04:11.107  
 Total                       :   15532.00 IOPS      60.67 MiB/s
00:04:11.122  
 Job: Nvme1n1 (Core Mask 0x40)
00:04:11.122  	 Nvme1n1             :  233064.00 IOPS     910.41 MiB/s
00:04:11.122  
 =============================================================
00:04:11.122  
 Total                       :  233064.00 IOPS     910.41 MiB/s
00:04:11.128  
 Job: Nvme1n1 (Core Mask 0x20)
00:04:11.128  	 Nvme1n1             :   13110.00 IOPS      51.21 MiB/s
00:04:11.128  
 =============================================================
00:04:11.128  
 Total                       :   13110.00 IOPS      51.21 MiB/s
00:15:22.940  Build timed out (after 15 minutes). Marking the build as failed.
00:15:22.950  Build was aborted
00:15:22.951  [PostBuildScript] - [INFO] Executing post build scripts.
00:15:22.958  [nvmf-tcp-phy-autotest] $ /usr/bin/env bash /tmp/jenkins1732716410831815662.sh
00:15:22.961  Start stage post_get_build_log.sh
```

**Comment by spdkci** [comment] 2021-07-07 14:36
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_52088.html

**Comment by yidong0635** [comment] 2021-07-09 00:37
bdevperf can be in a wild state with endless printing , and the time limitation has no effect . That will be appreciated if anyone 
have time to find the root cause.

**Comment by Comphix** [comment] 2021-08-02 08:41
Looks like this issue is about 20 days ago. Shall we close it for the time being if it does not happen recently?

**Closed** 2021-08-10 14:59 UTC
Labels: Intermittent Failure
