### ISSUE TITLE
setup.sh should load required iommu module

### ISSUE THREAD

**Issue by mgerdts** [spdk/spdk#1689] opened 2020-11-18 16:24 UTC
## Expected Behavior

After running `scripts/setup.sh`, I should be able to use NVMe drives.

## Current Behavior

The nvme driver is unbound and the vfio driver is bound, but while starting `spdk_tgt` I see:

```
# /opt/spdk/bin/spdk_tgt -m 0x8
[2020-11-18 15:49:57.727654] Starting SPDK v20.10 git sha1 e5d26ecc2 / DPDK 20.08.0 initialization...
[2020-11-18 15:49:57.728231] [ DPDK EAL parameters: [2020-11-18 15:49:57.728379] spdk_tgt [2020-11-18 15:49:57.728521] --no-shconf [2020-11-18 15:49:57.728667] -c 0x8 [2020-11-18 15:49:57.728804] --log-level=lib.eal:6 [2020-11-18 15:49:57.728940] --log-level=lib.cryptodev:5 [2020-11-18 15:49:57.729077] --log-level=user1:6 [2020-11-18 15:49:57.729214] --base-virtaddr=0x200000000000 [2020-11-18 15:49:57.729351] --match-allocations [2020-11-18 15:49:57.729488] --file-prefix=spdk_pid50 [2020-11-18 15:49:57.729633] ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL:   no supported IOMMU extensions found!
EAL: VFIO support could not be initialized
...
```

While trying to attach an NVMe controller:

```
# scripts/rpc.py bdev_nvme_attach_controller -b cache -t PCIe -a 0000:87:00.0
request:
{
  "name": "cache",
  "trtype": "PCIe",
  "traddr": "0000:87:00.0",
  "method": "bdev_nvme_attach_controller",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -19,
  "message": "No such device"
}
```

## Possible Solution

At least on CentOS 8.2, add `modprobe vfio_iommu_type1` to `setup.sh`.  Alternatively (Additionally?), document this requirement any place that the related kernel command line changes are documented.

## Steps to Reproduce

1. `reboot`
2. `env PCI_WHITELIST=${BDF:-please_set_BDF_to_be_safe} scripts/setup.sh`
3. `bin/spdk_tgt`
4. `scripts/rpc.py  bdev_nvme_attach_controller -b cache -t PCIe -a $BDF`

## Context (Environment including OS version, SPDK version, etc.)

* SPDK v20.10 git sha1 e5d26ecc2 / DPDK 20.08.0
* CentOS 8, with `yum update` as of November 17, 2020
* Linux 4.18.0-193.28.1.el8_2.x86_64

**Comment by jimharris** [comment] 2020-11-18 16:34
Hi @mgerdts,

Specifically on your comment here:

env PCI_WHITELIST=${BDF:-**set_BDF_or_your_nvme_root_disk_will_be_toast_not_that_it_ever_happened_to_me**} scripts/setup.sh

Has this happened to you recently?  setup.sh tries to check if there are active mounts on an nvme ssd before trying to unbind it.  If there's a bug there, we need to fix it.

-Jim

**Comment by mgerdts** [comment] 2020-11-18 16:59
> Hi @mgerdts,
> 
> Specifically on your comment here:
> 
> env PCI_WHITELIST=${BDF:-**set_BDF_or_your_nvme_root_disk_will_be_toast_not_that_it_ever_happened_to_me**} scripts/setup.sh
> 
> Has this happened to you recently? setup.sh tries to check if there are active mounts on an nvme ssd before trying to unbind it. If there's a bug there, we need to fix it.
> 
> -Jim

Yeah, I got bit by that.  I ran `setup.sh` without any options and my root disk disappeared.

It may be that I ran it in a privileged docker container, which would make it rather hard for the script to do the right thing.  With that understanding, I'll tone down the snark in the description.

**Comment by jimharris** [comment] 2020-11-18 17:17
We hadn't considered the privileged docker container case when making those setup.sh checks.  If you're willing I'd love to see if we could figure out how to guard against unmounting the root disk in that case too.  Currently we use info from /sys/block and /proc/sys/mountinfo to make decisions.  What do those look like in a privileged docker container?

Tagging @mikeBashStuff since I'd be leaning on him to help with the setup.sh changes.

**Comment by mgerdts** [comment] 2020-11-18 18:10
I don't see a significant difference `/sys/block/nvme*` nor `/proc/self/mountinfo`.  Perhaps the problem here is that lvm is used.

```
# awk '$5 == "/"' /proc/self/mountinfo
95 0 253:0 / / rw,relatime shared:1 - xfs /dev/mapper/my_vg-root rw,seclabel,attr2,inode64,noquota
```

Maybe a better/additional check would be:

```
# find /sys/bus/pci/devices/0000:01:00.0/ -wholename /*/holders/*
/sys/bus/pci/devices/0000:01:00.0/nvme/nvme0/nvme0n1/nvme0n1p1/holders/dm-1
/sys/bus/pci/devices/0000:01:00.0/nvme/nvme0/nvme0n1/nvme0n1p1/holders/dm-2
/sys/bus/pci/devices/0000:01:00.0/nvme/nvme0/nvme0n1/nvme0n1p1/holders/dm-0
```

The trailing `/` on the `/sys/bus/pci/devices/<bdf>/` is important so that it follows that symlink.

**Comment by mikeBashStuff** [comment] 2020-11-19 08:49
@jimharris @mgerdts I will take a look at it. I admit, I didn't take lvm|md devices into consideration while doing recent rewrites - I guess that was the itch at the back of my head a I had for some time now, trying to tell me I forgot about something. Since this doesn't seem to be related to the main problem reported under this issue though (the missing iommu extension) I will open a separate issue for it, marking it as critical (considering the havoc it may cause on the system).

**Comment by mikeBashStuff** [comment] 2020-11-19 10:11
@mgerdts  https://review.spdk.io/gerrit/c/spdk/spdk/+/5167 - this patch should prevent `setup.sh` from hijacking the nvme|virtio devices when they are part of a virtual device setup, would you kindly take it for a spin and see if it works on your end? I pasted results from my tests here: https://github.com/spdk/spdk/issues/1691#issuecomment-730266616

**Comment by mgerdts** [comment] 2020-11-23 15:02
Thanks, @mikeBashStuff.  I have confirmed that in-use devices are detected and I no longer lose my root file system while not running in a container.

When I tried to run it in a privileged container, `setup.sh` failed in an unrelated way due to an unconditional `modprobe uio` and missing content from the container's `/lib/modules`.  That's probably for the best, as I'm pretty sure the fix does not handle cases where an nvme device is visible in a privileged container but mounts that depend on it are not visible.  Running `setup.sh` in a privileged container sounds like a bad idea anyway.  Someone that cares about their data would be better off running `setup.sh` outside of any containers then using least-privileges principles to dole out access to the required vfio devices.

For those that are skipping to this message, the main problem reported in this bug has not been resolved and the issue should remain open.

**Comment by jimharris** [comment] 2020-11-23 15:06
Thanks @mikeBashStuff and @mgerdts for the updates on this.

@mikeBashStuff can you take a look at updating setup.sh to address the original issue reported by @mgerdts?

**Comment by mikeBashStuff** [comment] 2020-11-23 16:54
@mgerdts Appreciate your feedback. :) I will proceed with closing the #1691. And I agree. Currently, `setup.sh` doesn't have any awareness as to which namespaces it's working with. That said, it's still possible to see host's mount namespace from within the container so technically we could make it a bit smarter in that department. I am not sure if it's worth the effort though (this would probably also force users to run the container in a very specific way to make it work). Something to consider in the future for sure. :)

@jimharris Yes, planning to dive into it as soon as possible.

**Comment by mikeBashStuff** [comment] 2020-11-25 12:48
@mgerdts @jimharris I have submitted https://review.spdk.io/gerrit/c/spdk/spdk/+/5259 targeting this issue. However, I am not sure if this is really needed. Please, see the comment in the patch. I've looked up `vfio-pci` module dependencies on couple of distros, including `centos8`, and on all of them, if not directly compiled into the kernel, `vfio_iommu_type1` is listed in `vfio-pci` dependencies. E.g:
```
# modprobe --show-depends vfio-pci
insmod /lib/modules/4.19.0-6-amd64/kernel/virt/lib/irqbypass.ko
insmod /lib/modules/4.19.0-6-amd64/kernel/drivers/vfio/vfio.ko
insmod /lib/modules/4.19.0-6-amd64/kernel/drivers/vfio/vfio.ko
insmod /lib/modules/4.19.0-6-amd64/kernel/drivers/vfio/vfio_iommu_type1.ko
insmod /lib/modules/4.19.0-6-amd64/kernel/drivers/vfio/vfio_virqfd.ko
insmod /lib/modules/4.19.0-6-amd64/kernel/drivers/vfio/pci/vfio-pci.ko
```
So it should be loaded together with `vfio-pci`. Unless I unload this particular module manually, I can't really reproduce the scenario where dpdk complains about missing iommu extensions.

**Comment by mgerdts** [comment] 2020-12-02 22:58
@tomzawadzki it does not look like the iommu problem is fixed.  I see the dependencies you mention, but they seem to not have the intended impact.

A freshly rebooted system:

```
[root@ms-10 fix]# modprobe --show-depends vfio-pci
insmod /lib/modules/4.18.0-193.28.1.el8_2.x86_64/kernel/virt/lib/irqbypass.ko.xz
insmod /lib/modules/4.18.0-193.28.1.el8_2.x86_64/kernel/drivers/vfio/vfio.ko.xz
insmod /lib/modules/4.18.0-193.28.1.el8_2.x86_64/kernel/drivers/vfio/vfio.ko.xz
insmod /lib/modules/4.18.0-193.28.1.el8_2.x86_64/kernel/drivers/vfio/vfio_iommu_type1.ko.xz
insmod /lib/modules/4.18.0-193.28.1.el8_2.x86_64/kernel/drivers/vfio/vfio_virqfd.ko.xz
insmod /lib/modules/4.18.0-193.28.1.el8_2.x86_64/kernel/drivers/vfio/pci/vfio-pci.ko.xz ids=

[root@ms-10 fix]# lsmod | grep vfio
vfio_pci               57344  0
irqbypass              16384  2 vfio_pci,kvm
vfio_virqfd            16384  1 vfio_pci
vfio                   36864  1 vfio_pci
```

Test the fix:

```
[root@ms-10 ~]# cd fix

[root@ms-10 fix]# curl -O 'https://review.spdk.io/gerrit/plugins/gitiles/spdk/spdk/+archive/e1aba437452f7d9d329171de3e6a596753cc8bfc.tar.gz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2537k    0 2537k    0     0  1609k      0 --:--:--  0:00:01 --:--:-- 1609k

[root@ms-10 fix]# tar xzf e1aba437452f7d9d329171de3e6a596753cc8bfc.tar.gz

[root@ms-10 fix]# PCI_BLACKLIST=0000:01:00.0 ./scripts/setup.sh
0000:01:00.0 (144d a804): Skipping denied controller at 0000:01:00.0
0000:01:00.0 (144d a804): Active mountpoints on nvme0n1:myvg--ms--10-root,nvme0n1:cl_myvg--ms--10-home, so not binding PCI dev
0000:80:04.2 (8086 2021): ioatdma -> vfio-pci
0000:80:04.3 (8086 2021): ioatdma -> vfio-pci
0000:80:04.0 (8086 2021): ioatdma -> vfio-pci
0000:80:04.1 (8086 2021): ioatdma -> vfio-pci
0000:80:04.6 (8086 2021): ioatdma -> vfio-pci
0000:80:04.7 (8086 2021): ioatdma -> vfio-pci
0000:80:04.4 (8086 2021): ioatdma -> vfio-pci
0000:80:04.5 (8086 2021): ioatdma -> vfio-pci
0000:00:04.2 (8086 2021): ioatdma -> vfio-pci
0000:00:04.3 (8086 2021): ioatdma -> vfio-pci
0000:00:04.0 (8086 2021): ioatdma -> vfio-pci
0000:00:04.1 (8086 2021): ioatdma -> vfio-pci
0000:00:04.6 (8086 2021): ioatdma -> vfio-pci
0000:00:04.7 (8086 2021): ioatdma -> vfio-pci
0000:00:04.4 (8086 2021): ioatdma -> vfio-pci
0000:87:00.0 (144d a804): nvme -> vfio-pci
0000:86:00.0 (144d a804): nvme -> vfio-pci
0000:00:04.5 (8086 2021): ioatdma -> vfio-pci

[root@ms-10 fix]# lsmod | grep vfio
vfio_pci               57344  0
irqbypass              16384  2 vfio_pci,kvm
vfio_virqfd            16384  1 vfio_pci
vfio                   36864  1 vfio_pci
```

That doesn't look good.  Let's try starting `spdk_tgt` just to be sure.

```
[root@ms-10 fix]# /opt/spdk/bin/spdk_tgt -m 0x8
[2020-12-02 22:50:43.854769] Starting SPDK v20.10 git sha1 e5d26ecc2 / DPDK 20.08.0 initialization...
[2020-12-02 22:50:43.854885] [ DPDK EAL parameters: [2020-12-02 22:50:43.854897] spdk_tgt [2020-12-02 22:50:43.854907] --no-shconf [2020-12-02 22:50:43.854915] -c 0x8 [2020-12-02 22:50:43.854925] --log-level=lib.eal:6 [2020-12-02 22:50:43.854941] --log-level=lib.cryptodev:5 [2020-12-02 22:50:43.854949] --log-level=user1:6 [2020-12-02 22:50:43.854958] --base-virtaddr=0x200000000000 [2020-12-02 22:50:43.854966] --match-allocations [2020-12-02 22:50:43.854975] --file-prefix=spdk_pid10082 [2020-12-02 22:50:43.854982] ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL:   no supported IOMMU extensions found!
EAL: VFIO support could not be initialized
...
^C
```

Relevant to the attempted fix:

```
[root@ms-10 fix]# modinfo vfio_iommu_type1
filename:       /lib/modules/4.18.0-193.28.1.el8_2.x86_64/kernel/drivers/vfio/vfio_iommu_type1.ko.xz
description:    Type1 IOMMU driver for VFIO
...

[root@ms-10 fix]# echo $?
0

[root@ms-10 fix]# cat /sys/module/vfio/parameters/enable_unsafe_noiommu_mode
N
```

**Comment by mikeBashStuff** [comment] 2020-12-03 10:28
@mgerdts The fix for the `iommu` issue hasn't been merged yet and `e1aba437452f7d9d329171de3e6a596753cc8bfc` tree doesn't include it. The attempted fix is currently being reviewed here: https://review.spdk.io/gerrit/c/spdk/spdk/+/5259. 

As to your results seen in the comment, I am a bit confused. :) By default, I wouldn't expect `vfio_pci` module to be loaded into the kernel, unless there's some distro-specific path that loads it explicitly (like `/etc/init.d/kmod` or `systemd-modules-load` which lookup different `module-load.d` dirs at init). With said conf in place however, all dependencies should be loaded as well. E.g.:

```
[root@centos8-cloud-30617 ~]# printf '%s\n' /sys/module/vfio*

[root@centos8-cloud-30617 ~]# lsmod | grep vfio
[root@centos8-cloud-30617 ~]# echo vfio_pci >/etc/modules-load.d/vfio.conf
[root@centos8-cloud-30617 ~]# reboot
Connection to 192.168.121.118 closed by remote host.
Connection to 192.168.121.118 closed.
root@debianMB[SPDK]:~/spdk_repo/spdk# ssh  vagrant@192.168.121.118
The authenticity of host '192.168.121.118 (192.168.121.118)' can't be established.
ED25519 key fingerprint is SHA256:jgSJW8MwQWvdbzj41Bgxx/UW57EvG/KoMNCN+ZTH/ig.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.121.118' (ED25519) to the list of known hosts.
Last login: Thu Dec  3 10:14:07 2020 from 192.168.121.1
[root@centos8-cloud-30617 ~]# printf '%s\n' /sys/module/vfio*
/sys/module/vfio
/sys/module/vfio_iommu_type1
/sys/module/vfio_pci
/sys/module/vfio_virqfd
[root@centos8-cloud-30617 ~]# lsmod | grep vfio
vfio_pci               57344  0
vfio_virqfd            16384  1 vfio_pci
vfio_iommu_type1       32768  0
vfio                   36864  2 vfio_iommu_type1,vfio_pci
irqbypass              16384  1 vfio_pci
[root@centos8-cloud-30617 ~]#
```
Also when done manually:
```
[root@centos8-cloud-30617 ~]# printf '%s\n' /sys/module/vfio*
/sys/module/vfio
/sys/module/vfio_iommu_type1
/sys/module/vfio_pci
/sys/module/vfio_virqfd
root@centos8-cloud-30617 ~]# h=(/sys/module/vfio/holders/*)
root@centos8-cloud-30617 ~]# v=(/sys/module/vfio*)
[root@centos8-cloud-30617 ~]# modprobe -r "${h[@]##*/}" "${v[@]##*/}"
[root@centos8-cloud-30617 ~]# printf '%s\n' /sys/module/vfio*

[root@centos8-cloud-30617 ~]# modprobe vfio_pci
[root@centos8-cloud-30617 ~]# printf '%s\n' /sys/module/vfio*
/sys/module/vfio
/sys/module/vfio_iommu_type1
/sys/module/vfio_pci
/sys/module/vfio_virqfd
[root@centos8-cloud-30617 ~]#
```
With all that said, https://review.spdk.io/gerrit/c/spdk/spdk/+/5259 should load the `iommu` driver prior loading the `vfio_pci` driver so even the case seen on your system should be covered.

**Comment by mgerdts** [comment] 2020-12-03 11:07
@mikeBashStuff thanks for pointing out the error in my testing.  I managed to grab the wrong URL from gerrit and verified things are broken without the fix.  With cluestick in hand:

```
[root@ms-10 ~]# rm -rf realfix
[root@ms-10 ~]# mkdir realfix
[root@ms-10 ~]# cd realfix
[root@ms-10 realfix]# curl https://review.spdk.io/gerrit/changes/spdk%2Fspdk~5259/revisions/2/archive?format=tgz | tar xzf -
...

[root@ms-10 realfix]# PCI_BLACKLIST=0000:01:00.0 ./scripts/setup.sh reset
...

[root@ms-10 realfix]# lsmod | grep vfio
vfio_pci               57344  0
irqbypass              16384  2 vfio_pci,kvm
vfio_virqfd            16384  1 vfio_pci
vfio                   36864  1 vfio_pci

[root@ms-10 realfix]# PCI_BLACKLIST=0000:01:00.0 ./scripts/setup.sh
...

[root@ms-10 realfix]# lsmod | grep vfio
vfio_iommu_type1       32768  0
vfio_pci               57344  0
irqbypass              16384  2 vfio_pci,kvm
vfio_virqfd            16384  1 vfio_pci
vfio                   36864  2 vfio_iommu_type1,vfio_pci

[root@ms-10 realfix]# /opt/spdk/bin/spdk_tgt
[2020-12-03 11:01:01.301852] Starting SPDK v20.10 git sha1 e5d26ecc2 / DPDK 20.08.0 initialization...
[2020-12-03 11:01:01.302072] [ DPDK EAL parameters: [2020-12-03 11:01:01.302083] spdk_tgt [2020-12-03 11:01:01.302091] --no-shconf [2020-12-03 11:01:01.302098] -c 0x1 [2020-12-03 11:01:01.302106] --log-level=lib.eal:6 [2020-12-03 11:01:01.302116] --log-level=lib.cryptodev:5 [2020-12-03 11:01:01.302126] --log-level=user1:6 [2020-12-03 11:01:01.302137] --base-virtaddr=0x200000000000 [2020-12-03 11:01:01.302145] --match-allocations [2020-12-03 11:01:01.302152] --file-prefix=spdk_pid17517 [2020-12-03 11:01:01.302159] ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No legacy callbacks, legacy socket not created
[2020-12-03 11:01:01.361342] app.c: 462:spdk_app_start: *NOTICE*: Total cores available: 1
...
```

Yay, no more `VFIO support could not be initialized` errors.

**Comment by mikeBashStuff** [comment] 2020-12-07 08:57
Patch has been merged, closing this issue.

**Closed by mikeBashStuff** 2020-12-07 08:57 UTC
Labels: Sighting, Waiting on Submitter
