### ISSUE TITLE
Cannot run target application with 8192MB memory or more

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#922] opened 2019-08-21 10:58 UTC
## Current Behavior
nvmf_tgt, vhost and spdk_tgt cannot run with "-s" argument equal or more than 8192.
Works only if "-g" argument is additionally passed.

## Steps to Reproduce
1. HUGEMEM=300000 scripts/setup.sh
2. cat /proc/meminfo | grep Huge
```
HugePages_Total:   150000
HugePages_Free:    149991
HugePages_Rsvd:        0
HugePages_Surp:        0
```
3. Check no other target apps are running:
```
[sys_sgci@gklab-17-178 spdk]$ ps aux | grep spdk
sys_sgci 2469832  0.0  0.0 215744   888 pts/1    S+   12:56   0:00 grep --color=auto spdk
```
4. app/nvmf_tgt/nvmf_tgt -s 8192
```
[sys_sgci@gklab-17-178 spdk]$ sudo app/nvmf_tgt/nvmf_tgt -s 8192
Starting SPDK v19.07 / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: nvmf --no-shconf -c 0x1 -m 8192 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid24
69834 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: FATAL: Cannot init memory
EAL: Cannot init memory
Failed to initialize DPDK
```

## Context (Environment including OS version, SPDK version, etc.)
SPDK: 40c959cbcc96863c362305fa7ef187144ebde821 and/or dfe1678b7b1a63de8c452421473fecedcee410fe

OS: F29 5.1.20-200.fc29

**Comment by jimharris** [comment] 2019-08-21 16:27
Is this reproducible on multiple systems?  I tried this on my system (w/ 2MB huge pages) on both master and v19.07 and didn't see this problem.

**Comment by karlatec** [comment] 2019-08-21 18:30
Yes. I've done this on two separate physical systems.
Both F29, one with kernel 5.1.20 and the other on 5.2.6. 2MB huge pages as well. I'll ask someone from ITP tomorrow to try and reproduce it to be sure

**Comment by changpe1** [comment] 2019-08-22 01:17
I met same issue on my system too when using test/blobfs/mkfs/mkfs, but can't reproduce it again after one rebooting. The error message is same:

EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: FATAL: Cannot init memory
EAL: Cannot init memory

**Comment by jimharris** [comment] 2019-08-22 04:12
Can you try playing with some of the CONFIG_RTE_MAX_MEMSEG constants in dpdk/config/common_base?  Especially CONFIG_RTE_MAX_MEMSEG_PER_LIST and CONFIG_RTE_MAX_MEMSEG_PER_TYPE.

**Comment by darsto** [comment] 2019-08-27 14:52
DPDK can show more detailed logs about what's happening inside its memory allocator. Those logs have to be enabled programatically in the SPDK application, but are enabled by default e.g. in our `vtophys` test app.

I'll work with Karol to modify vtophys app to allocate 8GB of hugepages and we'll post an update here.

**Comment by tomzawadzki** [comment] 2019-10-08 15:29
[Bug scrub] @darsto Has there been any patches submitted/merged related to this issue ?

**Comment by clicx** [comment] 2019-10-15 08:41
I meet the same issue, nr_hugepages=40000, dpdk params: -c 0x3ff -m 20480
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: FATAL: Cannot init memory
EAL: Cannot init memory
Failed to initialize DPDK
Unable to initialize SPDK env

**Comment by optimistyzy** [comment] 2019-11-29 10:43
@jimharris @tomzawadzki Any update on this issue? Some users reported that even after reboot, they face the same issue.

**Comment by karlatec** [comment] 2019-11-29 11:53
If I recall correctly: you can try to get around the issue by loading vfio module with some huge dma entry limit, e.g.:
sudo modprobe  vfio_iommu_type1  dma_entry_limit=1000000

**Comment by optimistyzy** [comment] 2019-11-29 13:15
> If I recall correctly: you can try to get around the issue by loading vfio module with some huge dma entry limit, e.g.:
> sudo modprobe vfio_iommu_type1 dma_entry_limit=1000000

Hi @karlatec  Thanks. But how about for uio?

**Comment by darsto** [comment] 2020-01-30 12:14
Closing due to inactivity.

> If I recall correctly: you can try to get around the issue by loading vfio module with some huge dma entry limit, e.g.:
> sudo modprobe vfio_iommu_type1 dma_entry_limit=1000000

This was a workaround for another issue which is now fixed.

**Closed by darsto** 2020-01-30 12:14 UTC
Labels: help wanted

**Comment by mhae** [comment] 2020-09-16 22:58
Running into the same issue with 20.07 on debian.

**Comment by jiguanglizipao** [comment] 2021-10-09 01:10
I met the same issue with SPDK v21.04.
