### ISSUE TITLE
[SPDK CI]CI log is not generated https://ci.spdk.io/results/autotest-per-patch/builds/62872/archive/nvmf-tcp-vg-autotest/build.log

### ISSUE THREAD

**Issue by wanqunintel** [spdk/spdk#2264] opened 2021-12-02 01:40 UTC
# Bug report
CI log is not generated https://ci.spdk.io/results/autotest-per-patch/builds/62872/archive/nvmf-tcp-vg-autotest/build.log
build.log content is as follows.
https://10.211.11.56:8080/job/nvmf-tcp-vg-autotest/71/timestamps/?elapsed=HH:mm:ss.S&appendLog
IllegalArgumentException: durationMillis must not be negative

## Expected Behavior
Should have log generated with following path

**Comment by mikeBashStuff** [comment] 2021-12-02 08:03
This is caused by the system clock being out of sync with the ntp on some of the VM hosts.

**Comment by mikeBashStuff** [comment] 2021-12-02 08:35
Issue should be fixed, configuration on the VM hosts was updated. Let's leave this issue open for couple of days to make sure nothing else is affected.

**Comment by wanqunintel** [comment] 2021-12-03 01:46
Agreed with that.

**Comment by tomzawadzki** [comment] 2021-12-14 13:35
No further reports were posted after VM configuration was fixed. Closing.

**Closed by tomzawadzki** 2021-12-14 13:35 UTC
Labels: Sighting
