### ISSUE TITLE
[nvmf-vg-autotest] Connect Disconnect test failure

### ISSUE THREAD

**Issue by krish-reddy** [spdk/spdk#2117] opened 2021-08-20 12:26 UTC
# CI Intermittent Failure

00:05:52.157  ************************************
00:05:52.157  START TEST nvmf_connect_disconnect
00:05:52.157  ************************************

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/56526/archive/nvmf-vg-autotest/

## Execution failed at

00:06:14.213  ========== Backtrace start: ==========
00:06:14.213  
00:06:14.220  in test/nvmf/target/connect_disconnect.sh:35 -> main(["--transport=rdma"])
00:06:14.220       ...
00:06:14.220     30  	fi
00:06:14.220     31  	
00:06:14.220     32  	set +x
00:06:14.220     33  	for i in $(seq 1 $num_iterations); do
00:06:14.220     34  		nvme connect -t $TEST_TRANSPORT -n "nqn.2016-06.io.spdk:cnode1" -a "$NVMF_FIRST_TARGET_IP" -s "$NVMF_PORT" $IO_QUEUES
00:06:14.220  => 35  		waitforserial "$NVMF_SERIAL"
00:06:14.220     36  		nvme disconnect -n "nqn.2016-06.io.spdk:cnode1"
00:06:14.220     37  		waitforserial_disconnect "$NVMF_SERIAL"
00:06:14.220     38  	done
00:06:14.220     39  	set -x
00:06:14.221     40  	
00:06:14.221       ...
00:06:14.221  
00:06:14.221  ========== Backtrace end ==========

**Comment by spdkci** [comment] 2021-08-20 12:28
Another instance of this failure. Reported by @krish-reddy. log: https://ci.spdk.io/public_build/autotest-per-patch_56526.html

**Comment by ksztyber** [comment] 2021-08-20 12:42
Duplicate of #2060.

**Closed by ksztyber** 2021-08-20 12:42 UTC
Labels: Intermittent Failure
