### ISSUE TITLE
[ocf_fio_modes]  Error -1000012 during start cache PT_Nvme

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1354] opened 2020-04-18 22:53 UTC
WB_Nvme0: Successfully added
WB_Nvme0: Cache mode : wb
Inserting cache WB_Nvme1
WB_Nvme1: Successfully added
WB_Nvme1: Cache mode : wb
PT_Nvme: Not enough free RAM for cache metadata to start cache
PT_Nvme: Available RAM: 116473856 B
PT_Nvme: Needed RAM: 117334272 B
WT_Nvme: Not enough free RAM for cache metadata to start cache
WT_Nvme: Available RAM: 116473856 B
WT_Nvme: Needed RAM: 117334272 B
WB_Nvme0: Not enough free RAM for cache metadata to start cache
WB_Nvme0: Available RAM: 116473856 B
WB_Nvme0: Needed RAM: 117334272 B
WB_Nvme1: Not enough free RAM for cache metadata to start cache
WB_Nvme1: Available RAM: 116473856 B
WB_Nvme1: Needed RAM: 117334272 B
PT_Nvme: Attaching cache device failed
vbdev_ocf.c:1005:start_cache_cmpl: *ERROR*: Error -1000012 during start cache PT_Nvme, starting rollback
PT_Nvme: Cannot flush cache - cache device is detached
PT_Nvme: Cache PT_Nvme successfully stopped
vbdev_ocf.c: 220:remove_core_cache_lock_cmpl: *ERROR*: Error -1000014, can not lock cache instance PT_Nvme
WT_Nvme: Attaching cache device failed
vbdev_ocf.c:1005:start_cache_cmpl: *ERROR*: Error -1000012 during start cache WT_Nvme, starting rollback
WT_Nvme: Cannot flush cache - cache device is detached
WT_Nvme: Cache WT_Nvme successfully stopped
vbdev_ocf.c: 220:remove_core_cache_lock_cmpl: *ERROR*: Error -1000014, can not lock cache instance WT_Nvme

**Comment by spdkci** [comment] 2020-04-18 22:54
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_11047.html

**Comment by Donaim** [comment] 2020-04-22 10:44
Looking at
```
PT_Nvme: Not enough free RAM for cache metadata to start cache
PT_Nvme: Available RAM: 116473856 B
PT_Nvme: Needed RAM: 117334272 B
```
the issue is that OCF needed more RAM than we provide

I will submit a patch that will increase the number of hugepages that we allocate for CI tests

**Comment by Donaim** [comment] 2020-04-23 08:00
I did tests to see how much memory OCF consumes and it looks like 8GB that we allocated on CI should be enough.
Then I noticed that when OCF asks our env for "free memory" we report non-hugepage memory, while most allocation are done on hygepage memory.
So this is a bug that is most likely responsible for the reported error.
I will fix our OCF env function

**Comment by Donaim** [comment] 2020-04-23 09:23
There does'nt seem to be an API to get available HUGEPAGE memory in SPDK.
And if we return (-1)(uint64_t) like in OCF posix env example, then it will hang on initialization.
I will be looking into this more

**Comment by Donaim** [comment] 2020-04-23 12:32
Submitted a fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/1976

**Comment by Donaim** [comment] 2020-04-29 06:46
Fix is merged, this issue should not occur anymore. Closing

**Closed by Donaim** 2020-04-29 06:46 UTC
Labels: Intermittent Failure
