### ISSUE TITLE
[nvmf_nmic] No devices were found for the test

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#2061] opened 2021-08-02 09:03 UTC
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/54669/archive/nvmf-tcp-vg-autotest/build.log

## Execution failed at

```
00:05:33.458   14:11:00	-- nvmf/target/nmic.sh@45 -- # /home/vagrant/spdk_repo/spdk/scripts/fio-wrapper -p nvmf -i 4096 -d 1 -t write -r 1 -v
00:05:33.472  * No devices were found for the test, aborting
00:05:33.472    14:11:00	-- nvmf/target/nmic.sh@45 -- # trap - ERR
00:05:33.472    14:11:00	-- nvmf/target/nmic.sh@45 -- # print_backtrace
00:05:33.472    14:11:00	-- common/autotest_common.sh@987 -- # [[ ehxBET =~ e ]]
00:05:33.473    14:11:00	-- common/autotest_common.sh@989 -- # args=("${BASH_ARGV[@]}")
00:05:33.473    14:11:00	-- common/autotest_common.sh@989 -- # local args
00:05:33.473    14:11:00	-- common/autotest_common.sh@991 -- # xtrace_disable
00:05:33.473    14:11:00	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:05:33.473    14:11:00	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:05:33.473    14:11:00	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:05:33.473    14:11:00	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:05:33.473    14:11:00	-- common/autotest_common.sh@19 -- # set +x
00:05:33.473  ========== Backtrace start: ==========
00:05:33.473  
00:05:33.480  in test/nvmf/target/nmic.sh:45 -> main(["--transport=tcp"])
00:05:33.480       ...
00:05:33.480     40  	nvme connect -t $TEST_TRANSPORT -n "nqn.2016-06.io.spdk:cnode1" -a "$NVMF_FIRST_TARGET_IP" -s "$NVMF_PORT"
00:05:33.480     41  	nvme connect -t $TEST_TRANSPORT -n "nqn.2016-06.io.spdk:cnode1" -a "$NVMF_FIRST_TARGET_IP" -s "$NVMF_SECOND_PORT"
00:05:33.480     42  	
00:05:33.480     43  	waitforserial "$NVMF_SERIAL"
00:05:33.480     44  	
00:05:33.480  => 45  	$rootdir/scripts/fio-wrapper -p nvmf -i 4096 -d 1 -t write -r 1 -v
00:05:33.480     46  	
00:05:33.480     47  	nvme disconnect -n "nqn.2016-06.io.spdk:cnode1"
00:05:33.480     48  	
00:05:33.480     49  	trap - SIGINT SIGTERM EXIT
00:05:33.480     50  	
00:05:33.480       ...
00:05:33.480  
00:05:33.480  ========== Backtrace end ==========
```

**Comment by mikeBashStuff** [comment] 2021-08-02 09:03
Duplicate of #2060 @tomzawadzki will close this one and assign myself to #2060

**Closed by mikeBashStuff** 2021-08-02 09:03 UTC
Labels: Intermittent Failure
