### ISSUE TITLE
Spdk_tgt_trace file not deleted from /dev/shm 

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#302] opened 2018-05-18 12:39 UTC
## Expected Behavior
FIle spdk_tgt_trace.pid* deleted after spdk_tgt kill

## Current Behavior
File spdk_tgt_trace.pid* exist after spdk_tgt kill

## Possible Solution
None

## Steps to Reproduce
1. Run spdk_tgt:
app/spdk_tgt/spdk_tgt -m 0x1 -p 0 -c spdk_tgt.conf -s 1024 -r /var/tmp/spdk.sock
with config:
[Global]

[Ioat]
  Disable Yes
2. Wait until spdk_tgt starts
3. Kill spdk_tgt

## Context (Environment including OS version, SPDK version, etc.)
Virtual machine with ubuntu 16.4 and two emulated nvme devices (1G, 2G).

**Comment by wanqunintel** [comment] 2018-05-22 05:48
@yidong0635 can you double confirm if the spdk_tgt_trace.pid* can be deleted after waiting for a while or persisted not deleted?

**Comment by yidong0635** [comment] 2018-05-22 07:06
the files in spdk_tgt_trace.pid* located in `/dev/shm` , confirm it will never be deleted after killing  spdk_tgt .

**Comment by wanqunintel** [comment] 2018-05-23 00:56
verified with nvmf_tgt, it shows the same issue, but iscsi_tgt can delete the iscsi_trace.pid12663  spdk_iscsi_conns.-1 files

**Comment by yidong0635** [comment] 2018-05-23 01:01
![image](https://user-images.githubusercontent.com/39082016/40397900-c3dd77aa-5e67-11e8-896f-321b12fdc5a5.png)

**Comment by jimharris** [comment] 2018-05-23 16:45
Hi,

How do you propose this should be fixed?

Using SIGKILL means the application has no opportunity to delete it itself.  And having the application try to figure out which ones it can or should delete the next time it starts is problematic.

I’m open to suggestions here, but my feeling is this just expected behavior.

-Jim

**Comment by pawelwod** [comment] 2018-05-29 13:58
This is also an issue if SPDK crashes. There should be some way of recycling this memory. Maybe omitting PID or/and using file locking would be better to detect if SPDK can remove those artifacts.

**Comment by jimharris** [comment] 2018-05-29 17:37
Omitting PID and using file locking means we can’t have two of the same application running at once.  We’ve done a lot of work in other areas to ensure this works.

What if we had a separate “cleanup.sh” script in the scripts directory that could be used to clean up stuff like this?  I really don’t want to try to build logic into the apps itself to figure out which existing shm files can be deleted.  Normal operation is that the app doesn’t crash (including kill -9) – so I think I’d prefer to move cleanup from these kinds of cases to an external script that can be called explicitly by the user.

**Comment by wanqunintel** [comment] 2018-05-31 04:41
@yidong0635 would you double confirm about the kill action, is it ctrl+c or kill -9 or others? make sure it's doing the same for nvmf_tgt and iscsi_tgt

**Comment by pawelwod** [comment] 2018-06-07 20:44
@jimharris yes we can have “cleanup.sh” but do we want it? I think the SPDK target app  code (not library!) should be abble to recycle those artifacts, somehow. Ofcourse if user specyfy its own share memory ID it should clean it up by him self but defults values should be recycled automitacaly when app starts.

**Comment by jimharris** [comment] 2018-06-07 21:18
I’m open to ideas.  I’d like to clarify here through what exactly should get cleaned up.

First – I think for application FOO, it should only try to clean up trace files associated with FOO (i.e. FOO_trace.*).  I think it’s OK to even cleanup trace files for FOO with a shared memory ID.

Probably you’ll need to do an fcntl(F_SETLK) on the trace file when it’s created – similar to what we do in spdk_pci_device_claim().  Then you have to scan /dev/shm, find matching entries, try to open and F_SETLK, and if all of that succeeds, unlink the file.  If F_SETLK fails, then you know its associated application is still running.

Oh – and I think FreeBSD may use a different directory than /dev/shm, but I don’t recall offhand.

I’m still not convinced cleaning all of this up automatically, with no user intervention, is the right way to go.  It should at least print error messages for any orphaned trace files that it deletes.

**Comment by yidong0635** [comment] 2018-07-04 05:28
@jimharris  Can you help to review it , if need this patch?

**Comment by jimharris** [comment] 2018-07-10 20:34
This will automatically delete all files, even if the associated application is still running.  Maybe this is OK, but it seems a bit dangerous.

What do you think about my proposal from June 7th?  Then in most cases, these files would be cleaned up automatically.

**Comment by pawelwod** [comment] 2018-07-11 09:47
Maybe some simpler solution (don't know if we want this in library code or in shell script)

1. for each file /dev/shm/*trace.pid* and /dev/shm/spdk_*_conns.* files.
2. Discover PID from filename
3. File is used only if it is open -> check if there is a link to this file in /proc/PID/fd/*, if not remove this file.

Implementing this in shell script is super easy. In library a just a little bit harder.

**Comment by jimharris** [comment] 2018-07-11 13:18
This wouldn’t clean up files from apps using shared memory ID but I am OK with that. There should almost never be more than one shared memory ID being used on a system.  Let’s go with Pawels idea.

Sent from my iPhone

On Jul 11, 2018, at 2:47 AM, pawelwod <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe some simpler solution (don't know if we want this in library code or in shell script)

  1.  for each file /dev/shm/trace.pid and /dev/shm/spdk__conns. files.
  2.  Discover PID from filename
  3.  File is used only if it is open -> check if there is a link to this file in /proc/PID/fd/*, if not remove this file.

Implementing this in shell script is super easy. In library a just a little bit harder.

**Comment by pawelwod** [comment] 2018-07-11 13:31
Do we wan't this in cleanup script or in library startup code?

**Comment by jimharris** [comment] 2018-07-11 13:40
I think just a script. And it should print an error if run on FreeBSD since it doesn’t have proc entries like Linux.

To put it in the library, I think we would need to do the F_SETLK approach so that it works on both Linux and FreeBSD.

Sent from my iPhone

On Jul 11, 2018, at 6:32 AM, pawelwod <notifications@github.com<mailto:notifications@github.com>> wrote:


Do we wan't this in cleanup script or in library startup code?

**Comment by yidong0635** [comment] 2018-07-16 04:17
@jimharris and @pawelwod ：
update the patch,
1.for each file /dev/shm/trace.pid , I checked that only iscsi target can generate conns file named ：/dev/shm/spdk_iscsi_conns.-1  it's name can't change, so i will only remove /dev/shm/*trace.pid* file , it's size is more lager.
2.extract PID from file name.
3.  kill -0 PID to check if it's still running.

not test FreeBSD , to skip this.
./scripts/cleanup.sh
https://review.gerrithub.io/c/spdk/spdk/+/416326

**Closed** 2018-07-19 17:21 UTC
Labels: bug
