### ISSUE TITLE
System reports DMAR error when using Optane P5800X

### ISSUE THREAD

**Issue by YamboZhou** [spdk/spdk#2514] opened 2022-05-16 09:03 UTC
Hi all,

When we start SPDK vhost with Optane P5800X, kernel reports the following error in "/var/log/message":

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
kernel: dmar_fault: 812287 callbacks suppressed

kernel: DMAR: DRHD: handling fault status reg 2

kernel: DMAR: [DMA Write] Request device [99:00.0] fault addr 0 [fault reason 05] PTE Write access is not set

kernel: DMAR: DRHD: handling fault status reg 2

kernel: DMAR: [DMA Write] Request device [99:00.0] fault addr 0 [fault reason 05] PTE Write access is not set

kernel: DMAR: DRHD: handling fault status reg 2

kernel: DMAR: [DMA Write] Request device [99:00.0] fault addr 0 [fault reason 05] PTE Write access is not set

kernel: DMAR: DRHD: handling fault status reg 2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

We use kernel version 4.19.91. In our environment, we have multiple Optane SSDs and TLC/QLC NVMe SSDs, but only Optane SSDs report this error. (as the log shown above, slot '[99:00.0]' is a Optane SSD). 

SPDK version: 20.10

**Comment by jimharris** [comment] 2022-05-16 17:16
Hi @YamboZhou, do these faults occur when you attach the NVMe controller?  Or do they only happen after a VM connect to the Vhost app?

Also - do you see this with v22.01 or latest master?

**Comment by YamboZhou** [comment] 2022-05-17 04:12
Hi @jimharris, I find when we enable VSS capability of Optane P5800X, these faults will occur.  We use 4KB + 64Byte VSS now.  And they only happened when NVMe devices were attached in driver probe process.

There is no any influence for vhost I/O after that faults, but we try to figure out the root cause for this unexpected behavior to avoid potential issues.

**Comment by YamboZhou** [comment] 2022-05-17 04:15
Add more comments:

When we used normal format, like 4KB without extended meta area, we didn't see these faults.

**Comment by YamboZhou** [comment] 2022-05-17 10:20
@jimharris Hi Jim. Is this a firmware issue? When we enable VSS with 64Byte meta, SPDK NVMe driver reads/writes blocks without indicating metadata buffer in probe process and then Optane DMAs an invalid metadata buffer leading to this fault?

**Comment by jimharris** [comment] 2022-05-17 19:23
> @jimharris Hi Jim. Is this a firmware issue? When we enable VSS with 64Byte meta, SPDK NVMe driver reads/writes blocks without indicating metadata buffer in probe process and then Optane DMAs an invalid metadata buffer leading to this fault?

It is possible it is a FW issue.  Let me make sure I understand the issue correctly:

1) You see these faults occur during device attach.  So they happen before VM/vhost tries to connect.
2) After the faults, VM/vhost can still connect and there is no observed issues with I/O.

If these are true, can you try running simpler test like perf tool, to see if issue reproduces there?

Additional step would be to understand exactly which command is triggering the DMAR fault.  For example, does it happen during the actual spdk_nvme_probe() process, or does it happen after the namespaces are registered, and the DMAR faults happen when upper layers (GPT, lvol, etc.) do initial reads on the namespace to check for partition tables or metadata.

**Comment by changpe1** [comment] 2022-05-18 00:35
@YamboZhou I didn't see similar issue in my platform with P5800X, FW version: L0310100, and I also enabled the extended LBA format, it's good for us to know this issue will happen with SPDK tools(perf, fio_plugin).  

For IOVA=PA or IOVA=VA, which one do you use? I see `fault addr 0`, obviously it's invalid address.

**Comment by YamboZhou** [comment] 2022-05-18 03:16
@changpe1 We use FW L0310101 and the following disk format:

~~~~~~~~~~~~~~~~~~~~~~~~~~
nvme format -l 4  -m 0  -r /dev/nvme0n1
~~~~~~~~~~~~~~~~~~~~~~~~~~

We can reproduce this issue just by *hello_world* example.  I remember FW L0310100 does not support extended LBA? Hence,  we upgrade FW to L0310101 from Intel provided FW patch.

**Comment by changpe1** [comment] 2022-05-18 03:26
> @changpe1 We use FW L0310101 and the following disk format:
> 
> ```
> nvme format -l 4  -m 0  -r /dev/nvme0n1
> ```
> 
> We can reproduce this issue just by _hello_world_ example. I remember FW L0310100 does not support extended LBA? Hence, we upgrade FW to L0310101 from Intel provided FW patch.

ah~, I don't think you can use hello_world for the VSS tests, it only allocates fixed 4KiB  as R/W buffer, SPDK perf tool can work with VSS feature.

**Comment by YamboZhou** [comment] 2022-05-18 06:08
> > @changpe1 We use FW L0310101 and the following disk format:
> > ```
> > nvme format -l 4  -m 0  -r /dev/nvme0n1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We can reproduce this issue just by _hello_world_ example. I remember FW L0310100 does not support extended LBA? Hence, we upgrade FW to L0310101 from Intel provided FW patch.
> 
> ah~, I don't think you can use hello_world for the VSS tests, it only allocates fixed 4KiB as R/W buffer, SPDK perf tool can work with VSS feature.

Thanks @YamboZ

**Comment by YamboZhou** [comment] 2022-05-18 09:20
hi

**Comment by YamboZhou** [comment] 2022-05-18 09:42
Hi @jimharris @changpe1 ,

Thanks a lot for your help. I find this issue is in bdev layer as follows. 

When we register NVMe bdev, it will read blob when it starts. Since these I/Os (bdev_block_read) do not indicate metadata buffer, they lead to DMA faults if we enable VSS in Optane. I'm not sure whether host software must give a metadata buffer if VSS is enabled and we don't use this capability in start process.      

I/O submission: 
~~~~~~~~~~~~~~~~~~~~~~~~~
#0  bdev_blob_read (dev=0x4b5be90, channel=0x4b5b980, payload=0x2000085fe000, lba=0, lba_count=1, cb_args=0x4b5d3f0) at blob_bdev.c:132
#1  0x000000000045e3db in spdk_bs_load (dev=dev@entry=0x4b5be90, o=o@entry=0x7ffffff248a0, cb_fn=cb_fn@entry=0x456cc0 <lvs_load_cb>, cb_arg=cb_arg@entry=0x4b5bfe0) at blobstore.c:4459
#2  0x000000000045723e in spdk_lvs_load (bs_dev=0x4b5be90, cb_fn=cb_fn@entry=0x445460 <_vbdev_lvs_examine_cb>, cb_arg=cb_arg@entry=0x4b5be50) at lvol.c:420
#3  0x0000000000445238 in vbdev_lvs_examine (bdev=0x4b5b3c0) at vbdev_lvol.c:1336
#4  0x00000000004f595e in bdev_examine (bdev=0x4b5b3c0) at bdev.c:624
#5  0x00000000004f9d5b in bdev_start (bdev=0x4b5b3c0) at bdev.c:5663
#6  spdk_bdev_register (bdev=bdev@entry=0x4b5b3c0) at bdev.c:5674
#7  0x000000000043d53b in nvme_disk_create (ctx=0x4b5b3c0, prchk_flags=<optimized out>, ns=0x200009309f00, ctrlr=0x2000095ab3c0, base_name=<optimized out>, disk=0x4b5b3c0)
    at bdev_nvme.c:1362
#8  nvme_bdev_create (nvme_ns=0x4a58dc0, nvme_bdev_ctrlr=<optimized out>) at bdev_nvme.c:1387
#9  nvme_ctrlr_populate_standard_namespace (nvme_bdev_ctrlr=<optimized out>, nvme_ns=0x4a58dc0, ctx=0x0) at bdev_nvme.c:1418
#10 0x000000000043b2d4 in nvme_ctrlr_populate_namespace (ctx=0x0, nvme_ns=0x4a58dc0, ctrlr=0x4a586a0) at bdev_nvme.c:1524
#11 nvme_ctrlr_populate_namespaces (nvme_bdev_ctrlr=0x4a586a0, ctx=0x0) at bdev_nvme.c:1617
#12 0x000000000043cfb0 in attach_cb (cb_ctx=<optimized out>, trid=0x2000095ab3e8, ctrlr=0x2000095ab3c0, opts=<optimized out>) at bdev_nvme.c:1976
#13 0x000000000043d712 in spool_nvme_bdev_attach_cb (name=name@entry=0x7fffffffd2e0 "vol_n_b4:00.0", cb_ctx=cb_ctx@entry=0x0, trid=trid@entry=0x2000095ab3e8,
    ctrlr=ctrlr@entry=0x2000095ab3c0, opts=opts@entry=0x2000095ac9d8) at bdev_nvme.c:1992
#14 0x000000000041274f in attach_cb (cb_ctx=0x0, trid=0x2000095ab3e8, ctrlr=0x2000095ab3c0, opts=0x2000095ac9d8) at nvme_adp.c:162
#15 0x000000000047ef8f in nvme_ctrlr_poll_internal (probe_ctx=0x4863a90, ctrlr=0x2000095ab3c0) at nvme.c:745
#16 spdk_nvme_probe_poll_async (probe_ctx=0x4863a90) at nvme.c:1518
#17 0x000000000047f0e8 in nvme_init_controllers (probe_ctx=<optimized out>) at nvme.c:755
#18 spdk_nvme_probe (trid=<optimized out>, trid@entry=0x0, cb_ctx=0x0, probe_cb=probe_cb@entry=0x4128c0 <probe_cb>, attach_cb=attach_cb@entry=0x412590 <attach_cb>,
    remove_cb=remove_cb@entry=0x0) at nvme.c:903
#19 0x00000000004130e2 in nvme_probe (cb_ctx=<optimized out>, cb=<optimized out>) at nvme_adp.c:198
#20 0x00000000004133ed in spool_nvme_init (cb=cb@entry=0x40cc70 <spool_nvme_probe_cb>) at nvme_adp.c:838
#21 0x000000000040e740 in spool_init (opts=...) at spool.c:939
#22 0x000000000040c4c0 in spool_started (arg1=<optimized out>) at spool_main.c:539
#23 0x00000000004f62b0 in bdev_module_action_complete () at bdev.c:1292
#24 spdk_bdev_initialize (cb_fn=<optimized out>, cb_arg=<optimized out>) at bdev.c:1459
#25 0x000000000050a833 in spdk_subsystem_init (cb_fn=<optimized out>, cb_arg=<optimized out>) at subsystem.c:212
#26 0x000000000050d7ef in msg_queue_run_batch (max_msgs=<optimized out>, thread=0x4850ba0) at thread.c:544
#27 thread_poll (thread=thread@entry=0x4850ba0, max_msgs=max_msgs@entry=0, now=now@entry=42058185836343445) at thread.c:623
#28 0x000000000050e42c in spdk_thread_poll (thread=thread@entry=0x4850ba0, max_msgs=max_msgs@entry=0, now=42058185836343445) at thread.c:733
#29 0x0000000000509cf8 in _reactor_run (reactor=0x483e540) at reactor.c:906
#30 reactor_run (arg=0x483e540) at reactor.c:948
#31 0x000000000050a057 in spdk_reactors_start () at reactor.c:1056
#32 0x0000000000507200 in spdk_app_start (opts_user=opts_user@entry=0x7fffffffdf50, start_fn=start_fn@entry=0x40c4a0 <spool_started>, arg1=arg1@entry=0x0) at app.c:577
#33 0x0000000000408043 in main (argc=<optimized out>, argv=<optimized out>) at spool_main.c:746
~~~~~~~~~~~~~~~~~~~~~~~~~


I/O callback: (there is an obvious failure in callback)
~~~~~~~~~~~~~~~~~~~~~~~~~~
#0  0x00007ffff69fe055 in __memset_sse2 () from /lib64/libc.so.6
#1  0x000000000053ff62 in malloc_elem_free ()
#2  0x0000000000541f1c in malloc_heap_free ()
#3  0x0000000000543ee3 in rte_free ()
#4  0x0000000000524ec5 in spdk_free (buf=<optimized out>) at env.c:101
#5  0x0000000000519ba7 in spdk_bit_array_free (bap=<optimized out>) at bit_array.c:78
#6  0x000000000045a5d0 in bs_load_ctx_fail (ctx=0x4fb8280, bserrno=-84) at blobstore.c:3392
#7  0x0000000000454eea in bdev_blob_io_complete (bdev_io=0x200040485200, success=<optimized out>, arg=<optimized out>) at blob_bdev.c:86
#8  0x00000000004754af in nvme_complete_request (qpair=0x200008bc1e60, cpl=0x200006fb8010, req=0x200006fe7880, cb_arg=<optimized out>, cb_fn=<optimized out>) at nvme_internal.h:1179
#9  nvme_pcie_qpair_complete_tracker (qpair=qpair@entry=0x200008bc1e60, tr=0x200006f9c000, cpl=cpl@entry=0x200006fb8010, print_on_error=print_on_error@entry=true)
    at nvme_pcie_common.c:663
#10 0x00000000004758e1 in nvme_pcie_qpair_process_completions (qpair=0x200008bc1e60, max_completions=128) at nvme_pcie_common.c:856
#11 0x000000000047be5b in spdk_nvme_qpair_process_completions (qpair=qpair@entry=0x200008bc1e60, max_completions=max_completions@entry=0) at nvme_qpair.c:715
#12 0x00000000004760c4 in nvme_pcie_poll_group_process_completions (tgroup=0x4a44af0, completions_per_qpair=0, disconnected_qpair_cb=0x439920 <bdev_nvme_disconnected_qpair_cb>)
    at nvme_pcie_common.c:1100
#13 0x00000000004800c5 in nvme_transport_poll_group_process_completions (tgroup=tgroup@entry=0x4a44af0, completions_per_qpair=completions_per_qpair@entry=0,
    disconnected_qpair_cb=disconnected_qpair_cb@entry=0x439920 <bdev_nvme_disconnected_qpair_cb>) at nvme_transport.c:563
#14 0x0000000000489f67 in spdk_nvme_poll_group_process_completions (group=<optimized out>, completions_per_qpair=completions_per_qpair@entry=0,
    disconnected_qpair_cb=disconnected_qpair_cb@entry=0x439920 <bdev_nvme_disconnected_qpair_cb>) at nvme_poll_group.c:158
#15 0x00000000004398b7 in bdev_nvme_poll (arg=0x4854b40) at bdev_nvme.c:281
#16 0x000000000050d89d in thread_poll (thread=thread@entry=0x4850ba0, max_msgs=max_msgs@entry=0, now=now@entry=42058662443677013) at thread.c:644
#17 0x000000000050e42c in spdk_thread_poll (thread=thread@entry=0x4850ba0, max_msgs=max_msgs@entry=0, now=42058662443677013) at thread.c:733
#18 0x0000000000509cf8 in _reactor_run (reactor=0x483e540) at reactor.c:906
#19 reactor_run (arg=0x483e540) at reactor.c:948
#20 0x000000000050a057 in spdk_reactors_start () at reactor.c:1056
#21 0x0000000000507200 in spdk_app_start (opts_user=opts_user@entry=0x7fffffffdf50, start_fn=start_fn@entry=0x40c4a0 <spool_started>, arg1=arg1@entry=0x0) at app.c:577
#22 0x0000000000408043 in main (argc=<optimized out>, argv=<optimized out>) at spool_main.c:746
~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by changpe1** [comment] 2022-05-18 09:55
@YamboZhou I don't think SPDK blobstore can support VSS drive.

**Comment by YamboZhou** [comment] 2022-05-18 10:08
> @YamboZhou I don't think SPDK blobstore can support VSS drive.

@changpe1 We do not use blobstore in our service, but SPDK issues this I/O by default when it starts.

**Comment by Comphix** [comment] 2022-05-18 10:38
Looks like LVOL is examining the related bdev here at the start process.

**Comment by jimharris** [comment] 2022-05-19 23:41
> @YamboZhou I don't think SPDK blobstore can support VSS drive.

I agree @changpe1.  I think we need to check this in lvol bdev module - if the bdev has VSS, we should not try to examine it.

Thanks @YamboZhou for the details, this definitely helped to understand the full root cause here.

**Comment by Comphix** [comment] 2022-05-20 02:13
Looks like to could try to check base bdev's md size through below API to check the whether the bdev to examine is supporting VSS or not. If md size is not zero, then VSS is supported and the examine for LVOL bdev could be shipped.

```
uint32_t
spdk_bdev_get_md_size(const struct spdk_bdev *bdev)
{
	return bdev->md_len;
}
```

**Comment by Comphix** [comment] 2022-05-20 03:44
The SSD is formatted with 512+8

```
Number of LBA Formats:                 7
Current LBA Format:                    LBA Format #01
LBA Format #00: Data Size:   512  Metadata Size:     0
LBA Format #01: Data Size:   512  Metadata Size:     8
LBA Format #02: Data Size:   512  Metadata Size:    16
LBA Format #03: Data Size:  4096  Metadata Size:     0
LBA Format #04: Data Size:  4096  Metadata Size:     8
LBA Format #05: Data Size:  4096  Metadata Size:    64
LBA Format #06: Data Size:  4096  Metadata Size:   128
```

With the patch https://review.spdk.io/gerrit/c/spdk/spdk/+/12750

```
[2022-05-19 23:41:52.317982] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 1
[2022-05-19 23:41:52.493192] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
[2022-05-19 23:41:52.493527] accel_engine.c: 850:sw_accel_engine_init: *NOTICE*: Accel framework software engine initialized.
[2022-05-19 23:41:57.481455] vbdev_lvol.c:1445:vbdev_lvs_examine: *ERROR*: Cannot create bs dev on Nvme0n1
 which is formatted with metadata
```

**Comment by Comphix** [comment] 2022-05-20 03:47
@YamboZhou , will you also have a quick try on this patch. Thanks, Gang.

**Comment by Comphix** [comment] 2022-05-20 09:23
Close it as patch has been merged. Please let us know if there is any further issue. Thanks, Gang.

**Closed by Comphix** 2022-05-20 09:23 UTC
Labels: bug, Patches out for review
