### ISSUE TITLE
nvme_phy_autotest intermittent failure

### ISSUE THREAD

**Issue by Maciej-Szwed** [spdk/spdk#1058] opened 2019-11-15 10:15 UTC
nvme_phy_autotest failed with message:

/var/jenkins/workspace/NVMe_tests/nvme_phy_autotest/spdk/test/common/autotest_common.sh: line 384: kill: (1832902) - No such process
ERROR: process (pid: 1832902) is no longer running

Unfortunately there isn't any other line related to the error. Full log:
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/49698/archive/nvme_phy_autotest/failed_test.log

**Comment by spdkci** [comment] 2019-11-15 10:17
Another instance of this failure. Reported by @Maciej-Szwed. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49698.html

**Comment by jimharris** [comment] 2019-11-15 14:48
This is a duplicate of #1025.  A patch for that bug (it was a test issue) was merged yesterday.

**Closed by jimharris** 2019-11-15 14:48 UTC
Labels: Intermittent Failure
