### ISSUE TITLE
[nvmf_failover] core dumped from connection closed

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#2396] opened 2022-02-24 08:04 UTC
# CI Intermittent Failure

00:08:47.106  ************************************
00:08:47.106  START TEST nvmf_failover
00:08:47.106  ************************************
00:08:47.106   12:35:10	-- common/autotest_common.sh@965 -- # xtrace_enable
00:08:47.106   12:35:10	-- common/autotest_common.sh@966 -- # test/nvmf/host/failover.sh --transport=tcp

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/72078/archive/nvmf-tcp-uring-vg-autotest/build.log

## Execution failed at

00:09:23.153  Connection closed with partial response:
00:09:23.153  
00:09:23.153  
00:09:23.153  test/nvmf/host/failover.sh: line 62: 20766 Aborted                 (core dumped) $rootdir/test/bdev/bdevperf/bdevperf -z -r $bdevperf_rpc_sock -q 128 -o 4096 -w verify -t 10 -f &> $testdir/try.txt
00:09:23.153    12:35:44	-- host/failover.sh@62 -- # trap - ERR

00:09:23.154  ========== Backtrace start: ==========
00:09:23.154  
00:09:23.154  in test/nvmf/host/failover.sh:62 -> main(["--transport=tcp"])
00:09:23.154       ...
00:09:23.154     57  	
00:09:23.154     58  	sleep 1
00:09:23.154     59  	
00:09:23.154     60  	$rpc_py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_THIRD_PORT
00:09:23.154     61  	
00:09:23.154  => 62  	wait $run_test_pid
00:09:23.154     63  	
00:09:23.154     64  	killprocess $bdevperf_pid
00:09:23.154     65  	
00:09:23.154     66  	cat $testdir/try.txt
00:09:23.154     67  	# if this test fails it means we didn't fail over to the second
00:09:23.154       ...
00:09:23.154  
00:09:23.154  ========== Backtrace end ==========

**Comment by tomzawadzki** [comment] 2022-03-01 15:28
[Bug scrub] The info in the log seems to point to usban triggering in nvme_tcp_qpair_sock_cb. See:
```
00:09:33.836  Thread 1 (Thread 0x7f20c2939a00 (LWP 20766)):
00:09:33.836  #0  0x00007f20c2f912a2 in raise () from /usr/lib64/libc.so.6
00:09:33.836  No symbol table info available.
00:09:33.836  #1  0x00007f20c2f7a8a4 in abort () from /usr/lib64/libc.so.6
00:09:33.836  No symbol table info available.
00:09:33.836  #2  0x00007f20c316222f in __sanitizer::Abort() () from /usr/lib64/libubsan.so.1
00:09:33.836  No symbol table info available.
00:09:33.836  #3  0x00007f20c316d58c in __sanitizer::Die() () from /usr/lib64/libubsan.so.1
00:09:33.836  No symbol table info available.
00:09:33.836  #4  0x00007f20c314d3ef in __ubsan::ScopedReport::~ScopedReport() () from /usr/lib64/libubsan.so.1
00:09:33.836  No symbol table info available.
00:09:33.836  #5  0x00007f20c31509c0 in handleTypeMismatchImpl(__ubsan::TypeMismatchData*, unsigned long, __ubsan::ReportOptions) () from /usr/lib64/libubsan.so.1
00:09:33.836  No symbol table info available.
00:09:33.836  #6  0x00007f20c3151ce5 in __ubsan_handle_type_mismatch_v1 () from /usr/lib64/libubsan.so.1
00:09:33.836  No symbol table info available.
00:09:33.836  #7  0x00007f20c489d6d3 in nvme_tcp_qpair_sock_cb (ctx=0x7bb560, group=0x76dda0, sock=0x0) at nvme_tcp.c:1831
00:09:33.836          qpair = 0x7bb560
00:09:33.836          pgroup = 0x0
00:09:33.836          num_completions = 32767
00:09:33.836          tqpair = 0x7bb560
```

**Comment by tomzawadzki** [comment] 2022-03-01 15:37
This looks like a duplicate of #2390

**Closed by tomzawadzki** 2022-03-01 15:37 UTC
Labels: Intermittent Failure
