### ISSUE TITLE
bdevperf can't set the qos for the specified Malloc bdev if the number of lun some specific values

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#610] opened 2019-01-24 08:37 UTC
I have created bdev.conf with malloc bdev and set qos for some bdevs. but found that  
bdevperf somtimes can't work.

## Expected Behavior
the result should be the qos value.
## Current Behavior
The result is unlimited.

## Steps to Reproduce
1. configure bdev.conf with following config:

```
[Malloc]
  NumberOfLuns 7
  LunSizeInMB 32
[QoS]
  Limit_IOPS Malloc0 20000
  Limit_Read_BPS Malloc3 100
  Limit_Read_BPS Malloc1 50
```
2. run bdevperf with following parameters:
`./test/bdev/bdevperf/bdevperf -c bdev.conf -q 512 -o 4096 -w read -t 300
`
3.  The result is as below:
```
[root@waikikibeach44 spdk]# ./test/bdev/bdevperf/bdevperf -c bdev.conf -q 512 -o 4096 -w read -t 300
Starting SPDK v19.01-pre / DPDK 18.11.0 initialization...
[ DPDK EAL parameters: bdevperf --no-shconf -c 0x1 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid53976 ]
EAL: Detected 56 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
app.c: 625:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
Running I/O for 300 seconds...
 Logical core: 0
 Malloc6             :  404770.13 IO/s    1581.13 MB/s
 Malloc5             :  404770.13 IO/s    1581.13 MB/s
 Malloc4             :  404771.54 IO/s    1581.14 MB/s
 Malloc3             :   25603.67 IO/s     100.01 MB/s
 Malloc2             :  404771.84 IO/s    1581.14 MB/s
 Malloc1             :  404771.84 IO/s    1581.14 MB/s
 Malloc0             :  404773.35 IO/s    1581.15 MB/s
 =====================================================
 Total               : 2454232.51 IO/s    9586.85 MB/s

```
only Malloc3 have got qos result. malloc1 and malloc0 don't get the qos result.

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit: b8769cdb08813d2b41f7c6dfd92d863ac99ed24d

**Comment by Comphix** [comment] 2019-01-28 09:35
Looking at this issue.

**Comment by Comphix** [comment] 2019-01-29 06:53
Some findings

root@storage35:/home/gangcao/storage17/20160628/waikiki/spdk/test/bdev/bdevperf# ./bdevperf -c qos.conf -q 512 -o 4096 -w read -t 10 -m 0x1 -r /var/tmp/spdk.sock
Starting SPDK v19.01-pre / DPDK 18.11.0 initialization...
[ DPDK EAL parameters: bdevperf --no-shconf -c 0x1 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid38786 ]
EAL: Detected 44 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
app.c: 625:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
Running I/O for 10 seconds...
bdev.c:3818:spdk_bdev_close: *ERROR*: Closed last descriptor for bdev Malloc3 on thread 0xc2e990. Stopping QoS.
bdev.c:3818:spdk_bdev_close: *ERROR*: Closed last descriptor for bdev Malloc4 on thread 0xc2e990. Stopping QoS.
bdev.c:3818:spdk_bdev_close: *ERROR*: Closed last descriptor for bdev Malloc2 on thread 0xc2e990. Stopping QoS.
bdev.c:3818:spdk_bdev_close: *ERROR*: Closed last descriptor for bdev Malloc5 on thread 0xc2e990. Stopping QoS.
bdev.c:3818:spdk_bdev_close: *ERROR*: Closed last descriptor for bdev Malloc6 on thread 0xc2e990. Stopping QoS.
 Logical core: 0
 Malloc6             :   10054.00 IO/s      39.27 MB/s   <<<<< QoS achieved
 Malloc5             :   12866.40 IO/s      50.26 MB/s   <<<<< QoS achieved
 Malloc4             :   20106.40 IO/s      78.54 MB/s    <<<<< QoS achieved
 Malloc3             :   25712.50 IO/s     100.44 MB/s    <<<<< QoS achieved
 Malloc2             :   18029.50 IO/s      70.43 MB/s     <<<<< QoS achieved
 Malloc1             : 2085785.60 IO/s    8147.60 MB/s
 Malloc0             : 2085813.50 IO/s    8147.71 MB/s
 =====================================================
 Total               : 4258367.90 IO/s   16634.25 MB/s
root@storage35:/home/gangcao/storage17/20160628/waikiki/spdk/test/bdev/bdevperf# cat qos.conf
[Malloc]
  NumberOfLuns 7
  LunSizeInMB 32
[QoS]
  Limit_IOPS Malloc4 20000
  Limit_IOPS Malloc6 10000
  Limit_Read_BPS Malloc5 50
  Limit_Read_BPS Malloc2 70
  Limit_Read_BPS Malloc3 100

Seems like if I configure Malloc0 and Malloc1, the problem will occur as the QoS has been disabled at the startup of the application:

[ DPDK EAL parameters: bdevperf --no-shconf -c 0x1 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid38749 ]
EAL: Detected 44 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
app.c: 625:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
bdev.c:3818:spdk_bdev_close: *ERROR*: Closed last descriptor for bdev Malloc0 on thread 0x170d8c0. Stopping QoS.
bdev.c:3818:spdk_bdev_close: *ERROR*: Closed last descriptor for bdev Malloc1 on thread 0x170d8c0. Stopping QoS.
Running I/O for 10 seconds...
bdev.c:3818:spdk_bdev_close: *ERROR*: Closed last descriptor for bdev Malloc1 on thread 0x170d8c0. Stopping QoS.
bdev.c:3818:spdk_bdev_close: *ERROR*: Closed last descriptor for bdev Malloc0 on thread 0x170d8c0. Stopping QoS.
bdev.c:3818:spdk_bdev_close: *ERROR*: Closed last descriptor for bdev Malloc3 on thread 0x170d8c0. Stopping QoS.
bdev.c:3818:spdk_bdev_close: *ERROR*: Closed last descriptor for bdev Malloc2 on thread 0x170d8c0. Stopping QoS.

**Comment by Comphix** [comment] 2019-01-29 06:53
@liang2yan , please also have a try on other Bdev except Malloc0 and Malloc1, thanks

**Comment by Comphix** [comment] 2019-01-29 06:56
My commit id:

commit d1f943239ee8bb0d459da01fe96562bc5f4f0948
Author: Ben Walker <benjamin.walker@intel.com>
Date:   Mon Jan 28 11:09:59 2019 -0700

**Comment by Comphix** [comment] 2019-01-29 07:19
Seems like relating to the Malloc bdev creation. @liang2yan , please have a try with NVMe or NULL Bdev with the similar QoS configuration. Thanks.

**Comment by Comphix** [comment] 2019-01-29 07:44
Looks like relating to the Malloc Bdev, I've tried the NVMe SSD, it works as expected.

root@storage35:/home/gangcao/storage17/20160628/waikiki/spdk/test/bdev/bdevperf# ./bdevperf -c qos_ssd.conf -q 512 -o 4096 -w read -t 10 -r /var/tmp/spdk.sock
Starting SPDK v19.01-pre / DPDK 18.11.0 initialization...
[ DPDK EAL parameters: bdevperf --no-shconf -c 0x1 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid2222 ]
EAL: Detected 44 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
app.c: 625:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
Running I/O for 10 seconds...
 Logical core: 0
 Nvme6n1             :   25659.80 IO/s     100.23 MB/s
 Nvme3n1             :   10051.20 IO/s      39.26 MB/s
 Nvme2n1             :   20051.20 IO/s      78.33 MB/s
 Nvme1n1             :   10051.20 IO/s      39.26 MB/s
 Nvme0n1             :   20051.20 IO/s      78.33 MB/s
 Nvme5n1             :   17971.20 IO/s      70.20 MB/s
 Nvme4n1             :   12851.10 IO/s      50.20 MB/s
 Total               :  116686.90 IO/s     455.81 MB/s
root@storage35:/home/gangcao/storage17/20160628/waikiki/spdk/test/bdev/bdevperf# cat qos_ssd.conf
[Nvme]
  TransportID "trtype:PCIe traddr:0000:06:00.0" Nvme0
  TransportID "trtype:PCIe traddr:0000:07:00.0" Nvme1
  TransportID "trtype:PCIe traddr:0000:08:00.0" Nvme2
  TransportID "trtype:PCIe traddr:0000:09:00.0" Nvme3
  TransportID "trtype:PCIe traddr:0000:0a:00.0" Nvme4
  TransportID "trtype:PCIe traddr:0000:0b:00.0" Nvme5
  TransportID "trtype:PCIe traddr:0000:0d:00.0" Nvme6

[QoS]
  Limit_IOPS Nvme0n1 20000
  Limit_IOPS Nvme1n1 10000
  Limit_IOPS Nvme2n1 20000
  Limit_IOPS Nvme3n1 10000
  Limit_Read_BPS Nvme4n1 50
  Limit_Read_BPS Nvme5n1 70
  Limit_Read_BPS Nvme6n1 100

**Comment by Comphix** [comment] 2019-02-01 06:44
The root cause is that:

1. The QoS related structure and poller setup at the bdev create_cb
2. The logicial volume open & close the device
3. The QoS destroyed
4. The bdev open from upper layer again
5. The QoS is not setup

Detailed log as below:

(gdb) bt
#0  spdk_bdev_open (bdev=0x200013ef7ac0, write=false, remove_cb=0x44e227 <spdk_gpt_base_bdev_hotremove_cb>, remove_ctx=0x7b71b0,
    _desc=0x7b71b8) at bdev.c:3748
#1  0x000000000046eee8 in spdk_bdev_part_base_construct (bdev=0x200013ef7ac0, remove_cb=0x44e227 <spdk_gpt_base_bdev_hotremove_cb>,
    module=0x725780 <gpt_if>, fn_table=0x725800 <vbdev_gpt_fn_table>, tailq=0x7b7188, free_fn=0x44e1f6 <spdk_gpt_base_free>,
    ctx=0x7b7140, channel_size=16, ch_create_cb=0x0, ch_destroy_cb=0x0) at part.c:310
#2  0x000000000044e32e in spdk_gpt_base_bdev_init (bdev=0x200013ef7ac0) at vbdev_gpt.c:136
#3  0x000000000044edb2 in vbdev_gpt_read_gpt (bdev=0x200013ef7ac0) at vbdev_gpt.c:394
#4  0x000000000044f010 in vbdev_gpt_examine (bdev=0x200013ef7ac0) at vbdev_gpt.c:459
#5  0x000000000046ca46 in spdk_bdev_start (bdev=0x200013ef7ac0) at bdev.c:3636
#6  0x000000000046ca88 in spdk_bdev_register (bdev=0x200013ef7ac0) at bdev.c:3647
#7  0x0000000000428003 in create_malloc_disk (name=0x0, uuid=0x0, num_blocks=65536, block_size=512) at bdev_malloc.c:434
#8  0x00000000004281b7 in bdev_malloc_initialize () at bdev_malloc.c:477
#9  0x00000000004660c7 in spdk_bdev_modules_init () at bdev.c:854
#10 0x00000000004664e0 in spdk_bdev_initialize (cb_fn=0x46484f <spdk_bdev_initialize_complete>, cb_arg=0x0) at bdev.c:979
#11 0x000000000046487f in spdk_bdev_subsystem_initialize () at bdev.c:52
#12 0x000000000047343c in spdk_subsystem_init_next (rc=0) at subsystem.c:138
#13 0x0000000000464a65 in spdk_copy_engine_subsystem_initialize () at copy.c:48
#14 0x000000000047343c in spdk_subsystem_init_next (rc=0) at subsystem.c:138
#15 0x000000000047355d in spdk_subsystem_verify (arg1=0x0, arg2=0x0) at subsystem.c:166
#16 0x0000000000472451 in _spdk_event_queue_run_batch (reactor=0x7b5700, thread=0x7b5b30) at reactor.c:163
#17 0x0000000000472949 in _spdk_reactor_run (arg=0x7b5700) at reactor.c:312
#18 0x0000000000472ca2 in spdk_reactors_start () at reactor.c:421
#19 0x000000000047126f in spdk_app_start (opts=0x7fffffffddb0, start_fn=0x406914 <bdevperf_run>, arg1=0x0, arg2=0x0) at app.c:680
#20 0x000000000040748a in main (argc=13, argv=0x7fffffffdf48) at bdevperf.c:1026

#0  spdk_bdev_open (bdev=0x200013ef7ac0, write=true, remove_cb=0x407878 <vbdev_lvs_hotremove_cb>, remove_ctx=0x200013ef7ac0,
    _desc=0x7fffffffd940) at bdev.c:3748
#1  0x0000000000422e8d in spdk_bdev_create_bs_dev (bdev=0x200013ef7ac0, remove_cb=0x407878 <vbdev_lvs_hotremove_cb>,
    remove_ctx=0x200013ef7ac0) at blob_bdev.c:336
#2  0x000000000040a752 in vbdev_lvs_examine (bdev=0x200013ef7ac0) at vbdev_lvol.c:1329
#3  0x000000000046ca46 in spdk_bdev_start (bdev=0x200013ef7ac0) at bdev.c:3636
#4  0x000000000046ca88 in spdk_bdev_register (bdev=0x200013ef7ac0) at bdev.c:3647
#5  0x0000000000428003 in create_malloc_disk (name=0x0, uuid=0x0, num_blocks=65536, block_size=512) at bdev_malloc.c:434
#6  0x00000000004281b7 in bdev_malloc_initialize () at bdev_malloc.c:477
#7  0x00000000004660c7 in spdk_bdev_modules_init () at bdev.c:854
#8  0x00000000004664e0 in spdk_bdev_initialize (cb_fn=0x46484f <spdk_bdev_initialize_complete>, cb_arg=0x0) at bdev.c:979
#9  0x000000000046487f in spdk_bdev_subsystem_initialize () at bdev.c:52
#10 0x000000000047343c in spdk_subsystem_init_next (rc=0) at subsystem.c:138
#11 0x0000000000464a65 in spdk_copy_engine_subsystem_initialize () at copy.c:48
#12 0x000000000047343c in spdk_subsystem_init_next (rc=0) at subsystem.c:138
#13 0x000000000047355d in spdk_subsystem_verify (arg1=0x0, arg2=0x0) at subsystem.c:166
#14 0x0000000000472451 in _spdk_event_queue_run_batch (reactor=0x7b5700, thread=0x7b5b30) at reactor.c:163
#15 0x0000000000472949 in _spdk_reactor_run (arg=0x7b5700) at reactor.c:312
#16 0x0000000000472ca2 in spdk_reactors_start () at reactor.c:421
#17 0x000000000047126f in spdk_app_start (opts=0x7fffffffddb0, start_fn=0x406914 <bdevperf_run>, arg1=0x0, arg2=0x0) at app.c:680
#18 0x000000000040748a in main (argc=13, argv=0x7fffffffdf48) at bdevperf.c:1026


#0  spdk_bdev_close (desc=0x7b6850) at bdev.c:3791
#1  0x000000000046e6f3 in spdk_bdev_part_base_free (base=0x7b67f0) at part.c:87
#2  0x000000000044ed93 in spdk_gpt_bdev_complete (bdev_io=0x200007000040, status=true, arg=0x7b69a0) at vbdev_gpt.c:383
#3  0x000000000046b9e1 in _spdk_bdev_io_complete (ctx=0x200007000040) at bdev.c:3232
#4  0x0000000000477c64 in _spdk_msg_queue_run_batch (thread=0x7b5b30, max_msgs=8) at thread.c:297
#5  0x0000000000477de7 in spdk_thread_poll (thread=0x7b5b30, max_msgs=0) at thread.c:338
#6  0x000000000047298c in _spdk_reactor_run (arg=0x7b5700) at reactor.c:320
#7  0x0000000000472ca2 in spdk_reactors_start () at reactor.c:421

(gdb) bt
#0  spdk_bdev_close (desc=0x7b6bb0) at bdev.c:3792
#1  0x0000000000422dfe in bdev_blob_destroy (bs_dev=0x7b6b30) at blob_bdev.c:318
#2  0x00000000004185e2 in _spdk_bs_dev_destroy (io_device=0x7b6c30) at blobstore.c:2276
#3  0x0000000000478b07 in _finish_unregister (arg=0x7b6d40) at thread.c:694
#4  0x0000000000477c64 in _spdk_msg_queue_run_batch (thread=0x7b5b30, max_msgs=8) at thread.c:297
#5  0x0000000000477de7 in spdk_thread_poll (thread=0x7b5b30, max_msgs=0) at thread.c:338
#6  0x000000000047298c in _spdk_reactor_run (arg=0x7b5700) at reactor.c:320
#7  0x0000000000472ca2 in spdk_reactors_start () at reactor.c:421
#8  0x000000000047126f in spdk_app_start (opts=0x7fffffffddb0, start_fn=0x406914 <bdevperf_run>, arg1=0x0, arg2=0x0) at app.c:680
#9  0x000000000040748a in main (argc=13, argv=0x7fffffffdf48) at bdevperf.c:1026

>>>> QoS destroy

(gdb) bt
#0  spdk_bdev_open (bdev=0x200013effe40, write=true, remove_cb=0x0, remove_ctx=0x0, _desc=0x7b6800) at bdev.c:3749
#1  0x0000000000405370 in bdevperf_construct_targets () at bdevperf.c:216
#2  0x0000000000406946 in bdevperf_run (arg1=0x0, arg2=0x0) at bdevperf.c:751
#3  0x0000000000472451 in _spdk_event_queue_run_batch (reactor=0x7b5700, thread=0x7b5b30) at reactor.c:163
#4  0x0000000000472949 in _spdk_reactor_run (arg=0x7b5700) at reactor.c:312
#5  0x0000000000472ca2 in spdk_reactors_start () at reactor.c:421
#6  0x000000000047126f in spdk_app_start (opts=0x7fffffffddb0, start_fn=0x406914 <bdevperf_run>, arg1=0x0, arg2=0x0) at app.c:680
#7  0x000000000040748a in main (argc=13, argv=0x7fffffffdf48) at bdevperf.c:1026
#8  0x000000000047126f in spdk_app_start (opts=0x7fffffffddb0, start_fn=0x406914 <bdevperf_run>, arg1=0x0, arg2=0x0) at app.c:680
#9  0x000000000040748a in main (argc=13, argv=0x7fffffffdf48) at bdevperf.c:1026

>>>> At this moment, the QoS already destroyed and not enabled any more

**Comment by Comphix** [comment] 2019-02-01 06:44
Patch has been raised at https://review.gerrithub.io/#/c/spdk/spdk/+/442953/

**Comment by jimharris** [comment] 2019-03-01 22:30
Patch has been merged.

**Closed by jimharris** 2019-03-01 22:30 UTC
Labels: bug
