### ISSUE TITLE
Blobfs latent failures in test pool.

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#990] opened 2019-10-18 18:48 UTC
## Current Behavior
From time to time, the Blobfs tests fail with the following error message.

  20:40:56	# /var/jenkins/workspace/RBD_BlobFS_tests/BlobFS_autotest/spdk/scripts/rpc.py -s /var/tmp/spdk-blobfs.sock blobfs_detect BlobfsBdev
blobfs.c: 272:__initialize_cache: *ERROR*: Create mempool failed, you may increase the memory and try again
bdev_svc: blobfs.c:273: __initialize_cache: Assertion `false' failed.

## Possible Solution
Not sure yet, but there may just be a memory flag we need to set.

## Steps to Reproduce
One example below.
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/46894/archive/BlobFS_autotest/build.log

## Context (Environment including OS version, SPDK version, etc.)
In the Jenkins CI system.

**Comment by dong-liuliu** [comment] 2019-10-21 06:07
Hi, Seth

It is because the default fs cache size for blobfs (4GB) is too large for test env.
I'm going to add a simple RPC which can set the fs cache size. Then a smaller cache can solve this problem.

**Comment by dong-liuliu** [comment] 2019-10-21 08:40
Please check and review [https://review.gerrithub.io/c/spdk/spdk/+/471870](url) 
This issue should be solved by it.

**Comment by jimharris** [comment] 2019-10-21 16:06
Why does this only happen sometimes?

We need to fully root cause this, rather than just reducing cache size to 512MB.

**Comment by dong-liuliu** [comment] 2019-10-22 02:24
Hi, Jim, 
Probably, the root cause why it happens sometimes is because of the hugepage memory allocator in DPDK lib.

The cache pool of blobfs needs 4GB by default. Seems mempool creation requires all that 4GB are coming from one node. In my experiment, if the hugepage memory in each node is less than 4GB, even the total size is larger then 4GB, the mempool allocation of blobfs cache will fail.

From the build.log, in the test env, we setup 8GB hugepage memory, and each node 4GB. If hugepage operations are all on node0, and leave a full 4GB free hugepage in node1. Then, cache pool can be allocated in node1 successfully.
But if a few hugepages in node1 are already allocated out before blobfs cache allocation. Both nodes don't have a full 4GB. Then the cache pool allocation will fail.

**Comment by jimharris** [comment] 2019-10-22 03:26
Thanks @dong-liuliu.  I see the patch reduces the cache size from 4GB to 512MB.  Would it be better to reduce it to 3GB or 3.5GB instead?  512MB seems low based on your explanation.

**Comment by jimharris** [comment] 2019-10-22 03:39
This is for the new blobfs RPC tests - not the existing RocksDB tests.  So I'm fine with using 512MB for this case.

**Comment by dong-liuliu** [comment] 2019-10-22 04:48
Yes, Jim, this is only for new blobfs RPC tests.
I saw there is a 512mb cache setting in test/blobfs/mkfs/mkfs.c, so just follow it in blobfs RPC test.

**Comment by benlwalker** [comment] 2019-10-28 21:51
http://10.102.17.206/results/autotest-per-patch/builds/48049/archive/BlobFS_autotest/build.log

**Comment by dong-liuliu** [comment] 2019-10-29 07:28
So after 19.10 release, please review patch for this intermittent failure
https://review.gerrithub.io/c/spdk/spdk/+/471957/2

**Comment by spdkci** [comment] 2019-10-31 19:00
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48431.html

**Comment by spdkci** [comment] 2019-10-31 19:01
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48430.html

**Comment by spdkci** [comment] 2019-11-01 17:33
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48577.html

**Comment by spdkci** [comment] 2019-11-04 20:06
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48734.html

**Comment by spdkci** [comment] 2019-11-05 07:29
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48782.html

**Comment by spdkci** [comment] 2019-11-05 09:15
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48822.html

**Comment by spdkci** [comment] 2019-11-05 13:12
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48847.html

**Comment by spdkci** [comment] 2019-11-06 22:06
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49026.html

**Comment by jimharris** [comment] 2019-11-07 00:34
Patches from @dong-liuliu have been merged.  Thanks!

**Closed by jimharris** 2019-11-07 00:34 UTC
Labels: Intermittent Failure
