### ISSUE TITLE
FIO SPDK No I/O performed by spdk, perhaps try --debug=io option for details?

### ISSUE THREAD

**Issue by donghy-coredumped** [spdk/spdk#2725] opened 2022-10-08 06:41 UTC
# Bug report

FIO SPDK Report ：
TELEMETRY: No legacy callbacks, legacy socket not created
seqwrite_128K_j1_qd128: No I/O performed by spdk, perhaps try --debug=io option for details?

## Expected Behavior

This is expected behavior？

## Steps to Reproduce

1.https://github.com/spdk/spdk/tree/master/examples/nvme/fio_plugin
2.example_config.fio：
cat example_config.fio
[global]
ioengine=spdk
thread=1
group_reporting=1
direct=1
verify=0
bs=128K
rw=write
iodepth=16
ramp_time=60
runtime=1800

[seqwrite_128K_j1_qd128]
size=100%
numjobs=1
filename=trtype=PCIe traddr=35.00.0 ns=1
3. LD_PRELOAD=/root/donghy/spdk/build/fio/spdk_nvme /root/donghy/fio/fio example_config.fio

## Context (Environment including OS version, SPDK version, etc.)
spdk version:commit 78ff96bb7317a1a1e0fe84557d8f35a25b2e706c
OS:CentOS Linux release 8.5.2111 4.18.0-348.7.1.el8_5.x86_64

**Comment by Comphix** [comment] 2022-10-08 06:51
Are there any more logs from the FIO running besides below?

```
FIO SPDK Report ：
TELEMETRY: No legacy callbacks, legacy socket not created
seqwrite_128K_j1_qd128: No I/O performed by spdk, perhaps try --debug=io option for details?
```

**Comment by donghy-coredumped** [comment] 2022-10-08 07:02
> 

LD_PRELOAD=/root/donghy/spdk/build/fio/spdk_nvme /root/donghy/fio/fio example_config.fio
seqwrite_128K_j1_qd128: (g=0): rw=write, bs=(R) 128KiB-128KiB, (W) 128KiB-128KiB, (T) 128KiB-128KiB, ioengine=spdk, iodepth=16
fio-3.3
Starting 1 thread
TELEMETRY: No legacy callbacks, legacy socket not created
seqwrite_128K_j1_qd128: No I/O performed by spdk, perhaps try --debug=io option for details?
Jobs: 1 (f=0): [f(1)][100.0%][r=0KiB/s,w=3318MiB/s][r=0,w=26.5k IOPS][eta 00m:00s]
seqwrite_128K_j1_qd128: (groupid=0, jobs=1): err= 0: pid=2090588: Sat Oct  8 14:22:40 2022
  write: IOPS=31.0k, BW=3876MiB/s (4064MB/s)(3350GiB/885053msec)
    slat (nsec): min=1051, max=56187, avg=1971.74, stdev=449.96
    clat (usec): min=196, max=9554, avg=513.89, stdev=505.84
     lat (usec): min=209, max=9556, avg=515.87, stdev=505.84
    clat percentiles (usec):
     |  1.00th=[  285],  5.00th=[  285], 10.00th=[  289], 20.00th=[  318],
     | 30.00th=[  326], 40.00th=[  334], 50.00th=[  334], 60.00th=[  343],
     | 70.00th=[  351], 80.00th=[  515], 90.00th=[ 1188], 95.00th=[ 1205],
     | 99.00th=[ 2442], 99.50th=[ 4359], 99.90th=[ 5473], 99.95th=[ 5735],
     | 99.99th=[ 6390]
   bw (  MiB/s): min= 3534, max= 4106, per=100.00%, avg=3889.17, stdev=132.30, samples=1770
   iops        : min=28278, max=32855, avg=31113.13, stdev=1058.37, samples=1770
  lat (usec)   : 250=0.01%, 500=79.64%, 750=3.83%, 1000=1.60%
  lat (msec)   : 2=13.66%, 4=0.63%, 10=0.64%
  cpu          : usr=99.88%, sys=0.00%, ctx=1710, majf=0, minf=761
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=106.8%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=0,27442785,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
  WRITE: bw=3876MiB/s (4064MB/s), 3876MiB/s-3876MiB/s (4064MB/s-4064MB/s), io=3350GiB (3597GB), run=885053-885053msec

**Comment by Comphix** [comment] 2022-10-08 07:15
This is interesting.

Looks like FIO runs completed as expected while it is saying:

```
seqwrite_128K_j1_qd128: No I/O performed by spdk, perhaps try --debug=io option for details?
```

This logs seems reported by FIO tool.

**Comment by Comphix** [comment] 2022-10-08 07:18
Maybe could try to add below configuration in the FIO job or use --debug=io as suggested to get more details.
```
debug=io
```

**Comment by donghy-coredumped** [comment] 2022-10-08 07:34
> 


> This is interesting.
> 
> Looks like FIO runs completed as expected while it is saying:
> 
> ```
> seqwrite_128K_j1_qd128: No I/O performed by spdk, perhaps try --debug=io option for details?
> ```
> 
> This logs seems reported by FIO tool.

FIO Version : 3.3 


> Maybe could try to add below configuration in the FIO job or use --debug=io as suggested to get more details.
> 
> ```
> debug=io
> ```

spdk fio_spdk_debug.log  -A 20 -B 20
fio: set debug option io
io       2104510 load ioengine spdk
seqwrite_128K_j1_qd128: (g=0): rw=write, bs=(R) 128KiB-128KiB, (W) 128KiB-128KiB, (T) 128KiB-128KiB, ioengine=spdk, iodepth=16
fio-3.3
Starting 1 thread
io       2104510 **invalidate spdk cache** trtype=PCIe traddr=35.00.0 ns=1
io       2104510 fill_io_u: io_u 0x7fbe80002d40: off=0/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 prep: io_u 0x7fbe80002d40: off=0/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 queue: io_u 0x7fbe80002d40: off=0/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 calling ->commit(), depth 1
io       2104510 fill_io_u: io_u 0x7fbe80002b40: off=131072/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 prep: io_u 0x7fbe80002b40: off=131072/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 queue: io_u 0x7fbe80002b40: off=131072/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 calling ->commit(), depth 2
io       2104510 fill_io_u: io_u 0x7fbe80002940: off=262144/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 prep: io_u 0x7fbe80002940: off=262144/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 queue: io_u 0x7fbe80002940: off=262144/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 calling ->commit(), depth 3
io       2104510 fill_io_u: io_u 0x7fbe80002740: off=393216/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 prep: io_u 0x7fbe80002740: off=393216/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 queue: io_u 0x7fbe80002740: off=393216/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 calling ->commit(), depth 4
io       2104510 fill_io_u: io_u 0x7fbe80002540: off=524288/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 prep: io_u 0x7fbe80002540: off=524288/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 queue: io_u 0x7fbe80002540: off=524288/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 calling ->commit(), depth 5

most messages:

io       2104510 io complete: io_u 0x7fbe80002740: off=71022673920/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 fill_io_u: io_u 0x7fbe80002740: off=71024771072/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 prep: io_u 0x7fbe80002740: off=71024771072/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 queue: io_u 0x7fbe80002740: off=71024771072/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 calling ->commit(), depth 16
io       2104510 io_u_queued_complete: min=1
io       2104510 getevents: 1
io       2104510 io complete: io_u 0x7fbe80001540: off=71022804992/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 fill_io_u: io_u 0x7fbe80001540: off=71024902144/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 prep: io_u 0x7fbe80001540: off=71024902144/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 queue: io_u 0x7fbe80001540: off=71024902144/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 calling ->commit(), depth 16
io       2104510 io_u_queued_complete: min=1
io       2104510 getevents: 1
io       2104510 io complete: io_u 0x7fbe80000f40: off=71022936064/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 fill_io_u: io_u 0x7fbe80000f40: off=71025033216/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 prep: io_u 0x7fbe80000f40: off=71025033216/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 queue: io_u 0x7fbe80000f40: off=71025033216/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 calling ->commit(), depth 16
io       2104510 io_u_queued_complete: min=1
io       2104510 getevents: 1
io       2104510 io complete: io_u 0x7fbe80001140: off=71023067136/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 fill_io_u: io_u 0x7fbe80001140: off=71025164288/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 prep: io_u 0x7fbe80001140: off=71025164288/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 queue: io_u 0x7fbe80001140: off=71025164288/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 calling ->commit(), depth 16
io       2104510 io_u_queued_complete: min=1
io       2104510 getevents: 1
io       2104510 io complete: io_u 0x7fbe80001940: off=71023198208/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 fill_io_u: io_u 0x7fbe80001940: off=71025295360/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 prep: io_u 0x7fbe80001940: off=71025295360/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 queue: io_u 0x7fbe80001940: off=71025295360/len=131072/ddir=1io       2104510 /trtype=PCIe traddr=35.00.0 ns=1io       2104510
io       2104510 calling ->commit(), depth 16
io       2104510 io_u_queued_complete: min=1

**Comment by Comphix** [comment] 2022-10-08 07:39
From the debug log, it looks like no problem. IO off is increasing, and getevents is not zero which means IO is back.

Maybe you could have a try with other IO size like normal 4K? Or maybe different FIO version?

**Comment by wanghailiangx** [comment] 2022-10-09 04:58
I tested fio-3.7 and fio-3.28, didn't reproduce. This seems a fio issue, please refer: https://github.com/axboe/fio/issues/554.

**Comment by donghy-coredumped** [comment] 2022-10-09 06:52
The test found that if "size" is specified, it will report "No I/O performed by spdk":
1. runtime=1800, size=100% -> normal
2.runtime=1800, no size specified -->" No I/O performed by spdk"

**Comment by Comphix** [comment] 2022-10-09 07:08
> The test found that if "size" is specified, it will report "No I/O performed by spdk":
> 
> 1. runtime=1800, size=100% -> normal
>    2.runtime=1800, no size specified -->" No I/O performed by spdk"

In this case, it looks like a FIO issue.

**Comment by wanghailiangx** [comment] 2022-10-09 07:21
> The test found that if "size" is specified, it will report "No I/O performed by spdk":
> 
> 1. runtime=1800, size=100% -> normal
>    2.runtime=1800, no size specified -->" No I/O performed by spdk"

I tested with size or not, the conclusion is still the same. Based on experience, I guess SSD may not be mounted well. Your result WRITE bw=3876MiB/s, this seems fio through memory, not SSD. What model is your SSD? My result WRITE bw is less than 2G/s. Please try ./scripts/setup.sh reset and ./scripts/setup.sh again? Or you can run build/examples/identify.

**Comment by donghy-coredumped** [comment] 2022-10-10 02:47
> > The test found that if "size" is specified, it will report "No I/O performed by spdk":
> > 
> > 1. runtime=1800, size=100% -> normal
> >    2.runtime=1800, no size specified -->" No I/O performed by spdk"
> 
> In this case, it looks like a FIO issue.

Yes . I try switch 

> > The test found that if "size" is specified, it will report "No I/O performed by spdk":
> > 
> > 1. runtime=1800, size=100% -> normal
> >    2.runtime=1800, no size specified -->" No I/O performed by spdk"
> 
> I tested with size or not, the conclusion is still the same. Based on experience, I guess SSD may not be mounted well. Your result WRITE bw=3876MiB/s, this seems fio through memory, not SSD. What model is your SSD? My result WRITE bw is less than 2G/s. Please try ./scripts/setup.sh reset and ./scripts/setup.sh again? Or you can run build/examples/identify.

I use ScaleFlux CSD 3000

I try it ./scripts/setup.sh reset and ./scripts/setup.sh ,  but same result

**Comment by wanghailiangx** [comment] 2022-10-10 11:18
**invalidate spdk cache** trtype=PCIe traddr=35.00.0 ns=1
This prompt is irrelevant, there is the sentence when I test with --debug=io locally, but cant not reproduce "No I/O performed by spdk".

**Comment by ksztyber** [comment] 2022-12-06 15:55
[Bug scrub] Since this doesn't look like an SPDK issue, we can close this one.

**Closed by ksztyber** 2022-12-06 15:55 UTC
Labels: 3rd party issue
