### ISSUE TITLE
SPDK environment initialization from a DPDK application

### ISSUE THREAD

**Issue by pradeep-nalla** [spdk/spdk#529] opened 2018-12-01 05:57 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

I got a requirement of a DPDK application that forwards packets and also handle NVMe commands. As the DPDK's EAL is already initialized by the forwarding application, calling rte_eal_init again in the spdk_env_init is causing issue with rte_error being set to EALREADY. Is there a way for the env_dpdk library of SPDK to consider an already initialized DPDK. For time being I changed env_spdk to ignore EALREADY error.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by peluse** [comment] 2018-12-02 20:37
FYI from email:
Hi Pradeep,

There's no way to do that currently, but it's a very reasonable request.  Would you mind adding an issue in GitHub for this?  Since it's an enhancement request, there's no need to fill out the template - adding what you have here is sufficient.

http://github.com/spdk/spdk/issues

I'll add some comments on how it might be implemented in SPDK once the issue is filed.

Thanks,

-Jim

**Comment by darsto** [comment] 2018-12-05 09:02
@jimharris we've just added spdk_pci_init() that also needs to be called as a part of SPDK env initialization, so the name spdk_env_memory_map_init() isn't accurate anymore. How about spdk_env_post_init?

Or could we maybe publish spdk_pci_init(), spdk_mem_map_init() and spdk_vtophys_init(), so that they can be called externally? There will be a problem once we implement another spdk_something_init() and start requiring the users to call it though.

**Comment by jimharris** [comment] 2018-12-05 15:03
Good point on spdk_pci_init().  I agree that spdk_env_memory_map_init() then doesn't make sense.  I also agree that exporting each of those individual functions just makes it harder to use and update in the future.

spdk_env_post_init() is as good a name as any.

**Comment by pradeep-nalla** [comment] 2018-12-05 15:30
Yes. The user can be given flexibility with the initialisation of the SPDK
dependencies (here DPDK) not any fine grain control of the SPDK
initialisation itself.

Thanks
Pradeep.

**Comment by jimharris** [comment] 2018-12-13 04:46
@darsto brings up a good point - we will need to add a test case for this once this functionality is enabled.  Maybe we can do something like an SPDK NVMe test, initializing DPDK first, and then do the spdk_env_init.

**Comment by dong-liuliu** [comment] 2018-12-14 02:49
Add spdk_env_post_init at patch
https://review.gerrithub.io/c/spdk/spdk/+/437225

**Comment by dong-liuliu** [comment] 2018-12-14 02:50
@pradeep-nalla you may have a check whether function spdk_env_post_init could meet your requirement

**Comment by jimharris** [comment] 2018-12-18 23:48
I'm rethinking this.  I think this function should not be in env.h, but in a new include/spdk/env_dpdk.h.

The reason is that spdk_env_init v. spdk_env_post_init is very DPDK specific.  If someone develops an alternate env layer, defining what spdk_env_post_init does could be very difficult.  I think the meaning is more clear if we say:

If you're using DPDK, and you've already called rte_eal_init, then include include/spdk/env_dpdk.h and call spdk_env_dpdk_post_init().

@dong-liuliu - could you try revising your patch in this way?

**Comment by dong-liuliu** [comment] 2018-12-19 10:35
Sounds reasonable, will revise it following your rethinking.

**Comment by jimharris** [comment] 2018-12-20 20:05
@dong-liuliu - I like the updates to your patch.  I posted a few small comments but overall I think this is a winner!

**Comment by jimharris** [comment] 2019-01-08 13:31
https://review.gerrithub.io/#/c/spdk/spdk/+/437225/ has been merged to master.  You can now include spdk/env_dpdk.h and call spdk_env_dpdk_post_init() to perform the SPDK-specific initialization operations if your application has already called rte_eal_init() directly.

**Closed by jimharris** 2019-01-08 13:31 UTC
Labels: enhancement
