### ISSUE TITLE
NVMEoF failed to establish connection to spdk target

### ISSUE THREAD

**Issue by alekseymmm** [spdk/spdk#828] opened 2019-06-18 10:07 UTC
Started spdk nvmeof target but failed to discover and connect to it. With nvmf debug message 
```
./app/spdk_tgt/spdk_tgt -m 0xff -c etc/spdk/am_nvmf.conf.in -L nvmf
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0xff --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid143935 ]
EAL: 1 hugepages of size 1073741824 reserved, but no mounted hugetlbfs found for that size
app.c: 628:spdk_app_start: *NOTICE*: Total cores available: 8
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 1
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 2
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 3
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 4
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 5
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 6
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 7
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
subsystem.c:1123:spdk_nvmf_subsystem_add_ns: *DEBUG*: Subsystem nqn.2016-06.io.spdk:sky02: bdev Nvme0n1 assigned nsid 1
conf.c: 349:spdk_nvmf_parse_subsystem: *INFO*: Attaching block device Nvme0n1 to subsystem nqn.2016-06.io.spdk:sky02
subsystem.c:1123:spdk_nvmf_subsystem_add_ns: *DEBUG*: Subsystem nqn.2016-06.io.spdk:sky02: bdev Nvme1n1 assigned nsid 2
conf.c: 349:spdk_nvmf_parse_subsystem: *INFO*: Attaching block device Nvme1n1 to subsystem nqn.2016-06.io.spdk:sky02
nvmf_tgt.c: 437:nvmf_tgt_advance_state: *INFO*: Acceptor running

// discover started here

ctrlr.c:2525:nvmf_trace_command: *DEBUG*: Admin Fabrics cmd: fctype 0x01 cid 0
ctrlr.c:2545:nvmf_trace_command: *DEBUG*: SGL: Keyed (Inv): addr 0xffff8817dc9a7000 key 0x2be5e601 len 0x400
ctrlr.c: 481:spdk_nvmf_ctrlr_connect: *DEBUG*: recfmt 0x0 qid 0 sqsize 31
ctrlr.c: 483:spdk_nvmf_ctrlr_connect: *DEBUG*: Connect data:
ctrlr.c: 484:spdk_nvmf_ctrlr_connect: *DEBUG*:   cntlid:  0xffff
ctrlr.c: 492:spdk_nvmf_ctrlr_connect: *DEBUG*:   hostid: 99921c1b-6b5a-4e2b-85b0-32731c140422 ***
ctrlr.c: 509:spdk_nvmf_ctrlr_connect: *DEBUG*:   subnqn: "nqn.2014-08.org.nvmexpress.discovery"
ctrlr.c: 536:spdk_nvmf_ctrlr_connect: *DEBUG*:   hostnqn: "nqn.2016-06.io.spdk:sky02"
ctrlr.c: 595:spdk_nvmf_ctrlr_connect: *DEBUG*: Connect Admin Queue for controller ID 0xffff
ctrlr.c: 350:spdk_nvmf_ctrlr_create: *DEBUG*: cap 0x200101007f
ctrlr.c: 351:spdk_nvmf_ctrlr_create: *DEBUG*: vs 0x10300
ctrlr.c: 352:spdk_nvmf_ctrlr_create: *DEBUG*: cc 0x0
ctrlr.c: 353:spdk_nvmf_ctrlr_create: *DEBUG*: csts 0x0
ctrlr.c: 176:spdk_nvmf_ctrlr_start_keep_alive_timer: *DEBUG*: Ctrlr add keep alive poller
ctrlr.c: 211:ctrlr_add_qpair_and_update_rsp: *DEBUG*: connect capsule response: cntlid = 0x0001
ctrlr.c:2488:spdk_nvmf_request_complete: *DEBUG*: cpl: cid=0 cdw0=0x00000001 rsvd1=0 status=0x0000
rdma.c:3319:_qp_reset_failed_sends: *ERROR*: Failed to post a send for the qpair 0x3a82cb0 with errno -22
ctrlr.c:  88:spdk_nvmf_ctrlr_stop_keep_alive_timer: *DEBUG*: Stop keep alive poller
```
## Expected Behavior
Successful discover and connection

## Current Behavior
Error with log provided above

## Possible Solution
no idea

## Steps to Reproduce
1. On target side use this config am_nvmf.conf.in :
```
[Global]

[Nvmf]
  AcceptorPollRate 10000

[Transport]
  Type RDMA

[Transport]
  Type TCP

[Nvme]
  TransportID "trtype:PCIe traddr:0000:87:00.0" Nvme0
  TransportID "trtype:PCIe traddr:0000:89:00.0" Nvme1
  RetryCount 4
  TimeoutUsec 0
  ActionOnTimeout None
  AdminPollRate 100000
  IOPollRate 0

  HotplugEnable No


[Subsystem1]
  NQN nqn.2016-06.io.spdk:sky02
  Listen RDMA 10.2.2.120:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000001
  MN SPDK_Controller1
  MaxNamespaces 20
  Namespace Nvme0n1 1
  Namespace Nvme1n1 2
```
2. start target 
```./app/spdk_tgt/spdk_tgt -m 0xff -c etc/spdk/am_nvmf.conf.in -L nvmf``` 
3. On host side :
```
nvme discover -t rdma -a 10.2.2.120 -s 4420 -q nqn.2016-06.io.spdk:sky02
```
4. Get the error message

## Context (Environment including OS version, SPDK version, etc.)

1. Centos 7.4 linux kernel 3.10.0-693.21.1
2. SPDK latest (commit d1a96e7cde77f1ba476ef3a96feb720f9a572251)
3. Non-Volatile memory controller: Intel Corporation Device 0a54
4. Fabric controller: Intel Corporation Omni-Path HFI Silicon 100 Series [integrated] (rev 11)

**Comment by darsto** [comment] 2019-06-18 15:44
Bug scrub: Does it fail with RoCE or iWARP? We currently don't have any HW to reproduce this with Omni-Path.

**Comment by alekseymmm** [comment] 2019-06-19 07:57
@darsto I haven't tried RoCE or iWARP since I don't have any experience and knowledge of how to configure them. By the way, I tried linux kernel nvmeof target at this system and it works without any problems.

May be I can collect some more debug info to help investigating this problem ?

**Comment by alekseymmm** [comment] 2019-06-19 08:08
Also I tried SPDK 18.04 commit 9eb54cae6aca7ddefb501fe6e26d125d877d59c9 and it works either.

**Comment by KariukiJ** [comment] 2019-06-19 15:27
fio configuration file
[global]
ioengine=libaio
direct=1
iodepth=64
numjobs=1 # 2, 4,  8, 16
group_reporting
runtime=60s
offset_increment=10G
rw=read
bs=128K

[job1]
filename=/dev/nvme0n1

**Comment by alekseymmm** [comment] 2019-06-19 15:47
Tried capturing trace while doing discovery. May be it could help somehow
```
# ./app/trace/spdk_trace -s spdk_tgt -p 53121
TSC Rate: 2600000000
Trace Size of lcore (0): 32768
 0:      0.000     RDMA_CM_ASYNC_EVENT                   type:  4                
 0:     73.087     RDMA_QP_CREATE                                                object:0x2710370        
 0:     90.732     RDMA_QP_STATE_CHANGE                  state: 0x3              object:0x2710370        
 0:    726.492     RDMA_REQ_NEW                          cmid:  0x2710370        id:    r0               
 0:    726.828     RDMA_REQ_NEED_BUFFER                  cmid:  0x2710370        id:    r0               time:  0.336            
 0:    727.853     RDMA_REQ_TX_PENDING_H2C               cmid:  0x2710370        id:    r0               time:  1.362            
 0:    728.040     RDMA_REQ_TX_H2C                       cmid:  0x2710370        id:    r0               time:  1.548            
 0:    832.236     RDMA_REQ_RDY_TO_EXECUTE               cmid:  0x2710370        id:    r0               time:  105.745          
 0:    895.568     RDMA_REQ_EXECUTING                    cmid:  0x2710370        id:    r0               time:  169.076          
 0:    907.485     RDMA_REQ_EXECUTED                     cmid:  0x2710370        id:    r0               time:  180.993          
 0:    907.565     RDMA_REQ_RDY_TO_COMPL                 cmid:  0x2710370        id:    r0               time:  181.073          
 0:    907.777     RDMA_REQ_COMPLETING                   cmid:  0x2710370        id:    r0               time:  181.285          
 0:    936.836     RDMA_REQ_COMPLETED                    cmid:  0x2710370        id:    r0               time:  210.345          
 0:    942.774     RDMA_QP_STATE_CHANGE                  state: 0x6              object:0x2710370        
 0:   9987.844     RDMA_CM_ASYNC_EVENT                   type:  9                
 0:   9992.308     RDMA_QP_DESTROY                                               object:0x2710370     
```

**Comment by KariukiJ** [comment] 2019-06-19 17:27
@alekseymmm Can you capture a trace while sending I/Os? Can you also share the parameters your using to connect to the target? And the dmesg log showing the device and number of queues?
Thanks.

**Comment by alekseymmm** [comment] 2019-06-20 10:04
@KariukiJ 
I decided to fill issue regarding performance over omnipath here https://github.com/spdk/spdk/issues/835
and leave this bug only about latest spdk and establishing connection problem

**Comment by alekseymmm** [comment] 2019-06-20 11:15
When nvme discover fails I see this message in dmesg :
```
[79855.277274] nvme nvme0: Connect command failed, error wo/DNR bit: 7
```

**Comment by alekseymmm** [comment] 2019-06-20 11:17
> @alekseymmm Can you capture a trace while sending I/Os? Can you also share the parameters your using to connect to the target? And the dmesg log showing the device and number of queues?
> Thanks.

nvme discover fails so no nvme connect performed after. So the information about number of queues is unavailable.

**Comment by Seth5141** [comment] 2019-06-20 15:02
@alekseymmm could you try to discover and connect again on master but include the -Lrdma flag when you launch the target and post the results back? That will give us more information on what might be going wrong. In the meantime, I can think of a couple features that have been added since 18.04 that you might want to look at disabling or modifying to see if they are the culprit here:
1. Send with invalidate - I think that your librdma is probably too old to support this feature, but I am not sure what CentOS7 may have backported. You can however disable it with a compile time flag passed to configure. See configure --help for the actual flag name.
2. Shared receive queue support - this flag can be disabled at runtime when creating the rdma transport. See the rpc help for the exact command.
Note: the target tries to check both of these capabilities with the hardware interface, but we have had issues with both soft-roce and physical interfaces either misreporting or mishandling these features in the past.

**Comment by alekseymmm** [comment] 2019-06-21 09:56
@Seth5141  Here is log when running nvme discover with -L rdma on target
```
rdma.c:2754:spdk_nvmf_process_cm_event: *DEBUG*: Acceptor Event: RDMA_CM_EVENT_CONNECT_REQUEST
rdma.c:1244:nvmf_rdma_connect: *DEBUG*: Connect Recv on fabric intf name hfi1_0, dev_name uverbs0
rdma.c:1248:nvmf_rdma_connect: *DEBUG*: Listen Id was 0x2371540 with verbs 0x237cd50. ListenAddr: 0x2371300
rdma.c:1254:nvmf_rdma_connect: *DEBUG*: Calculating Queue Depth
rdma.c:1260:nvmf_rdma_connect: *DEBUG*: Target Max Queue Depth: 128
rdma.c:1265:nvmf_rdma_connect: *DEBUG*: Local NIC Max Send/Recv Queue Depth: 16383 Max Read/Write Queue Depth: 16
rdma.c:1272:nvmf_rdma_connect: *DEBUG*: Host (Initiator) NIC Max Incoming RDMA R/W operations: 16 Max Outgoing RDMA R/W operations: 0
rdma.c:1281:nvmf_rdma_connect: *DEBUG*: Host Receive Queue Size: 32
rdma.c:1282:nvmf_rdma_connect: *DEBUG*: Host Send Queue Size: 31
rdma.c:1288:nvmf_rdma_connect: *DEBUG*: Final Negotiated Queue Depth: 32 R/W Depth: 16
rdma.c:1007:spdk_nvmf_rdma_qpair_initialize: *DEBUG*: New RDMA Connection: 0x2390430
rdma.c:1194:spdk_nvmf_rdma_event_accept: *DEBUG*: Sent back the accept
rdma.c:1898:spdk_nvmf_rdma_request_process: *DEBUG*: Request 0x7fe29ccc6010 entering state 1
rdma.c:1898:spdk_nvmf_rdma_request_process: *DEBUG*: Request 0x7fe29ccc6010 entering state 2
rdma.c:1772:spdk_nvmf_rdma_request_parse_sgl: *DEBUG*: Request 0x7fe29ccc6010 took 1 buffer/s from central pool
rdma.c:1898:spdk_nvmf_rdma_request_process: *DEBUG*: Request 0x7fe29ccc6010 entering state 3
rdma.c:1898:spdk_nvmf_rdma_request_process: *DEBUG*: Request 0x7fe29ccc6010 entering state 4
rdma.c:1898:spdk_nvmf_rdma_request_process: *DEBUG*: Request 0x7fe29ccc6010 entering state 5
rdma.c:1898:spdk_nvmf_rdma_request_process: *DEBUG*: Request 0x7fe29ccc6010 entering state 6
rdma.c:1898:spdk_nvmf_rdma_request_process: *DEBUG*: Request 0x7fe29ccc6010 entering state 7
rdma.c:1898:spdk_nvmf_rdma_request_process: *DEBUG*: Request 0x7fe29ccc6010 entering state 9
rdma.c:1898:spdk_nvmf_rdma_request_process: *DEBUG*: Request 0x7fe29ccc6010 entering state 11
rdma.c:3319:_qp_reset_failed_sends: *ERROR*: Failed to post a send for the qpair 0x2390430 with errno -22
rdma.c:1898:spdk_nvmf_rdma_request_process: *DEBUG*: Request 0x7fe29ccc6010 entering state 12
rdma.c:1898:spdk_nvmf_rdma_request_process: *DEBUG*: Request 0x7fe29ccc6010 entering state 0
rdma.c: 620:spdk_nvmf_rdma_set_ibv_state: *DEBUG*: IBV QP#0 changed to: IBV_QPS_ERR
rdma.c:2754:spdk_nvmf_process_cm_event: *DEBUG*: Acceptor Event: RDMA_CM_EVENT_ESTABLISHED
rdma.c:2848:spdk_nvmf_process_ib_event: *DEBUG*: Last WQE reached event received for rqpair 0x2390430
```
Here is the versions of libs I have both on target and host
```
# rpm -qa | grep librdma
librdmacm-17.2-3.el7.x86_64
# rpm -qa | grep libibverbs
libibverbs-17.2-3.el7.x86_64
# rpm -qa | grep rdma-core
rdma-core-17.2-3.el7.x86_64
rdma-core-devel-17.2-3.el7.x86_64
```

**Comment by alekseymmm** [comment] 2019-06-21 10:07
@Seth5141  you were right and disabling RDMA_SEND_WITH_INVAL helped.
Although I cannot find proper ./configure flag but run
```
./configure --with-rdma
make clean; make CONFIG_RDMA=y CONFIG_RDMA_SEND_WITH_INVAL=n -j
```
solves this issue and target could be discovered and connected. Thank you.

I still have performance issue described in https://github.com/spdk/spdk/issues/835 but hope this information about establishing connection is helpful.

**Comment by Seth5141** [comment] 2019-06-27 18:36
@alekseymmm Thanks for following up with that. There is a known issue on older kernels. Essentially, there was a mix-up between an enum defining WR opcodes between the kernel and userspace library. The kernel commit in question is 9a59739bd01f77db6fbe2955a4fce165f0f43568.
If I am remembering correctly, there may have also been a couple of issues with in the kernel code related to how different devices were reporting support for send with invalidate.For example, soft-RoCE NICs will claim support for it when they don't. You would have to evaluate that one for your specific device.
I am going to close this since I don't believe that the issue is in SPDK. I believe that we are doing the right checks to make sure that sent with invalidate is supported.
I would recommend doing a couple of checks with your device to make sure that send with invalidate is working properly:
1. Try a more modern kernel (Something released after September 2018) with the send-with-invalidate command enabled and see if it works. My assumption is that you will find that this works since kernel-kernel works today.
2. If it still doesn't, dig into the kernel code for your device and look at the device_cap_flags reported by your NIC.

I encourage you to reopen this bug if you can't get send_with_invalidate working on a later kernel version with your device.

Thanks,

Seth

**Closed by Seth5141** 2019-06-27 18:36 UTC
Labels: help wanted

**Comment by KariukiJ** [comment] 2019-07-23 22:58
@alekseymmm I finally got access to a host and target system with OPA NICS. However, the system does not have an NVMe SSD. Thanks for reporting the DNR issue, I ran into that and used the recommendation above from @Seth5141 to resolve it. I will now switch to issue 835 to talk about performance.
