### ISSUE TITLE
NVMe-oF shutdown tc3 nvme_transport_admin_qpair_abort_aers() assert

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1200] opened 2020-02-12 09:22 UTC
Assert `bdevperf: nvme_transport.c:334: nvme_transport_admin_qpair_abort_aers: Assertion 'transport != NULL' failed.` is triggered on nvmf_shutdown_tc3 when using tcp transport.

As seen in log https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/60365/archive/nvmf_tcp_autotest/build.log
``` bash
task offset: 65792 on target bdev=Nvme6n1 fails
nvme_ctrlr.c:1094:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
posix.c: 358:spdk_posix_sock_create: *ERROR*: connect() failed, errno = 111
nvme_tcp.c:1529:nvme_tcp_ctrlr_connect_qpair: *ERROR*: sock connection error of tqpair=0x246dfd0 with addr=127.0.0.1, port=4420
nvme_ctrlr.c:1116:spdk_nvme_ctrlr_reset: *ERROR*: Controller reinitialization failed.
nvme_ctrlr.c: 699:nvme_ctrlr_fail: *ERROR*: ctrlr 127.0.0.1 in failed state.
bdev_nvme.c: 326:_bdev_nvme_reset_complete: *ERROR*: Resetting controller failed.
nvme_ctrlr.c:1094:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
posix.c: 358:spdk_posix_sock_create: *ERROR*: connect() failed, errno = 111
nvme_tcp.c:1529:nvme_tcp_ctrlr_connect_qpair: *ERROR*: sock connection error of tqpair=0x24bb150 with addr=127.0.0.1, port=4420
nvme_ctrlr.c:1116:spdk_nvme_ctrlr_reset: *ERROR*: Controller reinitialization failed.
nvme_ctrlr.c: 699:nvme_ctrlr_fail: *ERROR*: ctrlr 127.0.0.1 in failed state.
bdev_nvme.c: 326:_bdev_nvme_reset_complete: *ERROR*: Resetting controller failed.
nvme_ctrlr.c:1094:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
posix.c: 358:spdk_posix_sock_create: *ERROR*: connect() failed, errno = 111
nvme_tcp.c:1529:nvme_tcp_ctrlr_connect_qpair: *ERROR*: sock connection error of tqpair=0x2420e50 with addr=127.0.0.1, port=4420
nvme_ctrlr.c:1116:spdk_nvme_ctrlr_reset: *ERROR*: Controller reinitialization failed.
nvme_ctrlr.c: 699:nvme_ctrlr_fail: *ERROR*: ctrlr 127.0.0.1 in failed state.
bdev_nvme.c: 326:_bdev_nvme_reset_complete: *ERROR*: Resetting controller failed.
app.c: 712:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
nvme_ctrlr.c: 728:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
nvme_ctrlr.c: 728:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
nvme_ctrlr.c: 728:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
nvme_ctrlr.c: 728:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
nvme_ctrlr.c: 728:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
nvme_ctrlr.c: 728:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
nvme_ctrlr.c: 728:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
nvme_ctrlr.c: 728:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
nvme_ctrlr.c: 728:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
nvme_ctrlr.c: 728:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
nvme_ctrlr.c:1094:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
bdevperf: nvme_transport.c:334: nvme_transport_admin_qpair_abort_aers: Assertion `transport != NULL' failed.
test/nvmf/target/shutdown.sh: line 81: 37492 Aborted                 (core dumped) $rootdir/test/bdev/bdevperf/bdevperf -r /var/tmp/bdevperf.sock -c $testdir/bdevperf.conf -q 64 -o 65536 -w verify -t 10
 12:37:35	# kill -9 37492
test/nvmf/target/shutdown.sh: line 101: kill: (37492) - No such process
 12:37:35	# true
```

Further test are executed because of nvmf_shutdown_tc3 ignoring failure when killing the initiator. Job failed only due to generated core dump.
``` bash
# TODO: Right now the NVMe-oF initiator will not correctly detect broken connections
# and so it will never shut down. Just kill it.
kill -9 $perfpid || true
```

**Comment by spdkci** [comment] 2020-02-12 09:23
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60365.html

**Comment by changpe1** [comment] 2020-02-17 02:27
@optimistyzy Can you take a look of this issue? Thanks.

**Comment by optimistyzy** [comment] 2020-02-17 05:37
I did not see suspicious code in NVMe tcp layer, so propose this patch to avoid this issue: https://review.spdk.io/gerrit/c/spdk/spdk/+/918. Would like to let Seth get a look since he implemented the reset feature for NVMe-oF in 20.01.  @Seth5141

**Comment by optimistyzy** [comment] 2020-02-24 00:24
@tomzawadzki @shuhei-matsumoto I see this issue happened 12 days ago, actually, I cannot reproduce the assert issue on my platform. Did it happen during the refactoring of bdevperf (@shuhei-matsumoto)?

**Comment by optimistyzy** [comment] 2020-02-24 00:53
More analysis:
"bdev_nvme.c: 326:_bdev_nvme_reset_complete: *ERROR*: Resetting controller failed.
app.c: 712:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero"
We can see this time: spdk_app_stop is already called. And in the attached log: spdk_bdev_module_finish_done is called. So it means that the program is in existing phase. So this is why I ask that there are some issues related with bdevperf during refactoring.

**Comment by shuhei-matsumoto** [comment] 2020-02-24 05:46
@optimistyzy I have seen https://github.com/spdk/spdk/issues/1210 but have not seen this yet.

**Comment by tomzawadzki** [comment] 2020-02-25 15:20
[Bug scrub] @Seth5141 confirms this does not look related to #1210. Besides that the original occurrence wasn't within Shuhei's bdevperf refactor.

**Comment by optimistyzy** [comment] 2020-03-10 07:56
@tomzawadzki @shuhei-matsumoto Do we see this assert again in the test pool? I tried my best to reproduce this issue on my local platform, but I did not see the same assert genenerated. So I would like to ask you whether you see this issue again in our CI system.

**Comment by optimistyzy** [comment] 2020-03-11 02:50
Keep watching this issue, the last error happened more than 20 days ago, if the same assert issue does not happen in one week, I will close this issue. @tomzawadzki  @changpe1 @shuhei-matsumoto

**Comment by optimistyzy** [comment] 2020-03-18 05:44
close this issue, it seems that we did not see this issue happen again @tomzawadzki @changpe1 @shuhei-matsumoto . If we see this issue again, Let's reopen this issue again.

**Closed by optimistyzy** 2020-03-18 05:44 UTC
Labels: Bug Scrub, Intermittent Failure
