### ISSUE TITLE
[nvmf_timeout] wait for the ctrlr_loss_timeout_sec time and check controller failed

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#2864] opened 2023-01-12 05:24 UTC
# CI Intermittent Failure

```
00:16:59.493  ************************************
00:16:59.493  START TEST nvmf_timeout
00:16:59.493  ************************************
```

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/94789/archive/nvmf-tcp-vg-autotest/build.log

## Execution failed at

```
00:17:21.418  ========== Backtrace start: ==========
00:17:21.418  
00:17:21.418  in /home/vagrant/spdk_repo/spdk/test/nvmf/host/timeout.sh:61 -> main(["--transport=tcp"])
00:17:21.418       ...
00:17:21.418     56  	[[ "$(get_controller)" == "NVMe0" ]]
00:17:21.418     57  	[[ "$(get_bdev)" == "NVMe0n1" ]]
00:17:21.418     58  	
00:17:21.418     59  	# wait for the ctrlr_loss_timeout_sec time 10 sec and check bdevs and controller are deleted
00:17:21.418     60  	sleep 10
00:17:21.418  => 61  	[[ "$(get_controller)" == "" ]]
00:17:21.418     62  	[[ "$(get_bdev)" == "" ]]
00:17:21.418     63  	
00:17:21.418     64  	wait $rpc_pid
00:17:21.418     65  	
00:17:21.418     66  	killprocess $bdevperf_pid
00:17:21.418       ...
```

```
00:17:23.135  in /home/vagrant/spdk_repo/spdk/test/nvmf/nvmf.sh:97 -> main(["--transport=tcp"])
00:17:23.135       ...
00:17:23.135     92  	# TODO: disabled due to intermittent failures (RDMA_CM_EVENT_UNREACHABLE/ETIMEDOUT)
00:17:23.135     93  	#run_test $rootdir/test/nvmf/host/identify_kernel_nvmf.sh $TEST_ARGS
00:17:23.135     94  	
00:17:23.135     95  	if [[ $SPDK_TEST_USDT -eq 1 ]]; then
00:17:23.135     96  		run_test "nvmf_multipath" $rootdir/test/nvmf/host/multipath.sh "${TEST_ARGS[@]}"
00:17:23.135  => 97  		run_test "nvmf_timeout" $rootdir/test/nvmf/host/timeout.sh "${TEST_ARGS[@]}"
```

**Comment by spdkci** [comment] 2023-01-12 05:26
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_94789.html

**Comment by spdkci** [comment] 2023-01-12 14:27
Another instance of this failure. Reported by @sberbz. log: https://ci.spdk.io/public_build/autotest-per-patch_95028.html

**Comment by spdkci** [comment] 2023-01-13 00:38
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_94844.html

**Comment by spdkci** [comment] 2023-01-13 00:52
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_94872.html

**Comment by spdkci** [comment] 2023-01-15 13:27
Another instance of this failure. Reported by @richael02. log: https://ci.spdk.io/public_build/autotest-per-patch_95443.html

**Comment by spdkci** [comment] 2023-01-16 08:27
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_95423.html

**Comment by spdkci** [comment] 2023-01-16 12:21
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_95482.html

**Comment by spdkci** [comment] 2023-01-17 15:17
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_95701.html

**Comment by spdkci** [comment] 2023-01-19 08:04
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_96058.html

**Comment by spdkci** [comment] 2023-01-19 08:27
Another instance of this failure. Reported by @sberbz. log: https://ci.spdk.io/public_build/autotest-per-patch_96044.html

**Comment by spdkci** [comment] 2023-01-20 09:44
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_96291.html

**Comment by spdkci** [comment] 2023-01-20 12:32
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_96330.html

**Comment by spdkci** [comment] 2023-01-26 14:50
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_97060.html

**Comment by spdkci** [comment] 2023-01-30 11:14
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_97283.html

**Comment by spdkci** [comment] 2023-01-31 06:45
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_97604.html

**Comment by spdkci** [comment] 2023-02-02 02:39
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_97797.html

**Comment by spdkci** [comment] 2023-02-07 19:13
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_98144.html

**Comment by spdkci** [comment] 2023-02-09 23:03
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_98343.html

**Comment by spdkci** [comment] 2023-02-09 23:30
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_98350.html

**Comment by spdkci** [comment] 2023-02-14 13:51
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_98487.html

**Comment by spdkci** [comment] 2023-02-15 06:38
Another instance of this failure. Reported by @richael02. log: https://ci.spdk.io/public_build/autotest-per-patch_98555.html

**Comment by spdkci** [comment] 2023-02-18 16:04
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_98832.html

**Comment by spdkci** [comment] 2023-02-20 15:39
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_98857.html

**Comment by spdkci** [comment] 2023-02-22 11:46
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_98965.html

**Comment by spdkci** [comment] 2023-02-22 15:05
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_98989.html

**Comment by spdkci** [comment] 2023-02-27 08:53
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_99032.html

**Comment by spdkci** [comment] 2023-02-27 09:36
Another instance of this failure. Reported by @jlevon. log: https://ci.spdk.io/public_build/autotest-per-patch_98433.html

**Comment by spdkci** [comment] 2023-02-27 11:39
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_99216.html

**Comment by spdkci** [comment] 2023-02-28 12:16
Another instance of this failure. Reported by @swapnili. log: https://ci.spdk.io/public_build/autotest-per-patch_99319.html

**Comment by spdkci** [comment] 2023-03-09 16:01
Another instance of this failure. Reported by @sberbz. log: https://ci.spdk.io/public_build/autotest-per-patch_99887.html

**Comment by spdkci** [comment] 2023-03-09 17:57
Another instance of this failure. Reported by @sberbz. log: https://ci.spdk.io/public_build/autotest-per-patch_99901.html

**Comment by ksztyber** [comment] 2023-04-04 15:27
[Bug scrub] It seems that this issue has stopped occurring after adding extra debug logs. Closing until it reappears again.

**Comment by spdkci** [comment] 2023-04-19 10:42
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_102104.html

**Comment by KKaras169169** [comment] 2023-04-19 10:43
Hit this issue again today.

**Comment by spdkci** [comment] 2023-04-20 08:11
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_102139.html

**Comment by spdkci** [comment] 2023-04-20 12:29
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_102241.html

**Comment by spdkci** [comment] 2023-04-22 15:23
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_102402.html

**Comment by spdkci** [comment] 2023-04-24 11:32
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_102328.html

**Comment by ksztyber** [comment] 2023-04-25 15:28
[Bug scrub] Let's try to replace the sleep with a while loop checking if the controller is removed. @sberbz suggests that this might be a timeout issue, so if that's the case this should fix it.

**Comment by jimharris** [comment] 2023-04-26 20:05
This is almost certainly same root cause as described in #2865.

**Comment by jimharris** [comment] 2023-04-27 14:53
Patch merged.

**Closed by jimharris** 2023-04-27 14:53 UTC
Labels: Intermittent Failure

**Comment by spdkci** [comment] 2024-04-19 06:05
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_120610.html
