### ISSUE TITLE
SPDK bdev RPC will failed to bind 5th PCIE NVMe if run six device within one RPC scripts 

### ISSUE THREAD

**Issue by gwnet** [spdk/spdk#1431] opened 2020-06-04 12:36 UTC
## Expected Behavior
I run RPC scripts to add NVMe device and OCF device, SPDK will failed to find nvme device that does exist.
if we run RPC directly on that device, there is no problem. just has issue if it is the 5th device to be scanned.

## Current Behavior

====run this scripts==
echo nvme0n1
time scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t PCIe -a 0000:5e:00.0
time scripts/rpc.py bdev_malloc_create -b Malloc0 200 4096
time scripts/rpc.py bdev_ocf_create Cache1 wt Malloc0 Nvme0n1

echo nvme1n1
time scripts/rpc.py bdev_nvme_attach_controller -b Nvme1 -t PCIe -a 0000:5f:00.0
time scripts/rpc.py bdev_malloc_create -b Malloc1 200 4096
time scripts/rpc.py bdev_ocf_create Cache2 wt Malloc1 Nvme1n1

echo nvme2n1
time scripts/rpc.py bdev_nvme_attach_controller -b Nvme2 -t PCIe -a 0000:af:00.0
time scripts/rpc.py bdev_malloc_create -b Malloc2 200 4096
time scripts/rpc.py bdev_ocf_create Cache3 wt Malloc2 Nvme2n1

echo nvme3n1
time scripts/rpc.py bdev_nvme_attach_controller -b Nvme3 -t PCIe -a 0000:b0:00.0
time scripts/rpc.py bdev_malloc_create -b Malloc3 200 4096
time scripts/rpc.py bdev_ocf_create Cache4 wt Malloc3 Nvme3n1

echo nvme4n1
time scripts/rpc.py bdev_nvme_attach_controller -b Nvme4 -t PCIe -a 0000:b1:00.0
time scripts/rpc.py bdev_malloc_create -b Malloc4 200 4096
time scripts/rpc.py bdev_ocf_create Cache5 wt Malloc4 Nvme4n1

echo nvme5n1
time scripts/rpc.py bdev_nvme_attach_controller -b Nvme5 -t PCIe -a 0000:b2:00.0
time scripts/rpc.py bdev_malloc_create -b Malloc5 200 4096
time scripts/rpc.py bdev_ocf_create Cache6 wt Malloc5 Nvme5n1
===then SPDK server report there is no device===
intel@intel:~/wayne/spdk$ sudo app/spdk_tgt/spdk_tgt
Starting SPDK v20.04.1 git sha1 c5f0959de / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid120953 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
app.c: 646:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 371:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
vbdev_ocf.c:1535:examine_ctx_put: *ERROR*: OCF metadata probe for bdev 'Nvme0n1' failed with -1000006
Inserting cache Cache1
Cache1: Successfully added
Cache1: Cache mode : wt
Cache1: Super block config offset : 0 kiB
Cache1: Super block config size : 2196 B
Cache1: Super block runtime offset : 128 kiB
Cache1: Super block runtime size : 4 B
Cache1: Reserved offset : 256 kiB
Cache1: Reserved size : 128 kiB
Cache1: Part config offset : 384 kiB
Cache1: Part config size : 48 kiB
Cache1: Part runtime offset : 512 kiB
Cache1: Part runtime size : 4 kiB
Cache1: Core config offset : 640 kiB
Cache1: Core config size : 484 kiB
Cache1: Core runtime offset : 1152 kiB
Cache1: Core runtime size : 1172 kiB
Cache1: Core UUID offset : 2432 kiB
Cache1: Core UUID size : 16384 kiB
Cache1: Cleaning offset : 18816 kiB
Cache1: Cleaning size : 540 kiB
Cache1: Eviction offset : 19456 kiB
Cache1: Eviction size : 360 kiB
Cache1: Collision offset : 19840 kiB
Cache1: Collision size : 540 kiB
Cache1: List info offset : 20480 kiB
Cache1: List info size : 768 kiB
Cache1: Hash offset : 21248 kiB
Cache1: Hash size : 48 kiB
Cache1: Cache line size: 4 kiB
Cache1: Metadata capacity: 20 MiB
Cache1: OCF metadata self-test PASSED
Cache1: Policy 'always' initialized successfully
Cache1: Done saving cache state!
Cache1: Successfully attached
Cache1.Nvme0n1: Successfully added
vbdev_ocf.c:1535:examine_ctx_put: *ERROR*: OCF metadata probe for bdev 'Cache1' failed with -1000006
Inserting cache Cache2
Cache2: Successfully added
Cache2: Cache mode : wt
Cache2: Super block config offset : 0 kiB
Cache2: Super block config size : 2196 B
Cache2: Super block runtime offset : 128 kiB
Cache2: Super block runtime size : 4 B
Cache2: Reserved offset : 256 kiB
Cache2: Reserved size : 128 kiB
Cache2: Part config offset : 384 kiB
Cache2: Part config size : 48 kiB
Cache2: Part runtime offset : 512 kiB
Cache2: Part runtime size : 4 kiB
Cache2: Core config offset : 640 kiB
Cache2: Core config size : 484 kiB
Cache2: Core runtime offset : 1152 kiB
Cache2: Core runtime size : 1172 kiB
Cache2: Core UUID offset : 2432 kiB
Cache2: Core UUID size : 16384 kiB
Cache2: Cleaning offset : 18816 kiB
Cache2: Cleaning size : 540 kiB
Cache2: Eviction offset : 19456 kiB
Cache2: Eviction size : 360 kiB
Cache2: Collision offset : 19840 kiB
Cache2: Collision size : 540 kiB
Cache2: List info offset : 20480 kiB
Cache2: List info size : 768 kiB
Cache2: Hash offset : 21248 kiB
Cache2: Hash size : 48 kiB
Cache2: Cache line size: 4 kiB
Cache2: Metadata capacity: 20 MiB
Cache2: OCF metadata self-test PASSED
Cache2: Policy 'always' initialized successfully
Cache2: Done saving cache state!
Cache2: Successfully attached
Cache2.Nvme1n1: Successfully added
Inserting cache Cache3
Cache3: Successfully added
Cache3: Cache mode : wt
Cache3: Super block config offset : 0 kiB
Cache3: Super block config size : 2196 B
Cache3: Super block runtime offset : 128 kiB
Cache3: Super block runtime size : 4 B
Cache3: Reserved offset : 256 kiB
Cache3: Reserved size : 128 kiB
Cache3: Part config offset : 384 kiB
Cache3: Part config size : 48 kiB
Cache3: Part runtime offset : 512 kiB
Cache3: Part runtime size : 4 kiB
Cache3: Core config offset : 640 kiB
Cache3: Core config size : 484 kiB
Cache3: Core runtime offset : 1152 kiB
Cache3: Core runtime size : 1172 kiB
Cache3: Core UUID offset : 2432 kiB
Cache3: Core UUID size : 16384 kiB
Cache3: Cleaning offset : 18816 kiB
Cache3: Cleaning size : 540 kiB
Cache3: Eviction offset : 19456 kiB
Cache3: Eviction size : 360 kiB
Cache3: Collision offset : 19840 kiB
Cache3: Collision size : 540 kiB
Cache3: List info offset : 20480 kiB
Cache3: List info size : 768 kiB
Cache3: Hash offset : 21248 kiB
Cache3: Hash size : 48 kiB
Cache3: Cache line size: 4 kiB
Cache3: Metadata capacity: 20 MiB
Cache3: OCF metadata self-test PASSED
Cache3: Policy 'always' initialized successfully
Cache3: Done saving cache state!
Cache3: Successfully attached
Cache3.Nvme2n1: Successfully added
Inserting cache Cache4
Cache4: Successfully added
Cache4: Cache mode : wt
Cache4: Super block config offset : 0 kiB
Cache4: Super block config size : 2196 B
Cache4: Super block runtime offset : 128 kiB
Cache4: Super block runtime size : 4 B
Cache4: Reserved offset : 256 kiB
Cache4: Reserved size : 128 kiB
Cache4: Part config offset : 384 kiB
Cache4: Part config size : 48 kiB
Cache4: Part runtime offset : 512 kiB
Cache4: Part runtime size : 4 kiB
Cache4: Core config offset : 640 kiB
Cache4: Core config size : 484 kiB
Cache4: Core runtime offset : 1152 kiB
Cache4: Core runtime size : 1172 kiB
Cache4: Core UUID offset : 2432 kiB
Cache4: Core UUID size : 16384 kiB
Cache4: Cleaning offset : 18816 kiB
Cache4: Cleaning size : 540 kiB
Cache4: Eviction offset : 19456 kiB
Cache4: Eviction size : 360 kiB
Cache4: Collision offset : 19840 kiB
Cache4: Collision size : 540 kiB
Cache4: List info offset : 20480 kiB
Cache4: List info size : 768 kiB
Cache4: Hash offset : 21248 kiB
Cache4: Hash size : 48 kiB
Cache4: Cache line size: 4 kiB
Cache4: Metadata capacity: 20 MiB
Cache4: OCF metadata self-test PASSED
Cache4: Policy 'always' initialized successfully
Cache4: Done saving cache state!
Cache4: Successfully attached
Cache4.Nvme3n1: Successfully added
nvme_pcie.c:1090:nvme_pcie_qpair_construct: *ERROR*: alloc qpair_cmd failed
nvme.c: 465:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD: 0000:b1:00.0
EAL: Driver cannot attach the device (0000:b1:00.0)
EAL: Failed to attach device on primary process
nvme.c: 609:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
bdev_nvme.c:1765:spdk_bdev_nvme_create: *ERROR*: No controller was found with provided trid (traddr: 0000:b1:00.0)
bdev_malloc.c: 420:create_malloc_disk: *ERROR*: malloc_buf spdk_zmalloc() failed
vbdev_ocf.c:1458:vbdev_ocf_construct: *NOTICE*: OCF bdev 'Cache5' is waiting for cache device 'Malloc4' to connect
vbdev_ocf.c:1462:vbdev_ocf_construct: *NOTICE*: OCF bdev 'Cache5' is waiting for core device 'Nvme4n1' to connect
nvme_pcie.c:1090:nvme_pcie_qpair_construct: *ERROR*: alloc qpair_cmd failed
nvme.c: 465:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD: 0000:b2:00.0
EAL: Driver cannot attach the device (0000:b2:00.0)
EAL: Failed to attach device on primary process
nvme.c: 609:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
bdev_nvme.c:1765:spdk_bdev_nvme_create: *ERROR*: No controller was found with provided trid (traddr: 0000:b2:00.0)
bdev_malloc.c: 420:create_malloc_disk: *ERROR*: malloc_buf spdk_zmalloc() failed
vbdev_ocf.c:1458:vbdev_ocf_construct: *NOTICE*: OCF bdev 'Cache6' is waiting for cache device 'Malloc5' to connect
vbdev_ocf.c:1462:vbdev_ocf_construct: *NOTICE*: OCF bdev 'Cache6' is waiting for core device 'Nvme5n1' to connect
=======
=====if I run the 0000:b1:00::00 device separately, it does not show any issue====
 time scripts/rpc.py bdev_nvme_attach_controller -b Nvme4 -t PCIe -a 0000:b1:00.0
time scripts/rpc.py bdev_malloc_create -b Malloc4 200 4096
time scripts/rpc.py bdev_ocf_create Cache5 wt Malloc4 Nvme4n1
====the app log is below===
intel@intel:~/wayne/spdk$ sudo app/spdk_tgt/spdk_tgt
Starting SPDK v20.04.1 git sha1 c5f0959de / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid120997 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
app.c: 646:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 371:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
Inserting cache Cache5
Cache5: Successfully added
Cache5: Cache mode : wt
Cache5: Super block config offset : 0 kiB
Cache5: Super block config size : 2196 B
Cache5: Super block runtime offset : 128 kiB
Cache5: Super block runtime size : 4 B
Cache5: Reserved offset : 256 kiB
Cache5: Reserved size : 128 kiB
Cache5: Part config offset : 384 kiB
Cache5: Part config size : 48 kiB
Cache5: Part runtime offset : 512 kiB
Cache5: Part runtime size : 4 kiB
Cache5: Core config offset : 640 kiB
Cache5: Core config size : 484 kiB
Cache5: Core runtime offset : 1152 kiB
Cache5: Core runtime size : 1172 kiB
Cache5: Core UUID offset : 2432 kiB
Cache5: Core UUID size : 16384 kiB
Cache5: Cleaning offset : 18816 kiB
Cache5: Cleaning size : 540 kiB
Cache5: Eviction offset : 19456 kiB
Cache5: Eviction size : 360 kiB
Cache5: Collision offset : 19840 kiB
Cache5: Collision size : 540 kiB
Cache5: List info offset : 20480 kiB
Cache5: List info size : 768 kiB
Cache5: Hash offset : 21248 kiB
Cache5: Hash size : 48 kiB
Cache5: Cache line size: 4 kiB
Cache5: Metadata capacity: 20 MiB
Cache5: OCF metadata self-test PASSED
Cache5: Policy 'always' initialized successfully
Cache5: Done saving cache state!
Cache5: Successfully attached
Cache5.Nvme4n1: Successfully added

## Steps to Reproduce

checks above, need 6 nvme devices to reproduce this
1.
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)
OS is ubuntu 12.04, SPDK 20.04.1 release version

**Comment by tomzawadzki** [comment] 2020-06-04 14:39
Hi @gwnet 

```
bdev_malloc.c: 420:create_malloc_disk: ERROR: malloc_buf spdk_zmalloc() failed
```
Above suggests that it was not possible to allocate enough memory for malloc bdev.
From what I recall OCF takes bit more memory during the examine/initialization period. Since on initialization all of happens at once, it might be related.

How many Hugepages have you reserved (`HUGEMEM=x ./scripts/setup.sh`) ?
Did you try increasing this number ?

**Comment by gwnet** [comment] 2020-06-05 01:24
@tomzawadzki thank you so much man. it works. 
HugePages_Total:   20000
HugePages_Free:    18733
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:        40960000 kB
DirectMap4k:     1103220 kB
DirectMap2M:    32149504 kB
DirectMap1G:    168820736 kB

**Comment by gwnet** [comment] 2020-06-05 03:35
@tomzawadzki now I use scripts to create ocf. I use one nvme0n1 vbdevs as cache device. I split nvme0n1 into 10. for the core device, I use Malloc. 
===before I run my scripts to create OCF, I check there is no bdev in the system.
intel@intel:~/wayne/spdk$ sudo scripts/rpc.py bdev_ocf_get_bdevs
[]
intel@intel:~/wayne/spdk$ sudo scripts/rpc.py bdev_get_bdevs
[]
intel@intel:~/wayne/spdk$ 
==then I run through below scripts===
date -R --debug
echo split nvme5n1
time scripts/rpc.py bdev_nvme_attach_controller -b Nvme5 -t PCIe -a 0000:b2:00.0
time scripts/rpc.py bdev_split_create  Nvme5n1 10


echo OCF malloc0
date -R --debug
time scripts/rpc.py bdev_malloc_create -b Malloc0 200 4096
scripts/rpc.py bdev_ocf_create Cache1 wt Nvme5n1p0 Malloc0
date -R --debug
echo OCF done 

echo OCF malloc1
date -R --debug
time scripts/rpc.py bdev_malloc_create -b Malloc1 200 4096
scripts/rpc.py bdev_ocf_create Cache2 wt Nvme5n1p1 Malloc1
date -R --debug
echo OCF done 

echo OCF malloc2
date -R --debug
time scripts/rpc.py bdev_malloc_create -b Malloc2 200 4096
scripts/rpc.py bdev_ocf_create Cache3 wt Nvme5n1p2 Malloc2
date -R --debug
echo OCF done 

echo OCF malloc3
date -R --debug
time scripts/rpc.py bdev_malloc_create -b Malloc3 200 4096
scripts/rpc.py bdev_ocf_create Cache4 wt Nvme5n1p3 Malloc3
date -R --debug
echo OCF done 

echo OCF malloc4
date -R --debug
time scripts/rpc.py bdev_malloc_create -b Malloc4 200 4096
scripts/rpc.py bdev_ocf_create Cache5 wt Nvme5n1p4 Malloc4
date -R --debug
echo OCF done 

echo OCF malloc5
date -R --debug
time scripts/rpc.py bdev_malloc_create -b Malloc5 200 4096
scripts/rpc.py bdev_ocf_create Cache6 wt Nvme5n1p5 Malloc5
date -R --debug
echo OCF done 

echo OCF malloc6
date -R --debug
time scripts/rpc.py bdev_malloc_create -b Malloc6 200 4096
scripts/rpc.py bdev_ocf_create Cache7 wt Nvme5n1p6 Malloc6
date -R --debug
echo OCF done 

echo OCF malloc7
date -R --debug
time scripts/rpc.py bdev_malloc_create -b Malloc7 200 4096
scripts/rpc.py bdev_ocf_create Cache8 wt Nvme5n1p7 Malloc7
date -R --debug
echo OCF done 

echo OCF malloc8
date -R --debug
time scripts/rpc.py bdev_malloc_create -b Malloc8 200 4096
scripts/rpc.py bdev_ocf_create Cache9 wt Nvme5n1p8 Malloc8
date -R --debug
echo OCF done 

echo OCF malloc9
date -R --debug
time scripts/rpc.py bdev_malloc_create -b Malloc9 200 4096
scripts/rpc.py bdev_ocf_create Cache10 wt Nvme5n1p9 Malloc9
date -R --debug
echo OCF done 

===then I suffer this log===why it think Cache2 Cahce3 is already exist?
intel@intel:~/wayne/spdk$ sudo app/spdk_tgt/spdk_tgt
Starting SPDK v20.04.1 git sha1 c5f0959de / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid124454 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
app.c: 646:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 371:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
vbdev_ocf.c:1594:metadata_probe_cores_construct: *NOTICE*: OCF metadata found on Nvme5n1 belongs to bdev named 'Nvme5n1p0'
vbdev_ocf.c:1458:vbdev_ocf_construct: *NOTICE*: OCF bdev 'Cache1' is waiting for cache device 'Nvme5n1p0' to connect
vbdev_ocf.c:1462:vbdev_ocf_construct: *NOTICE*: OCF bdev 'Cache1' is waiting for core device 'Malloc0' to connect
vbdev_ocf.c:1462:vbdev_ocf_construct: *NOTICE*: OCF bdev 'Cache2' is waiting for core device 'Malloc1' to connect
vbdev_ocf.c:1462:vbdev_ocf_construct: *NOTICE*: OCF bdev 'Cache3' is waiting for core device 'Malloc2' to connect
Inserting cache Cache1
Cache1: Successfully added
Cache1: Cache mode : wt
Cache1: Super block config offset : 0 kiB
Cache1: Super block config size : 2196 B
Cache1: Super block runtime offset : 128 kiB
Cache1: Super block runtime size : 4 B
Cache1: Reserved offset : 256 kiB
Cache1: Reserved size : 128 kiB
Cache1: Part config offset : 384 kiB
Cache1: Part config size : 48 kiB
Cache1: Part runtime offset : 512 kiB
Cache1: Part runtime size : 4 kiB
Cache1: Core config offset : 640 kiB
Cache1: Core config size : 484 kiB
Cache1: Core runtime offset : 1152 kiB
Cache1: Core runtime size : 1172 kiB
Cache1: Core UUID offset : 2432 kiB
Cache1: Core UUID size : 16384 kiB
Cache1: Cleaning offset : 18816 kiB
Cache1: Cleaning size : 2173212 kiB
Cache1: Eviction offset : 2192128 kiB
Cache1: Eviction size : 1447396 kiB
Cache1: Collision offset : 3639552 kiB
Cache1: Collision size : 2173212 kiB
Cache1: List info offset : 5812864 kiB
Cache1: List info size : 3087772 kiB
Cache1: Hash offset : 8900736 kiB
Cache1: Hash size : 180928 kiB
Cache1: Cache line size: 4 kiB
Cache1: Metadata capacity: 9574 MiB
Cache1: OCF metadata self-test PASSED
vbdev_ocf.c:1189:init_vbdev: *ERROR*: Device with name 'Cache1' already exists
Cache1: Loading cache state...
Cache1: Policy 'always' initialized successfully
Cache1: Cannot find core 1 in pool, core added as inactive
Inserting cache Cache2
Cache2: Successfully added
Cache2: Cache mode : wt
Cache2: Super block config offset : 0 kiB
Cache2: Super block config size : 2196 B
Cache2: Super block runtime offset : 128 kiB
Cache2: Super block runtime size : 4 B
Cache2: Reserved offset : 256 kiB
Cache2: Reserved size : 128 kiB
Cache2: Part config offset : 384 kiB
Cache2: Part config size : 48 kiB
Cache2: Part runtime offset : 512 kiB
Cache2: Part runtime size : 4 kiB
Cache2: Core config offset : 640 kiB
Cache2: Core config size : 484 kiB
Cache2: Core runtime offset : 1152 kiB
Cache2: Core runtime size : 1172 kiB
Cache2: Core UUID offset : 2432 kiB
Cache2: Core UUID size : 16384 kiB
Cache2: Cleaning offset : 18816 kiB
Cache2: Cleaning size : 2173212 kiB
Cache2: Eviction offset : 2192128 kiB
Cache2: Eviction size : 1447396 kiB
Cache2: Collision offset : 3639552 kiB
Cache2: Collision size : 2173212 kiB
Cache2: List info offset : 5812864 kiB
Cache2: List info size : 3087772 kiB
Cache2: Hash offset : 8900736 kiB
Cache2: Hash size : 180928 kiB
Cache2: Cache line size: 4 kiB
Cache2: Metadata capacity: 9574 MiB
Cache2: OCF metadata self-test PASSED
vbdev_ocf.c:1189:init_vbdev: *ERROR*: Device with name 'Cache2' already exists
Cache2: Loading cache state...
Inserting cache Cache3
Cache3: Successfully added
Cache3: Cache mode : wt
Cache3: Super block config offset : 0 kiB
Cache3: Super block config size : 2196 B
Cache3: Super block runtime offset : 128 kiB
Cache3: Super block runtime size : 4 B
Cache3: Reserved offset : 256 kiB
Cache3: Reserved size : 128 kiB
Cache3: Part config offset : 384 kiB
Cache3: Part config size : 48 kiB
Cache3: Part runtime offset : 512 kiB
Cache3: Part runtime size : 4 kiB
Cache3: Core config offset : 640 kiB
Cache3: Core config size : 484 kiB
Cache3: Core runtime offset : 1152 kiB
Cache3: Core runtime size : 1172 kiB
Cache3: Core UUID offset : 2432 kiB
Cache3: Core UUID size : 16384 kiB
Cache3: Cleaning offset : 18816 kiB
Cache3: Cleaning size : 2173212 kiB
Cache3: Eviction offset : 2192128 kiB
Cache3: Eviction size : 1447396 kiB
Cache3: Collision offset : 3639552 kiB
Cache3: Collision size : 2173212 kiB
Cache3: List info offset : 5812864 kiB
Cache3: List info size : 3087772 kiB
Cache3: Hash offset : 8900736 kiB
Cache3: Hash size : 180928 kiB
Cache3: Cache line size: 4 kiB
Cache3: Metadata capacity: 9574 MiB
Cache3: OCF metadata self-test PASSED
vbdev_ocf.c:1189:init_vbdev: *ERROR*: Device with name 'Cache3' already exists
Cache3: Loading cache state...
Cache2: Policy 'always' initialized successfully
Cache2: Cannot find core 1 in pool, core added as inactive
Inserting cache Cache4
Cache4: Successfully added
Cache4: Cache mode : wt
Cache4: Attaching cache device failed
vbdev_ocf.c:1005:start_cache_cmpl: *ERROR*: Error -1000013 during start cache Cache4, starting rollback
Cache4: Cannot flush cache - cache device is detached
Cache4: Cache Cache4 successfully stopped
vbdev_ocf.c: 220:remove_core_cache_lock_cmpl: *ERROR*: Error -1000014, can not lock cache instance Cache4
Cache3: Loading Super block runtime ERROR, invalid checksumCache3: Metadata read FAILURE
Cache3: Metadata Error
Cache3: ERROR: Cannot load cache state
vbdev_ocf.c:1005:start_cache_cmpl: *ERROR*: Error -1000013 during start cache Cache3, starting rollback
Inserting cache Cache5
Cache5: Successfully added
Cache5: Cache mode : wt
Cache5: Super block config offset : 0 kiB
Cache5: Super block config size : 2196 B
Cache5: Super block runtime offset : 128 kiB
Cache5: Super block runtime size : 4 B
Cache5: Reserved offset : 256 kiB
Cache5: Reserved size : 128 kiB
Cache5: Part config offset : 384 kiB
Cache5: Part config size : 48 kiB
Cache5: Part runtime offset : 512 kiB
Cache5: Part runtime size : 4 kiB
Cache5: Core config offset : 640 kiB
Cache5: Core config size : 484 kiB
Cache5: Core runtime offset : 1152 kiB
Cache5: Core runtime size : 1172 kiB
Cache5: Core UUID offset : 2432 kiB
Cache5: Core UUID size : 16384 kiB
Cache5: Cleaning offset : 18816 kiB
Cache5: Cleaning size : 2173212 kiB
Cache5: Eviction offset : 2192128 kiB
Cache5: Eviction size : 1447396 kiB
Cache5: Collision offset : 3639552 kiB
Cache5: Collision size : 2173212 kiB
Cache5: List info offset : 5812864 kiB
Cache5: List info size : 3087772 kiB
Cache5: Hash offset : 8900736 kiB
Cache5: Hash size : 180928 kiB
Cache5: Cache line size: 4 kiB
Cache5: Metadata capacity: 9574 MiB
Cache5: OCF metadata self-test PASSED
Cache5: Policy 'always' initialized successfully

**Comment by tomzawadzki** [comment] 2020-06-16 11:34
Hi @gwnet please use the "```" code block, so it is easier to catch the questions in the middle of the comment.

If I understood the question, this looks like there are already OCF metadata present on the NVMe device:
```
vbdev_ocf.c:1594:metadata_probe_cores_construct: NOTICE: OCF metadata found on Nvme5n1 belongs to bdev named 'Nvme5n1p0'
vbdev_ocf.c:1458:vbdev_ocf_construct: NOTICE: OCF bdev 'Cache1' is waiting for cache device 'Nvme5n1p0' to connect
vbdev_ocf.c:1462:vbdev_ocf_construct: NOTICE: OCF bdev 'Cache1' is waiting for core device 'Malloc0' to connect
vbdev_ocf.c:1462:vbdev_ocf_construct: NOTICE: OCF bdev 'Cache2' is waiting for core device 'Malloc1' to connect
vbdev_ocf.c:1462:vbdev_ocf_construct: NOTICE: OCF bdev 'Cache3' is waiting for core device 'Malloc2' to connect
```

As you were performing following steps:
```
intel@intel:/wayne/spdk$ sudo scripts/rpc.py bdev_ocf_get_bdevs
[]
intel@intel:/wayne/spdk$ sudo scripts/rpc.py bdev_get_bdevs
[]
intel@intel:~/wayne/spdk$
==then I run through below scripts===
date -R --debug
echo split nvme5n1
time scripts/rpc.py bdev_nvme_attach_controller -b Nvme5 -t PCIe -a 0000:b2:00.0
time scripts/rpc.py bdev_split_create Nvme5n1 10
....
```
OCF metadata is saved on the NVMe device (or it's split parts), so to verify if some were already there you should first attach and split the NVMe. Then verify if any were present by issuing `bdev_ocf_get_bdevs` and `bdev_get_bdevs`.

**Comment by gwnet** [comment] 2020-06-16 12:49
@tomzawadzki thank you so much. you are quite right, I am sorry for late update. after I do one disk format between tests, the issue is gone. :)

**Comment by tomzawadzki** [comment] 2020-06-16 15:36
Glad to hear that. Since the issue is gone, let's close it :)

**Closed by tomzawadzki** 2020-06-16 15:36 UTC
Labels: question
