### ISSUE TITLE
nvme_cli test fails to link to the spdk repo

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1213] opened 2020-02-18 08:37 UTC
This seems to happen intermittently: https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/3846/archive/nvme-phy-autotest/build.log - `spdk_nvme_cli.sh` attempts to remove entire directory with `rm -f`. I take the assumption is that it should be an actual symlink to the repo we want to built nvme_cli against but here it's not the case.

Part where it fails:
```
 22:58:16	# rm -f /home/sys_sgsw/nvme-cli/spdk
rm: cannot remove '/home/sys_sgsw/nvme-cli/spdk': Is a directory
```

Simply use `rm -rf` instead as we want to use specific repo.

**Comment by darsto** [comment] 2020-02-18 09:24
@karlatec please assign someone ;)

**Comment by darsto** [comment] 2020-02-18 09:25
(anyone but me!)

**Comment by spdkci** [comment] 2020-02-18 09:33
Another instance of this failure. Reported by @mikeBashStuff. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3846.html

**Comment by spdkci** [comment] 2020-02-18 16:12
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3968.html

**Comment by spdkci** [comment] 2020-02-19 19:06
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4072.html

**Comment by jimharris** [comment] 2020-02-20 04:19
Bug scrub: All three failures reported so far are on GP1.  Assigning to @karlatec and @Seth5141.

**Comment by spdkci** [comment] 2020-02-20 11:55
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_4209.html

**Comment by karlatec** [comment] 2020-02-21 10:00
Appatently there are more nodes which do not have nvme-cli sources available, but they were silently skipping tests. I've added a fail condition for that here: https://review.spdk.io/gerrit/c/spdk/spdk/+/980
so please expect some more failures until I identify and fix all the test systems.

**Comment by spdkci** [comment] 2020-02-21 11:58
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_4359.html

**Comment by spdkci** [comment] 2020-02-23 21:27
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4341.html

**Comment by karlatec** [comment] 2020-02-24 07:29
It looks like these two occurrences happened on Friday before I provisioned nvme-cli source on test nodes. I can't see reproduction of original issue for nvme-phy-autotest since Friday afternoon GMT+1 time.

**Comment by karlatec** [comment] 2020-02-25 07:21
Update: none of the failed builds of nvme-phy-autotest in build history (150 builds) is related to this issue. Seems it's not occurring anymore.

**Closed** 2020-02-25 07:48 UTC
Labels: Infrastructure, Intermittent Failure
