### ISSUE TITLE
[iscsi-autotest] Error while connecting to /var/tmp/spdk0.sock

### ISSUE THREAD

**Issue by cyb70289** [spdk/spdk#1439] opened 2020-06-16 07:03 UTC
## Link to the failed CI build
https://ci.spdk.io/public_build/autotest-per-patch_18453.html

## Execution failed at
00:07:23.205  ========== Backtrace start: ==========
00:07:23.205  
00:07:23.210  in ./test/iscsi_tgt/ip_migration/ip_migration.sh:123 -> main([])
00:07:23.211       ...
00:07:23.211     118 	$rpc_py -s $rpc_first_addr spdk_kill_instance SIGTERM
00:07:23.211     119 	
00:07:23.211     120 	rpc_second_addr="/var/tmp/spdk1.sock"
00:07:23.211     121 	rpc_add_target_node $rpc_second_addr
00:07:23.211     122 	
00:07:23.211  => 123 	wait $fiopid
00:07:23.211     124 	
00:07:23.211     125 	trap - SIGINT SIGTERM EXIT
00:07:23.211     126 	
00:07:23.211     127 	iscsicleanup
00:07:23.211     128 	
00:07:23.211       ...
00:07:23.211  
00:07:23.211  ========== Backtrace end ==========
00:07:23.211    09:44:38	# xtrace_enable
00:07:23.212    09:44:38	# return 0
00:07:23.212   09:44:38	# kill_all_iscsi_target
00:07:23.212   09:44:38	# (( i = 0 ))
00:07:23.212   09:44:38	# (( i < 2 ))
00:07:23.212   09:44:38	# rpc_addr=/var/tmp/spdk0.sock
00:07:23.212   09:44:38	# /var/jenkins/workspace/iscsi-autotest/spdk/scripts/rpc.py -s /var/tmp/spdk0.sock spdk_kill_instance SIGTERM
00:07:23.444  Traceback (most recent call last):
00:07:23.444    File "/var/jenkins/workspace/iscsi-autotest/spdk/scripts/rpc/client.py", line 51, in __init__
00:07:23.444      self.sock.connect((addr, port))
00:07:23.444  socket.gaierror: [Errno -2] Name or service not known
00:07:23.444  
00:07:23.444  During handling of the above exception, another exception occurred:
00:07:23.444  
00:07:23.444  Traceback (most recent call last):
00:07:23.444    File "/var/jenkins/workspace/iscsi-autotest/spdk/scripts/rpc.py", line 2452, in <module>
00:07:23.444      args.client = rpc.client.JSONRPCClient(args.server_addr, args.port, args.timeout, log_level=getattr(logging, args.verbose.upper()))
00:07:23.444    File "/var/jenkins/workspace/iscsi-autotest/spdk/scripts/rpc/client.py", line 56, in __init__
00:07:23.444      "Error details: %s" % (addr, ex))
00:07:23.444  rpc.client.JSONRPCException: Error while connecting to /var/tmp/spdk0.sock
00:07:23.444  Error details: [Errno -2] Name or service not known
00:07:23.448    09:44:39	# trap - ERR
00:07:23.448    09:44:39	# print_backtrace
00:07:23.448    09:44:39	# [[ ehxBET =~ e ]]
00:07:23.449    09:44:39	# args=("${BASH_ARGV[@]}")
00:07:23.449    09:44:39	# local args
00:07:23.449    09:44:39	# xtrace_disable
00:07:23.449    09:44:39	# '[' no '!=' yes ']'
00:07:23.450    09:44:39	# PREV_BASH_OPTS=ehxBET
00:07:23.450    09:44:39	# [[ ehxBET == *\x* ]]
00:07:23.450    09:44:39	# XTRACE_DISABLED=yes
00:07:23.450    09:44:39	# set +x
00:07:23.450  ========== Backtrace start: ==========
00:07:23.450  
00:07:23.455  in /var/jenkins/workspace/iscsi-autotest/spdk/test/common/autotest_common.sh:874 -> run_test(["iscsi_tgt_ip_migration"],["./test/iscsi_tgt/ip_migration/ip_migration.sh"])
00:07:23.455       ...
00:07:23.455     869 		timing_enter $test_name
00:07:23.455     870 		echo "************************************"
00:07:23.455     871 		echo "START TEST $test_name"
00:07:23.455     872 		echo "************************************"
00:07:23.455     873 		xtrace_restore
00:07:23.455  => 874 		time "$@"
00:07:23.455     875 		xtrace_disable
00:07:23.455     876 		echo "************************************"
00:07:23.455     877 		echo "END TEST $test_name"
00:07:23.455     878 		echo "************************************"
00:07:23.455     879 		timing_exit $test_name
00:07:23.455       ...
00:07:23.459  in ./test/iscsi_tgt/iscsi_tgt.sh:50 -> main(["posix"])
00:07:23.459       ...
00:07:23.459     45  	run_test "iscsi_tgt_qos" ./test/iscsi_tgt/qos/qos.sh
00:07:23.459     46  	
00:07:23.459     47  	# IP Migration tests do not support network namespaces,
00:07:23.459     48  	# they can only be run on posix sockets.
00:07:23.459     49  	if [ "$TEST_TYPE" == "posix" ]; then
00:07:23.459  => 50  		run_test "iscsi_tgt_ip_migration" ./test/iscsi_tgt/ip_migration/ip_migration.sh
00:07:23.459     51  	fi
00:07:23.459     52  	run_test "iscsi_tgt_trace_record" ./test/iscsi_tgt/trace_record/trace_record.sh
00:07:23.459     53  	
00:07:23.459     54  	if [ $RUN_NIGHTLY -eq 1 ]; then
00:07:23.459     55  		if [ $SPDK_TEST_PMDK -eq 1 ]; then
00:07:23.459       ...
00:07:23.459  
00:07:23.460  ========== Backtrace end ==========
00:07:23.460    09:44:39	# xtrace_enable
00:07:23.460    09:44:39	# return 0
00:07:23.460  
00:07:23.460  real	0m14.205s
00:07:23.460  user	1m6.036s
00:07:23.460  sys	0m0.959s
00:07:23.461   09:44:39	# cleanup_veth_interfaces posix
00:07:23.461   09:44:39	# '[' posix == vpp ']'
00:07:23.461   09:44:39	# ip link delete spdk_init_int
00:07:23.512   09:44:39	# ip netns del spdk_iscsi_ns
00:07:23.514   09:44:39	# exit 1
00:07:23.515    09:44:39	# trap - ERR
00:07:23.515    09:44:39	# print_backtrace
00:07:23.515    09:44:39	# [[ ehxBET =~ e ]]
00:07:23.515    09:44:39	# args=("${BASH_ARGV[@]}")
00:07:23.515    09:44:39	# local args
00:07:23.516    09:44:39	# xtrace_disable
00:07:23.516    09:44:39	# '[' no '!=' yes ']'
00:07:23.516    09:44:39	# PREV_BASH_OPTS=ehxBET
00:07:23.516    09:44:39	# [[ ehxBET == *\x* ]]
00:07:23.516    09:44:39	# XTRACE_DISABLED=yes
00:07:23.516    09:44:39	# set +x
00:07:23.517  ========== Backtrace start: ==========
00:07:23.517  
00:07:23.525  in /var/jenkins/workspace/iscsi-autotest/spdk/test/common/autotest_common.sh:874 -> run_test(["iscsi_tgt_posix"],["./test/iscsi_tgt/iscsi_tgt.sh"],["posix"])
00:07:23.525       ...
00:07:23.525     869 		timing_enter $test_name
00:07:23.525     870 		echo "************************************"
00:07:23.525     871 		echo "START TEST $test_name"
00:07:23.525     872 		echo "************************************"
00:07:23.525     873 		xtrace_restore
00:07:23.525  => 874 		time "$@"
00:07:23.525     875 		xtrace_disable
00:07:23.525     876 		echo "************************************"
00:07:23.525     877 		echo "END TEST $test_name"
00:07:23.525     878 		echo "************************************"
00:07:23.525     879 		timing_exit $test_name
00:07:23.525       ...
00:07:23.529  in /var/jenkins/workspace/iscsi-autotest/spdk/autotest.sh:203 -> main(["/home/sys_sgci/autorun-spdk.conf"])
00:07:23.529       ...
00:07:23.529     198 		fi
00:07:23.529     199 	
00:07:23.529     200 		timing_exit lib
00:07:23.529     201 	
00:07:23.529     202 		if [ $SPDK_TEST_ISCSI -eq 1 ]; then
00:07:23.529  => 203 			run_test "iscsi_tgt_posix" ./test/iscsi_tgt/iscsi_tgt.sh posix
00:07:23.529     204 			run_test "spdkcli_iscsi" ./test/spdkcli/iscsi.sh
00:07:23.529     205 	
00:07:23.529     206 			# Run raid spdkcli test under iSCSI since blockdev tests run on systems that can't run spdkcli yet
00:07:23.529     207 			run_test "spdkcli_raid" test/spdkcli/raid.sh
00:07:23.529     208 		fi
00:07:23.529       ...
00:07:23.529  
00:07:23.529  ========== Backtrace end ==========

**Comment by tomzawadzki** [comment] 2020-06-16 10:40
Hi @cyb70289, this is duplicate of #1313 which was fixed on master. Rebasing on latest master shouldn't produce this intermittent failure. If it does occur, please re-open the original issue.

**Closed by tomzawadzki** 2020-06-16 10:40 UTC
Labels: Intermittent Failure
