### ISSUE TITLE
[nvmf_filesystem_no_in_capsule] Timeout after "Warning: The resulting partition is not properly aligned for best performance"

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2388] opened 2022-02-21 14:50 UTC
# CI Intermittent Failure

During nvmf-phy-autotest, nvmf_filesystem_no_in_capsule timed out after 30 minutes. Supplemental logs reported that some tests were not run, which resulted in "Aborted" status and overall failure.

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_71788.html

## Execution failed at

build.log:
...
00:03:05.317   12:01:07	-- common/autotest_common.sh@1051 -- # nvme_devices=1
00:03:05.317   12:01:07	-- common/autotest_common.sh@1052 -- # (( nvme_devices == nvme_device_counter ))
00:03:05.317   12:01:07	-- common/autotest_common.sh@1052 -- # return 0
00:03:05.317    12:01:07	-- target/filesystem.sh@58 -- # lsblk -l -o NAME,SERIAL
00:03:05.317    12:01:07	-- target/filesystem.sh@58 -- # grep -oP '([\w]*)(?=\s+SPDK00000000000001)'
00:03:05.317   12:01:07	-- target/filesystem.sh@58 -- # nvme_name=nvme0n1
00:03:05.317   12:01:07	-- target/filesystem.sh@60 -- # mkdir -p /mnt/device
00:03:05.317   12:01:07	-- target/filesystem.sh@62 -- # parted -s /dev/nvme0n1 mklabel msdos mkpart primary 0% 100%
**00:03:05.317  Warning: The resulting partition is not properly aligned for best performance: 1s % 2048s != 0s
00:03:05.317   12:01:07	-- target/filesystem.sh@63 -- # partprobe
00:30:26.291  Cancelling nested steps due to timeout**
00:30:26.294  Sending interrupt signal to process
00:30:42.838  Terminated
00:30:42.848  script returned exit code 143
00:30:42.854  [Pipeline] }
00:30:42.877  [Pipeline] // timeout
00:30:42.885  [Pipeline] }
00:30:42.905  [Pipeline] // stage
00:30:42.913  [Pipeline] }
00:30:42.917  Timeout has been exceeded
00:30:42.936  [Pipeline] // catchError
00:30:42.946  [Pipeline] stage
00:30:42.949  [Pipeline] { (Epilogue)
...

Supplemental logs -> build.log:
...
00:47:06.233  Not all tests were run. Failing the build.
00:47:06.233  ['nvmf_bdevperf', 'nvmf_shutdown', 'nvmf_shutdown_tc1', 'nvmf_shutdown_tc2', 'nvmf_shutdown_tc3', 'nvmf_target_disconnect', 'nvmf_target_disconnect_tc1', 'nvmf_target_disconnect_tc2', 'nvmf_target_disconnect_tc3']
00:47:06.252  [Pipeline] }
00:47:06.256  ERROR: script returned exit code 1
00:47:06.284  [Pipeline] // catchError
...

**Comment by spdkci** [comment] 2022-02-21 14:51
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_71788.html

**Comment by karlatec** [comment] 2022-03-02 13:28
`00:03:05.317 Warning: The resulting partition is not properly aligned for best performance: 1s % 2048s != 0s` is just a warning message from parted. Doesn't seem related to the timeout issue. Should be fixed though.

No clue why partprobe hanged though.

**Comment by kgodzwox** [comment] 2022-03-08 11:50
Warning fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/11820/1

**Comment by tomzawadzki** [comment] 2022-03-08 15:23
[Bug scrub] Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/11820 is only resolving the warning message. The root cause is not yet determined. So far attempts at reproduction failed.

Information provided in `target/filesystem.sh` can be improved, size of the device for example. It would be helpful for debugging future occurrences of this issue. Keeping this issue open, till such information is included in the logs.

**Closed** 2022-05-04 08:03 UTC
Labels: Intermittent Failure
