### ISSUE TITLE
SPDK vmd/led tool can't set the NVMe SSD LED state

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#1057] opened 2019-11-15 07:46 UTC
## Expected Behavior
The LED amber is off.

## Current Behavior
The LED amber is still on.

## Steps to Reproduce
1. set the VMD in the BIOS;
2. run lspci to get the nvme ssd new pci info:
```
0000:81:00.0 Non-Volatile memory controller: Intel Corporation NVMe Datacenter SSD [Optane]
0000:d8:00.0 Non-Volatile memory controller: Intel Corporation NVMe Datacenter SSD [Optane]
10000:01:00.0 Non-Volatile memory controller: Intel Corporation PCIe Data Center SSD (rev 01)
10001:01:00.0 Non-Volatile memory controller: Intel Corporation PCIe Data Center SSD (rev 01)
10001:02:00.0 Non-Volatile memory controller: Intel Corporation PCIe Data Center SSD (rev 01)

```
The last three nvme ssd is NVMe SSD behind VMD.
3.get the 201d devices:
```
0000:5d:05.5 RAID bus controller: Intel Corporation Device 201d (rev 04)
0000:d7:05.5 RAID bus controller: Intel Corporation Device 201d (rev 04)

```
4. get the latest spdk codes and compile the codes.
5. run setup.sh command:
`PCI_WHITELIST="0000:5d:05.5 0000:d7:05.5" ./scripts/setup.sh
`
6. run spdk_lspci tool:
```
List of available PCI devices:
5d0505:01:00.0 (8086 953) (NVMe disk behind VMD)
d70505:01:00.0 (8086 953) (NVMe disk behind VMD)
d70505:03:00.0 (8086 953) (NVMe disk behind VMD)
0000:5d:05.5 (8086 201d) (VMD)
0000:d7:05.5 (8086 201d) (VMD)

```
7. run vmd/led tool to turn off the LED:
./examples/vmd/led/led -s off

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit: dc6d89b925a1a04212a4373ab46d632d4f87dbd0

**Comment by jimharris** [comment] 2019-11-15 14:45
Assigning to @ksztyber - can you give @liang2yan some further debug steps?

**Comment by liang2yan** [comment] 2019-11-18 05:59
@ksztyber , please see attached file for the debug output of command "./examples/vmd/led/led -s off -d off".

**Comment by ksztyber** [comment] 2019-11-18 15:00
@liang2yan Could you check if the LED tool sees the changes being made? Running it without the -s argument should print the current state of the LEDs. E.g:
```
$ sudo examples/vmd/led/led
Starting SPDK v20.01-pre / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: led --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid6320 ]                                        
EAL: No available hugepages reported in hugepages-1048576kB                                                          
5d0505:01:00.0: off
5d0505:03:00.0: off
$ sudo examples/vmd/led/led -s fault                                                    
Starting SPDK v20.01-pre / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: led --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid6323 ]                                        
EAL: No available hugepages reported in hugepages-1048576kB                                                          
$ sudo examples/vmd/led/led
Starting SPDK v20.01-pre / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: led --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid6326 ]                                        
EAL: No available hugepages reported in hugepages-1048576kB                                                          
5d0505:01:00.0: fault
5d0505:03:00.0: fault
```

**Comment by liang2yan** [comment] 2019-11-19 02:06
@ksztyber , I have run same command with you. The log is as below:
```
[root@]./examples/vmd/led/led
Starting SPDK v20.01-pre git sha1 92df995 / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: led --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid8506 ]
EAL: No available hugepages reported in hugepages-1048576kB
5d0505:01:00.0: off
d70505:01:00.0: off
d70505:03:00.0: off
[root@]./examples/vmd/led/led -s fault
Starting SPDK v20.01-pre git sha1 92df995 / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: led --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid8517 ]
EAL: No available hugepages reported in hugepages-1048576kB
[root@]./examples/vmd/led/led
Starting SPDK v20.01-pre git sha1 92df995 / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: led --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid8529 ]
EAL: No available hugepages reported in hugepages-1048576kB
5d0505:01:00.0: fault
d70505:01:00.0: fault
d70505:03:00.0: fault
```
But I still can't see the status change of the led. is it my hardware issue?

**Comment by ksztyber** [comment] 2019-11-19 11:02
That is weird, it looks like the registers controlling the state of the LEDs are written correctly (they do hold their values), but they don't seem to be actually modifying the state of the LEDs. Could you check if they can be controlled using non-SPDK (e.g. `ledctl`) tools?

**Comment by liang2yan** [comment] 2019-11-20 05:40
I have run ledctl command using following parameters:
`ledctl off={/dev/nvme2n1 /dev/nvme3n1 /dev/nvme4n1}`
The three devices are the nvme sdd which are behind the RAID controllers. there is no change for the LED status. So how to control the nvme ssd led status?

**Comment by ksztyber** [comment] 2019-11-20 12:36
I'm afraid that the fact that you're not able to control the LEDs neither using SPDK, nor ledctl proves that the issue is not related to the software, but rather to some kind of hardware/configuration problem on your end. Have you tried using different SSDs?

**Comment by liang2yan** [comment] 2019-11-21 08:19
I used P4500 SSD, it still can't work. So any documents/link for the hardware which can enable VMD?

**Comment by ksztyber** [comment] 2019-11-22 13:05
Unfortunately I'm not aware of any documents describing the VMD's LED management... You could also try setting the registers responsible for LED management manually:
```
$ ls -l /sys/block/nvme0n1 # Note the second to last BDF (10001:00:01.0)
lrwxrwxrwx 1 root root 0 Nov 22 13:18 /sys/block/nvme0n1 -> ../devices/pci0000:d7/0000:d7:05.5/pci10001:00/10001:00:01.0/10001:03:00.0/nvme/nvme3/nvme0n1
# setpci -v -s 10001:00:01.0 CAP_EXP+0x18.w
10001:00:01.0 (cap 10 @90) @a8 = 0562
$ python -c "print(hex(0x562 & ~(0xf << 6) | 3 << 6 | 3 << 8))" # To turn off the LED we need to OR the register with 3 << 6 | 3 << 8
0x7e2
# setpci -v -s 10001:00:01.0 CAP_EXP+0x18.w=0x7e2
10001:00:01.0 (cap 10 @90) @a8 07e2
# setpci -v -s 10001:00:01.0 CAP_EXP+0x18.w
10001:00:01.0 (cap 10 @90) @a8 = 07e2
$ python -c "print(hex(0x562 & ~(0xf << 6) | 3 << 6 | 1 << 8))" # To make the LED blink we need to or the register with 3 << 6 | 1 << 8
0x5e2
# setpci -v -s 10001:00:01.0 CAP_EXP+0x18.w=0x5e2
10001:00:01.0 (cap 10 @90) @a8 05e2
```

**Comment by Comphix** [comment] 2019-11-26 12:58
> I have run ledctl command using following parameters:
> `ledctl off={/dev/nvme2n1 /dev/nvme3n1 /dev/nvme4n1}`
> The three devices are the nvme sdd which are behind the RAID controllers. there is no change for the LED status. So how to control the nvme ssd led status?

Hi Liang, can we have a try to 1) plug the NVMe SSD directly to the PCIe lane instead of behind the switch; 2) try the ledctl tool again for this NVMe SSD.

Thanks, Gang

**Comment by Comphix** [comment] 2019-11-26 13:03
Also one link for ledctl: https://linux.die.net/man/8/ledctl

**Comment by liang2yan** [comment] 2019-11-28 08:07
I have tried on another machine, the spdk led tool can work for P4500 SSD, but not P3700. So I think there is some platform and SSD limit for VMD LED function.

**Comment by peluse** [comment] 2019-12-03 15:30
@ksztyber can you please see if the VMD folks have or can provide any form of known issues list with specific platforms?  Also can we add a small blurb in the SPDK docs around VMD that describe or at least mention the use of ledctrl as a means to confirm led functionality on a platform w/o SPDK in the picture?

**Comment by erroldo** [comment] 2019-12-05 09:58
The LED blinking behind spdk-vmd is accomplished by writing the pcie slot control power and attention register with bits to propagate to the LED, likely through VPP depending on how said platform is wired to the LED from the slot control. First would be to ensure that basic platform plumbing is wired correctly to allow LED blinking without SPDK in the picture. Current test indicate another platform could blink the LED with a P4500 inserted. What is in the slot should not affect the led blinking, as he LED is implemented on the slot, not the device in this instance. I would suggest testing spdk-vmd led blinking on this system and let us know. From there we can determine if the spdk-vmd led code is not functioning or if the platform has an issue with the LED implementation path.

**Comment by ksztyber** [comment] 2019-12-05 10:09
@liang2yan what platforms are you using? Did you try to use both P4500 and P3700 on both platforms? 
@peluse yeah, I'll add a short paragraph to the VMD's docs.

**Comment by spdkci** [comment] 2019-12-06 03:06
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51605.html

**Comment by liang2yan** [comment] 2019-12-06 07:04
@ksztyber , I am using the Intel S2600WFT platform. the two platform used different version BIOS.I tried P4500 and P3700 on two platforms. The led tool can only work on one platform.

**Comment by peluse** [comment] 2020-01-06 22:41
@liang2yan I assume you mean that https://linux.die.net/man/8/ledctl works on one but not on the other?  If so then it sounds like this can be closed.

**Comment by jimharris** [comment] 2020-01-16 04:27
[Bug scrub] Marking as low priority bug.  It's not really a bug per se, but something we need to document.

**Comment by optimistyzy** [comment] 2020-06-10 05:54
@jimharris  I will close this issue according to the information from @liang2yan . The related document doc/vmd.md is updated with the LED management section. And I checked it, it is true.

**Closed by optimistyzy** 2020-06-10 05:54 UTC
Labels: Low, bug
