### ISSUE TITLE
EAL failed to attach device on CI

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1218] opened 2020-02-19 21:51 UTC
The following error was observed:
https://review.spdk.io/gerrit/c/spdk/spdk/+/853/4
```
EAL: Driver cannot attach the device (0000:85:00.0)
EAL: Failed to attach device on primary process
nvme.c: 606:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
bdev_nvme.c:1613:spdk_bdev_nvme_create: *ERROR*: No controller was found with provided trid (traddr: 0000:85:00.0)
json_config.c: 192:rpc_client_poller: *ERROR*: error response: {"code":-19,"message":"No such device"}}

```

**Comment by spdkci** [comment] 2020-02-19 21:52
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4068.html

**Comment by changpe1** [comment] 2020-02-20 01:56
From the log information, DPDK hotplug API returns an error when probing the drive.

**Comment by changpe1** [comment] 2020-02-20 03:59
Similar with #1209 too. This is attach failure, and #1209 is detach failure.

**Comment by changpe1** [comment] 2020-02-20 08:21
> Similar with #1209 too. This is attach failure, and #1209 is detach failure.

The detach failure information is related with autotest, I can reproduce it by using STUB in two terminals: 
1)  test/app/stub/stub -s 4096 -i 0 -m 0xE
2)  examples/nvme/identify/identify -i 0

Terminal 1 prints:
Starting SPDK v20.04-pre git sha1 6d8f1fc / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: stub -c 0xE -m 4096 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
app.c: 646:spdk_app_start: *NOTICE*: Total cores available: 3
reactor.c: 317:_spdk_reactor_run: *NOTICE*: Reactor started on core 2
reactor.c: 317:_spdk_reactor_run: *NOTICE*: Reactor started on core 3
reactor.c: 317:_spdk_reactor_run: *NOTICE*: Reactor started on core 1
EAL:   using IOMMU type 1 (Type 1)
EAL: Driver cannot detach the device (0000:84:00.0)
EAL: Failed to hotplug remove device on primary
EAL: Driver cannot detach the device (0000:85:00.0)
EAL: Failed to hotplug remove device on primary
EAL: Driver cannot detach the device (0000:84:00.0)
EAL: Failed to hotplug remove device on primary
EAL: Driver cannot detach the device (0000:85:00.0)
EAL: Failed to hotplug remove device on primary

Device 0000:84:00.0 is still attached at shutdown!
Device 0000:85:00.0 is still attached at shutdown!

Terminal 2 prints:
EAL: Failed to hotplug remove device.

This should be a bug, at least for this scenario, we didn't shutdown the NVMe controllers. I'll investigate more.

**Comment by spdkci** [comment] 2020-02-21 05:54
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4318.html

**Comment by spdkci** [comment] 2020-02-24 00:55
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4478.html

**Comment by spdkci** [comment] 2020-02-24 05:22
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4499.html

**Comment by darsto** [comment] 2020-02-24 11:51
Interesting - I can take a look if needed. Our multi-process device hotplug could use some love.

**Comment by changpe1** [comment] 2020-02-25 01:25
@darsto This issue is not caused by hotplug, although there are some error information printed from DPDK library.

Here is the one possible fix from SPDK side, https://review.spdk.io/gerrit/c/spdk/spdk/+/977, I think we should detach the controller when exit the stub  process, it may affect the next start as the issue shows.

**Comment by spdkci** [comment] 2020-02-25 01:46
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4631.html

**Comment by spdkci** [comment] 2020-02-25 02:12
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4635.html

**Comment by spdkci** [comment] 2020-02-25 02:25
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4638.html

**Comment by changpe1** [comment] 2020-02-25 03:00
> Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4638.html

spdk_nvme_transport_available_by_name() return false because no RDMA transport found.

This should not the same issue:
[ DPDK EAL parameters: nvme_cli --no-shconf -c 0x1 -m 512 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid224983 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
nvme.c: 598:spdk_nvme_probe_internal: *ERROR*: NVMe trtype 1 not available
nvme.c: 726:spdk_nvme_connect: *ERROR*: Create probe context failed
spdk_nvme_connect() failed
  03:16:03	# trap - ERR
  03:16:03	# print_backtrace
  03:16:03	# [[ ehxBET =~ e ]]
  03:16:03	# args=("${BASH_ARGV[@]}")
  03:16:03	# local args
  03:16:03	# xtrace_disable
  03:16:03	# '[' no '!=' yes ']'
  03:16:03	# PREV_BASH_OPTS=ehxBET
  03:16:03	# [[ ehxBET == *\x* ]]
  03:16:03	# XTRACE_DISABLED=yes
  03:16:03	# set +x
========== Backtrace start: ==========

in test/nvmf/target/nvme_cli.sh:58 -> main(["--transport=rdma"])
     ...

**Comment by spdkci** [comment] 2020-02-25 03:21
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4444.html

**Comment by shuhei-matsumoto** [comment] 2020-02-25 04:07
@changpe1  thanks for the analysis. I may have to move the following to #1227 

> > Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4638.html
> 
> spdk_nvme_transport_available_by_name() return false because no RDMA transport found.
> 
> This should not the same issue:
> [ DPDK EAL parameters: nvme_cli --no-shconf -c 0x1 -m 512 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid224983 ]
> EAL: No available hugepages reported in hugepages-1048576kB
> EAL: VFIO support initialized
> nvme.c: 598:spdk_nvme_probe_internal: _ERROR_: NVMe trtype 1 not available
> nvme.c: 726:spdk_nvme_connect: _ERROR_: Create probe context failed
> spdk_nvme_connect() failed
> 03:16:03 # trap - ERR
> 03:16:03 # print_backtrace
> 03:16:03 # [[ ehxBET =~ e ]]
> 03:16:03 # args=("${BASH_ARGV[@]}")
> 03:16:03 # local args
> 03:16:03 # xtrace_disable
> 03:16:03 # '[' no '!=' yes ']'
> 03:16:03 # PREV_BASH_OPTS=ehxBET
> 03:16:03 # [[ ehxBET == _\x_ ]]
> 03:16:03 # XTRACE_DISABLED=yes
> 03:16:03 # set +x
> ========== Backtrace start: ==========
> 
> in test/nvmf/target/nvme_cli.sh:58 -> main(["--transport=rdma"])
> ...

**Comment by spdkci** [comment] 2020-02-27 23:18
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4974.html

**Comment by changpe1** [comment] 2020-02-28 01:20
https://review.spdk.io/gerrit/c/spdk/spdk/+/977 was merged, let's continue to see if the issue still exist.

**Comment by changpe1** [comment] 2020-02-28 01:20
> Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4974.html

This is related with issue #1227 .

**Comment by changpe1** [comment] 2020-03-05 02:23
Attach failure should be related with we didn't shutdown the controller in STUB process, since patch was merged, I'm going to close this issue.

**Closed by changpe1** 2020-03-05 02:23 UTC
Labels: Intermittent Failure
