### ISSUE TITLE
if rpc server command need take a super long time, client socket will timeout, how to solve this?

### ISSUE THREAD

**Issue by gwnet** [spdk/spdk#1706] opened 2020-11-29 13:32 UTC
if the rpc server command for example create ftl device need long time to provision. we get error at client side below.
what is best way to solve this?
 
     **raise JSONRPCException("Connection closed with partial response:\n%s\n" % self._recv_buf)**

===below is the code that raise above error===I tried set timeout as None, but no help.
    def recv(self):
        start_time = time.process_time()
        response = self.decode_one_response()
        while not response:
            try:
                timeout = self.timeout - (time.process_time() - start_time)
                self.sock.settimeout(timeout)
                newdata = self.sock.recv(4096)
                if not newdata:
                    self.sock.close()
                    self.sock = None
                    raise JSONRPCException("Connection closed with partial response:\n%s\n" % self._recv_buf)
                self._recv_buf += newdata.decode("utf-8")
                response = self.decode_one_response()
            except socket.timeout:
                break  # throw exception after loop to avoid Python freaking out about nested exceptions
            except ValueError:
                continue  # incomplete response; keep buffering

## Steps to Reproduce

1.
2.
3.
4.

**Comment by yidong0635** [comment] 2020-12-01 06:55
Meet the same issue . Is this buffer is not enough ？

**Comment by Comphix** [comment] 2020-12-02 05:48
One possible way is to break the long time ftl_create operation into two phases.

Phase 1: RPC to asynchronously create (the ftl creation will happen in the background). The rpc_bdev_ftl_create() will return immediately.
Phase 2: Add a new list_ftl or get_ftl RPC method to check the status of the ftl creation

**Comment by gaowayne** [comment] 2020-12-02 06:39
@yidong0635 no worry about this now. I found the root cause, it is our FTL use too much C runtime memory, it is killed by OS OOM, so rpc client report that exception, that is correct. and rpc.py -t 600 can add a timeout value, it works. 

@Comphix, great suggestion, we will improve like this. current, our work around is rpc.py -t 600 and we need enough DRAM to run our app.  :)

**Comment by yidong0635** [comment] 2020-12-02 06:47
@gwnet ok, I encountered this issue at other testing before. And I had no idea about this too.  Thanks all.

**Comment by changpe1** [comment] 2021-01-06 08:05
@gwnet Can we close this issue now?

**Comment by gaowayne** [comment] 2021-01-06 09:25
@changpe1 yes, changpe, please go head close this.

**Closed** 2021-01-06 14:01 UTC
Labels: Sighting
