### ISSUE TITLE
VM report IO error when intel_iommu enabled

### ISSUE THREAD

**Issue by wuzhouhui** [spdk/spdk#447] opened 2018-09-27 06:02 UTC
When set `intel_iommu=on` in kernel parameters (in grub2.cfg), the block device in VM report IO error. This block device is generated by connecting vhost-user-blk socket of secondary SPDK vhost target.

## Expected Behavior

The block device can be read/write normally in VM.

## Current Behavior

The block device report IO error when  read/write in VM.

## Steps to Reproduce

1. Start primary vhost target by `vhost -i 0 -r /var/tmp/spdk.sock.p`
2. Start secondary vhost target by `vhost -i 0`
3. Construct nvme bdev for primary process by `rpc.py -s /var/tmp/spdk.sock.p construct_nvme_bdev`. (We only use nvme bdev created in step 4. If we skip step 3, the step 4 will failed because it can't find nvme controller from primary process)
4. Construct same nvme bdev for secondary process by `rpc.py construct_nvme_bdev`
5. Construct vhost-blk controller for secondary's nvme bdev by `rpc.py construct_vhost_blk_controller lv0 Nvme0n1`
6. Start VM by Qemu, connect socket of `lv0` in command line:
```
/root/qemu/x86_64-softmmu/qemu-system-x86_64 \
        -name guest=wzh,debug-threads=on \
        -machine pc-i440fx-2.12,accel=kvm,usb=off,dump-guest-core=off \
        -cpu host \
        -m 2048 \
        -object memory-backend-file,id=mem0,size=2G,mem-path=/dev/hugepages,share=on \
        -numa node,memdev=mem0 \
        -realtime mlock=off \
        -smp 2,sockets=2,cores=1,threads=1 \
        -uuid a84e96e6-2c53-408d-986b-c709bc6a0e51 \
        -no-user-config \
        -nodefaults \
        -rtc base=utc,driftfix=slew \
        -global kvm-pit.lost_tick_policy=delay \
        -no-shutdown \
        -boot strict=on \
        -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 \
        -device ahci,id=sata0,bus=pci.0,addr=0x4 \
        -drive file=/root/wzh/wzh.qcow2,format=qcow2,if=none,id=drive-virtio-disk0,cache=none \
        -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x5,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=0 \
        -device usb-tablet,id=input0,bus=usb.0,port=1 \
        -vnc :0 \
        -k en-us \
        -device cirrus-vga,id=video0,bus=pci.0,addr=0x2 \
        -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x6 \
        -msg timestamp=on \
        -chardev socket,id=char0,path=/root/spdk/app/vhost/lv0 \
        -device vhost-user-blk-pci,id=blk0,chardev=char0,num-queues=4
```
7. Login VM and read/write block device correspond to `lv0`

## Some logs from secondary vhost target
```
EAL: VFIO support initialized
EAL: WARNING! Base virtual address hint (0x20040008f000 != 0x7fbc63780000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING: Address Space Layout Randomization (ASLR) is enabled in the kernel.
EAL:    This may cause issues with mapping memory into secondary processes
...
VHOST_CONFIG: guest memory region 0, size: 0x80000000
	 guest physical addr: 0x0
	 guest virtual  addr: 0x7f49c2200000
	 host  virtual  addr: 0x2aaaaac00000
	 mmap addr : 0x2aaaaac00000
	 mmap size : 0x80000000
	 mmap align: 0x200000
	 mmap off  : 0x0
VHOST_CONFIG: /root/spdk/app/vhost/lv0: read message VHOST_USER_SET_VRING_KICK
VHOST_CONFIG: vring kick idx:0 file:25
VHOST_CONFIG: virtio is now ready for processing.
Cannot set up DMA mapping, error 22
vhost.c: 542:spdk_vhost_dev_mem_register: *WARNING*: Failed to register memory region 0. Future vtophys translation might fail.
VHOST_CONFIG: /root/spdk/app/vhost/lv0: read message VHOST_USER_SET_VRING_NUM
VHOST_CONFIG: /root/spdk/app/vhost/lv0: read message VHOST_USER_SET_VRING_BASE
nvme_pcie.c:1714:nvme_pcie_prp_list_append: *ERROR*: vtophys(0x2aaae0ed8000) failed
```
## Context (Environment including OS version, SPDK version, etc.)

SPDK: 713b48179676 on master
OS: CentOS 7.4, with kernel 3.10.0-862.el7.x86_64
Qemu: 2.12.1
`/proc/cmdline`: BOOT_IMAGE=/vmlinuz-3.10.0-862.el7.x86_64 root=UUID=54a3bb19-71b4-49d4-b43e-43baf2548284 ro crashkernel=auto rhgb quiet LANG=en_US.UTF-8 intel_iommu=on
`configure` param: `--enable-debug`

**Comment by wuzhouhui** [comment] 2018-09-27 06:03
The block device can be read/write normally in VM if we don't use secondary process

**Comment by pawelwod** [comment] 2018-09-27 06:14
You are getting a clear warning from DPDK:

>EAL: WARNING! Base virtual address hint (0x20040008f000 != 0x7fbc63780000) not respected!
> EAL:    This may cause issues with mapping memory into secondary processes
> EAL: WARNING: Address Space Layout Randomization (ASLR) is enabled in the kernel.
> EAL:    This may cause issues with mapping memory into secondary processes

So what you expect from scenario that uses secondary process?

**Comment by pawelwod** [comment] 2018-09-27 06:27
https://doc.dpdk.org/guides/prog_guide/multi_proc_support.html?highlight=multi%20process#multi-process-limitations

**Comment by darsto** [comment] 2018-09-27 07:39
The warning from EAL doesn't seem to be the cause here.

> Cannot set up DMA mapping, error 22
> vhost.c: 542:spdk_vhost_dev_mem_register: *WARNING*: Failed to register
memory region 0. Future vtophys translation might fail.

This is usually paired with a dmesg message that describes the issue. Could
you share dmesg here?

D.

**Comment by wuzhouhui** [comment] 2018-09-27 08:04
There are 8 SSD in my system:
```
31:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
32:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
33:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
34:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
d8:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
d9:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
da:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
db:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
```
But SPDK only use first two (31:00.0 and 32:00.0) and I only export 31:00.0 via vhost-user-blk to VM.

I don't find any usefull message from dmesg, maybe you can find some different. The complete dmesg is too long, so I just put last portion here:
```
...
[   14.454408] virbr0: port 1(virbr0-nic) entered blocking state
[   14.454413] virbr0: port 1(virbr0-nic) entered listening state
[   14.454760] IPv6: ADDRCONF(NETDEV_UP): virbr0: link is not ready
[   14.551429] virbr0: port 1(virbr0-nic) entered disabled state
[ 3890.428022] VFIO - User Level meta-driver version: 0.3
[ 3925.184678] pcieport 0000:30:00.0: bridge window [io  0x1000-0x0fff] to [bus 31] add_size 1000
[ 3925.184754] pcieport 0000:30:01.0: bridge window [io  0x1000-0x0fff] to [bus 32] add_size 1000
[ 3925.184826] pcieport 0000:30:02.0: bridge window [io  0x1000-0x0fff] to [bus 33] add_size 1000
[ 3925.184897] pcieport 0000:30:03.0: bridge window [io  0x1000-0x0fff] to [bus 34] add_size 1000
[ 3925.185033] pcieport 0000:30:00.0: res[13]=[io  0x1000-0x0fff] res_to_dev_res add_size 1000 min_align 1000
[ 3925.185040] pcieport 0000:30:01.0: res[13]=[io  0x1000-0x0fff] res_to_dev_res add_size 1000 min_align 1000
[ 3925.185048] pcieport 0000:30:02.0: res[13]=[io  0x1000-0x0fff] res_to_dev_res add_size 1000 min_align 1000
[ 3925.185055] pcieport 0000:30:03.0: res[13]=[io  0x1000-0x0fff] res_to_dev_res add_size 1000 min_align 1000
[ 3925.185062] pcieport 0000:2f:00.0: bridge window [io  0x1000-0x0fff] to [bus 30-35] add_size 4000
[ 3925.185078] pcieport 0000:2f:00.0: res[13]=[io  0x1000-0x0fff] res_to_dev_res add_size 4000 min_align 1000
[ 3925.185085] pcieport 0000:2e:00.0: bridge window [io  0x1000-0x0fff] to [bus 2f-35] add_size 4000
[ 3925.185098] pcieport 0000:2e:00.0: res[13]=[io  0x1000-0x0fff] res_to_dev_res add_size 4000 min_align 1000
[ 3925.185105] pcieport 0000:2e:00.0: res[13]=[io  0x1000-0x4fff] res_to_dev_res add_size 4000 min_align 1000
[ 3925.185116] pcieport 0000:2e:00.0: BAR 13: no space for [io  size 0x4000]
[ 3925.185123] pcieport 0000:2e:00.0: BAR 13: failed to assign [io  size 0x4000]
[ 3925.185132] pcieport 0000:2e:00.0: BAR 13: no space for [io  size 0x4000]
[ 3925.185138] pcieport 0000:2e:00.0: BAR 13: failed to assign [io  size 0x4000]
[ 3925.185146] pcieport 0000:2f:00.0: res[13]=[io  0x1000-0x0fff] res_to_dev_res add_size 4000 min_align 1000
[ 3925.185153] pcieport 0000:2f:00.0: res[13]=[io  0x1000-0x4fff] res_to_dev_res add_size 4000 min_align 1000
[ 3925.185159] pcieport 0000:2f:00.0: BAR 13: no space for [io  size 0x4000]
[ 3925.185165] pcieport 0000:2f:00.0: BAR 13: failed to assign [io  size 0x4000]
[ 3925.185172] pcieport 0000:2f:00.0: BAR 13: no space for [io  size 0x4000]
[ 3925.185177] pcieport 0000:2f:00.0: BAR 13: failed to assign [io  size 0x4000]
[ 3925.185188] pcieport 0000:30:00.0: res[13]=[io  0x1000-0x0fff] res_to_dev_res add_size 1000 min_align 1000
[ 3925.185195] pcieport 0000:30:00.0: res[13]=[io  0x1000-0x1fff] res_to_dev_res add_size 1000 min_align 1000
[ 3925.185202] pcieport 0000:30:01.0: res[13]=[io  0x1000-0x0fff] res_to_dev_res add_size 1000 min_align 1000
[ 3925.185209] pcieport 0000:30:01.0: res[13]=[io  0x1000-0x1fff] res_to_dev_res add_size 1000 min_align 1000
[ 3925.185215] pcieport 0000:30:02.0: res[13]=[io  0x1000-0x0fff] res_to_dev_res add_size 1000 min_align 1000
[ 3925.185222] pcieport 0000:30:02.0: res[13]=[io  0x1000-0x1fff] res_to_dev_res add_size 1000 min_align 1000
[ 3925.185229] pcieport 0000:30:03.0: res[13]=[io  0x1000-0x0fff] res_to_dev_res add_size 1000 min_align 1000
[ 3925.185236] pcieport 0000:30:03.0: res[13]=[io  0x1000-0x1fff] res_to_dev_res add_size 1000 min_align 1000
[ 3925.185242] pcieport 0000:30:00.0: BAR 13: no space for [io  size 0x1000]
[ 3925.185248] pcieport 0000:30:00.0: BAR 13: failed to assign [io  size 0x1000]
[ 3925.185254] pcieport 0000:30:01.0: BAR 13: no space for [io  size 0x1000]
[ 3925.185260] pcieport 0000:30:01.0: BAR 13: failed to assign [io  size 0x1000]
[ 3925.185266] pcieport 0000:30:02.0: BAR 13: no space for [io  size 0x1000]
[ 3925.185272] pcieport 0000:30:02.0: BAR 13: failed to assign [io  size 0x1000]
[ 3925.185278] pcieport 0000:30:03.0: BAR 13: no space for [io  size 0x1000]
[ 3925.185284] pcieport 0000:30:03.0: BAR 13: failed to assign [io  size 0x1000]
[ 3925.185291] pcieport 0000:30:03.0: BAR 13: no space for [io  size 0x1000]
[ 3925.185297] pcieport 0000:30:03.0: BAR 13: failed to assign [io  size 0x1000]
[ 3925.185303] pcieport 0000:30:02.0: BAR 13: no space for [io  size 0x1000]
[ 3925.185309] pcieport 0000:30:02.0: BAR 13: failed to assign [io  size 0x1000]
[ 3925.185315] pcieport 0000:30:01.0: BAR 13: no space for [io  size 0x1000]
[ 3925.185321] pcieport 0000:30:01.0: BAR 13: failed to assign [io  size 0x1000]
[ 3925.185327] pcieport 0000:30:00.0: BAR 13: no space for [io  size 0x1000]
[ 3925.185333] pcieport 0000:30:00.0: BAR 13: failed to assign [io  size 0x1000]
[ 3925.219458] pcieport 0000:d7:00.0: bridge window [io  0x1000-0x0fff] to [bus d8] add_size 1000
[ 3925.219478] pcieport 0000:d7:01.0: bridge window [io  0x1000-0x0fff] to [bus d9] add_size 1000
[ 3925.219495] pcieport 0000:d7:02.0: bridge window [io  0x1000-0x0fff] to [bus da] add_size 1000
[ 3925.219519] pcieport 0000:d7:00.0: res[13]=[io  0x1000-0x0fff] res_to_dev_res add_size 1000 min_align 1000
[ 3925.219526] pcieport 0000:d7:00.0: res[13]=[io  0x1000-0x1fff] res_to_dev_res add_size 1000 min_align 1000
[ 3925.219533] pcieport 0000:d7:01.0: res[13]=[io  0x1000-0x0fff] res_to_dev_res add_size 1000 min_align 1000
[ 3925.219540] pcieport 0000:d7:01.0: res[13]=[io  0x1000-0x1fff] res_to_dev_res add_size 1000 min_align 1000
[ 3925.219546] pcieport 0000:d7:02.0: res[13]=[io  0x1000-0x0fff] res_to_dev_res add_size 1000 min_align 1000
[ 3925.219553] pcieport 0000:d7:02.0: res[13]=[io  0x1000-0x1fff] res_to_dev_res add_size 1000 min_align 1000
[ 3925.219563] pcieport 0000:d7:00.0: BAR 13: no space for [io  size 0x1000]
[ 3925.219569] pcieport 0000:d7:00.0: BAR 13: failed to assign [io  size 0x1000]
[ 3925.219576] pcieport 0000:d7:01.0: BAR 13: no space for [io  size 0x1000]
[ 3925.219582] pcieport 0000:d7:01.0: BAR 13: failed to assign [io  size 0x1000]
[ 3925.219589] pcieport 0000:d7:02.0: BAR 13: no space for [io  size 0x1000]
[ 3925.219595] pcieport 0000:d7:02.0: BAR 13: failed to assign [io  size 0x1000]
[ 3925.219603] pcieport 0000:d7:02.0: BAR 13: no space for [io  size 0x1000]
[ 3925.219609] pcieport 0000:d7:02.0: BAR 13: failed to assign [io  size 0x1000]
[ 3925.219616] pcieport 0000:d7:01.0: BAR 13: no space for [io  size 0x1000]
[ 3925.219622] pcieport 0000:d7:01.0: BAR 13: failed to assign [io  size 0x1000]
[ 3925.219628] pcieport 0000:d7:00.0: BAR 13: no space for [io  size 0x1000]
[ 3925.219634] pcieport 0000:d7:00.0: BAR 13: failed to assign [io  size 0x1000]
[ 4047.457696] Bits 55-60 of /proc/PID/pagemap entries are about to stop being page-shift some time soon. See the linux/Documentation/vm/pagemap.txt for details.
[ 4050.526666] vfio_ecap_init: 0000:31:00.0 hiding ecap 0x19@0x2a0
[ 4050.526755] vfio_ecap_init: 0000:31:00.0 hiding ecap 0x1e@0x310
[ 4051.246821] vfio_ecap_init: 0000:32:00.0 hiding ecap 0x19@0x2a0
[ 4051.246905] vfio_ecap_init: 0000:32:00.0 hiding ecap 0x1e@0x310
[ 4051.967004] vfio_ecap_init: 0000:33:00.0 hiding ecap 0x19@0x2a0
[ 4051.967097] vfio_ecap_init: 0000:33:00.0 hiding ecap 0x1e@0x310
[ 4052.789936] vfio_ecap_init: 0000:34:00.0 hiding ecap 0x19@0x2a0
[ 4052.790016] vfio_ecap_init: 0000:34:00.0 hiding ecap 0x1e@0x310
[ 4053.608655] vfio_ecap_init: 0000:d8:00.0 hiding ecap 0x19@0x2a0
[ 4053.608665] vfio_ecap_init: 0000:d8:00.0 hiding ecap 0x1e@0x310
[ 4054.421707] vfio_ecap_init: 0000:d9:00.0 hiding ecap 0x19@0x2a0
[ 4054.421718] vfio_ecap_init: 0000:d9:00.0 hiding ecap 0x1e@0x310
[ 4055.234802] vfio_ecap_init: 0000:da:00.0 hiding ecap 0x19@0x2a0
[ 4055.234813] vfio_ecap_init: 0000:da:00.0 hiding ecap 0x1e@0x310
[ 4056.046879] vfio_ecap_init: 0000:db:00.0 hiding ecap 0x19@0x2a0
[ 4056.046890] vfio_ecap_init: 0000:db:00.0 hiding ecap 0x1e@0x310
```

**Comment by jimharris** [comment] 2018-09-27 17:09
Only the SPDK NVMe driver is supported in multi-process mode.  Other libraries in SPDK would need significant changes to support multi-process mode.

**Comment by darsto** [comment] 2018-09-28 11:29
> Only the SPDK NVMe driver is supported in multi-process mode. Other libraries in SPDK would need significant changes to support multi-process mode.

@jimharris 
I don't think those would be significant changes. In fact, I'd expect vhost to work in secondary process just fine now. I guess we have a bug rather than a missing feature.

@wuzhouhui 
>In kernel space, the `vfio_fops_unl_ioctl()` returns `-EINVAL` if `container->iommu_driver` is null. `container->iommu_driver` is null because the secondary process did call ioctl(VFIO_SET_IOMMU) before. DPDK will call ioctl(VFIO_SET_IOMMU) only for primary process (see `vfio_set_iommu_type` called in `rte_vfio_setup_device` of DPDK code):

That's true, although container->iommu_driver still shouldn't be null. It's the same container for primary and secondary process after all. Maybe primary process didn't call VFIO_SET_IOMMU either?. I'll try to debug this.

**Comment by jimharris** [comment] 2018-09-28 14:39
@darsto - they would be very significant changes.  Things like spdk_thread_send_msg and spdk_for_each_channel would need to be completely rethought since we can't pass function pointers across process boundaries.

**Comment by darsto** [comment] 2018-09-28 16:38
@jimharris what would we use them for?
I'm thinking of a very simple scenario where secondary process with an NVMe
disk exposes a vhost target. Being a secondary process means there's
different memory and PCI management, but the rest of the functionality
should work fine. The usecase from this issue should really just work IMO.

**Comment by jimharris** [comment] 2018-09-28 16:54
What would we use spdk_thread_send_msg and spdk_for_each_channel for?

We use them all over the place in the bdev layer.  It's used to coordinate resets and enforce QoS limits.  The NVMe-oF target uses it extensively to coordinate infrequent control path operations.  Blobstore uses it for cluster allocation synchronization.

I guess I don't understand why this has to be a secondary process.  Maybe this should theoretically work - but sharing a bdev across multiple processes will certainly not work.

**Comment by darsto** [comment] 2018-09-28 17:18
> We use them all over the place in the bdev layer. It's used to coordinate
resets and enforce QoS limits. The NVMe-oF target uses it extensively to
coordinate infrequent control path operations. Blobstore uses it for
cluster allocation synchronization.

@jimharris Ah right, I see. But this still doesn't explain the vfio errors.

**Comment by wuzhouhui** [comment] 2018-09-29 05:07
> 
> That's true, although container->iommu_driver still shouldn't be null. It's the same container for primary and secondary process after all. Maybe primary process didn't call VFIO_SET_IOMMU either?. I'll try to debug this.

I have found something useful.

If process is secondary, the DPDK will request container fd from primary (see `rte_vfio_get_container_fd()`). When primary get this request, it will open `/dev/vfio/vfio` (see `rte_vfio_get_container_fd()` called in `vfio_mp_primary()`) and return this fd as container fd directly. So the secondary's container fd is different from primary process. After the fd is sent, the primary will close() it. I think this should be the bug of DPDK.

**Comment by wuzhouhui** [comment] 2018-09-29 05:46
The issue disappeared after apply following ugly patch to DPDK:
```
Index: dpdk/lib/librte_eal/linuxapp/eal/eal_vfio.c
===================================================================
--- dpdk.orig/lib/librte_eal/linuxapp/eal/eal_vfio.c
+++ dpdk/lib/librte_eal/linuxapp/eal/eal_vfio.c
@@ -1040,6 +1040,8 @@ vfio_has_supported_extensions(int vfio_c
 	return 0;
 }
 
+int g_vfio_container_fd = -1;
+
 int
 rte_vfio_get_container_fd(void)
 {
@@ -1052,7 +1054,10 @@ rte_vfio_get_container_fd(void)
 
 	/* if we're in a primary process, try to open the container */
 	if (internal_config.process_type == RTE_PROC_PRIMARY) {
-		vfio_container_fd = open(VFIO_CONTAINER_PATH, O_RDWR);
+		if (g_vfio_container_fd < 0) {
+			g_vfio_container_fd = open(VFIO_CONTAINER_PATH, O_RDWR);
+		}
+		vfio_container_fd = g_vfio_container_fd;
 		if (vfio_container_fd < 0) {
 			RTE_LOG(ERR, EAL, "  cannot open VFIO container, "
 					"error %i (%s)\n", errno, strerror(errno));
Index: dpdk/lib/librte_eal/linuxapp/eal/eal_vfio_mp_sync.c
===================================================================
--- dpdk.orig/lib/librte_eal/linuxapp/eal/eal_vfio_mp_sync.c
+++ dpdk/lib/librte_eal/linuxapp/eal/eal_vfio_mp_sync.c
@@ -83,8 +83,10 @@ vfio_mp_primary(const struct rte_mp_msg
 	reply.len_param = sizeof(*r);
 
 	ret = rte_mp_reply(&reply, peer);
+	/*
 	if (m->req == SOCKET_REQ_CONTAINER && fd >= 0)
 		close(fd);
+	*/
 	return ret;
 }
  ```

**Comment by darsto** [comment] 2018-10-03 12:57
@wuzhouhui I confirm it's a bug. I have just submitted a fix to DPDK:
http://patches.dpdk.org/patch/45940/
It fixes the problem for me.

Let's see what DPDK folks will say.

**Comment by wuzhouhui** [comment] 2018-10-08 01:07
> @wuzhouhui I confirm it's a bug. I have just submitted a fix to DPDK:
> http://patches.dpdk.org/patch/45940/
> It fixes the problem for me.
> 
> Let's see what DPDK folks will say.

This patch works for we too.

**Comment by darsto** [comment] 2018-10-08 07:07
The patch got acked on DPDK, so closing this issue.

**Closed** 2018-10-08 07:07 UTC
