### ISSUE TITLE
NVMF hits assert during nvmf_shutdown_tc3

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1285] opened 2020-03-17 12:55 UTC
See https://ci.spdk.io/results/autotest-per-patch/builds/6603/archive/nvmf-phy-autotest/build.log

**Comment by spdkci** [comment] 2020-03-17 12:55
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_6603.html

**Comment by AlekseyMarchuk** [comment] 2020-03-17 13:23
That was caused by my patch, I'll check it

**Comment by AlekseyMarchuk** [comment] 2020-03-17 13:36
I'm sorry, that was my mistake. I completely forgot that WC will be generated for any WR in the case of error and I naively assumed that we could remove several checks. Preparing a fix for that

**Comment by AlekseyMarchuk** [comment] 2020-03-17 13:52
I reverted part of the problematic patch https://review.spdk.io/gerrit/c/spdk/spdk/+/1334

**Comment by spdkci** [comment] 2020-03-17 23:31
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_6695.html

**Comment by spdkci** [comment] 2020-03-17 23:32
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_6693.html

**Comment by spdkci** [comment] 2020-03-17 23:33
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_6696.html

**Comment by spdkci** [comment] 2020-03-17 23:35
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_6698.html

**Comment by jimharris** [comment] 2020-03-17 23:49
Patch has been merged.  Let's give it until tomorrow before closing this issue though.

**Comment by spdkci** [comment] 2020-03-18 08:44
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_6661.html

**Comment by spdkci** [comment] 2020-03-18 10:04
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_6773.html

**Comment by changpe1** [comment] 2020-03-19 04:25
@mikeBashStuff Can you check the failure cases is rebased or not? thanks.

**Comment by peluse** [comment] 2020-03-20 14:22
FYI mine passed

**Comment by Seth5141** [comment] 2020-03-20 23:22
@AlekseyMarchuk's change has been merged, closing.

**Comment by shuhei-matsumoto** [comment] 2020-03-24 06:19
Seth commented closing. So I push close button.

**Closed by shuhei-matsumoto** 2020-03-24 06:19 UTC
Labels: Infrastructure, bug
