### ISSUE TITLE
Jenkins fails to fetch refs from gerrit

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1969] opened 2021-06-01 10:25 UTC
Intermittent networking issue affecting some of the hosts.

https://ci.spdk.io/results/autotest-per-patch/builds/48787/archive/lvol-vg-autotest/build.log

```
00:00:00.810   > git fetch --tags --force --progress -- https://review.spdk.io/gerrit/a/spdk/spdk $GERRIT_REFSPEC:refs/local # timeout=5
00:00:01.522  ERROR: Error cloning remote repo 'origin'
00:00:01.522  hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- https://review.spdk.io/gerrit/a/spdk/spdk $GERRIT_REFSPEC:refs/local" returned status code 128:
00:00:01.522  stdout: 
00:00:01.522  stderr: fatal: unable to access 'https://review.spdk.io/gerrit/a/spdk/spdk/': gnutls_handshake() failed: Error in the pull function.
00:00:01.522  
00:00:01.522  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2450)
00:00:01.522  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2051)
00:00:01.522  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:84)
00:00:01.522  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:573)
00:00:01.522  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:802)
00:00:01.522  	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
00:00:01.522  	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
00:00:01.522  	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
00:00:01.522  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
00:00:01.522  	at hudson.remoting.Request$2.run(Request.java:375)
00:00:01.522  	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
00:00:01.522  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:00:01.522  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
00:00:01.522  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
00:00:01.522  	at java.lang.Thread.run(Thread.java:748)
00:00:01.522  	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to VM-host-WFP1
00:00:01.522  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
00:00:01.522  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
00:00:01.522  		at hudson.remoting.Channel.call(Channel.java:1001)
00:00:01.522  		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
00:00:01.522  		at sun.reflect.GeneratedMethodAccessor556.invoke(Unknown Source)
00:00:01.522  		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:00:01.522  		at java.lang.reflect.Method.invoke(Method.java:498)
00:00:01.522  		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
00:00:01.522  		at com.sun.proxy.$Proxy91.execute(Unknown Source)
00:00:01.522  		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1219)
00:00:01.522  		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1297)
00:00:01.522  		at hudson.scm.SCM.checkout(SCM.java:505)
00:00:01.522  		at hudson.model.AbstractProject.checkout(AbstractProject.java:1206)
00:00:01.522  		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
00:00:01.522  		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
00:00:01.522  		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
00:00:01.522  		at hudson.model.Run.execute(Run.java:1894)
00:00:01.522  		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
00:00:01.522  		at hudson.model.ResourceController.execute(ResourceController.java:97)
00:00:01.522  		at hudson.model.Executor.run(Executor.java:428)
00:00:01.522  ERROR: Error cloning remote repo 'origin'
00:00:01.522  Retrying after 10 seconds
```

**Comment by spdkci** [comment] 2021-06-01 10:26
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_48787.html

**Comment by spdkci** [comment] 2021-06-02 12:28
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_48860.html

**Comment by KKaras169169** [comment] 2021-06-16 07:24
I have found something similar, with connection timeout this time:

00:00:00.497  using GIT_ASKPASS to set credentials SPDKCI HTTPS Credentials
00:00:00.499  Setting http proxy: proxy-chain.intel.com:911
00:00:00.500   > git fetch --tags --force --progress -- https://review.spdk.io/gerrit/a/spdk/spdk $GERRIT_REFSPEC:refs/local # timeout=5
00:05:00.506  ERROR: Timeout after 5 minutes
00:05:00.578  ERROR: Error cloning remote repo 'origin'
00:05:00.578  hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- https://review.spdk.io/gerrit/a/spdk/spdk $GERRIT_REFSPEC:refs/local" returned status code 128:
00:05:00.578  stdout: 
00:05:00.578  stderr: fatal: the remote end hung up unexpectedly

**Comment by spdkci** [comment] 2021-06-16 07:25
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_49868.html

**Comment by spdkci** [comment] 2021-06-16 07:26
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_49867.html

**Comment by spdkci** [comment] 2021-06-16 07:26
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_49866.html

**Comment by spdkci** [comment] 2021-06-16 07:26
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_49864.html

**Comment by spdkci** [comment] 2021-06-17 10:38
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_50137.html

**Comment by spdkci** [comment] 2021-06-17 10:50
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_50131.html

**Comment by spdkci** [comment] 2021-06-17 11:42
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_50143.html

**Comment by spdkci** [comment] 2021-06-17 13:38
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_50136.html

**Comment by spdkci** [comment] 2021-06-18 02:10
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_50130.html

**Comment by spdkci** [comment] 2021-06-18 05:49
Another instance of this failure. Reported by @ChengqiangMeng. log: https://ci.spdk.io/public_build/autotest-per-patch_50242.html

**Comment by spdkci** [comment] 2021-06-18 05:56
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_50233.html

**Comment by spdkci** [comment] 2021-06-18 07:16
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_50239.html

**Comment by spdkci** [comment] 2021-06-18 07:25
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_50226.html

**Comment by spdkci** [comment] 2021-06-18 07:26
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_50171.html

**Comment by spdkci** [comment] 2021-06-18 07:28
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_50204.html

**Comment by karlatec** [comment] 2021-06-28 08:21
We won't be able to fix network or proxy issues on our side, but the occurrences of this issue was limited using CI "retry rules".
Last occurrence was over a week ago, so we could probably close this one.

**Comment by spdkci** [comment] 2021-07-05 14:40
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51665.html

**Comment by spdkci** [comment] 2021-07-05 14:42
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51669.html

**Comment by spdkci** [comment] 2021-07-05 14:47
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51667.html

**Comment by karlatec** [comment] 2021-07-06 07:14
Reopening due to recent network issue in CI environment. A lot of builds failed to fetch sources.

**Comment by spdkci** [comment] 2021-07-06 07:16
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51736.html

**Comment by spdkci** [comment] 2021-07-06 07:16
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51729.html

**Comment by spdkci** [comment] 2021-07-06 07:21
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_51666.html

**Comment by spdkci** [comment] 2021-07-06 07:24
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51743.html

**Comment by spdkci** [comment] 2021-07-06 07:25
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_51712.html

**Comment by spdkci** [comment] 2021-07-06 07:25
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_51668.html

**Comment by spdkci** [comment] 2021-07-06 07:26
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51698.html

**Comment by spdkci** [comment] 2021-07-06 07:26
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51724.html

**Comment by spdkci** [comment] 2021-07-06 07:26
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51704.html

**Comment by spdkci** [comment] 2021-07-06 07:29
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_51717.html

**Comment by spdkci** [comment] 2021-07-06 07:29
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_51722.html

**Comment by spdkci** [comment] 2021-07-06 07:29
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51714.html

**Comment by spdkci** [comment] 2021-07-06 07:30
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_51672.html

**Comment by spdkci** [comment] 2021-07-06 07:30
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51709.html

**Comment by spdkci** [comment] 2021-07-06 07:42
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51719.html

**Comment by spdkci** [comment] 2021-07-12 06:10
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_52430.html

**Comment by spdkci** [comment] 2021-07-12 08:50
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_52446.html

**Comment by spdkci** [comment] 2021-07-12 09:44
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_52449.html

**Comment by spdkci** [comment] 2021-07-12 10:01
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_52450.html

**Comment by spdkci** [comment] 2021-07-12 13:58
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_52453.html

**Comment by spdkci** [comment] 2021-07-13 06:57
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_52564.html

**Comment by spdkci** [comment] 2021-07-29 13:47
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_54492.html

**Comment by spdkci** [comment] 2021-07-29 13:53
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_54491.html

**Comment by spdkci** [comment] 2021-07-29 13:58
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_54490.html

**Comment by spdkci** [comment] 2021-07-29 14:12
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_54488.html

**Comment by spdkci** [comment] 2021-07-29 14:14
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_54489.html

**Comment by spdkci** [comment] 2021-07-29 14:49
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_54495.html

**Comment by spdkci** [comment] 2021-08-11 13:03
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_55784.html

**Comment by spdkci** [comment] 2021-09-20 09:11
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_58504.html

**Comment by spdkci** [comment] 2021-09-20 09:12
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_58505.html

**Comment by spdkci** [comment] 2021-09-20 10:38
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_58507.html

**Comment by spdkci** [comment] 2021-09-20 10:40
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_58506.html

**Comment by spdkci** [comment] 2021-09-20 14:46
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_58509.html

**Comment by spdkci** [comment] 2021-09-20 14:46
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_58510.html

**Comment by spdkci** [comment] 2021-09-22 07:21
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_58561.html

**Comment by spdkci** [comment] 2021-09-23 04:00
Another instance of this failure. Reported by @xjjx. log: https://ci.spdk.io/public_build/autotest-per-patch_58704.html

**Comment by spdkci** [comment] 2021-09-23 18:23
Another instance of this failure. Reported by @mkenguva. log: https://ci.spdk.io/public_build/autotest-per-patch_58799.html

**Comment by spdkci** [comment] 2021-09-24 15:39
Another instance of this failure. Reported by @mkenguva. log: https://ci.spdk.io/public_build/autotest-per-patch_58802.html

**Comment by spdkci** [comment] 2021-09-24 22:04
Another instance of this failure. Reported by @mkenguva. log: https://ci.spdk.io/public_build/autotest-per-patch_58974.html

**Comment by spdkci** [comment] 2021-09-27 09:27
Another instance of this failure. Reported by @xjjx. log: https://ci.spdk.io/public_build/autotest-per-patch_59102.html

**Comment by spdkci** [comment] 2021-09-27 09:27
Another instance of this failure. Reported by @xjjx. log: https://ci.spdk.io/public_build/autotest-per-patch_59101.html

**Comment by spdkci** [comment] 2021-09-27 09:27
Another instance of this failure. Reported by @xjjx. log: https://ci.spdk.io/public_build/autotest-per-patch_59100.html

**Comment by spdkci** [comment] 2021-09-27 11:54
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_59108.html

**Comment by spdkci** [comment] 2021-09-27 11:56
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_59095.html

**Comment by spdkci** [comment] 2021-09-27 11:59
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_59107.html

**Comment by spdkci** [comment] 2021-09-27 11:59
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_59106.html

**Comment by spdkci** [comment] 2021-09-28 06:20
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_59116.html

**Comment by spdkci** [comment] 2021-09-29 04:14
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_59289.html

**Comment by spdkci** [comment] 2021-09-29 06:26
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_59255.html

**Comment by spdkci** [comment] 2021-09-29 07:23
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_59257.html

**Comment by spdkci** [comment] 2021-09-29 08:24
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59276.html

**Comment by spdkci** [comment] 2021-10-01 06:53
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_59474.html

**Comment by spdkci** [comment] 2021-10-01 09:15
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59484.html

**Comment by spdkci** [comment] 2021-10-01 11:48
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_59479.html

**Comment by spdkci** [comment] 2021-10-01 11:49
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_59478.html

**Comment by spdkci** [comment] 2021-10-01 11:49
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_59477.html

**Comment by spdkci** [comment] 2021-10-05 08:38
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_59565.html

**Comment by spdkci** [comment] 2021-10-05 08:42
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_59574.html

**Comment by spdkci** [comment] 2021-10-05 09:03
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_59552.html

**Comment by spdkci** [comment] 2021-10-05 09:03
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_59543.html

**Comment by spdkci** [comment] 2021-10-05 09:04
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_59549.html

**Comment by spdkci** [comment] 2021-10-05 21:34
Another instance of this failure. Reported by @mkenguva. log: https://ci.spdk.io/public_build/autotest-per-patch_59546.html

**Comment by spdkci** [comment] 2021-10-06 06:20
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_59644.html

**Comment by spdkci** [comment] 2021-10-11 06:22
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_59730.html

**Comment by spdkci** [comment] 2021-11-23 11:22
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_62343.html

**Comment by spdkci** [comment] 2021-11-23 12:25
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_62347.html

**Comment by spdkci** [comment] 2021-11-23 12:28
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_62355.html

**Comment by spdkci** [comment] 2021-11-23 12:29
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_62353.html

**Comment by spdkci** [comment] 2021-11-23 13:11
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_62363.html

**Comment by spdkci** [comment] 2021-11-23 13:54
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_62366.html

**Comment by spdkci** [comment] 2021-11-23 13:55
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_62368.html

**Comment by spdkci** [comment] 2021-11-23 14:17
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_62372.html

**Comment by spdkci** [comment] 2021-11-24 09:45
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_62364.html

**Comment by spdkci** [comment] 2021-11-25 10:28
Another instance of this failure. Reported by @Maciej-Szulik. log: https://ci.spdk.io/public_build/autotest-per-patch_62336.html

**Comment by tomzawadzki** [comment] 2021-11-30 11:08
The latest report refer to completely different issue, rather than network related. 

First failure occurs at:
```
00:00:03.063   > git fetch --tags --force --progress -- https://review.spdk.io/gerrit/a/spdk/spdk refs/changes/66/10366/1:refs/local # timeout=5
00:00:17.216  ERROR: Error cloning remote repo 'origin'
00:00:17.216  hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- https://review.spdk.io/gerrit/a/spdk/spdk refs/changes/66/10366/1:refs/local" returned status code 128:
00:00:17.216  stdout: 
00:00:17.216  stderr: error: Could not read f7866a563fb0239392e1b1a46f2902ef237e74f0
00:00:17.216  remote: Counting objects: 1           
remote: Counting objects: 7317, done        
00:00:17.216  remote: Finding sources:   1% (42/4199)   
```
Then is followed by:
```
Resolving deltas:  72% (1477/2035), completed with 38 local objects.
00:00:17.216  fatal: pack has 558 unresolved deltas
00:00:17.216  fatal: fetch-pack: invalid index-pack output
```

Giving a quick look around for the cause, points to possibly `git fetch` missing some commits if done after shallow `git clone`. I believe there is optimization done during job execution to checkout minimal set of required changes.

@karlatec Could someone take a look at that ?

**Comment by mikeBashStuff** [comment] 2021-11-30 11:09
@tomzawadzki This was already fixed.

**Closed** 2021-11-30 15:26 UTC
Labels: Infrastructure, Intermittent Failure

**Comment by spdkci** [comment] 2021-12-22 16:56
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_64421.html
