### ISSUE TITLE
[nvmf_vfio_user] group != NULL assertion failed

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#2092] opened 2021-08-13 23:35 UTC
https://ci.spdk.io/results/autotest-per-patch/builds/56029/archive/nvmf-tcp-uring-vg-autotest/build.log
https://ci.spdk.io/public_build/autotest-per-patch_56029.html

```
00:09:34.207  EAL: No available 1048576 kB hugepages reported
00:09:34.404  TELEMETRY: No legacy callbacks, legacy socket not created
00:09:39.469  Initializing NVMe Controllers
00:09:39.469  Attached to NVMe over Fabrics controller at /var/run/vfio-user/domain/vfio-user1/1:: nqn.2019-07.io.spdk:cnode1
00:09:39.469  Associating VFIOUSER (/var/run/vfio-user/domain/vfio-user1/1) NSID 1 with lcore 1
00:09:39.469  Initialization complete. Launching workers.
00:09:39.469  ========================================================
00:09:39.469                                                                                                           Latency(us)
00:09:39.469  Device Information                                                   :       IOPS      MiB/s    Average        min        max
00:09:39.469  VFIOUSER (/var/run/vfio-user/domain/vfio-user1/1) NSID 1 from core  1:   66051.20     258.01    1937.58     960.08    3268.32
00:09:39.469  ========================================================
00:09:39.469  Total                                                                :   66051.20     258.01    1937.58     960.08    3268.32
00:09:39.469  
00:09:39.471   13:02:57	-- nvmf/target/nvmf_vfio_user.sh@47 -- # sleep 1
00:09:40.476   13:02:58	-- nvmf/target/nvmf_vfio_user.sh@48 -- # /home/vagrant/spdk_repo/spdk/build/examples/perf -r 'trtype:VFIOUSER traddr:/var/run/vfio-user/domain/vfio-user1/1 subnqn:nqn.2019-07.io.spdk:cnode1' -s 256 -g -q 128 -o 4096 -w write -t 5 -c 0x2
00:09:40.493  [2021-08-13 13:02:58.721154] Starting SPDK v21.10-pre git sha1 6a5aed64e / DPDK 21.05.0 initialization...
00:09:40.493  [2021-08-13 13:02:58.721466] [ DPDK EAL parameters: [2021-08-13 13:02:58.721589] perf [2021-08-13 13:02:58.721648] --no-shconf [2021-08-13 13:02:58.721696] -c 0x2 [2021-08-13 13:02:58.721740] -m 256 [2021-08-13 13:02:58.721774] --no-pci [2021-08-13 13:02:58.721827] --single-file-segments [2021-08-13 13:02:58.721876] --log-level=lib.eal:6 [2021-08-13 13:02:58.721922] --log-level=lib.cryptodev:5 [2021-08-13 13:02:58.721993] --log-level=user1:6 [2021-08-13 13:02:58.722049] --iova-mode=pa [2021-08-13 13:02:58.722096] --base-virtaddr=0x200000000000 [2021-08-13 13:02:58.722140] --match-allocations [2021-08-13 13:02:58.722184] --file-prefix=spdk_pid27034 [2021-08-13 13:02:58.722228] ]
00:09:40.509  EAL: No available 1048576 kB hugepages reported
00:09:40.708  TELEMETRY: No legacy callbacks, legacy socket not created
00:09:45.771  Initializing NVMe Controllers
00:09:45.771  Attached to NVMe over Fabrics controller at /var/run/vfio-user/domain/vfio-user1/1:: nqn.2019-07.io.spdk:cnode1
00:09:45.771  Associating VFIOUSER (/var/run/vfio-user/domain/vfio-user1/1) NSID 1 with lcore 1
00:09:45.771  Initialization complete. Launching workers.
00:09:45.771  ========================================================
00:09:45.771                                                                                                           Latency(us)
00:09:45.771  Device Information                                                   :       IOPS      MiB/s    Average        min        max
00:09:45.771  VFIOUSER (/var/run/vfio-user/domain/vfio-user1/1) NSID 1 from core  1:   63243.20     247.04    2023.64     924.20    3309.53
00:09:45.771  ========================================================
00:09:45.771  Total                                                                :   63243.20     247.04    2023.64     924.20    3309.53
00:09:45.771  
00:09:45.774   13:03:04	-- nvmf/target/nvmf_vfio_user.sh@49 -- # sleep 1
00:09:46.779   13:03:05	-- nvmf/target/nvmf_vfio_user.sh@50 -- # /home/vagrant/spdk_repo/spdk/build/examples/reconnect -r 'trtype:VFIOUSER traddr:/var/run/vfio-user/domain/vfio-user1/1 subnqn:nqn.2019-07.io.spdk:cnode1' -g -q 32 -o 4096 -w randrw -M 50 -t 5 -c 0xE
00:09:46.801  [2021-08-13 13:03:05.028657] Starting SPDK v21.10-pre git sha1 6a5aed64e / DPDK 21.05.0 initialization...
00:09:46.801  [2021-08-13 13:03:05.029219] [ DPDK EAL parameters: [2021-08-13 13:03:05.029321] reconnect [2021-08-13 13:03:05.029488] --no-shconf [2021-08-13 13:03:05.029578] -c 0xE [2021-08-13 13:03:05.029709] --single-file-segments [2021-08-13 13:03:05.029798] --log-level=lib.eal:6 [2021-08-13 13:03:05.029891] --log-level=lib.cryptodev:5 [2021-08-13 13:03:05.030015] --log-level=user1:6 [2021-08-13 13:03:05.030118] --iova-mode=pa [2021-08-13 13:03:05.030197] --base-virtaddr=0x200000000000 [2021-08-13 13:03:05.030274] --match-allocations [2021-08-13 13:03:05.030359] --file-prefix=spdk_pid27041 [2021-08-13 13:03:05.030438] ]
00:09:46.829  EAL: No available 1048576 kB hugepages reported
00:09:46.938  TELEMETRY: No legacy callbacks, legacy socket not created
00:09:51.996  nvmf_tgt: nvmf.c:1077: spdk_nvmf_qpair_disconnect: Assertion `group != NULL' failed.
00:09:51.998  Initializing NVMe Controllers
00:09:51.998  Attaching to NVMe over Fabrics controller at /var/run/vfio-user/domain/vfio-user1/1:: nqn.2019-07.io.spdk:cnode1
00:09:51.998  Attached to NVMe over Fabrics controller at /var/run/vfio-user/domain/vfio-user1/1:: nqn.2019-07.io.spdk:cnode1
00:09:51.998  Associating VFIOUSER (/var/run/vfio-user/domain/vfio-user1/1) with lcore 1
00:09:51.998  Associating VFIOUSER (/var/run/vfio-user/domain/vfio-user1/1) with lcore 2
00:09:51.998  Associating VFIOUSER (/var/run/vfio-user/domain/vfio-user1/1) with lcore 3
00:09:51.998  Initialization complete. Launching workers.
00:09:51.998  Starting thread on core 2
00:09:51.998  Starting thread on core 1
00:09:51.998  Starting thread on core 3
00:09:52.002   13:03:10	-- nvmf/target/nvmf_vfio_user.sh@51 -- # sleep 1
00:09:53.006   13:03:11	-- nvmf/target/nvmf_vfio_user.sh@41 -- # for i in $(seq 1 $NUM_DEVICES)
00:09:53.006   13:03:11	-- nvmf/target/nvmf_vfio_user.sh@42 -- # test_traddr=/var/run/vfio-user/domain/vfio-user2/2
00:09:53.006   13:03:11	-- nvmf/target/nvmf_vfio_user.sh@43 -- # test_subnqn=nqn.2019-07.io.spdk:cnode2
00:09:53.006   13:03:11	-- nvmf/target/nvmf_vfio_user.sh@44 -- # /home/vagrant/spdk_repo/spdk/build/examples/identify -r 'trtype:VFIOUSER traddr:/var/run/vfio-user/domain/vfio-user2/2 subnqn:nqn.2019-07.io.spdk:cnode2' -g -L nvme -L nvme_vfio -L vfio_pci
00:09:53.025  [2021-08-13 13:03:11.253757] Starting SPDK v21.10-pre git sha1 6a5aed64e / DPDK 21.05.0 initialization...
00:09:53.025  [2021-08-13 13:03:11.254006] [ DPDK EAL parameters: [2021-08-13 13:03:11.254067] identify [2021-08-13 13:03:11.254115] --no-shconf [2021-08-13 13:03:11.254185] -c 0x1 [2021-08-13 13:03:11.254248] -n 1 [2021-08-13 13:03:11.254290] -m 0 [2021-08-13 13:03:11.254338] --no-pci [2021-08-13 13:03:11.254375] --single-file-segments [2021-08-13 13:03:11.254432] --log-level=lib.eal:6 [2021-08-13 13:03:11.254495] --log-level=lib.cryptodev:5 [2021-08-13 13:03:11.254538] --log-level=user1:6 [2021-08-13 13:03:11.254580] --iova-mode=pa [2021-08-13 13:03:11.254631] --base-virtaddr=0x200000000000 [2021-08-13 13:03:11.254690] --match-allocations [2021-08-13 13:03:11.254744] --file-prefix=spdk_pid27059 [2021-08-13 13:03:11.254802] ]
00:09:53.045  EAL: No available 1048576 kB hugepages reported
00:09:53.148  TELEMETRY: No legacy callbacks, legacy socket not created
00:09:53.166  [2021-08-13 13:03:11.394936] nvme_vfio_user.c: 310:nvme_vfio_ctrlr_scan: *DEBUG*: Scan controller : /var/run/vfio-user/domain/vfio-user2/2
00:09:56.387  [2021-08-13 13:03:14.616135] vfio_user.c: 399:vfio_user_dev_setup: *ERROR*: Check VFIO_USER_VERSION message failed
00:09:56.387  [2021-08-13 13:03:14.616439] vfio_user_pci.c: 385:spdk_vfio_user_setup: *ERROR*: Error to setup vfio-user via path /var/run/vfio-user/domain/vfio-user2/2/cntrl
00:09:56.388  [2021-08-13 13:03:14.616572] nvme_vfio_user.c: 230:nvme_vfio_ctrlr_construct: *ERROR*: Error to setup vfio device
00:09:56.388  [2021-08-13 13:03:14.616686] nvme.c: 680:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD: /var/run/vfio-user/domain/vfio-user2/2
00:09:56.388  [2021-08-13 13:03:14.616794] nvme.c: 813:nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
00:09:56.388  [2021-08-13 13:03:14.616899] nvme.c: 995:spdk_nvme_connect: *ERROR*: Create probe context failed
00:09:56.389  spdk_nvme_connect() failed
00:09:56.396  test/nvmf/target/nvmf_vfio_user.sh: line 41: 26999 Aborted                 (core dumped) "${NVMF_APP[@]}" -m 0x1
00:09:56.396    13:03:14	-- nvmf/target/nvmf_vfio_user.sh@44 -- # trap - ERR
00:09:56.396    13:03:14	-- nvmf/target/nvmf_vfio_user.sh@44 -- # print_backtrace
00:09:56.396    13:03:14	-- common/autotest_common.sh@985 -- # [[ ehxBET =~ e ]]
00:09:56.396    13:03:14	-- common/autotest_common.sh@987 -- # args=("${BASH_ARGV[@]}")
00:09:56.396    13:03:14	-- common/autotest_common.sh@987 -- # local args
00:09:56.396    13:03:14	-- common/autotest_common.sh@989 -- # xtrace_disable
00:09:56.396    13:03:14	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:09:56.396    13:03:14	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:09:56.397    13:03:14	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:09:56.397    13:03:14	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:09:56.397    13:03:14	-- common/autotest_common.sh@19 -- # set +x
00:09:56.398  ========== Backtrace start: ==========
00:09:56.398  
00:09:56.405  in test/nvmf/target/nvmf_vfio_user.sh:44 -> main(["--transport=tcp"])
00:09:56.405       ...
00:09:56.405     39  	done
00:09:56.405     40  	
00:09:56.405     41  	for i in $(seq 1 $NUM_DEVICES); do
00:09:56.405     42  		test_traddr=/var/run/vfio-user/domain/vfio-user$i/$i
00:09:56.405     43  		test_subnqn=nqn.2019-07.io.spdk:cnode$i
00:09:56.405  => 44  		$SPDK_EXAMPLE_DIR/identify -r "trtype:$TEST_TRANSPORT traddr:$test_traddr subnqn:$test_subnqn" -g -L nvme -L nvme_vfio -L vfio_pci
00:09:56.405     45  		sleep 1
00:09:56.405     46  		$SPDK_EXAMPLE_DIR/perf -r "trtype:$TEST_TRANSPORT traddr:$test_traddr subnqn:$test_subnqn" -s 256 -g -q 128 -o 4096 -w read -t 5 -c 0x2
00:09:56.405     47  		sleep 1
00:09:56.405     48  		$SPDK_EXAMPLE_DIR/perf -r "trtype:$TEST_TRANSPORT traddr:$test_traddr subnqn:$test_subnqn" -s 256 -g -q 128 -o 4096 -w write -t 5 -c 0x2
00:09:56.405     49  		sleep 1
00:09:56.405       ...
```

**Comment by spdkci** [comment] 2021-08-13 23:36
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_56029.html

**Comment by changpe1** [comment] 2021-08-14 03:05
I was thinking this issue maybe caused by recent asynchronous NVMe IO creation patches, I bisected it was introduced via commit 0d0524b9e0.

**Comment by changpe1** [comment] 2021-08-16 06:55
commit 0d0524b9 can cause this issue, but this commit isn't the root cause for it, just because the deferred response changes the execution order sometimes.

**Comment by changpe1** [comment] 2021-08-16 07:12
The test suite before calling `reconnect` left a writeable DMA map in the libvfio-user, and when the new `reconnect` test starts, that left DMA map is in a global list which will overwrite controller data structure.  We need to have a cleanup in target.
1. call `vfu_setup_device_dma` when there is a new socket connection, while here, it means to start a new identify or perf in client.
2. call `vfu_destroy_device_dma` when the socket connection was broken, e.g: kill perf client. The API isn't exist for now, need to add it in libvfio-user first.

For this case, we didn't kill perf in client, even with 2) we still need to cleanup the left DMA maps, but 2) is still required to address kill QEMU or kill perf client cases.

**Comment by changpe1** [comment] 2021-08-16 08:45
diff --git a/lib/dma.h b/lib/dma.h
index 29809d3..1bfef09 100644
--- a/lib/dma.h
+++ b/lib/dma.h
@@ -245,7 +245,7 @@ dma_map_sg(dma_controller_t *dma, dma_sg_t *sg, struct iovec *iov,
             return ERROR_INT(EFAULT);
         }
-        if (sg->writeable) {
+        if (sg[i].writeable) {
             if (dma->dirty_pgsize > 0) {
                 _dma_mark_dirty(dma, region, sg);
             }
@@ -282,8 +282,8 @@ dma_unmap_sg(dma_controller_t *dma, const dma_sg_t *sg,
             /* bad region */
             continue;
         }
-        if (sg->writeable) {
-            LIST_REMOVE(sg, entry);
+        if (sg[i].writeable) {
+            LIST_REMOVE(&sg[i], entry);
         }
         vfu_log(dma->vfu_ctx, LOG_DEBUG, "unmap %p-%p",
                 sg[i].dma_addr + sg[i].offset,
@@ -305,6 +305,8 @@ dma_controller_dirty_page_get(dma_controller_t *dma, vfu_dma_addr_t add

**Comment by changpe1** [comment] 2021-08-16 08:49
Issue disappeared after apply above code in libvfio-user.

**Comment by jlevon** [comment] 2021-08-16 09:43
https://github.com/nutanix/libvfio-user/pull/586

**Comment by changpe1** [comment] 2021-08-17 01:39
> [nutanix/libvfio-user#586](https://github.com/nutanix/libvfio-user/pull/586)

thanks, tests passed.

**Comment by changpe1** [comment] 2021-08-18 05:08
Here is the patch https://review.spdk.io/gerrit/c/spdk/spdk/+/9207 to update the submodule.

**Comment by changpe1** [comment] 2021-08-19 07:39
Patch has been merged, closing this issue now.

**Closed by changpe1** 2021-08-19 07:39 UTC
Labels: bug, 3rd party issue, Intermittent Failure, Patches out for review
