### ISSUE TITLE
nvmf_shutdown_tc3: I/O connect with duplicate QID

### ISSUE THREAD

**Issue by benlwalker** [spdk/spdk#1323] opened 2020-03-30 20:09 UTC
```
ctrlr.c: 221:ctrlr_add_qpair_and_update_rsp: *ERROR*: Got I/O connect with duplicate QID 1
nvme_fabric.c: 454:nvme_fabric_qpair_connect: *ERROR*: Connect command failed
nvme_rdma.c:1203:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Failed to send an NVMe-oF Fabric CONNECT command
nvme_ctrlr.c: 373:spdk_nvme_ctrlr_alloc_io_qpair: *ERROR*: nvme_transport_ctrlr_connect_io_qpair() failed
```

NVMe-oF with RDMA transport. The test before it consisted of running bdevperf against the target, and then bdevperf was killed using SIGTERM. Then, when bdevperf reconnects, it gets the above error. It seems like the old connection hasn't been cleaned up on the target, although it should have because it was only a SIGTERM.

**Comment by benlwalker** [comment] 2020-03-30 20:10
https://ci.spdk.io/results/autotest-per-patch/builds/8281/archive/nvmf-phy-autotest/build.log

**Comment by jimharris** [comment] 2020-03-30 20:20
Is this a duplicate of #1096?

**Comment by changpe1** [comment] 2020-03-31 02:39
Can we use SIGTERM instead of kill -9 for the shutdown tests, I found if I used Ctrlr + C to kill the process, the NVMF target can destroy the related old controller resource.

**Comment by Seth5141** [comment] 2020-04-01 16:15
It is a duplicate @jimharris Thanks for pointing that out. We'll address this one from #1096

**Closed by Seth5141** 2020-04-01 16:15 UTC
