### ISSUE TITLE
iscsi fio.sh: fio takes 2 minutes to finish during the iscsi hotplug test - results in vpp or iscsi timeout

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1067] opened 2019-11-19 11:46 UTC
VPP autotest job times out at non obvious part of test script.
Checking the timing.txt it seems that fio.sh is sometimes taking much longer than expected.

## Expected Behavior
Timing.txt:
`autotest;iscsi_tgt;fio 18`
Usually this takes around 20 seconds on VPP autotest and iSCSI autotest jobs.

## Current Behavior
Timing.txt:
`autotest;iscsi_tgt;fio 113`
Timed out results take almost 2 minutes to run and fail much later in the test script when overall timer reaches 10 minutes.

## Context (Environment including OS version, SPDK version, etc.)
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50073.html

**Comment by Seth5141** [comment] 2019-11-19 23:42
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49619.html

**Comment by Seth5141** [comment] 2019-11-20 18:09
This appears to be a result of the iscsi hotplug test not exiting in a reasonable amount of time. On a normal build, the time during the iscsi_tgt break between destroying the raid bdev and the fio job finishing is about 1 second. However on both of the failed builds linked above, the time between destroying the raid bdev and the fio job finishing is nearly two minutes.
I think that this is generally related to FIO or the iscsi stack since it hits on both vpp and posix.

**Comment by Seth5141** [comment] 2019-11-20 18:11
@shuhei-matsumoto @ZiyeYang Do either of you have any idea why fio might hang during the hotplug test?

**Comment by shuhei-matsumoto** [comment] 2019-11-20 22:25
@Seth5141 

Thanks for your comment. Now I know this issue because I have seen this issue locally.

LUN (bdev) hotplug behavior is different after recent refinements. Connection is still active after removing LUN. LUN hotplug itself doesn't require exiting connection and this is the right behavior. 

Previous implementation had required exiting connection immediately unexpectedly. So previous behavior was wrong but good for test time.

I can reproduce locally and will investigate this issue. The test had additional 2 minutes but completed normally, so I hadn't investigated in detail yet. Sorry for my laziness. Please wait for my update.

We still have a missing piece for iSCSI hotplug. we don't support unit attention (asynchronous event notification) yet. This may be related with the issue.

If no unit attention caused this issue or not will be known after investigation or development of unit attention.

**Comment by shuhei-matsumoto** [comment] 2019-11-20 22:54
I'm watching the terminal editor when the issue occurs.

It looks that two minutes took at 
Jobs: 1 (f=1): [M(1),X(1)][100.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 00m:00s]

eta counted down 
```
Jobs: 1 (f=1): [M(1),X(1)][100.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 05m:00s]
Jobs: 1 (f=1): [M(1),X(1)][100.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 04m:00s]
Jobs: 1 (f=1): [M(1),X(1)][100.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 03m:00s]
Jobs: 1 (f=1): [M(1),X(1)][100.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 02m:00s]
Jobs: 1 (f=1): [M(1),X(1)][100.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 01m:00s]
Jobs: 1 (f=1): [M(1),X(1)][100.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 00m:00s]

```But stops here.

Ctrl + C showed the following backtrace, and could exit test immediately.

```
========== Backtrace start: ==========

in /home/spdk/spdk/test/iscsi_tgt/common.sh:62 -> cleanup_veth_interfaces()
     ...
   57                   kill_vpp
   58           fi
   59
   60           # Cleanup veth interfaces and network namespace
   61           # Note: removing one veth, removes the pair
=> 62           ip link delete $INITIATOR_INTERFACE
   63           ip netns del $TARGET_NAMESPACE
   64   }
   65
   66   function iscsitestinit() {
   67           if [ "$1" == "iso" ]; then
     ...
in /home/spdk/spdk/test/iscsi_tgt/common.sh:96 -> iscsitestfini()
     ...
   91   }
   92
   93   function iscsitestfini() {
   94           if [ "$1" == "iso" ]; then
   95                   if [ -n "$2" ]; then
=> 96                           cleanup_veth_interfaces $2
   97                   else
   98                           # default to posix
   99                           cleanup_veth_interfaces "posix"
   100                  fi
   101                  $rootdir/scripts/setup.sh reset
     ...
in ./test/iscsi_tgt/fio/fio.sh:1 -> main()

```

**Comment by shuhei-matsumoto** [comment] 2019-11-20 23:14
I think I don't find anything to get the root cause yet. I'm not sure if I can but please give me time to investigate more. I hope this is not so critical yet.

**Comment by shuhei-matsumoto** [comment] 2019-11-20 23:42
I don't know this explains all cases but for some cases, the target kept getting EAGAIN for socket read and test completed when the target got EINVAL.  We may be able to use spdk_sock_is_connected() Ben added recently for these cases. I will try it and share the result.

**Comment by shuhei-matsumoto** [comment] 2019-11-20 23:50
I may be able to explain the cause.

Before refinements: connection moves EXITING state immediately
After refinement: connection stays RUNNING and continues trying receive PDUs after LUN is removed. We had not expected socket read returned EAGAIN repeatedly in this case.

**Comment by shuhei-matsumoto** [comment] 2019-11-21 01:05
I got more information by reproducing and getting log locally.

From the target side, the connection has been active but idle for two minutes, and then the target got ECONNRESET.

Ctrl + C showed the initiator had stayed in
 => 62           ip link delete $INITIATOR_INTERFACE

We don't support asynchronous event notification but I'm not sure if async event notification is helpful for this case as long as I have investigated so far.

**Comment by shuhei-matsumoto** [comment] 2019-11-21 05:38
I collected the information during unexpected two minutes.

During two minutes, only NOP-In/Out are exchanged, there was no reset and no read/write I/O and FIO is just waiting for something.
After two minutes, initiator closed the TCP connection, and target knows it by ECONNRESET.

I suspend further investigation for now and will work on developing unit attention (async. event notification).

**Comment by shuhei-matsumoto** [comment] 2019-11-21 10:27
Correction. I will continue investigation tomorrow. During two minutes delay  connection is still active. Initiator may be waiting for some critical responses. Target replied all though. Contents of response PDU might be wrong. Thanks for your help and patience

**Comment by spdkci** [comment] 2019-11-25 20:54
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50635.html

**Comment by optimistyzy** [comment] 2019-11-26 06:08
@shuhei-matsumoto https://review.gerrithub.io/c/spdk/spdk/+/475815  This patch should work.

**Comment by Seth5141** [comment] 2019-11-26 16:59
@shuhei-matsumoto @optimistyzy For the time being, I am going to increase the timeout on these tests by 2 minutes to mitigate the intermittent failures, but leave this issue open while you decide on the right strategy going forward.

**Comment by optimistyzy** [comment] 2019-11-27 04:33
@Seth5141 @shuhei-matsumoto I used kernel 5.4-rc3 on my platform, I did not see two minutes, though sometimes it lasts long.

**Comment by shuhei-matsumoto** [comment] 2019-11-27 12:25
Hi @ZiyeYang @jimharris @Seth5141 

I talked with Ziye offline but I still can’t rely on Ziye’s patch and observation. 

NOP-in/out continue and don’t exit connection even after all Luns are removed. NOP-in/out are no related with two minutes.

 iSCSI is very matured and legacy. Very unlikely to use such a new kernel on the host. Updating the kernel is no easy solution to iscsi hosts. This is different from developing NVMe-TCP

**Comment by ak-gh** [comment] 2019-11-27 12:40
On Wed, Nov 27, 2019, 15:25 shuhei-matsumoto <notifications@github.com>
wrote:

> Hi @ZiyeYang <https://github.com/ZiyeYang> @jimharris
> <https://github.com/jimharris> @Seth5141 <https://github.com/Seth5141>
>
> I talked with Ziye offline but I still can’t rely on Ziye’s patch and
> observation.
>
> NOP-in/out continue and don’t exit connection even after all Luns are
> removed. NOP-in/out are no related with two minutes.
>

Two minutes above sound like default Linux initiator replacement timeout.
When command error is detected, iscsi error handler waits for the
replacement timeout to expire before failing commands to the upper layer
(multipath or application).

Regards,
Andrey

**Comment by shuhei-matsumoto** [comment] 2019-11-27 12:58
@ak-gh thank you so much for sharing your great knowledge. So do you have any recommended solution idea? Ziye has proposed an idea that we close connection after all LUNs are removed. Do you agree with that?

**Comment by shuhei-matsumoto** [comment] 2019-11-27 13:00
I found two minutes in https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/storage_administration_guide/iscsi-replacement-timeout

**Comment by shuhei-matsumoto** [comment] 2019-11-27 13:24
If we support unit attention, we can add/remove lun to existing connections correctly. It may be nice to keep connections regardless of number of luns. I will consider more tomorrow.

**Comment by ak-gh** [comment] 2019-11-27 13:50
On Wed, Nov 27, 2019, 16:24 shuhei-matsumoto <notifications@github.com>
wrote:

> If we support unit attention, we can add/remove lun to existing
> connections correctly. It may be nice to keep connections regardless of
> number of luns.
>
That sounds like the right thing to do to me, especially the part re true
hot-plugging (in contrast with extant hot unplug) luns to existing
connections.

Regards,
Andrey

**Comment by ak-gh** [comment] 2019-11-27 13:53
For the tests, it might make sense to shorten replacement timeout to, say,
10 sec (by setting node.session.timeo.replacement_timeout in the
initiator's iscsi.conf).

**Comment by jimharris** [comment] 2019-11-27 13:54
Does this indicate that we still have outstanding IO commands to the removed LUN?  Otherwise the initiator side would have no reason to wait two minutes.

**Comment by ak-gh** [comment] 2019-11-27 14:10
On Wed, Nov 27, 2019 at 4:54 PM Jim Harris <notifications@github.com> wrote:

> Does this indicate that we still have outstanding IO commands to the
> removed LUN?
>
Not necessarily on your side, but likely on the initiator's side.

> Otherwise the initiator side would have no reason to wait two minutes.
>
Nope, it waits anyway if it has in-flight commands, to let the connection
recover before deciding to fail those permanently.

Regards,
Andrey

**Comment by jimharris** [comment] 2019-11-27 14:50
> On Wed, Nov 27, 2019 at 4:54 PM Jim Harris ***@***.***> wrote: Does this indicate that we still have outstanding IO commands to the removed LUN?
> Not necessarily on your side, but likely on the initiator's side.

Exactly - on the initiator side.  (In this case when I said "we" I was referring to fio since that's the focus for the 2 minute timeout.)

> Otherwise the initiator side would have no reason to wait two minutes.
> Nope, it waits anyway if it has in-flight commands, to let the connection recover before deciding to fail those permanently. Regards, Andrey

If the initiator is waiting two minutes, then it thinks there are still in-flight commands.  If it thinks that are still in-flight commands, then it means the target isn't cleaning them up properly when the LUN is removed.  It could be that a task or PDU is getting leaked, or that the tasks and PDUs are properly freed but status isn't getting sent back to the initiator.

Shuhei - can you try this test with only large reads and then with only large writes?  Let's see if the 2 minute timeout only happens with one vs. the other.  Then we know where to dig for cases where the target fails to report status back to the initiator.

**Comment by ak-gh** [comment] 2019-11-27 17:21
On Wed, Nov 27, 2019 at 5:50 PM Jim Harris <notifications@github.com> wrote:

> On Wed, Nov 27, 2019 at 4:54 PM Jim Harris *@*.***> wrote: Does this
> indicate that we still have outstanding IO commands to the removed LUN?
> Not necessarily on your side, but likely on the initiator's side.
>
> Exactly - on the initiator side. (In this case when I said "we" I was
> referring to fio since that's the focus for the 2 minute timeout.)
>
> Otherwise the initiator side would have no reason to wait two minutes.
> Nope, it waits anyway if it has in-flight commands, to let the connection
> recover before deciding to fail those permanently. Regards, Andrey
>
> If the initiator is waiting two minutes, then it thinks there are still
> in-flight commands.
>
Just for clarity, there are two possible cases:
1. The target has failed all outstanding commands to the LUN in question,
and
2. It didn't.

In case (1), initiator will still enter replacement timeout. In case (2),
it will likely wait for the outstanding command(s) to be failed by the
target first. I'm a bit surprised it continues sending NOPs which may (or
may not) point to the case (2).

> If it thinks that are still in-flight commands, then it means the target
> isn't cleaning them up properly when the LUN is removed. It could be that a
> task or PDU is getting leaked, or that the tasks and PDUs are properly
> freed but status isn't getting sent back to the initiator.
>
It could really help to ensure that all commands addressing the LUN have
been failed,  and initiator has got proper status back (
CHECK_CONDITION/UNIT_ATTENTION sounds appropriate).

Regards,
Andrey

**Comment by shuhei-matsumoto** [comment] 2019-11-28 04:47
Hi @ak-gh @jimharris @ZiyeYang @Seth5141 

Thank you so much for your insight.

I noticed that I had been trapped by the previous code again. We had discarded any PDU or task before completion or abort is notified to initiator. I fixed this error by https://review.gerrithub.io/c/spdk/spdk/+/476033.
Please take a look at it.

Previously, for some reason iSCSI target exited all connections immediately when LUN is unplugged. So this issue had not occurred.

**Comment by shuhei-matsumoto** [comment] 2019-11-28 04:49
As long as I tried locally, the patch may fix this issue.

**Comment by shuhei-matsumoto** [comment] 2019-11-28 05:37
Sorry, The above patch was not enough. Please stay tune.

**Comment by shuhei-matsumoto** [comment] 2019-11-28 06:10
I think we have to satisfy the following:

1. do not discard any PDU and task submitted before we start LUN unplug.
2. wait all such PDU and task are completed or aborted
3. Then close bdev by which LUN is backed

I'm thinking that we may need to use swapping queue head to do 2).

**Comment by shuhei-matsumoto** [comment] 2019-11-28 06:27
I'm pursuing an idea to use CmdSN to wait for all such PDU and tasks are completed or aborted. By using CmdSN, we may be able to know which task is submitted before/after LUN is removed.

**Comment by shuhei-matsumoto** [comment] 2019-11-28 08:17
I had an updated idea but it will not complete today. Any input is appreciated

**Comment by shuhei-matsumoto** [comment] 2019-11-29 08:20
I updated the patch https://review.gerrithub.io/c/spdk/spdk/+/476033

Ziye’s patches are really nice and this looks ok so far

**Comment by spdkci** [comment] 2019-12-03 21:32
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51318.html

**Comment by optimistyzy** [comment] 2019-12-13 07:28
@shuhei-matsumoto Should we close this issue or still open this?

**Comment by shuhei-matsumoto** [comment] 2019-12-13 20:42
Hi @ZiyeYang 

Seth kindly restored the original 10 minutes timeout. He have added 2 minutes. We will see if this is fixed in a next few days. So let’s keep open until no reports here

**Comment by shuhei-matsumoto** [comment] 2019-12-19 04:36
A week passed since restoring original 10 minutes timeout. There is no report here. Close this issue. Thanks for all.

**Closed by shuhei-matsumoto** 2019-12-19 04:36 UTC
Labels: Intermittent Failure
