### ISSUE TITLE
nvme_pcie.c:2098:nvme_pcie_qpair_process_completions: *ERROR*: cpl does not map to outstanding cmd

### ISSUE THREAD

**Issue by yangliang20065613** [spdk/spdk#441] opened 2018-09-20 01:54 UTC
Firstly：
These errors below will happen when I restart the nvmf target, and  I stop the nvmf target by running “kill –s SIGTERM [ the pid of nvmf target]”. 
 
rdma.c:1517:spdk_nvmf_rdma_poll_group_create: *NOTICE*: Skipping unused RDMA device when creating poll group.
nvme_qpair.c: 131:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:172 nsid:1 lba:8467184 len:8
nvme_qpair.c: 283:nvme_qpair_print_completion: *NOTICE*: COMMAND ID CONFLICT (00/03) sqid:1 cid:172 cdw0:0 sqhd:006e p:1 m:0 dnr:0
nvme_pcie.c:2098:nvme_pcie_qpair_process_completions: *ERROR*: cpl does not map to outstanding cmd
nvme_qpair.c: 283:nvme_qpair_print_completion: *NOTICE*: SUCCESS (00/00) sqid:1 cid:172 cdw0:0 sqhd:006f p:1 m:0 dnr:0
nvme_pcie.c:1299:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
nvme_qpair.c: 131:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:173 nsid:1 lba:8467152 len:8
nvme_qpair.c: 283:nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:1 cid:173 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
rdma.c:1245:spdk_nvmf_rdma_destroy: *ERROR*: transport buffer pool count is 511 but should be 512
bdev.c: 674:spdk_bdev_mgr_unregister_cb: *ERROR*: bdev IO pool count is 65535 but should be 65536
 
 
Then：
I find the bug information on github, https://github.com/spdk/spdk/issues/217#issuecomment-345595194. But I couldn’t find the method how to resolve this bug.
 
 
Lastly：
The configuration file of Nvmf target：
[root@ nvmf_tgt]# cat nvmf.conf
[Global]
ReactorMask 0xf
[Rpc]
Enable Yes
Listen 127.0.0.1
 
 
[Nvme]
TransportId "trtype:PCIe traddr:0003:09:00.0" Nvme0
TransportId "trtype:PCIe traddr:0003:0a:00.0" Nvme1
TransportId "trtype:PCIe traddr:0003:0b:00.0" Nvme2
TransportId "trtype:PCIe traddr:0003:0c:00.0" Nvme3
 
[Subsystem1]
NQN nqn.2016-06.io.spdk:cnode1
Listen RDMA 192.168.4.38:4420
AllowAnyHost Yes
Host nqn.2016-06.io.spdk:init
SN SPDK00000000000001
Namespace Nvme0n1
 
[Subsystem2]
NQN nqn.2016-06.io.spdk:cnode2
Listen RDMA 192.168.4.38:4420
AllowAnyHost Yes
Host nqn.2016-06.io.spdk:init
SN SPDK00000000000002
Namespace Nvme1n1
 
[Subsystem3]
NQN nqn.2016-06.io.spdk:cnode3
Listen RDMA 192.168.4.38:4420
AllowAnyHost Yes
Host nqn.2016-06.io.spdk:init
SN SPDK00000000000003
Namespace Nvme2n1
 
[Subsystem4]
NQN nqn.2016-06.io.spdk:cnode4
Listen RDMA 192.168.4.38:4420
AllowAnyHost Yes
Host nqn.2016-06.io.spdk:init
SN SPDK00000000000004
Namespace Nvme3n1
 
The fio configuration file of Nvmf initiator：
[root@ result]# cat ../my.fio
[global]
ioengine=spdk_bdev
spdk_conf=./my_bdev.conf
thread=1
cpumask=0x1e
group_reporting=1
direct=1
verify=0
time_based=1
norandommap=1
runtime=60
iodepth=64
rw=write
bs=8k
 
[filename1]
filename=Nvme0n1
 
[filename2]
filename=Nvme1n1
 
[filename3]
filename=Nvme2n1
 
[filename4]
filename=Nvme3n1
 
The bdev configuration file of my_bdev.conf:
[root@ result]# cat ../my_bdev.conf
[Nvme]
TransportId "trtype:RDMA adrfam:IPv4 traddr:192.168.4.38 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode1" Nvme0
TransportId "trtype:RDMA adrfam:IPv4 traddr:192.168.4.38 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode2" Nvme1
TransportId "trtype:RDMA adrfam:IPv4 traddr:192.168.4.38 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode3" Nvme2
TransportId "trtype:RDMA adrfam:IPv4 traddr:192.168.4.38 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode4" Nvme3

## Context (Environment including OS version, SPDK version, etc.)
OS version: kernel:4.14.36  Linux Distribution：CentOS Linux release 7.5.1804 (AltArch)
SPDK version：18.04.1
NVMe SSD： Samsung PM963 & Samsung PM983
user nvme driver： uio
HUGEPAGE counter：8192
HUGEPAGE size：2048k

**Comment by liang2yan** [comment] 2018-09-20 02:04
@yangliang20065613 , can you provide the detailed steps to reproduce this issue? Then we can try to reproduce the issue in our env.

**Comment by yangliang20065613** [comment] 2018-09-20 02:26
Hi,
这个问题不是每次都出现，我是在测试spdk的nvmf，target端4块或者8块m.2的盘，用8个或者16个cpu核，client端队列深度64或者128，用fio plugin测试，client端用的cpu核数等于盘的个数。网卡是mlx25G的。感觉这个问题和盘和测试压力有关系。


发自我的 iPhone

**Comment by yangliang20065613** [comment] 2018-09-20 02:29
步骤就是把spdk nvmf搭起来，用fio测试就可以了。hupge page个数，target端cpu核数对问题出现影响比较大，数量越多发生的概率越大。

发自我的 iPhone

**Comment by yangliang20065613** [comment] 2018-09-20 02:34
还有initiator端队列在64,128时出问题概率也大一些。

发自我的 iPhone

**Comment by xuhuagen** [comment] 2018-09-21 08:29
@yangliang20065613 ,
My enviromet is
OS version: kernel:4.17.1 Linux Distribution：CentOS Linux release 7.5.1804 (AltArch)
SPDK version：18.04.1
NVMe SSD： Intel P3700 *8
user nvme driver： uio
HUGEPAGE counter：8192
HUGEPAGE size：2048k 

and the configuration file of Nvmf target and fio jobfile is samilar to yours.
but I can't reproduce your issue.

**Comment by xuhuagen** [comment] 2018-10-17 08:39
@yangliang20065613 

My enviromet is
OS version: kernel:4.17.1 Linux Distribution：CentOS Linux release 7.5.1804 (AltArch)
NVMe SSD： Intel P3700 *8
user nvme driver： uio
HUGEPAGE counter：8192
HUGEPAGE size：2048k
The configuration file of Nvmf target and fio jobfile is samilar to yours.

 **I send SIGTERM to kill nvmf_tgt  in target machine when fiojob is running in initiator**

**if SPDK version is 18.04.1**, the log as below:

```
^Crdma.c:1245:spdk_nvmf_rdma_destroy: *ERROR*: transport buffer pool count is 0 but should be 512
rdma.c: 288:spdk_nvmf_rdma_mgmt_channel_destroy: *ERROR*: Pending I/O list wasn't empty on channel destruction

```
**if SPDK version is update-to-date (commit id is  073f2dd8f28d4ced17ea736535919ff8e314f6cf)      
nvmf_tgt core dumped occur, core dumped**  log as below:
```
[root@waikikibeach35 tmp]# gdb -c core-reactor_0-11-0-0-34044-1539763632 /home/xuhuagen/spdk/app/nvmf_tgt/nvmf_tgt
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/xuhuagen/spdk/app/nvmf_tgt/nvmf_tgt...done.

warning: core file may not match specified executable file.
[New LWP 34044]
[New LWP 34051]
[New LWP 34046]
[New LWP 34045]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./app/nvmf_tgt/nvmf_tgt -c ../nvmf.conf.issue441'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f59be53b1ef in ibv_dereg_mr () from /lib64/libibverbs.so.1
Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64 libaio-0.3.109-13.el7.x86_64 libgcc-4.8.5-28.el7_5.1.x86_64 libibverbs-15-7.el7_5.x86_64 libnl3-3.2.28-4.el7.x86_64 librdmacm-15-7.el7_5.x86_64 libuuid-2.23.2-52.el7_5.1.x86_64 numactl-libs-2.0.9-7.el7.x86_64 openssl-libs-1.0.2k-12.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007f59be53b1ef in ibv_dereg_mr () from /lib64/libibverbs.so.1
#1  0x000000000044af9b in spdk_nvmf_rdma_qpair_destroy (rqpair=0x28fd990) at rdma.c:576
#2  0x000000000044c6c3 in spdk_nvmf_rdma_poller_poll (rtransport=rtransport@entry=0x272cf00, rpoller=0x2625540) at rdma.c:2779
#3  0x000000000044c96f in spdk_nvmf_rdma_poll_group_poll (group=<optimized out>) at rdma.c:2808
#4  0x0000000000447a2b in spdk_nvmf_poll_group_poll (ctx=<optimized out>) at nvmf.c:114
#5  0x0000000000452524 in _spdk_reactor_run (arg=0x2615e80) at reactor.c:514
#6  0x0000000000452acd in spdk_reactors_start () at reactor.c:677
#7  0x00000000004516d1 in spdk_app_start (opts=opts@entry=0x7fff38348170, start_fn=start_fn@entry=0x407210 <nvmf_tgt_started>,
    arg1=arg1@entry=0x0, arg2=arg2@entry=0x0) at app.c:650
#8  0x0000000000405f55 in main (argc=3, argv=0x7fff383482e8) at nvmf_main.c:75

```

**Comment by jimharris** [comment] 2018-11-01 04:56
Let's retest this after the patch set from @benlwalker is merged.

**Comment by wanqunintel** [comment] 2018-11-01 04:57
@xuhuagen , will retest with the latest patch udpated end of this week?

**Comment by xuhuagen** [comment] 2018-11-02 05:33
@benlwalker  patch for this issue is merged? what is the patch's link?

**Comment by xuhuagen** [comment] 2018-11-27 07:50
@yangliang20065613 

My enviromet is
OS version: kernel:4.17.1 Linux Distribution：CentOS Linux release 7.5.1804 (AltArch)
NVMe SSD： Intel P3700 *8
user nvme driver： uio
HUGEPAGE counter：8192
HUGEPAGE size：2048k
The configuration file of Nvmf target and fio jobfile is samilar to yours.

SPDK commit id is 9e2f1bff81466d675881454d8907dd65b62308b0,
I try to reproduce this issue
In initiator:
I run fio but fio can't exit normally. (only be killed by send SIGKILL)
In traget have error log, the log as below:

```
mlx5: waikikibeach35: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000012 00000000 00000000 00000000
00000000 9d003304 10000301 00119ad3
```

**Comment by jimharris** [comment] 2018-12-12 23:34
This "got completion with error" message indicates the MR spanning issue that was fixed a couple of weeks ago.  Could you please retest?

**Comment by jimharris** [comment] 2019-01-29 19:59
Fairly certain this issue is now resolved based on MR spanning fixes that went in a few months ago.  No word yet from the submitter to confirm, so closing this issue.  If retesting still shows a problem, please reopen this issue (if the issue is seen) or file a new issue.

**Closed by jimharris** 2019-01-29 19:59 UTC
Labels: Medium, Waiting on Submitter, bug
