### ISSUE TITLE
[nvmf_lvol] blobstore.c:1237: blob_serialize: Assertion `blob->state == SPDK_BLOB_STATE_DIRTY' failed

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1926] opened 2021-05-03 11:49 UTC
```
00:03:34.073  ************************************
00:03:34.073  START TEST nvmf_lvol
00:03:34.073  ************************************
00:03:34.073   12:02:18	# xtrace_enable
00:03:34.074   12:02:18	# test/nvmf/target/nvmf_lvol.sh --transport=rdma
00:03:34.122  * Purging old temporary test storage (/tmp/spdk.cF9hMe)
00:03:34.145  * Looking for test storage...
00:03:34.149  * Found test storage at /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/nvmf/target
00:03:34.150    12:02:18	# xtrace_enable
00:03:34.150   12:02:18	# source /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/nvmf/common.sh
00:03:34.150    12:02:18	# NVMF_PORT=4420
00:03:34.150    12:02:18	# NVMF_SECOND_PORT=4421
00:03:34.151    12:02:18	# NVMF_THIRD_PORT=4422
00:03:34.151    12:02:18	# NVMF_IP_PREFIX=192.168.100
00:03:34.151    12:02:18	# NVMF_IP_LEAST_ADDR=8
00:03:34.151    12:02:18	# NVMF_TCP_IP_ADDRESS=127.0.0.1
00:03:34.151    12:02:18	# NVMF_TRANSPORT_OPTS=
00:03:34.151    12:02:18	# NVMF_SERIAL=SPDK00000000000001
00:03:34.152    12:02:18	# : 0
00:03:34.152    12:02:18	# export NVMF_APP_SHM_ID
00:03:34.152    12:02:18	# build_nvmf_app_args
00:03:34.153    12:02:18	# '[' 0 -eq 1 ']'
00:03:34.153    12:02:18	# NVMF_APP+=(-i "$NVMF_APP_SHM_ID" -e 0xFFFF)
00:03:34.153    12:02:18	# '[' -n '' ']'
00:03:34.153    12:02:18	# '[' 0 -eq 1 ']'
00:03:34.153    12:02:18	# have_pci_nics=0
00:03:34.153   12:02:18	# MALLOC_BDEV_SIZE=64
00:03:34.153   12:02:18	# MALLOC_BLOCK_SIZE=512
00:03:34.153   12:02:18	# LVOL_BDEV_INIT_SIZE=20
00:03:34.154   12:02:18	# LVOL_BDEV_FINAL_SIZE=30
00:03:34.154   12:02:18	# rpc_py=/var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py
00:03:34.154   12:02:18	# nvmftestinit
00:03:34.154   12:02:18	# '[' -z rdma ']'
00:03:34.154   12:02:18	# '[' '' == iso ']'
00:03:34.154   12:02:18	# NVMF_TRANSPORT_OPTS='-t rdma'
00:03:34.154   12:02:18	# [[ rdma == \r\d\m\a ]]
00:03:34.155    12:02:18	# get_available_rdma_ips
00:03:34.155     12:02:18	# get_rdma_if_list
00:03:34.155     12:02:18	# rxe_cfg rxe-net
00:03:34.155     12:02:18	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rxe_cfg_small.sh rxe-net
00:03:34.167    12:02:18	# for nic_name in $(get_rdma_if_list)
00:03:34.167    12:02:18	# get_ip_address enp131s0f0np0
00:03:34.168    12:02:18	# interface=enp131s0f0np0
00:03:34.168    12:02:18	# ip -o -4 addr show enp131s0f0np0
00:03:34.168    12:02:18	# awk '{print $4}'
00:03:34.169    12:02:18	# cut -d/ -f1
00:03:34.171    12:02:18	# for nic_name in $(get_rdma_if_list)
00:03:34.171    12:02:18	# get_ip_address enp131s0f1np1
00:03:34.171    12:02:18	# interface=enp131s0f1np1
00:03:34.171    12:02:18	# ip -o -4 addr show enp131s0f1np1
00:03:34.172    12:02:18	# awk '{print $4}'
00:03:34.172    12:02:18	# cut -d/ -f1
00:03:34.175   12:02:18	# RDMA_IP_LIST='192.168.100.8
00:03:34.175  192.168.100.9'
00:03:34.176    12:02:18	# echo '192.168.100.8
00:03:34.176  192.168.100.9'
00:03:34.176    12:02:18	# head -n 1
00:03:34.178   12:02:18	# NVMF_FIRST_TARGET_IP=192.168.100.8
00:03:34.179    12:02:18	# echo '192.168.100.8
00:03:34.179  192.168.100.9'
00:03:34.179    12:02:18	# tail -n +2
00:03:34.179    12:02:18	# head -n 1
00:03:34.182   12:02:18	# NVMF_SECOND_TARGET_IP=192.168.100.9
00:03:34.182   12:02:18	# '[' -z 192.168.100.8 ']'
00:03:34.182   12:02:18	# '[' rdma == tcp ']'
00:03:34.183   12:02:18	# '[' rdma == rdma ']'
00:03:34.183   12:02:18	# modprobe nvme-rdma
00:03:34.197   12:02:18	# nvmfappstart -m 0x7
00:03:34.197   12:02:18	# timing_enter start_nvmf_tgt
00:03:34.198   12:02:18	# xtrace_disable
00:03:34.198   12:02:18	# '[' '' '!=' yes ']'
00:03:34.198   12:02:18	# PREV_BASH_OPTS=ehxBET
00:03:34.198   12:02:18	# [[ ehxBET == *\x* ]]
00:03:34.198   12:02:18	# XTRACE_DISABLED=yes
00:03:34.199   12:02:18	# set +x
00:03:34.200   12:02:18	# xtrace_enable
00:03:34.201   12:02:18	# nvmfpid=790263
00:03:34.202   12:02:18	# trap 'process_shm --id $NVMF_APP_SHM_ID; nvmftestfini; exit 1' SIGINT SIGTERM EXIT
00:03:34.202   12:02:18	# waitforlisten 790263
00:03:34.202   12:02:18	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/build/bin/nvmf_tgt -i 0 -e 0xFFFF -m 0x7
00:03:34.202   12:02:18	# '[' -z 790263 ']'
00:03:34.203   12:02:18	# local rpc_addr=/var/tmp/spdk.sock
00:03:34.203   12:02:18	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
00:03:34.203  Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
00:03:34.203   12:02:18	# xtrace_disable
00:03:34.203   12:02:18	# '[' no '!=' yes ']'
00:03:34.204   12:02:18	# PREV_BASH_OPTS=ehxBET
00:03:34.204   12:02:18	# [[ ehxBET == *\x* ]]
00:03:34.204   12:02:18	# XTRACE_DISABLED=yes
00:03:34.204   12:02:18	# set +x
00:03:34.227  [2021-05-03 12:02:18.174596] Starting SPDK v21.07-pre git sha1 d5b85d5bb / DPDK 20.11.0 initialization...
00:03:34.227  [2021-05-03 12:02:18.174690] [ DPDK EAL parameters: [2021-05-03 12:02:18.174704] nvmf [2021-05-03 12:02:18.174714] -c 0x7 [2021-05-03 12:02:18.174723] --log-level=lib.eal:6 [2021-05-03 12:02:18.174732] --log-level=lib.cryptodev:5 [2021-05-03 12:02:18.174741] --log-level=user1:6 [2021-05-03 12:02:18.174751] --base-virtaddr=0x200000000000 [2021-05-03 12:02:18.174760] --match-allocations [2021-05-03 12:02:18.174769] --file-prefix=spdk0 [2021-05-03 12:02:18.174778] --proc-type=auto [2021-05-03 12:02:18.174787] ]
00:03:34.261  EAL: No free hugepages reported in hugepages-2048kB
00:03:34.262  EAL: No available hugepages reported in hugepages-1048576kB
00:03:34.265  EAL: No legacy callbacks, legacy socket not created
00:03:34.301  [2021-05-03 12:02:18.248404] app.c: 535:spdk_app_start: *NOTICE*: Total cores available: 3
00:03:34.454  [2021-05-03 12:02:18.401321] app.c: 383:app_setup_trace: *NOTICE*: Tracepoint Group Mask 0xFFFF specified.
00:03:34.454  [2021-05-03 12:02:18.401404] app.c: 384:app_setup_trace: *NOTICE*: Use 'spdk_trace -s nvmf -i 0' to capture a snapshot of events at runtime.
00:03:34.454  [2021-05-03 12:02:18.401416] app.c: 389:app_setup_trace: *NOTICE*: Or copy /dev/shm/nvmf_trace.0 for offline analysis/debug.
00:03:34.454  [2021-05-03 12:02:18.401525] reactor.c: 929:reactor_run: *NOTICE*: Reactor started on core 1
00:03:34.454  [2021-05-03 12:02:18.401610] reactor.c: 929:reactor_run: *NOTICE*: Reactor started on core 0
00:03:34.455  [2021-05-03 12:02:18.401570] reactor.c: 929:reactor_run: *NOTICE*: Reactor started on core 2
00:03:34.455  [2021-05-03 12:02:18.401794] accel_engine.c: 852:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:03:35.142   12:02:19	# xtrace_enable
00:03:35.143   12:02:19	# (( i == 0 ))
00:03:35.143   12:02:19	# return 0
00:03:35.143   12:02:19	# timing_exit start_nvmf_tgt
00:03:35.143   12:02:19	# xtrace_disable
00:03:35.143   12:02:19	# '[' no '!=' yes ']'
00:03:35.144   12:02:19	# PREV_BASH_OPTS=ehxBET
00:03:35.144   12:02:19	# [[ ehxBET == *\x* ]]
00:03:35.144   12:02:19	# XTRACE_DISABLED=yes
00:03:35.144   12:02:19	# set +x
00:03:35.168   12:02:19	# xtrace_enable
00:03:35.168   12:02:19	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_create_transport -t rdma -u 8192
00:03:35.566    12:02:19	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py bdev_malloc_create 64 512
00:03:35.811   12:02:19	# base_bdevs='Malloc0 '
00:03:35.812    12:02:19	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py bdev_malloc_create 64 512
00:03:36.055   12:02:20	# base_bdevs+=Malloc1
00:03:36.055   12:02:20	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py bdev_raid_create -n raid0 -z 64 -r 0 -b 'Malloc0 Malloc1'
00:03:36.280    12:02:20	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py bdev_lvol_create_lvstore raid0 lvs
00:03:36.523   12:02:20	# lvs=02248c78-aab4-461f-ab95-c05a07c4130e
00:03:36.524    12:02:20	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py bdev_lvol_create -u 02248c78-aab4-461f-ab95-c05a07c4130e lvol 20
00:03:36.745   12:02:20	# lvol=4d4b6603-f908-4797-b88a-59e6c6655bf5
00:03:36.745   12:02:20	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode0 -a -s SPDK0
00:03:36.968   12:02:20	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode0 4d4b6603-f908-4797-b88a-59e6c6655bf5
00:03:37.190   12:02:21	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode0 -t rdma -a 192.168.100.8 -s 4420
00:03:37.399  [2021-05-03 12:02:21.346039] rdma.c:2650:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 192.168.100.8 port 4420 ***
00:03:37.416   12:02:21	# perf_pid=790300
00:03:37.416   12:02:21	# sleep 1
00:03:37.416   12:02:21	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/build/examples/perf -r 'trtype:rdma adrfam:IPv4 traddr:192.168.100.8 trsvcid:4420' -o 4096 -q 128 -s 512 -w randwrite -t 10 -c 0x18
00:03:37.429  [2021-05-03 12:02:21.376953] Starting SPDK v21.07-pre git sha1 d5b85d5bb / DPDK 20.11.0 initialization...
00:03:37.430  [2021-05-03 12:02:21.377059] [ DPDK EAL parameters: [2021-05-03 12:02:21.377078] perf [2021-05-03 12:02:21.377092] --no-shconf [2021-05-03 12:02:21.377104] -c 0x18 [2021-05-03 12:02:21.377116] -m 512 [2021-05-03 12:02:21.377129] --no-pci [2021-05-03 12:02:21.377141] --log-level=lib.eal:6 [2021-05-03 12:02:21.377154] --log-level=lib.cryptodev:5 [2021-05-03 12:02:21.377166] --log-level=user1:6 [2021-05-03 12:02:21.377178] --base-virtaddr=0x200000000000 [2021-05-03 12:02:21.377191] --match-allocations [2021-05-03 12:02:21.377204] --file-prefix=spdk_pid790300 [2021-05-03 12:02:21.377216] ]
00:03:37.439  EAL: No free hugepages reported in hugepages-2048kB
00:03:37.439  EAL: No available hugepages reported in hugepages-1048576kB
00:03:37.575  EAL: No legacy callbacks, legacy socket not created
00:03:38.419    12:02:22	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py bdev_lvol_snapshot 4d4b6603-f908-4797-b88a-59e6c6655bf5 MY_SNAPSHOT
00:03:38.642  nvmf_tgt: blobstore.c:1237: blob_serialize: Assertion `blob->state == SPDK_BLOB_STATE_DIRTY' failed.
00:03:41.294     12:02:25	# trap - ERR
00:03:41.294     12:02:25	# print_backtrace
00:03:41.295     12:02:25	# [[ hxBET =~ e ]]
00:03:41.295     12:02:25	# return 0
00:03:41.295   12:02:25	# snapshot='Connection closed with partial response:'
00:03:41.295  test/nvmf/target/nvmf_lvol.sh: line 43: 790263 Aborted                 (core dumped) "${NVMF_APP[@]}" "$@"
00:03:41.296    12:02:25	# trap - ERR
00:03:41.296    12:02:25	# print_backtrace
00:03:41.296    12:02:25	# [[ ehxBET =~ e ]]
00:03:41.296    12:02:25	# args=("${BASH_ARGV[@]}")
00:03:41.296    12:02:25	# local args
00:03:41.297    12:02:25	# xtrace_disable
00:03:41.297    12:02:25	# '[' no '!=' yes ']'
00:03:41.297    12:02:25	# PREV_BASH_OPTS=ehxBET
00:03:41.297    12:02:25	# [[ ehxBET == *\x* ]]
00:03:41.297    12:02:25	# XTRACE_DISABLED=yes
00:03:41.297    12:02:25	# set +x
00:03:41.298  ========== Backtrace start: ==========
00:03:41.298  
00:03:41.307  in test/nvmf/target/nvmf_lvol.sh:43 -> main(["--transport=rdma"])
00:03:41.307       ...
00:03:41.308     38  	perf_pid=$!
00:03:41.308     39  	
00:03:41.308     40  	sleep 1
00:03:41.308     41  	
00:03:41.308     42  	# Perform some operations on the logical volume
00:03:41.308  => 43  	snapshot=$($rpc_py bdev_lvol_snapshot $lvol "MY_SNAPSHOT")
00:03:41.308     44  	$rpc_py bdev_lvol_resize $lvol $LVOL_BDEV_FINAL_SIZE
00:03:41.308     45  	clone=$($rpc_py bdev_lvol_clone $snapshot "MY_CLONE")
00:03:41.308     46  	$rpc_py bdev_lvol_inflate $clone
00:03:41.308     47  	
00:03:41.308     48  	# Wait for I/O to complete
00:03:41.308       ...
00:03:41.308  
00:03:41.308  ========== Backtrace end ==========
```

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_43987.html

## Execution failed at

```
00:03:41.298  ========== Backtrace start: ==========
00:03:41.298  
00:03:41.307  in test/nvmf/target/nvmf_lvol.sh:43 -> main(["--transport=rdma"])
00:03:41.307       ...
00:03:41.308     38  	perf_pid=$!
00:03:41.308     39  	
00:03:41.308     40  	sleep 1
00:03:41.308     41  	
00:03:41.308     42  	# Perform some operations on the logical volume
00:03:41.308  => 43  	snapshot=$($rpc_py bdev_lvol_snapshot $lvol "MY_SNAPSHOT")
00:03:41.308     44  	$rpc_py bdev_lvol_resize $lvol $LVOL_BDEV_FINAL_SIZE
00:03:41.308     45  	clone=$($rpc_py bdev_lvol_clone $snapshot "MY_CLONE")
00:03:41.308     46  	$rpc_py bdev_lvol_inflate $clone
00:03:41.308     47  	
00:03:41.308     48  	# Wait for I/O to complete
00:03:41.308       ...
00:03:41.308  
00:03:41.308  ========== Backtrace end ==========

```

**Comment by spdkci** [comment] 2021-05-03 11:50
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_43987.html

**Comment by jimharris** [comment] 2021-05-03 15:43
I think this is a duplicate of #1909.  It looks like this failure was from a patch that was based on something earlier than when the #1909 fix was merged last week.

**Closed by jimharris** 2021-05-03 15:43 UTC
Labels: Intermittent Failure
