### ISSUE TITLE
[ocf_fio_modes] dd: error writing '/dev/nvme0n1': Operation not supported

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1494] opened 2020-07-13 23:12 UTC

**Comment by spdkci** [comment] 2020-07-13 23:14
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_21227.html

**Comment by spdkci** [comment] 2020-07-13 23:14
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_21235.html

**Comment by mikeBashStuff** [comment] 2020-07-14 08:15
This looks like a duplicate of #1456.

**Comment by tomzawadzki** [comment] 2020-07-14 12:51
Duplicate of #1456

**Closed by tomzawadzki** 2020-07-14 12:51 UTC
Labels: Intermittent Failure

**Comment by spdkci** [comment] 2020-08-21 07:28
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_24661.html
