### ISSUE TITLE
segfault on delete_nvme_controller RPC after hotremoving nvme bdevs

### ISSUE THREAD

**Issue by darsto** [spdk/spdk#495] opened 2018-11-07 15:44 UTC
I managed to get an assert failure after issuing `delete_nvme_controller` RPC:

`spdk_tgt: bdev_nvme.c:1102: remove_cb: Assertion `nvme_bdev->id == nsid' failed.`

It seems like we don't handle nvme bdev hotremoval very well.

## Steps to Reproduce
 $ ./app/spdk_tgt/spdk_tgt &
 $ ./scripts/rpc.py construct_nvme_bdev -b Nvme0 -t pcie -a 83:00.0
 $ ./scripts/rpc.py delete_bdev Nvme0n1
 $ ./scripts/rpc.py delete_nvme_controller Nvme0

I know `delete_bdev` just a debug feature but we might want to get it fixed anyway.

## Context (Environment including OS version, SPDK version, etc.)
SPDK: recent master:
commit f06d3d3bbf57548eb2688172ac839399375fa643 (origin/master, origin/HEAD)
Author: Piotr Pelplinski <piotr.pelplinski@intel.com>
Date:   Thu Oct 11 09:19:34 2018 +0200

    bdev: add possibility to allocate aligned buffer in _spdk_bdev_io_get_buf

DPDK from upstream spdk-18.08 branch

**Comment by changpe1** [comment] 2018-11-12 06:06
@darsto , I didn't reproduce the assert you mentioned, and I checked the code in bdev_nvme.c, I don't see the code which will clean nvme_bdev->id.   I'm thinking is there any steps you missed for the issue?

**Comment by liang2yan** [comment] 2018-11-13 05:13
@darsto , can you check your steps to see if any steps missing?

**Comment by darsto** [comment] 2018-11-15 09:15
@changpe1 The entire nvme_bdev is zeroed on hotremove.

https://github.com/spdk/spdk/blob/38ed4e4a0555e3f8b0d4c1bc85714fe130767136/lib/bdev/nvme/bdev_nvme.c#L285

**Comment by liang2yan** [comment] 2018-11-19 01:14
@darsto , can we close this issue since changpeng's patch has been merged?

**Closed** 2018-11-28 13:54 UTC
Labels: bug
