### ISSUE TITLE
[nvmf-tcp-vg-autotest] nvmf_filesystem_incapsule test failure

### ISSUE THREAD

**Issue by krish-reddy** [spdk/spdk#2116] opened 2021-08-20 12:22 UTC
# CI Intermittent Failure
00:04:19.547  ========== Backtrace start: ==========
00:04:19.547  
00:04:19.555  in test/nvmf/target/filesystem.sh:57 -> nvmf_filesystem_part(["4096"])
00:04:19.555       ...
00:04:19.555     52  		$rpc_py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc1
00:04:19.555     53  		$rpc_py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_PORT
00:04:19.555     54  	
00:04:19.555     55  		nvme connect -t $TEST_TRANSPORT -n "nqn.2016-06.io.spdk:cnode1" -a "$NVMF_FIRST_TARGET_IP" -s "$NVMF_PORT"
00:04:19.555     56  	
00:04:19.555  => 57  		waitforserial "$NVMF_SERIAL"
00:04:19.555     58  		nvme_name=$(lsblk -l -o NAME,SERIAL | grep -oP "([\w]*)(?=\s+${NVMF_SERIAL})")
00:04:19.555     59  	
00:04:19.555     60  		mkdir -p /mnt/device
00:04:19.555     61  	
00:04:19.556     62  		parted -s /dev/${nvme_name} mklabel msdos mkpart primary '0%' '100%'
00:04:19.556       ...
00:04:19.563  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:957 -> run_test(["nvmf_filesystem_incapsule"],["nvmf_filesystem_part"],["4096"])
00:04:19.563       ...
00:04:19.563     952 		timing_enter $test_name
00:04:19.563     953 		echo "************************************"
00:04:19.563     954 		echo "START TEST $test_name"
00:04:19.563     955 		echo "************************************"
00:04:19.563     956 		xtrace_restore
00:04:19.563  => 957 		time "$@"
00:04:19.563     958 		xtrace_disable
00:04:19.563     959 		echo "************************************"
00:04:19.563     960 		echo "END TEST $test_name"
00:04:19.563     961 		echo "************************************"
00:04:19.564     962 		timing_exit $test_name
00:04:19.564       ...
00:04:19.572  in test/nvmf/target/filesystem.sh:90 -> main(["--transport=tcp"])
00:04:19.572       ...
00:04:19.572     85  		killprocess $nvmfpid
00:04:19.572     86  		nvmfpid=
00:04:19.572     87  	}
00:04:19.572     88  	
00:04:19.572     89  	run_test "nvmf_filesystem_no_incapsule" nvmf_filesystem_part 0
00:04:19.572  => 90  	run_test "nvmf_filesystem_incapsule" nvmf_filesystem_part 4096
00:04:19.572     91  	
00:04:19.573     92  	nvmftestfini
00:04:19.573       ...
00:04:19.573  
00:04:19.574  ========== Backtrace end ==========

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/56520/archive/nvmf-tcp-vg-autotest/index.html

**Comment by spdkci** [comment] 2021-08-20 12:24
Another instance of this failure. Reported by @krish-reddy. log: https://ci.spdk.io/public_build/autotest-per-patch_56520.html

**Comment by ksztyber** [comment] 2021-08-20 12:41
I think this is a duplicate of #2060.

**Closed by ksztyber** 2021-08-20 12:41 UTC
Labels: Intermittent Failure
