### ISSUE TITLE
[nvmf_connect_disconnect] waitforserial "$NVMF_SERIAL" timed out

### ISSUE THREAD

**Issue by benlwalker** [spdk/spdk#1331] opened 2020-04-06 20:22 UTC
[nvmf_connect_disconnect] waitforserial "$NVMF_SERIAL" timed out

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/9055/archive/nvmf-autotest/build.log

## Execution failed at

```
 00:00:02	# /var/jenkins/workspace/nvmf-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 10.102.17.184 -s 4420
rdma.c:2748:spdk_nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 10.102.17.184 port 4420 ***
 00:00:03	# '[' 0 -eq 1 ']'
 00:00:03	# num_iterations=10
 00:00:03	# set +x
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
Waiting for devices
========== Backtrace start: ==========

in test/nvmf/target/connect_disconnect.sh:35 -> main(["--transport=rdma"])
     ...
   30  	fi
   31  	
   32  	set +x
   33  	for i in $(seq 1 $num_iterations); do
   34  		nvme connect -t $TEST_TRANSPORT -n "nqn.2016-06.io.spdk:cnode1" -a "$NVMF_FIRST_TARGET_IP" -s "$NVMF_PORT" $IO_QUEUES
=> 35  		waitforserial "$NVMF_SERIAL"
   36  		nvme disconnect -n "nqn.2016-06.io.spdk:cnode1"
   37  		waitforserial_disconnect "$NVMF_SERIAL"
   38  	done
   39  	set -x
   40  	
     ...

========== Backtrace end ==========
```

**Comment by Seth5141** [comment] 2020-04-07 00:13
Possible duplicate of #1252

**Comment by tomzawadzki** [comment] 2020-04-07 14:31
Duplicate of #1252

**Closed by tomzawadzki** 2020-04-07 14:31 UTC
Labels: Intermittent Failure

**Comment by spdkci** [comment] 2020-04-10 08:38
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_9872.html
