### ISSUE TITLE
DPDK 18.11 EAL: Failed to hotplug remove device

### ISSUE THREAD

**Issue by nagendra-v** [spdk/spdk#701] opened 2019-03-01 02:38 UTC
Seeing below DPDK error messages with nvme cli, identify and other utilities. Error messages are _not seen with  SPDK v18.10.1 / DPDK 18.08.0_.
# ./nvme list
Starting SPDK v19.01 / DPDK 18.11.0 initialization...
[ DPDK EAL parameters: nvme_cli -c 0x80 -m 512 --base-virtaddr=0x200000000000 --file-prefix=spdk1 --proc-type=auto --log-level=4 ]
TACIS:
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
0000:07:00.0     032WEU10J7000024     HWE52P431T6M002N                         1           1.60  TB /   1.60  TB    512   B +  0 B   1036
0000:05:00.0     18161E0F3BE7         Micron_9200_MTFDHAL1T9TCT                1           1.92  TB /   1.92  TB    512   B +  0 B   101008P0
0000:25:00.0     17501D76489F         Micron_9200_MTFDHAL1T9TCT                1           1.92  TB /   1.92  TB    512   B +  0 B   101008P0
0000:27:00.0     17501D7648A1         Micron_9200_MTFDHAL1T9TCT                1           1.92  TB /   1.92  TB    512   B +  0 B   101008P0
**_EAL: Driver cannot detach the device (0000:07:00.0)
EAL: Failed to hotplug remove device on primary
EAL: Failed to hotplug remove device
EAL: Driver cannot detach the device (0000:05:00.0)
EAL: Failed to hotplug remove device on primary
EAL: Failed to hotplug remove device
EAL: Driver cannot detach the device (0000:25:00.0)
EAL: Failed to hotplug remove device on primary
EAL: Failed to hotplug remove device
EAL: Driver cannot detach the device (0000:27:00.0)
EAL: Failed to hotplug remove device on primary
EAL: Failed to hotplug remove device_**

## Expected Behavior

Error messages should not be printed

## Current Behavior

Error messages printed for each nvme controller

## Steps to Reproduce

1. Load SPDK and then nvmf_tgt
2. run "nvme list" or "idenfity" command to see error messages
3.
4.

## Context (Environment including OS version, SPDK version, etc.)

SPDK v19.01 / DPDK 18.11.0 
nvme cli version 1.6 & master(issue seen with both versions

**Comment by darsto** [comment] 2019-03-01 07:15
Those messages are somewhat expected in multi-process w/ DPDK 18.11.

SPDK calls rte_pci_detach() on shutdown in each process and for DPDK <18.11 this resulted in releasing PCI resources for that single process - meaning it *had to* be called in each process separately. With DPDK 18.11 rte_pci_detach() does an internal IPC and tries to detach the device in all the processes within a shared-memory group, meaning it *has to* be called just once. SPDK, as a stopgap, fails those "unexpected" detach requests that came through IPC. It results in those error messages being printed, but doesn't cause any issues. SPDK still requires some work on the device management, but since the only visible drawback of current implementation are those messages, this is not a priority for now.

**Comment by darsto** [comment] 2019-03-01 07:16
This is not a bug technically, so I'm marking this as an "enhancement".

**Comment by nagendra-v** [comment] 2019-03-01 21:45
I don't think the problem is just messages, I am seeing cli commands hang. And also I am seeing other DPDK messages.

I am running several cli commands from scripts to get drive details, and I see commands either hang taking long time to get response.

EAL: rte_mp_request_sync failed
EAL: Failed to send hotplug request to secondary
EAL: Fail to recv reply for request /var/run/dpdk/spdk1/mp_socket_3683_657abe28a83:eal_dev_mp_request
EAL: Fail to recv reply for request /var/run/dpdk/spdk1/mp_socket_3675_6099422d765:eal_dev_mp_request
EAL: Fail to recv reply for request /var/run/dpdk/spdk1/mp_socket_3672_5ffd167d93c:eal_dev_mp_request
EAL: rte_mp_request_sync failed

**Comment by nagendra-v** [comment] 2019-03-01 23:02
@dancios  "With DPDK 18.11 rte_pci_detach() does an internal IPC and tries to detach the device in all the processes within a shared-memory group, meaning it _has to_ be called just once".
I am running only one instance of nvme cli, no other utility running. So there is no multiple process's doing detach, why the error messages are still shown?

**Comment by darsto** [comment] 2019-03-05 20:02
@nagendra-v Could you try running nvme-cli with "shm_id=-1" in the config file and see if it helps?

nvme-cli shouldn't hang and there's probably a bug somewhere, but let's try to narrow it down first.

**Comment by nagendra-v** [comment] 2019-03-08 02:25
Tried "shmd_id=-1", still see the issue.

I think the issue(utilities stuck) is when two utilities, like nvme cli and nvme_manage/identify OR two instance of nvme cli, are running at the same time. 

With nvmf_tgt running and when a utility does attach_cb, are they attaching to same shared memory evetually?

**Comment by darsto** [comment] 2019-03-11 13:40
@nagendra-v both nvmf_tgt and nvme-cli are SPDK applications. They can share their memory as long as they use the same "shm_id".

The original post mentions just one nvmf_tgt and one nvme-cli instance. I'd expect such setup to work correctly since that's what we test in our per-patch testing. Since you're saying you run into issues with multiple nvme-cli instances, could you write down the specific reproduction steps?

Thanks,
D.

**Comment by nagendra-v** [comment] 2019-03-14 23:49
@darsto Sorry for the confusion.
I opened this issue when I saw **_"EAL"_** the prints while testing SPDK v19.01 with just nvmf_tgt and nvme-cli.

Later on I tried with nvmf_tgt(shm-id set to 1) running and nvme-cli(with shm_id=1) along with with other nvme utility nvme_manage(also with -i 1) OR another instance or nvme-cli. That's when I noticed nvme-cli and nvme utility hang. But I haven't got chance to identify which combination, two instances of nvme-cli OR nvme utility with nvme-cli, causing the hang.

Let me know, if you want me to open another bug for hang issue,

**Comment by darsto** [comment] 2019-03-26 09:32
I think we can agree that nvme-cli could use some multi-process fuzz testing. We'll discuss this on today's bug scrub.

**Comment by darsto** [comment] 2019-03-26 15:16
@Comphix could you take a look? We could use some fuzz testing for nvme-cli.

**Comment by darsto** [comment] 2019-06-18 15:09
Bug scrub: We've integrated all the nvme-cli functionality into usual spdk targets as RPCs. nvme-cli is definitely buggy, but we don't want to spend too much time fixing it now.

**Comment by cranechu** [comment] 2019-08-27 08:46
It seems the same issue I met when trying to upgrade SPDK to v19.04 and v19.07 in my application pynvme. Finally, I decided to disable the function hotplug_mp, and fixed a bug in DPDK. (here is the changes for reference: https://github.com/cranechu/dpdk/commit/01579b2ec4341e8ecd44e0fd79e66643ed8cad6c

After that, I ported my application from SPDK v19.01 to v19.07 successfully.

**Comment by darsto** [comment] 2019-08-27 15:59
Closing then. Thanks @cranechu !

**Closed by darsto** 2019-08-27 15:59 UTC
Labels: Low, bug
