### ISSUE TITLE
Observing SIGSEGV in _nvme_qpair_submit_request

### ISSUE THREAD

**Issue by hasethuraman** [spdk/spdk#3380] opened 2024-05-16 07:58 UTC
# Sighting report

We observed two SIGSEGV as shown in below screenshots. 

![image](https://github.com/spdk/spdk/assets/10446093/cd066e0d-fc2c-4901-a712-69c54d0de911)
![image](https://github.com/spdk/spdk/assets/10446093/09b61b16-5923-46fd-9688-5ad8bd00c4f6)

We found that req->children points to an invalid memory and num_children as 0. At [line#965](https://github.com/spdk/spdk/blob/9f19acb513444ef6830b016dd5732471168101ef/lib/nvme/nvme_qpair.c#L965) see we access only if req->children != 0

Wondering if we should have had the similar check [here](https://github.com/spdk/spdk/blob/9f19acb513444ef6830b016dd5732471168101ef/lib/nvme/nvme_qpair.c#L955) too 

## Expected Behavior

Before we access req->children, we should see if num_children > 0 like in other place

## Current Behavior

In the code where the check is not present, tries to access invalid memory location causing SIGSEGV

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)

We are using the SPDK of this [commit](https://github.com/spdk/spdk/commit/13f9d281c93af370069fe17328f5971e95c19a2d) 
The function that we are discussing in nvme_qpair.c is intact in latest spdk code

So would like to know the community advice or reason on why we dont have that condition

**Comment by jimharris** [comment] 2024-05-16 16:10
Hi,

That commit is not part of SPDK, it appears to be part of some other branch in an SPDK fork.

It's also based on a much older version of SPDK, January 2022.

If you would like to further discuss this issue, please reproduce with v24.01 or master of mainline SPDK. Please also include details on how you get to this failure point. The backtraces seem to indicate you are using fabrics, and there is some detach operation going on, but if you'd like help you really need to provide a lot more details.

Thanks,

Jim

**Comment by hasethuraman** [comment] 2024-05-20 14:42
Thanks @jimharris. Yes, you are correct. It is based on Jan2022. This commit belongs to the tag at  https://github.com/openebs/spdk/commits/v22.01.x-mayastor/ 

I am not sure how easy for me to repro in later versions as I may have to do lot more changes in order to make our code work.

But we would like to get your advice/feedback in this version if possible.

When the NVME request is framed in nvme_allocate_request (where memset leaves the remaining payload to be initialized by nvme_request_add_child). If num_children remain uninitialized, the submit/remove/free (in _nvme_qpair_submit_request) wont be attempted as we have the num_children condition before that for device not in disconnected state.

But  our question is if num_children remain uninitialized and in addition when the device is disconnected, we will attempt to remove/free (in _nvme_qpair_submit_request).

Please correct if the above thought is wrong.

**Comment by jimharris** [comment] 2024-05-20 15:00
> Thanks @jimharris. Yes, you are correct. It is based on Jan2022. This commit belongs to the tag at https://github.com/openebs/spdk/commits/v22.01.x-mayastor/
> 
> I am not sure how easy for me to repro in later versions as I may have to do lot more changes in order to make our code work.
> 
> But we would like to get your advice/feedback in this version if possible.
> 
> When the NVME request is framed in nvme_allocate_request (where memset leaves the remaining payload to be initialized by nvme_request_add_child). If num_children remain uninitialized, the submit/remove/free (in _nvme_qpair_submit_request) wont be attempted as we have the num_children condition before that for device not in disconnected state.
> 
> But our question is if num_children remain uninitialized and in addition when the device is disconnected, we will attempt to remove/free (in _nvme_qpair_submit_request). This will result in accessing uninitialized children also.
> 
> Please correct if the above thought is wrong.

I see what you mean now @hasethuraman.  I agree a check is needed there.  Can you kindly explain your test case that hits this condition? It would be nice to add this to the SPDK CI. Also can you push a patch to make this change?

**Comment by ksztyber** [comment] 2024-09-03 15:06
[Bug scrub] Closing the issue, since there's no updates since May. @hasethuraman feel free to re-open if needed.

**Closed by ksztyber** 2024-09-03 15:06 UTC
Labels: Waiting on Submitter, Sighting
