### ISSUE TITLE
[vhost_blockdev] Segmentation fault at rte_spinlock_lock

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#2606] opened 2022-07-25 08:19 UTC
# CI Intermittent Failure

> 00:04:22.647  Core was generated by `/home/vagrant/spdk_repo/spdk/build/bin/spdk_tgt -r /tmp/spdk2.sock -g'.
> 00:04:22.647  Program terminated with signal SIGSEGV, Segmentation fault.
> 00:04:22.647  #0  0x00007f828d39fee3 in rte_spinlock_lock (sl=0x7f828d3e0001) at ../lib/eal/x86/include/rte_spinlock.h:28
> 00:04:22.647  28		asm volatile (
> 00:04:22.647  [Current thread is 1 (Thread 0x7f828bb96a00 (LWP 17274))]
> 00:04:22.647  
> 
> 00:04:22.648  Thread 1 (Thread 0x7f828bb96a00 (LWP 17274)):
> 00:04:22.648  #0  0x00007f828d39fee3 in rte_spinlock_lock (sl=0x7f828d3e0001) at ../lib/eal/x86/include/rte_spinlock.h:28
> 00:04:22.648          lock_val = 1
> 00:04:22.648  #1  0x00007f828d3a184d in malloc_heap_free (elem=0x200000266000) at ../lib/eal/common/malloc_heap.c:878
> 00:04:22.648          heap = 0x7f828d3e0001
> 00:04:22.648          start = 0x7fff3ad0e760
> 00:04:22.648          aligned_start = 0x200000266000
> 00:04:22.648          end = 0x7fff3ad0e710
> 00:04:22.648          aligned_end = 0x200003fff400
> 00:04:22.648          len = 140198691816157
> 00:04:22.648          aligned_len = 140734180157248
> 00:04:22.648          page_sz = 2097152
> 00:04:22.648          msl = 0x7f828d3e8348 <early_mem_config+136>
> 00:04:22.648          i = 8192
> 00:04:22.648          n_segs = 2515072
> 00:04:22.648          before_space = 5
> 00:04:22.648          after_space = 184320
> 00:04:22.648          ret = 0
> 00:04:22.648          unmapped = false
> 00:04:22.648          internal_conf = 0x7f828d3ef5c0 <internal_config>
> 00:04:22.648          asan_ptr = 0x200000266140
> 00:04:22.648          asan_data_len = 64
> 00:04:22.648  #2  0x00007f828d3a2c09 in mem_free (addr=0x200000266080, trace_ena=true) at ../lib/eal/common/rte_malloc.c:37
> 00:04:22.648  No locals.
> 00:04:22.648  #3  0x00007f828d3a2c4d in rte_free (addr=0x200000266080) at ../lib/eal/common/rte_malloc.c:44
> 00:04:22.648  No locals.
> 00:04:22.648  #4  0x00007f828d224dca in rte_mempool_free_memchunks (mp=0x200000266800) at ../lib/mempool/rte_mempool.c:292
> 00:04:22.648          memhdr = 0x200000266080
> 00:04:22.648          elt = 0x200003fff440
> 00:04:22.648  #5  0x00007f828d22685a in rte_mempool_free (mp=0x200000266800) at ../lib/mempool/rte_mempool.c:741
> 00:04:22.648          mempool_list = 0x7f828d3ec778 <early_mem_config+17592>
> 00:04:22.648          te = 0x200000266940
> 00:04:22.648  #6  0x00007f828e3f040e in spdk_mempool_free (mp=0x200000266800) at env.c:238
> 00:04:22.648  No locals.
> 00:04:22.648  #7  0x00007f828d644747 in spdk_thread_lib_fini () at thread.c:314
> 00:04:22.648          dev = 0x0
> 00:04:22.648          __func__ = "spdk_thread_lib_fini"
> 00:04:22.648  #8  0x00007f828dbadce2 in spdk_reactors_fini () at reactor.c:276
> 00:04:22.648          i = 128
> 00:04:22.648          reactor = 0x7f828a48bc78
> 00:04:22.648          __PRETTY_FUNCTION__ = "spdk_reactors_fini"
> 00:04:22.648  #9  0x00007f828dba9cd3 in spdk_app_fini () at app.c:628
> 00:04:22.648  No locals.
> 00:04:22.648  #10 0x000000000040281b in main (argc=4, argv=0x7fff3ad0ea88) at spdk_tgt.c:93
> 00:04:22.648          opts = {name = 0x4050f4 "spdk_tgt", json_config_file = 0x0, json_config_ignore_errors = false, rpc_addr = 

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_81098.html

## Execution failed at

> 00:04:12.652  ========== Backtrace start: ==========
> 00:04:12.652  
> 00:04:12.652  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:970 -> run_test(["vhost_blockdev"],["./test/vhost/initiator/blockdev.sh"])
> 00:04:12.652       ...
> 00:04:12.652     965 		timing_enter $test_name
> 00:04:12.652     966 		echo "************************************"
> 00:04:12.652     967 		echo "START TEST $test_name"
> 00:04:12.652     968 		echo "************************************"
> 00:04:12.652     969 		xtrace_restore
> 00:04:12.652  => 970 		time "$@"
> 00:04:12.652     971 		xtrace_disable
> 00:04:12.652     972 		echo "************************************"
> 00:04:12.652     973 		echo "END TEST $test_name"
> 00:04:12.652     974 		echo "************************************"
> 00:04:12.652     975 		timing_exit $test_name
> 00:04:12.652       ...
> 00:04:12.652  in /home/vagrant/spdk_repo/spdk/autotest.sh:286 -> main(["/home/vagrant/autorun-spdk.conf"])
> 00:04:12.652       ...
> 00:04:12.652     281 			run_test "blob_io_wait" ./test/blobstore/blob_io_wait/blob_io_wait.sh
> 00:04:12.652     282 		fi
> 00:04:12.652     283 	
> 00:04:12.652     284 		if [ $SPDK_TEST_VHOST_INIT -eq 1 ]; then
> 00:04:12.652     285 			timing_enter vhost_initiator
> 00:04:12.652  => 286 			run_test "vhost_blockdev" ./test/vhost/initiator/blockdev.sh
> 00:04:12.652     287 			run_test "spdkcli_virtio" ./test/spdkcli/virtio.sh
> 00:04:12.652     288 			run_test "vhost_shared" ./test/vhost/shared/shared.sh
> 00:04:12.652     289 			run_test "vhost_fuzz" ./test/vhost/fuzz/fuzz.sh
> 00:04:12.652     290 			timing_exit vhost_initiator
> 00:04:12.652     291 		fi
> 00:04:12.652       ...
> 00:04:12.652  
> 00:04:12.652  ========== Backtrace end ==========

**Comment by spdkci** [comment] 2022-07-25 08:20
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_81098.html

**Comment by yidong0635** [comment] 2022-07-26 02:10
@shuhei-matsumoto  Is this duplicated with #2596 ?

**Comment by ksztyber** [comment] 2022-07-26 08:20
Yeah, I agree with @yidong0635, this looks like a duplicate of #2596, so I'm closing this one, as there are more comments there. @shuhei-matsumoto if you think this is a separate issue, please feel free to reopen it.

**Closed by ksztyber** 2022-07-26 08:20 UTC
Labels: Intermittent Failure
