### ISSUE TITLE
nvmf_dif test fails w/keep alive timeout

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1863] opened 2021-03-28 11:44 UTC
(SEE LATER NOTES, THERE ARE ERRORS EARLIER IN THE OUTPUT THAT ARE LIKELY CAUSING THE ISSUES BELOW

## Current Behavior

When running NVMe-oF tests with TCP transport layer enabled nvmf_dif test (test/nvmf/target/dif.sh) fails on fio test due to:

```
00:09:01.253  fio: io engine spdk_bdev init failed. Perhaps try reducing io depth?
00:09:01.253  fio: pid=1325890, err=-1/
[...log truncated here...]
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=43053056, buflen=4096
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=17924096, buflen=4096
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=62648320, buflen=4096
00:09:01.255  fio: pid=1325889, err=5/file:io_u.c:1806, func=io_u error, error=Input/output error
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=7122944, buflen=4096
00:09:01.255  fio: pid=1325887, err=5/file:io_u.c:1806, func=io_u error, error=Input/output error
00:09:01.255  [2021-03-28 12:51:24.566146] bdev_nvme.c: 606:_bdev_nvme_failover_start: *NOTICE*: Unable to perform reset, already in progress.
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=42823680, buflen=4096
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=21368832, buflen=4096
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=655360, buflen=4096
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=23891968, buflen=4096
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=34185216, buflen=4096
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=50642944, buflen=4096
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=6262784, buflen=4096
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=44797952, buflen=4096
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=18182144, buflen=4096
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=17981440, buflen=4096
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=8749056, buflen=4096
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=54669312, buflen=4096
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=3141632, buflen=4096
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=3059712, buflen=4096
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=62361600, buflen=4096
00:09:01.255  fio: io_u error on file Nvme2n1: Input/output error: read offset=59977728, buflen=4096
00:09:01.255  fio: pid=1325883, err=5/file:io_u.c:1806, func=io_u error, error=Input/output error
00:09:01.256  [2021-03-28 12:51:24.566482] bdev_nvme.c: 249:bdev_nvme_disconnected_qpair_cb: *WARNING*: Failed to reconnect to qpair 0x7f1bb8037e60, errno 6
00:09:01.256  [2021-03-28 12:51:24.566517] bdev_nvme.c: 249:bdev_nvme_disconnected_qpair_cb: *WARNING*: Failed to reconnect to qpair 0x7f1bbc037e60, errno 6
00:09:01.257  fio: io_u error on file Nvme2n1: Input/output error: read offset=17874944, buflen=4096
00:09:01.257  fio: io_u error on file Nvme2n1: Input/output error: read offset=40820736, buflen=4096
```

**Currently this is not reproducible in CI**
This issue was detected when testing this change: https://review.spdk.io/gerrit/c/spdk/spdk/+/6998 on a bunch of physical system (G1,GP2, GP10 from CI). The test purpose was to verify that test/nvmf/nvmf.sh test suite would successfully pass on a physical system instead of a VM (what we normally use in CI for TCP tests). These physical systems OS version and kernel differs slightly from what we use in VMs, so it might be a OS/Kernel version issue.

## Steps to Reproduce

1. Build SPDK with:
```
./configure --enable-debug --enable-werror --with-rdma --with-idxd --with-fio=/usr/src/fio --with-iscsi-initiator --disable-unit-tests --enable-ubsan --enable-coverage --without-isal
```
2. Run ` test/nvmf/target/dif.sh --iso --transport=tcp` (or just run the whole autotest.sh test script)

## Context (Environment including OS version, SPDK version, etc.)

SPDK b33da506b54 (with f16657837f3 cherry picked on top)
Fedora 32 5.11.7-100.fc32.x86_64
gcc version 10.2.1 20200723 (Red Hat 10.2.1-1) (GCC)
Log files: 
[build.zip](https://github.com/spdk/spdk/files/6217236/build.zip)

**Comment by karlatec** [comment] 2021-03-28 11:47
@wawryk  or @mikeBashStuff  can I ask you to try to reproduce this on Fedora 32 or Fedora 33 VMs? They should have a similar kernel version to what's described in the issue. You might need to run this in a loop for some time, because the reproducibility is not high - I saw this 3 times out of around 80 autotest.sh runs.

**Comment by karlatec** [comment] 2021-03-28 11:47
This issue affects #1851 (running TCP tests on bare-metal instead of a VM), but due to low reproducibility is not a blocker.

**Comment by spdkci** [comment] 2021-04-01 10:12
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_40622.html

**Comment by spdkci** [comment] 2021-04-01 12:43
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_40628.html

**Comment by spdkci** [comment] 2021-04-01 14:54
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_40667.html

**Comment by spdkci** [comment] 2021-04-01 23:33
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_40659.html

**Comment by karlatec** [comment] 2021-04-08 06:58
@wawryk @mikeBashStuff  any updates on this one and what's the reproducibility using a VM?

**Comment by wawryk** [comment] 2021-04-12 06:04
@karlatec using fedora 32 and fedora 33 vm's and running tests in loop few hundred times, there were no reproduction.

**Comment by karlatec** [comment] 2021-04-12 08:43
@wawryk could you reproduce this again on GP1 then? Just to be sure this actually reproduces.

**Comment by wawryk** [comment] 2021-04-13 08:00
On 300 test on GP1, there was no fails.

**Comment by spdkci** [comment] 2021-04-14 22:49
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_41965.html

**Comment by spdkci** [comment] 2021-04-19 15:51
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_42530.html

**Comment by tomzawadzki** [comment] 2021-04-20 15:26
[Bug scrub] @peluse can take  a look on the issue.
It looks like now it is possible to reproduce on physical machines running TCP tests, hence the latest two reports.

**Comment by spdkci** [comment] 2021-04-21 07:47
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_42764.html

**Comment by spdkci** [comment] 2021-04-22 06:08
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_42975.html

**Comment by spdkci** [comment] 2021-04-22 19:40
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_43177.html

**Comment by spdkci** [comment] 2021-05-04 11:24
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_44069.html

**Comment by spdkci** [comment] 2021-05-07 14:32
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_44651.html

**Comment by spdkci** [comment] 2021-05-07 14:39
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_44637.html

**Comment by spdkci** [comment] 2021-05-07 14:39
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_44657.html

**Comment by spdkci** [comment] 2021-05-07 16:20
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_44687.html

**Comment by spdkci** [comment] 2021-05-07 17:22
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_44716.html

**Comment by spdkci** [comment] 2021-05-10 01:39
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_44919.html

**Comment by spdkci** [comment] 2021-05-17 11:18
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_47435.html

**Comment by spdkci** [comment] 2021-05-19 10:59
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_47632.html

**Comment by spdkci** [comment] 2021-05-19 12:23
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_47716.html

**Comment by spdkci** [comment] 2021-05-19 13:03
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_47722.html

**Comment by spdkci** [comment] 2021-05-19 13:09
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_47724.html

**Comment by spdkci** [comment] 2021-05-19 13:34
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_47728.html

**Comment by spdkci** [comment] 2021-05-19 15:56
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_47738.html

**Comment by spdkci** [comment] 2021-05-20 15:19
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_47861.html

**Comment by spdkci** [comment] 2021-06-10 15:07
Another instance of this failure. Reported by @tomzawadzki. log: Not Found

**Comment by peluse** [comment] 2021-06-14 22:12
Wow, I'm just all over it.  Forgot I owned this, will check it out this week, my bad

**Comment by peluse** [comment] 2021-06-14 22:29
I just ran 6x on 2 different systems without issues

System 1: Linux localhost.localdomain 5.6.13-100.fc30.x86_64 #1 SMP Fri May 15 00:36:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

System 2: Linux pels3 5.4.0-59-generic #65-Ubuntu SMP Thu Dec 10 12:01:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

In one of the prev CI failures this stuff preceedes the fio errors, could this be where the train left the tracks? 

nqn.2016-06.io.spdk:cnode2 due to keep alive timeout.
00:09:05.826  [2021-05-20 15:34:47.121808] ctrlr.c: 543:nvmf_ctrlr_add_io_qpair: *ERROR*: Inactive admin qpair (state 3, group (nil))
00:09:05.826  [2021-05-20 15:34:47.122004] nvme_qpair.c: 717:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 on qpair id 7
00:09:05.826  [2021-05-20 15:34:47.122127] nvme_fabric.c: 460:nvme_fabric_qpair_connect: *ERROR*: Connect command failed, rc -125, trtype:TCP adrfam:IPv4 traddr:10.0.0.2 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode1
00:09:05.826  [2021-05-20 15:34:47.122145] nvme_fabric.c: 468:nvme_fabric_qpair_connect: *ERROR*: Connect command completed with error: sct 0, sc 8
00:09:05.826  [2021-05-20 15:34:47.122157] nvme_tcp.c:1901:nvme_tcp_ctrlr_connect_qpair: *ERROR*: Failed to send an NVMe-oF Fabric CONNECT command
00:09:05.826  [2021-05-20 15:34:47.122173] bdev_nvme.c: 375:bdev_nvme_create_qpair: *ERROR*: Unable to connect I/O qpair.
00:09:05.827  [2021-05-20 15:34:47.122455] fio_plugin.c: 549:spdk_fio_bdev_open: *ERROR*: Unable to get I/O channel for bdev.

**Comment by spdkci** [comment] 2021-06-15 07:05
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_49689.html

**Comment by peluse** [comment] 2021-06-15 13:25
Same thing on this latest one.  The fio failures happen after the following startup (?) issues:

0:09:11.740  Starting 24 threads
00:09:11.740  [2021-06-14 16:00:10.333193] Starting SPDK v21.07-pre git sha1 b4450d4b3 / DPDK 21.02.0 initialization...
00:09:11.740  [2021-06-14 16:00:10.333320] [ DPDK EAL parameters: [2021-06-14 16:00:10.333333] fio [2021-06-14 16:00:10.333342] --no-shconf [2021-06-14 16:00:10.333349] -c 0x1 [2021-06-14 16:00:10.333357] --log-level=lib.eal:6 [2021-06-14 16:00:10.333364] --log-level=lib.cryptodev:5 [2021-06-14 16:00:10.333372] --log-level=user1:6 [2021-06-14 16:00:10.333380] --base-virtaddr=0x200000000000 [2021-06-14 16:00:10.333388] --match-allocations [2021-06-14 16:00:10.333424] --file-prefix=spdk_pid287962 [2021-06-14 16:00:10.333433] ]
00:09:11.784  EAL: No free 2048 kB hugepages reported on node 1
00:09:11.784  EAL: No available 1048576 kB hugepages reported
00:09:11.788  EAL: No legacy callbacks, legacy socket not created
00:09:11.937  [2021-06-14 16:00:10.530267] accel_engine.c: 920:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:09:23.175  [2021-06-14 16:00:21.767336] ctrlr.c: 185:nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host nqn.2016-06.io.spdk:host0 from subsystem nqn.2016-06.io.spdk:cnode0 due to keep alive timeout.
00:09:23.175  [2021-06-14 16:00:21.767481] ctrlr.c: 185:nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host nqn.2016-06.io.spdk:host1 from subsystem nqn.2016-06.io.spdk:cnode1 due to keep alive timeout.
00:09:23.175  [2021-06-14 16:00:21.767539] ctrlr.c: 185:nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host nqn.2016-06.io.spdk:host2 from subsystem nqn.2016-06.io.spdk:cnode2 due to keep alive timeout.
00:09:23.188  [2021-06-14 16:00:21.781101] nvme_qpair.c: 717:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 on qpair id 5
00:09:23.188  [2021-06-14 16:00:21.781245] nvme_qpair.c: 717:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 on qpair id 7
00:09:23.190  [2021-06-14 16:00:21.782599] nvme_qpair.c: 717:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 on qpair id 5
00:09:23.190  [2021-06-14 16:00:21.782728] nvme_qpair.c: 717:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 on qpair id 6
00:09:23.191  [2021-06-14 16:00:21.783857] nvme_qpair.c: 717:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 on qpair id 5
00:09:23.198  [2021-06-14 16:00:21.790439] ctrlr.c: 576:_nvmf_ctrlr_add_io_qpair: *ERROR*: Unknown controller ID 0x1
00:09:23.198  [2021-06-14 16:00:21.790612] nvme_fabric.c: 452:nvme_fabric_qpair_connect: *ERROR*: Connect command failed, rc -5, trtype:TCP adrfam:IPv4 traddr:10.0.0.2 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode0
00:09:23.198  [2021-06-14 16:00:21.790668] nvme_fabric.c: 460:nvme_fabric_qpair_connect: *ERROR*: Connect command completed with error: sct 1, sc 130
00:09:23.198  [2021-06-14 16:00:21.790708] nvme_tcp.c:1875:nvme_tcp_ctrlr_connect_qpair: *ERROR*: Failed to send an NVMe-oF Fabric CONNECT command
00:09:23.199  [2021-06-14 16:00:21.790717] ctrlr.c: 576:_nvmf_ctrlr_add_io_qpair: *ERROR*: Unknown controller ID 0x1
00:09:23.199  [2021-06-14 16:00:21.790750] ctrlr.c: 576:_nvmf_ctrlr_add_io_qpair: *ERROR*: Unknown controller ID 0x1

**Comment by spdkci** [comment] 2021-06-16 06:38
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_49865.html

**Comment by spdkci** [comment] 2021-06-16 08:49
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_49941.html

**Comment by peluse** [comment] 2021-06-17 22:08
@karlatec so I looked a little closer at this and consulted with Ben as well - the fio errors are most definitely wreckage from the real problem of the keep-alive timeout expiring.  Assuming this is loopback then it's, of course, not a real matter of network time it's something screwy preventing the keep-alive from staying alive.  

Couple of things I'l look at  some more but in the meantime can you confirm which initiator this test is using, us or the kernel?  And, then is it possible to switch to the other in CI for a period of a few weeks and see if there are more reproductions.  If the issue goes away it's something in the SPDK initiator, if it does not it's on the target side.  That will narrow things down quite a bit.  Can we do this?

Also, if you know off the top of your head what's running on what cores on the single machine that would be great too.  If not I can go dig through the test scripts but if you happen to know just update here.  Thanks!

**Comment by spdkci** [comment] 2021-06-24 17:15
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_50824.html

**Comment by peluse** [comment] 2021-06-24 17:25
@KariukiJ did you see my request earlier?

**Comment by mikeBashStuff** [comment] 2021-06-24 18:32
@peluse For these tests we are using SPDK as the initiator. I guess we could use this https://review.spdk.io/gerrit/c/spdk/spdk/+/8507 as means of switching to the kernel side and run some tests with this patch on top on an isolated group of systems that have been affected by this issue (I guess selecting a couple from the list in the description would do).

**Comment by peluse** [comment] 2021-06-24 18:47
@mikeBashStuff that would be great thanks! Do you need to run on an isolated set or can you just switch to kernel init for everything for a few weeks? I realized we'd lose some initiator coverage during that time but I assume the SPDK initiator is used in way more than this dif test yeah?

**Comment by mikeBashStuff** [comment] 2021-06-24 19:09
@peluse I am not sure we can do that. The CI pool run jobs - which execute functional tests - on per-patch bases. So to switch everything we would need to actually merge changes for these tests - that's the only way to make sure every job triggered for every patch out there will include this particular version of the dif tests. 

The alternative is to either trigger manually bunch of per-patch jobs with https://review.spdk.io/gerrit/c/spdk/spdk/+/8507 (or something similar) on top and see how that goes across the CI or just pull some systems out of the CI (I think it would be best to focus on those where it's known this issue happened at least once)  and then start executing only these dif tests in a loop for couple of days or more and see how that goes. I will definitely discuss this with @karlatec tomorrow to make sure we do it best way possible though. :)

**Comment by peluse** [comment] 2021-06-24 19:42
@mikeBashStuff OK I guess I don't see what the problem is.  My vote would be switch them all and if it doesn't work revert.  This will give us the most amount data the quickest.  Ben is out but this is what he was thinking too, will ping Jim...

**Comment by jimharris** [comment] 2021-06-24 20:10
@peluse, do you have a patch that would switch this test over to use the kernel initiator?  I'm not even sure we can do this type of DIF testing with the kernel nvme driver (but would love to be proved wrong).

I just have to believe there's a real SPDK bug here, probably somehow related to DIF - we have lots and lots of nvmf tests running in CI and this is the only case I've seen where we get these kind of keep alive timeouts.

We need to look in detail at each of the failures to see which test it failed on.  There are a lot of test cases in that dif.sh script.  An initial scan indicates it's usually (maybe always) one of the fio_dif_rand_params tests.  Most of the ones I saw were the second test in that function, but did see one where it was the first.

So I guess I'm reluctant to switch this over to the kernel initiator yet, even if its possible.  I think we need to focus first on what we can do to get more information when these failures actually occur (since it seems to be very very infrequent).

**Comment by peluse** [comment] 2021-06-24 20:19
@jimharris thanks - this was the first step Ben suggested to determine if the issue was in our initiator or our target but yeah I guess I didn't think about diff being doable with the kernel initiator to begin with.  I'm getting ready to head out on vacation until Tue next week, will pick it up then (yes, the patch to switch is above in the history from @mikeBashStuff)

**Comment by shuhei-matsumoto** [comment] 2021-06-24 20:40
@jimharris @peluse As long as we read https://www.kernel.org/doc/Documentation/block/data-integrity.txt it should be possible to read and write data with DIF metadata without any support from application or filesystem. I haven't tried yet and does not have such chance but I found DIF support in Linux kernel NVMe driver source code and it will be worth to try.

**Comment by karlatec** [comment] 2021-06-25 08:20
@peluse 
> Assuming this is loopback then it's, of course, not a real matter of network time it's something screwy preventing the keep-alive from staying alive.

It is loopback, but keep in mind that it's in fact a real physical loopback. All nodes running "nvmf-tcp-phy" tests have a 2-port NIC installed, and the ports are connected with DAC cable.
As a side note: this is not the case for "nvmf-phy" (which actually runs RDMA tests) job where we just rely on system local loopback.

> Do you need to run on an isolated set or can you just switch to kernel init for everything for a few weeks? I realized we'd lose some initiator coverage during that time but I assume the SPDK initiator is used in way more than this dif test yeah?

We can do that, but it's more a matter of changing the test scripts (see patch from @mikeBashStuff) rather than changing the configuration of CI itself.

**Comment by spdkci** [comment] 2021-06-25 19:32
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_50981.html

**Comment by spdkci** [comment] 2021-06-28 02:49
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_51036.html

**Comment by spdkci** [comment] 2021-06-28 04:33
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_51043.html

**Comment by spdkci** [comment] 2021-06-29 05:05
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_51160.html

**Comment by spdkci** [comment] 2021-06-29 05:05
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_51159.html

**Comment by spdkci** [comment] 2021-06-29 05:09
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_51156.html

**Comment by peluse** [comment] 2021-06-29 19:54
Looks like all the failures are within one function, commented it out in https://review.spdk.io/gerrit/c/spdk/spdk/+/8549 to see if we let it run for a bit if it goes away or if just the next test will start to fail.

**Comment by jimharris** [comment] 2021-06-29 20:36
> https://ci.spdk.io/public_build/autotest-per-patch_51160.html

This failure is not the nvmf_dif failure.  @peluse - is that why you added the thumbs down emoji?  This failure is the #2017 failure.

**Comment by jimharris** [comment] 2021-06-29 20:38
> https://ci.spdk.io/public_build/autotest-per-patch_51043.html

This test run is not associated with this failure.

**Comment by mikeBashStuff** [comment] 2021-06-30 15:36
Just to note: I have been running `dif.sh` tests with https://review.spdk.io/gerrit/c/spdk/spdk/+/8507 changes in the loop on one of the previously affected systems (GP11) for quite some time now (it already run >150 times) and so far none of the tests have failed (granted I had to add https://review.spdk.io/gerrit/c/spdk/spdk/+/8541 on top since I was unfortunately facing issue as described in https://github.com/spdk/spdk/issues/2015).

**Comment by peluse** [comment] 2021-06-30 16:13
@mikeBashStuff thanks for doing that.  I ran with your patch and added some debug to the target and determined that in this config the target keep alive timer is disabled.  Probably DIFF too.  Have another patch running that changes some order of tests as it's the same test (rand) that's failing within the script every time.  Just trying to narrow down where to start hunting in the code.  So far it hasn't failed.  Can probably drop the kernel init test - thanks again though

**Comment by peluse** [comment] 2021-06-30 16:42
Besides the patch that changes order or tests running CI (going slow, not proving to be very useful) I have a local version running 1000 in a row with debug log turned on.  Maybe that will provide a clue if it ever fails

**Comment by peluse** [comment] 2021-06-30 17:58
@karlatec @mikeBashStuff I see you guys were looking at this one, do you believe they might be related? https://github.com/spdk/spdk/issues/1900

**Comment by peluse** [comment] 2021-06-30 18:45
FYI switched my test machine to Fedora.. @jimharris see note above about Network Manager issue #1900

**Comment by peluse** [comment] 2021-07-06 15:21
@mikeBashStuff can you please run this patch in a loop in CI and let me know when we get a failure? All it does is turn on nvmf target debug logging.  thanks.  https://review.spdk.io/gerrit/c/spdk/spdk/+/8549

**Comment by mikeBashStuff** [comment] 2021-07-08 08:09
@peluse Sure, will try to get it done till the end of the week.

**Comment by mikeBashStuff** [comment] 2021-07-09 10:33
@peluse Attaching logs from the test (it's quite big just fyi) - the `fio_dif_rand_params` test fails on `##### Run 8`. As to #1900 I made sure all the net devices used for the test are not managed by the nm when it was executing just to be sure it's not a factor here.
[debug_1863.log.zip](https://github.com/spdk/spdk/files/6790643/debug_1863.log.zip)

**Comment by spdkci** [comment] 2021-07-14 05:21
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_52764.html

**Comment by spdkci** [comment] 2021-07-14 05:22
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_52768.html

**Comment by peluse** [comment] 2021-07-14 15:10
@mikeBashStuff I can't open that logfile on my mac for some reason.  Can you report as a tar?

**Comment by mikeBashStuff** [comment] 2021-07-14 15:17
@peluse github won't accept it as .tar. But the file inside the .zip is just a compressed one with xz (I can't upload it here uncompressed since it's ~100MB in size).

**Comment by peluse** [comment] 2021-07-15 15:47
[
[log.txt](https://github.com/spdk/spdk/files/6824502/log.txt)
](url)

**Comment by peluse** [comment] 2021-07-15 15:48
Prev entry is a snippet of the giant log file with nvmf debug turned on. The only difference I can see is that with the passing case all the log messages of READ and SUCCESS are almost ping pong, sometimes 2 in a row.  On the failing cases there are always a long serries of READ messages then a long series of SUCCESS

**Comment by spdkci** [comment] 2021-07-22 06:51
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_53569.html

**Comment by spdkci** [comment] 2021-07-22 07:10
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_53765.html

**Comment by spdkci** [comment] 2021-07-22 09:49
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_53837.html

**Comment by spdkci** [comment] 2021-07-22 13:04
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_53866.html

**Comment by spdkci** [comment] 2021-07-23 07:15
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_53926.html

**Comment by spdkci** [comment] 2021-07-23 07:18
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_53927.html

**Comment by tomzawadzki** [comment] 2021-07-27 15:05
[Bug scrub] @peluse do you have some suggestions on next steps, as additional tests or logs that could help narrow down the cause ?

**Comment by peluse** [comment] 2021-07-27 15:19
Yes, I have some next steps that I'll be working on this week

**Comment by spdkci** [comment] 2021-07-28 06:13
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_54400.html

**Comment by spdkci** [comment] 2021-07-29 06:23
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_54469.html

**Comment by spdkci** [comment] 2021-08-03 09:29
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_54959.html

**Comment by peluse** [comment] 2021-08-03 13:56
@mikeBashStuff would you possibly be able to run this patch in a loop for me? https://review.spdk.io/gerrit/c/spdk/spdk/+/8549 

It may have waay too much debug info in it, so lets see how crazy the log sizes are.  Thanks

**Comment by spdkci** [comment] 2021-08-04 01:31
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_54962.html

**Comment by mikeBashStuff** [comment] 2021-08-10 10:17
@peluse Sure, will try to spin it today.

**Comment by mikeBashStuff** [comment] 2021-08-10 14:22
Ok, so for the first try I started the test under SPDK built like so:

```
./configure --with-rdma --with-fio --without-isal --disable-unit-tests
```

It was spinning for several hours (133 iterations to be exact) with no failure, logs here (unfortunately, debug was not enabled for this run): 
[log_first_try.zip](https://github.com/spdk/spdk/files/6962157/log_first_try.zip)

I stopped the test since I realized  SPDK was not built exactly like autobuild does it nor how it was described in the issue. So I built it once more like so:

```
/configure --enable-debug --enable-werror --with-rdma --with-idxd --with-fio=/usr/src/fio --with-iscsi-initiator --disable-unit-tests --enable-ubsan --enable-coverage --without-isal
```

Started the test and this time it failed quite fast, after 8th iteration, logs here:
[log_second_try.zip](https://github.com/spdk/spdk/files/6962174/log_second_try.zip)
 
Not sure if `configure` options are a factor here or if it was just a coincidence but reckoned it's worth mentioning, especially that I've rebuilt SPDK again (same as during the first try) and the test has been happily running for over an hour now.

**Comment by peluse** [comment] 2021-08-10 14:39
Wow, intersting.  @jimharris @benlwalker I'll look into the logs this afternoon when I have some time.  The number of itterations passing vs failing with the 2 configure seems like a clue as opposed to coincidence...

**Comment by jimharris** [comment] 2021-08-10 14:56
Yeah - that is interesting!  I suspect either --enable-debug or --enable-ubsan would be the culprit.  @mikeBashStuff could you try adding those missing configure parameters one at a time to see which one starts causing the failures?  And then try the full autobuild configure line minus that one option to see if that runs without failure?

**Comment by mikeBashStuff** [comment] 2021-08-10 14:59
@jimharris Sure, will do.

**Comment by spdkci** [comment] 2021-08-12 10:39
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_55880.html

**Comment by spdkci** [comment] 2021-08-12 11:21
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_55881.html

**Comment by spdkci** [comment] 2021-08-12 20:19
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_55847.html

**Comment by spdkci** [comment] 2021-08-13 03:48
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_55939.html

**Comment by peluse** [comment] 2021-08-17 14:02
@mikeBashStuff could you re-run this patch over and over with the original (most failures) configure parms?  https://review.spdk.io/gerrit/c/spdk/spdk/+/8549

**Comment by spdkci** [comment] 2021-08-19 07:13
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_56325.html

**Comment by optimistyzy** [comment] 2021-08-25 06:43
This patch may be helpful:  https://review.spdk.io/gerrit/c/spdk/spdk/+/9284  Today when I am debugging uring related code, and realized there may be similar issue when using posix.  I think that in the test script, we used kernel initiator. And usually kernel will use all the cpu cores to do the connection first. So there will be more than 32 connections. And in our polling, every time we can only get 32 active sockets for pollin event.  It means that the sockets are lately added may get starvation especially in the qpair connection time.

**Comment by spdkci** [comment] 2021-08-31 06:15
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_57235.html

**Comment by mikeBashStuff** [comment] 2021-09-01 08:09
@peluse Sure, will try it out.

**Comment by mikeBashStuff** [comment] 2021-09-01 13:48
@peluse Since https://review.spdk.io/gerrit/c/spdk/spdk/+/9171 got recently merged I just rebuilt the SPDK on top of the latest master and re-run the tests (without lowering the `iodepth` param): It's been running for almost 6 hours, 235 iterations as of now, and no failure.

**Comment by jimharris** [comment] 2021-09-01 14:54
> @peluse Since https://review.spdk.io/gerrit/c/spdk/spdk/+/9171 got recently merged I just rebuilt the SPDK on top of the latest master and re-run the tests (without lowering the `iodepth` param): It's been running for almost 6 hours, 235 iterations as of now, and no failure.

That's interesting!  Let's keep it running but sounds like this issue is resolved.

@peluse, @optimistyzy  - I suspect there's something about completing the SW operations inline (instead of a poller) that was corrupting the nvmf dif calculations.  I'd feel better if we could pinpoint exactly why deferring the completions to a poller fixed this issue.

**Comment by peluse** [comment] 2021-09-01 14:57
@jimharris agreed I'm not a fan of "oh well, it seems to be working" :). Lets let is run for a while longer and make sure this appears to either fix or workaround it but not close it until I can zero in on it.  If this keeps working then it will be a pretty narrow code path to debug which would be GREAT!

**Comment by mikeBashStuff** [comment] 2021-09-02 13:04
Things are looking food - 1080 runs later, no failure.

**Comment by peluse** [comment] 2021-09-02 14:00
Great thanks!  Lets go into next week, then I'll start digging in to see if we can find out why this change is fixing/masking the root cause.

**Comment by spdkci** [comment] 2021-09-02 15:07
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_57453.html

**Comment by spdkci** [comment] 2021-09-07 17:37
Another instance of this failure. Reported by @tomek82. log: https://ci.spdk.io/public_build/autotest-per-patch_57246.html

**Comment by peluse** [comment] 2021-10-12 23:32
Seems like this still happens every once in a while, strange.  Either way I'm on sabbatical before the next bug scrub so this can sit until Dec 1 or someone else can grab it.  Good luck!

**Comment by spdkci** [comment] 2021-10-22 04:41
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_60894.html

**Comment by spdkci** [comment] 2022-01-05 06:21
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_67213.html

**Comment by jimharris** [comment] 2022-01-21 22:36
This issue hasn't been reported in 3 months.

**Closed by jimharris** 2022-01-21 22:36 UTC
Labels: Intermittent Failure
