### ISSUE TITLE
[CI] Error while removing network vagrant-libvirt. Call to virNetworkDestroy failed: 

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#2797] opened 2022-11-28 20:44 UTC
This wasn't specific to a test, it seemed to happen as CI was wrapping up its tests on one of the jobs.

```
00:24:08.873   18:47:50	-- common/autotest_common.sh@686 -- $ /usr/local/FlameGraph/flamegraph.pl --title 'Build Timing' --nametype Step: --countname seconds /home/vagrant/spdk_repo/spdk/../output/timing.txt
00:24:08.873  Ignored 1 lines with invalid format
00:24:08.873   18:47:50	-- spdk/autopackage.sh@39 -- $ exit 0
00:24:08.873  + [[ -n 4132 ]]
00:24:08.873  + sudo kill 4132
00:24:08.894  [Pipeline] }
00:24:08.914  [Pipeline] // timeout
00:24:08.920  [Pipeline] }
00:24:08.939  [Pipeline] // stage
00:24:08.945  [Pipeline] }
00:24:08.965  [Pipeline] // catchError
00:24:08.974  [Pipeline] stage
00:24:08.976  [Pipeline] { (Stop VM)
00:24:08.990  [Pipeline] sh
00:24:09.266  + vagrant halt
00:24:10.640  If run with libvirt provider please execute create_nvme_img.sh
00:24:10.640  If run with libvirt provider please execute create_nvme_img.sh
00:24:10.640  If run with libvirt provider please execute create_nvme_img.sh
00:24:10.640  If run with libvirt provider please execute create_nvme_img.sh
00:24:10.640  If run with libvirt provider please execute create_nvme_img.sh
00:24:10.640  If run with libvirt provider please execute create_nvme_img.sh
00:24:10.640  If run with libvirt provider please execute create_nvme_img.sh
00:24:10.640  If run with libvirt provider please execute create_nvme_img.sh
00:24:11.209  ==> default: Attempting graceful shutdown of VM...
00:24:16.475  [Pipeline] sh
00:24:16.754  + vagrant destroy -f
00:24:17.685  If run with libvirt provider please execute create_nvme_img.sh
00:24:17.685  If run with libvirt provider please execute create_nvme_img.sh
00:24:17.941  If run with libvirt provider please execute create_nvme_img.sh
00:24:17.942  If run with libvirt provider please execute create_nvme_img.sh
00:24:17.942  If run with libvirt provider please execute create_nvme_img.sh
00:24:17.942  If run with libvirt provider please execute create_nvme_img.sh
00:24:17.942  If run with libvirt provider please execute create_nvme_img.sh
00:24:17.942  If run with libvirt provider please execute create_nvme_img.sh
00:24:18.505  ==> default: Removing domain...
00:24:18.762  Error while removing network vagrant-libvirt. Call to virNetworkDestroy failed: Network not found: no network with matching uuid '07f96430-2f73-42b8-bfd0-76309d871421' (vagrant-libvirt).
00:24:18.774  [Pipeline] }
00:24:18.794  [Pipeline] // stage
00:24:18.802  [Pipeline] }
00:24:18.822  [Pipeline] // dir
00:24:18.830  [Pipeline] }
00:24:18.833  ERROR: script returned exit code 1
00:24:18.850  [Pipeline] // catchError
00:24:18.860  [Pipeline] stage
00:24:18.862  [Pipeline] { (Epilogue)
00:24:18.877  [Pipeline] sh
00:24:19.157  + jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh
00:24:19.157  jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh: line 9: cd: /var/jenkins/workspace/nvmf-tcp-uring-vg-autotest/output: No such file or directory
00:24:19.167  [Pipeline] }
00:24:19.187  [Pipeline] // stage
00:24:19.194  [Pipeline] }
00:24:19.211  [Pipeline] // wrap
00:24:19.219  [Pipeline] }
00:24:19.236  [Pipeline] // node
00:24:19.247  [Pipeline] End of Pipeline
00:24:19.259  ERROR: script returned exit code 1
00:24:19.264  Finished: FAILURE
```

**Comment by spdkci** [comment] 2022-11-28 20:45
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_91046.html

**Comment by mikeBashStuff** [comment] 2022-11-28 20:46
Duplicate of #2628

**Closed by mikeBashStuff** 2022-11-28 20:46 UTC
Labels: Intermittent Failure
