### ISSUE TITLE
nvme_autotest job timeout on Jenkins

### ISSUE THREAD

**Issue by Maciej-Szwed** [spdk/spdk#1041] opened 2019-11-07 10:53 UTC
nvme_autotest job on Jenkins timeout occurs after 4 minutes of tests execution and 15 minutes job overall time execution. This looks like some issue with job start. Logs:

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/49102/archive/nvme_autotest/build.log

**Comment by spdkci** [comment] 2019-11-07 10:56
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49102.html

**Comment by spdkci** [comment] 2019-11-07 11:03
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49103.html

**Comment by spdkci** [comment] 2019-11-07 11:09
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49104.html

**Comment by spdkci** [comment] 2019-11-07 12:31
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49111.html

**Comment by spdkci** [comment] 2019-11-07 12:32
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49109.html

**Comment by spdkci** [comment] 2019-11-07 12:38
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49119.html

**Comment by spdkci** [comment] 2019-11-07 12:41
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49118.html

**Comment by Maciej-Szwed** [comment] 2019-11-07 12:56
After closer investigation it looks like test hangs on line:
/usr/local/src/nvme-cli/nvme get-ns-id /dev/spdk/nvme0n1
from cuse tests set.

**Comment by karlatec** [comment] 2019-11-07 14:55
This is most probably caused by some of the VMs being updated to newer Fedora version, there are some issues after the update.
Just reverted them back to previous image. There might be some reports about this in next couple of hours as a result of latest failures.

**Comment by tomzawadzki** [comment] 2019-11-07 14:58
@karlatec All of the logs in this issue point to Fedora 28 VMs. This probably is not the right track to resolving this.

The failures/timeouts happen on get-ns-id, but sometimes on the preceding id-ctrl too.
@tkulasek Would you mind taking a look ?

**Comment by karlatec** [comment] 2019-11-07 15:00
@tomzawadzki Actually they point to F29, fedora_vm_6-10 were updated today and I just reverted them. I haven't seen a log from fedora_vm_1-5 which were not updated and still F28.

**Comment by tomzawadzki** [comment] 2019-11-07 15:04
Those occurred on fedora_vm8-10, but uname reports:
`Linux fedora28 5.3.6-100.fc29.x86_64 #1 SMP Mon Oct 14 21:48:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by karlatec** [comment] 2019-11-07 15:05
> fedora28

That's the hostname. Looks like it was not updated.

>  5.3.6-100.fc29

That's the actual system version.

**Comment by tkulasek** [comment] 2019-11-07 15:31
@tomzawadzki @karlatec It seems to be related to this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1762795

**Comment by jimharris** [comment] 2019-11-07 17:33
Removing intermittent failure tag from this since it's been root caused to a kernel bug on new Fedora.

Keeping open for now though.  @Maciej-Szwed @karlatec feel free to close once problematic VMs have all been downgraded.

**Comment by spdkci** [comment] 2019-11-08 09:27
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49124.html

**Comment by spdkci** [comment] 2019-11-08 09:27
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49137.html

**Comment by spdkci** [comment] 2019-11-08 09:28
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49138.html

**Comment by wawryk** [comment] 2019-11-08 12:08
VMs fedora_vm_6-10 once more updated to f29 but this time to avoid this kernel bug I downgrade kernel to 5.0.19-200.fc29.x86_64

We must watch how it works in CI and if still will be timeouts or fails we will revert back to f28

@tomzawadzki hostname updated to Fedora29 :)

**Comment by jimharris** [comment] 2019-11-14 04:38
Bug scrub: Closing this issue since hasn't been hit since downgrading kernels on VMs.

**Closed by jimharris** 2019-11-14 04:38 UTC
Labels: Intermittent Failure
