### ISSUE TITLE
[xnvme] bdev_xnvme_delete error report

### ISSUE THREAD

**Issue by ye1xchen** [spdk/spdk#2803] opened 2022-11-30 07:26 UTC
# Sighting report

Create the xnvme bdev, but report an error when deleting xnvme bdev.

## Expected Behavior

No error  report when deleting xnvme bdev.

## Current Behavior

thread.c:2077:spdk_io_device_unregister: *ERROR*: io_device 0x1542850 not found

## Steps to Reproduce

./build/bin/nvmf_tgt

```
./scripts/rpc.py bdev_xnvme_create /dev/ng0n1 bdev_ng0n1 io_uring_cmd
./scripts/rpc.py bdev_xnvme_delete bdev_ng0n1
thread.c:2077:spdk_io_device_unregister: *ERROR*: io_device 0x1542850 not found
```

```
./scripts/rpc.py bdev_xnvme_create /dev/nvme0n1 bdev_ng0n2 io_uring
./scripts/rpc.py bdev_xnvme_delete bdev_ng0n2
thread.c:2077:spdk_io_device_unregister: *ERROR*: io_device 0xb6a0b0 not found
```

## Context (Environment including OS version, SPDK version, etc.)

spdk: 565a44628d10dff7343568ea6dd4211d489595dc
fedora34 kernel6.0.0 or fedora 37

**Comment by jimharris** [comment] 2022-11-30 14:42
@krish-reddy, can you take a look?

**Comment by krish-reddy** [comment] 2022-12-07 07:07
Sure @jimharris , will do !

**Comment by ye1xchen** [comment] 2023-01-05 06:41
@krish-reddy, do you have any updates?

**Comment by krish-reddy** [comment] 2023-01-05 07:18
Hi @ye1xchen 
I am able to reproduce this on the latest SPDK code. Currently looking into it. Will update the status here !
Not much happened over the last month due to vacation and holidays.

**Comment by krish-reddy** [comment] 2023-01-05 10:33
Hi @jimharris @ye1xchen 
Please review the fix for this issue in the patch
https://review.spdk.io/gerrit/c/spdk/spdk/+/16144

**Comment by ye1xchen** [comment] 2023-01-05 11:33
Thanks @krish-reddy,  This patch worked.

**Comment by krish-reddy** [comment] 2023-01-09 13:54
Fix merged to the master.
https://github.com/spdk/spdk/commit/d093a9fb852104eee591f700d5d101bf4c2e0907

**Closed by krish-reddy** 2023-01-09 13:54 UTC
Labels: bug, Medium, Sighting, Patches out for review
