### ISSUE TITLE
[autobuild_check_format] /var/ci_repos/dpdk-submodule.git/objects does not exist

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1455] opened 2020-06-23 11:41 UTC
The following failure has been observed recently.

```
00:02:33.236  ************************************
00:02:33.236  START TEST autobuild_check_format
00:02:33.236  ************************************
00:02:33.236   09:47:03	$ xtrace_enable
00:02:33.236   09:47:03	$ ./scripts/check_format.sh
00:02:33.244  Checking file permissions... OK
00:02:35.988  Checking coding style... errors detected
00:02:36.815  error: object directory /var/ci_repos/dpdk-submodule.git/objects does not exist; check .git/objects/info/alternates
00:02:36.857  error: object directory /var/ci_repos/intel-ipsec-mb.git/objects does not exist; check .git/objects/info/alternates
00:02:36.857  error: bad tree object HEAD
00:02:36.857  fatal: 'git status --porcelain=2' failed in submodule intel-ipsec-mb
```

Rerunning auto test in the CI test pool did not fix this issue.
All following patches in the series were affected if one patch caused this failure.

Updating the patch fixed this issue. But any change was fine. There was no logical relationship between the patch and the result of auto test.

For example, in https://review.spdk.io/gerrit/c/spdk/spdk/+/3006, patch 1 caused always this but patch 2 did not cause this. There was no meaningful difference between patch  1 and 2.

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_19034.html

**Comment by shuhei-matsumoto** [comment] 2020-06-25 20:40
I observed this again, and updated the patch.
https://ci.spdk.io/public_build/autotest-per-patch_19324.html

**Comment by shuhei-matsumoto** [comment] 2020-06-26 05:29
Hi @karlatec @tomzawadzki 

This is my estimation but format check detected actual error but the reason of error was not shown, but the above reason was shown instead? So the tool may have the more detailed reason of the error.

**Comment by shuhei-matsumoto** [comment] 2020-06-26 05:55
The above estimation may be correct. The check tool found format error but the reason was 

```
00:02:36.815  error: object directory /var/ci_repos/dpdk-submodule.git/objects does not exist; check .git/objects/info/alternates
00:02:36.857  error: object directory /var/ci_repos/intel-ipsec-mb.git/objects does not exist; check .git/objects/info/alternates
00:02:36.857  error: bad tree object HEAD

```

Is it possible to output more accurate reason to the console? My installed tool could not find the error.

**Comment by tomzawadzki** [comment] 2020-06-30 15:11
[Bug scrub]: The check_format.sh fails on missing objects from 'mirror' repository for submodules. @mikeBashStuff Can you take a look what might be the cause ?

**Comment by mikeBashStuff** [comment] 2020-06-30 15:14
@tomzawadzki  Sure, will do.

**Comment by mikeBashStuff** [comment] 2020-07-06 07:38
Here's an attempt to mitigate this issue: https://review.spdk.io/gerrit/c/spdk/spdk/+/3223.

**Comment by tomzawadzki** [comment] 2020-07-07 08:10
@shuhei-matsumoto From the number of reports, it seems that the 'mirror' repository failed briefly for some reason (connectivity or state of the shared git repo). This was most likely brief occurrence. If it happens again, it should manifest in more expected place during the tests.

The mitigation [patch](https://review.spdk.io/gerrit/c/spdk/spdk/+/3223) posted by @mikeBashStuff was merged. This exact failure should no longer happen during check_format.sh. With that, I'll close the issue.

**Closed by tomzawadzki** 2020-07-07 08:10 UTC
Labels: Infrastructure
