### ISSUE TITLE
iostat issue

### ISSUE THREAD

**Issue by cunyinch** [spdk/spdk#1304] opened 2020-03-23 09:22 UTC
when I set 9 malloc disk with vhost app :
[Malloc]
NumberOfLuns 12
  # Malloc targets are 128M
LunSizeInMB 128
  # Block size. Default is 512 bytes.
BlockSize 4096

[VhostBlk0]
Path /var/tmp/vhost.0
Dev Malloc0
Cpumask 0x1

[VhostBlk1]
Path /var/tmp/vhost.1
Dev Malloc1
Cpumask 0x2

[VhostBlk2]
Path /var/tmp/vhost.2
Dev Malloc2
Cpumask 0x4

[VhostBlk3]
Path /var/tmp/vhost.3
Dev Malloc3
Cpumask 0x8

[VhostBlk4]
Path /var/tmp/vhost.4
Dev Malloc4
Cpumask 0x10

[VhostBlk5]
Path /var/tmp/vhost.5
Dev Malloc5
Cpumask 0x20

[VhostBlk6]
Path /var/tmp/vhost.6
Dev Malloc6
Cpumask 0x40

[VhostBlk7]
Path /var/tmp/vhost.7
Dev Malloc7
Cpumask 0x80

[VhostBlk8]
Path /var/tmp/vhost.8
Dev Malloc8
Cpumask 0x0100

[VhostBlk9]
Path /var/tmp/vhost.9
Dev Malloc9
Cpumask 0x0200

[VhostBlk10]
Path /var/tmp/vhost.10
Dev Malloc10
Cpumask 0x0400

[VhostBlk11]
Path /var/tmp/vhost.11
Dev Malloc11
Cpumask 0x0800

then run the bdev_set_qd_sampling_period as follow:

./scripts/rpc.py bdev_set_qd_sampling_period Malloc0  1
./scripts/rpc.py bdev_set_qd_sampling_period Malloc1  1
./scripts/rpc.py bdev_set_qd_sampling_period Malloc2  1
./scripts/rpc.py bdev_set_qd_sampling_period Malloc3  1
./scripts/rpc.py bdev_set_qd_sampling_period Malloc4  1
./scripts/rpc.py bdev_set_qd_sampling_period Malloc5  1
./scripts/rpc.py bdev_set_qd_sampling_period Malloc6  1
./scripts/rpc.py bdev_set_qd_sampling_period Malloc7  1
./scripts/rpc.py bdev_set_qd_sampling_period Malloc8  1

it works for Malloc0 - Malloc7, it failed when I try to set Malloc8

the driver error message as below:
thread.c: 747:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
thread.c: 747:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
thread.c: 747:spdk_thread_send_msg: *ERROR*: msg could not be enqueued
thread.c: 747:spdk_thread_send_msg: *ERROR*: msg could not be enqueued

**Comment by jimharris** [comment] 2020-03-23 14:30
Hi Cunyin!  Hope you are doing well.

bdev_set_qd_sampling_period is in units of microseconds.  I think sampling every 1 microsecond is probably too frequent.  1 millisecond (1000 microseconds) should be more than efficient.  1 millisecond is the same time period the Linux kernel uses for sampling queue depth.

I think what is happening here is that the polled timers are constantly expiring, which starts the sampling operations over and over again.  The error message indicates that the target thread's message ring is too full.

Could you try increasing the period from 1 to 1000 and see if that works?

**Comment by optimistyzy** [comment] 2020-03-24 02:59
Yesterday I had a talk with @cunyinch, I think that the issue is the define SPDK_MSG_BATCH_SIZE		8 defined in thread.c. We can support only 8 max message according to the static definition of this macro. see the code in _spdk_msg_queue_run_batch.  Currently, I suggest that @cunyinch  increases the value of SPDK_MSG_BATCH_SIZE  as a workaround. But even if there is 8 message to be handled,   it should be handled in another round. Still need to check why the message is lost and not executed in another round.

**Comment by jiaqizho** [comment] 2020-03-24 06:22
I tested this case , when SPDK_MSG_BATCH_SIZE more than 8 , it works.
This issue seem like is rte_ring issue , not a iostat issue.

**Comment by cunyinch** [comment] 2020-03-24 07:56
> Hi Cunyin! Hope you are doing well.
> 
> bdev_set_qd_sampling_period  is in units of microseconds. I think sampling every 1 microsecond is probably too frequent. 1 millisecond (1000 microseconds) should be more than efficient. 1 millisecond is the same time period the Linux kernel uses for sampling queue depth.
> 
> I think what is happening here is that the polled timers are constantly expiring, which starts the sampling operations over and over again. The error message indicates that the target thread's message ring is too full.
> 
> Could you try increasing the period from 1 to 1000 and see if that works?

Hi, Jim,

I just try your approch, it works :), I also try the method Ziye mentioned, set SPDK_MSG_BATCH_SIZE as 16, it works even if we set the  bdev_set_qd_sampling_period as 1, so it should not a bug, just make sure the bdev_set_qd_sampling_period  in a reasonable  range.

**Comment by cunyinch** [comment] 2020-03-24 07:59
@jimharris by the way, Yanbo is working on the https://github.com/jiaqizho/spdk-iostat-tool which adapt to the the latest version of SPDK, looking forword for this :)

**Comment by jimharris** [comment] 2020-03-24 13:48
Closing this issue.  We may want to consider increasing SPDK_MSG_BATCH_SIZE, but we can decide that separately from this issue.  Increasing the qd_sampling_period is the correct fix for this issue.

**Closed by jimharris** 2020-03-24 13:48 UTC
