### ISSUE TITLE
Cannot copy large file into VM when using SPDK with OCF

### ISSUE THREAD

**Issue by Second222None** [spdk/spdk#2501] opened 2022-05-06 08:19 UTC
# Bug report

When copying a large file (~4000MB) into VM disk provided by SPDK with OCF, vhost outputs the following:
```
VHOST_CONFIG: vring call idx:2 file:86
VHOST_CONFIG: read message VHOST_USER_SET_VRING_CALL
VHOST_CONFIG: vring call idx:3 file:87
[2022-04-21 17:19:19.502524] Cache1.Aio1: Failed to write data to cache sector: 1083264, bytes: 65536
[2022-04-21 17:19:19.502680] Cache1.Aio1: Failed to write data to cache sector: 1083392, bytes: 65536
[2022-04-21 17:19:19.502733] Cache1.Aio1: Failed to write data to cache sector: 1083520, bytes: 65536
[2022-04-21 17:19:19.502776] Cache1.Aio1: Failed to write data to cache sector: 1083648, bytes: 65536
[2022-04-21 17:19:19.502842] Cache1.Aio1: Failed to write data to cache sector: 1083776, bytes: 65536
```
The log comes from `src/engine/engine_wb.c:108`.

BTW, there is no error for small files.

## Possible Solution
No idea for the time being.

## Steps to Reproduce

1. /root/spdk/scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t pcie -a 0000:81.00.0
2. /root/spdk/scripts/rpc.py bdev_split_create -s 50000 Nvme0n1 2
3. /root/spdk/scripts/rpc.py bdev_aio_create /dev/sdd Aio1
4. /root/spdk/scripts/rpc.py bdev_ocf_create Cache1 wb Nvme0n1p0 Aio1 --cache-line-size 4
5. /root/spdk/scripts/rpc.py vhost_create_blk_controller --cpumask 0x1 vhostblk0 Cache1
6. Attach `vhostblk0` to VM and start it.
7. scp -r largefile.4G root@$VMIP:/ocfdisk

## Context (Environment including OS version, SPDK version, etc.)

* OCF version (commit hash or tag): commit 865d29d0cb93a71ce37a8410914c35005aa6ed54 (HEAD, tag: v21.6)
* Operating System: openEuler21.09
* Kernel version: 5.10
* SPDK version: d71a91bb74b9e8f62ef52b0c5784325ee76c2ede (HEAD -> master, origin/master, origin/HEAD)
* HugePage Size: 2M
* Cache device type (NAND/Optane/other): NVMe SSD
* Core device type (HDD/SSD/other): HDD
* Configuration:
* * Cache mode: (default: wt) wb
* * Cache line size: (default: 4) 4

**Comment by changpe1** [comment] 2022-05-12 04:02
[Bug Scrub] @rafalste can you take a look?

**Comment by rafalste** [comment] 2022-05-12 10:33
Yes @changpe1, I'll get into that. :) Thanks for the reminder.

**Comment by rafalste** [comment] 2022-05-18 11:49
Due to large amount of other tasks at the moment I need to postpone this a bit more. I'll post an update as soon as I have some time to test this.

**Comment by rafalste** [comment] 2022-06-08 13:07
Hi @Second222None,
I took the vhost/OCF solution for a ride and couldn't reproduce the error you're describing. I believe your problem may be related to your VM configuration. I've used a simple qemu VM by following [this SPDK vhost target documentation](https://spdk.io/doc/vhost.html).

Although, to be honest, I stumble upon some other problems while using your particular setup:
1. the SPDK/OCF version you've used was giving me a hard time managing the exported drive
2. using hugepage size of 2GB (I believe you meant 2G rather than 2M) was too small to even start a VM in my environment

To mitigate those problems, I've upgraded to the SPDK 22.05 release, as there were some vhost enhancements since the commit you were using (and also newer version of OCF was included in this release). I've also increased the hugepage size to 4GB ( `HUGEMEM=4096 ./scripts/setup.sh` ).
With that setup everything runs smoothly even when copying files larger than 4GB.
The only thing left in my mind, that might be a reason for problems with handling 4GB files, is the FAT filesystem that you may use on your core device.

Can you please test it once again following my suggestions?

**Comment by bo2yuan** [comment] 2022-06-08 13:58
Dear,
Thanks for taking the time to focus on this issue :)!
1. Having a taste of a newer version (especially a newer OCF version) is a good idea. 
2. I'm sure the HugePage size in my test is 2MiB, **NOT** 2GiB.  The memory reserved for SPDK is 32768MiB(HUGEMEM=32768 ./scripts/setup.sh). The tested VM configuration is 4 vCPUs, 8GiB DRAM.
3. The filesystem is xfs not FAT and it runs successfully when using **wt** cache mode. The error occurs when using **wb** cache mode. 

Thanks again!

**Comment by gaowayne** [comment] 2022-09-25 08:37
@Second222None may I know if you still need help? have you follow the Rafal suggestions? I have two cents here.
1. can you simplify the reproduce environment, if vhost issue 64K IO to OCF, can you run bdevperf to reproduce?
2. we also have opencas that is kernel version OCF(same OCF code), with this, we can bypass QEMU VM vhost, try copy large files on regular block device, will it work?

**Comment by rafalste** [comment] 2023-02-13 15:43
At the end of the last year Intel announced that they are dropping most of their storage business, which also includes OCF and the whole Open CAS software, so no further improvements will be done in the near future.
I don't know what the future of OCF will be in current circumstances but for now its status in SPDK will be deprecated until further notice.

**Closed by rafalste** 2023-02-13 15:43 UTC
Labels: Sighting
