### ISSUE TITLE
[nvmf-phy-test] fatal: .git/index: index file smaller than expected

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#1500] opened 2020-07-17 07:19 UTC
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/21508/archive/nvme-phy-autotest/build.log

## Execution failed at

 01:09:14	# git clean -dfx
00:03:39.038  fatal: .git/index: index file smaller than expected
00:03:39.038    01:09:14	# trap - ERR
00:03:39.038    01:09:14	# print_backtrace
00:03:39.038    01:09:14	# [[ ehxBET =~ e ]]
00:03:39.039    01:09:14	# args=("${BASH_ARGV[@]}")
00:03:39.039    01:09:14	# local args
00:03:39.039    01:09:14	# xtrace_disable
00:03:39.039    01:09:14	# '[' '' '!=' yes ']'
00:03:39.039    01:09:14	# PREV_BASH_OPTS=ehxBET
00:03:39.039    01:09:14	# [[ ehxBET == *\x* ]]
00:03:39.039    01:09:14	# XTRACE_DISABLED=yes
00:03:39.040    01:09:14	# set +x
00:03:39.040  ========== Backtrace start: ==========
00:03:39.040  
00:03:39.044  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/common/autotest_common.sh:851 -> nvme_cli_build([])
00:03:39.044       ...
00:03:39.044     846 		fi
00:03:39.044     847 	
00:03:39.044     848 		# Build against the version of SPDK under test
00:03:39.044     849 		pushd $spdk_nvme_cli
00:03:39.044     850 	
00:03:39.044  => 851 		git clean -dfx
00:03:39.044     852 	
00:03:39.044     853 		rm -f "$spdk_nvme_cli/spdk"
00:03:39.044     854 		ln -sf "$rootdir" "$spdk_nvme_cli/spdk"
00:03:39.044     855 	
00:03:39.044     856 		make -j$(nproc) LDFLAGS="$(make -s -C $spdk_nvme_cli/spdk ldflags)"
00:03:39.044       ...
00:03:39.045  in test/nvme/spdk_nvme_cli.sh:13 -> main([])
00:03:39.045       ...
00:03:39.045  backtrace unavailable
00:03:39.045       ...
00:03:39.045  
00:03:39.045  ========== Backtrace end ==========
00:03:39.045    01:09:14	# xtrace_enable
00:03:39.046    01:09:14	# return 0
00:03:39.046    01:09:14	# trap - ERR
00:03:39.046    01:09:14	# print_backtrace
00:03:39.046    01:09:14	# [[ ehxBET =~ e ]]
00:03:39.047    01:09:14	# args=("${BASH_ARGV[@]}")
00:03:39.047    01:09:14	# local args
00:03:39.047    01:09:14	# xtrace_disable
00:03:39.047    01:09:14	# '[' no '!=' yes ']'
00:03:39.047    01:09:14	# PREV_BASH_OPTS=ehxBET
00:03:39.048    01:09:14	# [[ ehxBET == *\x* ]]
00:03:39.048    01:09:14	# XTRACE_DISABLED=yes
00:03:39.048    01:09:14	# set +x
00:03:39.048  ========== Backtrace start: ==========
00:03:39.048  
00:03:39.050  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/common/autotest_common.sh:919 -> run_test(["nvme_cli"],["test/nvme/spdk_nvme_cli.sh"])
00:03:39.050       ...
00:03:39.051     914 		timing_enter $test_name
00:03:39.051     915 		echo "************************************"
00:03:39.051     916 		echo "START TEST $test_name"
00:03:39.051     917 		echo "************************************"
00:03:39.051     918 		xtrace_restore
00:03:39.051  => 919 		time "$@"
00:03:39.051     920 		xtrace_disable
00:03:39.051     921 		echo "************************************"
00:03:39.051     922 		echo "END TEST $test_name"
00:03:39.051     923 		echo "************************************"
00:03:39.051     924 		timing_exit $test_name
00:03:39.051       ...
00:03:39.054  in /var/jenkins/workspace/nvme-phy-autotest/spdk/autotest.sh:188 -> main(["/home/sys_sgci/autorun-spdk.conf"])
00:03:39.054       ...
00:03:39.054     183 		if [ $SPDK_TEST_NVME -eq 1 ]; then
00:03:39.054     184 			run_test "blockdev_nvme" test/bdev/blockdev.sh "nvme"
00:03:39.054     185 			run_test "blockdev_nvme_gpt" test/bdev/blockdev.sh "gpt"
00:03:39.054     186 			run_test "nvme" test/nvme/nvme.sh
00:03:39.054     187 			if [[ $SPDK_TEST_NVME_CLI -eq 1 ]]; then
00:03:39.054  => 188 				run_test "nvme_cli" test/nvme/spdk_nvme_cli.sh
00:03:39.054     189 			fi
00:03:39.054     190 			if [[ $SPDK_TEST_NVME_CUSE -eq 1 ]]; then
00:03:39.054     191 				run_test "nvme_cuse" test/nvme/cuse/nvme_cuse.sh
00:03:39.054     192 			fi
00:03:39.054     193 			run_test "nvme_rpc" test/nvme/nvme_rpc.sh
00:03:39.054       ...
00:03:39.054  
00:03:39.054  ========== Backtrace end ==========

**Comment by tomzawadzki** [comment] 2020-07-17 07:35
Duplicate of #1496

**Closed** 2020-07-17 07:37 UTC
Labels: Intermittent Failure
