### ISSUE TITLE
NVMe-OF : INVALID FIELD WRITE FAILED when sending IO size 512 KB

### ISSUE THREAD

**Issue by sudhesam** [spdk/spdk#274] opened 2018-04-01 20:51 UTC
Here is my test case: 

I am sending an IO size of 512 KB from initiator -> target.  When I turn-on tracing, I see the following error: 

rdma.c: 981:spdk_nvmf_rdma_request_process: *INFO*: Request 0x7fe02c00a4b0 entering state 5
**request.c: 105:nvmf_trace_command: *INFO*: I/O cmd: opc 0x81 fuse 0 cid 0 nsid 1 cdw10 0x5f79656b**
request.c: 107:nvmf_trace_command: *INFO*: mptr 0x100000000
request.c: 120:nvmf_trace_command: *INFO*: SGL: Keyed: addr 0x7f64a3145000 key 0x144a85 len 0x80000
**nvme_pcie.c:1623:nvme_pcie_prp_list_append: *INFO*: prp_index:0 virt_addr:0x7fe6f6f79000 len:524288**
nvme_pcie.c:1650:nvme_pcie_prp_list_append: *INFO*: prp1 = 0x2df6379000
nvme_pcie.c:1659:nvme_pcie_prp_list_append: *INFO*: prp[0] = 0x2df637a000
nvme_pcie.c:1659:nvme_pcie_prp_list_append: *INFO*: prp[1] = 0x2df637b000
...
...
...
nvme_pcie.c:1659:nvme_pcie_prp_list_append: *INFO*: prp[126] = 0x2df63f8000
nvme_pcie.c:1678:nvme_pcie_prp_list_append: *INFO*: prp2 = 0x2d34df2030 (PRP list)
rdma.c: 981:spdk_nvmf_rdma_request_process: *INFO*: Request 0x7fe02c00a4b0 entering state 6
**nvme_qpair.c: 136:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:5 cid:191 nsid:1 lba:0 len:1024
nvme_qpair.c: 297:nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:5 cid:191 cdw0:0 sqhd:0001 p:1 m:1 dnr:0**
request.c:  72:spdk_nvmf_request_complete_on_core: *INFO*: cpl: cid=0 cdw0=0x00000000 rsvd1=0 status=0x0400
rdma.c: 981:spdk_nvmf_rdma_request_process: *INFO*: Request 0x7fe02c00a4b0 entering state 7
rdma.c: 981:spdk_nvmf_rdma_request_process: *INFO*: Request 0x7fe02c00a4b0 entering state 9
rdma.c: 538:request_transfer_out: *INFO*: RDMA RECV POSTED. Recv: 0x7fe02c0293b0 Connection: 0x12676d0
rdma.c: 564:request_transfer_out: *INFO*: RDMA SEND POSTED. Request: 0x7fe02c00a4b0 Connection: 0x12676d0
...
...
...
request.c: 105:nvmf_trace_command: *INFO*: I/O cmd: opc 0x90 fuse 0 cid 0 nsid 1 cdw10 0x5f79656b
request.c: 120:nvmf_trace_command: *INFO*: SGL: Keyed: addr 0x7f68a2dff000 key 0x247aa len 0x80000
nvme_pcie.c:1623:nvme_pcie_prp_list_append: *INFO*: prp_index:0 virt_addr:0x7fe6f6f79000 len:524288
nvme_pcie.c:1650:nvme_pcie_prp_list_append: *INFO*: prp1 = 0x2df6379000
nvme_pcie.c:1659:nvme_pcie_prp_list_append: *INFO*: prp[0] = 0x2df637a000
nvme_pcie.c:1659:nvme_pcie_prp_list_append: *INFO*: prp[1] = 0x2df637b000
...
...
...
nvme_pcie.c:1659:nvme_pcie_prp_list_append: *INFO*: prp[126] = 0x2df63f8000
nvme_pcie.c:1678:nvme_pcie_prp_list_append: *INFO*: prp2 = 0x2d34df2030 (PRP list)
rdma.c: 981:spdk_nvmf_rdma_request_process: *INFO*: Request 0x7fe02c00a630 entering state 6
**nvme_qpair.c: 136:nvme_io_qpair_print_command: *NOTICE*: READ sqid:5 cid:191 nsid:1 lba:0 len:1024
nvme_qpair.c: 297:nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:5 cid:191 cdw0:0 sqhd:0002 p:1 m:1 dnr:0**
request.c:  72:spdk_nvmf_request_complete_on_core: *INFO*: cpl: cid=0 cdw0=0x00000000 rsvd1=0 status=0x0400

However, when I send IO size of just 512 bytes, I don't see 'INVALID FIELD' issue.  I am of the opinion that if the command field is INVALID, it should be INVALID for all IO sizes.

Here is the same tracing output for 512 bytes IO size:

rdma.c: 981:spdk_nvmf_rdma_request_process: *INFO*: Request 0x7fe02400a4b0 entering state 5
**request.c: 105:nvmf_trace_command: *INFO*: I/O cmd: opc 0x81 fuse 0 cid 0 nsid 1 cdw10 0x5f79656b**
request.c: 107:nvmf_trace_command: *INFO*: mptr 0x100000000
request.c: 120:nvmf_trace_command: *INFO*: SGL: Keyed: addr 0x7f42f5fc5000 key 0x14ac47 len 0x200
**nvme_pcie.c:1623:nvme_pcie_prp_list_append: *INFO*: prp_index:0 virt_addr:0x7fe737583000 len:512**
nvme_pcie.c:1650:nvme_pcie_prp_list_append: *INFO*: prp1 = 0x2e36983000
rdma.c: 981:spdk_nvmf_rdma_request_process: *INFO*: Request 0x7fe02400a4b0 entering state 6
request.c:  72:spdk_nvmf_request_complete_on_core: *INFO*: cpl: cid=0 cdw0=0x00000000 rsvd1=0 status=0x0000
rdma.c: 981:spdk_nvmf_rdma_request_process: *INFO*: Request 0x7fe02400a4b0 entering state 7
rdma.c: 981:spdk_nvmf_rdma_request_process: *INFO*: Request 0x7fe02400a4b0 entering state 9
rdma.c: 538:request_transfer_out: *INFO*: RDMA RECV POSTED. Recv: 0x7fe0240293b0 Connection: 0x12676c0
rdma.c: 564:request_transfer_out: *INFO*: RDMA SEND POSTED. Request: 0x7fe02400a4b0 Connection: 0x12676c0
...
...
...
**request.c: 105:nvmf_trace_command: *INFO*: I/O cmd: opc 0x90 fuse 0 cid 0 nsid 1 cdw10 0x5f79656b**
request.c: 120:nvmf_trace_command: *INFO*: SGL: Keyed: addr 0x7f46f5bff000 key 0x10ecfb len 0x200
**nvme_pcie.c:1623:nvme_pcie_prp_list_append: *INFO*: prp_index:0 virt_addr:0x7fe737583000 len:512**
nvme_pcie.c:1650:nvme_pcie_prp_list_append: *INFO*: prp1 = 0x2e36983000
rdma.c: 981:spdk_nvmf_rdma_request_process: *INFO*: Request 0x7fe02400a630 entering state 6
request.c:  72:spdk_nvmf_request_complete_on_core: *INFO*: cpl: cid=0 cdw0=0x00000000 rsvd1=0 status=0x0000
rdma.c: 981:spdk_nvmf_rdma_request_process: *INFO*: Request 0x7fe02400a630 entering state 7

**Comment by sudhesam** [comment] 2018-04-01 20:52
Thanks.

Any help appreciated.

**Comment by sudhesam** [comment] 2018-04-01 20:59
Both initiator and target has Mellanox ConnectX-5 and I have compiled DPDK with CONFIG_RTE_LIBRTE_MLX5_PMD=y

# lspci | grep -i mell
d8:00.0 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5]
d8:00.1 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5]
#

**Comment by sudhesam** [comment] 2018-04-01 21:21
nvmf_rdma_connect trace messages:

rdma.c:1458:spdk_nvmf_rdma_accept: *INFO*: Acceptor Event: RDMA_CM_EVENT_CONNECT_REQUEST
rdma.c: 654:nvmf_rdma_connect: *INFO*: Connect Recv on fabric intf name mlx5_0, dev_name uverbs0
rdma.c: 658:nvmf_rdma_connect: *INFO*: Listen Id was 0x1d98ce0 with verbs 0x1de7d10. ListenAddr: 0x1d98aa0
rdma.c: 664:nvmf_rdma_connect: *INFO*: Calculating Queue Depth
rdma.c: 669:nvmf_rdma_connect: *INFO*: Target Max Queue Depth: 1024
rdma.c: 674:nvmf_rdma_connect: *INFO*: Local NIC Max Send/Recv Queue Depth: 32768 Max Read/Write Queue Depth: 16
rdma.c: 681:nvmf_rdma_connect: *INFO*: Host (Initiator) NIC Max Incoming RDMA R/W operations: 16 Max Outgoing RDMA R/W operations: 0
rdma.c: 690:nvmf_rdma_connect: *INFO*: Host Receive Queue Size: 32
rdma.c: 691:nvmf_rdma_connect: *INFO*: Host Send Queue Size: 31
rdma.c: 697:nvmf_rdma_connect: *INFO*: Final Negotiated Queue Depth: 32 R/W Depth: 16

**Comment by jimharris** [comment] 2018-04-02 16:46
Is all of this from the target or the initiator or a mix of the two?

If you could provide the following, it would be helpful to narrow down the issue:


1)       Exact details on where these log messages are from.  For example, the nvme_ctrlr.c debug prints could be from the initiator (for the NVMe-oF controller) or the target (for the local NVMe SSD).

2)       Hardware configuration – specifically what is the storage attached on the target side.

3)       Base SPDK git commit you are using.

4)       A full, complete diff of the changes you have made locally.  This needs to be a full diff of the entire SPDK tree.

Thanks,

-Jim

**Comment by sudhesam** [comment] 2018-04-02 17:50
This is all on the 'target' side. 

1.  I have recompiled SPDK code with DEBUG turned-on and running nvmf_tgt with '-t all' option to show 
     the trace messages.

2.  Hardware configuration:
**From nvmf.conf (Full nvmf.conf that I am using is at the end of this message):**

**_[Nvme]_**

 TransportId "trtype:PCIe traddr:0000:b7:00.0" Nvme0
 TransportId "trtype:PCIe traddr:0000:b8:00.0" Nvme1

**From 'lspci -v' output for the devices used above:**

b7:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM961/PM961 (prog-if 02 [NVM Express])
        Subsystem: Samsung Electronics Co Ltd Device a801
        Physical Slot: 202-1
        Flags: bus master, fast devsel, latency 0, IRQ 55, NUMA node 1
        Memory at edf20000 (64-bit, non-prefetchable) [size=16K]
        Expansion ROM at edf00000 [disabled] [size=128K]
        Capabilities: [40] Power Management version 3
        Capabilities: [50] MSI: Enable- Count=1/32 Maskable- 64bit+
        Capabilities: [70] Express Endpoint, MSI 00
        Capabilities: [b0] MSI-X: Enable- Count=33 Masked-
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [148] Device Serial Number 00-00-00-00-00-00-00-00
        Capabilities: [158] Power Budgeting <?>
        Capabilities: [168] #19
        Capabilities: [188] Latency Tolerance Reporting
        Capabilities: [190] L1 PM Substates
        Kernel driver in use: uio_pci_generic
        Kernel modules: nvme

b8:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM961/PM961 (prog-if 02 [NVM Express])
        Subsystem: Samsung Electronics Co Ltd Device a801
        Physical Slot: 235-1
        Flags: bus master, fast devsel, latency 0, IRQ 57, NUMA node 1
        Memory at ede20000 (64-bit, non-prefetchable) [size=16K]
        Expansion ROM at ede00000 [disabled] [size=128K]
        Capabilities: [40] Power Management version 3
        Capabilities: [50] MSI: Enable- Count=1/32 Maskable- 64bit+
        Capabilities: [70] Express Endpoint, MSI 00
        Capabilities: [b0] MSI-X: Enable- Count=33 Masked-
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [148] Device Serial Number 00-00-00-00-00-00-00-00
        Capabilities: [158] Power Budgeting <?>
        Capabilities: [168] #19
        Capabilities: [188] Latency Tolerance Reporting
        Capabilities: [190] L1 PM Substates
        Kernel driver in use: uio_pci_generic
        Kernel modules: nvme

**lspci output for the Mellanox card on the 'target':**

d8:00.0 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5]
        Subsystem: Mellanox Technologies Device 0001
        Flags: bus master, fast devsel, latency 0, IRQ 70, NUMA node 1
        Memory at 39fffe000000 (64-bit, prefetchable) [size=32M]
        Expansion ROM at fbe00000 [disabled] [size=1M]
        Capabilities: [60] Express Endpoint, MSI 00
        Capabilities: [48] Vital Product Data
        Capabilities: [9c] MSI-X: Enable+ Count=64 Masked-
        Capabilities: [c0] Vendor Specific Information: Len=18 <?>
        Capabilities: [40] Power Management version 3
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [150] Alternative Routing-ID Interpretation (ARI)
        Capabilities: [1c0] #19
        Capabilities: [230] Access Control Services
        Kernel driver in use: mlx5_core
        Kernel modules: mlx5_core

d8:00.1 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5]
        Subsystem: Mellanox Technologies Device 0001
        Flags: bus master, fast devsel, latency 0, IRQ 133, NUMA node 1
        Memory at 39fffc000000 (64-bit, prefetchable) [size=32M]
        Expansion ROM at fbd00000 [disabled] [size=1M]
        Capabilities: [60] Express Endpoint, MSI 00
        Capabilities: [48] Vital Product Data
        Capabilities: [9c] MSI-X: Enable+ Count=64 Masked-
        Capabilities: [c0] Vendor Specific Information: Len=18 <?>
        Capabilities: [40] Power Management version 3
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [150] Alternative Routing-ID Interpretation (ARI)
        Capabilities: [230] Access Control Services
        Kernel driver in use: mlx5_core
        Kernel modules: mlx5_core

**Full nvmf.conf:**

**_[Global]_**

  ReactorMask 0x00FF
  TpointGroupMask 0xFFFF

**_# Define NVMf protocol global options_**
**_[Nvmf]_**

MaxQueuesPerSession 4
MaxQueueDepth 1024
InCapsuleDataSize 4096
AcceptorPollRate 10000

**_[Nvme]_**
 TransportId "trtype:PCIe traddr:0000:b7:00.0" Nvme0
 TransportId "trtype:PCIe traddr:0000:b8:00.0" Nvme1

  RetryCount 4
  Timeout 0
  ActionOnTimeout None
  AdminPollRate 100000

  HotplugEnable No

**# Namespaces backed by physical NVMe devices**
[Subsystem1]
  NQN nqn.2016-06.io.spdk:cnode1
  #Core 0
  Listen RDMA x.x.x.x:1023
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000001
  Namespace Nvme0n1 1

[Subsystem2]
  NQN nqn.2016-06.io.spdk:cnode2
  #Core 1
  Listen RDMA x.x.x.x:1023
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000002
  Namespace Nvme1n1 1

**3.  SPDK and DPDK version**

- SPDK (v18.01)
- DPDK (17.02.0)

4.  Local changes to SPDK:

I have made changes to only 3 files (Diff of changes mentioned below) :

1.  dpdk/config/common_base (To set CONFIG_RTE_LIBRTE_MLX5_PMD=y)
2.  spdk/lib/nvme/nvme_ctrlr.c (To print MDTS max_xfer_size, CTRLR min_page_size, CTRLR MDTS trace 
     messages)
3.  spdk/lib/nvmf/nvmf.c (To increase SPDK_NVMF_DEFAULT_MAX_IO_SIZE from 128k to 2 MB)

_**dpdk/config/common_base**_

$ git diff oss/dpdk/config/common_base
diff --git a/oss/dpdk/config/common_base b/oss/dpdk/config/common_base
index 39d5e3a..613cce6 100644
--- a/oss/dpdk/config/common_base
+++ b/oss/dpdk/config/common_base
@@ -215,8 +215,8 @@ CONFIG_RTE_LIBRTE_MLX4_SOFT_COUNTERS=1
 #
 # Compile burst-oriented Mellanox ConnectX-4 & ConnectX-5 (MLX5) PMD
 #
-CONFIG_RTE_LIBRTE_MLX5_PMD=n
-CONFIG_RTE_LIBRTE_MLX5_DEBUG=n
+CONFIG_RTE_LIBRTE_MLX5_PMD=y
+CONFIG_RTE_LIBRTE_MLX5_DEBUG=y
 CONFIG_RTE_LIBRTE_MLX5_TX_MP_CACHE=8

**_spdk/lib/nvme/nvme_ctrlr.c_**

diff --git a/oss/spdk/lib/nvme/nvme_ctrlr.c b/oss/spdk/lib/nvme/nvme_ctrlr.c
index 60271c0..e341bdb 100644
--- a/oss/spdk/lib/nvme/nvme_ctrlr.c
+++ b/oss/spdk/lib/nvme/nvme_ctrlr.c
@@ -797,6 +797,8 @@ nvme_ctrlr_identify(struct spdk_nvme_ctrlr *ctrlr)
                ctrlr->max_xfer_size = spdk_min(ctrlr->max_xfer_size,
                                                ctrlr->min_page_size * (1 << (ctrlr->cdata.mdts)));
                SPDK_DEBUGLOG(SPDK_LOG_NVME, "MDTS max_xfer_size %u\n", ctrlr->max_xfer_size);
+               SPDK_DEBUGLOG(SPDK_LOG_NVME, "CTRLR min_page_size %u\n", ctrlr->min_page_size);
+               SPDK_DEBUGLOG(SPDK_LOG_NVME, "CTRLR MDTS %u\n", ctrlr->cdata.mdts);
        }

        return 0;

**_spdk/lib/nvmf/nvmf.c_**

$ git diff oss/spdk/lib/nvmf/nvmf.c
diff --git a/oss/spdk/lib/nvmf/nvmf.c b/oss/spdk/lib/nvmf/nvmf.c
index d6b482e..476da24 100644
--- a/oss/spdk/lib/nvmf/nvmf.c
+++ b/oss/spdk/lib/nvmf/nvmf.c
@@ -55,7 +55,7 @@ SPDK_LOG_REGISTER_COMPONENT("nvmf", SPDK_LOG_NVMF)
 #define SPDK_NVMF_DEFAULT_MAX_QUEUE_DEPTH 128
 #define SPDK_NVMF_DEFAULT_MAX_QPAIRS_PER_CTRLR 64
 #define SPDK_NVMF_DEFAULT_IN_CAPSULE_DATA_SIZE 4096
-#define SPDK_NVMF_DEFAULT_MAX_IO_SIZE 131072
+#define SPDK_NVMF_DEFAULT_MAX_IO_SIZE 2097152

 void
 spdk_nvmf_tgt_opts_init(struct spdk_nvmf_tgt_opts *opts)

**Comment by WenqianZong** [comment] 2018-04-03 06:02
Hi sudhesam;
I can't reproduce this issue, please provide detail reproduce step.

BRS
Zongwenqian

**Comment by dverkamp-intel** [comment] 2018-04-06 17:46
I would like to echo Jim's request - it would be very helpful to see which messages are coming from the host (presumably this is the SPDK NVMe-oF host code in lib/nvme) and which are coming from the target (lib/nvme interacting with the PCIe-attached SSDs that are backing the namespaces).

Additionally, I'm quite confused by the log messages from your first post; for example, "I/O cmd: opc 0x81" doesn't look right - there is no defined NVMe I/O opcode 0x81.  There's another message later on that mentions I/O opcode 0x90, which is also not currently defined.  What code are you running on the host side? Can you test with a known-good host side, e.g. examples/nvme/perf?

**Comment by sudhesam** [comment] 2018-04-06 17:57
Thanks all for your help and support.

Regarding opcode, unfortunately I cannot discuss more in this forum.  I will have to check internally and get back to you as to what more information I can provide.

With respect to messages from the host, I will see if I can get some information through wireshark and update this thread.

**Comment by peluse** [comment] 2018-04-06 18:03
Daniel’s other suggestion about testing with a known good host is probably a really good data point also if you can do that….

Thx
Paul

**Comment by sudhesam** [comment] 2018-04-06 19:09
Sure.  Will do.  

Also, on some of the blogs I am seeing some tune able parameters like max_hw_sectors_kb and max_sectors_kb.  On couple of my setup (physical box) that I am testing with, both these are either set to 128 or  256.

I am asking this because if I test the same code in a virtual machine setup, I am able to send IO size of 1MB.  Here, max_hw_sectors_kb and max_sectors_kb is set to 1024.

My assumption is that this is affecting the IO size.  

Any inputs welcome.

**Comment by sudhesam** [comment] 2018-04-09 20:28
Wanted to know your thoughts on QD calculation in rdma.c.  In my physical environment (with Mellanox card), I see the following:

rdma.c:1458:spdk_nvmf_rdma_accept: *INFO*: Acceptor Event: RDMA_CM_EVENT_CONNECT_REQUEST
rdma.c: 654:nvmf_rdma_connect: *INFO*: Connect Recv on fabric intf name mlx5_0, dev_name uverbs0
rdma.c: 658:nvmf_rdma_connect: *INFO*: Listen Id was 0x1418d30 with verbs 0x1467c40. ListenAddr: 0x1418af0
rdma.c: 664:nvmf_rdma_connect: *INFO*: Calculating Queue Depth
rdma.c: 669:nvmf_rdma_connect: *INFO*: Target Max Queue Depth: 128
rdma.c: 674:nvmf_rdma_connect: *INFO*: Local NIC Max Send/Recv Queue Depth: 32768 Max Read/Write Queue Depth: 16
rdma.c: 681:nvmf_rdma_connect: *INFO*: Host (Initiator) NIC Max Incoming RDMA R/W operations: 16 Max Outgoing RDMA R/W operations: 0
rdma.c: 690:nvmf_rdma_connect: *INFO*: Host Receive Queue Size: 32
rdma.c: 691:nvmf_rdma_connect: *INFO*: Host Send Queue Size: 31
rdma.c: 697:nvmf_rdma_connect: *INFO*: Final Negotiated Queue Depth: 32 R/W Depth: 16

However, in my 'virtual' (or VMware) environment running soft-roce, I see the following:

rdma.c: 654:nvmf_rdma_connect: *INFO*: Connect Recv on fabric intf name rxe0, dev_name uverbs0
rdma.c: 658:nvmf_rdma_connect: *INFO*: Listen Id was 0x1f63520 with verbs 0x1f620b0. ListenAddr: 0x1f632e0
rdma.c: 664:nvmf_rdma_connect: *INFO*: Calculating Queue Depth
rdma.c: 669:nvmf_rdma_connect: *INFO*: Target Max Queue Depth: 128
rdma.c: 674:nvmf_rdma_connect: *INFO*: Local NIC Max Send/Recv Queue Depth: 16384 Max Read/Write Queue Depth: 128
rdma.c: 681:nvmf_rdma_connect: *INFO*: Host (Initiator) NIC Max Incoming RDMA R/W operations: 128 Max Outgoing RDMA R/W operations: 0
rdma.c: 690:nvmf_rdma_connect: *INFO*: Host Receive Queue Size: 128
rdma.c: 691:nvmf_rdma_connect: *INFO*: Host Send Queue Size: 127
rdma.c: 697:nvmf_rdma_connect: *INFO*: Final Negotiated Queue Depth: 128 R/W Depth: 128

Does 'Final Negotiated Queue Depth' have any impact on the IO size ?

Thanks once again and appreciate any help.

**Comment by sudhesam** [comment] 2018-04-11 01:43
Hello,

Appreciate any help on this issue.

**Comment by benlwalker** [comment] 2018-04-11 14:18
The "Final Negotiated Queue Depth" is the queue depth - the number of I/O that can be submitted simultaneously. That does not impact the maximum I/O size, which is set separately.

**Comment by sudhesam** [comment] 2018-04-20 06:56
I put some 'printf()' statements in the code to track who sets response->status.sc flag to '2' and here is what I found:

rpc.c:  83:spdk_rpc_initialize: *ERROR*: Unable to start RPC service at /var/tmp/spdk.sock
nvmf_tgt.c: 110:nvmf_tgt_create_subsystem: *NOTICE*: allocated subsystem nqn.2014-08.org.nvmexpress.discovery
nvmf_tgt.c: 110:nvmf_tgt_create_subsystem: *NOTICE*: allocated subsystem nqn.2016-06.io.spdk:cnode1
rdma.c:1156:spdk_nvmf_rdma_create: *NOTICE*: *** RDMA Transport Init ***
rdma.c:1396:spdk_nvmf_rdma_listen: *NOTICE*: *** NVMf Target Listening on 12.12.12.39 port 1023 ***
conf.c: 425:spdk_nvmf_construct_subsystem: *NOTICE*: Attaching block device Nvme0n1 to subsystem nqn.2016-06.io.spdk:cnode1
====> status_SC: 0, status_SCT: 0
====> status_SC: 0, status_SCT: 0
rdma.c:1537:spdk_nvmf_rdma_poll_group_create: *NOTICE*: Skipping unused RDMA device when creating poll group.
====> status_SC: 0, status_SCT: 0
====> status_SC: 0, status_SCT: 0
rdma.c:1537:spdk_nvmf_rdma_poll_group_create: *NOTICE*: Skipping unused RDMA device when creating poll group.
====> status_SC: 0, status_SCT: 0
====> status_SC: 0, status_SCT: 0
rdma.c:1537:spdk_nvmf_rdma_poll_group_create: *NOTICE*: Skipping unused RDMA device when creating poll group.
====> status_SC: 0, status_SCT: 0
====> status_SC: 0, status_SCT: 0
rdma.c:1537:spdk_nvmf_rdma_poll_group_create: *NOTICE*: Skipping unused RDMA device when creating poll group.
====> status_SC: 0, status_SCT: 0
====> status_SC: 0, status_SCT: 0
rdma.c:1537:spdk_nvmf_rdma_poll_group_create: *NOTICE*: Skipping unused RDMA device when creating poll group.
====> status_SC: 0, status_SCT: 0
====> status_SC: 0, status_SCT: 0
rdma.c:1537:spdk_nvmf_rdma_poll_group_create: *NOTICE*: Skipping unused RDMA device when creating poll group.
====> status_SC: 0, status_SCT: 0
====> status_SC: 0, status_SCT: 0
rdma.c:1537:spdk_nvmf_rdma_poll_group_create: *NOTICE*: Skipping unused RDMA device when creating poll group.
====> status_SC: 0, status_SCT: 0
====> status_SC: 0, status_SCT: 0
rdma.c:1537:spdk_nvmf_rdma_poll_group_create: *NOTICE*: Skipping unused RDMA device when creating poll group.
====> status_SC: 0, status_SCT: 0
====> status_SC: 0, status_SCT: 0
nvmf_tgt.c: 311:nvmf_tgt_advance_state: *NOTICE*: Acceptor running

spdk_nvmf_ctrlr_identify >> 1: sc = 0
**====> status_SC: 0, status_SCT: 0**
spdk_nvmf_ctrlr_identify >> 1: sc = 0
**====> status_SC: 2, status_SCT: 0**
nvme_qpair.c: 136:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:191 nsid:1 lba:0 len:514
GENERIC ERROR status
nvme_qpair.c: 301:nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:1 cid:191 cdw0:0 sqhd:0001 p:1 m:0 dnr:0
nvmf_bdev_ctrlr_complete_cmd >> 1: sc = 0
====> status_SC: 2, status_SCT: 0
nvme_qpair.c: 136:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:191 nsid:1 lba:0 len:514
GENERIC ERROR status
nvme_qpair.c: 301:nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:1 cid:191 cdw0:0 sqhd:0002 p:1 m:0 dnr:0
nvmf_bdev_ctrlr_complete_cmd >> 1: sc = 0
====> status_SC: 2, status_SCT: 0
nvme_qpair.c: 136:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:191 nsid:1 lba:0 len:514
GENERIC ERROR status
nvme_qpair.c: 301:nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:1 cid:191 cdw0:0 sqhd:0002 p:1 m:0 dnr:0
nvmf_bdev_ctrlr_complete_cmd >> 1: sc = 0

**Comment by wanqunintel** [comment] 2018-05-03 04:53
wenqian, would you reproduce it here

**Comment by sudhesam** [comment] 2018-05-03 17:02
root@testxx testxx]# nvme io-passthru /dev/nvme0 -o 1 -n 1 -4 0 **_-6 1023_** -i ./fio.out -w
NVMe Status:INVALID_FIELD(2) Command Result:00000000

[root@testxx testxx]# nvme io-passthru /dev/nvme0 -o 1 -n 1 -4 0 **_-6 524288_** -i ./fio.out -w
NVMe command result:00000000

As per NVMe spec, cdw12 is supposed to be in blocks.

If you see 1st command above, I am setting cdw12 = 1023 (i.e. 1024 blocks of 512 bytes each) and it gives INVALID_FIELD.
However, when I set cdw12 = 524288 (i.e. 512 * 1024) then the command completes successfully.

Can you please try the above (note: This is using 'nvme-cli' and kernel driver) in your setup ? If it works in your setup, then I think the problem is with the firmware on my NVMe drive.

Thanks for the help and support.

**Comment by WenqianZong** [comment] 2018-05-07 02:48
hi sudhesam:

What file is fio.out and where is it? Is fio.out means the application fio?

BRS
Zongwenqian

**Comment by sudhesam** [comment] 2018-05-07 17:19
Sorry, should have been clear about it.  It is just a "dummy" text file that is 512 K bytes large or higher.

**Comment by WenqianZong** [comment] 2018-05-08 01:27
After try following command ,the result is :

[root@waikikibeach43 zong]# nvme io-passthru /dev/nvme0n1 -o 1 -n 1 -4 0 -6 1023 -i ./fio.out -w
NVMe Status:INVALID_FIELD(2) Command Result:00000000
[root@waikikibeach43 zong]# nvme io-passthru /dev/nvme0n1 -o 1 -n 1 -4 0 -6 524288 -i ./fio.out -w
NVMe command result:00000000

BRS
Zongwenqian

**Comment by jimharris** [comment] 2018-05-08 19:32
cdw12 = 524288 = 0x80000.  Only the lower 16 bits are used for number of blocks - it's 0's based, so you then add 1.  So cdw12 = 0x80000 means transfer 1 block (0x0000 + 1).

Bit 19 is actually reserved and the target should be failing the command since it's not set to zero.  But that's a separate problem that should be tracked separately.

If you do an identify on /dev/nvme0n1, what does it report as MDTS?

**Comment by jimharris** [comment] 2018-05-08 20:54
It also appears from earlier in the log that the NVMe SSD you are using has a 256K MDTS.  So you cannot do a 512K I/O to that device using NVMe passthrough.  The SPDK NVMe driver will split the I/O based on MDTS if you use the read/write interface but won't try to interpret any passthrough commands.

**Comment by jimharris** [comment] 2018-05-08 21:35
My last response is not quite accurate.  If you specify -o 1 (WRITE), the command should go down the normal bdev write path and then the normal nvme driver write path.  The nvme driver should split it in this case.

But if you specify a vendor-specific opcode (as in your earlier post), it will not go through the normal nvme driver write path, and it will not get split.  In that case the 512KB command would go to an SSD that has specified 256KB MDTS and will fail.

Does -6 511 work?

**Comment by wanqunintel** [comment] 2018-05-10 04:36
@sudhesam would you reply for any feedback? thanks.

**Comment by sudhesam** [comment] 2018-05-14 18:58
Apologies for the delay in updating this thread.

Still getting INVALID_FIELD error with '-6 511'.

[root@testxx testxx]# dd if=/dev/random of=/tmp/foo.out bs=512 count=10 iflag=fullblock
10+0 records in
10+0 records out
5120 bytes (5.1 kB) copied, 3118.4 s, 0.0 kB/s

[root@testxx testxx]# ls -l /tmp/foo.out
-rw-r--r-- 1 root root 5120 May 14 11:17 /tmp/foo.out


[root@testxx testxx]# nvme io-passthru /dev/nvme0 -o 1 -n 1 -4 0 -6 511 -i /tmp/foo.out -w
NVMe Status:INVALID_FIELD(2) Command Result:00000000

**Comment by jimharris** [comment] 2018-05-14 22:14
A couple of questions:


1)       Can you attach the exact SPDK git commit ID you are using, plus the contents of “git diff” from your local clone?  I know previously you had some local mods to the repository – we need to know those exact mods to understand the issue.

2)       -6 511 indicates 512 blocks.  But the file is only 5120 bytes.  Was this the intention?  It seems the size of the file should match the number of bytes written via nvme-io-passthru.


Thanks,

-Jim

**Comment by jimharris** [comment] 2018-05-17 15:38
Hi Sudhe,

It was great to meet you at the SPDK summit!  And that we could bottom out on this issue.  Summarizing that discussion here so we can close this issue...

Your latest test here is not using SPDK at all - it's just using the kernel NVMe driver with a locally attached SSD.  This SSD has a 4KB formatted namespace.  MDTS is 256KB.  This means the max number of blocks for one command is 64.

I am fairly certain that nvme-write will work with the kernel driver.  This code path uses the NVME_IOCTL_SUBMIT_IO ioctl which routes the I/O through the block layer which understands the MDTS limits.  But you'll need to confirm that.

When using nvme io-passthru though, the drive is correctly returning INVALID_FIELD, since -6 511 indicates 512 blocks of 4KB each which is bigger than the 256KB MDTS.

Thanks,

-Jim

**Closed by jimharris** 2018-05-17 15:38 UTC
