### ISSUE TITLE
cmb_copy failure in QEMU

### ISSUE THREAD

**Issue by archiemorningstar** [spdk/spdk#1359] opened 2020-04-20 18:06 UTC
Trying to run cmb_copy (examples/nvme/cmb_copy) using an emulated CMB SSD in QEMU, but cmb_copy reports it cannot allocate a CMB buffer. The identify (examples/nvme/identify) reports the two emulated SSD's I created have 128MB of CMB. Enabling --enable-debug shows print outs:
```
call to spdk_nvme_ctrlr_alloc_cmb_io_buffer() fails (pctrlr->cmb_bar_virt_addr is
NULL):
could not get phys addr for 0x1088200000
nvme_pcie.c: 554:nvme_pcie_ctrlr_map_cmb: *ERROR*: spdk_mem_register() failed
```

## Expected Behavior
cmb_copy should be able to allocate the CMB buffer and run the example application successfully to perform a P2P copy from one emulated SSD to another emulated SSD.

## Current Behavior
Fails to allocate CMB buffer from the device selected to use causing the error
```
ERROR: buffer allocation failed
Are you sure 0000:00:04.0 has a valid CMB?
Error in spdk_cmb_copy(): -12
```

## Possible Solution
I tried to trace the code and see that when it searches for the physical address g_vtophys_pci_devices list is empty when trying to register the CMB memory space. It only gets later populated with the two SSDs when cleanup_pci_devices() is called at the end of spdk_pci_device_attach().

Tried to do a quick hack to disable the call to nvme_pcie_ctrlr_map_cmb() inside nvme_pcie_ctrlr_allocate_bars() and place the call after after the devices have been enumerated and attached (outside of spdk_pci_device_attach() and thus after cleanup_pci_devices())  and it *seemed* to work.

## Steps to Reproduce
1. Setup qemu environment with two CMB SSD emulated devices. My qemu startup:
```
x86_64-softmmu/qemu-system-x86_64 \
-cpu host \
-machine q35,accel=kvm,kernel-irqchip=split \
-smp 8 \
-m 32768 \
-enable-kvm \
-drive if=virtio,file=test1.qcow2,cache=none \
-vnc :1 \
-device e1000,netdev=net0 \
-netdev user,id=net0,hostfwd=tcp::5555-:22 \
-drive file=nvme0.img,if=none,id=D22,format=raw \
-device nvme,drive=D22,serial=1234,cmb_size_mb=128 \
-drive file=nvme1.img,if=none,id=D23,format=raw \
-device nvme,drive=D23,serial=5678,cmb_size_mb=128 \
-device intel-iommu,intremap=on
```
2. Use the two emulated SSDs with cmb_copy example application. My example cmb_copy:
```
cmb_copy -r 0000:00:04.0-1-0-1 -w 0000:00:03.0-1-0-1 -c 0000:00:04.0 
```

## Context (Environment including OS version, SPDK version, etc.)
QEMU v4.2.0
Guest OS Ubuntu 18.04
SPDK versions 20.01.1, 19.10.1, 19.04.1, 18.04.1 all with similar results

**Comment by sbates130272** [comment] 2020-04-20 18:15
Thanks @archiemorningstar. As noted in the email chain this was working in the past. Also the similar framework in-kernel (p2pdma) continues to work fine with QEMU so I do suspect this is an SPDK memory allocation issue.

**Comment by changpe1** [comment] 2020-04-21 08:08
Here is the fix with mater SPDK branch, I tested with provided command line, it passed https://review.spdk.io/gerrit/c/spdk/spdk/+/1955/1.

**Comment by changpe1** [comment] 2020-04-21 08:12
For the issue with SPDK v20.01.1 and earlier version, because in function spdk_pci_device_init() the callback to call spdk_mem_register() was earlier than TAILQ_INSERT_TAIL(&g_pci_hotplugged_devices, dev, internal.tailq);  Ben already refactor this part of code, so the issue isn't exist with master version.

**Comment by sbates130272** [comment] 2020-04-22 21:13
@changpe1 thanks for root causing this. So which release(s) of SPDK did this impact? Can we add some form of regression test based on this QEMU example from @archiemorningstar to ensure it does not regress in the future?

**Comment by sbates130272** [comment] 2020-04-22 21:19
Also @changpe1 it is not clear to me why we have to disable the CMB for SQEs in order to get cmb_copy to work. There should be plenty of room in the CMB for both the SQEs and the DMA data used for the copy. I just wonder if your fix (disabling SQEs in the CMB) is simply hiding the real root cause?

**Comment by archiemorningstar** [comment] 2020-04-23 00:13
@changpe1 @sbates130272 
The change works fine for cmb_copy but if you try to create a bdev with with a cmb ssd it crashes with an illegal instruction.
At least in my environment, I've traced it to a memset call in nvme_pcie_qpair_reset() which is trying to zero out the sqs. I'm not familiar with vector instructions, but it looks like an AVX2 instruction is being invoked and I guess trying to use these instructions with that address space doesn't work. Not sure how many other instances in the code try to manipulate memory in the same manner.

**Comment by changpe1** [comment] 2020-04-23 00:41
> Also @changpe1 it is not clear to me why we have to disable the CMB for SQEs in order to get cmb_copy to work. There should be plenty of room in the CMB for both the SQEs and the DMA data used for the copy. I just wonder if your fix (disabling SQEs in the CMB) is simply hiding the real root cause?

Actually I removed the limitation in the driver layer, and tested SQE in CMB with CMB copy, Ben added the limitation, I will ask him is there any special reason for it, if no I can add it back.

**Comment by changpe1** [comment] 2020-04-23 00:51
> @changpe1 @sbates130272
> The change works fine for cmb_copy but if you try to create a bdev with with a cmb ssd it crashes with an illegal instruction.
> At least in my environment, I've traced it to a memset call in nvme_pcie_qpair_reset() which is trying to zero out the sqs. I'm not familiar with vector instructions, but it looks like an AVX2 instruction is being invoked and I guess trying to use these instructions with that address space doesn't work. Not sure how many other instances in the code try to manipulate memory in the same manner.

I met the same issue too, and I removed that line in nvme_pcie_qpair_reset() to pass the test.  This maybe related with the configuration, it's should be another issue not related with this one.

**Comment by changpe1** [comment] 2020-04-30 04:14
The CMB issue is already fixed, for the memset issue with CMB, it's same with #1362, so I'm going to close this issue now.

**Closed by changpe1** 2020-04-30 04:14 UTC
Labels: Medium, bug
