### ISSUE TITLE
Why does spdk_rpc_construct_xxx_bdev always return "Invalid parameters" when it occur error.

### ISSUE THREAD

**Issue by yangtianyu0706** [spdk/spdk#767] opened 2019-04-24 02:24 UTC
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

[Question]
Why does spdk_rpc_construct_xxx_bdev always return "Invalid parameters" when it occur error.

## Expected Behavior

When we use rpc methods to create some bdev, all of functions that create bdev is always return "Invalid parameters" when it occur error. I have two more questions about this issue.
1.  Why should we design this way?
2.  Is it possible to increase the error code return?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by yangtianyu0706** [comment] 2019-04-24 02:25
@benlwalker @darsto

**Comment by peluse** [comment] 2019-04-24 18:08
It occurs because, I hate to say it, invalid parms were provided. Maybe share one example and we can help determine exactly what is wrong?

**Comment by jimharris** [comment] 2019-04-24 18:17
I think the problem is more that the error codes are too generic.  For example, we could provide more details on whether an RPC failed because their truly was an invalid parameter, or whether the specified bdev doesn't exist, or whether an operation can't be performed because the target object is busy for some reason.

Unfortunately we can't cover this was just one GitHub issue.  We probably need to file separate GitHub issues for each bdev module, so they can get individually assigned and independently fixed/closed.

I say we discuss this in next bug scrub and figure out a strategy.

**Comment by peluse** [comment] 2019-04-24 18:20
totally agree! I think seeing an example here though might point to something generally wrong with how any rpc is being sent by @yangtianyu0706 since the report seems to indicate they all fail....

**Comment by yangtianyu0706** [comment] 2019-04-25 07:06
> totally agree! I think seeing an example here though might point to something generally wrong with how any rpc is being sent by @yangtianyu0706 since the report seems to indicate they all fail....

For example, spdk_rpc_construct_aio_bdev function:
When create_aio_disk return NULL meams it fail to create bdev. But we can't see a specific error unless we query the log. First there will be some correctness of the check. Next, call spdk_bdev_register to register the bdev, it will return rc ( 0 = success, -EEXIST = already exists, -ENOMEM = no memory, -ENVAIL = Invalid argument). 

I looked at the call place to create the Bdev function and found that it was called only when the RPC or parsing the configuration file. So I have an idea that all the create functions return the real error code, not the Bdev pointer, eg. `int create_xx_bdev(parameters)`.

**Comment by darsto** [comment] 2019-04-25 08:11
Related to #319 "RPC error messages are not descriptive at all"

**Comment by peluse** [comment] 2019-04-26 13:55
I guess I'm just trying to understand whether this is really a general "RPC error codes are useless" or if @yangtianyu0706 is having issues with syntax or setup or something else.  We know the errors codes are not easy to decipher.  @yangtianyu0706 have you been able to get *any* RPC to work and if not can you paste in the exact steps that you are doing? We may be able to at least get you going if it's something unrelated to error messages.

**Comment by peluse** [comment] 2019-04-30 15:25
Bug scrub folks agree that we need a larger effort here to scrub RPC's in terms of naming, JSON config, error codes, etc., etc. This is something we will need to do as a larger project as opposed to using a github issue to fix everything. If @yangtianyu0706 has a specific instance that we can address here please update the bug, otherwise we'll close this once we have the Trello tasks up

**Comment by darsto** [comment] 2019-05-07 14:44
Bug scrub: Closing as it's a duplicate of https://github.com/spdk/spdk/issues/319, let's track it there.

**Closed by darsto** 2019-05-07 14:44 UTC
Labels: bug
