### ISSUE TITLE
[NVMe-oF RDMA]nvme_rdma_connect: *ERROR*: RDMA connect error -99 using fio plugin spdk_bdev when qd>1

### ISSUE THREAD

**Issue by wanqunintel** [spdk/spdk#1703] opened 2020-11-25 02:41 UTC
Running fio_plugin with spdk_bdev will fail to connect with RDMA transport when qd>1
## Expected Behavior
Should pass

## Current Behavior
[2020-11-20 15:05:22.771868] accel_engine.c: 692:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2020-11-20 15:05:24.443045] nvme_rdma.c:1097:nvme_rdma_connect: *ERROR*: RDMA connect error -99
[2020-11-20 15:05:24.443107] nvme_rdma.c:1328:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
[2020-11-20 15:05:25.446569] bdev_nvme.c: 348:bdev_nvme_create_qpair: *ERROR*: Unable to connect I/O qpair.
[2020-11-20 15:05:25.446618] fio_plugin.c: 523:spdk_fio_bdev_open: *ERROR*: Unable to get I/O channel for bdev.
fio: io engine spdk_bdev init failed. Perhaps try reducing io depth?
fio: pid=34309, err=-1/
[2020-11-20 15:07:00.236495] nvme_rdma.c:2283:nvme_rdma_cq_process_completions: *ERROR*: CQ error on Queue Pair 0x7fb8a40016b0, Response Index 140431002180006 (12): transport retry counter exceeded
fio: io_u error on file Nvme0n29: Input/output error: write offset=256151552, buflen=4096
fio: io_u error on file Nvme0n30: Input/output error: write offset=398057472, buflen=4096
fio: io_u error on file Nvme0n31: Input/output error: write offset=888008704, buflen=4096
fio: io_u error on file Nvme0n32: Input/output error: write offset=182575104, buflen=4096
fio: pid=34310, err=5/file:io_u.c:1806, func=io_u error, error=Input/output error

## Possible Solution
n/a

## Steps to Reproduce
target:
1../spdk/build/bin/nvmf_tgt -m 0x1F --json nvmf_tgt.json
[nvmf_tgt.json.log](https://github.com/spdk/spdk/files/5594089/nvmf_tgt.json.log)

host:
1. fio fio_plugin_randwrite_qd4.job
[fio_plugin_randwrite_qd4.job.log](https://github.com/spdk/spdk/files/5594090/fio_plugin_randwrite_qd4.job.log)
[spdk_bdev.json.log](https://github.com/spdk/spdk/files/5594092/spdk_bdev.json.log)

## Context (Environment including OS version, SPDK version, etc.)
OS: Fedora29, K5.4.5
SPDK: 657e50a03232b3bc84f5cf2b67dc7b5856453563

**Comment by AlekseyMarchuk** [comment] 2020-11-25 06:23
Hello,

Can you provide more information on your setup such as OS and kernel versions of both target and initiator hosts (you wrote Fedora29 with kernel 5.4.5 - is it target or initiator or both hosts?), how your hosts are connected (back 2 back or via switch?)
Could you also clarify your NIC model? Are you using RoCE/IB? If you are using Mellanox NICs then I would recommend you to install latest MOFED - in some cases such issues can be fixed by updating drivers/FW

**Comment by wanqunintel** [comment] 2020-11-25 08:07
Hi， Alex
I was running Fedora29 with kernel 5.4.5 both on target and host. They are connected with switch. I am using MLX NIC(Mellanox Technologies MT27700 Family [ConnectX-4]) for this example, but i don't think this is related with the NIC, it also happens with other vendors NIC. should not be hardware related.

**Comment by AlekseyMarchuk** [comment] 2020-11-25 08:34
The issue might be related to kernel ib driver. For example you can refer to this issue https://github.com/spdk/spdk/issues/1696 - the issue only happens on Fedora31. I'll check your scenario on my setup but as I remember it works fine.

**Comment by wanqunintel** [comment] 2020-11-26 01:14
Hi, Alex
I don't think this is related to the kernel ib driver as i was using exactly the same kernel and OS, which passed for the SPDK test in earlier version.

**Comment by wanqunintel** [comment] 2020-11-26 01:15
And this is randomly happens with QD>1, if you do a loop with QD=1,4,8,16,32,128 for different pattern, then it'll be easier to reproduce.

**Comment by AlekseyMarchuk** [comment] 2020-11-26 12:47
@wanqunintel I tried to reproduce this issue about 20 times with different qdepth values and all iterations passed. But I don't have a host with Fedora31 so I used Ubuntu 18.04 with mofed MLNX_OFED_LINUX-4.7-1.0.0.1. I plan to run VM with Fedora31 to check it in the same environment. 
Error -99 is caused by timeout on waiting for RDMA_CM_EVENT_ESTABLISHED event. The timeout is 1 second. While I'm trying to run a VM, could you try to increase the timeout at least 2 times and check if issues still occurs? The timeout is in lib/nvme/nvme_rdma.c
```
/* CM event processing timeout */
#define NVME_RDMA_QPAIR_CM_EVENT_TIMEOUT_US	1000000
```

**Comment by wanqunintel** [comment] 2020-12-02 08:24
Hi, Alex I checked my code, the value is exactly the same as what you have provided and rerun the test with loop, it still failed.

**Comment by AlekseyMarchuk** [comment] 2020-12-02 08:26
Let me clarify, I suggested increasing this timeout x2, so the value should be 
```
/* CM event processing timeout */
#define NVME_RDMA_QPAIR_CM_EVENT_TIMEOUT_US	2000000
```
Could you clarify if you increased this value

**Comment by AlekseyMarchuk** [comment] 2020-12-09 06:04
I met such a failure with intensive traffic generated by initiator (#1707). 
@wanqunintel Could you apply this patch and try to reproduce this issue?
```
diff --git a/module/bdev/nvme/bdev_nvme.c b/module/bdev/nvme/bdev_nvme.c
index 7352e24f4..446cda6c7 100644
--- a/module/bdev/nvme/bdev_nvme.c
+++ b/module/bdev/nvme/bdev_nvme.c
@@ -1958,7 +1958,8 @@ bdev_nvme_create(struct spdk_nvme_transport_id *trid,
        }

        spdk_nvme_ctrlr_get_default_ctrlr_opts(&ctx->opts, sizeof(ctx->opts));
-       ctx->opts.transport_retry_count = g_opts.retry_count;
+       ctx->opts.transport_retry_count = 7;
+       ctx->opts.transport_ack_timeout = 31;
        ctx->opts.keep_alive_timeout_ms = g_opts.keep_alive_timeout_ms;

        if (hostnqn) {
```

**Comment by wanqunintel** [comment] 2020-12-17 07:51
Hi， Alex
If you have the link to this patch, let me know and i will download it to test, before that, your patch should pass the CI. thank you.

**Comment by tomzawadzki** [comment] 2021-02-23 12:34
@wanqunintel I don't think the expectation is to merge the suggested changes. Is it possible for you to apply them manually just for testing ?

**Comment by AlekseyMarchuk** [comment] 2021-03-09 13:18
I hit the same problem when I was reproducing issue #1681
```
[2021-03-09 13:03:40.798057] nvme_fabric.c: 466:nvme_fabric_qpair_connect: *ERROR*: Connect command failed, rc -125, trtype:RDMA adrfam:IPv4 traddr:1.1.75.1 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode1
[2021-03-09 13:03:40.798125] nvme_rdma.c:1207:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Failed to send an NVMe-oF Fabric CONNECT command
[2021-03-09 13:03:40.807991] bdev_nvme.c: 346:bdev_nvme_create_qpair: *ERROR*: Unable to connect I/O qpair.
[2021-03-09 13:03:41.899003] nvme_rdma.c:1070:nvme_rdma_connect: *ERROR*: RDMA connect error -99
[2021-03-09 13:03:41.899098] nvme_rdma.c:1178:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
[2021-03-09 13:03:42.900028] bdev_nvme.c: 346:bdev_nvme_create_qpair: *ERROR*: Unable to connect I/O qpair.
[2021-03-09 13:03:43.929165] nvme_rdma.c:1070:nvme_rdma_connect: *ERROR*: RDMA connect error -99
[2021-03-09 13:03:43.929215] nvme_rdma.c:1178:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
[2021-03-09 13:03:44.930183] bdev_nvme.c: 346:bdev_nvme_create_qpair: *ERROR*: Unable to connect I/O qpair.
[2021-03-09 13:03:44.958724] fio_plugin.c: 522:spdk_fio_bdev_open: *ERROR*: Unable to get I/O channel for bdev.
```

The problem is in relatively small hardcoded timeout. In this case a huge number of qpairs is being connected simultaneously and the timeout might be not enough to get a response from the target since it is also busy with processing of IO requests. Changing the timeout helps to get rid of these errors:
```
diff --git a/lib/nvme/nvme_rdma.c b/lib/nvme/nvme_rdma.c
index d6a5cfb9d..1aec72490 100644
--- a/lib/nvme/nvme_rdma.c
+++ b/lib/nvme/nvme_rdma.c
@@ -67,7 +67,7 @@
 #define NVME_RDMA_NUM_CM_EVENTS                        256

 /* CM event processing timeout */
-#define NVME_RDMA_QPAIR_CM_EVENT_TIMEOUT_US    1000000
+#define NVME_RDMA_QPAIR_CM_EVENT_TIMEOUT_US    9000000

 /* The default size for a shared rdma completion queue. */
 #define DEFAULT_NVME_RDMA_CQ_SIZE              4096

``` 
@wanqunintel Could you increase the timeout on your side and check if it helps? We could make this timeout configurable in that case

**Comment by tomzawadzki** [comment] 2021-05-18 14:15
@wanqunintel have you had a chance to try increasing the timeout ?

**Comment by tomzawadzki** [comment] 2021-09-07 13:42
@wanqunintel please reopen the issue providing more details, if the issue is still relevant for you.

**Closed by tomzawadzki** 2021-09-07 13:42 UTC
Labels: Waiting on Submitter, Sighting

**Comment by wswseyes** [comment] 2023-12-13 07:11
@AlekseyMarchuk  I hit the same problem when I was using fio_plugin with spdk_bdev test raid5f which is composed of 8 NVMe(through rdma).

OS：Linux node176 5.15.0-25-generic #25-Ubuntu 
spdk：tag-v23.09
fio：v3.36

raid.json：
[raid.json](https://github.com/spdk/spdk/files/13657298/raid.json)

when I test raid5f with 8K-randread-8jobs-32qd，it's occur：
`[2023-12-13 15:07:54.008240] nvme_rdma.c:1150:nvme_rdma_connect_established: *ERROR*: RDMA connect error -99
[2023-12-13 15:07:54.008280] nvme_rdma.c:3119:nvme_rdma_poll_group_process_completions: *ERROR*: Failed to connect rqpair=0x20002ba01180
[2023-12-13 15:07:54.024494] nvme_rdma.c:1150:nvme_rdma_connect_established: *ERROR*: RDMA connect error -99
[2023-12-13 15:07:54.024532] nvme_rdma.c:3119:nvme_rdma_poll_group_process_completions: *ERROR*: Failed to connect rqpair=0x2000331ef140
[2023-12-13 15:07:54.024794] nvme_rdma.c:1150:nvme_rdma_connect_established: *ERROR*: RDMA connect error -99
[2023-12-13 15:07:54.024803] nvme_rdma.c:3119:nvme_rdma_poll_group_process_completions: *ERROR*: Failed to connect rqpair=0x200033000080
[2023-12-13 15:07:54.026066] nvme_rdma.c:1150:nvme_rdma_connect_established: *ERROR*: RDMA connect error -99
[2023-12-13 15:07:54.026080] nvme_rdma.c:3119:nvme_rdma_poll_group_process_completions: *ERROR*: Failed to connect rqpair=0x200032a000c0
[2023-12-13 15:07:54.026355] nvme_rdma.c:1150:nvme_rdma_connect_established: *ERROR*: RDMA connect error -99
[2023-12-13 15:07:54.026365] nvme_rdma.c:3119:nvme_rdma_poll_group_process_completions: *ERROR*: Failed to connect rqpair=0x200033600100
[2023-12-13 15:08:04.009774] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009810] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009819] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009824] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009829] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009838] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009844] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009848] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009853] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009860] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009864] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009870] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009874] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009879] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009885] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009891] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009897] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009904] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009911] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009917] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009923] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009929] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009936] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009942] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009949] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009954] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009961] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009967] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009973] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009979] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009986] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.009992] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
fio: io_u error on file raid5: Input/output error: read offset=352054263808, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1614315864064, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=942310727680, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=303533391872, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=2061115555840, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=592516390912, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1604464123904, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1451978588160, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=649091137536, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1745218445312, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=3296573702144, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=643681034240, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1748975124480, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=3346020237312, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=2280816041984, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=2153650888704, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=2818318262272, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=2843580874752, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1125645893632, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=2459116404736, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=264651816960, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1661282459648, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1710909702144, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=3278348402688, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1981399605248, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=797886324736, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1989796601856, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=384671023104, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=2105870942208, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=681509273600, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=258158264320, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=2555201978368, buflen=8192
fio: pid=452137, err=5/file:io_u.c:1896, func=io_u error, error=Input/output error
fio: io_u error on file raid5: Input/output error: read offset=2949084569600, buflen=8192
fio: pid=452131, err=5/file:io_u.c:1896, func=io_u error, error=Input/output error
fio: io_u error on file raid5: Input/output error: read offset=1306815250432, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=506553606144, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1559905116160, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=208018522112, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=2540178726912, buflen=8192
[2023-12-13 15:08:04.026087] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.026122] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.026131] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.026138] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.026145] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.026153] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.026161] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.026169] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.027010] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.027024] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.027033] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.027039] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.027047] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.027787] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.027799] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.027807] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.027814] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.027820] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.027827] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.027834] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.027841] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.027847] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.027854] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.027861] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.028605] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.028617] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.028623] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.028629] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.028636] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.028644] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.028649] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2023-12-13 15:08:04.028655] nvme_qpair.c: 580:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
fio: io_u error on file raid5: Input/output error: read offset=646844153856, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1509237342208, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=604170575872, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=2491528151040, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1790081646592, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=3245821009920, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1562554441728, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=2052845600768, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=2671473909760, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1951999352832, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=2088245936128, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=661776326656, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1531671527424, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=199204765696, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=923832475648, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1159909924864, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1962034495488, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1931441758208, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=2933631361024, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=2872786214912, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=3146576199680, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1173122793472, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1485587963904, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=53192179712, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=999668211712, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=346915479552, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=425740115968, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1841268760576, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=2910951407616, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1577222619136, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=2184738725888, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1268210933760, buflen=8192
fio: pid=452138, err=5/file:io_u.c:1896, func=io_u error, error=Input/output error
fio: io_u error on file raid5: Input/output error: read offset=2035367608320, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=922533093376, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=1516429246464, buflen=8192
fio: pid=452132, err=5/file:io_u.c:1896, func=io_u error, error=Input/output error
fio: io_u error on file raid5: Input/output error: read offset=1434851180544, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=911751888896, buflen=8192
fio: pid=452135, err=5/file:io_u.c:1896, func=io_u error, error=Input/output error
fio: io_u error on file raid5: Input/output error: read offset=70159384576, buflen=8192
fio: io_u error on file raid5: Input/output error: read offset=2493977976832, buflen=8192
fio: pid=452133, err=5/file:io_u.c:1896, func=io_u error, error=Input/output error
fio: io_u error on file raid5: Input/output error: read offset=93742465024, buflen=8192
fio: pid=452134, err=5/file:io_u.c:1896, func=io_u error, error=Input/output error
fio: io_u error on file raid5: Input/output error: read offset=1135588458496, buflen=8192
fio: pid=452136, err=5/file:io_u.c:1896, func=io_u error, error=Input/output error
[2023-12-13 15:08:05.026272] nvme_qpair.c: 797:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 0
[2023-12-13 15:08:05.032505] nvme_qpair.c: 797:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 0
`

I also try increase NVME_RDMA_QPAIR_CM_EVENT_TIMEOUT_US  to 10000000，but the problem still exist.
When I test raid5f with 8K-randread-4jobs-32qd，the problem occur sometimes.

What can I do for this？

**Comment by AlekseyMarchuk** [comment] 2023-12-13 10:16
Hi, there might be several reasons
1. Let's try to exclude network - run ib_read_bw on server: `ib_read_bw -d mlx5_0 -R -q 8` and on client:  `ib_read_bw -d mlx5_0 1.1.1.1 -R -D 10 -q 8 -s 8192`
2. What is your remote target? Make sure that target polls RDMA event channel frequently enough, otherwise it may not reply on connection request in time

**Comment by wswseyes** [comment] 2023-12-15 03:59
@AlekseyMarchuk I will try later，thanks
