### ISSUE TITLE
Broken Intel Optane SSD (Intel SSD DC P4800X 375GB) after SPDK tests.

### ISSUE THREAD

**Issue by songweijia** [spdk/spdk#814] opened 2019-06-07 15:16 UTC
## Expected Behavior and Current Behavior
We have a bounch of Intel SSD DC P4800X 375GB Card installed in our cluster. The server model is Dell PowerEdge R720 (Intel E5-2690 v0 x2, 96GB memory). The SSD broke when we run multiple fio test using the SPDK driver and prevented the system from booting with a freezing screen saying "Initializing firmware interfaces...". We are not sure if this related to SPDK code or other reasons, but Intel customer service told me that " Due to the SPDK kit being “open source” Intel is requesting you file a bug report." So I post it here.

And we have two cases caused such an issue. Please note that is non-deterministic.
Case 1: one of our students was running the "fio" benchmark using SPDK's fio_plugin (see spdk/examples/nvme/fio_plugin). He started a test evaluating the write throughput of SPDK on P4800X.

But he forgot that and ran another fio write test doing the same. After both of the tests failed. The aforementioned issue occurred. The environment:

SPDK: commit 14e1d0c747565f3175db7ddcf733c29282958dd7 on SPDK github master branch.
Operating System: Ubuntu Linux 18.04/ 
uname -a 
Linux compute26 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Case 2: we have two PCI cards installed in a server: one is DC P4800X and the other is DC P3600. I was trying to use the SPDK's nvme_manage to reformat both P4800X and P3600.

It works with P4800X, but failed with P3600. After several tries with P3600, operating system crashed. On rebooting, the aforementioned issue occurred.

I reinstalled this one so I cannot provide the SPDK release number. Operating System should also be Ubuntu 16.04.

Please let me know if you need more details.

**Comment by benlwalker** [comment] 2019-06-07 19:23
Case 1: Can you post the command line you used to start the fio plugin, plus any config files used? By default, two SPDK processes won't be able to access the same device at the same time (we do support multiprocess, but you have to explicitly turn it on with -i). The second time you started fio, it should have just failed. I tested that locally just now and it does indeed just fail to start on the second one.

Case 2: SPDK's nvme_manage tool is just sending commands to the NVMe drive from user space. The only way it can crash your operating system is if it ends up doing a stray DMA. You can protect yourself against that by turning on your IOMMU, but since we have strong checks in place everywhere I doubt that's happening. Are you able to take these two SSDs and plug them into a different system to see if that system boots up?

Is there any way to know exactly what is happening during boot when it is hanging on "Initializing firmware interfaces"? Is that even related to the SSD? Are there logs of any sort?

**Comment by songweijia** [comment] 2019-07-26 21:29
Hi @benlwalker, Sorry for replying very late since we were working on another path and our provider substituted the problematic cards. However, I want this issue to be solved so that we don't need to bounce it back to our provider again and again.

For case 1: One of our students did it long before. So far, I can only report whatever from his description. I attached the script he used to run the benchmark. He started a second experiment before the first one has finished.
[run_benchmark.py.zip](https://github.com/spdk/spdk/files/3437419/run_benchmark.py.zip)

For case 2: Yes, I tried installing the problematic card to another server with an identical configuration. It stopped that server from starting with exactly the same symptom. 

"Is there any way to know exactly what is happening during boot when it is hanging on "Initializing firmware interfaces"? Is that even related to the SSD? Are there logs of any sort?"
My understanding is that the BIOS is waiting for some acknowledge from the PCI card during the initialization which would never happen. As long as you have the problematic card, you should be able to find something. To look deeper into the problem, we may need some help from the BIOS. I believe Intel should have an environment for developing this PCIe device where the initialization process of the PCIe card could be investigated. If it helps, I could get our provider in the loop since they should have at three cards with the same symptom, which I returned. Having a card in hand could help solve this issue...

Btw, my original plan is to keep this post relevant to SPDK itself. But our provider's Intel contact suggests that this is the way my issue could be solved. I hope you guys don't feel offended if I posted an issue that is not SPDK's fault.

Thank you very much for your help!

**Comment by songweijia** [comment] 2019-07-31 17:27
To summarize my previous post: I believe the issue lies in the firmware of the Intel DC P4800X card. Our provider(Colfax Direct) talked to me to make this clear.

For how to reproduce the issue, I could only describe what happened when I had it. It's hard for us to narrow it down to a "do this, and it will break" pattern because we don't have many cards to experiment. However, I would like to be involved in solving this issue with SSD engineers.

**Comment by jimharris** [comment] 2019-10-25 22:24
Closing this as a 3rd party issue.  Please reopen if there is some future indication that it is SPDK related.  We can still have further discussion on this issue here, even when the issue is closed.

**Closed by jimharris** 2019-10-25 22:24 UTC
Labels: 3rd party issue
